BowlerKernel: com.neuronrobotics.sdk.addons.gamepad.PersistantControllerMap Class Reference
com.neuronrobotics.sdk.addons.gamepad.PersistantControllerMap Class Reference
Static Public Member Functions
static List< String > getDefaultMaps ()
static boolean areAllAxisMapped (String controllerName)
static void clearMapping (String controllerName)
static String getMappedAxisName (String controllerName, String incomingName)
static boolean isMapedAxis (String controllerName, String mappedValue)
static String getHardwareAxisFromMappedValue (String controllerName, String mappedValue)
static void map (String name, String controllerVal, String persistantVal)
static Set< String > getMappedAxis (String name)
Detailed Description
Definition at line 10 of file PersistantControllerMap.java.
Member Function Documentation
areAllAxisMapped()
static boolean com.neuronrobotics.sdk.addons.gamepad.PersistantControllerMap.areAllAxisMapped (String controllerName) static
Definition at line 17 of file PersistantControllerMap.java.
References com.neuronrobotics.sdk.addons.gamepad.PersistantControllerMap.getDefaultMaps(), and com.neuronrobotics.sdk.addons.gamepad.PersistantControllerMap.isMapedAxis().
Referenced by com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.setController().
clearMapping()
static void com.neuronrobotics.sdk.addons.gamepad.PersistantControllerMap.clearMapping (String controllerName) static
Definition at line 25 of file PersistantControllerMap.java.
References com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.getParamMap().
getDefaultMaps()
static List<String> com.neuronrobotics.sdk.addons.gamepad.PersistantControllerMap.getDefaultMaps () static
Definition at line 12 of file PersistantControllerMap.java.
Referenced by com.neuronrobotics.sdk.addons.gamepad.PersistantControllerMap.areAllAxisMapped(), and com.neuronrobotics.sdk.addons.gamepad.JogTrainerWidget.onEvent().
getHardwareAxisFromMappedValue()
static String com.neuronrobotics.sdk.addons.gamepad.PersistantControllerMap.getHardwareAxisFromMappedValue (String controllerName, String mappedValue) static
Definition at line 41 of file PersistantControllerMap.java.
References com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.getParamMap().
Referenced by com.neuronrobotics.sdk.addons.gamepad.PersistantControllerMap.isMapedAxis().
getMappedAxis()
static Set<String> com.neuronrobotics.sdk.addons.gamepad.PersistantControllerMap.getMappedAxis (String name) static
Definition at line 57 of file PersistantControllerMap.java.
References com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.getParamMap().
Referenced by com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.getMaps(), and com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.toString().
getMappedAxisName()
static String com.neuronrobotics.sdk.addons.gamepad.PersistantControllerMap.getMappedAxisName (String controllerName, String incomingName) static
Definition at line 29 of file PersistantControllerMap.java.
References com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.getParamMap().
Referenced by com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.connectDeviceImp(), com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.getMaps(), and com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.toString().
isMapedAxis()
static boolean com.neuronrobotics.sdk.addons.gamepad.PersistantControllerMap.isMapedAxis (String controllerName, String mappedValue) static
Definition at line 36 of file PersistantControllerMap.java.
References com.neuronrobotics.sdk.addons.gamepad.PersistantControllerMap.getHardwareAxisFromMappedValue().
Referenced by com.neuronrobotics.sdk.addons.gamepad.PersistantControllerMap.areAllAxisMapped(), and com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.toString().
map()
static void com.neuronrobotics.sdk.addons.gamepad.PersistantControllerMap.map (String name, String controllerVal, String persistantVal) static
Definition at line 52 of file PersistantControllerMap.java.
References com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.save(), and com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.setObject().
Referenced by com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.map().
The documentation for this class was generated from the following file:
src/main/java/com/neuronrobotics/sdk/addons/gamepad/PersistantControllerMap.java