BowlerKernel: com.neuronrobotics.replicator.driver.interpreter.CodeHandler Class Reference
com.neuronrobotics.replicator.driver.interpreter.CodeHandler Class Reference abstract
Public Member Functions
abstract void execute (GCodeLineData prev, GCodeLineData line) throws Exception
void setSubHandlers (List< CodeHandler > subHandlers)
void callSubMethods (GCodeLineData prev, GCodeLineData line) throws Exception
Detailed Description
Encapsulates a handler for a particular G or M code.
Author
Jonathan D.K. Gibbons
Version
1
Definition at line 12 of file CodeHandler.java.
Member Function Documentation
callSubMethods()
void com.neuronrobotics.replicator.driver.interpreter.CodeHandler.callSubMethods (GCodeLineData prev, GCodeLineData line) throws Exception
Call sub methods.
Parameters
prev the prev
line the line
Exceptions
Exception the exception
Definition at line 44 of file CodeHandler.java.
execute()
abstract void com.neuronrobotics.replicator.driver.interpreter.CodeHandler.execute (GCodeLineData prev, GCodeLineData line) throws Exception abstract
Execute the action associated with this handler. this is permitted to modify the values stored in line; prev should be considered immutable.
Parameters
prev The register values for the previous line of G code. Contains such things as the last set position, for interpolation schemes.
line The current set of register values for this line of G code.
Exceptions
Exception the exception
Reimplemented in com.neuronrobotics.replicator.driver.interpreter.EmptyCodeHandler.
Referenced by com.neuronrobotics.replicator.driver.interpreter.GCodeInterpreter.executeLine().
setSubHandlers()
void com.neuronrobotics.replicator.driver.interpreter.CodeHandler.setSubHandlers (List< CodeHandler > subHandlers)
Sets the sub handlers.
Parameters
subHandlers the new sub handlers
Definition at line 33 of file CodeHandler.java.
Referenced by com.neuronrobotics.replicator.driver.interpreter.GCodeInterpreter.setGHandler(), and com.neuronrobotics.replicator.driver.interpreter.GCodeInterpreter.setMHandler().
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/replicator/driver/interpreter/CodeHandler.java