BowlerKernel: com.neuronrobotics.sdk.common.device.server.bcs.core.BcsCoreNamespaceImp Class Reference
com.neuronrobotics.sdk.common.device.server.bcs.core.BcsCoreNamespaceImp Class Reference
Public Member Functions
BcsCoreNamespaceImp (final BowlerAbstractServer s, MACAddress mac)
Public Member Functions inherited from com.neuronrobotics.sdk.common.device.server.BowlerAbstractDeviceServerNamespace
BowlerAbstractDeviceServerNamespace (MACAddress addr, String namespaceString)
boolean checkRpc (BowlerDatagram data)
String getNamespace ()
ArrayList< RpcEncapsulation > getRpcList ()
void addRpc (RpcEncapsulation newRpc)
MACAddress getAddress ()
BowlerDatagram process (BowlerDatagram data)
int getNamespaceIndex ()
void setNamespaceIndex (int ns)
Private Attributes
BowlerAbstractServer server
Additional Inherited Members
Protected Attributes inherited from com.neuronrobotics.sdk.common.device.server.BowlerAbstractDeviceServerNamespace
ArrayList< RpcEncapsulation > rpc =new ArrayList<RpcEncapsulation>()
final String ns
Detailed Description
The Class BcsCoreNamespaceImp.
Definition at line 15 of file BcsCoreNamespaceImp.java.
Constructor & Destructor Documentation
BcsCoreNamespaceImp()
com.neuronrobotics.sdk.common.device.server.bcs.core.BcsCoreNamespaceImp.BcsCoreNamespaceImp (final BowlerAbstractServer s, MACAddress mac)
Instantiates a new bcs core namespace imp.
Parameters
s the s
mac the mac
Definition at line 27 of file BcsCoreNamespaceImp.java.
References com.neuronrobotics.sdk.common.BowlerDataType.ASCII, com.neuronrobotics.sdk.common.BowlerMethod.GET, com.neuronrobotics.sdk.common.device.server.BowlerAbstractDeviceServerNamespace.getNamespace(), com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.getNamespaces(), com.neuronrobotics.sdk.common.BowlerDataType.I08, com.neuronrobotics.sdk.common.device.server.BowlerAbstractDeviceServerNamespace.mac, com.neuronrobotics.sdk.common.BowlerMethod.POST, com.neuronrobotics.sdk.common.device.server.BowlerAbstractDeviceServerNamespace.process(), com.neuronrobotics.sdk.common.device.server.BowlerAbstractDeviceServerNamespace.rpc, and com.neuronrobotics.sdk.common.device.server.bcs.core.BcsCoreNamespaceImp.server.
Member Data Documentation
server
BowlerAbstractServer com.neuronrobotics.sdk.common.device.server.bcs.core.BcsCoreNamespaceImp.server private
The server.
Definition at line 19 of file BcsCoreNamespaceImp.java.
Referenced by com.neuronrobotics.sdk.common.device.server.bcs.core.BcsCoreNamespaceImp.BcsCoreNamespaceImp().
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/common/device/server/bcs/core/BcsCoreNamespaceImp.java