BowlerKernel: eu.mihosoft.vrl.v3d.ext.openjfx.importers.Optimizer Class Reference
eu.mihosoft.vrl.v3d.ext.openjfx.importers.Optimizer Class Reference
Classes
class KeyFrameComparator
class KeyInfo
class MapOfLists
Public Member Functions
Optimizer (Timeline timeline, Node root)
Optimizer (Timeline timeline, Node root, boolean convertToDiscrete)
void optimize ()
Private Member Functions
void optimize (Node node)
void optimizeMeshes ()
void optimizeFaces ()
void optimizePoints ()
void optimizeTexCoords ()
void cleanUpRepeatingFramesAndValues ()
void parseTimeline ()
void removeEmptyGroups ()
Private Attributes
Timeline timeline
Node root
Set< Transform > bound = new HashSet<>()
List< Parent > emptyParents = new ArrayList<>()
List< MeshView > meshViews = new ArrayList<>()
boolean convertToDiscrete = true
int trRemoved
Detailed Description
Optimizer to take 3D model and timeline loaded by one of the importers and do as much optimization on the scene graph that was create as we can while still being able to play the given animation.
Definition at line 68 of file Optimizer.java.
Constructor & Destructor Documentation
Optimizer() [1/2]
eu.mihosoft.vrl.v3d.ext.openjfx.importers.Optimizer.Optimizer (Timeline timeline, Node root)
Instantiates a new optimizer.
Parameters
timeline the timeline
root the root
Definition at line 94 of file Optimizer.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.Optimizer.root, and eu.mihosoft.vrl.v3d.ext.openjfx.importers.Optimizer.timeline.
Optimizer() [2/2]
eu.mihosoft.vrl.v3d.ext.openjfx.importers.Optimizer.Optimizer (Timeline timeline, Node root, boolean convertToDiscrete)
Instantiates a new optimizer.
Parameters
timeline the timeline
root the root
convertToDiscrete the convert to discrete
Definition at line 105 of file Optimizer.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.Optimizer.convertToDiscrete, eu.mihosoft.vrl.v3d.ext.openjfx.importers.Optimizer.root, and eu.mihosoft.vrl.v3d.ext.openjfx.importers.Optimizer.timeline.
Member Function Documentation
cleanUpRepeatingFramesAndValues()
void eu.mihosoft.vrl.v3d.ext.openjfx.importers.Optimizer.cleanUpRepeatingFramesAndValues () private
Clean up repeating frames and values.
Definition at line 390 of file Optimizer.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.Optimizer.timeline.
optimize() [1/2]
void eu.mihosoft.vrl.v3d.ext.openjfx.importers.Optimizer.optimize ()
Optimize.
Definition at line 117 of file Optimizer.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.Optimizer.emptyParents, eu.mihosoft.vrl.v3d.ext.openjfx.importers.Optimizer.optimizeMeshes(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.Optimizer.parseTimeline(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.Optimizer.removeEmptyGroups(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.Optimizer.root, and eu.mihosoft.vrl.v3d.ext.openjfx.importers.Optimizer.trRemoved.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.Optimizer.optimize().
optimize() [2/2]
void eu.mihosoft.vrl.v3d.ext.openjfx.importers.Optimizer.optimize (Node node) private
Optimize.
Parameters
node the node
Definition at line 140 of file Optimizer.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.Optimizer.bound, eu.mihosoft.vrl.v3d.ext.openjfx.importers.Optimizer.emptyParents, eu.mihosoft.vrl.v3d.ext.openjfx.importers.Optimizer.meshViews, eu.mihosoft.vrl.v3d.ext.openjfx.importers.Optimizer.optimize(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.Optimizer.timeline, and eu.mihosoft.vrl.v3d.ext.openjfx.importers.Optimizer.trRemoved.
optimizeFaces()
void eu.mihosoft.vrl.v3d.ext.openjfx.importers.Optimizer.optimizeFaces () private
Optimize faces.
Definition at line 197 of file Optimizer.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.Optimizer.meshViews.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.Optimizer.optimizeMeshes().
optimizeMeshes()
void eu.mihosoft.vrl.v3d.ext.openjfx.importers.Optimizer.optimizeMeshes () private
Optimize meshes.
Definition at line 188 of file Optimizer.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.Optimizer.optimizeFaces(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.Optimizer.optimizePoints(), and eu.mihosoft.vrl.v3d.ext.openjfx.importers.Optimizer.optimizeTexCoords().
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.Optimizer.optimize().
optimizePoints()
void eu.mihosoft.vrl.v3d.ext.openjfx.importers.Optimizer.optimizePoints () private
Optimize points.
Definition at line 267 of file Optimizer.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.Optimizer.meshViews.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.Optimizer.optimizeMeshes().
optimizeTexCoords()
void eu.mihosoft.vrl.v3d.ext.openjfx.importers.Optimizer.optimizeTexCoords () private
Optimize tex coords.
Definition at line 329 of file Optimizer.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.Optimizer.meshViews.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.Optimizer.optimizeMeshes().
parseTimeline()
void eu.mihosoft.vrl.v3d.ext.openjfx.importers.Optimizer.parseTimeline () private
Parses the timeline.
Definition at line 503 of file Optimizer.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.Optimizer.bound, eu.mihosoft.vrl.v3d.ext.openjfx.importers.Optimizer.convertToDiscrete, and eu.mihosoft.vrl.v3d.ext.openjfx.importers.Optimizer.timeline.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.Optimizer.optimize().
removeEmptyGroups()
void eu.mihosoft.vrl.v3d.ext.openjfx.importers.Optimizer.removeEmptyGroups () private
Removes the empty groups.
Definition at line 632 of file Optimizer.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.Optimizer.emptyParents.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.Optimizer.optimize().
Member Data Documentation
bound
Set<Transform> eu.mihosoft.vrl.v3d.ext.openjfx.importers.Optimizer.bound = new HashSet<>() private
The bound.
Definition at line 77 of file Optimizer.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.Optimizer.optimize(), and eu.mihosoft.vrl.v3d.ext.openjfx.importers.Optimizer.parseTimeline().
convertToDiscrete
boolean eu.mihosoft.vrl.v3d.ext.openjfx.importers.Optimizer.convertToDiscrete = true private
The convert to discrete.
Definition at line 86 of file Optimizer.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.Optimizer.Optimizer(), and eu.mihosoft.vrl.v3d.ext.openjfx.importers.Optimizer.parseTimeline().
emptyParents
List<Parent> eu.mihosoft.vrl.v3d.ext.openjfx.importers.Optimizer.emptyParents = new ArrayList<>() private
The empty parents.
Definition at line 80 of file Optimizer.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.Optimizer.optimize(), and eu.mihosoft.vrl.v3d.ext.openjfx.importers.Optimizer.removeEmptyGroups().
meshViews
List<MeshView> eu.mihosoft.vrl.v3d.ext.openjfx.importers.Optimizer.meshViews = new ArrayList<>() private
The mesh views.
Definition at line 83 of file Optimizer.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.Optimizer.optimize(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.Optimizer.optimizeFaces(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.Optimizer.optimizePoints(), and eu.mihosoft.vrl.v3d.ext.openjfx.importers.Optimizer.optimizeTexCoords().
root
Node eu.mihosoft.vrl.v3d.ext.openjfx.importers.Optimizer.root private
The root.
Definition at line 74 of file Optimizer.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.Optimizer.optimize(), and eu.mihosoft.vrl.v3d.ext.openjfx.importers.Optimizer.Optimizer().
timeline
Timeline eu.mihosoft.vrl.v3d.ext.openjfx.importers.Optimizer.timeline private
The timeline.
Definition at line 71 of file Optimizer.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.Optimizer.cleanUpRepeatingFramesAndValues(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.Optimizer.optimize(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.Optimizer.Optimizer(), and eu.mihosoft.vrl.v3d.ext.openjfx.importers.Optimizer.parseTimeline().
trRemoved
int eu.mihosoft.vrl.v3d.ext.openjfx.importers.Optimizer.trRemoved private
The tr empty.
Definition at line 112 of file Optimizer.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.Optimizer.optimize().
The documentation for this class was generated from the following file:
JCSG/src/main/java/eu/mihosoft/vrl/v3d/ext/openjfx/importers/Optimizer.java