BowlerKernel: com.neuronrobotics.sdk.common.ThreadedTimeout Class Reference
com.neuronrobotics.sdk.common.ThreadedTimeout Class Reference
Classes
class timerThreadClass
Public Member Functions
ThreadedTimeout ()
boolean isTimedOut ()
void initialize (long sleepTime, IthreadedTimoutListener listener)
long getAmountOfTimeForTimerToRun ()
void stop ()
long getStartTime ()
void setStartTime (long startTime)
Private Member Functions
void setTimeoutListener (IthreadedTimoutListener listener)
Private Attributes
long time
IthreadedTimoutListener listener
long startTime =0
Static Private Attributes
static timerThreadClass timerThread
Detailed Description
The Class ThreadedTimeout.
Definition at line 25 of file ThreadedTimeout.java.
Constructor & Destructor Documentation
ThreadedTimeout()
com.neuronrobotics.sdk.common.ThreadedTimeout.ThreadedTimeout ()
Instantiates a new threaded timeout.
Definition at line 48 of file ThreadedTimeout.java.
Member Function Documentation
getAmountOfTimeForTimerToRun()
long com.neuronrobotics.sdk.common.ThreadedTimeout.getAmountOfTimeForTimerToRun ()
Gets the amount of time for timer to run.
Returns
the amount of time for timer to run
Definition at line 79 of file ThreadedTimeout.java.
References com.neuronrobotics.sdk.common.ThreadedTimeout.time.
Referenced by com.neuronrobotics.sdk.common.ThreadedTimeout.isTimedOut(), and com.neuronrobotics.sdk.common.BowlerDatagram.onTimeout().
getStartTime()
long com.neuronrobotics.sdk.common.ThreadedTimeout.getStartTime ()
Gets the start time.
Returns
the start time
Definition at line 185 of file ThreadedTimeout.java.
References com.neuronrobotics.sdk.common.ThreadedTimeout.startTime.
Referenced by com.neuronrobotics.sdk.common.BowlerDatagram.getTimestamp(), com.neuronrobotics.sdk.common.ThreadedTimeout.isTimedOut(), and com.neuronrobotics.sdk.common.BowlerDatagram.onTimeout().
initialize()
void com.neuronrobotics.sdk.common.ThreadedTimeout.initialize (long sleepTime, IthreadedTimoutListener listener)
Initialize.
Parameters
sleepTime the sleep time
listener the listener
Definition at line 67 of file ThreadedTimeout.java.
References com.neuronrobotics.sdk.common.ThreadedTimeout.listener, com.neuronrobotics.sdk.common.ThreadedTimeout.setStartTime(), com.neuronrobotics.sdk.common.ThreadedTimeout.setTimeoutListener(), and com.neuronrobotics.sdk.common.ThreadedTimeout.timerThread.
Referenced by com.neuronrobotics.sdk.common.BowlerDatagram.onTimeout(), com.neuronrobotics.sdk.common.BowlerDatagram.setToFree(), and com.neuronrobotics.sdk.common.BowlerDatagram.validate().
isTimedOut()
boolean com.neuronrobotics.sdk.common.ThreadedTimeout.isTimedOut ()
Checks if is timed out.
Returns
true, if is timed out
Definition at line 57 of file ThreadedTimeout.java.
References com.neuronrobotics.sdk.common.ThreadedTimeout.getAmountOfTimeForTimerToRun(), and com.neuronrobotics.sdk.common.ThreadedTimeout.getStartTime().
Referenced by com.neuronrobotics.sdk.common.BowlerDatagram.checkValidPacket(), and com.neuronrobotics.sdk.common.BowlerAbstractConnection.disconnect().
setStartTime()
void com.neuronrobotics.sdk.common.ThreadedTimeout.setStartTime (long startTime)
Sets the start time.
Parameters
startTime the new start time
Definition at line 194 of file ThreadedTimeout.java.
References com.neuronrobotics.sdk.common.ThreadedTimeout.startTime.
Referenced by com.neuronrobotics.sdk.common.BowlerAbstractConnection.disconnect(), and com.neuronrobotics.sdk.common.ThreadedTimeout.initialize().
setTimeoutListener()
void com.neuronrobotics.sdk.common.ThreadedTimeout.setTimeoutListener (IthreadedTimoutListener listener) private
Sets the timeout listener.
Parameters
listener the new timeout listener
Definition at line 88 of file ThreadedTimeout.java.
References com.neuronrobotics.sdk.common.ThreadedTimeout.listener.
Referenced by com.neuronrobotics.sdk.common.ThreadedTimeout.initialize().
stop()
void com.neuronrobotics.sdk.common.ThreadedTimeout.stop ()
Stop.
Definition at line 175 of file ThreadedTimeout.java.
References com.neuronrobotics.sdk.common.ThreadedTimeout.timerThread.
Referenced by com.neuronrobotics.sdk.common.BowlerDatagram.setNotFree().
Member Data Documentation
listener
IthreadedTimoutListener com.neuronrobotics.sdk.common.ThreadedTimeout.listener private
The timed out.
Definition at line 39 of file ThreadedTimeout.java.
Referenced by com.neuronrobotics.sdk.common.ThreadedTimeout.initialize(), and com.neuronrobotics.sdk.common.ThreadedTimeout.setTimeoutListener().
startTime
long com.neuronrobotics.sdk.common.ThreadedTimeout.startTime =0 private
The start time.
Definition at line 42 of file ThreadedTimeout.java.
Referenced by com.neuronrobotics.sdk.common.ThreadedTimeout.getStartTime(), and com.neuronrobotics.sdk.common.ThreadedTimeout.setStartTime().
time
long com.neuronrobotics.sdk.common.ThreadedTimeout.time private
The time.
Definition at line 35 of file ThreadedTimeout.java.
Referenced by com.neuronrobotics.sdk.common.ThreadedTimeout.getAmountOfTimeForTimerToRun().
timerThread
timerThreadClass com.neuronrobotics.sdk.common.ThreadedTimeout.timerThread static private
The timer thread.
Definition at line 28 of file ThreadedTimeout.java.
Referenced by com.neuronrobotics.sdk.common.ThreadedTimeout.initialize(), and com.neuronrobotics.sdk.common.ThreadedTimeout.stop().
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/common/ThreadedTimeout.java