BowlerKernel: com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice Class Reference
com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice Class Reference
Public Member Functions
GcodeDevice (NRSerialPort serial)
AbstractLink getHeater (LinkConfiguration axis)
AbstractLink getLink (LinkConfiguration axis)
void disconnectDeviceImp ()
boolean connectDeviceImp ()
ArrayList< String > getNamespacesImp ()
String runLine (String line)
void runFile (File gcode)
int getTimeoutMs ()
void setTimeoutMs (int timeoutMs)
GCodeDeviceConfiguration getConfiguration ()
void flush (double seconds)
void loadCurrent ()
Public Member Functions inherited from com.neuronrobotics.sdk.common.NonBowlerDevice
boolean connect ()
boolean isAvailable () throws InvalidConnectionException
void disconnect ()
void onAsyncResponse (BowlerDatagram data)
ArrayList< String > getNamespaces ()
Public Member Functions inherited from com.neuronrobotics.sdk.common.BowlerAbstractDevice
void addConnectionEventListener (final IDeviceConnectionEventListener l)
void removeConnectionEventListener (IDeviceConnectionEventListener l)
void setConnection (BowlerAbstractConnection connection)
BowlerAbstractConnection getConnection ()
void setAddress (MACAddress address)
MACAddress getAddress ()
BowlerDatagram send (BowlerAbstractCommand command) throws NoConnectionAvailableException, InvalidResponseException
BowlerDatagram send (BowlerAbstractCommand command, int retry) throws NoConnectionAvailableException, InvalidResponseException
Object[] send (String namespace, BowlerMethod method, String rpcString, Object[] arguments, int retry) throws DeviceConnectionException
Object[] send (String namespace, BowlerMethod method, String rpcString, Object[] arguments) throws DeviceConnectionException
boolean ping ()
boolean ping (boolean switchParser)
ArrayList< ByteList > getRevisions ()
boolean hasNamespace (String string)
void startHeartBeat ()
void startHeartBeat (long msHeartBeatTime)
void stopHeartBeat ()
void setThreadedUpstreamPackets (boolean up)
ArrayList< RpcEncapsulation > getRpcList (String namespace)
void loadRpcList ()
void onAllResponse (BowlerDatagram data)
boolean isKeepAlive ()
void setKeepAlive (boolean keepAlive)
long getLastPacketTime ()
void setLastPacketTime (long lastPacketTime)
String getScriptingName ()
void setScriptingName (String scriptingName)
ArrayList< IDeviceConnectionEventListener > getDisconnectListeners ()
Private Member Functions
String getLine ()
Private Attributes
NRSerialPort serial
DataInputStream ins =null
DataOutputStream outs =null
int timeoutMs = 1000
GCodeDeviceConfiguration config = new GCodeDeviceConfiguration()
HashMap< LinkConfiguration, IGCodeChannel > links = new HashMap<LinkConfiguration,IGCodeChannel>()
AbstractLink heater =null
AbstractLink bed =null
Static Private Attributes
static final String tool = LinkType.GCODE_STEPPER_TOOL.getName()
static final String rot = LinkType.GCODE_STEPPER_ROTORY.getName()
static final String pris = LinkType.GCODE_STEPPER_PRISMATIC.getName()
Additional Inherited Members
Protected Member Functions inherited from com.neuronrobotics.sdk.common.BowlerAbstractDevice
void fireDisconnectEvent ()
void fireConnectEvent ()
Detailed Description
Definition at line 25 of file GcodeDevice.java.
Constructor & Destructor Documentation
GcodeDevice()
com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.GcodeDevice (NRSerialPort serial)
Definition at line 44 of file GcodeDevice.java.
References com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.serial.
Member Function Documentation
connectDeviceImp()
boolean com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.connectDeviceImp ()
Connect device imp.
Returns
true, if successful
Reimplemented from com.neuronrobotics.sdk.common.NonBowlerDevice.
Definition at line 160 of file GcodeDevice.java.
References com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.disconnectDeviceImp(), com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.ins, com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.outs, com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.runLine(), and com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.serial.
disconnectDeviceImp()
void com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.disconnectDeviceImp ()
This method tells the connection object to disconnect its pipes and close out the connection. Once this is called, it is safe to remove your device.
Reimplemented from com.neuronrobotics.sdk.common.NonBowlerDevice.
Definition at line 127 of file GcodeDevice.java.
References com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.getLine(), com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.ins, com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.outs, com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.runLine(), and com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.serial.
Referenced by com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.connectDeviceImp().
flush()
void com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.flush (double seconds)
This interface says the device can cache values and flush them in one push
Parameters
seconds the duration of the flush, from current position and time to cached positions in this many seconds
Implements com.neuronrobotics.sdk.common.IFlushable.
Definition at line 242 of file GcodeDevice.java.
References com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.bed, com.neuronrobotics.sdk.addons.kinematics.AbstractLink.flush(), com.neuronrobotics.sdk.addons.kinematics.gcodebridge.IGCodeChannel.getAxis(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getCurrentPosition(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getTargetValue(), com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.heater, com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.links, com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.loadCurrent(), and com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.runLine().
Referenced by com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GCodeHeater.flushAllDevice(), com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodePrismatic.flushAllDevice(), and com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeRotory.flushAllDevice().
getConfiguration()
GCodeDeviceConfiguration com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.getConfiguration ()
Return the configuration of the gcode device.
Returns
Implements com.neuronrobotics.sdk.addons.kinematics.gcodebridge.IGcodeExecuter.
Definition at line 237 of file GcodeDevice.java.
References com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.config.
getHeater()
AbstractLink com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.getHeater (LinkConfiguration axis)
Definition at line 48 of file GcodeDevice.java.
References com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.bed, com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getHardwareIndex(), and com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.heater.
Referenced by com.neuronrobotics.sdk.addons.kinematics.LinkFactory.getLinkLocal().
getLine()
String com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.getLine () private
Definition at line 177 of file GcodeDevice.java.
References com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.ins.
Referenced by com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.disconnectDeviceImp(), and com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.runLine().
getLink()
AbstractLink com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.getLink (LinkConfiguration axis)
Definition at line 66 of file GcodeDevice.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getHardwareIndex(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getTypeString(), com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.links, com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.pris, com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.rot, com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setDeviceTheoreticalMax(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setDeviceTheoreticalMin(), and com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.tool.
Referenced by com.neuronrobotics.sdk.addons.kinematics.LinkFactory.getLinkLocal().
getNamespacesImp()
ArrayList<String> com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.getNamespacesImp ()
Gets the namespaces imp.
Returns
the namespaces imp
Reimplemented from com.neuronrobotics.sdk.common.NonBowlerDevice.
Definition at line 172 of file GcodeDevice.java.
getTimeoutMs()
int com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.getTimeoutMs ()
Definition at line 228 of file GcodeDevice.java.
References com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.timeoutMs.
Referenced by com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.runLine().
loadCurrent()
void com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.loadCurrent ()
System.out.println("Found axis = "+s);
Definition at line 262 of file GcodeDevice.java.
References com.neuronrobotics.sdk.addons.kinematics.gcodebridge.IGCodeChannel.getAxis(), com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.links, com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.runLine(), and com.neuronrobotics.sdk.addons.kinematics.gcodebridge.IGCodeChannel.setValue().
Referenced by com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.flush(), com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodePrismatic.loadCurrent(), and com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeRotory.loadCurrent().
runFile()
void com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.runFile (File gcode)
Run all the lines in a file
Parameters
gcode
Implements com.neuronrobotics.sdk.addons.kinematics.gcodebridge.IGcodeExecuter.
Definition at line 223 of file GcodeDevice.java.
runLine()
String com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.runLine (String line)
Execute a single line of gcode
Parameters
line
Returns
Implements com.neuronrobotics.sdk.addons.kinematics.gcodebridge.IGcodeExecuter.
Definition at line 194 of file GcodeDevice.java.
References com.neuronrobotics.sdk.common.Log.error(), com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.getLine(), com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.getTimeoutMs(), com.neuronrobotics.sdk.common.Log.info(), com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.outs, and com.neuronrobotics.sdk.util.ThreadUtil.wait().
Referenced by com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.connectDeviceImp(), com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.disconnectDeviceImp(), com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.flush(), com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GCodeHeater.flushDevice(), com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodePrismatic.flushDevice(), com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeRotory.flushDevice(), and com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.loadCurrent().
setTimeoutMs()
void com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.setTimeoutMs (int timeoutMs)
Definition at line 232 of file GcodeDevice.java.
References com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.timeoutMs.
Member Data Documentation
bed
AbstractLink com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.bed =null private
Definition at line 41 of file GcodeDevice.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.flush(), and com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.getHeater().
config
GCodeDeviceConfiguration com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.config = new GCodeDeviceConfiguration() private
Definition at line 38 of file GcodeDevice.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.getConfiguration().
heater
AbstractLink com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.heater =null private
Definition at line 40 of file GcodeDevice.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.flush(), and com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.getHeater().
ins
DataInputStream com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.ins =null private
Definition at line 35 of file GcodeDevice.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.connectDeviceImp(), com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.disconnectDeviceImp(), and com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.getLine().
links
HashMap<LinkConfiguration,IGCodeChannel> com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.links = new HashMap<LinkConfiguration,IGCodeChannel>() private
Definition at line 39 of file GcodeDevice.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.flush(), com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.getLink(), and com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.loadCurrent().
outs
DataOutputStream com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.outs =null private
Definition at line 36 of file GcodeDevice.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.connectDeviceImp(), com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.disconnectDeviceImp(), and com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.runLine().
pris
final String com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.pris = LinkType.GCODE_STEPPER_PRISMATIC.getName() static private
Definition at line 31 of file GcodeDevice.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.getLink().
rot
final String com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.rot = LinkType.GCODE_STEPPER_ROTORY.getName() static private
Definition at line 29 of file GcodeDevice.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.getLink().
serial
NRSerialPort com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.serial private
Definition at line 33 of file GcodeDevice.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.connectDeviceImp(), com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.disconnectDeviceImp(), and com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.GcodeDevice().
timeoutMs
int com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.timeoutMs = 1000 private
Definition at line 37 of file GcodeDevice.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.getTimeoutMs(), and com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.setTimeoutMs().
tool
final String com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.tool = LinkType.GCODE_STEPPER_TOOL.getName() static private
Definition at line 27 of file GcodeDevice.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.getLink().
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/addons/kinematics/gcodebridge/GcodeDevice.java