BowlerKernel: com.neuronrobotics.sdk.namespace.bcs.pid.PidDeviceServer Class Reference
com.neuronrobotics.sdk.namespace.bcs.pid.PidDeviceServer Class Reference
Public Member Functions
PidDeviceServer (MACAddress mac, IPidControlNamespace device)
void onPIDEvent (PIDEvent e)
void onPIDLimitEvent (PIDLimitEvent e)
void onPIDReset (int group, float currentValue)
Public Member Functions inherited from com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer
BowlerAbstractServer (MACAddress mac)
void addBowlerDeviceServerNamespace (BowlerAbstractDeviceServerNamespace ns)
void removeBowlerDeviceServerNamespace (BowlerAbstractDeviceServerNamespace ns)
ArrayList< BowlerAbstractConnection > getServers ()
void startNetworkServer (final int port) throws IOException
void startNetworkServer () throws IOException
void addServer (BowlerAbstractConnection srv)
BowlerDatagram onSyncReceive (BowlerDatagram data)
void pushAsyncPacket (int namespaceIndex, String namespace, String rpcString, Object[] arguments, BowlerDataType[] asyncArguments)
synchronized void pushAsyncPacket (BowlerDatagram data)
ArrayList< BowlerAbstractDeviceServerNamespace > getNamespaces ()
void setNamespaces (ArrayList< BowlerAbstractDeviceServerNamespace > namespaces)
MACAddress getMacAddress ()
void setMacAddress (MACAddress macAddress)
Static Public Member Functions
static void main (String[] args)
Private Attributes
PidDeviceServerNamespace pidServer
Detailed Description
The Class PidDeviceServer.
Definition at line 18 of file PidDeviceServer.java.
Constructor & Destructor Documentation
PidDeviceServer()
com.neuronrobotics.sdk.namespace.bcs.pid.PidDeviceServer.PidDeviceServer (MACAddress mac, IPidControlNamespace device)
Instantiates a new pid device server.
Parameters
mac the mac
device the device
Definition at line 29 of file PidDeviceServer.java.
References com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.addBowlerDeviceServerNamespace(), com.neuronrobotics.sdk.namespace.bcs.pid.IPidControlNamespace.addPIDEventListener(), com.neuronrobotics.sdk.common.Log.info(), com.neuronrobotics.sdk.namespace.bcs.pid.PidDeviceServer.pidServer, and com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.startNetworkServer().
Referenced by com.neuronrobotics.sdk.namespace.bcs.pid.PidDeviceServer.main().
Member Function Documentation
main()
static void com.neuronrobotics.sdk.namespace.bcs.pid.PidDeviceServer.main (String[] args) static
The main method.
Parameters
args the arguments
Definition at line 102 of file PidDeviceServer.java.
References com.neuronrobotics.sdk.common.Log.enableInfoPrint(), and com.neuronrobotics.sdk.namespace.bcs.pid.PidDeviceServer.PidDeviceServer().
onPIDEvent()
void com.neuronrobotics.sdk.namespace.bcs.pid.PidDeviceServer.onPIDEvent (PIDEvent e)
On pid event.
Parameters
e the e
Implements com.neuronrobotics.sdk.pid.IPIDEventListener.
Definition at line 49 of file PidDeviceServer.java.
References com.neuronrobotics.sdk.common.device.server.BowlerAbstractDeviceServerNamespace.getNamespace(), com.neuronrobotics.sdk.common.Log.info(), com.neuronrobotics.sdk.namespace.bcs.pid.PidDeviceServer.pidServer, and com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.pushAsyncPacket().
onPIDLimitEvent()
void com.neuronrobotics.sdk.namespace.bcs.pid.PidDeviceServer.onPIDLimitEvent (PIDLimitEvent e)
On pid limit event.
Parameters
e the e
Implements com.neuronrobotics.sdk.pid.IPIDEventListener.
Definition at line 72 of file PidDeviceServer.java.
References com.neuronrobotics.sdk.common.device.server.BowlerAbstractDeviceServerNamespace.getNamespace(), com.neuronrobotics.sdk.namespace.bcs.pid.PidDeviceServer.pidServer, and com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.pushAsyncPacket().
onPIDReset()
void com.neuronrobotics.sdk.namespace.bcs.pid.PidDeviceServer.onPIDReset (int group, float currentValue)
On pid reset.
Parameters
group the group
currentValue the current value
Implements com.neuronrobotics.sdk.pid.IPIDEventListener.
Definition at line 94 of file PidDeviceServer.java.
Member Data Documentation
pidServer
PidDeviceServerNamespace com.neuronrobotics.sdk.namespace.bcs.pid.PidDeviceServer.pidServer private
The pid server.
Definition at line 21 of file PidDeviceServer.java.
Referenced by com.neuronrobotics.sdk.namespace.bcs.pid.PidDeviceServer.onPIDEvent(), com.neuronrobotics.sdk.namespace.bcs.pid.PidDeviceServer.onPIDLimitEvent(), and com.neuronrobotics.sdk.namespace.bcs.pid.PidDeviceServer.PidDeviceServer().
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/namespace/bcs/pid/PidDeviceServer.java