BowlerKernel: com.neuronrobotics.sdk.addons.gamepad.JogTrainerWidget Class Reference
com.neuronrobotics.sdk.addons.gamepad.JogTrainerWidget Class Reference
Public Member Functions
JogTrainerWidget (BowlerJInputDevice gameController)
void start (Stage primaryStage) throws Exception
void reset ()
void onEvent (String name, float value)
Static Public Member Functions
static void run (BowlerJInputDevice c)
Private Attributes
ResourceBundle resources
Label controllername
URL location
GridPane grid
int mappingIndex = 0
HashMap< Integer, TextField > fields = new HashMap<>()
String axisWaiting =null
long timeOfLastAxisSet =0
ArrayList< String > listOfMappedAxis =new ArrayList<>()
Button save
Stage primaryStage
BowlerJInputDevice gameController
Detailed Description
Definition at line 40 of file JogTrainerWidget.java.
Constructor & Destructor Documentation
JogTrainerWidget()
com.neuronrobotics.sdk.addons.gamepad.JogTrainerWidget.JogTrainerWidget (BowlerJInputDevice gameController)
Definition at line 126 of file JogTrainerWidget.java.
References com.neuronrobotics.sdk.addons.gamepad.JogTrainerWidget.gameController.
Referenced by com.neuronrobotics.sdk.addons.gamepad.JogTrainerWidget.run().
Member Function Documentation
onEvent()
void com.neuronrobotics.sdk.addons.gamepad.JogTrainerWidget.onEvent (String name, float value)
On event.
Parameters
name the name of the value that changed
value the value
Implements com.neuronrobotics.sdk.addons.gamepad.IGameControlEvent.
Definition at line 168 of file JogTrainerWidget.java.
References com.neuronrobotics.sdk.addons.gamepad.JogTrainerWidget.axisWaiting, com.neuronrobotics.sdk.addons.gamepad.JogTrainerWidget.fields, com.neuronrobotics.sdk.addons.gamepad.JogTrainerWidget.gameController, com.neuronrobotics.sdk.addons.gamepad.PersistantControllerMap.getDefaultMaps(), com.neuronrobotics.sdk.addons.gamepad.JogTrainerWidget.listOfMappedAxis, com.neuronrobotics.sdk.addons.gamepad.JogTrainerWidget.mappingIndex, and com.neuronrobotics.sdk.addons.gamepad.JogTrainerWidget.timeOfLastAxisSet.
reset()
void com.neuronrobotics.sdk.addons.gamepad.JogTrainerWidget.reset ()
Definition at line 156 of file JogTrainerWidget.java.
References com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.addListeners(), com.neuronrobotics.sdk.addons.gamepad.JogTrainerWidget.controllername, com.neuronrobotics.sdk.addons.gamepad.JogTrainerWidget.fields, com.neuronrobotics.sdk.addons.gamepad.JogTrainerWidget.gameController, com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.getName(), com.neuronrobotics.sdk.addons.gamepad.JogTrainerWidget.listOfMappedAxis, com.neuronrobotics.sdk.addons.gamepad.JogTrainerWidget.mappingIndex, and com.neuronrobotics.sdk.addons.gamepad.JogTrainerWidget.save.
run()
static void com.neuronrobotics.sdk.addons.gamepad.JogTrainerWidget.run (BowlerJInputDevice c) static
Definition at line 221 of file JogTrainerWidget.java.
References com.neuronrobotics.sdk.addons.gamepad.JogTrainerWidget.JogTrainerWidget(), and com.neuronrobotics.sdk.addons.gamepad.JogTrainerWidget.start().
Referenced by com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.setController().
start()
void com.neuronrobotics.sdk.addons.gamepad.JogTrainerWidget.start (Stage primaryStage) throws Exception
Definition at line 132 of file JogTrainerWidget.java.
References com.neuronrobotics.bowlerstudio.assets.AssetFactory.loadFile(), and com.neuronrobotics.sdk.addons.gamepad.JogTrainerWidget.primaryStage.
Referenced by com.neuronrobotics.sdk.addons.gamepad.JogTrainerWidget.run().
Member Data Documentation
axisWaiting
String com.neuronrobotics.sdk.addons.gamepad.JogTrainerWidget.axisWaiting =null private
Definition at line 55 of file JogTrainerWidget.java.
Referenced by com.neuronrobotics.sdk.addons.gamepad.JogTrainerWidget.onEvent().
controllername
Label com.neuronrobotics.sdk.addons.gamepad.JogTrainerWidget.controllername private
Definition at line 46 of file JogTrainerWidget.java.
Referenced by com.neuronrobotics.sdk.addons.gamepad.JogTrainerWidget.reset().
fields
HashMap<Integer, TextField> com.neuronrobotics.sdk.addons.gamepad.JogTrainerWidget.fields = new HashMap<>() private
Definition at line 54 of file JogTrainerWidget.java.
Referenced by com.neuronrobotics.sdk.addons.gamepad.JogTrainerWidget.onEvent(), and com.neuronrobotics.sdk.addons.gamepad.JogTrainerWidget.reset().
gameController
BowlerJInputDevice com.neuronrobotics.sdk.addons.gamepad.JogTrainerWidget.gameController private
Definition at line 61 of file JogTrainerWidget.java.
Referenced by com.neuronrobotics.sdk.addons.gamepad.JogTrainerWidget.JogTrainerWidget(), com.neuronrobotics.sdk.addons.gamepad.JogTrainerWidget.onEvent(), and com.neuronrobotics.sdk.addons.gamepad.JogTrainerWidget.reset().
grid
GridPane com.neuronrobotics.sdk.addons.gamepad.JogTrainerWidget.grid private
Definition at line 52 of file JogTrainerWidget.java.
listOfMappedAxis
ArrayList<String> com.neuronrobotics.sdk.addons.gamepad.JogTrainerWidget.listOfMappedAxis =new ArrayList<>() private
Definition at line 57 of file JogTrainerWidget.java.
Referenced by com.neuronrobotics.sdk.addons.gamepad.JogTrainerWidget.onEvent(), and com.neuronrobotics.sdk.addons.gamepad.JogTrainerWidget.reset().
location
URL com.neuronrobotics.sdk.addons.gamepad.JogTrainerWidget.location private
Definition at line 49 of file JogTrainerWidget.java.
mappingIndex
int com.neuronrobotics.sdk.addons.gamepad.JogTrainerWidget.mappingIndex = 0 private
Definition at line 53 of file JogTrainerWidget.java.
Referenced by com.neuronrobotics.sdk.addons.gamepad.JogTrainerWidget.onEvent(), and com.neuronrobotics.sdk.addons.gamepad.JogTrainerWidget.reset().
primaryStage
Stage com.neuronrobotics.sdk.addons.gamepad.JogTrainerWidget.primaryStage private
Definition at line 59 of file JogTrainerWidget.java.
Referenced by com.neuronrobotics.sdk.addons.gamepad.JogTrainerWidget.start().
resources
ResourceBundle com.neuronrobotics.sdk.addons.gamepad.JogTrainerWidget.resources private
Definition at line 43 of file JogTrainerWidget.java.
save
Button com.neuronrobotics.sdk.addons.gamepad.JogTrainerWidget.save private
Definition at line 58 of file JogTrainerWidget.java.
Referenced by com.neuronrobotics.sdk.addons.gamepad.JogTrainerWidget.reset().
timeOfLastAxisSet
long com.neuronrobotics.sdk.addons.gamepad.JogTrainerWidget.timeOfLastAxisSet =0 private
Definition at line 56 of file JogTrainerWidget.java.
Referenced by com.neuronrobotics.sdk.addons.gamepad.JogTrainerWidget.onEvent().
The documentation for this class was generated from the following file:
src/main/java/com/neuronrobotics/sdk/addons/gamepad/JogTrainerWidget.java