BowlerKernel: com.neuronrobotics.sdk.ui.ConnectionDialog Class Reference
com.neuronrobotics.sdk.ui.ConnectionDialog Class Reference
Public Member Functions
ConnectionDialog ()
void addConnectionPanel (AbstractConnectionPanel panel)
boolean showDialog ()
BowlerAbstractConnection getConnection ()
Static Public Member Functions
static boolean getBowlerDevice (BowlerAbstractDevice dev)
static boolean getBowlerDevice (BowlerAbstractDevice dev, AbstractConnectionPanel panel)
static BowlerAbstractConnection promptConnection ()
static BowlerAbstractConnection getHeadlessConnection (String config)
static BowlerAbstractConnection promptConnection (AbstractConnectionPanel panel)
Private Member Functions
void loadDefaultConnections ()
Private Attributes
SerialConnection connection = null
boolean isCancled = true
JPanel panel
JButton connectBtn
JButton refresh
JButton cancelBtn
JTabbedPane connectionPanels
LookAndFeel laf
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
The Class ConnectionDialog.
Definition at line 32 of file ConnectionDialog.java.
Constructor & Destructor Documentation
ConnectionDialog()
com.neuronrobotics.sdk.ui.ConnectionDialog.ConnectionDialog ()
Instantiates a new connection dialog.
Definition at line 64 of file ConnectionDialog.java.
References com.neuronrobotics.sdk.ui.ConnectionDialog.cancelBtn, com.neuronrobotics.sdk.ui.ConnectionDialog.connectBtn, com.neuronrobotics.sdk.ui.ConnectionDialog.connection, com.neuronrobotics.sdk.ui.ConnectionDialog.connectionPanels, com.neuronrobotics.sdk.serial.SerialConnection.disconnect(), com.neuronrobotics.sdk.ui.ConnectionDialog.getConnection(), com.neuronrobotics.sdk.ui.ConnectionImageIconFactory.getIcon(), com.neuronrobotics.sdk.common.Log.info(), com.neuronrobotics.sdk.ui.ConnectionDialog.isCancled, com.neuronrobotics.sdk.ui.ConnectionDialog.loadDefaultConnections(), com.neuronrobotics.sdk.ui.ConnectionDialog.panel, and com.neuronrobotics.sdk.ui.ConnectionDialog.refresh.
Referenced by com.neuronrobotics.sdk.ui.ConnectionDialog.promptConnection().
Member Function Documentation
addConnectionPanel()
void com.neuronrobotics.sdk.ui.ConnectionDialog.addConnectionPanel (AbstractConnectionPanel panel)
Adds the connection panel.
Parameters
panel the panel
Definition at line 165 of file ConnectionDialog.java.
References com.neuronrobotics.sdk.ui.ConnectionDialog.connectionPanels, and com.neuronrobotics.sdk.ui.ConnectionDialog.panel.
Referenced by com.neuronrobotics.sdk.ui.ConnectionDialog.loadDefaultConnections(), and com.neuronrobotics.sdk.ui.ConnectionDialog.promptConnection().
getBowlerDevice() [1/2]
static boolean com.neuronrobotics.sdk.ui.ConnectionDialog.getBowlerDevice (BowlerAbstractDevice dev) static
Gets the bowler device.
Parameters
dev the dev
Returns
the bowler device
Definition at line 205 of file ConnectionDialog.java.
getBowlerDevice() [2/2]
static boolean com.neuronrobotics.sdk.ui.ConnectionDialog.getBowlerDevice (BowlerAbstractDevice dev, AbstractConnectionPanel panel) static
Gets the bowler device.
Parameters
dev the dev
panel the panel
Returns
Returns if the device has been found
Definition at line 216 of file ConnectionDialog.java.
References com.neuronrobotics.sdk.common.BowlerAbstractDevice.connect(), com.neuronrobotics.sdk.ui.ConnectionDialog.connection, com.neuronrobotics.sdk.common.Log.info(), com.neuronrobotics.sdk.ui.ConnectionDialog.panel, com.neuronrobotics.sdk.common.BowlerAbstractDevice.ping(), com.neuronrobotics.sdk.ui.ConnectionDialog.promptConnection(), and com.neuronrobotics.sdk.common.BowlerAbstractDevice.setConnection().
getConnection()
BowlerAbstractConnection com.neuronrobotics.sdk.ui.ConnectionDialog.getConnection ()
Gets the connection.
Returns
the connection
Definition at line 189 of file ConnectionDialog.java.
References com.neuronrobotics.sdk.ui.ConnectionDialog.connectionPanels.
Referenced by com.neuronrobotics.sdk.ui.ConnectionDialog.ConnectionDialog(), and com.neuronrobotics.sdk.ui.ConnectionDialog.promptConnection().
getHeadlessConnection()
static BowlerAbstractConnection com.neuronrobotics.sdk.ui.ConnectionDialog.getHeadlessConnection (String config) static
Gets the headless connection.
Parameters
config the config
Returns
the headless connection
Definition at line 279 of file ConnectionDialog.java.
References com.neuronrobotics.sdk.common.ConfigManager.loadDefaultConnection().
Referenced by com.neuronrobotics.sdk.ui.ConnectionDialog.promptConnection().
loadDefaultConnections()
void com.neuronrobotics.sdk.ui.ConnectionDialog.loadDefaultConnections () private
Load default connections.
Definition at line 139 of file ConnectionDialog.java.
References com.neuronrobotics.sdk.ui.ConnectionDialog.addConnectionPanel(), and com.neuronrobotics.sdk.common.Log.error().
Referenced by com.neuronrobotics.sdk.ui.ConnectionDialog.ConnectionDialog().
promptConnection() [1/2]
static BowlerAbstractConnection com.neuronrobotics.sdk.ui.ConnectionDialog.promptConnection () static
Displays a serial connection dialog to the user and returns the connection or null.
Returns
the connection if one is selected, null if canceled or no connection is selected.
Definition at line 260 of file ConnectionDialog.java.
References com.neuronrobotics.sdk.ui.ConnectionDialog.ConnectionDialog(), com.neuronrobotics.sdk.ui.ConnectionDialog.getConnection(), com.neuronrobotics.sdk.ui.ConnectionDialog.getHeadlessConnection(), com.neuronrobotics.sdk.ui.ConnectionDialog.isCancled, and com.neuronrobotics.sdk.ui.ConnectionDialog.showDialog().
Referenced by com.neuronrobotics.sdk.common.DeviceManager.addConnection(), and com.neuronrobotics.sdk.ui.ConnectionDialog.getBowlerDevice().
promptConnection() [2/2]
static BowlerAbstractConnection com.neuronrobotics.sdk.ui.ConnectionDialog.promptConnection (AbstractConnectionPanel panel) static
Displays a serial connection dialog to the user and returns the connection or null.
Parameters
panel the panel
Returns
the connection if one is selected, null if canceled or no connection is selected.
Definition at line 289 of file ConnectionDialog.java.
References com.neuronrobotics.sdk.ui.ConnectionDialog.addConnectionPanel(), com.neuronrobotics.sdk.ui.ConnectionDialog.ConnectionDialog(), com.neuronrobotics.sdk.ui.ConnectionDialog.getConnection(), com.neuronrobotics.sdk.ui.ConnectionDialog.getHeadlessConnection(), com.neuronrobotics.sdk.ui.ConnectionDialog.isCancled, com.neuronrobotics.sdk.ui.ConnectionDialog.panel, and com.neuronrobotics.sdk.ui.ConnectionDialog.showDialog().
showDialog()
boolean com.neuronrobotics.sdk.ui.ConnectionDialog.showDialog ()
Displays the dialog and blocks until the user has chosen 'Set', 'Cancel', or 'No Connection' Returns true if the user set a connection, returns false otherwise.
Returns
- Did the user cancel
Definition at line 178 of file ConnectionDialog.java.
References com.neuronrobotics.sdk.ui.ConnectionDialog.isCancled.
Referenced by com.neuronrobotics.sdk.ui.ConnectionDialog.promptConnection().
Member Data Documentation
cancelBtn
JButton com.neuronrobotics.sdk.ui.ConnectionDialog.cancelBtn private
The cancel btn.
Definition at line 53 of file ConnectionDialog.java.
Referenced by com.neuronrobotics.sdk.ui.ConnectionDialog.ConnectionDialog().
connectBtn
JButton com.neuronrobotics.sdk.ui.ConnectionDialog.connectBtn private
The connect btn.
Definition at line 47 of file ConnectionDialog.java.
Referenced by com.neuronrobotics.sdk.ui.ConnectionDialog.ConnectionDialog().
connection
SerialConnection com.neuronrobotics.sdk.ui.ConnectionDialog.connection = null private
The connection.
Definition at line 38 of file ConnectionDialog.java.
Referenced by com.neuronrobotics.sdk.ui.ConnectionDialog.ConnectionDialog(), and com.neuronrobotics.sdk.ui.ConnectionDialog.getBowlerDevice().
connectionPanels
JTabbedPane com.neuronrobotics.sdk.ui.ConnectionDialog.connectionPanels private
The connection panels.
Definition at line 56 of file ConnectionDialog.java.
Referenced by com.neuronrobotics.sdk.ui.ConnectionDialog.addConnectionPanel(), com.neuronrobotics.sdk.ui.ConnectionDialog.ConnectionDialog(), and com.neuronrobotics.sdk.ui.ConnectionDialog.getConnection().
isCancled
boolean com.neuronrobotics.sdk.ui.ConnectionDialog.isCancled = true private
The is cancled.
Definition at line 41 of file ConnectionDialog.java.
Referenced by com.neuronrobotics.sdk.ui.ConnectionDialog.ConnectionDialog(), com.neuronrobotics.sdk.ui.ConnectionDialog.promptConnection(), and com.neuronrobotics.sdk.ui.ConnectionDialog.showDialog().
laf
LookAndFeel com.neuronrobotics.sdk.ui.ConnectionDialog.laf private
The laf.
Definition at line 59 of file ConnectionDialog.java.
panel
JPanel com.neuronrobotics.sdk.ui.ConnectionDialog.panel private
The panel.
Definition at line 44 of file ConnectionDialog.java.
Referenced by com.neuronrobotics.sdk.ui.ConnectionDialog.addConnectionPanel(), com.neuronrobotics.sdk.ui.ConnectionDialog.ConnectionDialog(), com.neuronrobotics.sdk.ui.ConnectionDialog.getBowlerDevice(), and com.neuronrobotics.sdk.ui.ConnectionDialog.promptConnection().
refresh
JButton com.neuronrobotics.sdk.ui.ConnectionDialog.refresh private
The refresh.
Definition at line 50 of file ConnectionDialog.java.
Referenced by com.neuronrobotics.sdk.ui.ConnectionDialog.ConnectionDialog().
serialVersionUID
final long com.neuronrobotics.sdk.ui.ConnectionDialog.serialVersionUID = 1L static private
The Constant serialVersionUID.
Definition at line 35 of file ConnectionDialog.java.
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/ui/ConnectionDialog.java