BowlerKernel: eu.mihosoft.vrl.v3d.STL Class Reference
eu.mihosoft.vrl.v3d.STL Class Reference
Static Public Member Functions
static CSG file (URL path) throws IOException, URISyntaxException
static CSG file (Path path) throws IOException
Detailed Description
Loads a CSG from stl.
Author
Michael Hoffer <info@.nosp@m.mich.nosp@m.aelho.nosp@m.ffer.nosp@m..de>
Definition at line 57 of file STL.java.
Member Function Documentation
file() [1/2]
static CSG eu.mihosoft.vrl.v3d.STL.file (Path path) throws IOException static
Loads a CSG from stl.
Parameters
path file path
Returns
CSG
Exceptions
IOException if loading failed
Definition at line 83 of file STL.java.
References eu.mihosoft.vrl.v3d.Polygon.fromPointsAllowDegenerate(), eu.mihosoft.vrl.v3d.CSG.fromPolygons(), and eu.mihosoft.vrl.v3d.ext.imagej.STLLoader.parse().
file() [2/2]
static CSG eu.mihosoft.vrl.v3d.STL.file (URL path) throws IOException, URISyntaxException static
Loads a CSG from stl.
Parameters
path file path
Returns
CSG
Exceptions
IOException if loading failed
URISyntaxException the URI syntax exception
Definition at line 67 of file STL.java.
Referenced by com.neuronrobotics.bowlerstudio.vitamins.Vitamins.get().
The documentation for this class was generated from the following file:
JCSG/src/main/java/eu/mihosoft/vrl/v3d/STL.java