BowlerKernel: com.neuronrobotics.sdk.addons.kinematics.ik.DeltaIKModel Class Reference
com.neuronrobotics.sdk.addons.kinematics.ik.DeltaIKModel Class Reference
Public Member Functions
double[] inverseKinematics (TransformNR target, double[] jointSpaceVector, DHChain chain)
double[] inverseKinematics6dof (TransformNR target, double[] jointSpaceVector, DHChain chain)
Detailed Description
Definition at line 11 of file DeltaIKModel.java.
Member Function Documentation
inverseKinematics()
double [] com.neuronrobotics.sdk.addons.kinematics.ik.DeltaIKModel.inverseKinematics (TransformNR target, double[] jointSpaceVector, DHChain chain)
Inverse kinematics.
Parameters
target the target
jointSpaceVector the joint space vector
chain the chain
Returns
the double[]
Implements com.neuronrobotics.sdk.addons.kinematics.DhInverseSolver.
Definition at line 18 of file DeltaIKModel.java.
References com.neuronrobotics.sdk.addons.kinematics.ik.DeltaIKModel.inverseKinematics6dof().
inverseKinematics6dof()
double [] com.neuronrobotics.sdk.addons.kinematics.ik.DeltaIKModel.inverseKinematics6dof (TransformNR target, double[] jointSpaceVector, DHChain chain)
System of equasions Theta2 = asin(z/wristVect) l3 = wristVect * cos(theta2) theta1 = acos(l1^2+x^2-l3^2/2*l1*x)
compute the top of the wrist now that the first 3 links are calculated
Calculte the second angle
Calculte the last angle
Definition at line 33 of file DeltaIKModel.java.
References com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.copy(), com.neuronrobotics.sdk.addons.kinematics.DHChain.forwardKinematicsMatrix(), com.neuronrobotics.sdk.addons.kinematics.DHChain.getLinks(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getRotation(), com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.getRotationAzimuth(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getX(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getY(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getZ(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.inverse(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.inverseOffset(), com.neuronrobotics.sdk.addons.kinematics.DHChain.kin, com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.times(), and com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.translateX().
Referenced by com.neuronrobotics.sdk.addons.kinematics.ik.DeltaIKModel.inverseKinematics().
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/addons/kinematics/ik/DeltaIKModel.java