BowlerKernel: com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase Class Reference
com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase Class Reference
Static Public Member Functions
static Object getObject (String paramsKey, String objectKey, Object defaultValue)
static HashMap< String, Object > getParamMap (String paramsKey)
static Object setObject (String paramsKey, String objectKey, Object value)
static Object removeObject (String paramsKey, String objectKey)
static void save ()
static HashMap< String, HashMap< String, Object > > getDatabase ()
static File loadFile () throws Exception
static void loginEvent (String username)
static String getGitSource () throws Exception
static void setGitSource (String myAssets)
static String getDbFile ()
static void setDbFile (String dbFile)
Static Private Member Functions
static void syncOldDBToNew (HashMap< String, HashMap< String, Object >> existing)
static void setRepo (GHRepository forkedRep)
Static Private Attributes
static final String repo = "BowlerStudioConfiguration"
static final String HTTPS_GITHUB_COM_NEURON_ROBOTICS_BOWLER_STUDIO_CONFIGURATION_GIT
static String gitSource = null
static String dbFile = "database.json"
static boolean checked
static HashMap< String, HashMap< String, Object > > database = null
static final Type TT_mapStringString
static Gson gson = new GsonBuilder().disableHtmlEscaping().setPrettyPrinting().create()
static IssueReportingExceptionHandler reporter = new IssueReportingExceptionHandler()
static String loggedInAs = null
Detailed Description
Definition at line 21 of file ConfigurationDatabase.java.
Member Function Documentation
getDatabase()
static HashMap<String, HashMap<String, Object> > com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.getDatabase () static
Definition at line 98 of file ConfigurationDatabase.java.
References com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.database, com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.deleteRepo(), com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.getGitSource(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.inlineFileScriptRun(), com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.loadFile(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.pull(), and com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.syncOldDBToNew().
Referenced by com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.getParamMap(), com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.save(), and com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.setGitSource().
getDbFile()
static String com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.getDbFile () static
Definition at line 226 of file ConfigurationDatabase.java.
References com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.dbFile.
Referenced by com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.loadFile(), and com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.save().
getGitSource()
static String com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.getGitSource () throws Exception static
Definition at line 178 of file ConfigurationDatabase.java.
References com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.checked, com.neuronrobotics.bowlerstudio.scripting.PasswordManager.getGithub(), com.neuronrobotics.bowlerstudio.scripting.PasswordManager.getLoginID(), com.neuronrobotics.bowlerstudio.scripting.PasswordManager.getUsername(), com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.gitSource, com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.hasNetwork(), com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.HTTPS_GITHUB_COM_NEURON_ROBOTICS_BOWLER_STUDIO_CONFIGURATION_GIT, com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.isLoginSuccess(), com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.repo, com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.setGitSource(), and com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.setRepo().
Referenced by com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.connectDeviceImp(), com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.getDatabase(), com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.loadFile(), com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.loginEvent(), and com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.save().
getObject()
static Object com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.getObject (String paramsKey, String objectKey, Object defaultValue) static
Definition at line 41 of file ConfigurationDatabase.java.
References com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.getParamMap(), and com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.setObject().
Referenced by com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.syncOldDBToNew().
getParamMap()
static HashMap<String, Object> com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.getParamMap (String paramsKey) static
Definition at line 49 of file ConfigurationDatabase.java.
References com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.getDatabase().
Referenced by com.neuronrobotics.sdk.addons.gamepad.PersistantControllerMap.clearMapping(), com.neuronrobotics.sdk.addons.gamepad.PersistantControllerMap.getHardwareAxisFromMappedValue(), com.neuronrobotics.sdk.addons.gamepad.PersistantControllerMap.getMappedAxis(), com.neuronrobotics.sdk.addons.gamepad.PersistantControllerMap.getMappedAxisName(), com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.getObject(), com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.removeObject(), and com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.setObject().
loadFile()
static File com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.loadFile () throws Exception static
Definition at line 130 of file ConfigurationDatabase.java.
References com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.fileFromGit(), com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.getDbFile(), and com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.getGitSource().
Referenced by com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.getDatabase().
loginEvent()
static void com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.loginEvent (String username) static
Definition at line 135 of file ConfigurationDatabase.java.
References com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.checked, com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.database, com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.getGitSource(), com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.gitSource, com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.loggedInAs, and com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.syncOldDBToNew().
removeObject()
static Object com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.removeObject (String paramsKey, String objectKey) static
Definition at line 60 of file ConfigurationDatabase.java.
References com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.getParamMap().
save()
static void com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.save () static
Definition at line 64 of file ConfigurationDatabase.java.
References com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.database, com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.deleteRepo(), com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.getDatabase(), com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.getDbFile(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getFullBranch(), com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.getGitSource(), com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.gson, com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.HTTPS_GITHUB_COM_NEURON_ROBOTICS_BOWLER_STUDIO_CONFIGURATION_GIT, com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.isLoginSuccess(), com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.loggedInAs, com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.pushCodeToGit(), and com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.TT_mapStringString.
Referenced by com.neuronrobotics.sdk.addons.gamepad.PersistantControllerMap.map().
setDbFile()
static void com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.setDbFile (String dbFile) static
Definition at line 230 of file ConfigurationDatabase.java.
References com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.dbFile, com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.gitSource, and com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.setGitSource().
setGitSource()
static void com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.setGitSource (String myAssets) static
Definition at line 215 of file ConfigurationDatabase.java.
References com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.checked, com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.database, com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.getDatabase(), and com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.gitSource.
Referenced by com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.getGitSource(), com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.setDbFile(), and com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.setRepo().
setObject()
static Object com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.setObject (String paramsKey, String objectKey, Object value) static
Definition at line 56 of file ConfigurationDatabase.java.
References com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.getParamMap().
Referenced by com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.getObject(), and com.neuronrobotics.sdk.addons.gamepad.PersistantControllerMap.map().
setRepo()
static void com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.setRepo (GHRepository forkedRep) static private
Definition at line 210 of file ConfigurationDatabase.java.
References com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.setGitSource().
Referenced by com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.getGitSource().
syncOldDBToNew()
static void com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.syncOldDBToNew (HashMap< String, HashMap< String, Object >> existing) static private
Definition at line 164 of file ConfigurationDatabase.java.
References com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.getObject().
Referenced by com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.getDatabase(), and com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.loginEvent().
Member Data Documentation
checked
boolean com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.checked static private
Definition at line 29 of file ConfigurationDatabase.java.
Referenced by com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.getGitSource(), com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.loginEvent(), and com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.setGitSource().
database
HashMap<String, HashMap<String, Object> > com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.database = null static private
Definition at line 30 of file ConfigurationDatabase.java.
Referenced by com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.getDatabase(), com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.loginEvent(), com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.save(), and com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.setGitSource().
dbFile
String com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.dbFile = "database.json" static private
Definition at line 28 of file ConfigurationDatabase.java.
Referenced by com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.getDbFile(), and com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.setDbFile().
gitSource
String com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.gitSource = null static private
Definition at line 27 of file ConfigurationDatabase.java.
Referenced by com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.getGitSource(), com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.loginEvent(), com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.setDbFile(), and com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.setGitSource().
gson
Gson com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.gson = new GsonBuilder().disableHtmlEscaping().setPrettyPrinting().create() static private
Definition at line 34 of file ConfigurationDatabase.java.
Referenced by com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.save().
HTTPS_GITHUB_COM_NEURON_ROBOTICS_BOWLER_STUDIO_CONFIGURATION_GIT
final String com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.HTTPS_GITHUB_COM_NEURON_ROBOTICS_BOWLER_STUDIO_CONFIGURATION_GIT static private
Initial value:
= "https://github.com/CommonWealthRobotics/"
            + repo + ".git"
Definition at line 24 of file ConfigurationDatabase.java.
Referenced by com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.getGitSource(), and com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.save().
loggedInAs
String com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.loggedInAs = null static private
Definition at line 36 of file ConfigurationDatabase.java.
Referenced by com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.loginEvent(), and com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.save().
repo
final String com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.repo = "BowlerStudioConfiguration" static private
Definition at line 23 of file ConfigurationDatabase.java.
Referenced by com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.getGitSource().
reporter
IssueReportingExceptionHandler com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.reporter = new IssueReportingExceptionHandler() static private
Definition at line 35 of file ConfigurationDatabase.java.
TT_mapStringString
final Type com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.TT_mapStringString static private
Initial value:
= new TypeToken<HashMap<String, HashMap<String, Object>>>() {
    }.getType()
Definition at line 31 of file ConfigurationDatabase.java.
Referenced by com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.save().
The documentation for this class was generated from the following file:
src/main/java/com/neuronrobotics/bowlerstudio/assets/ConfigurationDatabase.java