BowlerKernel: com.neuronrobotics.sdk.addons.kinematics.LinkFactory Class Reference
com.neuronrobotics.sdk.addons.kinematics.LinkFactory Class Reference
Public Member Functions
LinkFactory ()
LinkFactory (BowlerAbstractDevice bad)
LinkFactory (ILinkFactoryProvider connection, IExtendedPIDControl d)
AbstractLink getLink (String name)
AbstractLink getLink (LinkConfiguration c)
void refreshHardwareLayer (LinkConfiguration c)
void addLink (AbstractLink link)
double[] getLowerLimits ()
double[] getUpperLimits ()
void addLinkListener (ILinkListener l)
void flush (final double seconds)
IPidControlNamespace getPid (LinkConfiguration c)
DyIO getDyio (LinkConfiguration c)
GcodeDevice getGCODE (LinkConfiguration c)
void setCachedTargets (double[] jointSpaceVect)
boolean isConnected ()
ArrayList< LinkConfiguration > getLinkConfigurations ()
void removeLinkListener (AbstractKinematicsNR l)
void deleteLink (int i)
void sync ()
VirtualGenericPIDDevice getVirtual (String myVirtualDevName)
Public Member Functions inherited from com.neuronrobotics.sdk.addons.kinematics.IHardwareSyncPulseProvider
default void addIHardwareSyncPulseReciver (IHardwareSyncPulseReciver r)
default void removeIHardwareSyncPulseReciver (IHardwareSyncPulseReciver r)
default void doSync ()
default ArrayList< IHardwareSyncPulseReciver > getListeners ()
Static Public Member Functions
static void addLinkProvider (String typeTag, INewLinkProvider provider)
static boolean linkProviderExists (String typeTag)
Private Member Functions
AbstractLink getLinkLocal (LinkConfiguration c)
Private Attributes
ArrayList< AbstractLink > links = new ArrayList<AbstractLink>()
ArrayList< LinkConfiguration > linkConfigurations = null
Static Private Attributes
static HashMap< String, INewLinkProvider > userLinkProviders = new HashMap<String, INewLinkProvider>()
Additional Inherited Members
Public Attributes inherited from com.neuronrobotics.sdk.addons.kinematics.IHardwareSyncPulseProvider
HashMap< IHardwareSyncPulseProvider, ArrayList< IHardwareSyncPulseReciver > > syncPulse =new HashMap<>()
Detailed Description
A factory for creating Link objects.
Definition at line 27 of file LinkFactory.java.
Constructor & Destructor Documentation
LinkFactory() [1/3]
com.neuronrobotics.sdk.addons.kinematics.LinkFactory.LinkFactory ()
Instantiates a new link factory.
Definition at line 61 of file LinkFactory.java.
LinkFactory() [2/3]
com.neuronrobotics.sdk.addons.kinematics.LinkFactory.LinkFactory (BowlerAbstractDevice bad)
Instantiates a new link factory.
Parameters
bad the bad
Definition at line 70 of file LinkFactory.java.
References com.neuronrobotics.sdk.common.DeviceManager.addConnection(), and com.neuronrobotics.sdk.common.BowlerAbstractDevice.getScriptingName().
LinkFactory() [3/3]
com.neuronrobotics.sdk.addons.kinematics.LinkFactory.LinkFactory (ILinkFactoryProvider connection, IExtendedPIDControl d)
Instantiates a new link factory.
Parameters
connection the connection
d the d
Definition at line 81 of file LinkFactory.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkFactory.getLink(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getTotlaNumberOfLinks(), com.neuronrobotics.sdk.pid.ILinkFactoryProvider.requestLinkConfiguration(), and com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setPidConfiguration().
Member Function Documentation
addLink()
void com.neuronrobotics.sdk.addons.kinematics.LinkFactory.addLink (AbstractLink link)
THis interface lets the user add a link after instantiation
Parameters
link the link to be added in order
Definition at line 235 of file LinkFactory.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getLinkConfiguration(), com.neuronrobotics.sdk.addons.kinematics.LinkFactory.getLinkConfigurations(), and com.neuronrobotics.sdk.addons.kinematics.LinkFactory.links.
Referenced by com.neuronrobotics.sdk.addons.kinematics.LinkFactory.getLinkLocal(), com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.removeLimb(), and com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.setupReferencedLimbStartup().
addLinkListener()
void com.neuronrobotics.sdk.addons.kinematics.LinkFactory.addLinkListener (ILinkListener l)
Adds the link listener.
Parameters
l the l
Definition at line 272 of file LinkFactory.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkFactory.links.
Referenced by com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.addNewLink(), and com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.removeLink().
addLinkProvider()
static void com.neuronrobotics.sdk.addons.kinematics.LinkFactory.addLinkProvider (String typeTag, INewLinkProvider provider) static
Add a new link provider
Parameters
typeTag a string to link it to the string in the XML that determines type
provider the provider module
Definition at line 43 of file LinkFactory.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkType.addType(), and com.neuronrobotics.sdk.addons.kinematics.LinkFactory.userLinkProviders.
deleteLink()
void com.neuronrobotics.sdk.addons.kinematics.LinkFactory.deleteLink (int i)
Delete link.
Parameters
i the i
Definition at line 407 of file LinkFactory.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkFactory.getLinkConfigurations(), and com.neuronrobotics.sdk.addons.kinematics.LinkFactory.links.
Referenced by com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.removeLink().
flush()
void com.neuronrobotics.sdk.addons.kinematics.LinkFactory.flush (final double seconds)
Flush.
Parameters
seconds the seconds
Definition at line 283 of file LinkFactory.java.
References com.neuronrobotics.sdk.common.IFlushable.flush(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.flush(), com.neuronrobotics.sdk.addons.kinematics.LinkFactory.getLink(), com.neuronrobotics.sdk.addons.kinematics.LinkFactory.getLinkConfigurations(), and com.neuronrobotics.sdk.common.DeviceManager.getSpecificDevice().
Referenced by com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR._setDesiredJointSpaceVector().
getDyio()
DyIO com.neuronrobotics.sdk.addons.kinematics.LinkFactory.getDyio (LinkConfiguration c)
Gets the dyio.
Returns
the dyio from the database.
Definition at line 325 of file LinkFactory.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getDeviceScriptingName(), and com.neuronrobotics.sdk.common.DeviceManager.getSpecificDevice().
Referenced by com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.DHParameterKinematics(), and com.neuronrobotics.sdk.addons.kinematics.LinkFactory.getLinkLocal().
getGCODE()
GcodeDevice com.neuronrobotics.sdk.addons.kinematics.LinkFactory.getGCODE (LinkConfiguration c)
Gets the Gcode device from the database.
Returns
the GCODE device
Definition at line 336 of file LinkFactory.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getDeviceScriptingName(), and com.neuronrobotics.sdk.common.DeviceManager.getSpecificDevice().
Referenced by com.neuronrobotics.sdk.addons.kinematics.LinkFactory.getLinkLocal().
getLink() [1/2]
AbstractLink com.neuronrobotics.sdk.addons.kinematics.LinkFactory.getLink (LinkConfiguration c)
Gets the link.
Parameters
c the c
Returns
the link
Definition at line 121 of file LinkFactory.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkFactory.getLinkLocal(), and com.neuronrobotics.sdk.addons.kinematics.LinkFactory.links.
getLink() [2/2]
AbstractLink com.neuronrobotics.sdk.addons.kinematics.LinkFactory.getLink (String name)
Gets the link.
Parameters
name the name
Returns
the link
Definition at line 103 of file LinkFactory.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getLinkConfiguration(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getName(), and com.neuronrobotics.sdk.addons.kinematics.LinkFactory.links.
Referenced by com.neuronrobotics.sdk.addons.kinematics.AbstractLink.AbstractLink(), com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.addNewLink(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.cacheTargetValue(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.checkVector(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.flush(), com.neuronrobotics.sdk.addons.kinematics.LinkFactory.flush(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.flushAll(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.generateCad(), com.neuronrobotics.sdk.addons.kinematics.LinkFactory.LinkFactory(), com.neuronrobotics.sdk.addons.kinematics.LinkFactory.refreshHardwareLayer(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setPosition(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setTargetValue(), and com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.setupReferencedLimbStartup().
getLinkConfigurations()
ArrayList<LinkConfiguration> com.neuronrobotics.sdk.addons.kinematics.LinkFactory.getLinkConfigurations ()
Gets the link configurations.
Returns
the link configurations
Definition at line 383 of file LinkFactory.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkFactory.linkConfigurations.
Referenced by com.neuronrobotics.sdk.addons.kinematics.LinkFactory.addLink(), com.neuronrobotics.sdk.addons.kinematics.LinkFactory.deleteLink(), com.neuronrobotics.sdk.addons.kinematics.LinkFactory.flush(), com.neuronrobotics.sdk.addons.kinematics.DHChain.forwardKinematicsMatrix(), com.neuronrobotics.sdk.addons.kinematics.LinkFactory.isConnected(), com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.setChain(), and com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.setupReferencedLimbStartup().
getLinkLocal()
AbstractLink com.neuronrobotics.sdk.addons.kinematics.LinkFactory.getLinkLocal (LinkConfiguration c) private
Gets the link local.
Parameters
c the c
Returns
the link local
Definition at line 152 of file LinkFactory.java.
References com.neuronrobotics.sdk.addons.kinematics.IHardwareSyncPulseProvider.addIHardwareSyncPulseReciver(), com.neuronrobotics.sdk.addons.kinematics.LinkFactory.addLink(), com.neuronrobotics.sdk.addons.kinematics.INewLinkProvider.generate(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getDeviceScriptingName(), com.neuronrobotics.sdk.addons.kinematics.LinkFactory.getDyio(), com.neuronrobotics.sdk.addons.kinematics.LinkFactory.getGCODE(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getHardwareIndex(), com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.getHeater(), com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.getLink(), com.neuronrobotics.sdk.addons.kinematics.LinkFactory.getPid(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getTypeString(), com.neuronrobotics.sdk.addons.kinematics.LinkFactory.getVirtual(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.isPrismatic(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setLinkConfiguration(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setUseLimits(), and com.neuronrobotics.sdk.addons.kinematics.LinkFactory.userLinkProviders.
Referenced by com.neuronrobotics.sdk.addons.kinematics.LinkFactory.getLink(), and com.neuronrobotics.sdk.addons.kinematics.LinkFactory.refreshHardwareLayer().
getLowerLimits()
double [] com.neuronrobotics.sdk.addons.kinematics.LinkFactory.getLowerLimits ()
Gets the lower limits.
Returns
the lower limits
Definition at line 246 of file LinkFactory.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkFactory.links.
Referenced by com.neuronrobotics.sdk.addons.kinematics.DHChain.setFactory().
getPid()
IPidControlNamespace com.neuronrobotics.sdk.addons.kinematics.LinkFactory.getPid (LinkConfiguration c)
Gets the pid from the database..
Returns
the pid from the database.
Definition at line 313 of file LinkFactory.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getDeviceScriptingName(), and com.neuronrobotics.sdk.common.DeviceManager.getSpecificDevice().
Referenced by com.neuronrobotics.sdk.addons.kinematics.LinkFactory.getLinkLocal().
getUpperLimits()
double [] com.neuronrobotics.sdk.addons.kinematics.LinkFactory.getUpperLimits ()
Gets the upper limits.
Returns
the upper limits
Definition at line 259 of file LinkFactory.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkFactory.links.
Referenced by com.neuronrobotics.sdk.addons.kinematics.DHChain.setFactory().
getVirtual()
VirtualGenericPIDDevice com.neuronrobotics.sdk.addons.kinematics.LinkFactory.getVirtual (String myVirtualDevName)
Definition at line 417 of file LinkFactory.java.
References com.neuronrobotics.sdk.addons.kinematics.IHardwareSyncPulseProvider.addIHardwareSyncPulseReciver(), and com.neuronrobotics.sdk.common.DeviceManager.getSpecificDevice().
Referenced by com.neuronrobotics.sdk.addons.kinematics.LinkFactory.getLinkLocal().
isConnected()
boolean com.neuronrobotics.sdk.addons.kinematics.LinkFactory.isConnected ()
Checks if is connected.
Returns
true, if is connected
Definition at line 367 of file LinkFactory.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkFactory.getLinkConfigurations(), and com.neuronrobotics.sdk.common.DeviceManager.getSpecificDevice().
linkProviderExists()
static boolean com.neuronrobotics.sdk.addons.kinematics.LinkFactory.linkProviderExists (String typeTag) static
Check to see if link provider is already defined
Parameters
typeTag
Returns
Definition at line 54 of file LinkFactory.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkFactory.userLinkProviders.
refreshHardwareLayer()
void com.neuronrobotics.sdk.addons.kinematics.LinkFactory.refreshHardwareLayer (LinkConfiguration c)
Refresh hardware layer.
Parameters
c the c
Definition at line 134 of file LinkFactory.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractLink.addLinkListener(), com.neuronrobotics.sdk.addons.kinematics.LinkFactory.getLink(), com.neuronrobotics.sdk.addons.kinematics.LinkFactory.getLinkLocal(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getLinks(), com.neuronrobotics.sdk.addons.kinematics.LinkFactory.links, and com.neuronrobotics.sdk.addons.kinematics.AbstractLink.removeAllLinkListener().
removeLinkListener()
void com.neuronrobotics.sdk.addons.kinematics.LinkFactory.removeLinkListener (AbstractKinematicsNR l)
Removes the link listener.
Parameters
l the l
Definition at line 395 of file LinkFactory.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkFactory.links.
Referenced by com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.addNewLink(), and com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.removeLink().
setCachedTargets()
void com.neuronrobotics.sdk.addons.kinematics.LinkFactory.setCachedTargets (double[] jointSpaceVect)
Sets the cached targets.
Parameters
jointSpaceVect the new cached targets
Definition at line 347 of file LinkFactory.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkFactory.links.
Referenced by com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR._setDesiredJointSpaceVector().
sync()
void com.neuronrobotics.sdk.addons.kinematics.LinkFactory.sync ()
Implements com.neuronrobotics.sdk.addons.kinematics.IHardwareSyncPulseReciver.
Definition at line 413 of file LinkFactory.java.
References com.neuronrobotics.sdk.addons.kinematics.IHardwareSyncPulseProvider.doSync().
Member Data Documentation
linkConfigurations
ArrayList<LinkConfiguration> com.neuronrobotics.sdk.addons.kinematics.LinkFactory.linkConfigurations = null private
The link configurations.
Definition at line 34 of file LinkFactory.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.LinkFactory.getLinkConfigurations().
links
ArrayList<AbstractLink> com.neuronrobotics.sdk.addons.kinematics.LinkFactory.links = new ArrayList<AbstractLink>() private
The links.
Definition at line 31 of file LinkFactory.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.LinkFactory.addLink(), com.neuronrobotics.sdk.addons.kinematics.LinkFactory.addLinkListener(), com.neuronrobotics.sdk.addons.kinematics.LinkFactory.deleteLink(), com.neuronrobotics.sdk.addons.kinematics.LinkFactory.getLink(), com.neuronrobotics.sdk.addons.kinematics.LinkFactory.getLowerLimits(), com.neuronrobotics.sdk.addons.kinematics.LinkFactory.getUpperLimits(), com.neuronrobotics.sdk.addons.kinematics.LinkFactory.refreshHardwareLayer(), com.neuronrobotics.sdk.addons.kinematics.LinkFactory.removeLinkListener(), and com.neuronrobotics.sdk.addons.kinematics.LinkFactory.setCachedTargets().
userLinkProviders
HashMap<String, INewLinkProvider> com.neuronrobotics.sdk.addons.kinematics.LinkFactory.userLinkProviders = new HashMap<String, INewLinkProvider>() static private
Definition at line 28 of file LinkFactory.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.LinkFactory.addLinkProvider(), com.neuronrobotics.sdk.addons.kinematics.LinkFactory.getLinkLocal(), and com.neuronrobotics.sdk.addons.kinematics.LinkFactory.linkProviderExists().
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/addons/kinematics/LinkFactory.java