BowlerKernel: com.neuronrobotics.sdk.addons.kinematics.AbstractRotoryLink Class Reference
com.neuronrobotics.sdk.addons.kinematics.AbstractRotoryLink Class Reference abstract
Public Member Functions
AbstractRotoryLink (LinkConfiguration conf)
void incrementAngle (double inc)
void setTargetAngle (double pos)
void setCurrentAsAngle (double angle)
double getCurrentAngle ()
double getTargetAngle ()
double getMaxAngle ()
double getMinAngle ()
boolean isMaxAngle ()
boolean isMinAngle ()
Public Member Functions inherited from com.neuronrobotics.sdk.addons.kinematics.AbstractLink
double getDeviceMaximumValue ()
double getDeviceMinimumValue ()
void setDeviceMaximumValue (double max)
void setDeviceMinimumValue (double min)
double getDeviceMaxEngineeringUnits ()
double getDeviceMinEngineeringUnits ()
AbstractLink (LinkConfiguration conf)
void cacheTargetValue ()
abstract void cacheTargetValueDevice ()
void flush (double time)
void flushAll (double time)
abstract void flushDevice (double time)
abstract void flushAllDevice (double time)
abstract double getCurrentPosition ()
double toEngineeringUnits (double value)
double toLinkUnits (double euValue)
void addLinkListener (ILinkListener l)
void removeLinkListener (ILinkListener l)
void fireLinkListener (double linkUnitsValue)
void fireLinkLimitEvent (PIDLimitEvent e)
void Home ()
void incrementEngineeringUnits (double inc)
void setTargetEngineeringUnits (double pos)
void setCurrentEngineeringUnits (double angle)
double getCurrentEngineeringUnits ()
double getTargetEngineeringUnits ()
double getMaxEngineeringUnits ()
double getMinEngineeringUnits ()
void setMinEngineeringUnits (double minLimit)
void setMaxEngineeringUnits (double maxLimit)
double getMaxVelocityEngineeringUnits ()
void setMaxVelocityEngineeringUnits (double max)
boolean isMaxEngineeringUnits ()
boolean isMinEngineeringUnits ()
double getTargetValue ()
void setUpperLimit (int upperLimit)
void setLowerLimit (int lowerLimit)
void setHome (int home)
void setScale (double d)
double getScale ()
double getUpperLimit ()
double getLowerLimit ()
double getHome ()
void setCurrentAsUpperLimit ()
void setCurrentAsLowerLimit ()
void setUseLimits (boolean useLimits)
boolean isUseLimits ()
void setLinkConfiguration (LinkConfiguration conf)
LinkConfiguration getLinkConfiguration ()
ArrayList< ILinkListener > getLinks ()
void setLinks (ArrayList< ILinkListener > links)
void removeAllLinkListener ()
void setGlobalPositionListener (Object Object)
Object getGlobalPositionListener ()
LinkFactory getSlaveFactory ()
void setSlaveFactory (LinkFactory slaveFactory)
IMU getImu ()
void addChangeListener (ILinkConfigurationChangeListener l)
void removeChangeListener (ILinkConfigurationChangeListener l)
void clearChangeListener ()
Additional Inherited Members
Protected Member Functions inherited from com.neuronrobotics.sdk.addons.kinematics.AbstractLink
void setPosition (double val)
void setTargetValue (double val)
Detailed Description
The Class AbstractRotoryLink.
Definition at line 7 of file AbstractRotoryLink.java.
Constructor & Destructor Documentation
AbstractRotoryLink()
com.neuronrobotics.sdk.addons.kinematics.AbstractRotoryLink.AbstractRotoryLink (LinkConfiguration conf)
Instantiates a new abstract rotory link.
Parameters
conf the conf
Definition at line 14 of file AbstractRotoryLink.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractLink.conf.
Member Function Documentation
getCurrentAngle()
double com.neuronrobotics.sdk.addons.kinematics.AbstractRotoryLink.getCurrentAngle ()
Gets the current angle.
Returns
the current angle
Definition at line 51 of file AbstractRotoryLink.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getCurrentEngineeringUnits().
getMaxAngle()
double com.neuronrobotics.sdk.addons.kinematics.AbstractRotoryLink.getMaxAngle ()
Gets the max angle.
Returns
the max angle
Definition at line 69 of file AbstractRotoryLink.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getMaxEngineeringUnits().
getMinAngle()
double com.neuronrobotics.sdk.addons.kinematics.AbstractRotoryLink.getMinAngle ()
Gets the min angle.
Returns
the min angle
Definition at line 78 of file AbstractRotoryLink.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getMinEngineeringUnits().
getTargetAngle()
double com.neuronrobotics.sdk.addons.kinematics.AbstractRotoryLink.getTargetAngle ()
Gets the target angle.
Returns
the target angle
Definition at line 60 of file AbstractRotoryLink.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getTargetEngineeringUnits().
incrementAngle()
void com.neuronrobotics.sdk.addons.kinematics.AbstractRotoryLink.incrementAngle (double inc)
Increment angle.
Parameters
inc the inc
Definition at line 24 of file AbstractRotoryLink.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractLink.incrementEngineeringUnits().
isMaxAngle()
boolean com.neuronrobotics.sdk.addons.kinematics.AbstractRotoryLink.isMaxAngle ()
Checks if is max angle.
Returns
true, if is max angle
Definition at line 87 of file AbstractRotoryLink.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractLink.isMaxEngineeringUnits().
isMinAngle()
boolean com.neuronrobotics.sdk.addons.kinematics.AbstractRotoryLink.isMinAngle ()
Checks if is min angle.
Returns
true, if is min angle
Definition at line 96 of file AbstractRotoryLink.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractLink.isMinEngineeringUnits().
setCurrentAsAngle()
void com.neuronrobotics.sdk.addons.kinematics.AbstractRotoryLink.setCurrentAsAngle (double angle)
Sets the current as angle.
Parameters
angle the new current as angle
Definition at line 42 of file AbstractRotoryLink.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setCurrentEngineeringUnits().
setTargetAngle()
void com.neuronrobotics.sdk.addons.kinematics.AbstractRotoryLink.setTargetAngle (double pos)
Sets the target angle.
Parameters
pos the new target angle
Definition at line 33 of file AbstractRotoryLink.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setTargetEngineeringUnits().
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/addons/kinematics/AbstractRotoryLink.java