BowlerKernel: eu.mihosoft.vrl.v3d.Vector3d Class Reference
eu.mihosoft.vrl.v3d.Vector3d Class Reference
Public Member Functions
Vector3d (double x, double y, double z)
Vector3d (Number x, Number y, Number z)
Vector3d (double x, double y)
Vector3d (Number x, Number y)
Vector3d clone ()
Vector3d negated ()
Vector3d plus (Vector3d v)
Vector3d minus (Vector3d v)
Vector3d times (double a)
Vector3d times (Vector3d a)
Vector3d dividedBy (double a)
double dot (Vector3d a)
Vector3d lerp (Vector3d a, double t)
double magnitude ()
Vector3d normalized ()
Vector3d cross (Vector3d a)
String toStlString ()
StringBuilder toStlString (StringBuilder sb)
String toObjString ()
StringBuilder toObjString (StringBuilder sb)
Vector3d transform (Transform transform)
Vector3d transformed (Transform transform)
Vector3d transform (Transform transform, double amount)
Vector3d transformed (Transform transform, double amount)
String toString ()
boolean equals (Object obj)
boolean test (Object obj, double epsilon)
double angle (Vector3d v)
int hashCode ()
Vector3d orthogonal ()
Static Public Member Functions
static Vector3d xy (double x, double y)
static Vector3d xy (Number x, Number y)
static Vector3d xyz (double x, double y, double z)
static Vector3d xyz (Number x, Number y, Number z)
static Vector3d x (double x)
static Vector3d y (double y)
static Vector3d z (double z)
Static Public Attributes
static final Vector3d ZERO = new Vector3d(0, 0, 0)
static final Vector3d UNITY = new Vector3d(1, 1, 1)
static final Vector3d X_ONE = new Vector3d(1, 0, 0)
static final Vector3d Y_ONE = new Vector3d(0, 1, 0)
static final Vector3d Z_ONE = new Vector3d(0, 0, 1)
Static Private Attributes
static final long serialVersionUID = 1878117798187075166L
Detailed Description
3D Vector3d.
Author
Michael Hoffer <info@.nosp@m.mich.nosp@m.aelho.nosp@m.ffer.nosp@m..de>
Definition at line 48 of file Vector3d.java.
Constructor & Destructor Documentation
Vector3d() [1/4]
eu.mihosoft.vrl.v3d.Vector3d.Vector3d (double x, double y, double z)
Creates a new vector.
Parameters
x x value
y y value
z z value
Definition at line 78 of file Vector3d.java.
References eu.mihosoft.vrl.v3d.Vector3d.x(), eu.mihosoft.vrl.v3d.Vector3d.y(), and eu.mihosoft.vrl.v3d.Vector3d.z().
Referenced by eu.mihosoft.vrl.v3d.Vector3d.clone(), eu.mihosoft.vrl.v3d.Vector3d.cross(), eu.mihosoft.vrl.v3d.Vector3d.dividedBy(), eu.mihosoft.vrl.v3d.Vector3d.minus(), eu.mihosoft.vrl.v3d.Vector3d.negated(), eu.mihosoft.vrl.v3d.Vector3d.orthogonal(), eu.mihosoft.vrl.v3d.Vector3d.plus(), eu.mihosoft.vrl.v3d.Vector3d.test(), eu.mihosoft.vrl.v3d.Vector3d.times(), eu.mihosoft.vrl.v3d.Vector3d.x(), eu.mihosoft.vrl.v3d.Vector3d.xy(), eu.mihosoft.vrl.v3d.Vector3d.xyz(), eu.mihosoft.vrl.v3d.Vector3d.y(), and eu.mihosoft.vrl.v3d.Vector3d.z().
Vector3d() [2/4]
eu.mihosoft.vrl.v3d.Vector3d.Vector3d (Number x, Number y, Number z)
Definition at line 84 of file Vector3d.java.
References eu.mihosoft.vrl.v3d.Vector3d.x(), eu.mihosoft.vrl.v3d.Vector3d.y(), and eu.mihosoft.vrl.v3d.Vector3d.z().
Vector3d() [3/4]
eu.mihosoft.vrl.v3d.Vector3d.Vector3d (double x, double y)
Creates a new vector with specified
x
,
y
and
z = 0
.
Parameters
x x value
y y value
Definition at line 98 of file Vector3d.java.
References eu.mihosoft.vrl.v3d.Vector3d.x(), eu.mihosoft.vrl.v3d.Vector3d.y(), and eu.mihosoft.vrl.v3d.Vector3d.z().
Vector3d() [4/4]
eu.mihosoft.vrl.v3d.Vector3d.Vector3d (Number x, Number y)
Definition at line 105 of file Vector3d.java.
References eu.mihosoft.vrl.v3d.Vector3d.x(), and eu.mihosoft.vrl.v3d.Vector3d.y().
Member Function Documentation
angle()
double eu.mihosoft.vrl.v3d.Vector3d.angle (Vector3d v)
Returns the angle between this and the specified vector.
Parameters
v vector
Returns
angle in radians
Definition at line 431 of file Vector3d.java.
References eu.mihosoft.vrl.v3d.Vector3d.dot(), and eu.mihosoft.vrl.v3d.Vector3d.magnitude().
Referenced by eu.mihosoft.vrl.v3d.Fillet.outerFillet(), and eu.mihosoft.vrl.v3d.Edge.searchPlaneGroups().
clone()
Vector3d eu.mihosoft.vrl.v3d.Vector3d.clone ()
Definition at line 141 of file Vector3d.java.
References eu.mihosoft.vrl.v3d.Vector3d.Vector3d(), eu.mihosoft.vrl.v3d.Vector3d.x(), eu.mihosoft.vrl.v3d.Vector3d.y(), and eu.mihosoft.vrl.v3d.Vector3d.z().
Referenced by eu.mihosoft.vrl.v3d.Bounds.Bounds(), eu.mihosoft.vrl.v3d.Bounds.clone(), eu.mihosoft.vrl.v3d.Plane.clone(), eu.mihosoft.vrl.v3d.Vertex.clone(), eu.mihosoft.vrl.v3d.ext.org.poly2tri.PolygonUtil.concaveToConvex(), eu.mihosoft.vrl.v3d.Polygon.fromPoints(), eu.mihosoft.vrl.v3d.Edge.toPolygon(), and eu.mihosoft.vrl.v3d.Vector3d.transformed().
cross()
Vector3d eu.mihosoft.vrl.v3d.Vector3d.cross (Vector3d a)
Returns the cross product of this vector and the specified vector.
Note: this vector is not modified.
Parameters
a the vector
Returns
the cross product of this vector and the specified vector.
Definition at line 291 of file Vector3d.java.
References eu.mihosoft.vrl.v3d.Vector3d.Vector3d(), eu.mihosoft.vrl.v3d.Vector3d.x(), eu.mihosoft.vrl.v3d.Vector3d.y(), and eu.mihosoft.vrl.v3d.Vector3d.z().
Referenced by eu.mihosoft.vrl.v3d.Plane.createFromPoints(), eu.mihosoft.vrl.v3d.Cylinder.toPolygons(), eu.mihosoft.vrl.v3d.Polygon.transform(), and eu.mihosoft.vrl.v3d.Polygon.translate().
dividedBy()
Vector3d eu.mihosoft.vrl.v3d.Vector3d.dividedBy (double a)
Returns this vector devided by the specified value.
Parameters
a the value
Note: this vector is not modified.
Returns
this vector devided by the specified value
Definition at line 217 of file Vector3d.java.
References eu.mihosoft.vrl.v3d.Vector3d.Vector3d(), eu.mihosoft.vrl.v3d.Vector3d.x(), eu.mihosoft.vrl.v3d.Vector3d.y(), and eu.mihosoft.vrl.v3d.Vector3d.z().
Referenced by eu.mihosoft.vrl.v3d.Vector3d.normalized(), and eu.mihosoft.vrl.v3d.Extrude.normalizedX().
dot()
double eu.mihosoft.vrl.v3d.Vector3d.dot (Vector3d a)
Returns the dot product of this vector and the specified vector.
Note: this vector is not modified.
Parameters
a the second vector
Returns
the dot product of this vector and the specified vector
Definition at line 230 of file Vector3d.java.
References eu.mihosoft.vrl.v3d.Vector3d.x(), eu.mihosoft.vrl.v3d.Vector3d.y(), and eu.mihosoft.vrl.v3d.Vector3d.z().
Referenced by eu.mihosoft.vrl.v3d.Vector3d.angle(), eu.mihosoft.vrl.v3d.Plane.createFromPoints(), eu.mihosoft.vrl.v3d.Edge.getClosestPoint(), eu.mihosoft.vrl.v3d.Vector3d.magnitude(), eu.mihosoft.vrl.v3d.Vector3d.orthogonal(), eu.mihosoft.vrl.v3d.Plane.splitPolygon(), and eu.mihosoft.vrl.v3d.Polygon.transform().
equals()
boolean eu.mihosoft.vrl.v3d.Vector3d.equals (Object obj)
Definition at line 401 of file Vector3d.java.
References eu.mihosoft.vrl.v3d.Plane.EPSILON_Point, and eu.mihosoft.vrl.v3d.Vector3d.test().
Referenced by eu.mihosoft.vrl.v3d.Edge.falseBoundaryEdgeSharedWithOtherEdge(), and eu.mihosoft.vrl.v3d.Polygon.validateAndInit().
hashCode()
int eu.mihosoft.vrl.v3d.Vector3d.hashCode ()
Definition at line 440 of file Vector3d.java.
References eu.mihosoft.vrl.v3d.Vector3d.x(), eu.mihosoft.vrl.v3d.Vector3d.y(), and eu.mihosoft.vrl.v3d.Vector3d.z().
lerp()
Vector3d eu.mihosoft.vrl.v3d.Vector3d.lerp (Vector3d a, double t)
Linearly interpolates between this and the specified vector.
Note: this vector is not modified.
Parameters
a vector
t interpolation value
Returns
copy of this vector if
t = 0
; copy of a if
t = 1
; the point midway between this and the specified vector if
t = 0.5
Definition at line 245 of file Vector3d.java.
References eu.mihosoft.vrl.v3d.Vector3d.minus(), eu.mihosoft.vrl.v3d.Vector3d.plus(), and eu.mihosoft.vrl.v3d.Vector3d.times().
Referenced by eu.mihosoft.vrl.v3d.Vertex.interpolate().
magnitude()
double eu.mihosoft.vrl.v3d.Vector3d.magnitude ()
Returns the magnitude of this vector.
Note: this vector is not modified.
Returns
the magnitude of this vector
Definition at line 256 of file Vector3d.java.
References eu.mihosoft.vrl.v3d.Vector3d.dot().
Referenced by eu.mihosoft.vrl.v3d.Vector3d.angle(), eu.mihosoft.vrl.v3d.Vector3d.normalized(), eu.mihosoft.vrl.v3d.Extrude.normalizedX(), and eu.mihosoft.vrl.v3d.Fillet.outerFillet().
minus()
Vector3d eu.mihosoft.vrl.v3d.Vector3d.minus (Vector3d v)
Returns the difference of this vector and the specified vector.
Parameters
v the vector to subtract
Note: this vector is not modified.
Returns
the difference of this vector and the specified vector
Definition at line 178 of file Vector3d.java.
References eu.mihosoft.vrl.v3d.Vector3d.Vector3d(), eu.mihosoft.vrl.v3d.Vector3d.x(), eu.mihosoft.vrl.v3d.Vector3d.y(), and eu.mihosoft.vrl.v3d.Vector3d.z().
Referenced by eu.mihosoft.vrl.v3d.Plane.createFromPoints(), eu.mihosoft.vrl.v3d.Edge.Edge(), eu.mihosoft.vrl.v3d.Edge.getClosestPoint(), eu.mihosoft.vrl.v3d.Edge.length(), eu.mihosoft.vrl.v3d.Vector3d.lerp(), eu.mihosoft.vrl.v3d.Extrude.normalizedX(), eu.mihosoft.vrl.v3d.Fillet.outerFillet(), eu.mihosoft.vrl.v3d.Plane.splitPolygon(), eu.mihosoft.vrl.v3d.Cylinder.toPolygons(), eu.mihosoft.vrl.v3d.Polygon.transform(), and eu.mihosoft.vrl.v3d.Polygon.translate().
negated()
Vector3d eu.mihosoft.vrl.v3d.Vector3d.negated ()
Returns a negated copy of this vector.
Note: this vector is not modified.
Returns
a negated copy of this vector
Definition at line 152 of file Vector3d.java.
References eu.mihosoft.vrl.v3d.Vector3d.Vector3d(), eu.mihosoft.vrl.v3d.Vector3d.x(), eu.mihosoft.vrl.v3d.Vector3d.y(), and eu.mihosoft.vrl.v3d.Vector3d.z().
Referenced by eu.mihosoft.vrl.v3d.CSG.addTabsReorientation(), eu.mihosoft.vrl.v3d.Plane.flip(), eu.mihosoft.vrl.v3d.Vertex.flip(), and eu.mihosoft.vrl.v3d.Cylinder.toPolygons().
normalized()
Vector3d eu.mihosoft.vrl.v3d.Vector3d.normalized ()
Returns a normalized copy of this vector with length
1
.
Note: this vector is not modified.
Returns
a normalized copy of this vector with length
1
Definition at line 278 of file Vector3d.java.
References eu.mihosoft.vrl.v3d.Vector3d.dividedBy(), and eu.mihosoft.vrl.v3d.Vector3d.magnitude().
Referenced by eu.mihosoft.vrl.v3d.Plane.createFromPoints(), eu.mihosoft.vrl.v3d.Edge.Edge(), eu.mihosoft.vrl.v3d.Plane.Plane(), eu.mihosoft.vrl.v3d.Cylinder.toPolygons(), and eu.mihosoft.vrl.v3d.Polygon.transform().
orthogonal()
Vector3d eu.mihosoft.vrl.v3d.Vector3d.orthogonal ()
Creates a new vector which is orthogonal to this.
this_i , this_j , this_k greater than or equal to i,j,k {1,2,3} permutation
looking for orthogonal vector o to vector this: this_i * o_i + this_j * o_j + this_k * o_k = 0
Returns
a new vector which is orthogonal to this
Definition at line 508 of file Vector3d.java.
References eu.mihosoft.vrl.v3d.Vector3d.dot(), eu.mihosoft.vrl.v3d.Vector3d.Vector3d(), eu.mihosoft.vrl.v3d.Vector3d.x(), eu.mihosoft.vrl.v3d.Vector3d.y(), and eu.mihosoft.vrl.v3d.Vector3d.z().
plus()
Vector3d eu.mihosoft.vrl.v3d.Vector3d.plus (Vector3d v)
Returns the sum of this vector and the specified vector.
Parameters
v the vector to add
Note: this vector is not modified.
Returns
the sum of this vector and the specified vector
Definition at line 165 of file Vector3d.java.
References eu.mihosoft.vrl.v3d.Vector3d.Vector3d(), eu.mihosoft.vrl.v3d.Vector3d.x(), eu.mihosoft.vrl.v3d.Vector3d.y(), and eu.mihosoft.vrl.v3d.Vector3d.z().
Referenced by eu.mihosoft.vrl.v3d.Cylinder.cylPoint(), eu.mihosoft.vrl.v3d.Edge.getClosestPoint(), eu.mihosoft.vrl.v3d.Vector3d.lerp(), and eu.mihosoft.vrl.v3d.Sphere.sphereVertex().
test()
boolean eu.mihosoft.vrl.v3d.Vector3d.test (Object obj, double epsilon)
Definition at line 405 of file Vector3d.java.
References eu.mihosoft.vrl.v3d.Vector3d.Vector3d(), eu.mihosoft.vrl.v3d.Vector3d.x(), eu.mihosoft.vrl.v3d.Vector3d.y(), and eu.mihosoft.vrl.v3d.Vector3d.z().
Referenced by eu.mihosoft.vrl.v3d.Edge.equals(), eu.mihosoft.vrl.v3d.Vector3d.equals(), eu.mihosoft.vrl.v3d.Vertex.equals(), and eu.mihosoft.vrl.v3d.Edge.isThisPointOneOfMine().
times() [1/2]
Vector3d eu.mihosoft.vrl.v3d.Vector3d.times (double a)
Returns the product of this vector and the specified value.
Parameters
a the value
Note: this vector is not modified.
Returns
the product of this vector and the specified value
Definition at line 191 of file Vector3d.java.
References eu.mihosoft.vrl.v3d.Vector3d.Vector3d(), eu.mihosoft.vrl.v3d.Vector3d.x(), eu.mihosoft.vrl.v3d.Vector3d.y(), and eu.mihosoft.vrl.v3d.Vector3d.z().
Referenced by eu.mihosoft.vrl.v3d.Cylinder.Cylinder(), eu.mihosoft.vrl.v3d.Cylinder.cylPoint(), eu.mihosoft.vrl.v3d.Edge.getClosestPoint(), eu.mihosoft.vrl.v3d.Vector3d.lerp(), eu.mihosoft.vrl.v3d.Extrude.normalizedX(), and eu.mihosoft.vrl.v3d.Sphere.sphereVertex().
times() [2/2]
Vector3d eu.mihosoft.vrl.v3d.Vector3d.times (Vector3d a)
Returns the product of this vector and the specified vector.
Parameters
a the vector
Note: this vector is not modified.
Returns
the product of this vector and the specified vector
Definition at line 204 of file Vector3d.java.
References eu.mihosoft.vrl.v3d.Vector3d.Vector3d(), eu.mihosoft.vrl.v3d.Vector3d.x(), eu.mihosoft.vrl.v3d.Vector3d.y(), and eu.mihosoft.vrl.v3d.Vector3d.z().
toObjString() [1/2]
String eu.mihosoft.vrl.v3d.Vector3d.toObjString ()
Returns this vector in OBJ string format.
Returns
this vector in OBJ string format
Definition at line 325 of file Vector3d.java.
Referenced by eu.mihosoft.vrl.v3d.Vertex.toObjString().
toObjString() [2/2]
StringBuilder eu.mihosoft.vrl.v3d.Vector3d.toObjString (StringBuilder sb)
Returns this vector in OBJ string format.
Parameters
sb string builder
Returns
the specified string builder
Definition at line 335 of file Vector3d.java.
References eu.mihosoft.vrl.v3d.Vector3d.x(), eu.mihosoft.vrl.v3d.Vector3d.y(), and eu.mihosoft.vrl.v3d.Vector3d.z().
toStlString() [1/2]
String eu.mihosoft.vrl.v3d.Vector3d.toStlString ()
Returns this vector in STL string format.
Returns
this vector in STL string format
Definition at line 304 of file Vector3d.java.
Referenced by eu.mihosoft.vrl.v3d.Vertex.toStlString(), and eu.mihosoft.vrl.v3d.Polygon.toStlString().
toStlString() [2/2]
StringBuilder eu.mihosoft.vrl.v3d.Vector3d.toStlString (StringBuilder sb)
Returns this vector in STL string format.
Parameters
sb string builder
Returns
the specified string builder
Definition at line 314 of file Vector3d.java.
References eu.mihosoft.vrl.v3d.Vector3d.x(), eu.mihosoft.vrl.v3d.Vector3d.y(), and eu.mihosoft.vrl.v3d.Vector3d.z().
toString()
String eu.mihosoft.vrl.v3d.Vector3d.toString ()
Definition at line 393 of file Vector3d.java.
References eu.mihosoft.vrl.v3d.Vector3d.x(), eu.mihosoft.vrl.v3d.Vector3d.y(), and eu.mihosoft.vrl.v3d.Vector3d.z().
Referenced by eu.mihosoft.vrl.v3d.Vertex.toString().
transform() [1/2]
Vector3d eu.mihosoft.vrl.v3d.Vector3d.transform (Transform transform)
Applies the specified transformation to this vector.
Parameters
transform the transform to apply
Returns
this vector
Definition at line 348 of file Vector3d.java.
References eu.mihosoft.vrl.v3d.Vector3d.transform().
Referenced by eu.mihosoft.vrl.v3d.Vector3d.transform(), eu.mihosoft.vrl.v3d.Vertex.transform(), and eu.mihosoft.vrl.v3d.Vector3d.transformed().
transform() [2/2]
Vector3d eu.mihosoft.vrl.v3d.Vector3d.transform (Transform transform, double amount)
Applies the specified transformation to this vector.
Parameters
transform the transform to apply
amount the amount
Returns
this vector
Definition at line 372 of file Vector3d.java.
References eu.mihosoft.vrl.v3d.Vector3d.transform().
transformed() [1/2]
Vector3d eu.mihosoft.vrl.v3d.Vector3d.transformed (Transform transform)
Returns a transformed copy of this vector.
Parameters
transform the transform to apply
Note: this vector is not modified.
Returns
a transformed copy of this vector
Definition at line 361 of file Vector3d.java.
References eu.mihosoft.vrl.v3d.Vector3d.clone(), and eu.mihosoft.vrl.v3d.Vector3d.transform().
Referenced by eu.mihosoft.vrl.v3d.svg.SVGExporter.toPolyLine().
transformed() [2/2]
Vector3d eu.mihosoft.vrl.v3d.Vector3d.transformed (Transform transform, double amount)
Returns a transformed copy of this vector.
Parameters
transform the transform to apply
Note: this vector is not modified.
Parameters
amount the amount
Returns
a transformed copy of this vector
Definition at line 385 of file Vector3d.java.
References eu.mihosoft.vrl.v3d.Vector3d.clone(), and eu.mihosoft.vrl.v3d.Vector3d.transform().
x()
static Vector3d eu.mihosoft.vrl.v3d.Vector3d.x (double x) static
Creates a new vector with specified
x
.
Parameters
x x value
Returns
a new vector
[x,0,0]
Definition at line 474 of file Vector3d.java.
References eu.mihosoft.vrl.v3d.Vector3d.Vector3d().
Referenced by eu.mihosoft.vrl.v3d.Extrude.bezierToTransforms(), eu.mihosoft.vrl.v3d.Bounds.Bounds(), eu.mihosoft.vrl.v3d.Vector3d.clone(), eu.mihosoft.vrl.v3d.Edge.colinear(), eu.mihosoft.vrl.v3d.ext.org.poly2tri.PolygonUtil.concaveToConvex(), eu.mihosoft.vrl.v3d.Polygon.contains(), eu.mihosoft.vrl.v3d.Edge.contains(), eu.mihosoft.vrl.v3d.Bounds.contains(), eu.mihosoft.vrl.v3d.Vector3d.cross(), eu.mihosoft.vrl.v3d.Vector3d.dividedBy(), eu.mihosoft.vrl.v3d.Vector3d.dot(), eu.mihosoft.vrl.v3d.XModifier.eval(), eu.mihosoft.vrl.v3d.TextExtrude.evalCubicBezier(), eu.mihosoft.vrl.v3d.TextExtrude.evalQuadBezier(), eu.mihosoft.vrl.v3d.CSG.getBounds(), eu.mihosoft.vrl.v3d.Polygon.getBounds(), eu.mihosoft.vrl.v3d.Vertex.getX(), eu.mihosoft.vrl.v3d.Vector3d.hashCode(), eu.mihosoft.vrl.v3d.Bounds.intersects(), eu.mihosoft.vrl.v3d.Extrude.isCCW(), eu.mihosoft.vrl.v3d.CSGtoJavafx.meshFromPolygon(), eu.mihosoft.vrl.v3d.Vector3d.minus(), eu.mihosoft.vrl.v3d.Transform.mirror(), eu.mihosoft.vrl.v3d.CSG.move(), eu.mihosoft.vrl.v3d.Transform.move(), eu.mihosoft.vrl.v3d.Extrude.moveBezier(), eu.mihosoft.vrl.v3d.Vector3d.negated(), eu.mihosoft.vrl.v3d.Extrude.normalizedX(), eu.mihosoft.vrl.v3d.Vector3d.orthogonal(), eu.mihosoft.vrl.v3d.Fillet.outerFillet(), eu.mihosoft.vrl.v3d.Extrude.pathToTransforms(), com.neuronrobotics.bowlerkernel.Bezier3d.manipulation.performMove(), eu.mihosoft.vrl.v3d.Vector3d.plus(), eu.mihosoft.vrl.v3d.Transform.rot(), eu.mihosoft.vrl.v3d.Transform.scale(), com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.setCP1(), com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.setCP2(), com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.setEnd(), com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.setStart(), eu.mihosoft.vrl.v3d.Vector3d.test(), eu.mihosoft.vrl.v3d.Vector3d.times(), eu.mihosoft.vrl.v3d.Matrix3d.times(), eu.mihosoft.vrl.v3d.Vector3d.toObjString(), eu.mihosoft.vrl.v3d.Cube.toPolygons(), eu.mihosoft.vrl.v3d.RoundedCube.toPolygons(), eu.mihosoft.vrl.v3d.svg.SVGExporter.toPolyLine(), eu.mihosoft.vrl.v3d.Vector3d.toStlString(), eu.mihosoft.vrl.v3d.Vector3d.toString(), eu.mihosoft.vrl.v3d.CSG.toXMax(), eu.mihosoft.vrl.v3d.CSG.toXMin(), eu.mihosoft.vrl.v3d.Transform.transform(), eu.mihosoft.vrl.v3d.Transform.translate(), eu.mihosoft.vrl.v3d.Vector3d.Vector3d(), eu.mihosoft.vrl.v3d.Vector3d.xy(), and eu.mihosoft.vrl.v3d.Vector3d.xyz().
xy() [1/2]
static Vector3d eu.mihosoft.vrl.v3d.Vector3d.xy (double x, double y) static
Creates a new vector with specified
x
,
y
and
z = 0
.
Parameters
x x value
y y value
Definition at line 119 of file Vector3d.java.
References eu.mihosoft.vrl.v3d.Vector3d.Vector3d(), eu.mihosoft.vrl.v3d.Vector3d.x(), and eu.mihosoft.vrl.v3d.Vector3d.y().
Referenced by eu.mihosoft.vrl.v3d.Vector3d.xy().
xy() [2/2]
static Vector3d eu.mihosoft.vrl.v3d.Vector3d.xy (Number x, Number y) static
Definition at line 122 of file Vector3d.java.
References eu.mihosoft.vrl.v3d.Vector3d.x(), eu.mihosoft.vrl.v3d.Vector3d.xy(), and eu.mihosoft.vrl.v3d.Vector3d.y().
xyz() [1/2]
static Vector3d eu.mihosoft.vrl.v3d.Vector3d.xyz (double x, double y, double z) static
Creates a new vector with specified
x
,
y
and
z
.
Parameters
x x value
y y value
z z value
Definition at line 134 of file Vector3d.java.
References eu.mihosoft.vrl.v3d.Vector3d.Vector3d(), eu.mihosoft.vrl.v3d.Vector3d.x(), eu.mihosoft.vrl.v3d.Vector3d.y(), and eu.mihosoft.vrl.v3d.Vector3d.z().
xyz() [2/2]
static Vector3d eu.mihosoft.vrl.v3d.Vector3d.xyz (Number x, Number y, Number z) static
Definition at line 137 of file Vector3d.java.
References eu.mihosoft.vrl.v3d.Vector3d.Vector3d(), eu.mihosoft.vrl.v3d.Vector3d.x(), eu.mihosoft.vrl.v3d.Vector3d.y(), and eu.mihosoft.vrl.v3d.Vector3d.z().
y()
static Vector3d eu.mihosoft.vrl.v3d.Vector3d.y (double y) static
Creates a new vector with specified
y
.
Parameters
y y value
Returns
a new vector
[0,y,0]
Definition at line 484 of file Vector3d.java.
References eu.mihosoft.vrl.v3d.Vector3d.Vector3d().
Referenced by eu.mihosoft.vrl.v3d.Extrude.bezierToTransforms(), eu.mihosoft.vrl.v3d.Bounds.Bounds(), eu.mihosoft.vrl.v3d.Vector3d.clone(), eu.mihosoft.vrl.v3d.Edge.colinear(), eu.mihosoft.vrl.v3d.ext.org.poly2tri.PolygonUtil.concaveToConvex(), eu.mihosoft.vrl.v3d.Polygon.contains(), eu.mihosoft.vrl.v3d.Edge.contains(), eu.mihosoft.vrl.v3d.Bounds.contains(), eu.mihosoft.vrl.v3d.Vector3d.cross(), eu.mihosoft.vrl.v3d.Vector3d.dividedBy(), eu.mihosoft.vrl.v3d.Vector3d.dot(), eu.mihosoft.vrl.v3d.YModifier.eval(), eu.mihosoft.vrl.v3d.TextExtrude.evalCubicBezier(), eu.mihosoft.vrl.v3d.TextExtrude.evalQuadBezier(), eu.mihosoft.vrl.v3d.CSG.getBounds(), eu.mihosoft.vrl.v3d.Polygon.getBounds(), eu.mihosoft.vrl.v3d.Vertex.getY(), eu.mihosoft.vrl.v3d.Vector3d.hashCode(), eu.mihosoft.vrl.v3d.Bounds.intersects(), eu.mihosoft.vrl.v3d.Extrude.isCCW(), eu.mihosoft.vrl.v3d.CSGtoJavafx.meshFromPolygon(), eu.mihosoft.vrl.v3d.Vector3d.minus(), eu.mihosoft.vrl.v3d.Transform.mirror(), eu.mihosoft.vrl.v3d.CSG.move(), eu.mihosoft.vrl.v3d.Transform.move(), eu.mihosoft.vrl.v3d.Extrude.moveBezier(), eu.mihosoft.vrl.v3d.Vector3d.negated(), eu.mihosoft.vrl.v3d.Vector3d.orthogonal(), eu.mihosoft.vrl.v3d.Extrude.pathToTransforms(), com.neuronrobotics.bowlerkernel.Bezier3d.manipulation.performMove(), eu.mihosoft.vrl.v3d.Vector3d.plus(), eu.mihosoft.vrl.v3d.Transform.rot(), eu.mihosoft.vrl.v3d.Transform.scale(), com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.setCP1(), com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.setCP2(), com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.setEnd(), com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.setStart(), eu.mihosoft.vrl.v3d.Vector3d.test(), eu.mihosoft.vrl.v3d.Vector3d.times(), eu.mihosoft.vrl.v3d.Matrix3d.times(), eu.mihosoft.vrl.v3d.Vector3d.toObjString(), eu.mihosoft.vrl.v3d.Cube.toPolygons(), eu.mihosoft.vrl.v3d.Cylinder.toPolygons(), eu.mihosoft.vrl.v3d.RoundedCube.toPolygons(), eu.mihosoft.vrl.v3d.svg.SVGExporter.toPolyLine(), eu.mihosoft.vrl.v3d.Vector3d.toStlString(), eu.mihosoft.vrl.v3d.Vector3d.toString(), eu.mihosoft.vrl.v3d.CSG.toYMax(), eu.mihosoft.vrl.v3d.CSG.toYMin(), eu.mihosoft.vrl.v3d.Transform.transform(), eu.mihosoft.vrl.v3d.Transform.translate(), eu.mihosoft.vrl.v3d.Vector3d.Vector3d(), eu.mihosoft.vrl.v3d.Vector3d.xy(), and eu.mihosoft.vrl.v3d.Vector3d.xyz().
z()
static Vector3d eu.mihosoft.vrl.v3d.Vector3d.z (double z) static
Creates a new vector with specified
z
.
Parameters
z z value
Returns
a new vector
[0,0,z]
Definition at line 494 of file Vector3d.java.
References eu.mihosoft.vrl.v3d.Vector3d.Vector3d().
Referenced by eu.mihosoft.vrl.v3d.Extrude.bezierToTransforms(), eu.mihosoft.vrl.v3d.Bounds.Bounds(), eu.mihosoft.vrl.v3d.Vector3d.clone(), eu.mihosoft.vrl.v3d.Edge.colinear(), eu.mihosoft.vrl.v3d.ext.org.poly2tri.PolygonUtil.concaveToConvex(), eu.mihosoft.vrl.v3d.Edge.contains(), eu.mihosoft.vrl.v3d.Bounds.contains(), eu.mihosoft.vrl.v3d.Vector3d.cross(), eu.mihosoft.vrl.v3d.Vector3d.dividedBy(), eu.mihosoft.vrl.v3d.Vector3d.dot(), eu.mihosoft.vrl.v3d.ZModifier.eval(), eu.mihosoft.vrl.v3d.CSG.getBounds(), eu.mihosoft.vrl.v3d.Polygon.getBounds(), eu.mihosoft.vrl.v3d.Vertex.getZ(), eu.mihosoft.vrl.v3d.Vector3d.hashCode(), eu.mihosoft.vrl.v3d.Bounds.intersects(), eu.mihosoft.vrl.v3d.CSGtoJavafx.meshFromPolygon(), eu.mihosoft.vrl.v3d.Vector3d.minus(), eu.mihosoft.vrl.v3d.Transform.mirror(), eu.mihosoft.vrl.v3d.CSG.move(), eu.mihosoft.vrl.v3d.Transform.move(), eu.mihosoft.vrl.v3d.Vector3d.negated(), eu.mihosoft.vrl.v3d.Vector3d.orthogonal(), eu.mihosoft.vrl.v3d.Extrude.pathToTransforms(), com.neuronrobotics.bowlerkernel.Bezier3d.manipulation.performMove(), eu.mihosoft.vrl.v3d.Vector3d.plus(), eu.mihosoft.vrl.v3d.Transform.rot(), eu.mihosoft.vrl.v3d.Transform.scale(), com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.setCP1(), com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.setCP2(), com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.setEnd(), com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.setStart(), eu.mihosoft.vrl.v3d.Vector3d.test(), eu.mihosoft.vrl.v3d.Vector3d.times(), eu.mihosoft.vrl.v3d.Matrix3d.times(), eu.mihosoft.vrl.v3d.Vector3d.toObjString(), eu.mihosoft.vrl.v3d.Cube.toPolygons(), eu.mihosoft.vrl.v3d.Cylinder.toPolygons(), eu.mihosoft.vrl.v3d.RoundedCube.toPolygons(), eu.mihosoft.vrl.v3d.Vector3d.toStlString(), eu.mihosoft.vrl.v3d.Vector3d.toString(), eu.mihosoft.vrl.v3d.CSG.toZMax(), eu.mihosoft.vrl.v3d.CSG.toZMin(), eu.mihosoft.vrl.v3d.Transform.transform(), eu.mihosoft.vrl.v3d.Transform.translate(), eu.mihosoft.vrl.v3d.Vector3d.Vector3d(), and eu.mihosoft.vrl.v3d.Vector3d.xyz().
Member Data Documentation
serialVersionUID
final long eu.mihosoft.vrl.v3d.Vector3d.serialVersionUID = 1878117798187075166L static private
Definition at line 54 of file Vector3d.java.
UNITY
final Vector3d eu.mihosoft.vrl.v3d.Vector3d.UNITY = new Vector3d(1, 1, 1) static
The Constant UNITY.
Definition at line 60 of file Vector3d.java.
X_ONE
final Vector3d eu.mihosoft.vrl.v3d.Vector3d.X_ONE = new Vector3d(1, 0, 0) static
The Constant X_ONE.
Definition at line 63 of file Vector3d.java.
Referenced by eu.mihosoft.vrl.v3d.CSG.addTabsReorientation(), and eu.mihosoft.vrl.v3d.Extrude.normalizedX().
Y_ONE
final Vector3d eu.mihosoft.vrl.v3d.Vector3d.Y_ONE = new Vector3d(0, 1, 0) static
The Constant Y_ONE.
Definition at line 66 of file Vector3d.java.
Referenced by eu.mihosoft.vrl.v3d.CSG.addTabsReorientation(), and eu.mihosoft.vrl.v3d.Fillet.outerFillet().
Z_ONE
final Vector3d eu.mihosoft.vrl.v3d.Vector3d.Z_ONE = new Vector3d(0, 0, 1) static
The Constant Z_ONE.
Definition at line 69 of file Vector3d.java.
Referenced by eu.mihosoft.vrl.v3d.CSG.addTabsReorientation(), and eu.mihosoft.vrl.v3d.Cylinder.Cylinder().
ZERO
final Vector3d eu.mihosoft.vrl.v3d.Vector3d.ZERO = new Vector3d(0, 0, 0) static
The Constant ZERO.
Definition at line 57 of file Vector3d.java.
Referenced by eu.mihosoft.vrl.v3d.Cube.Cube(), eu.mihosoft.vrl.v3d.Cylinder.Cylinder(), eu.mihosoft.vrl.v3d.CSG.getBounds(), eu.mihosoft.vrl.v3d.RoundedCube.RoundedCube(), and eu.mihosoft.vrl.v3d.Polygon.validateAndInit().
The documentation for this class was generated from the following file:
JCSG/src/main/java/eu/mihosoft/vrl/v3d/Vector3d.java