BowlerKernel: com.neuronrobotics.bowlerstudio.scripting.SvgLoader Class Reference
com.neuronrobotics.bowlerstudio.scripting.SvgLoader Class Reference
Public Member Functions
Object inlineScriptRun (File code, ArrayList< Object > args) throws Exception
Object inlineScriptRun (String code, ArrayList< Object > args) throws Exception
String getShellType ()
ArrayList< String > getFileExtenetion ()
boolean getIsTextFile ()
String getDefaultContents ()
Public Member Functions inherited from com.neuronrobotics.bowlerstudio.scripting.IScriptingLanguage
default boolean isSupportedFileExtenetion (String filename)
default String getDefaultContents (String gitURL, String fileSlug)
Private Member Functions
Object run (SVGLoad s)
Detailed Description
Definition at line 15 of file SvgLoader.java.
Member Function Documentation
getDefaultContents()
String com.neuronrobotics.bowlerstudio.scripting.SvgLoader.getDefaultContents ()
Get the contents of an empty file
Returns
Implements com.neuronrobotics.bowlerstudio.scripting.IScriptingLanguage.
Definition at line 68 of file SvgLoader.java.
References eu.mihosoft.vrl.v3d.svg.SVGExporter.make().
getFileExtenetion()
ArrayList<String> com.neuronrobotics.bowlerstudio.scripting.SvgLoader.getFileExtenetion ()
Returns the list of supported file extentions Convention is to provide just the leters that make up the file extention
Implements com.neuronrobotics.bowlerstudio.scripting.IScriptingLanguage.
Definition at line 58 of file SvgLoader.java.
getIsTextFile()
boolean com.neuronrobotics.bowlerstudio.scripting.SvgLoader.getIsTextFile ()
This function returns if this is a binary file or a text file
Returns
true if the file is a text file.
Implements com.neuronrobotics.bowlerstudio.scripting.IScriptingLanguage.
Definition at line 63 of file SvgLoader.java.
getShellType()
String com.neuronrobotics.bowlerstudio.scripting.SvgLoader.getShellType ()
Returns the HashMap key for this language
Implements com.neuronrobotics.bowlerstudio.scripting.IScriptingLanguage.
Definition at line 53 of file SvgLoader.java.
inlineScriptRun() [1/2]
Object com.neuronrobotics.bowlerstudio.scripting.SvgLoader.inlineScriptRun (File code, ArrayList< Object > args) throws Exception
This interface is for adding additional language support.
Parameters
code file content of the code to be executed
args the incoming arguments as a list of objects
Returns
the objects returned form the code that ran
Implements com.neuronrobotics.bowlerstudio.scripting.IScriptingLanguage.
Definition at line 18 of file SvgLoader.java.
References com.neuronrobotics.bowlerstudio.scripting.SvgLoader.run().
inlineScriptRun() [2/2]
Object com.neuronrobotics.bowlerstudio.scripting.SvgLoader.inlineScriptRun (String code, ArrayList< Object > args) throws Exception
This interface is for adding additional language support.
Parameters
code the text content of the code to be executed
args the incoming arguments as a list of objects
Returns
the objects returned form the code that ran
Implements com.neuronrobotics.bowlerstudio.scripting.IScriptingLanguage.
Definition at line 24 of file SvgLoader.java.
References com.neuronrobotics.bowlerstudio.scripting.SvgLoader.run().
run()
Object com.neuronrobotics.bowlerstudio.scripting.SvgLoader.run (SVGLoad s) private
Definition at line 29 of file SvgLoader.java.
References eu.mihosoft.vrl.v3d.svg.SVGLoad.extrudeLayerToCSG(), eu.mihosoft.vrl.v3d.svg.SVGLoad.getLayers(), and eu.mihosoft.vrl.v3d.svg.SVGLoad.toPolygons().
Referenced by com.neuronrobotics.bowlerstudio.scripting.SvgLoader.inlineScriptRun().
The documentation for this class was generated from the following file:
src/main/java/com/neuronrobotics/bowlerstudio/scripting/SvgLoader.java