BowlerKernel: com.neuronrobotics.sdk.addons.kinematics.JointLimit Class Reference
com.neuronrobotics.sdk.addons.kinematics.JointLimit Class Reference
Public Member Functions
JointLimit (int axis, PIDLimitEvent e, LinkConfiguration linkConfiguration)
void setAxis (int axis)
int getAxis ()
void setValue (double value)
double getValue ()
void setTimeStamp (long timeStamp)
long getTimeStamp ()
void setLimitType (PIDLimitEventType limitType)
PIDLimitEventType getLimitType ()
String toString ()
Private Attributes
int axis
double value
long timeStamp
PIDLimitEventType limitType
Detailed Description
The Class JointLimit.
Definition at line 10 of file JointLimit.java.
Constructor & Destructor Documentation
JointLimit()
com.neuronrobotics.sdk.addons.kinematics.JointLimit.JointLimit (int axis, PIDLimitEvent e, LinkConfiguration linkConfiguration)
Instantiates a new joint limit.
Parameters
axis the axis
e the e
linkConfiguration the link configuration
Definition at line 31 of file JointLimit.java.
References com.neuronrobotics.sdk.addons.kinematics.JointLimit.axis, com.neuronrobotics.sdk.pid.PIDLimitEvent.getLimitType(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getScale(), com.neuronrobotics.sdk.pid.PIDLimitEvent.getTimeStamp(), com.neuronrobotics.sdk.pid.PIDLimitEvent.getValue(), com.neuronrobotics.sdk.addons.kinematics.JointLimit.setAxis(), com.neuronrobotics.sdk.addons.kinematics.JointLimit.setLimitType(), com.neuronrobotics.sdk.addons.kinematics.JointLimit.setTimeStamp(), and com.neuronrobotics.sdk.addons.kinematics.JointLimit.setValue().
Member Function Documentation
getAxis()
int com.neuronrobotics.sdk.addons.kinematics.JointLimit.getAxis ()
Gets the axis.
Returns
the axis
Definition at line 52 of file JointLimit.java.
References com.neuronrobotics.sdk.addons.kinematics.JointLimit.axis.
Referenced by com.neuronrobotics.sdk.addons.kinematics.JointLimit.toString().
getLimitType()
PIDLimitEventType com.neuronrobotics.sdk.addons.kinematics.JointLimit.getLimitType ()
Gets the limit type.
Returns
the limit type
Definition at line 106 of file JointLimit.java.
References com.neuronrobotics.sdk.addons.kinematics.JointLimit.limitType.
Referenced by com.neuronrobotics.sdk.addons.kinematics.JointLimit.toString().
getTimeStamp()
long com.neuronrobotics.sdk.addons.kinematics.JointLimit.getTimeStamp ()
Gets the time stamp.
Returns
the time stamp
Definition at line 88 of file JointLimit.java.
References com.neuronrobotics.sdk.addons.kinematics.JointLimit.timeStamp.
getValue()
double com.neuronrobotics.sdk.addons.kinematics.JointLimit.getValue ()
Gets the value.
Returns
the value
Definition at line 70 of file JointLimit.java.
References com.neuronrobotics.sdk.addons.kinematics.JointLimit.value.
setAxis()
void com.neuronrobotics.sdk.addons.kinematics.JointLimit.setAxis (int axis)
Sets the axis.
Parameters
axis the new axis
Definition at line 43 of file JointLimit.java.
References com.neuronrobotics.sdk.addons.kinematics.JointLimit.axis.
Referenced by com.neuronrobotics.sdk.addons.kinematics.JointLimit.JointLimit().
setLimitType()
void com.neuronrobotics.sdk.addons.kinematics.JointLimit.setLimitType (PIDLimitEventType limitType)
Sets the limit type.
Parameters
limitType the new limit type
Definition at line 97 of file JointLimit.java.
References com.neuronrobotics.sdk.addons.kinematics.JointLimit.limitType.
Referenced by com.neuronrobotics.sdk.addons.kinematics.JointLimit.JointLimit().
setTimeStamp()
void com.neuronrobotics.sdk.addons.kinematics.JointLimit.setTimeStamp (long timeStamp)
Sets the time stamp.
Parameters
timeStamp the new time stamp
Definition at line 79 of file JointLimit.java.
References com.neuronrobotics.sdk.addons.kinematics.JointLimit.timeStamp.
Referenced by com.neuronrobotics.sdk.addons.kinematics.JointLimit.JointLimit().
setValue()
void com.neuronrobotics.sdk.addons.kinematics.JointLimit.setValue (double value)
Sets the value.
Parameters
value the new value
Definition at line 61 of file JointLimit.java.
References com.neuronrobotics.sdk.addons.kinematics.JointLimit.value.
Referenced by com.neuronrobotics.sdk.addons.kinematics.JointLimit.JointLimit().
toString()
String com.neuronrobotics.sdk.addons.kinematics.JointLimit.toString ()
Definition at line 113 of file JointLimit.java.
References com.neuronrobotics.sdk.addons.kinematics.JointLimit.getAxis(), and com.neuronrobotics.sdk.addons.kinematics.JointLimit.getLimitType().
Member Data Documentation
axis
int com.neuronrobotics.sdk.addons.kinematics.JointLimit.axis private
The axis.
Definition at line 13 of file JointLimit.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.JointLimit.getAxis(), com.neuronrobotics.sdk.addons.kinematics.JointLimit.JointLimit(), and com.neuronrobotics.sdk.addons.kinematics.JointLimit.setAxis().
limitType
PIDLimitEventType com.neuronrobotics.sdk.addons.kinematics.JointLimit.limitType private
The limit type.
Definition at line 22 of file JointLimit.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.JointLimit.getLimitType(), and com.neuronrobotics.sdk.addons.kinematics.JointLimit.setLimitType().
timeStamp
long com.neuronrobotics.sdk.addons.kinematics.JointLimit.timeStamp private
The time stamp.
Definition at line 19 of file JointLimit.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.JointLimit.getTimeStamp(), and com.neuronrobotics.sdk.addons.kinematics.JointLimit.setTimeStamp().
value
double com.neuronrobotics.sdk.addons.kinematics.JointLimit.value private
The value.
Definition at line 16 of file JointLimit.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.JointLimit.getValue(), and com.neuronrobotics.sdk.addons.kinematics.JointLimit.setValue().
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/addons/kinematics/JointLimit.java