BowlerKernel: eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.MtlReader Class Reference
eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.MtlReader Class Reference
Public Member Functions
MtlReader (String filename, String parentUrl)
MtlReader (InputStream stream)
Map< String, Material > getMaterials ()
Private Member Functions
void read (InputStream inputStream) throws IOException
void addMaterial (String name)
Color readColor (String line)
Image loadImage (String filename)
Private Attributes
String baseUrl
Map< String, Material > materials = new HashMap<>()
PhongMaterial material = new PhongMaterial()
boolean modified = false
Detailed Description
Reader for OBJ file MTL material files.
Definition at line 54 of file MtlReader.java.
Constructor & Destructor Documentation
MtlReader() [1/2]
eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.MtlReader.MtlReader (String filename, String parentUrl)
Instantiates a new mtl reader.
Parameters
filename the filename
parentUrl the parent url
Definition at line 65 of file MtlReader.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.MtlReader.baseUrl, and eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.MtlReader.read().
MtlReader() [2/2]
eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.MtlReader.MtlReader (InputStream stream)
Instantiates a new mtl reader.
Parameters
stream the stream
Definition at line 84 of file MtlReader.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.MtlReader.read().
Member Function Documentation
addMaterial()
void eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.MtlReader.addMaterial (String name) private
Adds the material.
Parameters
name the name
Definition at line 171 of file MtlReader.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.MtlReader.material, eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.MtlReader.materials, and eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.MtlReader.modified.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.MtlReader.read().
getMaterials()
Map<String, Material> eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.MtlReader.getMaterials ()
Gets the materials.
Returns
the materials
Definition at line 214 of file MtlReader.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.MtlReader.materials.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.read(), and eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.read().
loadImage()
Image eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.MtlReader.loadImage (String filename) private
Load image.
Parameters
filename the filename
Returns
the image
Definition at line 202 of file MtlReader.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.MtlReader.baseUrl.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.MtlReader.read().
read()
void eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.MtlReader.read (InputStream inputStream) throws IOException private
Read.
Parameters
inputStream the input stream
Exceptions
IOException Signals that an I/O exception has occurred.
Definition at line 111 of file MtlReader.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.MtlReader.addMaterial(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.MtlReader.loadImage(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.MtlReader.material, eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.MtlReader.modified, and eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.MtlReader.readColor().
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.MtlReader.MtlReader().
readColor()
Color eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.MtlReader.readColor (String line) private
Read color.
Parameters
line the line
Returns
the color
Definition at line 188 of file MtlReader.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.MtlReader.read().
Member Data Documentation
baseUrl
String eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.MtlReader.baseUrl private
The base url.
Definition at line 57 of file MtlReader.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.MtlReader.loadImage(), and eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.MtlReader.MtlReader().
material
PhongMaterial eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.MtlReader.material = new PhongMaterial() private
The material.
Definition at line 100 of file MtlReader.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.MtlReader.addMaterial(), and eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.MtlReader.read().
materials
Map<String, Material> eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.MtlReader.materials = new HashMap<>() private
The materials.
Definition at line 97 of file MtlReader.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.MtlReader.addMaterial(), and eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.MtlReader.getMaterials().
modified
boolean eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.MtlReader.modified = false private
The modified.
Definition at line 103 of file MtlReader.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.MtlReader.addMaterial(), and eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.MtlReader.read().
The documentation for this class was generated from the following file:
JCSG/src/main/java/eu/mihosoft/vrl/v3d/ext/openjfx/importers/obj/MtlReader.java