BowlerKernel: com.neuronrobotics.bowlerstudio.AudioPlayer Class Reference
com.neuronrobotics.bowlerstudio.AudioPlayer Class Reference
Classes
enum Status
Public Member Functions
AudioPlayer (String tts)
AudioPlayer (File audioFile) throws IOException, UnsupportedAudioFileException
AudioPlayer (AudioInputStream ais)
AudioPlayer (File audioFile, LineListener lineListener) throws IOException, UnsupportedAudioFileException
AudioPlayer (AudioInputStream ais, LineListener lineListener)
AudioPlayer (File audioFile, SourceDataLine line, LineListener lineListener) throws IOException, UnsupportedAudioFileException
AudioPlayer (AudioInputStream ais, SourceDataLine line, LineListener lineListener)
AudioPlayer (File audioFile, SourceDataLine line, LineListener lineListener, int outputMode) throws IOException, UnsupportedAudioFileException
AudioPlayer (AudioInputStream ais, SourceDataLine line, LineListener lineListener, int outputMode)
void setAudio (AudioInputStream audio)
void cancel ()
SourceDataLine getLine ()
float getGainValue ()
void setGain (float fGain)
void run ()
void setLine (SourceDataLine line)
ISpeakingProgress getSpeakProgress ()
void setSpeakProgress (ISpeakingProgress speakProgress)
Static Public Member Functions
static double getThreshhold ()
static void setThreshhold (double t)
static double getLowerThreshhold ()
static void setLowerThreshhold (double lt)
static int getIntegralDepth ()
static void setIntegralDepth (int integralDepth)
static double getIntegralGain ()
static void setIntegralGain (double integralGain)
static double getDerivitiveGain ()
static void setDerivitiveGain (double derivitiveGain)
static IAudioProcessingLambda getLambda ()
static void setLambda (IAudioProcessingLambda lambda)
Static Public Attributes
static final int MONO = 0
static final int STEREO = 3
static final int LEFT_ONLY = 1
static final int RIGHT_ONLY = 2
Private Member Functions
double[] getIntegralBuffer ()
Private Attributes
AudioInputStream ais
LineListener lineListener
ISpeakingProgress speakProgress
SourceDataLine line
int outputMode
Status status = Status.WAITING
boolean exitRequested = false
float gain = 1.0f
String TTSString
Static Private Attributes
static double threshhold = 600 / 65535.0
static double lowerThreshhold = 100 / 65535.0
static int integralDepth = 30
static double integralGain = 1.0
static double derivitiveGain = 1.0
static IAudioProcessingLambda lambda
Detailed Description
A single Thread Audio Player Once used it has to be initialised again
Author
GOXR3PLUS
Definition at line 26 of file AudioPlayer.java.
Constructor & Destructor Documentation
AudioPlayer() [1/9]
com.neuronrobotics.bowlerstudio.AudioPlayer.AudioPlayer (String tts)
AudioPlayer which can be used if audio stream is to be set separately, using setAudio().
Definition at line 127 of file AudioPlayer.java.
References com.neuronrobotics.bowlerstudio.AudioPlayer.TTSString.
AudioPlayer() [2/9]
com.neuronrobotics.bowlerstudio.AudioPlayer.AudioPlayer (File audioFile) throws IOException, UnsupportedAudioFileException
Parameters
audioFile
Exceptions
IOException
UnsupportedAudioFileException
Definition at line 136 of file AudioPlayer.java.
AudioPlayer() [3/9]
com.neuronrobotics.bowlerstudio.AudioPlayer.AudioPlayer (AudioInputStream ais)
Parameters
ais
Definition at line 143 of file AudioPlayer.java.
References com.neuronrobotics.bowlerstudio.AudioPlayer.ais.
AudioPlayer() [4/9]
com.neuronrobotics.bowlerstudio.AudioPlayer.AudioPlayer (File audioFile, LineListener lineListener) throws IOException, UnsupportedAudioFileException
Parameters
audioFile
lineListener
Exceptions
IOException
UnsupportedAudioFileException
Definition at line 153 of file AudioPlayer.java.
References com.neuronrobotics.bowlerstudio.AudioPlayer.lineListener.
AudioPlayer() [5/9]
com.neuronrobotics.bowlerstudio.AudioPlayer.AudioPlayer (AudioInputStream ais, LineListener lineListener)
Parameters
ais
lineListener
Definition at line 162 of file AudioPlayer.java.
References com.neuronrobotics.bowlerstudio.AudioPlayer.ais, and com.neuronrobotics.bowlerstudio.AudioPlayer.lineListener.
AudioPlayer() [6/9]
com.neuronrobotics.bowlerstudio.AudioPlayer.AudioPlayer (File audioFile, SourceDataLine line, LineListener lineListener) throws IOException, UnsupportedAudioFileException
Parameters
audioFile
line
lineListener
Exceptions
IOException
UnsupportedAudioFileException
Definition at line 174 of file AudioPlayer.java.
References com.neuronrobotics.bowlerstudio.AudioPlayer.lineListener, and com.neuronrobotics.bowlerstudio.AudioPlayer.setLine().
AudioPlayer() [7/9]
com.neuronrobotics.bowlerstudio.AudioPlayer.AudioPlayer (AudioInputStream ais, SourceDataLine line, LineListener lineListener)
Parameters
ais
line
lineListener
Definition at line 186 of file AudioPlayer.java.
References com.neuronrobotics.bowlerstudio.AudioPlayer.ais, com.neuronrobotics.bowlerstudio.AudioPlayer.lineListener, and com.neuronrobotics.bowlerstudio.AudioPlayer.setLine().
AudioPlayer() [8/9]
com.neuronrobotics.bowlerstudio.AudioPlayer.AudioPlayer (File audioFile, SourceDataLine line, LineListener lineListener, int outputMode) throws IOException, UnsupportedAudioFileException
Parameters
audioFile audiofile
line line
lineListener lineListener
outputMode if MONO, force output to be mono; if STEREO, force output to be STEREO; if LEFT_ONLY, play a mono signal over the left channel of a stereo output, or mute the right channel of a stereo signal; if RIGHT_ONLY, do the same with the right output channel.
Exceptions
IOException IOException
UnsupportedAudioFileException UnsupportedAudioFileException
Definition at line 205 of file AudioPlayer.java.
References com.neuronrobotics.bowlerstudio.AudioPlayer.lineListener, com.neuronrobotics.bowlerstudio.AudioPlayer.outputMode, and com.neuronrobotics.bowlerstudio.AudioPlayer.setLine().
AudioPlayer() [9/9]
com.neuronrobotics.bowlerstudio.AudioPlayer.AudioPlayer (AudioInputStream ais, SourceDataLine line, LineListener lineListener, int outputMode)
Parameters
ais ais
line line
lineListener lineListener
outputMode if MONO, force output to be mono; if STEREO, force output to be STEREO; if LEFT_ONLY, play a mono signal over the left channel of a stereo output, or mute the right channel of a stereo signal; if RIGHT_ONLY, do the same with the right output channel.
Definition at line 224 of file AudioPlayer.java.
References com.neuronrobotics.bowlerstudio.AudioPlayer.ais, com.neuronrobotics.bowlerstudio.AudioPlayer.lineListener, com.neuronrobotics.bowlerstudio.AudioPlayer.outputMode, and com.neuronrobotics.bowlerstudio.AudioPlayer.setLine().
Member Function Documentation
cancel()
void com.neuronrobotics.bowlerstudio.AudioPlayer.cancel ()
Cancel the AudioPlayer which will cause the Thread to exit
Definition at line 244 of file AudioPlayer.java.
References com.neuronrobotics.bowlerstudio.AudioPlayer.exitRequested, and com.neuronrobotics.bowlerstudio.AudioPlayer.getLine().
Referenced by com.neuronrobotics.bowlerstudio.TextToSpeech.speak(), and com.neuronrobotics.bowlerstudio.TextToSpeech.stopSpeaking().
getDerivitiveGain()
static double com.neuronrobotics.bowlerstudio.AudioPlayer.getDerivitiveGain () static
Returns
the derivitiveGain
Definition at line 551 of file AudioPlayer.java.
References com.neuronrobotics.bowlerstudio.AudioPlayer.derivitiveGain.
Referenced by com.neuronrobotics.bowlerstudio.AudioPlayer.run().
getGainValue()
float com.neuronrobotics.bowlerstudio.AudioPlayer.getGainValue ()
Returns the GainValue
Definition at line 261 of file AudioPlayer.java.
References com.neuronrobotics.bowlerstudio.AudioPlayer.gain.
Referenced by com.neuronrobotics.bowlerstudio.AudioPlayer.run().
getIntegralBuffer()
double [] com.neuronrobotics.bowlerstudio.AudioPlayer.getIntegralBuffer () private
Returns
the integralBuffer
Definition at line 529 of file AudioPlayer.java.
References com.neuronrobotics.bowlerstudio.AudioPlayer.getIntegralDepth().
Referenced by com.neuronrobotics.bowlerstudio.AudioPlayer.run().
getIntegralDepth()
static int com.neuronrobotics.bowlerstudio.AudioPlayer.getIntegralDepth () static
Returns
the integralDepth
Definition at line 515 of file AudioPlayer.java.
References com.neuronrobotics.bowlerstudio.AudioPlayer.integralDepth.
Referenced by com.neuronrobotics.bowlerstudio.AudioPlayer.getIntegralBuffer(), and com.neuronrobotics.bowlerstudio.AudioPlayer.run().
getIntegralGain()
static double com.neuronrobotics.bowlerstudio.AudioPlayer.getIntegralGain () static
Returns
the integralGain
Definition at line 537 of file AudioPlayer.java.
References com.neuronrobotics.bowlerstudio.AudioPlayer.integralGain.
Referenced by com.neuronrobotics.bowlerstudio.AudioPlayer.run().
getLambda()
static IAudioProcessingLambda com.neuronrobotics.bowlerstudio.AudioPlayer.getLambda () static
Returns
the lambda
Definition at line 565 of file AudioPlayer.java.
References com.neuronrobotics.bowlerstudio.AudioPlayer.lambda.
getLine()
SourceDataLine com.neuronrobotics.bowlerstudio.AudioPlayer.getLine ()
Returns
The SourceDataLine
Definition at line 254 of file AudioPlayer.java.
References com.neuronrobotics.bowlerstudio.AudioPlayer.line.
Referenced by com.neuronrobotics.bowlerstudio.AudioPlayer.cancel(), com.neuronrobotics.bowlerstudio.AudioPlayer.run(), and com.neuronrobotics.bowlerstudio.AudioPlayer.setGain().
getLowerThreshhold()
static double com.neuronrobotics.bowlerstudio.AudioPlayer.getLowerThreshhold () static
Returns
the lowerThreshhold
Definition at line 500 of file AudioPlayer.java.
References com.neuronrobotics.bowlerstudio.AudioPlayer.lowerThreshhold.
getSpeakProgress()
ISpeakingProgress com.neuronrobotics.bowlerstudio.AudioPlayer.getSpeakProgress ()
Returns
the speakProgress
Definition at line 471 of file AudioPlayer.java.
References com.neuronrobotics.bowlerstudio.AudioPlayer.speakProgress.
getThreshhold()
static double com.neuronrobotics.bowlerstudio.AudioPlayer.getThreshhold () static
Returns
the threshhold
Definition at line 485 of file AudioPlayer.java.
References com.neuronrobotics.bowlerstudio.AudioPlayer.threshhold.
run()
void com.neuronrobotics.bowlerstudio.AudioPlayer.run ()
Definition at line 292 of file AudioPlayer.java.
References com.neuronrobotics.bowlerstudio.AudioPlayer.ais, com.neuronrobotics.bowlerstudio.AudioPlayer.exitRequested, com.neuronrobotics.bowlerstudio.AudioPlayer.getDerivitiveGain(), com.neuronrobotics.bowlerstudio.AudioPlayer.getGainValue(), com.neuronrobotics.bowlerstudio.AudioPlayer.getIntegralBuffer(), com.neuronrobotics.bowlerstudio.AudioPlayer.getIntegralDepth(), com.neuronrobotics.bowlerstudio.AudioPlayer.getIntegralGain(), com.neuronrobotics.bowlerstudio.AudioPlayer.getLine(), com.neuronrobotics.bowlerstudio.AudioPlayer.lambda, com.neuronrobotics.bowlerstudio.AudioPlayer.lineListener, com.neuronrobotics.bowlerstudio.AudioPlayer.outputMode, com.neuronrobotics.bowlerstudio.AudioPlayer.Status.PLAYING, com.neuronrobotics.bowlerstudio.AudioPlayer.setGain(), com.neuronrobotics.bowlerstudio.AudioPlayer.setLine(), com.neuronrobotics.bowlerstudio.AudioPlayer.speakProgress, com.neuronrobotics.bowlerstudio.IAudioProcessingLambda.startProcessing(), com.neuronrobotics.bowlerstudio.AudioPlayer.status, com.neuronrobotics.bowlerstudio.AudioPlayer.TTSString, com.neuronrobotics.bowlerstudio.IAudioProcessingLambda.update(), com.neuronrobotics.bowlerstudio.ISpeakingProgress.update(), and com.neuronrobotics.bowlerstudio.AudioStatus.X_NO_SOUND.
setAudio()
void com.neuronrobotics.bowlerstudio.AudioPlayer.setAudio (AudioInputStream audio)
Parameters
audio
Definition at line 234 of file AudioPlayer.java.
References com.neuronrobotics.bowlerstudio.AudioPlayer.Status.PLAYING, and com.neuronrobotics.bowlerstudio.AudioPlayer.status.
Referenced by com.neuronrobotics.bowlerstudio.CoquiDockerManager.speak(), and com.neuronrobotics.bowlerstudio.TextToSpeech.speak().
setDerivitiveGain()
static void com.neuronrobotics.bowlerstudio.AudioPlayer.setDerivitiveGain (double derivitiveGain) static
Parameters
derivitiveGain the derivitiveGain to set
Definition at line 558 of file AudioPlayer.java.
References com.neuronrobotics.bowlerstudio.AudioPlayer.derivitiveGain.
setGain()
void com.neuronrobotics.bowlerstudio.AudioPlayer.setGain (float fGain)
Sets Gain value. Line should be opened before calling this method. Linear scale 0.0 1.0 Threshold Coef. : 1/2 to avoid saturation.
Parameters
fGain
Definition at line 271 of file AudioPlayer.java.
References com.neuronrobotics.bowlerstudio.AudioPlayer.gain, and com.neuronrobotics.bowlerstudio.AudioPlayer.getLine().
Referenced by com.neuronrobotics.bowlerstudio.AudioPlayer.run(), com.neuronrobotics.bowlerstudio.CoquiDockerManager.speak(), and com.neuronrobotics.bowlerstudio.TextToSpeech.speak().
setIntegralDepth()
static void com.neuronrobotics.bowlerstudio.AudioPlayer.setIntegralDepth (int integralDepth) static
Parameters
integralDepth the integralDepth to set
Definition at line 522 of file AudioPlayer.java.
References com.neuronrobotics.bowlerstudio.AudioPlayer.integralDepth.
setIntegralGain()
static void com.neuronrobotics.bowlerstudio.AudioPlayer.setIntegralGain (double integralGain) static
Parameters
integralGain the integralGain to set
Definition at line 544 of file AudioPlayer.java.
References com.neuronrobotics.bowlerstudio.AudioPlayer.integralGain.
setLambda()
static void com.neuronrobotics.bowlerstudio.AudioPlayer.setLambda (IAudioProcessingLambda lambda) static
Parameters
lambda the lambda to set
Definition at line 572 of file AudioPlayer.java.
References com.neuronrobotics.bowlerstudio.AudioPlayer.lambda.
setLine()
void com.neuronrobotics.bowlerstudio.AudioPlayer.setLine (SourceDataLine line)
Definition at line 464 of file AudioPlayer.java.
References com.neuronrobotics.bowlerstudio.AudioPlayer.line.
Referenced by com.neuronrobotics.bowlerstudio.AudioPlayer.AudioPlayer(), and com.neuronrobotics.bowlerstudio.AudioPlayer.run().
setLowerThreshhold()
static void com.neuronrobotics.bowlerstudio.AudioPlayer.setLowerThreshhold (double lt) static
Parameters
lowerThreshhold the lowerThreshhold to set
Definition at line 507 of file AudioPlayer.java.
References com.neuronrobotics.bowlerstudio.AudioPlayer.lowerThreshhold.
setSpeakProgress()
void com.neuronrobotics.bowlerstudio.AudioPlayer.setSpeakProgress (ISpeakingProgress speakProgress)
Parameters
speakProgress the speakProgress to set
Definition at line 478 of file AudioPlayer.java.
References com.neuronrobotics.bowlerstudio.AudioPlayer.speakProgress.
Referenced by com.neuronrobotics.bowlerstudio.CoquiDockerManager.speak(), and com.neuronrobotics.bowlerstudio.TextToSpeech.speak().
setThreshhold()
static void com.neuronrobotics.bowlerstudio.AudioPlayer.setThreshhold (double t) static
Parameters
threshhold the threshhold to set
Definition at line 492 of file AudioPlayer.java.
References com.neuronrobotics.bowlerstudio.AudioPlayer.threshhold.
Member Data Documentation
ais
AudioInputStream com.neuronrobotics.bowlerstudio.AudioPlayer.ais private
Definition at line 32 of file AudioPlayer.java.
Referenced by com.neuronrobotics.bowlerstudio.AudioPlayer.AudioPlayer(), and com.neuronrobotics.bowlerstudio.AudioPlayer.run().
derivitiveGain
double com.neuronrobotics.bowlerstudio.AudioPlayer.derivitiveGain = 1.0 static private
Definition at line 46 of file AudioPlayer.java.
Referenced by com.neuronrobotics.bowlerstudio.AudioPlayer.getDerivitiveGain(), and com.neuronrobotics.bowlerstudio.AudioPlayer.setDerivitiveGain().
exitRequested
boolean com.neuronrobotics.bowlerstudio.AudioPlayer.exitRequested = false private
Definition at line 39 of file AudioPlayer.java.
Referenced by com.neuronrobotics.bowlerstudio.AudioPlayer.cancel(), and com.neuronrobotics.bowlerstudio.AudioPlayer.run().
gain
float com.neuronrobotics.bowlerstudio.AudioPlayer.gain = 1.0f private
Definition at line 40 of file AudioPlayer.java.
Referenced by com.neuronrobotics.bowlerstudio.AudioPlayer.getGainValue(), and com.neuronrobotics.bowlerstudio.AudioPlayer.setGain().
integralDepth
int com.neuronrobotics.bowlerstudio.AudioPlayer.integralDepth = 30 static private
Definition at line 44 of file AudioPlayer.java.
Referenced by com.neuronrobotics.bowlerstudio.AudioPlayer.getIntegralDepth(), and com.neuronrobotics.bowlerstudio.AudioPlayer.setIntegralDepth().
integralGain
double com.neuronrobotics.bowlerstudio.AudioPlayer.integralGain = 1.0 static private
Definition at line 45 of file AudioPlayer.java.
Referenced by com.neuronrobotics.bowlerstudio.AudioPlayer.getIntegralGain(), and com.neuronrobotics.bowlerstudio.AudioPlayer.setIntegralGain().
lambda
IAudioProcessingLambda com.neuronrobotics.bowlerstudio.AudioPlayer.lambda static private
Definition at line 47 of file AudioPlayer.java.
Referenced by com.neuronrobotics.bowlerstudio.AudioPlayer.getLambda(), com.neuronrobotics.bowlerstudio.AudioPlayer.run(), and com.neuronrobotics.bowlerstudio.AudioPlayer.setLambda().
LEFT_ONLY
final int com.neuronrobotics.bowlerstudio.AudioPlayer.LEFT_ONLY = 1 static
Definition at line 30 of file AudioPlayer.java.
line
SourceDataLine com.neuronrobotics.bowlerstudio.AudioPlayer.line private
Definition at line 35 of file AudioPlayer.java.
Referenced by com.neuronrobotics.bowlerstudio.AudioPlayer.getLine(), and com.neuronrobotics.bowlerstudio.AudioPlayer.setLine().
lineListener
LineListener com.neuronrobotics.bowlerstudio.AudioPlayer.lineListener private
Definition at line 33 of file AudioPlayer.java.
Referenced by com.neuronrobotics.bowlerstudio.AudioPlayer.AudioPlayer(), and com.neuronrobotics.bowlerstudio.AudioPlayer.run().
lowerThreshhold
double com.neuronrobotics.bowlerstudio.AudioPlayer.lowerThreshhold = 100 / 65535.0 static private
Definition at line 43 of file AudioPlayer.java.
Referenced by com.neuronrobotics.bowlerstudio.AudioPlayer.getLowerThreshhold(), and com.neuronrobotics.bowlerstudio.AudioPlayer.setLowerThreshhold().
MONO
final int com.neuronrobotics.bowlerstudio.AudioPlayer.MONO = 0 static
Definition at line 28 of file AudioPlayer.java.
outputMode
int com.neuronrobotics.bowlerstudio.AudioPlayer.outputMode private
Definition at line 36 of file AudioPlayer.java.
Referenced by com.neuronrobotics.bowlerstudio.AudioPlayer.AudioPlayer(), and com.neuronrobotics.bowlerstudio.AudioPlayer.run().
RIGHT_ONLY
final int com.neuronrobotics.bowlerstudio.AudioPlayer.RIGHT_ONLY = 2 static
Definition at line 31 of file AudioPlayer.java.
speakProgress
ISpeakingProgress com.neuronrobotics.bowlerstudio.AudioPlayer.speakProgress private
Definition at line 34 of file AudioPlayer.java.
Referenced by com.neuronrobotics.bowlerstudio.AudioPlayer.getSpeakProgress(), com.neuronrobotics.bowlerstudio.AudioPlayer.run(), and com.neuronrobotics.bowlerstudio.AudioPlayer.setSpeakProgress().
status
Status com.neuronrobotics.bowlerstudio.AudioPlayer.status = Status.WAITING private
Definition at line 38 of file AudioPlayer.java.
Referenced by com.neuronrobotics.bowlerstudio.AudioPlayer.run(), and com.neuronrobotics.bowlerstudio.AudioPlayer.setAudio().
STEREO
final int com.neuronrobotics.bowlerstudio.AudioPlayer.STEREO = 3 static
Definition at line 29 of file AudioPlayer.java.
threshhold
double com.neuronrobotics.bowlerstudio.AudioPlayer.threshhold = 600 / 65535.0 static private
Definition at line 42 of file AudioPlayer.java.
Referenced by com.neuronrobotics.bowlerstudio.AudioPlayer.getThreshhold(), and com.neuronrobotics.bowlerstudio.AudioPlayer.setThreshhold().
TTSString
String com.neuronrobotics.bowlerstudio.AudioPlayer.TTSString private
Definition at line 41 of file AudioPlayer.java.
Referenced by com.neuronrobotics.bowlerstudio.AudioPlayer.AudioPlayer(), and com.neuronrobotics.bowlerstudio.AudioPlayer.run().
The documentation for this class was generated from the following file:
src/main/java/com/neuronrobotics/bowlerstudio/AudioPlayer.java