BowlerKernel: com.neuronrobotics.bowlerstudio.physics.VehicleCSGPhysicsManager Class Reference
com.neuronrobotics.bowlerstudio.physics.VehicleCSGPhysicsManager Class Reference
Public Member Functions
VehicleCSGPhysicsManager (ArrayList< CSG > baseCSG, Transform pose, double mass, boolean adjustCenter, PhysicsCore core)
void update (float timeStep)
RaycastVehicle getVehicle ()
void setVehicle (RaycastVehicle vehicle)
VehicleTuning getTuning ()
void setTuning (VehicleTuning tuning)
Public Member Functions inherited from com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager
CSGPhysicsManager (List< CSG > baseCSG, Transform pose, double mass, boolean adjustCenter, PhysicsCore core)
CSGPhysicsManager (ArrayList< CSG > baseCSG, Vector3f start, double mass, PhysicsCore core)
void setup (CollisionShape fallShape, Transform pose, double mass, PhysicsCore core)
RigidBody getFallRigidBody ()
void setFallRigidBody (RigidBody fallRigidBody)
List< CSG > getBaseCSG ()
void setBaseCSG (List< CSG > baseCSG)
Transform getUpdateTransform ()
Affine getRigidBodyLocation ()
IPhysicsUpdate getUpdateManager ()
void setUpdateManager (IPhysicsUpdate updateManager)
PhysicsCore getCore ()
void setCore (PhysicsCore core)
Public Attributes
VehicleRaycaster vehicleRayCaster
Private Attributes
VehicleTuning tuning = new VehicleTuning()
RaycastVehicle vehicle
Additional Inherited Members
Static Public Member Functions inherited from com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager
static CSG getBoundingBox (CSG incoming)
Protected Member Functions inherited from com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager
CSG loadCSGToPoints (CSG baseCSG, boolean adjustCenter, Transform pose, ObjectArrayList< Vector3f > arg0)
Protected Attributes inherited from com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager
List< CSG > baseCSG = null
Detailed Description
Definition at line 14 of file VehicleCSGPhysicsManager.java.
Constructor & Destructor Documentation
VehicleCSGPhysicsManager()
com.neuronrobotics.bowlerstudio.physics.VehicleCSGPhysicsManager.VehicleCSGPhysicsManager (ArrayList< CSG > baseCSG, Transform pose, double mass, boolean adjustCenter, PhysicsCore core)
Definition at line 23 of file VehicleCSGPhysicsManager.java.
References com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager.baseCSG, com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager.core, com.neuronrobotics.bowlerstudio.physics.PhysicsCore.getDynamicsWorld(), com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager.getFallRigidBody(), com.neuronrobotics.bowlerstudio.physics.VehicleCSGPhysicsManager.getTuning(), com.neuronrobotics.bowlerstudio.physics.VehicleCSGPhysicsManager.setVehicle(), and com.neuronrobotics.bowlerstudio.physics.VehicleCSGPhysicsManager.vehicleRayCaster.
Member Function Documentation
getTuning()
VehicleTuning com.neuronrobotics.bowlerstudio.physics.VehicleCSGPhysicsManager.getTuning ()
Definition at line 57 of file VehicleCSGPhysicsManager.java.
References com.neuronrobotics.bowlerstudio.physics.VehicleCSGPhysicsManager.tuning.
Referenced by com.neuronrobotics.bowlerstudio.physics.VehicleCSGPhysicsManager.VehicleCSGPhysicsManager().
getVehicle()
RaycastVehicle com.neuronrobotics.bowlerstudio.physics.VehicleCSGPhysicsManager.getVehicle ()
Definition at line 48 of file VehicleCSGPhysicsManager.java.
References com.neuronrobotics.bowlerstudio.physics.VehicleCSGPhysicsManager.vehicle.
setTuning()
void com.neuronrobotics.bowlerstudio.physics.VehicleCSGPhysicsManager.setTuning (VehicleTuning tuning)
Definition at line 61 of file VehicleCSGPhysicsManager.java.
References com.neuronrobotics.bowlerstudio.physics.VehicleCSGPhysicsManager.tuning.
setVehicle()
void com.neuronrobotics.bowlerstudio.physics.VehicleCSGPhysicsManager.setVehicle (RaycastVehicle vehicle)
Definition at line 53 of file VehicleCSGPhysicsManager.java.
References com.neuronrobotics.bowlerstudio.physics.VehicleCSGPhysicsManager.vehicle.
Referenced by com.neuronrobotics.bowlerstudio.physics.VehicleCSGPhysicsManager.VehicleCSGPhysicsManager().
update()
void com.neuronrobotics.bowlerstudio.physics.VehicleCSGPhysicsManager.update (float timeStep)
Run the update for this ridgid body. Run any controllers for links
Reimplemented from com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager.
Definition at line 33 of file VehicleCSGPhysicsManager.java.
References com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager.getFallRigidBody(), com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager.getUpdateManager(), com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager.getUpdateTransform(), com.neuronrobotics.bowlerstudio.physics.IPhysicsUpdate.update(), and com.neuronrobotics.bowlerstudio.physics.VehicleCSGPhysicsManager.vehicle.
Member Data Documentation
tuning
VehicleTuning com.neuronrobotics.bowlerstudio.physics.VehicleCSGPhysicsManager.tuning = new VehicleTuning() private
Definition at line 19 of file VehicleCSGPhysicsManager.java.
Referenced by com.neuronrobotics.bowlerstudio.physics.VehicleCSGPhysicsManager.getTuning(), and com.neuronrobotics.bowlerstudio.physics.VehicleCSGPhysicsManager.setTuning().
vehicle
RaycastVehicle com.neuronrobotics.bowlerstudio.physics.VehicleCSGPhysicsManager.vehicle private
Definition at line 21 of file VehicleCSGPhysicsManager.java.
Referenced by com.neuronrobotics.bowlerstudio.physics.VehicleCSGPhysicsManager.getVehicle(), com.neuronrobotics.bowlerstudio.physics.VehicleCSGPhysicsManager.setVehicle(), and com.neuronrobotics.bowlerstudio.physics.VehicleCSGPhysicsManager.update().
vehicleRayCaster
VehicleRaycaster com.neuronrobotics.bowlerstudio.physics.VehicleCSGPhysicsManager.vehicleRayCaster
Definition at line 20 of file VehicleCSGPhysicsManager.java.
Referenced by com.neuronrobotics.bowlerstudio.physics.VehicleCSGPhysicsManager.VehicleCSGPhysicsManager().
The documentation for this class was generated from the following file:
src/main/java/com/neuronrobotics/bowlerstudio/physics/VehicleCSGPhysicsManager.java