BowlerKernel: com.neuronrobotics.sdk.commands.bcs.io.GetValueCommand Class Reference
com.neuronrobotics.sdk.commands.bcs.io.GetValueCommand Class Reference
Public Member Functions
GetValueCommand (int channel)
byte[] getCallingData ()
BowlerDatagram validate (BowlerDatagram data) throws InvalidResponseException
Public Member Functions inherited from com.neuronrobotics.sdk.common.BowlerAbstractCommand
void setOpCode (String opCode)
String getOpCode ()
void setMethod (BowlerMethod method)
BowlerMethod getMethod ()
byte getLength ()
byte[] getBytes ()
String toString ()
void setData (ByteList data)
ByteList getCallingDataStorage ()
void setNamespaceIndex (int namespaceIndex)
int getNamespaceIndex ()
Private Attributes
int channel
Additional Inherited Members
Static Public Member Functions inherited from com.neuronrobotics.sdk.common.BowlerAbstractCommand
static BowlerAbstractCommand parse (BowlerDatagram data)
Detailed Description
The Class GetValueCommand.
Definition at line 27 of file GetValueCommand.java.
Constructor & Destructor Documentation
GetValueCommand()
com.neuronrobotics.sdk.commands.bcs.io.GetValueCommand.GetValueCommand (int channel)
Instantiates a new gets the value command.
Parameters
channel the channel
Definition at line 37 of file GetValueCommand.java.
References com.neuronrobotics.sdk.commands.bcs.io.GetValueCommand.channel, com.neuronrobotics.sdk.common.BowlerMethod.GET, com.neuronrobotics.sdk.common.BowlerAbstractCommand.setMethod(), and com.neuronrobotics.sdk.common.BowlerAbstractCommand.setOpCode().
Member Function Documentation
getCallingData()
byte [] com.neuronrobotics.sdk.commands.bcs.io.GetValueCommand.getCallingData ()
Get the data that will be used to call the RPC (i.e. parameters for the RPC). Each instance of a BAC should determine the correct method for generating this data.
Returns
the parameters for the RPC
Reimplemented from com.neuronrobotics.sdk.common.BowlerAbstractCommand.
Definition at line 47 of file GetValueCommand.java.
References com.neuronrobotics.sdk.commands.bcs.io.GetValueCommand.channel, and com.neuronrobotics.sdk.common.ByteList.wrap().
validate()
BowlerDatagram com.neuronrobotics.sdk.commands.bcs.io.GetValueCommand.validate (BowlerDatagram data) throws InvalidResponseException
Determine if the return response was successful; throw an InvalidResponseExpection otherwise. Commands with more complicated validation should override this method and provide more specific checking.
Parameters
data the data
Returns
the incoming response
Exceptions
InvalidResponseException the invalid response exception
Reimplemented from com.neuronrobotics.sdk.common.BowlerAbstractCommand.
Definition at line 55 of file GetValueCommand.java.
References com.neuronrobotics.sdk.common.BowlerAbstractCommand.data, and com.neuronrobotics.sdk.common.BowlerAbstractCommand.getOpCode().
Member Data Documentation
channel
int com.neuronrobotics.sdk.commands.bcs.io.GetValueCommand.channel private
The channel.
Definition at line 30 of file GetValueCommand.java.
Referenced by com.neuronrobotics.sdk.commands.bcs.io.GetValueCommand.getCallingData(), and com.neuronrobotics.sdk.commands.bcs.io.GetValueCommand.GetValueCommand().
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/commands/bcs/io/GetValueCommand.java