BowlerKernel: eu.mihosoft.vrl.v3d.Dodecahedron Class Reference
eu.mihosoft.vrl.v3d.Dodecahedron Class Reference
Public Member Functions
Dodecahedron ()
Dodecahedron (double size)
Dodecahedron (Vector3d center, double size)
List< Polygon > toPolygons ()
Vector3d getCenter ()
Dodecahedron setCenter (Vector3d center)
double getRadius ()
void setRadius (double radius)
PropertyStorage getProperties ()
Dodecahedron noCenter ()
Public Member Functions inherited from eu.mihosoft.vrl.v3d.Primitive
CSG toCSG ()
Private Attributes
Vector3d center
double radius
boolean centered = true
final PropertyStorage properties = new PropertyStorage()
Detailed Description
Definition at line 11 of file Dodecahedron.java.
Constructor & Destructor Documentation
Dodecahedron() [1/3]
eu.mihosoft.vrl.v3d.Dodecahedron.Dodecahedron ()
Constructor. Creates a new dodecahedron with center
[0,0,0]
and dimensions
[1,1,1]
.
Definition at line 31 of file Dodecahedron.java.
References eu.mihosoft.vrl.v3d.Dodecahedron.center, and eu.mihosoft.vrl.v3d.Dodecahedron.radius.
Dodecahedron() [2/3]
eu.mihosoft.vrl.v3d.Dodecahedron.Dodecahedron (double size)
Constructor. Creates a new dodecahedron with center
[0,0,0]
and radius
size
.
Parameters
size size
Definition at line 42 of file Dodecahedron.java.
References eu.mihosoft.vrl.v3d.Dodecahedron.center, and eu.mihosoft.vrl.v3d.Dodecahedron.radius.
Dodecahedron() [3/3]
eu.mihosoft.vrl.v3d.Dodecahedron.Dodecahedron (Vector3d center, double size)
Constructor. Creates a new dodecahedron with the specified center and radius.
Parameters
center center of the dodecahedron
size of the dodecahedron
Definition at line 54 of file Dodecahedron.java.
References eu.mihosoft.vrl.v3d.Dodecahedron.center.
Member Function Documentation
getCenter()
Vector3d eu.mihosoft.vrl.v3d.Dodecahedron.getCenter ()
Gets the center.
Returns
the center
Definition at line 101 of file Dodecahedron.java.
References eu.mihosoft.vrl.v3d.Dodecahedron.center.
getProperties()
PropertyStorage eu.mihosoft.vrl.v3d.Dodecahedron.getProperties ()
Returns the property storage of this primitive.
Returns
the property storage of this primitive
Reimplemented from eu.mihosoft.vrl.v3d.Primitive.
Definition at line 137 of file Dodecahedron.java.
References eu.mihosoft.vrl.v3d.Dodecahedron.properties.
getRadius()
double eu.mihosoft.vrl.v3d.Dodecahedron.getRadius ()
Gets the radius.
Returns
the radius
Definition at line 120 of file Dodecahedron.java.
References eu.mihosoft.vrl.v3d.Dodecahedron.radius.
noCenter()
Dodecahedron eu.mihosoft.vrl.v3d.Dodecahedron.noCenter ()
Defines that this dodecahedron will not be centered.
Returns
this dodecahedron
Definition at line 145 of file Dodecahedron.java.
References eu.mihosoft.vrl.v3d.Dodecahedron.centered.
setCenter()
Dodecahedron eu.mihosoft.vrl.v3d.Dodecahedron.setCenter (Vector3d center)
Sets the center.
Parameters
center the center to set
Definition at line 110 of file Dodecahedron.java.
References eu.mihosoft.vrl.v3d.Dodecahedron.center.
setRadius()
void eu.mihosoft.vrl.v3d.Dodecahedron.setRadius (double radius)
Sets the radius.
Parameters
radius the radius to set
Definition at line 129 of file Dodecahedron.java.
References eu.mihosoft.vrl.v3d.Dodecahedron.radius.
toPolygons()
List<Polygon> eu.mihosoft.vrl.v3d.Dodecahedron.toPolygons ()
Returns the polygons that define this primitive.
Note: this method computes the polygons each time this method is called. The polygons can be cached inside a CSG object.
Returns
a list of polygons that define this primitive
Reimplemented from eu.mihosoft.vrl.v3d.Primitive.
Definition at line 63 of file Dodecahedron.java.
References eu.mihosoft.vrl.v3d.CSG.getPolygons(), eu.mihosoft.vrl.v3d.ext.quickhull3d.HullUtil.hull(), eu.mihosoft.vrl.v3d.Dodecahedron.radius, and eu.mihosoft.vrl.v3d.CSG.scale().
Member Data Documentation
center
Vector3d eu.mihosoft.vrl.v3d.Dodecahedron.center private
Center of this dodecahedron.
Definition at line 16 of file Dodecahedron.java.
Referenced by eu.mihosoft.vrl.v3d.Dodecahedron.Dodecahedron(), eu.mihosoft.vrl.v3d.Dodecahedron.getCenter(), and eu.mihosoft.vrl.v3d.Dodecahedron.setCenter().
centered
boolean eu.mihosoft.vrl.v3d.Dodecahedron.centered = true private
The centered.
Definition at line 23 of file Dodecahedron.java.
Referenced by eu.mihosoft.vrl.v3d.Dodecahedron.noCenter().
properties
final PropertyStorage eu.mihosoft.vrl.v3d.Dodecahedron.properties = new PropertyStorage() private
The properties.
Definition at line 26 of file Dodecahedron.java.
Referenced by eu.mihosoft.vrl.v3d.Dodecahedron.getProperties().
radius
double eu.mihosoft.vrl.v3d.Dodecahedron.radius private
Dodecahedron circumscribed radius.
Definition at line 20 of file Dodecahedron.java.
Referenced by eu.mihosoft.vrl.v3d.Dodecahedron.Dodecahedron(), eu.mihosoft.vrl.v3d.Dodecahedron.getRadius(), eu.mihosoft.vrl.v3d.Dodecahedron.setRadius(), and eu.mihosoft.vrl.v3d.Dodecahedron.toPolygons().
The documentation for this class was generated from the following file:
JCSG/src/main/java/eu/mihosoft/vrl/v3d/Dodecahedron.java