BowlerKernel: eu.mihosoft.vrl.v3d.YModifier Class Reference
eu.mihosoft.vrl.v3d.YModifier Class Reference
Public Member Functions
YModifier ()
YModifier (boolean centered)
double eval (Vector3d pos, CSG csg)
Private Attributes
Bounds bounds
double min = 0
double max = 1.0
double sPerUnit
boolean centered
Detailed Description
Modifies along y axis.
Author
Michael Hoffer <info@.nosp@m.mich.nosp@m.aelho.nosp@m.ffer.nosp@m..de>
Definition at line 14 of file YModifier.java.
Constructor & Destructor Documentation
YModifier() [1/2]
eu.mihosoft.vrl.v3d.YModifier.YModifier ()
Constructor.
Definition at line 34 of file YModifier.java.
YModifier() [2/2]
eu.mihosoft.vrl.v3d.YModifier.YModifier (boolean centered)
Constructor.
Parameters
centered defines whether to center origin at the csg location
Definition at line 42 of file YModifier.java.
References eu.mihosoft.vrl.v3d.YModifier.centered.
Member Function Documentation
eval()
double eu.mihosoft.vrl.v3d.YModifier.eval (Vector3d v, CSG csg)
Evaluates the function at the specified location.
Parameters
v location
csg csg
Returns
the weight of the specified position
Implements eu.mihosoft.vrl.v3d.WeightFunction.
Definition at line 50 of file YModifier.java.
References eu.mihosoft.vrl.v3d.YModifier.bounds, eu.mihosoft.vrl.v3d.YModifier.centered, eu.mihosoft.vrl.v3d.CSG.getBounds(), eu.mihosoft.vrl.v3d.Bounds.getMax(), eu.mihosoft.vrl.v3d.Bounds.getMin(), eu.mihosoft.vrl.v3d.YModifier.max, eu.mihosoft.vrl.v3d.YModifier.min, eu.mihosoft.vrl.v3d.YModifier.sPerUnit, and eu.mihosoft.vrl.v3d.Vector3d.y().
Member Data Documentation
bounds
Bounds eu.mihosoft.vrl.v3d.YModifier.bounds private
The bounds.
Definition at line 17 of file YModifier.java.
Referenced by eu.mihosoft.vrl.v3d.YModifier.eval().
centered
boolean eu.mihosoft.vrl.v3d.YModifier.centered private
The centered.
Definition at line 29 of file YModifier.java.
Referenced by eu.mihosoft.vrl.v3d.YModifier.eval(), and eu.mihosoft.vrl.v3d.YModifier.YModifier().
max
double eu.mihosoft.vrl.v3d.YModifier.max = 1.0 private
The max.
Definition at line 23 of file YModifier.java.
Referenced by eu.mihosoft.vrl.v3d.YModifier.eval().
min
double eu.mihosoft.vrl.v3d.YModifier.min = 0 private
The min.
Definition at line 20 of file YModifier.java.
Referenced by eu.mihosoft.vrl.v3d.YModifier.eval().
sPerUnit
double eu.mihosoft.vrl.v3d.YModifier.sPerUnit private
The s per unit.
Definition at line 26 of file YModifier.java.
Referenced by eu.mihosoft.vrl.v3d.YModifier.eval().
The documentation for this class was generated from the following file:
JCSG/src/main/java/eu/mihosoft/vrl/v3d/YModifier.java