BowlerKernel: com.neuronrobotics.sdk.pid.PIDEvent Class Reference
com.neuronrobotics.sdk.pid.PIDEvent Class Reference
Public Member Functions
PIDEvent ()
PIDEvent (int chan, float tick, long time, int velocity)
void set (int chan, float tick, long time, int velocity)
PIDEvent (BowlerDatagram data)
void setGroup (int channel)
int getGroup ()
void setValue (float ticks)
float getValue ()
void setTimeStamp (long timeStamp)
long getTimeStamp ()
String toString ()
void setVelocity (int vel)
int getVelocity ()
Private Attributes
int channel
float ticks
long timeStamp
int velocity
Detailed Description
The Class PIDEvent.
Definition at line 10 of file PIDEvent.java.
Constructor & Destructor Documentation
PIDEvent() [1/3]
com.neuronrobotics.sdk.pid.PIDEvent.PIDEvent ()
Definition at line 24 of file PIDEvent.java.
PIDEvent() [2/3]
com.neuronrobotics.sdk.pid.PIDEvent.PIDEvent (int chan, float tick, long time, int velocity)
Instantiates a new PID event.
Parameters
chan the chan
tick the tick
time the time
velocity the velocity
Definition at line 36 of file PIDEvent.java.
References com.neuronrobotics.sdk.pid.PIDEvent.setGroup(), com.neuronrobotics.sdk.pid.PIDEvent.setTimeStamp(), com.neuronrobotics.sdk.pid.PIDEvent.setValue(), com.neuronrobotics.sdk.pid.PIDEvent.setVelocity(), and com.neuronrobotics.sdk.pid.PIDEvent.velocity.
PIDEvent() [3/3]
com.neuronrobotics.sdk.pid.PIDEvent.PIDEvent (BowlerDatagram data)
Instantiates a new PID event.
Parameters
data the data
Definition at line 61 of file PIDEvent.java.
References com.neuronrobotics.sdk.common.ByteList.convertToInt(), com.neuronrobotics.sdk.common.ByteList.getByte(), com.neuronrobotics.sdk.common.ByteList.getBytes(), com.neuronrobotics.sdk.common.BowlerDatagram.getData(), com.neuronrobotics.sdk.common.BowlerDatagram.getRPC(), com.neuronrobotics.sdk.pid.PIDEvent.setGroup(), com.neuronrobotics.sdk.pid.PIDEvent.setTimeStamp(), com.neuronrobotics.sdk.pid.PIDEvent.setValue(), and com.neuronrobotics.sdk.pid.PIDEvent.setVelocity().
Member Function Documentation
getGroup()
int com.neuronrobotics.sdk.pid.PIDEvent.getGroup ()
Gets the group.
Returns
the group
Definition at line 85 of file PIDEvent.java.
References com.neuronrobotics.sdk.pid.PIDEvent.channel.
Referenced by com.neuronrobotics.sdk.namespace.bcs.pid.AbstractPidNamespaceImp.AbstractPidNamespaceImp(), com.neuronrobotics.sdk.namespace.bcs.pid.AbstractPidNamespaceImp.firePIDEvent(), and com.neuronrobotics.sdk.pid.PIDChannel.setPid().
getTimeStamp()
long com.neuronrobotics.sdk.pid.PIDEvent.getTimeStamp ()
Gets the time stamp.
Returns
the time stamp
Definition at line 121 of file PIDEvent.java.
References com.neuronrobotics.sdk.pid.PIDEvent.timeStamp.
Referenced by com.neuronrobotics.sdk.namespace.bcs.pid.AbstractPidNamespaceImp.firePIDEvent().
getValue()
float com.neuronrobotics.sdk.pid.PIDEvent.getValue ()
Gets the value.
Returns
the value
Definition at line 103 of file PIDEvent.java.
References com.neuronrobotics.sdk.pid.PIDEvent.ticks.
Referenced by com.neuronrobotics.sdk.namespace.bcs.pid.AbstractPidNamespaceImp.AbstractPidNamespaceImp(), com.neuronrobotics.sdk.namespace.bcs.pid.AbstractPidNamespaceImp.firePIDEvent(), com.neuronrobotics.sdk.addons.kinematics.PidPrismaticLink.setPIDChannel(), and com.neuronrobotics.sdk.addons.kinematics.PidRotoryLink.setPIDChannel().
getVelocity()
int com.neuronrobotics.sdk.pid.PIDEvent.getVelocity ()
Gets the velocity.
Returns
the velocity
Definition at line 147 of file PIDEvent.java.
References com.neuronrobotics.sdk.pid.PIDEvent.velocity.
set()
void com.neuronrobotics.sdk.pid.PIDEvent.set (int chan, float tick, long time, int velocity)
Sets new PID event.
Parameters
chan the chan
tick the tick
time the time
velocity the velocity
Definition at line 50 of file PIDEvent.java.
References com.neuronrobotics.sdk.pid.PIDEvent.setGroup(), com.neuronrobotics.sdk.pid.PIDEvent.setTimeStamp(), com.neuronrobotics.sdk.pid.PIDEvent.setValue(), com.neuronrobotics.sdk.pid.PIDEvent.setVelocity(), and com.neuronrobotics.sdk.pid.PIDEvent.velocity.
Referenced by com.neuronrobotics.sdk.pid.VirtualGenericPIDDevice.SyncThread.run().
setGroup()
void com.neuronrobotics.sdk.pid.PIDEvent.setGroup (int channel)
Sets the group.
Parameters
channel the new group
Definition at line 76 of file PIDEvent.java.
References com.neuronrobotics.sdk.pid.PIDEvent.channel.
Referenced by com.neuronrobotics.sdk.pid.PIDEvent.PIDEvent(), and com.neuronrobotics.sdk.pid.PIDEvent.set().
setTimeStamp()
void com.neuronrobotics.sdk.pid.PIDEvent.setTimeStamp (long timeStamp)
Sets the time stamp.
Parameters
timeStamp the new time stamp
Definition at line 112 of file PIDEvent.java.
References com.neuronrobotics.sdk.pid.PIDEvent.timeStamp.
Referenced by com.neuronrobotics.sdk.pid.PIDEvent.PIDEvent(), and com.neuronrobotics.sdk.pid.PIDEvent.set().
setValue()
void com.neuronrobotics.sdk.pid.PIDEvent.setValue (float ticks)
Sets the value.
Parameters
ticks the new value
Definition at line 94 of file PIDEvent.java.
References com.neuronrobotics.sdk.pid.PIDEvent.ticks.
Referenced by com.neuronrobotics.sdk.pid.PIDEvent.PIDEvent(), and com.neuronrobotics.sdk.pid.PIDEvent.set().
setVelocity()
void com.neuronrobotics.sdk.pid.PIDEvent.setVelocity (int vel)
Sets the velocity.
Parameters
vel the new velocity
Definition at line 138 of file PIDEvent.java.
Referenced by com.neuronrobotics.sdk.pid.PIDEvent.PIDEvent(), and com.neuronrobotics.sdk.pid.PIDEvent.set().
toString()
String com.neuronrobotics.sdk.pid.PIDEvent.toString ()
Definition at line 129 of file PIDEvent.java.
References com.neuronrobotics.sdk.pid.PIDEvent.channel, com.neuronrobotics.sdk.pid.PIDEvent.ticks, com.neuronrobotics.sdk.pid.PIDEvent.timeStamp, and com.neuronrobotics.sdk.pid.PIDEvent.velocity.
Member Data Documentation
channel
int com.neuronrobotics.sdk.pid.PIDEvent.channel private
The channel.
Definition at line 13 of file PIDEvent.java.
Referenced by com.neuronrobotics.sdk.pid.PIDEvent.getGroup(), com.neuronrobotics.sdk.pid.PIDEvent.setGroup(), and com.neuronrobotics.sdk.pid.PIDEvent.toString().
ticks
float com.neuronrobotics.sdk.pid.PIDEvent.ticks private
The ticks.
Definition at line 16 of file PIDEvent.java.
Referenced by com.neuronrobotics.sdk.pid.PIDEvent.getValue(), com.neuronrobotics.sdk.pid.PIDEvent.setValue(), and com.neuronrobotics.sdk.pid.PIDEvent.toString().
timeStamp
long com.neuronrobotics.sdk.pid.PIDEvent.timeStamp private
The time stamp.
Definition at line 19 of file PIDEvent.java.
Referenced by com.neuronrobotics.sdk.pid.PIDEvent.getTimeStamp(), com.neuronrobotics.sdk.pid.PIDEvent.setTimeStamp(), and com.neuronrobotics.sdk.pid.PIDEvent.toString().
velocity
int com.neuronrobotics.sdk.pid.PIDEvent.velocity private
The velocity.
Definition at line 22 of file PIDEvent.java.
Referenced by com.neuronrobotics.sdk.pid.PIDEvent.getVelocity(), com.neuronrobotics.sdk.pid.PIDEvent.PIDEvent(), com.neuronrobotics.sdk.pid.PIDEvent.set(), and com.neuronrobotics.sdk.pid.PIDEvent.toString().
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/pid/PIDEvent.java