BowlerKernel: com.neuronrobotics.sdk.common.MACAddress Class Reference
com.neuronrobotics.sdk.common.MACAddress Class Reference
Public Member Functions
MACAddress ()
MACAddress (String address)
MACAddress (byte[] address)
boolean equals (Object o)
boolean equals (MACAddress addr)
String toString ()
String getHexByteString (int index)
boolean isValid ()
byte[] getBytes ()
void increment ()
void setValues (MACAddress address2)
Static Public Attributes
static final String BROADCAST = "00:00:00:00:00:00"
Private Member Functions
void init (String address)
Private Attributes
byte[] address = new byte[]{0,0,0,0,0,0}
Detailed Description
A mac address object. This object represents a MAC Address.
Author
rbreznak
Definition at line 22 of file MACAddress.java.
Constructor & Destructor Documentation
MACAddress() [1/3]
com.neuronrobotics.sdk.common.MACAddress.MACAddress ()
Instantiates a new mAC address.
Definition at line 33 of file MACAddress.java.
MACAddress() [2/3]
com.neuronrobotics.sdk.common.MACAddress.MACAddress (String address)
Construct a new MAC address object with a given MAC address represented as a string of 6 bytes in hex deliminated by semicolons.
Parameters
address The string representation.
Definition at line 39 of file MACAddress.java.
References com.neuronrobotics.sdk.common.MACAddress.address, and com.neuronrobotics.sdk.common.MACAddress.init().
MACAddress() [3/3]
com.neuronrobotics.sdk.common.MACAddress.MACAddress (byte[] address)
Create a mac address from an array of bytes.
Parameters
address The byte array.
Definition at line 64 of file MACAddress.java.
References com.neuronrobotics.sdk.common.MACAddress.address.
Member Function Documentation
equals() [1/2]
boolean com.neuronrobotics.sdk.common.MACAddress.equals (MACAddress addr)
Equals.
Parameters
addr the addr
Returns
true, if successful
Definition at line 88 of file MACAddress.java.
References com.neuronrobotics.sdk.common.MACAddress.address.
equals() [2/2]
boolean com.neuronrobotics.sdk.common.MACAddress.equals (Object o)
Compare two mac addresses.
Parameters
o the o
Returns
true, if successful
Definition at line 76 of file MACAddress.java.
getBytes()
byte [] com.neuronrobotics.sdk.common.MACAddress.getBytes ()
Gets the bytes.
Returns
the bytes
Implements com.neuronrobotics.sdk.common.ISendable.
Definition at line 132 of file MACAddress.java.
References com.neuronrobotics.sdk.common.MACAddress.address.
Referenced by com.neuronrobotics.sdk.commands.neuronrobotics.dyio.ProvisionCommand.ProvisionCommand().
getHexByteString()
String com.neuronrobotics.sdk.common.MACAddress.getHexByteString (int index)
Gets the hex byte string.
Parameters
index the index
Returns
the hex byte string
Definition at line 115 of file MACAddress.java.
References com.neuronrobotics.sdk.common.MACAddress.address.
Referenced by com.neuronrobotics.sdk.common.MACAddress.toString().
increment()
void com.neuronrobotics.sdk.common.MACAddress.increment ()
Increment.
Definition at line 139 of file MACAddress.java.
References com.neuronrobotics.sdk.common.MACAddress.address.
init()
void com.neuronrobotics.sdk.common.MACAddress.init (String address) private
Inits the.
Parameters
address the address
Definition at line 48 of file MACAddress.java.
References com.neuronrobotics.sdk.common.MACAddress.address.
Referenced by com.neuronrobotics.sdk.common.MACAddress.MACAddress().
isValid()
boolean com.neuronrobotics.sdk.common.MACAddress.isValid ()
Checks if is valid.
Returns
true, if is valid
Definition at line 124 of file MACAddress.java.
Referenced by com.neuronrobotics.sdk.common.BowlerAbstractDevice.setAddress().
setValues()
void com.neuronrobotics.sdk.common.MACAddress.setValues (MACAddress address2)
Sets the values.
Parameters
address2 the new values
Definition at line 164 of file MACAddress.java.
References com.neuronrobotics.sdk.common.MACAddress.address.
toString()
String com.neuronrobotics.sdk.common.MACAddress.toString ()
Definition at line 100 of file MACAddress.java.
References com.neuronrobotics.sdk.common.MACAddress.address, and com.neuronrobotics.sdk.common.MACAddress.getHexByteString().
Referenced by com.neuronrobotics.sdk.serial.SerialConnection.getConnectionByMacAddress().
Member Data Documentation
address
byte [] com.neuronrobotics.sdk.common.MACAddress.address = new byte[]{0,0,0,0,0,0} private
The address.
Definition at line 28 of file MACAddress.java.
Referenced by com.neuronrobotics.sdk.common.MACAddress.equals(), com.neuronrobotics.sdk.common.MACAddress.getBytes(), com.neuronrobotics.sdk.common.MACAddress.getHexByteString(), com.neuronrobotics.sdk.common.MACAddress.increment(), com.neuronrobotics.sdk.common.MACAddress.init(), com.neuronrobotics.sdk.common.MACAddress.MACAddress(), com.neuronrobotics.sdk.common.MACAddress.setValues(), and com.neuronrobotics.sdk.common.MACAddress.toString().
BROADCAST
final String com.neuronrobotics.sdk.common.MACAddress.BROADCAST = "00:00:00:00:00:00" static
The Constant BROADCAST.
Definition at line 25 of file MACAddress.java.
Referenced by com.neuronrobotics.sdk.dyio.DyIO.DyIO(), com.neuronrobotics.sdk.genericdevice.GenericDevice.GenericDevice(), and com.neuronrobotics.sdk.pid.GenericPIDDevice.GenericPIDDevice().
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/common/MACAddress.java