BowlerKernel: com.neuronrobotics.sdk.network.AbstractNetworkDeviceServer Class Reference
com.neuronrobotics.sdk.network.AbstractNetworkDeviceServer Class Reference
Public Member Functions
AbstractNetworkDeviceServer (GenericDevice device, boolean useAsync, BowlerAbstractConnection serverConnection)
Public Member Functions inherited from com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer
BowlerAbstractServer (MACAddress mac)
void addBowlerDeviceServerNamespace (BowlerAbstractDeviceServerNamespace ns)
void removeBowlerDeviceServerNamespace (BowlerAbstractDeviceServerNamespace ns)
ArrayList< BowlerAbstractConnection > getServers ()
void startNetworkServer (final int port) throws IOException
void startNetworkServer () throws IOException
void addServer (BowlerAbstractConnection srv)
BowlerDatagram onSyncReceive (BowlerDatagram data)
void pushAsyncPacket (int namespaceIndex, String namespace, String rpcString, Object[] arguments, BowlerDataType[] asyncArguments)
synchronized void pushAsyncPacket (BowlerDatagram data)
ArrayList< BowlerAbstractDeviceServerNamespace > getNamespaces ()
void setNamespaces (ArrayList< BowlerAbstractDeviceServerNamespace > namespaces)
MACAddress getMacAddress ()
void setMacAddress (MACAddress macAddress)
Private Attributes
GenericDevice gen
Detailed Description
The Class AbstractNetworkDeviceServer.
Definition at line 15 of file AbstractNetworkDeviceServer.java.
Constructor & Destructor Documentation
AbstractNetworkDeviceServer()
com.neuronrobotics.sdk.network.AbstractNetworkDeviceServer.AbstractNetworkDeviceServer (GenericDevice device, boolean useAsync, BowlerAbstractConnection serverConnection)
Instantiates a new abstract network device server.
Parameters
device the device
useAsync the use async
serverConnection the server connection
Definition at line 30 of file AbstractNetworkDeviceServer.java.
References com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.addBowlerDeviceServerNamespace(), com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.addServer(), com.neuronrobotics.sdk.network.AbstractNetworkDeviceServer.gen, com.neuronrobotics.sdk.common.BowlerAbstractDevice.getAddress(), com.neuronrobotics.sdk.common.BowlerAbstractDevice.getConnection(), and com.neuronrobotics.sdk.common.BowlerAbstractDevice.getNamespaces().
Member Data Documentation
gen
GenericDevice com.neuronrobotics.sdk.network.AbstractNetworkDeviceServer.gen private
The gen.
Definition at line 18 of file AbstractNetworkDeviceServer.java.
Referenced by com.neuronrobotics.sdk.network.AbstractNetworkDeviceServer.AbstractNetworkDeviceServer().
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/network/AbstractNetworkDeviceServer.java