BowlerKernel: com.neuronrobotics.sdk.ui.AbstractConnectionPanel Class Reference
com.neuronrobotics.sdk.ui.AbstractConnectionPanel Class Reference abstract
Public Member Functions
abstract BowlerAbstractConnection getConnection ()
abstract void refresh ()
AbstractConnectionPanel (String title, ImageIcon icon, ConnectionDialog connectionDialog)
AbstractConnectionPanel (String title, ConnectionDialog connectionDialog)
void setTitle (String title)
String getTitle ()
void setIcon (ImageIcon icon)
ImageIcon getIcon ()
ConnectionDialog getConnectionDialog ()
void setConnectionDialog (ConnectionDialog connectionDialog)
Private Attributes
String title
ImageIcon icon
ConnectionDialog connectionDialog
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
The Class AbstractConnectionPanel.
Definition at line 26 of file AbstractConnectionPanel.java.
Constructor & Destructor Documentation
AbstractConnectionPanel() [1/2]
com.neuronrobotics.sdk.ui.AbstractConnectionPanel.AbstractConnectionPanel (String title, ImageIcon icon, ConnectionDialog connectionDialog)
Instantiates a new abstract connection panel.
Parameters
title the title
icon the icon
connectionDialog the connection dialog
Definition at line 61 of file AbstractConnectionPanel.java.
References com.neuronrobotics.sdk.ui.AbstractConnectionPanel.icon, com.neuronrobotics.sdk.ui.AbstractConnectionPanel.setConnectionDialog(), com.neuronrobotics.sdk.ui.AbstractConnectionPanel.setIcon(), com.neuronrobotics.sdk.ui.AbstractConnectionPanel.setTitle(), and com.neuronrobotics.sdk.ui.AbstractConnectionPanel.title.
AbstractConnectionPanel() [2/2]
com.neuronrobotics.sdk.ui.AbstractConnectionPanel.AbstractConnectionPanel (String title, ConnectionDialog connectionDialog)
Instantiates a new abstract connection panel.
Parameters
title the title
connectionDialog the connection dialog
Definition at line 74 of file AbstractConnectionPanel.java.
References com.neuronrobotics.sdk.ui.ConnectionImageIconFactory.getIcon(), com.neuronrobotics.sdk.ui.AbstractConnectionPanel.setConnectionDialog(), com.neuronrobotics.sdk.ui.AbstractConnectionPanel.setIcon(), com.neuronrobotics.sdk.ui.AbstractConnectionPanel.setTitle(), and com.neuronrobotics.sdk.ui.AbstractConnectionPanel.title.
Member Function Documentation
getConnection()
abstract BowlerAbstractConnection com.neuronrobotics.sdk.ui.AbstractConnectionPanel.getConnection () abstract
Gets the connection.
Returns
the connection
Reimplemented in com.neuronrobotics.sdk.ui.UsbConnectionPanel, com.neuronrobotics.sdk.ui.UDPConnectionPanel, com.neuronrobotics.sdk.ui.TCPConnectionPanel, com.neuronrobotics.sdk.ui.SerialConnectionPanel, and com.neuronrobotics.sdk.ui.BluetoothConnectionPanel.
getConnectionDialog()
ConnectionDialog com.neuronrobotics.sdk.ui.AbstractConnectionPanel.getConnectionDialog ()
Gets the connection dialog.
Returns
the connection dialog
Definition at line 124 of file AbstractConnectionPanel.java.
References com.neuronrobotics.sdk.ui.AbstractConnectionPanel.connectionDialog.
Referenced by com.neuronrobotics.sdk.ui.BluetoothConnectionPanel.refresh(), com.neuronrobotics.sdk.ui.SerialConnectionPanel.refresh(), com.neuronrobotics.sdk.ui.TCPConnectionPanel.refresh(), com.neuronrobotics.sdk.ui.UDPConnectionPanel.refresh(), and com.neuronrobotics.sdk.ui.UsbConnectionPanel.refresh().
getIcon()
ImageIcon com.neuronrobotics.sdk.ui.AbstractConnectionPanel.getIcon ()
Gets the icon.
Returns
the icon
Definition at line 112 of file AbstractConnectionPanel.java.
References com.neuronrobotics.sdk.ui.AbstractConnectionPanel.icon.
getTitle()
String com.neuronrobotics.sdk.ui.AbstractConnectionPanel.getTitle ()
Gets the title.
Returns
the title
Definition at line 94 of file AbstractConnectionPanel.java.
References com.neuronrobotics.sdk.ui.AbstractConnectionPanel.title.
refresh()
abstract void com.neuronrobotics.sdk.ui.AbstractConnectionPanel.refresh () abstract
Refresh.
Reimplemented in com.neuronrobotics.sdk.ui.UsbConnectionPanel, com.neuronrobotics.sdk.ui.UDPConnectionPanel, com.neuronrobotics.sdk.ui.TCPConnectionPanel, com.neuronrobotics.sdk.ui.SerialConnectionPanel, and com.neuronrobotics.sdk.ui.BluetoothConnectionPanel.
setConnectionDialog()
void com.neuronrobotics.sdk.ui.AbstractConnectionPanel.setConnectionDialog (ConnectionDialog connectionDialog)
Sets the connection dialog.
Parameters
connectionDialog the new connection dialog
Definition at line 133 of file AbstractConnectionPanel.java.
References com.neuronrobotics.sdk.ui.AbstractConnectionPanel.connectionDialog.
Referenced by com.neuronrobotics.sdk.ui.AbstractConnectionPanel.AbstractConnectionPanel().
setIcon()
void com.neuronrobotics.sdk.ui.AbstractConnectionPanel.setIcon (ImageIcon icon)
Sets the icon.
Parameters
icon the new icon
Definition at line 103 of file AbstractConnectionPanel.java.
References com.neuronrobotics.sdk.ui.AbstractConnectionPanel.icon.
Referenced by com.neuronrobotics.sdk.ui.AbstractConnectionPanel.AbstractConnectionPanel().
setTitle()
void com.neuronrobotics.sdk.ui.AbstractConnectionPanel.setTitle (String title)
Sets the title.
Parameters
title the new title
Definition at line 85 of file AbstractConnectionPanel.java.
References com.neuronrobotics.sdk.ui.AbstractConnectionPanel.title.
Referenced by com.neuronrobotics.sdk.ui.AbstractConnectionPanel.AbstractConnectionPanel().
Member Data Documentation
connectionDialog
ConnectionDialog com.neuronrobotics.sdk.ui.AbstractConnectionPanel.connectionDialog private
The connection dialog.
Definition at line 38 of file AbstractConnectionPanel.java.
Referenced by com.neuronrobotics.sdk.ui.BluetoothConnectionPanel.BluetoothConnectionPanel(), com.neuronrobotics.sdk.ui.AbstractConnectionPanel.getConnectionDialog(), com.neuronrobotics.sdk.ui.SerialConnectionPanel.SerialConnectionPanel(), com.neuronrobotics.sdk.ui.AbstractConnectionPanel.setConnectionDialog(), com.neuronrobotics.sdk.ui.TCPConnectionPanel.TCPConnectionPanel(), com.neuronrobotics.sdk.ui.UDPConnectionPanel.UDPConnectionPanel(), and com.neuronrobotics.sdk.ui.UsbConnectionPanel.UsbConnectionPanel().
icon
ImageIcon com.neuronrobotics.sdk.ui.AbstractConnectionPanel.icon private
The icon.
Definition at line 35 of file AbstractConnectionPanel.java.
Referenced by com.neuronrobotics.sdk.ui.AbstractConnectionPanel.AbstractConnectionPanel(), com.neuronrobotics.sdk.ui.AbstractConnectionPanel.getIcon(), and com.neuronrobotics.sdk.ui.AbstractConnectionPanel.setIcon().
serialVersionUID
final long com.neuronrobotics.sdk.ui.AbstractConnectionPanel.serialVersionUID = 1L static private
The Constant serialVersionUID.
Definition at line 29 of file AbstractConnectionPanel.java.
title
String com.neuronrobotics.sdk.ui.AbstractConnectionPanel.title private
The title.
Definition at line 32 of file AbstractConnectionPanel.java.
Referenced by com.neuronrobotics.sdk.ui.AbstractConnectionPanel.AbstractConnectionPanel(), com.neuronrobotics.sdk.ui.AbstractConnectionPanel.getTitle(), and com.neuronrobotics.sdk.ui.AbstractConnectionPanel.setTitle().
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/ui/AbstractConnectionPanel.java