BowlerKernel: com.neuronrobotics.sdk.common.BowlerRuntimeException Class Reference
com.neuronrobotics.sdk.common.BowlerRuntimeException Class Reference
Public Member Functions
BowlerRuntimeException (String message)
String toString ()
Private Attributes
String message
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
The Class BowlerRuntimeException.
Definition at line 22 of file BowlerRuntimeException.java.
Constructor & Destructor Documentation
BowlerRuntimeException()
com.neuronrobotics.sdk.common.BowlerRuntimeException.BowlerRuntimeException (String message)
Instantiates a new bowler runtime exception.
Parameters
message the message
Definition at line 35 of file BowlerRuntimeException.java.
References com.neuronrobotics.sdk.common.Log.error(), com.neuronrobotics.sdk.common.BowlerRuntimeException.message, and com.neuronrobotics.sdk.common.BowlerRuntimeException.toString().
Member Function Documentation
toString()
String com.neuronrobotics.sdk.common.BowlerRuntimeException.toString ()
Definition at line 44 of file BowlerRuntimeException.java.
References com.neuronrobotics.sdk.common.BowlerRuntimeException.message.
Referenced by com.neuronrobotics.sdk.common.BowlerRuntimeException.BowlerRuntimeException().
Member Data Documentation
message
String com.neuronrobotics.sdk.common.BowlerRuntimeException.message private
The message.
Definition at line 28 of file BowlerRuntimeException.java.
Referenced by com.neuronrobotics.sdk.common.BowlerRuntimeException.BowlerRuntimeException(), com.neuronrobotics.sdk.dyio.peripherals.DyIOPeripheralException.DyIOPeripheralException(), com.neuronrobotics.sdk.dyio.InvalidChannelOperationException.InvalidChannelOperationException(), and com.neuronrobotics.sdk.common.BowlerRuntimeException.toString().
serialVersionUID
final long com.neuronrobotics.sdk.common.BowlerRuntimeException.serialVersionUID = 1L static private
The Constant serialVersionUID.
Definition at line 25 of file BowlerRuntimeException.java.
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/common/BowlerRuntimeException.java