BowlerKernel: com.neuronrobotics.sdk.ui.TCPConnectionPanel Class Reference
com.neuronrobotics.sdk.ui.TCPConnectionPanel Class Reference
Public Member Functions
TCPConnectionPanel (ConnectionDialog connectionDialog)
BowlerAbstractConnection getConnection ()
void refresh ()
Public Member Functions inherited from com.neuronrobotics.sdk.ui.AbstractConnectionPanel
AbstractConnectionPanel (String title, ImageIcon icon, ConnectionDialog connectionDialog)
AbstractConnectionPanel (String title, ConnectionDialog connectionDialog)
void setTitle (String title)
String getTitle ()
void setIcon (ImageIcon icon)
ImageIcon getIcon ()
ConnectionDialog getConnectionDialog ()
void setConnectionDialog (ConnectionDialog connectionDialog)
Static Public Member Functions
static void setDefaultServer (String server)
Private Attributes
JComboBox connectionCbo = null
JTextField port = new JTextField(8)
Static Private Attributes
static final long serialVersionUID = 1L
static int defaultPortNum = 1866
static String defaultServer = "localhost"
Detailed Description
The Class TCPConnectionPanel.
Definition at line 33 of file TCPConnectionPanel.java.
Constructor & Destructor Documentation
TCPConnectionPanel()
com.neuronrobotics.sdk.ui.TCPConnectionPanel.TCPConnectionPanel (ConnectionDialog connectionDialog)
Instantiates a new TCP connection panel.
Parameters
connectionDialog the connection dialog
Definition at line 59 of file TCPConnectionPanel.java.
References com.neuronrobotics.sdk.ui.TCPConnectionPanel.connectionCbo, com.neuronrobotics.sdk.ui.AbstractConnectionPanel.connectionDialog, com.neuronrobotics.sdk.ui.TCPConnectionPanel.defaultPortNum, com.neuronrobotics.sdk.ui.ConnectionImageIconFactory.getIcon(), and com.neuronrobotics.sdk.ui.TCPConnectionPanel.port.
Member Function Documentation
getConnection()
BowlerAbstractConnection com.neuronrobotics.sdk.ui.TCPConnectionPanel.getConnection ()
Gets the connection.
Returns
the connection
Reimplemented from com.neuronrobotics.sdk.ui.AbstractConnectionPanel.
Definition at line 108 of file TCPConnectionPanel.java.
References com.neuronrobotics.sdk.ui.TCPConnectionPanel.connectionCbo, com.neuronrobotics.sdk.common.Log.info(), and com.neuronrobotics.sdk.ui.TCPConnectionPanel.port.
refresh()
void com.neuronrobotics.sdk.ui.TCPConnectionPanel.refresh ()
Refresh.
Reimplemented from com.neuronrobotics.sdk.ui.AbstractConnectionPanel.
Definition at line 140 of file TCPConnectionPanel.java.
References com.neuronrobotics.sdk.ui.AbstractConnectionPanel.getConnectionDialog().
setDefaultServer()
static void com.neuronrobotics.sdk.ui.TCPConnectionPanel.setDefaultServer (String server) static
Sets the default server.
Parameters
server the new default server
Definition at line 100 of file TCPConnectionPanel.java.
References com.neuronrobotics.sdk.ui.TCPConnectionPanel.defaultServer.
Member Data Documentation
connectionCbo
JComboBox com.neuronrobotics.sdk.ui.TCPConnectionPanel.connectionCbo = null private
The connection cbo.
Definition at line 45 of file TCPConnectionPanel.java.
Referenced by com.neuronrobotics.sdk.ui.TCPConnectionPanel.getConnection(), and com.neuronrobotics.sdk.ui.TCPConnectionPanel.TCPConnectionPanel().
defaultPortNum
int com.neuronrobotics.sdk.ui.TCPConnectionPanel.defaultPortNum = 1866 static private
The default port num.
Definition at line 39 of file TCPConnectionPanel.java.
Referenced by com.neuronrobotics.sdk.ui.TCPConnectionPanel.TCPConnectionPanel().
defaultServer
String com.neuronrobotics.sdk.ui.TCPConnectionPanel.defaultServer = "localhost" static private
The default server.
Definition at line 42 of file TCPConnectionPanel.java.
Referenced by com.neuronrobotics.sdk.ui.TCPConnectionPanel.setDefaultServer().
port
JTextField com.neuronrobotics.sdk.ui.TCPConnectionPanel.port = new JTextField(8) private
The port.
Definition at line 48 of file TCPConnectionPanel.java.
Referenced by com.neuronrobotics.sdk.ui.TCPConnectionPanel.getConnection(), and com.neuronrobotics.sdk.ui.TCPConnectionPanel.TCPConnectionPanel().
serialVersionUID
final long com.neuronrobotics.sdk.ui.TCPConnectionPanel.serialVersionUID = 1L static private
The Constant serialVersionUID.
Definition at line 36 of file TCPConnectionPanel.java.
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/ui/TCPConnectionPanel.java