BowlerKernel: com.neuronrobotics.replicator.driver.delta.DeltaRobotConfig Class Reference
com.neuronrobotics.replicator.driver.delta.DeltaRobotConfig Class Reference
Public Member Functions
DeltaRobotConfig (double e, double f, double re, double rf)
DeltaRobotConfig (DeltaRobotConfig config)
double getE ()
double getF ()
double getRe ()
double getRf ()
Private Member Functions
void setE (double e)
void setF (double f)
void setRe (double re)
void setRf (double rf)
Private Attributes
double e
double f
double re
double rf
Detailed Description
The Class DeltaRobotConfig.
Definition at line 7 of file DeltaRobotConfig.java.
Constructor & Destructor Documentation
DeltaRobotConfig() [1/2]
com.neuronrobotics.replicator.driver.delta.DeltaRobotConfig.DeltaRobotConfig (double e, double f, double re, double rf)
Instantiates a new delta robot config.
Parameters
e the e
f the f
re the re
rf the rf
Definition at line 31 of file DeltaRobotConfig.java.
References com.neuronrobotics.replicator.driver.delta.DeltaRobotConfig.e, com.neuronrobotics.replicator.driver.delta.DeltaRobotConfig.f, com.neuronrobotics.replicator.driver.delta.DeltaRobotConfig.re, com.neuronrobotics.replicator.driver.delta.DeltaRobotConfig.rf, com.neuronrobotics.replicator.driver.delta.DeltaRobotConfig.setE(), com.neuronrobotics.replicator.driver.delta.DeltaRobotConfig.setF(), com.neuronrobotics.replicator.driver.delta.DeltaRobotConfig.setRe(), and com.neuronrobotics.replicator.driver.delta.DeltaRobotConfig.setRf().
DeltaRobotConfig() [2/2]
com.neuronrobotics.replicator.driver.delta.DeltaRobotConfig.DeltaRobotConfig (DeltaRobotConfig config)
Instantiates a new delta robot config.
Parameters
config the config
Definition at line 43 of file DeltaRobotConfig.java.
References com.neuronrobotics.replicator.driver.delta.DeltaRobotConfig.getE(), com.neuronrobotics.replicator.driver.delta.DeltaRobotConfig.getF(), com.neuronrobotics.replicator.driver.delta.DeltaRobotConfig.getRe(), com.neuronrobotics.replicator.driver.delta.DeltaRobotConfig.getRf(), com.neuronrobotics.replicator.driver.delta.DeltaRobotConfig.setE(), com.neuronrobotics.replicator.driver.delta.DeltaRobotConfig.setF(), com.neuronrobotics.replicator.driver.delta.DeltaRobotConfig.setRe(), and com.neuronrobotics.replicator.driver.delta.DeltaRobotConfig.setRf().
Member Function Documentation
getE()
double com.neuronrobotics.replicator.driver.delta.DeltaRobotConfig.getE ()
Gets the e.
Returns
the e
Definition at line 64 of file DeltaRobotConfig.java.
References com.neuronrobotics.replicator.driver.delta.DeltaRobotConfig.e.
Referenced by com.neuronrobotics.replicator.driver.delta.DeltaRobotConfig.DeltaRobotConfig(), and com.neuronrobotics.replicator.driver.delta.DeltaRobotKinematics.getE().
getF()
double com.neuronrobotics.replicator.driver.delta.DeltaRobotConfig.getF ()
Gets the f.
Returns
the f
Definition at line 82 of file DeltaRobotConfig.java.
References com.neuronrobotics.replicator.driver.delta.DeltaRobotConfig.f.
Referenced by com.neuronrobotics.replicator.driver.delta.DeltaRobotConfig.DeltaRobotConfig(), and com.neuronrobotics.replicator.driver.delta.DeltaRobotKinematics.getF().
getRe()
double com.neuronrobotics.replicator.driver.delta.DeltaRobotConfig.getRe ()
Gets the re.
Returns
the re
Definition at line 100 of file DeltaRobotConfig.java.
References com.neuronrobotics.replicator.driver.delta.DeltaRobotConfig.re.
Referenced by com.neuronrobotics.replicator.driver.delta.DeltaRobotConfig.DeltaRobotConfig(), and com.neuronrobotics.replicator.driver.delta.DeltaRobotKinematics.getRe().
getRf()
double com.neuronrobotics.replicator.driver.delta.DeltaRobotConfig.getRf ()
Gets the rf.
Returns
the rf
Definition at line 118 of file DeltaRobotConfig.java.
References com.neuronrobotics.replicator.driver.delta.DeltaRobotConfig.rf.
Referenced by com.neuronrobotics.replicator.driver.delta.DeltaRobotConfig.DeltaRobotConfig(), and com.neuronrobotics.replicator.driver.delta.DeltaRobotKinematics.getRf().
setE()
void com.neuronrobotics.replicator.driver.delta.DeltaRobotConfig.setE (double e) private
Sets the e.
Parameters
e the new e
Definition at line 55 of file DeltaRobotConfig.java.
References com.neuronrobotics.replicator.driver.delta.DeltaRobotConfig.e.
Referenced by com.neuronrobotics.replicator.driver.delta.DeltaRobotConfig.DeltaRobotConfig().
setF()
void com.neuronrobotics.replicator.driver.delta.DeltaRobotConfig.setF (double f) private
Sets the f.
Parameters
f the new f
Definition at line 73 of file DeltaRobotConfig.java.
References com.neuronrobotics.replicator.driver.delta.DeltaRobotConfig.f.
Referenced by com.neuronrobotics.replicator.driver.delta.DeltaRobotConfig.DeltaRobotConfig().
setRe()
void com.neuronrobotics.replicator.driver.delta.DeltaRobotConfig.setRe (double re) private
Sets the re.
Parameters
re the new re
Definition at line 91 of file DeltaRobotConfig.java.
References com.neuronrobotics.replicator.driver.delta.DeltaRobotConfig.re.
Referenced by com.neuronrobotics.replicator.driver.delta.DeltaRobotConfig.DeltaRobotConfig().
setRf()
void com.neuronrobotics.replicator.driver.delta.DeltaRobotConfig.setRf (double rf) private
Sets the rf.
Parameters
rf the new rf
Definition at line 109 of file DeltaRobotConfig.java.
References com.neuronrobotics.replicator.driver.delta.DeltaRobotConfig.rf.
Referenced by com.neuronrobotics.replicator.driver.delta.DeltaRobotConfig.DeltaRobotConfig().
Member Data Documentation
e
double com.neuronrobotics.replicator.driver.delta.DeltaRobotConfig.e private
The e.
Definition at line 12 of file DeltaRobotConfig.java.
Referenced by com.neuronrobotics.replicator.driver.delta.DeltaRobotConfig.DeltaRobotConfig(), com.neuronrobotics.replicator.driver.delta.DeltaRobotConfig.getE(), and com.neuronrobotics.replicator.driver.delta.DeltaRobotConfig.setE().
f
double com.neuronrobotics.replicator.driver.delta.DeltaRobotConfig.f private
The f.
Definition at line 15 of file DeltaRobotConfig.java.
Referenced by com.neuronrobotics.replicator.driver.delta.DeltaRobotConfig.DeltaRobotConfig(), com.neuronrobotics.replicator.driver.delta.DeltaRobotConfig.getF(), and com.neuronrobotics.replicator.driver.delta.DeltaRobotConfig.setF().
re
double com.neuronrobotics.replicator.driver.delta.DeltaRobotConfig.re private
The re.
Definition at line 18 of file DeltaRobotConfig.java.
Referenced by com.neuronrobotics.replicator.driver.delta.DeltaRobotConfig.DeltaRobotConfig(), com.neuronrobotics.replicator.driver.delta.DeltaRobotConfig.getRe(), and com.neuronrobotics.replicator.driver.delta.DeltaRobotConfig.setRe().
rf
double com.neuronrobotics.replicator.driver.delta.DeltaRobotConfig.rf private
The rf.
Definition at line 21 of file DeltaRobotConfig.java.
Referenced by com.neuronrobotics.replicator.driver.delta.DeltaRobotConfig.DeltaRobotConfig(), com.neuronrobotics.replicator.driver.delta.DeltaRobotConfig.getRf(), and com.neuronrobotics.replicator.driver.delta.DeltaRobotConfig.setRf().
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/replicator/driver/delta/DeltaRobotConfig.java