BowlerKernel: com.neuronrobotics.sdk.common.TickToc Class Reference
com.neuronrobotics.sdk.common.TickToc Class Reference
Classes
class Pair
Static Public Member Functions
static void tic (String message)
static void clear ()
static void toc ()
static boolean isEnabled ()
static void setEnabled (boolean enabled)
Static Private Attributes
static final DecimalFormat df = new DecimalFormat(".000")
static boolean enabled =false
static ArrayList< Pair > events = new ArrayList<>()
Detailed Description
Definition at line 6 of file TickToc.java.
Member Function Documentation
clear()
static void com.neuronrobotics.sdk.common.TickToc.clear () static
Definition at line 39 of file TickToc.java.
References com.neuronrobotics.sdk.common.TickToc.events.
Referenced by com.neuronrobotics.sdk.common.TickToc.setEnabled(), and com.neuronrobotics.sdk.common.TickToc.toc().
isEnabled()
static boolean com.neuronrobotics.sdk.common.TickToc.isEnabled () static
Definition at line 58 of file TickToc.java.
References com.neuronrobotics.sdk.common.TickToc.enabled.
Referenced by com.neuronrobotics.sdk.common.TickToc.tic(), and com.neuronrobotics.sdk.common.TickToc.toc().
setEnabled()
static void com.neuronrobotics.sdk.common.TickToc.setEnabled (boolean enabled) static
Definition at line 63 of file TickToc.java.
References com.neuronrobotics.sdk.common.TickToc.clear(), com.neuronrobotics.sdk.common.TickToc.enabled, and com.neuronrobotics.sdk.common.TickToc.tic().
tic()
static void com.neuronrobotics.sdk.common.TickToc.tic (String message) static
Definition at line 32 of file TickToc.java.
References com.neuronrobotics.sdk.common.TickToc.events, and com.neuronrobotics.sdk.common.TickToc.isEnabled().
Referenced by com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR._setDesiredJointSpaceVector(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.setDesiredTaskSpaceTransform(), and com.neuronrobotics.sdk.common.TickToc.setEnabled().
toc()
static void com.neuronrobotics.sdk.common.TickToc.toc () static
Definition at line 42 of file TickToc.java.
References com.neuronrobotics.sdk.common.TickToc.clear(), com.neuronrobotics.sdk.common.TickToc.events, and com.neuronrobotics.sdk.common.TickToc.isEnabled().
Member Data Documentation
df
final DecimalFormat com.neuronrobotics.sdk.common.TickToc.df = new DecimalFormat(".000") static private
Definition at line 7 of file TickToc.java.
enabled
boolean com.neuronrobotics.sdk.common.TickToc.enabled =false static private
Definition at line 8 of file TickToc.java.
Referenced by com.neuronrobotics.sdk.common.TickToc.isEnabled(), and com.neuronrobotics.sdk.common.TickToc.setEnabled().
events
ArrayList<Pair> com.neuronrobotics.sdk.common.TickToc.events = new ArrayList<>() static private
Definition at line 30 of file TickToc.java.
Referenced by com.neuronrobotics.sdk.common.TickToc.clear(), com.neuronrobotics.sdk.common.TickToc.tic(), and com.neuronrobotics.sdk.common.TickToc.toc().
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/common/TickToc.java