BowlerKernel: com.neuronrobotics.replicator.driver.delta.DeltaRobotKinematics Class Reference
com.neuronrobotics.replicator.driver.delta.DeltaRobotKinematics Class Reference
Public Member Functions
DeltaRobotKinematics (DeltaRobotConfig config)
TransformNR delta_calcForward (double[] input)
double[] delta_calcInverse (TransformNR input)
double getE ()
double getF ()
double getRe ()
double getRf ()
Private Member Functions
double delta_calcAngleYZ (double x0, double y0, double z0)
Private Attributes
double sqrt3 = Math.sqrt(3.0)
double pi = Math.PI
double sin120 = sqrt3/2.0
double cos120 = -0.5
double tan60 = sqrt3
double sin30 = 0.5
double tan30 = 1/sqrt3
Detailed Description
The Class DeltaRobotKinematics.
Definition at line 10 of file DeltaRobotKinematics.java.
Constructor & Destructor Documentation
DeltaRobotKinematics()
com.neuronrobotics.replicator.driver.delta.DeltaRobotKinematics.DeltaRobotKinematics (DeltaRobotConfig config)
All units in milimeters.
Parameters
config the config
Definition at line 22 of file DeltaRobotKinematics.java.
Member Function Documentation
delta_calcAngleYZ()
double com.neuronrobotics.replicator.driver.delta.DeltaRobotKinematics.delta_calcAngleYZ (double x0, double y0, double z0) private
Delta_calc angle yz.
Parameters
x0 the x0
y0 the y0
z0 the z0
Returns
the double
Definition at line 118 of file DeltaRobotKinematics.java.
References com.neuronrobotics.replicator.driver.delta.DeltaRobotKinematics.getE(), com.neuronrobotics.replicator.driver.delta.DeltaRobotKinematics.getF(), com.neuronrobotics.replicator.driver.delta.DeltaRobotKinematics.getRe(), and com.neuronrobotics.replicator.driver.delta.DeltaRobotKinematics.getRf().
Referenced by com.neuronrobotics.replicator.driver.delta.DeltaRobotKinematics.delta_calcInverse().
delta_calcForward()
TransformNR com.neuronrobotics.replicator.driver.delta.DeltaRobotKinematics.delta_calcForward (double[] input)
Delta_calc forward.
Parameters
input the input
Returns
the transform nr
Definition at line 57 of file DeltaRobotKinematics.java.
References com.neuronrobotics.replicator.driver.delta.DeltaRobotKinematics.getE(), com.neuronrobotics.replicator.driver.delta.DeltaRobotKinematics.getF(), com.neuronrobotics.replicator.driver.delta.DeltaRobotKinematics.getRe(), com.neuronrobotics.replicator.driver.delta.DeltaRobotKinematics.getRf(), com.neuronrobotics.replicator.driver.delta.DeltaRobotKinematics.sin30, com.neuronrobotics.replicator.driver.delta.DeltaRobotKinematics.tan30, and com.neuronrobotics.replicator.driver.delta.DeltaRobotKinematics.tan60.
delta_calcInverse()
double [] com.neuronrobotics.replicator.driver.delta.DeltaRobotKinematics.delta_calcInverse (TransformNR input)
Delta_calc inverse.
Parameters
input the input
Returns
the double[]
Definition at line 145 of file DeltaRobotKinematics.java.
References com.neuronrobotics.replicator.driver.delta.DeltaRobotKinematics.cos120, com.neuronrobotics.replicator.driver.delta.DeltaRobotKinematics.delta_calcAngleYZ(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getX(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getY(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getZ(), and com.neuronrobotics.replicator.driver.delta.DeltaRobotKinematics.sin120.
getE()
double com.neuronrobotics.replicator.driver.delta.DeltaRobotKinematics.getE ()
Gets the e.
Returns
the e
Definition at line 165 of file DeltaRobotKinematics.java.
References com.neuronrobotics.replicator.driver.delta.DeltaRobotConfig.getE().
Referenced by com.neuronrobotics.replicator.driver.delta.DeltaRobotKinematics.delta_calcAngleYZ(), and com.neuronrobotics.replicator.driver.delta.DeltaRobotKinematics.delta_calcForward().
getF()
double com.neuronrobotics.replicator.driver.delta.DeltaRobotKinematics.getF ()
Gets the f.
Returns
the f
Definition at line 174 of file DeltaRobotKinematics.java.
References com.neuronrobotics.replicator.driver.delta.DeltaRobotConfig.getF().
Referenced by com.neuronrobotics.replicator.driver.delta.DeltaRobotKinematics.delta_calcAngleYZ(), and com.neuronrobotics.replicator.driver.delta.DeltaRobotKinematics.delta_calcForward().
getRe()
double com.neuronrobotics.replicator.driver.delta.DeltaRobotKinematics.getRe ()
Gets the re.
Returns
the re
Definition at line 183 of file DeltaRobotKinematics.java.
References com.neuronrobotics.replicator.driver.delta.DeltaRobotConfig.getRe().
Referenced by com.neuronrobotics.replicator.driver.delta.DeltaRobotKinematics.delta_calcAngleYZ(), and com.neuronrobotics.replicator.driver.delta.DeltaRobotKinematics.delta_calcForward().
getRf()
double com.neuronrobotics.replicator.driver.delta.DeltaRobotKinematics.getRf ()
Gets the rf.
Returns
the rf
Definition at line 192 of file DeltaRobotKinematics.java.
References com.neuronrobotics.replicator.driver.delta.DeltaRobotConfig.getRf().
Referenced by com.neuronrobotics.replicator.driver.delta.DeltaRobotKinematics.delta_calcAngleYZ(), and com.neuronrobotics.replicator.driver.delta.DeltaRobotKinematics.delta_calcForward().
Member Data Documentation
cos120
double com.neuronrobotics.replicator.driver.delta.DeltaRobotKinematics.cos120 = -0.5 private
The cos120.
Definition at line 38 of file DeltaRobotKinematics.java.
Referenced by com.neuronrobotics.replicator.driver.delta.DeltaRobotKinematics.delta_calcInverse().
pi
double com.neuronrobotics.replicator.driver.delta.DeltaRobotKinematics.pi = Math.PI private
The pi.
Definition at line 32 of file DeltaRobotKinematics.java.
sin120
double com.neuronrobotics.replicator.driver.delta.DeltaRobotKinematics.sin120 = sqrt3/2.0 private
The sin120.
Definition at line 35 of file DeltaRobotKinematics.java.
Referenced by com.neuronrobotics.replicator.driver.delta.DeltaRobotKinematics.delta_calcInverse().
sin30
double com.neuronrobotics.replicator.driver.delta.DeltaRobotKinematics.sin30 = 0.5 private
The sin30.
Definition at line 44 of file DeltaRobotKinematics.java.
Referenced by com.neuronrobotics.replicator.driver.delta.DeltaRobotKinematics.delta_calcForward().
sqrt3
double com.neuronrobotics.replicator.driver.delta.DeltaRobotKinematics.sqrt3 = Math.sqrt(3.0) private
The sqrt3.
Definition at line 29 of file DeltaRobotKinematics.java.
tan30
double com.neuronrobotics.replicator.driver.delta.DeltaRobotKinematics.tan30 = 1/sqrt3 private
The tan30.
Definition at line 47 of file DeltaRobotKinematics.java.
Referenced by com.neuronrobotics.replicator.driver.delta.DeltaRobotKinematics.delta_calcForward().
tan60
double com.neuronrobotics.replicator.driver.delta.DeltaRobotKinematics.tan60 = sqrt3 private
The tan60.
Definition at line 41 of file DeltaRobotKinematics.java.
Referenced by com.neuronrobotics.replicator.driver.delta.DeltaRobotKinematics.delta_calcForward().
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/replicator/driver/delta/DeltaRobotKinematics.java