BowlerKernel: eu.mihosoft.vrl.v3d.parametrics.Parameter Class Reference
eu.mihosoft.vrl.v3d.parametrics.Parameter Class Reference
Public Member Functions
Parameter ()
String getName ()
void setValue (Long newVal)
Long getValue ()
ArrayList< String > getOptions ()
String getStrValue ()
void setStrValue (String newValue)
void setMM (double newVal)
void setMicrons (long newVal)
double getMM ()
double getMicrons ()
Protected Member Functions
void setup (String key, Long defaultValue, ArrayList< String > options)
void setup (String key, String defaultValue, ArrayList< String > options)
Private Attributes
String name =null
final ArrayList< String > options =new ArrayList<String>()
Long value =null
String strValue =null
Detailed Description
Definition at line 5 of file Parameter.java.
Constructor & Destructor Documentation
Parameter()
eu.mihosoft.vrl.v3d.parametrics.Parameter.Parameter ()
Definition at line 11 of file Parameter.java.
Member Function Documentation
getMicrons()
double eu.mihosoft.vrl.v3d.parametrics.Parameter.getMicrons ()
Definition at line 97 of file Parameter.java.
References eu.mihosoft.vrl.v3d.parametrics.Parameter.getValue().
getMM()
double eu.mihosoft.vrl.v3d.parametrics.Parameter.getMM ()
Definition at line 94 of file Parameter.java.
References eu.mihosoft.vrl.v3d.parametrics.Parameter.getValue().
Referenced by eu.mihosoft.vrl.v3d.Cube.Cube(), eu.mihosoft.vrl.v3d.Cylinder.Cylinder(), eu.mihosoft.vrl.v3d.RoundedCube.RoundedCube(), and eu.mihosoft.vrl.v3d.Sphere.Sphere().
getName()
String eu.mihosoft.vrl.v3d.parametrics.Parameter.getName ()
Definition at line 49 of file Parameter.java.
References eu.mihosoft.vrl.v3d.parametrics.Parameter.name.
Referenced by eu.mihosoft.vrl.v3d.CSG.setParameter().
getOptions()
ArrayList<String> eu.mihosoft.vrl.v3d.parametrics.Parameter.getOptions ()
Definition at line 67 of file Parameter.java.
References eu.mihosoft.vrl.v3d.parametrics.Parameter.options.
getStrValue()
String eu.mihosoft.vrl.v3d.parametrics.Parameter.getStrValue ()
Definition at line 71 of file Parameter.java.
References eu.mihosoft.vrl.v3d.parametrics.Parameter.strValue.
Referenced by eu.mihosoft.vrl.v3d.parametrics.StringParameter.getString(), and eu.mihosoft.vrl.v3d.parametrics.Parameter.setup().
getValue()
Long eu.mihosoft.vrl.v3d.parametrics.Parameter.getValue ()
Definition at line 64 of file Parameter.java.
References eu.mihosoft.vrl.v3d.parametrics.Parameter.value.
Referenced by eu.mihosoft.vrl.v3d.parametrics.Parameter.getMicrons(), eu.mihosoft.vrl.v3d.parametrics.Parameter.getMM(), and eu.mihosoft.vrl.v3d.parametrics.Parameter.setup().
setMicrons()
void eu.mihosoft.vrl.v3d.parametrics.Parameter.setMicrons (long newVal)
Definition at line 90 of file Parameter.java.
References eu.mihosoft.vrl.v3d.parametrics.Parameter.setValue().
setMM()
void eu.mihosoft.vrl.v3d.parametrics.Parameter.setMM (double newVal)
Definition at line 87 of file Parameter.java.
References eu.mihosoft.vrl.v3d.parametrics.Parameter.setValue().
Referenced by com.neuronrobotics.bowlerstudio.vitamins.Vitamins.get().
setStrValue()
void eu.mihosoft.vrl.v3d.parametrics.Parameter.setStrValue (String newValue)
Definition at line 75 of file Parameter.java.
References eu.mihosoft.vrl.v3d.parametrics.CSGDatabase.getParamListeners(), eu.mihosoft.vrl.v3d.parametrics.Parameter.name, and eu.mihosoft.vrl.v3d.parametrics.Parameter.strValue.
Referenced by com.neuronrobotics.bowlerstudio.vitamins.Vitamins.get(), and eu.mihosoft.vrl.v3d.parametrics.StringParameter.setString().
setup() [1/2]
void eu.mihosoft.vrl.v3d.parametrics.Parameter.setup (String key, Long defaultValue, ArrayList< String > options) protected
Definition at line 13 of file Parameter.java.
References eu.mihosoft.vrl.v3d.parametrics.CSGDatabase.addParameterListener(), eu.mihosoft.vrl.v3d.parametrics.CSGDatabase.get(), eu.mihosoft.vrl.v3d.parametrics.Parameter.getValue(), eu.mihosoft.vrl.v3d.parametrics.Parameter.name, eu.mihosoft.vrl.v3d.parametrics.Parameter.options, eu.mihosoft.vrl.v3d.parametrics.CSGDatabase.set(), eu.mihosoft.vrl.v3d.parametrics.Parameter.setValue(), and eu.mihosoft.vrl.v3d.parametrics.Parameter.value.
Referenced by eu.mihosoft.vrl.v3d.parametrics.LengthParameter.LengthParameter(), and eu.mihosoft.vrl.v3d.parametrics.StringParameter.StringParameter().
setup() [2/2]
void eu.mihosoft.vrl.v3d.parametrics.Parameter.setup (String key, String defaultValue, ArrayList< String > options) protected
Definition at line 31 of file Parameter.java.
References eu.mihosoft.vrl.v3d.parametrics.CSGDatabase.addParameterListener(), eu.mihosoft.vrl.v3d.parametrics.CSGDatabase.get(), eu.mihosoft.vrl.v3d.parametrics.Parameter.getStrValue(), eu.mihosoft.vrl.v3d.parametrics.Parameter.name, eu.mihosoft.vrl.v3d.parametrics.Parameter.options, eu.mihosoft.vrl.v3d.parametrics.CSGDatabase.set(), and eu.mihosoft.vrl.v3d.parametrics.Parameter.strValue.
setValue()
void eu.mihosoft.vrl.v3d.parametrics.Parameter.setValue (Long newVal)
Definition at line 53 of file Parameter.java.
References eu.mihosoft.vrl.v3d.parametrics.CSGDatabase.getParamListeners(), eu.mihosoft.vrl.v3d.parametrics.Parameter.name, eu.mihosoft.vrl.v3d.parametrics.IParameterChanged.parameterChanged(), and eu.mihosoft.vrl.v3d.parametrics.Parameter.value.
Referenced by eu.mihosoft.vrl.v3d.parametrics.Parameter.setMicrons(), eu.mihosoft.vrl.v3d.parametrics.Parameter.setMM(), eu.mihosoft.vrl.v3d.CSG.setParameter(), eu.mihosoft.vrl.v3d.CSG.setParameterIfNull(), and eu.mihosoft.vrl.v3d.parametrics.Parameter.setup().
Member Data Documentation
name
String eu.mihosoft.vrl.v3d.parametrics.Parameter.name =null private
Definition at line 7 of file Parameter.java.
Referenced by eu.mihosoft.vrl.v3d.parametrics.Parameter.getName(), eu.mihosoft.vrl.v3d.parametrics.Parameter.setStrValue(), eu.mihosoft.vrl.v3d.parametrics.Parameter.setup(), and eu.mihosoft.vrl.v3d.parametrics.Parameter.setValue().
options
final ArrayList<String> eu.mihosoft.vrl.v3d.parametrics.Parameter.options =new ArrayList<String>() private
Definition at line 8 of file Parameter.java.
Referenced by eu.mihosoft.vrl.v3d.parametrics.Parameter.getOptions(), eu.mihosoft.vrl.v3d.parametrics.LengthParameter.LengthParameter(), eu.mihosoft.vrl.v3d.parametrics.Parameter.setup(), and eu.mihosoft.vrl.v3d.parametrics.StringParameter.StringParameter().
strValue
String eu.mihosoft.vrl.v3d.parametrics.Parameter.strValue =null private
Definition at line 10 of file Parameter.java.
Referenced by eu.mihosoft.vrl.v3d.parametrics.Parameter.getStrValue(), eu.mihosoft.vrl.v3d.parametrics.Parameter.setStrValue(), and eu.mihosoft.vrl.v3d.parametrics.Parameter.setup().
value
Long eu.mihosoft.vrl.v3d.parametrics.Parameter.value =null private
Definition at line 9 of file Parameter.java.
Referenced by eu.mihosoft.vrl.v3d.parametrics.Parameter.getValue(), eu.mihosoft.vrl.v3d.parametrics.Parameter.setup(), and eu.mihosoft.vrl.v3d.parametrics.Parameter.setValue().
The documentation for this class was generated from the following file:
JCSG/src/main/java/eu/mihosoft/vrl/v3d/parametrics/Parameter.java