BowlerKernel: com.neuronrobotics.sdk.common.NonBowlerDevice Class Reference
com.neuronrobotics.sdk.common.NonBowlerDevice Class Reference abstract
Public Member Functions
abstract void disconnectDeviceImp ()
abstract boolean connectDeviceImp ()
abstract ArrayList< String > getNamespacesImp ()
boolean connect ()
boolean isAvailable () throws InvalidConnectionException
void disconnect ()
void onAsyncResponse (BowlerDatagram data)
ArrayList< String > getNamespaces ()
Public Member Functions inherited from com.neuronrobotics.sdk.common.BowlerAbstractDevice
void addConnectionEventListener (final IDeviceConnectionEventListener l)
void removeConnectionEventListener (IDeviceConnectionEventListener l)
void setConnection (BowlerAbstractConnection connection)
BowlerAbstractConnection getConnection ()
void setAddress (MACAddress address)
MACAddress getAddress ()
BowlerDatagram send (BowlerAbstractCommand command) throws NoConnectionAvailableException, InvalidResponseException
BowlerDatagram send (BowlerAbstractCommand command, int retry) throws NoConnectionAvailableException, InvalidResponseException
Object[] send (String namespace, BowlerMethod method, String rpcString, Object[] arguments, int retry) throws DeviceConnectionException
Object[] send (String namespace, BowlerMethod method, String rpcString, Object[] arguments) throws DeviceConnectionException
boolean ping ()
boolean ping (boolean switchParser)
ArrayList< ByteList > getRevisions ()
boolean hasNamespace (String string)
void startHeartBeat ()
void startHeartBeat (long msHeartBeatTime)
void stopHeartBeat ()
void setThreadedUpstreamPackets (boolean up)
ArrayList< RpcEncapsulation > getRpcList (String namespace)
void loadRpcList ()
void onAllResponse (BowlerDatagram data)
boolean isKeepAlive ()
void setKeepAlive (boolean keepAlive)
long getLastPacketTime ()
void setLastPacketTime (long lastPacketTime)
String getScriptingName ()
void setScriptingName (String scriptingName)
ArrayList< IDeviceConnectionEventListener > getDisconnectListeners ()
Additional Inherited Members
Protected Member Functions inherited from com.neuronrobotics.sdk.common.BowlerAbstractDevice
void fireDisconnectEvent ()
void fireConnectEvent ()
Detailed Description
The Class NonBowlerDevice.
Definition at line 11 of file NonBowlerDevice.java.
Member Function Documentation
connect()
boolean com.neuronrobotics.sdk.common.NonBowlerDevice.connect ()
This method tells the connection object to start and connects the up and down streams pipes. Once this method is called and returns without exception, the device is ready to communicate with
Returns
true, if successful
Exceptions
InvalidConnectionException the invalid connection exception
Reimplemented from com.neuronrobotics.sdk.common.BowlerAbstractDevice.
Reimplemented in com.neuronrobotics.imageprovider.AbstractImageProvider, and com.neuronrobotics.sdk.addons.kinematics.MobileBase.
Definition at line 37 of file NonBowlerDevice.java.
References com.neuronrobotics.sdk.common.NonBowlerDevice.connectDeviceImp(), com.neuronrobotics.sdk.common.BowlerAbstractDevice.fireConnectEvent(), and com.neuronrobotics.sdk.common.NonBowlerDevice.isAvailable().
Referenced by com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.main(), and com.neuronrobotics.bowlerstudio.opencv.OpenCVManager.OpenCVManager().
connectDeviceImp()
abstract boolean com.neuronrobotics.sdk.common.NonBowlerDevice.connectDeviceImp () abstract
Connect device imp.
Returns
true, if successful
Reimplemented in com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice, com.neuronrobotics.imageprovider.URLImageProvider, com.neuronrobotics.imageprovider.StaticFileProvider, com.neuronrobotics.bowlerstudio.opencv.OpenCVManager, com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory, com.neuronrobotics.sdk.common.DMDevice, com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice, and com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.
Referenced by com.neuronrobotics.sdk.common.NonBowlerDevice.connect().
disconnect()
void com.neuronrobotics.sdk.common.NonBowlerDevice.disconnect ()
This method tells the connection object to disconnect its pipes and close out the connection. Once this is called, it is safe to remove your device.
Reimplemented from com.neuronrobotics.sdk.common.BowlerAbstractDevice.
Definition at line 58 of file NonBowlerDevice.java.
References com.neuronrobotics.sdk.common.NonBowlerDevice.disconnectDeviceImp(), and com.neuronrobotics.sdk.common.BowlerAbstractDevice.fireDisconnectEvent().
Referenced by com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.connectDeviceImp(), com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.DHParameterKinematics(), and com.neuronrobotics.bowlerstudio.BowlerKernel.processReturnedObjects().
disconnectDeviceImp()
abstract void com.neuronrobotics.sdk.common.NonBowlerDevice.disconnectDeviceImp () abstract
This method tells the connection object to disconnect its pipes and close out the connection. Once this is called, it is safe to remove your device.
Reimplemented in com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice, com.neuronrobotics.imageprovider.URLImageProvider, com.neuronrobotics.imageprovider.StaticFileProvider, com.neuronrobotics.bowlerstudio.opencv.OpenCVManager, com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory, com.neuronrobotics.sdk.common.DMDevice, com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice, and com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.
Referenced by com.neuronrobotics.sdk.common.NonBowlerDevice.disconnect().
getNamespaces()
ArrayList<String> com.neuronrobotics.sdk.common.NonBowlerDevice.getNamespaces ()
Get all the namespaces.
Returns
the namespaces
Reimplemented from com.neuronrobotics.sdk.common.BowlerAbstractDevice.
Definition at line 79 of file NonBowlerDevice.java.
References com.neuronrobotics.sdk.common.NonBowlerDevice.getNamespacesImp().
getNamespacesImp()
abstract ArrayList<String> com.neuronrobotics.sdk.common.NonBowlerDevice.getNamespacesImp () abstract
Gets the namespaces imp.
Returns
the namespaces imp
Reimplemented in com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice, com.neuronrobotics.imageprovider.URLImageProvider, com.neuronrobotics.imageprovider.StaticFileProvider, com.neuronrobotics.bowlerstudio.opencv.OpenCVManager, com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory, com.neuronrobotics.sdk.common.DMDevice, com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice, and com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.
Referenced by com.neuronrobotics.sdk.common.NonBowlerDevice.getNamespaces().
isAvailable()
boolean com.neuronrobotics.sdk.common.NonBowlerDevice.isAvailable () throws InvalidConnectionException
Determines if the device is available.
Returns
true if the device is avaiable, false if it is not
Exceptions
InvalidConnectionException the invalid connection exception
Reimplemented from com.neuronrobotics.sdk.common.BowlerAbstractDevice.
Reimplemented in com.neuronrobotics.imageprovider.AbstractImageProvider, and com.neuronrobotics.sdk.common.DMDevice.
Definition at line 50 of file NonBowlerDevice.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.MobileBase.connect(), com.neuronrobotics.sdk.common.NonBowlerDevice.connect(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.generateBody(), com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.main(), and com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.run().
onAsyncResponse()
void com.neuronrobotics.sdk.common.NonBowlerDevice.onAsyncResponse (BowlerDatagram data)
On async response.
Parameters
data the data
Implements com.neuronrobotics.sdk.common.IBowlerDatagramListener.
Reimplemented in com.neuronrobotics.imageprovider.AbstractImageProvider.
Definition at line 68 of file NonBowlerDevice.java.
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/common/NonBowlerDevice.java