BowlerKernel: com.neuronrobotics.sdk.addons.kinematics.xml.XmlFactory Class Reference
com.neuronrobotics.sdk.addons.kinematics.xml.XmlFactory Class Reference
Static Public Member Functions
static InputStream getDefaultConfigurationStream (String file)
static Document getAllNodesDocument (InputStream config)
static NodeList getAllNodesFromTag (String sTag, InputStream config)
static String getTagValue (String sTag, Element eElement)
static Double getTagValueDouble (String sTag, Element eElement)
Detailed Description
A factory for creating Xml objects.
Definition at line 19 of file XmlFactory.java.
Member Function Documentation
getAllNodesDocument()
static Document com.neuronrobotics.sdk.addons.kinematics.xml.XmlFactory.getAllNodesDocument (InputStream config) static
Gets the all nodes document.
Parameters
config the config
Returns
the all nodes document
Definition at line 37 of file XmlFactory.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.AbstractKinematicsNR(), com.neuronrobotics.sdk.addons.kinematics.xml.XmlFactory.getAllNodesFromTag(), and com.neuronrobotics.sdk.addons.kinematics.MobileBase.MobileBase().
getAllNodesFromTag()
static NodeList com.neuronrobotics.sdk.addons.kinematics.xml.XmlFactory.getAllNodesFromTag (String sTag, InputStream config) static
Gets the all nodes from tag.
Parameters
sTag the s tag
config the config
Returns
the all nodes from tag
Definition at line 64 of file XmlFactory.java.
References com.neuronrobotics.sdk.addons.kinematics.xml.XmlFactory.getAllNodesDocument().
getDefaultConfigurationStream()
static InputStream com.neuronrobotics.sdk.addons.kinematics.xml.XmlFactory.getDefaultConfigurationStream (String file) static
Gets the default configuration stream.
Parameters
file the file
Returns
the default configuration stream
Definition at line 27 of file XmlFactory.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.DHParameterKinematics(), and com.neuronrobotics.sdk.addons.kinematics.GenericKinematicsModelNR.GenericKinematicsModelNR().
getTagValue()
static String com.neuronrobotics.sdk.addons.kinematics.xml.XmlFactory.getTagValue (String sTag, Element eElement) static
Gets the tag value.
Parameters
sTag the s tag
eElement the e element
Returns
the tag value
Definition at line 77 of file XmlFactory.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getCode(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getVitamins(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.getVitamins(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.LinkConfiguration(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.loadConfig(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.loadConfigs(), and com.neuronrobotics.sdk.addons.kinematics.MobileBase.loadTransform().
getTagValueDouble()
static Double com.neuronrobotics.sdk.addons.kinematics.xml.XmlFactory.getTagValueDouble (String sTag, Element eElement) static
Gets the tag value double.
Parameters
sTag the s tag
eElement the e element
Returns
the tag value double
Definition at line 92 of file XmlFactory.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.DHLink.DHLink().
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/addons/kinematics/xml/XmlFactory.java