BowlerKernel: eu.mihosoft.vrl.v3d.ext.openjfx.importers.SmoothingGroups Class Reference
eu.mihosoft.vrl.v3d.ext.openjfx.importers.SmoothingGroups Class Reference
Classes
class Edge
Public Member Functions
SmoothingGroups (int faces[][], int[][] faceNormals, float[] normals)
Static Public Member Functions
static int[] calcSmoothGroups (int[][] faces, int[][] faceNormals, float[] normals)
static int[] calcSmoothGroups (TriangleMesh mesh, int[] flatFaces, int[] flatFaceNormals, float[] normals)
Private Member Functions
List< Integer > getNextConnectedComponent (Map< Edge, List< Integer >> adjacentFaces)
boolean hasNextConnectedComponent ()
void computeFaceEdges ()
Map< Edge, List< Integer > > getAdjacentFaces ()
Map< Edge, List< Integer > > getSmoothEdges (Map< Edge, List< Integer >> adjacentFaces)
List< List< Integer > > calcConnComponents (Map< Edge, List< Integer >> smoothEdges)
int[] generateSmGroups (List< List< Integer >> groups)
int[] calcSmoothGroups ()
Static Private Member Functions
static boolean isNormalsEqual (Vector3f n1, Vector3f n2)
Private Attributes
BitSet visited
Queue< Integer > q
int[][] faces
int[][] faceNormals
float[] normals
Edge[][] faceEdges
Static Private Attributes
static final float normalAngle = 0.9994f
Detailed Description
Util for converting Normals to Smoothing Groups.
Definition at line 51 of file SmoothingGroups.java.
Constructor & Destructor Documentation
SmoothingGroups()
eu.mihosoft.vrl.v3d.ext.openjfx.importers.SmoothingGroups.SmoothingGroups (int faces[][], int faceNormals[][], float[] normals)
Instantiates a new smoothing groups.
Parameters
faces the faces
faceNormals the face normals
normals the normals
Definition at line 78 of file SmoothingGroups.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.SmoothingGroups.faceNormals, eu.mihosoft.vrl.v3d.ext.openjfx.importers.SmoothingGroups.faces, eu.mihosoft.vrl.v3d.ext.openjfx.importers.SmoothingGroups.normals, eu.mihosoft.vrl.v3d.ext.openjfx.importers.SmoothingGroups.q, and eu.mihosoft.vrl.v3d.ext.openjfx.importers.SmoothingGroups.visited.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.SmoothingGroups.calcSmoothGroups().
Member Function Documentation
calcConnComponents()
List<List<Integer> > eu.mihosoft.vrl.v3d.ext.openjfx.importers.SmoothingGroups.calcConnComponents (Map< Edge, List< Integer >> smoothEdges) private
Calc conn components.
Parameters
smoothEdges the smooth edges
Returns
the list
Definition at line 252 of file SmoothingGroups.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.SmoothingGroups.getNextConnectedComponent(), and eu.mihosoft.vrl.v3d.ext.openjfx.importers.SmoothingGroups.hasNextConnectedComponent().
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.SmoothingGroups.calcSmoothGroups().
calcSmoothGroups() [1/3]
int [] eu.mihosoft.vrl.v3d.ext.openjfx.importers.SmoothingGroups.calcSmoothGroups () private
Calc smooth groups.
Returns
the int[]
Definition at line 293 of file SmoothingGroups.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.SmoothingGroups.calcConnComponents(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.SmoothingGroups.computeFaceEdges(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.SmoothingGroups.generateSmGroups(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.SmoothingGroups.getAdjacentFaces(), and eu.mihosoft.vrl.v3d.ext.openjfx.importers.SmoothingGroups.getSmoothEdges().
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.addMesh(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.addMesh(), and eu.mihosoft.vrl.v3d.ext.openjfx.importers.SmoothingGroups.calcSmoothGroups().
calcSmoothGroups() [2/3]
static int [] eu.mihosoft.vrl.v3d.ext.openjfx.importers.SmoothingGroups.calcSmoothGroups (int faces[][], int faceNormals[][], float[] normals) static
Calculates smoothing groups for data formatted in PolygonMesh style.
Parameters
faces An array of faces, where each face consists of an array of vertex and uv indices
faceNormals An array of face normals, where each face normal consists of an array of normal indices
normals The array of normals
Returns
An array of smooth groups, where the length of the array is the number of faces
Definition at line 387 of file SmoothingGroups.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.SmoothingGroups.calcSmoothGroups(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.SmoothingGroups.faceNormals, eu.mihosoft.vrl.v3d.ext.openjfx.importers.SmoothingGroups.faces, eu.mihosoft.vrl.v3d.ext.openjfx.importers.SmoothingGroups.normals, and eu.mihosoft.vrl.v3d.ext.openjfx.importers.SmoothingGroups.SmoothingGroups().
calcSmoothGroups() [3/3]
static int [] eu.mihosoft.vrl.v3d.ext.openjfx.importers.SmoothingGroups.calcSmoothGroups (TriangleMesh mesh, int[] flatFaces, int[] flatFaceNormals, float[] normals) static
Calculates smoothing groups for data formatted in TriangleMesh style.
Parameters
mesh the mesh
flatFaces An array of faces, where each triangle face is represented by 6 (vertex and uv) indices
flatFaceNormals An array of face normals, where each triangle face is represented by 3 normal indices
normals The array of normals
Returns
An array of smooth groups, where the length of the array is the number of faces
Definition at line 401 of file SmoothingGroups.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.SmoothingGroups.calcSmoothGroups(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.SmoothingGroups.faceNormals, eu.mihosoft.vrl.v3d.ext.openjfx.importers.SmoothingGroups.faces, eu.mihosoft.vrl.v3d.ext.openjfx.importers.SmoothingGroups.normals, and eu.mihosoft.vrl.v3d.ext.openjfx.importers.SmoothingGroups.SmoothingGroups().
computeFaceEdges()
void eu.mihosoft.vrl.v3d.ext.openjfx.importers.SmoothingGroups.computeFaceEdges () private
Compute face edges.
Definition at line 132 of file SmoothingGroups.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.SmoothingGroups.faceEdges, eu.mihosoft.vrl.v3d.ext.openjfx.importers.SmoothingGroups.faceNormals, and eu.mihosoft.vrl.v3d.ext.openjfx.importers.SmoothingGroups.faces.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.SmoothingGroups.calcSmoothGroups().
generateSmGroups()
int [] eu.mihosoft.vrl.v3d.ext.openjfx.importers.SmoothingGroups.generateSmGroups (List< List< Integer >> groups) private
Generate sm groups.
Parameters
groups the groups
Returns
the int[]
Definition at line 268 of file SmoothingGroups.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.SmoothingGroups.faceNormals.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.SmoothingGroups.calcSmoothGroups().
getAdjacentFaces()
Map<Edge, List<Integer> > eu.mihosoft.vrl.v3d.ext.openjfx.importers.SmoothingGroups.getAdjacentFaces () private
Gets the adjacent faces.
Returns
the adjacent faces
Definition at line 157 of file SmoothingGroups.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.SmoothingGroups.faceEdges.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.SmoothingGroups.calcSmoothGroups().
getNextConnectedComponent()
List<Integer> eu.mihosoft.vrl.v3d.ext.openjfx.importers.SmoothingGroups.getNextConnectedComponent (Map< Edge, List< Integer >> adjacentFaces) private
Gets the next connected component.
Parameters
adjacentFaces the adjacent faces
Returns
the next connected component
Definition at line 95 of file SmoothingGroups.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.SmoothingGroups.faceEdges, eu.mihosoft.vrl.v3d.ext.openjfx.importers.SmoothingGroups.faces, eu.mihosoft.vrl.v3d.ext.openjfx.importers.SmoothingGroups.q, and eu.mihosoft.vrl.v3d.ext.openjfx.importers.SmoothingGroups.visited.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.SmoothingGroups.calcConnComponents().
getSmoothEdges()
Map<Edge, List<Integer> > eu.mihosoft.vrl.v3d.ext.openjfx.importers.SmoothingGroups.getSmoothEdges (Map< Edge, List< Integer >> adjacentFaces) private
Gets the smooth edges.
Parameters
adjacentFaces the adjacent faces
Returns
the smooth edges
Definition at line 216 of file SmoothingGroups.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.SmoothingGroups.faceEdges.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.SmoothingGroups.calcSmoothGroups().
hasNextConnectedComponent()
boolean eu.mihosoft.vrl.v3d.ext.openjfx.importers.SmoothingGroups.hasNextConnectedComponent () private
Checks for next connected component.
Returns
true, if successful
Definition at line 125 of file SmoothingGroups.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.SmoothingGroups.calcConnComponents().
isNormalsEqual()
static boolean eu.mihosoft.vrl.v3d.ext.openjfx.importers.SmoothingGroups.isNormalsEqual (Vector3f n1, Vector3f n2) static private
Checks if is normals equal.
Parameters
n1 the n1
n2 the n2
Returns
true, if is normals equal
Definition at line 197 of file SmoothingGroups.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.SmoothingGroups.normalAngle.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.SmoothingGroups.Edge.isSmooth().
Member Data Documentation
faceEdges
Edge [][] eu.mihosoft.vrl.v3d.ext.openjfx.importers.SmoothingGroups.faceEdges private
The face edges.
Definition at line 69 of file SmoothingGroups.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.SmoothingGroups.computeFaceEdges(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.SmoothingGroups.getAdjacentFaces(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.SmoothingGroups.getNextConnectedComponent(), and eu.mihosoft.vrl.v3d.ext.openjfx.importers.SmoothingGroups.getSmoothEdges().
faceNormals
int [][] eu.mihosoft.vrl.v3d.ext.openjfx.importers.SmoothingGroups.faceNormals private
The face normals.
Definition at line 63 of file SmoothingGroups.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.SmoothingGroups.calcSmoothGroups(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.SmoothingGroups.computeFaceEdges(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.SmoothingGroups.generateSmGroups(), and eu.mihosoft.vrl.v3d.ext.openjfx.importers.SmoothingGroups.SmoothingGroups().
faces
int [][] eu.mihosoft.vrl.v3d.ext.openjfx.importers.SmoothingGroups.faces private
The faces.
Definition at line 60 of file SmoothingGroups.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.SmoothingGroups.calcSmoothGroups(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.SmoothingGroups.computeFaceEdges(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.SmoothingGroups.getNextConnectedComponent(), and eu.mihosoft.vrl.v3d.ext.openjfx.importers.SmoothingGroups.SmoothingGroups().
normalAngle
final float eu.mihosoft.vrl.v3d.ext.openjfx.importers.SmoothingGroups.normalAngle = 0.9994f static private
The Constant normalAngle.
Definition at line 188 of file SmoothingGroups.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.SmoothingGroups.isNormalsEqual().
normals
float [] eu.mihosoft.vrl.v3d.ext.openjfx.importers.SmoothingGroups.normals private
The normals.
Definition at line 66 of file SmoothingGroups.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.SmoothingGroups.calcSmoothGroups(), and eu.mihosoft.vrl.v3d.ext.openjfx.importers.SmoothingGroups.SmoothingGroups().
q
Queue<Integer> eu.mihosoft.vrl.v3d.ext.openjfx.importers.SmoothingGroups.q private
The q.
Definition at line 57 of file SmoothingGroups.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.SmoothingGroups.getNextConnectedComponent(), and eu.mihosoft.vrl.v3d.ext.openjfx.importers.SmoothingGroups.SmoothingGroups().
visited
BitSet eu.mihosoft.vrl.v3d.ext.openjfx.importers.SmoothingGroups.visited private
The not visited.
Definition at line 54 of file SmoothingGroups.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.SmoothingGroups.getNextConnectedComponent(), and eu.mihosoft.vrl.v3d.ext.openjfx.importers.SmoothingGroups.SmoothingGroups().
The documentation for this class was generated from the following file:
JCSG/src/main/java/eu/mihosoft/vrl/v3d/ext/openjfx/importers/SmoothingGroups.java