BowlerKernel: com.neuronrobotics.bowlerstudio.TextToSpeech Class Reference
com.neuronrobotics.bowlerstudio.TextToSpeech Class Reference
Public Member Functions
TextToSpeech ()
int speak (String text, float gainValue, boolean daemon, boolean join, ISpeakingProgress progress)
void stopSpeaking ()
Collection< Voice > getAvailableVoices ()
MaryInterface getMarytts ()
List< AudioEffect > getAudioEffects ()
void setVoice (String voice)
Private Attributes
AudioPlayer tts
MaryInterface marytts
Detailed Description
Author
GOXR3PLUS
Definition at line 25 of file TextToSpeech.java.
Constructor & Destructor Documentation
TextToSpeech()
com.neuronrobotics.bowlerstudio.TextToSpeech.TextToSpeech ()
Constructor
Definition at line 33 of file TextToSpeech.java.
References com.neuronrobotics.bowlerstudio.TextToSpeech.marytts.
Member Function Documentation
getAudioEffects()
List<AudioEffect> com.neuronrobotics.bowlerstudio.TextToSpeech.getAudioEffects ()
Return a list of available audio effects for MaryTTS
Returns
Definition at line 124 of file TextToSpeech.java.
getAvailableVoices()
Collection<Voice> com.neuronrobotics.bowlerstudio.TextToSpeech.getAvailableVoices ()
Available voices in String representation
Returns
The available voices for MaryTTS
Definition at line 108 of file TextToSpeech.java.
Referenced by com.neuronrobotics.bowlerstudio.BowlerKernel.speak().
getMarytts()
MaryInterface com.neuronrobotics.bowlerstudio.TextToSpeech.getMarytts ()
Returns
the marytts
Definition at line 115 of file TextToSpeech.java.
References com.neuronrobotics.bowlerstudio.TextToSpeech.marytts.
Referenced by com.neuronrobotics.bowlerstudio.BowlerKernel.speak().
setVoice()
void com.neuronrobotics.bowlerstudio.TextToSpeech.setVoice (String voice)
Change the default voice of the MaryTTS
Parameters
voice
Definition at line 135 of file TextToSpeech.java.
References com.neuronrobotics.bowlerstudio.TextToSpeech.marytts.
Referenced by com.neuronrobotics.bowlerstudio.BowlerKernel.speak().
speak()
int com.neuronrobotics.bowlerstudio.TextToSpeech.speak (String text, float gainValue, boolean daemon, boolean join, ISpeakingProgress progress)
Transform text to speech
Parameters
text The text that will be transformed to speech
daemon
True The thread that will start the text to speech Player will be a daemon Thread
False The thread that will start the text to speech Player will be a normal non daemon Thread
join
True The current Thread calling this method will wait(blocked) until the Thread which is playing the Speech finish
False The current Thread calling this method will continue freely after calling this method
progress
Implements com.neuronrobotics.bowlerstudio.ITTSEngine.
Definition at line 59 of file TextToSpeech.java.
References com.neuronrobotics.bowlerstudio.AudioPlayer.cancel(), com.neuronrobotics.bowlerstudio.TextToSpeech.marytts, com.neuronrobotics.bowlerstudio.AudioPlayer.setAudio(), com.neuronrobotics.bowlerstudio.AudioPlayer.setGain(), com.neuronrobotics.bowlerstudio.AudioPlayer.setSpeakProgress(), com.neuronrobotics.bowlerstudio.TextToSpeech.stopSpeaking(), and com.neuronrobotics.bowlerstudio.TextToSpeech.tts.
Referenced by com.neuronrobotics.bowlerstudio.BowlerKernel.speak().
stopSpeaking()
void com.neuronrobotics.bowlerstudio.TextToSpeech.stopSpeaking ()
Stop the MaryTTS from Speaking
Definition at line 95 of file TextToSpeech.java.
References com.neuronrobotics.bowlerstudio.AudioPlayer.cancel(), and com.neuronrobotics.bowlerstudio.TextToSpeech.tts.
Referenced by com.neuronrobotics.bowlerstudio.TextToSpeech.speak().
Member Data Documentation
marytts
MaryInterface com.neuronrobotics.bowlerstudio.TextToSpeech.marytts private
Definition at line 28 of file TextToSpeech.java.
Referenced by com.neuronrobotics.bowlerstudio.TextToSpeech.getMarytts(), com.neuronrobotics.bowlerstudio.TextToSpeech.setVoice(), com.neuronrobotics.bowlerstudio.TextToSpeech.speak(), and com.neuronrobotics.bowlerstudio.TextToSpeech.TextToSpeech().
tts
AudioPlayer com.neuronrobotics.bowlerstudio.TextToSpeech.tts private
Definition at line 27 of file TextToSpeech.java.
Referenced by com.neuronrobotics.bowlerstudio.TextToSpeech.speak(), and com.neuronrobotics.bowlerstudio.TextToSpeech.stopSpeaking().
The documentation for this class was generated from the following file:
src/main/java/com/neuronrobotics/bowlerstudio/TextToSpeech.java