BowlerKernel: com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR Class Reference
com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR Class Reference abstract
Public Member Functions
Object getRootListener ()
void setRootListener (Object listener)
abstract void disconnectDevice ()
abstract boolean connectDevice ()
ArrayList< String > getNamespacesImp ()
void disconnectDeviceImp ()
boolean connectDeviceImp ()
AbstractKinematicsNR ()
AbstractKinematicsNR (InputStream configFile, LinkFactory f)
AbstractKinematicsNR (Element doc, LinkFactory f)
String getXml ()
LinkConfiguration getLinkConfiguration (int linkIndex)
ArrayList< LinkConfiguration > getLinkConfigurations ()
PIDConfiguration getLinkCurrentConfiguration (int chan)
void setLinkCurrentConfiguration (int chan, PIDConfiguration c)
AbstractLink getAbstractLink (int index)
int getNumberOfLinks ()
TransformNR getCurrentTaskSpaceTransform ()
double readLinkValue (int index)
double readLinkTarget (int index)
double[] getCurrentJointSpaceVector ()
double[] getCurrentJointSpaceTarget ()
double getCurrentLinkEngineeringUnits (int linkIndex)
double[] setDesiredTaskSpaceTransform (TransformNR taskSpaceTransform, double seconds) throws Exception
boolean checkTaskSpaceTransform (TransformNR taskSpaceTransform, double seconds)
boolean checkTaskSpaceTransform (TransformNR taskSpaceTransform)
double getBestTime (TransformNR currentTaskSpaceTransform)
double getBestTime (double[] jointSpaceVect)
double[] setDesiredJointSpaceVector (double[] jointSpaceVect, double seconds) throws Exception
TransformNR calcForward (double[] jointSpaceVect)
TransformNR calcHome ()
void setDesiredJointAxisValue (int axis, double value, double seconds) throws Exception
void firePoseUpdate ()
TransformNR getFiducialToGlobalTransform ()
void setRobotToFiducialTransform (TransformNR baseToFiducial)
TransformNR getRobotToFiducialTransform ()
void setGlobalToFiducialTransform (TransformNR frameToBase, boolean fireUpdate)
void setGlobalToFiducialTransform (TransformNR frameToBase)
TransformNR inverseOffset (TransformNR t)
TransformNR forwardOffset (TransformNR t)
void addJointSpaceListener (IJointSpaceUpdateListenerNR l)
void removeJointSpaceUpdateListener (IJointSpaceUpdateListenerNR l)
void addRegistrationListener (IRegistrationListenerNR l)
void removeRegestrationUpdateListener (IRegistrationListenerNR l)
void addPoseUpdateListener (ITaskSpaceUpdateListenerNR l)
void removePoseUpdateListener (ITaskSpaceUpdateListenerNR l)
void onLinkPositionUpdate (AbstractLink source, double engineeringUnitsValue)
void onPIDEvent (PIDEvent e)
void onPIDLimitEvent (PIDLimitEvent e)
void onPIDReset (int group, float currentValue)
void homeAllLinks ()
void homeLink (int link)
void emergencyStop ()
ArrayList< PIDConfiguration > getAxisPidConfiguration ()
abstract double[] inverseKinematics (TransformNR taskSpaceTransform) throws Exception
abstract TransformNR forwardKinematics (double[] jointSpaceVector)
TransformNR getCurrentPoseTarget ()
void setCurrentPoseTarget (TransformNR currentPoseTarget)
void setFactory (LinkFactory factory)
LinkFactory getFactory ()
void setNoFlush (boolean noFlush)
boolean isNoFlush ()
int getRetryNumberBeforeFail ()
void setRetryNumberBeforeFail (int retryNumberBeforeFail)
void onLinkLimit (AbstractLink arg0, PIDLimitEvent arg1)
DHChain getDhParametersChain ()
void setDhParametersChain (DHChain dhParametersChain)
String[] getGitDhEngine ()
void setGitDhEngine (String[] dhEngine)
String[] getGitCadEngine ()
void setGitCadEngine (String[] cadEngine)
IMU getImu ()
void boundedLinkValueSet (int index, double value) throws Exception
double boundToLinkLimits (int index, double value)
double linkMass (int linkIndex)
double getMaxEngineeringUnits (int linkIndex)
double getMinEngineeringUnits (int linkIndex)
void setMaxEngineeringUnits (int linkIndex, double maxLimit)
void setMinEngineeringUnits (int linkIndex, double minLimit)
String getElectroMechanicalType (int linkIndex)
void setElectroMechanicalType (int linkIndex, String electroMechanicalType)
String getElectroMechanicalSize (int linkIndex)
void setElectroMechanicalSize (int linkIndex, String electroMechanicalSize)
String getShaftType (int linkIndex)
void setShaftType (int linkIndex, String shaftType)
String getShaftSize (int linkIndex)
void setDeviceMaximumValue (int linkIndex, double max)
void setDeviceMinimumValue (int linkIndex, double min)
double getDeviceMaximumValue (int linkIndex)
double getDeviceMinimumValue (int linkIndex)
void addChangeListener (int linkIndex, ILinkConfigurationChangeListener l)
void removeChangeListener (int linkIndex, ILinkConfigurationChangeListener l)
void clearChangeListener (int linkIndex)
void runRenderWrangler ()
void setRenderWrangler (Runnable renderWrangler)
TransformNR getDeltaToTarget (TransformNR target)
TransformNR getTipAlongTrajectory (TransformNR startingPoint, TransformNR deltaToTarget, double unitIncrement)
void asyncInterpolatedMove (TransformNR target, double seconds, InterpolationType type, IOnInterpolationDone listener, double ...conf)
InterpolationMoveState blockingInterpolatedMove (TransformNR target, double seconds, InterpolationType type, double ...conf)
Public Member Functions inherited from com.neuronrobotics.sdk.common.NonBowlerDevice
boolean connect ()
boolean isAvailable () throws InvalidConnectionException
void disconnect ()
void onAsyncResponse (BowlerDatagram data)
ArrayList< String > getNamespaces ()
Public Member Functions inherited from com.neuronrobotics.sdk.common.BowlerAbstractDevice
void addConnectionEventListener (final IDeviceConnectionEventListener l)
void removeConnectionEventListener (IDeviceConnectionEventListener l)
void setConnection (BowlerAbstractConnection connection)
BowlerAbstractConnection getConnection ()
void setAddress (MACAddress address)
MACAddress getAddress ()
BowlerDatagram send (BowlerAbstractCommand command) throws NoConnectionAvailableException, InvalidResponseException
BowlerDatagram send (BowlerAbstractCommand command, int retry) throws NoConnectionAvailableException, InvalidResponseException
Object[] send (String namespace, BowlerMethod method, String rpcString, Object[] arguments, int retry) throws DeviceConnectionException
Object[] send (String namespace, BowlerMethod method, String rpcString, Object[] arguments) throws DeviceConnectionException
boolean ping ()
boolean ping (boolean switchParser)
ArrayList< ByteList > getRevisions ()
boolean hasNamespace (String string)
void startHeartBeat ()
void startHeartBeat (long msHeartBeatTime)
void stopHeartBeat ()
void setThreadedUpstreamPackets (boolean up)
ArrayList< RpcEncapsulation > getRpcList (String namespace)
void loadRpcList ()
void onAllResponse (BowlerDatagram data)
boolean isKeepAlive ()
void setKeepAlive (boolean keepAlive)
long getLastPacketTime ()
void setLastPacketTime (long lastPacketTime)
String getScriptingName ()
void setScriptingName (String scriptingName)
ArrayList< IDeviceConnectionEventListener > getDisconnectListeners ()
Static Public Member Functions
static boolean checkTaskSpaceTransform (AbstractKinematicsNR dev, TransformNR taskSpaceTransform, double seconds)
static boolean checkTaskSpaceTransform (AbstractKinematicsNR dev, TransformNR taskSpaceTransform)
Protected Member Functions
ArrayList< LinkConfiguration > loadConfig (Element doc)
LinkFactory getDevice ()
void setDevice (LinkFactory f, ArrayList< LinkConfiguration > linkConfigs)
void firePoseTransform (TransformNR transform)
void fireTargetJointsUpdate (double[] jointSpaceVector, TransformNR fwd)
String getCode (Element e, String tag)
String[] getGitCodes (Element doc, String tag)
Protected Member Functions inherited from com.neuronrobotics.sdk.common.BowlerAbstractDevice
void fireDisconnectEvent ()
void fireConnectEvent ()
Protected Attributes
ArrayList< IJointSpaceUpdateListenerNR > jointSpaceUpdateListeners = new ArrayList<IJointSpaceUpdateListenerNR>()
Private Member Functions
String getDate ()
double[] _setDesiredJointSpaceVector (double[] jointSpaceVect, double seconds, boolean fireTaskUpdate) throws Exception
void fireJointSpaceLimitUpdate (int axis, JointLimit event)
void runHome (PIDChannel joint, int tps)
Static Private Member Functions
static boolean checkVector (AbstractKinematicsNR dev, double[] jointSpaceVect, double seconds)
Private Attributes
ArrayList< PIDConfiguration > pidConfigurations = new ArrayList<PIDConfiguration>()
ArrayList< ITaskSpaceUpdateListenerNR > taskSpaceUpdateListeners = new ArrayList<ITaskSpaceUpdateListenerNR>()
ArrayList< IRegistrationListenerNR > regListeners = new ArrayList<IRegistrationListenerNR>()
ArrayList< MobileBase > mobileBases = new ArrayList<MobileBase>()
String[] dhEngine
String[] cadEngine
TransformNR currentPoseTarget = new TransformNR()
TransformNR base2Fiducial = new TransformNR()
TransformNR fiducial2RAS = new TransformNR()
boolean noFlush = false
boolean noXmlConfig = true
DHChain dhParametersChain = null
Object root
LinkFactory factory = null
int retryNumberBeforeFail = 5
IMU imu = new IMU()
Runnable renderWrangler =null
long homeTime
Detailed Description
The Class AbstractKinematicsNR.
Definition at line 47 of file AbstractKinematicsNR.java.
Constructor & Destructor Documentation
AbstractKinematicsNR() [1/3]
com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.AbstractKinematicsNR ()
Instantiates a new abstract kinematics nr.
Definition at line 188 of file AbstractKinematicsNR.java.
AbstractKinematicsNR() [2/3]
com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.AbstractKinematicsNR (InputStream configFile, LinkFactory f)
Instantiates a new abstract kinematics nr.
Parameters
configFile the config file
f the f
Definition at line 207 of file AbstractKinematicsNR.java.
References com.neuronrobotics.sdk.addons.kinematics.xml.XmlFactory.getAllNodesDocument(), and com.neuronrobotics.sdk.common.Log.info().
AbstractKinematicsNR() [3/3]
com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.AbstractKinematicsNR (Element doc, LinkFactory f)
Instantiates a new abstract kinematics nr.
Parameters
doc the doc
f the f
Definition at line 234 of file AbstractKinematicsNR.java.
Member Function Documentation
_setDesiredJointSpaceVector()
double [] com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR._setDesiredJointSpaceVector (double[] jointSpaceVect, double seconds, boolean fireTaskUpdate) throws Exception private
This calculates the target pose .
Parameters
jointSpaceVect the joint space vect
seconds the time for the transition to take from current position to target, unit seconds
Returns
The joint space vector is returned for target arrival referance
Exceptions
Exception If there is a workspace error
Definition at line 733 of file AbstractKinematicsNR.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkFactory.flush(), com.neuronrobotics.sdk.addons.kinematics.LinkFactory.setCachedTargets(), and com.neuronrobotics.sdk.common.TickToc.tic().
addChangeListener()
void com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.addChangeListener (int linkIndex, ILinkConfigurationChangeListener l)
Definition at line 1630 of file AbstractKinematicsNR.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.MobileBase.addListeners().
addJointSpaceListener()
void com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.addJointSpaceListener (IJointSpaceUpdateListenerNR l)
Adds the joint space listener.
Parameters
l the l
Definition at line 1015 of file AbstractKinematicsNR.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.MobileBase.addListeners(), and com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.setChain().
addPoseUpdateListener()
void com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.addPoseUpdateListener (ITaskSpaceUpdateListenerNR l)
Adds the pose update listener.
Parameters
l the l
Definition at line 1058 of file AbstractKinematicsNR.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.setChain().
addRegistrationListener()
void com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.addRegistrationListener (IRegistrationListenerNR l)
Adds the registration listener.
Parameters
l the l
Definition at line 1036 of file AbstractKinematicsNR.java.
References com.neuronrobotics.sdk.addons.kinematics.IRegistrationListenerNR.onBaseToFiducialUpdate().
Referenced by com.neuronrobotics.sdk.addons.kinematics.MobileBase.connect(), and com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.run().
asyncInterpolatedMove()
void com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.asyncInterpolatedMove (TransformNR target, double seconds, InterpolationType type, IOnInterpolationDone listener, double ... conf)
Definition at line 1665 of file AbstractKinematicsNR.java.
References com.neuronrobotics.sdk.addons.kinematics.IOnInterpolationDone.done(), and com.neuronrobotics.sdk.addons.kinematics.InterpolationMoveState.FAULT.
Referenced by com.neuronrobotics.bowlerstudio.sequence.SequenceEvent.execute().
blockingInterpolatedMove()
InterpolationMoveState com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.blockingInterpolatedMove (TransformNR target, double seconds, InterpolationType type, double ... conf)
Definition at line 1678 of file AbstractKinematicsNR.java.
References com.neuronrobotics.sdk.addons.kinematics.InterpolationMoveState.FAULT, com.neuronrobotics.sdk.pid.InterpolationEngine.getInterpolationUnitIncrement(), com.neuronrobotics.sdk.addons.kinematics.InterpolationMoveState.READY, com.neuronrobotics.sdk.pid.InterpolationEngine.setSetpointWithTime(), and com.neuronrobotics.sdk.util.ThreadUtil.wait().
boundedLinkValueSet()
void com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.boundedLinkValueSet (int index, double value) throws Exception
Definition at line 1517 of file AbstractKinematicsNR.java.
boundToLinkLimits()
double com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.boundToLinkLimits (int index, double value)
Definition at line 1524 of file AbstractKinematicsNR.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getMaxEngineeringUnits(), and com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getMinEngineeringUnits().
calcForward()
TransformNR com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.calcForward (double[] jointSpaceVect)
Calc forward.
Parameters
jointSpaceVect the joint space vect
Returns
the transform nr
Definition at line 783 of file AbstractKinematicsNR.java.
calcHome()
TransformNR com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.calcHome ()
Calc home.
Returns
the transform nr
Reimplemented in com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.
Definition at line 792 of file AbstractKinematicsNR.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.calcHome(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.calcHome(), and com.neuronrobotics.sdk.addons.kinematics.MobileBase.getTipLocations().
checkTaskSpaceTransform() [1/4]
static boolean com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.checkTaskSpaceTransform (AbstractKinematicsNR dev, TransformNR taskSpaceTransform) static
Checks the desired pose for ability for the IK to calculate a valid pose.
Parameters
taskSpaceTransform the task space transform
Returns
True if pose is reachable, false if it is not
Definition at line 621 of file AbstractKinematicsNR.java.
checkTaskSpaceTransform() [2/4]
static boolean com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.checkTaskSpaceTransform (AbstractKinematicsNR dev, TransformNR taskSpaceTransform, double seconds) static
Checks the desired pose for ability for the IK to calculate a valid pose.
Parameters
taskSpaceTransform the task space transform
Returns
True if pose is reachable, false if it is not
Definition at line 605 of file AbstractKinematicsNR.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.inverseKinematics(), and com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.inverseOffset().
Referenced by com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.checkTaskSpaceTransform(), and com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.setCurrentPoseTarget().
checkTaskSpaceTransform() [3/4]
boolean com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.checkTaskSpaceTransform (TransformNR taskSpaceTransform)
Checks the desired pose for ability for the IK to calculate a valid pose.
Parameters
taskSpaceTransform the task space transform
Returns
True if pose is reachable, false if it is not
Definition at line 670 of file AbstractKinematicsNR.java.
checkTaskSpaceTransform() [4/4]
boolean com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.checkTaskSpaceTransform (TransformNR taskSpaceTransform, double seconds)
Checks the desired pose for ability for the IK to calculate a valid pose.
Parameters
taskSpaceTransform the task space transform
Returns
True if pose is reachable, false if it is not
Definition at line 661 of file AbstractKinematicsNR.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.checkTaskSpaceTransform().
checkVector()
static boolean com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.checkVector (AbstractKinematicsNR dev, double[] jointSpaceVect, double seconds) static private
Definition at line 624 of file AbstractKinematicsNR.java.
References com.neuronrobotics.sdk.common.Log.error(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.factory, com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getCurrentJointSpaceTarget(), com.neuronrobotics.sdk.addons.kinematics.LinkFactory.getLink(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getLinkConfiguration(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getMaxEngineeringUnits(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getMaxVelocityEngineeringUnits(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getMinEngineeringUnits(), and com.neuronrobotics.sdk.common.BowlerAbstractDevice.getScriptingName().
clearChangeListener()
void com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.clearChangeListener (int linkIndex)
Definition at line 1636 of file AbstractKinematicsNR.java.
connectDevice()
abstract boolean com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.connectDevice () abstract
Connect device.
Returns
true, if successful
Reimplemented in com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup, com.neuronrobotics.sdk.addons.kinematics.MobileBase, com.neuronrobotics.sdk.addons.kinematics.GenericKinematicsModelNR, and com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.
connectDeviceImp()
boolean com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.connectDeviceImp ()
Connect device imp.
Returns
true, if successful
Reimplemented from com.neuronrobotics.sdk.common.NonBowlerDevice.
Definition at line 181 of file AbstractKinematicsNR.java.
disconnectDevice()
abstract void com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.disconnectDevice () abstract
This method tells the connection object to disconnect its pipes and close out the connection. Once this is called, it is safe to remove your device.
Reimplemented in com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup, com.neuronrobotics.sdk.addons.kinematics.MobileBase, com.neuronrobotics.sdk.addons.kinematics.GenericKinematicsModelNR, and com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.
disconnectDeviceImp()
void com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.disconnectDeviceImp ()
This method tells the connection object to disconnect its pipes and close out the connection. Once this is called, it is safe to remove your device.
Reimplemented from com.neuronrobotics.sdk.common.NonBowlerDevice.
Definition at line 167 of file AbstractKinematicsNR.java.
emergencyStop()
void com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.emergencyStop ()
This is a quick stop for all axis of the robot.
Definition at line 1258 of file AbstractKinematicsNR.java.
fireJointSpaceLimitUpdate()
void com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.fireJointSpaceLimitUpdate (int axis, JointLimit event) private
Fire joint space limit update.
Parameters
axis the axis
event the event
Definition at line 890 of file AbstractKinematicsNR.java.
firePoseTransform()
void com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.firePoseTransform (TransformNR transform) protected
Fire pose transform.
Parameters
transform the transform
Definition at line 848 of file AbstractKinematicsNR.java.
References com.neuronrobotics.sdk.addons.kinematics.ITaskSpaceUpdateListenerNR.onTaskSpaceUpdate().
firePoseUpdate()
void com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.firePoseUpdate ()
Fire pose update.
Definition at line 858 of file AbstractKinematicsNR.java.
References com.neuronrobotics.sdk.addons.kinematics.IJointSpaceUpdateListenerNR.onJointSpaceUpdate().
fireTargetJointsUpdate()
void com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.fireTargetJointsUpdate (double[] jointSpaceVector, TransformNR fwd) protected
Fire target joints update.
Parameters
jointSpaceVector the joint space vector
fwd the fwd
Definition at line 876 of file AbstractKinematicsNR.java.
forwardKinematics()
abstract TransformNR com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.forwardKinematics (double[] jointSpaceVector) abstract
Forward kinematics.
Parameters
jointSpaceVector the joint space vector
Returns
6x1 vector in task space, unit in mm,radians [x,y,z,rotx,rotY,rotZ]
Reimplemented in com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup, com.neuronrobotics.sdk.addons.kinematics.MobileBase, com.neuronrobotics.sdk.addons.kinematics.GenericKinematicsModelNR, and com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.
forwardOffset()
TransformNR com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.forwardOffset (TransformNR t)
Forward offset.
Parameters
t the t
Returns
the transform nr
Definition at line 1002 of file AbstractKinematicsNR.java.
References com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getMatrixTransform().
Referenced by com.neuronrobotics.sdk.addons.kinematics.MobileBase.fireBaseUpdates(), com.neuronrobotics.sdk.addons.kinematics.DHChain.forwardOffset(), com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getJacobian(), com.neuronrobotics.bowlerstudio.physics.MobileBasePhysicsManager.MobileBasePhysicsManager(), and com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.updateBase().
getAbstractLink()
AbstractLink com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getAbstractLink (int index)
Gets the abstract link.
Parameters
index the index
Returns
the abstract link
Definition at line 444 of file AbstractKinematicsNR.java.
Referenced by com.neuronrobotics.bowlerstudio.physics.MobileBasePhysicsManager.MobileBasePhysicsManager(), com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.throwExceptionOnJointLimit(), and com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.updateLimb().
getAxisPidConfiguration()
ArrayList<PIDConfiguration> com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getAxisPidConfiguration ()
Gets the axis pid configuration.
Returns
the axis pid configuration
Definition at line 1273 of file AbstractKinematicsNR.java.
getBestTime() [1/2]
double com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getBestTime (double[] jointSpaceVect)
get the best possible time for a translation by checking the joint velocities
Parameters
jointSpaceVect new joint pose
Returns
the time of translation at best possible speed based on checking each link
Definition at line 697 of file AbstractKinematicsNR.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getMaxVelocityEngineeringUnits().
getBestTime() [2/2]
double com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getBestTime (TransformNR currentTaskSpaceTransform)
get the best possible time for a translation by checking the joint velocities
Parameters
currentTaskSpaceTransform new tip location to check
Returns
the time of translation at best possible speed based on checking each link
Definition at line 680 of file AbstractKinematicsNR.java.
getCode()
String com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getCode (Element e, String tag) protected
Gets the code.
Parameters
e the e
tag the tag
Returns
the code
Definition at line 1452 of file AbstractKinematicsNR.java.
References com.neuronrobotics.sdk.addons.kinematics.xml.XmlFactory.getTagValue().
getCurrentJointSpaceTarget()
double [] com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getCurrentJointSpaceTarget ()
Definition at line 553 of file AbstractKinematicsNR.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.checkVector().
getCurrentJointSpaceVector()
double [] com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getCurrentJointSpaceVector ()
This takes a reading of the robots position and converts it to a joint pace vector This vector is converted to Joint space and returned .
Returns
JointSpaceVector in mm,radians
Definition at line 537 of file AbstractKinematicsNR.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getChainTransformations(), com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getJacobian(), com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.inverseKinematics(), com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.linkCoM(), com.neuronrobotics.bowlerstudio.physics.MobileBasePhysicsManager.MobileBasePhysicsManager(), com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.setGlobalToFiducialTransform(), and com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.updateCadLocations().
getCurrentLinkEngineeringUnits()
double com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getCurrentLinkEngineeringUnits (int linkIndex)
Definition at line 561 of file AbstractKinematicsNR.java.
getCurrentPoseTarget()
TransformNR com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getCurrentPoseTarget ()
Gets the current pose target.
Returns
the current pose target
Definition at line 1299 of file AbstractKinematicsNR.java.
getCurrentTaskSpaceTransform()
TransformNR com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getCurrentTaskSpaceTransform ()
This takes a reading of the robots position and converts it to a joint space vector This vector is converted to task space and returned .
Returns
taskSpaceVector in mm,radians [x,y,z,rotx,rotY,rotZ]
Definition at line 516 of file AbstractKinematicsNR.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.MobileBase.main().
getDate()
String com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getDate () private
Gets the date.
Returns
the date
Definition at line 248 of file AbstractKinematicsNR.java.
getDeltaToTarget()
TransformNR com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getDeltaToTarget (TransformNR target)
Definition at line 1656 of file AbstractKinematicsNR.java.
References com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.inverse(), and com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.times().
getDevice()
LinkFactory com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getDevice () protected
Gets the device.
Returns
the device
Definition at line 434 of file AbstractKinematicsNR.java.
getDeviceMaximumValue()
double com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getDeviceMaximumValue (int linkIndex)
Override this method to specify a larger range
Returns
the maximum value possible for a link
Definition at line 1620 of file AbstractKinematicsNR.java.
getDeviceMinimumValue()
double com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getDeviceMinimumValue (int linkIndex)
Override this method to specify a larger range
Returns
the minimum value possible for a link
Definition at line 1627 of file AbstractKinematicsNR.java.
getDhParametersChain()
DHChain com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getDhParametersChain ()
Gets the dh parameters chain.
Returns
the dh parameters chain
Definition at line 1394 of file AbstractKinematicsNR.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.DHParameterKinematics().
getElectroMechanicalSize()
String com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getElectroMechanicalSize (int linkIndex)
Definition at line 1584 of file AbstractKinematicsNR.java.
getElectroMechanicalType()
String com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getElectroMechanicalType (int linkIndex)
Definition at line 1576 of file AbstractKinematicsNR.java.
getFactory()
LinkFactory com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getFactory ()
Gets the factory.
Returns
the factory
Definition at line 1331 of file AbstractKinematicsNR.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.MobileBase.addListeners(), com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.addNewLink(), com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.DHParameterKinematics(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.generateCad(), com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.removeLimb(), com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.removeLink(), com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.setChain(), and com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.setupReferencedLimbStartup().
getFiducialToGlobalTransform()
TransformNR com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getFiducialToGlobalTransform ()
Gets the fiducial to global transform.
Returns
the fiducial to global transform
Definition at line 901 of file AbstractKinematicsNR.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.WalkingDriveEngine.DriveArc(), com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getEmbedableXml(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.getEmbedableXml(), com.neuronrobotics.bowlerstudio.physics.MobileBasePhysicsManager.MobileBasePhysicsManager(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.pose(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.run(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.updateBase(), and com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.updateLimb().
getGitCadEngine()
String [] com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getGitCadEngine ()
Gets the cad engine.
Returns
the cad engine
Definition at line 1431 of file AbstractKinematicsNR.java.
Referenced by com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getCadScriptFromLimnb(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getCadScriptFromMobileBase(), com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getEmbedableXml(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.getEmbedableXml(), and com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getIgenerateBed().
getGitCodes()
String [] com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getGitCodes (Element doc, String tag) protected
Gets the gist codes.
Parameters
doc the doc
tag the tag
Returns
the gist codes
Definition at line 1475 of file AbstractKinematicsNR.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.MobileBase.loadConfigs().
getGitDhEngine()
String [] com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getGitDhEngine ()
Gets the dh engine.
Returns
the dh engine
Definition at line 1412 of file AbstractKinematicsNR.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getEmbedableXml(), and com.neuronrobotics.bowlerstudio.creature.MobileBaseLoader.setDefaultDhParameterKinematics().
getImu()
IMU com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getImu ()
Definition at line 1511 of file AbstractKinematicsNR.java.
Referenced by com.neuronrobotics.bowlerstudio.physics.MobileBasePhysicsManager.MobileBasePhysicsManager().
getLinkConfiguration()
LinkConfiguration com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getLinkConfiguration (int linkIndex)
Gets the link configuration.
Parameters
linkIndex the link index
Returns
the link configuration
Definition at line 394 of file AbstractKinematicsNR.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.checkVector(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.generateCad(), com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getEmbedableXml(), com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.linkCoM(), com.neuronrobotics.bowlerstudio.physics.MobileBasePhysicsManager.MobileBasePhysicsManager(), and com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.setChain().
getLinkConfigurations()
ArrayList<LinkConfiguration> com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getLinkConfigurations ()
Gets the link configurations.
Returns
the link configurations
Definition at line 403 of file AbstractKinematicsNR.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.DHParameterKinematics().
getLinkCurrentConfiguration()
PIDConfiguration com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getLinkCurrentConfiguration (int chan)
Gets the link current configuration.
Parameters
chan the chan
Returns
the link current configuration
Definition at line 415 of file AbstractKinematicsNR.java.
getMaxEngineeringUnits()
double com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getMaxEngineeringUnits (int linkIndex)
Gets the max engineering units.
Returns
the max engineering units
Definition at line 1544 of file AbstractKinematicsNR.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.WristNormalizer.score().
getMinEngineeringUnits()
double com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getMinEngineeringUnits (int linkIndex)
Gets the min engineering units.
Returns
the min engineering units
Definition at line 1553 of file AbstractKinematicsNR.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.WristNormalizer.score().
getNamespacesImp()
ArrayList<String> com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getNamespacesImp ()
Gets the namespaces imp.
Returns
the namespaces imp
Reimplemented from com.neuronrobotics.sdk.common.NonBowlerDevice.
Definition at line 155 of file AbstractKinematicsNR.java.
getNumberOfLinks()
int com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getNumberOfLinks ()
Gets the number of links defined in the configuration file.
Returns
number of links in XML
Definition at line 506 of file AbstractKinematicsNR.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.MobileBase.addListeners(), com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.DHParameterKinematics(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.generateCad(), com.neuronrobotics.sdk.addons.kinematics.GenericKinematicsModelNR.inverseKinematics(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.inverseKinematics(), com.neuronrobotics.bowlerstudio.physics.MobileBasePhysicsManager.MobileBasePhysicsManager(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.set(), and com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.throwExceptionOnJointLimit().
getRetryNumberBeforeFail()
int com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getRetryNumberBeforeFail ()
Gets the retry number before fail.
Returns
the retry number before fail
Definition at line 1360 of file AbstractKinematicsNR.java.
getRobotToFiducialTransform()
TransformNR com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getRobotToFiducialTransform ()
Gets the robot to fiducial transform.
Returns
the robot to fiducial transform
Definition at line 943 of file AbstractKinematicsNR.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getEmbedableXml(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.getEmbedableXml(), and com.neuronrobotics.bowlerstudio.physics.MobileBasePhysicsManager.MobileBasePhysicsManager().
getRootListener()
Object com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getRootListener ()
Gets the root listener.
Returns
the root listener
Definition at line 122 of file AbstractKinematicsNR.java.
Referenced by com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.selectCsgByLimb(), com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.setChain(), and com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.updateBase().
getShaftSize()
String com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getShaftSize (int linkIndex)
Definition at line 1600 of file AbstractKinematicsNR.java.
getShaftType()
String com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getShaftType (int linkIndex)
Definition at line 1592 of file AbstractKinematicsNR.java.
getTipAlongTrajectory()
TransformNR com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getTipAlongTrajectory (TransformNR startingPoint, TransformNR deltaToTarget, double unitIncrement)
Definition at line 1662 of file AbstractKinematicsNR.java.
References com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.scale(), and com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.times().
getXml()
String com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getXml ()
Gets the xml.
Returns
the xml
Reimplemented in com.neuronrobotics.sdk.addons.kinematics.MobileBase, and com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.
Definition at line 367 of file AbstractKinematicsNR.java.
homeAllLinks()
void com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.homeAllLinks ()
This method uses the latch values to home all of the robot links.
Definition at line 1150 of file AbstractKinematicsNR.java.
homeLink()
void com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.homeLink (int link)
Home link.
Parameters
link the link
Definition at line 1206 of file AbstractKinematicsNR.java.
References com.neuronrobotics.sdk.pid.PIDChannel.ConfigurePIDController(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getHardwareIndex(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getIndexLatch(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getLowerLimit(), com.neuronrobotics.sdk.pid.PIDChannel.getPid(), com.neuronrobotics.sdk.namespace.bcs.pid.IPidControlNamespace.getPIDChannel(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getUpperLimit(), com.neuronrobotics.sdk.common.Log.info(), com.neuronrobotics.sdk.addons.kinematics.LinkType.PID, com.neuronrobotics.sdk.pid.PIDConfiguration.setIndexLatch(), com.neuronrobotics.sdk.pid.PIDConfiguration.setStopOnIndex(), and com.neuronrobotics.sdk.pid.PIDConfiguration.setUseLatch().
inverseKinematics()
abstract double [] com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.inverseKinematics (TransformNR taskSpaceTransform) throws Exception abstract
Inverse kinematics.
Parameters
taskSpaceTransform the task space transform
Returns
Nx1 vector in task space, in mm where N is number of links
Exceptions
Exception the exception
Reimplemented in com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup, com.neuronrobotics.sdk.addons.kinematics.MobileBase, com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics, and com.neuronrobotics.sdk.addons.kinematics.GenericKinematicsModelNR.
Referenced by com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.checkTaskSpaceTransform().
inverseOffset()
TransformNR com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.inverseOffset (TransformNR t)
Inverse offset.
Parameters
t the t
Returns
the transform nr
Definition at line 983 of file AbstractKinematicsNR.java.
References com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getMatrixTransform().
Referenced by com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.checkTaskSpaceTransform(), and com.neuronrobotics.sdk.addons.kinematics.ik.DeltaIKModel.inverseKinematics6dof().
isNoFlush()
boolean com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.isNoFlush ()
Checks if is no flush.
Returns
true, if is no flush
Definition at line 1351 of file AbstractKinematicsNR.java.
linkMass()
double com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.linkMass (int linkIndex)
Definition at line 1535 of file AbstractKinematicsNR.java.
loadConfig()
ArrayList<LinkConfiguration> com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.loadConfig (Element doc) protected
Load XML configuration file, then store in LinkConfiguration (ArrayList type).
Parameters
doc the doc
Returns
the array list
Definition at line 260 of file AbstractKinematicsNR.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getSlaveLinks(), com.neuronrobotics.sdk.addons.kinematics.xml.XmlFactory.getTagValue(), and com.neuronrobotics.sdk.addons.kinematics.DHLink.setMobileBaseXml().
onLinkLimit()
void com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.onLinkLimit (AbstractLink source, PIDLimitEvent event)
On the event of a limit, this is called.
Parameters
source the source
event the event
Implements com.neuronrobotics.sdk.addons.kinematics.ILinkListener.
Definition at line 1381 of file AbstractKinematicsNR.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getHardwareIndex(), and com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getLinkConfiguration().
onLinkPositionUpdate()
void com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.onLinkPositionUpdate (AbstractLink source, double engineeringUnitsValue)
On link position update.
Parameters
source the source
engineeringUnitsValue the engineering units value
Implements com.neuronrobotics.sdk.addons.kinematics.ILinkListener.
Definition at line 1086 of file AbstractKinematicsNR.java.
References com.neuronrobotics.sdk.common.Log.error().
onPIDEvent()
void com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.onPIDEvent (PIDEvent e)
On pid event.
Parameters
e the e
Implements com.neuronrobotics.sdk.pid.IPIDEventListener.
Definition at line 1119 of file AbstractKinematicsNR.java.
onPIDLimitEvent()
void com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.onPIDLimitEvent (PIDLimitEvent e)
On pid limit event.
Parameters
e the e
Implements com.neuronrobotics.sdk.pid.IPIDEventListener.
Definition at line 1130 of file AbstractKinematicsNR.java.
References com.neuronrobotics.sdk.pid.PIDLimitEvent.getGroup().
onPIDReset()
void com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.onPIDReset (int group, float currentValue)
On pid reset.
Parameters
group the group
currentValue the current value
Implements com.neuronrobotics.sdk.pid.IPIDEventListener.
Definition at line 1143 of file AbstractKinematicsNR.java.
readLinkTarget()
double com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.readLinkTarget (int index)
Definition at line 528 of file AbstractKinematicsNR.java.
readLinkValue()
double com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.readLinkValue (int index)
Definition at line 525 of file AbstractKinematicsNR.java.
removeChangeListener()
void com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.removeChangeListener (int linkIndex, ILinkConfigurationChangeListener l)
Definition at line 1633 of file AbstractKinematicsNR.java.
removeJointSpaceUpdateListener()
void com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.removeJointSpaceUpdateListener (IJointSpaceUpdateListenerNR l)
Removes the joint space update listener.
Parameters
l the l
Definition at line 1026 of file AbstractKinematicsNR.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.disconnectDevice().
removePoseUpdateListener()
void com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.removePoseUpdateListener (ITaskSpaceUpdateListenerNR l)
Removes the pose update listener.
Parameters
l the l
Definition at line 1071 of file AbstractKinematicsNR.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.disconnectDevice().
removeRegestrationUpdateListener()
void com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.removeRegestrationUpdateListener (IRegistrationListenerNR l)
Removes the regestration update listener.
Parameters
l the l
Definition at line 1048 of file AbstractKinematicsNR.java.
runHome()
void com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.runHome (PIDChannel joint, int tps) private
Run home.
Parameters
joint the joint
tps the tps
Definition at line 1172 of file AbstractKinematicsNR.java.
References com.neuronrobotics.sdk.pid.PIDChannel.addPIDEventListener(), com.neuronrobotics.sdk.common.Log.debug(), com.neuronrobotics.sdk.common.Log.info(), com.neuronrobotics.sdk.pid.PIDChannel.removePIDEventListener(), com.neuronrobotics.sdk.pid.PIDChannel.SetPIDSetPoint(), and com.neuronrobotics.sdk.util.ThreadUtil.wait().
runRenderWrangler()
void com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.runRenderWrangler ()
Definition at line 1642 of file AbstractKinematicsNR.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.refreshPose(), com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.setGlobalToFiducialTransform(), and com.neuronrobotics.sdk.addons.kinematics.MobileBase.updatePositions().
setCurrentPoseTarget()
void com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.setCurrentPoseTarget (TransformNR currentPoseTarget)
Sets the current pose target.
Parameters
currentPoseTarget the new current pose target
Reimplemented in com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.
Definition at line 1310 of file AbstractKinematicsNR.java.
setDesiredJointAxisValue()
void com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.setDesiredJointAxisValue (int axis, double value, double seconds) throws Exception
Sets an individual target joint position .
Parameters
axis the joint index to set
value the value to set it to
seconds the time for the transition to take from current position to target, unit seconds
Exceptions
Exception If there is a workspace error
Definition at line 809 of file AbstractKinematicsNR.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getLowerLimit(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getUpperLimit(), and com.neuronrobotics.sdk.common.Log.info().
setDesiredJointSpaceVector()
double [] com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.setDesiredJointSpaceVector (double[] jointSpaceVect, double seconds) throws Exception
This calculates the target pose .
Parameters
jointSpaceVect the joint space vect
seconds the time for the transition to take from current position to target, unit seconds
Returns
The joint space vector is returned for target arrival referance
Exceptions
Exception If there is a workspace error
Definition at line 721 of file AbstractKinematicsNR.java.
setDesiredTaskSpaceTransform()
double [] com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.setDesiredTaskSpaceTransform (TransformNR taskSpaceTransform, double seconds) throws Exception
This calculates the target pose .
Parameters
taskSpaceTransform the task space transform
seconds the time for the transition to take from current position to target, unit seconds
Returns
The joint space vector is returned for target arrival referance
Exceptions
Exception If there is a workspace error
Definition at line 574 of file AbstractKinematicsNR.java.
References com.neuronrobotics.sdk.common.Log.info(), and com.neuronrobotics.sdk.common.TickToc.tic().
Referenced by com.neuronrobotics.sdk.addons.kinematics.MobileBase.initializeParalellGroups(), and com.neuronrobotics.sdk.addons.kinematics.MobileBase.main().
setDevice()
void com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.setDevice (LinkFactory f, ArrayList< LinkConfiguration > linkConfigs) protected
Sets the device.
Parameters
f the f
linkConfigs the link configs
Definition at line 454 of file AbstractKinematicsNR.java.
References com.neuronrobotics.sdk.namespace.bcs.pid.IPidControlNamespace.addPIDEventListener(), com.neuronrobotics.sdk.namespace.bcs.pid.IPidControlNamespace.ConfigurePIDController(), com.neuronrobotics.sdk.common.Log.error(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getHardwareIndex(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getIndexLatch(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getKD(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getKI(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getKP(), com.neuronrobotics.sdk.namespace.bcs.pid.IPidControlNamespace.getPIDConfiguration(), com.neuronrobotics.sdk.common.Log.info(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.isInverted(), com.neuronrobotics.sdk.addons.kinematics.LinkType.PID, com.neuronrobotics.sdk.pid.PIDConfiguration.setAsync(), com.neuronrobotics.sdk.pid.PIDConfiguration.setEnabled(), com.neuronrobotics.sdk.pid.PIDConfiguration.setGroup(), com.neuronrobotics.sdk.pid.PIDConfiguration.setIndexLatch(), com.neuronrobotics.sdk.pid.PIDConfiguration.setInverted(), com.neuronrobotics.sdk.pid.PIDConfiguration.setKD(), com.neuronrobotics.sdk.pid.PIDConfiguration.setKI(), com.neuronrobotics.sdk.pid.PIDConfiguration.setKP(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setLinkIndex(), com.neuronrobotics.sdk.pid.PIDConfiguration.setStopOnIndex(), and com.neuronrobotics.sdk.pid.PIDConfiguration.setUseLatch().
setDeviceMaximumValue()
void com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.setDeviceMaximumValue (int linkIndex, double max)
Override this method to specify a larger range
Definition at line 1606 of file AbstractKinematicsNR.java.
setDeviceMinimumValue()
void com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.setDeviceMinimumValue (int linkIndex, double min)
Override this method to specify a larger range
Definition at line 1613 of file AbstractKinematicsNR.java.
setDhParametersChain()
void com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.setDhParametersChain (DHChain dhParametersChain)
Sets the dh parameters chain.
Parameters
dhParametersChain the new dh parameters chain
Definition at line 1403 of file AbstractKinematicsNR.java.
setElectroMechanicalSize()
void com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.setElectroMechanicalSize (int linkIndex, String electroMechanicalSize)
Definition at line 1588 of file AbstractKinematicsNR.java.
setElectroMechanicalType()
void com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.setElectroMechanicalType (int linkIndex, String electroMechanicalType)
Definition at line 1580 of file AbstractKinematicsNR.java.
setFactory()
void com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.setFactory (LinkFactory factory)
Sets the factory.
Parameters
factory the new factory
Definition at line 1322 of file AbstractKinematicsNR.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.removeLimb().
setGitCadEngine()
void com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.setGitCadEngine (String[] cadEngine)
Sets the cad engine.
Parameters
cadEngine the new cad engine
Definition at line 1440 of file AbstractKinematicsNR.java.
Referenced by com.neuronrobotics.bowlerstudio.scripting.RobotHelper.getDefaultContents(), and com.neuronrobotics.sdk.addons.kinematics.MobileBase.loadConfigs().
setGitDhEngine()
void com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.setGitDhEngine (String[] dhEngine)
Sets the dh engine.
Parameters
dhEngine the new dh engine
Definition at line 1421 of file AbstractKinematicsNR.java.
Referenced by com.neuronrobotics.bowlerstudio.scripting.RobotHelper.getDefaultContents(), and com.neuronrobotics.bowlerstudio.creature.MobileBaseLoader.setGitDhEngine().
setGlobalToFiducialTransform() [1/2]
void com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.setGlobalToFiducialTransform (TransformNR frameToBase)
Sets the global to fiducial transform.
Parameters
frameToBase the new global to fiducial transform
Reimplemented in com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.
Definition at line 974 of file AbstractKinematicsNR.java.
setGlobalToFiducialTransform() [2/2]
void com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.setGlobalToFiducialTransform (TransformNR frameToBase, boolean fireUpdate)
Sets the global to fiducial transform.
Parameters
frameToBase the new global to fiducial transform
Definition at line 952 of file AbstractKinematicsNR.java.
References com.neuronrobotics.sdk.common.Log.error(), and com.neuronrobotics.sdk.addons.kinematics.IRegistrationListenerNR.onFiducialToGlobalUpdate().
Referenced by com.neuronrobotics.sdk.addons.kinematics.WalkingDriveEngine.DriveArc(), com.neuronrobotics.sdk.addons.kinematics.DHLink.fireOnLinkGlobalPositionChange(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.getEmbedableXml(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.pose(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.setFiducialToGlobalTransform(), and com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.updateBase().
setLinkCurrentConfiguration()
void com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.setLinkCurrentConfiguration (int chan, PIDConfiguration c)
Sets the link current configuration.
Parameters
chan the chan
c the c
Definition at line 425 of file AbstractKinematicsNR.java.
setMaxEngineeringUnits()
void com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.setMaxEngineeringUnits (int linkIndex, double maxLimit)
Sets the max engineering units.
Parameters
maxLimit the max engineering units
Definition at line 1563 of file AbstractKinematicsNR.java.
setMinEngineeringUnits()
void com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.setMinEngineeringUnits (int linkIndex, double minLimit)
Sets the min engineering units.
Parameters
minLimit the min engineering units
Definition at line 1572 of file AbstractKinematicsNR.java.
setNoFlush()
void com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.setNoFlush (boolean noFlush)
Sets the no flush.
Parameters
noFlush the new no flush
Definition at line 1342 of file AbstractKinematicsNR.java.
setRenderWrangler()
void com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.setRenderWrangler (Runnable renderWrangler)
Definition at line 1652 of file AbstractKinematicsNR.java.
Referenced by com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.setMobileBase().
setRetryNumberBeforeFail()
void com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.setRetryNumberBeforeFail (int retryNumberBeforeFail)
Sets the retry number before fail.
Parameters
retryNumberBeforeFail the new retry number before fail
Definition at line 1369 of file AbstractKinematicsNR.java.
setRobotToFiducialTransform()
void com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.setRobotToFiducialTransform (TransformNR baseToFiducial)
Reimplemented in com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.
Definition at line 914 of file AbstractKinematicsNR.java.
References com.neuronrobotics.sdk.common.Log.error(), and com.neuronrobotics.sdk.common.Log.info().
Referenced by com.neuronrobotics.sdk.addons.kinematics.MobileBase.loadConfigs().
setRootListener()
void com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.setRootListener (Object listener)
Sets the root listener.
Parameters
listener the new root listener
Definition at line 131 of file AbstractKinematicsNR.java.
Referenced by com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.updateBase().
setShaftType()
void com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.setShaftType (int linkIndex, String shaftType)
Definition at line 1596 of file AbstractKinematicsNR.java.
Member Data Documentation
base2Fiducial
TransformNR com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.base2Fiducial = new TransformNR() private
The base2 fiducial.
Definition at line 85 of file AbstractKinematicsNR.java.
cadEngine
String [] com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.cadEngine private
Initial value:
= new String[] { "https://github.com/madhephaestus/carl-the-hexapod.git",
            "ThreeDPrintCad.groovy" }
The cad engine.
Definition at line 71 of file AbstractKinematicsNR.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.setGitCadToolEngine().
currentPoseTarget
TransformNR com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.currentPoseTarget = new TransformNR() private
The current joint space positions. The current joint space target. The current pose target.
Definition at line 82 of file AbstractKinematicsNR.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.setCurrentPoseTarget().
dhEngine
String [] com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.dhEngine private
Initial value:
= new String[] { "https://github.com/madhephaestus/carl-the-hexapod.git",
            "DefaultDhSolver.groovy" }
The dh engine.
Definition at line 67 of file AbstractKinematicsNR.java.
dhParametersChain
DHChain com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.dhParametersChain = null private
The dh parameters chain.
Definition at line 97 of file AbstractKinematicsNR.java.
factory
LinkFactory com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.factory = null private
The factory.
Definition at line 105 of file AbstractKinematicsNR.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.addNewLink(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.checkVector(), and com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.removeLink().
fiducial2RAS
TransformNR com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.fiducial2RAS = new TransformNR() private
The fiducial2 ras.
Definition at line 88 of file AbstractKinematicsNR.java.
homeTime
long com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.homeTime private
This method uses the latch values to home the given link of the robot links.
Definition at line 1164 of file AbstractKinematicsNR.java.
imu
IMU com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.imu = new IMU() private
The object for communicating IMU information and registering it with the hardware
Definition at line 113 of file AbstractKinematicsNR.java.
jointSpaceUpdateListeners
ArrayList<IJointSpaceUpdateListenerNR> com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.jointSpaceUpdateListeners = new ArrayList<IJointSpaceUpdateListenerNR>() protected
The joint space update listeners.
Definition at line 58 of file AbstractKinematicsNR.java.
mobileBases
ArrayList<MobileBase> com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.mobileBases = new ArrayList<MobileBase>() private
The mobile bases.
Definition at line 64 of file AbstractKinematicsNR.java.
noFlush
boolean com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.noFlush = false private
The no flush.
Definition at line 91 of file AbstractKinematicsNR.java.
noXmlConfig
boolean com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.noXmlConfig = true private
The no xml config.
Definition at line 94 of file AbstractKinematicsNR.java.
pidConfigurations
ArrayList<PIDConfiguration> com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.pidConfigurations = new ArrayList<PIDConfiguration>() private
The configurations.
Definition at line 52 of file AbstractKinematicsNR.java.
regListeners
ArrayList<IRegistrationListenerNR> com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.regListeners = new ArrayList<IRegistrationListenerNR>() private
The reg listeners.
Definition at line 61 of file AbstractKinematicsNR.java.
renderWrangler
Runnable com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.renderWrangler =null private
Definition at line 115 of file AbstractKinematicsNR.java.
retryNumberBeforeFail
int com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.retryNumberBeforeFail = 5 private
The retry number before fail.
Definition at line 108 of file AbstractKinematicsNR.java.
root
Object com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.root private
The root.
Definition at line 100 of file AbstractKinematicsNR.java.
taskSpaceUpdateListeners
ArrayList<ITaskSpaceUpdateListenerNR> com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.taskSpaceUpdateListeners = new ArrayList<ITaskSpaceUpdateListenerNR>() private
The task space update listeners.
Definition at line 55 of file AbstractKinematicsNR.java.
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/addons/kinematics/AbstractKinematicsNR.java