BowlerKernel: com.neuronrobotics.sdk.bootloader.NRBoot.CoreLoader Class Reference
com.neuronrobotics.sdk.bootloader.NRBoot.CoreLoader Class Reference
Public Member Functions
CoreLoader (ArrayList< Core > cores)
void run ()
Public Attributes
boolean isDone =false
int val =0
Detailed Description
The Class CoreLoader.
Definition at line 177 of file NRBoot.java.
Constructor & Destructor Documentation
CoreLoader()
com.neuronrobotics.sdk.bootloader.NRBoot.CoreLoader.CoreLoader (ArrayList< Core > cores)
Instantiates a new core loader.
Parameters
cores the cores
Definition at line 193 of file NRBoot.java.
References com.neuronrobotics.sdk.bootloader.NRBoot.getParser(), com.neuronrobotics.sdk.bootloader.NRBoot.progressMax, com.neuronrobotics.sdk.bootloader.NRBoot.progressValue, and com.neuronrobotics.sdk.bootloader.IntelHexParser.size().
Member Function Documentation
run()
void com.neuronrobotics.sdk.bootloader.NRBoot.CoreLoader.run ()
Definition at line 205 of file NRBoot.java.
References com.neuronrobotics.sdk.bootloader.NRBoot.CoreLoader.isDone, com.neuronrobotics.sdk.bootloader.NRBoot.load(), com.neuronrobotics.sdk.bootloader.NRBoot.progressValue, com.neuronrobotics.sdk.bootloader.NRBoot.reset(), and com.neuronrobotics.sdk.bootloader.NRBoot.CoreLoader.val.
Member Data Documentation
isDone
boolean com.neuronrobotics.sdk.bootloader.NRBoot.CoreLoader.isDone =false
The is done.
Definition at line 183 of file NRBoot.java.
Referenced by com.neuronrobotics.sdk.bootloader.NRBoot.isLoadDone(), and com.neuronrobotics.sdk.bootloader.NRBoot.CoreLoader.run().
val
int com.neuronrobotics.sdk.bootloader.NRBoot.CoreLoader.val =0
The val.
Definition at line 186 of file NRBoot.java.
Referenced by com.neuronrobotics.sdk.bootloader.NRBoot.CoreLoader.run().
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/bootloader/NRBoot.java