BowlerKernel: com.neuronrobotics.bowlerstudio.lipsync.PhoneticDictionary Class Reference
com.neuronrobotics.bowlerstudio.lipsync.PhoneticDictionary Class Reference
Public Member Functions
PhoneticDictionary (File f) throws Exception
void init (File dictionaryUrl) throws Exception
ArrayList< String > find (String w)
Private Member Functions
String normalizePhonemes (String phonemes)
ArrayList< String > parseEntry (String entry, Map< String, ArrayList< String >> d)
Map< String, ArrayList< String > > parseDictionary (String dictionaryText)
String fetchDictionaryText (File dictionaryUrl) throws Exception
Private Attributes
Map< String, ArrayList< String > > dictionary
Detailed Description
Definition at line 14 of file PhoneticDictionary.java.
Constructor & Destructor Documentation
PhoneticDictionary()
com.neuronrobotics.bowlerstudio.lipsync.PhoneticDictionary.PhoneticDictionary (File f) throws Exception
Definition at line 17 of file PhoneticDictionary.java.
References com.neuronrobotics.bowlerstudio.lipsync.PhoneticDictionary.dictionary, and com.neuronrobotics.bowlerstudio.lipsync.PhoneticDictionary.init().
Member Function Documentation
fetchDictionaryText()
String com.neuronrobotics.bowlerstudio.lipsync.PhoneticDictionary.fetchDictionaryText (File dictionaryUrl) throws Exception private
Definition at line 68 of file PhoneticDictionary.java.
Referenced by com.neuronrobotics.bowlerstudio.lipsync.PhoneticDictionary.init().
find()
ArrayList<String> com.neuronrobotics.bowlerstudio.lipsync.PhoneticDictionary.find (String w)
Definition at line 84 of file PhoneticDictionary.java.
References com.neuronrobotics.bowlerstudio.lipsync.PhoneticDictionary.dictionary, com.neuronrobotics.bowlerstudio.AudioStatus.getFromPhoneme(), and com.neuronrobotics.bowlerstudio.AudioStatus.getPhonemes().
Referenced by com.neuronrobotics.bowlerstudio.lipsync.VoskLipSync.addWord().
init()
void com.neuronrobotics.bowlerstudio.lipsync.PhoneticDictionary.init (File dictionaryUrl) throws Exception
Definition at line 79 of file PhoneticDictionary.java.
References com.neuronrobotics.bowlerstudio.lipsync.PhoneticDictionary.dictionary, com.neuronrobotics.bowlerstudio.lipsync.PhoneticDictionary.fetchDictionaryText(), and com.neuronrobotics.bowlerstudio.lipsync.PhoneticDictionary.parseDictionary().
Referenced by com.neuronrobotics.bowlerstudio.lipsync.PhoneticDictionary.PhoneticDictionary().
normalizePhonemes()
String com.neuronrobotics.bowlerstudio.lipsync.PhoneticDictionary.normalizePhonemes (String phonemes) private
Definition at line 22 of file PhoneticDictionary.java.
Referenced by com.neuronrobotics.bowlerstudio.lipsync.PhoneticDictionary.parseEntry().
parseDictionary()
Map<String, ArrayList<String> > com.neuronrobotics.bowlerstudio.lipsync.PhoneticDictionary.parseDictionary (String dictionaryText) private
Definition at line 53 of file PhoneticDictionary.java.
References com.neuronrobotics.bowlerstudio.lipsync.PhoneticDictionary.dictionary, and com.neuronrobotics.bowlerstudio.lipsync.PhoneticDictionary.parseEntry().
Referenced by com.neuronrobotics.bowlerstudio.lipsync.PhoneticDictionary.init().
parseEntry()
ArrayList<String> com.neuronrobotics.bowlerstudio.lipsync.PhoneticDictionary.parseEntry (String entry, Map< String, ArrayList< String >> d) private
Definition at line 33 of file PhoneticDictionary.java.
References com.neuronrobotics.bowlerstudio.lipsync.PhoneticDictionary.normalizePhonemes().
Referenced by com.neuronrobotics.bowlerstudio.lipsync.PhoneticDictionary.parseDictionary().
Member Data Documentation
dictionary
Map<String, ArrayList<String> > com.neuronrobotics.bowlerstudio.lipsync.PhoneticDictionary.dictionary private
Definition at line 15 of file PhoneticDictionary.java.
Referenced by com.neuronrobotics.bowlerstudio.lipsync.PhoneticDictionary.find(), com.neuronrobotics.bowlerstudio.lipsync.PhoneticDictionary.init(), com.neuronrobotics.bowlerstudio.lipsync.PhoneticDictionary.parseDictionary(), and com.neuronrobotics.bowlerstudio.lipsync.PhoneticDictionary.PhoneticDictionary().
The documentation for this class was generated from the following file:
src/main/java/com/neuronrobotics/bowlerstudio/lipsync/PhoneticDictionary.java