BowlerKernel: com.neuronrobotics.sdk.addons.kinematics.DHLink Class Reference
com.neuronrobotics.sdk.addons.kinematics.DHLink Class Reference
Public Member Functions
DHLink (double d, double theta, double r, double alpha)
DHLink (Element nNode, LinkConfiguration newLinkConf)
DHLink (DHLink dhl)
void fireOnLinkGlobalPositionChange (TransformNR newPose)
void addDhLinkPositionListener (IDhLinkPositionListener l)
void removeDhLinkPositionListener (IDhLinkPositionListener l)
String getXml ()
double getD ()
double getTheta ()
double getR ()
double getAlpha ()
Matrix DhStepInverse (Matrix end, double jointValue)
Matrix DhStep (double jointValue)
Matrix DhStep (double rotory, double prismatic)
Matrix DhStepInverse (Matrix end, double rotory, double prismatic)
Matrix DhStepInverse (double rotory, double prismatic)
Matrix DhStepInversePrismatic (double prismatic)
Matrix DhStepInverseRotory (double rotory)
void setTransX (Matrix transX)
void setRotX (Matrix rotX)
Matrix getTransX ()
Matrix getRotX ()
Matrix getTransZ ()
Matrix getRotZ ()
Matrix DhStepJacobian (double rotoryVelocity, double prismaticVelocity)
Matrix getRotX_J ()
Matrix getTransX_J ()
Matrix getTransZ_J ()
Matrix getRotZ_J ()
String toString ()
Object getListener ()
void setListener (Object listener)
Object getRootListener ()
double getDelta ()
void setDelta (double d)
double getRadius ()
void setRadius (double radius)
void setTheta (double theta)
void setAlpha (double alpha)
DhLinkType getLinkType ()
void setLinkType (DhLinkType type)
void setMobileBaseXml (MobileBase embedableXml)
MobileBase getSlaveMobileBase ()
void setSlaveMobileBase (MobileBase embedableXml)
Private Member Functions
void setMatrix (double rotory, double prismatic)
void setJacobianMatrix (double rotory, double prismatic)
Private Attributes
double d
double theta
double radius
double alpha
Matrix transX
Matrix rotX
Matrix transZ
Matrix rotZ
Matrix transX_J
Matrix rotX_J
Matrix transZ_J
Matrix rotZ_J
Object listener =null
Object root =null
DhLinkType type = DhLinkType.ROTORY
ArrayList< IDhLinkPositionListener > dhlisteners = new ArrayList<IDhLinkPositionListener>()
MobileBase slaveMobileBase =null
LinkConfiguration newLinkConf
Detailed Description
The Class DHLink.
Definition at line 17 of file DHLink.java.
Constructor & Destructor Documentation
DHLink() [1/3]
com.neuronrobotics.sdk.addons.kinematics.DHLink.DHLink (double d, double theta, double r, double alpha)
Instantiates a new DH link.
Parameters
d the d
theta the theta
r the r
alpha the alpha
Definition at line 81 of file DHLink.java.
References com.neuronrobotics.sdk.addons.kinematics.DHLink.setAlpha(), com.neuronrobotics.sdk.addons.kinematics.DHLink.setDelta(), com.neuronrobotics.sdk.addons.kinematics.DHLink.setRadius(), and com.neuronrobotics.sdk.addons.kinematics.DHLink.setTheta().
DHLink() [2/3]
com.neuronrobotics.sdk.addons.kinematics.DHLink.DHLink (Element nNode, LinkConfiguration newLinkConf)
Instantiates a new DH link.
Parameters
nNode the n node
newLinkConf
Definition at line 95 of file DHLink.java.
References com.neuronrobotics.sdk.addons.kinematics.xml.XmlFactory.getTagValueDouble(), com.neuronrobotics.sdk.addons.kinematics.DHLink.newLinkConf, com.neuronrobotics.sdk.addons.kinematics.DHLink.setAlpha(), com.neuronrobotics.sdk.addons.kinematics.DHLink.setDelta(), com.neuronrobotics.sdk.addons.kinematics.DHLink.setRadius(), and com.neuronrobotics.sdk.addons.kinematics.DHLink.setTheta().
DHLink() [3/3]
com.neuronrobotics.sdk.addons.kinematics.DHLink.DHLink (DHLink dhl)
Definition at line 104 of file DHLink.java.
References com.neuronrobotics.sdk.addons.kinematics.DHLink.getAlpha(), com.neuronrobotics.sdk.addons.kinematics.DHLink.getDelta(), com.neuronrobotics.sdk.addons.kinematics.DHLink.getRadius(), com.neuronrobotics.sdk.addons.kinematics.DHLink.getTheta(), com.neuronrobotics.sdk.addons.kinematics.DHLink.setAlpha(), com.neuronrobotics.sdk.addons.kinematics.DHLink.setDelta(), com.neuronrobotics.sdk.addons.kinematics.DHLink.setRadius(), and com.neuronrobotics.sdk.addons.kinematics.DHLink.setTheta().
Member Function Documentation
addDhLinkPositionListener()
void com.neuronrobotics.sdk.addons.kinematics.DHLink.addDhLinkPositionListener (IDhLinkPositionListener l)
Adds the dh link position listener.
Parameters
l the l
Definition at line 129 of file DHLink.java.
References com.neuronrobotics.sdk.addons.kinematics.DHLink.dhlisteners.
DhStep() [1/2]
Matrix com.neuronrobotics.sdk.addons.kinematics.DHLink.DhStep (double jointValue)
Dh step prismatic.
Parameters
jointValue the joint value
Returns
the matrix
Definition at line 227 of file DHLink.java.
References com.neuronrobotics.sdk.addons.kinematics.DHLink.type.
DhStep() [2/2]
Matrix com.neuronrobotics.sdk.addons.kinematics.DHLink.DhStep (double rotory, double prismatic)
Dh step.
Parameters
rotory the rotory
prismatic the prismatic
Returns
the matrix
Definition at line 247 of file DHLink.java.
References com.neuronrobotics.sdk.addons.kinematics.DHLink.getRotX(), com.neuronrobotics.sdk.addons.kinematics.DHLink.getRotZ(), com.neuronrobotics.sdk.addons.kinematics.DHLink.getTransX(), com.neuronrobotics.sdk.addons.kinematics.DHLink.getTransZ(), and com.neuronrobotics.sdk.addons.kinematics.DHLink.setMatrix().
DhStepInverse() [1/3]
Matrix com.neuronrobotics.sdk.addons.kinematics.DHLink.DhStepInverse (double rotory, double prismatic)
Dh step inverse.
Parameters
rotory the rotory
prismatic the prismatic
Returns
the matrix
Definition at line 286 of file DHLink.java.
References com.neuronrobotics.sdk.addons.kinematics.DHLink.DhStepInverse(), and com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getMatrixTransform().
DhStepInverse() [2/3]
Matrix com.neuronrobotics.sdk.addons.kinematics.DHLink.DhStepInverse (Matrix end, double jointValue)
Dh step inverse .
Parameters
end the end
jointValue the joint value
Returns
the matrix
Definition at line 208 of file DHLink.java.
References com.neuronrobotics.sdk.addons.kinematics.DHLink.type.
Referenced by com.neuronrobotics.sdk.addons.kinematics.DHLink.DhStepInverse(), com.neuronrobotics.sdk.addons.kinematics.DHLink.DhStepInversePrismatic(), and com.neuronrobotics.sdk.addons.kinematics.DHLink.DhStepInverseRotory().
DhStepInverse() [3/3]
Matrix com.neuronrobotics.sdk.addons.kinematics.DHLink.DhStepInverse (Matrix end, double rotory, double prismatic)
Dh step inverse.
Parameters
end the end
rotory the rotory
prismatic the prismatic
Returns
the matrix
Definition at line 268 of file DHLink.java.
References com.neuronrobotics.sdk.addons.kinematics.DHLink.getRotX(), com.neuronrobotics.sdk.addons.kinematics.DHLink.getRotZ(), com.neuronrobotics.sdk.addons.kinematics.DHLink.getTransX(), com.neuronrobotics.sdk.addons.kinematics.DHLink.getTransZ(), and com.neuronrobotics.sdk.addons.kinematics.DHLink.setMatrix().
DhStepInversePrismatic()
Matrix com.neuronrobotics.sdk.addons.kinematics.DHLink.DhStepInversePrismatic (double prismatic)
Dh step inverse.
Parameters
prismatic the prismatic
Returns
the matrix
Definition at line 300 of file DHLink.java.
References com.neuronrobotics.sdk.addons.kinematics.DHLink.DhStepInverse().
Referenced by com.neuronrobotics.bowlerstudio.physics.MobileBasePhysicsManager.MobileBasePhysicsManager().
DhStepInverseRotory()
Matrix com.neuronrobotics.sdk.addons.kinematics.DHLink.DhStepInverseRotory (double rotory)
Dh step inverse.
Parameters
rotory the rotory
Returns
the matrix
Definition at line 312 of file DHLink.java.
References com.neuronrobotics.sdk.addons.kinematics.DHLink.DhStepInverse().
Referenced by com.neuronrobotics.bowlerstudio.physics.MobileBasePhysicsManager.MobileBasePhysicsManager().
DhStepJacobian()
Matrix com.neuronrobotics.sdk.addons.kinematics.DHLink.DhStepJacobian (double rotoryVelocity, double prismaticVelocity)
Gets a jacobian matrix of this link.
Parameters
rotoryVelocity the rotory velocity
prismaticVelocity the prismatic velocity
Returns
the Jacobian
Definition at line 413 of file DHLink.java.
References com.neuronrobotics.sdk.addons.kinematics.DHLink.getRotX_J(), com.neuronrobotics.sdk.addons.kinematics.DHLink.getRotZ_J(), com.neuronrobotics.sdk.addons.kinematics.DHLink.getTransX_J(), com.neuronrobotics.sdk.addons.kinematics.DHLink.getTransZ_J(), and com.neuronrobotics.sdk.addons.kinematics.DHLink.setJacobianMatrix().
fireOnLinkGlobalPositionChange()
void com.neuronrobotics.sdk.addons.kinematics.DHLink.fireOnLinkGlobalPositionChange (TransformNR newPose)
Fire on link global position change.
Parameters
newPose the new pose
Definition at line 116 of file DHLink.java.
References com.neuronrobotics.sdk.addons.kinematics.DHLink.dhlisteners, com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.setGlobalToFiducialTransform(), and com.neuronrobotics.sdk.addons.kinematics.DHLink.slaveMobileBase.
Referenced by com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.onJointSpaceUpdate().
getAlpha()
double com.neuronrobotics.sdk.addons.kinematics.DHLink.getAlpha ()
Gets the alpha.
Returns
the alpha
Definition at line 196 of file DHLink.java.
References com.neuronrobotics.sdk.addons.kinematics.DHLink.alpha.
Referenced by com.neuronrobotics.sdk.addons.kinematics.DHLink.DHLink(), com.neuronrobotics.sdk.addons.kinematics.DHLink.getRotX(), com.neuronrobotics.sdk.addons.kinematics.DHLink.getRotX_J(), and com.neuronrobotics.sdk.addons.kinematics.DHLink.toString().
getD()
double com.neuronrobotics.sdk.addons.kinematics.DHLink.getD ()
Gets the d.
Returns
the d
Definition at line 169 of file DHLink.java.
References com.neuronrobotics.sdk.addons.kinematics.DHLink.getDelta().
Referenced by com.neuronrobotics.sdk.addons.kinematics.DHLink.setJacobianMatrix(), and com.neuronrobotics.sdk.addons.kinematics.DHLink.setMatrix().
getDelta()
double com.neuronrobotics.sdk.addons.kinematics.DHLink.getDelta ()
Gets the delta.
Returns
the delta
Definition at line 551 of file DHLink.java.
References com.neuronrobotics.sdk.addons.kinematics.DHLink.d.
Referenced by com.neuronrobotics.sdk.addons.kinematics.DHLink.DHLink(), com.neuronrobotics.sdk.addons.kinematics.DHLink.getD(), and com.neuronrobotics.sdk.addons.kinematics.DHLink.toString().
getLinkType()
DhLinkType com.neuronrobotics.sdk.addons.kinematics.DHLink.getLinkType ()
Checks if is degenerate.
Returns
true, if is degenerate
Definition at line 613 of file DHLink.java.
References com.neuronrobotics.sdk.addons.kinematics.DHLink.type.
getListener()
Object com.neuronrobotics.sdk.addons.kinematics.DHLink.getListener ()
Gets the listener.
Returns
the listener
Definition at line 515 of file DHLink.java.
References com.neuronrobotics.sdk.addons.kinematics.DHLink.listener.
Referenced by com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.addNewLink(), and com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.updateLimb().
getR()
double com.neuronrobotics.sdk.addons.kinematics.DHLink.getR ()
Gets the r.
Returns
the r
Definition at line 187 of file DHLink.java.
References com.neuronrobotics.sdk.addons.kinematics.DHLink.getRadius().
Referenced by com.neuronrobotics.sdk.addons.kinematics.DHLink.getTransX(), and com.neuronrobotics.sdk.addons.kinematics.DHLink.getTransX_J().
getRadius()
double com.neuronrobotics.sdk.addons.kinematics.DHLink.getRadius ()
Gets the radius.
Returns
the radius
Definition at line 570 of file DHLink.java.
References com.neuronrobotics.sdk.addons.kinematics.DHLink.radius.
Referenced by com.neuronrobotics.sdk.addons.kinematics.DHLink.DHLink(), com.neuronrobotics.sdk.addons.kinematics.DHLink.getR(), and com.neuronrobotics.sdk.addons.kinematics.DHLink.toString().
getRootListener()
Object com.neuronrobotics.sdk.addons.kinematics.DHLink.getRootListener ()
Gets the root listener.
Returns
the root listener
Definition at line 533 of file DHLink.java.
References com.neuronrobotics.sdk.addons.kinematics.DHLink.root.
getRotX()
Matrix com.neuronrobotics.sdk.addons.kinematics.DHLink.getRotX ()
Gets the rot x.
Returns
the rot x
Definition at line 377 of file DHLink.java.
References com.neuronrobotics.sdk.addons.kinematics.DHLink.getAlpha(), and com.neuronrobotics.sdk.addons.kinematics.DHLink.rotX.
Referenced by com.neuronrobotics.sdk.addons.kinematics.DHLink.DhStep(), and com.neuronrobotics.sdk.addons.kinematics.DHLink.DhStepInverse().
getRotX_J()
Matrix com.neuronrobotics.sdk.addons.kinematics.DHLink.getRotX_J ()
Gets the rot x_ j.
Returns
the rot x_ j
Definition at line 450 of file DHLink.java.
References com.neuronrobotics.sdk.addons.kinematics.DHLink.getAlpha(), and com.neuronrobotics.sdk.addons.kinematics.DHLink.rotX_J.
Referenced by com.neuronrobotics.sdk.addons.kinematics.DHLink.DhStepJacobian().
getRotZ()
Matrix com.neuronrobotics.sdk.addons.kinematics.DHLink.getRotZ ()
Gets the rot z.
Returns
the rot z
Definition at line 402 of file DHLink.java.
References com.neuronrobotics.sdk.addons.kinematics.DHLink.rotZ.
Referenced by com.neuronrobotics.sdk.addons.kinematics.DHLink.DhStep(), and com.neuronrobotics.sdk.addons.kinematics.DHLink.DhStepInverse().
getRotZ_J()
Matrix com.neuronrobotics.sdk.addons.kinematics.DHLink.getRotZ_J ()
Gets the rot z_ j.
Returns
the rot z_ j
Definition at line 493 of file DHLink.java.
References com.neuronrobotics.sdk.addons.kinematics.DHLink.rotZ_J.
Referenced by com.neuronrobotics.sdk.addons.kinematics.DHLink.DhStepJacobian().
getSlaveMobileBase()
MobileBase com.neuronrobotics.sdk.addons.kinematics.DHLink.getSlaveMobileBase ()
Definition at line 635 of file DHLink.java.
References com.neuronrobotics.sdk.addons.kinematics.DHLink.slaveMobileBase.
Referenced by com.neuronrobotics.sdk.addons.kinematics.MobileBase.addListeners(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.generateCad(), com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getSlaveMobileBase(), and com.neuronrobotics.sdk.addons.kinematics.DHLink.getXml().
getTheta()
double com.neuronrobotics.sdk.addons.kinematics.DHLink.getTheta ()
Gets the theta.
Returns
the theta
Definition at line 178 of file DHLink.java.
References com.neuronrobotics.sdk.addons.kinematics.DHLink.theta.
Referenced by com.neuronrobotics.sdk.addons.kinematics.DHLink.DHLink(), com.neuronrobotics.sdk.addons.kinematics.DHLink.setJacobianMatrix(), com.neuronrobotics.sdk.addons.kinematics.DHLink.setMatrix(), and com.neuronrobotics.sdk.addons.kinematics.DHLink.toString().
getTransX()
Matrix com.neuronrobotics.sdk.addons.kinematics.DHLink.getTransX ()
Gets the trans x.
Returns
the trans x
Definition at line 361 of file DHLink.java.
References com.neuronrobotics.sdk.addons.kinematics.DHLink.getR(), and com.neuronrobotics.sdk.addons.kinematics.DHLink.transX.
Referenced by com.neuronrobotics.sdk.addons.kinematics.DHLink.DhStep(), and com.neuronrobotics.sdk.addons.kinematics.DHLink.DhStepInverse().
getTransX_J()
Matrix com.neuronrobotics.sdk.addons.kinematics.DHLink.getTransX_J ()
Gets the trans x_ j.
Returns
the trans x_ j
Definition at line 466 of file DHLink.java.
References com.neuronrobotics.sdk.addons.kinematics.DHLink.getR(), and com.neuronrobotics.sdk.addons.kinematics.DHLink.transX_J.
Referenced by com.neuronrobotics.sdk.addons.kinematics.DHLink.DhStepJacobian().
getTransZ()
Matrix com.neuronrobotics.sdk.addons.kinematics.DHLink.getTransZ ()
Gets the trans z.
Returns
the trans z
Definition at line 393 of file DHLink.java.
References com.neuronrobotics.sdk.addons.kinematics.DHLink.transZ.
Referenced by com.neuronrobotics.sdk.addons.kinematics.DHLink.DhStep(), and com.neuronrobotics.sdk.addons.kinematics.DHLink.DhStepInverse().
getTransZ_J()
Matrix com.neuronrobotics.sdk.addons.kinematics.DHLink.getTransZ_J ()
Gets the trans z_ j.
Returns
the trans z_ j
Definition at line 484 of file DHLink.java.
References com.neuronrobotics.sdk.addons.kinematics.DHLink.transZ_J.
Referenced by com.neuronrobotics.sdk.addons.kinematics.DHLink.DhStepJacobian().
getXml()
String com.neuronrobotics.sdk.addons.kinematics.DHLink.getXml ()
Gets the xml.
Returns
the xml
Definition at line 153 of file DHLink.java.
References com.neuronrobotics.sdk.addons.kinematics.DHLink.alpha, com.neuronrobotics.sdk.addons.kinematics.DHLink.d, com.neuronrobotics.sdk.addons.kinematics.MobileBase.getEmbedableXml(), com.neuronrobotics.sdk.addons.kinematics.DHLink.getSlaveMobileBase(), com.neuronrobotics.sdk.addons.kinematics.DHLink.radius, and com.neuronrobotics.sdk.addons.kinematics.DHLink.theta.
removeDhLinkPositionListener()
void com.neuronrobotics.sdk.addons.kinematics.DHLink.removeDhLinkPositionListener (IDhLinkPositionListener l)
Removes the dh link position listener.
Parameters
l the l
Definition at line 139 of file DHLink.java.
References com.neuronrobotics.sdk.addons.kinematics.DHLink.dhlisteners.
setAlpha()
void com.neuronrobotics.sdk.addons.kinematics.DHLink.setAlpha (double alpha)
Sets the alpha.
Parameters
alpha the new alpha
Definition at line 601 of file DHLink.java.
References com.neuronrobotics.sdk.addons.kinematics.DHLink.alpha, com.neuronrobotics.sdk.addons.kinematics.DHLink.newLinkConf, com.neuronrobotics.sdk.addons.kinematics.DHLink.rotX, and com.neuronrobotics.sdk.addons.kinematics.DHLink.rotX_J.
Referenced by com.neuronrobotics.sdk.addons.kinematics.DHLink.DHLink().
setDelta()
void com.neuronrobotics.sdk.addons.kinematics.DHLink.setDelta (double d)
Sets the delta.
Parameters
d the new delta
Definition at line 560 of file DHLink.java.
References com.neuronrobotics.sdk.addons.kinematics.DHLink.d, and com.neuronrobotics.sdk.addons.kinematics.DHLink.newLinkConf.
Referenced by com.neuronrobotics.sdk.addons.kinematics.DHLink.DHLink().
setJacobianMatrix()
void com.neuronrobotics.sdk.addons.kinematics.DHLink.setJacobianMatrix (double rotory, double prismatic) private
Sets up the 2 alterable Jacobian matrixs .
Parameters
rotory the rotory velocity of the Theta link
prismatic the linear velocity of the D link
Definition at line 431 of file DHLink.java.
References com.neuronrobotics.sdk.addons.kinematics.DHLink.getD(), com.neuronrobotics.sdk.addons.kinematics.DHLink.getTheta(), com.neuronrobotics.sdk.addons.kinematics.DHLink.rotZ_J, and com.neuronrobotics.sdk.addons.kinematics.DHLink.transZ_J.
Referenced by com.neuronrobotics.sdk.addons.kinematics.DHLink.DhStepJacobian().
setLinkType()
void com.neuronrobotics.sdk.addons.kinematics.DHLink.setLinkType (DhLinkType type)
Sets the type.
Parameters
type the new type
Definition at line 622 of file DHLink.java.
References com.neuronrobotics.sdk.addons.kinematics.DHLink.type.
Referenced by com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.addNewLink().
setListener()
void com.neuronrobotics.sdk.addons.kinematics.DHLink.setListener (Object listener)
Sets the listener.
Parameters
listener the new listener
Definition at line 524 of file DHLink.java.
References com.neuronrobotics.sdk.addons.kinematics.DHLink.listener.
Referenced by com.neuronrobotics.bowlerstudio.scripting.RobotHelper.getDefaultContents(), and com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.updateLimb().
setMatrix()
void com.neuronrobotics.sdk.addons.kinematics.DHLink.setMatrix (double rotory, double prismatic) private
Sets the matrix.
Parameters
rotory the rotory
prismatic the prismatic
Definition at line 342 of file DHLink.java.
References com.neuronrobotics.sdk.addons.kinematics.DHLink.getD(), com.neuronrobotics.sdk.addons.kinematics.DHLink.getTheta(), com.neuronrobotics.sdk.addons.kinematics.DHLink.rotZ, and com.neuronrobotics.sdk.addons.kinematics.DHLink.transZ.
Referenced by com.neuronrobotics.sdk.addons.kinematics.DHLink.DhStep(), and com.neuronrobotics.sdk.addons.kinematics.DHLink.DhStepInverse().
setMobileBaseXml()
void com.neuronrobotics.sdk.addons.kinematics.DHLink.setMobileBaseXml (MobileBase embedableXml)
Sets the mobile base xml.
Parameters
embedableXml the new mobile base xml
Definition at line 631 of file DHLink.java.
References com.neuronrobotics.sdk.addons.kinematics.DHLink.setSlaveMobileBase().
Referenced by com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.loadConfig().
setRadius()
void com.neuronrobotics.sdk.addons.kinematics.DHLink.setRadius (double radius)
Sets the radius.
Parameters
radius the new radius
Definition at line 579 of file DHLink.java.
References com.neuronrobotics.sdk.addons.kinematics.DHLink.newLinkConf, com.neuronrobotics.sdk.addons.kinematics.DHLink.radius, com.neuronrobotics.sdk.addons.kinematics.DHLink.transX, and com.neuronrobotics.sdk.addons.kinematics.DHLink.transX_J.
Referenced by com.neuronrobotics.sdk.addons.kinematics.DHLink.DHLink().
setRotX()
void com.neuronrobotics.sdk.addons.kinematics.DHLink.setRotX (Matrix rotX)
Sets the rot x.
Parameters
rotX the new rot x
Definition at line 331 of file DHLink.java.
References com.neuronrobotics.sdk.addons.kinematics.DHLink.rotX.
setSlaveMobileBase()
void com.neuronrobotics.sdk.addons.kinematics.DHLink.setSlaveMobileBase (MobileBase embedableXml)
Definition at line 639 of file DHLink.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.DHLink.setMobileBaseXml().
setTheta()
void com.neuronrobotics.sdk.addons.kinematics.DHLink.setTheta (double theta)
Sets the theta.
Parameters
theta the new theta
Definition at line 591 of file DHLink.java.
References com.neuronrobotics.sdk.addons.kinematics.DHLink.newLinkConf, and com.neuronrobotics.sdk.addons.kinematics.DHLink.theta.
Referenced by com.neuronrobotics.sdk.addons.kinematics.DHLink.DHLink().
setTransX()
void com.neuronrobotics.sdk.addons.kinematics.DHLink.setTransX (Matrix transX)
Sets the trans x.
Parameters
transX the new trans x
Definition at line 322 of file DHLink.java.
References com.neuronrobotics.sdk.addons.kinematics.DHLink.transX.
toString()
String com.neuronrobotics.sdk.addons.kinematics.DHLink.toString ()
Definition at line 501 of file DHLink.java.
References com.neuronrobotics.sdk.addons.kinematics.DHLink.getAlpha(), com.neuronrobotics.sdk.addons.kinematics.DHLink.getDelta(), com.neuronrobotics.sdk.addons.kinematics.DHLink.getRadius(), and com.neuronrobotics.sdk.addons.kinematics.DHLink.getTheta().
Member Data Documentation
alpha
double com.neuronrobotics.sdk.addons.kinematics.DHLink.alpha private
The alpha.
Definition at line 29 of file DHLink.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.DHLink.getAlpha(), com.neuronrobotics.sdk.addons.kinematics.DHLink.getXml(), and com.neuronrobotics.sdk.addons.kinematics.DHLink.setAlpha().
d
double com.neuronrobotics.sdk.addons.kinematics.DHLink.d private
The d.
Definition at line 20 of file DHLink.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.DHLink.getDelta(), com.neuronrobotics.sdk.addons.kinematics.DHLink.getXml(), and com.neuronrobotics.sdk.addons.kinematics.DHLink.setDelta().
dhlisteners
ArrayList<IDhLinkPositionListener> com.neuronrobotics.sdk.addons.kinematics.DHLink.dhlisteners = new ArrayList<IDhLinkPositionListener>() private
The dhlisteners.
Definition at line 65 of file DHLink.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.DHLink.addDhLinkPositionListener(), com.neuronrobotics.sdk.addons.kinematics.DHLink.fireOnLinkGlobalPositionChange(), and com.neuronrobotics.sdk.addons.kinematics.DHLink.removeDhLinkPositionListener().
listener
Object com.neuronrobotics.sdk.addons.kinematics.DHLink.listener =null private
The listener.
Definition at line 56 of file DHLink.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.DHLink.getListener(), and com.neuronrobotics.sdk.addons.kinematics.DHLink.setListener().
newLinkConf
LinkConfiguration com.neuronrobotics.sdk.addons.kinematics.DHLink.newLinkConf private
Definition at line 70 of file DHLink.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.DHLink.DHLink(), com.neuronrobotics.sdk.addons.kinematics.DHLink.setAlpha(), com.neuronrobotics.sdk.addons.kinematics.DHLink.setDelta(), com.neuronrobotics.sdk.addons.kinematics.DHLink.setRadius(), and com.neuronrobotics.sdk.addons.kinematics.DHLink.setTheta().
radius
double com.neuronrobotics.sdk.addons.kinematics.DHLink.radius private
The radius.
Definition at line 26 of file DHLink.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.DHLink.getRadius(), com.neuronrobotics.sdk.addons.kinematics.DHLink.getXml(), and com.neuronrobotics.sdk.addons.kinematics.DHLink.setRadius().
root
Object com.neuronrobotics.sdk.addons.kinematics.DHLink.root =null private
The root.
Definition at line 59 of file DHLink.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.DHLink.getRootListener().
rotX
Matrix com.neuronrobotics.sdk.addons.kinematics.DHLink.rotX private
The rot x.
Definition at line 35 of file DHLink.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.DHLink.getRotX(), com.neuronrobotics.sdk.addons.kinematics.DHLink.setAlpha(), and com.neuronrobotics.sdk.addons.kinematics.DHLink.setRotX().
rotX_J
Matrix com.neuronrobotics.sdk.addons.kinematics.DHLink.rotX_J private
The rot x_ j.
Definition at line 47 of file DHLink.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.DHLink.getRotX_J(), and com.neuronrobotics.sdk.addons.kinematics.DHLink.setAlpha().
rotZ
Matrix com.neuronrobotics.sdk.addons.kinematics.DHLink.rotZ private
The rot z.
Definition at line 41 of file DHLink.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.DHLink.getRotZ(), and com.neuronrobotics.sdk.addons.kinematics.DHLink.setMatrix().
rotZ_J
Matrix com.neuronrobotics.sdk.addons.kinematics.DHLink.rotZ_J private
The rot z_ j.
Definition at line 53 of file DHLink.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.DHLink.getRotZ_J(), and com.neuronrobotics.sdk.addons.kinematics.DHLink.setJacobianMatrix().
slaveMobileBase
MobileBase com.neuronrobotics.sdk.addons.kinematics.DHLink.slaveMobileBase =null private
The embedable xml.
Definition at line 68 of file DHLink.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.DHLink.fireOnLinkGlobalPositionChange(), and com.neuronrobotics.sdk.addons.kinematics.DHLink.getSlaveMobileBase().
theta
double com.neuronrobotics.sdk.addons.kinematics.DHLink.theta private
The theta.
Definition at line 23 of file DHLink.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.DHLink.getTheta(), com.neuronrobotics.sdk.addons.kinematics.DHLink.getXml(), and com.neuronrobotics.sdk.addons.kinematics.DHLink.setTheta().
transX
Matrix com.neuronrobotics.sdk.addons.kinematics.DHLink.transX private
The trans x.
Definition at line 32 of file DHLink.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.DHLink.getTransX(), com.neuronrobotics.sdk.addons.kinematics.DHLink.setRadius(), and com.neuronrobotics.sdk.addons.kinematics.DHLink.setTransX().
transX_J
Matrix com.neuronrobotics.sdk.addons.kinematics.DHLink.transX_J private
The trans x_ j.
Definition at line 44 of file DHLink.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.DHLink.getTransX_J(), and com.neuronrobotics.sdk.addons.kinematics.DHLink.setRadius().
transZ
Matrix com.neuronrobotics.sdk.addons.kinematics.DHLink.transZ private
The trans z.
Definition at line 38 of file DHLink.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.DHLink.getTransZ(), and com.neuronrobotics.sdk.addons.kinematics.DHLink.setMatrix().
transZ_J
Matrix com.neuronrobotics.sdk.addons.kinematics.DHLink.transZ_J private
The trans z_ j.
Definition at line 50 of file DHLink.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.DHLink.getTransZ_J(), and com.neuronrobotics.sdk.addons.kinematics.DHLink.setJacobianMatrix().
type
DhLinkType com.neuronrobotics.sdk.addons.kinematics.DHLink.type = DhLinkType.ROTORY private
The type.
Definition at line 62 of file DHLink.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.DHLink.DhStep(), com.neuronrobotics.sdk.addons.kinematics.DHLink.DhStepInverse(), com.neuronrobotics.sdk.addons.kinematics.DHLink.getLinkType(), and com.neuronrobotics.sdk.addons.kinematics.DHLink.setLinkType().
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/addons/kinematics/DHLink.java