BowlerKernel: com.neuronrobotics.bowlerstudio.scripting.PasswordManager Class Reference
com.neuronrobotics.bowlerstudio.scripting.PasswordManager Class Reference
Static Public Member Functions
static void checkInternet ()
static String getPassword ()
static GitHub getGithub ()
static void setGithub (GitHub g)
static String getUsername ()
static synchronized void login () throws IOException
static void waitForLogin () throws Exception
static boolean loggedIn ()
static boolean hasStoredCredentials ()
static boolean hasStoredToken ()
static void logout () throws IOException
static GitHub setupAnyonmous () throws IOException
static IGitHubLoginManager getLoginManager ()
static void setLoginManager (IGitHubLoginManager lm)
static void loadLoginData (File ws) throws Exception
static CredentialsProvider getCredentialProvider ()
static boolean hasNetwork ()
static String getLoginID ()
static File getWorkspace ()
static void setWorkspace (File workspace)
static File getUsernamefile ()
static File getPassfile ()
static File getTokenfile ()
static boolean isAnonMode ()
static List< String > getListOfScopes ()
static void setListOfScopes (List< String > listOfScopes)
Static Private Member Functions
static void performLogin (String u, String p) throws Exception
static KeysetHandle getKey () throws IOException
static void writeData (String user, String passcleartext) throws Exception
static void writeToken (String user, String passcleartext) throws Exception
static void setCredentialProvider (CredentialsProvider cp)
static void setLoginID (String loginID)
static void setAnonMode (boolean isAnonMode)
Static Private Attributes
static IGitHubLoginManager loginManager =null
static IGitHubLoginManager loginWebFlow = new GitHubWebFlow()
static List< String > listOfScopes
static IGitHubLoginManager loginHeadless
static File workspace = null
static String loginID = null
static String pw = null
static CredentialsProvider cp
static GitHub github
static boolean hasnetwork
static boolean isLoggedIn = false
static boolean isAnonMode = false
Detailed Description
Definition at line 33 of file PasswordManager.java.
Member Function Documentation
checkInternet()
static void com.neuronrobotics.bowlerstudio.scripting.PasswordManager.checkInternet () static
Definition at line 124 of file PasswordManager.java.
References com.neuronrobotics.bowlerstudio.scripting.PasswordManager.hasnetwork.
Referenced by com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.checkout(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.cloneRepo(), com.neuronrobotics.bowlerstudio.scripting.PasswordManager.login(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.pull(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.resolveConflict().
getCredentialProvider()
static CredentialsProvider com.neuronrobotics.bowlerstudio.scripting.PasswordManager.getCredentialProvider () static
Definition at line 437 of file PasswordManager.java.
References com.neuronrobotics.bowlerstudio.scripting.PasswordManager.cp.
Referenced by com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.checkOwner(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.cloneRepoLocalSelectAuth(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.deleteBranch(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.fork(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getAllBranches(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.newBranchLocal(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.pull(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.pushCodeToGit(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.tagRepo().
getGithub()
static GitHub com.neuronrobotics.bowlerstudio.scripting.PasswordManager.getGithub () static
Definition at line 153 of file PasswordManager.java.
References com.neuronrobotics.bowlerstudio.scripting.PasswordManager.github.
Referenced by com.neuronrobotics.bowlerstudio.IssueReportingExceptionHandler.except(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.fork(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.forkGist(), com.neuronrobotics.bowlerstudio.vitamins.Vitamins.getGitRepoDatabase(), com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.getGitSource(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getUserIdOfGist(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.makeNewRepo(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.makeNewRepoNoFailOver(), com.neuronrobotics.bowlerstudio.vitamins.Vitamins.saveDatabaseForkIfMissing(), and com.neuronrobotics.bowlerstudio.scripting.PasswordManager.setupAnyonmous().
getKey()
static KeysetHandle com.neuronrobotics.bowlerstudio.scripting.PasswordManager.getKey () throws IOException static private
Definition at line 379 of file PasswordManager.java.
References com.neuronrobotics.bowlerstudio.scripting.PasswordManager.getWorkspace().
Referenced by com.neuronrobotics.bowlerstudio.scripting.PasswordManager.loadLoginData(), com.neuronrobotics.bowlerstudio.scripting.PasswordManager.performLogin(), com.neuronrobotics.bowlerstudio.scripting.PasswordManager.writeData(), and com.neuronrobotics.bowlerstudio.scripting.PasswordManager.writeToken().
getListOfScopes()
static List<String> com.neuronrobotics.bowlerstudio.scripting.PasswordManager.getListOfScopes () static
Definition at line 490 of file PasswordManager.java.
References com.neuronrobotics.bowlerstudio.scripting.PasswordManager.listOfScopes.
Referenced by com.neuronrobotics.bowlerstudio.scripting.GitHubWebFlow.doStepOne().
getLoginID()
static String com.neuronrobotics.bowlerstudio.scripting.PasswordManager.getLoginID () static
Definition at line 449 of file PasswordManager.java.
References com.neuronrobotics.bowlerstudio.scripting.PasswordManager.loginID.
Referenced by com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.fork(), com.neuronrobotics.bowlerstudio.vitamins.Vitamins.getGitRepoDatabase(), com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.getGitSource(), com.neuronrobotics.bowlerstudio.scripting.PasswordManager.getUsername(), com.neuronrobotics.bowlerstudio.scripting.PasswordManager.loadLoginData(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.makeNewRepo(), com.neuronrobotics.bowlerstudio.scripting.PasswordManager.waitForLogin(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.waitForLogin().
getLoginManager()
static IGitHubLoginManager com.neuronrobotics.bowlerstudio.scripting.PasswordManager.getLoginManager () static
Definition at line 334 of file PasswordManager.java.
References com.neuronrobotics.bowlerstudio.scripting.PasswordManager.loginHeadless, com.neuronrobotics.bowlerstudio.scripting.PasswordManager.loginManager, and com.neuronrobotics.bowlerstudio.scripting.PasswordManager.loginWebFlow.
Referenced by com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getLoginManager(), and com.neuronrobotics.bowlerstudio.scripting.PasswordManager.login().
getPassfile()
static File com.neuronrobotics.bowlerstudio.scripting.PasswordManager.getPassfile () static
Definition at line 472 of file PasswordManager.java.
References com.neuronrobotics.bowlerstudio.scripting.PasswordManager.getWorkspace().
Referenced by com.neuronrobotics.bowlerstudio.scripting.PasswordManager.hasStoredCredentials(), com.neuronrobotics.bowlerstudio.scripting.PasswordManager.loadLoginData(), com.neuronrobotics.bowlerstudio.scripting.PasswordManager.logout(), and com.neuronrobotics.bowlerstudio.scripting.PasswordManager.writeData().
getPassword()
static String com.neuronrobotics.bowlerstudio.scripting.PasswordManager.getPassword () static
Definition at line 149 of file PasswordManager.java.
References com.neuronrobotics.bowlerstudio.scripting.PasswordManager.pw.
Referenced by com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.waitForLogin().
getTokenfile()
static File com.neuronrobotics.bowlerstudio.scripting.PasswordManager.getTokenfile () static
Definition at line 477 of file PasswordManager.java.
References com.neuronrobotics.bowlerstudio.scripting.PasswordManager.getWorkspace().
Referenced by com.neuronrobotics.bowlerstudio.scripting.PasswordManager.hasStoredToken(), com.neuronrobotics.bowlerstudio.scripting.PasswordManager.logout(), com.neuronrobotics.bowlerstudio.scripting.PasswordManager.performLogin(), and com.neuronrobotics.bowlerstudio.scripting.PasswordManager.writeToken().
getUsername()
static String com.neuronrobotics.bowlerstudio.scripting.PasswordManager.getUsername () static
Definition at line 161 of file PasswordManager.java.
References com.neuronrobotics.bowlerstudio.scripting.PasswordManager.getLoginID().
Referenced by com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.commit(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.forkGist(), com.neuronrobotics.bowlerstudio.vitamins.Vitamins.getGitRepoDatabase(), com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.getGitSource(), com.neuronrobotics.bowlerstudio.scripting.PasswordManager.login(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.login(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.logout(), com.neuronrobotics.bowlerstudio.vitamins.Vitamins.processSelfPR(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.pushCodeToGit(), com.neuronrobotics.bowlerstudio.vitamins.Vitamins.saveDatabase(), and com.neuronrobotics.bowlerstudio.vitamins.Vitamins.saveDatabaseForkIfMissing().
getUsernamefile()
static File com.neuronrobotics.bowlerstudio.scripting.PasswordManager.getUsernamefile () static
Definition at line 468 of file PasswordManager.java.
References com.neuronrobotics.bowlerstudio.scripting.PasswordManager.getWorkspace().
Referenced by com.neuronrobotics.bowlerstudio.scripting.PasswordManager.hasStoredCredentials(), com.neuronrobotics.bowlerstudio.scripting.PasswordManager.hasStoredToken(), com.neuronrobotics.bowlerstudio.scripting.PasswordManager.loadLoginData(), com.neuronrobotics.bowlerstudio.scripting.PasswordManager.writeData(), and com.neuronrobotics.bowlerstudio.scripting.PasswordManager.writeToken().
getWorkspace()
static File com.neuronrobotics.bowlerstudio.scripting.PasswordManager.getWorkspace () static
Definition at line 458 of file PasswordManager.java.
References com.neuronrobotics.bowlerstudio.scripting.PasswordManager.workspace.
Referenced by com.neuronrobotics.bowlerstudio.scripting.PasswordManager.getKey(), com.neuronrobotics.bowlerstudio.scripting.PasswordManager.getPassfile(), com.neuronrobotics.bowlerstudio.scripting.PasswordManager.getTokenfile(), com.neuronrobotics.bowlerstudio.scripting.PasswordManager.getUsernamefile(), and com.neuronrobotics.bowlerstudio.scripting.PasswordManager.login().
hasNetwork()
static boolean com.neuronrobotics.bowlerstudio.scripting.PasswordManager.hasNetwork () static
Definition at line 445 of file PasswordManager.java.
References com.neuronrobotics.bowlerstudio.scripting.PasswordManager.hasnetwork.
Referenced by com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.hasNetwork(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.login(), com.neuronrobotics.bowlerstudio.scripting.PasswordManager.performLogin(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.pushCodeToGit(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.waitForLogin().
hasStoredCredentials()
static boolean com.neuronrobotics.bowlerstudio.scripting.PasswordManager.hasStoredCredentials () static
Definition at line 300 of file PasswordManager.java.
References com.neuronrobotics.bowlerstudio.scripting.PasswordManager.getPassfile(), and com.neuronrobotics.bowlerstudio.scripting.PasswordManager.getUsernamefile().
Referenced by com.neuronrobotics.bowlerstudio.scripting.PasswordManager.loadLoginData(), and com.neuronrobotics.bowlerstudio.scripting.PasswordManager.login().
hasStoredToken()
static boolean com.neuronrobotics.bowlerstudio.scripting.PasswordManager.hasStoredToken () static
Definition at line 307 of file PasswordManager.java.
References com.neuronrobotics.bowlerstudio.scripting.PasswordManager.getTokenfile(), and com.neuronrobotics.bowlerstudio.scripting.PasswordManager.getUsernamefile().
isAnonMode()
static boolean com.neuronrobotics.bowlerstudio.scripting.PasswordManager.isAnonMode () static
Definition at line 482 of file PasswordManager.java.
References com.neuronrobotics.bowlerstudio.scripting.PasswordManager.isAnonMode.
loadLoginData()
static void com.neuronrobotics.bowlerstudio.scripting.PasswordManager.loadLoginData (File ws) throws Exception static
Definition at line 349 of file PasswordManager.java.
References com.neuronrobotics.bowlerstudio.scripting.PasswordManager.getKey(), com.neuronrobotics.bowlerstudio.scripting.PasswordManager.getLoginID(), com.neuronrobotics.bowlerstudio.scripting.PasswordManager.getPassfile(), com.neuronrobotics.bowlerstudio.scripting.PasswordManager.getUsernamefile(), com.neuronrobotics.bowlerstudio.scripting.PasswordManager.hasStoredCredentials(), com.neuronrobotics.bowlerstudio.scripting.PasswordManager.logout(), com.neuronrobotics.bowlerstudio.scripting.PasswordManager.performLogin(), com.neuronrobotics.bowlerstudio.scripting.PasswordManager.setLoginID(), and com.neuronrobotics.bowlerstudio.scripting.PasswordManager.setWorkspace().
Referenced by com.neuronrobotics.bowlerstudio.scripting.PasswordManager.login(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.setWorkspace().
loggedIn()
static boolean com.neuronrobotics.bowlerstudio.scripting.PasswordManager.loggedIn () static
Definition at line 296 of file PasswordManager.java.
References com.neuronrobotics.bowlerstudio.scripting.PasswordManager.isLoggedIn.
Referenced by com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.isLoginSuccess(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.login(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.newBranchLocal(), com.neuronrobotics.bowlerstudio.scripting.PasswordManager.waitForLogin(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.waitForLogin().
login()
static synchronized void com.neuronrobotics.bowlerstudio.scripting.PasswordManager.login () throws IOException static
Definition at line 165 of file PasswordManager.java.
References com.neuronrobotics.bowlerstudio.scripting.PasswordManager.checkInternet(), com.neuronrobotics.bowlerstudio.scripting.PasswordManager.getLoginManager(), com.neuronrobotics.bowlerstudio.scripting.PasswordManager.getUsername(), com.neuronrobotics.bowlerstudio.scripting.PasswordManager.getWorkspace(), com.neuronrobotics.bowlerstudio.scripting.PasswordManager.hasnetwork, com.neuronrobotics.bowlerstudio.scripting.PasswordManager.hasStoredCredentials(), com.neuronrobotics.bowlerstudio.scripting.PasswordManager.isLoggedIn, com.neuronrobotics.bowlerstudio.scripting.PasswordManager.loadLoginData(), com.neuronrobotics.bowlerstudio.scripting.IGitHubLoginManager.prompt(), com.neuronrobotics.bowlerstudio.scripting.PasswordManager.pw, com.neuronrobotics.bowlerstudio.scripting.PasswordManager.setLoginID(), com.neuronrobotics.bowlerstudio.scripting.PasswordManager.setupAnyonmous(), and com.neuronrobotics.bowlerstudio.scripting.PasswordManager.waitForLogin().
Referenced by com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.login(), and com.neuronrobotics.bowlerstudio.scripting.PasswordManager.waitForLogin().
logout()
static void com.neuronrobotics.bowlerstudio.scripting.PasswordManager.logout () throws IOException static
Definition at line 310 of file PasswordManager.java.
References com.neuronrobotics.bowlerstudio.scripting.PasswordManager.cp, com.neuronrobotics.bowlerstudio.scripting.PasswordManager.getPassfile(), com.neuronrobotics.bowlerstudio.scripting.PasswordManager.getTokenfile(), com.neuronrobotics.bowlerstudio.scripting.PasswordManager.isAnonMode, com.neuronrobotics.bowlerstudio.scripting.PasswordManager.isLoggedIn, com.neuronrobotics.bowlerstudio.scripting.PasswordManager.pw, and com.neuronrobotics.bowlerstudio.scripting.PasswordManager.setGithub().
Referenced by com.neuronrobotics.bowlerstudio.scripting.PasswordManager.loadLoginData(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.logout(), com.neuronrobotics.bowlerstudio.scripting.PasswordManager.performLogin(), and com.neuronrobotics.bowlerstudio.scripting.PasswordManager.setupAnyonmous().
performLogin()
static void com.neuronrobotics.bowlerstudio.scripting.PasswordManager.performLogin (String u, String p) throws Exception static private
Definition at line 219 of file PasswordManager.java.
References com.neuronrobotics.bowlerstudio.scripting.PasswordManager.getKey(), com.neuronrobotics.bowlerstudio.scripting.PasswordManager.getTokenfile(), com.neuronrobotics.bowlerstudio.scripting.PasswordManager.github, com.neuronrobotics.bowlerstudio.scripting.PasswordManager.hasNetwork(), com.neuronrobotics.bowlerstudio.scripting.PasswordManager.isLoggedIn, com.neuronrobotics.bowlerstudio.scripting.PasswordManager.logout(), com.neuronrobotics.bowlerstudio.scripting.PasswordManager.setAnonMode(), com.neuronrobotics.bowlerstudio.scripting.PasswordManager.setCredentialProvider(), com.neuronrobotics.bowlerstudio.scripting.PasswordManager.setGithub(), com.neuronrobotics.bowlerstudio.scripting.PasswordManager.setLoginID(), com.neuronrobotics.bowlerstudio.scripting.PasswordManager.writeData(), and com.neuronrobotics.bowlerstudio.scripting.PasswordManager.writeToken().
Referenced by com.neuronrobotics.bowlerstudio.scripting.PasswordManager.loadLoginData(), and com.neuronrobotics.bowlerstudio.scripting.PasswordManager.waitForLogin().
setAnonMode()
static void com.neuronrobotics.bowlerstudio.scripting.PasswordManager.setAnonMode (boolean isAnonMode) static private
Definition at line 486 of file PasswordManager.java.
References com.neuronrobotics.bowlerstudio.scripting.PasswordManager.isAnonMode.
Referenced by com.neuronrobotics.bowlerstudio.scripting.PasswordManager.performLogin(), and com.neuronrobotics.bowlerstudio.scripting.PasswordManager.setupAnyonmous().
setCredentialProvider()
static void com.neuronrobotics.bowlerstudio.scripting.PasswordManager.setCredentialProvider (CredentialsProvider cp) static private
Definition at line 441 of file PasswordManager.java.
References com.neuronrobotics.bowlerstudio.scripting.PasswordManager.cp.
Referenced by com.neuronrobotics.bowlerstudio.scripting.PasswordManager.performLogin().
setGithub()
static void com.neuronrobotics.bowlerstudio.scripting.PasswordManager.setGithub (GitHub g) static
Definition at line 157 of file PasswordManager.java.
References com.neuronrobotics.bowlerstudio.scripting.PasswordManager.github.
Referenced by com.neuronrobotics.bowlerstudio.scripting.PasswordManager.logout(), com.neuronrobotics.bowlerstudio.scripting.PasswordManager.performLogin(), and com.neuronrobotics.bowlerstudio.scripting.PasswordManager.setupAnyonmous().
setListOfScopes()
static void com.neuronrobotics.bowlerstudio.scripting.PasswordManager.setListOfScopes (List< String > listOfScopes) static
Definition at line 494 of file PasswordManager.java.
References com.neuronrobotics.bowlerstudio.scripting.PasswordManager.listOfScopes.
setLoginID()
static void com.neuronrobotics.bowlerstudio.scripting.PasswordManager.setLoginID (String loginID) static private
Definition at line 453 of file PasswordManager.java.
References com.neuronrobotics.bowlerstudio.scripting.PasswordManager.loginID.
Referenced by com.neuronrobotics.bowlerstudio.scripting.PasswordManager.loadLoginData(), com.neuronrobotics.bowlerstudio.scripting.PasswordManager.login(), com.neuronrobotics.bowlerstudio.scripting.PasswordManager.performLogin(), com.neuronrobotics.bowlerstudio.scripting.PasswordManager.writeData(), and com.neuronrobotics.bowlerstudio.scripting.PasswordManager.writeToken().
setLoginManager()
static void com.neuronrobotics.bowlerstudio.scripting.PasswordManager.setLoginManager (IGitHubLoginManager lm) static
Definition at line 345 of file PasswordManager.java.
References com.neuronrobotics.bowlerstudio.scripting.PasswordManager.loginManager.
Referenced by com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.setLoginManager().
setupAnyonmous()
static GitHub com.neuronrobotics.bowlerstudio.scripting.PasswordManager.setupAnyonmous () throws IOException static
Definition at line 325 of file PasswordManager.java.
References com.neuronrobotics.bowlerstudio.scripting.PasswordManager.getGithub(), com.neuronrobotics.bowlerstudio.scripting.PasswordManager.logout(), com.neuronrobotics.bowlerstudio.scripting.PasswordManager.setAnonMode(), and com.neuronrobotics.bowlerstudio.scripting.PasswordManager.setGithub().
Referenced by com.neuronrobotics.bowlerstudio.scripting.PasswordManager.login(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.setupAnyonmous().
setWorkspace()
static void com.neuronrobotics.bowlerstudio.scripting.PasswordManager.setWorkspace (File workspace) static
Definition at line 464 of file PasswordManager.java.
References com.neuronrobotics.bowlerstudio.scripting.PasswordManager.workspace.
Referenced by com.neuronrobotics.bowlerstudio.scripting.PasswordManager.loadLoginData().
waitForLogin()
static void com.neuronrobotics.bowlerstudio.scripting.PasswordManager.waitForLogin () throws Exception static
The GistID we are waiting to see
Definition at line 201 of file PasswordManager.java.
References com.neuronrobotics.bowlerstudio.scripting.PasswordManager.getLoginID(), com.neuronrobotics.bowlerstudio.scripting.PasswordManager.hasnetwork, com.neuronrobotics.bowlerstudio.scripting.PasswordManager.isLoggedIn, com.neuronrobotics.bowlerstudio.scripting.PasswordManager.loggedIn(), com.neuronrobotics.bowlerstudio.scripting.PasswordManager.login(), com.neuronrobotics.bowlerstudio.scripting.PasswordManager.performLogin(), and com.neuronrobotics.bowlerstudio.scripting.PasswordManager.pw.
Referenced by com.neuronrobotics.bowlerstudio.scripting.PasswordManager.login(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.waitForLogin().
writeData()
static void com.neuronrobotics.bowlerstudio.scripting.PasswordManager.writeData (String user, String passcleartext) throws Exception static private
Definition at line 407 of file PasswordManager.java.
References com.neuronrobotics.bowlerstudio.scripting.PasswordManager.getKey(), com.neuronrobotics.bowlerstudio.scripting.PasswordManager.getPassfile(), com.neuronrobotics.bowlerstudio.scripting.PasswordManager.getUsernamefile(), com.neuronrobotics.bowlerstudio.scripting.PasswordManager.pw, and com.neuronrobotics.bowlerstudio.scripting.PasswordManager.setLoginID().
Referenced by com.neuronrobotics.bowlerstudio.scripting.PasswordManager.performLogin().
writeToken()
static void com.neuronrobotics.bowlerstudio.scripting.PasswordManager.writeToken (String user, String passcleartext) throws Exception static private
Definition at line 422 of file PasswordManager.java.
References com.neuronrobotics.bowlerstudio.scripting.PasswordManager.getKey(), com.neuronrobotics.bowlerstudio.scripting.PasswordManager.getTokenfile(), com.neuronrobotics.bowlerstudio.scripting.PasswordManager.getUsernamefile(), com.neuronrobotics.bowlerstudio.scripting.PasswordManager.pw, and com.neuronrobotics.bowlerstudio.scripting.PasswordManager.setLoginID().
Referenced by com.neuronrobotics.bowlerstudio.scripting.PasswordManager.performLogin().
Member Data Documentation
cp
CredentialsProvider com.neuronrobotics.bowlerstudio.scripting.PasswordManager.cp static private
Definition at line 144 of file PasswordManager.java.
Referenced by com.neuronrobotics.bowlerstudio.scripting.PasswordManager.getCredentialProvider(), com.neuronrobotics.bowlerstudio.scripting.PasswordManager.logout(), and com.neuronrobotics.bowlerstudio.scripting.PasswordManager.setCredentialProvider().
github
GitHub com.neuronrobotics.bowlerstudio.scripting.PasswordManager.github static private
Definition at line 145 of file PasswordManager.java.
Referenced by com.neuronrobotics.bowlerstudio.scripting.PasswordManager.getGithub(), com.neuronrobotics.bowlerstudio.scripting.PasswordManager.performLogin(), and com.neuronrobotics.bowlerstudio.scripting.PasswordManager.setGithub().
hasnetwork
boolean com.neuronrobotics.bowlerstudio.scripting.PasswordManager.hasnetwork static private
Definition at line 146 of file PasswordManager.java.
Referenced by com.neuronrobotics.bowlerstudio.scripting.PasswordManager.checkInternet(), com.neuronrobotics.bowlerstudio.scripting.PasswordManager.hasNetwork(), com.neuronrobotics.bowlerstudio.scripting.PasswordManager.login(), and com.neuronrobotics.bowlerstudio.scripting.PasswordManager.waitForLogin().
isAnonMode
boolean com.neuronrobotics.bowlerstudio.scripting.PasswordManager.isAnonMode = false static private
Definition at line 148 of file PasswordManager.java.
Referenced by com.neuronrobotics.bowlerstudio.scripting.PasswordManager.isAnonMode(), com.neuronrobotics.bowlerstudio.scripting.PasswordManager.logout(), and com.neuronrobotics.bowlerstudio.scripting.PasswordManager.setAnonMode().
isLoggedIn
boolean com.neuronrobotics.bowlerstudio.scripting.PasswordManager.isLoggedIn = false static private
Definition at line 147 of file PasswordManager.java.
Referenced by com.neuronrobotics.bowlerstudio.scripting.PasswordManager.loggedIn(), com.neuronrobotics.bowlerstudio.scripting.PasswordManager.login(), com.neuronrobotics.bowlerstudio.scripting.PasswordManager.logout(), com.neuronrobotics.bowlerstudio.scripting.PasswordManager.performLogin(), and com.neuronrobotics.bowlerstudio.scripting.PasswordManager.waitForLogin().
listOfScopes
List<String> com.neuronrobotics.bowlerstudio.scripting.PasswordManager.listOfScopes static private
Initial value:
= Arrays.asList("repo", "gist", "write:packages", "read:packages", "delete:packages",
            "user", "delete_repo")
Definition at line 36 of file PasswordManager.java.
Referenced by com.neuronrobotics.bowlerstudio.scripting.PasswordManager.getListOfScopes(), and com.neuronrobotics.bowlerstudio.scripting.PasswordManager.setListOfScopes().
loginHeadless
IGitHubLoginManager com.neuronrobotics.bowlerstudio.scripting.PasswordManager.loginHeadless static private
Definition at line 38 of file PasswordManager.java.
Referenced by com.neuronrobotics.bowlerstudio.scripting.PasswordManager.getLoginManager().
loginID
String com.neuronrobotics.bowlerstudio.scripting.PasswordManager.loginID = null static private
Definition at line 142 of file PasswordManager.java.
Referenced by com.neuronrobotics.bowlerstudio.scripting.PasswordManager.getLoginID(), and com.neuronrobotics.bowlerstudio.scripting.PasswordManager.setLoginID().
loginManager
IGitHubLoginManager com.neuronrobotics.bowlerstudio.scripting.PasswordManager.loginManager =null static private
Definition at line 34 of file PasswordManager.java.
Referenced by com.neuronrobotics.bowlerstudio.scripting.PasswordManager.getLoginManager(), and com.neuronrobotics.bowlerstudio.scripting.PasswordManager.setLoginManager().
loginWebFlow
IGitHubLoginManager com.neuronrobotics.bowlerstudio.scripting.PasswordManager.loginWebFlow = new GitHubWebFlow() static private
Definition at line 35 of file PasswordManager.java.
Referenced by com.neuronrobotics.bowlerstudio.scripting.PasswordManager.getLoginManager().
pw
String com.neuronrobotics.bowlerstudio.scripting.PasswordManager.pw = null static private
Definition at line 143 of file PasswordManager.java.
Referenced by com.neuronrobotics.bowlerstudio.scripting.PasswordManager.getPassword(), com.neuronrobotics.bowlerstudio.scripting.PasswordManager.login(), com.neuronrobotics.bowlerstudio.scripting.PasswordManager.logout(), com.neuronrobotics.bowlerstudio.scripting.PasswordManager.waitForLogin(), com.neuronrobotics.bowlerstudio.scripting.PasswordManager.writeData(), and com.neuronrobotics.bowlerstudio.scripting.PasswordManager.writeToken().
workspace
File com.neuronrobotics.bowlerstudio.scripting.PasswordManager.workspace = null static private
Definition at line 141 of file PasswordManager.java.
Referenced by com.neuronrobotics.bowlerstudio.scripting.PasswordManager.getWorkspace(), and com.neuronrobotics.bowlerstudio.scripting.PasswordManager.setWorkspace().
The documentation for this class was generated from the following file:
GithubPasswordManager/GithubPasswordManager/src/main/java/com/neuronrobotics/bowlerstudio/scripting/PasswordManager.java