BowlerKernel: eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh Class Reference
eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh Class Reference
Classes
enum BoundaryMode
enum MapBorderMode
Public Member Functions
SubdivisionMesh (PolygonMesh originalMesh, int subdivisionLevel, BoundaryMode boundaryMode, MapBorderMode mapBorderMode)
void update ()
PolygonMesh getOriginalMesh ()
int getSubdivisionLevel ()
void setSubdivisionLevel (int subdivisionLevel)
SubdivisionMesh.BoundaryMode getBoundaryMode ()
void setBoundaryMode (SubdivisionMesh.BoundaryMode boundaryMode)
SubdivisionMesh.MapBorderMode getMapBorderMode ()
void setMapBorderMode (SubdivisionMesh.MapBorderMode mapBorderMode)
Public Member Functions inherited from eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMesh
PolygonMesh ()
PolygonMesh (float[] points, float[] texCoords, int[][] faces)
ObservableFloatArray getPoints ()
ObservableFloatArray getTexCoords ()
ObservableIntegerArray getFaceSmoothingGroups ()
int getNumEdgesInFaces ()
int getPointElementSize ()
int getTexCoordElementSize ()
int getFaceElementSize ()
Private Member Functions
void setSubdivisionLevelForced (int subdivisionLevel)
void setBoundaryModeForced (SubdivisionMesh.BoundaryMode boundaryMode)
void setMapBorderModeForced (SubdivisionMesh.MapBorderMode mapBorderMode)
Private Attributes
final PolygonMesh originalMesh
int subdivisionLevel
BoundaryMode boundaryMode
MapBorderMode mapBorderMode
final List< SymbolicPolygonMesh > symbolicMeshes
boolean pointValuesDirty
boolean meshDirty
boolean subdivisionLevelDirty
Additional Inherited Members
Public Attributes inherited from eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMesh
int[][] faces = new int[0][0]
Protected Attributes inherited from eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMesh
int numEdgesInFaces = -1
Detailed Description
Catmull Clark subdivision surface polygon mesh.
Definition at line 45 of file SubdivisionMesh.java.
Constructor & Destructor Documentation
SubdivisionMesh()
eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.SubdivisionMesh (PolygonMesh originalMesh, int subdivisionLevel, BoundaryMode boundaryMode, MapBorderMode mapBorderMode)
Instantiates a new subdivision mesh.
Parameters
originalMesh the original mesh
subdivisionLevel the subdivision level
boundaryMode the boundary mode
mapBorderMode the map border mode
Definition at line 107 of file SubdivisionMesh.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.boundaryMode, eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMesh.getPoints(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMesh.getTexCoords(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.mapBorderMode, eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.meshDirty, eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.originalMesh, eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.pointValuesDirty, eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.setBoundaryModeForced(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.setMapBorderModeForced(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.setSubdivisionLevelForced(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.subdivisionLevel, and eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.symbolicMeshes.
Member Function Documentation
getBoundaryMode()
SubdivisionMesh.BoundaryMode eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.getBoundaryMode ()
Gets the boundary mode.
Returns
the boundary mode
Definition at line 230 of file SubdivisionMesh.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.boundaryMode.
getMapBorderMode()
SubdivisionMesh.MapBorderMode eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.getMapBorderMode ()
Gets the map border mode.
Returns
the map border mode
Definition at line 250 of file SubdivisionMesh.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.mapBorderMode.
getOriginalMesh()
PolygonMesh eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.getOriginalMesh ()
Gets the original mesh.
Returns
the original mesh
Definition at line 201 of file SubdivisionMesh.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.originalMesh.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.subdivisionLevelProperty().
getSubdivisionLevel()
int eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.getSubdivisionLevel ()
Gets the subdivision level.
Returns
the subdivision level
Definition at line 210 of file SubdivisionMesh.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.subdivisionLevel.
setBoundaryMode()
void eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.setBoundaryMode (SubdivisionMesh.BoundaryMode boundaryMode)
Sets the boundary mode.
Parameters
boundaryMode the new boundary mode
Definition at line 239 of file SubdivisionMesh.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.boundaryMode, and eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.setBoundaryModeForced().
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.boundaryModeProperty().
setBoundaryModeForced()
void eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.setBoundaryModeForced (SubdivisionMesh.BoundaryMode boundaryMode) private
Sets the boundary mode forced.
Parameters
boundaryMode the new boundary mode forced
Definition at line 181 of file SubdivisionMesh.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.boundaryMode, and eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.meshDirty.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.setBoundaryMode(), and eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.SubdivisionMesh().
setMapBorderMode()
void eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.setMapBorderMode (SubdivisionMesh.MapBorderMode mapBorderMode)
Sets the map border mode.
Parameters
mapBorderMode the new map border mode
Definition at line 259 of file SubdivisionMesh.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.mapBorderMode, and eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.setMapBorderModeForced().
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.mapBorderModeProperty().
setMapBorderModeForced()
void eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.setMapBorderModeForced (SubdivisionMesh.MapBorderMode mapBorderMode) private
Sets the map border mode forced.
Parameters
mapBorderMode the new map border mode forced
Definition at line 191 of file SubdivisionMesh.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.mapBorderMode, and eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.meshDirty.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.setMapBorderMode(), and eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.SubdivisionMesh().
setSubdivisionLevel()
void eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.setSubdivisionLevel (int subdivisionLevel)
Sets the subdivision level.
Parameters
subdivisionLevel the new subdivision level
Definition at line 219 of file SubdivisionMesh.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.setSubdivisionLevelForced(), and eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.subdivisionLevel.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.subdivisionLevelProperty().
setSubdivisionLevelForced()
void eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.setSubdivisionLevelForced (int subdivisionLevel) private
Sets the subdivision level forced.
Parameters
subdivisionLevel the new subdivision level forced
Definition at line 171 of file SubdivisionMesh.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.subdivisionLevel, and eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.subdivisionLevelDirty.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.setSubdivisionLevel(), and eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.SubdivisionMesh().
update()
void eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.update ()
Updates the variables of the underlying polygon mesh. It only updates the fields that need to be updated.
Definition at line 129 of file SubdivisionMesh.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.boundaryMode, eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMesh.faces, eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMesh.getFaceSmoothingGroups(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMesh.getPoints(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMesh.getTexCoords(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.mapBorderMode, eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.meshDirty, eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMesh.numEdgesInFaces, eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.originalMesh, eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicPolygonMesh.points, eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.pointValuesDirty, eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.subdivide(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.subdivisionLevel, eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.subdivisionLevelDirty, eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.symbolicMeshes, and eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicPointArray.update().
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.boundaryModeProperty(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.mapBorderModeProperty(), and eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.subdivisionLevelProperty().
Member Data Documentation
boundaryMode
BoundaryMode eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.boundaryMode private
The boundary mode.
Definition at line 54 of file SubdivisionMesh.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.getBoundaryMode(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.setBoundaryMode(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.setBoundaryModeForced(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.SubdivisionMesh(), and eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.update().
mapBorderMode
MapBorderMode eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.mapBorderMode private
The map border mode.
Definition at line 57 of file SubdivisionMesh.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.getMapBorderMode(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.setMapBorderMode(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.setMapBorderModeForced(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.SubdivisionMesh(), and eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.update().
meshDirty
boolean eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.meshDirty private
The mesh dirty.
Definition at line 66 of file SubdivisionMesh.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.setBoundaryModeForced(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.setMapBorderModeForced(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.SubdivisionMesh(), and eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.update().
originalMesh
final PolygonMesh eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.originalMesh private
The original mesh.
Definition at line 48 of file SubdivisionMesh.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.getOriginalMesh(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.SubdivisionMesh(), and eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.update().
pointValuesDirty
boolean eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.pointValuesDirty private
The point values dirty.
Definition at line 63 of file SubdivisionMesh.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.SubdivisionMesh(), and eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.update().
subdivisionLevel
int eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.subdivisionLevel private
The subdivision level.
Definition at line 51 of file SubdivisionMesh.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.getSubdivisionLevel(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.setSubdivisionLevel(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.setSubdivisionLevelForced(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.SubdivisionMesh(), and eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.update().
subdivisionLevelDirty
boolean eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.subdivisionLevelDirty private
The subdivision level dirty.
Definition at line 69 of file SubdivisionMesh.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.setSubdivisionLevelForced(), and eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.update().
symbolicMeshes
final List<SymbolicPolygonMesh> eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.symbolicMeshes private
The symbolic meshes.
Definition at line 60 of file SubdivisionMesh.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.SubdivisionMesh(), and eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.update().
The documentation for this class was generated from the following file:
JCSG/src/main/java/eu/mihosoft/vrl/v3d/ext/openjfx/shape3d/SubdivisionMesh.java