BowlerKernel: com.neuronrobotics.bowlerstudio.lipsync.VoskLipSync Class Reference
com.neuronrobotics.bowlerstudio.lipsync.VoskLipSync Class Reference
Classes
class VoskPartial
class VoskResultl
class VoskResultWord
Public Member Functions
void processRaw (File f, String ttsLocation) throws UnsupportedAudioFileException, IOException
AudioInputStream startProcessing (AudioInputStream ais, String TTSString)
AudioStatus update (AudioStatus current, double amplitudeUnitVector, double currentRollingAverage, double currentDerivitiveTerm, double percent)
double getTimeLeadLag ()
void setTimeLeadLag (double timeLeadLag)
Static Public Member Functions
static VoskLipSync get ()
static void loadDictionary ()
static String getModelName ()
static void setModelName (String modelName)
static String promptFromMicrophone () throws IOException, LineUnavailableException
static double getPercentageTimeOfLipSyncReadahead ()
static void setPercentageTimeOfLipSyncReadahead (double percentageTimeOfLipSyncReadahead)
Private Member Functions
VoskLipSync ()
AudioStatus toStatus (String phoneme)
void addWord (VoskResultWord word, long len)
void add (TimeCodedViseme v)
void processWords (List< VoskResultWord > wordList, long len)
Private Attributes
double positionInTrack
double timeLeadLag = 0.5
Static Private Attributes
static double PercentageTimeOfLipSyncReadahead = 2
static VoskLipSync singelton = null
static Model model
static String modelName
static PhoneticDictionary dict
static AudioFormat format = new AudioFormat(AudioFormat.Encoding.PCM_SIGNED, 60000, 16, 2, 4, 44100, false)
Detailed Description
Definition at line 37 of file VoskLipSync.java.
Constructor & Destructor Documentation
VoskLipSync()
com.neuronrobotics.bowlerstudio.lipsync.VoskLipSync.VoskLipSync () private
Definition at line 41 of file VoskLipSync.java.
Referenced by com.neuronrobotics.bowlerstudio.lipsync.VoskLipSync.get().
Member Function Documentation
add()
void com.neuronrobotics.bowlerstudio.lipsync.VoskLipSync.add (TimeCodedViseme v) private
Definition at line 301 of file VoskLipSync.java.
Referenced by com.neuronrobotics.bowlerstudio.lipsync.VoskLipSync.addWord(), and com.neuronrobotics.bowlerstudio.lipsync.VoskLipSync.processRaw().
addWord()
void com.neuronrobotics.bowlerstudio.lipsync.VoskLipSync.addWord (VoskResultWord word, long len) private
Definition at line 161 of file VoskLipSync.java.
References com.neuronrobotics.bowlerstudio.AudioStatus.A_PBM_SOUNDS, com.neuronrobotics.bowlerstudio.lipsync.VoskLipSync.add(), com.neuronrobotics.bowlerstudio.AudioStatus.B_KST_SOUNDS, com.neuronrobotics.bowlerstudio.AudioStatus.C_EH_AE_SOUNDS, com.neuronrobotics.bowlerstudio.AudioStatus.D_AA_SOUNDS, com.neuronrobotics.bowlerstudio.lipsync.VoskLipSync.dict, com.neuronrobotics.bowlerstudio.AudioStatus.E_AO_ER_SOUNDS, com.neuronrobotics.bowlerstudio.AudioStatus.F_UW_OW_W_SOUNDS, com.neuronrobotics.bowlerstudio.lipsync.PhoneticDictionary.find(), com.neuronrobotics.bowlerstudio.AudioStatus.H_L_SOUNDS, com.neuronrobotics.bowlerstudio.lipsync.VoskLipSync.timeLeadLag, com.neuronrobotics.bowlerstudio.lipsync.VoskLipSync.toStatus(), and com.neuronrobotics.bowlerstudio.AudioStatus.X_NO_SOUND.
Referenced by com.neuronrobotics.bowlerstudio.lipsync.VoskLipSync.processWords().
get()
static VoskLipSync com.neuronrobotics.bowlerstudio.lipsync.VoskLipSync.get () static
Definition at line 45 of file VoskLipSync.java.
References com.neuronrobotics.bowlerstudio.lipsync.VoskLipSync.singelton, and com.neuronrobotics.bowlerstudio.lipsync.VoskLipSync.VoskLipSync().
getModelName()
static String com.neuronrobotics.bowlerstudio.lipsync.VoskLipSync.getModelName () static
Returns
the modelName
Definition at line 103 of file VoskLipSync.java.
References com.neuronrobotics.bowlerstudio.lipsync.VoskLipSync.modelName.
Referenced by com.neuronrobotics.bowlerstudio.lipsync.VoskLipSync.promptFromMicrophone(), and com.neuronrobotics.bowlerstudio.lipsync.VoskLipSync.setModelName().
getPercentageTimeOfLipSyncReadahead()
static double com.neuronrobotics.bowlerstudio.lipsync.VoskLipSync.getPercentageTimeOfLipSyncReadahead () static
Returns
the percentageTimeOfLipSyncReadahead
Definition at line 508 of file VoskLipSync.java.
References com.neuronrobotics.bowlerstudio.lipsync.VoskLipSync.PercentageTimeOfLipSyncReadahead.
Referenced by com.neuronrobotics.bowlerstudio.lipsync.VoskLipSync.processRaw().
getTimeLeadLag()
double com.neuronrobotics.bowlerstudio.lipsync.VoskLipSync.getTimeLeadLag ()
Returns
the timeLeadLag
Definition at line 523 of file VoskLipSync.java.
References com.neuronrobotics.bowlerstudio.lipsync.VoskLipSync.timeLeadLag.
loadDictionary()
static void com.neuronrobotics.bowlerstudio.lipsync.VoskLipSync.loadDictionary () static
Definition at line 90 of file VoskLipSync.java.
References com.neuronrobotics.bowlerstudio.lipsync.VoskLipSync.dict, and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.fileFromGit().
processRaw()
void com.neuronrobotics.bowlerstudio.lipsync.VoskLipSync.processRaw (File f, String ttsLocation) throws UnsupportedAudioFileException, IOException
Definition at line 319 of file VoskLipSync.java.
References com.neuronrobotics.bowlerstudio.lipsync.VoskLipSync.add(), com.neuronrobotics.bowlerstudio.lipsync.VoskLipSync.format, com.neuronrobotics.bowlerstudio.lipsync.VoskLipSync.getPercentageTimeOfLipSyncReadahead(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getWorkspace(), com.neuronrobotics.bowlerstudio.lipsync.VoskLipSync.model, com.neuronrobotics.bowlerstudio.lipsync.VoskLipSync.positionInTrack, com.neuronrobotics.bowlerstudio.lipsync.VoskLipSync.processWords(), and com.neuronrobotics.bowlerstudio.AudioStatus.X_NO_SOUND.
Referenced by com.neuronrobotics.bowlerstudio.lipsync.VoskLipSync.startProcessing().
processWords()
void com.neuronrobotics.bowlerstudio.lipsync.VoskLipSync.processWords (List< VoskResultWord > wordList, long len) private
Definition at line 308 of file VoskLipSync.java.
References com.neuronrobotics.bowlerstudio.lipsync.VoskLipSync.addWord().
Referenced by com.neuronrobotics.bowlerstudio.lipsync.VoskLipSync.processRaw().
promptFromMicrophone()
static String com.neuronrobotics.bowlerstudio.lipsync.VoskLipSync.promptFromMicrophone () throws IOException, LineUnavailableException static
Definition at line 455 of file VoskLipSync.java.
References com.neuronrobotics.bowlerstudio.lipsync.VoskLipSync.format, com.neuronrobotics.bowlerstudio.lipsync.VoskLipSync.getModelName(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getWorkspace(), and com.neuronrobotics.bowlerstudio.lipsync.VoskLipSync.model.
setModelName()
static void com.neuronrobotics.bowlerstudio.lipsync.VoskLipSync.setModelName (String modelName) static
Parameters
modelName the modelName to set
Definition at line 110 of file VoskLipSync.java.
References com.neuronrobotics.bowlerstudio.lipsync.VoskLipSync.getModelName(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getWorkspace(), com.neuronrobotics.bowlerstudio.lipsync.VoskLipSync.model, and com.neuronrobotics.bowlerstudio.lipsync.VoskLipSync.modelName.
setPercentageTimeOfLipSyncReadahead()
static void com.neuronrobotics.bowlerstudio.lipsync.VoskLipSync.setPercentageTimeOfLipSyncReadahead (double percentageTimeOfLipSyncReadahead) static
Parameters
percentageTimeOfLipSyncReadahead the percentageTimeOfLipSyncReadahead to set
Definition at line 516 of file VoskLipSync.java.
References com.neuronrobotics.bowlerstudio.lipsync.VoskLipSync.PercentageTimeOfLipSyncReadahead.
setTimeLeadLag()
void com.neuronrobotics.bowlerstudio.lipsync.VoskLipSync.setTimeLeadLag (double timeLeadLag)
Parameters
timeLeadLag the timeLeadLag to set
Definition at line 530 of file VoskLipSync.java.
References com.neuronrobotics.bowlerstudio.lipsync.VoskLipSync.timeLeadLag.
startProcessing()
AudioInputStream com.neuronrobotics.bowlerstudio.lipsync.VoskLipSync.startProcessing (AudioInputStream ais, String TTSString)
Implements com.neuronrobotics.bowlerstudio.IAudioProcessingLambda.
Definition at line 395 of file VoskLipSync.java.
References com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getWorkspace(), and com.neuronrobotics.bowlerstudio.lipsync.VoskLipSync.processRaw().
toStatus()
AudioStatus com.neuronrobotics.bowlerstudio.lipsync.VoskLipSync.toStatus (String phoneme) private
Definition at line 153 of file VoskLipSync.java.
References com.neuronrobotics.bowlerstudio.AudioStatus.getFromPhoneme(), and com.neuronrobotics.bowlerstudio.AudioStatus.X_NO_SOUND.
Referenced by com.neuronrobotics.bowlerstudio.lipsync.VoskLipSync.addWord().
update()
AudioStatus com.neuronrobotics.bowlerstudio.lipsync.VoskLipSync.update (AudioStatus current, double amplitudeUnitVector, double currentRollingAverage, double currentDerivitiveTerm, double percent)
Implements com.neuronrobotics.bowlerstudio.IAudioProcessingLambda.
Definition at line 425 of file VoskLipSync.java.
References com.neuronrobotics.bowlerstudio.AudioStatus.get(), and com.neuronrobotics.bowlerstudio.AudioStatus.X_NO_SOUND.
Member Data Documentation
dict
PhoneticDictionary com.neuronrobotics.bowlerstudio.lipsync.VoskLipSync.dict static private
Definition at line 81 of file VoskLipSync.java.
Referenced by com.neuronrobotics.bowlerstudio.lipsync.VoskLipSync.addWord(), and com.neuronrobotics.bowlerstudio.lipsync.VoskLipSync.loadDictionary().
format
AudioFormat com.neuronrobotics.bowlerstudio.lipsync.VoskLipSync.format = new AudioFormat(AudioFormat.Encoding.PCM_SIGNED, 60000, 16, 2, 4, 44100, false) static private
Definition at line 82 of file VoskLipSync.java.
Referenced by com.neuronrobotics.bowlerstudio.lipsync.VoskLipSync.processRaw(), and com.neuronrobotics.bowlerstudio.lipsync.VoskLipSync.promptFromMicrophone().
model
Model com.neuronrobotics.bowlerstudio.lipsync.VoskLipSync.model static private
Definition at line 79 of file VoskLipSync.java.
Referenced by com.neuronrobotics.bowlerstudio.lipsync.VoskLipSync.processRaw(), com.neuronrobotics.bowlerstudio.lipsync.VoskLipSync.promptFromMicrophone(), and com.neuronrobotics.bowlerstudio.lipsync.VoskLipSync.setModelName().
modelName
String com.neuronrobotics.bowlerstudio.lipsync.VoskLipSync.modelName static private
Definition at line 80 of file VoskLipSync.java.
Referenced by com.neuronrobotics.bowlerstudio.lipsync.VoskLipSync.getModelName(), and com.neuronrobotics.bowlerstudio.lipsync.VoskLipSync.setModelName().
PercentageTimeOfLipSyncReadahead
double com.neuronrobotics.bowlerstudio.lipsync.VoskLipSync.PercentageTimeOfLipSyncReadahead = 2 static private
Definition at line 38 of file VoskLipSync.java.
Referenced by com.neuronrobotics.bowlerstudio.lipsync.VoskLipSync.getPercentageTimeOfLipSyncReadahead(), and com.neuronrobotics.bowlerstudio.lipsync.VoskLipSync.setPercentageTimeOfLipSyncReadahead().
positionInTrack
double com.neuronrobotics.bowlerstudio.lipsync.VoskLipSync.positionInTrack private
Definition at line 150 of file VoskLipSync.java.
Referenced by com.neuronrobotics.bowlerstudio.lipsync.VoskLipSync.processRaw().
singelton
VoskLipSync com.neuronrobotics.bowlerstudio.lipsync.VoskLipSync.singelton = null static private
Definition at line 39 of file VoskLipSync.java.
Referenced by com.neuronrobotics.bowlerstudio.lipsync.VoskLipSync.get().
timeLeadLag
double com.neuronrobotics.bowlerstudio.lipsync.VoskLipSync.timeLeadLag = 0.5 private
Definition at line 151 of file VoskLipSync.java.
Referenced by com.neuronrobotics.bowlerstudio.lipsync.VoskLipSync.addWord(), com.neuronrobotics.bowlerstudio.lipsync.VoskLipSync.getTimeLeadLag(), and com.neuronrobotics.bowlerstudio.lipsync.VoskLipSync.setTimeLeadLag().
The documentation for this class was generated from the following file:
src/main/java/com/neuronrobotics/bowlerstudio/lipsync/VoskLipSync.java