BowlerKernel: com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration Class Reference
com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration Class Reference
Public Member Functions
LinkConfiguration (Element eElement)
LinkConfiguration (Object[] args)
void setVitamin (String name, String type, String id)
void setVitaminVariant (String name, String tagValue2)
String getVitaminVariant (String name)
LinkConfiguration ()
LinkConfiguration (LinkConfiguration from)
LinkConfiguration (int home, int llimit, int ulimit, double d)
String toString ()
String getXml ()
void setName (String name)
String getName ()
void setHardwareIndex (int index)
int getHardwareIndex ()
void setScale (double scale)
double getScale ()
double getDeviceTheoreticalMax ()
void setDeviceTheoreticalMax (double deviceTheoreticalMax)
double getDeviceTheoreticalMin ()
void setDeviceTheoreticalMin (double deviceTheoreticalMin)
void setUpperLimit (double upperLimit)
double getUpperLimit ()
void setLowerLimit (double lowerLimit)
double getLowerLimit ()
double getKP ()
double getKI ()
double getKD ()
void setKP (double kP)
void setKI (double kI)
void setKD (double kD)
void setInverted (boolean inverted)
boolean isInverted ()
void setIndexLatch (double indexLatch)
double getIndexLatch ()
void setLatch (boolean isLatch)
boolean isLatch ()
void setStopOnLatch (boolean isStopOnLatch)
boolean isStopOnLatch ()
void setHomingTicksPerSecond (int homingTicksPerSecond)
int getHomingTicksPerSecond ()
void setUpperVelocity (double upperVelocity)
double getUpperVelocity ()
double getLowerVelocity ()
int getLinkIndex ()
void setLinkIndex (int linkIndex)
int getTotlaNumberOfLinks ()
void setTotlaNumberOfLinks (int totlaNumberOfLinks)
PIDConfiguration getPidConfiguration ()
void setPidConfiguration (IPidControlNamespace pid)
String getDeviceScriptingName ()
void setDeviceScriptingName (String deviceScriptingName)
double getStaticOffset ()
void setStaticOffset (double staticOffset)
boolean isInvertLimitVelocityPolarity ()
void setInvertLimitVelocityPolarity (boolean invertVelocity)
ArrayList< LinkConfiguration > getSlaveLinks ()
void setSlaveLinks (ArrayList< LinkConfiguration > slaveLinks)
double getMassKg ()
void setMassKg (double mass)
TransformNR getCenterOfMassFromCentroid ()
void setCenterOfMassFromCentroid (TransformNR com)
TransformNR getimuFromCentroid ()
void setimuFromCentroid (TransformNR imu)
String getElectroMechanicalType ()
void setElectroMechanicalType (String electroMechanicalType)
String getElectroMechanicalSize ()
void setElectroMechanicalSize (String electroMechanicalSize)
String getShaftType ()
void setShaftType (String shaftType)
String getShaftSize ()
void setShaftSize (String shaftSize)
boolean isPassive ()
void setPassive (boolean passive)
HashMap< String, String[]> getVitamins ()
void setVitamins (HashMap< String, String[]> vitamins)
String getTypeString ()
void setTypeString (String typeString)
boolean isVirtual ()
boolean isTool ()
boolean isPrismatic ()
void addChangeListener (ILinkConfigurationChangeListener l)
void removeChangeListener (ILinkConfigurationChangeListener l)
void clearChangeListener ()
ArrayList< ILinkConfigurationChangeListener > getListeners ()
void event (TransformNR changed)
boolean isPauseEvents ()
void setPauseEvents (boolean pauseEvents)
Protected Member Functions
void getVitamins (Element doc)
Private Member Functions
String[] getCoreShaftPart ()
String[] getCoreEmPart ()
Private Attributes
ArrayList< ILinkConfigurationChangeListener > listeners = null
boolean pauseEvents =false
String name = "newLink"
String type = "virtual"
int index = 0
int totlaNumberOfLinks = 1
int linkIndex = 0
double scale = 1.0
double upperLimit = 100000
double lowerLimit = -100000
double k [] = new double[] { 1, 0, 0 }
boolean inverted = false
boolean isLatch = false
double indexLatch = 0
boolean isStopOnLatch = false
int homingTicksPerSecond = 10000000
double velocityLimit = 100000000
String deviceScriptingName = "exampleDevice"
double deviceTheoreticalMax = 180
double deviceTheoreticalMin = 0
double mass = 0.01
TransformNR centerOfMassFromCentroid = new TransformNR()
TransformNR imuFromCentroid = new TransformNR()
double staticOffset = 0
ArrayList< LinkConfiguration > slaveLinks = new ArrayList<LinkConfiguration>()
boolean invertVelocity = false
boolean invertLimitVelocityPolarity = false
HashMap< String, String[]> vitamins = new HashMap<String, String[]>()
HashMap< String, String > vitaminVariant = new HashMap<String, String>()
boolean passive = false
boolean newAbs = false
Detailed Description
The Class LinkConfiguration.
Definition at line 25 of file LinkConfiguration.java.
Constructor & Destructor Documentation
LinkConfiguration() [1/5]
com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.LinkConfiguration (Element eElement)
Instantiates a new link configuration.
Parameters
eElement the e element
Definition at line 109 of file LinkConfiguration.java.
References com.neuronrobotics.sdk.common.Log.error(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getHardwareIndex(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getLowerLimit(), com.neuronrobotics.sdk.addons.kinematics.xml.XmlFactory.getTagValue(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getTypeString(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getUpperLimit(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getVitamins(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.inverted, com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.invertLimitVelocityPolarity, com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.isLatch, com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.isStopOnLatch, com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.k, com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.newAbs, com.neuronrobotics.sdk.addons.kinematics.LinkType.PID, com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setCenterOfMassFromCentroid(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setDeviceScriptingName(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setDeviceTheoreticalMax(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setDeviceTheoreticalMin(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setElectroMechanicalSize(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setElectroMechanicalType(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setHardwareIndex(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setHomingTicksPerSecond(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setimuFromCentroid(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setIndexLatch(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setLowerLimit(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setMassKg(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setName(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setPassive(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setScale(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setShaftSize(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setShaftType(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setStaticOffset(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setTypeString(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setUpperLimit(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setUpperVelocity(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.staticOffset, and com.neuronrobotics.sdk.addons.kinematics.LinkType.VIRTUAL.
LinkConfiguration() [2/5]
com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.LinkConfiguration (Object[] args)
Instantiates a new link configuration.
Parameters
args the args
Definition at line 258 of file LinkConfiguration.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkType.PID, com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setHardwareIndex(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setLowerLimit(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setName(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setScale(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setTotlaNumberOfLinks(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setTypeString(), and com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setUpperLimit().
LinkConfiguration() [3/5]
com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.LinkConfiguration ()
Instantiates a new link configuration.
Definition at line 339 of file LinkConfiguration.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.LinkConfiguration().
LinkConfiguration() [4/5]
com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.LinkConfiguration (LinkConfiguration from)
Definition at line 343 of file LinkConfiguration.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getCenterOfMassFromCentroid(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getDeviceScriptingName(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getDeviceTheoreticalMax(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getDeviceTheoreticalMin(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getHardwareIndex(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getHomingTicksPerSecond(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getimuFromCentroid(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getIndexLatch(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getLowerLimit(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getMassKg(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getName(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getScale(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getStaticOffset(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getTypeString(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getUpperLimit(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getUpperVelocity(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getVitamins(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.isLatch, com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.isPassive(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.isStopOnLatch, com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.LinkConfiguration(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setCenterOfMassFromCentroid(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setDeviceScriptingName(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setDeviceTheoreticalMax(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setDeviceTheoreticalMin(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setHardwareIndex(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setHomingTicksPerSecond(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setimuFromCentroid(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setIndexLatch(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setLatch(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setLowerLimit(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setMassKg(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setName(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setPassive(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setScale(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setStaticOffset(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setStopOnLatch(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setTypeString(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setUpperLimit(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setUpperVelocity(), and com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.slaveLinks.
LinkConfiguration() [5/5]
com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.LinkConfiguration (int home, int llimit, int ulimit, double d)
Instantiates a new link configuration.
Parameters
home the home
llimit the llimit
ulimit the ulimit
d the d
Definition at line 383 of file LinkConfiguration.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setLowerLimit(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setScale(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setStaticOffset(), and com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setUpperLimit().
Member Function Documentation
addChangeListener()
void com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.addChangeListener (ILinkConfigurationChangeListener l)
Definition at line 1094 of file LinkConfiguration.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getListeners().
Referenced by com.neuronrobotics.sdk.addons.kinematics.AbstractLink.addChangeListener().
clearChangeListener()
void com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.clearChangeListener ()
Definition at line 1104 of file LinkConfiguration.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getListeners(), and com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.listeners.
Referenced by com.neuronrobotics.sdk.addons.kinematics.AbstractLink.clearChangeListener().
event()
void com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.event (TransformNR changed)
Implements com.neuronrobotics.sdk.addons.kinematics.math.ITransformNRChangeListener.
Definition at line 1130 of file LinkConfiguration.java.
getCenterOfMassFromCentroid()
TransformNR com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getCenterOfMassFromCentroid ()
Definition at line 925 of file LinkConfiguration.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.centerOfMassFromCentroid.
Referenced by com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getXml(), and com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.LinkConfiguration().
getCoreEmPart()
String [] com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getCoreEmPart () private
Definition at line 960 of file LinkConfiguration.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.vitamins.
Referenced by com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getElectroMechanicalSize(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getElectroMechanicalType(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setElectroMechanicalSize(), and com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setElectroMechanicalType().
getCoreShaftPart()
String [] com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getCoreShaftPart () private
Definition at line 953 of file LinkConfiguration.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.vitamins.
Referenced by com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getShaftSize(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getShaftType(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setShaftSize(), and com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setShaftType().
getDeviceScriptingName()
String com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getDeviceScriptingName ()
Gets the device scripting name.
Returns
the device scripting name
Definition at line 861 of file LinkConfiguration.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.deviceScriptingName.
Referenced by com.neuronrobotics.sdk.addons.kinematics.LinkFactory.getDyio(), com.neuronrobotics.sdk.addons.kinematics.LinkFactory.getGCODE(), com.neuronrobotics.sdk.addons.kinematics.LinkFactory.getLinkLocal(), com.neuronrobotics.sdk.addons.kinematics.LinkFactory.getPid(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getXml(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.LinkConfiguration(), and com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.toString().
getDeviceTheoreticalMax()
double com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getDeviceTheoreticalMax ()
Definition at line 513 of file LinkConfiguration.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.deviceTheoreticalMax.
Referenced by com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getDeviceMaximumValue(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getXml(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.LinkConfiguration(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setIndexLatch(), and com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setUpperLimit().
getDeviceTheoreticalMin()
double com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getDeviceTheoreticalMin ()
Definition at line 522 of file LinkConfiguration.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.deviceTheoreticalMin.
Referenced by com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getDeviceMinimumValue(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getXml(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.LinkConfiguration(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setIndexLatch(), and com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setLowerLimit().
getElectroMechanicalSize()
String com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getElectroMechanicalSize ()
Definition at line 976 of file LinkConfiguration.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getCoreEmPart().
getElectroMechanicalType()
String com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getElectroMechanicalType ()
Definition at line 967 of file LinkConfiguration.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getCoreEmPart().
getHardwareIndex()
int com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getHardwareIndex ()
gets the hardware index for maping this kinematics link to its assocaited hardware index.
Returns
the hardware index
Definition at line 490 of file LinkConfiguration.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.index.
Referenced by com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.getHeater(), com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.getLink(), com.neuronrobotics.sdk.addons.kinematics.LinkFactory.getLinkLocal(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getPidConfiguration(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getXml(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.homeLink(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.LinkConfiguration(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.onLinkLimit(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.setDevice(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setPidConfiguration(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setTargetValue(), and com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.toString().
getHomingTicksPerSecond()
int com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getHomingTicksPerSecond ()
Gets the homing ticks per second.
Returns
the homing ticks per second
Definition at line 736 of file LinkConfiguration.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.homingTicksPerSecond.
Referenced by com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getXml(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.LinkConfiguration(), and com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.toString().
getimuFromCentroid()
TransformNR com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getimuFromCentroid ()
Definition at line 937 of file LinkConfiguration.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.imuFromCentroid.
Referenced by com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getXml(), and com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.LinkConfiguration().
getIndexLatch()
double com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getIndexLatch ()
Gets the index latch.
Returns
the index latch
Definition at line 680 of file LinkConfiguration.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.indexLatch.
Referenced by com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getPidConfiguration(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getXml(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.homeLink(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.LinkConfiguration(), and com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.setDevice().
getKD()
double com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getKD ()
Gets the kd.
Returns
the kd
Definition at line 607 of file LinkConfiguration.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.k.
Referenced by com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getPidConfiguration(), and com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.setDevice().
getKI()
double com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getKI ()
Gets the ki.
Returns
the ki
Definition at line 598 of file LinkConfiguration.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.k.
Referenced by com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getPidConfiguration(), and com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.setDevice().
getKP()
double com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getKP ()
Gets the kp.
Returns
the kp
Definition at line 589 of file LinkConfiguration.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.k.
Referenced by com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getPidConfiguration(), and com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.setDevice().
getLinkIndex()
int com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getLinkIndex ()
THis is the index of this link in its kinematics chain.
Returns
the link index
Definition at line 782 of file LinkConfiguration.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.linkIndex.
Referenced by com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager._generateStls().
getListeners()
ArrayList<ILinkConfigurationChangeListener> com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getListeners ()
Definition at line 1109 of file LinkConfiguration.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.listeners.
Referenced by com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.addChangeListener(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.clearChangeListener(), and com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.removeChangeListener().
getLowerLimit()
double com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getLowerLimit ()
Gets the lower limit.
Returns
the lower limit
Definition at line 580 of file LinkConfiguration.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.lowerLimit.
Referenced by com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getLowerLimit(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getXml(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.homeLink(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.LinkConfiguration(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.setDesiredJointAxisValue(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setStaticOffset(), and com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.toString().
getLowerVelocity()
double com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getLowerVelocity ()
Gets the lower velocity.
Returns
the lower velocity
Definition at line 773 of file LinkConfiguration.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.velocityLimit.
Referenced by com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getXml().
getMassKg()
double com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getMassKg ()
Definition at line 916 of file LinkConfiguration.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.mass.
Referenced by com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getXml(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.LinkConfiguration(), and com.neuronrobotics.bowlerstudio.physics.MobileBasePhysicsManager.MobileBasePhysicsManager().
getName()
String com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getName ()
Gets the name.
Returns
the name
Definition at line 469 of file LinkConfiguration.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.name.
Referenced by com.neuronrobotics.sdk.addons.kinematics.AbstractLink.AbstractLink(), com.neuronrobotics.bowlerstudio.scripting.RobotHelper.getDefaultContents(), com.neuronrobotics.sdk.addons.kinematics.LinkFactory.getLink(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getXml(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.LinkConfiguration(), and com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.toString().
getPidConfiguration()
PIDConfiguration com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getPidConfiguration ()
Gets the pid configuration.
Returns
the pid configuration
Definition at line 820 of file LinkConfiguration.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getHardwareIndex(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getIndexLatch(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getKD(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getKI(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getKP(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.isInverted(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.isStopOnLatch, com.neuronrobotics.sdk.pid.PIDConfiguration.setGroup(), com.neuronrobotics.sdk.pid.PIDConfiguration.setIndexLatch(), com.neuronrobotics.sdk.pid.PIDConfiguration.setInverted(), com.neuronrobotics.sdk.pid.PIDConfiguration.setKD(), com.neuronrobotics.sdk.pid.PIDConfiguration.setKI(), com.neuronrobotics.sdk.pid.PIDConfiguration.setKP(), and com.neuronrobotics.sdk.pid.PIDConfiguration.setStopOnIndex().
getScale()
double com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getScale ()
Gets the scale.
Returns
the scale
Definition at line 509 of file LinkConfiguration.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.scale.
Referenced by com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getDeviceMaxEngineeringUnits(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getDeviceMinEngineeringUnits(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getMaxEngineeringUnits(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getMinEngineeringUnits(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getScale(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getXml(), com.neuronrobotics.sdk.addons.kinematics.JointLimit.JointLimit(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.LinkConfiguration(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setMaxEngineeringUnits(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setMinEngineeringUnits(), and com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.toString().
getShaftSize()
String com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getShaftSize ()
Definition at line 994 of file LinkConfiguration.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getCoreShaftPart().
getShaftType()
String com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getShaftType ()
Definition at line 985 of file LinkConfiguration.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getCoreShaftPart().
getSlaveLinks()
ArrayList<LinkConfiguration> com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getSlaveLinks ()
Definition at line 907 of file LinkConfiguration.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.slaveLinks.
Referenced by com.neuronrobotics.sdk.addons.kinematics.AbstractLink.AbstractLink(), and com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.loadConfig().
getStaticOffset()
double com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getStaticOffset ()
Gets the static offset.
Returns
the static offset
Definition at line 880 of file LinkConfiguration.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.staticOffset.
Referenced by com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getHome(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getXml(), and com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.LinkConfiguration().
getTotlaNumberOfLinks()
int com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getTotlaNumberOfLinks ()
Gets the totla number of links.
Returns
the totla number of links
Definition at line 801 of file LinkConfiguration.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.totlaNumberOfLinks.
Referenced by com.neuronrobotics.sdk.addons.kinematics.LinkFactory.LinkFactory().
getTypeString()
String com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getTypeString ()
Definition at line 1021 of file LinkConfiguration.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.type.
Referenced by com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.getLink(), com.neuronrobotics.sdk.addons.kinematics.LinkFactory.getLinkLocal(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getXml(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.isPrismatic(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.isTool(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.isVirtual(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.LinkConfiguration(), and com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.toString().
getUpperLimit()
double com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getUpperLimit ()
Gets the upper limit.
Returns
the upper limit
Definition at line 553 of file LinkConfiguration.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.upperLimit.
Referenced by com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getUpperLimit(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getXml(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.homeLink(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.LinkConfiguration(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.setDesiredJointAxisValue(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setStaticOffset(), and com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.toString().
getUpperVelocity()
double com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getUpperVelocity ()
Gets the upper velocity.
Returns
the upper velocity
Definition at line 764 of file LinkConfiguration.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.velocityLimit.
Referenced by com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getMaxVelocityEngineeringUnits(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getXml(), and com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.LinkConfiguration().
getVitamins() [1/2]
HashMap<String, String[]> com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getVitamins ()
Definition at line 1012 of file LinkConfiguration.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.vitamins.
Referenced by com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getXml(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.LinkConfiguration(), and com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setVitamin().
getVitamins() [2/2]
void com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getVitamins (Element doc) protected
Gets the vitamins.
Parameters
doc the doc
Definition at line 275 of file LinkConfiguration.java.
References com.neuronrobotics.sdk.addons.kinematics.xml.XmlFactory.getTagValue(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setVitamin(), and com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setVitaminVariant().
Referenced by com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.LinkConfiguration().
getVitaminVariant()
String com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getVitaminVariant (String name)
Get a purchaing code for a vitamin
Parameters
name name of vitamin
Returns
Definition at line 332 of file LinkConfiguration.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.name, and com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.vitaminVariant.
Referenced by com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getXml().
getXml()
String com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getXml ()
Gets the xml.
Returns
the xml
Definition at line 418 of file LinkConfiguration.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.deviceScriptingName, com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getCenterOfMassFromCentroid(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getDeviceScriptingName(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getDeviceTheoreticalMax(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getDeviceTheoreticalMin(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getHardwareIndex(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getHomingTicksPerSecond(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getimuFromCentroid(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getIndexLatch(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getLowerLimit(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getLowerVelocity(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getMassKg(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getName(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getScale(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getStaticOffset(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getTypeString(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getUpperLimit(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getUpperVelocity(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getVitamins(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getVitaminVariant(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getXml(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.isLatch, com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.isPassive(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.isStopOnLatch, and com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.slaveLinks.
Referenced by com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getEmbedableXml().
isInverted()
boolean com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.isInverted ()
Checks if is inverted.
Returns
true, if is inverted
Definition at line 656 of file LinkConfiguration.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.inverted.
Referenced by com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getPidConfiguration(), and com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.setDevice().
isInvertLimitVelocityPolarity()
boolean com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.isInvertLimitVelocityPolarity ()
Definition at line 898 of file LinkConfiguration.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.invertLimitVelocityPolarity.
isLatch()
boolean com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.isLatch ()
Checks if is latch.
Returns
true, if is latch
Definition at line 698 of file LinkConfiguration.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.isLatch.
isPassive()
boolean com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.isPassive ()
Definition at line 1003 of file LinkConfiguration.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.passive.
Referenced by com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getXml(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.LinkConfiguration(), and com.neuronrobotics.bowlerstudio.physics.MobileBasePhysicsManager.MobileBasePhysicsManager().
isPauseEvents()
boolean com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.isPauseEvents ()
Definition at line 1134 of file LinkConfiguration.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.pauseEvents.
isPrismatic()
boolean com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.isPrismatic ()
Checks if is prismatic.
Returns
true, if is prismatic
Definition at line 1078 of file LinkConfiguration.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getTypeString().
Referenced by com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.addNewLink(), com.neuronrobotics.sdk.addons.kinematics.DHChain.forwardKinematicsMatrix(), com.neuronrobotics.sdk.addons.kinematics.LinkFactory.getLinkLocal(), and com.neuronrobotics.bowlerstudio.physics.MobileBasePhysicsManager.MobileBasePhysicsManager().
isStopOnLatch()
boolean com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.isStopOnLatch ()
Checks if is stop on latch.
Returns
true, if is stop on latch
Definition at line 717 of file LinkConfiguration.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.isStopOnLatch.
isTool()
boolean com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.isTool ()
Checks if is tool.
Returns
true, if is tool
Definition at line 1057 of file LinkConfiguration.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getTypeString().
Referenced by com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.addNewLink().
isVirtual()
boolean com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.isVirtual ()
Checks if is virtual.
Returns
true, if is virtual
Definition at line 1037 of file LinkConfiguration.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getTypeString().
removeChangeListener()
void com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.removeChangeListener (ILinkConfigurationChangeListener l)
Definition at line 1099 of file LinkConfiguration.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getListeners().
Referenced by com.neuronrobotics.sdk.addons.kinematics.AbstractLink.removeChangeListener().
setCenterOfMassFromCentroid()
void com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setCenterOfMassFromCentroid (TransformNR com)
Definition at line 929 of file LinkConfiguration.java.
References com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.addChangeListener(), and com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.removeChangeListener().
Referenced by com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.LinkConfiguration().
setDeviceScriptingName()
void com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setDeviceScriptingName (String deviceScriptingName)
Sets the device scripting name.
Parameters
deviceScriptingName the new device scripting name
Definition at line 870 of file LinkConfiguration.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.deviceScriptingName.
Referenced by com.neuronrobotics.bowlerstudio.scripting.RobotHelper.getDefaultContents(), and com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.LinkConfiguration().
setDeviceTheoreticalMax()
void com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setDeviceTheoreticalMax (double deviceTheoreticalMax)
Definition at line 517 of file LinkConfiguration.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.deviceTheoreticalMax.
Referenced by com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.getLink(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.LinkConfiguration(), com.neuronrobotics.sdk.addons.kinematics.MockRotoryLink.MockRotoryLink(), com.neuronrobotics.sdk.addons.kinematics.PidPrismaticLink.PidPrismaticLink(), com.neuronrobotics.sdk.addons.kinematics.PidRotoryLink.PidRotoryLink(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setDeviceMaximumValue(), and com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setUpperLimit().
setDeviceTheoreticalMin()
void com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setDeviceTheoreticalMin (double deviceTheoreticalMin)
Definition at line 526 of file LinkConfiguration.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.deviceTheoreticalMin.
Referenced by com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.getLink(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.LinkConfiguration(), com.neuronrobotics.sdk.addons.kinematics.MockRotoryLink.MockRotoryLink(), com.neuronrobotics.sdk.addons.kinematics.PidPrismaticLink.PidPrismaticLink(), com.neuronrobotics.sdk.addons.kinematics.PidRotoryLink.PidRotoryLink(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setDeviceMinimumValue(), and com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setLowerLimit().
setElectroMechanicalSize()
void com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setElectroMechanicalSize (String electroMechanicalSize)
Definition at line 980 of file LinkConfiguration.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getCoreEmPart().
Referenced by com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.LinkConfiguration().
setElectroMechanicalType()
void com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setElectroMechanicalType (String electroMechanicalType)
Definition at line 971 of file LinkConfiguration.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getCoreEmPart().
Referenced by com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.LinkConfiguration().
setHardwareIndex()
void com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setHardwareIndex (int index)
sets the hardware index for maping this kinematics link to its assocaited hardware index.
Parameters
index the new hardware index
Definition at line 479 of file LinkConfiguration.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.index.
Referenced by com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.LinkConfiguration().
setHomingTicksPerSecond()
void com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setHomingTicksPerSecond (int homingTicksPerSecond)
Sets the homing ticks per second.
Parameters
homingTicksPerSecond the new homing ticks per second
Definition at line 726 of file LinkConfiguration.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.homingTicksPerSecond.
Referenced by com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.LinkConfiguration(), and com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setPidConfiguration().
setimuFromCentroid()
void com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setimuFromCentroid (TransformNR imu)
Definition at line 941 of file LinkConfiguration.java.
References com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.addChangeListener(), and com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.removeChangeListener().
Referenced by com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.LinkConfiguration().
setIndexLatch()
void com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setIndexLatch (double indexLatch)
Sets the index latch.
Parameters
indexLatch the new index latch
Definition at line 665 of file LinkConfiguration.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getDeviceTheoreticalMax(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getDeviceTheoreticalMin(), and com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.indexLatch.
Referenced by com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.LinkConfiguration().
setInverted()
void com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setInverted (boolean inverted)
Sets the inverted.
Parameters
inverted the new inverted
Definition at line 646 of file LinkConfiguration.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.inverted.
setInvertLimitVelocityPolarity()
void com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setInvertLimitVelocityPolarity (boolean invertVelocity)
Definition at line 902 of file LinkConfiguration.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.invertVelocity.
setKD()
void com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setKD (double kD)
Sets the kd.
Parameters
kD the new kd
Definition at line 636 of file LinkConfiguration.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.k.
setKI()
void com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setKI (double kI)
Sets the ki.
Parameters
kI the new ki
Definition at line 626 of file LinkConfiguration.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.k.
setKP()
void com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setKP (double kP)
Sets the kp.
Parameters
kP the new kp
Definition at line 616 of file LinkConfiguration.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.k.
setLatch()
void com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setLatch (boolean isLatch)
Sets the latch.
Parameters
isLatch the new latch
Definition at line 689 of file LinkConfiguration.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.isLatch.
Referenced by com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.LinkConfiguration().
setLinkIndex()
void com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setLinkIndex (int linkIndex)
This sets the index of the link in itts kinematic chain.
Parameters
linkIndex the new link index
Definition at line 791 of file LinkConfiguration.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.linkIndex.
Referenced by com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.setDevice().
setLowerLimit()
void com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setLowerLimit (double lowerLimit)
Sets the lower limit.
Parameters
lowerLimit the new lower limit
Definition at line 562 of file LinkConfiguration.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getDeviceTheoreticalMin(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.lowerLimit, com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.newAbs, and com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setDeviceTheoreticalMin().
Referenced by com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.LinkConfiguration(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setCurrentAsLowerLimit(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setLowerLimit(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setMaxEngineeringUnits(), and com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setMinEngineeringUnits().
setMassKg()
void com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setMassKg (double mass)
Definition at line 920 of file LinkConfiguration.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.mass.
Referenced by com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.LinkConfiguration().
setName()
void com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setName (String name)
Sets the name.
Parameters
name the new name
Definition at line 458 of file LinkConfiguration.java.
References com.neuronrobotics.sdk.common.Log.info(), and com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.name.
Referenced by com.neuronrobotics.bowlerstudio.scripting.RobotHelper.getDefaultContents(), and com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.LinkConfiguration().
setPassive()
void com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setPassive (boolean passive)
Definition at line 1007 of file LinkConfiguration.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.passive.
Referenced by com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.LinkConfiguration().
setPauseEvents()
void com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setPauseEvents (boolean pauseEvents)
Definition at line 1138 of file LinkConfiguration.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.pauseEvents.
Referenced by com.neuronrobotics.sdk.addons.kinematics.MockRotoryLink.MockRotoryLink(), com.neuronrobotics.sdk.addons.kinematics.PidPrismaticLink.PidPrismaticLink(), and com.neuronrobotics.sdk.addons.kinematics.PidRotoryLink.PidRotoryLink().
setPidConfiguration()
void com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setPidConfiguration (IPidControlNamespace pid)
Sets the pid configuration.
Parameters
pid the new pid configuration
Definition at line 837 of file LinkConfiguration.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getHardwareIndex(), com.neuronrobotics.sdk.pid.PIDConfiguration.getIndexLatch(), com.neuronrobotics.sdk.pid.PIDConfiguration.getKD(), com.neuronrobotics.sdk.pid.PIDConfiguration.getKI(), com.neuronrobotics.sdk.pid.PIDConfiguration.getKP(), com.neuronrobotics.sdk.namespace.bcs.pid.IPidControlNamespace.getPIDConfiguration(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.indexLatch, com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.inverted, com.neuronrobotics.sdk.pid.PIDConfiguration.isInverted(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.isLatch, com.neuronrobotics.sdk.pid.PIDConfiguration.isStopOnIndex(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.isStopOnLatch, com.neuronrobotics.sdk.pid.PIDConfiguration.isUseLatch(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.k, com.neuronrobotics.sdk.addons.kinematics.LinkType.PID, and com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setHomingTicksPerSecond().
Referenced by com.neuronrobotics.sdk.addons.kinematics.LinkFactory.LinkFactory().
setScale()
void com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setScale (double scale)
Sets the scale.
Parameters
scale the new scale
Definition at line 499 of file LinkConfiguration.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.scale.
Referenced by com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.LinkConfiguration(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setCurrentEngineeringUnits(), and com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setScale().
setShaftSize()
void com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setShaftSize (String shaftSize)
Definition at line 998 of file LinkConfiguration.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getCoreShaftPart().
Referenced by com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.LinkConfiguration().
setShaftType()
void com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setShaftType (String shaftType)
Definition at line 989 of file LinkConfiguration.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getCoreShaftPart().
Referenced by com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.LinkConfiguration().
setSlaveLinks()
void com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setSlaveLinks (ArrayList< LinkConfiguration > slaveLinks)
Definition at line 911 of file LinkConfiguration.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.slaveLinks.
setStaticOffset()
void com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setStaticOffset (double staticOffset)
Sets the static offset.
Parameters
staticOffset the new static offset
Definition at line 889 of file LinkConfiguration.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getLowerLimit(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getUpperLimit(), and com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.staticOffset.
Referenced by com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.LinkConfiguration(), and com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setHome().
setStopOnLatch()
void com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setStopOnLatch (boolean isStopOnLatch)
Sets the stop on latch.
Parameters
isStopOnLatch the new stop on latch
Definition at line 707 of file LinkConfiguration.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.isStopOnLatch.
Referenced by com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.LinkConfiguration().
setTotlaNumberOfLinks()
void com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setTotlaNumberOfLinks (int totlaNumberOfLinks)
Sets the totla number of links.
Parameters
totlaNumberOfLinks the new totla number of links
Definition at line 810 of file LinkConfiguration.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.totlaNumberOfLinks.
Referenced by com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.LinkConfiguration().
setTypeString()
void com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setTypeString (String typeString)
Definition at line 1025 of file LinkConfiguration.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.type.
Referenced by com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.LinkConfiguration().
setUpperLimit()
void com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setUpperLimit (double upperLimit)
Sets the upper limit.
Parameters
upperLimit the new upper limit
Definition at line 536 of file LinkConfiguration.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getDeviceTheoreticalMax(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.newAbs, com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setDeviceTheoreticalMax(), and com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.upperLimit.
Referenced by com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.LinkConfiguration(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setCurrentAsUpperLimit(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setMaxEngineeringUnits(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setMinEngineeringUnits(), and com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setUpperLimit().
setUpperVelocity()
void com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setUpperVelocity (double upperVelocity)
Sets the upper velocity.
Parameters
upperVelocity the new upper velocity
Definition at line 754 of file LinkConfiguration.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.LinkConfiguration(), and com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setMaxVelocityEngineeringUnits().
setVitamin()
void com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setVitamin (String name, String type, String id)
Add a vitamin to this link
Parameters
name the name of this vitamin, if the name already exists, the data will be overwritten.
type the vitamin type, this maps the the json filename
id the part ID, theis maps to the key in the json for the vitamin
Definition at line 306 of file LinkConfiguration.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getVitamins(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.name, and com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.type.
Referenced by com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getVitamins().
setVitamins()
void com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setVitamins (HashMap< String, String[]> vitamins)
Definition at line 1016 of file LinkConfiguration.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.vitamins.
setVitaminVariant()
void com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setVitaminVariant (String name, String tagValue2)
Set a purchasing code for a vitamin
Parameters
name name of vitamin
tagValue2 Purchaning code
Definition at line 321 of file LinkConfiguration.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.name, and com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.vitaminVariant.
Referenced by com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getVitamins().
toString()
String com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.toString ()
Definition at line 396 of file LinkConfiguration.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.deviceScriptingName, com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getDeviceScriptingName(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getHardwareIndex(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getHomingTicksPerSecond(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getLowerLimit(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getName(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getScale(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getTypeString(), and com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getUpperLimit().
Member Data Documentation
centerOfMassFromCentroid
TransformNR com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.centerOfMassFromCentroid = new TransformNR() private
Definition at line 80 of file LinkConfiguration.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getCenterOfMassFromCentroid().
deviceScriptingName
String com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.deviceScriptingName = "exampleDevice" private
The device scripting name.
Definition at line 76 of file LinkConfiguration.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getDeviceScriptingName(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getXml(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setDeviceScriptingName(), and com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.toString().
deviceTheoreticalMax
double com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.deviceTheoreticalMax = 180 private
Definition at line 77 of file LinkConfiguration.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getDeviceTheoreticalMax(), and com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setDeviceTheoreticalMax().
deviceTheoreticalMin
double com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.deviceTheoreticalMin = 0 private
Definition at line 78 of file LinkConfiguration.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getDeviceTheoreticalMin(), and com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setDeviceTheoreticalMin().
homingTicksPerSecond
int com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.homingTicksPerSecond = 10000000 private
The homing ticks per second.
Definition at line 70 of file LinkConfiguration.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getHomingTicksPerSecond(), and com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setHomingTicksPerSecond().
imuFromCentroid
TransformNR com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.imuFromCentroid = new TransformNR() private
Definition at line 81 of file LinkConfiguration.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getimuFromCentroid().
index
int com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.index = 0 private
The index.
Definition at line 35 of file LinkConfiguration.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getHardwareIndex(), and com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setHardwareIndex().
indexLatch
double com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.indexLatch = 0 private
The index latch.
Definition at line 64 of file LinkConfiguration.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getIndexLatch(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setIndexLatch(), and com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setPidConfiguration().
inverted
boolean com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.inverted = false private
The inverted.
Definition at line 58 of file LinkConfiguration.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.isInverted(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.LinkConfiguration(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setInverted(), and com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setPidConfiguration().
invertLimitVelocityPolarity
boolean com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.invertLimitVelocityPolarity = false private
This is the flag for setting the direction of the velocity lock out for limit switches
Definition at line 97 of file LinkConfiguration.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.isInvertLimitVelocityPolarity(), and com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.LinkConfiguration().
invertVelocity
boolean com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.invertVelocity = false private
This is the flag for setting the direction of the velocity lock out for limit switches
Definition at line 91 of file LinkConfiguration.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setInvertLimitVelocityPolarity().
isLatch
boolean com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.isLatch = false private
The is latch.
Definition at line 61 of file LinkConfiguration.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getXml(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.isLatch(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.LinkConfiguration(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setLatch(), and com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setPidConfiguration().
isStopOnLatch
boolean com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.isStopOnLatch = false private
The is stop on latch.
Definition at line 67 of file LinkConfiguration.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getPidConfiguration(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getXml(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.isStopOnLatch(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.LinkConfiguration(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setPidConfiguration(), and com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setStopOnLatch().
k
double com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.k[] = new double[] { 1, 0, 0 } private
The k.
Definition at line 55 of file LinkConfiguration.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getKD(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getKI(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getKP(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.LinkConfiguration(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setKD(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setKI(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setKP(), and com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setPidConfiguration().
linkIndex
int com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.linkIndex = 0 private
The link index.
Definition at line 41 of file LinkConfiguration.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getLinkIndex(), and com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setLinkIndex().
listeners
ArrayList<ILinkConfigurationChangeListener> com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.listeners = null private
Definition at line 26 of file LinkConfiguration.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.clearChangeListener(), and com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getListeners().
lowerLimit
double com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.lowerLimit = -100000 private
The lower limit.
Definition at line 52 of file LinkConfiguration.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getLowerLimit(), and com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setLowerLimit().
mass
double com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.mass = 0.01 private
Definition at line 79 of file LinkConfiguration.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getMassKg(), and com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setMassKg().
name
String com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.name = "newLink" private
The name.
Definition at line 29 of file LinkConfiguration.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getName(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getVitaminVariant(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setName(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setVitamin(), and com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setVitaminVariant().
newAbs
boolean com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.newAbs = false private
Definition at line 102 of file LinkConfiguration.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.LinkConfiguration(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setLowerLimit(), and com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setUpperLimit().
passive
boolean com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.passive = false private
Definition at line 101 of file LinkConfiguration.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.isPassive(), and com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setPassive().
pauseEvents
boolean com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.pauseEvents =false private
Definition at line 27 of file LinkConfiguration.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.isPauseEvents(), and com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setPauseEvents().
scale
double com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.scale = 1.0 private
The scale.
Definition at line 46 of file LinkConfiguration.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getScale(), and com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setScale().
slaveLinks
ArrayList<LinkConfiguration> com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.slaveLinks = new ArrayList<LinkConfiguration>() private
Definition at line 85 of file LinkConfiguration.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getSlaveLinks(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getXml(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.LinkConfiguration(), and com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setSlaveLinks().
staticOffset
double com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.staticOffset = 0 private
The static offset.
Definition at line 83 of file LinkConfiguration.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getStaticOffset(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.LinkConfiguration(), and com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setStaticOffset().
totlaNumberOfLinks
int com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.totlaNumberOfLinks = 1 private
The totla number of links.
Definition at line 38 of file LinkConfiguration.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getTotlaNumberOfLinks(), and com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setTotlaNumberOfLinks().
type
String com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.type = "virtual" private
The type.
Definition at line 32 of file LinkConfiguration.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getTypeString(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setTypeString(), and com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setVitamin().
upperLimit
double com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.upperLimit = 100000 private
The upper limit.
Definition at line 49 of file LinkConfiguration.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getUpperLimit(), and com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setUpperLimit().
velocityLimit
double com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.velocityLimit = 100000000 private
The upper velocity.
Definition at line 73 of file LinkConfiguration.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getLowerVelocity(), and com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getUpperVelocity().
vitamins
HashMap<String, String[]> com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.vitamins = new HashMap<String, String[]>() private
Definition at line 99 of file LinkConfiguration.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getCoreEmPart(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getCoreShaftPart(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getVitamins(), and com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setVitamins().
vitaminVariant
HashMap<String, String> com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.vitaminVariant = new HashMap<String, String>() private
Definition at line 100 of file LinkConfiguration.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getVitaminVariant(), and com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setVitaminVariant().
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/addons/kinematics/LinkConfiguration.java