BowlerKernel: eu.mihosoft.vrl.v3d.Icosahedron Class Reference
eu.mihosoft.vrl.v3d.Icosahedron Class Reference
Public Member Functions
Icosahedron ()
Icosahedron (double size)
Icosahedron (Vector3d center, double size)
List< Polygon > toPolygons ()
Vector3d getCenter ()
Icosahedron setCenter (Vector3d center)
double getRadius ()
void setRadius (double radius)
PropertyStorage getProperties ()
Icosahedron noCenter ()
Public Member Functions inherited from eu.mihosoft.vrl.v3d.Primitive
CSG toCSG ()
Private Attributes
Vector3d center
double radius
boolean centered = true
final PropertyStorage properties = new PropertyStorage()
Detailed Description
Definition at line 11 of file Icosahedron.java.
Constructor & Destructor Documentation
Icosahedron() [1/3]
eu.mihosoft.vrl.v3d.Icosahedron.Icosahedron ()
Constructor. Creates a new icosahedron with center
[0,0,0]
and dimensions
[1,1,1]
.
Definition at line 31 of file Icosahedron.java.
References eu.mihosoft.vrl.v3d.Icosahedron.center, and eu.mihosoft.vrl.v3d.Icosahedron.radius.
Icosahedron() [2/3]
eu.mihosoft.vrl.v3d.Icosahedron.Icosahedron (double size)
Constructor. Creates a new icosahedron with center
[0,0,0]
and radius
size
.
Parameters
size size
Definition at line 42 of file Icosahedron.java.
References eu.mihosoft.vrl.v3d.Icosahedron.center, and eu.mihosoft.vrl.v3d.Icosahedron.radius.
Icosahedron() [3/3]
eu.mihosoft.vrl.v3d.Icosahedron.Icosahedron (Vector3d center, double size)
Constructor. Creates a new icosahedron with the specified center and radius.
Parameters
center center of the icosahedron
size of the icosahedron
Definition at line 54 of file Icosahedron.java.
References eu.mihosoft.vrl.v3d.Icosahedron.center.
Member Function Documentation
getCenter()
Vector3d eu.mihosoft.vrl.v3d.Icosahedron.getCenter ()
Gets the center.
Returns
the center
Definition at line 92 of file Icosahedron.java.
References eu.mihosoft.vrl.v3d.Icosahedron.center.
getProperties()
PropertyStorage eu.mihosoft.vrl.v3d.Icosahedron.getProperties ()
Returns the property storage of this primitive.
Returns
the property storage of this primitive
Reimplemented from eu.mihosoft.vrl.v3d.Primitive.
Definition at line 128 of file Icosahedron.java.
References eu.mihosoft.vrl.v3d.Icosahedron.properties.
getRadius()
double eu.mihosoft.vrl.v3d.Icosahedron.getRadius ()
Gets the radius.
Returns
the radius
Definition at line 111 of file Icosahedron.java.
References eu.mihosoft.vrl.v3d.Icosahedron.radius.
noCenter()
Icosahedron eu.mihosoft.vrl.v3d.Icosahedron.noCenter ()
Defines that this icosahedron will not be centered.
Returns
this icosahedron
Definition at line 136 of file Icosahedron.java.
References eu.mihosoft.vrl.v3d.Icosahedron.centered.
setCenter()
Icosahedron eu.mihosoft.vrl.v3d.Icosahedron.setCenter (Vector3d center)
Sets the center.
Parameters
center the center to set
Definition at line 101 of file Icosahedron.java.
References eu.mihosoft.vrl.v3d.Icosahedron.center.
setRadius()
void eu.mihosoft.vrl.v3d.Icosahedron.setRadius (double radius)
Sets the radius.
Parameters
radius the radius to set
Definition at line 120 of file Icosahedron.java.
References eu.mihosoft.vrl.v3d.Icosahedron.radius.
toPolygons()
List<Polygon> eu.mihosoft.vrl.v3d.Icosahedron.toPolygons ()
Returns the polygons that define this primitive.
Note: this method computes the polygons each time this method is called. The polygons can be cached inside a CSG object.
Returns
a list of polygons that define this primitive
Reimplemented from eu.mihosoft.vrl.v3d.Primitive.
Definition at line 63 of file Icosahedron.java.
References eu.mihosoft.vrl.v3d.CSG.getPolygons(), eu.mihosoft.vrl.v3d.ext.quickhull3d.HullUtil.hull(), eu.mihosoft.vrl.v3d.Icosahedron.radius, and eu.mihosoft.vrl.v3d.CSG.scale().
Member Data Documentation
center
Vector3d eu.mihosoft.vrl.v3d.Icosahedron.center private
Center of this icosahedron.
Definition at line 16 of file Icosahedron.java.
Referenced by eu.mihosoft.vrl.v3d.Icosahedron.getCenter(), eu.mihosoft.vrl.v3d.Icosahedron.Icosahedron(), and eu.mihosoft.vrl.v3d.Icosahedron.setCenter().
centered
boolean eu.mihosoft.vrl.v3d.Icosahedron.centered = true private
The centered.
Definition at line 23 of file Icosahedron.java.
Referenced by eu.mihosoft.vrl.v3d.Icosahedron.noCenter().
properties
final PropertyStorage eu.mihosoft.vrl.v3d.Icosahedron.properties = new PropertyStorage() private
The properties.
Definition at line 26 of file Icosahedron.java.
Referenced by eu.mihosoft.vrl.v3d.Icosahedron.getProperties().
radius
double eu.mihosoft.vrl.v3d.Icosahedron.radius private
Icosahedron circumscribed radius.
Definition at line 20 of file Icosahedron.java.
Referenced by eu.mihosoft.vrl.v3d.Icosahedron.getRadius(), eu.mihosoft.vrl.v3d.Icosahedron.Icosahedron(), eu.mihosoft.vrl.v3d.Icosahedron.setRadius(), and eu.mihosoft.vrl.v3d.Icosahedron.toPolygons().
The documentation for this class was generated from the following file:
JCSG/src/main/java/eu/mihosoft/vrl/v3d/Icosahedron.java