BowlerKernel: com.neuronrobotics.bowlerstudio.opencv.OpenCVManager Class Reference
com.neuronrobotics.bowlerstudio.opencv.OpenCVManager Class Reference
Public Member Functions
void disconnectDeviceImp ()
boolean connectDeviceImp ()
ArrayList< String > getNamespacesImp ()
VideoCapture getCapture ()
Public Member Functions inherited from com.neuronrobotics.sdk.common.NonBowlerDevice
boolean connect ()
boolean isAvailable () throws InvalidConnectionException
void disconnect ()
void onAsyncResponse (BowlerDatagram data)
ArrayList< String > getNamespaces ()
Public Member Functions inherited from com.neuronrobotics.sdk.common.BowlerAbstractDevice
void addConnectionEventListener (final IDeviceConnectionEventListener l)
void removeConnectionEventListener (IDeviceConnectionEventListener l)
void setConnection (BowlerAbstractConnection connection)
BowlerAbstractConnection getConnection ()
void setAddress (MACAddress address)
MACAddress getAddress ()
BowlerDatagram send (BowlerAbstractCommand command) throws NoConnectionAvailableException, InvalidResponseException
BowlerDatagram send (BowlerAbstractCommand command, int retry) throws NoConnectionAvailableException, InvalidResponseException
Object[] send (String namespace, BowlerMethod method, String rpcString, Object[] arguments, int retry) throws DeviceConnectionException
Object[] send (String namespace, BowlerMethod method, String rpcString, Object[] arguments) throws DeviceConnectionException
boolean ping ()
boolean ping (boolean switchParser)
ArrayList< ByteList > getRevisions ()
boolean hasNamespace (String string)
void startHeartBeat ()
void startHeartBeat (long msHeartBeatTime)
void stopHeartBeat ()
void setThreadedUpstreamPackets (boolean up)
ArrayList< RpcEncapsulation > getRpcList (String namespace)
void loadRpcList ()
void onAllResponse (BowlerDatagram data)
boolean isKeepAlive ()
void setKeepAlive (boolean keepAlive)
long getLastPacketTime ()
void setLastPacketTime (long lastPacketTime)
String getScriptingName ()
void setScriptingName (String scriptingName)
ArrayList< IDeviceConnectionEventListener > getDisconnectListeners ()
Static Public Member Functions
static OpenCVManager get (int index)
Private Member Functions
OpenCVManager (int camerIndex)
void setCapture (VideoCapture capture)
Private Attributes
int camerIndex
VideoCapture capture
Static Private Attributes
static boolean libLoaded = false
Additional Inherited Members
Protected Member Functions inherited from com.neuronrobotics.sdk.common.BowlerAbstractDevice
void fireDisconnectEvent ()
void fireConnectEvent ()
Detailed Description
Definition at line 10 of file OpenCVManager.java.
Constructor & Destructor Documentation
OpenCVManager()
com.neuronrobotics.bowlerstudio.opencv.OpenCVManager.OpenCVManager (int camerIndex) private
Definition at line 23 of file OpenCVManager.java.
References com.neuronrobotics.bowlerstudio.opencv.OpenCVManager.camerIndex, com.neuronrobotics.sdk.common.NonBowlerDevice.connect(), and com.neuronrobotics.bowlerstudio.opencv.OpenCVManager.libLoaded.
Referenced by com.neuronrobotics.bowlerstudio.opencv.OpenCVManager.get().
Member Function Documentation
connectDeviceImp()
boolean com.neuronrobotics.bowlerstudio.opencv.OpenCVManager.connectDeviceImp ()
Connect device imp.
Returns
true, if successful
Reimplemented from com.neuronrobotics.sdk.common.NonBowlerDevice.
Definition at line 42 of file OpenCVManager.java.
References com.neuronrobotics.bowlerstudio.opencv.OpenCVManager.camerIndex, com.neuronrobotics.bowlerstudio.opencv.OpenCVManager.getCapture(), and com.neuronrobotics.bowlerstudio.opencv.OpenCVManager.setCapture().
disconnectDeviceImp()
void com.neuronrobotics.bowlerstudio.opencv.OpenCVManager.disconnectDeviceImp ()
This method tells the connection object to disconnect its pipes and close out the connection. Once this is called, it is safe to remove your device.
Reimplemented from com.neuronrobotics.sdk.common.NonBowlerDevice.
Definition at line 36 of file OpenCVManager.java.
References com.neuronrobotics.bowlerstudio.opencv.OpenCVManager.getCapture().
get()
static OpenCVManager com.neuronrobotics.bowlerstudio.opencv.OpenCVManager.get (int index) static
Definition at line 30 of file OpenCVManager.java.
References com.neuronrobotics.sdk.common.DeviceManager.getSpecificDevice(), and com.neuronrobotics.bowlerstudio.opencv.OpenCVManager.OpenCVManager().
getCapture()
VideoCapture com.neuronrobotics.bowlerstudio.opencv.OpenCVManager.getCapture ()
Returns
the capture
Definition at line 62 of file OpenCVManager.java.
References com.neuronrobotics.bowlerstudio.opencv.OpenCVManager.capture.
Referenced by com.neuronrobotics.bowlerstudio.opencv.OpenCVManager.connectDeviceImp(), and com.neuronrobotics.bowlerstudio.opencv.OpenCVManager.disconnectDeviceImp().
getNamespacesImp()
ArrayList<String> com.neuronrobotics.bowlerstudio.opencv.OpenCVManager.getNamespacesImp ()
Gets the namespaces imp.
Returns
the namespaces imp
Reimplemented from com.neuronrobotics.sdk.common.NonBowlerDevice.
Definition at line 54 of file OpenCVManager.java.
setCapture()
void com.neuronrobotics.bowlerstudio.opencv.OpenCVManager.setCapture (VideoCapture capture) private
Parameters
capture the capture to set
Definition at line 69 of file OpenCVManager.java.
References com.neuronrobotics.bowlerstudio.opencv.OpenCVManager.capture.
Referenced by com.neuronrobotics.bowlerstudio.opencv.OpenCVManager.connectDeviceImp().
Member Data Documentation
camerIndex
int com.neuronrobotics.bowlerstudio.opencv.OpenCVManager.camerIndex private
Definition at line 12 of file OpenCVManager.java.
Referenced by com.neuronrobotics.bowlerstudio.opencv.OpenCVManager.connectDeviceImp(), and com.neuronrobotics.bowlerstudio.opencv.OpenCVManager.OpenCVManager().
capture
VideoCapture com.neuronrobotics.bowlerstudio.opencv.OpenCVManager.capture private
Definition at line 13 of file OpenCVManager.java.
Referenced by com.neuronrobotics.bowlerstudio.opencv.OpenCVManager.getCapture(), and com.neuronrobotics.bowlerstudio.opencv.OpenCVManager.setCapture().
libLoaded
boolean com.neuronrobotics.bowlerstudio.opencv.OpenCVManager.libLoaded = false static private
Definition at line 11 of file OpenCVManager.java.
Referenced by com.neuronrobotics.bowlerstudio.opencv.OpenCVManager.OpenCVManager().
The documentation for this class was generated from the following file:
src/main/java/com/neuronrobotics/bowlerstudio/opencv/OpenCVManager.java