BowlerKernel: com.neuronrobotics.sdk.addons.kinematics.GradiantDecent Class Reference
com.neuronrobotics.sdk.addons.kinematics.GradiantDecent Class Reference
Public Member Functions
GradiantDecent (DHChain dhChain, boolean debug)
double[] inverseKinematics (TransformNR target, double[] jointSpaceVector, DHChain chain)
Private Attributes
final DHChain dhChain
final boolean debug
Detailed Description
The Class GradiantDecent.
Definition at line 12 of file GradiantDecent.java.
Constructor & Destructor Documentation
GradiantDecent()
com.neuronrobotics.sdk.addons.kinematics.GradiantDecent.GradiantDecent (DHChain dhChain, boolean debug)
Instantiates a new gradiant decent.
Parameters
dhChain the dh chain
debug the debug
Definition at line 26 of file GradiantDecent.java.
References com.neuronrobotics.sdk.addons.kinematics.GradiantDecent.debug, and com.neuronrobotics.sdk.addons.kinematics.GradiantDecent.dhChain.
Member Function Documentation
inverseKinematics()
double [] com.neuronrobotics.sdk.addons.kinematics.GradiantDecent.inverseKinematics (TransformNR target, double[] jointSpaceVector, DHChain chain)
Inverse kinematics.
Parameters
target the target
jointSpaceVector the joint space vector
chain the chain
Returns
the double[]
Implements com.neuronrobotics.sdk.addons.kinematics.DhInverseSolver.
Definition at line 35 of file GradiantDecent.java.
References com.neuronrobotics.sdk.addons.kinematics.GradiantDecent.debug, com.neuronrobotics.sdk.addons.kinematics.GradiantDecent.dhChain, com.neuronrobotics.sdk.addons.kinematics.DHChain.forwardKinematics(), com.neuronrobotics.sdk.addons.kinematics.DHChain.getLinks(), com.neuronrobotics.sdk.addons.kinematics.DHChain.getlowerLimits(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getOffsetOrentationMagnitude(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getOffsetVectorMagnitude(), com.neuronrobotics.sdk.addons.kinematics.DHChain.getUpperLimits(), com.neuronrobotics.sdk.addons.kinematics.GradiantDecentNode.jitter(), and com.neuronrobotics.sdk.addons.kinematics.GradiantDecentNode.step().
Member Data Documentation
debug
final boolean com.neuronrobotics.sdk.addons.kinematics.GradiantDecent.debug private
The debug.
Definition at line 18 of file GradiantDecent.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.GradiantDecent.GradiantDecent(), and com.neuronrobotics.sdk.addons.kinematics.GradiantDecent.inverseKinematics().
dhChain
final DHChain com.neuronrobotics.sdk.addons.kinematics.GradiantDecent.dhChain private
The dh chain.
Definition at line 15 of file GradiantDecent.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.GradiantDecent.GradiantDecent(), and com.neuronrobotics.sdk.addons.kinematics.GradiantDecent.inverseKinematics().
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/addons/kinematics/GradiantDecent.java