BowlerKernel: com.neuronrobotics.sdk.network.BowlerUDPServer Class Reference
com.neuronrobotics.sdk.network.BowlerUDPServer Class Reference
Public Member Functions
BowlerUDPServer ()
BowlerUDPServer (int port)
void disconnect ()
boolean connect ()
boolean reconnect () throws IOException
boolean waitingForConnection ()
DataInputStream getDataIns () throws NullPointerException
DataOutputStream getDataOuts () throws NullPointerException
void write (byte[] data) throws IOException
BowlerDatagram loadPacketFromPhy (ByteList bytesToPacketBuffer) throws NullPointerException, IOException
Public Member Functions inherited from com.neuronrobotics.sdk.common.BowlerAbstractConnection
void setThreadedUpstreamPackets (boolean up)
BowlerDatagram sendSynchronusly (BowlerDatagram sendable)
synchronized BowlerDatagram sendSynchronusly (BowlerDatagram sendable, boolean switchParser)
void sendAsync (BowlerDatagram sendable) throws IOException
void setSynchronusPacketTimeoutTime (int sleepTime)
int getSleepTime ()
long msSinceLastSend ()
synchronized void setConnected (boolean c)
boolean isConnected ()
void clearLastSyncronousResponse ()
BowlerDatagram getLastSyncronousResponse ()
void onDataReceived (BowlerDatagram data)
void addDatagramListener (IBowlerDatagramListener listener)
void removeDatagramListener (IBowlerDatagramListener listener)
void setDataIns (DataInputStream dataIns)
void setDataOuts (DataOutputStream dataOuts)
void setChunkSize (int chunkSize)
int getChunkSize ()
void setAsyncQueue (QueueManager asyncQueue)
void setSyncQueue (QueueManager syncQueue)
QueueManager getAsyncQueue ()
QueueManager getSyncQueue ()
void addConnectionEventListener (IConnectionEventListener l)
void removeConnectionEventListener (IConnectionEventListener l)
void setSynchronousDatagramListener (ISynchronousDatagramListener l)
void removeSynchronousDatagramListener (ISynchronousDatagramListener l)
RpcEncapsulation locateRpc (String namespace, BowlerMethod method, String rpcString)
Object[] parseResponse (String namespace, BowlerMethod method, String rpcString, BowlerDatagram dg)
Object[] send (MACAddress addr, String namespace, BowlerMethod method, String rpcString, Object[] arguments, int retry) throws DeviceConnectionException
boolean isInitializedNamespaces ()
ArrayList< String > getNamespaces (MACAddress addr)
boolean hasNamespace (String string, MACAddress addr)
ArrayList< RpcEncapsulation > getRpcList (String namespace, MACAddress addr)
BowlerDatagram send (BowlerAbstractCommand command, MACAddress addr, int retry) throws NoConnectionAvailableException, InvalidResponseException
BowlerDatagram send (BowlerAbstractCommand command, MACAddress addr, int retry, boolean switchParser) throws NoConnectionAvailableException, InvalidResponseException
BowlerDatagram send (BowlerAbstractCommand command, MACAddress addr) throws NoConnectionAvailableException, InvalidResponseException
BowlerDatagram send (BowlerAbstractCommand command, MACAddress addr, boolean switchParser) throws NoConnectionAvailableException, InvalidResponseException
boolean ping (MACAddress mac)
boolean ping (MACAddress mac, boolean switchParser)
void startHeartBeat ()
void startHeartBeat (long msHeartBeatTime)
void stopHeartBeat ()
double getPercentagePrint ()
void setPercentagePrint (double percentagePrint)
long getLastWrite ()
void setLastWrite (long lastWrite)
boolean isUseThreadedStack ()
void setUseThreadedStack (boolean useThreadedStack)
boolean isBeater ()
void setBeater (boolean beater)
Private Attributes
int sleepTime = 1000
InetAddress IPAddressSet =null
ByteList internalReceiveBuffer = new ByteList()
DatagramSocket udpSock = null
int port = 1865
int destinationPort =port
Additional Inherited Members
Static Public Member Functions inherited from com.neuronrobotics.sdk.common.BowlerAbstractConnection
static BowlerAbstractCommand getCommand (String namespace, BowlerMethod method, String rpcString, Object[] arguments, RpcEncapsulation rpc)
Protected Member Functions inherited from com.neuronrobotics.sdk.common.BowlerAbstractConnection
BowlerDatagram fireSyncOnReceive (BowlerDatagram datagram)
void fireAsyncOnResponse (BowlerDatagram datagram)
void waitForConnectioToBeReady ()
Detailed Description
The Class BowlerUDPServer.
Definition at line 37 of file BowlerUDPServer.java.
Constructor & Destructor Documentation
BowlerUDPServer() [1/2]
com.neuronrobotics.sdk.network.BowlerUDPServer.BowlerUDPServer ()
Instantiates a new bowler udp server.
Definition at line 62 of file BowlerUDPServer.java.
References com.neuronrobotics.sdk.common.BowlerAbstractConnection.setChunkSize(), com.neuronrobotics.sdk.common.BowlerAbstractConnection.setSynchronusPacketTimeoutTime(), and com.neuronrobotics.sdk.network.BowlerUDPServer.sleepTime.
BowlerUDPServer() [2/2]
com.neuronrobotics.sdk.network.BowlerUDPServer.BowlerUDPServer (int port)
Instantiates a new bowler udp server.
Parameters
port the port
Definition at line 72 of file BowlerUDPServer.java.
References com.neuronrobotics.sdk.network.BowlerUDPServer.port, com.neuronrobotics.sdk.common.BowlerAbstractConnection.setChunkSize(), com.neuronrobotics.sdk.common.BowlerAbstractConnection.setSynchronusPacketTimeoutTime(), and com.neuronrobotics.sdk.network.BowlerUDPServer.sleepTime.
Member Function Documentation
connect()
boolean com.neuronrobotics.sdk.network.BowlerUDPServer.connect ()
Attempt to establish a connection. Return if the attempt was successful.
Returns
true, if successful
Reimplemented from com.neuronrobotics.sdk.common.BowlerAbstractConnection.
Definition at line 92 of file BowlerUDPServer.java.
References com.neuronrobotics.sdk.common.BowlerAbstractConnection.isConnected(), com.neuronrobotics.sdk.network.BowlerUDPServer.port, com.neuronrobotics.sdk.common.BowlerAbstractConnection.setConnected(), and com.neuronrobotics.sdk.network.BowlerUDPServer.udpSock.
Referenced by com.neuronrobotics.sdk.network.BowlerUDPServer.reconnect().
disconnect()
void com.neuronrobotics.sdk.network.BowlerUDPServer.disconnect ()
Disconnect and deactive the current connection.
Reimplemented from com.neuronrobotics.sdk.common.BowlerAbstractConnection.
Definition at line 81 of file BowlerUDPServer.java.
References com.neuronrobotics.sdk.common.BowlerAbstractConnection.setConnected(), and com.neuronrobotics.sdk.network.BowlerUDPServer.udpSock.
Referenced by com.neuronrobotics.sdk.network.BowlerUDPServer.reconnect().
getDataIns()
DataInputStream com.neuronrobotics.sdk.network.BowlerUDPServer.getDataIns () throws NullPointerException
Gets the data ins.
Returns
the data ins
Exceptions
NullPointerException the null pointer exception
Reimplemented from com.neuronrobotics.sdk.common.BowlerAbstractConnection.
Definition at line 139 of file BowlerUDPServer.java.
getDataOuts()
DataOutputStream com.neuronrobotics.sdk.network.BowlerUDPServer.getDataOuts () throws NullPointerException
Gets the data outs.
Returns
the data outs
Exceptions
NullPointerException the null pointer exception
Reimplemented from com.neuronrobotics.sdk.common.BowlerAbstractConnection.
Definition at line 151 of file BowlerUDPServer.java.
loadPacketFromPhy()
BowlerDatagram com.neuronrobotics.sdk.network.BowlerUDPServer.loadPacketFromPhy (ByteList bytesToPacketBuffer) throws NullPointerException, IOException
Load packet from phy.
Parameters
bytesToPacketBuffer the bytes to packet buffer
Returns
the bowler datagram
Exceptions
NullPointerException the null pointer exception
IOException Signals that an I/O exception has occurred.
Reimplemented from com.neuronrobotics.sdk.common.BowlerAbstractConnection.
Definition at line 177 of file BowlerUDPServer.java.
References com.neuronrobotics.sdk.common.ByteList.add(), com.neuronrobotics.sdk.network.BowlerUDPServer.destinationPort, com.neuronrobotics.sdk.common.Log.info(), com.neuronrobotics.sdk.network.BowlerUDPServer.internalReceiveBuffer, com.neuronrobotics.sdk.network.BowlerUDPServer.IPAddressSet, com.neuronrobotics.sdk.common.ByteList.pop(), com.neuronrobotics.sdk.common.ByteList.size(), and com.neuronrobotics.sdk.network.BowlerUDPServer.udpSock.
reconnect()
boolean com.neuronrobotics.sdk.network.BowlerUDPServer.reconnect () throws IOException
Reconnect.
Returns
true, if successful
Exceptions
IOException Signals that an I/O exception has occurred.
Definition at line 116 of file BowlerUDPServer.java.
References com.neuronrobotics.sdk.network.BowlerUDPServer.connect(), and com.neuronrobotics.sdk.network.BowlerUDPServer.disconnect().
Referenced by com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.removeServer().
waitingForConnection()
boolean com.neuronrobotics.sdk.network.BowlerUDPServer.waitingForConnection ()
Attempt to re-establish a connection. Return if the attempt was successful.
Returns
true, if successful Attempt to re-establish a connection. Return if the attempt was successful.
true, if successful
Reimplemented from com.neuronrobotics.sdk.common.BowlerAbstractConnection.
Definition at line 126 of file BowlerUDPServer.java.
write()
void com.neuronrobotics.sdk.network.BowlerUDPServer.write (byte[] data) throws IOException
Write.
Parameters
data the data
Exceptions
IOException Signals that an I/O exception has occurred.
Reimplemented from com.neuronrobotics.sdk.common.BowlerAbstractConnection.
Definition at line 163 of file BowlerUDPServer.java.
References com.neuronrobotics.sdk.network.BowlerUDPServer.destinationPort, com.neuronrobotics.sdk.common.Log.info(), com.neuronrobotics.sdk.network.BowlerUDPServer.IPAddressSet, com.neuronrobotics.sdk.common.BowlerAbstractConnection.setLastWrite(), com.neuronrobotics.sdk.network.BowlerUDPServer.udpSock, and com.neuronrobotics.sdk.common.BowlerAbstractConnection.waitForConnectioToBeReady().
Member Data Documentation
destinationPort
int com.neuronrobotics.sdk.network.BowlerUDPServer.destinationPort =port private
The destination port.
Definition at line 57 of file BowlerUDPServer.java.
Referenced by com.neuronrobotics.sdk.network.BowlerUDPServer.loadPacketFromPhy(), and com.neuronrobotics.sdk.network.BowlerUDPServer.write().
internalReceiveBuffer
ByteList com.neuronrobotics.sdk.network.BowlerUDPServer.internalReceiveBuffer = new ByteList() private
The internal receive buffer.
Definition at line 46 of file BowlerUDPServer.java.
Referenced by com.neuronrobotics.sdk.network.BowlerUDPServer.loadPacketFromPhy().
IPAddressSet
InetAddress com.neuronrobotics.sdk.network.BowlerUDPServer.IPAddressSet =null private
The IP address set.
Definition at line 43 of file BowlerUDPServer.java.
Referenced by com.neuronrobotics.sdk.network.BowlerUDPServer.loadPacketFromPhy(), and com.neuronrobotics.sdk.network.BowlerUDPServer.write().
port
int com.neuronrobotics.sdk.network.BowlerUDPServer.port = 1865 private
The port.
Definition at line 54 of file BowlerUDPServer.java.
Referenced by com.neuronrobotics.sdk.network.BowlerUDPServer.BowlerUDPServer(), and com.neuronrobotics.sdk.network.BowlerUDPServer.connect().
sleepTime
int com.neuronrobotics.sdk.network.BowlerUDPServer.sleepTime = 1000 private
The sleep time.
Definition at line 40 of file BowlerUDPServer.java.
Referenced by com.neuronrobotics.sdk.network.BowlerUDPServer.BowlerUDPServer().
udpSock
DatagramSocket com.neuronrobotics.sdk.network.BowlerUDPServer.udpSock = null private
The udp sock.
Definition at line 49 of file BowlerUDPServer.java.
Referenced by com.neuronrobotics.sdk.network.BowlerUDPServer.connect(), com.neuronrobotics.sdk.network.BowlerUDPServer.disconnect(), com.neuronrobotics.sdk.network.BowlerUDPServer.loadPacketFromPhy(), and com.neuronrobotics.sdk.network.BowlerUDPServer.write().
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/network/BowlerUDPServer.java