BowlerKernel: com.neuronrobotics.sdk.addons.kinematics.imu.IMU Class Reference
com.neuronrobotics.sdk.addons.kinematics.imu.IMU Class Reference
Public Member Functions
void addhardwareListeners (IMUUpdateListener l)
void addvirtualListeners (IMUUpdateListener l)
void removehardwareListeners (IMUUpdateListener l)
void removevirtualListeners (IMUUpdateListener l)
void clearhardwareListeners ()
void clearvirtualListeners ()
IMUUpdate getVirtualState ()
void setVirtualState (IMUUpdate virtualState)
IMUUpdate getHardwareState ()
void setHardwareState (IMUUpdate hardwareState)
Private Attributes
ArrayList< IMUUpdateListener > virtualListeneras = new ArrayList<IMUUpdateListener>()
ArrayList< IMUUpdateListener > hardwareListeneras = new ArrayList<IMUUpdateListener>()
IMUUpdate virtualState =new IMUUpdate(0.0,0.0,0.0,0.0,0.0,0.0)
IMUUpdate hardwareState =new IMUUpdate(null,null,null,null,null,null)
Detailed Description
Definition at line 5 of file IMU.java.
Member Function Documentation
addhardwareListeners()
void com.neuronrobotics.sdk.addons.kinematics.imu.IMU.addhardwareListeners (IMUUpdateListener l)
Definition at line 12 of file IMU.java.
References com.neuronrobotics.sdk.addons.kinematics.imu.IMU.hardwareListeneras.
addvirtualListeners()
void com.neuronrobotics.sdk.addons.kinematics.imu.IMU.addvirtualListeners (IMUUpdateListener l)
Definition at line 16 of file IMU.java.
References com.neuronrobotics.sdk.addons.kinematics.imu.IMU.virtualListeneras.
clearhardwareListeners()
void com.neuronrobotics.sdk.addons.kinematics.imu.IMU.clearhardwareListeners ()
Definition at line 29 of file IMU.java.
References com.neuronrobotics.sdk.addons.kinematics.imu.IMU.hardwareListeneras.
clearvirtualListeners()
void com.neuronrobotics.sdk.addons.kinematics.imu.IMU.clearvirtualListeners ()
Definition at line 33 of file IMU.java.
References com.neuronrobotics.sdk.addons.kinematics.imu.IMU.virtualListeneras.
getHardwareState()
IMUUpdate com.neuronrobotics.sdk.addons.kinematics.imu.IMU.getHardwareState ()
Definition at line 47 of file IMU.java.
References com.neuronrobotics.sdk.addons.kinematics.imu.IMU.hardwareState.
getVirtualState()
IMUUpdate com.neuronrobotics.sdk.addons.kinematics.imu.IMU.getVirtualState ()
Definition at line 37 of file IMU.java.
References com.neuronrobotics.sdk.addons.kinematics.imu.IMU.virtualState.
removehardwareListeners()
void com.neuronrobotics.sdk.addons.kinematics.imu.IMU.removehardwareListeners (IMUUpdateListener l)
Definition at line 21 of file IMU.java.
References com.neuronrobotics.sdk.addons.kinematics.imu.IMU.hardwareListeneras.
removevirtualListeners()
void com.neuronrobotics.sdk.addons.kinematics.imu.IMU.removevirtualListeners (IMUUpdateListener l)
Definition at line 25 of file IMU.java.
References com.neuronrobotics.sdk.addons.kinematics.imu.IMU.virtualListeneras.
setHardwareState()
void com.neuronrobotics.sdk.addons.kinematics.imu.IMU.setHardwareState (IMUUpdate hardwareState)
Definition at line 51 of file IMU.java.
References com.neuronrobotics.sdk.addons.kinematics.imu.IMU.hardwareListeneras, and com.neuronrobotics.sdk.addons.kinematics.imu.IMU.hardwareState.
setVirtualState()
void com.neuronrobotics.sdk.addons.kinematics.imu.IMU.setVirtualState (IMUUpdate virtualState)
Definition at line 41 of file IMU.java.
References com.neuronrobotics.sdk.addons.kinematics.imu.IMU.virtualListeneras, and com.neuronrobotics.sdk.addons.kinematics.imu.IMU.virtualState.
Referenced by com.neuronrobotics.bowlerstudio.physics.MobileBasePhysicsManager.getUpdater().
Member Data Documentation
hardwareListeneras
ArrayList<IMUUpdateListener> com.neuronrobotics.sdk.addons.kinematics.imu.IMU.hardwareListeneras = new ArrayList<IMUUpdateListener>() private
Definition at line 7 of file IMU.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.imu.IMU.addhardwareListeners(), com.neuronrobotics.sdk.addons.kinematics.imu.IMU.clearhardwareListeners(), com.neuronrobotics.sdk.addons.kinematics.imu.IMU.removehardwareListeners(), and com.neuronrobotics.sdk.addons.kinematics.imu.IMU.setHardwareState().
hardwareState
IMUUpdate com.neuronrobotics.sdk.addons.kinematics.imu.IMU.hardwareState =new IMUUpdate(null,null,null,null,null,null) private
Definition at line 10 of file IMU.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.imu.IMU.getHardwareState(), and com.neuronrobotics.sdk.addons.kinematics.imu.IMU.setHardwareState().
virtualListeneras
ArrayList<IMUUpdateListener> com.neuronrobotics.sdk.addons.kinematics.imu.IMU.virtualListeneras = new ArrayList<IMUUpdateListener>() private
Definition at line 6 of file IMU.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.imu.IMU.addvirtualListeners(), com.neuronrobotics.sdk.addons.kinematics.imu.IMU.clearvirtualListeners(), com.neuronrobotics.sdk.addons.kinematics.imu.IMU.removevirtualListeners(), and com.neuronrobotics.sdk.addons.kinematics.imu.IMU.setVirtualState().
virtualState
IMUUpdate com.neuronrobotics.sdk.addons.kinematics.imu.IMU.virtualState =new IMUUpdate(0.0,0.0,0.0,0.0,0.0,0.0) private
Definition at line 9 of file IMU.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.imu.IMU.getVirtualState(), and com.neuronrobotics.sdk.addons.kinematics.imu.IMU.setVirtualState().
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/addons/kinematics/imu/IMU.java