BowlerKernel: com.neuronrobotics.sdk.addons.kinematics.AbstractPrismaticLink Class Reference
com.neuronrobotics.sdk.addons.kinematics.AbstractPrismaticLink Class Reference abstract
Public Member Functions
AbstractPrismaticLink (LinkConfiguration conf)
void incrementDisplacment (double inc)
void setTargetDisplacment (double pos)
void setCurrentAsDisplacment (double Displacment)
double getCurrentDisplacment ()
double getTargetDisplacment ()
double getMaxDisplacment ()
double getMinDisplacment ()
boolean isMaxDisplacment ()
boolean isMinDisplacment ()
Public Member Functions inherited from com.neuronrobotics.sdk.addons.kinematics.AbstractLink
double getDeviceMaximumValue ()
double getDeviceMinimumValue ()
void setDeviceMaximumValue (double max)
void setDeviceMinimumValue (double min)
double getDeviceMaxEngineeringUnits ()
double getDeviceMinEngineeringUnits ()
AbstractLink (LinkConfiguration conf)
void cacheTargetValue ()
abstract void cacheTargetValueDevice ()
void flush (double time)
void flushAll (double time)
abstract void flushDevice (double time)
abstract void flushAllDevice (double time)
abstract double getCurrentPosition ()
double toEngineeringUnits (double value)
double toLinkUnits (double euValue)
void addLinkListener (ILinkListener l)
void removeLinkListener (ILinkListener l)
void fireLinkListener (double linkUnitsValue)
void fireLinkLimitEvent (PIDLimitEvent e)
void Home ()
void incrementEngineeringUnits (double inc)
void setTargetEngineeringUnits (double pos)
void setCurrentEngineeringUnits (double angle)
double getCurrentEngineeringUnits ()
double getTargetEngineeringUnits ()
double getMaxEngineeringUnits ()
double getMinEngineeringUnits ()
void setMinEngineeringUnits (double minLimit)
void setMaxEngineeringUnits (double maxLimit)
double getMaxVelocityEngineeringUnits ()
void setMaxVelocityEngineeringUnits (double max)
boolean isMaxEngineeringUnits ()
boolean isMinEngineeringUnits ()
double getTargetValue ()
void setUpperLimit (int upperLimit)
void setLowerLimit (int lowerLimit)
void setHome (int home)
void setScale (double d)
double getScale ()
double getUpperLimit ()
double getLowerLimit ()
double getHome ()
void setCurrentAsUpperLimit ()
void setCurrentAsLowerLimit ()
void setUseLimits (boolean useLimits)
boolean isUseLimits ()
void setLinkConfiguration (LinkConfiguration conf)
LinkConfiguration getLinkConfiguration ()
ArrayList< ILinkListener > getLinks ()
void setLinks (ArrayList< ILinkListener > links)
void removeAllLinkListener ()
void setGlobalPositionListener (Object Object)
Object getGlobalPositionListener ()
LinkFactory getSlaveFactory ()
void setSlaveFactory (LinkFactory slaveFactory)
IMU getImu ()
void addChangeListener (ILinkConfigurationChangeListener l)
void removeChangeListener (ILinkConfigurationChangeListener l)
void clearChangeListener ()
Additional Inherited Members
Protected Member Functions inherited from com.neuronrobotics.sdk.addons.kinematics.AbstractLink
void setPosition (double val)
void setTargetValue (double val)
Detailed Description
The Class AbstractPrismaticLink.
Definition at line 7 of file AbstractPrismaticLink.java.
Constructor & Destructor Documentation
AbstractPrismaticLink()
com.neuronrobotics.sdk.addons.kinematics.AbstractPrismaticLink.AbstractPrismaticLink (LinkConfiguration conf)
Instantiates a new abstract prismatic link.
Parameters
conf the conf
Definition at line 14 of file AbstractPrismaticLink.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractLink.conf.
Member Function Documentation
getCurrentDisplacment()
double com.neuronrobotics.sdk.addons.kinematics.AbstractPrismaticLink.getCurrentDisplacment ()
Gets the current displacment.
Returns
the current displacment
Definition at line 51 of file AbstractPrismaticLink.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getCurrentEngineeringUnits().
getMaxDisplacment()
double com.neuronrobotics.sdk.addons.kinematics.AbstractPrismaticLink.getMaxDisplacment ()
Gets the max displacment.
Returns
the max displacment
Definition at line 69 of file AbstractPrismaticLink.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getMaxEngineeringUnits().
getMinDisplacment()
double com.neuronrobotics.sdk.addons.kinematics.AbstractPrismaticLink.getMinDisplacment ()
Gets the min displacment.
Returns
the min displacment
Definition at line 78 of file AbstractPrismaticLink.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getMinEngineeringUnits().
getTargetDisplacment()
double com.neuronrobotics.sdk.addons.kinematics.AbstractPrismaticLink.getTargetDisplacment ()
Gets the target displacment.
Returns
the target displacment
Definition at line 60 of file AbstractPrismaticLink.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getTargetEngineeringUnits().
incrementDisplacment()
void com.neuronrobotics.sdk.addons.kinematics.AbstractPrismaticLink.incrementDisplacment (double inc)
Increment displacment.
Parameters
inc the inc
Definition at line 24 of file AbstractPrismaticLink.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractLink.incrementEngineeringUnits().
isMaxDisplacment()
boolean com.neuronrobotics.sdk.addons.kinematics.AbstractPrismaticLink.isMaxDisplacment ()
Checks if is max displacment.
Returns
true, if is max displacment
Definition at line 87 of file AbstractPrismaticLink.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractLink.isMaxEngineeringUnits().
isMinDisplacment()
boolean com.neuronrobotics.sdk.addons.kinematics.AbstractPrismaticLink.isMinDisplacment ()
Checks if is min displacment.
Returns
true, if is min displacment
Definition at line 96 of file AbstractPrismaticLink.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractLink.isMinEngineeringUnits().
setCurrentAsDisplacment()
void com.neuronrobotics.sdk.addons.kinematics.AbstractPrismaticLink.setCurrentAsDisplacment (double Displacment)
Sets the current as displacment.
Parameters
Displacment the new current as displacment
Definition at line 42 of file AbstractPrismaticLink.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setCurrentEngineeringUnits().
setTargetDisplacment()
void com.neuronrobotics.sdk.addons.kinematics.AbstractPrismaticLink.setTargetDisplacment (double pos)
Sets the target displacment.
Parameters
pos the new target displacment
Definition at line 33 of file AbstractPrismaticLink.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setTargetEngineeringUnits().
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/addons/kinematics/AbstractPrismaticLink.java