BowlerKernel: eu.mihosoft.vrl.v3d.ext.org.poly2tri.PolygonUtil Class Reference
eu.mihosoft.vrl.v3d.ext.org.poly2tri.PolygonUtil Class Reference
Static Public Member Functions
static List< eu.mihosoft.vrl.v3d.Polygon > concaveToConvex (eu.mihosoft.vrl.v3d.Polygon incoming)
static List< eu.mihosoft.vrl.v3d.Polygon > concaveToConvex (eu.mihosoft.vrl.v3d.Polygon incoming, boolean strictTriangulation)
static Polygon pruneDuplicatePoints (Polygon incoming)
Private Member Functions
PolygonUtil ()
Detailed Description
The Class PolygonUtil.
Author
Michael Hoffer <info@.nosp@m.mich.nosp@m.aelho.nosp@m.ffer.nosp@m..de>
Definition at line 58 of file PolygonUtil.java.
Constructor & Destructor Documentation
PolygonUtil()
eu.mihosoft.vrl.v3d.ext.org.poly2tri.PolygonUtil.PolygonUtil () private
Instantiates a new polygon util.
Definition at line 63 of file PolygonUtil.java.
Member Function Documentation
concaveToConvex() [1/2]
static List<eu.mihosoft.vrl.v3d.Polygon> eu.mihosoft.vrl.v3d.ext.org.poly2tri.PolygonUtil.concaveToConvex (eu.mihosoft.vrl.v3d.Polygon incoming) static
Concave to convex.
Parameters
incoming the concave
Returns
the list
Definition at line 104 of file PolygonUtil.java.
Referenced by eu.mihosoft.vrl.v3d.Edge.boundaryPolygonsOfPlaneGroup(), eu.mihosoft.vrl.v3d.CSG.fixDegenerates(), eu.mihosoft.vrl.v3d.Polygon.fromConcavePoints(), eu.mihosoft.vrl.v3d.Extrude.polygons(), and eu.mihosoft.vrl.v3d.CSG.updatePolygons().
concaveToConvex() [2/2]
static List<eu.mihosoft.vrl.v3d.Polygon> eu.mihosoft.vrl.v3d.ext.org.poly2tri.PolygonUtil.concaveToConvex (eu.mihosoft.vrl.v3d.Polygon incoming, boolean strictTriangulation) static
Definition at line 107 of file PolygonUtil.java.
References eu.mihosoft.vrl.v3d.Debug3dProvider.addObject(), eu.mihosoft.vrl.v3d.Debug3dProvider.clearScreen(), eu.mihosoft.vrl.v3d.Vector3d.clone(), eu.mihosoft.vrl.v3d.Plane.EPSILON, eu.mihosoft.vrl.v3d.Transform.inverse(), eu.mihosoft.vrl.v3d.Extrude.isCCW(), eu.mihosoft.vrl.v3d.Transform.rotx(), eu.mihosoft.vrl.v3d.Transform.roty(), eu.mihosoft.vrl.v3d.Vector3d.x(), eu.mihosoft.vrl.v3d.Vector3d.y(), and eu.mihosoft.vrl.v3d.Vector3d.z().
pruneDuplicatePoints()
static Polygon eu.mihosoft.vrl.v3d.ext.org.poly2tri.PolygonUtil.pruneDuplicatePoints (Polygon incoming) static
Definition at line 349 of file PolygonUtil.java.
References eu.mihosoft.vrl.v3d.Plane.EPSILON_duplicate, eu.mihosoft.vrl.v3d.Vertex.pos, and eu.mihosoft.vrl.v3d.Polygon.vertices.
The documentation for this class was generated from the following file:
JCSG/src/main/java/eu/mihosoft/vrl/v3d/ext/org/poly2tri/PolygonUtil.java