BowlerKernel: com.neuronrobotics.bowlerstudio.creature.MobileBaseLoader Class Reference
com.neuronrobotics.bowlerstudio.creature.MobileBaseLoader Class Reference
Public Member Functions
void setGitDhEngine (String gitsId, String file, DHParameterKinematics dh)
File setDefaultDhParameterKinematics (DHParameterKinematics device)
void setDefaultWalkingEngine (MobileBase device)
void setGitWalkingEngine (String git, String file, MobileBase device)
MobileBase getBase ()
void setBase (MobileBase base)
Static Public Member Functions
static MobileBase initializeScripts (MobileBase base)
static MobileBase fromGit (String id, String file) throws Exception
static MobileBaseLoader get (MobileBase base)
Private Member Functions
MobileBaseLoader (MobileBase base)
Private Attributes
MobileBase base
IDriveEngine defaultDriveEngine
Static Private Attributes
static HashMap< MobileBase, MobileBaseLoader > map = new HashMap<>()
Detailed Description
Definition at line 21 of file MobileBaseLoader.java.
Constructor & Destructor Documentation
MobileBaseLoader()
com.neuronrobotics.bowlerstudio.creature.MobileBaseLoader.MobileBaseLoader (MobileBase base) private
Definition at line 26 of file MobileBaseLoader.java.
References com.neuronrobotics.bowlerstudio.creature.MobileBaseLoader.base, com.neuronrobotics.sdk.addons.kinematics.MobileBase.initializeParalellGroups(), com.neuronrobotics.bowlerstudio.creature.MobileBaseLoader.setBase(), and com.neuronrobotics.bowlerstudio.creature.MobileBaseLoader.setDefaultWalkingEngine().
Referenced by com.neuronrobotics.bowlerstudio.creature.MobileBaseLoader.initializeScripts().
Member Function Documentation
fromGit()
static MobileBase com.neuronrobotics.bowlerstudio.creature.MobileBaseLoader.fromGit (String id, String file) throws Exception static
Definition at line 153 of file MobileBaseLoader.java.
References com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.codeFromGit(), com.neuronrobotics.bowlerstudio.creature.MobileBaseLoader.initializeScripts(), and com.neuronrobotics.sdk.addons.kinematics.MobileBase.setGitSelfSource().
get()
static MobileBaseLoader com.neuronrobotics.bowlerstudio.creature.MobileBaseLoader.get (MobileBase base) static
Definition at line 161 of file MobileBaseLoader.java.
References com.neuronrobotics.bowlerstudio.creature.MobileBaseLoader.base, com.neuronrobotics.bowlerstudio.creature.MobileBaseLoader.initializeScripts(), and com.neuronrobotics.bowlerstudio.creature.MobileBaseLoader.map.
Referenced by com.neuronrobotics.bowlerstudio.scripting.RobotHelper.inlineScriptRun(), and com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.setMobileBase().
getBase()
MobileBase com.neuronrobotics.bowlerstudio.creature.MobileBaseLoader.getBase ()
Definition at line 167 of file MobileBaseLoader.java.
References com.neuronrobotics.bowlerstudio.creature.MobileBaseLoader.base.
Referenced by com.neuronrobotics.bowlerstudio.scripting.RobotHelper.inlineScriptRun().
initializeScripts()
static MobileBase com.neuronrobotics.bowlerstudio.creature.MobileBaseLoader.initializeScripts (MobileBase base) static
Definition at line 133 of file MobileBaseLoader.java.
References com.neuronrobotics.bowlerstudio.creature.MobileBaseLoader.base, com.neuronrobotics.bowlerstudio.creature.MobileBaseLoader.map, and com.neuronrobotics.bowlerstudio.creature.MobileBaseLoader.MobileBaseLoader().
Referenced by com.neuronrobotics.bowlerstudio.creature.MobileBaseLoader.fromGit(), and com.neuronrobotics.bowlerstudio.creature.MobileBaseLoader.get().
setBase()
void com.neuronrobotics.bowlerstudio.creature.MobileBaseLoader.setBase (MobileBase base)
Definition at line 171 of file MobileBaseLoader.java.
References com.neuronrobotics.bowlerstudio.creature.MobileBaseLoader.base.
Referenced by com.neuronrobotics.bowlerstudio.creature.MobileBaseLoader.MobileBaseLoader().
setDefaultDhParameterKinematics()
File com.neuronrobotics.bowlerstudio.creature.MobileBaseLoader.setDefaultDhParameterKinematics (DHParameterKinematics device)
Definition at line 40 of file MobileBaseLoader.java.
References com.neuronrobotics.bowlerstudio.creature.MobileBaseLoader.base, com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.fileFromGit(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.get(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getGitDhEngine(), com.neuronrobotics.sdk.common.BowlerAbstractDevice.getScriptingName(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getUi(), com.neuronrobotics.bowlerstudio.creature.IMobileBaseUI.highlightException(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.inlineFileScriptRun(), com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.setInverseSolver(), and com.neuronrobotics.bowlerstudio.util.FileWatchDeviceWrapper.watch().
Referenced by com.neuronrobotics.bowlerstudio.creature.MobileBaseLoader.setDefaultWalkingEngine(), and com.neuronrobotics.bowlerstudio.creature.MobileBaseLoader.setGitDhEngine().
setDefaultWalkingEngine()
void com.neuronrobotics.bowlerstudio.creature.MobileBaseLoader.setDefaultWalkingEngine (MobileBase device)
Definition at line 77 of file MobileBaseLoader.java.
References com.neuronrobotics.bowlerstudio.creature.MobileBaseLoader.defaultDriveEngine, com.neuronrobotics.sdk.addons.kinematics.MobileBase.getAllDHChains(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.getGitWalkingEngine(), com.neuronrobotics.bowlerstudio.creature.MobileBaseLoader.setDefaultDhParameterKinematics(), and com.neuronrobotics.bowlerstudio.creature.MobileBaseLoader.setGitWalkingEngine().
Referenced by com.neuronrobotics.bowlerstudio.creature.MobileBaseLoader.MobileBaseLoader().
setGitDhEngine()
void com.neuronrobotics.bowlerstudio.creature.MobileBaseLoader.setGitDhEngine (String gitsId, String file, DHParameterKinematics dh)
Definition at line 33 of file MobileBaseLoader.java.
References com.neuronrobotics.bowlerstudio.creature.MobileBaseLoader.setDefaultDhParameterKinematics(), and com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.setGitDhEngine().
setGitWalkingEngine()
void com.neuronrobotics.bowlerstudio.creature.MobileBaseLoader.setGitWalkingEngine (String git, String file, MobileBase device)
Definition at line 86 of file MobileBaseLoader.java.
References com.neuronrobotics.bowlerstudio.creature.MobileBaseLoader.base, com.neuronrobotics.bowlerstudio.creature.MobileBaseLoader.defaultDriveEngine, com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.deleteRepo(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.fileFromGit(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.get(), com.neuronrobotics.sdk.common.BowlerAbstractDevice.getScriptingName(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getUi(), com.neuronrobotics.bowlerstudio.creature.IMobileBaseUI.highlightException(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.inlineFileScriptRun(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.setGitWalkingEngine(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.setWalkingDriveEngine(), and com.neuronrobotics.bowlerstudio.util.FileWatchDeviceWrapper.watch().
Referenced by com.neuronrobotics.bowlerstudio.creature.MobileBaseLoader.setDefaultWalkingEngine().
Member Data Documentation
base
MobileBase com.neuronrobotics.bowlerstudio.creature.MobileBaseLoader.base private
Definition at line 23 of file MobileBaseLoader.java.
Referenced by com.neuronrobotics.bowlerstudio.creature.MobileBaseLoader.get(), com.neuronrobotics.bowlerstudio.creature.MobileBaseLoader.getBase(), com.neuronrobotics.bowlerstudio.creature.MobileBaseLoader.initializeScripts(), com.neuronrobotics.bowlerstudio.creature.MobileBaseLoader.MobileBaseLoader(), com.neuronrobotics.bowlerstudio.creature.MobileBaseLoader.setBase(), com.neuronrobotics.bowlerstudio.creature.MobileBaseLoader.setDefaultDhParameterKinematics(), and com.neuronrobotics.bowlerstudio.creature.MobileBaseLoader.setGitWalkingEngine().
defaultDriveEngine
IDriveEngine com.neuronrobotics.bowlerstudio.creature.MobileBaseLoader.defaultDriveEngine private
Definition at line 24 of file MobileBaseLoader.java.
Referenced by com.neuronrobotics.bowlerstudio.creature.MobileBaseLoader.setDefaultWalkingEngine(), and com.neuronrobotics.bowlerstudio.creature.MobileBaseLoader.setGitWalkingEngine().
map
HashMap<MobileBase, MobileBaseLoader> com.neuronrobotics.bowlerstudio.creature.MobileBaseLoader.map = new HashMap<>() static private
Definition at line 22 of file MobileBaseLoader.java.
Referenced by com.neuronrobotics.bowlerstudio.creature.MobileBaseLoader.get(), and com.neuronrobotics.bowlerstudio.creature.MobileBaseLoader.initializeScripts().
The documentation for this class was generated from the following file:
src/main/java/com/neuronrobotics/bowlerstudio/creature/MobileBaseLoader.java