BowlerKernel: eu.mihosoft.vrl.v3d.TextExtrude Class Reference
eu.mihosoft.vrl.v3d.TextExtrude Class Reference
Classes
class LineSegment
Public Member Functions
List< LineSegment > getLineSegment ()
List< Vector3d > getOffset ()
Static Public Member Functions
static ArrayList< CSG > text (double dir, String text, Font font)
Private Member Functions
TextExtrude (String text, Font font, double dir)
void getPoints (PathElement elem)
void loadPoints ()
Vector3d evalCubicBezier (CubicCurveTo c, Vector3d ini, double t)
Vector3d evalQuadBezier (QuadCurveTo c, Vector3d ini, double t)
double getArea ()
boolean isHole ()
Path generatePath ()
Private Attributes
final String text
List< Vector3d > points
Vector3d p0
final List< LineSegment > polis = new ArrayList<>()
double dir
Static Private Attributes
static final String default_font = "FreeSerif"
static final int POINTS_CURVE = 10
Detailed Description
The Class Text.
Definition at line 29 of file TextExtrude.java.
Constructor & Destructor Documentation
TextExtrude()
eu.mihosoft.vrl.v3d.TextExtrude.TextExtrude (String text, Font font, double dir) private
Definition at line 120 of file TextExtrude.java.
References eu.mihosoft.vrl.v3d.CSG.difference().
Member Function Documentation
evalCubicBezier()
Vector3d eu.mihosoft.vrl.v3d.TextExtrude.evalCubicBezier (CubicCurveTo c, Vector3d ini, double t) private
Definition at line 236 of file TextExtrude.java.
References eu.mihosoft.vrl.v3d.Vector3d.x(), and eu.mihosoft.vrl.v3d.Vector3d.y().
evalQuadBezier()
Vector3d eu.mihosoft.vrl.v3d.TextExtrude.evalQuadBezier (QuadCurveTo c, Vector3d ini, double t) private
Definition at line 249 of file TextExtrude.java.
References eu.mihosoft.vrl.v3d.Vector3d.x(), and eu.mihosoft.vrl.v3d.Vector3d.y().
generatePath()
Path eu.mihosoft.vrl.v3d.TextExtrude.generatePath () private
Definition at line 275 of file TextExtrude.java.
getArea()
double eu.mihosoft.vrl.v3d.TextExtrude.getArea () private
Definition at line 260 of file TextExtrude.java.
getLineSegment()
List<LineSegment> eu.mihosoft.vrl.v3d.TextExtrude.getLineSegment ()
Definition at line 181 of file TextExtrude.java.
getOffset()
List<Vector3d> eu.mihosoft.vrl.v3d.TextExtrude.getOffset ()
Definition at line 185 of file TextExtrude.java.
getPoints()
void eu.mihosoft.vrl.v3d.TextExtrude.getPoints (PathElement elem) private
Definition at line 190 of file TextExtrude.java.
isHole()
boolean eu.mihosoft.vrl.v3d.TextExtrude.isHole () private
Definition at line 269 of file TextExtrude.java.
loadPoints()
void eu.mihosoft.vrl.v3d.TextExtrude.loadPoints () private
Definition at line 221 of file TextExtrude.java.
References eu.mihosoft.vrl.v3d.Polygon.fromPoints(), eu.mihosoft.vrl.v3d.Extrude.isCCW(), and eu.mihosoft.vrl.v3d.Extrude.points().
text()
static ArrayList<CSG> eu.mihosoft.vrl.v3d.TextExtrude.text (double dir, String text, Font font) static
Extrudes the specified path (convex or concave polygon without holes or intersections, specified in CCW) into the specified direction.
Parameters
dir direction of extrusion
text text
font font configuration of the text
Returns
a CSG object that consists of the extruded polygon
Definition at line 174 of file TextExtrude.java.
Member Data Documentation
default_font
final String eu.mihosoft.vrl.v3d.TextExtrude.default_font = "FreeSerif" static private
Definition at line 30 of file TextExtrude.java.
dir
double eu.mihosoft.vrl.v3d.TextExtrude.dir private
Definition at line 39 of file TextExtrude.java.
p0
Vector3d eu.mihosoft.vrl.v3d.TextExtrude.p0 private
Definition at line 35 of file TextExtrude.java.
points
List<Vector3d> eu.mihosoft.vrl.v3d.TextExtrude.points private
Definition at line 34 of file TextExtrude.java.
POINTS_CURVE
final int eu.mihosoft.vrl.v3d.TextExtrude.POINTS_CURVE = 10 static private
Definition at line 31 of file TextExtrude.java.
polis
final List<LineSegment> eu.mihosoft.vrl.v3d.TextExtrude.polis = new ArrayList<>() private
Definition at line 36 of file TextExtrude.java.
text
final String eu.mihosoft.vrl.v3d.TextExtrude.text private
Definition at line 33 of file TextExtrude.java.
Referenced by eu.mihosoft.vrl.v3d.CSG.text(), and eu.mihosoft.vrl.v3d.Text3d.Text3d().
The documentation for this class was generated from the following file:
JCSG/src/main/java/eu/mihosoft/vrl/v3d/TextExtrude.java