BowlerKernel: com.neuronrobotics.sdk.addons.kinematics.AnalogRotoryLink Class Reference
com.neuronrobotics.sdk.addons.kinematics.AnalogRotoryLink Class Reference
Public Member Functions
AnalogRotoryLink (AnalogInputChannel c, LinkConfiguration conf)
void cacheTargetValueDevice ()
void flushDevice (double time)
void flushAllDevice (double time)
double getCurrentPosition ()
void setAnalogChannel (AnalogInputChannel channel)
AnalogInputChannel getChannel ()
void onAnalogValueChange (AnalogInputChannel chan, double value)
Public Member Functions inherited from com.neuronrobotics.sdk.addons.kinematics.AbstractRotoryLink
AbstractRotoryLink (LinkConfiguration conf)
void incrementAngle (double inc)
void setTargetAngle (double pos)
void setCurrentAsAngle (double angle)
double getCurrentAngle ()
double getTargetAngle ()
double getMaxAngle ()
double getMinAngle ()
boolean isMaxAngle ()
boolean isMinAngle ()
Public Member Functions inherited from com.neuronrobotics.sdk.addons.kinematics.AbstractLink
double getDeviceMaximumValue ()
double getDeviceMinimumValue ()
void setDeviceMaximumValue (double max)
void setDeviceMinimumValue (double min)
double getDeviceMaxEngineeringUnits ()
double getDeviceMinEngineeringUnits ()
AbstractLink (LinkConfiguration conf)
void cacheTargetValue ()
void flush (double time)
void flushAll (double time)
double toEngineeringUnits (double value)
double toLinkUnits (double euValue)
void addLinkListener (ILinkListener l)
void removeLinkListener (ILinkListener l)
void fireLinkListener (double linkUnitsValue)
void fireLinkLimitEvent (PIDLimitEvent e)
void Home ()
void incrementEngineeringUnits (double inc)
void setTargetEngineeringUnits (double pos)
void setCurrentEngineeringUnits (double angle)
double getCurrentEngineeringUnits ()
double getTargetEngineeringUnits ()
double getMaxEngineeringUnits ()
double getMinEngineeringUnits ()
void setMinEngineeringUnits (double minLimit)
void setMaxEngineeringUnits (double maxLimit)
double getMaxVelocityEngineeringUnits ()
void setMaxVelocityEngineeringUnits (double max)
boolean isMaxEngineeringUnits ()
boolean isMinEngineeringUnits ()
double getTargetValue ()
void setUpperLimit (int upperLimit)
void setLowerLimit (int lowerLimit)
void setHome (int home)
void setScale (double d)
double getScale ()
double getUpperLimit ()
double getLowerLimit ()
double getHome ()
void setCurrentAsUpperLimit ()
void setCurrentAsLowerLimit ()
void setUseLimits (boolean useLimits)
boolean isUseLimits ()
void setLinkConfiguration (LinkConfiguration conf)
LinkConfiguration getLinkConfiguration ()
ArrayList< ILinkListener > getLinks ()
void setLinks (ArrayList< ILinkListener > links)
void removeAllLinkListener ()
void setGlobalPositionListener (Object Object)
Object getGlobalPositionListener ()
LinkFactory getSlaveFactory ()
void setSlaveFactory (LinkFactory slaveFactory)
IMU getImu ()
void addChangeListener (ILinkConfigurationChangeListener l)
void removeChangeListener (ILinkConfigurationChangeListener l)
void clearChangeListener ()
Private Attributes
AnalogInputChannel channel
Additional Inherited Members
Protected Member Functions inherited from com.neuronrobotics.sdk.addons.kinematics.AbstractLink
void setPosition (double val)
void setTargetValue (double val)
Detailed Description
The Class AnalogRotoryLink.
Definition at line 11 of file AnalogRotoryLink.java.
Constructor & Destructor Documentation
AnalogRotoryLink()
com.neuronrobotics.sdk.addons.kinematics.AnalogRotoryLink.AnalogRotoryLink (AnalogInputChannel c, LinkConfiguration conf)
Instantiates a new analog rotory link.
Parameters
c the c
conf the conf
Definition at line 22 of file AnalogRotoryLink.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractLink.conf, and com.neuronrobotics.sdk.addons.kinematics.AnalogRotoryLink.setAnalogChannel().
Member Function Documentation
cacheTargetValueDevice()
void com.neuronrobotics.sdk.addons.kinematics.AnalogRotoryLink.cacheTargetValueDevice ()
This method is called in order to take the target value and pass it to the implementation's target value This method should not alter the position of the implementations link If the implementation target does not handle chached values, this should be chached in code.
Reimplemented from com.neuronrobotics.sdk.addons.kinematics.AbstractLink.
Definition at line 31 of file AnalogRotoryLink.java.
flushAllDevice()
void com.neuronrobotics.sdk.addons.kinematics.AnalogRotoryLink.flushAllDevice (double time)
This method will force one link to update its position in the given time (seconds) This will also flush the host controller.
Parameters
time (seconds) for the position update to take
Reimplemented from com.neuronrobotics.sdk.addons.kinematics.AbstractLink.
Definition at line 47 of file AnalogRotoryLink.java.
flushDevice()
void com.neuronrobotics.sdk.addons.kinematics.AnalogRotoryLink.flushDevice (double time)
This method will force one link to update its position in the given time (seconds).
Parameters
time (seconds) for the position update to take
Reimplemented from com.neuronrobotics.sdk.addons.kinematics.AbstractLink.
Definition at line 39 of file AnalogRotoryLink.java.
getChannel()
AnalogInputChannel com.neuronrobotics.sdk.addons.kinematics.AnalogRotoryLink.getChannel ()
Gets the channel.
Returns
the channel
Definition at line 78 of file AnalogRotoryLink.java.
References com.neuronrobotics.sdk.addons.kinematics.AnalogRotoryLink.channel.
Referenced by com.neuronrobotics.sdk.addons.kinematics.AnalogRotoryLink.getCurrentPosition(), and com.neuronrobotics.sdk.addons.kinematics.AnalogRotoryLink.onAnalogValueChange().
getCurrentPosition()
double com.neuronrobotics.sdk.addons.kinematics.AnalogRotoryLink.getCurrentPosition ()
This method should return the current position of the link This method is expected to perform a communication with the device .
Returns
the current position of the link
Reimplemented from com.neuronrobotics.sdk.addons.kinematics.AbstractLink.
Definition at line 55 of file AnalogRotoryLink.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractLink.fireLinkListener(), com.neuronrobotics.sdk.addons.kinematics.AnalogRotoryLink.getChannel(), and com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral.getValue().
onAnalogValueChange()
void com.neuronrobotics.sdk.addons.kinematics.AnalogRotoryLink.onAnalogValueChange (AnalogInputChannel chan, double value)
IAnalogInputListener.
Parameters
chan the chan
value The value of the analog channel is sent to listeners
Implements com.neuronrobotics.sdk.dyio.peripherals.IAnalogInputListener.
Definition at line 86 of file AnalogRotoryLink.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractLink.fireLinkListener(), and com.neuronrobotics.sdk.addons.kinematics.AnalogRotoryLink.getChannel().
setAnalogChannel()
void com.neuronrobotics.sdk.addons.kinematics.AnalogRotoryLink.setAnalogChannel (AnalogInputChannel channel)
Sets the analog channel.
Parameters
channel the new analog channel
Definition at line 66 of file AnalogRotoryLink.java.
References com.neuronrobotics.sdk.dyio.peripherals.AnalogInputChannel.addAnalogInputListener(), com.neuronrobotics.sdk.addons.kinematics.AnalogRotoryLink.channel, and com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral.configAdvancedAsyncNotEqual().
Referenced by com.neuronrobotics.sdk.addons.kinematics.AnalogRotoryLink.AnalogRotoryLink().
Member Data Documentation
channel
AnalogInputChannel com.neuronrobotics.sdk.addons.kinematics.AnalogRotoryLink.channel private
The channel.
Definition at line 14 of file AnalogRotoryLink.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.AnalogRotoryLink.getChannel(), and com.neuronrobotics.sdk.addons.kinematics.AnalogRotoryLink.setAnalogChannel().
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/addons/kinematics/AnalogRotoryLink.java