BowlerKernel: eu.mihosoft.vrl.v3d.Matrix3d Class Reference
eu.mihosoft.vrl.v3d.Matrix3d Class Reference
Public Member Functions
Matrix3d (double m11, double m12, double m13, double m21, double m22, double m23, double m31, double m32, double m33)
String toString ()
boolean equals (Object obj)
Matrix3d times (double a)
Vector3d times (Vector3d a)
Public Attributes
double m11
double m21
double m31
Static Public Attributes
static final Matrix3d ZERO = new Matrix3d(0, 0, 0, 0, 0, 0, 0, 0, 0)
static final Matrix3d UNITY = new Matrix3d(1, 0, 0, 0, 1, 0, 0, 0, 1)
Detailed Description
3D Matrix3d.
Author
cpoliwoda
Definition at line 14 of file Matrix3d.java.
Constructor & Destructor Documentation
Matrix3d()
eu.mihosoft.vrl.v3d.Matrix3d.Matrix3d (double m11, double m12, double m13, double m21, double m22, double m23, double m31, double m32, double m33)
Instantiates a new matrix3d.
Parameters
m11 the m11
m12 the m12
m13 the m13
m21 the m21
m22 the m22
m23 the m23
m31 the m31
m32 the m32
m33 the m33
Definition at line 44 of file Matrix3d.java.
References eu.mihosoft.vrl.v3d.Matrix3d.m11, eu.mihosoft.vrl.v3d.Matrix3d.m21, and eu.mihosoft.vrl.v3d.Matrix3d.m31.
Referenced by eu.mihosoft.vrl.v3d.Matrix3d.equals(), and eu.mihosoft.vrl.v3d.Matrix3d.times().
Member Function Documentation
equals()
boolean eu.mihosoft.vrl.v3d.Matrix3d.equals (Object obj)
Definition at line 72 of file Matrix3d.java.
References eu.mihosoft.vrl.v3d.Matrix3d.m11, eu.mihosoft.vrl.v3d.Matrix3d.m21, eu.mihosoft.vrl.v3d.Matrix3d.m31, and eu.mihosoft.vrl.v3d.Matrix3d.Matrix3d().
times() [1/2]
Matrix3d eu.mihosoft.vrl.v3d.Matrix3d.times (double a)
Returns the product of this matrix and the specified value.
Parameters
a the value
Note: this matrix is not modified.
Returns
the product of this matrix and the specified value
Definition at line 119 of file Matrix3d.java.
References eu.mihosoft.vrl.v3d.Matrix3d.m11, eu.mihosoft.vrl.v3d.Matrix3d.m21, eu.mihosoft.vrl.v3d.Matrix3d.m31, and eu.mihosoft.vrl.v3d.Matrix3d.Matrix3d().
times() [2/2]
Vector3d eu.mihosoft.vrl.v3d.Matrix3d.times (Vector3d a)
Returns the product of this matrix and the specified vector.
Parameters
a the vector
Note: the vector is not modified.
Returns
the product of this matrix and the specified vector
Definition at line 135 of file Matrix3d.java.
References eu.mihosoft.vrl.v3d.Matrix3d.m11, eu.mihosoft.vrl.v3d.Matrix3d.m21, eu.mihosoft.vrl.v3d.Matrix3d.m31, eu.mihosoft.vrl.v3d.Vector3d.x(), eu.mihosoft.vrl.v3d.Vector3d.y(), and eu.mihosoft.vrl.v3d.Vector3d.z().
toString()
String eu.mihosoft.vrl.v3d.Matrix3d.toString ()
Definition at line 62 of file Matrix3d.java.
References eu.mihosoft.vrl.v3d.Matrix3d.m11, eu.mihosoft.vrl.v3d.Matrix3d.m21, and eu.mihosoft.vrl.v3d.Matrix3d.m31.
Member Data Documentation
m11
double eu.mihosoft.vrl.v3d.Matrix3d.m11
The m13.
Definition at line 17 of file Matrix3d.java.
Referenced by eu.mihosoft.vrl.v3d.Matrix3d.equals(), eu.mihosoft.vrl.v3d.Matrix3d.Matrix3d(), eu.mihosoft.vrl.v3d.Matrix3d.times(), and eu.mihosoft.vrl.v3d.Matrix3d.toString().
m21
double eu.mihosoft.vrl.v3d.Matrix3d.m21
The m23.
Definition at line 20 of file Matrix3d.java.
Referenced by eu.mihosoft.vrl.v3d.Matrix3d.equals(), eu.mihosoft.vrl.v3d.Matrix3d.Matrix3d(), eu.mihosoft.vrl.v3d.Matrix3d.times(), and eu.mihosoft.vrl.v3d.Matrix3d.toString().
m31
double eu.mihosoft.vrl.v3d.Matrix3d.m31
The m33.
Definition at line 23 of file Matrix3d.java.
Referenced by eu.mihosoft.vrl.v3d.Matrix3d.equals(), eu.mihosoft.vrl.v3d.Matrix3d.Matrix3d(), eu.mihosoft.vrl.v3d.Matrix3d.times(), and eu.mihosoft.vrl.v3d.Matrix3d.toString().
UNITY
final Matrix3d eu.mihosoft.vrl.v3d.Matrix3d.UNITY = new Matrix3d(1, 0, 0, 0, 1, 0, 0, 0, 1) static
The Constant UNITY.
Definition at line 29 of file Matrix3d.java.
ZERO
final Matrix3d eu.mihosoft.vrl.v3d.Matrix3d.ZERO = new Matrix3d(0, 0, 0, 0, 0, 0, 0, 0, 0) static
The Constant ZERO.
Definition at line 26 of file Matrix3d.java.
The documentation for this class was generated from the following file:
JCSG/src/main/java/eu/mihosoft/vrl/v3d/Matrix3d.java