BowlerKernel: com.neuronrobotics.bowlerstudio.BowlerKernel Class Reference
com.neuronrobotics.bowlerstudio.BowlerKernel Class Reference
Static Public Member Functions
static void main (String[] args) throws Exception
static ArrayList< String > loadHistory () throws IOException
static void writeHistory (List< String > history)
static int speak (String msg, ISpeakingProgress progress)
static int speak (String msg)
static int speak (String msg, Number rate, Number pitch, Number voice, Number shift, Number volume)
static int speak (String msg, Number rate, Number pitch, Number voiceNumber, Number shift, Number volume, ISpeakingProgress progress)
static void upenURL (String string)
static void upenURL (URI htmlUrl)
Static Private Member Functions
static void fail ()
static void finish (long startTime)
static void processReturnedObjectsStart (Object ret, File baseWorkspaceFile)
static void processReturnedObjects (Object ret, ArrayList< CSG > csgBits)
Static Private Attributes
static File historyFile = new File(ScriptingEngine.getWorkspace().getAbsolutePath() + "/bowler.history")
Detailed Description
Definition at line 51 of file BowlerKernel.java.
Member Function Documentation
fail()
static void com.neuronrobotics.bowlerstudio.BowlerKernel.fail () static private
Definition at line 83 of file BowlerKernel.java.
Referenced by com.neuronrobotics.bowlerstudio.BowlerKernel.main(), com.neuronrobotics.bowlerstudio.BowlerKernel.processReturnedObjects(), and com.neuronrobotics.bowlerstudio.BowlerKernel.processReturnedObjectsStart().
finish()
static void com.neuronrobotics.bowlerstudio.BowlerKernel.finish (long startTime) static private
Definition at line 345 of file BowlerKernel.java.
Referenced by com.neuronrobotics.bowlerstudio.BowlerKernel.main().
loadHistory()
static ArrayList<String> com.neuronrobotics.bowlerstudio.BowlerKernel.loadHistory () throws IOException static
Definition at line 521 of file BowlerKernel.java.
References com.neuronrobotics.bowlerstudio.BowlerKernel.historyFile.
Referenced by com.neuronrobotics.bowlerstudio.BowlerKernel.main().
main()
static void com.neuronrobotics.bowlerstudio.BowlerKernel.main (String[] args) throws Exception static
Parameters
args the command line arguments
Definition at line 99 of file BowlerKernel.java.
References com.neuronrobotics.bowlerstudio.BowlerKernel.fail(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.filesInGit(), com.neuronrobotics.bowlerstudio.BowlerKernel.finish(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getRepositoryCloneDirectory(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.gitScriptRun(), eu.mihosoft.vrl.v3d.JavaFXInitializer.go(), com.neuronrobotics.bowlerstudio.BowlerKernel.historyFile, com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.inlineFileScriptRun(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.inlineScriptStringRun(), com.neuronrobotics.bowlerstudio.BowlerKernel.loadHistory(), com.neuronrobotics.bowlerstudio.BowlerKernel.processReturnedObjectsStart(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.pull(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.waitForLogin(), and com.neuronrobotics.bowlerstudio.BowlerKernel.writeHistory().
processReturnedObjects()
static void com.neuronrobotics.bowlerstudio.BowlerKernel.processReturnedObjects (Object ret, ArrayList< CSG > csgBits) static private
Definition at line 414 of file BowlerKernel.java.
References com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager._generateStls(), com.neuronrobotics.bowlerstudio.creature.IgenerateBed.arrangeBed(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.connect(), com.neuronrobotics.sdk.common.NonBowlerDevice.disconnect(), com.neuronrobotics.bowlerstudio.BowlerKernel.fail(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.generateBody(), com.neuronrobotics.bowlerstudio.creature.CadFileExporter.generateManufacturingParts(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.get(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.getGitSelfSource(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getIgenerateBed(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getPrintBed(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getRepositoryCloneDirectory(), com.neuronrobotics.sdk.common.BowlerAbstractDevice.getScriptingName(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getUi(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.setConfigurationViewerMode(), and com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.setUi().
Referenced by com.neuronrobotics.bowlerstudio.BowlerKernel.processReturnedObjectsStart().
processReturnedObjectsStart()
static void com.neuronrobotics.bowlerstudio.BowlerKernel.processReturnedObjectsStart (Object ret, File baseWorkspaceFile) static private
Definition at line 351 of file BowlerKernel.java.
References com.neuronrobotics.bowlerstudio.BowlerKernel.fail(), com.neuronrobotics.bowlerstudio.creature.CadFileExporter.generateManufacturingParts(), com.neuronrobotics.bowlerstudio.printbed.PrintBedManager.hasPrintBed, com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.locateGitUrl(), com.neuronrobotics.bowlerstudio.printbed.PrintBedManager.makePrintBeds(), com.neuronrobotics.bowlerstudio.vitamins.VitaminBomManager.MANUFACTURING_BOM_CSV, com.neuronrobotics.bowlerstudio.vitamins.VitaminBomManager.MANUFACTURING_BOM_JSON, com.neuronrobotics.bowlerstudio.BowlerKernel.processReturnedObjects(), and eu.mihosoft.vrl.v3d.CSG.setProgressMoniter().
Referenced by com.neuronrobotics.bowlerstudio.BowlerKernel.main().
speak() [1/4]
static int com.neuronrobotics.bowlerstudio.BowlerKernel.speak (String msg) static
Definition at line 560 of file BowlerKernel.java.
References com.neuronrobotics.bowlerstudio.BowlerKernel.speak().
speak() [2/4]
static int com.neuronrobotics.bowlerstudio.BowlerKernel.speak (String msg, ISpeakingProgress progress) static
Definition at line 556 of file BowlerKernel.java.
Referenced by com.neuronrobotics.bowlerstudio.BowlerKernel.speak().
speak() [3/4]
static int com.neuronrobotics.bowlerstudio.BowlerKernel.speak (String msg, Number rate, Number pitch, Number voice, Number shift, Number volume) static
Definition at line 566 of file BowlerKernel.java.
References com.neuronrobotics.bowlerstudio.BowlerKernel.speak().
speak() [4/4]
static int com.neuronrobotics.bowlerstudio.BowlerKernel.speak (String msg, Number rate, Number pitch, Number voiceNumber, Number shift, Number volume, ISpeakingProgress progress) static
Definition at line 571 of file BowlerKernel.java.
References com.neuronrobotics.bowlerstudio.CoquiDockerManager.get(), com.neuronrobotics.bowlerstudio.TextToSpeech.getAvailableVoices(), com.neuronrobotics.bowlerstudio.TextToSpeech.getMarytts(), com.neuronrobotics.bowlerstudio.TextToSpeech.setVoice(), com.neuronrobotics.bowlerstudio.CoquiDockerManager.speak(), and com.neuronrobotics.bowlerstudio.TextToSpeech.speak().
upenURL() [1/2]
static void com.neuronrobotics.bowlerstudio.BowlerKernel.upenURL (String string) static
Definition at line 660 of file BowlerKernel.java.
Referenced by com.neuronrobotics.bowlerstudio.vitamins.Vitamins.processSelfPR(), com.neuronrobotics.bowlerstudio.IssueReportingExceptionHandler.runReport(), and com.neuronrobotics.bowlerstudio.vitamins.Vitamins.saveDatabaseForkIfMissing().
upenURL() [2/2]
static void com.neuronrobotics.bowlerstudio.BowlerKernel.upenURL (URI htmlUrl) static
Definition at line 675 of file BowlerKernel.java.
writeHistory()
static void com.neuronrobotics.bowlerstudio.BowlerKernel.writeHistory (List< String > history) static
Definition at line 534 of file BowlerKernel.java.
References com.neuronrobotics.bowlerstudio.BowlerKernel.historyFile.
Referenced by com.neuronrobotics.bowlerstudio.BowlerKernel.main().
Member Data Documentation
historyFile
File com.neuronrobotics.bowlerstudio.BowlerKernel.historyFile = new File(ScriptingEngine.getWorkspace().getAbsolutePath() + "/bowler.history") static private
Definition at line 54 of file BowlerKernel.java.
Referenced by com.neuronrobotics.bowlerstudio.BowlerKernel.loadHistory(), com.neuronrobotics.bowlerstudio.BowlerKernel.main(), and com.neuronrobotics.bowlerstudio.BowlerKernel.writeHistory().
The documentation for this class was generated from the following file:
src/main/java/com/neuronrobotics/bowlerstudio/BowlerKernel.java