BowlerKernel: eu.mihosoft.vrl.v3d.ext.openjfx.importers.Importer3D Class Reference
eu.mihosoft.vrl.v3d.ext.openjfx.importers.Importer3D Class Reference
Static Public Member Functions
static String[] getSupportedFormatExtensionFilters ()
static Node load (String fileUrl) throws IOException
static Node load (String fileUrl, boolean asPolygonMesh) throws IOException
static Pair< Node, Timeline > loadIncludingAnimation (String fileUrl, boolean asPolygonMesh) throws IOException
Detailed Description
Base Importer for all supported 3D file formats.
Definition at line 51 of file Importer3D.java.
Member Function Documentation
getSupportedFormatExtensionFilters()
static String [] eu.mihosoft.vrl.v3d.ext.openjfx.importers.Importer3D.getSupportedFormatExtensionFilters () static
Get array of extension filters for supported file formats.
Returns
array of extension filters for supported file formats.
Definition at line 58 of file Importer3D.java.
load() [1/2]
static Node eu.mihosoft.vrl.v3d.ext.openjfx.importers.Importer3D.load (String fileUrl) throws IOException static
Load a 3D file, always loaded as TriangleMesh.
Parameters
fileUrl The url of the 3D file to load
Returns
The loaded Node which could be a MeshView or a Group
Exceptions
IOException if issue loading file
Definition at line 70 of file Importer3D.java.
load() [2/2]
static Node eu.mihosoft.vrl.v3d.ext.openjfx.importers.Importer3D.load (String fileUrl, boolean asPolygonMesh) throws IOException static
Load a 3D file.
Parameters
fileUrl The url of the 3D file to load
asPolygonMesh When true load as a PolygonMesh if the loader supports
Returns
The loaded Node which could be a MeshView or a Group
Exceptions
IOException if issue loading file
Definition at line 82 of file Importer3D.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.Importer3D.loadIncludingAnimation().
loadIncludingAnimation()
static Pair<Node,Timeline> eu.mihosoft.vrl.v3d.ext.openjfx.importers.Importer3D.loadIncludingAnimation (String fileUrl, boolean asPolygonMesh) throws IOException static
Load a 3D file.
Parameters
fileUrl The url of the 3D file to load
asPolygonMesh When true load as a PolygonMesh if the loader supports
Returns
The loaded Node which could be a MeshView or a Group and the Timeline animation
Exceptions
IOException if issue loading file
Definition at line 94 of file Importer3D.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.ImporterFinder.addUrlToClassPath(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.Importer.getRoot(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.Importer.getTimeline(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.Importer.isSupported(), and eu.mihosoft.vrl.v3d.ext.openjfx.importers.Importer.load().
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.Importer3D.load().
The documentation for this class was generated from the following file:
JCSG/src/main/java/eu/mihosoft/vrl/v3d/ext/openjfx/importers/Importer3D.java