BowlerKernel: com.neuronrobotics.sdk.network.BowlerTCPServer Class Reference
com.neuronrobotics.sdk.network.BowlerTCPServer Class Reference
Public Member Functions
BowlerTCPServer (Socket socket) throws IOException
boolean connect ()
boolean isConnected ()
void disconnect ()
boolean waitingForConnection ()
boolean isClientConnected ()
Public Member Functions inherited from com.neuronrobotics.sdk.common.BowlerAbstractConnection
void setThreadedUpstreamPackets (boolean up)
BowlerDatagram sendSynchronusly (BowlerDatagram sendable)
synchronized BowlerDatagram sendSynchronusly (BowlerDatagram sendable, boolean switchParser)
void sendAsync (BowlerDatagram sendable) throws IOException
void setSynchronusPacketTimeoutTime (int sleepTime)
int getSleepTime ()
long msSinceLastSend ()
synchronized void setConnected (boolean c)
void clearLastSyncronousResponse ()
BowlerDatagram getLastSyncronousResponse ()
void onDataReceived (BowlerDatagram data)
void addDatagramListener (IBowlerDatagramListener listener)
void removeDatagramListener (IBowlerDatagramListener listener)
void setDataIns (DataInputStream dataIns)
DataInputStream getDataIns () throws NullPointerException
void setDataOuts (DataOutputStream dataOuts)
DataOutputStream getDataOuts () throws NullPointerException
void setChunkSize (int chunkSize)
int getChunkSize ()
void setAsyncQueue (QueueManager asyncQueue)
void setSyncQueue (QueueManager syncQueue)
QueueManager getAsyncQueue ()
QueueManager getSyncQueue ()
void addConnectionEventListener (IConnectionEventListener l)
void removeConnectionEventListener (IConnectionEventListener l)
void setSynchronousDatagramListener (ISynchronousDatagramListener l)
void removeSynchronousDatagramListener (ISynchronousDatagramListener l)
RpcEncapsulation locateRpc (String namespace, BowlerMethod method, String rpcString)
Object[] parseResponse (String namespace, BowlerMethod method, String rpcString, BowlerDatagram dg)
Object[] send (MACAddress addr, String namespace, BowlerMethod method, String rpcString, Object[] arguments, int retry) throws DeviceConnectionException
boolean isInitializedNamespaces ()
ArrayList< String > getNamespaces (MACAddress addr)
boolean hasNamespace (String string, MACAddress addr)
ArrayList< RpcEncapsulation > getRpcList (String namespace, MACAddress addr)
BowlerDatagram send (BowlerAbstractCommand command, MACAddress addr, int retry) throws NoConnectionAvailableException, InvalidResponseException
BowlerDatagram send (BowlerAbstractCommand command, MACAddress addr, int retry, boolean switchParser) throws NoConnectionAvailableException, InvalidResponseException
BowlerDatagram send (BowlerAbstractCommand command, MACAddress addr) throws NoConnectionAvailableException, InvalidResponseException
BowlerDatagram send (BowlerAbstractCommand command, MACAddress addr, boolean switchParser) throws NoConnectionAvailableException, InvalidResponseException
boolean ping (MACAddress mac)
boolean ping (MACAddress mac, boolean switchParser)
void startHeartBeat ()
void startHeartBeat (long msHeartBeatTime)
void stopHeartBeat ()
double getPercentagePrint ()
void setPercentagePrint (double percentagePrint)
long getLastWrite ()
void setLastWrite (long lastWrite)
boolean isUseThreadedStack ()
void setUseThreadedStack (boolean useThreadedStack)
boolean isBeater ()
void setBeater (boolean beater)
BowlerDatagram loadPacketFromPhy (ByteList bytesToPacketBuffer) throws NullPointerException, IOException
void write (byte[] data) throws IOException
Private Attributes
int sleepTime = 5000
PrintWriter out
Socket socket
Additional Inherited Members
Static Public Member Functions inherited from com.neuronrobotics.sdk.common.BowlerAbstractConnection
static BowlerAbstractCommand getCommand (String namespace, BowlerMethod method, String rpcString, Object[] arguments, RpcEncapsulation rpc)
Protected Member Functions inherited from com.neuronrobotics.sdk.common.BowlerAbstractConnection
BowlerDatagram fireSyncOnReceive (BowlerDatagram datagram)
void fireAsyncOnResponse (BowlerDatagram datagram)
void waitForConnectioToBeReady ()
Detailed Description
The Class BowlerTCPServer.
Definition at line 34 of file BowlerTCPServer.java.
Constructor & Destructor Documentation
BowlerTCPServer()
com.neuronrobotics.sdk.network.BowlerTCPServer.BowlerTCPServer (Socket socket) throws IOException
Instantiates a new bowler tcp server.
Parameters
socket the socket
Exceptions
IOException Signals that an I/O exception has occurred.
Definition at line 52 of file BowlerTCPServer.java.
References com.neuronrobotics.sdk.network.BowlerTCPServer.connect(), com.neuronrobotics.sdk.network.BowlerTCPServer.out, com.neuronrobotics.sdk.common.BowlerAbstractConnection.setChunkSize(), com.neuronrobotics.sdk.common.BowlerAbstractConnection.setConnected(), com.neuronrobotics.sdk.common.BowlerAbstractConnection.setDataIns(), com.neuronrobotics.sdk.common.BowlerAbstractConnection.setDataOuts(), com.neuronrobotics.sdk.common.BowlerAbstractConnection.setSynchronusPacketTimeoutTime(), com.neuronrobotics.sdk.network.BowlerTCPServer.sleepTime, and com.neuronrobotics.sdk.network.BowlerTCPServer.socket.
Member Function Documentation
connect()
boolean com.neuronrobotics.sdk.network.BowlerTCPServer.connect ()
Attempt to establish a connection. Return if the attempt was successful.
Returns
true, if successful
Reimplemented from com.neuronrobotics.sdk.common.BowlerAbstractConnection.
Definition at line 75 of file BowlerTCPServer.java.
References com.neuronrobotics.sdk.network.BowlerTCPServer.isConnected(), and com.neuronrobotics.sdk.common.Log.warning().
Referenced by com.neuronrobotics.sdk.network.BowlerTCPServer.BowlerTCPServer().
disconnect()
void com.neuronrobotics.sdk.network.BowlerTCPServer.disconnect ()
Disconnect and deactive the current connection.
Reimplemented from com.neuronrobotics.sdk.common.BowlerAbstractConnection.
Definition at line 98 of file BowlerTCPServer.java.
References com.neuronrobotics.sdk.common.BowlerAbstractConnection.getDataIns(), com.neuronrobotics.sdk.network.BowlerTCPServer.isConnected(), com.neuronrobotics.sdk.network.BowlerTCPServer.socket, and com.neuronrobotics.sdk.common.Log.warning().
isClientConnected()
boolean com.neuronrobotics.sdk.network.BowlerTCPServer.isClientConnected ()
Checks if is client connected.
Returns
true, if is client connected
Definition at line 143 of file BowlerTCPServer.java.
References com.neuronrobotics.sdk.network.BowlerTCPServer.out.
Referenced by com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.pushAsyncPacket().
isConnected()
boolean com.neuronrobotics.sdk.network.BowlerTCPServer.isConnected ()
Checks if is connected.
Returns
true, if is connected
Reimplemented from com.neuronrobotics.sdk.common.BowlerAbstractConnection.
Definition at line 90 of file BowlerTCPServer.java.
Referenced by com.neuronrobotics.sdk.network.BowlerTCPServer.connect(), and com.neuronrobotics.sdk.network.BowlerTCPServer.disconnect().
waitingForConnection()
boolean com.neuronrobotics.sdk.network.BowlerTCPServer.waitingForConnection ()
Attempt to re-establish a connection. Return if the attempt was successful.
Returns
true, if successful Attempt to re-establish a connection. Return if the attempt was successful.
true, if successful
Reimplemented from com.neuronrobotics.sdk.common.BowlerAbstractConnection.
Definition at line 134 of file BowlerTCPServer.java.
Member Data Documentation
out
PrintWriter com.neuronrobotics.sdk.network.BowlerTCPServer.out private
The out.
Definition at line 40 of file BowlerTCPServer.java.
Referenced by com.neuronrobotics.sdk.network.BowlerTCPServer.BowlerTCPServer(), and com.neuronrobotics.sdk.network.BowlerTCPServer.isClientConnected().
sleepTime
int com.neuronrobotics.sdk.network.BowlerTCPServer.sleepTime = 5000 private
The sleep time.
Definition at line 37 of file BowlerTCPServer.java.
Referenced by com.neuronrobotics.sdk.network.BowlerTCPServer.BowlerTCPServer().
socket
Socket com.neuronrobotics.sdk.network.BowlerTCPServer.socket private
The socket.
Definition at line 43 of file BowlerTCPServer.java.
Referenced by com.neuronrobotics.sdk.network.BowlerTCPServer.BowlerTCPServer(), and com.neuronrobotics.sdk.network.BowlerTCPServer.disconnect().
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/network/BowlerTCPServer.java