BowlerKernel: eu.mihosoft.vrl.v3d.RoundedCylinder Class Reference
eu.mihosoft.vrl.v3d.RoundedCylinder Class Reference
Public Member Functions
RoundedCylinder (double startRadius, double endRadius, double height, int numSlices)
RoundedCylinder (double startRadius, double height)
List< Polygon > toPolygons ()
PropertyStorage getProperties ()
int getResolution ()
RoundedCylinder resolution (int resolution)
double getCornerRadius ()
RoundedCylinder cornerRadius (double cornerRadius)
int getNumCornerSlices ()
RoundedCylinder setNumCornerSlices (int numCornerSlices)
Public Member Functions inherited from eu.mihosoft.vrl.v3d.Primitive
CSG toCSG ()
Private Attributes
final PropertyStorage properties = new PropertyStorage()
double cornerRadius = 2
int resolution = 30
double startRadius
double endRadius
double height
int numCornerSlices
Detailed Description
The Class RoundedCube.
Author
Michael Hoffer <info@.nosp@m.mich.nosp@m.aelho.nosp@m.ffer.nosp@m..de>
Definition at line 19 of file RoundedCylinder.java.
Constructor & Destructor Documentation
RoundedCylinder() [1/2]
eu.mihosoft.vrl.v3d.RoundedCylinder.RoundedCylinder (double startRadius, double endRadius, double height, int numSlices)
Constructor. Creates a cylinder ranging from
[0,0,0]
to
[0,0,height]
with the specified
radius
and
height
. The resolution of the tessellation can be controlled with
numSlices
.
Parameters
startRadius cylinder start radius
endRadius cylinder end radius
height cylinder height
numSlices number of slices (used for tessellation)
Definition at line 49 of file RoundedCylinder.java.
References eu.mihosoft.vrl.v3d.RoundedCylinder.endRadius, eu.mihosoft.vrl.v3d.RoundedCylinder.height, eu.mihosoft.vrl.v3d.RoundedCylinder.setNumCornerSlices(), and eu.mihosoft.vrl.v3d.RoundedCylinder.startRadius.
RoundedCylinder() [2/2]
eu.mihosoft.vrl.v3d.RoundedCylinder.RoundedCylinder (double startRadius, double height)
Constructor. Creates a cylinder ranging from
[0,0,0]
to
[0,0,height]
with the specified
radius
and
height
. The resolution of the tessellation can be controlled with
numSlices
.
Parameters
startRadius cylinder start radius
height cylinder height
Definition at line 66 of file RoundedCylinder.java.
References eu.mihosoft.vrl.v3d.RoundedCylinder.height, eu.mihosoft.vrl.v3d.RoundedCylinder.setNumCornerSlices(), and eu.mihosoft.vrl.v3d.RoundedCylinder.startRadius.
Member Function Documentation
cornerRadius()
RoundedCylinder eu.mihosoft.vrl.v3d.RoundedCylinder.cornerRadius (double cornerRadius)
Corner radius.
Parameters
cornerRadius the corner radius to set
Returns
this cube
Definition at line 145 of file RoundedCylinder.java.
References eu.mihosoft.vrl.v3d.RoundedCylinder.cornerRadius.
getCornerRadius()
double eu.mihosoft.vrl.v3d.RoundedCylinder.getCornerRadius ()
Gets the corner radius.
Returns
the corner radius
Definition at line 135 of file RoundedCylinder.java.
References eu.mihosoft.vrl.v3d.RoundedCylinder.cornerRadius.
getNumCornerSlices()
int eu.mihosoft.vrl.v3d.RoundedCylinder.getNumCornerSlices ()
Definition at line 152 of file RoundedCylinder.java.
References eu.mihosoft.vrl.v3d.RoundedCylinder.numCornerSlices.
getProperties()
PropertyStorage eu.mihosoft.vrl.v3d.RoundedCylinder.getProperties ()
Returns the property storage of this primitive.
Returns
the property storage of this primitive
Reimplemented from eu.mihosoft.vrl.v3d.Primitive.
Definition at line 105 of file RoundedCylinder.java.
References eu.mihosoft.vrl.v3d.RoundedCylinder.properties.
getResolution()
int eu.mihosoft.vrl.v3d.RoundedCylinder.getResolution ()
Gets the resolution.
Returns
the resolution
Definition at line 115 of file RoundedCylinder.java.
References eu.mihosoft.vrl.v3d.RoundedCylinder.resolution.
resolution()
RoundedCylinder eu.mihosoft.vrl.v3d.RoundedCylinder.resolution (int resolution)
Resolution.
Parameters
resolution the resolution to set
Returns
this cube
Definition at line 125 of file RoundedCylinder.java.
References eu.mihosoft.vrl.v3d.RoundedCylinder.resolution.
setNumCornerSlices()
RoundedCylinder eu.mihosoft.vrl.v3d.RoundedCylinder.setNumCornerSlices (int numCornerSlices)
Definition at line 158 of file RoundedCylinder.java.
References eu.mihosoft.vrl.v3d.RoundedCylinder.numCornerSlices.
Referenced by eu.mihosoft.vrl.v3d.RoundedCylinder.RoundedCylinder().
toPolygons()
List<Polygon> eu.mihosoft.vrl.v3d.RoundedCylinder.toPolygons ()
Returns the polygons that define this primitive.
Note: this method computes the polygons each time this method is called. The polygons can be cached inside a CSG object.
Returns
a list of polygons that define this primitive
Reimplemented from eu.mihosoft.vrl.v3d.Primitive.
Definition at line 79 of file RoundedCylinder.java.
References eu.mihosoft.vrl.v3d.RoundedCylinder.cornerRadius, eu.mihosoft.vrl.v3d.RoundedCylinder.endRadius, eu.mihosoft.vrl.v3d.CSG.getPolygons(), eu.mihosoft.vrl.v3d.RoundedCylinder.height, eu.mihosoft.vrl.v3d.ext.quickhull3d.HullUtil.hull(), eu.mihosoft.vrl.v3d.CSG.movez(), eu.mihosoft.vrl.v3d.RoundedCylinder.numCornerSlices, eu.mihosoft.vrl.v3d.RoundedCylinder.resolution, eu.mihosoft.vrl.v3d.RoundedCylinder.startRadius, eu.mihosoft.vrl.v3d.Primitive.toCSG(), and eu.mihosoft.vrl.v3d.CSG.toZMin().
Member Data Documentation
cornerRadius
double eu.mihosoft.vrl.v3d.RoundedCylinder.cornerRadius = 2 private
The corner radius.
Definition at line 25 of file RoundedCylinder.java.
Referenced by eu.mihosoft.vrl.v3d.RoundedCylinder.cornerRadius(), eu.mihosoft.vrl.v3d.RoundedCylinder.getCornerRadius(), and eu.mihosoft.vrl.v3d.RoundedCylinder.toPolygons().
endRadius
double eu.mihosoft.vrl.v3d.RoundedCylinder.endRadius private
Definition at line 32 of file RoundedCylinder.java.
Referenced by eu.mihosoft.vrl.v3d.RoundedCylinder.RoundedCylinder(), and eu.mihosoft.vrl.v3d.RoundedCylinder.toPolygons().
height
double eu.mihosoft.vrl.v3d.RoundedCylinder.height private
Definition at line 34 of file RoundedCylinder.java.
Referenced by eu.mihosoft.vrl.v3d.RoundedCylinder.RoundedCylinder(), and eu.mihosoft.vrl.v3d.RoundedCylinder.toPolygons().
numCornerSlices
int eu.mihosoft.vrl.v3d.RoundedCylinder.numCornerSlices private
Definition at line 36 of file RoundedCylinder.java.
Referenced by eu.mihosoft.vrl.v3d.RoundedCylinder.getNumCornerSlices(), eu.mihosoft.vrl.v3d.RoundedCylinder.setNumCornerSlices(), and eu.mihosoft.vrl.v3d.RoundedCylinder.toPolygons().
properties
final PropertyStorage eu.mihosoft.vrl.v3d.RoundedCylinder.properties = new PropertyStorage() private
The properties.
Definition at line 22 of file RoundedCylinder.java.
Referenced by eu.mihosoft.vrl.v3d.RoundedCylinder.getProperties().
resolution
int eu.mihosoft.vrl.v3d.RoundedCylinder.resolution = 30 private
The resolution.
Definition at line 28 of file RoundedCylinder.java.
Referenced by eu.mihosoft.vrl.v3d.RoundedCylinder.getResolution(), eu.mihosoft.vrl.v3d.RoundedCylinder.resolution(), and eu.mihosoft.vrl.v3d.RoundedCylinder.toPolygons().
startRadius
double eu.mihosoft.vrl.v3d.RoundedCylinder.startRadius private
Definition at line 30 of file RoundedCylinder.java.
Referenced by eu.mihosoft.vrl.v3d.RoundedCylinder.RoundedCylinder(), and eu.mihosoft.vrl.v3d.RoundedCylinder.toPolygons().
The documentation for this class was generated from the following file:
JCSG/src/main/java/eu/mihosoft/vrl/v3d/RoundedCylinder.java