BowlerKernel: eu.mihosoft.vrl.v3d.RoundedCube Class Reference
eu.mihosoft.vrl.v3d.RoundedCube Class Reference
Public Member Functions
RoundedCube ()
RoundedCube (double size)
RoundedCube (LengthParameter w, LengthParameter h, LengthParameter d)
RoundedCube (LengthParameter size)
RoundedCube (Vector3d center, Vector3d dimensions)
RoundedCube (double w, double h, double d)
List< Polygon > toPolygons ()
PropertyStorage getProperties ()
Vector3d getCenter ()
void setCenter (Vector3d center)
Vector3d getDimensions ()
void setDimensions (Vector3d dimensions)
RoundedCube noCenter ()
int getResolution ()
void setResolution (int resolution)
RoundedCube resolution (int resolution)
double getCornerRadius ()
void setCornerRadius (double cornerRadius)
RoundedCube cornerRadius (double cornerRadius)
Public Member Functions inherited from eu.mihosoft.vrl.v3d.Primitive
CSG toCSG ()
Private Attributes
Vector3d dimensions
Vector3d center
boolean centered =true
final PropertyStorage properties = new PropertyStorage()
double cornerRadius = 0.1
int resolution = 8
Detailed Description
The Class RoundedCube.
Author
Michael Hoffer <info@.nosp@m.mich.nosp@m.aelho.nosp@m.ffer.nosp@m..de>
Definition at line 19 of file RoundedCube.java.
Constructor & Destructor Documentation
RoundedCube() [1/6]
eu.mihosoft.vrl.v3d.RoundedCube.RoundedCube ()
Constructor. Creates a new rounded cube with center
[0,0,0]
and dimensions
[1,1,1]
.
Definition at line 45 of file RoundedCube.java.
References eu.mihosoft.vrl.v3d.RoundedCube.center, and eu.mihosoft.vrl.v3d.RoundedCube.dimensions.
RoundedCube() [2/6]
eu.mihosoft.vrl.v3d.RoundedCube.RoundedCube (double size)
Constructor. Creates a new rounded cube with center
[0,0,0]
and dimensions
[size,size,size]
.
Parameters
size size
Definition at line 56 of file RoundedCube.java.
References eu.mihosoft.vrl.v3d.RoundedCube.center, and eu.mihosoft.vrl.v3d.RoundedCube.dimensions.
RoundedCube() [3/6]
eu.mihosoft.vrl.v3d.RoundedCube.RoundedCube (LengthParameter w, LengthParameter h, LengthParameter d)
Definition at line 62 of file RoundedCube.java.
References eu.mihosoft.vrl.v3d.parametrics.Parameter.getMM(), and eu.mihosoft.vrl.v3d.Vector3d.ZERO.
RoundedCube() [4/6]
eu.mihosoft.vrl.v3d.RoundedCube.RoundedCube (LengthParameter size)
Definition at line 68 of file RoundedCube.java.
RoundedCube() [5/6]
eu.mihosoft.vrl.v3d.RoundedCube.RoundedCube (Vector3d center, Vector3d dimensions)
Constructor. Creates a new rounded cuboid with the specified center and dimensions.
Parameters
center center of the cuboid
dimensions cube dimensions
Definition at line 79 of file RoundedCube.java.
References eu.mihosoft.vrl.v3d.RoundedCube.center, and eu.mihosoft.vrl.v3d.RoundedCube.dimensions.
RoundedCube() [6/6]
eu.mihosoft.vrl.v3d.RoundedCube.RoundedCube (double w, double h, double d)
Constructor. Creates a new rounded cuboid with center
[0,0,0]
and with the specified dimensions.
Parameters
w width
h height
d depth
Definition at line 92 of file RoundedCube.java.
References eu.mihosoft.vrl.v3d.Vector3d.ZERO.
Member Function Documentation
cornerRadius()
RoundedCube eu.mihosoft.vrl.v3d.RoundedCube.cornerRadius (double cornerRadius)
Corner radius.
Parameters
cornerRadius the corner radius to set
Returns
this cube
Definition at line 241 of file RoundedCube.java.
References eu.mihosoft.vrl.v3d.RoundedCube.cornerRadius.
getCenter()
Vector3d eu.mihosoft.vrl.v3d.RoundedCube.getCenter ()
Gets the center.
Returns
the center
Definition at line 148 of file RoundedCube.java.
References eu.mihosoft.vrl.v3d.RoundedCube.center.
getCornerRadius()
double eu.mihosoft.vrl.v3d.RoundedCube.getCornerRadius ()
Gets the corner radius.
Returns
the corner radius
Definition at line 222 of file RoundedCube.java.
References eu.mihosoft.vrl.v3d.RoundedCube.cornerRadius.
Referenced by eu.mihosoft.vrl.v3d.RoundedCube.toPolygons().
getDimensions()
Vector3d eu.mihosoft.vrl.v3d.RoundedCube.getDimensions ()
Gets the dimensions.
Returns
the dimensions
Definition at line 166 of file RoundedCube.java.
References eu.mihosoft.vrl.v3d.RoundedCube.dimensions.
getProperties()
PropertyStorage eu.mihosoft.vrl.v3d.RoundedCube.getProperties ()
Returns the property storage of this primitive.
Returns
the property storage of this primitive
Reimplemented from eu.mihosoft.vrl.v3d.Primitive.
Definition at line 139 of file RoundedCube.java.
References eu.mihosoft.vrl.v3d.RoundedCube.properties.
getResolution()
int eu.mihosoft.vrl.v3d.RoundedCube.getResolution ()
Gets the resolution.
Returns
the resolution
Definition at line 193 of file RoundedCube.java.
References eu.mihosoft.vrl.v3d.RoundedCube.resolution.
Referenced by eu.mihosoft.vrl.v3d.RoundedCube.toPolygons().
noCenter()
RoundedCube eu.mihosoft.vrl.v3d.RoundedCube.noCenter ()
Defines that this cube will not be centered.
Returns
this cube
Definition at line 183 of file RoundedCube.java.
References eu.mihosoft.vrl.v3d.RoundedCube.centered.
resolution()
RoundedCube eu.mihosoft.vrl.v3d.RoundedCube.resolution (int resolution)
Resolution.
Parameters
resolution the resolution to set
Returns
this cube
Definition at line 212 of file RoundedCube.java.
References eu.mihosoft.vrl.v3d.RoundedCube.resolution.
setCenter()
void eu.mihosoft.vrl.v3d.RoundedCube.setCenter (Vector3d center)
Sets the center.
Parameters
center the center to set
Definition at line 157 of file RoundedCube.java.
References eu.mihosoft.vrl.v3d.RoundedCube.center.
setCornerRadius()
void eu.mihosoft.vrl.v3d.RoundedCube.setCornerRadius (double cornerRadius)
Sets the corner radius.
Parameters
cornerRadius the corner radius to set
Definition at line 231 of file RoundedCube.java.
References eu.mihosoft.vrl.v3d.RoundedCube.cornerRadius.
setDimensions()
void eu.mihosoft.vrl.v3d.RoundedCube.setDimensions (Vector3d dimensions)
Sets the dimensions.
Parameters
dimensions the dimensions to set
Definition at line 175 of file RoundedCube.java.
References eu.mihosoft.vrl.v3d.RoundedCube.dimensions.
setResolution()
void eu.mihosoft.vrl.v3d.RoundedCube.setResolution (int resolution)
Sets the resolution.
Parameters
resolution the resolution to set
Definition at line 202 of file RoundedCube.java.
References eu.mihosoft.vrl.v3d.RoundedCube.resolution.
toPolygons()
List<Polygon> eu.mihosoft.vrl.v3d.RoundedCube.toPolygons ()
Returns the polygons that define this primitive.
Note: this method computes the polygons each time this method is called. The polygons can be cached inside a CSG object.
Returns
a list of polygons that define this primitive
Reimplemented from eu.mihosoft.vrl.v3d.Primitive.
Definition at line 101 of file RoundedCube.java.
References eu.mihosoft.vrl.v3d.RoundedCube.centered, eu.mihosoft.vrl.v3d.RoundedCube.dimensions, eu.mihosoft.vrl.v3d.RoundedCube.getCornerRadius(), eu.mihosoft.vrl.v3d.CSG.getPolygons(), eu.mihosoft.vrl.v3d.RoundedCube.getResolution(), eu.mihosoft.vrl.v3d.CSG.hull(), eu.mihosoft.vrl.v3d.Primitive.toCSG(), eu.mihosoft.vrl.v3d.Transform.transform(), eu.mihosoft.vrl.v3d.CSG.transformed(), eu.mihosoft.vrl.v3d.Transform.translate(), eu.mihosoft.vrl.v3d.CSG.union(), eu.mihosoft.vrl.v3d.Transform.unity(), eu.mihosoft.vrl.v3d.Vector3d.x(), eu.mihosoft.vrl.v3d.Vector3d.y(), and eu.mihosoft.vrl.v3d.Vector3d.z().
Member Data Documentation
center
Vector3d eu.mihosoft.vrl.v3d.RoundedCube.center private
The center.
Definition at line 27 of file RoundedCube.java.
Referenced by eu.mihosoft.vrl.v3d.RoundedCube.getCenter(), eu.mihosoft.vrl.v3d.RoundedCube.RoundedCube(), and eu.mihosoft.vrl.v3d.RoundedCube.setCenter().
centered
boolean eu.mihosoft.vrl.v3d.RoundedCube.centered =true private
The centered.
Definition at line 30 of file RoundedCube.java.
Referenced by eu.mihosoft.vrl.v3d.RoundedCube.noCenter(), and eu.mihosoft.vrl.v3d.RoundedCube.toPolygons().
cornerRadius
double eu.mihosoft.vrl.v3d.RoundedCube.cornerRadius = 0.1 private
The corner radius.
Definition at line 36 of file RoundedCube.java.
Referenced by eu.mihosoft.vrl.v3d.RoundedCube.cornerRadius(), eu.mihosoft.vrl.v3d.RoundedCube.getCornerRadius(), and eu.mihosoft.vrl.v3d.RoundedCube.setCornerRadius().
dimensions
Vector3d eu.mihosoft.vrl.v3d.RoundedCube.dimensions private
Cube dimensions.
Definition at line 24 of file RoundedCube.java.
Referenced by eu.mihosoft.vrl.v3d.RoundedCube.getDimensions(), eu.mihosoft.vrl.v3d.RoundedCube.RoundedCube(), eu.mihosoft.vrl.v3d.RoundedCube.setDimensions(), and eu.mihosoft.vrl.v3d.RoundedCube.toPolygons().
properties
final PropertyStorage eu.mihosoft.vrl.v3d.RoundedCube.properties = new PropertyStorage() private
The properties.
Definition at line 33 of file RoundedCube.java.
Referenced by eu.mihosoft.vrl.v3d.RoundedCube.getProperties().
resolution
int eu.mihosoft.vrl.v3d.RoundedCube.resolution = 8 private
The resolution.
Definition at line 39 of file RoundedCube.java.
Referenced by eu.mihosoft.vrl.v3d.RoundedCube.getResolution(), eu.mihosoft.vrl.v3d.RoundedCube.resolution(), and eu.mihosoft.vrl.v3d.RoundedCube.setResolution().
The documentation for this class was generated from the following file:
JCSG/src/main/java/eu/mihosoft/vrl/v3d/RoundedCube.java