BowlerKernel: eu.mihosoft.vrl.v3d.Primitive Class Reference
eu.mihosoft.vrl.v3d.Primitive Class Reference abstract
Public Member Functions
abstract List< Polygon > toPolygons ()
CSG toCSG ()
abstract PropertyStorage getProperties ()
Detailed Description
A primitive geometry.
Author
Michael Hoffer <info@.nosp@m.mich.nosp@m.aelho.nosp@m.ffer.nosp@m..de>
Definition at line 44 of file Primitive.java.
Member Function Documentation
getProperties()
abstract PropertyStorage eu.mihosoft.vrl.v3d.Primitive.getProperties () abstract
Returns the property storage of this primitive.
Returns
the property storage of this primitive
Reimplemented in eu.mihosoft.vrl.v3d.Wedge, eu.mihosoft.vrl.v3d.Toroid, eu.mihosoft.vrl.v3d.Text3d, eu.mihosoft.vrl.v3d.Tetrahedron, eu.mihosoft.vrl.v3d.Sphere, eu.mihosoft.vrl.v3d.RoundedCylinder, eu.mihosoft.vrl.v3d.RoundedCube, eu.mihosoft.vrl.v3d.Polyhedron, eu.mihosoft.vrl.v3d.Octahedron, eu.mihosoft.vrl.v3d.Isosceles, eu.mihosoft.vrl.v3d.Icosahedron, eu.mihosoft.vrl.v3d.Hexagon, eu.mihosoft.vrl.v3d.Fillet, eu.mihosoft.vrl.v3d.Dodecahedron, eu.mihosoft.vrl.v3d.Cylinder, eu.mihosoft.vrl.v3d.Cube, eu.mihosoft.vrl.v3d.ChamferedCylinder, and eu.mihosoft.vrl.v3d.ChamferedCube.
Referenced by eu.mihosoft.vrl.v3d.Primitive.toCSG().
toCSG()
CSG eu.mihosoft.vrl.v3d.Primitive.toCSG ()
Returns this primitive as CSG.
Returns
this primitive as CSG
Implements eu.mihosoft.vrl.v3d.ItoCSG.
Definition at line 63 of file Primitive.java.
References eu.mihosoft.vrl.v3d.CSG.fromPolygons(), eu.mihosoft.vrl.v3d.Primitive.getProperties(), eu.mihosoft.vrl.v3d.CSG.setParameter(), and eu.mihosoft.vrl.v3d.Primitive.toPolygons().
Referenced by eu.mihosoft.vrl.v3d.CSG.addTabs(), eu.mihosoft.vrl.v3d.Fillet.corner(), eu.mihosoft.vrl.v3d.CSG.getBoundingBox(), com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager.getBoundingBox(), com.neuronrobotics.bowlerstudio.printbed.PrintBedManager.init(), com.neuronrobotics.bowlerstudio.printbed.PrintBedManager.makePrintBeds(), eu.mihosoft.vrl.v3d.Bounds.toCSG(), eu.mihosoft.vrl.v3d.Bounds.toCube(), eu.mihosoft.vrl.v3d.CSG.toolOffset(), eu.mihosoft.vrl.v3d.ChamferedCube.toPolygons(), eu.mihosoft.vrl.v3d.ChamferedCylinder.toPolygons(), eu.mihosoft.vrl.v3d.Fillet.toPolygons(), eu.mihosoft.vrl.v3d.Hexagon.toPolygons(), eu.mihosoft.vrl.v3d.RoundedCube.toPolygons(), and eu.mihosoft.vrl.v3d.RoundedCylinder.toPolygons().
toPolygons()
abstract List<Polygon> eu.mihosoft.vrl.v3d.Primitive.toPolygons () abstract
Returns the polygons that define this primitive.
Note: this method computes the polygons each time this method is called. The polygons can be cached inside a CSG object.
Returns
a list of polygons that define this primitive
Reimplemented in eu.mihosoft.vrl.v3d.Wedge, eu.mihosoft.vrl.v3d.Toroid, eu.mihosoft.vrl.v3d.Text3d, eu.mihosoft.vrl.v3d.Tetrahedron, eu.mihosoft.vrl.v3d.Sphere, eu.mihosoft.vrl.v3d.RoundedCylinder, eu.mihosoft.vrl.v3d.RoundedCube, eu.mihosoft.vrl.v3d.Polyhedron, eu.mihosoft.vrl.v3d.Octahedron, eu.mihosoft.vrl.v3d.Isosceles, eu.mihosoft.vrl.v3d.Icosahedron, eu.mihosoft.vrl.v3d.Hexagon, eu.mihosoft.vrl.v3d.Fillet, eu.mihosoft.vrl.v3d.Dodecahedron, eu.mihosoft.vrl.v3d.Cylinder, eu.mihosoft.vrl.v3d.Cube, eu.mihosoft.vrl.v3d.ChamferedCylinder, and eu.mihosoft.vrl.v3d.ChamferedCube.
Referenced by eu.mihosoft.vrl.v3d.Primitive.toCSG().
The documentation for this class was generated from the following file:
JCSG/src/main/java/eu/mihosoft/vrl/v3d/Primitive.java