BowlerKernel: com.neuronrobotics.sdk.util.ThreadedNsTimer Class Reference
com.neuronrobotics.sdk.util.ThreadedNsTimer Class Reference
Public Member Functions
ThreadedNsTimer (IThreadedNsTimerListener l, long nsInterval, boolean failOnRealtime)
void run ()
boolean isRunning ()
void setRunning (boolean running)
long getStartTime ()
Private Member Functions
long recalculateTarget ()
void setStartTime (long startTime)
Private Attributes
IThreadedNsTimerListener listener
long startTime
long currentInterval
long timerInterval
long loopIndex =0
boolean running =true
boolean failOnRealtime
Detailed Description
The Class ThreadedNsTimer.
Definition at line 7 of file ThreadedNsTimer.java.
Constructor & Destructor Documentation
ThreadedNsTimer()
com.neuronrobotics.sdk.util.ThreadedNsTimer.ThreadedNsTimer (IThreadedNsTimerListener l, long nsInterval, boolean failOnRealtime)
Instantiates a new threaded ns timer.
Parameters
l the l
nsInterval the ns interval
failOnRealtime the fail on realtime
Definition at line 37 of file ThreadedNsTimer.java.
References com.neuronrobotics.sdk.util.ThreadedNsTimer.failOnRealtime, com.neuronrobotics.sdk.util.ThreadedNsTimer.listener, and com.neuronrobotics.sdk.util.ThreadedNsTimer.timerInterval.
Member Function Documentation
getStartTime()
long com.neuronrobotics.sdk.util.ThreadedNsTimer.getStartTime ()
Gets the start time.
Returns
the start time
Definition at line 109 of file ThreadedNsTimer.java.
References com.neuronrobotics.sdk.util.ThreadedNsTimer.startTime.
Referenced by com.neuronrobotics.sdk.util.ThreadedNsTimer.recalculateTarget().
isRunning()
boolean com.neuronrobotics.sdk.util.ThreadedNsTimer.isRunning ()
Checks if is running.
Returns
true, if is running
Definition at line 91 of file ThreadedNsTimer.java.
References com.neuronrobotics.sdk.util.ThreadedNsTimer.running.
Referenced by com.neuronrobotics.sdk.util.ThreadedNsTimer.run().
recalculateTarget()
long com.neuronrobotics.sdk.util.ThreadedNsTimer.recalculateTarget () private
Recalculate target.
Returns
the long
Definition at line 54 of file ThreadedNsTimer.java.
References com.neuronrobotics.sdk.util.ThreadedNsTimer.currentInterval, com.neuronrobotics.sdk.util.ThreadedNsTimer.getStartTime(), com.neuronrobotics.sdk.util.ThreadedNsTimer.loopIndex, and com.neuronrobotics.sdk.util.ThreadedNsTimer.timerInterval.
Referenced by com.neuronrobotics.sdk.util.ThreadedNsTimer.run().
run()
void com.neuronrobotics.sdk.util.ThreadedNsTimer.run ()
Definition at line 63 of file ThreadedNsTimer.java.
References com.neuronrobotics.sdk.util.ThreadedNsTimer.failOnRealtime, com.neuronrobotics.sdk.util.ThreadedNsTimer.isRunning(), com.neuronrobotics.sdk.util.ThreadedNsTimer.listener, com.neuronrobotics.sdk.util.ThreadedNsTimer.loopIndex, com.neuronrobotics.sdk.util.IThreadedNsTimerListener.onTimerInterval(), com.neuronrobotics.sdk.util.ThreadedNsTimer.recalculateTarget(), and com.neuronrobotics.sdk.util.ThreadedNsTimer.setStartTime().
setRunning()
void com.neuronrobotics.sdk.util.ThreadedNsTimer.setRunning (boolean running)
Sets the running.
Parameters
running the new running
Definition at line 100 of file ThreadedNsTimer.java.
References com.neuronrobotics.sdk.util.ThreadedNsTimer.running.
setStartTime()
void com.neuronrobotics.sdk.util.ThreadedNsTimer.setStartTime (long startTime) private
Sets the start time.
Parameters
startTime the new start time
Definition at line 118 of file ThreadedNsTimer.java.
References com.neuronrobotics.sdk.util.ThreadedNsTimer.startTime.
Referenced by com.neuronrobotics.sdk.util.ThreadedNsTimer.run().
Member Data Documentation
currentInterval
long com.neuronrobotics.sdk.util.ThreadedNsTimer.currentInterval private
The current interval.
Definition at line 16 of file ThreadedNsTimer.java.
Referenced by com.neuronrobotics.sdk.util.ThreadedNsTimer.recalculateTarget().
failOnRealtime
boolean com.neuronrobotics.sdk.util.ThreadedNsTimer.failOnRealtime private
The fail on realtime.
Definition at line 28 of file ThreadedNsTimer.java.
Referenced by com.neuronrobotics.sdk.util.ThreadedNsTimer.run(), and com.neuronrobotics.sdk.util.ThreadedNsTimer.ThreadedNsTimer().
listener
IThreadedNsTimerListener com.neuronrobotics.sdk.util.ThreadedNsTimer.listener private
The listener.
Definition at line 10 of file ThreadedNsTimer.java.
Referenced by com.neuronrobotics.sdk.util.ThreadedNsTimer.run(), and com.neuronrobotics.sdk.util.ThreadedNsTimer.ThreadedNsTimer().
loopIndex
long com.neuronrobotics.sdk.util.ThreadedNsTimer.loopIndex =0 private
The loop index.
Definition at line 22 of file ThreadedNsTimer.java.
Referenced by com.neuronrobotics.sdk.util.ThreadedNsTimer.recalculateTarget(), and com.neuronrobotics.sdk.util.ThreadedNsTimer.run().
running
boolean com.neuronrobotics.sdk.util.ThreadedNsTimer.running =true private
The running.
Definition at line 25 of file ThreadedNsTimer.java.
Referenced by com.neuronrobotics.sdk.util.ThreadedNsTimer.isRunning(), and com.neuronrobotics.sdk.util.ThreadedNsTimer.setRunning().
startTime
long com.neuronrobotics.sdk.util.ThreadedNsTimer.startTime private
The start time.
Definition at line 13 of file ThreadedNsTimer.java.
Referenced by com.neuronrobotics.sdk.util.ThreadedNsTimer.getStartTime(), and com.neuronrobotics.sdk.util.ThreadedNsTimer.setStartTime().
timerInterval
long com.neuronrobotics.sdk.util.ThreadedNsTimer.timerInterval private
The timer interval.
Definition at line 19 of file ThreadedNsTimer.java.
Referenced by com.neuronrobotics.sdk.util.ThreadedNsTimer.recalculateTarget(), and com.neuronrobotics.sdk.util.ThreadedNsTimer.ThreadedNsTimer().
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/util/ThreadedNsTimer.java