BowlerKernel: com.neuronrobotics.sdk.common.BowlerAbstractConnection.QueueManager Class Reference
com.neuronrobotics.sdk.common.BowlerAbstractConnection.QueueManager Class Reference
Public Member Functions
QueueManager (boolean b)
void run ()
void kill ()
Private Member Functions
boolean runPacketUpdate ()
void addDatagram (BowlerDatagram dg)
Private Attributes
ArrayList< BowlerDatagram > queueBuffer = new ArrayList<BowlerDatagram>()
ByteList bytesToPacketBuffer = new ByteList()
boolean isSystemQueue =false
boolean killSwitch =false
Detailed Description
Thread safe queue manager.
Author
rbreznak
Definition at line 1306 of file BowlerAbstractConnection.java.
Constructor & Destructor Documentation
QueueManager()
com.neuronrobotics.sdk.common.BowlerAbstractConnection.QueueManager.QueueManager (boolean b)
Instantiates a new queue manager.
Parameters
b the b
Definition at line 1325 of file BowlerAbstractConnection.java.
References com.neuronrobotics.sdk.common.BowlerAbstractConnection.QueueManager.isSystemQueue.
Member Function Documentation
addDatagram()
void com.neuronrobotics.sdk.common.BowlerAbstractConnection.QueueManager.addDatagram (BowlerDatagram dg) private
Adds the datagram.
Parameters
dg the dg
Definition at line 1430 of file BowlerAbstractConnection.java.
References com.neuronrobotics.sdk.common.BowlerAbstractConnection.QueueManager.queueBuffer.
Referenced by com.neuronrobotics.sdk.common.BowlerAbstractConnection.onDataReceived().
kill()
void com.neuronrobotics.sdk.common.BowlerAbstractConnection.QueueManager.kill ()
Kill.
Definition at line 1437 of file BowlerAbstractConnection.java.
References com.neuronrobotics.sdk.common.BowlerAbstractConnection.QueueManager.killSwitch.
Referenced by com.neuronrobotics.sdk.common.BowlerAbstractConnection.setConnected().
run()
void com.neuronrobotics.sdk.common.BowlerAbstractConnection.QueueManager.run ()
Definition at line 1333 of file BowlerAbstractConnection.java.
References com.neuronrobotics.sdk.common.Log.enableErrorPrint(), com.neuronrobotics.sdk.common.Log.error(), com.neuronrobotics.sdk.common.BowlerAbstractConnection.getLastWrite(), com.neuronrobotics.sdk.common.Log.getMinimumPrintLevel(), com.neuronrobotics.sdk.common.BowlerAbstractConnection.getPercentagePrint(), com.neuronrobotics.sdk.common.BowlerAbstractConnection.getSleepTime(), com.neuronrobotics.sdk.common.Log.info(), com.neuronrobotics.sdk.common.BowlerAbstractConnection.isBeater(), com.neuronrobotics.sdk.common.BowlerAbstractConnection.isConnected(), com.neuronrobotics.sdk.common.BowlerDatagram.isSyncronous(), com.neuronrobotics.sdk.common.BowlerAbstractConnection.QueueManager.isSystemQueue, com.neuronrobotics.sdk.common.BowlerAbstractConnection.isUseThreadedStack(), com.neuronrobotics.sdk.common.BowlerAbstractConnection.QueueManager.killSwitch, com.neuronrobotics.sdk.common.BowlerAbstractConnection.pushUp(), com.neuronrobotics.sdk.common.BowlerAbstractConnection.QueueManager.queueBuffer, com.neuronrobotics.sdk.common.BowlerAbstractConnection.runHeartBeat(), com.neuronrobotics.sdk.common.BowlerAbstractConnection.QueueManager.runPacketUpdate(), com.neuronrobotics.sdk.common.Log.setMinimumPrintLevel(), and com.neuronrobotics.sdk.util.ThreadUtil.wait().
runPacketUpdate()
boolean com.neuronrobotics.sdk.common.BowlerAbstractConnection.QueueManager.runPacketUpdate () private
Run packet update.
Returns
true, if successful
Definition at line 1404 of file BowlerAbstractConnection.java.
References com.neuronrobotics.sdk.common.BowlerAbstractConnection.QueueManager.bytesToPacketBuffer, com.neuronrobotics.sdk.common.BowlerAbstractConnection.disconnect(), com.neuronrobotics.sdk.common.Log.error(), com.neuronrobotics.sdk.common.Log.info(), com.neuronrobotics.sdk.common.BowlerAbstractConnection.isConnected(), com.neuronrobotics.sdk.common.BowlerAbstractConnection.loadPacketFromPhy(), and com.neuronrobotics.sdk.common.BowlerAbstractConnection.onDataReceived().
Referenced by com.neuronrobotics.sdk.common.BowlerAbstractConnection.QueueManager.run(), and com.neuronrobotics.sdk.common.BowlerAbstractConnection.sendSynchronusly().
Member Data Documentation
bytesToPacketBuffer
ByteList com.neuronrobotics.sdk.common.BowlerAbstractConnection.QueueManager.bytesToPacketBuffer = new ByteList() private
The bytes to packet buffer.
Definition at line 1312 of file BowlerAbstractConnection.java.
Referenced by com.neuronrobotics.sdk.common.BowlerAbstractConnection.QueueManager.runPacketUpdate().
isSystemQueue
boolean com.neuronrobotics.sdk.common.BowlerAbstractConnection.QueueManager.isSystemQueue =false private
The is system queue.
Definition at line 1315 of file BowlerAbstractConnection.java.
Referenced by com.neuronrobotics.sdk.common.BowlerAbstractConnection.QueueManager.QueueManager(), and com.neuronrobotics.sdk.common.BowlerAbstractConnection.QueueManager.run().
killSwitch
boolean com.neuronrobotics.sdk.common.BowlerAbstractConnection.QueueManager.killSwitch =false private
The kill switch.
Definition at line 1318 of file BowlerAbstractConnection.java.
Referenced by com.neuronrobotics.sdk.common.BowlerAbstractConnection.QueueManager.kill(), and com.neuronrobotics.sdk.common.BowlerAbstractConnection.QueueManager.run().
queueBuffer
ArrayList<BowlerDatagram> com.neuronrobotics.sdk.common.BowlerAbstractConnection.QueueManager.queueBuffer = new ArrayList<BowlerDatagram>() private
The queue buffer.
Definition at line 1309 of file BowlerAbstractConnection.java.
Referenced by com.neuronrobotics.sdk.common.BowlerAbstractConnection.QueueManager.addDatagram(), and com.neuronrobotics.sdk.common.BowlerAbstractConnection.QueueManager.run().
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/common/BowlerAbstractConnection.java