BowlerKernel: com.neuronrobotics.sdk.addons.irobot.CreateArm Class Reference
com.neuronrobotics.sdk.addons.irobot.CreateArm Class Reference
Public Member Functions
CreateArm (ServoChannel[] links)
void home ()
void rest ()
void gripClose ()
void gripOpen ()
void setShouler (double angle)
void setElbow (double angle)
void setWrist (double angle)
void setAngles (double shoulder, double elbow, double wrist)
void setAngles (double shoulder, double elbow, double wrist, float time)
double[] getAngles ()
double[] getCartesianPose ()
String getCartesianPoseString ()
void setCartesianPose (double[] p)
void setCartesianPose (double[] p, float time)
void setCartesianPose (double x, double y, double orentation)
void setCartesianPose (double x, double y, double orentation, float time)
void setCartesianX (double x)
void setCartesianY (double y)
void setCartesianOrentation (double o)
double GetOrentation ()
void setCenters (double[] centers)
double[] getCenters ()
void setBlocking (boolean blocking)
boolean isBlocking ()
void setScale (double scale[])
double[] getScale ()
Private Member Functions
void check (ServoChannel[] links)
boolean updateCartesian (double x, double y, double orentation)
double sqrt (double d)
double atan2 (double y, double x)
double acos (double d)
double sin (double angle)
double cos (double angle)
double ToRadians (double degrees)
Private Attributes
double scale [] ={1.55,1.50,-1.76}
double[] positions =new double[4]
double[] angles =new double[3]
double[] pose =new double[3]
double[] centers ={134,136,128,48}
boolean blocking = false
double xyThreshHold = .1
double orentThreshHold = 1
Static Private Attributes
static final double l1 = 6.0
static final double l2 = 3.93
static final double l3 = 4.75
static final double M_PI = Math.PI
Detailed Description
The Class CreateArm.
Definition at line 25 of file CreateArm.java.
Constructor & Destructor Documentation
CreateArm()
com.neuronrobotics.sdk.addons.irobot.CreateArm.CreateArm (ServoChannel[] links)
Instantiates a new creates the arm.
Parameters
links this is an array of servo channel links. 0th element is shoulder 1th element is elbow 2th element is is wrist 3th element is the gripper
Definition at line 76 of file CreateArm.java.
References com.neuronrobotics.sdk.addons.irobot.CreateArm.check(), com.neuronrobotics.sdk.addons.irobot.CreateArm.getCartesianPose(), com.neuronrobotics.sdk.addons.irobot.CreateArm.home(), and com.neuronrobotics.sdk.addons.irobot.CreateArm.pose.
Member Function Documentation
acos()
double com.neuronrobotics.sdk.addons.irobot.CreateArm.acos (double d) private
Acos.
Parameters
d the d
Returns
the double
Definition at line 456 of file CreateArm.java.
Referenced by com.neuronrobotics.sdk.addons.irobot.CreateArm.setCartesianPose().
atan2()
double com.neuronrobotics.sdk.addons.irobot.CreateArm.atan2 (double y, double x) private
Atan2.
Parameters
y the y
x the x
Returns
the double
Definition at line 446 of file CreateArm.java.
Referenced by com.neuronrobotics.sdk.addons.irobot.CreateArm.setCartesianPose().
check()
void com.neuronrobotics.sdk.addons.irobot.CreateArm.check (ServoChannel[] links) private
Check.
Parameters
links the links
Definition at line 133 of file CreateArm.java.
References com.neuronrobotics.sdk.addons.irobot.CreateArm.getCenters(), com.neuronrobotics.sdk.addons.irobot.CreateArm.positions, and com.neuronrobotics.sdk.dyio.peripherals.ServoChannel.SetPosition().
Referenced by com.neuronrobotics.sdk.addons.irobot.CreateArm.CreateArm().
cos()
double com.neuronrobotics.sdk.addons.irobot.CreateArm.cos (double angle) private
Cos.
Parameters
angle the angle
Returns
the double
Definition at line 476 of file CreateArm.java.
Referenced by com.neuronrobotics.sdk.addons.irobot.CreateArm.getCartesianPose(), and com.neuronrobotics.sdk.addons.irobot.CreateArm.setCartesianPose().
getAngles()
double [] com.neuronrobotics.sdk.addons.irobot.CreateArm.getAngles ()
Gets the angles.
Returns
an array of angles in degrees. This should correspond to pose of the arm.
Definition at line 253 of file CreateArm.java.
References com.neuronrobotics.sdk.addons.irobot.CreateArm.getCenters(), com.neuronrobotics.sdk.addons.irobot.CreateArm.getScale(), and com.neuronrobotics.sdk.addons.irobot.CreateArm.positions.
Referenced by com.neuronrobotics.sdk.addons.irobot.CreateArm.getCartesianPose(), com.neuronrobotics.sdk.addons.irobot.CreateArm.GetOrentation(), and com.neuronrobotics.sdk.addons.irobot.CreateArm.setAngles().
getCartesianPose()
double [] com.neuronrobotics.sdk.addons.irobot.CreateArm.getCartesianPose ()
Gets the cartesian pose.
Returns
pose vector, X,Y,Orentation
Definition at line 268 of file CreateArm.java.
References com.neuronrobotics.sdk.addons.irobot.CreateArm.angles, com.neuronrobotics.sdk.addons.irobot.CreateArm.cos(), com.neuronrobotics.sdk.addons.irobot.CreateArm.getAngles(), com.neuronrobotics.sdk.addons.irobot.CreateArm.GetOrentation(), com.neuronrobotics.sdk.addons.irobot.CreateArm.l1, com.neuronrobotics.sdk.addons.irobot.CreateArm.l2, com.neuronrobotics.sdk.addons.irobot.CreateArm.l3, com.neuronrobotics.sdk.addons.irobot.CreateArm.pose, com.neuronrobotics.sdk.addons.irobot.CreateArm.sin(), and com.neuronrobotics.sdk.addons.irobot.CreateArm.ToRadians().
Referenced by com.neuronrobotics.sdk.addons.irobot.CreateArm.CreateArm(), com.neuronrobotics.sdk.addons.irobot.CreateArm.getCartesianPoseString(), com.neuronrobotics.sdk.addons.irobot.CreateArm.home(), and com.neuronrobotics.sdk.addons.irobot.CreateArm.rest().
getCartesianPoseString()
String com.neuronrobotics.sdk.addons.irobot.CreateArm.getCartesianPoseString ()
Gets the cartesian pose string.
Returns
the cartesian pose string
Definition at line 286 of file CreateArm.java.
References com.neuronrobotics.sdk.addons.irobot.CreateArm.getCartesianPose(), and com.neuronrobotics.sdk.addons.irobot.CreateArm.pose.
getCenters()
double [] com.neuronrobotics.sdk.addons.irobot.CreateArm.getCenters ()
Gets the centers.
Returns
the centers
Definition at line 514 of file CreateArm.java.
References com.neuronrobotics.sdk.addons.irobot.CreateArm.centers.
Referenced by com.neuronrobotics.sdk.addons.irobot.CreateArm.check(), com.neuronrobotics.sdk.addons.irobot.CreateArm.getAngles(), and com.neuronrobotics.sdk.addons.irobot.CreateArm.setAngles().
GetOrentation()
double com.neuronrobotics.sdk.addons.irobot.CreateArm.GetOrentation ()
Gets the orentation.
Returns
the current approach orientation of the wrist
Definition at line 495 of file CreateArm.java.
References com.neuronrobotics.sdk.addons.irobot.CreateArm.angles, and com.neuronrobotics.sdk.addons.irobot.CreateArm.getAngles().
Referenced by com.neuronrobotics.sdk.addons.irobot.CreateArm.getCartesianPose().
getScale()
double [] com.neuronrobotics.sdk.addons.irobot.CreateArm.getScale ()
Gets the scale.
Returns
the scale
Definition at line 550 of file CreateArm.java.
References com.neuronrobotics.sdk.addons.irobot.CreateArm.scale.
Referenced by com.neuronrobotics.sdk.addons.irobot.CreateArm.getAngles(), and com.neuronrobotics.sdk.addons.irobot.CreateArm.setAngles().
gripClose()
void com.neuronrobotics.sdk.addons.irobot.CreateArm.gripClose ()
Grip close.
Definition at line 103 of file CreateArm.java.
References com.neuronrobotics.sdk.addons.irobot.CreateArm.centers, com.neuronrobotics.sdk.addons.irobot.CreateArm.isBlocking(), and com.neuronrobotics.sdk.dyio.peripherals.ServoChannel.SetPosition().
gripOpen()
void com.neuronrobotics.sdk.addons.irobot.CreateArm.gripOpen ()
Grip open.
Definition at line 117 of file CreateArm.java.
References com.neuronrobotics.sdk.addons.irobot.CreateArm.centers, com.neuronrobotics.sdk.addons.irobot.CreateArm.isBlocking(), and com.neuronrobotics.sdk.dyio.peripherals.ServoChannel.SetPosition().
Referenced by com.neuronrobotics.sdk.addons.irobot.CreateArm.home(), and com.neuronrobotics.sdk.addons.irobot.CreateArm.rest().
home()
void com.neuronrobotics.sdk.addons.irobot.CreateArm.home ()
Home.
Definition at line 85 of file CreateArm.java.
References com.neuronrobotics.sdk.addons.irobot.CreateArm.getCartesianPose(), com.neuronrobotics.sdk.addons.irobot.CreateArm.gripOpen(), com.neuronrobotics.sdk.addons.irobot.CreateArm.setAngles(), and com.neuronrobotics.sdk.addons.irobot.CreateArm.setCartesianPose().
Referenced by com.neuronrobotics.sdk.addons.irobot.CreateArm.CreateArm().
isBlocking()
boolean com.neuronrobotics.sdk.addons.irobot.CreateArm.isBlocking ()
Checks if is blocking.
Returns
true, if is blocking
Definition at line 532 of file CreateArm.java.
References com.neuronrobotics.sdk.addons.irobot.CreateArm.blocking.
Referenced by com.neuronrobotics.sdk.addons.irobot.CreateArm.gripClose(), com.neuronrobotics.sdk.addons.irobot.CreateArm.gripOpen(), and com.neuronrobotics.sdk.addons.irobot.CreateArm.setAngles().
rest()
void com.neuronrobotics.sdk.addons.irobot.CreateArm.rest ()
Rest.
Definition at line 94 of file CreateArm.java.
References com.neuronrobotics.sdk.addons.irobot.CreateArm.getCartesianPose(), com.neuronrobotics.sdk.addons.irobot.CreateArm.gripOpen(), com.neuronrobotics.sdk.addons.irobot.CreateArm.setAngles(), and com.neuronrobotics.sdk.addons.irobot.CreateArm.setCartesianPose().
setAngles() [1/2]
void com.neuronrobotics.sdk.addons.irobot.CreateArm.setAngles (double shoulder, double elbow, double wrist)
This takes angles in degrees and converts them to servo positions; Note: All zeros would be the arm completely horizontal, all links pointing out.
Parameters
shoulder the shoulder
elbow the elbow
wrist the wrist
Definition at line 182 of file CreateArm.java.
Referenced by com.neuronrobotics.sdk.addons.irobot.CreateArm.home(), com.neuronrobotics.sdk.addons.irobot.CreateArm.rest(), com.neuronrobotics.sdk.addons.irobot.CreateArm.setCartesianPose(), com.neuronrobotics.sdk.addons.irobot.CreateArm.setElbow(), com.neuronrobotics.sdk.addons.irobot.CreateArm.setShouler(), and com.neuronrobotics.sdk.addons.irobot.CreateArm.setWrist().
setAngles() [2/2]
void com.neuronrobotics.sdk.addons.irobot.CreateArm.setAngles (double shoulder, double elbow, double wrist, float time)
This takes angles in degrees and converts them to servo positions; Note: All zeros would be the arm completely horizontal, all links pointing out.
Parameters
shoulder the shoulder
elbow the elbow
wrist the wrist
time the time it should take for the transition to take
Definition at line 195 of file CreateArm.java.
References com.neuronrobotics.sdk.addons.irobot.CreateArm.angles, com.neuronrobotics.sdk.addons.irobot.CreateArm.centers, com.neuronrobotics.sdk.addons.irobot.CreateArm.getAngles(), com.neuronrobotics.sdk.addons.irobot.CreateArm.getCenters(), com.neuronrobotics.sdk.addons.irobot.CreateArm.getScale(), com.neuronrobotics.sdk.common.Log.info(), com.neuronrobotics.sdk.addons.irobot.CreateArm.isBlocking(), com.neuronrobotics.sdk.addons.irobot.CreateArm.pose, com.neuronrobotics.sdk.addons.irobot.CreateArm.positions, and com.neuronrobotics.sdk.dyio.peripherals.ServoChannel.SetPosition().
setBlocking()
void com.neuronrobotics.sdk.addons.irobot.CreateArm.setBlocking (boolean blocking)
Sets the blocking.
Parameters
blocking the new blocking
Definition at line 523 of file CreateArm.java.
References com.neuronrobotics.sdk.addons.irobot.CreateArm.blocking.
setCartesianOrentation()
void com.neuronrobotics.sdk.addons.irobot.CreateArm.setCartesianOrentation (double o)
Sets the cartesian orentation.
Parameters
o the new cartesian orentation
Definition at line 422 of file CreateArm.java.
References com.neuronrobotics.sdk.addons.irobot.CreateArm.pose, and com.neuronrobotics.sdk.addons.irobot.CreateArm.setCartesianPose().
setCartesianPose() [1/4]
void com.neuronrobotics.sdk.addons.irobot.CreateArm.setCartesianPose (double x, double y, double orentation)
Sets the cartesian pose.
Parameters
x the x
y the y
orentation the orentation
Definition at line 323 of file CreateArm.java.
References com.neuronrobotics.sdk.addons.irobot.CreateArm.setCartesianPose().
setCartesianPose() [2/4]
void com.neuronrobotics.sdk.addons.irobot.CreateArm.setCartesianPose (double x, double y, double orentation, float time)
Sets the cartesian pose.
Parameters
x the x
y the y
orentation the orentation
time the time
Definition at line 335 of file CreateArm.java.
References com.neuronrobotics.sdk.addons.irobot.CreateArm.acos(), com.neuronrobotics.sdk.addons.irobot.CreateArm.atan2(), com.neuronrobotics.sdk.addons.irobot.CreateArm.cos(), com.neuronrobotics.sdk.common.Log.info(), com.neuronrobotics.sdk.addons.irobot.CreateArm.l1, com.neuronrobotics.sdk.addons.irobot.CreateArm.l2, com.neuronrobotics.sdk.addons.irobot.CreateArm.l3, com.neuronrobotics.sdk.addons.irobot.CreateArm.M_PI, com.neuronrobotics.sdk.addons.irobot.CreateArm.pose, com.neuronrobotics.sdk.addons.irobot.CreateArm.setAngles(), com.neuronrobotics.sdk.addons.irobot.CreateArm.sin(), com.neuronrobotics.sdk.addons.irobot.CreateArm.sqrt(), and com.neuronrobotics.sdk.addons.irobot.CreateArm.updateCartesian().
setCartesianPose() [3/4]
void com.neuronrobotics.sdk.addons.irobot.CreateArm.setCartesianPose (double[] p)
Sets the cartesian pose.
Parameters
p the new cartesian pose
Definition at line 302 of file CreateArm.java.
Referenced by com.neuronrobotics.sdk.addons.irobot.CreateArm.home(), com.neuronrobotics.sdk.addons.irobot.CreateArm.rest(), com.neuronrobotics.sdk.addons.irobot.CreateArm.setCartesianOrentation(), com.neuronrobotics.sdk.addons.irobot.CreateArm.setCartesianPose(), com.neuronrobotics.sdk.addons.irobot.CreateArm.setCartesianX(), and com.neuronrobotics.sdk.addons.irobot.CreateArm.setCartesianY().
setCartesianPose() [4/4]
void com.neuronrobotics.sdk.addons.irobot.CreateArm.setCartesianPose (double[] p, float time)
Sets the cartesian pose.
Parameters
p the p
time the time
Definition at line 312 of file CreateArm.java.
References com.neuronrobotics.sdk.addons.irobot.CreateArm.setCartesianPose().
setCartesianX()
void com.neuronrobotics.sdk.addons.irobot.CreateArm.setCartesianX (double x)
Sets the cartesian x.
Parameters
x the new cartesian x
Definition at line 404 of file CreateArm.java.
References com.neuronrobotics.sdk.addons.irobot.CreateArm.pose, and com.neuronrobotics.sdk.addons.irobot.CreateArm.setCartesianPose().
setCartesianY()
void com.neuronrobotics.sdk.addons.irobot.CreateArm.setCartesianY (double y)
Sets the cartesian y.
Parameters
y the new cartesian y
Definition at line 413 of file CreateArm.java.
References com.neuronrobotics.sdk.addons.irobot.CreateArm.pose, and com.neuronrobotics.sdk.addons.irobot.CreateArm.setCartesianPose().
setCenters()
void com.neuronrobotics.sdk.addons.irobot.CreateArm.setCenters (double[] centers)
Sets the centers.
Parameters
centers the new centers
Definition at line 505 of file CreateArm.java.
References com.neuronrobotics.sdk.addons.irobot.CreateArm.centers.
setElbow()
void com.neuronrobotics.sdk.addons.irobot.CreateArm.setElbow (double angle)
Sets the elbow.
Parameters
angle set just the elbow angle
Definition at line 161 of file CreateArm.java.
References com.neuronrobotics.sdk.addons.irobot.CreateArm.angles, and com.neuronrobotics.sdk.addons.irobot.CreateArm.setAngles().
setScale()
void com.neuronrobotics.sdk.addons.irobot.CreateArm.setScale (double scale[])
Sets the scale.
Parameters
scale the new scale
Definition at line 541 of file CreateArm.java.
References com.neuronrobotics.sdk.addons.irobot.CreateArm.scale.
setShouler()
void com.neuronrobotics.sdk.addons.irobot.CreateArm.setShouler (double angle)
Sets the shouler.
Parameters
angle set just the shoulder angle
Definition at line 152 of file CreateArm.java.
References com.neuronrobotics.sdk.addons.irobot.CreateArm.angles, and com.neuronrobotics.sdk.addons.irobot.CreateArm.setAngles().
setWrist()
void com.neuronrobotics.sdk.addons.irobot.CreateArm.setWrist (double angle)
Sets the wrist.
Parameters
angle set just the wrist angle
Definition at line 170 of file CreateArm.java.
References com.neuronrobotics.sdk.addons.irobot.CreateArm.angles, and com.neuronrobotics.sdk.addons.irobot.CreateArm.setAngles().
sin()
double com.neuronrobotics.sdk.addons.irobot.CreateArm.sin (double angle) private
Sin.
Parameters
angle the angle
Returns
the double
Definition at line 466 of file CreateArm.java.
Referenced by com.neuronrobotics.sdk.addons.irobot.CreateArm.getCartesianPose(), and com.neuronrobotics.sdk.addons.irobot.CreateArm.setCartesianPose().
sqrt()
double com.neuronrobotics.sdk.addons.irobot.CreateArm.sqrt (double d) private
Sqrt.
Parameters
d the d
Returns
the double
Definition at line 435 of file CreateArm.java.
Referenced by com.neuronrobotics.sdk.addons.irobot.CreateArm.setCartesianPose().
ToRadians()
double com.neuronrobotics.sdk.addons.irobot.CreateArm.ToRadians (double degrees) private
To radians.
Parameters
degrees the degrees
Returns
the double
Definition at line 486 of file CreateArm.java.
References com.neuronrobotics.sdk.addons.irobot.CreateArm.M_PI.
Referenced by com.neuronrobotics.sdk.addons.irobot.CreateArm.getCartesianPose().
updateCartesian()
boolean com.neuronrobotics.sdk.addons.irobot.CreateArm.updateCartesian (double x, double y, double orentation) private
Update cartesian.
Parameters
x the x
y the y
orentation the orentation
Returns
true, if successful
Definition at line 378 of file CreateArm.java.
References com.neuronrobotics.sdk.common.Log.info(), com.neuronrobotics.sdk.addons.irobot.CreateArm.orentThreshHold, com.neuronrobotics.sdk.addons.irobot.CreateArm.pose, and com.neuronrobotics.sdk.addons.irobot.CreateArm.xyThreshHold.
Referenced by com.neuronrobotics.sdk.addons.irobot.CreateArm.setCartesianPose().
Member Data Documentation
angles
double [] com.neuronrobotics.sdk.addons.irobot.CreateArm.angles =new double[3] private
The angles.
Definition at line 50 of file CreateArm.java.
Referenced by com.neuronrobotics.sdk.addons.irobot.CreateArm.getCartesianPose(), com.neuronrobotics.sdk.addons.irobot.CreateArm.GetOrentation(), com.neuronrobotics.sdk.addons.irobot.CreateArm.setAngles(), com.neuronrobotics.sdk.addons.irobot.CreateArm.setElbow(), com.neuronrobotics.sdk.addons.irobot.CreateArm.setShouler(), and com.neuronrobotics.sdk.addons.irobot.CreateArm.setWrist().
blocking
boolean com.neuronrobotics.sdk.addons.irobot.CreateArm.blocking = false private
The blocking.
Definition at line 59 of file CreateArm.java.
Referenced by com.neuronrobotics.sdk.addons.irobot.CreateArm.isBlocking(), and com.neuronrobotics.sdk.addons.irobot.CreateArm.setBlocking().
centers
double [] com.neuronrobotics.sdk.addons.irobot.CreateArm.centers ={134,136,128,48} private
The centers.
Definition at line 56 of file CreateArm.java.
Referenced by com.neuronrobotics.sdk.addons.irobot.CreateArm.getCenters(), com.neuronrobotics.sdk.addons.irobot.CreateArm.gripClose(), com.neuronrobotics.sdk.addons.irobot.CreateArm.gripOpen(), com.neuronrobotics.sdk.addons.irobot.CreateArm.setAngles(), and com.neuronrobotics.sdk.addons.irobot.CreateArm.setCenters().
l1
final double com.neuronrobotics.sdk.addons.irobot.CreateArm.l1 = 6.0 static private
The Constant l1.
Definition at line 31 of file CreateArm.java.
Referenced by com.neuronrobotics.sdk.addons.irobot.CreateArm.getCartesianPose(), and com.neuronrobotics.sdk.addons.irobot.CreateArm.setCartesianPose().
l2
final double com.neuronrobotics.sdk.addons.irobot.CreateArm.l2 = 3.93 static private
The Constant l2.
Definition at line 34 of file CreateArm.java.
Referenced by com.neuronrobotics.sdk.addons.irobot.CreateArm.getCartesianPose(), and com.neuronrobotics.sdk.addons.irobot.CreateArm.setCartesianPose().
l3
final double com.neuronrobotics.sdk.addons.irobot.CreateArm.l3 = 4.75 static private
The Constant l3.
Definition at line 37 of file CreateArm.java.
Referenced by com.neuronrobotics.sdk.addons.irobot.CreateArm.getCartesianPose(), and com.neuronrobotics.sdk.addons.irobot.CreateArm.setCartesianPose().
M_PI
final double com.neuronrobotics.sdk.addons.irobot.CreateArm.M_PI = Math.PI static private
The Constant M_PI.
Definition at line 41 of file CreateArm.java.
Referenced by com.neuronrobotics.sdk.addons.irobot.CreateArm.setCartesianPose(), and com.neuronrobotics.sdk.addons.irobot.CreateArm.ToRadians().
orentThreshHold
double com.neuronrobotics.sdk.addons.irobot.CreateArm.orentThreshHold = 1 private
The orent thresh hold.
Definition at line 65 of file CreateArm.java.
Referenced by com.neuronrobotics.sdk.addons.irobot.CreateArm.updateCartesian().
pose
double [] com.neuronrobotics.sdk.addons.irobot.CreateArm.pose =new double[3] private
The pose.
Definition at line 53 of file CreateArm.java.
Referenced by com.neuronrobotics.sdk.addons.irobot.CreateArm.CreateArm(), com.neuronrobotics.sdk.addons.irobot.CreateArm.getCartesianPose(), com.neuronrobotics.sdk.addons.irobot.CreateArm.getCartesianPoseString(), com.neuronrobotics.sdk.addons.irobot.CreateArm.setAngles(), com.neuronrobotics.sdk.addons.irobot.CreateArm.setCartesianOrentation(), com.neuronrobotics.sdk.addons.irobot.CreateArm.setCartesianPose(), com.neuronrobotics.sdk.addons.irobot.CreateArm.setCartesianX(), com.neuronrobotics.sdk.addons.irobot.CreateArm.setCartesianY(), and com.neuronrobotics.sdk.addons.irobot.CreateArm.updateCartesian().
positions
double [] com.neuronrobotics.sdk.addons.irobot.CreateArm.positions =new double[4] private
The positions.
Definition at line 47 of file CreateArm.java.
Referenced by com.neuronrobotics.sdk.addons.irobot.CreateArm.check(), com.neuronrobotics.sdk.addons.irobot.CreateArm.getAngles(), and com.neuronrobotics.sdk.addons.irobot.CreateArm.setAngles().
scale
double com.neuronrobotics.sdk.addons.irobot.CreateArm.scale[] ={1.55,1.50,-1.76} private
The scale.
Definition at line 44 of file CreateArm.java.
Referenced by com.neuronrobotics.sdk.addons.irobot.CreateArm.getScale(), and com.neuronrobotics.sdk.addons.irobot.CreateArm.setScale().
xyThreshHold
double com.neuronrobotics.sdk.addons.irobot.CreateArm.xyThreshHold = .1 private
The xy thresh hold.
Definition at line 62 of file CreateArm.java.
Referenced by com.neuronrobotics.sdk.addons.irobot.CreateArm.updateCartesian().
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/addons/irobot/CreateArm.java