BowlerKernel: com.neuronrobotics.sdk.dyio.peripherals.DCMotorOutputChannel Class Reference
com.neuronrobotics.sdk.dyio.peripherals.DCMotorOutputChannel Class Reference
Public Member Functions
DCMotorOutputChannel (int channel)
DCMotorOutputChannel (DyIO dyio, int channel)
DCMotorOutputChannel (DyIOChannel channel)
void SetVelocity (float velocity)
boolean hasAsync ()
Public Member Functions inherited from com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral
DyIOAbstractPeripheral (DyIOChannel channel, DyIOChannelMode myMode, boolean async)
DyIOChannelMode getClassMode ()
boolean isEnabled ()
boolean setMode ()
boolean setMode (boolean async)
boolean setMode (DyIOChannelMode mode, boolean async)
DyIOChannel getChannel ()
DyIOChannelMode getMode ()
boolean setValue (int value) throws InvalidResponseException
boolean setValue (ByteList value) throws InvalidResponseException
int getValue () throws InvalidResponseException
boolean SavePosition (int pos)
boolean configAdvancedAsyncNotEqual ()
boolean configAdvancedAsyncDeadBand (int deadbandSize)
boolean configAdvancedAsyncTreshhold (int threshholdValue, AsyncThreshholdEdgeType edgeType)
boolean configAdvancedAsyncAutoSample ()
boolean configAdvancedAsyncNotEqual (int msTime)
boolean configAdvancedAsyncDeadBand (int msTime, int deadbandSize)
boolean configAdvancedAsyncTreshhold (int msTime, int threshholdValue, AsyncThreshholdEdgeType edgeType)
boolean configAdvancedAsyncAutoSample (int msTime)
boolean flush ()
void setAsync (boolean b)
int getConfiguration ()
Detailed Description
The Class DCMotorOutputChannel.
Definition at line 27 of file DCMotorOutputChannel.java.
Constructor & Destructor Documentation
DCMotorOutputChannel() [1/3]
com.neuronrobotics.sdk.dyio.peripherals.DCMotorOutputChannel.DCMotorOutputChannel (int channel)
Constructor. Creates an counter input input channel that is syncronous only by default.
Parameters
channel - the channel object requested from the DyIO
Definition at line 35 of file DCMotorOutputChannel.java.
References com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral.channel, com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral.getChannel(), and com.neuronrobotics.sdk.common.DeviceManager.getSpecificDevice().
DCMotorOutputChannel() [2/3]
com.neuronrobotics.sdk.dyio.peripherals.DCMotorOutputChannel.DCMotorOutputChannel (DyIO dyio, int channel)
Constructor. Creates an counter input input channel that is syncronous only by default.
Parameters
dyio the dyio
channel - the channel object requested from the DyIO
Definition at line 46 of file DCMotorOutputChannel.java.
References com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral.channel, and com.neuronrobotics.sdk.dyio.DyIO.getChannel().
DCMotorOutputChannel() [3/3]
com.neuronrobotics.sdk.dyio.peripherals.DCMotorOutputChannel.DCMotorOutputChannel (DyIOChannel channel)
DCMotorOutputChannel.
Parameters
channel The channel object to set up as a full duty, hardware PWM
Definition at line 57 of file DCMotorOutputChannel.java.
References com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral.channel, com.neuronrobotics.sdk.dyio.DyIOChannelMode.DC_MOTOR_VEL, and com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral.setMode().
Member Function Documentation
hasAsync()
boolean com.neuronrobotics.sdk.dyio.peripherals.DCMotorOutputChannel.hasAsync ()
This method is to check if this peripheral is capable to be set as up as asynchronous.
Returns
if it cna be async
Reimplemented from com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral.
Definition at line 88 of file DCMotorOutputChannel.java.
SetVelocity()
void com.neuronrobotics.sdk.dyio.peripherals.DCMotorOutputChannel.SetVelocity (float velocity)
This takes in a velocity from 100 to -100 100 is full on forward, -100 is full on backward and 0 is stop.
Parameters
velocity the velocity
Definition at line 71 of file DCMotorOutputChannel.java.
References com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral.setValue().
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/dyio/peripherals/DCMotorOutputChannel.java