BowlerKernel: com.neuronrobotics.sdk.bootloader.hexLine Class Reference
com.neuronrobotics.sdk.bootloader.hexLine Class Reference
Public Member Functions
int getCheckSum ()
hexLine (String s) throws Exception
int getStartAddress ()
int getEndAddress ()
void setHighAddress (long highAddress)
int getByteCount ()
int getRecordType ()
byte[] getDataBytes ()
Boolean hasData ()
String toString ()
Private Member Functions
byte[] dataToArray (ArrayList< Byte > bl)
Private Attributes
ArrayList< Byte > dataBytes = new ArrayList<Byte>()
int address
int byteCount
int recordType
int checkSum
boolean hasSetHighAddress =false
Detailed Description
The Class hexLine.
Definition at line 10 of file hexLine.java.
Constructor & Destructor Documentation
hexLine()
com.neuronrobotics.sdk.bootloader.hexLine.hexLine (String s) throws Exception
Instantiates a new hex line.
Parameters
s the s
Exceptions
Exception the exception
Definition at line 45 of file hexLine.java.
References com.neuronrobotics.sdk.bootloader.hexLine.address, com.neuronrobotics.sdk.bootloader.hexLine.byteCount, com.neuronrobotics.sdk.bootloader.hexLine.checkSum, com.neuronrobotics.sdk.bootloader.hexLine.dataBytes, and com.neuronrobotics.sdk.bootloader.hexLine.recordType.
Member Function Documentation
dataToArray()
byte [] com.neuronrobotics.sdk.bootloader.hexLine.dataToArray (ArrayList< Byte > bl) private
Data to array.
Parameters
bl the bl
Returns
the byte[]
Definition at line 145 of file hexLine.java.
Referenced by com.neuronrobotics.sdk.bootloader.hexLine.getDataBytes().
getByteCount()
int com.neuronrobotics.sdk.bootloader.hexLine.getByteCount ()
Gets the byte count.
Returns
the byte count
Definition at line 105 of file hexLine.java.
References com.neuronrobotics.sdk.bootloader.hexLine.byteCount.
getCheckSum()
int com.neuronrobotics.sdk.bootloader.hexLine.getCheckSum ()
Gets the check sum.
Returns
the check sum
Definition at line 35 of file hexLine.java.
References com.neuronrobotics.sdk.bootloader.hexLine.checkSum.
getDataBytes()
byte [] com.neuronrobotics.sdk.bootloader.hexLine.getDataBytes ()
Gets the data bytes.
Returns
the data bytes
Definition at line 123 of file hexLine.java.
References com.neuronrobotics.sdk.bootloader.hexLine.dataBytes, and com.neuronrobotics.sdk.bootloader.hexLine.dataToArray().
Referenced by com.neuronrobotics.sdk.bootloader.IntelHexParser.IntelHexParser(), and com.neuronrobotics.sdk.bootloader.hexLine.toString().
getEndAddress()
int com.neuronrobotics.sdk.bootloader.hexLine.getEndAddress ()
Gets the end address.
Returns
the end address
Definition at line 84 of file hexLine.java.
References com.neuronrobotics.sdk.bootloader.hexLine.address, and com.neuronrobotics.sdk.bootloader.hexLine.dataBytes.
Referenced by com.neuronrobotics.sdk.bootloader.IntelHexParser.IntelHexParser().
getRecordType()
int com.neuronrobotics.sdk.bootloader.hexLine.getRecordType ()
Gets the record type.
Returns
the record type
Definition at line 114 of file hexLine.java.
References com.neuronrobotics.sdk.bootloader.hexLine.recordType.
Referenced by com.neuronrobotics.sdk.bootloader.hexLine.toString().
getStartAddress()
int com.neuronrobotics.sdk.bootloader.hexLine.getStartAddress ()
Gets the start address.
Returns
the start address
Definition at line 75 of file hexLine.java.
References com.neuronrobotics.sdk.bootloader.hexLine.address.
Referenced by com.neuronrobotics.sdk.bootloader.hexLine.toString().
hasData()
Boolean com.neuronrobotics.sdk.bootloader.hexLine.hasData ()
Checks for data.
Returns
the boolean
Definition at line 134 of file hexLine.java.
References com.neuronrobotics.sdk.bootloader.hexLine.dataBytes.
setHighAddress()
void com.neuronrobotics.sdk.bootloader.hexLine.setHighAddress (long highAddress)
Sets the high address.
Parameters
highAddress the new high address
Definition at line 93 of file hexLine.java.
References com.neuronrobotics.sdk.bootloader.hexLine.address, and com.neuronrobotics.sdk.bootloader.hexLine.hasSetHighAddress.
toString()
String com.neuronrobotics.sdk.bootloader.hexLine.toString ()
Definition at line 157 of file hexLine.java.
References com.neuronrobotics.sdk.bootloader.hexLine.getDataBytes(), com.neuronrobotics.sdk.bootloader.hexLine.getRecordType(), and com.neuronrobotics.sdk.bootloader.hexLine.getStartAddress().
Member Data Documentation
address
int com.neuronrobotics.sdk.bootloader.hexLine.address private
The address.
Definition at line 16 of file hexLine.java.
Referenced by com.neuronrobotics.sdk.bootloader.hexLine.getEndAddress(), com.neuronrobotics.sdk.bootloader.hexLine.getStartAddress(), com.neuronrobotics.sdk.bootloader.hexLine.hexLine(), and com.neuronrobotics.sdk.bootloader.hexLine.setHighAddress().
byteCount
int com.neuronrobotics.sdk.bootloader.hexLine.byteCount private
The byte count.
Definition at line 19 of file hexLine.java.
Referenced by com.neuronrobotics.sdk.bootloader.hexLine.getByteCount(), and com.neuronrobotics.sdk.bootloader.hexLine.hexLine().
checkSum
int com.neuronrobotics.sdk.bootloader.hexLine.checkSum private
The check sum.
Definition at line 25 of file hexLine.java.
Referenced by com.neuronrobotics.sdk.bootloader.hexLine.getCheckSum(), and com.neuronrobotics.sdk.bootloader.hexLine.hexLine().
dataBytes
ArrayList<Byte> com.neuronrobotics.sdk.bootloader.hexLine.dataBytes = new ArrayList<Byte>() private
The data bytes.
Definition at line 13 of file hexLine.java.
Referenced by com.neuronrobotics.sdk.bootloader.hexLine.getDataBytes(), com.neuronrobotics.sdk.bootloader.hexLine.getEndAddress(), com.neuronrobotics.sdk.bootloader.hexLine.hasData(), and com.neuronrobotics.sdk.bootloader.hexLine.hexLine().
hasSetHighAddress
boolean com.neuronrobotics.sdk.bootloader.hexLine.hasSetHighAddress =false private
The has set high address.
Definition at line 28 of file hexLine.java.
Referenced by com.neuronrobotics.sdk.bootloader.hexLine.setHighAddress().
recordType
int com.neuronrobotics.sdk.bootloader.hexLine.recordType private
The record type.
Definition at line 22 of file hexLine.java.
Referenced by com.neuronrobotics.sdk.bootloader.hexLine.getRecordType(), and com.neuronrobotics.sdk.bootloader.hexLine.hexLine().
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/bootloader/hexLine.java