BowlerKernel: com.neuronrobotics.sdk.common.device.server.BowlerAbstractDeviceServerNamespace Class Reference
com.neuronrobotics.sdk.common.device.server.BowlerAbstractDeviceServerNamespace Class Reference abstract
Public Member Functions
BowlerAbstractDeviceServerNamespace (MACAddress addr, String namespaceString)
boolean checkRpc (BowlerDatagram data)
String getNamespace ()
ArrayList< RpcEncapsulation > getRpcList ()
void addRpc (RpcEncapsulation newRpc)
MACAddress getAddress ()
BowlerDatagram process (BowlerDatagram data)
int getNamespaceIndex ()
void setNamespaceIndex (int ns)
Protected Attributes
ArrayList< RpcEncapsulation > rpc =new ArrayList<RpcEncapsulation>()
final String ns
Private Attributes
final MACAddress mac
int namespaceIndex =0
Detailed Description
The Class BowlerAbstractDeviceServerNamespace.
Definition at line 16 of file BowlerAbstractDeviceServerNamespace.java.
Constructor & Destructor Documentation
BowlerAbstractDeviceServerNamespace()
com.neuronrobotics.sdk.common.device.server.BowlerAbstractDeviceServerNamespace.BowlerAbstractDeviceServerNamespace (MACAddress addr, String namespaceString)
Instantiates a new bowler abstract device server namespace.
Parameters
addr the addr
namespaceString the namespace string
Definition at line 36 of file BowlerAbstractDeviceServerNamespace.java.
Member Function Documentation
addRpc()
void com.neuronrobotics.sdk.common.device.server.BowlerAbstractDeviceServerNamespace.addRpc (RpcEncapsulation newRpc)
Adds the rpc.
Parameters
newRpc the new rpc
Definition at line 82 of file BowlerAbstractDeviceServerNamespace.java.
References com.neuronrobotics.sdk.common.device.server.BowlerAbstractDeviceServerNamespace.rpc.
checkRpc()
boolean com.neuronrobotics.sdk.common.device.server.BowlerAbstractDeviceServerNamespace.checkRpc (BowlerDatagram data)
Check rpc.
Parameters
data the data
Returns
true, if successful
Definition at line 47 of file BowlerAbstractDeviceServerNamespace.java.
References com.neuronrobotics.sdk.common.BowlerDatagram.getMethod(), com.neuronrobotics.sdk.common.BowlerDatagram.getRPC(), and com.neuronrobotics.sdk.common.device.server.BowlerAbstractDeviceServerNamespace.getRpcList().
getAddress()
MACAddress com.neuronrobotics.sdk.common.device.server.BowlerAbstractDeviceServerNamespace.getAddress ()
Gets the address.
Returns
the address
Definition at line 91 of file BowlerAbstractDeviceServerNamespace.java.
References com.neuronrobotics.sdk.common.device.server.BowlerAbstractDeviceServerNamespace.mac.
Referenced by com.neuronrobotics.sdk.common.device.server.BowlerAbstractDeviceServerNamespace.process().
getNamespace()
String com.neuronrobotics.sdk.common.device.server.BowlerAbstractDeviceServerNamespace.getNamespace ()
Gets the namespace.
Returns
the namespace
Definition at line 62 of file BowlerAbstractDeviceServerNamespace.java.
References com.neuronrobotics.sdk.common.device.server.BowlerAbstractDeviceServerNamespace.ns.
Referenced by com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.addBowlerDeviceServerNamespace(), com.neuronrobotics.sdk.common.device.server.bcs.core.BcsCoreNamespaceImp.BcsCoreNamespaceImp(), com.neuronrobotics.sdk.common.device.server.bcs.rpc.BcsRpcNamespaceImp.BcsRpcNamespaceImp(), com.neuronrobotics.sdk.namespace.bcs.pid.PidDeviceServer.onPIDEvent(), com.neuronrobotics.sdk.namespace.bcs.pid.PidDeviceServer.onPIDLimitEvent(), and com.neuronrobotics.sdk.namespace.bcs.pid.PidDeviceServerNamespace.PidDeviceServerNamespace().
getNamespaceIndex()
int com.neuronrobotics.sdk.common.device.server.BowlerAbstractDeviceServerNamespace.getNamespaceIndex ()
Gets the namespace index.
Returns
the namespace index
Definition at line 126 of file BowlerAbstractDeviceServerNamespace.java.
References com.neuronrobotics.sdk.common.device.server.BowlerAbstractDeviceServerNamespace.namespaceIndex.
Referenced by com.neuronrobotics.sdk.namespace.bcs.pid.PidDeviceServerNamespace.PidDeviceServerNamespace().
getRpcList()
ArrayList<RpcEncapsulation> com.neuronrobotics.sdk.common.device.server.BowlerAbstractDeviceServerNamespace.getRpcList ()
Gets the rpc list.
Returns
the rpc list
Definition at line 71 of file BowlerAbstractDeviceServerNamespace.java.
References com.neuronrobotics.sdk.common.device.server.BowlerAbstractDeviceServerNamespace.rpc.
Referenced by com.neuronrobotics.sdk.common.device.server.BowlerDeviceReServerNamespace.BowlerDeviceReServerNamespace(), com.neuronrobotics.sdk.common.device.server.BowlerAbstractDeviceServerNamespace.checkRpc(), and com.neuronrobotics.sdk.common.device.server.BowlerAbstractDeviceServerNamespace.process().
process()
BowlerDatagram com.neuronrobotics.sdk.common.device.server.BowlerAbstractDeviceServerNamespace.process (BowlerDatagram data)
Process.
Parameters
data the data
Returns
the bowler datagram
Reimplemented in com.neuronrobotics.sdk.common.device.server.BowlerDeviceReServerNamespace.
Definition at line 101 of file BowlerAbstractDeviceServerNamespace.java.
References com.neuronrobotics.sdk.common.device.server.BowlerAbstractDeviceServerNamespace.getAddress(), com.neuronrobotics.sdk.common.RpcEncapsulation.getCommandUpstream(), com.neuronrobotics.sdk.common.BowlerDatagram.getMethod(), com.neuronrobotics.sdk.common.RpcEncapsulation.getProcessor(), com.neuronrobotics.sdk.common.BowlerDatagram.getRPC(), com.neuronrobotics.sdk.common.device.server.BowlerAbstractDeviceServerNamespace.getRpcList(), com.neuronrobotics.sdk.common.RpcEncapsulation.parseResponseDownstream(), and com.neuronrobotics.sdk.common.device.server.IBowlerCommandProcessor.process().
Referenced by com.neuronrobotics.sdk.common.device.server.bcs.core.BcsCoreNamespaceImp.BcsCoreNamespaceImp(), com.neuronrobotics.sdk.common.device.server.bcs.rpc.BcsRpcNamespaceImp.BcsRpcNamespaceImp(), and com.neuronrobotics.sdk.namespace.bcs.pid.PidDeviceServerNamespace.PidDeviceServerNamespace().
setNamespaceIndex()
void com.neuronrobotics.sdk.common.device.server.BowlerAbstractDeviceServerNamespace.setNamespaceIndex (int ns)
Sets the namespace index.
Parameters
ns the new namespace index
Definition at line 135 of file BowlerAbstractDeviceServerNamespace.java.
References com.neuronrobotics.sdk.common.device.server.BowlerAbstractDeviceServerNamespace.namespaceIndex, and com.neuronrobotics.sdk.common.device.server.BowlerAbstractDeviceServerNamespace.ns.
Referenced by com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.addBowlerDeviceServerNamespace(), and com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.setup().
Member Data Documentation
mac
final MACAddress com.neuronrobotics.sdk.common.device.server.BowlerAbstractDeviceServerNamespace.mac private
The mac.
Definition at line 25 of file BowlerAbstractDeviceServerNamespace.java.
Referenced by com.neuronrobotics.sdk.common.device.server.bcs.core.BcsCoreNamespaceImp.BcsCoreNamespaceImp(), com.neuronrobotics.sdk.common.device.server.bcs.rpc.BcsRpcNamespaceImp.BcsRpcNamespaceImp(), and com.neuronrobotics.sdk.common.device.server.BowlerAbstractDeviceServerNamespace.getAddress().
namespaceIndex
int com.neuronrobotics.sdk.common.device.server.BowlerAbstractDeviceServerNamespace.namespaceIndex =0 private
The namespace index.
Definition at line 28 of file BowlerAbstractDeviceServerNamespace.java.
Referenced by com.neuronrobotics.sdk.common.device.server.BowlerAbstractDeviceServerNamespace.getNamespaceIndex(), and com.neuronrobotics.sdk.common.device.server.BowlerAbstractDeviceServerNamespace.setNamespaceIndex().
ns
final String com.neuronrobotics.sdk.common.device.server.BowlerAbstractDeviceServerNamespace.ns protected
The ns.
Definition at line 22 of file BowlerAbstractDeviceServerNamespace.java.
Referenced by com.neuronrobotics.sdk.common.device.server.BowlerAbstractDeviceServerNamespace.getNamespace(), and com.neuronrobotics.sdk.common.device.server.BowlerAbstractDeviceServerNamespace.setNamespaceIndex().
rpc
ArrayList<RpcEncapsulation> com.neuronrobotics.sdk.common.device.server.BowlerAbstractDeviceServerNamespace.rpc =new ArrayList<RpcEncapsulation>() protected
The rpc.
Definition at line 19 of file BowlerAbstractDeviceServerNamespace.java.
Referenced by com.neuronrobotics.sdk.common.device.server.BowlerAbstractDeviceServerNamespace.addRpc(), com.neuronrobotics.sdk.common.device.server.bcs.core.BcsCoreNamespaceImp.BcsCoreNamespaceImp(), com.neuronrobotics.sdk.common.device.server.bcs.rpc.BcsRpcNamespaceImp.BcsRpcNamespaceImp(), com.neuronrobotics.sdk.common.device.server.BowlerAbstractDeviceServerNamespace.getRpcList(), and com.neuronrobotics.sdk.namespace.bcs.pid.PidDeviceServerNamespace.PidDeviceServerNamespace().
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/common/device/server/BowlerAbstractDeviceServerNamespace.java