BowlerKernel: com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer Class Reference
com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer Class Reference abstract
Public Member Functions
BowlerAbstractServer (MACAddress mac)
void addBowlerDeviceServerNamespace (BowlerAbstractDeviceServerNamespace ns)
void removeBowlerDeviceServerNamespace (BowlerAbstractDeviceServerNamespace ns)
ArrayList< BowlerAbstractConnection > getServers ()
void startNetworkServer (final int port) throws IOException
void startNetworkServer () throws IOException
void addServer (BowlerAbstractConnection srv)
BowlerDatagram onSyncReceive (BowlerDatagram data)
void pushAsyncPacket (int namespaceIndex, String namespace, String rpcString, Object[] arguments, BowlerDataType[] asyncArguments)
synchronized void pushAsyncPacket (BowlerDatagram data)
ArrayList< BowlerAbstractDeviceServerNamespace > getNamespaces ()
void setNamespaces (ArrayList< BowlerAbstractDeviceServerNamespace > namespaces)
MACAddress getMacAddress ()
void setMacAddress (MACAddress macAddress)
Private Member Functions
void setup ()
BowlerDatagram processLocal (BowlerDatagram data)
void removeServer (BowlerAbstractConnection b)
Private Attributes
ArrayList< BowlerAbstractConnection > servers = new ArrayList<BowlerAbstractConnection>()
ArrayList< BowlerAbstractConnection > localServers = new ArrayList<BowlerAbstractConnection>()
ArrayList< BowlerAbstractDeviceServerNamespace > namespaces = new ArrayList<BowlerAbstractDeviceServerNamespace>()
BcsCoreNamespaceImp bcsCore
BcsRpcNamespaceImp bcsRpc
BowlerUDPServer udpServer
MACAddress macAddress
Detailed Description
The Class BowlerAbstractServer.
Definition at line 37 of file BowlerAbstractServer.java.
Constructor & Destructor Documentation
BowlerAbstractServer()
com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.BowlerAbstractServer (MACAddress mac)
Instantiates a new bowler abstract server.
Parameters
mac the mac
Definition at line 66 of file BowlerAbstractServer.java.
References com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.bcsCore, com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.bcsRpc, com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.setMacAddress(), and com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.setup().
Member Function Documentation
addBowlerDeviceServerNamespace()
void com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.addBowlerDeviceServerNamespace (BowlerAbstractDeviceServerNamespace ns)
Adds the bowler device server namespace.
Parameters
ns the ns
Definition at line 92 of file BowlerAbstractServer.java.
References com.neuronrobotics.sdk.common.Log.error(), com.neuronrobotics.sdk.common.device.server.BowlerAbstractDeviceServerNamespace.getNamespace(), com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.getNamespaces(), com.neuronrobotics.sdk.common.device.server.BowlerAbstractDeviceServerNamespace.setNamespaceIndex(), and com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.setup().
Referenced by com.neuronrobotics.sdk.network.AbstractNetworkDeviceServer.AbstractNetworkDeviceServer(), and com.neuronrobotics.sdk.namespace.bcs.pid.PidDeviceServer.PidDeviceServer().
addServer()
void com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.addServer (BowlerAbstractConnection srv)
Adds the server.
Parameters
srv the srv
Definition at line 204 of file BowlerAbstractServer.java.
References com.neuronrobotics.sdk.common.BowlerAbstractConnection.addConnectionEventListener(), com.neuronrobotics.sdk.common.BowlerAbstractConnection.connect(), com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.removeServer(), com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.servers, com.neuronrobotics.sdk.common.BowlerAbstractConnection.setSynchronousDatagramListener(), and com.neuronrobotics.sdk.common.Log.warning().
Referenced by com.neuronrobotics.sdk.network.AbstractNetworkDeviceServer.AbstractNetworkDeviceServer(), and com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.startNetworkServer().
getMacAddress()
MACAddress com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.getMacAddress ()
Gets the mac address.
Returns
the mac address
Definition at line 388 of file BowlerAbstractServer.java.
References com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.macAddress.
getNamespaces()
ArrayList<BowlerAbstractDeviceServerNamespace> com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.getNamespaces ()
Gets the namespaces.
Returns
the namespaces
Definition at line 369 of file BowlerAbstractServer.java.
References com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.namespaces.
Referenced by com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.addBowlerDeviceServerNamespace(), com.neuronrobotics.sdk.common.device.server.bcs.core.BcsCoreNamespaceImp.BcsCoreNamespaceImp(), com.neuronrobotics.sdk.common.device.server.bcs.rpc.BcsRpcNamespaceImp.BcsRpcNamespaceImp(), com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.processLocal(), com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.removeBowlerDeviceServerNamespace(), and com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.setup().
getServers()
ArrayList<BowlerAbstractConnection> com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.getServers ()
Gets the servers.
Returns
the servers
Definition at line 150 of file BowlerAbstractServer.java.
References com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.servers.
Referenced by com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.pushAsyncPacket(), and com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.removeServer().
onSyncReceive()
BowlerDatagram com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.onSyncReceive (BowlerDatagram data)
On sync inconimg packet.
Parameters
data the data
Returns
the bowler datagram
Implements com.neuronrobotics.sdk.common.ISynchronousDatagramListener.
Definition at line 228 of file BowlerAbstractServer.java.
References com.neuronrobotics.sdk.common.Log.debug(), com.neuronrobotics.sdk.common.Log.error(), com.neuronrobotics.sdk.common.BowlerDatagram.getRPC(), com.neuronrobotics.sdk.common.Log.info(), com.neuronrobotics.sdk.common.BowlerDatagram.isUpstream(), and com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.processLocal().
processLocal()
BowlerDatagram com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.processLocal (BowlerDatagram data) private
Process local.
Parameters
data the data
Returns
the bowler datagram
Definition at line 126 of file BowlerAbstractServer.java.
References com.neuronrobotics.sdk.common.Log.error(), com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.getNamespaces(), com.neuronrobotics.sdk.common.BowlerDatagram.getRPC(), and com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.setup().
Referenced by com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.onSyncReceive().
pushAsyncPacket() [1/2]
synchronized void com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.pushAsyncPacket (BowlerDatagram data)
Push async packet.
Parameters
data the data
Definition at line 313 of file BowlerAbstractServer.java.
References com.neuronrobotics.sdk.common.BowlerAbstractConnection.disconnect(), com.neuronrobotics.sdk.common.Log.error(), com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.getServers(), com.neuronrobotics.sdk.common.Log.info(), com.neuronrobotics.sdk.network.BowlerTCPServer.isClientConnected(), com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.localServers, and com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.servers.
pushAsyncPacket() [2/2]
void com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.pushAsyncPacket (int namespaceIndex, String namespace, String rpcString, Object[] arguments, BowlerDataType[] asyncArguments)
THis is the scripting interface to Bowler devices. THis allows a user to describe a namespace, rpc, and array or arguments to be paced into the packet based on the data types of the argument. The response in likewise unpacked into an array of objects.
Parameters
namespaceIndex the namespace index
namespace The string of the desired namespace
rpcString The string of the desired RPC
arguments An array of objects corresponding to the data to be stuffed into the packet.
asyncArguments the async arguments
Exceptions
DeviceConnectionException If the desired RPC's are not available then this will be thrown
Definition at line 289 of file BowlerAbstractServer.java.
References com.neuronrobotics.sdk.common.BowlerMethod.ASYNCHRONOUS, com.neuronrobotics.sdk.common.Log.debug(), and com.neuronrobotics.sdk.common.BowlerAbstractConnection.getCommand().
Referenced by com.neuronrobotics.sdk.common.device.server.BowlerDeviceReServerNamespace.BowlerDeviceReServerNamespace(), com.neuronrobotics.sdk.namespace.bcs.pid.PidDeviceServer.onPIDEvent(), and com.neuronrobotics.sdk.namespace.bcs.pid.PidDeviceServer.onPIDLimitEvent().
removeBowlerDeviceServerNamespace()
void com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.removeBowlerDeviceServerNamespace (BowlerAbstractDeviceServerNamespace ns)
Removes the bowler device server namespace.
Parameters
ns the ns
Definition at line 113 of file BowlerAbstractServer.java.
References com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.getNamespaces(), and com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.setup().
removeServer()
void com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.removeServer (BowlerAbstractConnection b) private
Removes the server.
Parameters
b the b
Definition at line 258 of file BowlerAbstractServer.java.
References com.neuronrobotics.sdk.common.Log.error(), com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.getServers(), com.neuronrobotics.sdk.network.BowlerUDPServer.reconnect(), and com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.udpServer.
Referenced by com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.addServer().
setMacAddress()
void com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.setMacAddress (MACAddress macAddress)
Sets the mac address.
Parameters
macAddress the new mac address
Definition at line 397 of file BowlerAbstractServer.java.
References com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.macAddress.
Referenced by com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.BowlerAbstractServer().
setNamespaces()
void com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.setNamespaces (ArrayList< BowlerAbstractDeviceServerNamespace > namespaces)
Sets the namespaces.
Parameters
namespaces the new namespaces
Definition at line 378 of file BowlerAbstractServer.java.
References com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.namespaces.
setup()
void com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.setup () private
Setup.
Definition at line 76 of file BowlerAbstractServer.java.
References com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.bcsCore, com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.bcsRpc, com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.getNamespaces(), and com.neuronrobotics.sdk.common.device.server.BowlerAbstractDeviceServerNamespace.setNamespaceIndex().
Referenced by com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.addBowlerDeviceServerNamespace(), com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.BowlerAbstractServer(), com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.processLocal(), and com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.removeBowlerDeviceServerNamespace().
startNetworkServer() [1/2]
void com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.startNetworkServer () throws IOException
Start network server.
Exceptions
IOException Signals that an I/O exception has occurred.
Definition at line 194 of file BowlerAbstractServer.java.
Referenced by com.neuronrobotics.sdk.namespace.bcs.pid.PidDeviceServer.PidDeviceServer().
startNetworkServer() [2/2]
void com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.startNetworkServer (final int port) throws IOException
Start network server.
Parameters
port the port
Exceptions
IOException Signals that an I/O exception has occurred.
Definition at line 163 of file BowlerAbstractServer.java.
References com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.addServer(), com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.udpServer, and com.neuronrobotics.sdk.common.Log.warning().
Member Data Documentation
bcsCore
BcsCoreNamespaceImp com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.bcsCore private
The bcs core.
Definition at line 50 of file BowlerAbstractServer.java.
Referenced by com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.BowlerAbstractServer(), and com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.setup().
bcsRpc
BcsRpcNamespaceImp com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.bcsRpc private
The bcs rpc.
Definition at line 53 of file BowlerAbstractServer.java.
Referenced by com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.BowlerAbstractServer(), and com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.setup().
localServers
ArrayList<BowlerAbstractConnection> com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.localServers = new ArrayList<BowlerAbstractConnection>() private
The local servers.
Definition at line 44 of file BowlerAbstractServer.java.
Referenced by com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.pushAsyncPacket().
macAddress
MACAddress com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.macAddress private
The mac address.
Definition at line 59 of file BowlerAbstractServer.java.
Referenced by com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.getMacAddress(), and com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.setMacAddress().
namespaces
ArrayList<BowlerAbstractDeviceServerNamespace> com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.namespaces = new ArrayList<BowlerAbstractDeviceServerNamespace>() private
The namespaces.
Definition at line 47 of file BowlerAbstractServer.java.
Referenced by com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.getNamespaces(), and com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.setNamespaces().
servers
ArrayList<BowlerAbstractConnection> com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.servers = new ArrayList<BowlerAbstractConnection>() private
The servers.
Definition at line 41 of file BowlerAbstractServer.java.
Referenced by com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.addServer(), com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.getServers(), and com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.pushAsyncPacket().
udpServer
BowlerUDPServer com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.udpServer private
The udp server.
Definition at line 56 of file BowlerAbstractServer.java.
Referenced by com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.removeServer(), and com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.startNetworkServer().
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/common/device/server/BowlerAbstractServer.java