BowlerKernel: com.neuronrobotics.bowlerstudio.assets.AssetFactory Class Reference
com.neuronrobotics.bowlerstudio.assets.AssetFactory Class Reference
Static Public Member Functions
static FXMLLoader loadLayout (String file, boolean refresh) throws Exception
static FXMLLoader loadLayout (String file) throws Exception
static File loadFile (String file) throws Exception
static void writeImage (Image img, File file)
static Image loadAsset (String file) throws Exception
static ImageView loadIcon (String file)
static String getGitSource () throws Exception
static void setGitSource (String gitSource, String assetRepoBranch) throws Exception
static void loadAllAssets () throws Exception
static String getAssetRepoBranch ()
static void setAssetRepoBranch (String assetRepoBranch)
static void deleteFolder (File folder)
Static Public Attributes
static final String repo = "BowlerStudioImageAssets"
Private Member Functions
AssetFactory ()
Static Private Attributes
static String gitSource = "https://github.com/madhephaestus/" + repo + ".git"
static HashMap< String, Image > cache = new HashMap<>()
static HashMap< String, FXMLLoader > loaders = new HashMap<>()
static String assetRepoBranch = ""
Detailed Description
Definition at line 26 of file AssetFactory.java.
Constructor & Destructor Documentation
AssetFactory()
com.neuronrobotics.bowlerstudio.assets.AssetFactory.AssetFactory () private
Definition at line 34 of file AssetFactory.java.
Member Function Documentation
deleteFolder()
static void com.neuronrobotics.bowlerstudio.assets.AssetFactory.deleteFolder (File folder) static
Definition at line 177 of file AssetFactory.java.
getAssetRepoBranch()
static String com.neuronrobotics.bowlerstudio.assets.AssetFactory.getAssetRepoBranch () static
Definition at line 169 of file AssetFactory.java.
References com.neuronrobotics.bowlerstudio.assets.AssetFactory.assetRepoBranch.
Referenced by com.neuronrobotics.bowlerstudio.assets.AssetFactory.loadFile().
getGitSource()
static String com.neuronrobotics.bowlerstudio.assets.AssetFactory.getGitSource () throws Exception static
Definition at line 142 of file AssetFactory.java.
References com.neuronrobotics.bowlerstudio.assets.AssetFactory.gitSource.
Referenced by com.neuronrobotics.bowlerstudio.assets.AssetFactory.loadAsset(), and com.neuronrobotics.bowlerstudio.assets.AssetFactory.loadFile().
loadAllAssets()
static void com.neuronrobotics.bowlerstudio.assets.AssetFactory.loadAllAssets () throws Exception static
Definition at line 155 of file AssetFactory.java.
References com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.filesInGit(), com.neuronrobotics.bowlerstudio.assets.StudioBuildInfo.getVersion(), com.neuronrobotics.bowlerstudio.assets.AssetFactory.gitSource, and com.neuronrobotics.bowlerstudio.assets.AssetFactory.loadAsset().
Referenced by com.neuronrobotics.bowlerstudio.assets.AssetFactory.setGitSource().
loadAsset()
static Image com.neuronrobotics.bowlerstudio.assets.AssetFactory.loadAsset (String file) throws Exception static
Definition at line 85 of file AssetFactory.java.
References com.neuronrobotics.bowlerstudio.assets.AssetFactory.cache, com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.createFile(), com.neuronrobotics.bowlerstudio.assets.AssetFactory.getGitSource(), com.neuronrobotics.bowlerstudio.assets.AssetFactory.loadFile(), com.neuronrobotics.bowlerstudio.assets.AssetFactory.loadLayout(), and com.neuronrobotics.bowlerstudio.assets.AssetFactory.writeImage().
Referenced by com.neuronrobotics.bowlerstudio.assets.AssetFactory.loadAllAssets(), and com.neuronrobotics.bowlerstudio.assets.AssetFactory.loadIcon().
loadFile()
static File com.neuronrobotics.bowlerstudio.assets.AssetFactory.loadFile (String file) throws Exception static
Definition at line 53 of file AssetFactory.java.
References com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.fileFromGit(), com.neuronrobotics.bowlerstudio.assets.AssetFactory.getAssetRepoBranch(), and com.neuronrobotics.bowlerstudio.assets.AssetFactory.getGitSource().
Referenced by com.neuronrobotics.bowlerstudio.assets.AssetFactory.loadAsset(), com.neuronrobotics.bowlerstudio.assets.AssetFactory.loadLayout(), and com.neuronrobotics.sdk.addons.gamepad.JogTrainerWidget.start().
loadIcon()
static ImageView com.neuronrobotics.bowlerstudio.assets.AssetFactory.loadIcon (String file) static
Definition at line 128 of file AssetFactory.java.
References com.neuronrobotics.bowlerstudio.IssueReportingExceptionHandler.except(), and com.neuronrobotics.bowlerstudio.assets.AssetFactory.loadAsset().
loadLayout() [1/2]
static FXMLLoader com.neuronrobotics.bowlerstudio.assets.AssetFactory.loadLayout (String file) throws Exception static
Definition at line 49 of file AssetFactory.java.
References com.neuronrobotics.bowlerstudio.assets.AssetFactory.loadLayout().
loadLayout() [2/2]
static FXMLLoader com.neuronrobotics.bowlerstudio.assets.AssetFactory.loadLayout (String file, boolean refresh) throws Exception static
Definition at line 37 of file AssetFactory.java.
References com.neuronrobotics.bowlerstudio.assets.AssetFactory.loaders, and com.neuronrobotics.bowlerstudio.assets.AssetFactory.loadFile().
Referenced by com.neuronrobotics.bowlerstudio.assets.AssetFactory.loadAsset(), and com.neuronrobotics.bowlerstudio.assets.AssetFactory.loadLayout().
setAssetRepoBranch()
static void com.neuronrobotics.bowlerstudio.assets.AssetFactory.setAssetRepoBranch (String assetRepoBranch) static
Definition at line 173 of file AssetFactory.java.
References com.neuronrobotics.bowlerstudio.assets.AssetFactory.assetRepoBranch.
Referenced by com.neuronrobotics.bowlerstudio.assets.AssetFactory.setGitSource().
setGitSource()
static void com.neuronrobotics.bowlerstudio.assets.AssetFactory.setGitSource (String gitSource, String assetRepoBranch) throws Exception static
Definition at line 146 of file AssetFactory.java.
References com.neuronrobotics.bowlerstudio.assets.AssetFactory.assetRepoBranch, com.neuronrobotics.bowlerstudio.assets.AssetFactory.cache, com.neuronrobotics.bowlerstudio.assets.AssetFactory.gitSource, com.neuronrobotics.bowlerstudio.assets.AssetFactory.loadAllAssets(), and com.neuronrobotics.bowlerstudio.assets.AssetFactory.setAssetRepoBranch().
writeImage()
static void com.neuronrobotics.bowlerstudio.assets.AssetFactory.writeImage (Image img, File file) static
Definition at line 62 of file AssetFactory.java.
Referenced by com.neuronrobotics.bowlerstudio.assets.AssetFactory.loadAsset().
Member Data Documentation
assetRepoBranch
String com.neuronrobotics.bowlerstudio.assets.AssetFactory.assetRepoBranch = "" static private
Definition at line 32 of file AssetFactory.java.
Referenced by com.neuronrobotics.bowlerstudio.assets.AssetFactory.getAssetRepoBranch(), com.neuronrobotics.bowlerstudio.assets.AssetFactory.setAssetRepoBranch(), and com.neuronrobotics.bowlerstudio.assets.AssetFactory.setGitSource().
cache
HashMap<String, Image> com.neuronrobotics.bowlerstudio.assets.AssetFactory.cache = new HashMap<>() static private
Definition at line 30 of file AssetFactory.java.
Referenced by com.neuronrobotics.bowlerstudio.assets.AssetFactory.loadAsset(), and com.neuronrobotics.bowlerstudio.assets.AssetFactory.setGitSource().
gitSource
String com.neuronrobotics.bowlerstudio.assets.AssetFactory.gitSource = "https://github.com/madhephaestus/" + repo + ".git" static private
Definition at line 29 of file AssetFactory.java.
Referenced by com.neuronrobotics.bowlerstudio.assets.AssetFactory.getGitSource(), com.neuronrobotics.bowlerstudio.assets.AssetFactory.loadAllAssets(), and com.neuronrobotics.bowlerstudio.assets.AssetFactory.setGitSource().
loaders
HashMap<String, FXMLLoader> com.neuronrobotics.bowlerstudio.assets.AssetFactory.loaders = new HashMap<>() static private
Definition at line 31 of file AssetFactory.java.
Referenced by com.neuronrobotics.bowlerstudio.assets.AssetFactory.loadLayout().
repo
final String com.neuronrobotics.bowlerstudio.assets.AssetFactory.repo = "BowlerStudioImageAssets" static
Definition at line 28 of file AssetFactory.java.
The documentation for this class was generated from the following file:
src/main/java/com/neuronrobotics/bowlerstudio/assets/AssetFactory.java