BowlerKernel: com.neuronrobotics.bowlerstudio.scripting.RobotHelper Class Reference
com.neuronrobotics.bowlerstudio.scripting.RobotHelper Class Reference
Public Member Functions
Object inlineScriptRun (File code, ArrayList< Object > args)
Object inlineScriptRun (String code, ArrayList< Object > args)
String getShellType ()
boolean getIsTextFile ()
String getDefaultContents ()
String getDefaultContents (String gitURL, String slug)
ArrayList< String > getFileExtenetion ()
Public Member Functions inherited from com.neuronrobotics.bowlerstudio.scripting.IScriptingLanguage
default boolean isSupportedFileExtenetion (String filename)
Detailed Description
Definition at line 17 of file RobotHelper.java.
Member Function Documentation
getDefaultContents() [1/2]
String com.neuronrobotics.bowlerstudio.scripting.RobotHelper.getDefaultContents ()
Get the contents of an empty file
Returns
Implements com.neuronrobotics.bowlerstudio.scripting.IScriptingLanguage.
Definition at line 74 of file RobotHelper.java.
References com.neuronrobotics.sdk.addons.kinematics.MobileBase.getXml().
getDefaultContents() [2/2]
String com.neuronrobotics.bowlerstudio.scripting.RobotHelper.getDefaultContents (String gitURL, String slug)
Get the contents of an empty file
Returns
Implements com.neuronrobotics.bowlerstudio.scripting.IScriptingLanguage.
Definition at line 85 of file RobotHelper.java.
References com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.addNewLink(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.copyGitFile(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.getAppendages(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getName(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.getXml(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setDeviceScriptingName(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.setGitCadEngine(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.setGitDhEngine(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.setGitSelfSource(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.setGitWalkingEngine(), com.neuronrobotics.sdk.addons.kinematics.DHLink.setListener(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setName(), and com.neuronrobotics.sdk.common.BowlerAbstractDevice.setScriptingName().
getFileExtenetion()
ArrayList<String> com.neuronrobotics.bowlerstudio.scripting.RobotHelper.getFileExtenetion ()
Returns the list of supported file extentions Convention is to provide just the leters that make up the file extention
Implements com.neuronrobotics.bowlerstudio.scripting.IScriptingLanguage.
Definition at line 117 of file RobotHelper.java.
getIsTextFile()
boolean com.neuronrobotics.bowlerstudio.scripting.RobotHelper.getIsTextFile ()
This function returns if this is a binary file or a text file
Returns
true if the file is a text file.
Implements com.neuronrobotics.bowlerstudio.scripting.IScriptingLanguage.
Definition at line 64 of file RobotHelper.java.
getShellType()
String com.neuronrobotics.bowlerstudio.scripting.RobotHelper.getShellType ()
Returns the HashMap key for this language
Implements com.neuronrobotics.bowlerstudio.scripting.IScriptingLanguage.
Definition at line 59 of file RobotHelper.java.
inlineScriptRun() [1/2]
Object com.neuronrobotics.bowlerstudio.scripting.RobotHelper.inlineScriptRun (File code, ArrayList< Object > args)
This interface is for adding additional language support.
Parameters
code file content of the code to be executed
args the incoming arguments as a list of objects
Returns
the objects returned form the code that ran
Implements com.neuronrobotics.bowlerstudio.scripting.IScriptingLanguage.
Definition at line 20 of file RobotHelper.java.
References com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.findGitTagFromFile(), com.neuronrobotics.bowlerstudio.creature.MobileBaseLoader.get(), com.neuronrobotics.bowlerstudio.creature.MobileBaseLoader.getBase(), and com.neuronrobotics.sdk.addons.kinematics.MobileBase.setGitSelfSource().
inlineScriptRun() [2/2]
Object com.neuronrobotics.bowlerstudio.scripting.RobotHelper.inlineScriptRun (String code, ArrayList< Object > args)
This interface is for adding additional language support.
Parameters
code the text content of the code to be executed
args the incoming arguments as a list of objects
Returns
the objects returned form the code that ran
Implements com.neuronrobotics.bowlerstudio.scripting.IScriptingLanguage.
Definition at line 44 of file RobotHelper.java.
The documentation for this class was generated from the following file:
src/main/java/com/neuronrobotics/bowlerstudio/scripting/RobotHelper.java