BowlerKernel: com.neuronrobotics.sdk.ui.BluetoothConnectionPanel.BluetoothSearchProcess Class Reference
com.neuronrobotics.sdk.ui.BluetoothConnectionPanel.BluetoothSearchProcess Class Reference
Public Member Functions
void run ()
double getPercentage ()
boolean isComplete ()
Private Attributes
boolean isRunning = false
Detailed Description
The Class BluetoothSearchProcess.
Definition at line 160 of file BluetoothConnectionPanel.java.
Member Function Documentation
getPercentage()
double com.neuronrobotics.sdk.ui.BluetoothConnectionPanel.BluetoothSearchProcess.getPercentage ()
Gets the percentage.
Returns
the percentage
Implements com.neuronrobotics.sdk.util.IMonitorable.
Definition at line 212 of file BluetoothConnectionPanel.java.
isComplete()
boolean com.neuronrobotics.sdk.ui.BluetoothConnectionPanel.BluetoothSearchProcess.isComplete ()
Checks if is complete.
Returns
true, if is complete
Implements com.neuronrobotics.sdk.util.IMonitorable.
Definition at line 220 of file BluetoothConnectionPanel.java.
References com.neuronrobotics.sdk.ui.BluetoothConnectionPanel.BluetoothSearchProcess.isRunning.
run()
void com.neuronrobotics.sdk.ui.BluetoothConnectionPanel.BluetoothSearchProcess.run ()
Definition at line 168 of file BluetoothConnectionPanel.java.
References com.neuronrobotics.sdk.ui.BluetoothConnectionPanel.blue, com.neuronrobotics.sdk.ui.BluetoothConnectionPanel.connection, com.neuronrobotics.sdk.ui.BluetoothConnectionPanel.connectionCbo, com.neuronrobotics.sdk.wireless.bluetooth.BluetoothSerialConnection.disconnect(), com.neuronrobotics.sdk.ui.BluetoothConnectionPanel.displayWarning, com.neuronrobotics.sdk.wireless.bluetooth.BlueCoveManager.getAvailableSerialDevices(), com.neuronrobotics.sdk.ui.ConnectionImageIconFactory.getIcon(), com.neuronrobotics.sdk.common.Log.info(), com.neuronrobotics.sdk.ui.BluetoothConnectionPanel.BluetoothSearchProcess.isRunning, and com.neuronrobotics.sdk.ui.BluetoothConnectionPanel.message.
Member Data Documentation
isRunning
boolean com.neuronrobotics.sdk.ui.BluetoothConnectionPanel.BluetoothSearchProcess.isRunning = false private
The is running.
Definition at line 163 of file BluetoothConnectionPanel.java.
Referenced by com.neuronrobotics.sdk.ui.BluetoothConnectionPanel.BluetoothSearchProcess.isComplete(), and com.neuronrobotics.sdk.ui.BluetoothConnectionPanel.BluetoothSearchProcess.run().
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/ui/BluetoothConnectionPanel.java