BowlerKernel: com.neuronrobotics.sdk.common.DeviceManager Class Reference
com.neuronrobotics.sdk.common.DeviceManager Class Reference
Static Public Member Functions
static void addConnection (final Object newDevice, String name)
static void addConnection (BowlerAbstractConnection connection)
static void addConnection ()
static void remove (BowlerAbstractDevice newDevice)
static void addDeviceAddedListener (IDeviceAddedListener l)
static void removeDeviceAddedListener (IDeviceAddedListener l)
static Object getSpecificDevice (String name, IDeviceProvider provider)
static Object getSpecificDevice (String name)
static Object getSpecificDevice (Class<?> class1, String name)
static List< String > listConnectedDevice ()
static List< String > listConnectedDevice (Class<?> class1)
Static Private Member Functions
static void addConnectionBAD (final BowlerAbstractDevice newDevice, String name)
Static Private Attributes
static final ArrayList< BowlerAbstractDevice > devices = new ArrayList<BowlerAbstractDevice>()
static final ArrayList< IDeviceAddedListener > deviceAddedListener = new ArrayList<IDeviceAddedListener>()
Detailed Description
The Class DeviceManager.
Definition at line 20 of file DeviceManager.java.
Member Function Documentation
addConnection() [1/3]
static void com.neuronrobotics.sdk.common.DeviceManager.addConnection () static
Adds the connection.
Definition at line 183 of file DeviceManager.java.
References com.neuronrobotics.sdk.ui.ConnectionDialog.promptConnection(), and com.neuronrobotics.sdk.common.BowlerDatagram.setUseBowlerV4().
Referenced by com.neuronrobotics.sdk.common.DeviceManager.addConnection(), and com.neuronrobotics.sdk.common.DeviceManager.getSpecificDevice().
addConnection() [2/3]
static void com.neuronrobotics.sdk.common.DeviceManager.addConnection (BowlerAbstractConnection connection) static
Adds the connection.
Parameters
connection the connection
Definition at line 123 of file DeviceManager.java.
References com.neuronrobotics.sdk.common.DeviceManager.addConnection(), com.neuronrobotics.sdk.common.BowlerAbstractDevice.connect(), com.neuronrobotics.sdk.dyio.DyIO.connect(), com.neuronrobotics.sdk.pid.GenericPIDDevice.connect(), com.neuronrobotics.sdk.common.BowlerAbstractDevice.getConnection(), com.neuronrobotics.sdk.common.BowlerAbstractDevice.hasNamespace(), com.neuronrobotics.sdk.common.BowlerAbstractDevice.ping(), com.neuronrobotics.sdk.common.BowlerAbstractDevice.setConnection(), com.neuronrobotics.sdk.pid.GenericPIDDevice.setConnection(), com.neuronrobotics.sdk.common.BowlerDatagram.setUseBowlerV4(), and com.neuronrobotics.sdk.util.ThreadUtil.wait().
addConnection() [3/3]
static void com.neuronrobotics.sdk.common.DeviceManager.addConnection (final Object newDevice, String name) static
Adds the connection.
Parameters
newDevice the new device
name the name
Definition at line 36 of file DeviceManager.java.
References com.neuronrobotics.sdk.common.DeviceManager.addConnectionBAD(), and com.neuronrobotics.sdk.common.DMDevice.wrappable().
Referenced by com.neuronrobotics.sdk.addons.kinematics.LinkFactory.LinkFactory().
addConnectionBAD()
static void com.neuronrobotics.sdk.common.DeviceManager.addConnectionBAD (final BowlerAbstractDevice newDevice, String name) static private
Adds the connection.
Parameters
newDevice the new device
name the name
Definition at line 59 of file DeviceManager.java.
References com.neuronrobotics.sdk.common.BowlerAbstractDevice.addConnectionEventListener(), com.neuronrobotics.sdk.common.BowlerAbstractDevice.connect(), com.neuronrobotics.sdk.common.DeviceManager.deviceAddedListener, com.neuronrobotics.sdk.common.DeviceManager.devices, com.neuronrobotics.sdk.common.BowlerAbstractDevice.getScriptingName(), com.neuronrobotics.sdk.common.DeviceManager.getSpecificDevice(), com.neuronrobotics.sdk.common.DMDevice.getWrapped(), com.neuronrobotics.sdk.common.BowlerAbstractDevice.isAvailable(), com.neuronrobotics.sdk.common.DeviceManager.listConnectedDevice(), com.neuronrobotics.sdk.common.IDeviceAddedListener.onNewDeviceAdded(), com.neuronrobotics.sdk.common.DeviceManager.remove(), com.neuronrobotics.sdk.common.BowlerAbstractDevice.setScriptingName(), and com.neuronrobotics.sdk.common.Log.warning().
Referenced by com.neuronrobotics.sdk.common.DeviceManager.addConnection().
addDeviceAddedListener()
static void com.neuronrobotics.sdk.common.DeviceManager.addDeviceAddedListener (IDeviceAddedListener l) static
Adds the device added listener.
Parameters
l the l
Definition at line 220 of file DeviceManager.java.
References com.neuronrobotics.sdk.common.DeviceManager.deviceAddedListener.
getSpecificDevice() [1/3]
static Object com.neuronrobotics.sdk.common.DeviceManager.getSpecificDevice (Class<?> class1, String name) static
Gets the specific device.
Parameters
class1 the class1
name the name
Returns
the specific device
Definition at line 300 of file DeviceManager.java.
References com.neuronrobotics.sdk.common.DeviceManager.devices, com.neuronrobotics.sdk.common.DeviceManager.getSpecificDevice(), and com.neuronrobotics.sdk.common.DeviceManager.listConnectedDevice().
getSpecificDevice() [2/3]
static Object com.neuronrobotics.sdk.common.DeviceManager.getSpecificDevice (String name) static
Gets the specific device.
Parameters
name the name
Returns
the specific device
Definition at line 274 of file DeviceManager.java.
References com.neuronrobotics.sdk.common.DeviceManager.devices.
getSpecificDevice() [3/3]
static Object com.neuronrobotics.sdk.common.DeviceManager.getSpecificDevice (String name, IDeviceProvider provider) static
Gets the specific device.
Parameters
name the name
Returns
the specific device
Definition at line 243 of file DeviceManager.java.
References com.neuronrobotics.sdk.common.DeviceManager.addConnection(), com.neuronrobotics.sdk.common.IDeviceProvider.call(), and com.neuronrobotics.sdk.common.DeviceManager.devices.
Referenced by com.neuronrobotics.sdk.common.DeviceManager.addConnectionBAD(), com.neuronrobotics.sdk.dyio.peripherals.AnalogInputChannel.AnalogInputChannel(), com.neuronrobotics.sdk.dyio.peripherals.CounterInputChannel.CounterInputChannel(), com.neuronrobotics.sdk.dyio.peripherals.CounterOutputChannel.CounterOutputChannel(), com.neuronrobotics.sdk.dyio.peripherals.DCMotorOutputChannel.DCMotorOutputChannel(), com.neuronrobotics.sdk.dyio.peripherals.DigitalInputChannel.DigitalInputChannel(), com.neuronrobotics.sdk.dyio.peripherals.DigitalOutputChannel.DigitalOutputChannel(), com.neuronrobotics.sdk.addons.kinematics.LinkFactory.flush(), com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.get(), com.neuronrobotics.bowlerstudio.opencv.OpenCVManager.get(), com.neuronrobotics.bowlerstudio.sequence.TimeSequence.getDevices(), com.neuronrobotics.sdk.addons.kinematics.LinkFactory.getDyio(), com.neuronrobotics.sdk.addons.kinematics.LinkFactory.getGCODE(), com.neuronrobotics.sdk.addons.kinematics.LinkFactory.getPid(), com.neuronrobotics.sdk.common.DeviceManager.getSpecificDevice(), com.neuronrobotics.sdk.addons.kinematics.LinkFactory.getVirtual(), com.neuronrobotics.sdk.addons.kinematics.LinkFactory.isConnected(), com.neuronrobotics.application.xmpp.DyIOConversation.onMessage(), com.neuronrobotics.sdk.dyio.peripherals.PPMReaderChannel.PPMReaderChannel(), com.neuronrobotics.sdk.dyio.peripherals.PWMOutputChannel.PWMOutputChannel(), com.neuronrobotics.sdk.dyio.peripherals.ServoChannel.ServoChannel(), com.neuronrobotics.sdk.dyio.peripherals.SPIChannel.SPIChannel(), and com.neuronrobotics.sdk.dyio.peripherals.UARTChannel.UARTChannel().
listConnectedDevice() [1/2]
static List<String> com.neuronrobotics.sdk.common.DeviceManager.listConnectedDevice () static
List connected device.
Returns
the list
Definition at line 328 of file DeviceManager.java.
References com.neuronrobotics.sdk.common.DeviceManager.devices.
Referenced by com.neuronrobotics.sdk.common.DeviceManager.addConnectionBAD(), com.neuronrobotics.bowlerstudio.sequence.TimeSequence.getDevices(), and com.neuronrobotics.sdk.common.DeviceManager.getSpecificDevice().
listConnectedDevice() [2/2]
static List<String> com.neuronrobotics.sdk.common.DeviceManager.listConnectedDevice (Class<?> class1) static
List connected device.
Parameters
class1 the class1
Returns
the list
Definition at line 344 of file DeviceManager.java.
References com.neuronrobotics.sdk.common.DeviceManager.devices.
remove()
static void com.neuronrobotics.sdk.common.DeviceManager.remove (BowlerAbstractDevice newDevice) static
Removes the.
Parameters
newDevice the new device
Definition at line 205 of file DeviceManager.java.
References com.neuronrobotics.sdk.common.DeviceManager.deviceAddedListener, and com.neuronrobotics.sdk.common.DeviceManager.devices.
Referenced by com.neuronrobotics.sdk.common.DeviceManager.addConnectionBAD().
removeDeviceAddedListener()
static void com.neuronrobotics.sdk.common.DeviceManager.removeDeviceAddedListener (IDeviceAddedListener l) static
Removes the device added listener.
Parameters
l the l
Definition at line 231 of file DeviceManager.java.
References com.neuronrobotics.sdk.common.DeviceManager.deviceAddedListener.
Member Data Documentation
deviceAddedListener
final ArrayList<IDeviceAddedListener> com.neuronrobotics.sdk.common.DeviceManager.deviceAddedListener = new ArrayList<IDeviceAddedListener>() static private
The Constant deviceAddedListener.
Definition at line 26 of file DeviceManager.java.
Referenced by com.neuronrobotics.sdk.common.DeviceManager.addConnectionBAD(), com.neuronrobotics.sdk.common.DeviceManager.addDeviceAddedListener(), com.neuronrobotics.sdk.common.DeviceManager.remove(), and com.neuronrobotics.sdk.common.DeviceManager.removeDeviceAddedListener().
devices
final ArrayList<BowlerAbstractDevice> com.neuronrobotics.sdk.common.DeviceManager.devices = new ArrayList<BowlerAbstractDevice>() static private
The Constant devices.
Definition at line 23 of file DeviceManager.java.
Referenced by com.neuronrobotics.sdk.common.DeviceManager.addConnectionBAD(), com.neuronrobotics.sdk.common.DeviceManager.getSpecificDevice(), com.neuronrobotics.sdk.common.DeviceManager.listConnectedDevice(), and com.neuronrobotics.sdk.common.DeviceManager.remove().
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/common/DeviceManager.java