BowlerKernel: com.neuronrobotics.sdk.pid.PIDChannel Class Reference
com.neuronrobotics.sdk.pid.PIDChannel Class Reference
Public Member Functions
PIDChannel (IPidControlNamespace p, int i)
boolean SetPIDSetPoint (float setpoint, double seconds)
boolean SetPIDInterpolatedVelocity (int unitsPerSecond, double seconds) throws PIDCommandException
boolean SetPDVelocity (int unitsPerSecond, double seconds) throws PIDCommandException
float GetPIDPosition ()
boolean ConfigurePIDController (PIDConfiguration config)
PIDConfiguration getPIDConfiguration ()
boolean ResetPIDChannel ()
boolean ResetPIDChannel (int valueToSetCurrentTo)
void setPid (IPidControlNamespace p)
IPidControlNamespace getPid ()
void removePIDEventListener (IPIDEventListener l)
void addPIDEventListener (IPIDEventListener l)
void firePIDLimitEvent (PIDLimitEvent e)
void firePIDEvent (PIDEvent e)
void firePIDResetEvent (int group, float value)
void flush (double time)
void setCachedTargetValue (float targetValue)
float getCachedTargetValue ()
void setCurrentCachedPosition (float currentCachedPosition)
float getCurrentCachedPosition ()
boolean isAvailable ()
int getGroup ()
Private Attributes
IPidControlNamespace pid
int index
float targetValue
float currentCachedPosition
ArrayList< IPIDEventListener > PIDEventListeners = new ArrayList<IPIDEventListener>()
Detailed Description
The Class PIDChannel.
Definition at line 12 of file PIDChannel.java.
Constructor & Destructor Documentation
PIDChannel()
com.neuronrobotics.sdk.pid.PIDChannel.PIDChannel (IPidControlNamespace p, int i)
Instantiates a new PID channel.
Parameters
p the p
i the i
Definition at line 35 of file PIDChannel.java.
References com.neuronrobotics.sdk.pid.PIDChannel.index, and com.neuronrobotics.sdk.pid.PIDChannel.setPid().
Member Function Documentation
addPIDEventListener()
void com.neuronrobotics.sdk.pid.PIDChannel.addPIDEventListener (IPIDEventListener l)
Adds the pid event listener.
Parameters
l the l
Definition at line 183 of file PIDChannel.java.
References com.neuronrobotics.sdk.pid.PIDChannel.PIDEventListeners.
Referenced by com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.runHome(), com.neuronrobotics.sdk.addons.kinematics.PidPrismaticLink.setPIDChannel(), and com.neuronrobotics.sdk.addons.kinematics.PidRotoryLink.setPIDChannel().
ConfigurePIDController()
boolean com.neuronrobotics.sdk.pid.PIDChannel.ConfigurePIDController (PIDConfiguration config)
Configure pid controller.
Parameters
config the config
Returns
true, if successful
Definition at line 91 of file PIDChannel.java.
References com.neuronrobotics.sdk.namespace.bcs.pid.IPidControlNamespace.ConfigurePIDController(), com.neuronrobotics.sdk.pid.PIDChannel.getPid(), com.neuronrobotics.sdk.pid.PIDChannel.index, and com.neuronrobotics.sdk.pid.PIDConfiguration.setGroup().
Referenced by com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.homeLink().
firePIDEvent()
void com.neuronrobotics.sdk.pid.PIDChannel.firePIDEvent (PIDEvent e)
Fire pid event.
Parameters
e the e
Definition at line 205 of file PIDChannel.java.
References com.neuronrobotics.sdk.pid.PIDChannel.PIDEventListeners.
Referenced by com.neuronrobotics.sdk.pid.PIDChannel.setPid().
firePIDLimitEvent()
void com.neuronrobotics.sdk.pid.PIDChannel.firePIDLimitEvent (PIDLimitEvent e)
Fire pid limit event.
Parameters
e the e
Definition at line 194 of file PIDChannel.java.
References com.neuronrobotics.sdk.pid.PIDChannel.PIDEventListeners.
Referenced by com.neuronrobotics.sdk.pid.PIDChannel.setPid().
firePIDResetEvent()
void com.neuronrobotics.sdk.pid.PIDChannel.firePIDResetEvent (int group, float value)
Fire pid reset event.
Parameters
group the group
value the value
Definition at line 218 of file PIDChannel.java.
References com.neuronrobotics.sdk.pid.PIDChannel.PIDEventListeners.
Referenced by com.neuronrobotics.sdk.pid.PIDChannel.setPid().
flush()
void com.neuronrobotics.sdk.pid.PIDChannel.flush (double time)
Flush.
Parameters
time the time
Definition at line 229 of file PIDChannel.java.
References com.neuronrobotics.sdk.pid.PIDChannel.getCachedTargetValue(), and com.neuronrobotics.sdk.pid.PIDChannel.SetPIDSetPoint().
Referenced by com.neuronrobotics.sdk.addons.kinematics.PidPrismaticLink.flushDevice(), and com.neuronrobotics.sdk.addons.kinematics.PidRotoryLink.flushDevice().
getCachedTargetValue()
float com.neuronrobotics.sdk.pid.PIDChannel.getCachedTargetValue ()
Gets the cached target value.
Returns
the cached target value
Definition at line 252 of file PIDChannel.java.
References com.neuronrobotics.sdk.pid.PIDChannel.targetValue.
Referenced by com.neuronrobotics.sdk.pid.PIDChannel.flush(), com.neuronrobotics.sdk.namespace.bcs.pid.AbstractPidNamespaceImp.flushPIDChannels(), com.neuronrobotics.sdk.pid.VirtualGenericPIDDevice.flushPIDChannels(), and com.neuronrobotics.sdk.namespace.bcs.pid.LegacyPidNamespaceImp.SetAllPIDSetPoint().
getCurrentCachedPosition()
float com.neuronrobotics.sdk.pid.PIDChannel.getCurrentCachedPosition ()
Gets the current cached position.
Returns
the current cached position
Definition at line 274 of file PIDChannel.java.
References com.neuronrobotics.sdk.pid.PIDChannel.currentCachedPosition.
Referenced by com.neuronrobotics.sdk.namespace.bcs.pid.AbstractPidNamespaceImp.GetCachedPosition().
getGroup()
int com.neuronrobotics.sdk.pid.PIDChannel.getGroup ()
Gets the group.
Returns
the group
Definition at line 293 of file PIDChannel.java.
References com.neuronrobotics.sdk.pid.PIDChannel.index.
Referenced by com.neuronrobotics.sdk.pid.PIDChannel.setCachedTargetValue().
getPid()
IPidControlNamespace com.neuronrobotics.sdk.pid.PIDChannel.getPid ()
Gets the pid.
Returns
the pid
Definition at line 163 of file PIDChannel.java.
References com.neuronrobotics.sdk.pid.PIDChannel.pid.
Referenced by com.neuronrobotics.sdk.pid.PIDChannel.ConfigurePIDController(), com.neuronrobotics.sdk.addons.kinematics.PidPrismaticLink.flushAllDevice(), com.neuronrobotics.sdk.addons.kinematics.PidRotoryLink.flushAllDevice(), com.neuronrobotics.sdk.pid.PIDChannel.getPIDConfiguration(), com.neuronrobotics.sdk.pid.PIDChannel.GetPIDPosition(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.homeLink(), com.neuronrobotics.sdk.pid.PIDChannel.ResetPIDChannel(), com.neuronrobotics.sdk.pid.PIDChannel.SetPDVelocity(), com.neuronrobotics.sdk.pid.PIDChannel.SetPIDInterpolatedVelocity(), and com.neuronrobotics.sdk.pid.PIDChannel.SetPIDSetPoint().
getPIDConfiguration()
PIDConfiguration com.neuronrobotics.sdk.pid.PIDChannel.getPIDConfiguration ()
Gets the PID configuration.
Returns
the PID configuration
Definition at line 102 of file PIDChannel.java.
References com.neuronrobotics.sdk.pid.PIDChannel.getPid(), com.neuronrobotics.sdk.namespace.bcs.pid.IPidControlNamespace.getPIDConfiguration(), and com.neuronrobotics.sdk.pid.PIDChannel.index.
GetPIDPosition()
float com.neuronrobotics.sdk.pid.PIDChannel.GetPIDPosition ()
Gets the pid position.
Returns
the int
Definition at line 81 of file PIDChannel.java.
References com.neuronrobotics.sdk.pid.PIDChannel.getPid(), com.neuronrobotics.sdk.namespace.bcs.pid.IPidControlNamespace.GetPIDPosition(), and com.neuronrobotics.sdk.pid.PIDChannel.index.
Referenced by com.neuronrobotics.sdk.addons.kinematics.PidPrismaticLink.getCurrentPosition(), and com.neuronrobotics.sdk.addons.kinematics.PidRotoryLink.getCurrentPosition().
isAvailable()
boolean com.neuronrobotics.sdk.pid.PIDChannel.isAvailable ()
Checks if is available.
Returns
true, if is available
Definition at line 283 of file PIDChannel.java.
References com.neuronrobotics.sdk.namespace.bcs.pid.IPidControlNamespace.isAvailable(), and com.neuronrobotics.sdk.pid.PIDChannel.pid.
removePIDEventListener()
void com.neuronrobotics.sdk.pid.PIDChannel.removePIDEventListener (IPIDEventListener l)
Removes the pid event listener.
Parameters
l the l
Definition at line 172 of file PIDChannel.java.
References com.neuronrobotics.sdk.pid.PIDChannel.PIDEventListeners.
Referenced by com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.runHome().
ResetPIDChannel() [1/2]
boolean com.neuronrobotics.sdk.pid.PIDChannel.ResetPIDChannel ()
Reset pid channel.
Returns
true, if successful
Definition at line 111 of file PIDChannel.java.
References com.neuronrobotics.sdk.pid.PIDChannel.getPid(), com.neuronrobotics.sdk.pid.PIDChannel.index, and com.neuronrobotics.sdk.namespace.bcs.pid.IPidControlNamespace.ResetPIDChannel().
ResetPIDChannel() [2/2]
boolean com.neuronrobotics.sdk.pid.PIDChannel.ResetPIDChannel (int valueToSetCurrentTo)
Reset pid channel.
Parameters
valueToSetCurrentTo the value to set current to
Returns
true, if successful
Definition at line 122 of file PIDChannel.java.
References com.neuronrobotics.sdk.pid.PIDChannel.getPid(), com.neuronrobotics.sdk.pid.PIDChannel.index, and com.neuronrobotics.sdk.namespace.bcs.pid.IPidControlNamespace.ResetPIDChannel().
setCachedTargetValue()
void com.neuronrobotics.sdk.pid.PIDChannel.setCachedTargetValue (float targetValue)
Sets the cached target value.
Parameters
targetValue the new cached target value
Definition at line 238 of file PIDChannel.java.
References com.neuronrobotics.sdk.pid.PIDChannel.getGroup(), com.neuronrobotics.sdk.common.Log.info(), and com.neuronrobotics.sdk.pid.PIDChannel.targetValue.
Referenced by com.neuronrobotics.sdk.addons.kinematics.PidPrismaticLink.cacheTargetValueDevice(), com.neuronrobotics.sdk.addons.kinematics.PidRotoryLink.cacheTargetValueDevice(), com.neuronrobotics.sdk.namespace.bcs.pid.LegacyPidNamespaceImp.GetAllPIDPosition(), com.neuronrobotics.sdk.pid.VirtualGenericPIDDevice.GetAllPIDPosition(), com.neuronrobotics.sdk.namespace.bcs.pid.LegacyPidNamespaceImp.SetAllPIDSetPoint(), and com.neuronrobotics.sdk.namespace.bcs.pid.LegacyPidNamespaceImp.SetPIDSetPoint().
setCurrentCachedPosition()
void com.neuronrobotics.sdk.pid.PIDChannel.setCurrentCachedPosition (float currentCachedPosition)
Sets the current cached position.
Parameters
currentCachedPosition the new current cached position
Definition at line 263 of file PIDChannel.java.
References com.neuronrobotics.sdk.pid.PIDChannel.currentCachedPosition.
Referenced by com.neuronrobotics.sdk.namespace.bcs.pid.AbstractPidNamespaceImp.AbstractPidNamespaceImp(), and com.neuronrobotics.sdk.namespace.bcs.pid.AbstractPidNamespaceImp.SetCachedPosition().
SetPDVelocity()
boolean com.neuronrobotics.sdk.pid.PIDChannel.SetPDVelocity (int unitsPerSecond, double seconds) throws PIDCommandException
Sets the pd velocity.
Parameters
unitsPerSecond the units per second
seconds the seconds
Returns
true, if successful
Exceptions
PIDCommandException the PID command exception
Definition at line 72 of file PIDChannel.java.
References com.neuronrobotics.sdk.pid.PIDChannel.getPid(), com.neuronrobotics.sdk.pid.PIDChannel.index, and com.neuronrobotics.sdk.namespace.bcs.pid.IPidControlNamespace.SetPDVelocity().
setPid()
void com.neuronrobotics.sdk.pid.PIDChannel.setPid (IPidControlNamespace p)
Sets the pid.
Parameters
p the new pid
Definition at line 131 of file PIDChannel.java.
References com.neuronrobotics.sdk.namespace.bcs.pid.IPidControlNamespace.addPIDEventListener(), com.neuronrobotics.sdk.pid.PIDChannel.firePIDEvent(), com.neuronrobotics.sdk.pid.PIDChannel.firePIDLimitEvent(), com.neuronrobotics.sdk.pid.PIDChannel.firePIDResetEvent(), com.neuronrobotics.sdk.pid.PIDEvent.getGroup(), com.neuronrobotics.sdk.pid.PIDLimitEvent.getGroup(), com.neuronrobotics.sdk.pid.PIDChannel.index, and com.neuronrobotics.sdk.pid.PIDChannel.pid.
Referenced by com.neuronrobotics.sdk.pid.PIDChannel.PIDChannel().
SetPIDInterpolatedVelocity()
boolean com.neuronrobotics.sdk.pid.PIDChannel.SetPIDInterpolatedVelocity (int unitsPerSecond, double seconds) throws PIDCommandException
Sets the pid interpolated velocity.
Parameters
unitsPerSecond the units per second
seconds the seconds
Returns
true, if successful
Exceptions
PIDCommandException the PID command exception
Definition at line 60 of file PIDChannel.java.
References com.neuronrobotics.sdk.pid.PIDChannel.getPid(), com.neuronrobotics.sdk.pid.PIDChannel.index, and com.neuronrobotics.sdk.namespace.bcs.pid.IPidControlNamespace.SetPIDInterpolatedVelocity().
SetPIDSetPoint()
boolean com.neuronrobotics.sdk.pid.PIDChannel.SetPIDSetPoint (float setpoint, double seconds)
Sets the pid set point.
Parameters
setpoint the setpoint
seconds the seconds
Returns
true, if successful
Definition at line 47 of file PIDChannel.java.
References com.neuronrobotics.sdk.pid.PIDChannel.getPid(), com.neuronrobotics.sdk.pid.PIDChannel.index, and com.neuronrobotics.sdk.namespace.bcs.pid.IPidControlNamespace.SetPIDSetPoint().
Referenced by com.neuronrobotics.sdk.pid.PIDChannel.flush(), and com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.runHome().
Member Data Documentation
currentCachedPosition
float com.neuronrobotics.sdk.pid.PIDChannel.currentCachedPosition private
The current cached position.
Definition at line 24 of file PIDChannel.java.
Referenced by com.neuronrobotics.sdk.pid.PIDChannel.getCurrentCachedPosition(), and com.neuronrobotics.sdk.pid.PIDChannel.setCurrentCachedPosition().
index
int com.neuronrobotics.sdk.pid.PIDChannel.index private
The index.
Definition at line 18 of file PIDChannel.java.
Referenced by com.neuronrobotics.sdk.pid.PIDChannel.ConfigurePIDController(), com.neuronrobotics.sdk.pid.PIDChannel.getGroup(), com.neuronrobotics.sdk.pid.PIDChannel.getPIDConfiguration(), com.neuronrobotics.sdk.pid.PIDChannel.GetPIDPosition(), com.neuronrobotics.sdk.pid.PIDChannel.PIDChannel(), com.neuronrobotics.sdk.pid.PIDChannel.ResetPIDChannel(), com.neuronrobotics.sdk.pid.PIDChannel.SetPDVelocity(), com.neuronrobotics.sdk.pid.PIDChannel.setPid(), com.neuronrobotics.sdk.pid.PIDChannel.SetPIDInterpolatedVelocity(), and com.neuronrobotics.sdk.pid.PIDChannel.SetPIDSetPoint().
pid
IPidControlNamespace com.neuronrobotics.sdk.pid.PIDChannel.pid private
The pid.
Definition at line 15 of file PIDChannel.java.
Referenced by com.neuronrobotics.sdk.pid.PIDChannel.getPid(), com.neuronrobotics.sdk.pid.PIDChannel.isAvailable(), and com.neuronrobotics.sdk.pid.PIDChannel.setPid().
PIDEventListeners
ArrayList<IPIDEventListener> com.neuronrobotics.sdk.pid.PIDChannel.PIDEventListeners = new ArrayList<IPIDEventListener>() private
The PID event listeners.
Definition at line 27 of file PIDChannel.java.
Referenced by com.neuronrobotics.sdk.pid.PIDChannel.addPIDEventListener(), com.neuronrobotics.sdk.pid.PIDChannel.firePIDEvent(), com.neuronrobotics.sdk.pid.PIDChannel.firePIDLimitEvent(), com.neuronrobotics.sdk.pid.PIDChannel.firePIDResetEvent(), and com.neuronrobotics.sdk.pid.PIDChannel.removePIDEventListener().
targetValue
float com.neuronrobotics.sdk.pid.PIDChannel.targetValue private
The target value.
Definition at line 21 of file PIDChannel.java.
Referenced by com.neuronrobotics.sdk.pid.PIDChannel.getCachedTargetValue(), and com.neuronrobotics.sdk.pid.PIDChannel.setCachedTargetValue().
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/pid/PIDChannel.java