BowlerKernel: eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList Class Reference
eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList Class Reference
Classes
class Itr
class ListItr
class SubList
Public Member Functions
FloatArrayList (int initialCapacity)
FloatArrayList ()
FloatArrayList (Collection<? extends Float > c)
void trimToSize ()
void ensureCapacity (int minCapacity)
int size ()
boolean isEmpty ()
boolean contains (Object o)
int indexOf (Object o)
int lastIndexOf (Object o)
Object clone ()
Object[] toArray ()
float[] toFloatArray ()
Float get (int index)
Float set (int index, Float element)
boolean add (Float e)
void add (int index, Float element)
Float remove (int index)
boolean remove (Object o)
void clear ()
boolean addAll (Collection<? extends Float > c)
boolean addAll (int index, Collection<? extends Float > c)
boolean removeAll (Collection<?> c)
boolean retainAll (Collection<?> c)
ListIterator< Float > listIterator (int index)
ListIterator< Float > listIterator ()
Iterator< Float > iterator ()
List< Float > subList (int fromIndex, int toIndex)
Protected Member Functions
void removeRange (int fromIndex, int toIndex)
Private Member Functions
void ensureCapacityInternal (int minCapacity)
void grow (int minCapacity)
void fastRemove (int index)
void rangeCheck (int index)
void rangeCheckForAdd (int index)
String outOfBoundsMsg (int index)
boolean batchRemove (Collection<?> c, boolean complement)
void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
void readObject (java.io.ObjectInputStream s) throws java.io.IOException, ClassNotFoundException
Static Private Member Functions
static int hugeCapacity (int minCapacity)
Private Attributes
transient float[] elementData
int size
Static Private Attributes
static final int MAX_ARRAY_SIZE = Integer.MAX_VALUE - 8
Detailed Description
Resizable-array implementation of the List<Float> interface. Implements all optional list operations, and doesn't permit null s. In addition to implementing the List interface, this class provides methods to manipulate the size of the array that is used internally to store the list. (This class is roughly equivalent to Vector , except that it is unsynchronized.)
The size , isEmpty , get , set , iterator , and listIterator operations run in constant time. The add operation runs in amortized constant time , that is, adding n elements requires O(n) time. All of the other operations run in linear time (roughly speaking). The constant factor is low compared to that for the LinkedList implementation.
Each ArrayList instance has a capacity . The capacity is the size of the array used to store the elements in the list. It is always at least as large as the list size. As elements are added to an ArrayList, its capacity grows automatically. The details of the growth policy are not specified beyond the fact that adding an element has constant amortized time cost.
An application can increase the capacity of an ArrayList instance before adding a large number of elements using the ensureCapacity operation. This may reduce the amount of incremental reallocation.
Note that this implementation is not synchronized. If multiple threads access an ArrayList instance concurrently, and at least one of the threads modifies the list structurally, it must be synchronized externally. (A structural modification is any operation that adds or deletes one or more elements, or explicitly resizes the backing array; merely setting the value of an element is not a structural modification.) This is typically accomplished by synchronizing on some object that naturally encapsulates the list.
If no such object exists, the list should be "wrapped" using the Collections.synchronizedList method. This is best done at creation time, to prevent accidental unsynchronized access to the list: List list = Collections.synchronizedList(new ArrayList(...));
name="fail-fast" The iterators returned by this class's iterator and {listIterator} methods are fail-fast : if the list is structurally modified at any time after the iterator is created, in any way except through the iterator's own ListIterator#remove() remove} or ListIterator#add(Object) add} methods, the iterator will throw a ConcurrentModificationException}. Thus, in the face of concurrent modification, the iterator fails quickly and cleanly, rather than risking arbitrary, non-deterministic behavior at an undetermined time in the future. Note that the fail-fast behavior of an iterator cannot be guaranteed as it is, generally speaking, impossible to make any hard guarantees in the presence of unsynchronized concurrent modification. Fail-fast iterators throw
ConcurrentModificationException
on a best-effort basis. Therefore, it would be wrong to write a program that depended on this exception for its correctness: the fail-fast behavior of iterators should be used only to detect bugs.
This class is a member of the ="{@docRoot}/../technotes/guides/collections/ index.html" Java Collections Framework .
See also
Collection
List
LinkedList
Vector
TODO replace with ObservableFloatArray
Definition at line 103 of file FloatArrayList.java.
Constructor & Destructor Documentation
FloatArrayList() [1/3]
eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.FloatArrayList (int initialCapacity)
Constructs an empty list with the specified initial capacity.
Parameters
initialCapacity the initial capacity of the list
Exceptions
IllegalArgumentException if the specified initial capacity is negative
Definition at line 125 of file FloatArrayList.java.
FloatArrayList() [2/3]
eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.FloatArrayList ()
Constructs an empty list with an initial capacity of ten.
Definition at line 136 of file FloatArrayList.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.clone().
FloatArrayList() [3/3]
eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.FloatArrayList (Collection<? extends Float > c)
Constructs a list containing the elements of the specified collection, in the order they are returned by the collection's iterator.
Parameters
c the collection whose elements are to be placed into this list
Exceptions
NullPointerException if the specified collection is null
Definition at line 147 of file FloatArrayList.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.elementData, and eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.size.
Member Function Documentation
add() [1/2]
boolean eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.add (Float e)
Appends the specified element to the end of this list.
Parameters
e element to be appended to this list
Returns
true (as specified by Collection#add)
Definition at line 420 of file FloatArrayList.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.elementData, eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.ensureCapacityInternal(), and eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.size.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.ListItr.add(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.SubList.add(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.addMesh(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.addMesh(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.read(), and eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.read().
add() [2/2]
void eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.add (int index, Float element)
Inserts the specified element at the specified position in this list. Shifts the element currently at that position (if any) and any subsequent elements to the right (adds one to their indices).
Parameters
index index at which the specified element is to be inserted
element element to be inserted
Exceptions
IndexOutOfBoundsException
Reimplemented in eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.SubList.
Definition at line 434 of file FloatArrayList.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.elementData, eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.ensureCapacityInternal(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.rangeCheckForAdd(), and eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.size.
addAll() [1/2]
boolean eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.addAll (Collection<? extends Float > c)
Appends all of the elements in the specified collection to the end of this list, in the order that they are returned by the specified collection's Iterator. The behavior of this operation is undefined if the specified collection is modified while the operation is in progress. (This implies that the behavior of this call is undefined if the specified collection is this list, and this list is nonempty.)
Parameters
c collection containing elements to be added to this list
Returns
true if this list changed as a result of the call
Exceptions
NullPointerException if the specified collection is null
Reimplemented in eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.SubList.
Definition at line 530 of file FloatArrayList.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.elementData, eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.ensureCapacityInternal(), and eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.size.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.SubList.addAll().
addAll() [2/2]
boolean eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.addAll (int index, Collection<? extends Float > c)
Inserts all of the elements in the specified collection into this list, starting at the specified position. Shifts the element currently at that position (if any) and any subsequent elements to the right (increases their indices). The new elements will appear in the list in the order that they are returned by the specified collection's iterator.
Parameters
index index at which to insert the first element from the specified collection
c collection containing elements to be added to this list
Returns
true if this list changed as a result of the call
Exceptions
IndexOutOfBoundsException
NullPointerException if the specified collection is null
Reimplemented in eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.SubList.
Definition at line 551 of file FloatArrayList.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.elementData, eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.ensureCapacityInternal(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.rangeCheckForAdd(), and eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.size.
batchRemove()
boolean eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.batchRemove (Collection<?> c, boolean complement) private
Batch remove.
Parameters
c the c
complement the complement
Returns
true, if successful
Definition at line 665 of file FloatArrayList.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.elementData, and eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.size.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.removeAll(), and eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.retainAll().
clear()
void eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.clear ()
Removes all of the elements from this list. The list will be empty after this call returns.
Definition at line 510 of file FloatArrayList.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.elementData, and eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.size.
clone()
Object eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.clone ()
Returns a shallow copy of this ArrayList instance. (The elements themselves are not copied.)
Returns
a clone of this ArrayList instance
Definition at line 302 of file FloatArrayList.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.clone(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.elementData, eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.FloatArrayList(), and eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.size.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.clone().
contains()
boolean eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.contains (Object o)
Returns true if this list contains the specified element. More formally, returns true if and only if this list contains at least one element e such that (o==null ? e==null : o.equals(e)) .
Parameters
o element whose presence in this list is to be tested
Returns
true if this list contains the specified element
Definition at line 257 of file FloatArrayList.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.indexOf().
ensureCapacity()
void eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.ensureCapacity (int minCapacity)
Increases the capacity of this ArrayList instance, if necessary, to ensure that it can hold at least the number of elements specified by the minimum capacity argument.
Parameters
minCapacity the desired minimum capacity
Definition at line 175 of file FloatArrayList.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.ensureCapacityInternal().
ensureCapacityInternal()
void eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.ensureCapacityInternal (int minCapacity) private
Ensure capacity internal.
Parameters
minCapacity the min capacity
Definition at line 186 of file FloatArrayList.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.elementData, and eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.grow().
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.add(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.addAll(), and eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.ensureCapacity().
fastRemove()
void eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.fastRemove (int index) private
Fast remove.
Parameters
index the index
Definition at line 499 of file FloatArrayList.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.elementData, and eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.size.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.remove().
get()
Float eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.get (int index)
Returns the element at the specified position in this list.
Parameters
index index of the element to return
Returns
the element at the specified position in this list
Exceptions
IndexOutOfBoundsException
Reimplemented in eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.SubList.
Definition at line 392 of file FloatArrayList.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.elementData, and eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.rangeCheck().
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.addMesh(), and eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.addMesh().
grow()
void eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.grow (int minCapacity) private
Increases the capacity to ensure that it can hold at least the number of elements specified by the minimum capacity argument.
Parameters
minCapacity the desired minimum capacity
Definition at line 206 of file FloatArrayList.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.elementData, eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.hugeCapacity(), and eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.MAX_ARRAY_SIZE.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.ensureCapacityInternal().
hugeCapacity()
static int eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.hugeCapacity (int minCapacity) static private
Huge capacity.
Parameters
minCapacity the min capacity
Returns
the int
Definition at line 224 of file FloatArrayList.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.MAX_ARRAY_SIZE.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.grow().
indexOf()
int eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.indexOf (Object o)
Returns the index of the first occurrence of the specified element in this list, or -1 if this list does not contain the element. More formally, returns the lowest index i such that (o==null ? get(i)==null : o.equals(get(i))) , or -1 if there is no such index.
Parameters
o the o
Returns
the int
Definition at line 269 of file FloatArrayList.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.elementData, and eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.size.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.contains().
isEmpty()
boolean eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.isEmpty ()
Returns true if this list contains no elements.
Returns
true if this list contains no elements
Definition at line 246 of file FloatArrayList.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.size.
iterator()
Iterator<Float> eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.iterator ()
Returns an iterator over the elements in this list in proper sequence.
The returned iterator is fail-fast.
Returns
an iterator over the elements in this list in proper sequence
Reimplemented in eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.SubList.
Definition at line 774 of file FloatArrayList.java.
lastIndexOf()
int eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.lastIndexOf (Object o)
Returns the index of the last occurrence of the specified element in this list, or -1 if this list does not contain the element. More formally, returns the highest index i such that (o==null ? get(i)==null : o.equals(get(i))) , or -1 if there is no such index.
Parameters
o the o
Returns
the int
Definition at line 288 of file FloatArrayList.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.elementData, and eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.size.
listIterator() [1/2]
ListIterator<Float> eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.listIterator ()
Returns a list iterator over the elements in this list (in proper sequence).
The returned list iterator is fail-fast.
Returns
the list iterator
See also
listIterator(int)
Definition at line 764 of file FloatArrayList.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.SubList.iterator().
listIterator() [2/2]
ListIterator<Float> eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.listIterator (int index)
Returns a list iterator over the elements in this list (in proper sequence), starting at the specified position in the list. The specified index indicates the first element that would be returned by an initial call to {next}. An initial call to ListIterator#previous previous} would return the element with the specified index minus one. The returned list iterator is fail-fast.
Parameters
index the index
Returns
the list iterator
Exceptions
IndexOutOfBoundsException
Reimplemented in eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.SubList.
Definition at line 751 of file FloatArrayList.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.size.
outOfBoundsMsg()
String eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.outOfBoundsMsg (int index) private
Constructs an IndexOutOfBoundsException detail message. Of the many possible refactorings of the error handling code, this "outlining" performs best with both server and client VMs.
Parameters
index the index
Returns
the string
Reimplemented in eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.SubList.
Definition at line 621 of file FloatArrayList.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.size.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.rangeCheck(), and eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.rangeCheckForAdd().
rangeCheck()
void eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.rangeCheck (int index) private
Checks if the given index is in range. If not, throws an appropriate runtime exception. This method does not check if the index is negative: It is always used immediately prior to an array access, which throws an ArrayIndexOutOfBoundsException if index is negative.
Parameters
index the index
Reimplemented in eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.SubList.
Definition at line 599 of file FloatArrayList.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.outOfBoundsMsg(), and eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.size.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.get(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.remove(), and eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.set().
rangeCheckForAdd()
void eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.rangeCheckForAdd (int index) private
A version of rangeCheck used by add and addAll.
Parameters
index the index
Reimplemented in eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.SubList.
Definition at line 609 of file FloatArrayList.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.outOfBoundsMsg(), and eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.size.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.add(), and eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.addAll().
readObject()
void eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.readObject (java.io.ObjectInputStream s) throws java.io.IOException, ClassNotFoundException private
Reconstitute the ArrayList instance from a stream (that is, deserialize it).
Parameters
s the s
Exceptions
ClassNotFoundException the class not found exception
Definition at line 726 of file FloatArrayList.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.elementData, and eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.size.
remove() [1/2]
Float eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.remove (int index)
Removes the element at the specified position in this list. Shifts any subsequent elements to the left (subtracts one from their indices).
Parameters
index the index of the element to be removed
Returns
the element that was removed from the list
Exceptions
IndexOutOfBoundsException
Reimplemented in eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.SubList.
Definition at line 453 of file FloatArrayList.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.elementData, eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.rangeCheck(), and eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.size.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.Itr.remove(), and eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.SubList.remove().
remove() [2/2]
boolean eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.remove (Object o)
Removes the first occurrence of the specified element from this list, if it is present. If the list does not contain the element, it is unchanged. More formally, removes the element with the lowest index i such that (o==null ? get(i)==null : o.equals(get(i))) (if such an element exists). Returns true if this list contained the specified element (or equivalently, if this list changed as a result of the call).
Parameters
o element to be removed from this list, if present
Returns
true if this list contained the specified element
Definition at line 479 of file FloatArrayList.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.elementData, eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.fastRemove(), and eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.size.
removeAll()
boolean eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.removeAll (Collection<?> c)
Removes from this list all of its elements that are contained in the specified collection.
Parameters
c collection containing elements to be removed from this list
Returns
true
if this list changed as a result of the call
Exceptions
ClassCastException if the class of an element of this list is incompatible with the specified collection (="Collection.html#optional-restrictions"optional)
NullPointerException if this list contains a null element and the specified collection does not permit null elements (="Collection.html#optional-restrictions"optional), or if the specified collection is null
See also
Collection::contains(Object)
Definition at line 637 of file FloatArrayList.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.batchRemove().
removeRange()
void eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.removeRange (int fromIndex, int toIndex) protected
Removes from this list all of the elements whose index is between
fromIndex
, inclusive, and
toIndex
, exclusive. Shifts any succeeding elements to the left (reduces their index). This call shortens the list by
(toIndex - fromIndex)
elements. (If
toIndex==fromIndex
, this operation has no effect.)
Parameters
fromIndex the from index
toIndex the to index
Exceptions
IndexOutOfBoundsException if
fromIndex
or
toIndex
is out of range (
fromIndex < 0
                                 || fromIndex >= size() || toIndex > size() || toIndex < fromIndex
)
Reimplemented in eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.SubList.
Definition at line 579 of file FloatArrayList.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.elementData, and eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.size.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.SubList.removeRange().
retainAll()
boolean eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.retainAll (Collection<?> c)
Retains only the elements in this list that are contained in the specified collection. In other words, removes from this list all of its elements that are not contained in the specified collection.
Parameters
c collection containing elements to be retained in this list
Returns
true
if this list changed as a result of the call
Exceptions
ClassCastException if the class of an element of this list is incompatible with the specified collection (="Collection.html#optional-restrictions"optional)
NullPointerException if this list contains a null element and the specified collection does not permit null elements (="Collection.html#optional-restrictions"optional), or if the specified collection is null
See also
Collection::contains(Object)
Definition at line 654 of file FloatArrayList.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.batchRemove().
set()
Float eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.set (int index, Float element)
Replaces the element at the specified position in this list with the specified element.
Parameters
index index of the element to replace
element element to be stored at the specified position
Returns
the element previously at the specified position
Exceptions
IndexOutOfBoundsException
Reimplemented in eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.SubList.
Definition at line 406 of file FloatArrayList.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.elementData, and eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.rangeCheck().
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.SubList.listIterator(), and eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.ListItr.set().
size()
int eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.size ()
Returns the number of elements in this list.
Returns
the number of elements in this list
Reimplemented in eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.SubList.
Definition at line 237 of file FloatArrayList.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.size.
subList()
List<Float> eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.subList (int fromIndex, int toIndex)
Returns a view of the portion of this list between the specified
fromIndex
, inclusive, and
toIndex
, exclusive. (If
fromIndex
and
toIndex
are equal, the returned list is empty.) The returned list is backed by this list, so non-structural changes in the returned list are reflected in this list, and vice-versa. The returned list supports all of the optional list operations.
This method eliminates the need for explicit range operations (of the sort that commonly exist for arrays). Any operation that expects a list can be used as a range operation by passing a subList view instead of a whole list. For example, the following idiom removes a range of elements from a list:
 list.subList(from, to).clear();
Similar idioms may be constructed for indexOf(Object) and lastIndexOf(Object), and all of the algorithms in the Collections class can be applied to a subList.
The semantics of the list returned by this method become undefined if the backing list (i.e., this list) is structurally modified in any way other than via the returned list. (Structural modifications are those that change the size of this list, or otherwise perturb it in such a fashion that iterations in progress may yield incorrect results.)
Parameters
fromIndex the from index
toIndex the to index
Returns
the list
Exceptions
IndexOutOfBoundsException
IllegalArgumentException
Reimplemented in eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.SubList.
Definition at line 947 of file FloatArrayList.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.size.
toArray()
Object [] eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.toArray ()
Returns an array containing all of the elements in this list in proper sequence (from first to last element).
The returned array will be "safe" in that no references to it are maintained by this list. (In other words, this method must allocate a new array). The caller is thus free to modify the returned array.
This method acts as bridge between array-based and collection-based APIs.
Returns
an array containing all of the elements in this list in proper sequence
Definition at line 324 of file FloatArrayList.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.elementData, and eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.size.
toFloatArray()
float [] eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.toFloatArray ()
To float array.
Returns
the float[]
Reimplemented in eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.SubList.
Definition at line 367 of file FloatArrayList.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.elementData, and eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.size.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.addMesh(), and eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.addMesh().
trimToSize()
void eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.trimToSize ()
Trims the capacity of this ArrayList instance to be the list current size. An application can use this operation to minimize the storage of an ArrayList instance.
Definition at line 161 of file FloatArrayList.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.elementData, and eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.size.
writeObject()
void eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.writeObject (java.io.ObjectOutputStream s) throws java.io.IOException private
Save the state of the ArrayList instance to a stream (that is, serialize it).
Parameters
s the s @serialData The length of the array backing the ArrayList instance is emitted (int), followed by all of its elements (each an Object) in the proper order.
Definition at line 701 of file FloatArrayList.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.elementData, and eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.size.
Member Data Documentation
elementData
transient float [] eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.elementData private
The array buffer into which the elements of the ArrayList are stored. The capacity of the ArrayList is the length of this array buffer.
Definition at line 110 of file FloatArrayList.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.add(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.addAll(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.batchRemove(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.clear(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.clone(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.ensureCapacityInternal(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.fastRemove(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.FloatArrayList(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.get(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.SubList.get(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.grow(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.indexOf(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.lastIndexOf(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.SubList.listIterator(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.Itr.next(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.ListItr.previous(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.readObject(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.remove(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.removeRange(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.SubList.set(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.set(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.toArray(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.toFloatArray(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.SubList.toFloatArray(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.trimToSize(), and eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.writeObject().
MAX_ARRAY_SIZE
final int eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.MAX_ARRAY_SIZE = Integer.MAX_VALUE - 8 static private
The maximum size of array to allocate. Some VMs reserve some header words in an array. Attempts to allocate larger arrays may result in OutOfMemoryError: Requested array size exceeds VM limit
Definition at line 198 of file FloatArrayList.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.grow(), and eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.hugeCapacity().
size
int eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.size private
The size of the ArrayList (the number of elements it contains).
@serial
Reimplemented in eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.SubList.
Definition at line 117 of file FloatArrayList.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.add(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.addAll(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.addMesh(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.addMesh(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.batchRemove(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.clear(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.clone(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.fastRemove(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.FloatArrayList(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.Itr.hasNext(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.indexOf(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.isEmpty(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.lastIndexOf(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.listIterator(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.Itr.next(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.normalIndex(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.normalIndex(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.outOfBoundsMsg(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.rangeCheck(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.rangeCheckForAdd(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.read(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.read(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.readObject(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.remove(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.removeRange(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.size(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.subList(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.toArray(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.toFloatArray(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.trimToSize(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.uvIndex(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.uvIndex(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.vertexIndex(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.vertexIndex(), and eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.writeObject().
The documentation for this class was generated from the following file:
JCSG/src/main/java/eu/mihosoft/vrl/v3d/ext/openjfx/importers/obj/FloatArrayList.java