BowlerKernel: eu.mihosoft.vrl.v3d.svg.SVGExporter Class Reference
eu.mihosoft.vrl.v3d.svg.SVGExporter Class Reference
Public Member Functions
SVGExporter ()
String make ()
void makeGroup ()
Static Public Member Functions
static void export (List< Polygon > polygons, File defaultDir, boolean groupAll) throws IOException
static void export (CSG currentCsg, File defaultDir) throws IOException
static void export (List< CSG > currentCsg, File defaultDir) throws IOException
Static Public Attributes
static List< String > colorNames
Private Member Functions
void colorTick ()
void makeLayer ()
void toPolyLine (Polygon p)
void setName (String name)
Static Private Member Functions
static void write (String output, File defaultDir) throws IOException
static void addCsg (CSG currentCsg, SVGExporter svg) throws IOException
Private Attributes
String footer = "</svg>"
String section = ""
int colorTicker =0
ArrayList< String > polylines = new ArrayList<>()
ArrayList< String > groups = new ArrayList<>()
ArrayList< String > layers = new ArrayList<>()
int layerCounter = 1
int groupCounter = 1
int lineCounter =0
String name =""
Static Private Attributes
static final double Scale = 3.543307
static final double VueBoxSize = 100
Detailed Description
Definition at line 18 of file SVGExporter.java.
Constructor & Destructor Documentation
SVGExporter()
eu.mihosoft.vrl.v3d.svg.SVGExporter.SVGExporter ()
Definition at line 44 of file SVGExporter.java.
Member Function Documentation
addCsg()
static void eu.mihosoft.vrl.v3d.svg.SVGExporter.addCsg (CSG currentCsg, SVGExporter svg) throws IOException static private
Definition at line 202 of file SVGExporter.java.
References eu.mihosoft.vrl.v3d.Slice.slice().
colorTick()
void eu.mihosoft.vrl.v3d.svg.SVGExporter.colorTick () private
Definition at line 90 of file SVGExporter.java.
Referenced by eu.mihosoft.vrl.v3d.svg.SVGExporter.export().
export() [1/3]
static void eu.mihosoft.vrl.v3d.svg.SVGExporter.export (CSG currentCsg, File defaultDir) throws IOException static
Definition at line 173 of file SVGExporter.java.
References eu.mihosoft.vrl.v3d.svg.SVGExporter.make().
export() [2/3]
static void eu.mihosoft.vrl.v3d.svg.SVGExporter.export (List< CSG > currentCsg, File defaultDir) throws IOException static
Definition at line 178 of file SVGExporter.java.
References eu.mihosoft.vrl.v3d.svg.SVGExporter.make().
export() [3/3]
static void eu.mihosoft.vrl.v3d.svg.SVGExporter.export (List< Polygon > polygons, File defaultDir, boolean groupAll) throws IOException static
Definition at line 152 of file SVGExporter.java.
References eu.mihosoft.vrl.v3d.svg.SVGExporter.colorTick(), eu.mihosoft.vrl.v3d.svg.SVGExporter.make(), and eu.mihosoft.vrl.v3d.svg.SVGExporter.toPolyLine().
Referenced by com.neuronrobotics.bowlerstudio.creature.CadFileExporter.makeSvg().
make()
String eu.mihosoft.vrl.v3d.svg.SVGExporter.make ()
Definition at line 47 of file SVGExporter.java.
Referenced by eu.mihosoft.vrl.v3d.svg.SVGExporter.export(), and com.neuronrobotics.bowlerstudio.scripting.SvgLoader.getDefaultContents().
makeGroup()
void eu.mihosoft.vrl.v3d.svg.SVGExporter.makeGroup ()
Definition at line 97 of file SVGExporter.java.
makeLayer()
void eu.mihosoft.vrl.v3d.svg.SVGExporter.makeLayer () private
Definition at line 110 of file SVGExporter.java.
setName()
void eu.mihosoft.vrl.v3d.svg.SVGExporter.setName (String name) private
Definition at line 213 of file SVGExporter.java.
toPolyLine()
void eu.mihosoft.vrl.v3d.svg.SVGExporter.toPolyLine (Polygon p) private
Definition at line 129 of file SVGExporter.java.
References eu.mihosoft.vrl.v3d.Vertex.pos, eu.mihosoft.vrl.v3d.Transform.rotX(), eu.mihosoft.vrl.v3d.Vector3d.transformed(), eu.mihosoft.vrl.v3d.Polygon.vertices, eu.mihosoft.vrl.v3d.Vector3d.x(), and eu.mihosoft.vrl.v3d.Vector3d.y().
Referenced by eu.mihosoft.vrl.v3d.svg.SVGExporter.export().
write()
static void eu.mihosoft.vrl.v3d.svg.SVGExporter.write (String output, File defaultDir) throws IOException static private
Definition at line 163 of file SVGExporter.java.
Member Data Documentation
colorNames
List<String> eu.mihosoft.vrl.v3d.svg.SVGExporter.colorNames static
Initial value:
= Arrays.asList("crimson","gray","darkmagenta","darkolivegreen","darkgreen",
            "darkblue",
            "deeppink",
            "chartreuse",
            "green",
            "orange",
            "lime",
            "black",
            "tomato")
Definition at line 26 of file SVGExporter.java.
colorTicker
int eu.mihosoft.vrl.v3d.svg.SVGExporter.colorTicker =0 private
Definition at line 25 of file SVGExporter.java.
footer
String eu.mihosoft.vrl.v3d.svg.SVGExporter.footer = "</svg>" private
Definition at line 19 of file SVGExporter.java.
groupCounter
int eu.mihosoft.vrl.v3d.svg.SVGExporter.groupCounter = 1 private
Definition at line 41 of file SVGExporter.java.
groups
ArrayList<String> eu.mihosoft.vrl.v3d.svg.SVGExporter.groups = new ArrayList<>() private
Definition at line 38 of file SVGExporter.java.
layerCounter
int eu.mihosoft.vrl.v3d.svg.SVGExporter.layerCounter = 1 private
Definition at line 40 of file SVGExporter.java.
layers
ArrayList<String> eu.mihosoft.vrl.v3d.svg.SVGExporter.layers = new ArrayList<>() private
Definition at line 39 of file SVGExporter.java.
lineCounter
int eu.mihosoft.vrl.v3d.svg.SVGExporter.lineCounter =0 private
Definition at line 42 of file SVGExporter.java.
name
String eu.mihosoft.vrl.v3d.svg.SVGExporter.name ="" private
Definition at line 43 of file SVGExporter.java.
polylines
ArrayList<String> eu.mihosoft.vrl.v3d.svg.SVGExporter.polylines = new ArrayList<>() private
Definition at line 37 of file SVGExporter.java.
Scale
final double eu.mihosoft.vrl.v3d.svg.SVGExporter.Scale = 3.543307 static private
Definition at line 23 of file SVGExporter.java.
section
String eu.mihosoft.vrl.v3d.svg.SVGExporter.section = "" private
Definition at line 20 of file SVGExporter.java.
VueBoxSize
final double eu.mihosoft.vrl.v3d.svg.SVGExporter.VueBoxSize = 100 static private
Definition at line 24 of file SVGExporter.java.
The documentation for this class was generated from the following file:
JCSG/src/main/java/eu/mihosoft/vrl/v3d/svg/SVGExporter.java