BowlerKernel: eu.mihosoft.vrl.v3d.Fillet Class Reference
eu.mihosoft.vrl.v3d.Fillet Class Reference
Public Member Functions
PropertyStorage getProperties ()
Fillet (double w, double h)
List< Polygon > toPolygons ()
Public Member Functions inherited from eu.mihosoft.vrl.v3d.Primitive
CSG toCSG ()
Static Public Member Functions
static CSG corner (double rad, double angle)
static CSG outerFillet (CSG base, double rad)
static CSG outerFillet (List< Polygon > polys, double rad)
Private Attributes
final PropertyStorage properties = new PropertyStorage()
Detailed Description
Definition at line 6 of file Fillet.java.
Constructor & Destructor Documentation
Fillet()
eu.mihosoft.vrl.v3d.Fillet.Fillet (double w, double h)
Constructor. Creates a new cuboid with center
[0,0,0]
and with the specified dimensions.
Parameters
w width
h height
Definition at line 24 of file Fillet.java.
Referenced by eu.mihosoft.vrl.v3d.Fillet.outerFillet().
Member Function Documentation
corner()
static CSG eu.mihosoft.vrl.v3d.Fillet.corner (double rad, double angle) static
Definition at line 30 of file Fillet.java.
References eu.mihosoft.vrl.v3d.CSG.difference(), eu.mihosoft.vrl.v3d.Extrude.revolve(), eu.mihosoft.vrl.v3d.Primitive.toCSG(), and eu.mihosoft.vrl.v3d.CSG.unionAll().
Referenced by eu.mihosoft.vrl.v3d.Fillet.outerFillet().
getProperties()
PropertyStorage eu.mihosoft.vrl.v3d.Fillet.getProperties ()
Returns the property storage of this primitive.
Returns
the property storage of this primitive
Reimplemented from eu.mihosoft.vrl.v3d.Primitive.
Definition at line 13 of file Fillet.java.
References eu.mihosoft.vrl.v3d.Fillet.properties.
outerFillet() [1/2]
static CSG eu.mihosoft.vrl.v3d.Fillet.outerFillet (CSG base, double rad) static
Definition at line 36 of file Fillet.java.
References eu.mihosoft.vrl.v3d.Slice.slice(), and eu.mihosoft.vrl.v3d.CSG.union().
outerFillet() [2/2]
static CSG eu.mihosoft.vrl.v3d.Fillet.outerFillet (List< Polygon > polys, double rad) static
Definition at line 41 of file Fillet.java.
References eu.mihosoft.vrl.v3d.Vector3d.angle(), eu.mihosoft.vrl.v3d.Fillet.corner(), eu.mihosoft.vrl.v3d.Fillet.Fillet(), eu.mihosoft.vrl.v3d.Vector3d.magnitude(), eu.mihosoft.vrl.v3d.Vector3d.minus(), eu.mihosoft.vrl.v3d.CSG.move(), eu.mihosoft.vrl.v3d.CSG.rotz(), eu.mihosoft.vrl.v3d.CSG.unionAll(), eu.mihosoft.vrl.v3d.Vector3d.x(), and eu.mihosoft.vrl.v3d.Vector3d.Y_ONE.
toPolygons()
List<Polygon> eu.mihosoft.vrl.v3d.Fillet.toPolygons ()
Returns the polygons that define this primitive.
Note: this method computes the polygons each time this method is called. The polygons can be cached inside a CSG object.
Returns
a list of polygons that define this primitive
Reimplemented from eu.mihosoft.vrl.v3d.Primitive.
Definition at line 85 of file Fillet.java.
References eu.mihosoft.vrl.v3d.CSG.difference(), eu.mihosoft.vrl.v3d.CSG.getPolygons(), eu.mihosoft.vrl.v3d.CSG.movey(), eu.mihosoft.vrl.v3d.CSG.rotx(), eu.mihosoft.vrl.v3d.Primitive.toCSG(), eu.mihosoft.vrl.v3d.CSG.toXMin(), eu.mihosoft.vrl.v3d.CSG.toYMin(), and eu.mihosoft.vrl.v3d.CSG.toZMin().
Member Data Documentation
properties
final PropertyStorage eu.mihosoft.vrl.v3d.Fillet.properties = new PropertyStorage() private
The properties.
Definition at line 11 of file Fillet.java.
Referenced by eu.mihosoft.vrl.v3d.Fillet.getProperties().
The documentation for this class was generated from the following file:
JCSG/src/main/java/eu/mihosoft/vrl/v3d/Fillet.java