BowlerKernel: com.neuronrobotics.sdk.addons.kinematics.PidRotoryLink Class Reference
com.neuronrobotics.sdk.addons.kinematics.PidRotoryLink Class Reference
Public Member Functions
PidRotoryLink (PIDChannel c, LinkConfiguration conf, boolean b)
void cacheTargetValueDevice ()
void flushDevice (double time)
void flushAllDevice (double time)
double getCurrentPosition ()
void setPIDChannel (PIDChannel channel)
PIDChannel getPIDChannel ()
Public Member Functions inherited from com.neuronrobotics.sdk.addons.kinematics.AbstractRotoryLink
AbstractRotoryLink (LinkConfiguration conf)
void incrementAngle (double inc)
void setTargetAngle (double pos)
void setCurrentAsAngle (double angle)
double getCurrentAngle ()
double getTargetAngle ()
double getMaxAngle ()
double getMinAngle ()
boolean isMaxAngle ()
boolean isMinAngle ()
Public Member Functions inherited from com.neuronrobotics.sdk.addons.kinematics.AbstractLink
double getDeviceMaximumValue ()
double getDeviceMinimumValue ()
void setDeviceMaximumValue (double max)
void setDeviceMinimumValue (double min)
double getDeviceMaxEngineeringUnits ()
double getDeviceMinEngineeringUnits ()
AbstractLink (LinkConfiguration conf)
void cacheTargetValue ()
void flush (double time)
void flushAll (double time)
double toEngineeringUnits (double value)
double toLinkUnits (double euValue)
void addLinkListener (ILinkListener l)
void removeLinkListener (ILinkListener l)
void fireLinkListener (double linkUnitsValue)
void fireLinkLimitEvent (PIDLimitEvent e)
void Home ()
void incrementEngineeringUnits (double inc)
void setTargetEngineeringUnits (double pos)
void setCurrentEngineeringUnits (double angle)
double getCurrentEngineeringUnits ()
double getTargetEngineeringUnits ()
double getMaxEngineeringUnits ()
double getMinEngineeringUnits ()
void setMinEngineeringUnits (double minLimit)
void setMaxEngineeringUnits (double maxLimit)
double getMaxVelocityEngineeringUnits ()
void setMaxVelocityEngineeringUnits (double max)
boolean isMaxEngineeringUnits ()
boolean isMinEngineeringUnits ()
double getTargetValue ()
void setUpperLimit (int upperLimit)
void setLowerLimit (int lowerLimit)
void setHome (int home)
void setScale (double d)
double getScale ()
double getUpperLimit ()
double getLowerLimit ()
double getHome ()
void setCurrentAsUpperLimit ()
void setCurrentAsLowerLimit ()
void setUseLimits (boolean useLimits)
boolean isUseLimits ()
void setLinkConfiguration (LinkConfiguration conf)
LinkConfiguration getLinkConfiguration ()
ArrayList< ILinkListener > getLinks ()
void setLinks (ArrayList< ILinkListener > links)
void removeAllLinkListener ()
void setGlobalPositionListener (Object Object)
Object getGlobalPositionListener ()
LinkFactory getSlaveFactory ()
void setSlaveFactory (LinkFactory slaveFactory)
IMU getImu ()
void addChangeListener (ILinkConfigurationChangeListener l)
void removeChangeListener (ILinkConfigurationChangeListener l)
void clearChangeListener ()
Private Attributes
PIDChannel channel
Additional Inherited Members
Protected Member Functions inherited from com.neuronrobotics.sdk.addons.kinematics.AbstractLink
void setPosition (double val)
void setTargetValue (double val)
Detailed Description
The Class PidRotoryLink.
Definition at line 12 of file PidRotoryLink.java.
Constructor & Destructor Documentation
PidRotoryLink()
com.neuronrobotics.sdk.addons.kinematics.PidRotoryLink.PidRotoryLink (PIDChannel c, LinkConfiguration conf, boolean b)
Instantiates a new pid rotory link.
Parameters
c the c
conf the conf
b
Definition at line 24 of file PidRotoryLink.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractLink.conf, com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setDeviceTheoreticalMax(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setDeviceTheoreticalMin(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setPauseEvents(), and com.neuronrobotics.sdk.addons.kinematics.PidRotoryLink.setPIDChannel().
Member Function Documentation
cacheTargetValueDevice()
void com.neuronrobotics.sdk.addons.kinematics.PidRotoryLink.cacheTargetValueDevice ()
This method is called in order to take the target value and pass it to the implementation's target value This method should not alter the position of the implementations link If the implementation target does not handle chached values, this should be chached in code.
Reimplemented from com.neuronrobotics.sdk.addons.kinematics.AbstractLink.
Definition at line 42 of file PidRotoryLink.java.
References com.neuronrobotics.sdk.addons.kinematics.PidRotoryLink.channel, com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getTargetValue(), and com.neuronrobotics.sdk.pid.PIDChannel.setCachedTargetValue().
flushAllDevice()
void com.neuronrobotics.sdk.addons.kinematics.PidRotoryLink.flushAllDevice (double time)
This method will force one link to update its position in the given time (seconds) This will also flush the host controller.
Parameters
time (seconds) for the position update to take
Reimplemented from com.neuronrobotics.sdk.addons.kinematics.AbstractLink.
Definition at line 59 of file PidRotoryLink.java.
References com.neuronrobotics.sdk.addons.kinematics.PidRotoryLink.channel, com.neuronrobotics.sdk.addons.kinematics.AbstractLink.fireLinkListener(), com.neuronrobotics.sdk.namespace.bcs.pid.IPidControlNamespace.flushPIDChannels(), com.neuronrobotics.sdk.addons.kinematics.PidRotoryLink.getCurrentPosition(), and com.neuronrobotics.sdk.pid.PIDChannel.getPid().
flushDevice()
void com.neuronrobotics.sdk.addons.kinematics.PidRotoryLink.flushDevice (double time)
This method will force one link to update its position in the given time (seconds).
Parameters
time (seconds) for the position update to take
Reimplemented from com.neuronrobotics.sdk.addons.kinematics.AbstractLink.
Definition at line 50 of file PidRotoryLink.java.
References com.neuronrobotics.sdk.addons.kinematics.PidRotoryLink.channel, com.neuronrobotics.sdk.addons.kinematics.AbstractLink.fireLinkListener(), com.neuronrobotics.sdk.pid.PIDChannel.flush(), and com.neuronrobotics.sdk.addons.kinematics.PidRotoryLink.getCurrentPosition().
getCurrentPosition()
double com.neuronrobotics.sdk.addons.kinematics.PidRotoryLink.getCurrentPosition ()
This method should return the current position of the link This method is expected to perform a communication with the device .
Returns
the current position of the link
Reimplemented from com.neuronrobotics.sdk.addons.kinematics.AbstractLink.
Definition at line 68 of file PidRotoryLink.java.
References com.neuronrobotics.sdk.addons.kinematics.PidRotoryLink.channel, and com.neuronrobotics.sdk.pid.PIDChannel.GetPIDPosition().
Referenced by com.neuronrobotics.sdk.addons.kinematics.PidRotoryLink.flushAllDevice(), and com.neuronrobotics.sdk.addons.kinematics.PidRotoryLink.flushDevice().
getPIDChannel()
PIDChannel com.neuronrobotics.sdk.addons.kinematics.PidRotoryLink.getPIDChannel ()
Gets the PID channel.
Returns
the PID channel
Definition at line 105 of file PidRotoryLink.java.
References com.neuronrobotics.sdk.addons.kinematics.PidRotoryLink.channel.
setPIDChannel()
void com.neuronrobotics.sdk.addons.kinematics.PidRotoryLink.setPIDChannel (PIDChannel channel)
Sets the PID channel.
Parameters
channel the new PID channel
Definition at line 79 of file PidRotoryLink.java.
References com.neuronrobotics.sdk.pid.PIDChannel.addPIDEventListener(), com.neuronrobotics.sdk.addons.kinematics.PidRotoryLink.channel, com.neuronrobotics.sdk.addons.kinematics.AbstractLink.fireLinkLimitEvent(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.fireLinkListener(), and com.neuronrobotics.sdk.pid.PIDEvent.getValue().
Referenced by com.neuronrobotics.sdk.addons.kinematics.PidRotoryLink.PidRotoryLink().
Member Data Documentation
channel
PIDChannel com.neuronrobotics.sdk.addons.kinematics.PidRotoryLink.channel private
The channel.
Definition at line 15 of file PidRotoryLink.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.PidRotoryLink.cacheTargetValueDevice(), com.neuronrobotics.sdk.addons.kinematics.PidRotoryLink.flushAllDevice(), com.neuronrobotics.sdk.addons.kinematics.PidRotoryLink.flushDevice(), com.neuronrobotics.sdk.addons.kinematics.PidRotoryLink.getCurrentPosition(), com.neuronrobotics.sdk.addons.kinematics.PidRotoryLink.getPIDChannel(), and com.neuronrobotics.sdk.addons.kinematics.PidRotoryLink.setPIDChannel().
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/addons/kinematics/PidRotoryLink.java