BowlerKernel: com.neuronrobotics.sdk.config.SDKBuildInfo Class Reference
com.neuronrobotics.sdk.config.SDKBuildInfo Class Reference
Static Public Member Functions
static String getVersion ()
static int getProtocolVersion ()
static int getSDKVersion ()
static int getBuildVersion ()
static int[] getBuildInfo ()
static String getBuildDate ()
static String getSDKVersionString ()
static boolean isOS64bit ()
static boolean isARM ()
static boolean isLinux ()
static boolean isWindows ()
static boolean isMac ()
static boolean isUnix ()
Static Private Member Functions
static String getTag (String target)
static InputStream getBuildPropertiesStream ()
Static Private Attributes
static final String NAME
Detailed Description
The Class SDKBuildInfo.
Definition at line 12 of file SDKBuildInfo.java.
Member Function Documentation
getBuildDate()
static String com.neuronrobotics.sdk.config.SDKBuildInfo.getBuildDate () static
Gets the builds the date.
Returns
the builds the date
Definition at line 108 of file SDKBuildInfo.java.
getBuildInfo()
static int [] com.neuronrobotics.sdk.config.SDKBuildInfo.getBuildInfo () static
Gets the builds the info.
Returns
the builds the info
Definition at line 62 of file SDKBuildInfo.java.
References com.neuronrobotics.sdk.config.SDKBuildInfo.getVersion().
Referenced by com.neuronrobotics.sdk.dyio.DyIO.checkFirmwareRev(), com.neuronrobotics.sdk.config.SDKBuildInfo.getBuildVersion(), com.neuronrobotics.sdk.config.SDKBuildInfo.getProtocolVersion(), and com.neuronrobotics.sdk.config.SDKBuildInfo.getSDKVersion().
getBuildPropertiesStream()
static InputStream com.neuronrobotics.sdk.config.SDKBuildInfo.getBuildPropertiesStream () static private
Gets the builds the properties stream.
Returns
the builds the properties stream
Definition at line 129 of file SDKBuildInfo.java.
Referenced by com.neuronrobotics.sdk.config.SDKBuildInfo.getTag().
getBuildVersion()
static int com.neuronrobotics.sdk.config.SDKBuildInfo.getBuildVersion () static
Gets the builds the version.
Returns
the builds the version
Definition at line 53 of file SDKBuildInfo.java.
References com.neuronrobotics.sdk.config.SDKBuildInfo.getBuildInfo().
getProtocolVersion()
static int com.neuronrobotics.sdk.config.SDKBuildInfo.getProtocolVersion () static
Gets the protocol version.
Returns
the protocol version
Definition at line 35 of file SDKBuildInfo.java.
References com.neuronrobotics.sdk.config.SDKBuildInfo.getBuildInfo().
getSDKVersion()
static int com.neuronrobotics.sdk.config.SDKBuildInfo.getSDKVersion () static
Gets the SDK version.
Returns
the SDK version
Definition at line 44 of file SDKBuildInfo.java.
References com.neuronrobotics.sdk.config.SDKBuildInfo.getBuildInfo().
getSDKVersionString()
static String com.neuronrobotics.sdk.config.SDKBuildInfo.getSDKVersionString () static
Gets the SDK version string.
Returns
the SDK version string
Definition at line 138 of file SDKBuildInfo.java.
References com.neuronrobotics.sdk.config.SDKBuildInfo.NAME.
Referenced by com.neuronrobotics.sdk.common.Log.Log().
getTag()
static String com.neuronrobotics.sdk.config.SDKBuildInfo.getTag (String target) static private
Gets the tag.
Parameters
target the target
Returns
the tag
Definition at line 78 of file SDKBuildInfo.java.
References com.neuronrobotics.sdk.config.SDKBuildInfo.getBuildPropertiesStream().
Referenced by com.neuronrobotics.sdk.config.SDKBuildInfo.getVersion().
getVersion()
static String com.neuronrobotics.sdk.config.SDKBuildInfo.getVersion () static
Gets the version.
Returns
the version
Definition at line 23 of file SDKBuildInfo.java.
References com.neuronrobotics.sdk.config.SDKBuildInfo.getTag().
Referenced by com.neuronrobotics.bowlerstudio.IssueReportingExceptionHandler.except(), and com.neuronrobotics.sdk.config.SDKBuildInfo.getBuildInfo().
isARM()
static boolean com.neuronrobotics.sdk.config.SDKBuildInfo.isARM () static
Checks if is arm.
Returns
true, if is arm
Definition at line 156 of file SDKBuildInfo.java.
isLinux()
static boolean com.neuronrobotics.sdk.config.SDKBuildInfo.isLinux () static
Checks if is linux.
Returns
true, if is linux
Definition at line 165 of file SDKBuildInfo.java.
Referenced by com.neuronrobotics.sdk.config.SDKBuildInfo.isUnix().
isMac()
static boolean com.neuronrobotics.sdk.config.SDKBuildInfo.isMac () static
Checks if is mac.
Returns
true, if is mac
Definition at line 183 of file SDKBuildInfo.java.
Referenced by com.neuronrobotics.sdk.config.SDKBuildInfo.isUnix().
isOS64bit()
static boolean com.neuronrobotics.sdk.config.SDKBuildInfo.isOS64bit () static
Checks if is o s64bit.
Returns
true, if is o s64bit
Definition at line 147 of file SDKBuildInfo.java.
isUnix()
static boolean com.neuronrobotics.sdk.config.SDKBuildInfo.isUnix () static
Checks if is unix.
Returns
true, if is unix
Definition at line 192 of file SDKBuildInfo.java.
References com.neuronrobotics.sdk.config.SDKBuildInfo.isLinux(), and com.neuronrobotics.sdk.config.SDKBuildInfo.isMac().
isWindows()
static boolean com.neuronrobotics.sdk.config.SDKBuildInfo.isWindows () static
Checks if is windows.
Returns
true, if is windows
Definition at line 174 of file SDKBuildInfo.java.
Member Data Documentation
NAME
final String com.neuronrobotics.sdk.config.SDKBuildInfo.NAME static private
Initial value:
= "Neuron Robotics SDK "
            + getProtocolVersion() + "." + getSDKVersion() + "("
            + getBuildVersion() + ")"
The Constant NAME.
Definition at line 14 of file SDKBuildInfo.java.
Referenced by com.neuronrobotics.sdk.config.SDKBuildInfo.getSDKVersionString().
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/config/SDKBuildInfo.java