BowlerKernel: com.neuronrobotics.bowlerstudio.sequence.TimeSequence Class Reference
com.neuronrobotics.bowlerstudio.sequence.TimeSequence Class Reference
Public Member Functions
void execute (String content) throws Exception
void runSequence () throws Exception
void load (String content)
HashMap< String, SequenceEvent > getSequence (String d)
String save ()
ArrayList< String > getDevicesInSequence ()
void setDevicesInSequence (ArrayList< String > devicesInSequence)
long getDuration ()
void setDuration (long duration)
String getWavfile ()
void setWavfile (String wavfile)
String getWavurl ()
void setWavurl (String wavurl)
String getFile ()
void setFile (String file)
String getUrl ()
void setUrl (String url)
HashMap< String, Object > getInitialize ()
void setInitialize (HashMap< String, Object > initialize)
HashMap< String, Object > getDatabase ()
void setDatabase (HashMap< String, Object > database)
Static Public Member Functions
static HashMap< String, AbstractKinematicsNR > getDevices ()
Private Member Functions
void addWavFileRun (ArrayList< Thread > threads) throws InvalidRemoteException, TransportException, GitAPIException, IOException, UnsupportedAudioFileException, LineUnavailableException
String getDevice (String d)
Static Private Member Functions
static void loadMobileBase (HashMap< String, AbstractKinematicsNR > map, MobileBase specificDevice2, int depth)
Private Attributes
Gson gson = new GsonBuilder().disableHtmlEscaping().setPrettyPrinting().create()
HashMap< String, Object > database
HashMap< String, Object > initialize
String url
String file
String wavurl
String wavfile
long duration
ArrayList< String > devicesInSequence
Static Private Attributes
static Type TT_mapStringString
static Type TT_listString
static Type TT_SequenceEvent
static Type TT_mapSequence
Detailed Description
Definition at line 31 of file TimeSequence.java.
Member Function Documentation
addWavFileRun()
void com.neuronrobotics.bowlerstudio.sequence.TimeSequence.addWavFileRun (ArrayList< Thread > threads) throws InvalidRemoteException, TransportException, GitAPIException, IOException, UnsupportedAudioFileException, LineUnavailableException private
Definition at line 142 of file TimeSequence.java.
References com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.fileFromGit(), com.neuronrobotics.bowlerstudio.sequence.TimeSequence.getDuration(), com.neuronrobotics.bowlerstudio.sequence.TimeSequence.getWavfile(), com.neuronrobotics.bowlerstudio.sequence.TimeSequence.getWavurl(), com.neuronrobotics.bowlerstudio.sequence.TimeSequence.setDuration(), and com.neuronrobotics.sdk.util.ThreadUtil.wait().
Referenced by com.neuronrobotics.bowlerstudio.sequence.TimeSequence.runSequence().
execute()
void com.neuronrobotics.bowlerstudio.sequence.TimeSequence.execute (String content) throws Exception
Definition at line 85 of file TimeSequence.java.
References com.neuronrobotics.bowlerstudio.sequence.TimeSequence.load(), and com.neuronrobotics.bowlerstudio.sequence.TimeSequence.runSequence().
Referenced by com.neuronrobotics.bowlerstudio.scripting.SequenceRunner.inlineScriptRun().
getDatabase()
HashMap<String, Object> com.neuronrobotics.bowlerstudio.sequence.TimeSequence.getDatabase ()
Definition at line 281 of file TimeSequence.java.
References com.neuronrobotics.bowlerstudio.sequence.TimeSequence.database.
Referenced by com.neuronrobotics.bowlerstudio.sequence.TimeSequence.getSequence(), com.neuronrobotics.bowlerstudio.sequence.TimeSequence.load(), and com.neuronrobotics.bowlerstudio.sequence.TimeSequence.save().
getDevice()
String com.neuronrobotics.bowlerstudio.sequence.TimeSequence.getDevice (String d) private
Definition at line 210 of file TimeSequence.java.
References com.neuronrobotics.bowlerstudio.sequence.TimeSequence.devicesInSequence.
Referenced by com.neuronrobotics.bowlerstudio.sequence.TimeSequence.getSequence().
getDevices()
static HashMap<String, AbstractKinematicsNR> com.neuronrobotics.bowlerstudio.sequence.TimeSequence.getDevices () static
Definition at line 53 of file TimeSequence.java.
References com.neuronrobotics.sdk.common.DeviceManager.getSpecificDevice(), com.neuronrobotics.sdk.common.DeviceManager.listConnectedDevice(), and com.neuronrobotics.bowlerstudio.sequence.TimeSequence.loadMobileBase().
Referenced by com.neuronrobotics.bowlerstudio.sequence.TimeSequence.runSequence().
getDevicesInSequence()
ArrayList<String> com.neuronrobotics.bowlerstudio.sequence.TimeSequence.getDevicesInSequence ()
Definition at line 223 of file TimeSequence.java.
References com.neuronrobotics.bowlerstudio.sequence.TimeSequence.devicesInSequence.
Referenced by com.neuronrobotics.bowlerstudio.sequence.TimeSequence.runSequence().
getDuration()
long com.neuronrobotics.bowlerstudio.sequence.TimeSequence.getDuration ()
Definition at line 232 of file TimeSequence.java.
References com.neuronrobotics.bowlerstudio.sequence.TimeSequence.duration.
Referenced by com.neuronrobotics.bowlerstudio.sequence.TimeSequence.addWavFileRun(), and com.neuronrobotics.bowlerstudio.sequence.TimeSequence.runSequence().
getFile()
String com.neuronrobotics.bowlerstudio.sequence.TimeSequence.getFile ()
Definition at line 256 of file TimeSequence.java.
References com.neuronrobotics.bowlerstudio.sequence.TimeSequence.file.
Referenced by com.neuronrobotics.bowlerstudio.sequence.TimeSequence.runSequence().
getInitialize()
HashMap<String, Object> com.neuronrobotics.bowlerstudio.sequence.TimeSequence.getInitialize ()
Definition at line 272 of file TimeSequence.java.
References com.neuronrobotics.bowlerstudio.sequence.TimeSequence.initialize.
Referenced by com.neuronrobotics.bowlerstudio.sequence.TimeSequence.load().
getSequence()
HashMap<String, SequenceEvent> com.neuronrobotics.bowlerstudio.sequence.TimeSequence.getSequence (String d)
Definition at line 199 of file TimeSequence.java.
References com.neuronrobotics.bowlerstudio.sequence.TimeSequence.getDatabase(), com.neuronrobotics.bowlerstudio.sequence.TimeSequence.getDevice(), com.neuronrobotics.bowlerstudio.sequence.TimeSequence.gson, and com.neuronrobotics.bowlerstudio.sequence.TimeSequence.TT_mapSequence.
Referenced by com.neuronrobotics.bowlerstudio.sequence.TimeSequence.load(), and com.neuronrobotics.bowlerstudio.sequence.TimeSequence.runSequence().
getUrl()
String com.neuronrobotics.bowlerstudio.sequence.TimeSequence.getUrl ()
Definition at line 264 of file TimeSequence.java.
References com.neuronrobotics.bowlerstudio.sequence.TimeSequence.url.
Referenced by com.neuronrobotics.bowlerstudio.sequence.TimeSequence.runSequence().
getWavfile()
String com.neuronrobotics.bowlerstudio.sequence.TimeSequence.getWavfile ()
Definition at line 240 of file TimeSequence.java.
References com.neuronrobotics.bowlerstudio.sequence.TimeSequence.wavfile.
Referenced by com.neuronrobotics.bowlerstudio.sequence.TimeSequence.addWavFileRun(), and com.neuronrobotics.bowlerstudio.sequence.TimeSequence.runSequence().
getWavurl()
String com.neuronrobotics.bowlerstudio.sequence.TimeSequence.getWavurl ()
Definition at line 248 of file TimeSequence.java.
References com.neuronrobotics.bowlerstudio.sequence.TimeSequence.wavurl.
Referenced by com.neuronrobotics.bowlerstudio.sequence.TimeSequence.addWavFileRun(), and com.neuronrobotics.bowlerstudio.sequence.TimeSequence.runSequence().
load()
void com.neuronrobotics.bowlerstudio.sequence.TimeSequence.load (String content)
Definition at line 183 of file TimeSequence.java.
References com.neuronrobotics.bowlerstudio.sequence.TimeSequence.devicesInSequence, com.neuronrobotics.bowlerstudio.sequence.TimeSequence.getDatabase(), com.neuronrobotics.bowlerstudio.sequence.TimeSequence.getInitialize(), com.neuronrobotics.bowlerstudio.sequence.TimeSequence.getSequence(), com.neuronrobotics.bowlerstudio.sequence.TimeSequence.gson, com.neuronrobotics.bowlerstudio.sequence.TimeSequence.setDatabase(), com.neuronrobotics.bowlerstudio.sequence.TimeSequence.setDevicesInSequence(), com.neuronrobotics.bowlerstudio.sequence.TimeSequence.setDuration(), com.neuronrobotics.bowlerstudio.sequence.TimeSequence.setFile(), com.neuronrobotics.bowlerstudio.sequence.TimeSequence.setInitialize(), com.neuronrobotics.bowlerstudio.sequence.TimeSequence.setUrl(), com.neuronrobotics.bowlerstudio.sequence.TimeSequence.setWavfile(), com.neuronrobotics.bowlerstudio.sequence.TimeSequence.setWavurl(), com.neuronrobotics.bowlerstudio.sequence.TimeSequence.TT_listString, and com.neuronrobotics.bowlerstudio.sequence.TimeSequence.TT_mapStringString.
Referenced by com.neuronrobotics.bowlerstudio.sequence.TimeSequence.execute().
loadMobileBase()
static void com.neuronrobotics.bowlerstudio.sequence.TimeSequence.loadMobileBase (HashMap< String, AbstractKinematicsNR > map, MobileBase specificDevice2, int depth) static private
Definition at line 65 of file TimeSequence.java.
References com.neuronrobotics.sdk.addons.kinematics.MobileBase.getAllDHChains(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.getAllParallelGroups(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.getParallelGroup(), and com.neuronrobotics.sdk.common.BowlerAbstractDevice.getScriptingName().
Referenced by com.neuronrobotics.bowlerstudio.sequence.TimeSequence.getDevices().
runSequence()
void com.neuronrobotics.bowlerstudio.sequence.TimeSequence.runSequence () throws Exception
Definition at line 92 of file TimeSequence.java.
References com.neuronrobotics.bowlerstudio.sequence.TimeSequence.addWavFileRun(), com.neuronrobotics.bowlerstudio.sequence.SequenceEvent.execute(), com.neuronrobotics.bowlerstudio.sequence.TimeSequence.getDevices(), com.neuronrobotics.bowlerstudio.sequence.TimeSequence.getDevicesInSequence(), com.neuronrobotics.bowlerstudio.sequence.TimeSequence.getDuration(), com.neuronrobotics.bowlerstudio.sequence.TimeSequence.getFile(), com.neuronrobotics.bowlerstudio.sequence.TimeSequence.getSequence(), com.neuronrobotics.bowlerstudio.sequence.TimeSequence.getUrl(), com.neuronrobotics.bowlerstudio.sequence.TimeSequence.getWavfile(), com.neuronrobotics.bowlerstudio.sequence.TimeSequence.getWavurl(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.gitScriptRun().
Referenced by com.neuronrobotics.bowlerstudio.sequence.TimeSequence.execute().
save()
String com.neuronrobotics.bowlerstudio.sequence.TimeSequence.save ()
Definition at line 219 of file TimeSequence.java.
References com.neuronrobotics.bowlerstudio.sequence.TimeSequence.getDatabase(), and com.neuronrobotics.bowlerstudio.sequence.TimeSequence.gson.
setDatabase()
void com.neuronrobotics.bowlerstudio.sequence.TimeSequence.setDatabase (HashMap< String, Object > database)
Definition at line 285 of file TimeSequence.java.
References com.neuronrobotics.bowlerstudio.sequence.TimeSequence.database.
Referenced by com.neuronrobotics.bowlerstudio.sequence.TimeSequence.load().
setDevicesInSequence()
void com.neuronrobotics.bowlerstudio.sequence.TimeSequence.setDevicesInSequence (ArrayList< String > devicesInSequence)
Definition at line 227 of file TimeSequence.java.
References com.neuronrobotics.bowlerstudio.sequence.TimeSequence.devicesInSequence, and com.neuronrobotics.bowlerstudio.sequence.TimeSequence.initialize.
Referenced by com.neuronrobotics.bowlerstudio.sequence.TimeSequence.load().
setDuration()
void com.neuronrobotics.bowlerstudio.sequence.TimeSequence.setDuration (long duration)
Definition at line 236 of file TimeSequence.java.
References com.neuronrobotics.bowlerstudio.sequence.TimeSequence.duration.
Referenced by com.neuronrobotics.bowlerstudio.sequence.TimeSequence.addWavFileRun(), and com.neuronrobotics.bowlerstudio.sequence.TimeSequence.load().
setFile()
void com.neuronrobotics.bowlerstudio.sequence.TimeSequence.setFile (String file)
Definition at line 260 of file TimeSequence.java.
References com.neuronrobotics.bowlerstudio.sequence.TimeSequence.file.
Referenced by com.neuronrobotics.bowlerstudio.sequence.TimeSequence.load().
setInitialize()
void com.neuronrobotics.bowlerstudio.sequence.TimeSequence.setInitialize (HashMap< String, Object > initialize)
Definition at line 276 of file TimeSequence.java.
References com.neuronrobotics.bowlerstudio.sequence.TimeSequence.database, and com.neuronrobotics.bowlerstudio.sequence.TimeSequence.initialize.
Referenced by com.neuronrobotics.bowlerstudio.sequence.TimeSequence.load().
setUrl()
void com.neuronrobotics.bowlerstudio.sequence.TimeSequence.setUrl (String url)
Definition at line 268 of file TimeSequence.java.
References com.neuronrobotics.bowlerstudio.sequence.TimeSequence.url.
Referenced by com.neuronrobotics.bowlerstudio.sequence.TimeSequence.load().
setWavfile()
void com.neuronrobotics.bowlerstudio.sequence.TimeSequence.setWavfile (String wavfile)
Definition at line 244 of file TimeSequence.java.
References com.neuronrobotics.bowlerstudio.sequence.TimeSequence.wavfile.
Referenced by com.neuronrobotics.bowlerstudio.sequence.TimeSequence.load().
setWavurl()
void com.neuronrobotics.bowlerstudio.sequence.TimeSequence.setWavurl (String wavurl)
Definition at line 252 of file TimeSequence.java.
References com.neuronrobotics.bowlerstudio.sequence.TimeSequence.wavurl.
Referenced by com.neuronrobotics.bowlerstudio.sequence.TimeSequence.load().
Member Data Documentation
database
HashMap<String, Object> com.neuronrobotics.bowlerstudio.sequence.TimeSequence.database private
Definition at line 44 of file TimeSequence.java.
Referenced by com.neuronrobotics.bowlerstudio.sequence.TimeSequence.getDatabase(), com.neuronrobotics.bowlerstudio.sequence.TimeSequence.setDatabase(), and com.neuronrobotics.bowlerstudio.sequence.TimeSequence.setInitialize().
devicesInSequence
ArrayList<String> com.neuronrobotics.bowlerstudio.sequence.TimeSequence.devicesInSequence private
Definition at line 51 of file TimeSequence.java.
Referenced by com.neuronrobotics.bowlerstudio.sequence.TimeSequence.getDevice(), com.neuronrobotics.bowlerstudio.sequence.TimeSequence.getDevicesInSequence(), com.neuronrobotics.bowlerstudio.sequence.TimeSequence.load(), and com.neuronrobotics.bowlerstudio.sequence.TimeSequence.setDevicesInSequence().
duration
long com.neuronrobotics.bowlerstudio.sequence.TimeSequence.duration private
Definition at line 50 of file TimeSequence.java.
Referenced by com.neuronrobotics.bowlerstudio.sequence.TimeSequence.getDuration(), and com.neuronrobotics.bowlerstudio.sequence.TimeSequence.setDuration().
file
String com.neuronrobotics.bowlerstudio.sequence.TimeSequence.file private
Definition at line 47 of file TimeSequence.java.
Referenced by com.neuronrobotics.bowlerstudio.sequence.TimeSequence.getFile(), and com.neuronrobotics.bowlerstudio.sequence.TimeSequence.setFile().
gson
Gson com.neuronrobotics.bowlerstudio.sequence.TimeSequence.gson = new GsonBuilder().disableHtmlEscaping().setPrettyPrinting().create() private
Definition at line 43 of file TimeSequence.java.
Referenced by com.neuronrobotics.bowlerstudio.sequence.TimeSequence.getSequence(), com.neuronrobotics.bowlerstudio.sequence.TimeSequence.load(), and com.neuronrobotics.bowlerstudio.sequence.TimeSequence.save().
initialize
HashMap<String, Object> com.neuronrobotics.bowlerstudio.sequence.TimeSequence.initialize private
Definition at line 45 of file TimeSequence.java.
Referenced by com.neuronrobotics.bowlerstudio.sequence.TimeSequence.getInitialize(), com.neuronrobotics.bowlerstudio.sequence.TimeSequence.setDevicesInSequence(), and com.neuronrobotics.bowlerstudio.sequence.TimeSequence.setInitialize().
TT_listString
Type com.neuronrobotics.bowlerstudio.sequence.TimeSequence.TT_listString static private
Initial value:
= new TypeToken<ArrayList<String>>() {
    }.getType()
Definition at line 36 of file TimeSequence.java.
Referenced by com.neuronrobotics.bowlerstudio.sequence.TimeSequence.load().
TT_mapSequence
Type com.neuronrobotics.bowlerstudio.sequence.TimeSequence.TT_mapSequence static private
Initial value:
= new TypeToken<HashMap<String, SequenceEvent>>() {
    }.getType()
Definition at line 40 of file TimeSequence.java.
Referenced by com.neuronrobotics.bowlerstudio.sequence.TimeSequence.getSequence().
TT_mapStringString
Type com.neuronrobotics.bowlerstudio.sequence.TimeSequence.TT_mapStringString static private
Initial value:
= new TypeToken<HashMap<String, Object>>() {
    }.getType()
Definition at line 34 of file TimeSequence.java.
Referenced by com.neuronrobotics.bowlerstudio.sequence.TimeSequence.load().
TT_SequenceEvent
Type com.neuronrobotics.bowlerstudio.sequence.TimeSequence.TT_SequenceEvent static private
Initial value:
= new TypeToken<SequenceEvent>() {
    }.getType()
Definition at line 38 of file TimeSequence.java.
url
String com.neuronrobotics.bowlerstudio.sequence.TimeSequence.url private
Definition at line 46 of file TimeSequence.java.
Referenced by com.neuronrobotics.bowlerstudio.sequence.TimeSequence.getUrl(), and com.neuronrobotics.bowlerstudio.sequence.TimeSequence.setUrl().
wavfile
String com.neuronrobotics.bowlerstudio.sequence.TimeSequence.wavfile private
Definition at line 49 of file TimeSequence.java.
Referenced by com.neuronrobotics.bowlerstudio.sequence.TimeSequence.getWavfile(), and com.neuronrobotics.bowlerstudio.sequence.TimeSequence.setWavfile().
wavurl
String com.neuronrobotics.bowlerstudio.sequence.TimeSequence.wavurl private
Definition at line 48 of file TimeSequence.java.
Referenced by com.neuronrobotics.bowlerstudio.sequence.TimeSequence.getWavurl(), and com.neuronrobotics.bowlerstudio.sequence.TimeSequence.setWavurl().
The documentation for this class was generated from the following file:
src/main/java/com/neuronrobotics/bowlerstudio/sequence/TimeSequence.java