BowlerKernel: com.neuronrobotics.sdk.genericdevice.GenericDevice Class Reference
com.neuronrobotics.sdk.genericdevice.GenericDevice Class Reference
Public Member Functions
GenericDevice (BowlerAbstractConnection connection)
boolean isAvailable () throws InvalidConnectionException
void onAllResponse (BowlerDatagram data)
void onAsyncResponse (BowlerDatagram data)
Public Member Functions inherited from com.neuronrobotics.sdk.common.BowlerAbstractDevice
void addConnectionEventListener (final IDeviceConnectionEventListener l)
void removeConnectionEventListener (IDeviceConnectionEventListener l)
void setConnection (BowlerAbstractConnection connection)
boolean connect () throws InvalidConnectionException
void disconnect ()
BowlerAbstractConnection getConnection ()
void setAddress (MACAddress address)
MACAddress getAddress ()
BowlerDatagram send (BowlerAbstractCommand command) throws NoConnectionAvailableException, InvalidResponseException
BowlerDatagram send (BowlerAbstractCommand command, int retry) throws NoConnectionAvailableException, InvalidResponseException
Object[] send (String namespace, BowlerMethod method, String rpcString, Object[] arguments, int retry) throws DeviceConnectionException
Object[] send (String namespace, BowlerMethod method, String rpcString, Object[] arguments) throws DeviceConnectionException
boolean ping ()
boolean ping (boolean switchParser)
ArrayList< ByteList > getRevisions ()
ArrayList< String > getNamespaces ()
boolean hasNamespace (String string)
void startHeartBeat ()
void startHeartBeat (long msHeartBeatTime)
void stopHeartBeat ()
void setThreadedUpstreamPackets (boolean up)
ArrayList< RpcEncapsulation > getRpcList (String namespace)
void loadRpcList ()
boolean isKeepAlive ()
void setKeepAlive (boolean keepAlive)
long getLastPacketTime ()
void setLastPacketTime (long lastPacketTime)
String getScriptingName ()
void setScriptingName (String scriptingName)
ArrayList< IDeviceConnectionEventListener > getDisconnectListeners ()
Additional Inherited Members
Protected Member Functions inherited from com.neuronrobotics.sdk.common.BowlerAbstractDevice
void fireDisconnectEvent ()
void fireConnectEvent ()
Detailed Description
This is a basic device with only bcs.core
Author
hephaestus
Definition at line 16 of file GenericDevice.java.
Constructor & Destructor Documentation
GenericDevice()
com.neuronrobotics.sdk.genericdevice.GenericDevice.GenericDevice (BowlerAbstractConnection connection)
Builds a DyIO with the given connection and the broadcast address.
Parameters
connection the connection
Definition at line 23 of file GenericDevice.java.
References com.neuronrobotics.sdk.common.MACAddress.BROADCAST, com.neuronrobotics.sdk.common.BowlerAbstractDevice.connection, com.neuronrobotics.sdk.common.BowlerAbstractDevice.setAddress(), and com.neuronrobotics.sdk.common.BowlerAbstractDevice.setConnection().
Member Function Documentation
isAvailable()
boolean com.neuronrobotics.sdk.genericdevice.GenericDevice.isAvailable () throws InvalidConnectionException
Determines if the device is available.
Returns
true if the device is avaiable, false if it is not
Exceptions
InvalidConnectionException the invalid connection exception
Reimplemented from com.neuronrobotics.sdk.common.BowlerAbstractDevice.
Definition at line 32 of file GenericDevice.java.
References com.neuronrobotics.sdk.common.BowlerAbstractDevice.getConnection(), and com.neuronrobotics.sdk.common.BowlerAbstractConnection.isConnected().
onAllResponse()
void com.neuronrobotics.sdk.genericdevice.GenericDevice.onAllResponse (BowlerDatagram data)
On all response.
Parameters
data the data
Reimplemented from com.neuronrobotics.sdk.common.BowlerAbstractDevice.
Definition at line 40 of file GenericDevice.java.
onAsyncResponse()
void com.neuronrobotics.sdk.genericdevice.GenericDevice.onAsyncResponse (BowlerDatagram data)
On async response.
Parameters
data the data
Implements com.neuronrobotics.sdk.common.IBowlerDatagramListener.
Definition at line 49 of file GenericDevice.java.
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/genericdevice/GenericDevice.java