BowlerKernel: com.neuronrobotics.imageprovider.URLImageProvider Class Reference
com.neuronrobotics.imageprovider.URLImageProvider Class Reference
Public Member Functions
URLImageProvider (URL url)
void disconnectDeviceImp ()
boolean connectDeviceImp ()
ArrayList< String > getNamespacesImp ()
BufferedImage captureNewImage ()
Public Member Functions inherited from com.neuronrobotics.imageprovider.AbstractImageProvider
void onAsyncResponse (BowlerDatagram data)
boolean connect ()
boolean isAvailable () throws InvalidConnectionException
BufferedImage getLatestImage (BufferedImage inputImage, BufferedImage displayImage)
BufferedImage getLatestImage ()
javafx.scene.image.Image getLatestJfxImage ()
void setGlobalPositionListener (javafx.scene.transform.Affine globalPos)
javafx.scene.transform.Affine getGlobalPos ()
void setGlobalPos (javafx.scene.transform.Affine globalPos)
Public Member Functions inherited from com.neuronrobotics.sdk.common.NonBowlerDevice
void disconnect ()
ArrayList< String > getNamespaces ()
Public Member Functions inherited from com.neuronrobotics.sdk.common.BowlerAbstractDevice
void addConnectionEventListener (final IDeviceConnectionEventListener l)
void removeConnectionEventListener (IDeviceConnectionEventListener l)
void setConnection (BowlerAbstractConnection connection)
BowlerAbstractConnection getConnection ()
void setAddress (MACAddress address)
MACAddress getAddress ()
BowlerDatagram send (BowlerAbstractCommand command) throws NoConnectionAvailableException, InvalidResponseException
BowlerDatagram send (BowlerAbstractCommand command, int retry) throws NoConnectionAvailableException, InvalidResponseException
Object[] send (String namespace, BowlerMethod method, String rpcString, Object[] arguments, int retry) throws DeviceConnectionException
Object[] send (String namespace, BowlerMethod method, String rpcString, Object[] arguments) throws DeviceConnectionException
boolean ping ()
boolean ping (boolean switchParser)
ArrayList< ByteList > getRevisions ()
boolean hasNamespace (String string)
void startHeartBeat ()
void startHeartBeat (long msHeartBeatTime)
void stopHeartBeat ()
void setThreadedUpstreamPackets (boolean up)
ArrayList< RpcEncapsulation > getRpcList (String namespace)
void loadRpcList ()
void onAllResponse (BowlerDatagram data)
boolean isKeepAlive ()
void setKeepAlive (boolean keepAlive)
long getLastPacketTime ()
void setLastPacketTime (long lastPacketTime)
String getScriptingName ()
void setScriptingName (String scriptingName)
ArrayList< IDeviceConnectionEventListener > getDisconnectListeners ()
Protected Member Functions
boolean captureNewImage (BufferedImage imageData)
Protected Member Functions inherited from com.neuronrobotics.sdk.common.BowlerAbstractDevice
void fireDisconnectEvent ()
void fireConnectEvent ()
Private Attributes
URL url
Additional Inherited Members
Static Public Member Functions inherited from com.neuronrobotics.imageprovider.AbstractImageProvider
static void deepCopy (BufferedImage src, BufferedImage dest)
static BufferedImage newBufferImage (int w, int h)
static BufferedImage toGrayScale (BufferedImage in, int w, int h)
static BufferedImage toGrayScale (BufferedImage in, double scale)
static javafx.scene.image.Image getJfxImage (BufferedImage bf)
Detailed Description
Definition at line 13 of file URLImageProvider.java.
Constructor & Destructor Documentation
URLImageProvider()
com.neuronrobotics.imageprovider.URLImageProvider.URLImageProvider (URL url)
Definition at line 18 of file URLImageProvider.java.
References com.neuronrobotics.imageprovider.URLImageProvider.url.
Member Function Documentation
captureNewImage() [1/2]
BufferedImage com.neuronrobotics.imageprovider.URLImageProvider.captureNewImage ()
This method should capture a new image and return it
Returns
Reimplemented from com.neuronrobotics.imageprovider.AbstractImageProvider.
Definition at line 49 of file URLImageProvider.java.
References com.neuronrobotics.imageprovider.URLImageProvider.url.
Referenced by com.neuronrobotics.imageprovider.URLImageProvider.captureNewImage().
captureNewImage() [2/2]
boolean com.neuronrobotics.imageprovider.URLImageProvider.captureNewImage (BufferedImage imageData) protected
This method should capture a new image and load it into the Mat datatype
Parameters
imageData
Returns
Reimplemented from com.neuronrobotics.imageprovider.AbstractImageProvider.
Definition at line 23 of file URLImageProvider.java.
References com.neuronrobotics.imageprovider.URLImageProvider.captureNewImage(), and com.neuronrobotics.imageprovider.AbstractImageProvider.deepCopy().
connectDeviceImp()
boolean com.neuronrobotics.imageprovider.URLImageProvider.connectDeviceImp ()
Connect device imp.
Returns
true, if successful
Reimplemented from com.neuronrobotics.sdk.common.NonBowlerDevice.
Definition at line 37 of file URLImageProvider.java.
disconnectDeviceImp()
void com.neuronrobotics.imageprovider.URLImageProvider.disconnectDeviceImp ()
This method tells the connection object to disconnect its pipes and close out the connection. Once this is called, it is safe to remove your device.
Reimplemented from com.neuronrobotics.sdk.common.NonBowlerDevice.
Definition at line 31 of file URLImageProvider.java.
getNamespacesImp()
ArrayList<String> com.neuronrobotics.imageprovider.URLImageProvider.getNamespacesImp ()
Gets the namespaces imp.
Returns
the namespaces imp
Reimplemented from com.neuronrobotics.sdk.common.NonBowlerDevice.
Definition at line 43 of file URLImageProvider.java.
Member Data Documentation
url
URL com.neuronrobotics.imageprovider.URLImageProvider.url private
Definition at line 16 of file URLImageProvider.java.
Referenced by com.neuronrobotics.imageprovider.URLImageProvider.captureNewImage(), and com.neuronrobotics.imageprovider.URLImageProvider.URLImageProvider().
The documentation for this class was generated from the following file:
src/main/java/com/neuronrobotics/imageprovider/URLImageProvider.java