BowlerKernel: com.neuronrobotics.sdk.addons.kinematics.SearchTreeSolver.searchTree Class Reference
com.neuronrobotics.sdk.addons.kinematics.SearchTreeSolver.searchTree Class Reference
Public Member Functions
searchTree (double[] jointSpaceVector, double startingIncrement)
configuration getBest (double[] jointSpaceVector)
Detailed Description
The Class searchTree.
Definition at line 128 of file SearchTreeSolver.java.
Constructor & Destructor Documentation
searchTree()
com.neuronrobotics.sdk.addons.kinematics.SearchTreeSolver.searchTree.searchTree (double[] jointSpaceVector, double startingIncrement)
Instantiates a new search tree.
Parameters
jointSpaceVector the joint space vector
startingIncrement the starting increment
Definition at line 140 of file SearchTreeSolver.java.
Member Function Documentation
getBest()
configuration com.neuronrobotics.sdk.addons.kinematics.SearchTreeSolver.searchTree.getBest (double[] jointSpaceVector)
Gets the best.
Parameters
jointSpaceVector the joint space vector
Returns
the best
Definition at line 154 of file SearchTreeSolver.java.
References com.neuronrobotics.sdk.addons.kinematics.SearchTreeSolver.getTarget(), com.neuronrobotics.sdk.addons.kinematics.SearchTreeSolver.configuration.same(), and com.neuronrobotics.sdk.addons.kinematics.SearchTreeSolver.searchNode.setCurrent().
Referenced by com.neuronrobotics.sdk.addons.kinematics.SearchTreeSolver.inverseKinematics().
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/addons/kinematics/SearchTreeSolver.java