BowlerKernel: eu.mihosoft.vrl.v3d.Extrude Class Reference
eu.mihosoft.vrl.v3d.Extrude Class Reference
Static Public Member Functions
static CSG polygons (Polygon polygon1, Number zDistance)
static CSG polygons (Polygon polygon1, Polygon polygon2)
static ArrayList< CSG > polygons (eu.mihosoft.vrl.v3d.Polygon polygon1, ArrayList< Transform > transforms)
static ArrayList< CSG > polygons (eu.mihosoft.vrl.v3d.Polygon polygon1, Transform... transformparts)
static CSG points (Vector3d dir, List< Vector3d > points)
static CSG points (Vector3d dir, Vector3d... points)
static List< Vector3d > toCCW (List< Vector3d > points)
static boolean isCCW (Polygon polygon)
static IExtrusion getExtrusionEngine ()
static void setExtrusionEngine (IExtrusion extrusionEngine)
static CSG byPath (List< List< Vector3d >> points, double height)
static CSG byPath (List< List< Vector3d >> points, double height, int resolution)
static ArrayList< Transform > pathToTransforms (List< List< Vector3d >> points, int resolution)
static ArrayList< CSG > moveAlongProfile (CSG object, List< List< Vector3d >> points, int resolution)
static ArrayList< Transform > bezierToTransforms (Vector3d controlA, Vector3d controlB, Vector3d endPoint, int iterations)
static ArrayList< Transform > bezierToTransforms (List< Vector3d > parts, int iterations)
static ArrayList< Transform > bezierToTransforms (BezierPath pathA, BezierPath pathB, int iterations, Vector3d controlA, Vector3d controlB)
static ArrayList< Transform > bezierToTransforms (Vector3d start, Vector3d controlA, Vector3d controlB, Vector3d endPoint, int iterations)
static ArrayList< CSG > revolve (CSG slice, double radius, int numSlices)
static ArrayList< CSG > revolve (Polygon poly, int numSlices)
static ArrayList< CSG > revolve (Polygon poly, double radius, int numSlices)
static ArrayList< CSG > revolve (CSG slice, double radius, double archLen, int numSlices)
static ArrayList< CSG > revolve (CSG slice, double radius, double archLen, List< List< Vector3d >> points, int numSlices)
static ArrayList< CSG > bezier (CSG slice, ArrayList< Double > controlA, ArrayList< Double > controlB, ArrayList< Double > endPoint, int numSlices)
static ArrayList< CSG > bezier (ArrayList< CSG > s, ArrayList< Double > controlA, ArrayList< Double > controlB, ArrayList< Double > endPoint)
static ArrayList< CSG > hull (ArrayList< CSG > s, ArrayList< Transform > p)
static ArrayList< CSG > hull (CSG c, ArrayList< Transform > p)
static ArrayList< CSG > linear (ArrayList< CSG > s, ArrayList< Double > endPoint)
static ArrayList< CSG > linear (CSG s, ArrayList< Double > endPoint, int numSlices)
static ArrayList< CSG > move (ArrayList< CSG > slice, ArrayList< Transform > p)
static ArrayList< CSG > move (CSG slice, ArrayList< Transform > p)
static ArrayList< CSG > moveBezier (CSG slice, ArrayList< Double > controlA, ArrayList< Double > controlB, ArrayList< Double > endPoint, int numSlices)
static ArrayList< CSG > moveBezier (ArrayList< CSG > slice, ArrayList< Double > controlA, ArrayList< Double > controlB, ArrayList< Double > endPoint)
static ArrayList< CSG > moveBezier (CSG slice, BezierPath pathA, int numSlices)
static ArrayList< CSG > moveBezier (CSG slice, BezierPath pathA, BezierPath pathB, int iterations)
static Polygon toCCW (Polygon concave)
Private Member Functions
Extrude ()
Transform toTransform ()
Static Private Member Functions
static double normalizedX (Vector3d v1, Vector3d v2)
static Vector3d fromDouble (ArrayList< Double > controlA)
Static Private Attributes
static IExtrusion extrusionEngine
Detailed Description
Extrudes concave and convex polygons.
Author
Michael Hoffer <info@.nosp@m.mich.nosp@m.aelho.nosp@m.ffer.nosp@m..de>
Definition at line 55 of file Extrude.java.
Constructor & Destructor Documentation
Extrude()
eu.mihosoft.vrl.v3d.Extrude.Extrude () private
Instantiates a new extrude.
Definition at line 126 of file Extrude.java.
Member Function Documentation
bezier() [1/2]
static ArrayList<CSG> eu.mihosoft.vrl.v3d.Extrude.bezier (ArrayList< CSG > s, ArrayList< Double > controlA, ArrayList< Double > controlB, ArrayList< Double > endPoint) static
Definition at line 642 of file Extrude.java.
References eu.mihosoft.vrl.v3d.ext.quickhull3d.HullUtil.hull(), and eu.mihosoft.vrl.v3d.Extrude.moveBezier().
bezier() [2/2]
static ArrayList<CSG> eu.mihosoft.vrl.v3d.Extrude.bezier (CSG slice, ArrayList< Double > controlA, ArrayList< Double > controlB, ArrayList< Double > endPoint, int numSlices) static
Definition at line 632 of file Extrude.java.
References eu.mihosoft.vrl.v3d.CSG.clone().
Referenced by eu.mihosoft.vrl.v3d.Extrude.linear().
bezierToTransforms() [1/4]
static ArrayList<Transform> eu.mihosoft.vrl.v3d.Extrude.bezierToTransforms (BezierPath pathA, BezierPath pathB, int iterations, Vector3d controlA, Vector3d controlB) static
Definition at line 448 of file Extrude.java.
References com.piro.bezier.BezierPath.eval(), eu.mihosoft.vrl.v3d.Transform.rotY(), eu.mihosoft.vrl.v3d.Transform.rotZ(), eu.mihosoft.vrl.v3d.Transform.translateX(), eu.mihosoft.vrl.v3d.Transform.translateY(), eu.mihosoft.vrl.v3d.Transform.translateZ(), eu.mihosoft.vrl.v3d.Vector3d.x(), eu.mihosoft.vrl.v3d.Vector3d.y(), and eu.mihosoft.vrl.v3d.Vector3d.z().
bezierToTransforms() [2/4]
static ArrayList<Transform> eu.mihosoft.vrl.v3d.Extrude.bezierToTransforms (List< Vector3d > parts, int iterations) static
Definition at line 431 of file Extrude.java.
References eu.mihosoft.vrl.v3d.Extrude.bezierToTransforms().
bezierToTransforms() [3/4]
static ArrayList<Transform> eu.mihosoft.vrl.v3d.Extrude.bezierToTransforms (Vector3d controlA, Vector3d controlB, Vector3d endPoint, int iterations) static
Definition at line 419 of file Extrude.java.
References com.piro.bezier.BezierPath.parsePathString(), eu.mihosoft.vrl.v3d.Vector3d.x(), eu.mihosoft.vrl.v3d.Vector3d.y(), and eu.mihosoft.vrl.v3d.Vector3d.z().
Referenced by eu.mihosoft.vrl.v3d.Extrude.bezierToTransforms(), eu.mihosoft.vrl.v3d.Extrude.moveBezier(), eu.mihosoft.vrl.v3d.Extrude.pathToTransforms(), and com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.transforms().
bezierToTransforms() [4/4]
static ArrayList<Transform> eu.mihosoft.vrl.v3d.Extrude.bezierToTransforms (Vector3d start, Vector3d controlA, Vector3d controlB, Vector3d endPoint, int iterations) static
Definition at line 558 of file Extrude.java.
References eu.mihosoft.vrl.v3d.Extrude.bezierToTransforms(), com.piro.bezier.BezierPath.parsePathString(), eu.mihosoft.vrl.v3d.Vector3d.x(), eu.mihosoft.vrl.v3d.Vector3d.y(), and eu.mihosoft.vrl.v3d.Vector3d.z().
byPath() [1/2]
static CSG eu.mihosoft.vrl.v3d.Extrude.byPath (List< List< Vector3d >> points, double height) static
Definition at line 340 of file Extrude.java.
References eu.mihosoft.vrl.v3d.Extrude.points().
byPath() [2/2]
static CSG eu.mihosoft.vrl.v3d.Extrude.byPath (List< List< Vector3d >> points, double height, int resolution) static
Definition at line 346 of file Extrude.java.
References eu.mihosoft.vrl.v3d.Extrude.pathToTransforms(), and eu.mihosoft.vrl.v3d.Extrude.points().
fromDouble()
static Vector3d eu.mihosoft.vrl.v3d.Extrude.fromDouble (ArrayList< Double > controlA) static private
Definition at line 716 of file Extrude.java.
Referenced by eu.mihosoft.vrl.v3d.Extrude.moveBezier().
getExtrusionEngine()
static IExtrusion eu.mihosoft.vrl.v3d.Extrude.getExtrusionEngine () static
Definition at line 332 of file Extrude.java.
References eu.mihosoft.vrl.v3d.Extrude.extrusionEngine.
Referenced by eu.mihosoft.vrl.v3d.svg.SVGLoad.extrudeLayers(), and eu.mihosoft.vrl.v3d.Extrude.points().
hull() [1/2]
static ArrayList<CSG> eu.mihosoft.vrl.v3d.Extrude.hull (ArrayList< CSG > s, ArrayList< Transform > p) static
Definition at line 657 of file Extrude.java.
References eu.mihosoft.vrl.v3d.ext.quickhull3d.HullUtil.hull(), and eu.mihosoft.vrl.v3d.Extrude.move().
Referenced by eu.mihosoft.vrl.v3d.Extrude.hull().
hull() [2/2]
static ArrayList<CSG> eu.mihosoft.vrl.v3d.Extrude.hull (CSG c, ArrayList< Transform > p) static
Definition at line 670 of file Extrude.java.
References eu.mihosoft.vrl.v3d.CSG.clone(), and eu.mihosoft.vrl.v3d.Extrude.hull().
isCCW()
static boolean eu.mihosoft.vrl.v3d.Extrude.isCCW (Polygon polygon) static
Checks if is ccw.
Parameters
polygon the polygon
Returns
true, if is ccw
Definition at line 258 of file Extrude.java.
References eu.mihosoft.vrl.v3d.Extrude.normalizedX(), eu.mihosoft.vrl.v3d.Vertex.pos, eu.mihosoft.vrl.v3d.Polygon.vertices, eu.mihosoft.vrl.v3d.Vector3d.x(), and eu.mihosoft.vrl.v3d.Vector3d.y().
Referenced by eu.mihosoft.vrl.v3d.ext.org.poly2tri.PolygonUtil.concaveToConvex(), eu.mihosoft.vrl.v3d.TextExtrude.loadPoints(), eu.mihosoft.vrl.v3d.Slice.sanatize(), and eu.mihosoft.vrl.v3d.Extrude.toCCW().
linear() [1/2]
static ArrayList<CSG> eu.mihosoft.vrl.v3d.Extrude.linear (ArrayList< CSG > s, ArrayList< Double > endPoint) static
Definition at line 678 of file Extrude.java.
References eu.mihosoft.vrl.v3d.Extrude.bezier().
linear() [2/2]
static ArrayList<CSG> eu.mihosoft.vrl.v3d.Extrude.linear (CSG s, ArrayList< Double > endPoint, int numSlices) static
Definition at line 683 of file Extrude.java.
References eu.mihosoft.vrl.v3d.Extrude.bezier().
move() [1/2]
static ArrayList<CSG> eu.mihosoft.vrl.v3d.Extrude.move (ArrayList< CSG > slice, ArrayList< Transform > p) static
Definition at line 689 of file Extrude.java.
References eu.mihosoft.vrl.v3d.CSG.move().
Referenced by eu.mihosoft.vrl.v3d.Extrude.hull(), eu.mihosoft.vrl.v3d.Extrude.moveAlongProfile(), and eu.mihosoft.vrl.v3d.Extrude.moveBezier().
move() [2/2]
static ArrayList<CSG> eu.mihosoft.vrl.v3d.Extrude.move (CSG slice, ArrayList< Transform > p) static
Definition at line 694 of file Extrude.java.
References eu.mihosoft.vrl.v3d.CSG.move().
moveAlongProfile()
static ArrayList<CSG> eu.mihosoft.vrl.v3d.Extrude.moveAlongProfile (CSG object, List< List< Vector3d >> points, int resolution) static
Definition at line 414 of file Extrude.java.
References eu.mihosoft.vrl.v3d.Extrude.move(), eu.mihosoft.vrl.v3d.Extrude.pathToTransforms(), and eu.mihosoft.vrl.v3d.Extrude.points().
moveBezier() [1/4]
static ArrayList<CSG> eu.mihosoft.vrl.v3d.Extrude.moveBezier (ArrayList< CSG > slice, ArrayList< Double > controlA, ArrayList< Double > controlB, ArrayList< Double > endPoint) static
Definition at line 706 of file Extrude.java.
References eu.mihosoft.vrl.v3d.Extrude.bezierToTransforms(), eu.mihosoft.vrl.v3d.Extrude.fromDouble(), and eu.mihosoft.vrl.v3d.Extrude.move().
moveBezier() [2/4]
static ArrayList<CSG> eu.mihosoft.vrl.v3d.Extrude.moveBezier (CSG slice, ArrayList< Double > controlA, ArrayList< Double > controlB, ArrayList< Double > endPoint, int numSlices) static
Definition at line 698 of file Extrude.java.
References eu.mihosoft.vrl.v3d.Extrude.bezierToTransforms(), eu.mihosoft.vrl.v3d.Extrude.fromDouble(), and eu.mihosoft.vrl.v3d.Extrude.move().
Referenced by eu.mihosoft.vrl.v3d.Extrude.bezier(), and eu.mihosoft.vrl.v3d.Extrude.moveBezier().
moveBezier() [3/4]
static ArrayList<CSG> eu.mihosoft.vrl.v3d.Extrude.moveBezier (CSG slice, BezierPath pathA, BezierPath pathB, int iterations) static
Definition at line 730 of file Extrude.java.
References eu.mihosoft.vrl.v3d.Extrude.bezierToTransforms(), and eu.mihosoft.vrl.v3d.Extrude.move().
moveBezier() [4/4]
static ArrayList<CSG> eu.mihosoft.vrl.v3d.Extrude.moveBezier (CSG slice, BezierPath pathA, int numSlices) static
Definition at line 720 of file Extrude.java.
References com.piro.bezier.BezierPath.eval(), eu.mihosoft.vrl.v3d.Extrude.moveBezier(), com.piro.bezier.BezierPath.parsePathString(), eu.mihosoft.vrl.v3d.Vector3d.x(), and eu.mihosoft.vrl.v3d.Vector3d.y().
normalizedX()
static double eu.mihosoft.vrl.v3d.Extrude.normalizedX (Vector3d v1, Vector3d v2) static private
Normalized x.
Parameters
v1 the v1
v2 the v2
Returns
the double
Definition at line 326 of file Extrude.java.
References eu.mihosoft.vrl.v3d.Vector3d.dividedBy(), eu.mihosoft.vrl.v3d.Vector3d.magnitude(), eu.mihosoft.vrl.v3d.Vector3d.minus(), eu.mihosoft.vrl.v3d.Vector3d.times(), eu.mihosoft.vrl.v3d.Vector3d.x(), and eu.mihosoft.vrl.v3d.Vector3d.X_ONE.
Referenced by eu.mihosoft.vrl.v3d.Extrude.isCCW().
pathToTransforms()
static ArrayList<Transform> eu.mihosoft.vrl.v3d.Extrude.pathToTransforms (List< List< Vector3d >> points, int resolution) static
Definition at line 364 of file Extrude.java.
References eu.mihosoft.vrl.v3d.Extrude.bezierToTransforms(), com.piro.bezier.BezierPath.parsePathString(), eu.mihosoft.vrl.v3d.Extrude.points(), eu.mihosoft.vrl.v3d.Vector3d.x(), eu.mihosoft.vrl.v3d.Vector3d.y(), and eu.mihosoft.vrl.v3d.Vector3d.z().
Referenced by eu.mihosoft.vrl.v3d.Extrude.byPath(), eu.mihosoft.vrl.v3d.Extrude.moveAlongProfile(), and eu.mihosoft.vrl.v3d.Extrude.revolve().
points() [1/2]
static CSG eu.mihosoft.vrl.v3d.Extrude.points (Vector3d dir, List< Vector3d > points) static
Definition at line 199 of file Extrude.java.
References eu.mihosoft.vrl.v3d.IExtrusion.extrude(), and eu.mihosoft.vrl.v3d.Extrude.getExtrusionEngine().
Referenced by eu.mihosoft.vrl.v3d.Extrude.byPath(), eu.mihosoft.vrl.v3d.Parabola.extrudeByEquation(), eu.mihosoft.vrl.v3d.TextExtrude.loadPoints(), eu.mihosoft.vrl.v3d.Extrude.moveAlongProfile(), eu.mihosoft.vrl.v3d.Extrude.pathToTransforms(), eu.mihosoft.vrl.v3d.Extrude.points(), eu.mihosoft.vrl.v3d.Extrude.revolve(), eu.mihosoft.vrl.v3d.Extrude.toCCW(), eu.mihosoft.vrl.v3d.DXF.toParts(), eu.mihosoft.vrl.v3d.Isosceles.toPolygons(), and eu.mihosoft.vrl.v3d.Wedge.toPolygons().
points() [2/2]
static CSG eu.mihosoft.vrl.v3d.Extrude.points (Vector3d dir, Vector3d... points) static
Extrudes the specified path (convex or concave polygon without holes or intersections, specified in CCW) into the specified direction.
Parameters
dir direction
points path (convex or concave polygon without holes or intersections)
Returns
a CSG object that consists of the extruded polygon
Definition at line 213 of file Extrude.java.
References eu.mihosoft.vrl.v3d.Extrude.points().
polygons() [1/4]
static ArrayList<CSG> eu.mihosoft.vrl.v3d.Extrude.polygons (eu.mihosoft.vrl.v3d.Polygon polygon1, ArrayList< Transform > transforms) static
Definition at line 174 of file Extrude.java.
References eu.mihosoft.vrl.v3d.Polygon.fromPoints(), eu.mihosoft.vrl.v3d.Extrude.polygons(), and eu.mihosoft.vrl.v3d.Extrude.toCCW().
polygons() [2/4]
static ArrayList<CSG> eu.mihosoft.vrl.v3d.Extrude.polygons (eu.mihosoft.vrl.v3d.Polygon polygon1, Transform... transformparts) static
Definition at line 193 of file Extrude.java.
References eu.mihosoft.vrl.v3d.Extrude.polygons().
polygons() [3/4]
static CSG eu.mihosoft.vrl.v3d.Extrude.polygons (Polygon polygon1, Number zDistance) static
Definition at line 130 of file Extrude.java.
References eu.mihosoft.vrl.v3d.Polygon.transformed().
Referenced by eu.mihosoft.vrl.v3d.Extrude.polygons(), and eu.mihosoft.vrl.v3d.Extrude.revolve().
polygons() [4/4]
static CSG eu.mihosoft.vrl.v3d.Extrude.polygons (Polygon polygon1, Polygon polygon2) static
Definition at line 134 of file Extrude.java.
References eu.mihosoft.vrl.v3d.ext.org.poly2tri.PolygonUtil.concaveToConvex(), eu.mihosoft.vrl.v3d.Polygon.flipped(), eu.mihosoft.vrl.v3d.Polygon.fromPoints(), eu.mihosoft.vrl.v3d.CSG.fromPolygons(), eu.mihosoft.vrl.v3d.Polygon.getStorage(), and eu.mihosoft.vrl.v3d.Polygon.vertices.
revolve() [1/5]
static ArrayList<CSG> eu.mihosoft.vrl.v3d.Extrude.revolve (CSG slice, double radius, double archLen, int numSlices) static
Definition at line 602 of file Extrude.java.
References eu.mihosoft.vrl.v3d.Extrude.revolve().
revolve() [2/5]
static ArrayList<CSG> eu.mihosoft.vrl.v3d.Extrude.revolve (CSG slice, double radius, double archLen, List< List< Vector3d >> points, int numSlices) static
Definition at line 606 of file Extrude.java.
References eu.mihosoft.vrl.v3d.CSG.hullAll(), eu.mihosoft.vrl.v3d.CSG.movey(), eu.mihosoft.vrl.v3d.Extrude.pathToTransforms(), eu.mihosoft.vrl.v3d.Extrude.points(), eu.mihosoft.vrl.v3d.CSG.rotz(), and eu.mihosoft.vrl.v3d.CSG.transformed().
revolve() [3/5]
static ArrayList<CSG> eu.mihosoft.vrl.v3d.Extrude.revolve (CSG slice, double radius, int numSlices) static
Definition at line 575 of file Extrude.java.
Referenced by eu.mihosoft.vrl.v3d.Fillet.corner(), and eu.mihosoft.vrl.v3d.Extrude.revolve().
revolve() [4/5]
static ArrayList<CSG> eu.mihosoft.vrl.v3d.Extrude.revolve (Polygon poly, double radius, int numSlices) static
Definition at line 583 of file Extrude.java.
References eu.mihosoft.vrl.v3d.Transform.movex(), eu.mihosoft.vrl.v3d.Extrude.polygons(), eu.mihosoft.vrl.v3d.Transform.roty(), and eu.mihosoft.vrl.v3d.Polygon.transformed().
revolve() [5/5]
static ArrayList<CSG> eu.mihosoft.vrl.v3d.Extrude.revolve (Polygon poly, int numSlices) static
Definition at line 579 of file Extrude.java.
References eu.mihosoft.vrl.v3d.Extrude.revolve().
setExtrusionEngine()
static void eu.mihosoft.vrl.v3d.Extrude.setExtrusionEngine (IExtrusion extrusionEngine) static
Definition at line 336 of file Extrude.java.
References eu.mihosoft.vrl.v3d.Extrude.extrusionEngine.
toCCW() [1/2]
static List<Vector3d> eu.mihosoft.vrl.v3d.Extrude.toCCW (List< Vector3d > points) static
To ccw.
Parameters
points the points
Returns
the list
Definition at line 224 of file Extrude.java.
References eu.mihosoft.vrl.v3d.Polygon.fromPoints(), eu.mihosoft.vrl.v3d.Extrude.isCCW(), and eu.mihosoft.vrl.v3d.Extrude.points().
Referenced by eu.mihosoft.vrl.v3d.svg.SVGLoad.loadSingle(), and eu.mihosoft.vrl.v3d.Extrude.polygons().
toCCW() [2/2]
static Polygon eu.mihosoft.vrl.v3d.Extrude.toCCW (Polygon concave) static
Definition at line 737 of file Extrude.java.
References eu.mihosoft.vrl.v3d.Polygon.fromPoints(), eu.mihosoft.vrl.v3d.Polygon.getPoints(), eu.mihosoft.vrl.v3d.Extrude.isCCW(), and eu.mihosoft.vrl.v3d.Extrude.points().
toTransform()
Transform eu.mihosoft.vrl.v3d.Extrude.toTransform () private
Definition at line 443 of file Extrude.java.
Member Data Documentation
extrusionEngine
IExtrusion eu.mihosoft.vrl.v3d.Extrude.extrusionEngine static private
Definition at line 56 of file Extrude.java.
Referenced by eu.mihosoft.vrl.v3d.Extrude.getExtrusionEngine(), and eu.mihosoft.vrl.v3d.Extrude.setExtrusionEngine().
The documentation for this class was generated from the following file:
JCSG/src/main/java/eu/mihosoft/vrl/v3d/Extrude.java