BowlerKernel: eu.mihosoft.vrl.v3d.Tetrahedron Class Reference
eu.mihosoft.vrl.v3d.Tetrahedron Class Reference
Public Member Functions
Tetrahedron ()
Tetrahedron (double size)
Tetrahedron (Vector3d center, double size)
List< Polygon > toPolygons ()
Vector3d getCenter ()
Tetrahedron setCenter (Vector3d center)
double getRadius ()
void setRadius (double radius)
PropertyStorage getProperties ()
Tetrahedron noCenter ()
Public Member Functions inherited from eu.mihosoft.vrl.v3d.Primitive
CSG toCSG ()
Private Attributes
Vector3d center
double radius
boolean centered = true
final PropertyStorage properties = new PropertyStorage()
Detailed Description
Definition at line 13 of file Tetrahedron.java.
Constructor & Destructor Documentation
Tetrahedron() [1/3]
eu.mihosoft.vrl.v3d.Tetrahedron.Tetrahedron ()
Constructor. Creates a new tetrahedron with center
[0,0,0]
and dimensions
[1,1,1]
.
Definition at line 33 of file Tetrahedron.java.
References eu.mihosoft.vrl.v3d.Tetrahedron.center, and eu.mihosoft.vrl.v3d.Tetrahedron.radius.
Tetrahedron() [2/3]
eu.mihosoft.vrl.v3d.Tetrahedron.Tetrahedron (double size)
Constructor. Creates a new tetrahedron with center
[0,0,0]
and radius
size
.
Parameters
size size
Definition at line 44 of file Tetrahedron.java.
References eu.mihosoft.vrl.v3d.Tetrahedron.center, and eu.mihosoft.vrl.v3d.Tetrahedron.radius.
Tetrahedron() [3/3]
eu.mihosoft.vrl.v3d.Tetrahedron.Tetrahedron (Vector3d center, double size)
Constructor. Creates a new tetrahedron with the specified center and radius.
Parameters
center center of the tetrahedron
size of the tetrahedron
Definition at line 56 of file Tetrahedron.java.
References eu.mihosoft.vrl.v3d.Tetrahedron.center.
Member Function Documentation
getCenter()
Vector3d eu.mihosoft.vrl.v3d.Tetrahedron.getCenter ()
Gets the center.
Returns
the center
Definition at line 86 of file Tetrahedron.java.
References eu.mihosoft.vrl.v3d.Tetrahedron.center.
getProperties()
PropertyStorage eu.mihosoft.vrl.v3d.Tetrahedron.getProperties ()
Returns the property storage of this primitive.
Returns
the property storage of this primitive
Reimplemented from eu.mihosoft.vrl.v3d.Primitive.
Definition at line 122 of file Tetrahedron.java.
References eu.mihosoft.vrl.v3d.Tetrahedron.properties.
getRadius()
double eu.mihosoft.vrl.v3d.Tetrahedron.getRadius ()
Gets the radius.
Returns
the radius
Definition at line 105 of file Tetrahedron.java.
References eu.mihosoft.vrl.v3d.Tetrahedron.radius.
noCenter()
Tetrahedron eu.mihosoft.vrl.v3d.Tetrahedron.noCenter ()
Defines that this tetrahedron will not be centered.
Returns
this tetrahedron
Definition at line 130 of file Tetrahedron.java.
References eu.mihosoft.vrl.v3d.Tetrahedron.centered.
setCenter()
Tetrahedron eu.mihosoft.vrl.v3d.Tetrahedron.setCenter (Vector3d center)
Sets the center.
Parameters
center the center to set
Definition at line 95 of file Tetrahedron.java.
References eu.mihosoft.vrl.v3d.Tetrahedron.center.
setRadius()
void eu.mihosoft.vrl.v3d.Tetrahedron.setRadius (double radius)
Sets the radius.
Parameters
radius the radius to set
Definition at line 114 of file Tetrahedron.java.
References eu.mihosoft.vrl.v3d.Tetrahedron.radius.
toPolygons()
List<Polygon> eu.mihosoft.vrl.v3d.Tetrahedron.toPolygons ()
Returns the polygons that define this primitive.
Note: this method computes the polygons each time this method is called. The polygons can be cached inside a CSG object.
Returns
a list of polygons that define this primitive
Reimplemented from eu.mihosoft.vrl.v3d.Primitive.
Definition at line 65 of file Tetrahedron.java.
References eu.mihosoft.vrl.v3d.CSG.getPolygons(), eu.mihosoft.vrl.v3d.ext.quickhull3d.HullUtil.hull(), eu.mihosoft.vrl.v3d.Tetrahedron.radius, and eu.mihosoft.vrl.v3d.CSG.scale().
Member Data Documentation
center
Vector3d eu.mihosoft.vrl.v3d.Tetrahedron.center private
Center of this tetrahedron.
Definition at line 18 of file Tetrahedron.java.
Referenced by eu.mihosoft.vrl.v3d.Tetrahedron.getCenter(), eu.mihosoft.vrl.v3d.Tetrahedron.setCenter(), and eu.mihosoft.vrl.v3d.Tetrahedron.Tetrahedron().
centered
boolean eu.mihosoft.vrl.v3d.Tetrahedron.centered = true private
The centered.
Definition at line 25 of file Tetrahedron.java.
Referenced by eu.mihosoft.vrl.v3d.Tetrahedron.noCenter().
properties
final PropertyStorage eu.mihosoft.vrl.v3d.Tetrahedron.properties = new PropertyStorage() private
The properties.
Definition at line 28 of file Tetrahedron.java.
Referenced by eu.mihosoft.vrl.v3d.Tetrahedron.getProperties().
radius
double eu.mihosoft.vrl.v3d.Tetrahedron.radius private
Tetrahedron circumscribed radius.
Definition at line 22 of file Tetrahedron.java.
Referenced by eu.mihosoft.vrl.v3d.Tetrahedron.getRadius(), eu.mihosoft.vrl.v3d.Tetrahedron.setRadius(), eu.mihosoft.vrl.v3d.Tetrahedron.Tetrahedron(), and eu.mihosoft.vrl.v3d.Tetrahedron.toPolygons().
The documentation for this class was generated from the following file:
JCSG/src/main/java/eu/mihosoft/vrl/v3d/Tetrahedron.java