BowlerKernel: eu.mihosoft.vrl.v3d.PropertyStorage Class Reference
eu.mihosoft.vrl.v3d.PropertyStorage Class Reference
Public Member Functions
PropertyStorage ()
void set (String key, Object property)
void delete (String key)
boolean contains (String key)
Private Attributes
final Map< String, Object > map = new HashMap<>()
Static Private Attributes
static final Color[] colors
Detailed Description
A simple property storage.
Author
Michael Hoffer <info@.nosp@m.mich.nosp@m.aelho.nosp@m.ffer.nosp@m..de>
Definition at line 47 of file PropertyStorage.java.
Constructor & Destructor Documentation
PropertyStorage()
eu.mihosoft.vrl.v3d.PropertyStorage.PropertyStorage ()
Constructor. Creates a new property storage.
Definition at line 60 of file PropertyStorage.java.
Member Function Documentation
contains()
boolean eu.mihosoft.vrl.v3d.PropertyStorage.contains (String key)
Indicates whether this storage contains the requested property.
Parameters
key key
Returns
true
if this storage contains the requested property;
false
Definition at line 109 of file PropertyStorage.java.
References eu.mihosoft.vrl.v3d.PropertyStorage.map.
delete()
void eu.mihosoft.vrl.v3d.PropertyStorage.delete (String key)
Deletes the requested property if present. Does nothing otherwise.
Parameters
key key
Definition at line 98 of file PropertyStorage.java.
References eu.mihosoft.vrl.v3d.PropertyStorage.map.
set()
void eu.mihosoft.vrl.v3d.PropertyStorage.set (String key, Object property)
Sets a property. Existing properties are overwritten.
Parameters
key key
property property
Definition at line 70 of file PropertyStorage.java.
References eu.mihosoft.vrl.v3d.PropertyStorage.map.
Member Data Documentation
colors
final Color [] eu.mihosoft.vrl.v3d.PropertyStorage.colors static private
Initial value:
= {
        Color.RED, Color.YELLOW, Color.GREEN, Color.BLUE, Color.MAGENTA,
        Color.WHITE, Color.BLACK, Color.GRAY, Color.ORANGE}
The Constant colors.
Definition at line 53 of file PropertyStorage.java.
map
final Map<String, Object> eu.mihosoft.vrl.v3d.PropertyStorage.map = new HashMap<>() private
The map.
Definition at line 50 of file PropertyStorage.java.
Referenced by eu.mihosoft.vrl.v3d.PropertyStorage.contains(), eu.mihosoft.vrl.v3d.PropertyStorage.delete(), and eu.mihosoft.vrl.v3d.PropertyStorage.set().
The documentation for this class was generated from the following file:
JCSG/src/main/java/eu/mihosoft/vrl/v3d/PropertyStorage.java