BowlerKernel: com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor Class Reference
com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor Class Reference
Public Member Functions
BezierEditor (String URL, String file, int numPoints) throws InvalidRemoteException, TransportException, GitAPIException, IOException
BezierEditor (File data, int numPoints)
ArrayList< CSG > getCSG ()
ArrayList< Object > get ()
void update ()
void setEnd (double newX, double newY, double newZ)
void setStart (double newX, double newY, double newZ)
void setCP1 (double newX, double newY, double newZ)
void setCP2 (double newX, double newY, double newZ)
void setStart (Vector3d point)
void setCP1 (Vector3d point)
void setCP2 (Vector3d point)
void setEnd (Vector3d point)
ArrayList< Transform > transforms ()
void save ()
CartesianManipulator getEndManip ()
CartesianManipulator getStartManip ()
void setStartManip (CartesianManipulator start)
void addBezierToTheEnd (BezierEditor b)
ArrayList< CSG > getPartsInternal ()
void setPartsInternal (ArrayList< CSG > partsInternal)
Private Member Functions
TransformNR updateLines (CartesianManipulator m, CartesianManipulator p, Line l, Affine poseAF)
int getNumParts ()
Private Attributes
ArrayList< CSG > partsInternal = null
CartesianManipulator endManip
CartesianManipulator start
String url
String gitfile
boolean saving
ArrayList< BezierEditor > nextBez = new ArrayList<>()
Line cp1Line = new Line()
Line cp2Line = new Line()
Affine cp1LinePose = new Affine()
Affine cp2LinePose = new Affine()
Detailed Description
Definition at line 42 of file BezierEditor.java.
Constructor & Destructor Documentation
BezierEditor() [1/2]
com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.BezierEditor (String URL, String file, int numPoints) throws InvalidRemoteException, TransportException, GitAPIException, IOException
Definition at line 69 of file BezierEditor.java.
References com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.fileFromGit(), com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.gitfile, and com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.url.
BezierEditor() [2/2]
com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.BezierEditor (File data, int numPoints)
Definition at line 76 of file BezierEditor.java.
References com.neuronrobotics.bowlerkernel.Bezier3d.CartesianManipulator.addDependant(), com.neuronrobotics.bowlerkernel.Bezier3d.CartesianManipulator.addEventListener(), com.neuronrobotics.bowlerkernel.Bezier3d.CartesianManipulator.addSaveListener(), eu.mihosoft.vrl.v3d.CSG.clone(), com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.cp1Line, com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.cp2Line, com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.cp2LinePose, com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.endManip, com.neuronrobotics.bowlerkernel.Bezier3d.CartesianManipulator.manipulationMatrix, com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.save(), com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.setPartsInternal(), com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.setStartManip(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.setX(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.setY(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.setZ(), and com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.update().
Member Function Documentation
addBezierToTheEnd()
void com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.addBezierToTheEnd (BezierEditor b)
Definition at line 392 of file BezierEditor.java.
References com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.endManip, com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.nextBez, and com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.setStartManip().
get()
ArrayList<Object> com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.get ()
Definition at line 176 of file BezierEditor.java.
References com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.cp1Line, com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.cp2Line, and com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.getCSG().
getCSG()
ArrayList<CSG> com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.getCSG ()
Definition at line 165 of file BezierEditor.java.
References com.neuronrobotics.bowlerkernel.Bezier3d.CartesianManipulator.get(), com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.getEndManip(), com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.getPartsInternal(), and com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.getStartManip().
Referenced by com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.get().
getEndManip()
CartesianManipulator com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.getEndManip ()
Definition at line 365 of file BezierEditor.java.
References com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.endManip.
Referenced by com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.getCSG(), com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.save(), and com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.transforms().
getNumParts()
int com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.getNumParts () private
Definition at line 307 of file BezierEditor.java.
References com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.getPartsInternal().
Referenced by com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.save(), com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.transforms(), and com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.update().
getPartsInternal()
ArrayList<CSG> com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.getPartsInternal ()
Definition at line 397 of file BezierEditor.java.
References com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.partsInternal.
Referenced by com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.getCSG(), com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.getNumParts(), and com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.update().
getStartManip()
CartesianManipulator com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.getStartManip ()
Definition at line 372 of file BezierEditor.java.
References com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.start.
Referenced by com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.getCSG(), com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.save(), com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.setStart(), and com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.transforms().
save()
void com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.save ()
Definition at line 311 of file BezierEditor.java.
References com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.getEndManip(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getFullBranch(), com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.getNumParts(), com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.getStartManip(), com.neuronrobotics.bowlerkernel.Bezier3d.CartesianManipulator.getX(), com.neuronrobotics.bowlerkernel.Bezier3d.CartesianManipulator.getY(), com.neuronrobotics.bowlerkernel.Bezier3d.CartesianManipulator.getZ(), com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.gitfile, com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.nextBez, com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.pushCodeToGit(), com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.saving, com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.start, and com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.url.
Referenced by com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.BezierEditor(), com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.setCP1(), com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.setCP2(), com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.setEnd(), com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.setStart(), and com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.setStartManip().
setCP1() [1/2]
void com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.setCP1 (double newX, double newY, double newZ)
Definition at line 262 of file BezierEditor.java.
References com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.save(), and com.neuronrobotics.bowlerkernel.Bezier3d.CartesianManipulator.set().
Referenced by com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.setCP1().
setCP1() [2/2]
void com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.setCP1 (Vector3d point)
Definition at line 277 of file BezierEditor.java.
References com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.setCP1(), eu.mihosoft.vrl.v3d.Vector3d.x(), eu.mihosoft.vrl.v3d.Vector3d.y(), and eu.mihosoft.vrl.v3d.Vector3d.z().
setCP2() [1/2]
void com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.setCP2 (double newX, double newY, double newZ)
Definition at line 268 of file BezierEditor.java.
References com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.save(), and com.neuronrobotics.bowlerkernel.Bezier3d.CartesianManipulator.set().
Referenced by com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.setCP2().
setCP2() [2/2]
void com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.setCP2 (Vector3d point)
Definition at line 281 of file BezierEditor.java.
References com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.setCP2(), eu.mihosoft.vrl.v3d.Vector3d.x(), eu.mihosoft.vrl.v3d.Vector3d.y(), and eu.mihosoft.vrl.v3d.Vector3d.z().
setEnd() [1/2]
void com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.setEnd (double newX, double newY, double newZ)
Definition at line 251 of file BezierEditor.java.
References com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.endManip, com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.save(), and com.neuronrobotics.bowlerkernel.Bezier3d.CartesianManipulator.set().
Referenced by com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.setEnd().
setEnd() [2/2]
void com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.setEnd (Vector3d point)
Definition at line 285 of file BezierEditor.java.
References com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.setEnd(), eu.mihosoft.vrl.v3d.Vector3d.x(), eu.mihosoft.vrl.v3d.Vector3d.y(), and eu.mihosoft.vrl.v3d.Vector3d.z().
setPartsInternal()
void com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.setPartsInternal (ArrayList< CSG > partsInternal)
Definition at line 401 of file BezierEditor.java.
References com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.partsInternal, and com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.update().
Referenced by com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.BezierEditor().
setStart() [1/2]
void com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.setStart (double newX, double newY, double newZ)
Definition at line 256 of file BezierEditor.java.
References com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.getStartManip(), com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.save(), and com.neuronrobotics.bowlerkernel.Bezier3d.CartesianManipulator.set().
Referenced by com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.setStart().
setStart() [2/2]
void com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.setStart (Vector3d point)
Definition at line 273 of file BezierEditor.java.
References com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.setStart(), eu.mihosoft.vrl.v3d.Vector3d.x(), eu.mihosoft.vrl.v3d.Vector3d.y(), and eu.mihosoft.vrl.v3d.Vector3d.z().
setStartManip()
void com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.setStartManip (CartesianManipulator start)
Definition at line 376 of file BezierEditor.java.
References com.neuronrobotics.bowlerkernel.Bezier3d.CartesianManipulator.addDependant(), com.neuronrobotics.bowlerkernel.Bezier3d.CartesianManipulator.addEventListener(), com.neuronrobotics.bowlerkernel.Bezier3d.CartesianManipulator.addSaveListener(), com.neuronrobotics.bowlerkernel.Bezier3d.CartesianManipulator.clearListeners(), com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.cp1Line, com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.cp1LinePose, com.neuronrobotics.bowlerkernel.Bezier3d.CartesianManipulator.manipulationMatrix, com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.save(), com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.start, and com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.update().
Referenced by com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.addBezierToTheEnd(), and com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.BezierEditor().
transforms()
ArrayList<Transform> com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.transforms ()
Definition at line 289 of file BezierEditor.java.
References eu.mihosoft.vrl.v3d.Extrude.bezierToTransforms(), com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.getEndManip(), com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.getNumParts(), com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.getStartManip(), com.neuronrobotics.bowlerkernel.Bezier3d.CartesianManipulator.getX(), com.neuronrobotics.bowlerkernel.Bezier3d.CartesianManipulator.getY(), and com.neuronrobotics.bowlerkernel.Bezier3d.CartesianManipulator.getZ().
Referenced by com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.update().
update()
void com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.update ()
Definition at line 186 of file BezierEditor.java.
References com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.cp1Line, com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.cp1LinePose, com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.cp2Line, com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.cp2LinePose, com.neuronrobotics.bowlerstudio.physics.TransformFactory.csgToNR(), com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.endManip, com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.getNumParts(), com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.getPartsInternal(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getX(), com.neuronrobotics.bowlerkernel.Bezier3d.CartesianManipulator.getX(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getY(), com.neuronrobotics.bowlerkernel.Bezier3d.CartesianManipulator.getY(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getZ(), com.neuronrobotics.bowlerkernel.Bezier3d.CartesianManipulator.getZ(), com.neuronrobotics.bowlerkernel.Bezier3d.CartesianManipulator.isMoving(), com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.nextBez, com.neuronrobotics.bowlerstudio.physics.TransformFactory.nrToAffine(), com.neuronrobotics.bowlerkernel.Bezier3d.CartesianManipulator.set(), com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.start, com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.times(), com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.transforms(), and com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.updateLines().
Referenced by com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.BezierEditor(), com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.setPartsInternal(), and com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.setStartManip().
updateLines()
TransformNR com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.updateLines (CartesianManipulator m, CartesianManipulator p, Line l, Affine poseAF) private
Definition at line 223 of file BezierEditor.java.
References com.neuronrobotics.bowlerkernel.Bezier3d.CartesianManipulator.getX(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getY(), com.neuronrobotics.bowlerkernel.Bezier3d.CartesianManipulator.getY(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getZ(), com.neuronrobotics.bowlerkernel.Bezier3d.CartesianManipulator.getZ(), com.neuronrobotics.bowlerstudio.physics.TransformFactory.nrToAffine(), and com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.times().
Referenced by com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.update().
Member Data Documentation
cp1Line
Line com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.cp1Line = new Line() private
Definition at line 64 of file BezierEditor.java.
Referenced by com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.BezierEditor(), com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.get(), com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.setStartManip(), and com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.update().
cp1LinePose
Affine com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.cp1LinePose = new Affine() private
Definition at line 66 of file BezierEditor.java.
Referenced by com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.setStartManip(), and com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.update().
cp2Line
Line com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.cp2Line = new Line() private
Definition at line 65 of file BezierEditor.java.
Referenced by com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.BezierEditor(), com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.get(), and com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.update().
cp2LinePose
Affine com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.cp2LinePose = new Affine() private
Definition at line 67 of file BezierEditor.java.
Referenced by com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.BezierEditor(), and com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.update().
endManip
CartesianManipulator com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.endManip private
Definition at line 54 of file BezierEditor.java.
Referenced by com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.addBezierToTheEnd(), com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.BezierEditor(), com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.getEndManip(), com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.setEnd(), and com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.update().
gitfile
String com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.gitfile private
Definition at line 61 of file BezierEditor.java.
Referenced by com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.BezierEditor(), and com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.save().
nextBez
ArrayList<BezierEditor> com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.nextBez = new ArrayList<>() private
Definition at line 63 of file BezierEditor.java.
Referenced by com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.addBezierToTheEnd(), com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.save(), and com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.update().
partsInternal
ArrayList<CSG> com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.partsInternal = null private
Definition at line 51 of file BezierEditor.java.
Referenced by com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.getPartsInternal(), and com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.setPartsInternal().
saving
boolean com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.saving private
Definition at line 62 of file BezierEditor.java.
Referenced by com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.save().
start
CartesianManipulator com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.start private
Definition at line 57 of file BezierEditor.java.
Referenced by com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.getStartManip(), com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.save(), com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.setStartManip(), and com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.update().
url
String com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.url private
Definition at line 60 of file BezierEditor.java.
Referenced by com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.BezierEditor(), and com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.save().
The documentation for this class was generated from the following file:
src/main/java/com/neuronrobotics/bowlerkernel/Bezier3d/BezierEditor.java