BowlerKernel: eu.mihosoft.vrl.v3d.Debug3dProvider Class Reference
eu.mihosoft.vrl.v3d.Debug3dProvider Class Reference
Static Public Member Functions
static void addObject (Object o)
static void clearScreen ()
static boolean isProviderAvailible ()
static void setProvider (IDebug3dProvider provider)
Detailed Description
Definition at line 3 of file Debug3dProvider.java.
Member Function Documentation
addObject()
static void eu.mihosoft.vrl.v3d.Debug3dProvider.addObject (Object o) static
Definition at line 5 of file Debug3dProvider.java.
References eu.mihosoft.vrl.v3d.IDebug3dProvider.addObject(), and eu.mihosoft.vrl.v3d.Debug3dProvider.isProviderAvailible().
Referenced by eu.mihosoft.vrl.v3d.ext.org.poly2tri.PolygonUtil.concaveToConvex(), eu.mihosoft.vrl.v3d.CSG.fixDegenerates(), and eu.mihosoft.vrl.v3d.CSG.updatePolygons().
clearScreen()
static void eu.mihosoft.vrl.v3d.Debug3dProvider.clearScreen () static
Definition at line 8 of file Debug3dProvider.java.
References eu.mihosoft.vrl.v3d.IDebug3dProvider.clearScreen(), and eu.mihosoft.vrl.v3d.Debug3dProvider.isProviderAvailible().
Referenced by eu.mihosoft.vrl.v3d.ext.org.poly2tri.PolygonUtil.concaveToConvex(), eu.mihosoft.vrl.v3d.CSG.fixDegenerates(), eu.mihosoft.vrl.v3d.CSG.triangulate(), and eu.mihosoft.vrl.v3d.CSG.updatePolygons().
isProviderAvailible()
static boolean eu.mihosoft.vrl.v3d.Debug3dProvider.isProviderAvailible () static
Definition at line 11 of file Debug3dProvider.java.
Referenced by eu.mihosoft.vrl.v3d.Debug3dProvider.addObject(), and eu.mihosoft.vrl.v3d.Debug3dProvider.clearScreen().
setProvider()
static void eu.mihosoft.vrl.v3d.Debug3dProvider.setProvider (IDebug3dProvider provider) static
Parameters
provider the provider to set
Definition at line 17 of file Debug3dProvider.java.
Referenced by eu.mihosoft.vrl.v3d.CSG.triangulate(), and eu.mihosoft.vrl.v3d.CSG.updatePolygons().
The documentation for this class was generated from the following file:
JCSG/src/main/java/eu/mihosoft/vrl/v3d/Debug3dProvider.java