BowlerKernel: eu.mihosoft.vrl.v3d.ext.openjfx.importers.Importer Class Reference
eu.mihosoft.vrl.v3d.ext.openjfx.importers.Importer Class Reference abstract
Public Member Functions
abstract void load (String url, boolean asPolygonMesh) throws IOException
abstract Group getRoot ()
abstract boolean isSupported (String supportType)
Timeline getTimeline ()
Detailed Description
The Class Importer.
Definition at line 42 of file Importer.java.
Member Function Documentation
getRoot()
abstract Group eu.mihosoft.vrl.v3d.ext.openjfx.importers.Importer.getRoot () abstract
Gets the 3D node that was loaded earlier through the load() call.
Returns
The loaded node
Reimplemented in eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjOrPolyObjImporter.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.Importer3D.loadIncludingAnimation().
getTimeline()
Timeline eu.mihosoft.vrl.v3d.ext.openjfx.importers.Importer.getTimeline ()
Can be overridden to return a timeline animation for the 3D file.
Returns
A timeline animation. Null if there is no timeline animation.
Definition at line 75 of file Importer.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.Importer3D.loadIncludingAnimation().
isSupported()
abstract boolean eu.mihosoft.vrl.v3d.ext.openjfx.importers.Importer.isSupported (String supportType) abstract
Tests if the given 3D file extension is supported (e.g. "ma", "ase", "obj", "fxml", "dae").
Parameters
supportType The file extension (e.g. "ma", "ase", "obj", "fxml", "dae")
Returns
True if the extension is of a supported type. False otherwise.
Reimplemented in eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjOrPolyObjImporter.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.Importer3D.loadIncludingAnimation().
load()
abstract void eu.mihosoft.vrl.v3d.ext.openjfx.importers.Importer.load (String url, boolean asPolygonMesh) throws IOException abstract
Loads the 3D file.
Parameters
url The url of the 3D file to load
asPolygonMesh When true load as a PolygonMesh if the loader supports.
Exceptions
IOException If issue loading file
Reimplemented in eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjOrPolyObjImporter.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.Importer3D.loadIncludingAnimation().
The documentation for this class was generated from the following file:
JCSG/src/main/java/eu/mihosoft/vrl/v3d/ext/openjfx/importers/Importer.java