BowlerKernel: com.neuronrobotics.sdk.wireless.bluetooth.BlueCoveManager Class Reference
com.neuronrobotics.sdk.wireless.bluetooth.BlueCoveManager Class Reference
Public Member Functions
BlueCoveManager ()
synchronized void find () throws MissingNativeLibraryException
void deviceDiscovered (RemoteDevice btDevice, DeviceClass cod)
synchronized void inquiryCompleted (int discType)
void servicesDiscovered (int transID, ServiceRecord[] servRecord)
synchronized void serviceSearchCompleted (int transID, int respCode)
String[] getAvailableSerialDevices (boolean refresh)
synchronized RemoteDevice getDevice (String name)
synchronized void disconnect ()
synchronized void connect (String devAddress)
synchronized DataInputStream getDataIns ()
synchronized DataOutputStream getDataOuts ()
Private Member Functions
synchronized boolean connect ()
Private Attributes
String selected = null
DataInputStream ins
DataOutputStream outs
StreamConnection conn
int searchId =0xffff
Detailed Description
The Class BlueCoveManager.
Definition at line 45 of file BlueCoveManager.java.
Constructor & Destructor Documentation
BlueCoveManager()
com.neuronrobotics.sdk.wireless.bluetooth.BlueCoveManager.BlueCoveManager ()
Instantiates a new blue cove manager.
Definition at line 74 of file BlueCoveManager.java.
Member Function Documentation
connect() [1/2]
synchronized boolean com.neuronrobotics.sdk.wireless.bluetooth.BlueCoveManager.connect () private
Connect.
Returns
true, if successful
Definition at line 248 of file BlueCoveManager.java.
References com.neuronrobotics.sdk.wireless.bluetooth.BlueCoveManager.conn, com.neuronrobotics.sdk.wireless.bluetooth.BlueCoveManager.getDevice(), com.neuronrobotics.sdk.common.Log.info(), com.neuronrobotics.sdk.wireless.bluetooth.BlueCoveManager.ins, com.neuronrobotics.sdk.wireless.bluetooth.BlueCoveManager.outs, com.neuronrobotics.sdk.wireless.bluetooth.BlueCoveManager.searchId, and com.neuronrobotics.sdk.wireless.bluetooth.BlueCoveManager.selected.
Referenced by com.neuronrobotics.sdk.wireless.bluetooth.BlueCoveManager.connect().
connect() [2/2]
synchronized void com.neuronrobotics.sdk.wireless.bluetooth.BlueCoveManager.connect (String devAddress)
Connect.
Parameters
devAddress the dev address
Definition at line 231 of file BlueCoveManager.java.
References com.neuronrobotics.sdk.wireless.bluetooth.BlueCoveManager.connect(), com.neuronrobotics.sdk.wireless.bluetooth.BlueCoveManager.find(), com.neuronrobotics.sdk.wireless.bluetooth.BlueCoveManager.getDevice(), and com.neuronrobotics.sdk.wireless.bluetooth.BlueCoveManager.selected.
Referenced by com.neuronrobotics.sdk.wireless.bluetooth.BluetoothSerialConnection.connect().
deviceDiscovered()
void com.neuronrobotics.sdk.wireless.bluetooth.BlueCoveManager.deviceDiscovered (RemoteDevice btDevice, DeviceClass cod)
Definition at line 114 of file BlueCoveManager.java.
disconnect()
synchronized void com.neuronrobotics.sdk.wireless.bluetooth.BlueCoveManager.disconnect ()
Disconnect.
Definition at line 198 of file BlueCoveManager.java.
References com.neuronrobotics.sdk.wireless.bluetooth.BlueCoveManager.conn, com.neuronrobotics.sdk.common.Log.info(), com.neuronrobotics.sdk.wireless.bluetooth.BlueCoveManager.ins, com.neuronrobotics.sdk.wireless.bluetooth.BlueCoveManager.outs, com.neuronrobotics.sdk.wireless.bluetooth.BlueCoveManager.searchId, and com.neuronrobotics.sdk.wireless.bluetooth.BlueCoveManager.selected.
Referenced by com.neuronrobotics.sdk.wireless.bluetooth.BluetoothSerialConnection.disconnect(), and com.neuronrobotics.sdk.wireless.bluetooth.BlueCoveManager.find().
find()
synchronized void com.neuronrobotics.sdk.wireless.bluetooth.BlueCoveManager.find () throws MissingNativeLibraryException
Find.
Exceptions
MissingNativeLibraryException the missing native library exception
Definition at line 82 of file BlueCoveManager.java.
References com.neuronrobotics.sdk.wireless.bluetooth.BlueCoveManager.disconnect(), com.neuronrobotics.sdk.common.Log.info(), and com.neuronrobotics.sdk.wireless.bluetooth.BlueCoveManager.selected.
Referenced by com.neuronrobotics.sdk.wireless.bluetooth.BlueCoveManager.connect(), com.neuronrobotics.sdk.wireless.bluetooth.BlueCoveManager.getAvailableSerialDevices(), and com.neuronrobotics.sdk.wireless.bluetooth.BluetoothSerialConnection.recon().
getAvailableSerialDevices()
String [] com.neuronrobotics.sdk.wireless.bluetooth.BlueCoveManager.getAvailableSerialDevices (boolean refresh)
Gets the available serial devices.
Parameters
refresh the refresh
Returns
the available serial devices
Definition at line 148 of file BlueCoveManager.java.
References com.neuronrobotics.sdk.wireless.bluetooth.BlueCoveManager.find().
Referenced by com.neuronrobotics.sdk.wireless.bluetooth.BlueCoveManager.getDevice(), and com.neuronrobotics.sdk.ui.BluetoothConnectionPanel.BluetoothSearchProcess.run().
getDataIns()
synchronized DataInputStream com.neuronrobotics.sdk.wireless.bluetooth.BlueCoveManager.getDataIns ()
Gets the data ins.
Returns
the data ins
Definition at line 308 of file BlueCoveManager.java.
References com.neuronrobotics.sdk.wireless.bluetooth.BlueCoveManager.ins, and com.neuronrobotics.sdk.wireless.bluetooth.BlueCoveManager.selected.
Referenced by com.neuronrobotics.sdk.wireless.bluetooth.BluetoothSerialConnection.connect().
getDataOuts()
synchronized DataOutputStream com.neuronrobotics.sdk.wireless.bluetooth.BlueCoveManager.getDataOuts ()
Gets the data outs.
Returns
the data outs
Definition at line 319 of file BlueCoveManager.java.
References com.neuronrobotics.sdk.wireless.bluetooth.BlueCoveManager.outs, and com.neuronrobotics.sdk.wireless.bluetooth.BlueCoveManager.selected.
Referenced by com.neuronrobotics.sdk.wireless.bluetooth.BluetoothSerialConnection.connect().
getDevice()
synchronized RemoteDevice com.neuronrobotics.sdk.wireless.bluetooth.BlueCoveManager.getDevice (String name)
Gets the device.
Parameters
name the name
Returns
the device
Definition at line 175 of file BlueCoveManager.java.
References com.neuronrobotics.sdk.wireless.bluetooth.BlueCoveManager.getAvailableSerialDevices().
Referenced by com.neuronrobotics.sdk.wireless.bluetooth.BluetoothSerialConnection.BluetoothSerialConnection(), com.neuronrobotics.sdk.wireless.bluetooth.BlueCoveManager.connect(), and com.neuronrobotics.sdk.ui.BluetoothConnectionPanel.getConnection().
inquiryCompleted()
synchronized void com.neuronrobotics.sdk.wireless.bluetooth.BlueCoveManager.inquiryCompleted (int discType)
Definition at line 122 of file BlueCoveManager.java.
servicesDiscovered()
void com.neuronrobotics.sdk.wireless.bluetooth.BlueCoveManager.servicesDiscovered (int transID, ServiceRecord[] servRecord)
Definition at line 129 of file BlueCoveManager.java.
serviceSearchCompleted()
synchronized void com.neuronrobotics.sdk.wireless.bluetooth.BlueCoveManager.serviceSearchCompleted (int transID, int respCode)
Definition at line 138 of file BlueCoveManager.java.
Member Data Documentation
conn
StreamConnection com.neuronrobotics.sdk.wireless.bluetooth.BlueCoveManager.conn private
The conn.
Definition at line 66 of file BlueCoveManager.java.
Referenced by com.neuronrobotics.sdk.wireless.bluetooth.BlueCoveManager.connect(), and com.neuronrobotics.sdk.wireless.bluetooth.BlueCoveManager.disconnect().
ins
DataInputStream com.neuronrobotics.sdk.wireless.bluetooth.BlueCoveManager.ins private
The ins.
Definition at line 60 of file BlueCoveManager.java.
Referenced by com.neuronrobotics.sdk.wireless.bluetooth.BlueCoveManager.connect(), com.neuronrobotics.sdk.wireless.bluetooth.BlueCoveManager.disconnect(), and com.neuronrobotics.sdk.wireless.bluetooth.BlueCoveManager.getDataIns().
outs
DataOutputStream com.neuronrobotics.sdk.wireless.bluetooth.BlueCoveManager.outs private
The outs.
Definition at line 63 of file BlueCoveManager.java.
Referenced by com.neuronrobotics.sdk.wireless.bluetooth.BlueCoveManager.connect(), com.neuronrobotics.sdk.wireless.bluetooth.BlueCoveManager.disconnect(), and com.neuronrobotics.sdk.wireless.bluetooth.BlueCoveManager.getDataOuts().
searchId
int com.neuronrobotics.sdk.wireless.bluetooth.BlueCoveManager.searchId =0xffff private
The search id.
Definition at line 69 of file BlueCoveManager.java.
Referenced by com.neuronrobotics.sdk.wireless.bluetooth.BlueCoveManager.connect(), and com.neuronrobotics.sdk.wireless.bluetooth.BlueCoveManager.disconnect().
selected
String com.neuronrobotics.sdk.wireless.bluetooth.BlueCoveManager.selected = null private
The selected.
Definition at line 57 of file BlueCoveManager.java.
Referenced by com.neuronrobotics.sdk.wireless.bluetooth.BlueCoveManager.connect(), com.neuronrobotics.sdk.wireless.bluetooth.BlueCoveManager.disconnect(), com.neuronrobotics.sdk.wireless.bluetooth.BlueCoveManager.find(), com.neuronrobotics.sdk.wireless.bluetooth.BlueCoveManager.getDataIns(), and com.neuronrobotics.sdk.wireless.bluetooth.BlueCoveManager.getDataOuts().
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/wireless/bluetooth/BlueCoveManager.java