BowlerKernel: com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection Class Reference
com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection Class Reference
Classes
class EventHandlingThread
enum usbControlState
Public Member Functions
UsbCDCSerialConnection (String deviceString)
UsbCDCSerialConnection (UsbDevice device)
boolean connect ()
Device findDevice (String seriualNumber)
void disconnect ()
void write (byte[] src) throws IOException
BowlerDatagram loadPacketFromPhy (ByteList bytesToPacketBuffer) throws NullPointerException, IOException
boolean waitingForConnection ()
void dataEventOccurred (UsbDeviceDataEvent arg0)
void errorEventOccurred (UsbDeviceErrorEvent arg0)
void usbDeviceDetached (UsbDeviceEvent arg0)
void onDeviceEvent (UsbDevice device)
Public Member Functions inherited from com.neuronrobotics.sdk.common.BowlerAbstractConnection
void setThreadedUpstreamPackets (boolean up)
BowlerDatagram sendSynchronusly (BowlerDatagram sendable)
synchronized BowlerDatagram sendSynchronusly (BowlerDatagram sendable, boolean switchParser)
void sendAsync (BowlerDatagram sendable) throws IOException
void setSynchronusPacketTimeoutTime (int sleepTime)
int getSleepTime ()
long msSinceLastSend ()
synchronized void setConnected (boolean c)
boolean isConnected ()
void clearLastSyncronousResponse ()
BowlerDatagram getLastSyncronousResponse ()
void onDataReceived (BowlerDatagram data)
void addDatagramListener (IBowlerDatagramListener listener)
void removeDatagramListener (IBowlerDatagramListener listener)
void setDataIns (DataInputStream dataIns)
DataInputStream getDataIns () throws NullPointerException
void setDataOuts (DataOutputStream dataOuts)
DataOutputStream getDataOuts () throws NullPointerException
void setChunkSize (int chunkSize)
int getChunkSize ()
void setAsyncQueue (QueueManager asyncQueue)
void setSyncQueue (QueueManager syncQueue)
QueueManager getAsyncQueue ()
QueueManager getSyncQueue ()
void addConnectionEventListener (IConnectionEventListener l)
void removeConnectionEventListener (IConnectionEventListener l)
void setSynchronousDatagramListener (ISynchronousDatagramListener l)
void removeSynchronousDatagramListener (ISynchronousDatagramListener l)
RpcEncapsulation locateRpc (String namespace, BowlerMethod method, String rpcString)
Object[] parseResponse (String namespace, BowlerMethod method, String rpcString, BowlerDatagram dg)
Object[] send (MACAddress addr, String namespace, BowlerMethod method, String rpcString, Object[] arguments, int retry) throws DeviceConnectionException
boolean isInitializedNamespaces ()
ArrayList< String > getNamespaces (MACAddress addr)
boolean hasNamespace (String string, MACAddress addr)
ArrayList< RpcEncapsulation > getRpcList (String namespace, MACAddress addr)
BowlerDatagram send (BowlerAbstractCommand command, MACAddress addr, int retry) throws NoConnectionAvailableException, InvalidResponseException
BowlerDatagram send (BowlerAbstractCommand command, MACAddress addr, int retry, boolean switchParser) throws NoConnectionAvailableException, InvalidResponseException
BowlerDatagram send (BowlerAbstractCommand command, MACAddress addr) throws NoConnectionAvailableException, InvalidResponseException
BowlerDatagram send (BowlerAbstractCommand command, MACAddress addr, boolean switchParser) throws NoConnectionAvailableException, InvalidResponseException
boolean ping (MACAddress mac)
boolean ping (MACAddress mac, boolean switchParser)
void startHeartBeat ()
void startHeartBeat (long msHeartBeatTime)
void stopHeartBeat ()
double getPercentagePrint ()
void setPercentagePrint (double percentagePrint)
long getLastWrite ()
void setLastWrite (long lastWrite)
boolean isUseThreadedStack ()
void setUseThreadedStack (boolean useThreadedStack)
boolean isBeater ()
void setBeater (boolean beater)
Static Public Member Functions
static void addUsbDeviceEventListener (IUsbDeviceEventListener l)
static void removeUsbDeviceEventListener (IUsbDeviceEventListener l)
static UsbDevice mapLibUsbDevicetoJavaxDevice (Device device)
static ArrayList< UsbDevice > getAllUsbBowlerDevices () throws UnsupportedEncodingException, UsbDisconnectedException, SecurityException, UsbException
static String getUniqueID (UsbDevice d) throws UnsupportedEncodingException, UsbDisconnectedException, UsbException
Static Public Member Functions inherited from com.neuronrobotics.sdk.common.BowlerAbstractConnection
static BowlerAbstractCommand getCommand (String namespace, BowlerMethod method, String rpcString, Object[] arguments, RpcEncapsulation rpc)
Private Member Functions
void setup ()
void kernelDetatch (UsbDevice mDevice)
void localDisconnect ()
void prepIrp (UsbIrp irp, byte[] data)
Static Private Member Functions
static void resetUsbSystem ()
static void dumpDevice (final UsbDevice device, ArrayList< UsbDevice > addrs) throws UnsupportedEncodingException, UsbDisconnectedException, UsbException
Private Attributes
UsbDevice mDevice
String MyDeviceString =""
UsbInterface dataInterface
UsbEndpoint dataInEndpoint
UsbEndpoint dataOutEndpoint
DeviceHandle deviceHandle
int interfaceNumber
UsbPipe camInpipe
UsbIrp read = new DefaultUsbIrp()
UsbPipe camOutpipe
UsbIrp write = new DefaultUsbIrp()
Static Private Attributes
static HotplugCallbackHandle callbackHandle
static ArrayList< IUsbDeviceEventListener > usbDeviceEventListeners = new ArrayList<IUsbDeviceEventListener>()
static EventHandlingThread thread
Additional Inherited Members
Protected Member Functions inherited from com.neuronrobotics.sdk.common.BowlerAbstractConnection
BowlerDatagram fireSyncOnReceive (BowlerDatagram datagram)
void fireAsyncOnResponse (BowlerDatagram datagram)
void waitForConnectioToBeReady ()
Detailed Description
The Class UsbCDCSerialConnection.
Definition at line 56 of file UsbCDCSerialConnection.java.
Constructor & Destructor Documentation
UsbCDCSerialConnection() [1/2]
com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.UsbCDCSerialConnection (String deviceString)
Instantiates a new usb cdc serial connection.
Parameters
deviceString the device string
Definition at line 114 of file UsbCDCSerialConnection.java.
References com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.MyDeviceString, and com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.setup().
UsbCDCSerialConnection() [2/2]
com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.UsbCDCSerialConnection (UsbDevice device)
Instantiates a new usb cdc serial connection.
Parameters
device the device
Definition at line 125 of file UsbCDCSerialConnection.java.
References com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.getUniqueID(), com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.MyDeviceString, and com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.setup().
Member Function Documentation
addUsbDeviceEventListener()
static void com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.addUsbDeviceEventListener (IUsbDeviceEventListener l) static
Adds the usb device event listener.
Parameters
l the l
Definition at line 249 of file UsbCDCSerialConnection.java.
References com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.usbDeviceEventListeners.
Referenced by com.neuronrobotics.sdk.ui.UsbConnectionPanel.UsbConnectionPanel().
connect()
boolean com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.connect ()
Attempt to establish a connection. Return if the attempt was successful.
Returns
true, if successful
Reimplemented from com.neuronrobotics.sdk.common.BowlerAbstractConnection.
Definition at line 428 of file UsbCDCSerialConnection.java.
References com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.dataInEndpoint, com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.dataInterface, com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.dataOutEndpoint, com.neuronrobotics.sdk.common.Log.error(), com.neuronrobotics.sdk.common.BowlerAbstractConnection.isConnected(), com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.kernelDetatch(), com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.localDisconnect(), com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.mDevice, com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.resetUsbSystem(), com.neuronrobotics.sdk.common.BowlerAbstractConnection.setConnected(), and com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.setup().
dataEventOccurred()
void com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.dataEventOccurred (UsbDeviceDataEvent arg0)
Definition at line 827 of file UsbCDCSerialConnection.java.
disconnect()
void com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.disconnect ()
Disconnect and deactive the current connection.
Reimplemented from com.neuronrobotics.sdk.common.BowlerAbstractConnection.
Definition at line 651 of file UsbCDCSerialConnection.java.
References com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.localDisconnect().
Referenced by com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.errorEventOccurred(), com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.loadPacketFromPhy(), com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.usbDeviceDetached(), and com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.write().
dumpDevice()
static void com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.dumpDevice (final UsbDevice device, ArrayList< UsbDevice > addrs) throws UnsupportedEncodingException, UsbDisconnectedException, UsbException static private
Dump device.
Parameters
device the device
addrs the addrs
Exceptions
UnsupportedEncodingException the unsupported encoding exception
UsbDisconnectedException the usb disconnected exception
UsbException the usb exception
Definition at line 312 of file UsbCDCSerialConnection.java.
Referenced by com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.getAllUsbBowlerDevices().
errorEventOccurred()
void com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.errorEventOccurred (UsbDeviceErrorEvent arg0)
Definition at line 836 of file UsbCDCSerialConnection.java.
References com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.disconnect(), and com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.mDevice.
findDevice()
Device com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.findDevice (String seriualNumber)
Find device.
Parameters
seriualNumber the seriual number
Returns
the device
Definition at line 520 of file UsbCDCSerialConnection.java.
Referenced by com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.kernelDetatch().
getAllUsbBowlerDevices()
static ArrayList<UsbDevice> com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.getAllUsbBowlerDevices () throws UnsupportedEncodingException, UsbDisconnectedException, SecurityException, UsbException static
Gets the all usb bowler devices.
Returns
the all usb bowler devices
Exceptions
UnsupportedEncodingException the unsupported encoding exception
UsbDisconnectedException the usb disconnected exception
SecurityException the security exception
UsbException the usb exception
Definition at line 355 of file UsbCDCSerialConnection.java.
References com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.dumpDevice().
Referenced by com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.mapLibUsbDevicetoJavaxDevice(), com.neuronrobotics.sdk.ui.UsbConnectionPanel.refresh(), and com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.setup().
getUniqueID()
static String com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.getUniqueID (UsbDevice d) throws UnsupportedEncodingException, UsbDisconnectedException, UsbException static
Gets the unique id.
Parameters
d the d
Returns
the unique id
Exceptions
UnsupportedEncodingException the unsupported encoding exception
UsbDisconnectedException the usb disconnected exception
UsbException the usb exception
Definition at line 376 of file UsbCDCSerialConnection.java.
Referenced by com.neuronrobotics.sdk.ui.UsbConnectionPanel.refresh(), com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.setup(), and com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.UsbCDCSerialConnection().
kernelDetatch()
void com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.kernelDetatch (UsbDevice mDevice) private
Kernel detatch.
Parameters
mDevice the m device
Definition at line 563 of file UsbCDCSerialConnection.java.
References com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.dataInterface, com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.deviceHandle, com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.findDevice(), com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.interfaceNumber, and com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.mDevice.
Referenced by com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.connect().
loadPacketFromPhy()
BowlerDatagram com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.loadPacketFromPhy (ByteList bytesToPacketBuffer) throws NullPointerException, IOException
Load packet from phy.
Parameters
bytesToPacketBuffer the bytes to packet buffer
Returns
the bowler datagram
Exceptions
NullPointerException the null pointer exception
IOException Signals that an I/O exception has occurred.
Reimplemented from com.neuronrobotics.sdk.common.BowlerAbstractConnection.
Definition at line 735 of file UsbCDCSerialConnection.java.
References com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.camInpipe, com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.dataInEndpoint, com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.disconnect(), com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.prepIrp(), and com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.read.
localDisconnect()
void com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.localDisconnect () private
Local disconnect.
Definition at line 600 of file UsbCDCSerialConnection.java.
References com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.camInpipe, com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.camOutpipe, com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.dataInterface, com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.deviceHandle, and com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.mDevice.
Referenced by com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.connect(), and com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.disconnect().
mapLibUsbDevicetoJavaxDevice()
static UsbDevice com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.mapLibUsbDevicetoJavaxDevice (Device device) static
Map lib usb deviceto javax device.
Parameters
device the device
Returns
the usb device
Definition at line 270 of file UsbCDCSerialConnection.java.
References com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.getAllUsbBowlerDevices().
Referenced by com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.resetUsbSystem().
onDeviceEvent()
void com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.onDeviceEvent (UsbDevice device)
On device event.
Parameters
device the device
Implements com.neuronrobotics.sdk.javaxusb.IUsbDeviceEventListener.
Definition at line 861 of file UsbCDCSerialConnection.java.
prepIrp()
void com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.prepIrp (UsbIrp irp, byte[] data) private
Prep irp.
Parameters
irp the irp
data the data
Definition at line 663 of file UsbCDCSerialConnection.java.
Referenced by com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.loadPacketFromPhy(), and com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.write().
removeUsbDeviceEventListener()
static void com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.removeUsbDeviceEventListener (IUsbDeviceEventListener l) static
Removes the usb device event listener.
Parameters
l the l
Definition at line 259 of file UsbCDCSerialConnection.java.
References com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.usbDeviceEventListeners.
resetUsbSystem()
static void com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.resetUsbSystem () static private
Reset usb system.
Definition at line 194 of file UsbCDCSerialConnection.java.
References com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.callbackHandle, com.neuronrobotics.sdk.util.OsInfoUtil.isWindows(), com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.mapLibUsbDevicetoJavaxDevice(), com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.thread, and com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.usbDeviceEventListeners.
Referenced by com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.connect().
setup()
void com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.setup () private
Setup.
Definition at line 388 of file UsbCDCSerialConnection.java.
References com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.getAllUsbBowlerDevices(), com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.getUniqueID(), and com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.MyDeviceString.
Referenced by com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.connect(), and com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.UsbCDCSerialConnection().
usbDeviceDetached()
void com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.usbDeviceDetached (UsbDeviceEvent arg0)
Definition at line 848 of file UsbCDCSerialConnection.java.
References com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.disconnect(), and com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.mDevice.
waitingForConnection()
boolean com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.waitingForConnection ()
Attempt to re-establish a connection. Return if the attempt was successful.
Returns
true, if successful Attempt to re-establish a connection. Return if the attempt was successful.
true, if successful
Reimplemented from com.neuronrobotics.sdk.common.BowlerAbstractConnection.
Definition at line 818 of file UsbCDCSerialConnection.java.
write()
void com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.write (byte[] src) throws IOException
Write.
Parameters
src the src
Exceptions
IOException Signals that an I/O exception has occurred.
Reimplemented from com.neuronrobotics.sdk.common.BowlerAbstractConnection.
Definition at line 680 of file UsbCDCSerialConnection.java.
References com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.camOutpipe, com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.dataOutEndpoint, com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.disconnect(), com.neuronrobotics.sdk.common.BowlerAbstractConnection.isConnected(), com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.prepIrp(), com.neuronrobotics.sdk.common.BowlerAbstractConnection.setLastWrite(), com.neuronrobotics.sdk.util.ThreadUtil.wait(), com.neuronrobotics.sdk.common.BowlerAbstractConnection.waitForConnectioToBeReady(), and com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.write.
Member Data Documentation
callbackHandle
HotplugCallbackHandle com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.callbackHandle static private
The callback handle.
Definition at line 98 of file UsbCDCSerialConnection.java.
Referenced by com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.resetUsbSystem().
camInpipe
UsbPipe com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.camInpipe private
The cam inpipe.
Definition at line 86 of file UsbCDCSerialConnection.java.
Referenced by com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.loadPacketFromPhy(), and com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.localDisconnect().
camOutpipe
UsbPipe com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.camOutpipe private
The cam outpipe.
Definition at line 92 of file UsbCDCSerialConnection.java.
Referenced by com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.localDisconnect(), and com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.write().
dataInEndpoint
UsbEndpoint com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.dataInEndpoint private
The data in endpoint.
Definition at line 73 of file UsbCDCSerialConnection.java.
Referenced by com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.connect(), and com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.loadPacketFromPhy().
dataInterface
UsbInterface com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.dataInterface private
The data interface.
Definition at line 70 of file UsbCDCSerialConnection.java.
Referenced by com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.connect(), com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.kernelDetatch(), and com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.localDisconnect().
dataOutEndpoint
UsbEndpoint com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.dataOutEndpoint private
The data out endpoint.
Definition at line 76 of file UsbCDCSerialConnection.java.
Referenced by com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.connect(), and com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.write().
deviceHandle
DeviceHandle com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.deviceHandle private
The device handle.
Definition at line 80 of file UsbCDCSerialConnection.java.
Referenced by com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.kernelDetatch(), and com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.localDisconnect().
interfaceNumber
int com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.interfaceNumber private
The interface number.
Definition at line 83 of file UsbCDCSerialConnection.java.
Referenced by com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.kernelDetatch().
mDevice
UsbDevice com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.mDevice private
The m device.
Definition at line 63 of file UsbCDCSerialConnection.java.
Referenced by com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.connect(), com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.errorEventOccurred(), com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.kernelDetatch(), com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.localDisconnect(), and com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.usbDeviceDetached().
MyDeviceString
String com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.MyDeviceString ="" private
The My device string.
Definition at line 66 of file UsbCDCSerialConnection.java.
Referenced by com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.setup(), and com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.UsbCDCSerialConnection().
read
UsbIrp com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.read = new DefaultUsbIrp() private
The read.
Definition at line 89 of file UsbCDCSerialConnection.java.
Referenced by com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.loadPacketFromPhy().
thread
EventHandlingThread com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.thread static private
The thread.
Definition at line 104 of file UsbCDCSerialConnection.java.
Referenced by com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.resetUsbSystem().
usbDeviceEventListeners
ArrayList<IUsbDeviceEventListener> com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.usbDeviceEventListeners = new ArrayList<IUsbDeviceEventListener>() static private
The usb device event listeners.
Definition at line 101 of file UsbCDCSerialConnection.java.
Referenced by com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.addUsbDeviceEventListener(), com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.removeUsbDeviceEventListener(), and com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.resetUsbSystem().
write
UsbIrp com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.write = new DefaultUsbIrp() private
The write.
Definition at line 95 of file UsbCDCSerialConnection.java.
Referenced by com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.write().
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/javaxusb/UsbCDCSerialConnection.java