BowlerKernel: eu.mihosoft.vrl.v3d.ext.quickhull3d.HullUtil Class Reference
eu.mihosoft.vrl.v3d.ext.quickhull3d.HullUtil Class Reference
Static Public Member Functions
static CSG hull (List<?> points)
static CSG hull (List< Vector3d > points, PropertyStorage storage)
static CSG hull (CSG csg, PropertyStorage storage)
static CSG hull (CSG... csgList)
Private Member Functions
HullUtil ()
Detailed Description
The Class HullUtil.
Author
Michael Hoffer <info@.nosp@m.mich.nosp@m.aelho.nosp@m.ffer.nosp@m..de>
Definition at line 20 of file HullUtil.java.
Constructor & Destructor Documentation
HullUtil()
eu.mihosoft.vrl.v3d.ext.quickhull3d.HullUtil.HullUtil () private
Instantiates a new hull util.
Definition at line 25 of file HullUtil.java.
Member Function Documentation
hull() [1/4]
static CSG eu.mihosoft.vrl.v3d.ext.quickhull3d.HullUtil.hull (CSG csg, PropertyStorage storage) static
Hull.
Parameters
csg the csg
storage the storage
Returns
the csg
Definition at line 97 of file HullUtil.java.
References eu.mihosoft.vrl.v3d.CSG.getPolygons(), and eu.mihosoft.vrl.v3d.ext.quickhull3d.HullUtil.hull().
hull() [2/4]
static CSG eu.mihosoft.vrl.v3d.ext.quickhull3d.HullUtil.hull (CSG... csgList) static
Hull.
Parameters
csgList a list of csg
Returns
the csg
Definition at line 113 of file HullUtil.java.
References eu.mihosoft.vrl.v3d.ext.quickhull3d.HullUtil.hull().
hull() [3/4]
static CSG eu.mihosoft.vrl.v3d.ext.quickhull3d.HullUtil.hull (List< Vector3d > points, PropertyStorage storage) static
Hull.
Parameters
points the points
storage the storage
Returns
the csg
Definition at line 60 of file HullUtil.java.
References eu.mihosoft.vrl.v3d.Polygon.fromPoints(), eu.mihosoft.vrl.v3d.CSG.fromPolygons(), eu.mihosoft.vrl.v3d.ext.quickhull3d.HullUtil.hull(), and eu.mihosoft.vrl.v3d.CSG.triangulate().
hull() [4/4]
static CSG eu.mihosoft.vrl.v3d.ext.quickhull3d.HullUtil.hull (List<?> points) static
Hull.
Parameters
points the points
Returns
the csg
Definition at line 36 of file HullUtil.java.
Referenced by eu.mihosoft.vrl.v3d.Extrude.bezier(), eu.mihosoft.vrl.v3d.CSG.hull(), eu.mihosoft.vrl.v3d.Extrude.hull(), eu.mihosoft.vrl.v3d.ext.quickhull3d.HullUtil.hull(), eu.mihosoft.vrl.v3d.CSG.hullAll(), eu.mihosoft.vrl.v3d.CSG.minkowskiHullShape(), eu.mihosoft.vrl.v3d.Dodecahedron.toPolygons(), eu.mihosoft.vrl.v3d.Icosahedron.toPolygons(), eu.mihosoft.vrl.v3d.Octahedron.toPolygons(), eu.mihosoft.vrl.v3d.RoundedCylinder.toPolygons(), and eu.mihosoft.vrl.v3d.Tetrahedron.toPolygons().
The documentation for this class was generated from the following file:
JCSG/src/main/java/eu/mihosoft/vrl/v3d/ext/quickhull3d/HullUtil.java