BowlerKernel: com.neuronrobotics.sdk.bowlercam.device.ItemMarker Class Reference
com.neuronrobotics.sdk.bowlercam.device.ItemMarker Class Reference
Public Member Functions
ItemMarker (int x, int y, int radius)
void setX (int x)
int getX ()
void setY (int y)
int getY ()
void setRadius (int radius)
int getRadius ()
String toString ()
Private Attributes
int x
int y
int radius
Detailed Description
The Class ItemMarker.
Definition at line 7 of file ItemMarker.java.
Constructor & Destructor Documentation
ItemMarker()
com.neuronrobotics.sdk.bowlercam.device.ItemMarker.ItemMarker (int x, int y, int radius)
Instantiates a new item marker.
Parameters
x the x
y the y
radius the radius
Definition at line 25 of file ItemMarker.java.
References com.neuronrobotics.sdk.bowlercam.device.ItemMarker.radius, com.neuronrobotics.sdk.bowlercam.device.ItemMarker.setRadius(), com.neuronrobotics.sdk.bowlercam.device.ItemMarker.setX(), com.neuronrobotics.sdk.bowlercam.device.ItemMarker.setY(), com.neuronrobotics.sdk.bowlercam.device.ItemMarker.x, and com.neuronrobotics.sdk.bowlercam.device.ItemMarker.y.
Member Function Documentation
getRadius()
int com.neuronrobotics.sdk.bowlercam.device.ItemMarker.getRadius ()
Gets the radius.
Returns
the radius
Definition at line 81 of file ItemMarker.java.
References com.neuronrobotics.sdk.bowlercam.device.ItemMarker.radius.
getX()
int com.neuronrobotics.sdk.bowlercam.device.ItemMarker.getX ()
Gets the x.
Returns
the x
Definition at line 45 of file ItemMarker.java.
References com.neuronrobotics.sdk.bowlercam.device.ItemMarker.x.
getY()
int com.neuronrobotics.sdk.bowlercam.device.ItemMarker.getY ()
Gets the y.
Returns
the y
Definition at line 63 of file ItemMarker.java.
References com.neuronrobotics.sdk.bowlercam.device.ItemMarker.y.
setRadius()
void com.neuronrobotics.sdk.bowlercam.device.ItemMarker.setRadius (int radius)
Sets the radius.
Parameters
radius the new radius
Definition at line 72 of file ItemMarker.java.
References com.neuronrobotics.sdk.bowlercam.device.ItemMarker.radius.
Referenced by com.neuronrobotics.sdk.bowlercam.device.ItemMarker.ItemMarker().
setX()
void com.neuronrobotics.sdk.bowlercam.device.ItemMarker.setX (int x)
Sets the x.
Parameters
x the new x
Definition at line 36 of file ItemMarker.java.
References com.neuronrobotics.sdk.bowlercam.device.ItemMarker.x.
Referenced by com.neuronrobotics.sdk.bowlercam.device.ItemMarker.ItemMarker().
setY()
void com.neuronrobotics.sdk.bowlercam.device.ItemMarker.setY (int y)
Sets the y.
Parameters
y the new y
Definition at line 54 of file ItemMarker.java.
References com.neuronrobotics.sdk.bowlercam.device.ItemMarker.y.
Referenced by com.neuronrobotics.sdk.bowlercam.device.ItemMarker.ItemMarker().
toString()
String com.neuronrobotics.sdk.bowlercam.device.ItemMarker.toString ()
Definition at line 89 of file ItemMarker.java.
References com.neuronrobotics.sdk.bowlercam.device.ItemMarker.radius, com.neuronrobotics.sdk.bowlercam.device.ItemMarker.x, and com.neuronrobotics.sdk.bowlercam.device.ItemMarker.y.
Member Data Documentation
radius
int com.neuronrobotics.sdk.bowlercam.device.ItemMarker.radius private
The radius.
Definition at line 16 of file ItemMarker.java.
Referenced by com.neuronrobotics.sdk.bowlercam.device.ItemMarker.getRadius(), com.neuronrobotics.sdk.bowlercam.device.ItemMarker.ItemMarker(), com.neuronrobotics.sdk.bowlercam.device.ItemMarker.setRadius(), and com.neuronrobotics.sdk.bowlercam.device.ItemMarker.toString().
x
int com.neuronrobotics.sdk.bowlercam.device.ItemMarker.x private
The x.
Definition at line 10 of file ItemMarker.java.
Referenced by com.neuronrobotics.sdk.bowlercam.device.ItemMarker.getX(), com.neuronrobotics.sdk.bowlercam.device.ItemMarker.ItemMarker(), com.neuronrobotics.sdk.bowlercam.device.ItemMarker.setX(), and com.neuronrobotics.sdk.bowlercam.device.ItemMarker.toString().
y
int com.neuronrobotics.sdk.bowlercam.device.ItemMarker.y private
The y.
Definition at line 13 of file ItemMarker.java.
Referenced by com.neuronrobotics.sdk.bowlercam.device.ItemMarker.getY(), com.neuronrobotics.sdk.bowlercam.device.ItemMarker.ItemMarker(), com.neuronrobotics.sdk.bowlercam.device.ItemMarker.setY(), and com.neuronrobotics.sdk.bowlercam.device.ItemMarker.toString().
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/bowlercam/device/ItemMarker.java