BowlerKernel: com.neuronrobotics.bowlerstudio.vitamins.VitaminBomManager Class Reference
com.neuronrobotics.bowlerstudio.vitamins.VitaminBomManager Class Reference
Classes
class VitaminElement
Public Member Functions
VitaminBomManager (String url) throws IOException
void set (String name, String type, String size, TransformNR location)
CSG get (String name)
TransformNR getCoMLocation (String name)
double getMassKg (String name)
Map< String, Object > getConfiguration (String name)
void clear ()
void save ()
Static Public Attributes
static final String MANUFACTURING_BOM_BASE = "manufacturing/bom"
static final String MANUFACTURING_BOM_JSON = MANUFACTURING_BOM_BASE + ".json"
static final String MANUFACTURING_BOM_CSV = MANUFACTURING_BOM_BASE + ".csv"
Private Member Functions
VitaminElement getElement (String name)
void saveLocal ()
void write (String file, String content) throws InvalidRemoteException, TransportException, GitAPIException, IOException
Private Attributes
HashMap< String, ArrayList< VitaminElement > > database = null
String baseURL
Static Private Attributes
static boolean saving = false
Detailed Description
Definition at line 29 of file VitaminBomManager.java.
Constructor & Destructor Documentation
VitaminBomManager()
com.neuronrobotics.bowlerstudio.vitamins.VitaminBomManager.VitaminBomManager (String url) throws IOException
Definition at line 48 of file VitaminBomManager.java.
References com.neuronrobotics.bowlerstudio.vitamins.VitaminBomManager.baseURL, com.neuronrobotics.bowlerstudio.vitamins.VitaminBomManager.database, com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getRepositoryCloneDirectory(), com.neuronrobotics.bowlerstudio.vitamins.VitaminBomManager.MANUFACTURING_BOM_JSON, and com.neuronrobotics.bowlerstudio.vitamins.VitaminBomManager.save().
Member Function Documentation
clear()
void com.neuronrobotics.bowlerstudio.vitamins.VitaminBomManager.clear ()
Definition at line 157 of file VitaminBomManager.java.
References com.neuronrobotics.bowlerstudio.vitamins.VitaminBomManager.database.
get()
CSG com.neuronrobotics.bowlerstudio.vitamins.VitaminBomManager.get (String name)
Definition at line 102 of file VitaminBomManager.java.
References com.neuronrobotics.bowlerstudio.vitamins.Vitamins.get(), com.neuronrobotics.bowlerstudio.vitamins.VitaminBomManager.getElement(), com.neuronrobotics.bowlerstudio.physics.TransformFactory.nrToCSG(), eu.mihosoft.vrl.v3d.CSG.setColor(), eu.mihosoft.vrl.v3d.CSG.setManufacturing(), and eu.mihosoft.vrl.v3d.CSG.transformed().
getCoMLocation()
TransformNR com.neuronrobotics.bowlerstudio.vitamins.VitaminBomManager.getCoMLocation (String name)
Definition at line 122 of file VitaminBomManager.java.
References com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.copy(), com.neuronrobotics.bowlerstudio.vitamins.VitaminBomManager.getConfiguration(), com.neuronrobotics.bowlerstudio.vitamins.VitaminBomManager.getElement(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.translateX(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.translateY(), and com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.translateZ().
getConfiguration()
Map<String, Object> com.neuronrobotics.bowlerstudio.vitamins.VitaminBomManager.getConfiguration (String name)
Definition at line 136 of file VitaminBomManager.java.
References com.neuronrobotics.bowlerstudio.vitamins.Vitamins.getConfiguration(), and com.neuronrobotics.bowlerstudio.vitamins.VitaminBomManager.getElement().
Referenced by com.neuronrobotics.bowlerstudio.vitamins.VitaminBomManager.getCoMLocation(), com.neuronrobotics.bowlerstudio.vitamins.VitaminBomManager.getMassKg(), and com.neuronrobotics.bowlerstudio.vitamins.VitaminBomManager.saveLocal().
getElement()
VitaminElement com.neuronrobotics.bowlerstudio.vitamins.VitaminBomManager.getElement (String name) private
Definition at line 144 of file VitaminBomManager.java.
References com.neuronrobotics.bowlerstudio.vitamins.VitaminBomManager.database.
Referenced by com.neuronrobotics.bowlerstudio.vitamins.VitaminBomManager.get(), com.neuronrobotics.bowlerstudio.vitamins.VitaminBomManager.getCoMLocation(), com.neuronrobotics.bowlerstudio.vitamins.VitaminBomManager.getConfiguration(), and com.neuronrobotics.bowlerstudio.vitamins.VitaminBomManager.set().
getMassKg()
double com.neuronrobotics.bowlerstudio.vitamins.VitaminBomManager.getMassKg (String name)
Definition at line 132 of file VitaminBomManager.java.
References com.neuronrobotics.bowlerstudio.vitamins.VitaminBomManager.getConfiguration().
save()
void com.neuronrobotics.bowlerstudio.vitamins.VitaminBomManager.save ()
Definition at line 223 of file VitaminBomManager.java.
References com.neuronrobotics.bowlerstudio.vitamins.VitaminBomManager.saveLocal().
Referenced by com.neuronrobotics.bowlerstudio.vitamins.VitaminBomManager.set(), and com.neuronrobotics.bowlerstudio.vitamins.VitaminBomManager.VitaminBomManager().
saveLocal()
void com.neuronrobotics.bowlerstudio.vitamins.VitaminBomManager.saveLocal () private
Definition at line 163 of file VitaminBomManager.java.
References com.neuronrobotics.bowlerstudio.vitamins.VitaminBomManager.baseURL, com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.codeFromGit(), com.neuronrobotics.bowlerstudio.vitamins.VitaminBomManager.database, com.neuronrobotics.bowlerstudio.vitamins.VitaminBomManager.getConfiguration(), com.neuronrobotics.bowlerstudio.vitamins.VitaminBomManager.MANUFACTURING_BOM_CSV, com.neuronrobotics.bowlerstudio.vitamins.VitaminBomManager.MANUFACTURING_BOM_JSON, com.neuronrobotics.bowlerstudio.vitamins.VitaminBomManager.saving, and com.neuronrobotics.bowlerstudio.vitamins.VitaminBomManager.write().
Referenced by com.neuronrobotics.bowlerstudio.vitamins.VitaminBomManager.save().
set()
void com.neuronrobotics.bowlerstudio.vitamins.VitaminBomManager.set (String name, String type, String size, TransformNR location)
Definition at line 79 of file VitaminBomManager.java.
References com.neuronrobotics.bowlerstudio.vitamins.VitaminBomManager.database, com.neuronrobotics.bowlerstudio.vitamins.VitaminBomManager.getElement(), and com.neuronrobotics.bowlerstudio.vitamins.VitaminBomManager.save().
write()
void com.neuronrobotics.bowlerstudio.vitamins.VitaminBomManager.write (String file, String content) throws InvalidRemoteException, TransportException, GitAPIException, IOException private
Definition at line 210 of file VitaminBomManager.java.
References com.neuronrobotics.bowlerstudio.vitamins.VitaminBomManager.baseURL, and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.fileFromGit().
Referenced by com.neuronrobotics.bowlerstudio.vitamins.VitaminBomManager.saveLocal().
Member Data Documentation
baseURL
String com.neuronrobotics.bowlerstudio.vitamins.VitaminBomManager.baseURL private
Definition at line 46 of file VitaminBomManager.java.
Referenced by com.neuronrobotics.bowlerstudio.vitamins.VitaminBomManager.saveLocal(), com.neuronrobotics.bowlerstudio.vitamins.VitaminBomManager.VitaminBomManager(), and com.neuronrobotics.bowlerstudio.vitamins.VitaminBomManager.write().
database
HashMap<String, ArrayList<VitaminElement> > com.neuronrobotics.bowlerstudio.vitamins.VitaminBomManager.database = null private
Definition at line 45 of file VitaminBomManager.java.
Referenced by com.neuronrobotics.bowlerstudio.vitamins.VitaminBomManager.clear(), com.neuronrobotics.bowlerstudio.vitamins.VitaminBomManager.getElement(), com.neuronrobotics.bowlerstudio.vitamins.VitaminBomManager.saveLocal(), com.neuronrobotics.bowlerstudio.vitamins.VitaminBomManager.set(), and com.neuronrobotics.bowlerstudio.vitamins.VitaminBomManager.VitaminBomManager().
MANUFACTURING_BOM_BASE
final String com.neuronrobotics.bowlerstudio.vitamins.VitaminBomManager.MANUFACTURING_BOM_BASE = "manufacturing/bom" static
Definition at line 30 of file VitaminBomManager.java.
MANUFACTURING_BOM_CSV
final String com.neuronrobotics.bowlerstudio.vitamins.VitaminBomManager.MANUFACTURING_BOM_CSV = MANUFACTURING_BOM_BASE + ".csv" static
Definition at line 32 of file VitaminBomManager.java.
Referenced by com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getPrintBed(), com.neuronrobotics.bowlerstudio.BowlerKernel.processReturnedObjectsStart(), and com.neuronrobotics.bowlerstudio.vitamins.VitaminBomManager.saveLocal().
MANUFACTURING_BOM_JSON
final String com.neuronrobotics.bowlerstudio.vitamins.VitaminBomManager.MANUFACTURING_BOM_JSON = MANUFACTURING_BOM_BASE + ".json" static
Definition at line 31 of file VitaminBomManager.java.
Referenced by com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getPrintBed(), com.neuronrobotics.bowlerstudio.BowlerKernel.processReturnedObjectsStart(), com.neuronrobotics.bowlerstudio.vitamins.VitaminBomManager.saveLocal(), and com.neuronrobotics.bowlerstudio.vitamins.VitaminBomManager.VitaminBomManager().
saving
boolean com.neuronrobotics.bowlerstudio.vitamins.VitaminBomManager.saving = false static private
Definition at line 33 of file VitaminBomManager.java.
Referenced by com.neuronrobotics.bowlerstudio.vitamins.VitaminBomManager.saveLocal().
The documentation for this class was generated from the following file:
src/main/java/com/neuronrobotics/bowlerstudio/vitamins/VitaminBomManager.java