BowlerKernel: com.neuronrobotics.sdk.addons.kinematics.WristNormalizer Class Reference
com.neuronrobotics.sdk.addons.kinematics.WristNormalizer Class Reference
Static Public Member Functions
static double[] normalize (double[] calculated, double[] current, DHChain chain)
static boolean isStrictMode ()
static void setBoundLinkValueMode ()
static void setStrictMode ()
Static Private Member Functions
static double[] option (double w1, double w2, double w3)
static void score (double[] calculated, double[] current, HashMap< double[], Double > scores, AbstractKinematicsNR kin)
Static Private Attributes
static boolean strictMode = false
Detailed Description
Definition at line 5 of file WristNormalizer.java.
Member Function Documentation
isStrictMode()
static boolean com.neuronrobotics.sdk.addons.kinematics.WristNormalizer.isStrictMode () static
Definition at line 87 of file WristNormalizer.java.
References com.neuronrobotics.sdk.addons.kinematics.WristNormalizer.strictMode.
normalize()
static double [] com.neuronrobotics.sdk.addons.kinematics.WristNormalizer.normalize (double[] calculated, double[] current, DHChain chain) static
Definition at line 8 of file WristNormalizer.java.
References com.neuronrobotics.sdk.addons.kinematics.DHChain.kin, com.neuronrobotics.sdk.addons.kinematics.WristNormalizer.option(), com.neuronrobotics.sdk.addons.kinematics.WristNormalizer.score(), and com.neuronrobotics.sdk.addons.kinematics.WristNormalizer.strictMode.
option()
static double [] com.neuronrobotics.sdk.addons.kinematics.WristNormalizer.option (double w1, double w2, double w3) static private
Definition at line 61 of file WristNormalizer.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.WristNormalizer.normalize().
score()
static void com.neuronrobotics.sdk.addons.kinematics.WristNormalizer.score (double[] calculated, double[] current, HashMap< double[], Double > scores, AbstractKinematicsNR kin) static private
Definition at line 65 of file WristNormalizer.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getMaxEngineeringUnits(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getMinEngineeringUnits(), and com.neuronrobotics.sdk.addons.kinematics.WristNormalizer.strictMode.
Referenced by com.neuronrobotics.sdk.addons.kinematics.WristNormalizer.normalize().
setBoundLinkValueMode()
static void com.neuronrobotics.sdk.addons.kinematics.WristNormalizer.setBoundLinkValueMode () static
Definition at line 90 of file WristNormalizer.java.
References com.neuronrobotics.sdk.addons.kinematics.WristNormalizer.strictMode.
setStrictMode()
static void com.neuronrobotics.sdk.addons.kinematics.WristNormalizer.setStrictMode () static
Definition at line 93 of file WristNormalizer.java.
References com.neuronrobotics.sdk.addons.kinematics.WristNormalizer.strictMode.
Member Data Documentation
strictMode
boolean com.neuronrobotics.sdk.addons.kinematics.WristNormalizer.strictMode = false static private
Definition at line 6 of file WristNormalizer.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.WristNormalizer.isStrictMode(), com.neuronrobotics.sdk.addons.kinematics.WristNormalizer.normalize(), com.neuronrobotics.sdk.addons.kinematics.WristNormalizer.score(), com.neuronrobotics.sdk.addons.kinematics.WristNormalizer.setBoundLinkValueMode(), and com.neuronrobotics.sdk.addons.kinematics.WristNormalizer.setStrictMode().
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/addons/kinematics/WristNormalizer.java