BowlerKernel: com.neuronrobotics.sdk.addons.kinematics.GenericKinematicsModelNR Class Reference
com.neuronrobotics.sdk.addons.kinematics.GenericKinematicsModelNR Class Reference
Public Member Functions
GenericKinematicsModelNR (InputStream configFile, GenericPIDDevice device)
GenericKinematicsModelNR ()
TransformNR forwardKinematics (double[] jointSpaceVector)
double[] inverseKinematics (TransformNR cartesianSpaceVector) throws Exception
void disconnectDevice ()
boolean connectDevice ()
Public Member Functions inherited from com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR
Object getRootListener ()
void setRootListener (Object listener)
ArrayList< String > getNamespacesImp ()
void disconnectDeviceImp ()
boolean connectDeviceImp ()
AbstractKinematicsNR ()
AbstractKinematicsNR (InputStream configFile, LinkFactory f)
AbstractKinematicsNR (Element doc, LinkFactory f)
String getXml ()
LinkConfiguration getLinkConfiguration (int linkIndex)
ArrayList< LinkConfiguration > getLinkConfigurations ()
PIDConfiguration getLinkCurrentConfiguration (int chan)
void setLinkCurrentConfiguration (int chan, PIDConfiguration c)
AbstractLink getAbstractLink (int index)
int getNumberOfLinks ()
TransformNR getCurrentTaskSpaceTransform ()
double readLinkValue (int index)
double readLinkTarget (int index)
double[] getCurrentJointSpaceVector ()
double[] getCurrentJointSpaceTarget ()
double getCurrentLinkEngineeringUnits (int linkIndex)
double[] setDesiredTaskSpaceTransform (TransformNR taskSpaceTransform, double seconds) throws Exception
boolean checkTaskSpaceTransform (TransformNR taskSpaceTransform, double seconds)
boolean checkTaskSpaceTransform (TransformNR taskSpaceTransform)
double getBestTime (TransformNR currentTaskSpaceTransform)
double getBestTime (double[] jointSpaceVect)
double[] setDesiredJointSpaceVector (double[] jointSpaceVect, double seconds) throws Exception
TransformNR calcForward (double[] jointSpaceVect)
TransformNR calcHome ()
void setDesiredJointAxisValue (int axis, double value, double seconds) throws Exception
void firePoseUpdate ()
TransformNR getFiducialToGlobalTransform ()
void setRobotToFiducialTransform (TransformNR baseToFiducial)
TransformNR getRobotToFiducialTransform ()
void setGlobalToFiducialTransform (TransformNR frameToBase, boolean fireUpdate)
void setGlobalToFiducialTransform (TransformNR frameToBase)
TransformNR inverseOffset (TransformNR t)
TransformNR forwardOffset (TransformNR t)
void addJointSpaceListener (IJointSpaceUpdateListenerNR l)
void removeJointSpaceUpdateListener (IJointSpaceUpdateListenerNR l)
void addRegistrationListener (IRegistrationListenerNR l)
void removeRegestrationUpdateListener (IRegistrationListenerNR l)
void addPoseUpdateListener (ITaskSpaceUpdateListenerNR l)
void removePoseUpdateListener (ITaskSpaceUpdateListenerNR l)
void onLinkPositionUpdate (AbstractLink source, double engineeringUnitsValue)
void onPIDEvent (PIDEvent e)
void onPIDLimitEvent (PIDLimitEvent e)
void onPIDReset (int group, float currentValue)
void homeAllLinks ()
void homeLink (int link)
void emergencyStop ()
ArrayList< PIDConfiguration > getAxisPidConfiguration ()
TransformNR getCurrentPoseTarget ()
void setCurrentPoseTarget (TransformNR currentPoseTarget)
void setFactory (LinkFactory factory)
LinkFactory getFactory ()
void setNoFlush (boolean noFlush)
boolean isNoFlush ()
int getRetryNumberBeforeFail ()
void setRetryNumberBeforeFail (int retryNumberBeforeFail)
void onLinkLimit (AbstractLink arg0, PIDLimitEvent arg1)
DHChain getDhParametersChain ()
void setDhParametersChain (DHChain dhParametersChain)
String[] getGitDhEngine ()
void setGitDhEngine (String[] dhEngine)
String[] getGitCadEngine ()
void setGitCadEngine (String[] cadEngine)
IMU getImu ()
void boundedLinkValueSet (int index, double value) throws Exception
double boundToLinkLimits (int index, double value)
double linkMass (int linkIndex)
double getMaxEngineeringUnits (int linkIndex)
double getMinEngineeringUnits (int linkIndex)
void setMaxEngineeringUnits (int linkIndex, double maxLimit)
void setMinEngineeringUnits (int linkIndex, double minLimit)
String getElectroMechanicalType (int linkIndex)
void setElectroMechanicalType (int linkIndex, String electroMechanicalType)
String getElectroMechanicalSize (int linkIndex)
void setElectroMechanicalSize (int linkIndex, String electroMechanicalSize)
String getShaftType (int linkIndex)
void setShaftType (int linkIndex, String shaftType)
String getShaftSize (int linkIndex)
void setDeviceMaximumValue (int linkIndex, double max)
void setDeviceMinimumValue (int linkIndex, double min)
double getDeviceMaximumValue (int linkIndex)
double getDeviceMinimumValue (int linkIndex)
void addChangeListener (int linkIndex, ILinkConfigurationChangeListener l)
void removeChangeListener (int linkIndex, ILinkConfigurationChangeListener l)
void clearChangeListener (int linkIndex)
void runRenderWrangler ()
void setRenderWrangler (Runnable renderWrangler)
TransformNR getDeltaToTarget (TransformNR target)
TransformNR getTipAlongTrajectory (TransformNR startingPoint, TransformNR deltaToTarget, double unitIncrement)
void asyncInterpolatedMove (TransformNR target, double seconds, InterpolationType type, IOnInterpolationDone listener, double ...conf)
InterpolationMoveState blockingInterpolatedMove (TransformNR target, double seconds, InterpolationType type, double ...conf)
Public Member Functions inherited from com.neuronrobotics.sdk.common.NonBowlerDevice
boolean connect ()
boolean isAvailable () throws InvalidConnectionException
void disconnect ()
void onAsyncResponse (BowlerDatagram data)
ArrayList< String > getNamespaces ()
Public Member Functions inherited from com.neuronrobotics.sdk.common.BowlerAbstractDevice
void addConnectionEventListener (final IDeviceConnectionEventListener l)
void removeConnectionEventListener (IDeviceConnectionEventListener l)
void setConnection (BowlerAbstractConnection connection)
BowlerAbstractConnection getConnection ()
void setAddress (MACAddress address)
MACAddress getAddress ()
BowlerDatagram send (BowlerAbstractCommand command) throws NoConnectionAvailableException, InvalidResponseException
BowlerDatagram send (BowlerAbstractCommand command, int retry) throws NoConnectionAvailableException, InvalidResponseException
Object[] send (String namespace, BowlerMethod method, String rpcString, Object[] arguments, int retry) throws DeviceConnectionException
Object[] send (String namespace, BowlerMethod method, String rpcString, Object[] arguments) throws DeviceConnectionException
boolean ping ()
boolean ping (boolean switchParser)
ArrayList< ByteList > getRevisions ()
boolean hasNamespace (String string)
void startHeartBeat ()
void startHeartBeat (long msHeartBeatTime)
void stopHeartBeat ()
void setThreadedUpstreamPackets (boolean up)
ArrayList< RpcEncapsulation > getRpcList (String namespace)
void loadRpcList ()
void onAllResponse (BowlerDatagram data)
boolean isKeepAlive ()
void setKeepAlive (boolean keepAlive)
long getLastPacketTime ()
void setLastPacketTime (long lastPacketTime)
String getScriptingName ()
void setScriptingName (String scriptingName)
ArrayList< IDeviceConnectionEventListener > getDisconnectListeners ()
Additional Inherited Members
Static Public Member Functions inherited from com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR
static boolean checkTaskSpaceTransform (AbstractKinematicsNR dev, TransformNR taskSpaceTransform, double seconds)
static boolean checkTaskSpaceTransform (AbstractKinematicsNR dev, TransformNR taskSpaceTransform)
Protected Member Functions inherited from com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR
ArrayList< LinkConfiguration > loadConfig (Element doc)
LinkFactory getDevice ()
void setDevice (LinkFactory f, ArrayList< LinkConfiguration > linkConfigs)
void firePoseTransform (TransformNR transform)
void fireTargetJointsUpdate (double[] jointSpaceVector, TransformNR fwd)
String getCode (Element e, String tag)
String[] getGitCodes (Element doc, String tag)
Protected Member Functions inherited from com.neuronrobotics.sdk.common.BowlerAbstractDevice
void fireDisconnectEvent ()
void fireConnectEvent ()
Protected Attributes inherited from com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR
ArrayList< IJointSpaceUpdateListenerNR > jointSpaceUpdateListeners = new ArrayList<IJointSpaceUpdateListenerNR>()
Detailed Description
The Class GenericKinematicsModelNR.
Definition at line 20 of file GenericKinematicsModelNR.java.
Constructor & Destructor Documentation
GenericKinematicsModelNR() [1/2]
com.neuronrobotics.sdk.addons.kinematics.GenericKinematicsModelNR.GenericKinematicsModelNR (InputStream configFile, GenericPIDDevice device)
Instantiates a new generic kinematics model nr.
Parameters
configFile the config file
device the device
Definition at line 31 of file GenericKinematicsModelNR.java.
GenericKinematicsModelNR() [2/2]
com.neuronrobotics.sdk.addons.kinematics.GenericKinematicsModelNR.GenericKinematicsModelNR ()
Instantiates a new generic kinematics model nr.
Definition at line 41 of file GenericKinematicsModelNR.java.
References com.neuronrobotics.sdk.addons.kinematics.xml.XmlFactory.getDefaultConfigurationStream().
Member Function Documentation
connectDevice()
boolean com.neuronrobotics.sdk.addons.kinematics.GenericKinematicsModelNR.connectDevice ()
Connect device.
Returns
true, if successful
Reimplemented from com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.
Definition at line 103 of file GenericKinematicsModelNR.java.
disconnectDevice()
void com.neuronrobotics.sdk.addons.kinematics.GenericKinematicsModelNR.disconnectDevice ()
This method tells the connection object to disconnect its pipes and close out the connection. Once this is called, it is safe to remove your device.
Reimplemented from com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.
Definition at line 94 of file GenericKinematicsModelNR.java.
forwardKinematics()
TransformNR com.neuronrobotics.sdk.addons.kinematics.GenericKinematicsModelNR.forwardKinematics (double[] jointSpaceVector)
Forward kinematics.
Parameters
jointSpaceVector the joint space vector
Returns
6x1 vector in task space, unit in mm,radians [x,y,z,rotx,rotY,rotZ]
Reimplemented from com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.
Definition at line 49 of file GenericKinematicsModelNR.java.
References com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.getRotationMatrix(), com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.getRotationX(), com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.getRotationY(), and com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.getRotationZ().
inverseKinematics()
double [] com.neuronrobotics.sdk.addons.kinematics.GenericKinematicsModelNR.inverseKinematics (TransformNR taskSpaceTransform) throws Exception
Inverse kinematics.
Parameters
taskSpaceTransform the task space transform
Returns
Nx1 vector in task space, in mm where N is number of links
Exceptions
Exception the exception
Reimplemented from com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.
Definition at line 72 of file GenericKinematicsModelNR.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getNumberOfLinks().
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/addons/kinematics/GenericKinematicsModelNR.java