BowlerKernel: com.neuronrobotics.sdk.common.BowlerAbstractDevice Class Reference
com.neuronrobotics.sdk.common.BowlerAbstractDevice Class Reference abstract
Public Member Functions
boolean isAvailable () throws InvalidConnectionException
void addConnectionEventListener (final IDeviceConnectionEventListener l)
void removeConnectionEventListener (IDeviceConnectionEventListener l)
void setConnection (BowlerAbstractConnection connection)
boolean connect () throws InvalidConnectionException
void disconnect ()
BowlerAbstractConnection getConnection ()
void setAddress (MACAddress address)
MACAddress getAddress ()
BowlerDatagram send (BowlerAbstractCommand command) throws NoConnectionAvailableException, InvalidResponseException
BowlerDatagram send (BowlerAbstractCommand command, int retry) throws NoConnectionAvailableException, InvalidResponseException
Object[] send (String namespace, BowlerMethod method, String rpcString, Object[] arguments, int retry) throws DeviceConnectionException
Object[] send (String namespace, BowlerMethod method, String rpcString, Object[] arguments) throws DeviceConnectionException
boolean ping ()
boolean ping (boolean switchParser)
ArrayList< ByteList > getRevisions ()
ArrayList< String > getNamespaces ()
boolean hasNamespace (String string)
void startHeartBeat ()
void startHeartBeat (long msHeartBeatTime)
void stopHeartBeat ()
void setThreadedUpstreamPackets (boolean up)
ArrayList< RpcEncapsulation > getRpcList (String namespace)
void loadRpcList ()
void onAllResponse (BowlerDatagram data)
boolean isKeepAlive ()
void setKeepAlive (boolean keepAlive)
long getLastPacketTime ()
void setLastPacketTime (long lastPacketTime)
String getScriptingName ()
void setScriptingName (String scriptingName)
ArrayList< IDeviceConnectionEventListener > getDisconnectListeners ()
Public Member Functions inherited from com.neuronrobotics.sdk.common.IBowlerDatagramListener
void onAsyncResponse (BowlerDatagram data)
Protected Member Functions
void fireDisconnectEvent ()
void fireConnectEvent ()
Private Attributes
boolean keepAlive = true
boolean disconnecting = false
long lastPacketTime =0
BowlerAbstractConnection connection =null
MACAddress address = new MACAddress(MACAddress.BROADCAST)
ArrayList< IDeviceConnectionEventListener > disconnectListeners = new ArrayList<IDeviceConnectionEventListener> ()
String scriptingName = "device"
Detailed Description
AbstractDevices are used to model devices that are connected to the Bowler network. AbstractDevice implementations should encapsulate command generation and provide higher-level actions to users.
Author
rbreznak
Definition at line 47 of file BowlerAbstractDevice.java.
Member Function Documentation
addConnectionEventListener()
void com.neuronrobotics.sdk.common.BowlerAbstractDevice.addConnectionEventListener (final IDeviceConnectionEventListener l)
Adds the connection event listener.
Parameters
l the l
Definition at line 108 of file BowlerAbstractDevice.java.
References com.neuronrobotics.sdk.common.BowlerAbstractConnection.addConnectionEventListener(), com.neuronrobotics.sdk.common.BowlerAbstractDevice.connection, com.neuronrobotics.sdk.common.BowlerAbstractDevice.getDisconnectListeners(), com.neuronrobotics.sdk.common.IDeviceConnectionEventListener.onConnect(), and com.neuronrobotics.sdk.common.IDeviceConnectionEventListener.onDisconnect().
Referenced by com.neuronrobotics.sdk.common.DeviceManager.addConnectionBAD(), com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.DHParameterKinematics(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.scriptFromFileInfo(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.setMobileBase(), and com.neuronrobotics.bowlerstudio.util.FileWatchDeviceWrapper.watch().
connect()
boolean com.neuronrobotics.sdk.common.BowlerAbstractDevice.connect () throws InvalidConnectionException
This method tells the connection object to start and connects the up and down streams pipes. Once this method is called and returns without exception, the device is ready to communicate with
Returns
true, if successful
Exceptions
InvalidConnectionException the invalid connection exception
Reimplemented in com.neuronrobotics.imageprovider.AbstractImageProvider, com.neuronrobotics.sdk.pid.VirtualGenericPIDDevice, com.neuronrobotics.sdk.pid.GenericPIDDevice, com.neuronrobotics.sdk.dyio.DyIO, com.neuronrobotics.sdk.common.NonBowlerDevice, com.neuronrobotics.sdk.common.device.server.BowlerAbstractDeviceServer, com.neuronrobotics.sdk.bootloader.NRBootLoader, and com.neuronrobotics.sdk.addons.kinematics.MobileBase.
Definition at line 185 of file BowlerAbstractDevice.java.
References com.neuronrobotics.sdk.common.BowlerAbstractConnection.connect(), com.neuronrobotics.sdk.common.BowlerAbstractDevice.connection, com.neuronrobotics.sdk.common.BowlerAbstractDevice.isAvailable(), and com.neuronrobotics.sdk.common.BowlerAbstractConnection.isConnected().
Referenced by com.neuronrobotics.sdk.common.DeviceManager.addConnection(), com.neuronrobotics.sdk.common.DeviceManager.addConnectionBAD(), com.neuronrobotics.sdk.ui.ConnectionDialog.getBowlerDevice(), and com.neuronrobotics.sdk.serial.SerialConnection.getConnectionByMacAddress().
disconnect()
void com.neuronrobotics.sdk.common.BowlerAbstractDevice.disconnect ()
This method tells the connection object to disconnect its pipes and close out the connection. Once this is called, it is safe to remove your device.
Reimplemented in com.neuronrobotics.sdk.pid.VirtualGenericPIDDevice, and com.neuronrobotics.sdk.common.NonBowlerDevice.
Definition at line 204 of file BowlerAbstractDevice.java.
References com.neuronrobotics.sdk.common.BowlerAbstractDevice.connection, com.neuronrobotics.sdk.common.BowlerAbstractConnection.disconnect(), com.neuronrobotics.sdk.common.Log.info(), and com.neuronrobotics.sdk.common.BowlerAbstractConnection.isConnected().
Referenced by com.neuronrobotics.sdk.bootloader.NRBootLoader.connect(), com.neuronrobotics.sdk.bootloader.NRBoot.NRBoot(), com.neuronrobotics.sdk.bootloader.NRBoot.reset(), and com.neuronrobotics.sdk.bootloader.NRBootLoader.reset().
fireConnectEvent()
void com.neuronrobotics.sdk.common.BowlerAbstractDevice.fireConnectEvent () protected
Fire connect event.
Definition at line 95 of file BowlerAbstractDevice.java.
References com.neuronrobotics.sdk.common.BowlerAbstractDevice.getDisconnectListeners(), and com.neuronrobotics.sdk.common.IDeviceConnectionEventListener.onConnect().
Referenced by com.neuronrobotics.sdk.common.NonBowlerDevice.connect(), and com.neuronrobotics.sdk.pid.VirtualGenericPIDDevice.connect().
fireDisconnectEvent()
void com.neuronrobotics.sdk.common.BowlerAbstractDevice.fireDisconnectEvent () protected
Set the connection to use when communicating commands with a device.
Definition at line 84 of file BowlerAbstractDevice.java.
References com.neuronrobotics.sdk.common.BowlerAbstractDevice.getDisconnectListeners(), and com.neuronrobotics.sdk.common.IDeviceConnectionEventListener.onDisconnect().
Referenced by com.neuronrobotics.sdk.common.NonBowlerDevice.disconnect(), and com.neuronrobotics.sdk.pid.VirtualGenericPIDDevice.disconnect().
getAddress()
MACAddress com.neuronrobotics.sdk.common.BowlerAbstractDevice.getAddress ()
Get the device's mac address.
Returns
the device's address
Definition at line 240 of file BowlerAbstractDevice.java.
References com.neuronrobotics.sdk.common.BowlerAbstractDevice.address.
Referenced by com.neuronrobotics.sdk.network.AbstractNetworkDeviceServer.AbstractNetworkDeviceServer(), com.neuronrobotics.sdk.common.device.server.BowlerDeviceReServerNamespace.BowlerDeviceReServerNamespace(), com.neuronrobotics.sdk.dyio.DyIO.connect(), com.neuronrobotics.sdk.serial.SerialConnection.getConnectionByMacAddress(), com.neuronrobotics.sdk.common.BowlerAbstractDevice.getNamespaces(), com.neuronrobotics.sdk.common.BowlerAbstractDevice.getRpcList(), com.neuronrobotics.sdk.common.BowlerAbstractDevice.hasNamespace(), com.neuronrobotics.sdk.common.BowlerAbstractDevice.ping(), com.neuronrobotics.sdk.bootloader.NRBootLoader.reset(), com.neuronrobotics.sdk.common.BowlerAbstractDevice.send(), com.neuronrobotics.sdk.common.device.server.BowlerAbstractDeviceServer.sendAsync(), com.neuronrobotics.sdk.common.device.server.BowlerAbstractDeviceServer.sendSyncResponse(), and com.neuronrobotics.sdk.dyio.DyIO.toString().
getConnection()
BowlerAbstractConnection com.neuronrobotics.sdk.common.BowlerAbstractDevice.getConnection ()
Get the connection that is used for communicating with the device.
Returns
the device's connection
Definition at line 219 of file BowlerAbstractDevice.java.
References com.neuronrobotics.sdk.common.BowlerAbstractDevice.connection.
Referenced by com.neuronrobotics.sdk.network.AbstractNetworkDeviceServer.AbstractNetworkDeviceServer(), com.neuronrobotics.sdk.common.DeviceManager.addConnection(), com.neuronrobotics.sdk.bootloader.NRBootLoader.connect(), com.neuronrobotics.sdk.dyio.DyIO.connect(), com.neuronrobotics.sdk.common.BowlerAbstractDevice.isAvailable(), com.neuronrobotics.sdk.dyio.DyIO.isAvailable(), com.neuronrobotics.sdk.genericdevice.GenericDevice.isAvailable(), com.neuronrobotics.sdk.namespace.bcs.pid.LegacyPidNamespaceImp.killAllPidGroups(), com.neuronrobotics.sdk.bootloader.NRBootLoader.reset(), com.neuronrobotics.sdk.dyio.DyIO.resync(), com.neuronrobotics.sdk.common.device.server.BowlerAbstractDeviceServer.sendAsync(), com.neuronrobotics.sdk.common.device.server.BowlerAbstractDeviceServer.sendPacketWithNoResponse(), com.neuronrobotics.sdk.common.device.server.BowlerAbstractDeviceServer.sendSyncResponse(), com.neuronrobotics.sdk.common.BowlerAbstractDevice.startHeartBeat(), and com.neuronrobotics.sdk.common.BowlerAbstractDevice.stopHeartBeat().
getDisconnectListeners()
ArrayList<IDeviceConnectionEventListener> com.neuronrobotics.sdk.common.BowlerAbstractDevice.getDisconnectListeners ()
Gets the disconnect listeners.
Returns
the disconnect listeners
Definition at line 507 of file BowlerAbstractDevice.java.
References com.neuronrobotics.sdk.common.BowlerAbstractDevice.disconnectListeners.
Referenced by com.neuronrobotics.sdk.common.BowlerAbstractDevice.addConnectionEventListener(), com.neuronrobotics.sdk.common.BowlerAbstractDevice.fireConnectEvent(), com.neuronrobotics.sdk.common.BowlerAbstractDevice.fireDisconnectEvent(), com.neuronrobotics.sdk.common.BowlerAbstractDevice.removeConnectionEventListener(), and com.neuronrobotics.sdk.common.BowlerAbstractDevice.setConnection().
getLastPacketTime()
long com.neuronrobotics.sdk.common.BowlerAbstractDevice.getLastPacketTime ()
Gets the last packet time.
Returns
the last packet time
Definition at line 467 of file BowlerAbstractDevice.java.
References com.neuronrobotics.sdk.common.BowlerAbstractDevice.lastPacketTime.
getNamespaces()
ArrayList<String> com.neuronrobotics.sdk.common.BowlerAbstractDevice.getNamespaces ()
Get all the namespaces.
Returns
the namespaces
Reimplemented in com.neuronrobotics.sdk.pid.VirtualGenericPIDDevice, and com.neuronrobotics.sdk.common.NonBowlerDevice.
Definition at line 363 of file BowlerAbstractDevice.java.
References com.neuronrobotics.sdk.common.BowlerAbstractDevice.connection, com.neuronrobotics.sdk.common.BowlerAbstractDevice.getAddress(), and com.neuronrobotics.sdk.common.BowlerAbstractConnection.getNamespaces().
Referenced by com.neuronrobotics.sdk.network.AbstractNetworkDeviceServer.AbstractNetworkDeviceServer(), and com.neuronrobotics.sdk.common.BowlerAbstractDevice.loadRpcList().
getRevisions()
ArrayList<ByteList> com.neuronrobotics.sdk.common.BowlerAbstractDevice.getRevisions ()
Gets the revisions.
Returns
the revisions
Definition at line 341 of file BowlerAbstractDevice.java.
References com.neuronrobotics.sdk.common.Log.debug(), com.neuronrobotics.sdk.common.Log.error(), com.neuronrobotics.sdk.common.ByteList.getBytes(), com.neuronrobotics.sdk.common.BowlerDatagram.getData(), and com.neuronrobotics.sdk.common.BowlerAbstractDevice.send().
Referenced by com.neuronrobotics.sdk.dyio.DyIO.resync().
getRpcList()
ArrayList<RpcEncapsulation> com.neuronrobotics.sdk.common.BowlerAbstractDevice.getRpcList (String namespace)
Requests all of the RPC's from a namespace.
Parameters
namespace the namespace
Returns
the rpc list
Definition at line 418 of file BowlerAbstractDevice.java.
References com.neuronrobotics.sdk.common.BowlerAbstractDevice.connection, com.neuronrobotics.sdk.common.BowlerAbstractDevice.getAddress(), and com.neuronrobotics.sdk.common.BowlerAbstractConnection.getRpcList().
Referenced by com.neuronrobotics.sdk.common.device.server.BowlerDeviceReServerNamespace.BowlerDeviceReServerNamespace(), and com.neuronrobotics.sdk.common.BowlerAbstractDevice.loadRpcList().
getScriptingName()
String com.neuronrobotics.sdk.common.BowlerAbstractDevice.getScriptingName ()
Gets the scripting name.
Returns
the scripting name
Reimplemented in com.neuronrobotics.sdk.common.DMDevice.
Definition at line 487 of file BowlerAbstractDevice.java.
References com.neuronrobotics.sdk.common.BowlerAbstractDevice.scriptingName.
Referenced by com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager._generateStls(), com.neuronrobotics.sdk.common.DeviceManager.addConnectionBAD(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.checkVector(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.generateBody(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.generateStls(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.getEmbedableXml(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getIgenerateBed(), com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.getTipOffsetFromThisLinkInLimb(), com.neuronrobotics.sdk.addons.kinematics.LinkFactory.LinkFactory(), com.neuronrobotics.bowlerstudio.sequence.TimeSequence.loadMobileBase(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.makeLimbTag(), com.neuronrobotics.bowlerstudio.BowlerKernel.processReturnedObjects(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.run(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.scriptFromFileInfo(), com.neuronrobotics.bowlerstudio.creature.MobileBaseLoader.setDefaultDhParameterKinematics(), com.neuronrobotics.bowlerstudio.creature.MobileBaseLoader.setGitWalkingEngine(), com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.setGlobalToFiducialTransform(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.setMassKg(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.setMobileBase(), com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.setupReferencedLimbStartup(), and com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.updateBase().
hasNamespace()
boolean com.neuronrobotics.sdk.common.BowlerAbstractDevice.hasNamespace (String string)
Check the device to see if it has the requested namespace.
Parameters
string the string
Returns
true, if successful
Definition at line 373 of file BowlerAbstractDevice.java.
References com.neuronrobotics.sdk.common.BowlerAbstractDevice.connection, com.neuronrobotics.sdk.common.BowlerAbstractDevice.getAddress(), and com.neuronrobotics.sdk.common.BowlerAbstractConnection.hasNamespace().
Referenced by com.neuronrobotics.sdk.common.DeviceManager.addConnection(), com.neuronrobotics.sdk.dyio.DyIO.connect(), com.neuronrobotics.sdk.pid.GenericPIDDevice.getImplementation(), and com.neuronrobotics.sdk.dyio.DyIO.resync().
isAvailable()
boolean com.neuronrobotics.sdk.common.BowlerAbstractDevice.isAvailable () throws InvalidConnectionException
Determines if the device is available.
Returns
true if the device is avaiable, false if it is not
Exceptions
InvalidConnectionException the invalid connection exception
Reimplemented in com.neuronrobotics.imageprovider.AbstractImageProvider, com.neuronrobotics.sdk.pid.VirtualGenericPIDDevice, com.neuronrobotics.sdk.genericdevice.GenericDevice, com.neuronrobotics.sdk.dyio.DyIO, com.neuronrobotics.sdk.common.NonBowlerDevice, and com.neuronrobotics.sdk.common.DMDevice.
Definition at line 76 of file BowlerAbstractDevice.java.
References com.neuronrobotics.sdk.common.BowlerAbstractDevice.disconnecting, com.neuronrobotics.sdk.common.BowlerAbstractDevice.getConnection(), and com.neuronrobotics.sdk.common.BowlerAbstractConnection.isConnected().
Referenced by com.neuronrobotics.sdk.common.DeviceManager.addConnectionBAD(), com.neuronrobotics.sdk.bootloader.NRBootLoader.connect(), com.neuronrobotics.sdk.common.BowlerAbstractDevice.connect(), com.neuronrobotics.sdk.common.device.server.BowlerAbstractDeviceServer.connect(), com.neuronrobotics.sdk.bowlercam.device.BowlerCamDevice.getBlobs(), com.neuronrobotics.sdk.bowlercam.device.BowlerCamDevice.getHighSpeedImage(), com.neuronrobotics.sdk.bowlercam.device.BowlerCamDevice.getImageServerURL(), com.neuronrobotics.sdk.namespace.bcs.pid.AbstractPidNamespaceImp.isAvailable(), com.neuronrobotics.sdk.bowlercam.device.BowlerCamDevice.highSpeedAutoCapture.run(), and com.neuronrobotics.sdk.bowlercam.device.BowlerCamDevice.startHighSpeedAutoCapture().
isKeepAlive()
boolean com.neuronrobotics.sdk.common.BowlerAbstractDevice.isKeepAlive ()
Checks if is keep alive.
Returns
true, if is keep alive
Definition at line 448 of file BowlerAbstractDevice.java.
References com.neuronrobotics.sdk.common.BowlerAbstractDevice.keepAlive.
loadRpcList()
void com.neuronrobotics.sdk.common.BowlerAbstractDevice.loadRpcList ()
Loads all the Requests for the RPC's from all namespaces.
Definition at line 425 of file BowlerAbstractDevice.java.
References com.neuronrobotics.sdk.common.BowlerAbstractDevice.getNamespaces(), and com.neuronrobotics.sdk.common.BowlerAbstractDevice.getRpcList().
onAllResponse()
void com.neuronrobotics.sdk.common.BowlerAbstractDevice.onAllResponse (BowlerDatagram data)
On all response.
Parameters
data the data
Reimplemented in com.neuronrobotics.sdk.genericdevice.GenericDevice, com.neuronrobotics.sdk.common.device.server.BowlerAbstractDeviceServer, com.neuronrobotics.sdk.bowlercam.device.BowlerCamDevice, and com.neuronrobotics.sdk.bootloader.NRBootLoader.
Definition at line 439 of file BowlerAbstractDevice.java.
ping() [1/2]
boolean com.neuronrobotics.sdk.common.BowlerAbstractDevice.ping ()
Implementation of the Bowler ping ("_png") command Sends a ping to the device returns the device's MAC address.
Returns
the device's address
Definition at line 322 of file BowlerAbstractDevice.java.
Referenced by com.neuronrobotics.sdk.common.DeviceManager.addConnection(), com.neuronrobotics.sdk.ui.ConnectionDialog.getBowlerDevice(), com.neuronrobotics.sdk.serial.SerialConnection.getConnectionByMacAddress(), and com.neuronrobotics.sdk.bootloader.NRBoot.NRBoot().
ping() [2/2]
boolean com.neuronrobotics.sdk.common.BowlerAbstractDevice.ping (boolean switchParser)
Implementation of the Bowler ping ("_png") command Sends a ping to the device returns the device's MAC address.
Parameters
switchParser the switch parser
Returns
the device's address
Definition at line 333 of file BowlerAbstractDevice.java.
References com.neuronrobotics.sdk.common.BowlerAbstractDevice.connection, com.neuronrobotics.sdk.common.BowlerAbstractDevice.getAddress(), and com.neuronrobotics.sdk.common.BowlerAbstractConnection.ping().
removeConnectionEventListener()
void com.neuronrobotics.sdk.common.BowlerAbstractDevice.removeConnectionEventListener (IDeviceConnectionEventListener l)
Removes the connection event listener.
Parameters
l the l
Definition at line 138 of file BowlerAbstractDevice.java.
References com.neuronrobotics.sdk.common.BowlerAbstractDevice.getDisconnectListeners().
send() [1/4]
BowlerDatagram com.neuronrobotics.sdk.common.BowlerAbstractDevice.send (BowlerAbstractCommand command) throws NoConnectionAvailableException, InvalidResponseException
Send a command to the connection.
Parameters
command the command
Returns
the syncronous response
Exceptions
NoConnectionAvailableException the no connection available exception
InvalidResponseException the invalid response exception
Reimplemented in com.neuronrobotics.sdk.pid.VirtualGenericPIDDevice.
Definition at line 265 of file BowlerAbstractDevice.java.
Referenced by com.neuronrobotics.sdk.namespace.bcs.pid.LegacyPidNamespaceImp.ConfigurePDVelovityController(), com.neuronrobotics.sdk.namespace.bcs.pid.LegacyPidNamespaceImp.ConfigurePIDController(), com.neuronrobotics.sdk.bootloader.NRBootLoader.erase(), com.neuronrobotics.sdk.namespace.bcs.pid.LegacyPidNamespaceImp.GetAllPIDPosition(), com.neuronrobotics.sdk.bowlercam.device.BowlerCamDevice.getBlobs(), com.neuronrobotics.sdk.bootloader.NRBootLoader.getBootloaderID(), com.neuronrobotics.sdk.bowlercam.device.BowlerCamDevice.getImageServerURL(), com.neuronrobotics.sdk.namespace.bcs.pid.LegacyPidNamespaceImp.getPIDChannelCount(), com.neuronrobotics.sdk.namespace.bcs.pid.LegacyPidNamespaceImp.getPIDConfiguration(), com.neuronrobotics.sdk.namespace.bcs.pid.LegacyPidNamespaceImp.GetPIDPosition(), com.neuronrobotics.sdk.common.BowlerAbstractDevice.getRevisions(), com.neuronrobotics.sdk.namespace.bcs.pid.LegacyPidNamespaceImp.killAllPidGroups(), com.neuronrobotics.sdk.namespace.bcs.pid.LegacyPidNamespaceImp.ResetPIDChannel(), com.neuronrobotics.sdk.namespace.bcs.pid.PidNamespaceImp.send(), com.neuronrobotics.sdk.common.BowlerAbstractDevice.send(), com.neuronrobotics.sdk.namespace.bcs.pid.LegacyPidNamespaceImp.SetAllPIDSetPoint(), com.neuronrobotics.sdk.namespace.bcs.pid.LegacyPidNamespaceImp.SetPDVelocity(), com.neuronrobotics.sdk.namespace.bcs.pid.LegacyPidNamespaceImp.SetPIDSetPoint(), com.neuronrobotics.sdk.bowlercam.device.BowlerCamDevice.updateFilter(), com.neuronrobotics.sdk.bowlercam.device.BowlerCamDevice.updateImage(), and com.neuronrobotics.sdk.bootloader.NRBootLoader.write().
send() [2/4]
BowlerDatagram com.neuronrobotics.sdk.common.BowlerAbstractDevice.send (BowlerAbstractCommand command, int retry) throws NoConnectionAvailableException, InvalidResponseException
Send a command to the connection.
Parameters
command the command
retry the retry
Returns
the syncronous response
Exceptions
NoConnectionAvailableException the no connection available exception
InvalidResponseException the invalid response exception
Definition at line 278 of file BowlerAbstractDevice.java.
References com.neuronrobotics.sdk.common.BowlerAbstractDevice.connection, com.neuronrobotics.sdk.common.BowlerAbstractDevice.getAddress(), and com.neuronrobotics.sdk.common.BowlerAbstractConnection.send().
send() [3/4]
Object [] com.neuronrobotics.sdk.common.BowlerAbstractDevice.send (String namespace, BowlerMethod method, String rpcString, Object[] arguments) throws DeviceConnectionException
THis is the scripting interface to Bowler devices. THis allows a user to describe a namespace, rpc, and array or arguments to be paced into the packet based on the data types of the argument. The response in likewise unpacked into an array of objects.
Parameters
namespace The string of the desired namespace
method the method
rpcString The string of the desired RPC
arguments An array of objects corresponding to the data to be stuffed into the packet.
Returns
The return arguments parsed and packet into an array of arguments
Exceptions
DeviceConnectionException If the desired RPC's are not available then this will be thrown
Reimplemented in com.neuronrobotics.sdk.dyio.DyIO.
Definition at line 312 of file BowlerAbstractDevice.java.
References com.neuronrobotics.sdk.common.BowlerAbstractDevice.send().
send() [4/4]
Object [] com.neuronrobotics.sdk.common.BowlerAbstractDevice.send (String namespace, BowlerMethod method, String rpcString, Object[] arguments, int retry) throws DeviceConnectionException
THis is the scripting interface to Bowler devices. THis allows a user to describe a namespace, rpc, and array or arguments to be paced into the packet based on the data types of the argument. The response in likewise unpacked into an array of objects.
Parameters
namespace The string of the desired namespace
method the method
rpcString The string of the desired RPC
arguments An array of objects corresponding to the data to be stuffed into the packet.
retry the retry
Returns
The return arguments parsed and packet into an array of arguments
Exceptions
DeviceConnectionException If the desired RPC's are not available then this will be thrown
Definition at line 296 of file BowlerAbstractDevice.java.
References com.neuronrobotics.sdk.common.BowlerAbstractDevice.connection, com.neuronrobotics.sdk.common.BowlerAbstractDevice.getAddress(), and com.neuronrobotics.sdk.common.BowlerAbstractConnection.send().
setAddress()
void com.neuronrobotics.sdk.common.BowlerAbstractDevice.setAddress (MACAddress address)
Set the MAC Address of the device. Every device should have a unique MAC address.
Parameters
address the new address
Definition at line 228 of file BowlerAbstractDevice.java.
References com.neuronrobotics.sdk.common.BowlerAbstractDevice.address, and com.neuronrobotics.sdk.common.MACAddress.isValid().
Referenced by com.neuronrobotics.sdk.dyio.DyIO.connect(), com.neuronrobotics.sdk.dyio.DyIO.DyIO(), com.neuronrobotics.sdk.genericdevice.GenericDevice.GenericDevice(), com.neuronrobotics.sdk.pid.GenericPIDDevice.GenericPIDDevice(), and com.neuronrobotics.sdk.dyio.DyIO.getAllChannelModes().
setConnection()
void com.neuronrobotics.sdk.common.BowlerAbstractDevice.setConnection (BowlerAbstractConnection connection)
Sets the connection.
Parameters
connection the new connection
Reimplemented in com.neuronrobotics.sdk.pid.GenericPIDDevice.
Definition at line 152 of file BowlerAbstractDevice.java.
References com.neuronrobotics.sdk.common.BowlerAbstractConnection.addConnectionEventListener(), com.neuronrobotics.sdk.common.BowlerAbstractConnection.addDatagramListener(), com.neuronrobotics.sdk.common.BowlerAbstractDevice.connection, com.neuronrobotics.sdk.common.BowlerAbstractDevice.getDisconnectListeners(), and com.neuronrobotics.sdk.common.BowlerAbstractDevice.setThreadedUpstreamPackets().
Referenced by com.neuronrobotics.sdk.common.DeviceManager.addConnection(), com.neuronrobotics.sdk.dyio.DyIO.DyIO(), com.neuronrobotics.sdk.genericdevice.GenericDevice.GenericDevice(), com.neuronrobotics.sdk.ui.ConnectionDialog.getBowlerDevice(), and com.neuronrobotics.sdk.bootloader.NRBootLoader.NRBootLoader().
setKeepAlive()
void com.neuronrobotics.sdk.common.BowlerAbstractDevice.setKeepAlive (boolean keepAlive)
Sets the keep alive.
Parameters
keepAlive the new keep alive
Definition at line 457 of file BowlerAbstractDevice.java.
References com.neuronrobotics.sdk.common.BowlerAbstractDevice.keepAlive.
setLastPacketTime()
void com.neuronrobotics.sdk.common.BowlerAbstractDevice.setLastPacketTime (long lastPacketTime)
Sets the last packet time.
Parameters
lastPacketTime the new last packet time
Definition at line 477 of file BowlerAbstractDevice.java.
References com.neuronrobotics.sdk.common.BowlerAbstractDevice.lastPacketTime.
setScriptingName()
void com.neuronrobotics.sdk.common.BowlerAbstractDevice.setScriptingName (String scriptingName)
Sets the scripting name.
Parameters
scriptingName the new scripting name
Definition at line 497 of file BowlerAbstractDevice.java.
References com.neuronrobotics.sdk.common.BowlerAbstractDevice.scriptingName.
Referenced by com.neuronrobotics.sdk.common.DeviceManager.addConnectionBAD(), com.neuronrobotics.bowlerstudio.scripting.RobotHelper.getDefaultContents(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.loadConfigs(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.loadLimb(), and com.neuronrobotics.sdk.pid.VirtualGenericPIDDevice.VirtualGenericPIDDevice().
setThreadedUpstreamPackets()
void com.neuronrobotics.sdk.common.BowlerAbstractDevice.setThreadedUpstreamPackets (boolean up)
Tells the connection to use asynchronous packets as threads or not.
Parameters
up the new threaded upstream packets
Definition at line 406 of file BowlerAbstractDevice.java.
References com.neuronrobotics.sdk.common.BowlerAbstractDevice.connection, and com.neuronrobotics.sdk.common.BowlerAbstractConnection.setThreadedUpstreamPackets().
Referenced by com.neuronrobotics.sdk.common.BowlerAbstractDevice.setConnection().
startHeartBeat() [1/2]
void com.neuronrobotics.sdk.common.BowlerAbstractDevice.startHeartBeat ()
Start heart beat.
Definition at line 380 of file BowlerAbstractDevice.java.
References com.neuronrobotics.sdk.common.BowlerAbstractDevice.getConnection(), and com.neuronrobotics.sdk.common.BowlerAbstractConnection.startHeartBeat().
Referenced by com.neuronrobotics.sdk.dyio.DyIO.connect().
startHeartBeat() [2/2]
void com.neuronrobotics.sdk.common.BowlerAbstractDevice.startHeartBeat (long msHeartBeatTime)
Start heart beat.
Parameters
msHeartBeatTime the ms heart beat time
Reimplemented in com.neuronrobotics.sdk.dyio.DyIO.
Definition at line 389 of file BowlerAbstractDevice.java.
References com.neuronrobotics.sdk.common.BowlerAbstractDevice.getConnection(), and com.neuronrobotics.sdk.common.BowlerAbstractConnection.startHeartBeat().
stopHeartBeat()
void com.neuronrobotics.sdk.common.BowlerAbstractDevice.stopHeartBeat ()
Stop heart beat.
Reimplemented in com.neuronrobotics.sdk.dyio.DyIO.
Definition at line 396 of file BowlerAbstractDevice.java.
References com.neuronrobotics.sdk.common.BowlerAbstractDevice.getConnection(), and com.neuronrobotics.sdk.common.BowlerAbstractConnection.stopHeartBeat().
Member Data Documentation
address
MACAddress com.neuronrobotics.sdk.common.BowlerAbstractDevice.address = new MACAddress(MACAddress.BROADCAST) private
The address.
Definition at line 61 of file BowlerAbstractDevice.java.
Referenced by com.neuronrobotics.sdk.dyio.DyIO.DyIO(), com.neuronrobotics.sdk.common.BowlerAbstractDevice.getAddress(), and com.neuronrobotics.sdk.common.BowlerAbstractDevice.setAddress().
connection
BowlerAbstractConnection com.neuronrobotics.sdk.common.BowlerAbstractDevice.connection =null private
The connection.
Definition at line 59 of file BowlerAbstractDevice.java.
Referenced by com.neuronrobotics.sdk.common.BowlerAbstractDevice.addConnectionEventListener(), com.neuronrobotics.sdk.common.BowlerAbstractDevice.connect(), com.neuronrobotics.sdk.common.BowlerAbstractDevice.disconnect(), com.neuronrobotics.sdk.dyio.DyIO.DyIO(), com.neuronrobotics.sdk.genericdevice.GenericDevice.GenericDevice(), com.neuronrobotics.sdk.pid.GenericPIDDevice.GenericPIDDevice(), com.neuronrobotics.sdk.common.BowlerAbstractDevice.getConnection(), com.neuronrobotics.sdk.common.BowlerAbstractDevice.getNamespaces(), com.neuronrobotics.sdk.common.BowlerAbstractDevice.getRpcList(), com.neuronrobotics.sdk.common.BowlerAbstractDevice.hasNamespace(), com.neuronrobotics.sdk.common.BowlerAbstractDevice.ping(), com.neuronrobotics.sdk.common.BowlerAbstractDevice.send(), com.neuronrobotics.sdk.common.BowlerAbstractDevice.setConnection(), com.neuronrobotics.sdk.pid.GenericPIDDevice.setConnection(), and com.neuronrobotics.sdk.common.BowlerAbstractDevice.setThreadedUpstreamPackets().
disconnecting
boolean com.neuronrobotics.sdk.common.BowlerAbstractDevice.disconnecting = false private
The disconnecting.
Definition at line 53 of file BowlerAbstractDevice.java.
Referenced by com.neuronrobotics.sdk.common.BowlerAbstractDevice.isAvailable().
disconnectListeners
ArrayList<IDeviceConnectionEventListener> com.neuronrobotics.sdk.common.BowlerAbstractDevice.disconnectListeners = new ArrayList<IDeviceConnectionEventListener> () private
The disconnect listeners.
Definition at line 64 of file BowlerAbstractDevice.java.
Referenced by com.neuronrobotics.sdk.common.BowlerAbstractDevice.getDisconnectListeners().
keepAlive
boolean com.neuronrobotics.sdk.common.BowlerAbstractDevice.keepAlive = true private
The keep alive.
Definition at line 50 of file BowlerAbstractDevice.java.
Referenced by com.neuronrobotics.sdk.common.BowlerAbstractDevice.isKeepAlive(), and com.neuronrobotics.sdk.common.BowlerAbstractDevice.setKeepAlive().
lastPacketTime
long com.neuronrobotics.sdk.common.BowlerAbstractDevice.lastPacketTime =0 private
The last packet time.
Definition at line 56 of file BowlerAbstractDevice.java.
Referenced by com.neuronrobotics.sdk.common.BowlerAbstractDevice.getLastPacketTime(), and com.neuronrobotics.sdk.common.BowlerAbstractDevice.setLastPacketTime().
scriptingName
String com.neuronrobotics.sdk.common.BowlerAbstractDevice.scriptingName = "device" private
The scripting name.
Definition at line 67 of file BowlerAbstractDevice.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.compute(), com.neuronrobotics.sdk.common.BowlerAbstractDevice.getScriptingName(), and com.neuronrobotics.sdk.common.BowlerAbstractDevice.setScriptingName().
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/common/BowlerAbstractDevice.java