BowlerKernel: com.neuronrobotics.sdk.commands.bcs.pid.ConfigurePIDCommand Class Reference
com.neuronrobotics.sdk.commands.bcs.pid.ConfigurePIDCommand Class Reference
Public Member Functions
ConfigurePIDCommand (char group)
ConfigurePIDCommand (char group, boolean enabled, boolean inverted, boolean async, double KP, double KI, double KD, double latchValue, boolean use, boolean stop, double up, double low, double hStop)
ConfigurePIDCommand (PIDConfiguration config)
Public Member Functions inherited from com.neuronrobotics.sdk.common.BowlerAbstractCommand
byte[] getCallingData ()
void setOpCode (String opCode)
String getOpCode ()
void setMethod (BowlerMethod method)
BowlerMethod getMethod ()
byte getLength ()
BowlerDatagram validate (BowlerDatagram data) throws InvalidResponseException
byte[] getBytes ()
String toString ()
void setData (ByteList data)
ByteList getCallingDataStorage ()
void setNamespaceIndex (int namespaceIndex)
int getNamespaceIndex ()
Additional Inherited Members
Static Public Member Functions inherited from com.neuronrobotics.sdk.common.BowlerAbstractCommand
static BowlerAbstractCommand parse (BowlerDatagram data)
Detailed Description
The Class ConfigurePIDCommand.
Definition at line 12 of file ConfigurePIDCommand.java.
Constructor & Destructor Documentation
ConfigurePIDCommand() [1/3]
com.neuronrobotics.sdk.commands.bcs.pid.ConfigurePIDCommand.ConfigurePIDCommand (char group)
Instantiates a new configure pid command.
Parameters
group the group
Definition at line 19 of file ConfigurePIDCommand.java.
References com.neuronrobotics.sdk.common.ByteList.add(), com.neuronrobotics.sdk.common.BowlerMethod.GET, com.neuronrobotics.sdk.common.BowlerAbstractCommand.getCallingDataStorage(), com.neuronrobotics.sdk.common.BowlerAbstractCommand.setMethod(), and com.neuronrobotics.sdk.common.BowlerAbstractCommand.setOpCode().
ConfigurePIDCommand() [2/3]
com.neuronrobotics.sdk.commands.bcs.pid.ConfigurePIDCommand.ConfigurePIDCommand (char group, boolean enabled, boolean inverted, boolean async, double KP, double KI, double KD, double latchValue, boolean use, boolean stop, double up, double low, double hStop)
Instantiates a new configure pid command.
Parameters
group the group
enabled the enabled
inverted the inverted
async the async
KP the kp
KI the ki
KD the kd
latchValue the latch value
use the use
stop the stop
up the up
low the low
hStop the h stop
Definition at line 42 of file ConfigurePIDCommand.java.
ConfigurePIDCommand() [3/3]
com.neuronrobotics.sdk.commands.bcs.pid.ConfigurePIDCommand.ConfigurePIDCommand (PIDConfiguration config)
Instantiates a new configure pid command.
Parameters
config the config
Definition at line 51 of file ConfigurePIDCommand.java.
References com.neuronrobotics.sdk.common.ByteList.add(), com.neuronrobotics.sdk.common.ByteList.addAs32(), com.neuronrobotics.sdk.common.BowlerMethod.CRITICAL, com.neuronrobotics.sdk.common.BowlerAbstractCommand.getCallingDataStorage(), com.neuronrobotics.sdk.pid.PIDConfiguration.getGroup(), com.neuronrobotics.sdk.pid.PIDConfiguration.getIndexLatch(), com.neuronrobotics.sdk.pid.PIDConfiguration.getKD(), com.neuronrobotics.sdk.pid.PIDConfiguration.getKI(), com.neuronrobotics.sdk.pid.PIDConfiguration.getKP(), com.neuronrobotics.sdk.pid.PIDConfiguration.isAsync(), com.neuronrobotics.sdk.pid.PIDConfiguration.isEnabled(), com.neuronrobotics.sdk.pid.PIDConfiguration.isInverted(), com.neuronrobotics.sdk.pid.PIDConfiguration.isStopOnIndex(), com.neuronrobotics.sdk.pid.PIDConfiguration.isUseLatch(), com.neuronrobotics.sdk.common.BowlerAbstractCommand.setMethod(), and com.neuronrobotics.sdk.common.BowlerAbstractCommand.setOpCode().
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/commands/bcs/pid/ConfigurePIDCommand.java