BowlerKernel: eu.mihosoft.vrl.v3d.ext.openjfx.importers.SmoothingGroups.Edge Class Reference
eu.mihosoft.vrl.v3d.ext.openjfx.importers.SmoothingGroups.Edge Class Reference
Public Member Functions
Edge (int from, int to, int fromNormal, int toNormal)
boolean isSmooth (Edge edge)
int hashCode ()
boolean equals (Object obj)
Detailed Description
The Class Edge.
Definition at line 311 of file SmoothingGroups.java.
Constructor & Destructor Documentation
Edge()
eu.mihosoft.vrl.v3d.ext.openjfx.importers.SmoothingGroups.Edge.Edge (int from, int to, int fromNormal, int toNormal)
Instantiates a new edge.
Parameters
from the from
to the to
fromNormal the from normal
toNormal the to normal
Definition at line 327 of file SmoothingGroups.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.SmoothingGroups.Edge.equals().
Member Function Documentation
equals()
boolean eu.mihosoft.vrl.v3d.ext.openjfx.importers.SmoothingGroups.Edge.equals (Object obj)
Definition at line 361 of file SmoothingGroups.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.SmoothingGroups.Edge.Edge().
hashCode()
int eu.mihosoft.vrl.v3d.ext.openjfx.importers.SmoothingGroups.Edge.hashCode ()
Definition at line 350 of file SmoothingGroups.java.
isSmooth()
boolean eu.mihosoft.vrl.v3d.ext.openjfx.importers.SmoothingGroups.Edge.isSmooth (Edge edge)
Checks if is smooth.
Parameters
edge the edge
Returns
true, if is smooth
Definition at line 340 of file SmoothingGroups.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.SmoothingGroups.isNormalsEqual().
The documentation for this class was generated from the following file:
JCSG/src/main/java/eu/mihosoft/vrl/v3d/ext/openjfx/importers/SmoothingGroups.java