BowlerKernel: com.neuronrobotics.sdk.ui.SerialConnectionPanel Class Reference
com.neuronrobotics.sdk.ui.SerialConnectionPanel Class Reference
Public Member Functions
SerialConnectionPanel (ConnectionDialog connectionDialog)
BowlerAbstractConnection getConnection ()
void refresh ()
Public Member Functions inherited from com.neuronrobotics.sdk.ui.AbstractConnectionPanel
AbstractConnectionPanel (String title, ImageIcon icon, ConnectionDialog connectionDialog)
AbstractConnectionPanel (String title, ConnectionDialog connectionDialog)
void setTitle (String title)
String getTitle ()
void setIcon (ImageIcon icon)
ImageIcon getIcon ()
ConnectionDialog getConnectionDialog ()
void setConnectionDialog (ConnectionDialog connectionDialog)
Private Attributes
JTextField baudrateTxt = new JTextField(8)
JComboBox connectionCbo = null
JButton refresh
SerialConnection connection = null
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
The Class SerialConnectionPanel.
Definition at line 38 of file SerialConnectionPanel.java.
Constructor & Destructor Documentation
SerialConnectionPanel()
com.neuronrobotics.sdk.ui.SerialConnectionPanel.SerialConnectionPanel (ConnectionDialog connectionDialog)
Instantiates a new serial connection panel.
Parameters
connectionDialog the connection dialog
Definition at line 60 of file SerialConnectionPanel.java.
References com.neuronrobotics.sdk.ui.SerialConnectionPanel.baudrateTxt, com.neuronrobotics.sdk.ui.SerialConnectionPanel.connectionCbo, com.neuronrobotics.sdk.ui.AbstractConnectionPanel.connectionDialog, com.neuronrobotics.sdk.ui.ConnectionImageIconFactory.getIcon(), and com.neuronrobotics.sdk.ui.SerialConnectionPanel.refresh.
Member Function Documentation
getConnection()
BowlerAbstractConnection com.neuronrobotics.sdk.ui.SerialConnectionPanel.getConnection ()
Gets the connection.
Returns
the connection
Reimplemented from com.neuronrobotics.sdk.ui.AbstractConnectionPanel.
Definition at line 95 of file SerialConnectionPanel.java.
References com.neuronrobotics.sdk.ui.SerialConnectionPanel.baudrateTxt, com.neuronrobotics.sdk.ui.SerialConnectionPanel.connection, com.neuronrobotics.sdk.ui.SerialConnectionPanel.connectionCbo, and com.neuronrobotics.sdk.common.Log.info().
refresh()
void com.neuronrobotics.sdk.ui.SerialConnectionPanel.refresh ()
Refresh.
Reimplemented from com.neuronrobotics.sdk.ui.AbstractConnectionPanel.
Definition at line 117 of file SerialConnectionPanel.java.
References com.neuronrobotics.sdk.ui.SerialConnectionPanel.connectionCbo, com.neuronrobotics.sdk.serial.SerialConnection.getAvailableSerialPorts(), and com.neuronrobotics.sdk.ui.AbstractConnectionPanel.getConnectionDialog().
Member Data Documentation
baudrateTxt
JTextField com.neuronrobotics.sdk.ui.SerialConnectionPanel.baudrateTxt = new JTextField(8) private
The baudrate txt.
Definition at line 44 of file SerialConnectionPanel.java.
Referenced by com.neuronrobotics.sdk.ui.SerialConnectionPanel.getConnection(), and com.neuronrobotics.sdk.ui.SerialConnectionPanel.SerialConnectionPanel().
connection
SerialConnection com.neuronrobotics.sdk.ui.SerialConnectionPanel.connection = null private
The connection.
Definition at line 53 of file SerialConnectionPanel.java.
Referenced by com.neuronrobotics.sdk.ui.SerialConnectionPanel.getConnection().
connectionCbo
JComboBox com.neuronrobotics.sdk.ui.SerialConnectionPanel.connectionCbo = null private
The connection cbo.
Definition at line 47 of file SerialConnectionPanel.java.
Referenced by com.neuronrobotics.sdk.ui.SerialConnectionPanel.getConnection(), com.neuronrobotics.sdk.ui.SerialConnectionPanel.refresh(), and com.neuronrobotics.sdk.ui.SerialConnectionPanel.SerialConnectionPanel().
refresh
JButton com.neuronrobotics.sdk.ui.SerialConnectionPanel.refresh private
The refresh.
Definition at line 50 of file SerialConnectionPanel.java.
Referenced by com.neuronrobotics.sdk.ui.SerialConnectionPanel.SerialConnectionPanel().
serialVersionUID
final long com.neuronrobotics.sdk.ui.SerialConnectionPanel.serialVersionUID = 1L static private
The Constant serialVersionUID.
Definition at line 41 of file SerialConnectionPanel.java.
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/ui/SerialConnectionPanel.java