BowlerKernel: eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjOrPolyObjImporter Class Reference
eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjOrPolyObjImporter Class Reference
Public Member Functions
void load (String fileUrl, boolean asPolygonMesh) throws IOException
Group getRoot ()
boolean isSupported (String extension)
Public Member Functions inherited from eu.mihosoft.vrl.v3d.ext.openjfx.importers.Importer
Timeline getTimeline ()
Detailed Description
object loader.
Definition at line 42 of file ObjOrPolyObjImporter.java.
Member Function Documentation
getRoot()
Group eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjOrPolyObjImporter.getRoot ()
Gets the 3D node that was loaded earlier through the load() call.
Returns
The loaded node
Reimplemented from eu.mihosoft.vrl.v3d.ext.openjfx.importers.Importer.
Definition at line 70 of file ObjOrPolyObjImporter.java.
isSupported()
boolean eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjOrPolyObjImporter.isSupported (String supportType)
Tests if the given 3D file extension is supported (e.g. "ma", "ase", "obj", "fxml", "dae").
Parameters
supportType The file extension (e.g. "ma", "ase", "obj", "fxml", "dae")
Returns
True if the extension is of a supported type. False otherwise.
Reimplemented from eu.mihosoft.vrl.v3d.ext.openjfx.importers.Importer.
Definition at line 78 of file ObjOrPolyObjImporter.java.
load()
void eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjOrPolyObjImporter.load (String url, boolean asPolygonMesh) throws IOException
Loads the 3D file.
Parameters
url The url of the 3D file to load
asPolygonMesh When true load as a PolygonMesh if the loader supports.
Exceptions
IOException If issue loading file
Reimplemented from eu.mihosoft.vrl.v3d.ext.openjfx.importers.Importer.
Definition at line 51 of file ObjOrPolyObjImporter.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.buildMeshView(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.buildPolygonMeshView(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.getMeshes(), and eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.getMeshes().
The documentation for this class was generated from the following file:
JCSG/src/main/java/eu/mihosoft/vrl/v3d/ext/openjfx/importers/obj/ObjOrPolyObjImporter.java