BowlerKernel: com.neuronrobotics.bowlerstudio.scripting.ArduinoLoader Class Reference
com.neuronrobotics.bowlerstudio.scripting.ArduinoLoader Class Reference
Public Member Functions
Object inlineScriptRun (File code, ArrayList< Object > args) throws Exception
Object inlineScriptRun (String code, ArrayList< Object > args) throws Exception
String getShellType ()
boolean getIsTextFile ()
String getDefaultContents ()
ArrayList< String > getFileExtenetion ()
Public Member Functions inherited from com.neuronrobotics.bowlerstudio.scripting.IScriptingLanguage
default boolean isSupportedFileExtenetion (String filename)
default String getDefaultContents (String gitURL, String fileSlug)
Static Public Member Functions
static void installBoard (String product, String arch) throws Exception
static void installLibrary (String lib) throws Exception
static void run (String execString) throws Exception
static String getDefaultPort ()
static void setDefaultPort (String defaultPort)
static String getDefaultBoard ()
static void setDefaultBoard (String defaultBoard)
static String getARDUINOExec ()
static void setARDUINOExec (String aRDUINO)
Private Member Functions
File findIno (File start)
Static Private Attributes
static String ARDUINO = "arduino"
static String defaultPort = null
static String defaultBoard = null
static boolean loadedBowler = false
Detailed Description
Definition at line 9 of file ArduinoLoader.java.
Member Function Documentation
findIno()
File com.neuronrobotics.bowlerstudio.scripting.ArduinoLoader.findIno (File start) private
Definition at line 99 of file ArduinoLoader.java.
Referenced by com.neuronrobotics.bowlerstudio.scripting.ArduinoLoader.inlineScriptRun().
getARDUINOExec()
static String com.neuronrobotics.bowlerstudio.scripting.ArduinoLoader.getARDUINOExec () static
Definition at line 195 of file ArduinoLoader.java.
References com.neuronrobotics.bowlerstudio.scripting.ArduinoLoader.ARDUINO.
Referenced by com.neuronrobotics.bowlerstudio.scripting.ArduinoLoader.inlineScriptRun(), com.neuronrobotics.bowlerstudio.scripting.ArduinoLoader.installBoard(), and com.neuronrobotics.bowlerstudio.scripting.ArduinoLoader.installLibrary().
getDefaultBoard()
static String com.neuronrobotics.bowlerstudio.scripting.ArduinoLoader.getDefaultBoard () static
Definition at line 143 of file ArduinoLoader.java.
References com.neuronrobotics.bowlerstudio.scripting.ArduinoLoader.defaultBoard.
Referenced by com.neuronrobotics.bowlerstudio.scripting.ArduinoLoader.inlineScriptRun().
getDefaultContents()
String com.neuronrobotics.bowlerstudio.scripting.ArduinoLoader.getDefaultContents ()
Get the contents of an empty file
Returns
Implements com.neuronrobotics.bowlerstudio.scripting.IScriptingLanguage.
Definition at line 154 of file ArduinoLoader.java.
getDefaultPort()
static String com.neuronrobotics.bowlerstudio.scripting.ArduinoLoader.getDefaultPort () static
Definition at line 135 of file ArduinoLoader.java.
References com.neuronrobotics.bowlerstudio.scripting.ArduinoLoader.defaultPort.
Referenced by com.neuronrobotics.bowlerstudio.scripting.ArduinoLoader.inlineScriptRun().
getFileExtenetion()
ArrayList<String> com.neuronrobotics.bowlerstudio.scripting.ArduinoLoader.getFileExtenetion ()
Returns the list of supported file extentions Convention is to provide just the leters that make up the file extention
Implements com.neuronrobotics.bowlerstudio.scripting.IScriptingLanguage.
Definition at line 204 of file ArduinoLoader.java.
getIsTextFile()
boolean com.neuronrobotics.bowlerstudio.scripting.ArduinoLoader.getIsTextFile ()
This function returns if this is a binary file or a text file
Returns
true if the file is a text file.
Implements com.neuronrobotics.bowlerstudio.scripting.IScriptingLanguage.
Definition at line 131 of file ArduinoLoader.java.
getShellType()
String com.neuronrobotics.bowlerstudio.scripting.ArduinoLoader.getShellType ()
Returns the HashMap key for this language
Implements com.neuronrobotics.bowlerstudio.scripting.IScriptingLanguage.
Definition at line 126 of file ArduinoLoader.java.
inlineScriptRun() [1/2]
Object com.neuronrobotics.bowlerstudio.scripting.ArduinoLoader.inlineScriptRun (File code, ArrayList< Object > args) throws Exception
This interface is for adding additional language support.
Parameters
code file content of the code to be executed
args the incoming arguments as a list of objects
Returns
the objects returned form the code that ran
Implements com.neuronrobotics.bowlerstudio.scripting.IScriptingLanguage.
Definition at line 21 of file ArduinoLoader.java.
References com.neuronrobotics.bowlerstudio.scripting.ArduinoLoader.findIno(), com.neuronrobotics.bowlerstudio.scripting.ArduinoLoader.getARDUINOExec(), com.neuronrobotics.bowlerstudio.scripting.ArduinoLoader.getDefaultBoard(), com.neuronrobotics.bowlerstudio.scripting.ArduinoLoader.getDefaultPort(), com.neuronrobotics.bowlerstudio.scripting.ArduinoLoader.loadedBowler, com.neuronrobotics.bowlerstudio.scripting.ArduinoLoader.run(), com.neuronrobotics.bowlerstudio.scripting.ArduinoLoader.setDefaultBoard(), and com.neuronrobotics.bowlerstudio.scripting.ArduinoLoader.setDefaultPort().
inlineScriptRun() [2/2]
Object com.neuronrobotics.bowlerstudio.scripting.ArduinoLoader.inlineScriptRun (String code, ArrayList< Object > args) throws Exception
This interface is for adding additional language support.
Parameters
code the text content of the code to be executed
args the incoming arguments as a list of objects
Returns
the objects returned form the code that ran
Implements com.neuronrobotics.bowlerstudio.scripting.IScriptingLanguage.
Definition at line 120 of file ArduinoLoader.java.
installBoard()
static void com.neuronrobotics.bowlerstudio.scripting.ArduinoLoader.installBoard (String product, String arch) throws Exception static
Definition at line 63 of file ArduinoLoader.java.
References com.neuronrobotics.bowlerstudio.scripting.ArduinoLoader.getARDUINOExec(), and com.neuronrobotics.bowlerstudio.scripting.ArduinoLoader.run().
installLibrary()
static void com.neuronrobotics.bowlerstudio.scripting.ArduinoLoader.installLibrary (String lib) throws Exception static
Definition at line 67 of file ArduinoLoader.java.
References com.neuronrobotics.bowlerstudio.scripting.ArduinoLoader.getARDUINOExec(), and com.neuronrobotics.bowlerstudio.scripting.ArduinoLoader.run().
run()
static void com.neuronrobotics.bowlerstudio.scripting.ArduinoLoader.run (String execString) throws Exception static
Definition at line 71 of file ArduinoLoader.java.
Referenced by com.neuronrobotics.bowlerstudio.scripting.ArduinoLoader.inlineScriptRun(), com.neuronrobotics.bowlerstudio.scripting.ArduinoLoader.installBoard(), and com.neuronrobotics.bowlerstudio.scripting.ArduinoLoader.installLibrary().
setARDUINOExec()
static void com.neuronrobotics.bowlerstudio.scripting.ArduinoLoader.setARDUINOExec (String aRDUINO) static
Definition at line 199 of file ArduinoLoader.java.
References com.neuronrobotics.bowlerstudio.scripting.ArduinoLoader.ARDUINO.
setDefaultBoard()
static void com.neuronrobotics.bowlerstudio.scripting.ArduinoLoader.setDefaultBoard (String defaultBoard) static
Definition at line 147 of file ArduinoLoader.java.
References com.neuronrobotics.bowlerstudio.scripting.ArduinoLoader.defaultBoard.
Referenced by com.neuronrobotics.bowlerstudio.scripting.ArduinoLoader.inlineScriptRun().
setDefaultPort()
static void com.neuronrobotics.bowlerstudio.scripting.ArduinoLoader.setDefaultPort (String defaultPort) static
Definition at line 139 of file ArduinoLoader.java.
References com.neuronrobotics.bowlerstudio.scripting.ArduinoLoader.defaultPort.
Referenced by com.neuronrobotics.bowlerstudio.scripting.ArduinoLoader.inlineScriptRun().
Member Data Documentation
ARDUINO
String com.neuronrobotics.bowlerstudio.scripting.ArduinoLoader.ARDUINO = "arduino" static private
Definition at line 11 of file ArduinoLoader.java.
Referenced by com.neuronrobotics.bowlerstudio.scripting.ArduinoLoader.getARDUINOExec(), and com.neuronrobotics.bowlerstudio.scripting.ArduinoLoader.setARDUINOExec().
defaultBoard
String com.neuronrobotics.bowlerstudio.scripting.ArduinoLoader.defaultBoard = null static private
Definition at line 16 of file ArduinoLoader.java.
Referenced by com.neuronrobotics.bowlerstudio.scripting.ArduinoLoader.getDefaultBoard(), and com.neuronrobotics.bowlerstudio.scripting.ArduinoLoader.setDefaultBoard().
defaultPort
String com.neuronrobotics.bowlerstudio.scripting.ArduinoLoader.defaultPort = null static private
Definition at line 15 of file ArduinoLoader.java.
Referenced by com.neuronrobotics.bowlerstudio.scripting.ArduinoLoader.getDefaultPort(), and com.neuronrobotics.bowlerstudio.scripting.ArduinoLoader.setDefaultPort().
loadedBowler
boolean com.neuronrobotics.bowlerstudio.scripting.ArduinoLoader.loadedBowler = false static private
Definition at line 17 of file ArduinoLoader.java.
Referenced by com.neuronrobotics.bowlerstudio.scripting.ArduinoLoader.inlineScriptRun().
The documentation for this class was generated from the following file:
src/main/java/com/neuronrobotics/bowlerstudio/scripting/ArduinoLoader.java