BowlerKernel: com.neuronrobotics.bowlerstudio.physics.MobileBasePhysicsManager Class Reference
com.neuronrobotics.bowlerstudio.physics.MobileBasePhysicsManager Class Reference
Public Member Functions
MobileBasePhysicsManager (MobileBase base, ArrayList< CSG > baseCad, HashMap< LinkConfiguration, ArrayList< CSG >> simplecad)
MobileBasePhysicsManager (MobileBase base, ArrayList< CSG > baseCad, HashMap< LinkConfiguration, ArrayList< CSG >> simplecad, PhysicsCore core)
void clear ()
Static Public Attributes
static final float PhysicsGravityScalar = 6
static final float LIFT_EPS = (float) Math.toRadians(0.1)
Private Member Functions
IPhysicsUpdate getUpdater (RigidBody body, IMU base)
Private Attributes
HashMap< LinkConfiguration, ArrayList< CSG > > simplecad
float lift = 0
ArrayList< ILinkListener > linkListeners = new ArrayList<>()
Detailed Description
Definition at line 39 of file MobileBasePhysicsManager.java.
Constructor & Destructor Documentation
MobileBasePhysicsManager() [1/2]
com.neuronrobotics.bowlerstudio.physics.MobileBasePhysicsManager.MobileBasePhysicsManager (MobileBase base, ArrayList< CSG > baseCad, HashMap< LinkConfiguration, ArrayList< CSG >> simplecad)
Definition at line 95 of file MobileBasePhysicsManager.java.
References com.neuronrobotics.bowlerstudio.physics.PhysicsEngine.get(), and com.neuronrobotics.bowlerstudio.physics.MobileBasePhysicsManager.simplecad.
MobileBasePhysicsManager() [2/2]
com.neuronrobotics.bowlerstudio.physics.MobileBasePhysicsManager.MobileBasePhysicsManager (MobileBase base, ArrayList< CSG > baseCad, HashMap< LinkConfiguration, ArrayList< CSG >> simplecad, PhysicsCore core)
Definition at line 100 of file MobileBasePhysicsManager.java.
References com.neuronrobotics.bowlerstudio.physics.PhysicsCore.add(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.addLinkListener(), com.neuronrobotics.bowlerstudio.physics.TransformFactory.bulletToAffine(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.copy(), com.neuronrobotics.sdk.addons.kinematics.DHLink.DhStepInversePrismatic(), com.neuronrobotics.sdk.addons.kinematics.DHLink.DhStepInverseRotory(), com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.forwardKinematics(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.forwardOffset(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getAbstractLink(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.getAllDHChains(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getBaseCad(), com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager.getBoundingBox(), com.neuronrobotics.sdk.addons.kinematics.DHChain.getCachedChain(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getCurrentJointSpaceVector(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getCurrentPosition(), com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getDhChain(), com.neuronrobotics.bowlerstudio.physics.PhysicsCore.getDynamicsWorld(), com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager.getFallRigidBody(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getFiducialToGlobalTransform(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getImu(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getImu(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getLinkConfiguration(), com.neuronrobotics.sdk.addons.kinematics.DHChain.getLinks(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getMassKg(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.getMassKg(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getMaxEngineeringUnits(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getMinEngineeringUnits(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getNumberOfLinks(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getRobotToFiducialTransform(), com.neuronrobotics.bowlerstudio.physics.MobileBasePhysicsManager.getUpdater(), eu.mihosoft.vrl.v3d.CSG.hullAll(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.isPassive(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.isPrismatic(), com.neuronrobotics.bowlerstudio.physics.MobileBasePhysicsManager.lift, com.neuronrobotics.bowlerstudio.physics.MobileBasePhysicsManager.linkListeners, com.neuronrobotics.bowlerstudio.physics.TransformFactory.nrToAffine(), com.neuronrobotics.bowlerstudio.physics.TransformFactory.nrToBullet(), com.neuronrobotics.bowlerstudio.physics.TransformFactory.nrToCSG(), com.neuronrobotics.bowlerstudio.physics.MobileBasePhysicsManager.PhysicsGravityScalar, com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager.setBaseCSG(), eu.mihosoft.vrl.v3d.CSG.setColor(), com.neuronrobotics.bowlerstudio.physics.HingeCSGPhysicsManager.setConstraint(), com.neuronrobotics.bowlerstudio.physics.HingeCSGPhysicsManager.setController(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.setFiducialToGlobalTransform(), eu.mihosoft.vrl.v3d.CSG.setManipulator(), com.neuronrobotics.bowlerstudio.physics.HingeCSGPhysicsManager.setMuscleStrength(), com.neuronrobotics.bowlerstudio.physics.HingeCSGPhysicsManager.setTarget(), com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager.setUpdateManager(), com.neuronrobotics.bowlerstudio.physics.MobileBasePhysicsManager.simplecad, eu.mihosoft.vrl.v3d.CSG.transformed(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.translateZ(), and com.neuronrobotics.sdk.util.ThreadUtil.wait().
Member Function Documentation
clear()
void com.neuronrobotics.bowlerstudio.physics.MobileBasePhysicsManager.clear ()
Definition at line 317 of file MobileBasePhysicsManager.java.
References com.neuronrobotics.bowlerstudio.physics.MobileBasePhysicsManager.linkListeners, and com.neuronrobotics.bowlerstudio.physics.MobileBasePhysicsManager.simplecad.
getUpdater()
IPhysicsUpdate com.neuronrobotics.bowlerstudio.physics.MobileBasePhysicsManager.getUpdater (RigidBody body, IMU base) private
Definition at line 47 of file MobileBasePhysicsManager.java.
References com.neuronrobotics.bowlerstudio.physics.TransformFactory.nrToBullet(), com.neuronrobotics.bowlerstudio.physics.MobileBasePhysicsManager.PhysicsGravityScalar, and com.neuronrobotics.sdk.addons.kinematics.imu.IMU.setVirtualState().
Referenced by com.neuronrobotics.bowlerstudio.physics.MobileBasePhysicsManager.MobileBasePhysicsManager().
Member Data Documentation
lift
float com.neuronrobotics.bowlerstudio.physics.MobileBasePhysicsManager.lift = 0 private
Definition at line 43 of file MobileBasePhysicsManager.java.
Referenced by com.neuronrobotics.bowlerstudio.physics.MobileBasePhysicsManager.MobileBasePhysicsManager().
LIFT_EPS
final float com.neuronrobotics.bowlerstudio.physics.MobileBasePhysicsManager.LIFT_EPS = (float) Math.toRadians(0.1) static
Definition at line 45 of file MobileBasePhysicsManager.java.
linkListeners
ArrayList<ILinkListener> com.neuronrobotics.bowlerstudio.physics.MobileBasePhysicsManager.linkListeners = new ArrayList<>() private
Definition at line 44 of file MobileBasePhysicsManager.java.
Referenced by com.neuronrobotics.bowlerstudio.physics.MobileBasePhysicsManager.clear(), and com.neuronrobotics.bowlerstudio.physics.MobileBasePhysicsManager.MobileBasePhysicsManager().
PhysicsGravityScalar
final float com.neuronrobotics.bowlerstudio.physics.MobileBasePhysicsManager.PhysicsGravityScalar = 6 static
Definition at line 41 of file MobileBasePhysicsManager.java.
Referenced by com.neuronrobotics.bowlerstudio.physics.MobileBasePhysicsManager.getUpdater(), com.neuronrobotics.bowlerstudio.physics.MobileBasePhysicsManager.MobileBasePhysicsManager(), and com.neuronrobotics.bowlerstudio.physics.PhysicsCore.PhysicsCore().
simplecad
HashMap<LinkConfiguration, ArrayList<CSG> > com.neuronrobotics.bowlerstudio.physics.MobileBasePhysicsManager.simplecad private
Definition at line 42 of file MobileBasePhysicsManager.java.
Referenced by com.neuronrobotics.bowlerstudio.physics.MobileBasePhysicsManager.clear(), and com.neuronrobotics.bowlerstudio.physics.MobileBasePhysicsManager.MobileBasePhysicsManager().
The documentation for this class was generated from the following file:
src/main/java/com/neuronrobotics/bowlerstudio/physics/MobileBasePhysicsManager.java