BowlerKernel: com.neuronrobotics.sdk.bowlercam.device.BowlerCamDevice Class Reference
com.neuronrobotics.sdk.bowlercam.device.BowlerCamDevice Class Reference
Classes
class highSpeedAutoCapture
class ImageReader
Public Member Functions
void addWebcamImageListener (IWebcamImageListener l)
void onAllResponse (BowlerDatagram data)
BufferedImage getHighSpeedImage (int cam) throws MalformedURLException, IOException
void onAsyncResponse (BowlerDatagram data)
boolean updateImage (int chan, double scale)
String getImageServerURL (int chan)
BufferedImage getImage (int chan)
void startHighSpeedAutoCapture (int cam, double scale, int fps)
void stopAutoCapture (int cam)
boolean updateFilter (Color c, int threshhold, boolean within, int minBlobSize, int maxBlobSize)
ArrayList< ItemMarker > getBlobs ()
BufferedImage resize (BufferedImage image, double scale)
BufferedImage ByteArrayToImage (byte[] array) throws IOException
Public Member Functions inherited from com.neuronrobotics.sdk.common.BowlerAbstractDevice
boolean isAvailable () throws InvalidConnectionException
void addConnectionEventListener (final IDeviceConnectionEventListener l)
void removeConnectionEventListener (IDeviceConnectionEventListener l)
void setConnection (BowlerAbstractConnection connection)
boolean connect () throws InvalidConnectionException
void disconnect ()
BowlerAbstractConnection getConnection ()
void setAddress (MACAddress address)
MACAddress getAddress ()
BowlerDatagram send (BowlerAbstractCommand command) throws NoConnectionAvailableException, InvalidResponseException
BowlerDatagram send (BowlerAbstractCommand command, int retry) throws NoConnectionAvailableException, InvalidResponseException
Object[] send (String namespace, BowlerMethod method, String rpcString, Object[] arguments, int retry) throws DeviceConnectionException
Object[] send (String namespace, BowlerMethod method, String rpcString, Object[] arguments) throws DeviceConnectionException
boolean ping ()
boolean ping (boolean switchParser)
ArrayList< ByteList > getRevisions ()
ArrayList< String > getNamespaces ()
boolean hasNamespace (String string)
void startHeartBeat ()
void startHeartBeat (long msHeartBeatTime)
void stopHeartBeat ()
void setThreadedUpstreamPackets (boolean up)
ArrayList< RpcEncapsulation > getRpcList (String namespace)
void loadRpcList ()
boolean isKeepAlive ()
void setKeepAlive (boolean keepAlive)
long getLastPacketTime ()
void setLastPacketTime (long lastPacketTime)
String getScriptingName ()
void setScriptingName (String scriptingName)
ArrayList< IDeviceConnectionEventListener > getDisconnectListeners ()
Private Member Functions
void fireIWebcamImageListenerEvent (int camera, BufferedImage im)
Private Attributes
ByteList tmp = new ByteList()
ArrayList< IWebcamImageListener > imageListeners = new ArrayList<IWebcamImageListener>()
ArrayList< highSpeedAutoCapture > captures = new ArrayList<highSpeedAutoCapture> ()
ArrayList< BufferedImage > images = new ArrayList<BufferedImage>()
ArrayList< String > urls = new ArrayList<String> ()
ArrayList< ItemMarker > mark = new ArrayList<ItemMarker> ()
boolean gotLastMark = false
Additional Inherited Members
Protected Member Functions inherited from com.neuronrobotics.sdk.common.BowlerAbstractDevice
void fireDisconnectEvent ()
void fireConnectEvent ()
Detailed Description
The Class BowlerCamDevice.
Definition at line 28 of file BowlerCamDevice.java.
Member Function Documentation
addWebcamImageListener()
void com.neuronrobotics.sdk.bowlercam.device.BowlerCamDevice.addWebcamImageListener (IWebcamImageListener l)
Adds the webcam image listener.
Parameters
l the l
Definition at line 58 of file BowlerCamDevice.java.
References com.neuronrobotics.sdk.bowlercam.device.BowlerCamDevice.imageListeners.
ByteArrayToImage()
BufferedImage com.neuronrobotics.sdk.bowlercam.device.BowlerCamDevice.ByteArrayToImage (byte[] array) throws IOException
Byte array to image.
Parameters
array the array
Returns
the buffered image
Exceptions
IOException Signals that an I/O exception has occurred.
Definition at line 424 of file BowlerCamDevice.java.
Referenced by com.neuronrobotics.sdk.bowlercam.device.BowlerCamDevice.onAsyncResponse().
fireIWebcamImageListenerEvent()
void com.neuronrobotics.sdk.bowlercam.device.BowlerCamDevice.fireIWebcamImageListenerEvent (int camera, BufferedImage im) private
Fire i webcam image listener event.
Parameters
camera the camera
im the im
Definition at line 69 of file BowlerCamDevice.java.
References com.neuronrobotics.sdk.bowlercam.device.BowlerCamDevice.imageListeners.
Referenced by com.neuronrobotics.sdk.bowlercam.device.BowlerCamDevice.onAsyncResponse(), and com.neuronrobotics.sdk.bowlercam.device.BowlerCamDevice.highSpeedAutoCapture.run().
getBlobs()
ArrayList<ItemMarker> com.neuronrobotics.sdk.bowlercam.device.BowlerCamDevice.getBlobs ()
Gets the blobs.
Returns
the blobs
Definition at line 302 of file BowlerCamDevice.java.
References com.neuronrobotics.sdk.bowlercam.device.BowlerCamDevice.gotLastMark, com.neuronrobotics.sdk.common.BowlerAbstractDevice.isAvailable(), com.neuronrobotics.sdk.bowlercam.device.BowlerCamDevice.mark, and com.neuronrobotics.sdk.common.BowlerAbstractDevice.send().
getHighSpeedImage()
BufferedImage com.neuronrobotics.sdk.bowlercam.device.BowlerCamDevice.getHighSpeedImage (int cam) throws MalformedURLException, IOException
Gets the high speed image.
Parameters
cam the cam
Returns
the high speed image
Exceptions
MalformedURLException the malformed url exception
IOException Signals that an I/O exception has occurred.
Definition at line 91 of file BowlerCamDevice.java.
References com.neuronrobotics.sdk.common.Log.error(), com.neuronrobotics.sdk.bowlercam.device.BowlerCamDevice.getImageServerURL(), com.neuronrobotics.sdk.bowlercam.device.BowlerCamDevice.images, com.neuronrobotics.sdk.common.Log.info(), com.neuronrobotics.sdk.common.BowlerAbstractDevice.isAvailable(), com.neuronrobotics.sdk.bowlercam.device.BowlerCamDevice.ImageReader.isDone(), com.neuronrobotics.sdk.bowlercam.device.BowlerCamDevice.urls, and com.neuronrobotics.sdk.util.ThreadUtil.wait().
Referenced by com.neuronrobotics.sdk.bowlercam.device.BowlerCamDevice.highSpeedAutoCapture.run().
getImage()
BufferedImage com.neuronrobotics.sdk.bowlercam.device.BowlerCamDevice.getImage (int chan)
Gets the image.
Parameters
chan the chan
Returns
the image
Definition at line 246 of file BowlerCamDevice.java.
References com.neuronrobotics.sdk.bowlercam.device.BowlerCamDevice.images.
getImageServerURL()
String com.neuronrobotics.sdk.bowlercam.device.BowlerCamDevice.getImageServerURL (int chan)
Gets the image server url.
Parameters
chan the chan
Returns
the image server url
Definition at line 228 of file BowlerCamDevice.java.
References com.neuronrobotics.sdk.common.ByteList.asString(), com.neuronrobotics.sdk.common.BowlerDatagram.getData(), com.neuronrobotics.sdk.common.BowlerAbstractDevice.isAvailable(), com.neuronrobotics.sdk.common.BowlerAbstractDevice.send(), and com.neuronrobotics.sdk.bowlercam.device.BowlerCamDevice.urls.
Referenced by com.neuronrobotics.sdk.bowlercam.device.BowlerCamDevice.getHighSpeedImage().
onAllResponse()
void com.neuronrobotics.sdk.bowlercam.device.BowlerCamDevice.onAllResponse (BowlerDatagram data)
On all response.
Parameters
data the data
Reimplemented from com.neuronrobotics.sdk.common.BowlerAbstractDevice.
Definition at line 78 of file BowlerCamDevice.java.
onAsyncResponse()
void com.neuronrobotics.sdk.bowlercam.device.BowlerCamDevice.onAsyncResponse (BowlerDatagram data)
On async response.
Parameters
data the data
Implements com.neuronrobotics.sdk.common.IBowlerDatagramListener.
Definition at line 166 of file BowlerCamDevice.java.
References com.neuronrobotics.sdk.common.ByteList.add(), com.neuronrobotics.sdk.bowlercam.device.BowlerCamDevice.ByteArrayToImage(), com.neuronrobotics.sdk.common.ByteList.clear(), com.neuronrobotics.sdk.common.ByteList.convertToInt(), com.neuronrobotics.sdk.bowlercam.device.BowlerCamDevice.fireIWebcamImageListenerEvent(), com.neuronrobotics.sdk.common.ByteList.getBytes(), com.neuronrobotics.sdk.common.BowlerDatagram.getData(), com.neuronrobotics.sdk.common.BowlerDatagram.getRPC(), com.neuronrobotics.sdk.bowlercam.device.BowlerCamDevice.gotLastMark, com.neuronrobotics.sdk.bowlercam.device.BowlerCamDevice.images, com.neuronrobotics.sdk.common.Log.info(), com.neuronrobotics.sdk.bowlercam.device.BowlerCamDevice.mark, com.neuronrobotics.sdk.common.ByteList.popList(), com.neuronrobotics.sdk.common.ByteList.size(), and com.neuronrobotics.sdk.bowlercam.device.BowlerCamDevice.tmp.
resize()
BufferedImage com.neuronrobotics.sdk.bowlercam.device.BowlerCamDevice.resize (BufferedImage image, double scale)
Resize.
Parameters
image the image
scale the scale
Returns
the buffered image
Definition at line 403 of file BowlerCamDevice.java.
Referenced by com.neuronrobotics.sdk.bowlercam.device.BowlerCamDevice.highSpeedAutoCapture.run().
startHighSpeedAutoCapture()
void com.neuronrobotics.sdk.bowlercam.device.BowlerCamDevice.startHighSpeedAutoCapture (int cam, double scale, int fps)
Start high speed auto capture.
Parameters
cam the cam
scale the scale
fps the fps
Definition at line 257 of file BowlerCamDevice.java.
References com.neuronrobotics.sdk.bowlercam.device.BowlerCamDevice.captures, com.neuronrobotics.sdk.common.BowlerAbstractDevice.isAvailable(), and com.neuronrobotics.sdk.bowlercam.device.BowlerCamDevice.stopAutoCapture().
stopAutoCapture()
void com.neuronrobotics.sdk.bowlercam.device.BowlerCamDevice.stopAutoCapture (int cam)
Stop auto capture.
Parameters
cam the cam
Definition at line 270 of file BowlerCamDevice.java.
References com.neuronrobotics.sdk.bowlercam.device.BowlerCamDevice.captures.
Referenced by com.neuronrobotics.sdk.bowlercam.device.BowlerCamDevice.startHighSpeedAutoCapture().
updateFilter()
boolean com.neuronrobotics.sdk.bowlercam.device.BowlerCamDevice.updateFilter (Color c, int threshhold, boolean within, int minBlobSize, int maxBlobSize)
Update filter.
Parameters
c the c
threshhold the threshhold
within the within
minBlobSize the min blob size
maxBlobSize the max blob size
Returns
true, if successful
Definition at line 287 of file BowlerCamDevice.java.
References com.neuronrobotics.sdk.common.BowlerAbstractDevice.send().
updateImage()
boolean com.neuronrobotics.sdk.bowlercam.device.BowlerCamDevice.updateImage (int chan, double scale)
Update image.
Parameters
chan the chan
scale the scale
Returns
true, if successful
Definition at line 218 of file BowlerCamDevice.java.
References com.neuronrobotics.sdk.common.BowlerAbstractDevice.send().
Member Data Documentation
captures
ArrayList<highSpeedAutoCapture> com.neuronrobotics.sdk.bowlercam.device.BowlerCamDevice.captures = new ArrayList<highSpeedAutoCapture> () private
The captures.
Definition at line 38 of file BowlerCamDevice.java.
Referenced by com.neuronrobotics.sdk.bowlercam.device.BowlerCamDevice.startHighSpeedAutoCapture(), and com.neuronrobotics.sdk.bowlercam.device.BowlerCamDevice.stopAutoCapture().
gotLastMark
boolean com.neuronrobotics.sdk.bowlercam.device.BowlerCamDevice.gotLastMark = false private
The got last mark.
Definition at line 50 of file BowlerCamDevice.java.
Referenced by com.neuronrobotics.sdk.bowlercam.device.BowlerCamDevice.getBlobs(), and com.neuronrobotics.sdk.bowlercam.device.BowlerCamDevice.onAsyncResponse().
imageListeners
ArrayList<IWebcamImageListener> com.neuronrobotics.sdk.bowlercam.device.BowlerCamDevice.imageListeners = new ArrayList<IWebcamImageListener>() private
The image listeners.
Definition at line 35 of file BowlerCamDevice.java.
Referenced by com.neuronrobotics.sdk.bowlercam.device.BowlerCamDevice.addWebcamImageListener(), and com.neuronrobotics.sdk.bowlercam.device.BowlerCamDevice.fireIWebcamImageListenerEvent().
images
ArrayList<BufferedImage> com.neuronrobotics.sdk.bowlercam.device.BowlerCamDevice.images = new ArrayList<BufferedImage>() private
The images.
Definition at line 41 of file BowlerCamDevice.java.
Referenced by com.neuronrobotics.sdk.bowlercam.device.BowlerCamDevice.getHighSpeedImage(), com.neuronrobotics.sdk.bowlercam.device.BowlerCamDevice.getImage(), com.neuronrobotics.sdk.bowlercam.device.BowlerCamDevice.onAsyncResponse(), and com.neuronrobotics.sdk.bowlercam.device.BowlerCamDevice.ImageReader.run().
mark
ArrayList<ItemMarker> com.neuronrobotics.sdk.bowlercam.device.BowlerCamDevice.mark = new ArrayList<ItemMarker> () private
The mark.
Definition at line 47 of file BowlerCamDevice.java.
Referenced by com.neuronrobotics.sdk.bowlercam.device.BowlerCamDevice.getBlobs(), and com.neuronrobotics.sdk.bowlercam.device.BowlerCamDevice.onAsyncResponse().
tmp
ByteList com.neuronrobotics.sdk.bowlercam.device.BowlerCamDevice.tmp = new ByteList() private
The tmp.
Definition at line 31 of file BowlerCamDevice.java.
Referenced by com.neuronrobotics.sdk.bowlercam.device.BowlerCamDevice.onAsyncResponse().
urls
ArrayList<String> com.neuronrobotics.sdk.bowlercam.device.BowlerCamDevice.urls = new ArrayList<String> () private
The urls.
Definition at line 44 of file BowlerCamDevice.java.
Referenced by com.neuronrobotics.sdk.bowlercam.device.BowlerCamDevice.getHighSpeedImage(), com.neuronrobotics.sdk.bowlercam.device.BowlerCamDevice.getImageServerURL(), and com.neuronrobotics.sdk.bowlercam.device.BowlerCamDevice.ImageReader.run().
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/bowlercam/device/BowlerCamDevice.java