BowlerKernel: com.neuronrobotics.sdk.common.device.server.BowlerDeviceReServerNamespace Class Reference
com.neuronrobotics.sdk.common.device.server.BowlerDeviceReServerNamespace Class Reference
Public Member Functions
BowlerDeviceReServerNamespace (BowlerAbstractConnection device, BowlerAbstractServer server, boolean useAsync, int namespaceIndex, String namespaceString, GenericDevice gen)
BowlerAbstractServer getServer ()
void setServer (BowlerAbstractServer server)
BowlerDatagram process (BowlerDatagram data)
Public Member Functions inherited from com.neuronrobotics.sdk.common.device.server.BowlerAbstractDeviceServerNamespace
BowlerAbstractDeviceServerNamespace (MACAddress addr, String namespaceString)
boolean checkRpc (BowlerDatagram data)
String getNamespace ()
ArrayList< RpcEncapsulation > getRpcList ()
void addRpc (RpcEncapsulation newRpc)
MACAddress getAddress ()
int getNamespaceIndex ()
void setNamespaceIndex (int ns)
Private Attributes
BowlerAbstractConnection device
BowlerAbstractServer server
Additional Inherited Members
Protected Attributes inherited from com.neuronrobotics.sdk.common.device.server.BowlerAbstractDeviceServerNamespace
ArrayList< RpcEncapsulation > rpc =new ArrayList<RpcEncapsulation>()
final String ns
Detailed Description
The Class BowlerDeviceReServerNamespace.
Definition at line 17 of file BowlerDeviceReServerNamespace.java.
Constructor & Destructor Documentation
BowlerDeviceReServerNamespace()
com.neuronrobotics.sdk.common.device.server.BowlerDeviceReServerNamespace.BowlerDeviceReServerNamespace (BowlerAbstractConnection device, BowlerAbstractServer server, boolean useAsync, int namespaceIndex, String namespaceString, GenericDevice gen)
Instantiates a new bowler device re server namespace.
Parameters
device the device
server the server
useAsync the use async
namespaceIndex the namespace index
namespaceString the namespace string
gen the gen
Definition at line 35 of file BowlerDeviceReServerNamespace.java.
References com.neuronrobotics.sdk.common.BowlerAbstractConnection.addDatagramListener(), com.neuronrobotics.sdk.common.device.server.BowlerDeviceReServerNamespace.device, com.neuronrobotics.sdk.common.BowlerAbstractDevice.getAddress(), com.neuronrobotics.sdk.common.device.server.BowlerAbstractDeviceServerNamespace.getRpcList(), com.neuronrobotics.sdk.common.BowlerAbstractDevice.getRpcList(), com.neuronrobotics.sdk.common.device.server.BowlerDeviceReServerNamespace.getServer(), com.neuronrobotics.sdk.common.Log.info(), com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.pushAsyncPacket(), and com.neuronrobotics.sdk.common.device.server.BowlerDeviceReServerNamespace.setServer().
Member Function Documentation
getServer()
BowlerAbstractServer com.neuronrobotics.sdk.common.device.server.BowlerDeviceReServerNamespace.getServer ()
Gets the server.
Returns
the server
Definition at line 65 of file BowlerDeviceReServerNamespace.java.
References com.neuronrobotics.sdk.common.device.server.BowlerDeviceReServerNamespace.server.
Referenced by com.neuronrobotics.sdk.common.device.server.BowlerDeviceReServerNamespace.BowlerDeviceReServerNamespace().
process()
BowlerDatagram com.neuronrobotics.sdk.common.device.server.BowlerDeviceReServerNamespace.process (BowlerDatagram data)
Process.
Parameters
data the data
Returns
the bowler datagram
Reimplemented from com.neuronrobotics.sdk.common.device.server.BowlerAbstractDeviceServerNamespace.
Definition at line 82 of file BowlerDeviceReServerNamespace.java.
References com.neuronrobotics.sdk.common.device.server.BowlerDeviceReServerNamespace.device, and com.neuronrobotics.sdk.common.BowlerAbstractConnection.sendSynchronusly().
setServer()
void com.neuronrobotics.sdk.common.device.server.BowlerDeviceReServerNamespace.setServer (BowlerAbstractServer server)
Sets the server.
Parameters
server the new server
Definition at line 74 of file BowlerDeviceReServerNamespace.java.
References com.neuronrobotics.sdk.common.device.server.BowlerDeviceReServerNamespace.server.
Referenced by com.neuronrobotics.sdk.common.device.server.BowlerDeviceReServerNamespace.BowlerDeviceReServerNamespace().
Member Data Documentation
device
BowlerAbstractConnection com.neuronrobotics.sdk.common.device.server.BowlerDeviceReServerNamespace.device private
The device.
Definition at line 20 of file BowlerDeviceReServerNamespace.java.
Referenced by com.neuronrobotics.sdk.common.device.server.BowlerDeviceReServerNamespace.BowlerDeviceReServerNamespace(), and com.neuronrobotics.sdk.common.device.server.BowlerDeviceReServerNamespace.process().
server
BowlerAbstractServer com.neuronrobotics.sdk.common.device.server.BowlerDeviceReServerNamespace.server private
The server.
Definition at line 23 of file BowlerDeviceReServerNamespace.java.
Referenced by com.neuronrobotics.sdk.common.device.server.BowlerDeviceReServerNamespace.getServer(), and com.neuronrobotics.sdk.common.device.server.BowlerDeviceReServerNamespace.setServer().
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/common/device/server/BowlerDeviceReServerNamespace.java