BowlerKernel: com.neuronrobotics.imageprovider.VirtualCameraFactory Class Reference
com.neuronrobotics.imageprovider.VirtualCameraFactory Class Reference
Static Public Member Functions
static AbstractImageProvider getVirtualCamera ()
static IVirtualCameraFactory getFactory ()
static void setFactory (IVirtualCameraFactory factory)
Static Private Attributes
static IVirtualCameraFactory factory
Detailed Description
Definition at line 6 of file VirtualCameraFactory.java.
Member Function Documentation
getFactory()
static IVirtualCameraFactory com.neuronrobotics.imageprovider.VirtualCameraFactory.getFactory () static
Definition at line 23 of file VirtualCameraFactory.java.
References com.neuronrobotics.imageprovider.VirtualCameraFactory.factory.
Referenced by com.neuronrobotics.imageprovider.VirtualCameraFactory.getVirtualCamera().
getVirtualCamera()
static AbstractImageProvider com.neuronrobotics.imageprovider.VirtualCameraFactory.getVirtualCamera () static
Definition at line 20 of file VirtualCameraFactory.java.
References com.neuronrobotics.imageprovider.VirtualCameraFactory.getFactory(), and com.neuronrobotics.imageprovider.IVirtualCameraFactory.getVirtualCamera().
setFactory()
static void com.neuronrobotics.imageprovider.VirtualCameraFactory.setFactory (IVirtualCameraFactory factory) static
Definition at line 26 of file VirtualCameraFactory.java.
References com.neuronrobotics.imageprovider.VirtualCameraFactory.factory.
Member Data Documentation
factory
IVirtualCameraFactory com.neuronrobotics.imageprovider.VirtualCameraFactory.factory static private
Initial value:
= new IVirtualCameraFactory() {
        @Override
        public AbstractImageProvider getVirtualCamera() {
            try {
                return new URLImageProvider(new URL("http://commonwealthrobotics.com/img/AndrewHarrington/2014-09-15-86.jpg"));
            } catch (MalformedURLException e) {
                throw new RuntimeException(e);
            }
        }
    }
Definition at line 7 of file VirtualCameraFactory.java.
Referenced by com.neuronrobotics.imageprovider.VirtualCameraFactory.getFactory(), and com.neuronrobotics.imageprovider.VirtualCameraFactory.setFactory().
The documentation for this class was generated from the following file:
src/main/java/com/neuronrobotics/imageprovider/VirtualCameraFactory.java