BowlerKernel: eu.mihosoft.vrl.v3d.Cube Class Reference
eu.mihosoft.vrl.v3d.Cube Class Reference
Public Member Functions
Cube ()
Cube (double size)
Cube (Vector3d center, Vector3d dimensions)
Cube (double w, double h, double d)
Cube (LengthParameter w, LengthParameter h, LengthParameter d)
Cube (LengthParameter size)
List< Polygon > toPolygons ()
Vector3d getCenter ()
Cube setCenter (Vector3d center)
Vector3d getDimensions ()
Cube setDimensions (Vector3d dimensions)
PropertyStorage getProperties ()
Cube noCenter ()
Public Member Functions inherited from eu.mihosoft.vrl.v3d.Primitive
CSG toCSG ()
Private Attributes
Vector3d center
Vector3d dimensions
boolean centered = true
final PropertyStorage properties = new PropertyStorage()
Detailed Description
An axis-aligned solid cuboid defined by
center
and
dimensions
.
Author
Michael Hoffer <info@.nosp@m.mich.nosp@m.aelho.nosp@m.ffer.nosp@m..de>
Definition at line 49 of file Cube.java.
Constructor & Destructor Documentation
Cube() [1/6]
eu.mihosoft.vrl.v3d.Cube.Cube ()
Constructor. Creates a new cube with center
[0,0,0]
and dimensions
[1,1,1]
.
Definition at line 69 of file Cube.java.
References eu.mihosoft.vrl.v3d.Cube.center, and eu.mihosoft.vrl.v3d.Cube.dimensions.
Cube() [2/6]
eu.mihosoft.vrl.v3d.Cube.Cube (double size)
Constructor. Creates a new cube with center
[0,0,0]
and dimensions
[size,size,size]
.
Parameters
size size
Definition at line 80 of file Cube.java.
References eu.mihosoft.vrl.v3d.Cube.center, and eu.mihosoft.vrl.v3d.Cube.dimensions.
Cube() [3/6]
eu.mihosoft.vrl.v3d.Cube.Cube (Vector3d center, Vector3d dimensions)
Constructor. Creates a new cuboid with the specified center and dimensions.
Parameters
center center of the cuboid
dimensions cube dimensions
Definition at line 92 of file Cube.java.
References eu.mihosoft.vrl.v3d.Cube.center, and eu.mihosoft.vrl.v3d.Cube.dimensions.
Cube() [4/6]
eu.mihosoft.vrl.v3d.Cube.Cube (double w, double h, double d)
Constructor. Creates a new cuboid with center
[0,0,0]
and with the specified dimensions.
Parameters
w width
h height
d depth
Definition at line 105 of file Cube.java.
References eu.mihosoft.vrl.v3d.Vector3d.ZERO.
Cube() [5/6]
eu.mihosoft.vrl.v3d.Cube.Cube (LengthParameter w, LengthParameter h, LengthParameter d)
Definition at line 108 of file Cube.java.
References eu.mihosoft.vrl.v3d.parametrics.Parameter.getMM(), and eu.mihosoft.vrl.v3d.Vector3d.ZERO.
Cube() [6/6]
eu.mihosoft.vrl.v3d.Cube.Cube (LengthParameter size)
Definition at line 114 of file Cube.java.
Member Function Documentation
getCenter()
Vector3d eu.mihosoft.vrl.v3d.Cube.getCenter ()
Gets the center.
Returns
the center
Definition at line 172 of file Cube.java.
References eu.mihosoft.vrl.v3d.Cube.center.
getDimensions()
Vector3d eu.mihosoft.vrl.v3d.Cube.getDimensions ()
Gets the dimensions.
Returns
the dimensions
Definition at line 191 of file Cube.java.
References eu.mihosoft.vrl.v3d.Cube.dimensions.
getProperties()
PropertyStorage eu.mihosoft.vrl.v3d.Cube.getProperties ()
Returns the property storage of this primitive.
Returns
the property storage of this primitive
Reimplemented from eu.mihosoft.vrl.v3d.Primitive.
Definition at line 209 of file Cube.java.
References eu.mihosoft.vrl.v3d.Cube.properties.
noCenter()
Cube eu.mihosoft.vrl.v3d.Cube.noCenter ()
Defines that this cube will not be centered.
Returns
this cube
Definition at line 217 of file Cube.java.
References eu.mihosoft.vrl.v3d.Cube.centered.
setCenter()
Cube eu.mihosoft.vrl.v3d.Cube.setCenter (Vector3d center)
Sets the center.
Parameters
center the center to set
Definition at line 181 of file Cube.java.
References eu.mihosoft.vrl.v3d.Cube.center.
setDimensions()
Cube eu.mihosoft.vrl.v3d.Cube.setDimensions (Vector3d dimensions)
Sets the dimensions.
Parameters
dimensions the dimensions to set
Definition at line 200 of file Cube.java.
References eu.mihosoft.vrl.v3d.Cube.dimensions.
toPolygons()
List<Polygon> eu.mihosoft.vrl.v3d.Cube.toPolygons ()
Returns the polygons that define this primitive.
Note: this method computes the polygons each time this method is called. The polygons can be cached inside a CSG object.
Returns
a list of polygons that define this primitive
Reimplemented from eu.mihosoft.vrl.v3d.Primitive.
Definition at line 121 of file Cube.java.
References eu.mihosoft.vrl.v3d.Cube.center, eu.mihosoft.vrl.v3d.Cube.centered, eu.mihosoft.vrl.v3d.Cube.dimensions, eu.mihosoft.vrl.v3d.Cube.properties, eu.mihosoft.vrl.v3d.Transform.transform(), eu.mihosoft.vrl.v3d.Transform.translate(), eu.mihosoft.vrl.v3d.Transform.unity(), eu.mihosoft.vrl.v3d.Vector3d.x(), eu.mihosoft.vrl.v3d.Vector3d.y(), and eu.mihosoft.vrl.v3d.Vector3d.z().
Member Data Documentation
center
Vector3d eu.mihosoft.vrl.v3d.Cube.center private
Center of this cube.
Definition at line 54 of file Cube.java.
Referenced by eu.mihosoft.vrl.v3d.Cube.Cube(), eu.mihosoft.vrl.v3d.Cube.getCenter(), eu.mihosoft.vrl.v3d.Cube.setCenter(), and eu.mihosoft.vrl.v3d.Cube.toPolygons().
centered
boolean eu.mihosoft.vrl.v3d.Cube.centered = true private
The centered.
Definition at line 61 of file Cube.java.
Referenced by eu.mihosoft.vrl.v3d.Cube.noCenter(), and eu.mihosoft.vrl.v3d.Cube.toPolygons().
dimensions
Vector3d eu.mihosoft.vrl.v3d.Cube.dimensions private
Cube dimensions.
Definition at line 58 of file Cube.java.
Referenced by eu.mihosoft.vrl.v3d.Cube.Cube(), eu.mihosoft.vrl.v3d.Cube.getDimensions(), eu.mihosoft.vrl.v3d.Cube.setDimensions(), and eu.mihosoft.vrl.v3d.Cube.toPolygons().
properties
final PropertyStorage eu.mihosoft.vrl.v3d.Cube.properties = new PropertyStorage() private
The properties.
Definition at line 64 of file Cube.java.
Referenced by eu.mihosoft.vrl.v3d.Cube.getProperties(), and eu.mihosoft.vrl.v3d.Cube.toPolygons().
The documentation for this class was generated from the following file:
JCSG/src/main/java/eu/mihosoft/vrl/v3d/Cube.java