BowlerKernel: com.neuronrobotics.sdk.commands.bcs.io.ConfigAsyncCommand Class Reference
com.neuronrobotics.sdk.commands.bcs.io.ConfigAsyncCommand Class Reference
Public Member Functions
ConfigAsyncCommand (int channel, int msTime, AsyncMode mode)
ConfigAsyncCommand (int channel, int msTime, int deadbandValue)
ConfigAsyncCommand (int channel, int msTime, int threshholdValue, AsyncThreshholdEdgeType edge)
Public Member Functions inherited from com.neuronrobotics.sdk.common.BowlerAbstractCommand
byte[] getCallingData ()
void setOpCode (String opCode)
String getOpCode ()
void setMethod (BowlerMethod method)
BowlerMethod getMethod ()
byte getLength ()
BowlerDatagram validate (BowlerDatagram data) throws InvalidResponseException
byte[] getBytes ()
String toString ()
void setData (ByteList data)
ByteList getCallingDataStorage ()
void setNamespaceIndex (int namespaceIndex)
int getNamespaceIndex ()
Additional Inherited Members
Static Public Member Functions inherited from com.neuronrobotics.sdk.common.BowlerAbstractCommand
static BowlerAbstractCommand parse (BowlerDatagram data)
Detailed Description
The Class ConfigAsyncCommand.
Definition at line 10 of file ConfigAsyncCommand.java.
Constructor & Destructor Documentation
ConfigAsyncCommand() [1/3]
com.neuronrobotics.sdk.commands.bcs.io.ConfigAsyncCommand.ConfigAsyncCommand (int channel, int msTime, AsyncMode mode)
Instantiates a new config async command.
Parameters
channel the channel
msTime the ms time
mode the mode
Definition at line 19 of file ConfigAsyncCommand.java.
References com.neuronrobotics.sdk.common.ByteList.add(), com.neuronrobotics.sdk.common.ByteList.addAs32(), com.neuronrobotics.sdk.commands.bcs.io.AsyncMode.AUTOSAMP, com.neuronrobotics.sdk.common.BowlerMethod.CRITICAL, com.neuronrobotics.sdk.common.BowlerAbstractCommand.getCallingDataStorage(), com.neuronrobotics.sdk.commands.bcs.io.AsyncMode.getValue(), com.neuronrobotics.sdk.commands.bcs.io.AsyncMode.NOTEQUAL, com.neuronrobotics.sdk.common.BowlerAbstractCommand.setMethod(), and com.neuronrobotics.sdk.common.BowlerAbstractCommand.setOpCode().
ConfigAsyncCommand() [2/3]
com.neuronrobotics.sdk.commands.bcs.io.ConfigAsyncCommand.ConfigAsyncCommand (int channel, int msTime, int deadbandValue)
Instantiates a new config async command.
Parameters
channel the channel
msTime the ms time
deadbandValue the deadband value
Definition at line 36 of file ConfigAsyncCommand.java.
References com.neuronrobotics.sdk.common.ByteList.add(), com.neuronrobotics.sdk.common.ByteList.addAs32(), com.neuronrobotics.sdk.common.BowlerMethod.CRITICAL, com.neuronrobotics.sdk.commands.bcs.io.AsyncMode.DEADBAND, com.neuronrobotics.sdk.common.BowlerAbstractCommand.getCallingDataStorage(), com.neuronrobotics.sdk.common.BowlerAbstractCommand.setMethod(), and com.neuronrobotics.sdk.common.BowlerAbstractCommand.setOpCode().
ConfigAsyncCommand() [3/3]
com.neuronrobotics.sdk.commands.bcs.io.ConfigAsyncCommand.ConfigAsyncCommand (int channel, int msTime, int threshholdValue, AsyncThreshholdEdgeType edge)
Instantiates a new config async command.
Parameters
channel the channel
msTime the ms time
threshholdValue the threshhold value
edge the edge
Definition at line 53 of file ConfigAsyncCommand.java.
References com.neuronrobotics.sdk.common.ByteList.add(), com.neuronrobotics.sdk.common.ByteList.addAs32(), com.neuronrobotics.sdk.common.BowlerMethod.CRITICAL, com.neuronrobotics.sdk.common.BowlerAbstractCommand.getCallingDataStorage(), com.neuronrobotics.sdk.commands.bcs.io.AsyncThreshholdEdgeType.getValue(), com.neuronrobotics.sdk.common.BowlerAbstractCommand.setMethod(), com.neuronrobotics.sdk.common.BowlerAbstractCommand.setOpCode(), and com.neuronrobotics.sdk.commands.bcs.io.AsyncMode.THRESHHOLD.
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/commands/bcs/io/ConfigAsyncCommand.java