BowlerKernel: com.neuronrobotics.sdk.bootloader.NRBootLoader Class Reference
com.neuronrobotics.sdk.bootloader.NRBootLoader Class Reference
Public Member Functions
NRBootLoader (BowlerAbstractConnection serialConnection)
boolean connect ()
String getBootloaderID ()
boolean write (int core, ByteData flashData)
boolean erase (int core)
void reset ()
void onAllResponse (BowlerDatagram data)
void onAsyncResponse (BowlerDatagram data)
Public Member Functions inherited from com.neuronrobotics.sdk.common.BowlerAbstractDevice
boolean isAvailable () throws InvalidConnectionException
void addConnectionEventListener (final IDeviceConnectionEventListener l)
void removeConnectionEventListener (IDeviceConnectionEventListener l)
void setConnection (BowlerAbstractConnection connection)
void disconnect ()
BowlerAbstractConnection getConnection ()
void setAddress (MACAddress address)
MACAddress getAddress ()
BowlerDatagram send (BowlerAbstractCommand command) throws NoConnectionAvailableException, InvalidResponseException
BowlerDatagram send (BowlerAbstractCommand command, int retry) throws NoConnectionAvailableException, InvalidResponseException
Object[] send (String namespace, BowlerMethod method, String rpcString, Object[] arguments, int retry) throws DeviceConnectionException
Object[] send (String namespace, BowlerMethod method, String rpcString, Object[] arguments) throws DeviceConnectionException
boolean ping ()
boolean ping (boolean switchParser)
ArrayList< ByteList > getRevisions ()
ArrayList< String > getNamespaces ()
boolean hasNamespace (String string)
void startHeartBeat ()
void startHeartBeat (long msHeartBeatTime)
void stopHeartBeat ()
void setThreadedUpstreamPackets (boolean up)
ArrayList< RpcEncapsulation > getRpcList (String namespace)
void loadRpcList ()
boolean isKeepAlive ()
void setKeepAlive (boolean keepAlive)
long getLastPacketTime ()
void setLastPacketTime (long lastPacketTime)
String getScriptingName ()
void setScriptingName (String scriptingName)
ArrayList< IDeviceConnectionEventListener > getDisconnectListeners ()
Additional Inherited Members
Protected Member Functions inherited from com.neuronrobotics.sdk.common.BowlerAbstractDevice
void fireDisconnectEvent ()
void fireConnectEvent ()
Detailed Description
The Class NRBootLoader.
Author
hephaestus
Definition at line 24 of file NRBootLoader.java.
Constructor & Destructor Documentation
NRBootLoader()
com.neuronrobotics.sdk.bootloader.NRBootLoader.NRBootLoader (BowlerAbstractConnection serialConnection)
Instantiates a new NR boot loader.
Parameters
serialConnection the serial connection
Definition at line 31 of file NRBootLoader.java.
References com.neuronrobotics.sdk.bootloader.NRBootLoader.connect(), and com.neuronrobotics.sdk.common.BowlerAbstractDevice.setConnection().
Member Function Documentation
connect()
boolean com.neuronrobotics.sdk.bootloader.NRBootLoader.connect ()
This method tells the connection object to start and connects the up and down streams pipes. Once this method is called and returns without exception, the device is ready to communicate with
Returns
true, if successful
Exceptions
InvalidConnectionException the invalid connection exception
Reimplemented from com.neuronrobotics.sdk.common.BowlerAbstractDevice.
Definition at line 45 of file NRBootLoader.java.
References com.neuronrobotics.sdk.common.BowlerAbstractDevice.disconnect(), com.neuronrobotics.sdk.bootloader.NRBootLoader.getBootloaderID(), com.neuronrobotics.sdk.common.BowlerAbstractDevice.getConnection(), com.neuronrobotics.sdk.common.BowlerAbstractDevice.isAvailable(), and com.neuronrobotics.sdk.common.BowlerAbstractConnection.setSynchronusPacketTimeoutTime().
Referenced by com.neuronrobotics.sdk.bootloader.NRBoot.NRBoot(), and com.neuronrobotics.sdk.bootloader.NRBootLoader.NRBootLoader().
erase()
boolean com.neuronrobotics.sdk.bootloader.NRBootLoader.erase (int core)
Erase.
Parameters
core the core
Returns
true, if successful
Definition at line 108 of file NRBootLoader.java.
References com.neuronrobotics.sdk.common.BowlerAbstractDevice.send().
Referenced by com.neuronrobotics.sdk.bootloader.NRBoot.send().
getBootloaderID()
String com.neuronrobotics.sdk.bootloader.NRBootLoader.getBootloaderID ()
Gets the bootloader id.
Returns
the bootloader id
Definition at line 66 of file NRBootLoader.java.
References com.neuronrobotics.sdk.common.BowlerDatagram.getData(), and com.neuronrobotics.sdk.common.BowlerAbstractDevice.send().
Referenced by com.neuronrobotics.sdk.bootloader.NRBootLoader.connect(), and com.neuronrobotics.sdk.bootloader.NRBoot.load().
onAllResponse()
void com.neuronrobotics.sdk.bootloader.NRBootLoader.onAllResponse (BowlerDatagram data)
On all response.
Parameters
data the data
Reimplemented from com.neuronrobotics.sdk.common.BowlerAbstractDevice.
Definition at line 133 of file NRBootLoader.java.
onAsyncResponse()
void com.neuronrobotics.sdk.bootloader.NRBootLoader.onAsyncResponse (BowlerDatagram data)
On async response.
Parameters
data the data
Implements com.neuronrobotics.sdk.common.IBowlerDatagramListener.
Definition at line 141 of file NRBootLoader.java.
reset()
void com.neuronrobotics.sdk.bootloader.NRBootLoader.reset ()
Reset.
Definition at line 115 of file NRBootLoader.java.
References com.neuronrobotics.sdk.common.BowlerAbstractDevice.disconnect(), com.neuronrobotics.sdk.common.BowlerAbstractDevice.getAddress(), com.neuronrobotics.sdk.common.BowlerAbstractDevice.getConnection(), com.neuronrobotics.sdk.common.BowlerAbstractConnection.getDataOuts(), and com.neuronrobotics.sdk.common.BowlerAbstractConnection.sendAsync().
Referenced by com.neuronrobotics.sdk.bootloader.NRBoot.reset().
write()
boolean com.neuronrobotics.sdk.bootloader.NRBootLoader.write (int core, ByteData flashData)
Write.
Parameters
core the core
flashData the flash data
Returns
true, if successful
Definition at line 84 of file NRBootLoader.java.
References com.neuronrobotics.sdk.bootloader.ByteData.getData(), com.neuronrobotics.sdk.common.BowlerDatagram.getRPC(), com.neuronrobotics.sdk.bootloader.ByteData.getStartAddress(), and com.neuronrobotics.sdk.common.BowlerAbstractDevice.send().
Referenced by com.neuronrobotics.sdk.bootloader.NRBoot.send().
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/bootloader/NRBootLoader.java