BowlerKernel: com.neuronrobotics.sdk.bootloader.ByteData Class Reference
com.neuronrobotics.sdk.bootloader.ByteData Class Reference
Public Member Functions
ByteData (long address)
long getStartAddress ()
long getEndAddress ()
void setData (byte data)
byte[] getData ()
String toString ()
Private Member Functions
void setAddress (long address)
Private Attributes
long address
ArrayList< Byte > dataBytes = new ArrayList<Byte>()
Detailed Description
The Class ByteData.
Definition at line 9 of file ByteData.java.
Constructor & Destructor Documentation
ByteData()
com.neuronrobotics.sdk.bootloader.ByteData.ByteData (long address)
Instantiates a new byte data.
Parameters
address the address
Definition at line 22 of file ByteData.java.
References com.neuronrobotics.sdk.bootloader.ByteData.setAddress().
Member Function Documentation
getData()
byte [] com.neuronrobotics.sdk.bootloader.ByteData.getData ()
Gets the data.
Returns
the data
Definition at line 67 of file ByteData.java.
References com.neuronrobotics.sdk.bootloader.ByteData.dataBytes.
Referenced by com.neuronrobotics.sdk.bootloader.IntelHexParser.IntelHexParser(), and com.neuronrobotics.sdk.bootloader.NRBootLoader.write().
getEndAddress()
long com.neuronrobotics.sdk.bootloader.ByteData.getEndAddress ()
Gets the end address.
Returns
the end address
Definition at line 49 of file ByteData.java.
References com.neuronrobotics.sdk.bootloader.ByteData.address, and com.neuronrobotics.sdk.bootloader.ByteData.dataBytes.
getStartAddress()
long com.neuronrobotics.sdk.bootloader.ByteData.getStartAddress ()
Gets the start address.
Returns
the start address
Definition at line 40 of file ByteData.java.
References com.neuronrobotics.sdk.bootloader.ByteData.address.
Referenced by com.neuronrobotics.sdk.bootloader.NRBootLoader.write().
setAddress()
void com.neuronrobotics.sdk.bootloader.ByteData.setAddress (long address) private
Sets the address.
Parameters
address the new address
Definition at line 31 of file ByteData.java.
References com.neuronrobotics.sdk.bootloader.ByteData.address.
Referenced by com.neuronrobotics.sdk.bootloader.ByteData.ByteData().
setData()
void com.neuronrobotics.sdk.bootloader.ByteData.setData (byte data)
Sets the data.
Parameters
data the new data
Definition at line 58 of file ByteData.java.
References com.neuronrobotics.sdk.bootloader.ByteData.dataBytes.
Referenced by com.neuronrobotics.sdk.bootloader.IntelHexParser.IntelHexParser().
toString()
String com.neuronrobotics.sdk.bootloader.ByteData.toString ()
Definition at line 79 of file ByteData.java.
References com.neuronrobotics.sdk.bootloader.ByteData.address, and com.neuronrobotics.sdk.bootloader.ByteData.dataBytes.
Member Data Documentation
address
long com.neuronrobotics.sdk.bootloader.ByteData.address private
The address.
Definition at line 12 of file ByteData.java.
Referenced by com.neuronrobotics.sdk.bootloader.ByteData.getEndAddress(), com.neuronrobotics.sdk.bootloader.ByteData.getStartAddress(), com.neuronrobotics.sdk.bootloader.ByteData.setAddress(), and com.neuronrobotics.sdk.bootloader.ByteData.toString().
dataBytes
ArrayList<Byte> com.neuronrobotics.sdk.bootloader.ByteData.dataBytes = new ArrayList<Byte>() private
The data bytes.
Definition at line 15 of file ByteData.java.
Referenced by com.neuronrobotics.sdk.bootloader.ByteData.getData(), com.neuronrobotics.sdk.bootloader.ByteData.getEndAddress(), com.neuronrobotics.sdk.bootloader.ByteData.setData(), and com.neuronrobotics.sdk.bootloader.ByteData.toString().
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/bootloader/ByteData.java