BowlerKernel: eu.mihosoft.vrl.v3d.svg.ImageTracer Class Reference
eu.mihosoft.vrl.v3d.svg.ImageTracer Class Reference
Classes
class ImageData
class IndexedImage
Public Member Functions
IndexedImage imageToTracedata (String filename, HashMap< String, Float > options, byte[][] palette) throws Exception
IndexedImage imageToTracedata (BufferedImage image, HashMap< String, Float > options, byte[][] palette) throws Exception
Static Public Member Functions
static int arraycontains (String[] arr, String str)
static float parsenext (String[] arr, int i)
static void saveString (String filename, String str) throws Exception
static ImageData loadImageData (String filename) throws Exception
static ImageData loadImageData (BufferedImage image) throws Exception
static byte bytetrans (byte b)
static String imageToSVG (String filename, HashMap< String, Float > options, byte[][] palette) throws Exception
static String imageToSVG (BufferedImage image, HashMap< String, Float > options, byte[][] palette) throws Exception
static String imagedataToSVG (ImageData imgd, HashMap< String, Float > options, byte[][] palette)
static IndexedImage imagedataToTracedata (ImageData imgd, HashMap< String, Float > options, byte[][] palette)
static HashMap< String, Float > checkoptions (HashMap< String, Float > options)
static IndexedImage colorquantization (ImageData imgd, byte[][] palette, HashMap< String, Float > options)
static byte[][] generatepalette (int numberofcolors)
static byte[][] samplepalette (int numberofcolors, ImageData imgd)
static int[][][] layering (IndexedImage ii)
static ArrayList< ArrayList< Integer[]> > pathscan (int[][] arr, float pathomit)
static ArrayList< ArrayList< ArrayList< Integer[]> > > batchpathscan (int[][][] layers, float pathomit)
static ArrayList< ArrayList< Double[]> > internodes (ArrayList< ArrayList< Integer[]>> paths)
static ArrayList< Double[]> tracepath (ArrayList< Double[]> path, float ltreshold, float qtreshold)
static ArrayList< Double[]> fitseq (ArrayList< Double[]> path, float ltreshold, float qtreshold, int seqstart, int seqend)
static ArrayList< ArrayList< Double[]> > batchtracepaths (ArrayList< ArrayList< Double[]>> internodepaths, float ltres, float qtres)
static ArrayList< ArrayList< ArrayList< Double[]> > > batchtracelayers (ArrayList< ArrayList< ArrayList< Double[]>>> binternodes, float ltres, float qtres)
static float roundtodec (float val, float places)
static void svgpathstring (StringBuilder sb, String desc, ArrayList< Double[]> segments, String colorstr, HashMap< String, Float > options)
static String getsvgstring (IndexedImage ii, HashMap< String, Float > options)
Static Public Attributes
static String versionnumber = "1.1.1"
Detailed Description
Definition at line 53 of file ImageTracer.java.
Member Function Documentation
arraycontains()
static int eu.mihosoft.vrl.v3d.svg.ImageTracer.arraycontains (String[] arr, String str) static
Definition at line 57 of file ImageTracer.java.
batchpathscan()
static ArrayList<ArrayList<ArrayList<Integer[]> > > eu.mihosoft.vrl.v3d.svg.ImageTracer.batchpathscan (int layers[][][], float pathomit) static
Definition at line 605 of file ImageTracer.java.
References eu.mihosoft.vrl.v3d.svg.ImageTracer.pathscan().
Referenced by eu.mihosoft.vrl.v3d.svg.ImageTracer.imagedataToTracedata().
batchtracelayers()
static ArrayList<ArrayList<ArrayList<Double[]> > > eu.mihosoft.vrl.v3d.svg.ImageTracer.batchtracelayers (ArrayList< ArrayList< ArrayList< Double[]>>> binternodes, float ltres, float qtres) static
Definition at line 823 of file ImageTracer.java.
References eu.mihosoft.vrl.v3d.svg.ImageTracer.batchtracepaths().
Referenced by eu.mihosoft.vrl.v3d.svg.ImageTracer.imagedataToTracedata().
batchtracepaths()
static ArrayList<ArrayList<Double[]> > eu.mihosoft.vrl.v3d.svg.ImageTracer.batchtracepaths (ArrayList< ArrayList< Double[]>> internodepaths, float ltres, float qtres) static
Definition at line 814 of file ImageTracer.java.
References eu.mihosoft.vrl.v3d.svg.ImageTracer.tracepath().
Referenced by eu.mihosoft.vrl.v3d.svg.ImageTracer.batchtracelayers().
bytetrans()
static byte eu.mihosoft.vrl.v3d.svg.ImageTracer.bytetrans (byte b) static
Definition at line 119 of file ImageTracer.java.
Referenced by eu.mihosoft.vrl.v3d.svg.ImageTracer.loadImageData().
checkoptions()
static HashMap<String,Float> eu.mihosoft.vrl.v3d.svg.ImageTracer.checkoptions (HashMap< String, Float > options) static
Definition at line 176 of file ImageTracer.java.
Referenced by eu.mihosoft.vrl.v3d.svg.ImageTracer.getsvgstring(), eu.mihosoft.vrl.v3d.svg.ImageTracer.imagedataToSVG(), eu.mihosoft.vrl.v3d.svg.ImageTracer.imageToSVG(), and eu.mihosoft.vrl.v3d.svg.ImageTracer.imageToTracedata().
colorquantization()
static IndexedImage eu.mihosoft.vrl.v3d.svg.ImageTracer.colorquantization (ImageData imgd, byte palette[][], HashMap< String, Float > options) static
Definition at line 211 of file ImageTracer.java.
References eu.mihosoft.vrl.v3d.svg.ImageTracer.generatepalette(), and eu.mihosoft.vrl.v3d.svg.ImageTracer.samplepalette().
Referenced by eu.mihosoft.vrl.v3d.svg.ImageTracer.imagedataToTracedata().
fitseq()
static ArrayList<Double[]> eu.mihosoft.vrl.v3d.svg.ImageTracer.fitseq (ArrayList< Double[]> path, float ltreshold, float qtreshold, int seqstart, int seqend) static
Definition at line 723 of file ImageTracer.java.
Referenced by eu.mihosoft.vrl.v3d.svg.ImageTracer.tracepath().
generatepalette()
static byte [][] eu.mihosoft.vrl.v3d.svg.ImageTracer.generatepalette (int numberofcolors) static
Definition at line 310 of file ImageTracer.java.
Referenced by eu.mihosoft.vrl.v3d.svg.ImageTracer.colorquantization().
getsvgstring()
static String eu.mihosoft.vrl.v3d.svg.ImageTracer.getsvgstring (IndexedImage ii, HashMap< String, Float > options) static
Definition at line 971 of file ImageTracer.java.
References eu.mihosoft.vrl.v3d.svg.ImageTracer.checkoptions(), eu.mihosoft.vrl.v3d.svg.ImageTracer.svgpathstring(), and eu.mihosoft.vrl.v3d.svg.ImageTracer.versionnumber.
Referenced by eu.mihosoft.vrl.v3d.svg.ImageTracer.imagedataToSVG().
imagedataToSVG()
static String eu.mihosoft.vrl.v3d.svg.ImageTracer.imagedataToSVG (ImageData imgd, HashMap< String, Float > options, byte palette[][]) static
Definition at line 142 of file ImageTracer.java.
References eu.mihosoft.vrl.v3d.svg.ImageTracer.checkoptions(), eu.mihosoft.vrl.v3d.svg.ImageTracer.getsvgstring(), and eu.mihosoft.vrl.v3d.svg.ImageTracer.imagedataToTracedata().
Referenced by eu.mihosoft.vrl.v3d.svg.ImageTracer.imageToSVG().
imagedataToTracedata()
static IndexedImage eu.mihosoft.vrl.v3d.svg.ImageTracer.imagedataToTracedata (ImageData imgd, HashMap< String, Float > options, byte palette[][]) static
Definition at line 161 of file ImageTracer.java.
References eu.mihosoft.vrl.v3d.svg.ImageTracer.batchpathscan(), eu.mihosoft.vrl.v3d.svg.ImageTracer.batchtracelayers(), eu.mihosoft.vrl.v3d.svg.ImageTracer.colorquantization(), and eu.mihosoft.vrl.v3d.svg.ImageTracer.layering().
Referenced by eu.mihosoft.vrl.v3d.svg.ImageTracer.imagedataToSVG(), and eu.mihosoft.vrl.v3d.svg.ImageTracer.imageToTracedata().
imageToSVG() [1/2]
static String eu.mihosoft.vrl.v3d.svg.ImageTracer.imageToSVG (BufferedImage image, HashMap< String, Float > options, byte palette[][]) throws Exception static
Definition at line 135 of file ImageTracer.java.
References eu.mihosoft.vrl.v3d.svg.ImageTracer.checkoptions(), eu.mihosoft.vrl.v3d.svg.ImageTracer.imagedataToSVG(), and eu.mihosoft.vrl.v3d.svg.ImageTracer.loadImageData().
imageToSVG() [2/2]
static String eu.mihosoft.vrl.v3d.svg.ImageTracer.imageToSVG (String filename, HashMap< String, Float > options, byte palette[][]) throws Exception static
Definition at line 130 of file ImageTracer.java.
References eu.mihosoft.vrl.v3d.svg.ImageTracer.checkoptions(), eu.mihosoft.vrl.v3d.svg.ImageTracer.imagedataToSVG(), and eu.mihosoft.vrl.v3d.svg.ImageTracer.loadImageData().
imageToTracedata() [1/2]
IndexedImage eu.mihosoft.vrl.v3d.svg.ImageTracer.imageToTracedata (BufferedImage image, HashMap< String, Float > options, byte palette[][]) throws Exception
Definition at line 154 of file ImageTracer.java.
References eu.mihosoft.vrl.v3d.svg.ImageTracer.checkoptions(), eu.mihosoft.vrl.v3d.svg.ImageTracer.imagedataToTracedata(), and eu.mihosoft.vrl.v3d.svg.ImageTracer.loadImageData().
imageToTracedata() [2/2]
IndexedImage eu.mihosoft.vrl.v3d.svg.ImageTracer.imageToTracedata (String filename, HashMap< String, Float > options, byte palette[][]) throws Exception
Definition at line 149 of file ImageTracer.java.
References eu.mihosoft.vrl.v3d.svg.ImageTracer.checkoptions(), eu.mihosoft.vrl.v3d.svg.ImageTracer.imagedataToTracedata(), and eu.mihosoft.vrl.v3d.svg.ImageTracer.loadImageData().
internodes()
static ArrayList<ArrayList<Double[]> > eu.mihosoft.vrl.v3d.svg.ImageTracer.internodes (ArrayList< ArrayList< Integer[]>> paths) static
Definition at line 614 of file ImageTracer.java.
layering()
static int [][][] eu.mihosoft.vrl.v3d.svg.ImageTracer.layering (IndexedImage ii) static
Definition at line 372 of file ImageTracer.java.
Referenced by eu.mihosoft.vrl.v3d.svg.ImageTracer.imagedataToTracedata().
loadImageData() [1/2]
static ImageData eu.mihosoft.vrl.v3d.svg.ImageTracer.loadImageData (BufferedImage image) throws Exception static
Definition at line 103 of file ImageTracer.java.
References eu.mihosoft.vrl.v3d.svg.ImageTracer.bytetrans().
loadImageData() [2/2]
static ImageData eu.mihosoft.vrl.v3d.svg.ImageTracer.loadImageData (String filename) throws Exception static
Definition at line 99 of file ImageTracer.java.
Referenced by eu.mihosoft.vrl.v3d.svg.ImageTracer.imageToSVG(), and eu.mihosoft.vrl.v3d.svg.ImageTracer.imageToTracedata().
parsenext()
static float eu.mihosoft.vrl.v3d.svg.ImageTracer.parsenext (String[] arr, int i) static
Definition at line 61 of file ImageTracer.java.
pathscan()
static ArrayList<ArrayList<Integer[]> > eu.mihosoft.vrl.v3d.svg.ImageTracer.pathscan (int arr[][], float pathomit) static
Definition at line 413 of file ImageTracer.java.
Referenced by eu.mihosoft.vrl.v3d.svg.ImageTracer.batchpathscan().
roundtodec()
static float eu.mihosoft.vrl.v3d.svg.ImageTracer.roundtodec (float val, float places) static
Definition at line 837 of file ImageTracer.java.
Referenced by eu.mihosoft.vrl.v3d.svg.ImageTracer.svgpathstring().
samplepalette()
static byte [][] eu.mihosoft.vrl.v3d.svg.ImageTracer.samplepalette (int numberofcolors, ImageData imgd) static
Definition at line 354 of file ImageTracer.java.
Referenced by eu.mihosoft.vrl.v3d.svg.ImageTracer.colorquantization().
saveString()
static void eu.mihosoft.vrl.v3d.svg.ImageTracer.saveString (String filename, String str) throws Exception static
Definition at line 88 of file ImageTracer.java.
svgpathstring()
static void eu.mihosoft.vrl.v3d.svg.ImageTracer.svgpathstring (StringBuilder sb, String desc, ArrayList< Double[]> segments, String colorstr, HashMap< String, Float > options) static
Definition at line 842 of file ImageTracer.java.
References eu.mihosoft.vrl.v3d.svg.ImageTracer.roundtodec().
Referenced by eu.mihosoft.vrl.v3d.svg.ImageTracer.getsvgstring().
tracepath()
static ArrayList<Double[]> eu.mihosoft.vrl.v3d.svg.ImageTracer.tracepath (ArrayList< Double[]> path, float ltreshold, float qtreshold) static
Definition at line 691 of file ImageTracer.java.
References eu.mihosoft.vrl.v3d.svg.ImageTracer.fitseq().
Referenced by eu.mihosoft.vrl.v3d.svg.ImageTracer.batchtracepaths().
Member Data Documentation
versionnumber
String eu.mihosoft.vrl.v3d.svg.ImageTracer.versionnumber = "1.1.1" static
Definition at line 55 of file ImageTracer.java.
Referenced by eu.mihosoft.vrl.v3d.svg.ImageTracer.getsvgstring().
The documentation for this class was generated from the following file:
JCSG/src/main/java/eu/mihosoft/vrl/v3d/svg/ImageTracer.java