BowlerKernel: com.neuronrobotics.sdk.ui.UsbConnectionPanel Class Reference
com.neuronrobotics.sdk.ui.UsbConnectionPanel Class Reference
Public Member Functions
UsbConnectionPanel (ConnectionDialog connectionDialog)
BowlerAbstractConnection getConnection ()
void refresh ()
void onDeviceEvent (UsbDevice device)
Public Member Functions inherited from com.neuronrobotics.sdk.ui.AbstractConnectionPanel
AbstractConnectionPanel (String title, ImageIcon icon, ConnectionDialog connectionDialog)
AbstractConnectionPanel (String title, ConnectionDialog connectionDialog)
void setTitle (String title)
String getTitle ()
void setIcon (ImageIcon icon)
ImageIcon getIcon ()
ConnectionDialog getConnectionDialog ()
void setConnectionDialog (ConnectionDialog connectionDialog)
Private Attributes
JComboBox connectionCbo = null
JButton refresh
UsbCDCSerialConnection connection = null
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
The Class UsbConnectionPanel.
Definition at line 51 of file UsbConnectionPanel.java.
Constructor & Destructor Documentation
UsbConnectionPanel()
com.neuronrobotics.sdk.ui.UsbConnectionPanel.UsbConnectionPanel (ConnectionDialog connectionDialog)
Instantiates a new usb connection panel.
Parameters
connectionDialog the connection dialog
Definition at line 71 of file UsbConnectionPanel.java.
References com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.addUsbDeviceEventListener(), com.neuronrobotics.sdk.ui.UsbConnectionPanel.connectionCbo, com.neuronrobotics.sdk.ui.AbstractConnectionPanel.connectionDialog, com.neuronrobotics.sdk.ui.ConnectionImageIconFactory.getIcon(), and com.neuronrobotics.sdk.ui.UsbConnectionPanel.refresh.
Member Function Documentation
getConnection()
BowlerAbstractConnection com.neuronrobotics.sdk.ui.UsbConnectionPanel.getConnection ()
Gets the connection.
Returns
the connection
Reimplemented from com.neuronrobotics.sdk.ui.AbstractConnectionPanel.
Definition at line 106 of file UsbConnectionPanel.java.
References com.neuronrobotics.sdk.ui.UsbConnectionPanel.connection, com.neuronrobotics.sdk.ui.UsbConnectionPanel.connectionCbo, and com.neuronrobotics.sdk.common.Log.info().
onDeviceEvent()
void com.neuronrobotics.sdk.ui.UsbConnectionPanel.onDeviceEvent (UsbDevice device)
On device event.
Parameters
device the device
Implements com.neuronrobotics.sdk.javaxusb.IUsbDeviceEventListener.
Definition at line 161 of file UsbConnectionPanel.java.
References com.neuronrobotics.sdk.ui.UsbConnectionPanel.refresh, and com.neuronrobotics.sdk.util.ThreadUtil.wait().
refresh()
void com.neuronrobotics.sdk.ui.UsbConnectionPanel.refresh ()
Refresh.
Reimplemented from com.neuronrobotics.sdk.ui.AbstractConnectionPanel.
Definition at line 123 of file UsbConnectionPanel.java.
References com.neuronrobotics.sdk.ui.UsbConnectionPanel.connectionCbo, com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.getAllUsbBowlerDevices(), com.neuronrobotics.sdk.ui.AbstractConnectionPanel.getConnectionDialog(), and com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.getUniqueID().
Member Data Documentation
connection
UsbCDCSerialConnection com.neuronrobotics.sdk.ui.UsbConnectionPanel.connection = null private
The connection.
Definition at line 64 of file UsbConnectionPanel.java.
Referenced by com.neuronrobotics.sdk.ui.UsbConnectionPanel.getConnection().
connectionCbo
JComboBox com.neuronrobotics.sdk.ui.UsbConnectionPanel.connectionCbo = null private
The connection cbo.
Definition at line 58 of file UsbConnectionPanel.java.
Referenced by com.neuronrobotics.sdk.ui.UsbConnectionPanel.getConnection(), com.neuronrobotics.sdk.ui.UsbConnectionPanel.refresh(), and com.neuronrobotics.sdk.ui.UsbConnectionPanel.UsbConnectionPanel().
refresh
JButton com.neuronrobotics.sdk.ui.UsbConnectionPanel.refresh private
The refresh.
Definition at line 61 of file UsbConnectionPanel.java.
Referenced by com.neuronrobotics.sdk.ui.UsbConnectionPanel.onDeviceEvent(), and com.neuronrobotics.sdk.ui.UsbConnectionPanel.UsbConnectionPanel().
serialVersionUID
final long com.neuronrobotics.sdk.ui.UsbConnectionPanel.serialVersionUID = 1L static private
The Constant serialVersionUID.
Definition at line 54 of file UsbConnectionPanel.java.
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/ui/UsbConnectionPanel.java