BowlerKernel: com.neuronrobotics.sdk.common.RpcEncapsulation Class Reference
com.neuronrobotics.sdk.common.RpcEncapsulation Class Reference
Public Member Functions
RpcEncapsulation (int namespaceIndex, String namespace, String rpc, BowlerMethod downStreamMethod, BowlerDataType[] downstreamArguments, BowlerMethod upStreamMethod, BowlerDataType[] upstreamArguments)
RpcEncapsulation (int namespaceIndex, String namespace, String rpc, BowlerMethod downStreamMethod, BowlerDataType[] downstreamArguments, BowlerMethod upStreamMethod, BowlerDataType[] upstreamArguments, IBowlerCommandProcessor processor)
void setArguments (BowlerMethod downStreamMethod, BowlerDataType[] downstreamArguments, BowlerMethod upStreamMethod, BowlerDataType[] upstreamArguments)
BowlerAbstractCommand getCommand (Object[] doswnstreamData)
BowlerAbstractCommand getCommandUpstream (Object[] doswnstreamData)
BowlerAbstractCommand getCommand (Object[] doswnstreamData, BowlerDataType[] arguments)
Object[] parseResponse (BowlerDatagram datagram)
Object[] parseResponseDownstream (BowlerDatagram datagram)
Object[] parseResponse (BowlerDatagram datagram, BowlerDataType[] arguments)
String getNamespace ()
void setNamespace (String namespace)
String getRpc ()
void setRpc (String rpc)
BowlerMethod getDownstreamMethod ()
void setDownStreamMethod (BowlerMethod method)
BowlerDataType[] getDownstreamArguments ()
void setDownstreamArguments (BowlerDataType[] downstreamArguments)
BowlerDataType[] getUpstreamArguments ()
void setUpstreamArguments (BowlerDataType[] upstreamArguments)
BowlerMethod getUpStreamMethod ()
void setUpStreamMethod (BowlerMethod upStreamMethod)
String toString ()
int getNamespaceIndex ()
void setNamespaceIndex (int namespaceIndex)
IBowlerCommandProcessor getProcessor ()
void setProcessor (IBowlerCommandProcessor processor)
Private Attributes
String rpc
BowlerMethod method
BowlerDataType[] downstreamArguments
BowlerDataType[] upstreamArguments
BowlerMethod upStreamMethod
int namespaceIndex
IBowlerCommandProcessor processor
Detailed Description
The Class RpcEncapsulation.
Definition at line 9 of file RpcEncapsulation.java.
Constructor & Destructor Documentation
RpcEncapsulation() [1/2]
com.neuronrobotics.sdk.common.RpcEncapsulation.RpcEncapsulation (int namespaceIndex, String namespace, String rpc, BowlerMethod downStreamMethod, BowlerDataType[] downstreamArguments, BowlerMethod upStreamMethod, BowlerDataType[] upstreamArguments)
This is an encapsulation object for a given RPC.
Parameters
namespaceIndex the namespace index
namespace The corosponding Namespace
rpc The 4 byte RPC code
downStreamMethod The method for sending messages
downstreamArguments The array of data types for a downstream message
upStreamMethod The return method type
upstreamArguments THe return method arguments
Definition at line 46 of file RpcEncapsulation.java.
References com.neuronrobotics.sdk.common.RpcEncapsulation.downstreamArguments, com.neuronrobotics.sdk.common.RpcEncapsulation.namespaceIndex, com.neuronrobotics.sdk.common.RpcEncapsulation.rpc, com.neuronrobotics.sdk.common.RpcEncapsulation.upstreamArguments, and com.neuronrobotics.sdk.common.RpcEncapsulation.upStreamMethod.
RpcEncapsulation() [2/2]
com.neuronrobotics.sdk.common.RpcEncapsulation.RpcEncapsulation (int namespaceIndex, String namespace, String rpc, BowlerMethod downStreamMethod, BowlerDataType[] downstreamArguments, BowlerMethod upStreamMethod, BowlerDataType[] upstreamArguments, IBowlerCommandProcessor processor)
This is an encapsulation object for a given RPC.
Parameters
namespaceIndex the namespace index
namespace The corosponding Namespace
rpc The 4 byte RPC code
downStreamMethod The method for sending messages
downstreamArguments The array of data types for a downstream message
upStreamMethod The return method type
upstreamArguments THe return method arguments
processor the processor
Definition at line 64 of file RpcEncapsulation.java.
References com.neuronrobotics.sdk.common.RpcEncapsulation.downstreamArguments, com.neuronrobotics.sdk.common.RpcEncapsulation.setArguments(), com.neuronrobotics.sdk.common.RpcEncapsulation.setNamespace(), com.neuronrobotics.sdk.common.RpcEncapsulation.setNamespaceIndex(), com.neuronrobotics.sdk.common.RpcEncapsulation.setProcessor(), com.neuronrobotics.sdk.common.RpcEncapsulation.setRpc(), com.neuronrobotics.sdk.common.RpcEncapsulation.upstreamArguments, and com.neuronrobotics.sdk.common.RpcEncapsulation.upStreamMethod.
Member Function Documentation
getCommand() [1/2]
BowlerAbstractCommand com.neuronrobotics.sdk.common.RpcEncapsulation.getCommand (Object[] doswnstreamData)
Gets the command.
Parameters
doswnstreamData the doswnstream data
Returns
the command
Definition at line 95 of file RpcEncapsulation.java.
References com.neuronrobotics.sdk.common.RpcEncapsulation.downstreamArguments.
Referenced by com.neuronrobotics.sdk.common.BowlerAbstractConnection.getCommand(), and com.neuronrobotics.sdk.common.RpcEncapsulation.getCommandUpstream().
getCommand() [2/2]
BowlerAbstractCommand com.neuronrobotics.sdk.common.RpcEncapsulation.getCommand (Object[] doswnstreamData, BowlerDataType[] arguments)
Gets the command.
Parameters
doswnstreamData the doswnstream data
arguments the arguments
Returns
the command
Definition at line 117 of file RpcEncapsulation.java.
References com.neuronrobotics.sdk.common.ByteList.add(), com.neuronrobotics.sdk.common.ByteList.addAs16(), com.neuronrobotics.sdk.common.ByteList.addAs32(), com.neuronrobotics.sdk.common.Log.error(), com.neuronrobotics.sdk.common.ByteList.get(), com.neuronrobotics.sdk.common.BowlerAbstractCommand.getCallingDataStorage(), com.neuronrobotics.sdk.common.RpcEncapsulation.getDownstreamMethod(), com.neuronrobotics.sdk.common.RpcEncapsulation.getNamespaceIndex(), com.neuronrobotics.sdk.common.RpcEncapsulation.getRpc(), com.neuronrobotics.sdk.common.BowlerAbstractCommand.setMethod(), com.neuronrobotics.sdk.common.BowlerAbstractCommand.setNamespaceIndex(), com.neuronrobotics.sdk.common.BowlerAbstractCommand.setOpCode(), com.neuronrobotics.sdk.common.ByteList.size(), and com.neuronrobotics.sdk.common.RpcEncapsulation.toString().
getCommandUpstream()
BowlerAbstractCommand com.neuronrobotics.sdk.common.RpcEncapsulation.getCommandUpstream (Object[] doswnstreamData)
Gets the command upstream.
Parameters
doswnstreamData the doswnstream data
Returns
the command upstream
Definition at line 105 of file RpcEncapsulation.java.
References com.neuronrobotics.sdk.common.RpcEncapsulation.getCommand(), and com.neuronrobotics.sdk.common.RpcEncapsulation.upstreamArguments.
Referenced by com.neuronrobotics.sdk.common.device.server.BowlerAbstractDeviceServerNamespace.process().
getDownstreamArguments()
BowlerDataType [] com.neuronrobotics.sdk.common.RpcEncapsulation.getDownstreamArguments ()
Gets the downstream arguments.
Returns
the downstream arguments
Definition at line 398 of file RpcEncapsulation.java.
References com.neuronrobotics.sdk.common.RpcEncapsulation.downstreamArguments.
Referenced by com.neuronrobotics.sdk.common.device.server.bcs.rpc.BcsRpcNamespaceImp.BcsRpcNamespaceImp(), and com.neuronrobotics.sdk.common.RpcEncapsulation.toString().
getDownstreamMethod()
BowlerMethod com.neuronrobotics.sdk.common.RpcEncapsulation.getDownstreamMethod ()
Gets the downstream method.
Returns
the downstream method
Definition at line 380 of file RpcEncapsulation.java.
References com.neuronrobotics.sdk.common.RpcEncapsulation.method.
Referenced by com.neuronrobotics.sdk.common.device.server.bcs.rpc.BcsRpcNamespaceImp.BcsRpcNamespaceImp(), com.neuronrobotics.sdk.common.RpcEncapsulation.getCommand(), and com.neuronrobotics.sdk.common.RpcEncapsulation.toString().
getNamespace()
String com.neuronrobotics.sdk.common.RpcEncapsulation.getNamespace ()
Gets the namespace.
Returns
the namespace
Definition at line 344 of file RpcEncapsulation.java.
Referenced by com.neuronrobotics.sdk.common.RpcEncapsulation.toString().
getNamespaceIndex()
int com.neuronrobotics.sdk.common.RpcEncapsulation.getNamespaceIndex ()
Gets the namespace index.
Returns
the namespace index
Definition at line 487 of file RpcEncapsulation.java.
References com.neuronrobotics.sdk.common.RpcEncapsulation.namespaceIndex.
Referenced by com.neuronrobotics.sdk.common.RpcEncapsulation.getCommand().
getProcessor()
IBowlerCommandProcessor com.neuronrobotics.sdk.common.RpcEncapsulation.getProcessor ()
Gets the processor.
Returns
the processor
Definition at line 505 of file RpcEncapsulation.java.
References com.neuronrobotics.sdk.common.RpcEncapsulation.processor.
Referenced by com.neuronrobotics.sdk.common.device.server.BowlerAbstractDeviceServerNamespace.process().
getRpc()
String com.neuronrobotics.sdk.common.RpcEncapsulation.getRpc ()
Gets the rpc.
Returns
the rpc
Definition at line 362 of file RpcEncapsulation.java.
References com.neuronrobotics.sdk.common.RpcEncapsulation.rpc.
Referenced by com.neuronrobotics.sdk.common.RpcEncapsulation.getCommand(), and com.neuronrobotics.sdk.common.RpcEncapsulation.toString().
getUpstreamArguments()
BowlerDataType [] com.neuronrobotics.sdk.common.RpcEncapsulation.getUpstreamArguments ()
Gets the upstream arguments.
Returns
the upstream arguments
Definition at line 422 of file RpcEncapsulation.java.
References com.neuronrobotics.sdk.common.RpcEncapsulation.upstreamArguments.
Referenced by com.neuronrobotics.sdk.common.device.server.bcs.rpc.BcsRpcNamespaceImp.BcsRpcNamespaceImp(), and com.neuronrobotics.sdk.common.RpcEncapsulation.toString().
getUpStreamMethod()
BowlerMethod com.neuronrobotics.sdk.common.RpcEncapsulation.getUpStreamMethod ()
Gets the up stream method.
Returns
the up stream method
Definition at line 447 of file RpcEncapsulation.java.
References com.neuronrobotics.sdk.common.RpcEncapsulation.upStreamMethod.
Referenced by com.neuronrobotics.sdk.common.device.server.bcs.rpc.BcsRpcNamespaceImp.BcsRpcNamespaceImp(), and com.neuronrobotics.sdk.common.RpcEncapsulation.toString().
parseResponse() [1/2]
Object [] com.neuronrobotics.sdk.common.RpcEncapsulation.parseResponse (BowlerDatagram datagram)
Parses the response.
Parameters
datagram the datagram
Returns
the object[]
Definition at line 225 of file RpcEncapsulation.java.
References com.neuronrobotics.sdk.common.RpcEncapsulation.upstreamArguments.
Referenced by com.neuronrobotics.sdk.common.BowlerAbstractConnection.parseResponse(), and com.neuronrobotics.sdk.common.RpcEncapsulation.parseResponseDownstream().
parseResponse() [2/2]
Object [] com.neuronrobotics.sdk.common.RpcEncapsulation.parseResponse (BowlerDatagram datagram, BowlerDataType[] arguments)
Parses the response.
Parameters
datagram the datagram
arguments the arguments
Returns
the object[]
Definition at line 246 of file RpcEncapsulation.java.
References com.neuronrobotics.sdk.common.ByteList.add(), com.neuronrobotics.sdk.common.ByteList.asString(), com.neuronrobotics.sdk.common.ByteList.convertToInt(), com.neuronrobotics.sdk.common.Log.error(), com.neuronrobotics.sdk.common.BowlerDatagram.getData(), com.neuronrobotics.sdk.common.ByteList.getUnsigned(), com.neuronrobotics.sdk.common.ByteList.pop(), and com.neuronrobotics.sdk.common.ByteList.popList().
parseResponseDownstream()
Object [] com.neuronrobotics.sdk.common.RpcEncapsulation.parseResponseDownstream (BowlerDatagram datagram)
Parses the response downstream.
Parameters
datagram the datagram
Returns
the object[]
Definition at line 235 of file RpcEncapsulation.java.
References com.neuronrobotics.sdk.common.RpcEncapsulation.downstreamArguments, and com.neuronrobotics.sdk.common.RpcEncapsulation.parseResponse().
Referenced by com.neuronrobotics.sdk.common.device.server.BowlerAbstractDeviceServerNamespace.process().
setArguments()
void com.neuronrobotics.sdk.common.RpcEncapsulation.setArguments (BowlerMethod downStreamMethod, BowlerDataType[] downstreamArguments, BowlerMethod upStreamMethod, BowlerDataType[] upstreamArguments)
Sets the arguments.
Parameters
downStreamMethod the down stream method
downstreamArguments the downstream arguments
upStreamMethod the up stream method
upstreamArguments the upstream arguments
Definition at line 82 of file RpcEncapsulation.java.
References com.neuronrobotics.sdk.common.RpcEncapsulation.setDownstreamArguments(), com.neuronrobotics.sdk.common.RpcEncapsulation.setDownStreamMethod(), com.neuronrobotics.sdk.common.RpcEncapsulation.setUpstreamArguments(), and com.neuronrobotics.sdk.common.RpcEncapsulation.setUpStreamMethod().
Referenced by com.neuronrobotics.sdk.common.RpcEncapsulation.RpcEncapsulation().
setDownstreamArguments()
void com.neuronrobotics.sdk.common.RpcEncapsulation.setDownstreamArguments (BowlerDataType[] downstreamArguments)
Sets the downstream arguments.
Parameters
downstreamArguments the new downstream arguments
Definition at line 408 of file RpcEncapsulation.java.
References com.neuronrobotics.sdk.common.RpcEncapsulation.downstreamArguments.
Referenced by com.neuronrobotics.sdk.common.RpcEncapsulation.setArguments().
setDownStreamMethod()
void com.neuronrobotics.sdk.common.RpcEncapsulation.setDownStreamMethod (BowlerMethod method)
Sets the down stream method.
Parameters
method the new down stream method
Definition at line 389 of file RpcEncapsulation.java.
References com.neuronrobotics.sdk.common.RpcEncapsulation.method.
Referenced by com.neuronrobotics.sdk.common.RpcEncapsulation.setArguments().
setNamespace()
void com.neuronrobotics.sdk.common.RpcEncapsulation.setNamespace (String namespace)
Sets the namespace.
Parameters
namespace the new namespace
Definition at line 353 of file RpcEncapsulation.java.
Referenced by com.neuronrobotics.sdk.common.RpcEncapsulation.RpcEncapsulation().
setNamespaceIndex()
void com.neuronrobotics.sdk.common.RpcEncapsulation.setNamespaceIndex (int namespaceIndex)
Sets the namespace index.
Parameters
namespaceIndex the new namespace index
Definition at line 496 of file RpcEncapsulation.java.
References com.neuronrobotics.sdk.common.RpcEncapsulation.namespaceIndex.
Referenced by com.neuronrobotics.sdk.common.RpcEncapsulation.RpcEncapsulation().
setProcessor()
void com.neuronrobotics.sdk.common.RpcEncapsulation.setProcessor (IBowlerCommandProcessor processor)
Sets the processor.
Parameters
processor the new processor
Definition at line 514 of file RpcEncapsulation.java.
References com.neuronrobotics.sdk.common.RpcEncapsulation.processor.
Referenced by com.neuronrobotics.sdk.common.RpcEncapsulation.RpcEncapsulation().
setRpc()
void com.neuronrobotics.sdk.common.RpcEncapsulation.setRpc (String rpc)
Sets the rpc.
Parameters
rpc the new rpc
Definition at line 371 of file RpcEncapsulation.java.
References com.neuronrobotics.sdk.common.RpcEncapsulation.rpc.
Referenced by com.neuronrobotics.sdk.common.RpcEncapsulation.RpcEncapsulation().
setUpstreamArguments()
void com.neuronrobotics.sdk.common.RpcEncapsulation.setUpstreamArguments (BowlerDataType[] upstreamArguments)
Sets the upstream arguments.
Parameters
upstreamArguments the new upstream arguments
Definition at line 431 of file RpcEncapsulation.java.
References com.neuronrobotics.sdk.common.RpcEncapsulation.upstreamArguments.
Referenced by com.neuronrobotics.sdk.common.RpcEncapsulation.setArguments().
setUpStreamMethod()
void com.neuronrobotics.sdk.common.RpcEncapsulation.setUpStreamMethod (BowlerMethod upStreamMethod)
Sets the up stream method.
Parameters
upStreamMethod the new up stream method
Definition at line 456 of file RpcEncapsulation.java.
References com.neuronrobotics.sdk.common.RpcEncapsulation.upStreamMethod.
Referenced by com.neuronrobotics.sdk.common.RpcEncapsulation.setArguments().
toString()
String com.neuronrobotics.sdk.common.RpcEncapsulation.toString ()
Definition at line 464 of file RpcEncapsulation.java.
References com.neuronrobotics.sdk.common.RpcEncapsulation.getDownstreamArguments(), com.neuronrobotics.sdk.common.RpcEncapsulation.getDownstreamMethod(), com.neuronrobotics.sdk.common.RpcEncapsulation.getNamespace(), com.neuronrobotics.sdk.common.RpcEncapsulation.getRpc(), com.neuronrobotics.sdk.common.RpcEncapsulation.getUpstreamArguments(), and com.neuronrobotics.sdk.common.RpcEncapsulation.getUpStreamMethod().
Referenced by com.neuronrobotics.sdk.common.RpcEncapsulation.getCommand(), and com.neuronrobotics.sdk.common.BowlerAbstractConnection.getRpcList().
Member Data Documentation
downstreamArguments
BowlerDataType [] com.neuronrobotics.sdk.common.RpcEncapsulation.downstreamArguments private
The downstream arguments.
Definition at line 21 of file RpcEncapsulation.java.
Referenced by com.neuronrobotics.sdk.common.RpcEncapsulation.getCommand(), com.neuronrobotics.sdk.common.RpcEncapsulation.getDownstreamArguments(), com.neuronrobotics.sdk.common.RpcEncapsulation.parseResponseDownstream(), com.neuronrobotics.sdk.common.RpcEncapsulation.RpcEncapsulation(), and com.neuronrobotics.sdk.common.RpcEncapsulation.setDownstreamArguments().
method
BowlerMethod com.neuronrobotics.sdk.common.RpcEncapsulation.method private
The method.
Definition at line 18 of file RpcEncapsulation.java.
Referenced by com.neuronrobotics.sdk.common.RpcEncapsulation.getDownstreamMethod(), and com.neuronrobotics.sdk.common.RpcEncapsulation.setDownStreamMethod().
namespaceIndex
int com.neuronrobotics.sdk.common.RpcEncapsulation.namespaceIndex private
The namespace index.
Definition at line 30 of file RpcEncapsulation.java.
Referenced by com.neuronrobotics.sdk.common.RpcEncapsulation.getNamespaceIndex(), com.neuronrobotics.sdk.common.RpcEncapsulation.RpcEncapsulation(), and com.neuronrobotics.sdk.common.RpcEncapsulation.setNamespaceIndex().
processor
IBowlerCommandProcessor com.neuronrobotics.sdk.common.RpcEncapsulation.processor private
The processor.
Definition at line 33 of file RpcEncapsulation.java.
Referenced by com.neuronrobotics.sdk.common.RpcEncapsulation.getProcessor(), and com.neuronrobotics.sdk.common.RpcEncapsulation.setProcessor().
rpc
String com.neuronrobotics.sdk.common.RpcEncapsulation.rpc private
The namespace. The rpc.
Definition at line 15 of file RpcEncapsulation.java.
Referenced by com.neuronrobotics.sdk.common.RpcEncapsulation.getRpc(), com.neuronrobotics.sdk.common.RpcEncapsulation.RpcEncapsulation(), and com.neuronrobotics.sdk.common.RpcEncapsulation.setRpc().
upstreamArguments
BowlerDataType [] com.neuronrobotics.sdk.common.RpcEncapsulation.upstreamArguments private
The upstream arguments.
Definition at line 24 of file RpcEncapsulation.java.
Referenced by com.neuronrobotics.sdk.common.RpcEncapsulation.getCommandUpstream(), com.neuronrobotics.sdk.common.RpcEncapsulation.getUpstreamArguments(), com.neuronrobotics.sdk.common.RpcEncapsulation.parseResponse(), com.neuronrobotics.sdk.common.RpcEncapsulation.RpcEncapsulation(), and com.neuronrobotics.sdk.common.RpcEncapsulation.setUpstreamArguments().
upStreamMethod
BowlerMethod com.neuronrobotics.sdk.common.RpcEncapsulation.upStreamMethod private
The up stream method.
Definition at line 27 of file RpcEncapsulation.java.
Referenced by com.neuronrobotics.sdk.common.RpcEncapsulation.getUpStreamMethod(), com.neuronrobotics.sdk.common.RpcEncapsulation.RpcEncapsulation(), and com.neuronrobotics.sdk.common.RpcEncapsulation.setUpStreamMethod().
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/common/RpcEncapsulation.java