BowlerKernel: com.neuronrobotics.bowlerstudio.creature.CadFileExporter Class Reference
com.neuronrobotics.bowlerstudio.creature.CadFileExporter Class Reference
Public Member Functions
CadFileExporter (IMobileBaseUI myUI)
CadFileExporter ()
ArrayList< File > generateManufacturingParts (List< CSG > totalAssembly, File baseDirForFiles) throws IOException
Private Member Functions
File makeStl (String nameBase, CSG tmp) throws IOException
File makeObj (String nameBase, CSG tmp) throws IOException
File makeSvg (String nameBase, List< CSG > currentCsg) throws IOException
Detailed Description
Definition at line 19 of file CadFileExporter.java.
Constructor & Destructor Documentation
CadFileExporter() [1/2]
com.neuronrobotics.bowlerstudio.creature.CadFileExporter.CadFileExporter (IMobileBaseUI myUI)
Definition at line 22 of file CadFileExporter.java.
CadFileExporter() [2/2]
com.neuronrobotics.bowlerstudio.creature.CadFileExporter.CadFileExporter ()
Definition at line 25 of file CadFileExporter.java.
Member Function Documentation
generateManufacturingParts()
ArrayList<File> com.neuronrobotics.bowlerstudio.creature.CadFileExporter.generateManufacturingParts (List< CSG > totalAssembly, File baseDirForFiles) throws IOException
Definition at line 65 of file CadFileExporter.java.
References com.neuronrobotics.bowlerstudio.creature.CadFileExporter.makeObj(), com.neuronrobotics.bowlerstudio.creature.CadFileExporter.makeStl(), com.neuronrobotics.bowlerstudio.creature.CadFileExporter.makeSvg(), eu.mihosoft.vrl.v3d.CSG.prepForManufacturing(), com.neuronrobotics.bowlerstudio.creature.IMobileBaseUI.setAllCSG(), com.neuronrobotics.bowlerstudio.creature.IMobileBaseUI.setCsg(), and eu.mihosoft.vrl.v3d.CSG.setName().
Referenced by com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.generateStls(), com.neuronrobotics.bowlerstudio.BowlerKernel.processReturnedObjects(), and com.neuronrobotics.bowlerstudio.BowlerKernel.processReturnedObjectsStart().
makeObj()
File com.neuronrobotics.bowlerstudio.creature.CadFileExporter.makeObj (String nameBase, CSG tmp) throws IOException private
Definition at line 138 of file CadFileExporter.java.
References eu.mihosoft.vrl.v3d.FileUtil.write().
Referenced by com.neuronrobotics.bowlerstudio.creature.CadFileExporter.generateManufacturingParts().
makeStl()
File com.neuronrobotics.bowlerstudio.creature.CadFileExporter.makeStl (String nameBase, CSG tmp) throws IOException private
Definition at line 131 of file CadFileExporter.java.
References eu.mihosoft.vrl.v3d.FileUtil.write().
Referenced by com.neuronrobotics.bowlerstudio.creature.CadFileExporter.generateManufacturingParts().
makeSvg()
File com.neuronrobotics.bowlerstudio.creature.CadFileExporter.makeSvg (String nameBase, List< CSG > currentCsg) throws IOException private
Definition at line 146 of file CadFileExporter.java.
References eu.mihosoft.vrl.v3d.CSG.addSlicePlane(), eu.mihosoft.vrl.v3d.svg.SVGExporter.export(), eu.mihosoft.vrl.v3d.CSG.getSlicePlanes(), eu.mihosoft.vrl.v3d.CSG.movez(), eu.mihosoft.vrl.v3d.CSG.setName(), and eu.mihosoft.vrl.v3d.CSG.toZMin().
Referenced by com.neuronrobotics.bowlerstudio.creature.CadFileExporter.generateManufacturingParts().
The documentation for this class was generated from the following file:
src/main/java/com/neuronrobotics/bowlerstudio/creature/CadFileExporter.java