BowlerKernel: com.neuronrobotics.sdk.dyio.peripherals.CounterOutputChannel Class Reference
com.neuronrobotics.sdk.dyio.peripherals.CounterOutputChannel Class Reference
Public Member Functions
CounterOutputChannel (int channel)
CounterOutputChannel (DyIO dyio, int channel)
CounterOutputChannel (DyIOChannel channel)
CounterOutputChannel (DyIOChannel channel, boolean isAsync)
boolean SetPosition (int pos)
boolean SetPosition (int pos, float time)
void addCounterOutputListener (ICounterOutputListener l)
void removeCounterOutputListener (ICounterOutputListener l)
void removeAllCounterOutputListeners ()
boolean setValue (int value)
void onChannelEvent (DyIOChannelEvent e)
boolean hasAsync ()
void setAsync (boolean isAsync)
Public Member Functions inherited from com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral
DyIOAbstractPeripheral (DyIOChannel channel, DyIOChannelMode myMode, boolean async)
DyIOChannelMode getClassMode ()
boolean isEnabled ()
boolean setMode ()
boolean setMode (boolean async)
boolean setMode (DyIOChannelMode mode, boolean async)
DyIOChannel getChannel ()
DyIOChannelMode getMode ()
boolean setValue (ByteList value) throws InvalidResponseException
int getValue () throws InvalidResponseException
boolean SavePosition (int pos)
boolean configAdvancedAsyncNotEqual ()
boolean configAdvancedAsyncDeadBand (int deadbandSize)
boolean configAdvancedAsyncTreshhold (int threshholdValue, AsyncThreshholdEdgeType edgeType)
boolean configAdvancedAsyncAutoSample ()
boolean configAdvancedAsyncNotEqual (int msTime)
boolean configAdvancedAsyncDeadBand (int msTime, int deadbandSize)
boolean configAdvancedAsyncTreshhold (int msTime, int threshholdValue, AsyncThreshholdEdgeType edgeType)
boolean configAdvancedAsyncAutoSample (int msTime)
boolean flush ()
int getConfiguration ()
Protected Member Functions
void fireOnCounterOutput (int value)
Private Member Functions
void init (DyIOChannel channel, boolean isAsync)
boolean validate ()
Private Attributes
ArrayList< ICounterOutputListener > listeners = new ArrayList<ICounterOutputListener>()
Detailed Description
The Class CounterOutputChannel.
Definition at line 34 of file CounterOutputChannel.java.
Constructor & Destructor Documentation
CounterOutputChannel() [1/4]
com.neuronrobotics.sdk.dyio.peripherals.CounterOutputChannel.CounterOutputChannel (int channel)
Constructor. Creates an counter input input channel that is syncronous only by default.
Parameters
channel - the channel object requested from the DyIO
Definition at line 45 of file CounterOutputChannel.java.
References com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral.channel, com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral.getChannel(), and com.neuronrobotics.sdk.common.DeviceManager.getSpecificDevice().
CounterOutputChannel() [2/4]
com.neuronrobotics.sdk.dyio.peripherals.CounterOutputChannel.CounterOutputChannel (DyIO dyio, int channel)
Constructor. Creates an counter input input channel that is syncronous only by default.
Parameters
dyio the dyio
channel - the channel object requested from the DyIO
Definition at line 56 of file CounterOutputChannel.java.
References com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral.channel, and com.neuronrobotics.sdk.dyio.DyIO.getChannel().
CounterOutputChannel() [3/4]
com.neuronrobotics.sdk.dyio.peripherals.CounterOutputChannel.CounterOutputChannel (DyIOChannel channel)
Constructor. Creates an counter input input channel that is syncronous only by default.
Parameters
channel - the channel object requested from the DyIO
Definition at line 66 of file CounterOutputChannel.java.
References com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral.channel.
CounterOutputChannel() [4/4]
com.neuronrobotics.sdk.dyio.peripherals.CounterOutputChannel.CounterOutputChannel (DyIOChannel channel, boolean isAsync)
Instantiates a new counter output channel.
Parameters
channel the channel
isAsync the is async
Definition at line 76 of file CounterOutputChannel.java.
References com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral.channel, com.neuronrobotics.sdk.dyio.DyIOChannelMode.COUNT_OUT_INT, and com.neuronrobotics.sdk.dyio.peripherals.CounterOutputChannel.init().
Member Function Documentation
addCounterOutputListener()
void com.neuronrobotics.sdk.dyio.peripherals.CounterOutputChannel.addCounterOutputListener (ICounterOutputListener l)
addCounterOutputListener.
Parameters
l add this listener to this channels event listeners
Definition at line 132 of file CounterOutputChannel.java.
References com.neuronrobotics.sdk.dyio.peripherals.CounterOutputChannel.listeners.
fireOnCounterOutput()
void com.neuronrobotics.sdk.dyio.peripherals.CounterOutputChannel.fireOnCounterOutput (int value) protected
Fire on counter output.
Parameters
value the value
Definition at line 166 of file CounterOutputChannel.java.
References com.neuronrobotics.sdk.dyio.peripherals.CounterOutputChannel.listeners.
Referenced by com.neuronrobotics.sdk.dyio.peripherals.CounterOutputChannel.onChannelEvent().
hasAsync()
boolean com.neuronrobotics.sdk.dyio.peripherals.CounterOutputChannel.hasAsync ()
This method is to check if this peripheral is capable to be set as up as asynchronous.
Returns
if it cna be async
Reimplemented from com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral.
Definition at line 196 of file CounterOutputChannel.java.
init()
void com.neuronrobotics.sdk.dyio.peripherals.CounterOutputChannel.init (DyIOChannel channel, boolean isAsync) private
Inits the.
Parameters
channel the channel
isAsync the is async
Definition at line 87 of file CounterOutputChannel.java.
References com.neuronrobotics.sdk.dyio.DyIOChannel.addChannelEventListener(), com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral.channel, com.neuronrobotics.sdk.dyio.DyIOChannelMode.COUNT_OUT_INT, com.neuronrobotics.sdk.dyio.DyIOChannel.resync(), and com.neuronrobotics.sdk.dyio.DyIOChannel.setMode().
Referenced by com.neuronrobotics.sdk.dyio.peripherals.CounterOutputChannel.CounterOutputChannel().
onChannelEvent()
void com.neuronrobotics.sdk.dyio.peripherals.CounterOutputChannel.onChannelEvent (DyIOChannelEvent e)
onChannelEvent Send the counter value to all the listening objects.
Parameters
e the e
Implements com.neuronrobotics.sdk.dyio.IChannelEventListener.
Definition at line 189 of file CounterOutputChannel.java.
References com.neuronrobotics.sdk.dyio.peripherals.CounterOutputChannel.fireOnCounterOutput(), and com.neuronrobotics.sdk.dyio.DyIOChannelEvent.getSignedValue().
removeAllCounterOutputListeners()
void com.neuronrobotics.sdk.dyio.peripherals.CounterOutputChannel.removeAllCounterOutputListeners ()
Removes the all counter output listeners.
Definition at line 157 of file CounterOutputChannel.java.
References com.neuronrobotics.sdk.dyio.peripherals.CounterOutputChannel.listeners.
removeCounterOutputListener()
void com.neuronrobotics.sdk.dyio.peripherals.CounterOutputChannel.removeCounterOutputListener (ICounterOutputListener l)
removeCounterOutputListener.
Parameters
l remove this listener to this channels event listeners
Definition at line 146 of file CounterOutputChannel.java.
References com.neuronrobotics.sdk.dyio.peripherals.CounterOutputChannel.listeners.
setAsync()
void com.neuronrobotics.sdk.dyio.peripherals.CounterOutputChannel.setAsync (boolean isAsync)
Sets the async.
Parameters
isAsync the new async
Reimplemented from com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral.
Definition at line 205 of file CounterOutputChannel.java.
References com.neuronrobotics.sdk.dyio.DyIOChannelMode.COUNT_OUT_INT, and com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral.setMode().
SetPosition() [1/2]
boolean com.neuronrobotics.sdk.dyio.peripherals.CounterOutputChannel.SetPosition (int pos)
Set the Counter to a given position.
Parameters
pos the pos
Returns
if the action was successful
Definition at line 102 of file CounterOutputChannel.java.
SetPosition() [2/2]
boolean com.neuronrobotics.sdk.dyio.peripherals.CounterOutputChannel.SetPosition (int pos, float time)
Steps the Counter though a transformation over a given amount of time.
Parameters
pos - the end position
time - the number of seconds for the transition to take place
Returns
if the action was successful
Definition at line 113 of file CounterOutputChannel.java.
References com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral.flush(), com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral.getChannel(), com.neuronrobotics.sdk.dyio.DyIOChannel.setCachedTime(), com.neuronrobotics.sdk.dyio.DyIOChannel.setCachedValue(), and com.neuronrobotics.sdk.dyio.peripherals.CounterOutputChannel.validate().
setValue()
boolean com.neuronrobotics.sdk.dyio.peripherals.CounterOutputChannel.setValue (int value)
This method sets the value of the output of the giver peripheral.
Parameters
value Sets this value to the channel
Returns
if the set worked
Exceptions
InvalidResponseException the invalid response exception
Reimplemented from com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral.
Definition at line 176 of file CounterOutputChannel.java.
References com.neuronrobotics.sdk.common.ByteList.addAs32(), and com.neuronrobotics.sdk.common.Log.info().
validate()
boolean com.neuronrobotics.sdk.dyio.peripherals.CounterOutputChannel.validate () private
Validate.
Returns
true, if successful
Definition at line 214 of file CounterOutputChannel.java.
References com.neuronrobotics.sdk.dyio.DyIOChannelMode.COUNT_OUT_INT, com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral.getMode(), and com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral.isEnabled().
Referenced by com.neuronrobotics.sdk.dyio.peripherals.CounterOutputChannel.SetPosition().
Member Data Documentation
listeners
ArrayList<ICounterOutputListener> com.neuronrobotics.sdk.dyio.peripherals.CounterOutputChannel.listeners = new ArrayList<ICounterOutputListener>() private
The listeners.
Definition at line 37 of file CounterOutputChannel.java.
Referenced by com.neuronrobotics.sdk.dyio.peripherals.CounterOutputChannel.addCounterOutputListener(), com.neuronrobotics.sdk.dyio.peripherals.CounterOutputChannel.fireOnCounterOutput(), com.neuronrobotics.sdk.dyio.peripherals.CounterOutputChannel.removeAllCounterOutputListeners(), and com.neuronrobotics.sdk.dyio.peripherals.CounterOutputChannel.removeCounterOutputListener().
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/dyio/peripherals/CounterOutputChannel.java