BowlerKernel: eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.SubList Class Reference
eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.SubList Class Reference
Public Member Functions
int[] toIntArray ()
Integer set (int index, Integer e)
Integer get (int index)
int size ()
void add (int index, Integer e)
Integer remove (int index)
boolean addAll (Collection<? extends Integer > c)
boolean addAll (int index, Collection<? extends Integer > c)
Iterator< Integer > iterator ()
ListIterator< Integer > listIterator (final int index)
List< Integer > subList (int fromIndex, int toIndex)
Public Member Functions inherited from eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList
IntegerArrayList (int initialCapacity)
IntegerArrayList ()
IntegerArrayList (Collection<? extends Integer > c)
void trimToSize ()
void ensureCapacity (int minCapacity)
boolean isEmpty ()
boolean contains (Object o)
int indexOf (Object o)
int lastIndexOf (Object o)
Object clone ()
Object[] toArray ()
boolean add (Integer e)
boolean remove (Object o)
void clear ()
boolean removeAll (Collection<?> c)
boolean retainAll (Collection<?> c)
ListIterator< Integer > listIterator ()
Protected Member Functions
void removeRange (int fromIndex, int toIndex)
Private Member Functions
void rangeCheck (int index)
void rangeCheckForAdd (int index)
String outOfBoundsMsg (int index)
void checkForComodification ()
Private Attributes
final IntegerArrayList parent
final int parentOffset
final int offset
Detailed Description
The Class SubList.
Definition at line 976 of file IntegerArrayList.java.
Member Function Documentation
add()
void eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.SubList.add (int index, Integer element)
Inserts the specified element at the specified position in this list. Shifts the element currently at that position (if any) and any subsequent elements to the right (adds one to their indices).
Parameters
index index at which the specified element is to be inserted
element element to be inserted
Exceptions
IndexOutOfBoundsException Inserts the specified element at the specified position in this list. Shifts the element currently at that position (if any) and any subsequent elements to the right (adds one to their indices).
Reimplemented from eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.
Definition at line 1049 of file IntegerArrayList.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.add(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.SubList.checkForComodification(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.SubList.parent, eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.SubList.parentOffset, and eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.SubList.rangeCheckForAdd().
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.SubList.listIterator().
addAll() [1/2]
boolean eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.SubList.addAll (Collection<? extends Integer > c)
Appends all of the elements in the specified collection to the end of this list, in the order that they are returned by the specified collection's Iterator. The behavior of this operation is undefined if the specified collection is modified while the operation is in progress. (This implies that the behavior of this call is undefined if the specified collection is this list, and this list is nonempty.)
Parameters
c collection containing elements to be added to this list
Returns
true if this list changed as a result of the call
Exceptions
NullPointerException if the specified collection is null
Reimplemented from eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.
Definition at line 1084 of file IntegerArrayList.java.
addAll() [2/2]
boolean eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.SubList.addAll (int index, Collection<? extends Integer > c)
Inserts all of the elements in the specified collection into this list, starting at the specified position. Shifts the element currently at that position (if any) and any subsequent elements to the right (increases their indices). The new elements will appear in the list in the order that they are returned by the specified collection's iterator.
Parameters
index index at which to insert the first element from the specified collection
c collection containing elements to be added to this list
Returns
true if this list changed as a result of the call
Exceptions
IndexOutOfBoundsException Inserts all of the elements in the specified collection into this list, starting at the specified position. Shifts the element currently at that position (if any) and any subsequent elements to the right (increases their indices). The new elements will appear in the list in the order that they are returned by the specified collection's iterator.
NullPointerException if the specified collection is null
Reimplemented from eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.
Definition at line 1091 of file IntegerArrayList.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.addAll(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.SubList.checkForComodification(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.SubList.parent, eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.SubList.parentOffset, and eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.SubList.rangeCheckForAdd().
checkForComodification()
void eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.SubList.checkForComodification () private
Check for comodification.
Definition at line 1255 of file IntegerArrayList.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.SubList.add(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.SubList.addAll(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.SubList.get(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.SubList.listIterator(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.SubList.remove(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.SubList.removeRange(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.SubList.set(), and eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.SubList.size().
get()
Integer eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.SubList.get (int index)
Returns the element at the specified position in this list.
Parameters
index index of the element to return
Returns
the element at the specified position in this list
Exceptions
IndexOutOfBoundsException Returns the element at the specified position in this list.
Reimplemented from eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.
Definition at line 1032 of file IntegerArrayList.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.SubList.checkForComodification(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.elementData, eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.SubList.offset, and eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.SubList.rangeCheck().
iterator()
Iterator<Integer> eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.SubList.iterator ()
Returns an iterator over the elements in this list in proper sequence.
The returned iterator is fail-fast.
Returns
an iterator over the elements in this list in proper sequence
Reimplemented from eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.
Definition at line 1107 of file IntegerArrayList.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.listIterator().
listIterator()
ListIterator<Integer> eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.SubList.listIterator (final int index)
Returns a list iterator over the elements in this list (in proper sequence), starting at the specified position in the list. The specified index indicates the first element that would be returned by an initial call to {next}. An initial call to ListIterator#previous previous} would return the element with the specified index minus one. The returned list iterator is fail-fast.
Parameters
index the index
Returns
the list iterator
Exceptions
IndexOutOfBoundsException Returns a list iterator over the elements in this list (in proper sequence), starting at the specified position in the list. The specified index indicates the first element that would be returned by an initial call to {next}. An initial call to ListIterator#previous previous} would return the element with the specified index minus one. The returned list iterator is fail-fast.
Reimplemented from eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.
Definition at line 1114 of file IntegerArrayList.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.SubList.add(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.SubList.checkForComodification(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.elementData, eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.SubList.offset, eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.SubList.rangeCheckForAdd(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.SubList.remove(), and eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.set().
outOfBoundsMsg()
String eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.SubList.outOfBoundsMsg (int index) private
Out of bounds msg.
Parameters
index the index
Returns
the string
Reimplemented from eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.
Definition at line 1248 of file IntegerArrayList.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.SubList.rangeCheck(), and eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.SubList.rangeCheckForAdd().
rangeCheck()
void eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.SubList.rangeCheck (int index) private
Range check.
Parameters
index the index
Reimplemented from eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.
Definition at line 1227 of file IntegerArrayList.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.SubList.outOfBoundsMsg().
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.SubList.get(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.SubList.remove(), and eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.SubList.set().
rangeCheckForAdd()
void eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.SubList.rangeCheckForAdd (int index) private
Range check for add.
Parameters
index the index
Reimplemented from eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.
Definition at line 1237 of file IntegerArrayList.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.SubList.outOfBoundsMsg().
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.SubList.add(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.SubList.addAll(), and eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.SubList.listIterator().
remove()
Integer eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.SubList.remove (int index)
Removes the element at the specified position in this list. Shifts any subsequent elements to the left (subtracts one from their indices).
Parameters
index the index of the element to be removed
Returns
the element that was removed from the list
Exceptions
IndexOutOfBoundsException Removes the element at the specified position in this list. Shifts any subsequent elements to the left (subtracts one from their indices).
Reimplemented from eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.
Definition at line 1060 of file IntegerArrayList.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.SubList.checkForComodification(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.SubList.parent, eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.SubList.parentOffset, eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.SubList.rangeCheck(), and eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.remove().
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.SubList.listIterator().
removeRange()
void eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.SubList.removeRange (int fromIndex, int toIndex) protected
Removes from this list all of the elements whose index is between
fromIndex
, inclusive, and
toIndex
, exclusive. Shifts any succeeding elements to the left (reduces their index). This call shortens the list by
(toIndex - fromIndex)
elements. (If
toIndex==fromIndex
, this operation has no effect.)
Parameters
fromIndex the from index
toIndex the to index
Exceptions
IndexOutOfBoundsException if
fromIndex
or
toIndex
is out of range (
fromIndex < 0
                                 || fromIndex >= size() || toIndex > size() || toIndex < fromIndex
)
Reimplemented from eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.
Definition at line 1072 of file IntegerArrayList.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.SubList.checkForComodification(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.SubList.parent, eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.SubList.parentOffset, and eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.removeRange().
set()
Integer eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.SubList.set (int index, Integer element)
Replaces the element at the specified position in this list with the specified element.
Parameters
index index of the element to replace
element element to be stored at the specified position
Returns
the element previously at the specified position
Exceptions
IndexOutOfBoundsException Replaces the element at the specified position in this list with the specified element.
Reimplemented from eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.
Definition at line 1021 of file IntegerArrayList.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.SubList.checkForComodification(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.elementData, eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.SubList.offset, and eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.SubList.rangeCheck().
size()
int eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.SubList.size ()
The size of the ArrayList (the number of elements it contains).
@serial
Reimplemented from eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.
Definition at line 1041 of file IntegerArrayList.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.SubList.checkForComodification().
subList()
List<Integer> eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.SubList.subList (int fromIndex, int toIndex)
Returns a view of the portion of this list between the specified
fromIndex
, inclusive, and
toIndex
, exclusive. (If
fromIndex
and
toIndex
are equal, the returned list is empty.) The returned list is backed by this list, so non-structural changes in the returned list are reflected in this list, and vice-versa. The returned list supports all of the optional list operations.
This method eliminates the need for explicit range operations (of the sort that commonly exist for arrays). Any operation that expects a list can be used as a range operation by passing a subList view instead of a whole list. For example, the following idiom removes a range of elements from a list:
 list.subList(from, to).clear();
Similar idioms may be constructed for indexOf(Object) and lastIndexOf(Object), and all of the algorithms in the Collections class can be applied to a subList.
The semantics of the list returned by this method become undefined if the backing list (i.e., this list) is structurally modified in any way other than via the returned list. (Structural modifications are those that change the size of this list, or otherwise perturb it in such a fashion that iterations in progress may yield incorrect results.)
Parameters
fromIndex the from index
toIndex the to index
Returns
the list
Exceptions
IndexOutOfBoundsException Returns a view of the portion of this list between the specified
fromIndex
, inclusive, and
toIndex
, exclusive. (If
fromIndex
and
toIndex
are equal, the returned list is empty.) The returned list is backed by this list, so non-structural changes in the returned list are reflected in this list, and vice-versa. The returned list supports all of the optional list operations. This method eliminates the need for explicit range operations (of the sort that commonly exist for arrays). Any operation that expects a list can be used as a range operation by passing a subList view instead of a whole list. For example, the following idiom removes a range of elements from a list:
 list.subList(from, to).clear();
Similar idioms may be constructed for indexOf(Object) and lastIndexOf(Object), and all of the algorithms in the Collections class can be applied to a subList. The semantics of the list returned by this method become undefined if the backing list (i.e., this list) is structurally modified in any way other than via the returned list. (Structural modifications are those that change the size of this list, or otherwise perturb it in such a fashion that iterations in progress may yield incorrect results.)
IllegalArgumentException Returns a view of the portion of this list between the specified
fromIndex
, inclusive, and
toIndex
, exclusive. (If
fromIndex
and
toIndex
are equal, the returned list is empty.) The returned list is backed by this list, so non-structural changes in the returned list are reflected in this list, and vice-versa. The returned list supports all of the optional list operations. This method eliminates the need for explicit range operations (of the sort that commonly exist for arrays). Any operation that expects a list can be used as a range operation by passing a subList view instead of a whole list. For example, the following idiom removes a range of elements from a list:
 list.subList(from, to).clear();
Similar idioms may be constructed for indexOf(Object) and lastIndexOf(Object), and all of the algorithms in the Collections class can be applied to a subList. The semantics of the list returned by this method become undefined if the backing list (i.e., this list) is structurally modified in any way other than via the returned list. (Structural modifications are those that change the size of this list, or otherwise perturb it in such a fashion that iterations in progress may yield incorrect results.)
Reimplemented from eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.
Definition at line 1217 of file IntegerArrayList.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.SubList.offset.
toIntArray()
int [] eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.SubList.toIntArray ()
To int array.
Returns
the int[]
Reimplemented from eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.
Definition at line 1012 of file IntegerArrayList.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.elementData, and eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.SubList.offset.
Member Data Documentation
offset
final int eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.SubList.offset private
The offset.
Definition at line 985 of file IntegerArrayList.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.SubList.get(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.SubList.listIterator(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.SubList.set(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.SubList.subList(), and eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.SubList.toIntArray().
parent
final IntegerArrayList eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.SubList.parent private
The parent.
Definition at line 979 of file IntegerArrayList.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.SubList.add(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.SubList.addAll(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.SubList.remove(), and eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.SubList.removeRange().
parentOffset
final int eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.SubList.parentOffset private
The parent offset.
Definition at line 982 of file IntegerArrayList.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.SubList.add(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.SubList.addAll(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.SubList.remove(), and eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.SubList.removeRange().
The documentation for this class was generated from the following file:
JCSG/src/main/java/eu/mihosoft/vrl/v3d/ext/openjfx/importers/obj/IntegerArrayList.java