BowlerKernel: eu.mihosoft.vrl.v3d.Toroid Class Reference
eu.mihosoft.vrl.v3d.Toroid Class Reference
Public Member Functions
Toroid (double innerRadius, double OuterRadius)
Toroid (double innerRadius, double OuterRadius, int numSlices, int facets)
List< Polygon > toPolygons ()
PropertyStorage getProperties ()
Public Member Functions inherited from eu.mihosoft.vrl.v3d.Primitive
CSG toCSG ()
Private Attributes
final PropertyStorage properties = new PropertyStorage()
Detailed Description
A solid cylinder.
The tessellation can be controlled via the numSlices parameter.
Author
Michael Hoffer <info@.nosp@m.mich.nosp@m.aelho.nosp@m.ffer.nosp@m..de>
Definition at line 48 of file Toroid.java.
Constructor & Destructor Documentation
Toroid() [1/2]
eu.mihosoft.vrl.v3d.Toroid.Toroid (double innerRadius, double OuterRadius)
Definition at line 53 of file Toroid.java.
Toroid() [2/2]
eu.mihosoft.vrl.v3d.Toroid.Toroid (double innerRadius, double OuterRadius, int numSlices, int facets)
Definition at line 56 of file Toroid.java.
References eu.mihosoft.vrl.v3d.Polygon.flipped(), eu.mihosoft.vrl.v3d.Polygon.fromPoints(), eu.mihosoft.vrl.v3d.Polygon.getStorage(), eu.mihosoft.vrl.v3d.Transform.movex(), eu.mihosoft.vrl.v3d.Toroid.properties, eu.mihosoft.vrl.v3d.Transform.roty(), eu.mihosoft.vrl.v3d.Polygon.transformed(), and eu.mihosoft.vrl.v3d.Polygon.vertices.
Member Function Documentation
getProperties()
PropertyStorage eu.mihosoft.vrl.v3d.Toroid.getProperties ()
Returns the property storage of this primitive.
Returns
the property storage of this primitive
Reimplemented from eu.mihosoft.vrl.v3d.Primitive.
Definition at line 129 of file Toroid.java.
References eu.mihosoft.vrl.v3d.Toroid.properties.
toPolygons()
List<Polygon> eu.mihosoft.vrl.v3d.Toroid.toPolygons ()
Returns the polygons that define this primitive.
Note: this method computes the polygons each time this method is called. The polygons can be cached inside a CSG object.
Returns
a list of polygons that define this primitive
Reimplemented from eu.mihosoft.vrl.v3d.Primitive.
Definition at line 119 of file Toroid.java.
Member Data Documentation
properties
final PropertyStorage eu.mihosoft.vrl.v3d.Toroid.properties = new PropertyStorage() private
The properties.
Definition at line 51 of file Toroid.java.
Referenced by eu.mihosoft.vrl.v3d.Toroid.getProperties(), and eu.mihosoft.vrl.v3d.Toroid.Toroid().
The documentation for this class was generated from the following file:
JCSG/src/main/java/eu/mihosoft/vrl/v3d/Toroid.java