BowlerKernel: com.neuronrobotics.bowlerstudio.creature.UserManagedPrintBed Class Reference
com.neuronrobotics.bowlerstudio.creature.UserManagedPrintBed Class Reference
Public Member Functions
UserManagedPrintBed (File printArrangment, MobileBaseCadManager mobileBaseCadManager) throws IOException
ArrayList< CSG > generateCad (DHParameterKinematics dh, int linkIndex)
ArrayList< CSG > generateBody (MobileBase base)
ArrayList< CSG > arrangeBed (MobileBase base)
Private Attributes
MobileBaseCadManager mobileBaseCadManager
String source
Detailed Description
Definition at line 26 of file UserManagedPrintBed.java.
Constructor & Destructor Documentation
UserManagedPrintBed()
com.neuronrobotics.bowlerstudio.creature.UserManagedPrintBed.UserManagedPrintBed (File printArrangment, MobileBaseCadManager mobileBaseCadManager) throws IOException
Definition at line 34 of file UserManagedPrintBed.java.
References com.neuronrobotics.sdk.addons.kinematics.MobileBase.getGitSelfSource(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getMobileBase(), com.neuronrobotics.bowlerstudio.creature.UserManagedPrintBed.mobileBaseCadManager, and com.neuronrobotics.bowlerstudio.creature.UserManagedPrintBed.source.
Member Function Documentation
arrangeBed()
ArrayList<CSG> com.neuronrobotics.bowlerstudio.creature.UserManagedPrintBed.arrangeBed (MobileBase base)
This function should generate the bed or beds or parts to be used in manufacturing If parts are to be ganged up to make print beds then this should happen here
Parameters
base the base to generate
Returns
simulatable CAD objects
Implements com.neuronrobotics.bowlerstudio.creature.IgenerateBed.
Definition at line 51 of file UserManagedPrintBed.java.
References com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getAllCad(), com.neuronrobotics.bowlerstudio.printbed.PrintBedManager.makePrintBeds(), com.neuronrobotics.bowlerstudio.creature.UserManagedPrintBed.mobileBaseCadManager, and com.neuronrobotics.bowlerstudio.creature.UserManagedPrintBed.source.
generateBody()
ArrayList<CSG> com.neuronrobotics.bowlerstudio.creature.UserManagedPrintBed.generateBody (MobileBase base)
This function should generate the body and any limbs of a given base. the user should attach any listeners from the DH link for simulation
Parameters
base the base to generate
Returns
simulatable CAD objects
Implements com.neuronrobotics.bowlerstudio.creature.IgenerateBody.
Definition at line 45 of file UserManagedPrintBed.java.
generateCad()
ArrayList<CSG> com.neuronrobotics.bowlerstudio.creature.UserManagedPrintBed.generateCad (DHParameterKinematics dh, int linkIndex)
This function should use the D-H parameters to generate cad objects to build this configuration the user should attach any listeners from the DH link for simulation
Parameters
dh the list of DH configurations
Returns
simulatable CAD objects
Implements com.neuronrobotics.bowlerstudio.creature.IgenerateCad.
Definition at line 40 of file UserManagedPrintBed.java.
Member Data Documentation
mobileBaseCadManager
MobileBaseCadManager com.neuronrobotics.bowlerstudio.creature.UserManagedPrintBed.mobileBaseCadManager private
Definition at line 28 of file UserManagedPrintBed.java.
Referenced by com.neuronrobotics.bowlerstudio.creature.UserManagedPrintBed.arrangeBed(), and com.neuronrobotics.bowlerstudio.creature.UserManagedPrintBed.UserManagedPrintBed().
source
String com.neuronrobotics.bowlerstudio.creature.UserManagedPrintBed.source private
Definition at line 33 of file UserManagedPrintBed.java.
Referenced by com.neuronrobotics.bowlerstudio.creature.UserManagedPrintBed.arrangeBed(), and com.neuronrobotics.bowlerstudio.creature.UserManagedPrintBed.UserManagedPrintBed().
The documentation for this class was generated from the following file:
src/main/java/com/neuronrobotics/bowlerstudio/creature/UserManagedPrintBed.java