BowlerKernel: com.neuronrobotics.sdk.commands.bcs.io.SetChannelValueCommand Class Reference
com.neuronrobotics.sdk.commands.bcs.io.SetChannelValueCommand Class Reference
Public Member Functions
SetChannelValueCommand (int channel, int value, DyIOChannelMode mode)
SetChannelValueCommand (int channel, int value, float time, DyIOChannelMode mode)
SetChannelValueCommand (int channel, ISendable data)
SetChannelValueCommand (int channel, int value, DyIOChannelMode mode, boolean saveTheValue)
SetChannelValueCommand (int channel, int[] value, DyIOChannelMode mode)
BowlerDatagram validate (BowlerDatagram data) throws InvalidResponseException
Public Member Functions inherited from com.neuronrobotics.sdk.common.BowlerAbstractCommand
byte[] getCallingData ()
void setOpCode (String opCode)
String getOpCode ()
void setMethod (BowlerMethod method)
BowlerMethod getMethod ()
byte getLength ()
byte[] getBytes ()
String toString ()
void setData (ByteList data)
ByteList getCallingDataStorage ()
void setNamespaceIndex (int namespaceIndex)
int getNamespaceIndex ()
Additional Inherited Members
Static Public Member Functions inherited from com.neuronrobotics.sdk.common.BowlerAbstractCommand
static BowlerAbstractCommand parse (BowlerDatagram data)
Detailed Description
The Class SetChannelValueCommand.
Definition at line 29 of file SetChannelValueCommand.java.
Constructor & Destructor Documentation
SetChannelValueCommand() [1/5]
com.neuronrobotics.sdk.commands.bcs.io.SetChannelValueCommand.SetChannelValueCommand (int channel, int value, DyIOChannelMode mode)
Instantiates a new sets the channel value command.
Parameters
channel the channel
value the value
mode the mode
Definition at line 38 of file SetChannelValueCommand.java.
References com.neuronrobotics.sdk.common.ByteList.add(), com.neuronrobotics.sdk.common.ByteList.addAs16(), com.neuronrobotics.sdk.common.ByteList.addAs32(), com.neuronrobotics.sdk.common.BowlerAbstractCommand.getCallingDataStorage(), com.neuronrobotics.sdk.common.BowlerMethod.POST, com.neuronrobotics.sdk.common.BowlerAbstractCommand.setMethod(), and com.neuronrobotics.sdk.common.BowlerAbstractCommand.setOpCode().
SetChannelValueCommand() [2/5]
com.neuronrobotics.sdk.commands.bcs.io.SetChannelValueCommand.SetChannelValueCommand (int channel, int value, float time, DyIOChannelMode mode)
SetChannelValueCommand.
Parameters
channel the DyIO pin to use
value the value to set the pin to
time the time it should take for the action to be performed in seconds
mode the mode the channel is in
Definition at line 71 of file SetChannelValueCommand.java.
References com.neuronrobotics.sdk.common.ByteList.add(), com.neuronrobotics.sdk.common.ByteList.addAs16(), com.neuronrobotics.sdk.common.ByteList.addAs32(), com.neuronrobotics.sdk.common.BowlerAbstractCommand.getCallingDataStorage(), com.neuronrobotics.sdk.common.BowlerMethod.POST, com.neuronrobotics.sdk.common.BowlerAbstractCommand.setMethod(), and com.neuronrobotics.sdk.common.BowlerAbstractCommand.setOpCode().
SetChannelValueCommand() [3/5]
com.neuronrobotics.sdk.commands.bcs.io.SetChannelValueCommand.SetChannelValueCommand (int channel, ISendable data)
Instantiates a new sets the channel value command.
Parameters
channel the channel
data the data
Definition at line 100 of file SetChannelValueCommand.java.
References com.neuronrobotics.sdk.common.ByteList.add(), com.neuronrobotics.sdk.common.BowlerAbstractCommand.data, com.neuronrobotics.sdk.common.BowlerAbstractCommand.getCallingDataStorage(), com.neuronrobotics.sdk.common.BowlerMethod.POST, com.neuronrobotics.sdk.common.BowlerAbstractCommand.setMethod(), and com.neuronrobotics.sdk.common.BowlerAbstractCommand.setOpCode().
SetChannelValueCommand() [4/5]
com.neuronrobotics.sdk.commands.bcs.io.SetChannelValueCommand.SetChannelValueCommand (int channel, int value, DyIOChannelMode mode, boolean saveTheValue)
SetChannelValueCommand.
Parameters
channel the DyIO pin to use
value the value to set the pin to
mode the mode the channel is in
saveTheValue if true, the value is saved as the starting position for the channel
Definition at line 121 of file SetChannelValueCommand.java.
References com.neuronrobotics.sdk.common.ByteList.add(), com.neuronrobotics.sdk.common.BowlerMethod.CRITICAL, com.neuronrobotics.sdk.common.BowlerAbstractCommand.getCallingDataStorage(), com.neuronrobotics.sdk.common.BowlerMethod.POST, com.neuronrobotics.sdk.common.BowlerAbstractCommand.setMethod(), and com.neuronrobotics.sdk.common.BowlerAbstractCommand.setOpCode().
SetChannelValueCommand() [5/5]
com.neuronrobotics.sdk.commands.bcs.io.SetChannelValueCommand.SetChannelValueCommand (int channel, int[] value, DyIOChannelMode mode)
SetChannelValueCommand.
Parameters
channel the DyIO pin to use
value the value to set the pin to
mode the mode the channel is in
Definition at line 145 of file SetChannelValueCommand.java.
References com.neuronrobotics.sdk.common.ByteList.add(), com.neuronrobotics.sdk.common.BowlerAbstractCommand.getCallingDataStorage(), com.neuronrobotics.sdk.common.BowlerMethod.POST, com.neuronrobotics.sdk.common.BowlerAbstractCommand.setMethod(), and com.neuronrobotics.sdk.common.BowlerAbstractCommand.setOpCode().
Member Function Documentation
validate()
BowlerDatagram com.neuronrobotics.sdk.commands.bcs.io.SetChannelValueCommand.validate (BowlerDatagram data) throws InvalidResponseException
Determine if the return response was successful; throw an InvalidResponseExpection otherwise. Commands with more complicated validation should override this method and provide more specific checking.
Parameters
data the data
Returns
the incoming response
Exceptions
InvalidResponseException the invalid response exception
Reimplemented from com.neuronrobotics.sdk.common.BowlerAbstractCommand.
Definition at line 163 of file SetChannelValueCommand.java.
References com.neuronrobotics.sdk.common.BowlerAbstractCommand.data.
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/commands/bcs/io/SetChannelValueCommand.java