BowlerKernel: com.neuronrobotics.bowlerstudio.IssueReportingExceptionHandler Class Reference
com.neuronrobotics.bowlerstudio.IssueReportingExceptionHandler Class Reference
Public Member Functions
IssueReportingExceptionHandler ()
void uncaughtException (Thread t, Throwable e)
void except (Throwable e, String stacktraceFromCatch)
void except (Throwable t)
Static Public Member Functions
static void runLater (Runnable r)
static void runLater (Runnable r, Throwable ex)
static String getTitle (Throwable element)
static String getTitle (StackTraceElement[] element)
Private Member Functions
void runReport (StackTraceElement[] element, String body, GitHub github)
boolean checkIgnoreExceptions (Throwable t)
Private Attributes
int fxExceptionCount
Static Private Attributes
static int timerErrorCount = 0
static boolean processing = false
static HashMap< Throwable, String > exceptionQueue = new HashMap<Throwable, String>()
static boolean reportIssues = false
static HashMap< String, Integer > exceptionCounter = new HashMap<String, Integer>()
Detailed Description
Definition at line 30 of file IssueReportingExceptionHandler.java.
Constructor & Destructor Documentation
IssueReportingExceptionHandler()
com.neuronrobotics.bowlerstudio.IssueReportingExceptionHandler.IssueReportingExceptionHandler ()
Definition at line 40 of file IssueReportingExceptionHandler.java.
Member Function Documentation
checkIgnoreExceptions()
boolean com.neuronrobotics.bowlerstudio.IssueReportingExceptionHandler.checkIgnoreExceptions (Throwable t) private
Definition at line 263 of file IssueReportingExceptionHandler.java.
Referenced by com.neuronrobotics.bowlerstudio.IssueReportingExceptionHandler.except().
except() [1/2]
void com.neuronrobotics.bowlerstudio.IssueReportingExceptionHandler.except (Throwable e, String stacktraceFromCatch)
Definition at line 71 of file IssueReportingExceptionHandler.java.
References com.neuronrobotics.bowlerstudio.IssueReportingExceptionHandler.checkIgnoreExceptions(), com.neuronrobotics.bowlerstudio.IssueReportingExceptionHandler.exceptionCounter, com.neuronrobotics.bowlerstudio.scripting.PasswordManager.getGithub(), com.neuronrobotics.bowlerstudio.IssueReportingExceptionHandler.getTitle(), com.neuronrobotics.sdk.config.SDKBuildInfo.getVersion(), com.neuronrobotics.javacad.JavaCadBuildInfo.getVersion(), com.neuronrobotics.bowlerkernel.BowlerKernelBuildInfo.getVersion(), com.neuronrobotics.bowlerstudio.assets.StudioBuildInfo.getVersion(), com.neuronrobotics.bowlerstudio.IssueReportingExceptionHandler.processing, com.neuronrobotics.bowlerstudio.IssueReportingExceptionHandler.reportIssues, com.neuronrobotics.bowlerstudio.IssueReportingExceptionHandler.runReport(), and com.neuronrobotics.bowlerstudio.IssueReportingExceptionHandler.timerErrorCount.
Referenced by com.neuronrobotics.bowlerstudio.vitamins.Vitamins.getConfigurationRW(), com.neuronrobotics.bowlerstudio.assets.AssetFactory.loadIcon(), and com.neuronrobotics.bowlerstudio.IssueReportingExceptionHandler.uncaughtException().
except() [2/2]
void com.neuronrobotics.bowlerstudio.IssueReportingExceptionHandler.except (Throwable t)
Definition at line 233 of file IssueReportingExceptionHandler.java.
getTitle() [1/2]
static String com.neuronrobotics.bowlerstudio.IssueReportingExceptionHandler.getTitle (StackTraceElement[] element) static
Definition at line 275 of file IssueReportingExceptionHandler.java.
getTitle() [2/2]
static String com.neuronrobotics.bowlerstudio.IssueReportingExceptionHandler.getTitle (Throwable element) static
Definition at line 271 of file IssueReportingExceptionHandler.java.
Referenced by com.neuronrobotics.bowlerstudio.IssueReportingExceptionHandler.except(), and com.neuronrobotics.bowlerstudio.IssueReportingExceptionHandler.runReport().
runLater() [1/2]
static void com.neuronrobotics.bowlerstudio.IssueReportingExceptionHandler.runLater (Runnable r) static
Definition at line 55 of file IssueReportingExceptionHandler.java.
runLater() [2/2]
static void com.neuronrobotics.bowlerstudio.IssueReportingExceptionHandler.runLater (Runnable r, Throwable ex) static
Definition at line 59 of file IssueReportingExceptionHandler.java.
runReport()
void com.neuronrobotics.bowlerstudio.IssueReportingExceptionHandler.runReport (StackTraceElement[] element, String body, GitHub github) private
Definition at line 166 of file IssueReportingExceptionHandler.java.
References com.neuronrobotics.bowlerstudio.IssueReportingExceptionHandler.getTitle(), com.neuronrobotics.bowlerstudio.assets.StudioBuildInfo.getVersion(), and com.neuronrobotics.bowlerstudio.BowlerKernel.upenURL().
Referenced by com.neuronrobotics.bowlerstudio.IssueReportingExceptionHandler.except().
uncaughtException()
void com.neuronrobotics.bowlerstudio.IssueReportingExceptionHandler.uncaughtException (Thread t, Throwable e)
Definition at line 46 of file IssueReportingExceptionHandler.java.
References com.neuronrobotics.bowlerstudio.IssueReportingExceptionHandler.except().
Referenced by com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.closeGit(), com.neuronrobotics.bowlerstudio.vitamins.Vitamins.getGitRepoDatabase(), com.neuronrobotics.bowlerstudio.vitamins.Vitamins.reLoadDatabaseFromFiles(), com.neuronrobotics.bowlerstudio.scripting.GitTimeoutThread.run(), and com.neuronrobotics.bowlerstudio.vitamins.Vitamins.saveDatabaseForkIfMissing().
Member Data Documentation
exceptionCounter
HashMap<String, Integer> com.neuronrobotics.bowlerstudio.IssueReportingExceptionHandler.exceptionCounter = new HashMap<String, Integer>() static private
Definition at line 38 of file IssueReportingExceptionHandler.java.
Referenced by com.neuronrobotics.bowlerstudio.IssueReportingExceptionHandler.except().
exceptionQueue
HashMap<Throwable, String> com.neuronrobotics.bowlerstudio.IssueReportingExceptionHandler.exceptionQueue = new HashMap<Throwable, String>() static private
Definition at line 35 of file IssueReportingExceptionHandler.java.
fxExceptionCount
int com.neuronrobotics.bowlerstudio.IssueReportingExceptionHandler.fxExceptionCount private
Definition at line 33 of file IssueReportingExceptionHandler.java.
processing
boolean com.neuronrobotics.bowlerstudio.IssueReportingExceptionHandler.processing = false static private
Definition at line 34 of file IssueReportingExceptionHandler.java.
Referenced by com.neuronrobotics.bowlerstudio.IssueReportingExceptionHandler.except().
reportIssues
boolean com.neuronrobotics.bowlerstudio.IssueReportingExceptionHandler.reportIssues = false static private
Definition at line 36 of file IssueReportingExceptionHandler.java.
Referenced by com.neuronrobotics.bowlerstudio.IssueReportingExceptionHandler.except().
timerErrorCount
int com.neuronrobotics.bowlerstudio.IssueReportingExceptionHandler.timerErrorCount = 0 static private
Definition at line 31 of file IssueReportingExceptionHandler.java.
Referenced by com.neuronrobotics.bowlerstudio.IssueReportingExceptionHandler.except().
The documentation for this class was generated from the following file:
src/main/java/com/neuronrobotics/bowlerstudio/IssueReportingExceptionHandler.java