BowlerKernel: com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics Class Reference
com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics Class Reference
Public Member Functions
DHParameterKinematics (BowlerAbstractDevice bad, Element linkStream)
DHParameterKinematics (BowlerAbstractDevice bad, InputStream linkStream)
DHParameterKinematics (BowlerAbstractDevice bad, InputStream linkStream, InputStream depricated)
DHParameterKinematics (BowlerAbstractDevice bad)
DHParameterKinematics (BowlerAbstractDevice bad, String file)
DHParameterKinematics (BowlerAbstractDevice bad, File configFile) throws FileNotFoundException
DHParameterKinematics ()
DHParameterKinematics (String file)
DHParameterKinematics (Element linkStream)
DHParameterKinematics (File configFile) throws FileNotFoundException
double[] inverseKinematics (TransformNR taskSpaceTransform) throws Exception
TransformNR forwardKinematics (double[] jointSpaceVector)
Matrix getJacobian (DHChain chain, double[] jointSpaceVector, int index)
Matrix getJacobian ()
Matrix getJacobian (int index)
Matrix getJacobian (double[] jointSpaceVector, int index)
ArrayList< TransformNR > getChainTransformations ()
void setDhChain (DHChain chain)
DHChain getDhChain ()
DHChain getChain ()
void setChain (DHChain chain)
String getXml ()
String getEmbedableXml ()
void disconnectDevice ()
boolean connectDevice ()
void onTaskSpaceUpdate (AbstractKinematicsNR source, TransformNR pose)
void onTargetTaskSpaceUpdate (AbstractKinematicsNR source, TransformNR pose)
DhInverseSolver getInverseSolver ()
void setInverseSolver (DhInverseSolver inverseSolver)
Object getCurrentTargetObject ()
void addNewLink (LinkConfiguration newLink, DHLink dhLink)
void removeLink (int index)
ArrayList< TransformNR > updateCadLocations ()
void onJointSpaceUpdate (final AbstractKinematicsNR source, final double[] joints)
void setGlobalToFiducialTransform (TransformNR frameToBase)
void onJointSpaceTargetUpdate (AbstractKinematicsNR source, double[] joints)
void onJointSpaceLimit (AbstractKinematicsNR source, int axis, JointLimit event)
TransformNR linkCoM (double linkAngleToClaculate, int linkIndex)
TransformNR linkCoM (int linkIndex)
Object getLinkObjectManipulator (int index)
double getDH_Theta (int index)
double getDH_D (int index)
double getDH_R (int index)
double getDH_Alpha (int index)
void setDH_Theta (int index, double value)
void setDH_D (int index, double value)
void setDH_R (int index, double value)
void setDH_Alpha (int index, double value)
DHLink getDhLink (int i)
Object getListener (int i)
void setRobotToFiducialTransform (TransformNR newTrans)
void refreshPose ()
MobileBase getSlaveMobileBase (int index)
void throwExceptionOnJointLimit (boolean b)
TransformNR getLinkTip (int linkIndex)
Public Member Functions inherited from com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR
Object getRootListener ()
void setRootListener (Object listener)
ArrayList< String > getNamespacesImp ()
void disconnectDeviceImp ()
boolean connectDeviceImp ()
AbstractKinematicsNR ()
AbstractKinematicsNR (InputStream configFile, LinkFactory f)
AbstractKinematicsNR (Element doc, LinkFactory f)
LinkConfiguration getLinkConfiguration (int linkIndex)
ArrayList< LinkConfiguration > getLinkConfigurations ()
PIDConfiguration getLinkCurrentConfiguration (int chan)
void setLinkCurrentConfiguration (int chan, PIDConfiguration c)
AbstractLink getAbstractLink (int index)
int getNumberOfLinks ()
TransformNR getCurrentTaskSpaceTransform ()
double readLinkValue (int index)
double readLinkTarget (int index)
double[] getCurrentJointSpaceVector ()
double[] getCurrentJointSpaceTarget ()
double getCurrentLinkEngineeringUnits (int linkIndex)
double[] setDesiredTaskSpaceTransform (TransformNR taskSpaceTransform, double seconds) throws Exception
boolean checkTaskSpaceTransform (TransformNR taskSpaceTransform, double seconds)
boolean checkTaskSpaceTransform (TransformNR taskSpaceTransform)
double getBestTime (TransformNR currentTaskSpaceTransform)
double getBestTime (double[] jointSpaceVect)
double[] setDesiredJointSpaceVector (double[] jointSpaceVect, double seconds) throws Exception
TransformNR calcForward (double[] jointSpaceVect)
TransformNR calcHome ()
void setDesiredJointAxisValue (int axis, double value, double seconds) throws Exception
void firePoseUpdate ()
TransformNR getFiducialToGlobalTransform ()
TransformNR getRobotToFiducialTransform ()
void setGlobalToFiducialTransform (TransformNR frameToBase, boolean fireUpdate)
TransformNR inverseOffset (TransformNR t)
TransformNR forwardOffset (TransformNR t)
void addJointSpaceListener (IJointSpaceUpdateListenerNR l)
void removeJointSpaceUpdateListener (IJointSpaceUpdateListenerNR l)
void addRegistrationListener (IRegistrationListenerNR l)
void removeRegestrationUpdateListener (IRegistrationListenerNR l)
void addPoseUpdateListener (ITaskSpaceUpdateListenerNR l)
void removePoseUpdateListener (ITaskSpaceUpdateListenerNR l)
void onLinkPositionUpdate (AbstractLink source, double engineeringUnitsValue)
void onPIDEvent (PIDEvent e)
void onPIDLimitEvent (PIDLimitEvent e)
void onPIDReset (int group, float currentValue)
void homeAllLinks ()
void homeLink (int link)
void emergencyStop ()
ArrayList< PIDConfiguration > getAxisPidConfiguration ()
TransformNR getCurrentPoseTarget ()
void setCurrentPoseTarget (TransformNR currentPoseTarget)
void setFactory (LinkFactory factory)
LinkFactory getFactory ()
void setNoFlush (boolean noFlush)
boolean isNoFlush ()
int getRetryNumberBeforeFail ()
void setRetryNumberBeforeFail (int retryNumberBeforeFail)
void onLinkLimit (AbstractLink arg0, PIDLimitEvent arg1)
DHChain getDhParametersChain ()
void setDhParametersChain (DHChain dhParametersChain)
String[] getGitDhEngine ()
void setGitDhEngine (String[] dhEngine)
String[] getGitCadEngine ()
void setGitCadEngine (String[] cadEngine)
IMU getImu ()
void boundedLinkValueSet (int index, double value) throws Exception
double boundToLinkLimits (int index, double value)
double linkMass (int linkIndex)
double getMaxEngineeringUnits (int linkIndex)
double getMinEngineeringUnits (int linkIndex)
void setMaxEngineeringUnits (int linkIndex, double maxLimit)
void setMinEngineeringUnits (int linkIndex, double minLimit)
String getElectroMechanicalType (int linkIndex)
void setElectroMechanicalType (int linkIndex, String electroMechanicalType)
String getElectroMechanicalSize (int linkIndex)
void setElectroMechanicalSize (int linkIndex, String electroMechanicalSize)
String getShaftType (int linkIndex)
void setShaftType (int linkIndex, String shaftType)
String getShaftSize (int linkIndex)
void setDeviceMaximumValue (int linkIndex, double max)
void setDeviceMinimumValue (int linkIndex, double min)
double getDeviceMaximumValue (int linkIndex)
double getDeviceMinimumValue (int linkIndex)
void addChangeListener (int linkIndex, ILinkConfigurationChangeListener l)
void removeChangeListener (int linkIndex, ILinkConfigurationChangeListener l)
void clearChangeListener (int linkIndex)
void runRenderWrangler ()
void setRenderWrangler (Runnable renderWrangler)
TransformNR getDeltaToTarget (TransformNR target)
TransformNR getTipAlongTrajectory (TransformNR startingPoint, TransformNR deltaToTarget, double unitIncrement)
void asyncInterpolatedMove (TransformNR target, double seconds, InterpolationType type, IOnInterpolationDone listener, double ...conf)
InterpolationMoveState blockingInterpolatedMove (TransformNR target, double seconds, InterpolationType type, double ...conf)
Public Member Functions inherited from com.neuronrobotics.sdk.common.NonBowlerDevice
boolean connect ()
boolean isAvailable () throws InvalidConnectionException
void disconnect ()
void onAsyncResponse (BowlerDatagram data)
ArrayList< String > getNamespaces ()
Public Member Functions inherited from com.neuronrobotics.sdk.common.BowlerAbstractDevice
void addConnectionEventListener (final IDeviceConnectionEventListener l)
void removeConnectionEventListener (IDeviceConnectionEventListener l)
void setConnection (BowlerAbstractConnection connection)
BowlerAbstractConnection getConnection ()
void setAddress (MACAddress address)
MACAddress getAddress ()
BowlerDatagram send (BowlerAbstractCommand command) throws NoConnectionAvailableException, InvalidResponseException
BowlerDatagram send (BowlerAbstractCommand command, int retry) throws NoConnectionAvailableException, InvalidResponseException
Object[] send (String namespace, BowlerMethod method, String rpcString, Object[] arguments, int retry) throws DeviceConnectionException
Object[] send (String namespace, BowlerMethod method, String rpcString, Object[] arguments) throws DeviceConnectionException
boolean ping ()
boolean ping (boolean switchParser)
ArrayList< ByteList > getRevisions ()
boolean hasNamespace (String string)
void startHeartBeat ()
void startHeartBeat (long msHeartBeatTime)
void stopHeartBeat ()
void setThreadedUpstreamPackets (boolean up)
ArrayList< RpcEncapsulation > getRpcList (String namespace)
void loadRpcList ()
void onAllResponse (BowlerDatagram data)
boolean isKeepAlive ()
void setKeepAlive (boolean keepAlive)
long getLastPacketTime ()
void setLastPacketTime (long lastPacketTime)
String getScriptingName ()
void setScriptingName (String scriptingName)
ArrayList< IDeviceConnectionEventListener > getDisconnectListeners ()
Private Member Functions
double[] crossProduct (double[] a, double[] b)
Private Attributes
DHChain chain = null
ArrayList< Object > linksListeners = new ArrayList<Object>()
Object currentTarget = new Object()
ArrayList< LinkConfiguration > configs
Additional Inherited Members
Static Public Member Functions inherited from com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR
static boolean checkTaskSpaceTransform (AbstractKinematicsNR dev, TransformNR taskSpaceTransform, double seconds)
static boolean checkTaskSpaceTransform (AbstractKinematicsNR dev, TransformNR taskSpaceTransform)
Protected Member Functions inherited from com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR
ArrayList< LinkConfiguration > loadConfig (Element doc)
LinkFactory getDevice ()
void setDevice (LinkFactory f, ArrayList< LinkConfiguration > linkConfigs)
void firePoseTransform (TransformNR transform)
void fireTargetJointsUpdate (double[] jointSpaceVector, TransformNR fwd)
String getCode (Element e, String tag)
String[] getGitCodes (Element doc, String tag)
Protected Member Functions inherited from com.neuronrobotics.sdk.common.BowlerAbstractDevice
void fireDisconnectEvent ()
void fireConnectEvent ()
Protected Attributes inherited from com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR
ArrayList< IJointSpaceUpdateListenerNR > jointSpaceUpdateListeners = new ArrayList<IJointSpaceUpdateListenerNR>()
Detailed Description
The Class DHParameterKinematics.
Definition at line 23 of file DHParameterKinematics.java.
Constructor & Destructor Documentation
DHParameterKinematics() [1/10]
com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.DHParameterKinematics (BowlerAbstractDevice bad, Element linkStream)
Instantiates a new DH parameter kinematics.
Parameters
bad the bad
linkStream the link stream
Definition at line 64 of file DHParameterKinematics.java.
References com.neuronrobotics.sdk.common.BowlerAbstractDevice.addConnectionEventListener(), com.neuronrobotics.sdk.common.NonBowlerDevice.disconnect(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getDhParametersChain(), com.neuronrobotics.sdk.addons.kinematics.LinkFactory.getDyio(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getFactory(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getLinkConfigurations(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getNumberOfLinks(), com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getSlaveMobileBase(), and com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.setChain().
DHParameterKinematics() [2/10]
com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.DHParameterKinematics (BowlerAbstractDevice bad, InputStream linkStream)
Instantiates a new DH parameter kinematics.
Parameters
bad the bad
linkStream the link stream
Definition at line 99 of file DHParameterKinematics.java.
References com.neuronrobotics.sdk.common.BowlerAbstractDevice.addConnectionEventListener(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getDhParametersChain(), com.neuronrobotics.sdk.addons.kinematics.LinkFactory.getDyio(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getFactory(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getLinkConfigurations(), and com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.setChain().
DHParameterKinematics() [3/10]
com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.DHParameterKinematics (BowlerAbstractDevice bad, InputStream linkStream, InputStream depricated)
Instantiates a new DH parameter kinematics.
Parameters
bad the bad
linkStream the link stream
depricated the depricated
Definition at line 120 of file DHParameterKinematics.java.
DHParameterKinematics() [4/10]
com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.DHParameterKinematics (BowlerAbstractDevice bad)
Instantiates a new DH parameter kinematics.
Parameters
bad the bad
Definition at line 130 of file DHParameterKinematics.java.
References com.neuronrobotics.sdk.addons.kinematics.xml.XmlFactory.getDefaultConfigurationStream().
DHParameterKinematics() [5/10]
com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.DHParameterKinematics (BowlerAbstractDevice bad, String file)
Instantiates a new DH parameter kinematics.
Parameters
bad the bad
file the file
Definition at line 142 of file DHParameterKinematics.java.
References com.neuronrobotics.sdk.addons.kinematics.xml.XmlFactory.getDefaultConfigurationStream().
DHParameterKinematics() [6/10]
com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.DHParameterKinematics (BowlerAbstractDevice bad, File configFile) throws FileNotFoundException
Instantiates a new DH parameter kinematics.
Parameters
bad the bad
configFile the config file
Exceptions
FileNotFoundException the file not found exception
Definition at line 156 of file DHParameterKinematics.java.
DHParameterKinematics() [7/10]
com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.DHParameterKinematics ()
Instantiates a new DH parameter kinematics.
Definition at line 163 of file DHParameterKinematics.java.
DHParameterKinematics() [8/10]
com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.DHParameterKinematics (String file)
Instantiates a new DH parameter kinematics.
Parameters
file the file
Definition at line 173 of file DHParameterKinematics.java.
References com.neuronrobotics.sdk.addons.kinematics.xml.XmlFactory.getDefaultConfigurationStream().
DHParameterKinematics() [9/10]
com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.DHParameterKinematics (Element linkStream)
Instantiates a new DH parameter kinematics.
Parameters
linkStream the link stream
Definition at line 183 of file DHParameterKinematics.java.
DHParameterKinematics() [10/10]
com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.DHParameterKinematics (File configFile) throws FileNotFoundException
Instantiates a new DH parameter kinematics.
Parameters
configFile the config file
Exceptions
FileNotFoundException the file not found exception
Definition at line 195 of file DHParameterKinematics.java.
Member Function Documentation
addNewLink()
void com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.addNewLink (LinkConfiguration newLink, DHLink dhLink)
Adds the new link.
Parameters
newLink the new link
dhLink the dh link
Definition at line 580 of file DHParameterKinematics.java.
References com.neuronrobotics.sdk.addons.kinematics.DHChain.addLink(), com.neuronrobotics.sdk.addons.kinematics.LinkFactory.addLinkListener(), com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.chain, com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.factory, com.neuronrobotics.sdk.addons.kinematics.AbstractLink.flush(), com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getDhChain(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getFactory(), com.neuronrobotics.sdk.addons.kinematics.LinkFactory.getLink(), com.neuronrobotics.sdk.addons.kinematics.DHLink.getListener(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.isPrismatic(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.isTool(), com.neuronrobotics.sdk.addons.kinematics.DhLinkType.PRISMATIC, com.neuronrobotics.sdk.addons.kinematics.LinkFactory.removeLinkListener(), com.neuronrobotics.sdk.addons.kinematics.DhLinkType.ROTORY, com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.setChain(), com.neuronrobotics.sdk.addons.kinematics.DHChain.setFactory(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setGlobalPositionListener(), com.neuronrobotics.sdk.addons.kinematics.DHLink.setLinkType(), and com.neuronrobotics.sdk.addons.kinematics.DhLinkType.TOOL.
Referenced by com.neuronrobotics.bowlerstudio.scripting.RobotHelper.getDefaultContents().
connectDevice()
boolean com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.connectDevice ()
Connect device.
Returns
true, if successful
Reimplemented from com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.
Reimplemented in com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.
Definition at line 512 of file DHParameterKinematics.java.
crossProduct()
double [] com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.crossProduct (double[] a, double[] b) private
Cross product.
Parameters
a the a
b the b
Returns
the double[]
Definition at line 230 of file DHParameterKinematics.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getJacobian().
disconnectDevice()
void com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.disconnectDevice ()
This method tells the connection object to disconnect its pipes and close out the connection. Once this is called, it is safe to remove your device.
Reimplemented from com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.
Reimplemented in com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.
Definition at line 499 of file DHParameterKinematics.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.removeJointSpaceUpdateListener(), and com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.removePoseUpdateListener().
forwardKinematics()
TransformNR com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.forwardKinematics (double[] jointSpaceVector)
Forward kinematics.
Parameters
jointSpaceVector the joint space vector
Returns
6x1 vector in task space, unit in mm,radians [x,y,z,rotx,rotY,rotZ]
Reimplemented from com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.
Reimplemented in com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.
Definition at line 217 of file DHParameterKinematics.java.
References com.neuronrobotics.sdk.addons.kinematics.DHChain.forwardKinematics(), and com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getDhChain().
Referenced by com.neuronrobotics.bowlerstudio.physics.MobileBasePhysicsManager.MobileBasePhysicsManager().
getChain()
DHChain com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getChain ()
Gets the chain.
Returns
the chain
Definition at line 401 of file DHParameterKinematics.java.
References com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.chain.
Referenced by com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.compute(), com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getChainTransformations(), com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getDH_Alpha(), com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getDH_D(), com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getDH_R(), com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getDH_Theta(), com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getDhChain(), com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getLinkObjectManipulator(), com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getLinkTip(), com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.linkCoM(), com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.onJointSpaceUpdate(), com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.setDH_Alpha(), com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.setDH_D(), com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.setDH_R(), com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.setDH_Theta(), com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.setGlobalToFiducialTransform(), com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.updateCadLocations(), and com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.updateLimb().
getChainTransformations()
ArrayList<TransformNR> com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getChainTransformations ()
Gets the chain transformations.
Returns
the chain transformations
Definition at line 373 of file DHParameterKinematics.java.
References com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getChain(), com.neuronrobotics.sdk.addons.kinematics.DHChain.getChain(), and com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getCurrentJointSpaceVector().
getCurrentTargetObject()
Object com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getCurrentTargetObject ()
Gets the current target Object.
Returns
the current target Object
Definition at line 568 of file DHParameterKinematics.java.
References com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.currentTarget.
getDH_Alpha()
double com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getDH_Alpha (int index)
Gets the alpha.
Returns
the alpha
Definition at line 753 of file DHParameterKinematics.java.
References com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getChain(), and com.neuronrobotics.sdk.addons.kinematics.DHChain.getLinks().
getDH_D()
double com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getDH_D (int index)
Gets the d.
Returns
the d
Definition at line 733 of file DHParameterKinematics.java.
References com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getChain(), and com.neuronrobotics.sdk.addons.kinematics.DHChain.getLinks().
getDH_R()
double com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getDH_R (int index)
Gets the r.
Returns
the r
Definition at line 744 of file DHParameterKinematics.java.
References com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getChain(), and com.neuronrobotics.sdk.addons.kinematics.DHChain.getLinks().
getDH_Theta()
double com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getDH_Theta (int index)
Gets the theta.
Returns
the theta
Definition at line 725 of file DHParameterKinematics.java.
References com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getChain(), and com.neuronrobotics.sdk.addons.kinematics.DHChain.getLinks().
getDhChain()
DHChain com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getDhChain ()
Gets the dh chain.
Returns
the dh chain
Definition at line 392 of file DHParameterKinematics.java.
References com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getChain().
Referenced by com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.addNewLink(), com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.forwardKinematics(), com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getDhLink(), com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getJacobian(), com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getListener(), com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.inverseKinematics(), com.neuronrobotics.bowlerstudio.physics.MobileBasePhysicsManager.MobileBasePhysicsManager(), and com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.removeLink().
getDhLink()
DHLink com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getDhLink (int i)
Definition at line 795 of file DHParameterKinematics.java.
References com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getDhChain(), and com.neuronrobotics.sdk.addons.kinematics.DHChain.getLinks().
Referenced by com.neuronrobotics.sdk.addons.kinematics.MobileBase.addListeners(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.generateCad(), and com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getSlaveMobileBase().
getEmbedableXml()
String com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getEmbedableXml ()
Gets the embedable xml.
Returns
the embedable xml
Definition at line 461 of file DHParameterKinematics.java.
References com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.chain, com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getFiducialToGlobalTransform(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getGitCadEngine(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getGitDhEngine(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getLinkConfiguration(), com.neuronrobotics.sdk.addons.kinematics.DHChain.getLinks(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getRobotToFiducialTransform(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getXml(), and com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getXml().
Referenced by com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getXml(), and com.neuronrobotics.sdk.addons.kinematics.MobileBase.makeLimbTag().
getInverseSolver()
DhInverseSolver com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getInverseSolver ()
Gets the inverse solver.
Returns
the inverse solver
Definition at line 549 of file DHParameterKinematics.java.
References com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.chain, and com.neuronrobotics.sdk.addons.kinematics.DHChain.getInverseSolver().
getJacobian() [1/4]
Matrix com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getJacobian ()
Gets the Jacobian matrix.
Returns
a matrix representing the Jacobian for the current configuration
Definition at line 348 of file DHParameterKinematics.java.
References com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getDhChain().
Referenced by com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getJacobian().
getJacobian() [2/4]
Matrix com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getJacobian (DHChain chain, double[] jointSpaceVector, int index)
Gets the Jacobian matrix.
Parameters
jointSpaceVector the joint space vector
Returns
a matrix representing the Jacobian for the current configuration
Definition at line 245 of file DHParameterKinematics.java.
References com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.chain, com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.crossProduct(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.forwardOffset(), com.neuronrobotics.sdk.addons.kinematics.DHChain.getChain(), com.neuronrobotics.sdk.addons.kinematics.DHChain.getLinks(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getMatrixTransform(), com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.getRotationMatrix(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getRotationMatrix(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getX(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getY(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getZ(), and com.neuronrobotics.sdk.addons.kinematics.DhLinkType.ROTORY.
getJacobian() [3/4]
Matrix com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getJacobian (double[] jointSpaceVector, int index)
Gets the Jacobian matrix.
Returns
a matrix representing the Jacobian for the current configuration
Definition at line 364 of file DHParameterKinematics.java.
References com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getDhChain(), and com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getJacobian().
getJacobian() [4/4]
Matrix com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getJacobian (int index)
Gets the Jacobian matrix.
Returns
a matrix representing the Jacobian for the current configuration
Definition at line 356 of file DHParameterKinematics.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getCurrentJointSpaceVector(), and com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getJacobian().
getLinkObjectManipulator()
Object com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getLinkObjectManipulator (int index)
Definition at line 716 of file DHParameterKinematics.java.
References com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getChain(), and com.neuronrobotics.sdk.addons.kinematics.DHChain.getLinks().
getLinkTip()
TransformNR com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getLinkTip (int linkIndex)
Definition at line 830 of file DHParameterKinematics.java.
References com.neuronrobotics.sdk.addons.kinematics.DHChain.getCachedChain(), and com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getChain().
getListener()
Object com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getListener (int i)
Definition at line 798 of file DHParameterKinematics.java.
References com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getDhChain(), and com.neuronrobotics.sdk.addons.kinematics.DHChain.getLinks().
getSlaveMobileBase()
MobileBase com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getSlaveMobileBase (int index)
Definition at line 814 of file DHParameterKinematics.java.
References com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getDhLink(), and com.neuronrobotics.sdk.addons.kinematics.DHLink.getSlaveMobileBase().
Referenced by com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.DHParameterKinematics(), and com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.updateLimb().
getXml()
String com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getXml ()
Gets the xml.
Returns
the xml
Reimplemented from com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.
Definition at line 445 of file DHParameterKinematics.java.
References com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getEmbedableXml().
inverseKinematics()
double [] com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.inverseKinematics (TransformNR taskSpaceTransform) throws Exception
Inverse kinematics.
Parameters
taskSpaceTransform the task space transform
Returns
Nx1 vector in task space, in mm where N is number of links
Exceptions
Exception the exception
Reimplemented from com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.
Reimplemented in com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.
Definition at line 206 of file DHParameterKinematics.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getCurrentJointSpaceVector(), com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getDhChain(), and com.neuronrobotics.sdk.addons.kinematics.DHChain.inverseKinematics().
linkCoM() [1/2]
TransformNR com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.linkCoM (double linkAngleToClaculate, int linkIndex)
Definition at line 705 of file DHParameterKinematics.java.
References com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getChain(), com.neuronrobotics.sdk.addons.kinematics.DHChain.getChain(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getCurrentJointSpaceVector(), and com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getLinkConfiguration().
Referenced by com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.linkCoM().
linkCoM() [2/2]
TransformNR com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.linkCoM (int linkIndex)
Definition at line 713 of file DHParameterKinematics.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getCurrentJointSpaceVector(), and com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.linkCoM().
onJointSpaceLimit()
void com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.onJointSpaceLimit (AbstractKinematicsNR source, int axis, JointLimit event)
The JointSpace limit This is called when the kinematics model has a new set of pose data.
Parameters
source The AbstractKinematics object that the update was called from
axis the axis
event the event
Implements com.neuronrobotics.sdk.addons.kinematics.IJointSpaceUpdateListenerNR.
Definition at line 698 of file DHParameterKinematics.java.
onJointSpaceTargetUpdate()
void com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.onJointSpaceTargetUpdate (AbstractKinematicsNR source, double[] joints)
The JointSpace update event This is called when the kinematics model has a new set of pose data.
Parameters
source The AbstractKinematics object that the update was called from
joints the current joint space values mm,radians
Implements com.neuronrobotics.sdk.addons.kinematics.IJointSpaceUpdateListenerNR.
Definition at line 684 of file DHParameterKinematics.java.
onJointSpaceUpdate()
void com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.onJointSpaceUpdate (final AbstractKinematicsNR source, final double[] joints)
The JointSpace update event This is called when the kinematics model has a new set of pose data.
Parameters
source The AbstractKinematics object that the update was called from
joints the current joint space values mm,radians
Implements com.neuronrobotics.sdk.addons.kinematics.IJointSpaceUpdateListenerNR.
Definition at line 646 of file DHParameterKinematics.java.
References com.neuronrobotics.sdk.addons.kinematics.DHLink.fireOnLinkGlobalPositionChange(), com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getChain(), com.neuronrobotics.sdk.addons.kinematics.DHChain.getLinks(), and com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.updateCadLocations().
onTargetTaskSpaceUpdate()
void com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.onTargetTaskSpaceUpdate (AbstractKinematicsNR source, TransformNR pose)
The position update event This is called when the kinematics model has a new set of target data.
Parameters
source The AbstractKinematics object that the update was called from
pose target pose transform
Implements com.neuronrobotics.sdk.addons.kinematics.ITaskSpaceUpdateListenerNR.
Definition at line 539 of file DHParameterKinematics.java.
onTaskSpaceUpdate()
void com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.onTaskSpaceUpdate (AbstractKinematicsNR source, TransformNR pose)
The position update event This is called when the kinematics model has a new set of pose data.
Parameters
source The AbstractKinematics object that the update was called from
pose the current pose transform
Implements com.neuronrobotics.sdk.addons.kinematics.ITaskSpaceUpdateListenerNR.
Definition at line 526 of file DHParameterKinematics.java.
refreshPose()
void com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.refreshPose ()
Definition at line 811 of file DHParameterKinematics.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.runRenderWrangler().
removeLink()
void com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.removeLink (int index)
Removes the link.
Parameters
index the index
Definition at line 611 of file DHParameterKinematics.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkFactory.addLinkListener(), com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.chain, com.neuronrobotics.sdk.addons.kinematics.LinkFactory.deleteLink(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.factory, com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getDhChain(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getFactory(), com.neuronrobotics.sdk.addons.kinematics.DHChain.getLinks(), com.neuronrobotics.sdk.addons.kinematics.LinkFactory.removeLinkListener(), and com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.setChain().
setChain()
void com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.setChain (DHChain chain)
Sets the chain.
Parameters
chain the new chain
Definition at line 411 of file DHParameterKinematics.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.addJointSpaceListener(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.addPoseUpdateListener(), com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.chain, com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.configs, com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getFactory(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getLinkConfiguration(), com.neuronrobotics.sdk.addons.kinematics.LinkFactory.getLinkConfigurations(), com.neuronrobotics.sdk.addons.kinematics.DHChain.getLinks(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getRootListener(), com.neuronrobotics.sdk.addons.kinematics.DhLinkType.PRISMATIC, com.neuronrobotics.sdk.addons.kinematics.DhLinkType.ROTORY, and com.neuronrobotics.sdk.addons.kinematics.DhLinkType.TOOL.
Referenced by com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.addNewLink(), com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.DHParameterKinematics(), com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.removeLink(), and com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.setDhChain().
setDH_Alpha()
void com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.setDH_Alpha (int index, double value)
Gets the alpha.
Definition at line 791 of file DHParameterKinematics.java.
References com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getChain(), and com.neuronrobotics.sdk.addons.kinematics.DHChain.getLinks().
setDH_D()
void com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.setDH_D (int index, double value)
Gets the d.
Definition at line 771 of file DHParameterKinematics.java.
References com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getChain(), and com.neuronrobotics.sdk.addons.kinematics.DHChain.getLinks().
setDH_R()
void com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.setDH_R (int index, double value)
Gets the r.
Definition at line 782 of file DHParameterKinematics.java.
References com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getChain(), and com.neuronrobotics.sdk.addons.kinematics.DHChain.getLinks().
setDH_Theta()
void com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.setDH_Theta (int index, double value)
Gets the theta.
Definition at line 763 of file DHParameterKinematics.java.
References com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getChain(), and com.neuronrobotics.sdk.addons.kinematics.DHChain.getLinks().
setDhChain()
void com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.setDhChain (DHChain chain)
Sets the dh chain.
Parameters
chain the new dh chain
Definition at line 383 of file DHParameterKinematics.java.
References com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.setChain().
setGlobalToFiducialTransform()
void com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.setGlobalToFiducialTransform (TransformNR frameToBase)
Sets the global to fiducial transform.
Parameters
frameToBase the new global to fiducial transform
Reimplemented from com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.
Definition at line 663 of file DHParameterKinematics.java.
References com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getChain(), com.neuronrobotics.sdk.addons.kinematics.DHChain.getChain(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getCurrentJointSpaceVector(), com.neuronrobotics.sdk.common.BowlerAbstractDevice.getScriptingName(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.runRenderWrangler(), and com.neuronrobotics.sdk.addons.kinematics.DHChain.setChain().
Referenced by com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.updateLimb().
setInverseSolver()
void com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.setInverseSolver (DhInverseSolver inverseSolver)
Sets the inverse solver.
Parameters
inverseSolver the new inverse solver
Definition at line 559 of file DHParameterKinematics.java.
References com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.chain, and com.neuronrobotics.sdk.addons.kinematics.DHChain.setInverseSolver().
Referenced by com.neuronrobotics.bowlerstudio.creature.MobileBaseLoader.setDefaultDhParameterKinematics().
setRobotToFiducialTransform()
void com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.setRobotToFiducialTransform (TransformNR newTrans)
Sets the robot to fiducial transform.
Parameters
newTrans the new robot to fiducial transform
Reimplemented from com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.
Definition at line 807 of file DHParameterKinematics.java.
throwExceptionOnJointLimit()
void com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.throwExceptionOnJointLimit (boolean b)
THis disables the exception being thrown on joint limits normal mode is to throw an exception when a joint is commanded to a value beyond its limits
when exceptions are disabled, the joint just goes to the limit instead.
Parameters
b
Definition at line 824 of file DHParameterKinematics.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getAbstractLink(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getNumberOfLinks(), and com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setUseLimits().
updateCadLocations()
ArrayList<TransformNR> com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.updateCadLocations ()
Update cad locations.
Definition at line 627 of file DHParameterKinematics.java.
References com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getChain(), com.neuronrobotics.sdk.addons.kinematics.DHChain.getChain(), and com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getCurrentJointSpaceVector().
Referenced by com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.onJointSpaceUpdate().
Member Data Documentation
chain
DHChain com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.chain = null private
The chain.
Definition at line 27 of file DHParameterKinematics.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.addNewLink(), com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getChain(), com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getEmbedableXml(), com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getInverseSolver(), com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getJacobian(), com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.removeLink(), com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.setChain(), and com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.setInverseSolver().
configs
ArrayList<LinkConfiguration> com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.configs private
Definition at line 54 of file DHParameterKinematics.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.setChain().
currentTarget
Object com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.currentTarget = new Object() private
The current target.
Definition at line 33 of file DHParameterKinematics.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getCurrentTargetObject().
linksListeners
ArrayList<Object> com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.linksListeners = new ArrayList<Object>() private
The links listeners.
Definition at line 30 of file DHParameterKinematics.java.
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/addons/kinematics/DHParameterKinematics.java