BowlerKernel: eu.mihosoft.vrl.v3d.XModifier Class Reference
eu.mihosoft.vrl.v3d.XModifier Class Reference
Public Member Functions
XModifier ()
XModifier (boolean centered)
double eval (Vector3d pos, CSG csg)
Private Attributes
Bounds bounds
double min = 0
double max = 1.0
double sPerUnit
boolean centered
Detailed Description
Modifies along x axis.
Author
Michael Hoffer <info@.nosp@m.mich.nosp@m.aelho.nosp@m.ffer.nosp@m..de>
Definition at line 14 of file XModifier.java.
Constructor & Destructor Documentation
XModifier() [1/2]
eu.mihosoft.vrl.v3d.XModifier.XModifier ()
Constructor.
Definition at line 35 of file XModifier.java.
XModifier() [2/2]
eu.mihosoft.vrl.v3d.XModifier.XModifier (boolean centered)
Constructor.
Parameters
centered defines whether to center origin at the csg location
Definition at line 43 of file XModifier.java.
References eu.mihosoft.vrl.v3d.XModifier.centered.
Member Function Documentation
eval()
double eu.mihosoft.vrl.v3d.XModifier.eval (Vector3d v, CSG csg)
Evaluates the function at the specified location.
Parameters
v location
csg csg
Returns
the weight of the specified position
Implements eu.mihosoft.vrl.v3d.WeightFunction.
Definition at line 51 of file XModifier.java.
References eu.mihosoft.vrl.v3d.XModifier.bounds, eu.mihosoft.vrl.v3d.XModifier.centered, eu.mihosoft.vrl.v3d.CSG.getBounds(), eu.mihosoft.vrl.v3d.Bounds.getMax(), eu.mihosoft.vrl.v3d.Bounds.getMin(), eu.mihosoft.vrl.v3d.XModifier.max, eu.mihosoft.vrl.v3d.XModifier.min, eu.mihosoft.vrl.v3d.XModifier.sPerUnit, and eu.mihosoft.vrl.v3d.Vector3d.x().
Member Data Documentation
bounds
Bounds eu.mihosoft.vrl.v3d.XModifier.bounds private
The bounds.
Definition at line 17 of file XModifier.java.
Referenced by eu.mihosoft.vrl.v3d.XModifier.eval().
centered
boolean eu.mihosoft.vrl.v3d.XModifier.centered private
The centered.
Definition at line 29 of file XModifier.java.
Referenced by eu.mihosoft.vrl.v3d.XModifier.eval(), and eu.mihosoft.vrl.v3d.XModifier.XModifier().
max
double eu.mihosoft.vrl.v3d.XModifier.max = 1.0 private
The max.
Definition at line 23 of file XModifier.java.
Referenced by eu.mihosoft.vrl.v3d.XModifier.eval().
min
double eu.mihosoft.vrl.v3d.XModifier.min = 0 private
The min.
Definition at line 20 of file XModifier.java.
Referenced by eu.mihosoft.vrl.v3d.XModifier.eval().
sPerUnit
double eu.mihosoft.vrl.v3d.XModifier.sPerUnit private
The s per unit.
Definition at line 26 of file XModifier.java.
Referenced by eu.mihosoft.vrl.v3d.XModifier.eval().
The documentation for this class was generated from the following file:
JCSG/src/main/java/eu/mihosoft/vrl/v3d/XModifier.java