BowlerKernel: com.neuronrobotics.sdk.addons.kinematics.AbstractLink Class Reference
com.neuronrobotics.sdk.addons.kinematics.AbstractLink Class Reference abstract
Public Member Functions
double getDeviceMaximumValue ()
double getDeviceMinimumValue ()
void setDeviceMaximumValue (double max)
void setDeviceMinimumValue (double min)
double getDeviceMaxEngineeringUnits ()
double getDeviceMinEngineeringUnits ()
AbstractLink (LinkConfiguration conf)
void cacheTargetValue ()
abstract void cacheTargetValueDevice ()
void flush (double time)
void flushAll (double time)
abstract void flushDevice (double time)
abstract void flushAllDevice (double time)
abstract double getCurrentPosition ()
double toEngineeringUnits (double value)
double toLinkUnits (double euValue)
void addLinkListener (ILinkListener l)
void removeLinkListener (ILinkListener l)
void fireLinkListener (double linkUnitsValue)
void fireLinkLimitEvent (PIDLimitEvent e)
void Home ()
void incrementEngineeringUnits (double inc)
void setTargetEngineeringUnits (double pos)
void setCurrentEngineeringUnits (double angle)
double getCurrentEngineeringUnits ()
double getTargetEngineeringUnits ()
double getMaxEngineeringUnits ()
double getMinEngineeringUnits ()
void setMinEngineeringUnits (double minLimit)
void setMaxEngineeringUnits (double maxLimit)
double getMaxVelocityEngineeringUnits ()
void setMaxVelocityEngineeringUnits (double max)
boolean isMaxEngineeringUnits ()
boolean isMinEngineeringUnits ()
double getTargetValue ()
void setUpperLimit (int upperLimit)
void setLowerLimit (int lowerLimit)
void setHome (int home)
void setScale (double d)
double getScale ()
double getUpperLimit ()
double getLowerLimit ()
double getHome ()
void setCurrentAsUpperLimit ()
void setCurrentAsLowerLimit ()
void setUseLimits (boolean useLimits)
boolean isUseLimits ()
void setLinkConfiguration (LinkConfiguration conf)
LinkConfiguration getLinkConfiguration ()
ArrayList< ILinkListener > getLinks ()
void setLinks (ArrayList< ILinkListener > links)
void removeAllLinkListener ()
void setGlobalPositionListener (Object Object)
Object getGlobalPositionListener ()
LinkFactory getSlaveFactory ()
void setSlaveFactory (LinkFactory slaveFactory)
IMU getImu ()
void addChangeListener (ILinkConfigurationChangeListener l)
void removeChangeListener (ILinkConfigurationChangeListener l)
void clearChangeListener ()
Protected Member Functions
void setPosition (double val)
void setTargetValue (double val)
Private Attributes
double targetValue =0
double targetEngineeringUnits =0
ArrayList< ILinkListener > links = new ArrayList<ILinkListener>()
LinkConfiguration conf =null
ArrayList< LinkConfiguration > slaveLinks
LinkFactory slaveFactory = new LinkFactory()
boolean useLimits =true
Object linksLocation =null
IMU imu = new IMU()
Detailed Description
The Class AbstractLink.
Definition at line 22 of file AbstractLink.java.
Constructor & Destructor Documentation
AbstractLink()
com.neuronrobotics.sdk.addons.kinematics.AbstractLink.AbstractLink (LinkConfiguration conf)
Instantiates a new abstract link.
Parameters
conf the conf
Definition at line 101 of file AbstractLink.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractLink.conf, com.neuronrobotics.sdk.addons.kinematics.LinkFactory.getLink(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getName(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getSlaveFactory(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getSlaveLinks(), and com.neuronrobotics.sdk.addons.kinematics.AbstractLink.slaveLinks.
Member Function Documentation
addChangeListener()
void com.neuronrobotics.sdk.addons.kinematics.AbstractLink.addChangeListener (ILinkConfigurationChangeListener l)
Definition at line 686 of file AbstractLink.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.addChangeListener(), and com.neuronrobotics.sdk.addons.kinematics.AbstractLink.conf.
addLinkListener()
void com.neuronrobotics.sdk.addons.kinematics.AbstractLink.addLinkListener (ILinkListener l)
Adds the link listener.
Parameters
l the l
Definition at line 209 of file AbstractLink.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getLinks().
Referenced by com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.generateCad(), com.neuronrobotics.bowlerstudio.physics.MobileBasePhysicsManager.MobileBasePhysicsManager(), and com.neuronrobotics.sdk.addons.kinematics.LinkFactory.refreshHardwareLayer().
cacheTargetValue()
void com.neuronrobotics.sdk.addons.kinematics.AbstractLink.cacheTargetValue ()
This method is called in order to take the target value and pass it to the implementation's target value This method should not alter the position of the implementations link If the implementation target does not handle chached values, this should be chached in code.
Definition at line 116 of file AbstractLink.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractLink.cacheTargetValue(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.cacheTargetValueDevice(), com.neuronrobotics.sdk.addons.kinematics.LinkFactory.getLink(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getSlaveFactory(), and com.neuronrobotics.sdk.addons.kinematics.AbstractLink.slaveLinks.
Referenced by com.neuronrobotics.sdk.addons.kinematics.AbstractLink.cacheTargetValue(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.Home(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setPosition(), and com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setTargetValue().
cacheTargetValueDevice()
abstract void com.neuronrobotics.sdk.addons.kinematics.AbstractLink.cacheTargetValueDevice () abstract
This method is called in order to take the target value and pass it to the implementation's target value This method should not alter the position of the implementations link If the implementation target does not handle chached values, this should be chached in code.
Reimplemented in com.neuronrobotics.sdk.addons.kinematics.PidRotoryLink, com.neuronrobotics.sdk.addons.kinematics.PidPrismaticLink, com.neuronrobotics.sdk.addons.kinematics.MockRotoryLink, com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeRotory, com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodePrismatic, com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GCodeHeater, com.neuronrobotics.sdk.addons.kinematics.AnalogRotoryLink, and com.neuronrobotics.sdk.addons.kinematics.AnalogPrismaticLink.
Referenced by com.neuronrobotics.sdk.addons.kinematics.AbstractLink.cacheTargetValue().
clearChangeListener()
void com.neuronrobotics.sdk.addons.kinematics.AbstractLink.clearChangeListener ()
Definition at line 692 of file AbstractLink.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.clearChangeListener(), and com.neuronrobotics.sdk.addons.kinematics.AbstractLink.conf.
fireLinkLimitEvent()
void com.neuronrobotics.sdk.addons.kinematics.AbstractLink.fireLinkLimitEvent (PIDLimitEvent e)
This fires off a limit event.
Parameters
e the e
Definition at line 251 of file AbstractLink.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getLinks().
Referenced by com.neuronrobotics.sdk.addons.kinematics.PidRotoryLink.setPIDChannel(), and com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setTargetValue().
fireLinkListener()
void com.neuronrobotics.sdk.addons.kinematics.AbstractLink.fireLinkListener (double linkUnitsValue)
This method sends the updated angle value to all listeners.
Parameters
linkUnitsValue the link units value
Definition at line 233 of file AbstractLink.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getLinks(), com.neuronrobotics.sdk.addons.kinematics.ILinkListener.onLinkPositionUpdate(), and com.neuronrobotics.sdk.addons.kinematics.AbstractLink.toEngineeringUnits().
Referenced by com.neuronrobotics.sdk.addons.kinematics.PidPrismaticLink.flushAllDevice(), com.neuronrobotics.sdk.addons.kinematics.PidRotoryLink.flushAllDevice(), com.neuronrobotics.sdk.addons.kinematics.PidPrismaticLink.flushDevice(), com.neuronrobotics.sdk.addons.kinematics.PidRotoryLink.flushDevice(), com.neuronrobotics.sdk.addons.kinematics.AnalogPrismaticLink.getCurrentPosition(), com.neuronrobotics.sdk.addons.kinematics.AnalogRotoryLink.getCurrentPosition(), com.neuronrobotics.sdk.addons.kinematics.AnalogPrismaticLink.onAnalogValueChange(), com.neuronrobotics.sdk.addons.kinematics.AnalogRotoryLink.onAnalogValueChange(), com.neuronrobotics.sdk.addons.kinematics.PidPrismaticLink.setPIDChannel(), com.neuronrobotics.sdk.addons.kinematics.PidRotoryLink.setPIDChannel(), com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodePrismatic.setValue(), and com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeRotory.setValue().
flush()
void com.neuronrobotics.sdk.addons.kinematics.AbstractLink.flush (double time)
This method will force one link to update its position in the given time (seconds).
Parameters
time (seconds) for the position update to take
Implements com.neuronrobotics.sdk.common.IFlushable.
Definition at line 137 of file AbstractLink.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractLink.flush(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.flushDevice(), com.neuronrobotics.sdk.addons.kinematics.LinkFactory.getLink(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getSlaveFactory(), and com.neuronrobotics.sdk.addons.kinematics.AbstractLink.slaveLinks.
Referenced by com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.addNewLink(), com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.flush(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.flush(), and com.neuronrobotics.sdk.addons.kinematics.LinkFactory.flush().
flushAll()
void com.neuronrobotics.sdk.addons.kinematics.AbstractLink.flushAll (double time)
This method will force one link to update its position in the given time (seconds) This will also flush the host controller.
Parameters
time (seconds) for the position update to take
Definition at line 152 of file AbstractLink.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractLink.flushAll(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.flushAllDevice(), com.neuronrobotics.sdk.addons.kinematics.LinkFactory.getLink(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getSlaveFactory(), and com.neuronrobotics.sdk.addons.kinematics.AbstractLink.slaveLinks.
Referenced by com.neuronrobotics.sdk.addons.kinematics.AbstractLink.flushAll().
flushAllDevice()
abstract void com.neuronrobotics.sdk.addons.kinematics.AbstractLink.flushAllDevice (double time) abstract
This method will force one link to update its position in the given time (seconds) This will also flush the host controller.
Parameters
time (seconds) for the position update to take
Reimplemented in com.neuronrobotics.sdk.addons.kinematics.PidRotoryLink, com.neuronrobotics.sdk.addons.kinematics.PidPrismaticLink, com.neuronrobotics.sdk.addons.kinematics.MockRotoryLink, com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeRotory, com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodePrismatic, com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GCodeHeater, com.neuronrobotics.sdk.addons.kinematics.AnalogRotoryLink, and com.neuronrobotics.sdk.addons.kinematics.AnalogPrismaticLink.
Referenced by com.neuronrobotics.sdk.addons.kinematics.AbstractLink.flushAll().
flushDevice()
abstract void com.neuronrobotics.sdk.addons.kinematics.AbstractLink.flushDevice (double time) abstract
This method will force one link to update its position in the given time (seconds).
Parameters
time (seconds) for the position update to take
Reimplemented in com.neuronrobotics.sdk.addons.kinematics.PidRotoryLink, com.neuronrobotics.sdk.addons.kinematics.PidPrismaticLink, com.neuronrobotics.sdk.addons.kinematics.MockRotoryLink, com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeRotory, com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodePrismatic, com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GCodeHeater, com.neuronrobotics.sdk.addons.kinematics.AnalogRotoryLink, and com.neuronrobotics.sdk.addons.kinematics.AnalogPrismaticLink.
Referenced by com.neuronrobotics.sdk.addons.kinematics.AbstractLink.flush().
getCurrentEngineeringUnits()
double com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getCurrentEngineeringUnits ()
Gets the current engineering units.
Returns
the current engineering units
Definition at line 309 of file AbstractLink.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getCurrentPosition(), and com.neuronrobotics.sdk.addons.kinematics.AbstractLink.toEngineeringUnits().
Referenced by com.neuronrobotics.sdk.addons.kinematics.AbstractRotoryLink.getCurrentAngle(), and com.neuronrobotics.sdk.addons.kinematics.AbstractPrismaticLink.getCurrentDisplacment().
getCurrentPosition()
abstract double com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getCurrentPosition () abstract
This method should return the current position of the link This method is expected to perform a communication with the device .
Returns
the current position of the link
Reimplemented in com.neuronrobotics.sdk.addons.kinematics.PidRotoryLink, com.neuronrobotics.sdk.addons.kinematics.PidPrismaticLink, com.neuronrobotics.sdk.addons.kinematics.MockRotoryLink, com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeRotory, com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodePrismatic, com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GCodeHeater, com.neuronrobotics.sdk.addons.kinematics.AnalogRotoryLink, and com.neuronrobotics.sdk.addons.kinematics.AnalogPrismaticLink.
Referenced by com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.flush(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getCurrentEngineeringUnits(), com.neuronrobotics.bowlerstudio.physics.MobileBasePhysicsManager.MobileBasePhysicsManager(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setCurrentAsLowerLimit(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setCurrentAsUpperLimit(), and com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setCurrentEngineeringUnits().
getDeviceMaxEngineeringUnits()
double com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getDeviceMaxEngineeringUnits ()
Gets the max engineering units.
Returns
the max engineering units
Definition at line 78 of file AbstractLink.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractLink.conf, com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getDeviceMaximumValue(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getDeviceMinimumValue(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getScale(), and com.neuronrobotics.sdk.addons.kinematics.AbstractLink.toEngineeringUnits().
getDeviceMaximumValue()
double com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getDeviceMaximumValue ()
Override this method to specify a larger range
Returns
the maximum value possible for a link
Definition at line 50 of file AbstractLink.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractLink.conf, and com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getDeviceTheoreticalMax().
Referenced by com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getDeviceMaxEngineeringUnits(), and com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getDeviceMinEngineeringUnits().
getDeviceMinEngineeringUnits()
double com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getDeviceMinEngineeringUnits ()
Gets the min engineering units.
Returns
the min engineering units
Definition at line 90 of file AbstractLink.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractLink.conf, com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getDeviceMaximumValue(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getDeviceMinimumValue(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getScale(), and com.neuronrobotics.sdk.addons.kinematics.AbstractLink.toEngineeringUnits().
getDeviceMinimumValue()
double com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getDeviceMinimumValue ()
Override this method to specify a larger range
Returns
the minimum value possible for a link
Definition at line 57 of file AbstractLink.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractLink.conf, and com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getDeviceTheoreticalMin().
Referenced by com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getDeviceMaxEngineeringUnits(), and com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getDeviceMinEngineeringUnits().
getGlobalPositionListener()
Object com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getGlobalPositionListener ()
Definition at line 673 of file AbstractLink.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractLink.linksLocation.
Referenced by com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.updateLimb().
getHome()
double com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getHome ()
Gets the home.
Returns
the home
Definition at line 585 of file AbstractLink.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractLink.conf, and com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getStaticOffset().
Referenced by com.neuronrobotics.sdk.addons.kinematics.AbstractLink.Home(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setCurrentEngineeringUnits(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.toEngineeringUnits(), and com.neuronrobotics.sdk.addons.kinematics.AbstractLink.toLinkUnits().
getImu()
IMU com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getImu ()
Definition at line 683 of file AbstractLink.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractLink.imu.
Referenced by com.neuronrobotics.bowlerstudio.physics.MobileBasePhysicsManager.MobileBasePhysicsManager().
getLinkConfiguration()
LinkConfiguration com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getLinkConfiguration ()
Gets the link configuration.
Returns
the link configuration
Definition at line 635 of file AbstractLink.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractLink.conf.
Referenced by com.neuronrobotics.sdk.addons.kinematics.LinkFactory.addLink(), com.neuronrobotics.sdk.addons.kinematics.LinkFactory.getLink(), and com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.onLinkLimit().
getLinks()
ArrayList<ILinkListener> com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getLinks ()
Gets the links.
Returns
the links
Definition at line 644 of file AbstractLink.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractLink.links.
Referenced by com.neuronrobotics.sdk.addons.kinematics.AbstractLink.addLinkListener(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.fireLinkLimitEvent(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.fireLinkListener(), com.neuronrobotics.sdk.addons.kinematics.LinkFactory.refreshHardwareLayer(), and com.neuronrobotics.sdk.addons.kinematics.AbstractLink.removeLinkListener().
getLowerLimit()
double com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getLowerLimit ()
Gets the lower limit.
Returns
the lower limit
Definition at line 576 of file AbstractLink.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractLink.conf, and com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getLowerLimit().
Referenced by com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getMaxEngineeringUnits(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getMinEngineeringUnits(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.isMinEngineeringUnits(), com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.printError(), and com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setTargetValue().
getMaxEngineeringUnits()
double com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getMaxEngineeringUnits ()
Gets the max engineering units.
Returns
the max engineering units
Definition at line 332 of file AbstractLink.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractLink.conf, com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getLowerLimit(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getScale(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getUpperLimit(), and com.neuronrobotics.sdk.addons.kinematics.AbstractLink.toEngineeringUnits().
Referenced by com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.boundToLinkLimits(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.checkVector(), com.neuronrobotics.sdk.addons.kinematics.AbstractRotoryLink.getMaxAngle(), com.neuronrobotics.sdk.addons.kinematics.AbstractPrismaticLink.getMaxDisplacment(), com.neuronrobotics.bowlerstudio.physics.MobileBasePhysicsManager.MobileBasePhysicsManager(), and com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setTargetValue().
getMaxVelocityEngineeringUnits()
double com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getMaxVelocityEngineeringUnits ()
Gets the max engineering units.
Returns
the max engineering units
Definition at line 381 of file AbstractLink.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractLink.conf, com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getUpperVelocity(), and com.neuronrobotics.sdk.addons.kinematics.AbstractLink.toEngineeringUnits().
Referenced by com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.checkVector(), and com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getBestTime().
getMinEngineeringUnits()
double com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getMinEngineeringUnits ()
Gets the min engineering units.
Returns
the min engineering units
Definition at line 344 of file AbstractLink.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractLink.conf, com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getLowerLimit(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getScale(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getUpperLimit(), and com.neuronrobotics.sdk.addons.kinematics.AbstractLink.toEngineeringUnits().
Referenced by com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.boundToLinkLimits(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.checkVector(), com.neuronrobotics.sdk.addons.kinematics.AbstractRotoryLink.getMinAngle(), com.neuronrobotics.sdk.addons.kinematics.AbstractPrismaticLink.getMinDisplacment(), com.neuronrobotics.bowlerstudio.physics.MobileBasePhysicsManager.MobileBasePhysicsManager(), and com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setTargetValue().
getScale()
double com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getScale ()
Gets the scale.
Returns
the scale
Definition at line 558 of file AbstractLink.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractLink.conf, and com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getScale().
Referenced by com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setTargetValue(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.toEngineeringUnits(), and com.neuronrobotics.sdk.addons.kinematics.AbstractLink.toLinkUnits().
getSlaveFactory()
LinkFactory com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getSlaveFactory ()
Definition at line 676 of file AbstractLink.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractLink.slaveFactory.
Referenced by com.neuronrobotics.sdk.addons.kinematics.AbstractLink.AbstractLink(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.cacheTargetValue(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.flush(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.flushAll(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setPosition(), and com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setTargetValue().
getTargetEngineeringUnits()
double com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getTargetEngineeringUnits ()
Gets the target engineering units.
Returns
the target engineering units
Definition at line 323 of file AbstractLink.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getTargetValue(), and com.neuronrobotics.sdk.addons.kinematics.AbstractLink.toEngineeringUnits().
Referenced by com.neuronrobotics.sdk.addons.kinematics.AbstractRotoryLink.getTargetAngle(), and com.neuronrobotics.sdk.addons.kinematics.AbstractPrismaticLink.getTargetDisplacment().
getTargetValue()
double com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getTargetValue ()
Gets the target value.
Returns
the target value
Definition at line 513 of file AbstractLink.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractLink.targetValue.
Referenced by com.neuronrobotics.sdk.addons.kinematics.MockRotoryLink.cacheTargetValueDevice(), com.neuronrobotics.sdk.addons.kinematics.PidPrismaticLink.cacheTargetValueDevice(), com.neuronrobotics.sdk.addons.kinematics.PidRotoryLink.cacheTargetValueDevice(), com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.flush(), com.neuronrobotics.sdk.addons.kinematics.MockRotoryLink.flushAllDevice(), com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GCodeHeater.flushDevice(), com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodePrismatic.flushDevice(), com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeRotory.flushDevice(), com.neuronrobotics.sdk.addons.kinematics.MockRotoryLink.flushDevice(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getTargetEngineeringUnits(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.isMaxEngineeringUnits(), and com.neuronrobotics.sdk.addons.kinematics.AbstractLink.isMinEngineeringUnits().
getUpperLimit()
double com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getUpperLimit ()
Gets the upper limit.
Returns
the upper limit
Definition at line 567 of file AbstractLink.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractLink.conf, and com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getUpperLimit().
Referenced by com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getMaxEngineeringUnits(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getMinEngineeringUnits(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.isMaxEngineeringUnits(), com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.printError(), and com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setTargetValue().
Home()
void com.neuronrobotics.sdk.addons.kinematics.AbstractLink.Home ()
Home.
Definition at line 261 of file AbstractLink.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractLink.cacheTargetValue(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getHome(), and com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setTargetValue().
incrementEngineeringUnits()
void com.neuronrobotics.sdk.addons.kinematics.AbstractLink.incrementEngineeringUnits (double inc)
Increment engineering units.
Parameters
inc the inc
Definition at line 271 of file AbstractLink.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setTargetEngineeringUnits(), and com.neuronrobotics.sdk.addons.kinematics.AbstractLink.targetEngineeringUnits.
Referenced by com.neuronrobotics.sdk.addons.kinematics.AbstractRotoryLink.incrementAngle(), and com.neuronrobotics.sdk.addons.kinematics.AbstractPrismaticLink.incrementDisplacment().
isMaxEngineeringUnits()
boolean com.neuronrobotics.sdk.addons.kinematics.AbstractLink.isMaxEngineeringUnits ()
Checks if is max engineering units.
Returns
true, if is max engineering units
Definition at line 398 of file AbstractLink.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getTargetValue(), and com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getUpperLimit().
Referenced by com.neuronrobotics.sdk.addons.kinematics.AbstractRotoryLink.isMaxAngle(), and com.neuronrobotics.sdk.addons.kinematics.AbstractPrismaticLink.isMaxDisplacment().
isMinEngineeringUnits()
boolean com.neuronrobotics.sdk.addons.kinematics.AbstractLink.isMinEngineeringUnits ()
Checks if is min engineering units.
Returns
true, if is min engineering units
Definition at line 410 of file AbstractLink.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getLowerLimit(), and com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getTargetValue().
Referenced by com.neuronrobotics.sdk.addons.kinematics.AbstractRotoryLink.isMinAngle(), and com.neuronrobotics.sdk.addons.kinematics.AbstractPrismaticLink.isMinDisplacment().
isUseLimits()
boolean com.neuronrobotics.sdk.addons.kinematics.AbstractLink.isUseLimits ()
Checks if is use limits.
Returns
true, if is use limits
Definition at line 617 of file AbstractLink.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractLink.useLimits.
Referenced by com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setTargetValue().
removeAllLinkListener()
void com.neuronrobotics.sdk.addons.kinematics.AbstractLink.removeAllLinkListener ()
Removes the all link listener.
Definition at line 660 of file AbstractLink.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractLink.links.
Referenced by com.neuronrobotics.sdk.addons.kinematics.LinkFactory.refreshHardwareLayer().
removeChangeListener()
void com.neuronrobotics.sdk.addons.kinematics.AbstractLink.removeChangeListener (ILinkConfigurationChangeListener l)
Definition at line 689 of file AbstractLink.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractLink.conf, and com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.removeChangeListener().
removeLinkListener()
void com.neuronrobotics.sdk.addons.kinematics.AbstractLink.removeLinkListener (ILinkListener l)
Removes the link listener.
Parameters
l the l
Definition at line 221 of file AbstractLink.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getLinks().
setCurrentAsLowerLimit()
void com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setCurrentAsLowerLimit ()
Sets the current as lower limit.
Definition at line 599 of file AbstractLink.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractLink.conf, com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getCurrentPosition(), and com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setLowerLimit().
setCurrentAsUpperLimit()
void com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setCurrentAsUpperLimit ()
Sets the current as upper limit.
Definition at line 592 of file AbstractLink.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractLink.conf, com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getCurrentPosition(), and com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setUpperLimit().
setCurrentEngineeringUnits()
void com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setCurrentEngineeringUnits (double angle)
Sets the current engineering units.
Parameters
angle the new current engineering units
Definition at line 298 of file AbstractLink.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractLink.conf, com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getCurrentPosition(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getHome(), and com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setScale().
Referenced by com.neuronrobotics.sdk.addons.kinematics.AbstractRotoryLink.setCurrentAsAngle(), and com.neuronrobotics.sdk.addons.kinematics.AbstractPrismaticLink.setCurrentAsDisplacment().
setDeviceMaximumValue()
void com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setDeviceMaximumValue (double max)
Override this method to specify a larger range
Definition at line 63 of file AbstractLink.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractLink.conf, and com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setDeviceTheoreticalMax().
setDeviceMinimumValue()
void com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setDeviceMinimumValue (double min)
Override this method to specify a larger range
Definition at line 70 of file AbstractLink.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractLink.conf, and com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setDeviceTheoreticalMin().
setGlobalPositionListener()
void com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setGlobalPositionListener (Object Object)
Definition at line 664 of file AbstractLink.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.addNewLink(), and com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.updateLimb().
setHome()
void com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setHome (int home)
Sets the home.
Parameters
home the new home
Definition at line 540 of file AbstractLink.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractLink.conf, and com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setStaticOffset().
Referenced by com.neuronrobotics.sdk.addons.kinematics.MockRotoryLink.MockRotoryLink().
setLinkConfiguration()
void com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setLinkConfiguration (LinkConfiguration conf)
Sets the link configuration.
Parameters
conf the new link configuration
Definition at line 626 of file AbstractLink.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractLink.conf.
Referenced by com.neuronrobotics.sdk.addons.kinematics.LinkFactory.getLinkLocal().
setLinks()
void com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setLinks (ArrayList< ILinkListener > links)
Sets the links.
Parameters
links the new links
Definition at line 653 of file AbstractLink.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractLink.links.
setLowerLimit()
void com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setLowerLimit (int lowerLimit)
Sets the lower limit.
Parameters
lowerLimit the new lower limit
Definition at line 531 of file AbstractLink.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractLink.conf, and com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setLowerLimit().
Referenced by com.neuronrobotics.sdk.addons.kinematics.MockRotoryLink.MockRotoryLink().
setMaxEngineeringUnits()
void com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setMaxEngineeringUnits (double maxLimit)
Sets the lower limit.
Parameters
lowerLimit the new lower limit
Definition at line 368 of file AbstractLink.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractLink.conf, com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getScale(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setLowerLimit(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setUpperLimit(), and com.neuronrobotics.sdk.addons.kinematics.AbstractLink.toLinkUnits().
setMaxVelocityEngineeringUnits()
void com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setMaxVelocityEngineeringUnits (double max)
Gets the max engineering units.
Returns
the max engineering units
Definition at line 389 of file AbstractLink.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractLink.conf, com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setUpperVelocity(), and com.neuronrobotics.sdk.addons.kinematics.AbstractLink.toLinkUnits().
setMinEngineeringUnits()
void com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setMinEngineeringUnits (double minLimit)
Sets the upper limit.
Parameters
upperLimit the new upper limit
Definition at line 356 of file AbstractLink.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractLink.conf, com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getScale(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setLowerLimit(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setUpperLimit(), and com.neuronrobotics.sdk.addons.kinematics.AbstractLink.toLinkUnits().
setPosition()
void com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setPosition (double val) protected
Sets the position.
Parameters
val the new position
Definition at line 422 of file AbstractLink.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractLink.cacheTargetValue(), com.neuronrobotics.sdk.addons.kinematics.LinkFactory.getLink(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getSlaveFactory(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setTargetValue(), and com.neuronrobotics.sdk.addons.kinematics.AbstractLink.slaveLinks.
Referenced by com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setTargetEngineeringUnits().
setScale()
void com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setScale (double d)
Sets the scale.
Parameters
d the new scale
Definition at line 549 of file AbstractLink.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractLink.conf, and com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setScale().
Referenced by com.neuronrobotics.sdk.addons.kinematics.MockRotoryLink.MockRotoryLink().
setSlaveFactory()
void com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setSlaveFactory (LinkFactory slaveFactory)
Definition at line 679 of file AbstractLink.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractLink.slaveFactory.
setTargetEngineeringUnits()
void com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setTargetEngineeringUnits (double pos)
Sets the target engineering units.
Parameters
pos the new target engineering units
Definition at line 280 of file AbstractLink.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setPosition(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.targetEngineeringUnits, and com.neuronrobotics.sdk.addons.kinematics.AbstractLink.toLinkUnits().
Referenced by com.neuronrobotics.sdk.addons.kinematics.AbstractLink.incrementEngineeringUnits(), com.neuronrobotics.sdk.addons.kinematics.AbstractRotoryLink.setTargetAngle(), and com.neuronrobotics.sdk.addons.kinematics.AbstractPrismaticLink.setTargetDisplacment().
setTargetValue()
void com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setTargetValue (double val) protected
Sets the target value.
Parameters
val the new target value
Definition at line 441 of file AbstractLink.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractLink.cacheTargetValue(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.conf, com.neuronrobotics.sdk.addons.kinematics.AbstractLink.fireLinkLimitEvent(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getHardwareIndex(), com.neuronrobotics.sdk.addons.kinematics.LinkFactory.getLink(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getLowerLimit(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getMaxEngineeringUnits(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getMinEngineeringUnits(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getScale(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getSlaveFactory(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getUpperLimit(), com.neuronrobotics.sdk.common.Log.info(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.isUseLimits(), com.neuronrobotics.sdk.pid.PIDLimitEventType.LOWERLIMIT, com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setTargetValue(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.slaveLinks, com.neuronrobotics.sdk.addons.kinematics.AbstractLink.targetValue, com.neuronrobotics.sdk.addons.kinematics.AbstractLink.toEngineeringUnits(), and com.neuronrobotics.sdk.pid.PIDLimitEventType.UPPERLIMIT.
Referenced by com.neuronrobotics.sdk.addons.kinematics.AbstractLink.Home(), com.neuronrobotics.sdk.addons.kinematics.MockRotoryLink.MockRotoryLink(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setPosition(), and com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setTargetValue().
setUpperLimit()
void com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setUpperLimit (int upperLimit)
Sets the upper limit.
Parameters
upperLimit the new upper limit
Definition at line 522 of file AbstractLink.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractLink.conf, and com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setUpperLimit().
Referenced by com.neuronrobotics.sdk.addons.kinematics.MockRotoryLink.MockRotoryLink().
setUseLimits()
void com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setUseLimits (boolean useLimits)
Sets the use limits.
Parameters
useLimits the new use limits
Definition at line 608 of file AbstractLink.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractLink.useLimits.
Referenced by com.neuronrobotics.sdk.addons.kinematics.LinkFactory.getLinkLocal(), and com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.throwExceptionOnJointLimit().
toEngineeringUnits()
double com.neuronrobotics.sdk.addons.kinematics.AbstractLink.toEngineeringUnits (double value)
To engineering units.
Parameters
value the value
Returns
the double
Definition at line 190 of file AbstractLink.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getHome(), and com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getScale().
Referenced by com.neuronrobotics.sdk.addons.kinematics.AbstractLink.fireLinkListener(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getCurrentEngineeringUnits(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getDeviceMaxEngineeringUnits(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getDeviceMinEngineeringUnits(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getMaxEngineeringUnits(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getMaxVelocityEngineeringUnits(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getMinEngineeringUnits(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getTargetEngineeringUnits(), and com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setTargetValue().
toLinkUnits()
double com.neuronrobotics.sdk.addons.kinematics.AbstractLink.toLinkUnits (double euValue)
To link units.
Parameters
euValue the eu value
Returns
the int
Definition at line 200 of file AbstractLink.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getHome(), and com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getScale().
Referenced by com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.printError(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setMaxEngineeringUnits(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setMaxVelocityEngineeringUnits(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setMinEngineeringUnits(), and com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setTargetEngineeringUnits().
Member Data Documentation
conf
LinkConfiguration com.neuronrobotics.sdk.addons.kinematics.AbstractLink.conf =null private
The conf.
Definition at line 34 of file AbstractLink.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.AbstractLink.AbstractLink(), com.neuronrobotics.sdk.addons.kinematics.AbstractPrismaticLink.AbstractPrismaticLink(), com.neuronrobotics.sdk.addons.kinematics.AbstractRotoryLink.AbstractRotoryLink(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.addChangeListener(), com.neuronrobotics.sdk.addons.kinematics.AnalogPrismaticLink.AnalogPrismaticLink(), com.neuronrobotics.sdk.addons.kinematics.AnalogRotoryLink.AnalogRotoryLink(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.clearChangeListener(), com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GCodeHeater.GCodeHeater(), com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodePrismatic.GcodePrismatic(), com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeRotory.GcodeRotory(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getDeviceMaxEngineeringUnits(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getDeviceMaximumValue(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getDeviceMinEngineeringUnits(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getDeviceMinimumValue(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getHome(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getLinkConfiguration(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getLowerLimit(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getMaxEngineeringUnits(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getMaxVelocityEngineeringUnits(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getMinEngineeringUnits(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getScale(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getUpperLimit(), com.neuronrobotics.sdk.addons.kinematics.MockRotoryLink.MockRotoryLink(), com.neuronrobotics.sdk.addons.kinematics.PidPrismaticLink.PidPrismaticLink(), com.neuronrobotics.sdk.addons.kinematics.PidRotoryLink.PidRotoryLink(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.removeChangeListener(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setCurrentAsLowerLimit(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setCurrentAsUpperLimit(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setCurrentEngineeringUnits(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setDeviceMaximumValue(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setDeviceMinimumValue(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setHome(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setLinkConfiguration(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setLowerLimit(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setMaxEngineeringUnits(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setMaxVelocityEngineeringUnits(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setMinEngineeringUnits(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setScale(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setTargetValue(), and com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setUpperLimit().
imu
IMU com.neuronrobotics.sdk.addons.kinematics.AbstractLink.imu = new IMU() private
The object for communicating IMU information and registering it with the hardware
Definition at line 45 of file AbstractLink.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getImu().
links
ArrayList<ILinkListener> com.neuronrobotics.sdk.addons.kinematics.AbstractLink.links = new ArrayList<ILinkListener>() private
The links.
Definition at line 31 of file AbstractLink.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getLinks(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.removeAllLinkListener(), and com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setLinks().
linksLocation
Object com.neuronrobotics.sdk.addons.kinematics.AbstractLink.linksLocation =null private
Definition at line 40 of file AbstractLink.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getGlobalPositionListener().
slaveFactory
LinkFactory com.neuronrobotics.sdk.addons.kinematics.AbstractLink.slaveFactory = new LinkFactory() private
Definition at line 36 of file AbstractLink.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getSlaveFactory(), and com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setSlaveFactory().
slaveLinks
ArrayList<LinkConfiguration> com.neuronrobotics.sdk.addons.kinematics.AbstractLink.slaveLinks private
Definition at line 35 of file AbstractLink.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.AbstractLink.AbstractLink(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.cacheTargetValue(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.flush(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.flushAll(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setPosition(), and com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setTargetValue().
targetEngineeringUnits
double com.neuronrobotics.sdk.addons.kinematics.AbstractLink.targetEngineeringUnits =0 private
The target engineering units.
Definition at line 28 of file AbstractLink.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.AbstractLink.incrementEngineeringUnits(), and com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setTargetEngineeringUnits().
targetValue
double com.neuronrobotics.sdk.addons.kinematics.AbstractLink.targetValue =0 private
The target value.
Definition at line 25 of file AbstractLink.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getTargetValue(), and com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setTargetValue().
useLimits
boolean com.neuronrobotics.sdk.addons.kinematics.AbstractLink.useLimits =true private
The use limits.
Definition at line 38 of file AbstractLink.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.AbstractLink.isUseLimits(), and com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setUseLimits().
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/addons/kinematics/AbstractLink.java