BowlerKernel: com.neuronrobotics.sdk.dyio.DyIOPowerEvent Class Reference
com.neuronrobotics.sdk.dyio.DyIOPowerEvent Class Reference
Public Member Functions
DyIOPowerEvent (DyIOPowerState bankA, DyIOPowerState bankB, double batteryVoltage)
DyIOPowerState getChannelAMode ()
DyIOPowerState getChannelBMode ()
double getVoltage ()
String toString ()
Private Member Functions
void setVoltage (double voltage)
Private Attributes
DyIOPowerState bankAState
DyIOPowerState bankBState
double voltage
Detailed Description
The Class DyIOPowerEvent.
Definition at line 7 of file DyIOPowerEvent.java.
Constructor & Destructor Documentation
DyIOPowerEvent()
com.neuronrobotics.sdk.dyio.DyIOPowerEvent.DyIOPowerEvent (DyIOPowerState bankA, DyIOPowerState bankB, double batteryVoltage)
Instantiates a new dy io power event.
Parameters
bankA the bank a
bankB the bank b
batteryVoltage the battery voltage
Definition at line 25 of file DyIOPowerEvent.java.
References com.neuronrobotics.sdk.dyio.DyIOPowerEvent.bankAState, com.neuronrobotics.sdk.dyio.DyIOPowerEvent.bankBState, and com.neuronrobotics.sdk.dyio.DyIOPowerEvent.setVoltage().
Member Function Documentation
getChannelAMode()
DyIOPowerState com.neuronrobotics.sdk.dyio.DyIOPowerEvent.getChannelAMode ()
Gets the channel a mode.
Returns
the channel a mode
Definition at line 36 of file DyIOPowerEvent.java.
References com.neuronrobotics.sdk.dyio.DyIOPowerEvent.bankAState.
getChannelBMode()
DyIOPowerState com.neuronrobotics.sdk.dyio.DyIOPowerEvent.getChannelBMode ()
Gets the channel b mode.
Returns
the channel b mode
Definition at line 45 of file DyIOPowerEvent.java.
References com.neuronrobotics.sdk.dyio.DyIOPowerEvent.bankBState.
getVoltage()
double com.neuronrobotics.sdk.dyio.DyIOPowerEvent.getVoltage ()
Gets the voltage.
Returns
the voltage
Definition at line 63 of file DyIOPowerEvent.java.
References com.neuronrobotics.sdk.dyio.DyIOPowerEvent.voltage.
Referenced by com.neuronrobotics.sdk.dyio.DyIOPowerEvent.toString().
setVoltage()
void com.neuronrobotics.sdk.dyio.DyIOPowerEvent.setVoltage (double voltage) private
Sets the voltage.
Parameters
voltage the new voltage
Definition at line 54 of file DyIOPowerEvent.java.
References com.neuronrobotics.sdk.dyio.DyIOPowerEvent.voltage.
Referenced by com.neuronrobotics.sdk.dyio.DyIOPowerEvent.DyIOPowerEvent().
toString()
String com.neuronrobotics.sdk.dyio.DyIOPowerEvent.toString ()
Definition at line 71 of file DyIOPowerEvent.java.
References com.neuronrobotics.sdk.dyio.DyIOPowerEvent.bankAState, com.neuronrobotics.sdk.dyio.DyIOPowerEvent.bankBState, and com.neuronrobotics.sdk.dyio.DyIOPowerEvent.getVoltage().
Member Data Documentation
bankAState
DyIOPowerState com.neuronrobotics.sdk.dyio.DyIOPowerEvent.bankAState private
The bank a state.
Definition at line 10 of file DyIOPowerEvent.java.
Referenced by com.neuronrobotics.sdk.dyio.DyIOPowerEvent.DyIOPowerEvent(), com.neuronrobotics.sdk.dyio.DyIOPowerEvent.getChannelAMode(), and com.neuronrobotics.sdk.dyio.DyIOPowerEvent.toString().
bankBState
DyIOPowerState com.neuronrobotics.sdk.dyio.DyIOPowerEvent.bankBState private
The bank b state.
Definition at line 13 of file DyIOPowerEvent.java.
Referenced by com.neuronrobotics.sdk.dyio.DyIOPowerEvent.DyIOPowerEvent(), com.neuronrobotics.sdk.dyio.DyIOPowerEvent.getChannelBMode(), and com.neuronrobotics.sdk.dyio.DyIOPowerEvent.toString().
voltage
double com.neuronrobotics.sdk.dyio.DyIOPowerEvent.voltage private
The voltage.
Definition at line 16 of file DyIOPowerEvent.java.
Referenced by com.neuronrobotics.sdk.dyio.DyIOPowerEvent.getVoltage(), and com.neuronrobotics.sdk.dyio.DyIOPowerEvent.setVoltage().
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/dyio/DyIOPowerEvent.java