BowlerKernel: eu.mihosoft.vrl.v3d.parametrics.StringParameter Class Reference
eu.mihosoft.vrl.v3d.parametrics.StringParameter Class Reference
Public Member Functions
StringParameter (String key, String defaultValue, ArrayList< String > options)
void setString (String s)
String getString ()
List< String > getStringOptions ()
Public Member Functions inherited from eu.mihosoft.vrl.v3d.parametrics.Parameter
Parameter ()
String getName ()
void setValue (Long newVal)
Long getValue ()
ArrayList< String > getOptions ()
String getStrValue ()
void setStrValue (String newValue)
void setMM (double newVal)
void setMicrons (long newVal)
double getMM ()
double getMicrons ()
Private Attributes
List< String > options2
Additional Inherited Members
Protected Member Functions inherited from eu.mihosoft.vrl.v3d.parametrics.Parameter
void setup (String key, Long defaultValue, ArrayList< String > options)
void setup (String key, String defaultValue, ArrayList< String > options)
Detailed Description
Definition at line 6 of file StringParameter.java.
Constructor & Destructor Documentation
StringParameter()
eu.mihosoft.vrl.v3d.parametrics.StringParameter.StringParameter (String key, String defaultValue, ArrayList< String > options)
Definition at line 9 of file StringParameter.java.
References eu.mihosoft.vrl.v3d.parametrics.Parameter.options, eu.mihosoft.vrl.v3d.parametrics.StringParameter.options2, and eu.mihosoft.vrl.v3d.parametrics.Parameter.setup().
Member Function Documentation
getString()
String eu.mihosoft.vrl.v3d.parametrics.StringParameter.getString ()
Definition at line 16 of file StringParameter.java.
References eu.mihosoft.vrl.v3d.parametrics.Parameter.getStrValue().
getStringOptions()
List<String> eu.mihosoft.vrl.v3d.parametrics.StringParameter.getStringOptions ()
Definition at line 19 of file StringParameter.java.
References eu.mihosoft.vrl.v3d.parametrics.StringParameter.options2.
setString()
void eu.mihosoft.vrl.v3d.parametrics.StringParameter.setString (String s)
Definition at line 13 of file StringParameter.java.
References eu.mihosoft.vrl.v3d.parametrics.Parameter.setStrValue().
Member Data Documentation
options2
List<String> eu.mihosoft.vrl.v3d.parametrics.StringParameter.options2 private
Definition at line 8 of file StringParameter.java.
Referenced by eu.mihosoft.vrl.v3d.parametrics.StringParameter.getStringOptions(), and eu.mihosoft.vrl.v3d.parametrics.StringParameter.StringParameter().
The documentation for this class was generated from the following file:
JCSG/src/main/java/eu/mihosoft/vrl/v3d/parametrics/StringParameter.java