BowlerKernel: com.neuronrobotics.sdk.addons.kinematics.MobileBase Class Reference
com.neuronrobotics.sdk.addons.kinematics.MobileBase Class Reference
Public Member Functions
MobileBase ()
TransformNR calcHome (DHParameterKinematics limb)
HashMap< DHParameterKinematics, TransformNR > getTipLocations ()
boolean pose (TransformNR newAbsolutePose) throws Exception
boolean poseAroundPoint (TransformNR newAbsolutePose, TransformNR around) throws Exception
boolean pose (TransformNR newAbsolutePose, TransformNR around, HashMap< DHParameterKinematics, TransformNR > tipList) throws Exception
MobileBase (InputStream configFile)
MobileBase (Element doc)
ParallelGroup getParallelGroup (String name)
Set< String > getParallelGroupNames ()
ArrayList< DHParameterKinematics > getAllParallelGroups ()
ParallelGroup getParallelGroup (DHParameterKinematics limb)
void addLimbToParallel (DHParameterKinematics limb, TransformNR tipOffset, String name, String relativeLimb, int relativeIndex)
void initializeParalellGroups ()
void disconnectDevice ()
boolean connectDevice ()
double[] inverseKinematics (TransformNR taskSpaceTransform) throws Exception
TransformNR forwardKinematics (double[] jointSpaceVector)
ArrayList< DHParameterKinematics > getLegs ()
ArrayList< DHParameterKinematics > getAppendages ()
ArrayList< DHParameterKinematics > getAllDHChains ()
HashMap< String, String[]> getVitamins ()
void setVitamin (String name, String type, String id)
void setVitaminVariant (String name, String tagValue2)
String getVitaminVariant (String name)
String getXml ()
String getEmbedableXml ()
ArrayList< DHParameterKinematics > getSteerable ()
ArrayList< DHParameterKinematics > getDrivable ()
void setWalkingDriveEngine (IDriveEngine walkingDriveEngine)
void DriveArc (TransformNR newPose, double seconds)
void DriveVelocityStraight (double cmPerSecond)
void DriveVelocityArc (double degreesPerSecond, double cmRadius)
void updatePositions ()
String[] getGitWalkingEngine ()
void setGitWalkingEngine (String[] walkingEngine)
String[] getGitSelfSource ()
void setGitSelfSource (String[] selfSource)
double getMassKg ()
void setMassKg (double mass)
TransformNR getCenterOfMassFromCentroid ()
void setCenterOfMassFromCentroid (TransformNR centerOfMassFromCentroid)
TransformNR getIMUFromCentroid ()
void setIMUFromCentroid (TransformNR centerOfMassFromCentroid)
void setFiducialToGlobalTransform (TransformNR globe)
void shutDownParallel (ParallelGroup group)
boolean connect ()
void setHomeProvider (ICalcLimbHomeProvider homeProvider)
void addIOnMobileBaseRenderChange (IOnMobileBaseRenderChange l)
void removeIOnMobileBaseRenderChange (IOnMobileBaseRenderChange l)
void clearIOnMobileBaseRenderChange ()
void event (LinkConfiguration newConf)
void onIOnMobileBaseRenderChange ()
void onJointSpaceUpdate (AbstractKinematicsNR source, double[] joints)
void onJointSpaceTargetUpdate (AbstractKinematicsNR source, double[] joints)
void onJointSpaceLimit (AbstractKinematicsNR source, int axis, JointLimit event)
void sync ()
Public Member Functions inherited from com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR
Object getRootListener ()
void setRootListener (Object listener)
ArrayList< String > getNamespacesImp ()
void disconnectDeviceImp ()
boolean connectDeviceImp ()
AbstractKinematicsNR ()
AbstractKinematicsNR (InputStream configFile, LinkFactory f)
AbstractKinematicsNR (Element doc, LinkFactory f)
LinkConfiguration getLinkConfiguration (int linkIndex)
ArrayList< LinkConfiguration > getLinkConfigurations ()
PIDConfiguration getLinkCurrentConfiguration (int chan)
void setLinkCurrentConfiguration (int chan, PIDConfiguration c)
AbstractLink getAbstractLink (int index)
int getNumberOfLinks ()
TransformNR getCurrentTaskSpaceTransform ()
double readLinkValue (int index)
double readLinkTarget (int index)
double[] getCurrentJointSpaceVector ()
double[] getCurrentJointSpaceTarget ()
double getCurrentLinkEngineeringUnits (int linkIndex)
double[] setDesiredTaskSpaceTransform (TransformNR taskSpaceTransform, double seconds) throws Exception
boolean checkTaskSpaceTransform (TransformNR taskSpaceTransform, double seconds)
boolean checkTaskSpaceTransform (TransformNR taskSpaceTransform)
double getBestTime (TransformNR currentTaskSpaceTransform)
double getBestTime (double[] jointSpaceVect)
double[] setDesiredJointSpaceVector (double[] jointSpaceVect, double seconds) throws Exception
TransformNR calcForward (double[] jointSpaceVect)
TransformNR calcHome ()
void setDesiredJointAxisValue (int axis, double value, double seconds) throws Exception
void firePoseUpdate ()
TransformNR getFiducialToGlobalTransform ()
void setRobotToFiducialTransform (TransformNR baseToFiducial)
TransformNR getRobotToFiducialTransform ()
void setGlobalToFiducialTransform (TransformNR frameToBase, boolean fireUpdate)
void setGlobalToFiducialTransform (TransformNR frameToBase)
TransformNR inverseOffset (TransformNR t)
TransformNR forwardOffset (TransformNR t)
void addJointSpaceListener (IJointSpaceUpdateListenerNR l)
void removeJointSpaceUpdateListener (IJointSpaceUpdateListenerNR l)
void addRegistrationListener (IRegistrationListenerNR l)
void removeRegestrationUpdateListener (IRegistrationListenerNR l)
void addPoseUpdateListener (ITaskSpaceUpdateListenerNR l)
void removePoseUpdateListener (ITaskSpaceUpdateListenerNR l)
void onLinkPositionUpdate (AbstractLink source, double engineeringUnitsValue)
void onPIDEvent (PIDEvent e)
void onPIDLimitEvent (PIDLimitEvent e)
void onPIDReset (int group, float currentValue)
void homeAllLinks ()
void homeLink (int link)
void emergencyStop ()
ArrayList< PIDConfiguration > getAxisPidConfiguration ()
TransformNR getCurrentPoseTarget ()
void setCurrentPoseTarget (TransformNR currentPoseTarget)
void setFactory (LinkFactory factory)
LinkFactory getFactory ()
void setNoFlush (boolean noFlush)
boolean isNoFlush ()
int getRetryNumberBeforeFail ()
void setRetryNumberBeforeFail (int retryNumberBeforeFail)
void onLinkLimit (AbstractLink arg0, PIDLimitEvent arg1)
DHChain getDhParametersChain ()
void setDhParametersChain (DHChain dhParametersChain)
String[] getGitDhEngine ()
void setGitDhEngine (String[] dhEngine)
String[] getGitCadEngine ()
void setGitCadEngine (String[] cadEngine)
IMU getImu ()
void boundedLinkValueSet (int index, double value) throws Exception
double boundToLinkLimits (int index, double value)
double linkMass (int linkIndex)
double getMaxEngineeringUnits (int linkIndex)
double getMinEngineeringUnits (int linkIndex)
void setMaxEngineeringUnits (int linkIndex, double maxLimit)
void setMinEngineeringUnits (int linkIndex, double minLimit)
String getElectroMechanicalType (int linkIndex)
void setElectroMechanicalType (int linkIndex, String electroMechanicalType)
String getElectroMechanicalSize (int linkIndex)
void setElectroMechanicalSize (int linkIndex, String electroMechanicalSize)
String getShaftType (int linkIndex)
void setShaftType (int linkIndex, String shaftType)
String getShaftSize (int linkIndex)
void setDeviceMaximumValue (int linkIndex, double max)
void setDeviceMinimumValue (int linkIndex, double min)
double getDeviceMaximumValue (int linkIndex)
double getDeviceMinimumValue (int linkIndex)
void addChangeListener (int linkIndex, ILinkConfigurationChangeListener l)
void removeChangeListener (int linkIndex, ILinkConfigurationChangeListener l)
void clearChangeListener (int linkIndex)
void runRenderWrangler ()
void setRenderWrangler (Runnable renderWrangler)
TransformNR getDeltaToTarget (TransformNR target)
TransformNR getTipAlongTrajectory (TransformNR startingPoint, TransformNR deltaToTarget, double unitIncrement)
void asyncInterpolatedMove (TransformNR target, double seconds, InterpolationType type, IOnInterpolationDone listener, double ...conf)
InterpolationMoveState blockingInterpolatedMove (TransformNR target, double seconds, InterpolationType type, double ...conf)
Public Member Functions inherited from com.neuronrobotics.sdk.common.NonBowlerDevice
boolean isAvailable () throws InvalidConnectionException
void disconnect ()
void onAsyncResponse (BowlerDatagram data)
ArrayList< String > getNamespaces ()
Public Member Functions inherited from com.neuronrobotics.sdk.common.BowlerAbstractDevice
void addConnectionEventListener (final IDeviceConnectionEventListener l)
void removeConnectionEventListener (IDeviceConnectionEventListener l)
void setConnection (BowlerAbstractConnection connection)
BowlerAbstractConnection getConnection ()
void setAddress (MACAddress address)
MACAddress getAddress ()
BowlerDatagram send (BowlerAbstractCommand command) throws NoConnectionAvailableException, InvalidResponseException
BowlerDatagram send (BowlerAbstractCommand command, int retry) throws NoConnectionAvailableException, InvalidResponseException
Object[] send (String namespace, BowlerMethod method, String rpcString, Object[] arguments, int retry) throws DeviceConnectionException
Object[] send (String namespace, BowlerMethod method, String rpcString, Object[] arguments) throws DeviceConnectionException
boolean ping ()
boolean ping (boolean switchParser)
ArrayList< ByteList > getRevisions ()
boolean hasNamespace (String string)
void startHeartBeat ()
void startHeartBeat (long msHeartBeatTime)
void stopHeartBeat ()
void setThreadedUpstreamPackets (boolean up)
ArrayList< RpcEncapsulation > getRpcList (String namespace)
void loadRpcList ()
void onAllResponse (BowlerDatagram data)
boolean isKeepAlive ()
void setKeepAlive (boolean keepAlive)
long getLastPacketTime ()
void setLastPacketTime (long lastPacketTime)
String getScriptingName ()
void setScriptingName (String scriptingName)
ArrayList< IDeviceConnectionEventListener > getDisconnectListeners ()
Public Member Functions inherited from com.neuronrobotics.sdk.addons.kinematics.IHardwareSyncPulseProvider
default void addIHardwareSyncPulseReciver (IHardwareSyncPulseReciver r)
default void removeIHardwareSyncPulseReciver (IHardwareSyncPulseReciver r)
default void doSync ()
default ArrayList< IHardwareSyncPulseReciver > getListeners ()
Static Public Member Functions
static void main (String[] args) throws Exception
Static Public Member Functions inherited from com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR
static boolean checkTaskSpaceTransform (AbstractKinematicsNR dev, TransformNR taskSpaceTransform, double seconds)
static boolean checkTaskSpaceTransform (AbstractKinematicsNR dev, TransformNR taskSpaceTransform)
Private Member Functions
void removeLimFromParallel (DHParameterKinematics limb)
void loadConfigs (Element doc)
TransformNR loadTransform (String tagname, Element e)
String getname (Element e)
String getParallelGroup (Element e)
String getTag (Element e, String tagname)
void loadLimb (Element doc, String tag, ArrayList< DHParameterKinematics > list)
void loadVitamins (Element doc)
void getVitamins (Element doc)
String makeLimbTag (String xml, DHParameterKinematics l)
IDriveEngine getWalkingDriveEngine ()
void fireBaseUpdates ()
HashMap< String, ParallelGroup > getParallelGroups ()
void addListeners (DHParameterKinematics kin)
void fireIOnMobileBaseRenderChange ()
Private Attributes
final ArrayList< DHParameterKinematics > legs = new ArrayList<DHParameterKinematics>()
final ArrayList< DHParameterKinematics > appendages = new ArrayList<DHParameterKinematics>()
final ArrayList< DHParameterKinematics > steerable = new ArrayList<DHParameterKinematics>()
final ArrayList< DHParameterKinematics > drivable = new ArrayList<DHParameterKinematics>()
final ArrayList< IOnMobileBaseRenderChange > changeListeners = new ArrayList<IOnMobileBaseRenderChange>()
IDriveEngine walkingDriveEngine = new WalkingDriveEngine()
String[] walkingEngine
HashMap< String, String[]> vitamins = new HashMap<String, String[]>()
HashMap< String, String > vitaminVariant = new HashMap<String, String>()
String[] selfSource = new String[2]
double mass = 0.5
TransformNR centerOfMassFromCentroid = new TransformNR()
TransformNR IMUFromCentroid = new TransformNR()
HashMap< String, ParallelGroup > parallelGroups = new HashMap<String, ParallelGroup>()
ICalcLimbHomeProvider homeProvider = null
Additional Inherited Members
Public Attributes inherited from com.neuronrobotics.sdk.addons.kinematics.IHardwareSyncPulseProvider
HashMap< IHardwareSyncPulseProvider, ArrayList< IHardwareSyncPulseReciver > > syncPulse =new HashMap<>()
Protected Member Functions inherited from com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR
ArrayList< LinkConfiguration > loadConfig (Element doc)
LinkFactory getDevice ()
void setDevice (LinkFactory f, ArrayList< LinkConfiguration > linkConfigs)
void firePoseTransform (TransformNR transform)
void fireTargetJointsUpdate (double[] jointSpaceVector, TransformNR fwd)
String getCode (Element e, String tag)
String[] getGitCodes (Element doc, String tag)
Protected Member Functions inherited from com.neuronrobotics.sdk.common.BowlerAbstractDevice
void fireDisconnectEvent ()
void fireConnectEvent ()
Protected Attributes inherited from com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR
ArrayList< IJointSpaceUpdateListenerNR > jointSpaceUpdateListeners = new ArrayList<IJointSpaceUpdateListenerNR>()
Detailed Description
The Class MobileBase.
Definition at line 28 of file MobileBase.java.
Constructor & Destructor Documentation
MobileBase() [1/3]
com.neuronrobotics.sdk.addons.kinematics.MobileBase.MobileBase ()
Instantiates a new mobile base.
Definition at line 70 of file MobileBase.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.MobileBase.main().
MobileBase() [2/3]
com.neuronrobotics.sdk.addons.kinematics.MobileBase.MobileBase (InputStream configFile)
Instantiates a new mobile base.
Parameters
configFile the config file
Definition at line 138 of file MobileBase.java.
References com.neuronrobotics.sdk.addons.kinematics.xml.XmlFactory.getAllNodesDocument(), and com.neuronrobotics.sdk.addons.kinematics.MobileBase.loadConfigs().
MobileBase() [3/3]
com.neuronrobotics.sdk.addons.kinematics.MobileBase.MobileBase (Element doc)
Instantiates a new mobile base.
Parameters
doc the doc
Definition at line 165 of file MobileBase.java.
References com.neuronrobotics.sdk.addons.kinematics.MobileBase.loadConfigs().
Member Function Documentation
addIOnMobileBaseRenderChange()
void com.neuronrobotics.sdk.addons.kinematics.MobileBase.addIOnMobileBaseRenderChange (IOnMobileBaseRenderChange l)
Definition at line 967 of file MobileBase.java.
References com.neuronrobotics.sdk.addons.kinematics.MobileBase.changeListeners.
Referenced by com.neuronrobotics.sdk.addons.kinematics.MobileBase.addListeners(), and com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.run().
addLimbToParallel()
void com.neuronrobotics.sdk.addons.kinematics.MobileBase.addLimbToParallel (DHParameterKinematics limb, TransformNR tipOffset, String name, String relativeLimb, int relativeIndex)
Definition at line 203 of file MobileBase.java.
References com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.addLimb(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.getParallelGroup(), and com.neuronrobotics.sdk.addons.kinematics.MobileBase.removeLimFromParallel().
addListeners()
void com.neuronrobotics.sdk.addons.kinematics.MobileBase.addListeners (DHParameterKinematics kin) private
Definition at line 908 of file MobileBase.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.addChangeListener(), com.neuronrobotics.sdk.addons.kinematics.IHardwareSyncPulseProvider.addIHardwareSyncPulseReciver(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.addIOnMobileBaseRenderChange(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.addJointSpaceListener(), com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getDhLink(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getFactory(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getNumberOfLinks(), and com.neuronrobotics.sdk.addons.kinematics.DHLink.getSlaveMobileBase().
Referenced by com.neuronrobotics.sdk.addons.kinematics.MobileBase.connect().
calcHome()
TransformNR com.neuronrobotics.sdk.addons.kinematics.MobileBase.calcHome (DHParameterKinematics limb)
Calc home.
Returns
the transform nr
Definition at line 78 of file MobileBase.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.calcHome(), com.neuronrobotics.sdk.addons.kinematics.ICalcLimbHomeProvider.calcHome(), and com.neuronrobotics.sdk.addons.kinematics.MobileBase.homeProvider.
clearIOnMobileBaseRenderChange()
void com.neuronrobotics.sdk.addons.kinematics.MobileBase.clearIOnMobileBaseRenderChange ()
Definition at line 978 of file MobileBase.java.
References com.neuronrobotics.sdk.addons.kinematics.MobileBase.changeListeners.
connect()
boolean com.neuronrobotics.sdk.addons.kinematics.MobileBase.connect ()
This method tells the connection object to start and connects the up and down streams pipes. Once this method is called and returns without exception, the device is ready to communicate with
Returns
true, if successful
Exceptions
InvalidConnectionException the invalid connection exception
Reimplemented from com.neuronrobotics.sdk.common.NonBowlerDevice.
Definition at line 880 of file MobileBase.java.
References com.neuronrobotics.sdk.addons.kinematics.MobileBase.addListeners(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.addRegistrationListener(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.connect(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.fireBaseUpdates(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.getAllDHChains(), and com.neuronrobotics.sdk.common.NonBowlerDevice.isAvailable().
Referenced by com.neuronrobotics.sdk.addons.kinematics.MobileBase.connect(), and com.neuronrobotics.bowlerstudio.BowlerKernel.processReturnedObjects().
connectDevice()
boolean com.neuronrobotics.sdk.addons.kinematics.MobileBase.connectDevice ()
Connect device.
Returns
true, if successful
Reimplemented from com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.
Definition at line 428 of file MobileBase.java.
References com.neuronrobotics.sdk.common.Log.error(), and com.neuronrobotics.sdk.addons.kinematics.MobileBase.getAllDHChains().
disconnectDevice()
void com.neuronrobotics.sdk.addons.kinematics.MobileBase.disconnectDevice ()
This method tells the connection object to disconnect its pipes and close out the connection. Once this is called, it is safe to remove your device.
Reimplemented from com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.
Definition at line 415 of file MobileBase.java.
References com.neuronrobotics.sdk.addons.kinematics.MobileBase.getAllDHChains().
DriveArc()
void com.neuronrobotics.sdk.addons.kinematics.MobileBase.DriveArc (TransformNR newPose, double seconds)
Drive arc.
Parameters
newPose the new pose
seconds the seconds
Definition at line 757 of file MobileBase.java.
References com.neuronrobotics.sdk.addons.kinematics.IDriveEngine.DriveArc(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.getWalkingDriveEngine(), and com.neuronrobotics.sdk.addons.kinematics.MobileBase.updatePositions().
DriveVelocityArc()
void com.neuronrobotics.sdk.addons.kinematics.MobileBase.DriveVelocityArc (double degreesPerSecond, double cmRadius)
Drive velocity arc.
Parameters
degreesPerSecond the degrees per second
cmRadius the cm radius
Definition at line 779 of file MobileBase.java.
References com.neuronrobotics.sdk.addons.kinematics.IDriveEngine.DriveVelocityArc(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.getWalkingDriveEngine(), and com.neuronrobotics.sdk.addons.kinematics.MobileBase.updatePositions().
DriveVelocityStraight()
void com.neuronrobotics.sdk.addons.kinematics.MobileBase.DriveVelocityStraight (double cmPerSecond)
Drive velocity straight.
Parameters
cmPerSecond the cm per second
Definition at line 767 of file MobileBase.java.
References com.neuronrobotics.sdk.addons.kinematics.IDriveEngine.DriveVelocityStraight(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.getWalkingDriveEngine(), and com.neuronrobotics.sdk.addons.kinematics.MobileBase.updatePositions().
event()
void com.neuronrobotics.sdk.addons.kinematics.MobileBase.event (LinkConfiguration newConf)
Implements com.neuronrobotics.sdk.addons.kinematics.ILinkConfigurationChangeListener.
Definition at line 984 of file MobileBase.java.
References com.neuronrobotics.sdk.addons.kinematics.MobileBase.fireIOnMobileBaseRenderChange().
fireBaseUpdates()
void com.neuronrobotics.sdk.addons.kinematics.MobileBase.fireBaseUpdates () private
Definition at line 863 of file MobileBase.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.forwardOffset(), and com.neuronrobotics.sdk.addons.kinematics.MobileBase.getAllDHChains().
Referenced by com.neuronrobotics.sdk.addons.kinematics.MobileBase.connect(), and com.neuronrobotics.sdk.addons.kinematics.MobileBase.loadConfigs().
fireIOnMobileBaseRenderChange()
void com.neuronrobotics.sdk.addons.kinematics.MobileBase.fireIOnMobileBaseRenderChange () private
Definition at line 956 of file MobileBase.java.
References com.neuronrobotics.sdk.addons.kinematics.MobileBase.changeListeners, and com.neuronrobotics.sdk.addons.kinematics.IOnMobileBaseRenderChange.onIOnMobileBaseRenderChange().
Referenced by com.neuronrobotics.sdk.addons.kinematics.MobileBase.event(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.onIOnMobileBaseRenderChange(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.onJointSpaceUpdate(), and com.neuronrobotics.sdk.addons.kinematics.MobileBase.updatePositions().
forwardKinematics()
TransformNR com.neuronrobotics.sdk.addons.kinematics.MobileBase.forwardKinematics (double[] jointSpaceVector)
Forward kinematics.
Parameters
jointSpaceVector the joint space vector
Returns
6x1 vector in task space, unit in mm,radians [x,y,z,rotx,rotY,rotZ]
Reimplemented from com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.
Definition at line 457 of file MobileBase.java.
getAllDHChains()
ArrayList<DHParameterKinematics> com.neuronrobotics.sdk.addons.kinematics.MobileBase.getAllDHChains ()
Gets the all dh chains.
Returns
the all dh chains
Definition at line 485 of file MobileBase.java.
References com.neuronrobotics.sdk.addons.kinematics.MobileBase.appendages, com.neuronrobotics.sdk.addons.kinematics.MobileBase.drivable, com.neuronrobotics.sdk.addons.kinematics.MobileBase.legs, and com.neuronrobotics.sdk.addons.kinematics.MobileBase.steerable.
Referenced by com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager._generateStls(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.connect(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.connectDevice(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.disconnectDevice(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.fireBaseUpdates(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.generateBody(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.generateCad(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.loadJointPose(), com.neuronrobotics.bowlerstudio.sequence.TimeSequence.loadMobileBase(), com.neuronrobotics.bowlerstudio.physics.MobileBasePhysicsManager.MobileBasePhysicsManager(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.run(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.set(), com.neuronrobotics.bowlerstudio.creature.MobileBaseLoader.setDefaultWalkingEngine(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.setMobileBase(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.updateBase(), and com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.updateMobileBase().
getAllParallelGroups()
ArrayList<DHParameterKinematics> com.neuronrobotics.sdk.addons.kinematics.MobileBase.getAllParallelGroups ()
Definition at line 184 of file MobileBase.java.
References com.neuronrobotics.sdk.addons.kinematics.MobileBase.getParallelGroup(), and com.neuronrobotics.sdk.addons.kinematics.MobileBase.getParallelGroupNames().
Referenced by com.neuronrobotics.bowlerstudio.sequence.TimeSequence.loadMobileBase().
getAppendages()
ArrayList<DHParameterKinematics> com.neuronrobotics.sdk.addons.kinematics.MobileBase.getAppendages ()
Gets the appendages.
Returns
the appendages
Definition at line 476 of file MobileBase.java.
References com.neuronrobotics.sdk.addons.kinematics.MobileBase.appendages.
Referenced by com.neuronrobotics.bowlerstudio.scripting.RobotHelper.getDefaultContents().
getCenterOfMassFromCentroid()
TransformNR com.neuronrobotics.sdk.addons.kinematics.MobileBase.getCenterOfMassFromCentroid ()
Definition at line 841 of file MobileBase.java.
References com.neuronrobotics.sdk.addons.kinematics.MobileBase.centerOfMassFromCentroid.
Referenced by com.neuronrobotics.sdk.addons.kinematics.MobileBase.getEmbedableXml().
getDrivable()
ArrayList<DHParameterKinematics> com.neuronrobotics.sdk.addons.kinematics.MobileBase.getDrivable ()
Gets the drivable.
Returns
the drivable
Definition at line 728 of file MobileBase.java.
References com.neuronrobotics.sdk.addons.kinematics.MobileBase.drivable.
getEmbedableXml()
String com.neuronrobotics.sdk.addons.kinematics.MobileBase.getEmbedableXml ()
Gets the embedable xml.
Returns
the embedable xml
Definition at line 617 of file MobileBase.java.
References com.neuronrobotics.sdk.addons.kinematics.MobileBase.appendages, com.neuronrobotics.sdk.addons.kinematics.MobileBase.drivable, com.neuronrobotics.sdk.addons.kinematics.MobileBase.getCenterOfMassFromCentroid(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getFiducialToGlobalTransform(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getGitCadEngine(), com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.getGitCadToolEngine(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.getGitWalkingEngine(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.getIMUFromCentroid(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.getMassKg(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.getParallelGroups(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getRobotToFiducialTransform(), com.neuronrobotics.sdk.common.BowlerAbstractDevice.getScriptingName(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.getVitamins(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.getVitaminVariant(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getXml(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.legs, com.neuronrobotics.sdk.addons.kinematics.MobileBase.makeLimbTag(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.setGlobalToFiducialTransform(), and com.neuronrobotics.sdk.addons.kinematics.MobileBase.steerable.
Referenced by com.neuronrobotics.sdk.addons.kinematics.DHLink.getXml(), and com.neuronrobotics.sdk.addons.kinematics.MobileBase.getXml().
getGitSelfSource()
String [] com.neuronrobotics.sdk.addons.kinematics.MobileBase.getGitSelfSource ()
Gets the self source.
Returns
the self source
Definition at line 817 of file MobileBase.java.
References com.neuronrobotics.sdk.addons.kinematics.MobileBase.selfSource.
Referenced by com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.generateStls(), com.neuronrobotics.bowlerstudio.BowlerKernel.processReturnedObjects(), and com.neuronrobotics.bowlerstudio.creature.UserManagedPrintBed.UserManagedPrintBed().
getGitWalkingEngine()
String [] com.neuronrobotics.sdk.addons.kinematics.MobileBase.getGitWalkingEngine ()
Gets the walking engine.
Returns
the walking engine
Definition at line 798 of file MobileBase.java.
References com.neuronrobotics.sdk.addons.kinematics.MobileBase.walkingEngine.
Referenced by com.neuronrobotics.sdk.addons.kinematics.MobileBase.getEmbedableXml(), and com.neuronrobotics.bowlerstudio.creature.MobileBaseLoader.setDefaultWalkingEngine().
getIMUFromCentroid()
TransformNR com.neuronrobotics.sdk.addons.kinematics.MobileBase.getIMUFromCentroid ()
Definition at line 849 of file MobileBase.java.
References com.neuronrobotics.sdk.addons.kinematics.MobileBase.IMUFromCentroid.
Referenced by com.neuronrobotics.sdk.addons.kinematics.MobileBase.getEmbedableXml(), and com.neuronrobotics.sdk.addons.kinematics.MobileBase.pose().
getLegs()
ArrayList<DHParameterKinematics> com.neuronrobotics.sdk.addons.kinematics.MobileBase.getLegs ()
Gets the legs.
Returns
the legs
Definition at line 467 of file MobileBase.java.
References com.neuronrobotics.sdk.addons.kinematics.MobileBase.legs.
Referenced by com.neuronrobotics.sdk.addons.kinematics.WalkingDriveEngine.DriveArc().
getMassKg()
double com.neuronrobotics.sdk.addons.kinematics.MobileBase.getMassKg ()
Definition at line 832 of file MobileBase.java.
References com.neuronrobotics.sdk.addons.kinematics.MobileBase.mass.
Referenced by com.neuronrobotics.sdk.addons.kinematics.MobileBase.getEmbedableXml(), and com.neuronrobotics.bowlerstudio.physics.MobileBasePhysicsManager.MobileBasePhysicsManager().
getname()
String com.neuronrobotics.sdk.addons.kinematics.MobileBase.getname (Element e) private
Gets the name.
Parameters
e the e
tag the tag
Returns
the name
Definition at line 312 of file MobileBase.java.
References com.neuronrobotics.sdk.addons.kinematics.MobileBase.getTag().
Referenced by com.neuronrobotics.sdk.addons.kinematics.MobileBase.loadLimb().
getParallelGroup() [1/3]
ParallelGroup com.neuronrobotics.sdk.addons.kinematics.MobileBase.getParallelGroup (DHParameterKinematics limb)
Definition at line 192 of file MobileBase.java.
References com.neuronrobotics.sdk.addons.kinematics.MobileBase.getParallelGroup(), and com.neuronrobotics.sdk.addons.kinematics.MobileBase.getParallelGroupNames().
getParallelGroup() [2/3]
String com.neuronrobotics.sdk.addons.kinematics.MobileBase.getParallelGroup (Element e) private
Gets the contents in the group.
Parameters
e the e
tag the tag
Returns
the name
Definition at line 326 of file MobileBase.java.
References com.neuronrobotics.sdk.addons.kinematics.MobileBase.getTag().
getParallelGroup() [3/3]
ParallelGroup com.neuronrobotics.sdk.addons.kinematics.MobileBase.getParallelGroup (String name)
Definition at line 171 of file MobileBase.java.
References com.neuronrobotics.sdk.addons.kinematics.MobileBase.getParallelGroups().
Referenced by com.neuronrobotics.sdk.addons.kinematics.MobileBase.addLimbToParallel(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.getAllParallelGroups(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.getParallelGroup(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.loadConfigs(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.loadLimb(), com.neuronrobotics.bowlerstudio.sequence.TimeSequence.loadMobileBase(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.main(), and com.neuronrobotics.sdk.addons.kinematics.MobileBase.removeLimFromParallel().
getParallelGroupNames()
Set<String> com.neuronrobotics.sdk.addons.kinematics.MobileBase.getParallelGroupNames ()
Definition at line 180 of file MobileBase.java.
References com.neuronrobotics.sdk.addons.kinematics.MobileBase.getParallelGroups().
Referenced by com.neuronrobotics.sdk.addons.kinematics.MobileBase.getAllParallelGroups(), and com.neuronrobotics.sdk.addons.kinematics.MobileBase.getParallelGroup().
getParallelGroups()
HashMap<String, ParallelGroup> com.neuronrobotics.sdk.addons.kinematics.MobileBase.getParallelGroups () private
Definition at line 875 of file MobileBase.java.
References com.neuronrobotics.sdk.addons.kinematics.MobileBase.parallelGroups.
Referenced by com.neuronrobotics.sdk.addons.kinematics.MobileBase.getEmbedableXml(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.getParallelGroup(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.getParallelGroupNames(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.initializeParalellGroups(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.makeLimbTag(), and com.neuronrobotics.sdk.addons.kinematics.MobileBase.removeLimFromParallel().
getSteerable()
ArrayList<DHParameterKinematics> com.neuronrobotics.sdk.addons.kinematics.MobileBase.getSteerable ()
Gets the steerable.
Returns
the steerable
Definition at line 719 of file MobileBase.java.
References com.neuronrobotics.sdk.addons.kinematics.MobileBase.steerable.
getTag()
String com.neuronrobotics.sdk.addons.kinematics.MobileBase.getTag (Element e, String tagname) private
Gets the localTag
Parameters
e the e
tag the tag
Returns
the name
Definition at line 337 of file MobileBase.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.MobileBase.getname(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.getParallelGroup(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.loadConfigs(), and com.neuronrobotics.sdk.addons.kinematics.MobileBase.loadLimb().
getTipLocations()
HashMap<DHParameterKinematics, TransformNR> com.neuronrobotics.sdk.addons.kinematics.MobileBase.getTipLocations ()
Definition at line 86 of file MobileBase.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.calcHome(), and com.neuronrobotics.sdk.addons.kinematics.MobileBase.legs.
Referenced by com.neuronrobotics.sdk.addons.kinematics.MobileBase.pose(), and com.neuronrobotics.sdk.addons.kinematics.MobileBase.poseAroundPoint().
getVitamins() [1/2]
HashMap<String, String[]> com.neuronrobotics.sdk.addons.kinematics.MobileBase.getVitamins ()
Definition at line 524 of file MobileBase.java.
References com.neuronrobotics.sdk.addons.kinematics.MobileBase.vitamins.
Referenced by com.neuronrobotics.sdk.addons.kinematics.MobileBase.getEmbedableXml(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.loadVitamins(), and com.neuronrobotics.sdk.addons.kinematics.MobileBase.setVitamin().
getVitamins() [2/2]
void com.neuronrobotics.sdk.addons.kinematics.MobileBase.getVitamins (Element doc) private
Gets the vitamins.
Parameters
doc the doc
Definition at line 533 of file MobileBase.java.
References com.neuronrobotics.sdk.addons.kinematics.xml.XmlFactory.getTagValue(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.setVitamin(), and com.neuronrobotics.sdk.addons.kinematics.MobileBase.setVitaminVariant().
getVitaminVariant()
String com.neuronrobotics.sdk.addons.kinematics.MobileBase.getVitaminVariant (String name)
Get a purchaing code for a vitamin
Parameters
name name of vitamin
Returns
Definition at line 588 of file MobileBase.java.
References com.neuronrobotics.sdk.addons.kinematics.MobileBase.vitaminVariant.
Referenced by com.neuronrobotics.sdk.addons.kinematics.MobileBase.getEmbedableXml().
getWalkingDriveEngine()
IDriveEngine com.neuronrobotics.sdk.addons.kinematics.MobileBase.getWalkingDriveEngine () private
Gets the walking drive engine.
Returns
the walking drive engine
Definition at line 737 of file MobileBase.java.
References com.neuronrobotics.sdk.addons.kinematics.MobileBase.walkingDriveEngine.
Referenced by com.neuronrobotics.sdk.addons.kinematics.MobileBase.DriveArc(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.DriveVelocityArc(), and com.neuronrobotics.sdk.addons.kinematics.MobileBase.DriveVelocityStraight().
getXml()
String com.neuronrobotics.sdk.addons.kinematics.MobileBase.getXml ()
Gets the xml.
Returns
the xml
Reimplemented from com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.
Definition at line 601 of file MobileBase.java.
References com.neuronrobotics.sdk.addons.kinematics.MobileBase.getEmbedableXml().
Referenced by com.neuronrobotics.bowlerstudio.scripting.RobotHelper.getDefaultContents(), and com.neuronrobotics.sdk.addons.kinematics.MobileBase.main().
initializeParalellGroups()
void com.neuronrobotics.sdk.addons.kinematics.MobileBase.initializeParalellGroups ()
Definition at line 261 of file MobileBase.java.
References com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.calcHome(), com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.getConstituantLimbs(), com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.getNameOfParallelGroup(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.getParallelGroups(), and com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.setDesiredTaskSpaceTransform().
Referenced by com.neuronrobotics.bowlerstudio.creature.MobileBaseLoader.MobileBaseLoader().
inverseKinematics()
double [] com.neuronrobotics.sdk.addons.kinematics.MobileBase.inverseKinematics (TransformNR taskSpaceTransform) throws Exception
Inverse kinematics.
Parameters
taskSpaceTransform the task space transform
Returns
Nx1 vector in task space, in mm where N is number of links
Exceptions
Exception the exception
Reimplemented from com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.
Definition at line 445 of file MobileBase.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getNumberOfLinks().
loadConfigs()
void com.neuronrobotics.sdk.addons.kinematics.MobileBase.loadConfigs (Element doc) private
Load configs.
Parameters
doc the doc
Definition at line 225 of file MobileBase.java.
References com.neuronrobotics.sdk.addons.kinematics.MobileBase.appendages, com.neuronrobotics.sdk.addons.kinematics.MobileBase.drivable, com.neuronrobotics.sdk.addons.kinematics.MobileBase.fireBaseUpdates(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getGitCodes(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.getParallelGroup(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.getTag(), com.neuronrobotics.sdk.addons.kinematics.xml.XmlFactory.getTagValue(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.legs, com.neuronrobotics.sdk.addons.kinematics.MobileBase.loadLimb(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.loadTransform(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.loadVitamins(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.setCenterOfMassFromCentroid(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.setGitCadEngine(), com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.setGitCadToolEngine(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.setGitWalkingEngine(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.setIMUFromCentroid(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.setMassKg(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.setRobotToFiducialTransform(), com.neuronrobotics.sdk.common.BowlerAbstractDevice.setScriptingName(), and com.neuronrobotics.sdk.addons.kinematics.MobileBase.steerable.
Referenced by com.neuronrobotics.sdk.addons.kinematics.MobileBase.MobileBase().
loadLimb()
void com.neuronrobotics.sdk.addons.kinematics.MobileBase.loadLimb (Element doc, String tag, ArrayList< DHParameterKinematics > list) private
Load limb.
Parameters
doc the doc
tag the tag
list the list
Definition at line 366 of file MobileBase.java.
References com.neuronrobotics.sdk.addons.kinematics.MobileBase.getname(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.getParallelGroup(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.getTag(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.loadTransform(), com.neuronrobotics.sdk.common.BowlerAbstractDevice.setScriptingName(), and com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.setupReferencedLimbStartup().
Referenced by com.neuronrobotics.sdk.addons.kinematics.MobileBase.loadConfigs().
loadTransform()
TransformNR com.neuronrobotics.sdk.addons.kinematics.MobileBase.loadTransform (String tagname, Element e) private
Definition at line 279 of file MobileBase.java.
References com.neuronrobotics.sdk.addons.kinematics.xml.XmlFactory.getTagValue().
Referenced by com.neuronrobotics.sdk.addons.kinematics.MobileBase.loadConfigs(), and com.neuronrobotics.sdk.addons.kinematics.MobileBase.loadLimb().
loadVitamins()
void com.neuronrobotics.sdk.addons.kinematics.MobileBase.loadVitamins (Element doc) private
Load limb.
Parameters
doc the doc
tag the tag
list the list
Definition at line 510 of file MobileBase.java.
References com.neuronrobotics.sdk.addons.kinematics.MobileBase.getVitamins().
Referenced by com.neuronrobotics.sdk.addons.kinematics.MobileBase.loadConfigs().
main()
static void com.neuronrobotics.sdk.addons.kinematics.MobileBase.main (String[] args) throws Exception static
Definition at line 922 of file MobileBase.java.
References com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.copy(), com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.getConstituantLimbs(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getCurrentTaskSpaceTransform(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.getParallelGroup(), com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.getTipOffset(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getX(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.getXml(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.MobileBase(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.setDesiredTaskSpaceTransform(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.times(), and com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.translateX().
makeLimbTag()
String com.neuronrobotics.sdk.addons.kinematics.MobileBase.makeLimbTag (String xml, DHParameterKinematics l) private
Definition at line 694 of file MobileBase.java.
References com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.getConstituantLimbs(), com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getEmbedableXml(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.getParallelGroups(), com.neuronrobotics.sdk.common.BowlerAbstractDevice.getScriptingName(), com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.getTipOffset(), com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.getTipOffsetRelativeIndex(), and com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.getTipOffsetRelativeName().
Referenced by com.neuronrobotics.sdk.addons.kinematics.MobileBase.getEmbedableXml().
onIOnMobileBaseRenderChange()
void com.neuronrobotics.sdk.addons.kinematics.MobileBase.onIOnMobileBaseRenderChange ()
Implements com.neuronrobotics.sdk.addons.kinematics.IOnMobileBaseRenderChange.
Definition at line 990 of file MobileBase.java.
References com.neuronrobotics.sdk.addons.kinematics.MobileBase.fireIOnMobileBaseRenderChange().
onJointSpaceLimit()
void com.neuronrobotics.sdk.addons.kinematics.MobileBase.onJointSpaceLimit (AbstractKinematicsNR source, int axis, JointLimit event)
The JointSpace limit This is called when the kinematics model has a new set of pose data.
Parameters
source The AbstractKinematics object that the update was called from
axis the axis
event the event
Implements com.neuronrobotics.sdk.addons.kinematics.IJointSpaceUpdateListenerNR.
Definition at line 1008 of file MobileBase.java.
onJointSpaceTargetUpdate()
void com.neuronrobotics.sdk.addons.kinematics.MobileBase.onJointSpaceTargetUpdate (AbstractKinematicsNR source, double[] joints)
The JointSpace update event This is called when the kinematics model has a new set of pose data.
Parameters
source The AbstractKinematics object that the update was called from
joints the current joint space values mm,radians
Implements com.neuronrobotics.sdk.addons.kinematics.IJointSpaceUpdateListenerNR.
Definition at line 1002 of file MobileBase.java.
onJointSpaceUpdate()
void com.neuronrobotics.sdk.addons.kinematics.MobileBase.onJointSpaceUpdate (AbstractKinematicsNR source, double[] joints)
The JointSpace update event This is called when the kinematics model has a new set of pose data.
Parameters
source The AbstractKinematics object that the update was called from
joints the current joint space values mm,radians
Implements com.neuronrobotics.sdk.addons.kinematics.IJointSpaceUpdateListenerNR.
Definition at line 996 of file MobileBase.java.
References com.neuronrobotics.sdk.addons.kinematics.MobileBase.fireIOnMobileBaseRenderChange().
pose() [1/2]
boolean com.neuronrobotics.sdk.addons.kinematics.MobileBase.pose (TransformNR newAbsolutePose) throws Exception
Definition at line 97 of file MobileBase.java.
References com.neuronrobotics.sdk.addons.kinematics.MobileBase.getIMUFromCentroid(), and com.neuronrobotics.sdk.addons.kinematics.MobileBase.getTipLocations().
Referenced by com.neuronrobotics.sdk.addons.kinematics.MobileBase.pose(), and com.neuronrobotics.sdk.addons.kinematics.MobileBase.poseAroundPoint().
pose() [2/2]
boolean com.neuronrobotics.sdk.addons.kinematics.MobileBase.pose (TransformNR newAbsolutePose, TransformNR around, HashMap< DHParameterKinematics, TransformNR > tipList) throws Exception
Definition at line 109 of file MobileBase.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getFiducialToGlobalTransform(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.legs, com.neuronrobotics.sdk.addons.kinematics.MobileBase.pose(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.setGlobalToFiducialTransform(), and com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.times().
poseAroundPoint()
boolean com.neuronrobotics.sdk.addons.kinematics.MobileBase.poseAroundPoint (TransformNR newAbsolutePose, TransformNR around) throws Exception
Definition at line 103 of file MobileBase.java.
References com.neuronrobotics.sdk.addons.kinematics.MobileBase.getTipLocations(), and com.neuronrobotics.sdk.addons.kinematics.MobileBase.pose().
removeIOnMobileBaseRenderChange()
void com.neuronrobotics.sdk.addons.kinematics.MobileBase.removeIOnMobileBaseRenderChange (IOnMobileBaseRenderChange l)
Definition at line 973 of file MobileBase.java.
References com.neuronrobotics.sdk.addons.kinematics.MobileBase.changeListeners.
removeLimFromParallel()
void com.neuronrobotics.sdk.addons.kinematics.MobileBase.removeLimFromParallel (DHParameterKinematics limb) private
Definition at line 210 of file MobileBase.java.
References com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.getConstituantLimbs(), com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.getNameOfParallelGroup(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.getParallelGroup(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.getParallelGroups(), and com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.removeLimb().
Referenced by com.neuronrobotics.sdk.addons.kinematics.MobileBase.addLimbToParallel().
setCenterOfMassFromCentroid()
void com.neuronrobotics.sdk.addons.kinematics.MobileBase.setCenterOfMassFromCentroid (TransformNR centerOfMassFromCentroid)
Definition at line 845 of file MobileBase.java.
References com.neuronrobotics.sdk.addons.kinematics.MobileBase.centerOfMassFromCentroid.
Referenced by com.neuronrobotics.sdk.addons.kinematics.MobileBase.loadConfigs().
setFiducialToGlobalTransform()
void com.neuronrobotics.sdk.addons.kinematics.MobileBase.setFiducialToGlobalTransform (TransformNR globe)
Definition at line 857 of file MobileBase.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.setGlobalToFiducialTransform().
Referenced by com.neuronrobotics.bowlerstudio.physics.MobileBasePhysicsManager.MobileBasePhysicsManager().
setGitSelfSource()
void com.neuronrobotics.sdk.addons.kinematics.MobileBase.setGitSelfSource (String[] selfSource)
Sets the self source. index 0 is GIT url index 1 is filename
Parameters
selfSource the new self source
Definition at line 828 of file MobileBase.java.
References com.neuronrobotics.sdk.addons.kinematics.MobileBase.selfSource.
Referenced by com.neuronrobotics.bowlerstudio.creature.MobileBaseLoader.fromGit(), com.neuronrobotics.bowlerstudio.scripting.RobotHelper.getDefaultContents(), and com.neuronrobotics.bowlerstudio.scripting.RobotHelper.inlineScriptRun().
setGitWalkingEngine()
void com.neuronrobotics.sdk.addons.kinematics.MobileBase.setGitWalkingEngine (String[] walkingEngine)
Sets the walking engine.
Parameters
walkingEngine the new walking engine
Definition at line 807 of file MobileBase.java.
References com.neuronrobotics.sdk.addons.kinematics.MobileBase.walkingEngine.
Referenced by com.neuronrobotics.bowlerstudio.scripting.RobotHelper.getDefaultContents(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.loadConfigs(), and com.neuronrobotics.bowlerstudio.creature.MobileBaseLoader.setGitWalkingEngine().
setHomeProvider()
void com.neuronrobotics.sdk.addons.kinematics.MobileBase.setHomeProvider (ICalcLimbHomeProvider homeProvider)
Definition at line 963 of file MobileBase.java.
References com.neuronrobotics.sdk.addons.kinematics.MobileBase.homeProvider.
setIMUFromCentroid()
void com.neuronrobotics.sdk.addons.kinematics.MobileBase.setIMUFromCentroid (TransformNR centerOfMassFromCentroid)
Definition at line 853 of file MobileBase.java.
References com.neuronrobotics.sdk.addons.kinematics.MobileBase.centerOfMassFromCentroid.
Referenced by com.neuronrobotics.sdk.addons.kinematics.MobileBase.loadConfigs().
setMassKg()
void com.neuronrobotics.sdk.addons.kinematics.MobileBase.setMassKg (double mass)
Definition at line 836 of file MobileBase.java.
References com.neuronrobotics.sdk.common.BowlerAbstractDevice.getScriptingName(), and com.neuronrobotics.sdk.addons.kinematics.MobileBase.mass.
Referenced by com.neuronrobotics.sdk.addons.kinematics.MobileBase.loadConfigs().
setVitamin()
void com.neuronrobotics.sdk.addons.kinematics.MobileBase.setVitamin (String name, String type, String id)
Add a vitamin to this link
Parameters
name the name of this vitamin, if the name already exists, the data will be overwritten.
type the vitamin type, this maps the the json filename
id the part ID, theis maps to the key in the json for the vitamin
Definition at line 564 of file MobileBase.java.
References com.neuronrobotics.sdk.addons.kinematics.MobileBase.getVitamins().
Referenced by com.neuronrobotics.sdk.addons.kinematics.MobileBase.getVitamins().
setVitaminVariant()
void com.neuronrobotics.sdk.addons.kinematics.MobileBase.setVitaminVariant (String name, String tagValue2)
Set a purchasing code for a vitamin
Parameters
name name of vitamin
tagValue2 Purchaning code
Definition at line 578 of file MobileBase.java.
References com.neuronrobotics.sdk.addons.kinematics.MobileBase.vitaminVariant.
Referenced by com.neuronrobotics.sdk.addons.kinematics.MobileBase.getVitamins().
setWalkingDriveEngine()
void com.neuronrobotics.sdk.addons.kinematics.MobileBase.setWalkingDriveEngine (IDriveEngine walkingDriveEngine)
Sets the walking drive engine.
Parameters
walkingDriveEngine the new walking drive engine
Definition at line 747 of file MobileBase.java.
References com.neuronrobotics.sdk.addons.kinematics.MobileBase.walkingDriveEngine.
Referenced by com.neuronrobotics.bowlerstudio.creature.MobileBaseLoader.setGitWalkingEngine().
shutDownParallel()
void com.neuronrobotics.sdk.addons.kinematics.MobileBase.shutDownParallel (ParallelGroup group)
Definition at line 870 of file MobileBase.java.
References com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.close(), com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.getNameOfParallelGroup(), and com.neuronrobotics.sdk.addons.kinematics.MobileBase.parallelGroups.
sync()
void com.neuronrobotics.sdk.addons.kinematics.MobileBase.sync ()
Implements com.neuronrobotics.sdk.addons.kinematics.IHardwareSyncPulseReciver.
Definition at line 1014 of file MobileBase.java.
References com.neuronrobotics.sdk.addons.kinematics.IHardwareSyncPulseProvider.doSync().
updatePositions()
void com.neuronrobotics.sdk.addons.kinematics.MobileBase.updatePositions ()
Update positions.
Definition at line 788 of file MobileBase.java.
References com.neuronrobotics.sdk.addons.kinematics.MobileBase.fireIOnMobileBaseRenderChange(), and com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.runRenderWrangler().
Referenced by com.neuronrobotics.sdk.addons.kinematics.MobileBase.DriveArc(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.DriveVelocityArc(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.DriveVelocityStraight(), and com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.setMobileBase().
Member Data Documentation
appendages
final ArrayList<DHParameterKinematics> com.neuronrobotics.sdk.addons.kinematics.MobileBase.appendages = new ArrayList<DHParameterKinematics>() private
The appendages.
Definition at line 35 of file MobileBase.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.MobileBase.getAllDHChains(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.getAppendages(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.getEmbedableXml(), and com.neuronrobotics.sdk.addons.kinematics.MobileBase.loadConfigs().
centerOfMassFromCentroid
TransformNR com.neuronrobotics.sdk.addons.kinematics.MobileBase.centerOfMassFromCentroid = new TransformNR() private
Definition at line 60 of file MobileBase.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.MobileBase.getCenterOfMassFromCentroid(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.setCenterOfMassFromCentroid(), and com.neuronrobotics.sdk.addons.kinematics.MobileBase.setIMUFromCentroid().
changeListeners
final ArrayList<IOnMobileBaseRenderChange> com.neuronrobotics.sdk.addons.kinematics.MobileBase.changeListeners = new ArrayList<IOnMobileBaseRenderChange>() private
The drivable.
Definition at line 44 of file MobileBase.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.MobileBase.addIOnMobileBaseRenderChange(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.clearIOnMobileBaseRenderChange(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.fireIOnMobileBaseRenderChange(), and com.neuronrobotics.sdk.addons.kinematics.MobileBase.removeIOnMobileBaseRenderChange().
drivable
final ArrayList<DHParameterKinematics> com.neuronrobotics.sdk.addons.kinematics.MobileBase.drivable = new ArrayList<DHParameterKinematics>() private
The drivable.
Definition at line 41 of file MobileBase.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.MobileBase.getAllDHChains(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.getDrivable(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.getEmbedableXml(), and com.neuronrobotics.sdk.addons.kinematics.MobileBase.loadConfigs().
homeProvider
ICalcLimbHomeProvider com.neuronrobotics.sdk.addons.kinematics.MobileBase.homeProvider = null private
Definition at line 65 of file MobileBase.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.MobileBase.calcHome(), and com.neuronrobotics.sdk.addons.kinematics.MobileBase.setHomeProvider().
IMUFromCentroid
TransformNR com.neuronrobotics.sdk.addons.kinematics.MobileBase.IMUFromCentroid = new TransformNR() private
Definition at line 62 of file MobileBase.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.MobileBase.getIMUFromCentroid().
legs
final ArrayList<DHParameterKinematics> com.neuronrobotics.sdk.addons.kinematics.MobileBase.legs = new ArrayList<DHParameterKinematics>() private
The legs.
Definition at line 32 of file MobileBase.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.MobileBase.getAllDHChains(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.getEmbedableXml(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.getLegs(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.getTipLocations(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.loadConfigs(), and com.neuronrobotics.sdk.addons.kinematics.MobileBase.pose().
mass
double com.neuronrobotics.sdk.addons.kinematics.MobileBase.mass = 0.5 private
Definition at line 59 of file MobileBase.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.MobileBase.getMassKg(), and com.neuronrobotics.sdk.addons.kinematics.MobileBase.setMassKg().
parallelGroups
HashMap<String, ParallelGroup> com.neuronrobotics.sdk.addons.kinematics.MobileBase.parallelGroups = new HashMap<String, ParallelGroup>() private
Definition at line 64 of file MobileBase.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.MobileBase.getParallelGroups(), and com.neuronrobotics.sdk.addons.kinematics.MobileBase.shutDownParallel().
selfSource
String [] com.neuronrobotics.sdk.addons.kinematics.MobileBase.selfSource = new String[2] private
The self source.
Definition at line 57 of file MobileBase.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.MobileBase.getGitSelfSource(), and com.neuronrobotics.sdk.addons.kinematics.MobileBase.setGitSelfSource().
steerable
final ArrayList<DHParameterKinematics> com.neuronrobotics.sdk.addons.kinematics.MobileBase.steerable = new ArrayList<DHParameterKinematics>() private
The steerable.
Definition at line 38 of file MobileBase.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.MobileBase.getAllDHChains(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.getEmbedableXml(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.getSteerable(), and com.neuronrobotics.sdk.addons.kinematics.MobileBase.loadConfigs().
vitamins
HashMap<String, String[]> com.neuronrobotics.sdk.addons.kinematics.MobileBase.vitamins = new HashMap<String, String[]>() private
Definition at line 53 of file MobileBase.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.MobileBase.getVitamins().
vitaminVariant
HashMap<String, String> com.neuronrobotics.sdk.addons.kinematics.MobileBase.vitaminVariant = new HashMap<String, String>() private
Definition at line 54 of file MobileBase.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.MobileBase.getVitaminVariant(), and com.neuronrobotics.sdk.addons.kinematics.MobileBase.setVitaminVariant().
walkingDriveEngine
IDriveEngine com.neuronrobotics.sdk.addons.kinematics.MobileBase.walkingDriveEngine = new WalkingDriveEngine() private
The walking drive engine.
Definition at line 47 of file MobileBase.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.MobileBase.getWalkingDriveEngine(), and com.neuronrobotics.sdk.addons.kinematics.MobileBase.setWalkingDriveEngine().
walkingEngine
String [] com.neuronrobotics.sdk.addons.kinematics.MobileBase.walkingEngine private
Initial value:
= new String[] { "https://github.com/madhephaestus/carl-the-hexapod.git",
            "WalkingDriveEngine.groovy" }
The walking engine.
Definition at line 50 of file MobileBase.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.MobileBase.getGitWalkingEngine(), and com.neuronrobotics.sdk.addons.kinematics.MobileBase.setGitWalkingEngine().
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/addons/kinematics/MobileBase.java