BowlerKernel: com.neuronrobotics.sdk.pid.PausableTime Class Reference
com.neuronrobotics.sdk.pid.PausableTime Class Reference
Static Public Member Functions
static long currentTimeMillis ()
static void pause (boolean val)
static void step (long ms)
static void sleep (long durationMS)
static void addIPauseTimeListener (IPauseTimeListener l)
static void removeIPauseTimeListener (IPauseTimeListener l)
Static Private Attributes
static long timePaused = 0
static long durationPaused = 0
static boolean paused =false
static ArrayList< IPauseTimeListener > listeners = new ArrayList<IPauseTimeListener>()
Detailed Description
Definition at line 5 of file PausableTime.java.
Member Function Documentation
addIPauseTimeListener()
static void com.neuronrobotics.sdk.pid.PausableTime.addIPauseTimeListener (IPauseTimeListener l) static
Definition at line 53 of file PausableTime.java.
References com.neuronrobotics.sdk.pid.PausableTime.listeners.
currentTimeMillis()
static long com.neuronrobotics.sdk.pid.PausableTime.currentTimeMillis () static
Definition at line 11 of file PausableTime.java.
References com.neuronrobotics.sdk.pid.PausableTime.durationPaused, com.neuronrobotics.sdk.pid.PausableTime.paused, and com.neuronrobotics.sdk.pid.PausableTime.timePaused.
pause()
static void com.neuronrobotics.sdk.pid.PausableTime.pause (boolean val) static
Definition at line 17 of file PausableTime.java.
References com.neuronrobotics.sdk.pid.PausableTime.durationPaused, com.neuronrobotics.sdk.pid.PausableTime.listeners, com.neuronrobotics.sdk.pid.PausableTime.paused, and com.neuronrobotics.sdk.pid.PausableTime.timePaused.
Referenced by com.neuronrobotics.sdk.pid.PausableTime.step().
removeIPauseTimeListener()
static void com.neuronrobotics.sdk.pid.PausableTime.removeIPauseTimeListener (IPauseTimeListener l) static
Definition at line 58 of file PausableTime.java.
References com.neuronrobotics.sdk.pid.PausableTime.listeners.
sleep()
static void com.neuronrobotics.sdk.pid.PausableTime.sleep (long durationMS) static
Definition at line 38 of file PausableTime.java.
References com.neuronrobotics.sdk.pid.PausableTime.paused.
Referenced by com.neuronrobotics.sdk.pid.PausableTime.step().
step()
static void com.neuronrobotics.sdk.pid.PausableTime.step (long ms) static
Definition at line 29 of file PausableTime.java.
References com.neuronrobotics.sdk.pid.PausableTime.pause(), com.neuronrobotics.sdk.pid.PausableTime.paused, and com.neuronrobotics.sdk.pid.PausableTime.sleep().
Member Data Documentation
durationPaused
long com.neuronrobotics.sdk.pid.PausableTime.durationPaused = 0 static private
Definition at line 7 of file PausableTime.java.
Referenced by com.neuronrobotics.sdk.pid.PausableTime.currentTimeMillis(), and com.neuronrobotics.sdk.pid.PausableTime.pause().
listeners
ArrayList<IPauseTimeListener> com.neuronrobotics.sdk.pid.PausableTime.listeners = new ArrayList<IPauseTimeListener>() static private
Definition at line 9 of file PausableTime.java.
Referenced by com.neuronrobotics.sdk.pid.PausableTime.addIPauseTimeListener(), com.neuronrobotics.sdk.pid.PausableTime.pause(), and com.neuronrobotics.sdk.pid.PausableTime.removeIPauseTimeListener().
paused
boolean com.neuronrobotics.sdk.pid.PausableTime.paused =false static private
Definition at line 8 of file PausableTime.java.
Referenced by com.neuronrobotics.sdk.pid.PausableTime.currentTimeMillis(), com.neuronrobotics.sdk.pid.PausableTime.pause(), com.neuronrobotics.sdk.pid.PausableTime.sleep(), and com.neuronrobotics.sdk.pid.PausableTime.step().
timePaused
long com.neuronrobotics.sdk.pid.PausableTime.timePaused = 0 static private
Definition at line 6 of file PausableTime.java.
Referenced by com.neuronrobotics.sdk.pid.PausableTime.currentTimeMillis(), and com.neuronrobotics.sdk.pid.PausableTime.pause().
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/pid/PausableTime.java