BowlerKernel: com.neuronrobotics.bowlerkernel.Bezier3d.manipulation Class Reference
com.neuronrobotics.bowlerkernel.Bezier3d.manipulation Class Reference
Classes
enum DragState
Public Member Functions
void addEventListener (Runnable r)
void addDependant (manipulation r)
void addSaveListener (Runnable r)
void clearListeners ()
manipulation (Affine mm, Vector3d o, CSG m, TransformNR p)
boolean isMoving ()
void set (double newX, double newY, double newZ)
Static Public Member Functions
static IInteractiveUIElementProvider getUi ()
static void setUi (IInteractiveUIElementProvider ui)
Public Attributes
TransformNR currentPose
Private Member Functions
void fireMove (TransformNR trans, TransformNR camFrame2)
void fireSave ()
void pressed (MouseEvent event)
void release (MouseEvent event)
void dragged (MouseEvent event)
void mouseRelease (MouseEvent event)
void setDragging (MouseEvent event)
void performMove (TransformNR trans, TransformNR camFrame2)
void setGlobal (TransformNR global)
Private Attributes
ArrayList< Runnable > eventListeners = new ArrayList<>()
ArrayList< Runnable > saveListeners = new ArrayList<>()
ArrayList< manipulation > dependants = new ArrayList<>()
Affine manipulationMatrix
Vector3d orintation
CSG manip
TransformNR globalPose
PhongMaterial color
PhongMaterial highlight = new PhongMaterial(Color.GOLD)
DragState state = DragState.IDLE
Static Private Attributes
static IInteractiveUIElementProvider ui
Detailed Description
Definition at line 19 of file manipulation.java.
Constructor & Destructor Documentation
manipulation()
com.neuronrobotics.bowlerkernel.Bezier3d.manipulation.manipulation (Affine mm, Vector3d o, CSG m, TransformNR p)
Definition at line 90 of file manipulation.java.
References com.neuronrobotics.bowlerkernel.Bezier3d.manipulation.color, com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.copy(), com.neuronrobotics.bowlerkernel.Bezier3d.manipulation.currentPose, eu.mihosoft.vrl.v3d.CSG.getColor(), com.neuronrobotics.bowlerkernel.Bezier3d.manipulation.getUi(), com.neuronrobotics.bowlerkernel.Bezier3d.manipulation.globalPose, com.neuronrobotics.bowlerkernel.Bezier3d.manipulation.manipulationMatrix, com.neuronrobotics.bowlerstudio.physics.TransformFactory.nrToAffine(), and com.neuronrobotics.bowlerkernel.Bezier3d.IInteractiveUIElementProvider.runLater().
Member Function Documentation
addDependant()
void com.neuronrobotics.bowlerkernel.Bezier3d.manipulation.addDependant (manipulation r)
Definition at line 55 of file manipulation.java.
References com.neuronrobotics.bowlerkernel.Bezier3d.manipulation.dependants.
addEventListener()
void com.neuronrobotics.bowlerkernel.Bezier3d.manipulation.addEventListener (Runnable r)
Definition at line 49 of file manipulation.java.
References com.neuronrobotics.bowlerkernel.Bezier3d.manipulation.eventListeners.
Referenced by com.neuronrobotics.bowlerstudio.printbed.PrintBedObject.addEventListener().
addSaveListener()
void com.neuronrobotics.bowlerkernel.Bezier3d.manipulation.addSaveListener (Runnable r)
Definition at line 61 of file manipulation.java.
References com.neuronrobotics.bowlerkernel.Bezier3d.manipulation.saveListeners.
Referenced by com.neuronrobotics.bowlerstudio.printbed.PrintBedObject.addSaveListener(), and com.neuronrobotics.bowlerstudio.printbed.PrintBedObject.PrintBedObject().
clearListeners()
void com.neuronrobotics.bowlerkernel.Bezier3d.manipulation.clearListeners ()
Definition at line 67 of file manipulation.java.
References com.neuronrobotics.bowlerkernel.Bezier3d.manipulation.eventListeners, and com.neuronrobotics.bowlerkernel.Bezier3d.manipulation.saveListeners.
dragged()
void com.neuronrobotics.bowlerkernel.Bezier3d.manipulation.dragged (MouseEvent event) private
Definition at line 163 of file manipulation.java.
fireMove()
void com.neuronrobotics.bowlerkernel.Bezier3d.manipulation.fireMove (TransformNR trans, TransformNR camFrame2) private
Definition at line 73 of file manipulation.java.
References com.neuronrobotics.bowlerkernel.Bezier3d.manipulation.dependants, and com.neuronrobotics.bowlerkernel.Bezier3d.manipulation.eventListeners.
fireSave()
void com.neuronrobotics.bowlerkernel.Bezier3d.manipulation.fireSave () private
Definition at line 82 of file manipulation.java.
References com.neuronrobotics.bowlerkernel.Bezier3d.manipulation.saveListeners.
getUi()
static IInteractiveUIElementProvider com.neuronrobotics.bowlerkernel.Bezier3d.manipulation.getUi () static
Definition at line 230 of file manipulation.java.
Referenced by com.neuronrobotics.bowlerkernel.Bezier3d.manipulation.manipulation().
isMoving()
boolean com.neuronrobotics.bowlerkernel.Bezier3d.manipulation.isMoving ()
Definition at line 175 of file manipulation.java.
References com.neuronrobotics.bowlerkernel.Bezier3d.manipulation.DragState.Dragging.
mouseRelease()
void com.neuronrobotics.bowlerkernel.Bezier3d.manipulation.mouseRelease (MouseEvent event) private
Definition at line 179 of file manipulation.java.
References com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.setX(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.setY(), and com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.setZ().
performMove()
void com.neuronrobotics.bowlerkernel.Bezier3d.manipulation.performMove (TransformNR trans, TransformNR camFrame2) private
Definition at line 201 of file manipulation.java.
References com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.copy(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getX(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getY(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getZ(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.setRotation(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.setX(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.setY(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.setZ(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.times(), eu.mihosoft.vrl.v3d.Vector3d.x(), eu.mihosoft.vrl.v3d.Vector3d.y(), and eu.mihosoft.vrl.v3d.Vector3d.z().
pressed()
void com.neuronrobotics.bowlerkernel.Bezier3d.manipulation.pressed (MouseEvent event) private
Definition at line 140 of file manipulation.java.
References com.neuronrobotics.bowlerkernel.Bezier3d.manipulation.DragState.Dragging.
release()
void com.neuronrobotics.bowlerkernel.Bezier3d.manipulation.release (MouseEvent event) private
Definition at line 155 of file manipulation.java.
References eu.mihosoft.vrl.v3d.CSG.getMesh(), and com.neuronrobotics.bowlerkernel.Bezier3d.manipulation.DragState.IDLE.
set()
void com.neuronrobotics.bowlerkernel.Bezier3d.manipulation.set (double newX, double newY, double newZ)
Definition at line 238 of file manipulation.java.
References com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.setX(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.setY(), and com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.setZ().
Referenced by com.neuronrobotics.bowlerstudio.printbed.PrintBedObject.checkBounds().
setDragging()
void com.neuronrobotics.bowlerkernel.Bezier3d.manipulation.setDragging (MouseEvent event) private
Definition at line 190 of file manipulation.java.
setGlobal()
void com.neuronrobotics.bowlerkernel.Bezier3d.manipulation.setGlobal (TransformNR global) private
Definition at line 221 of file manipulation.java.
References com.neuronrobotics.bowlerstudio.physics.TransformFactory.nrToAffine(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.setX(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.setY(), and com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.setZ().
setUi()
static void com.neuronrobotics.bowlerkernel.Bezier3d.manipulation.setUi (IInteractiveUIElementProvider ui) static
Definition at line 234 of file manipulation.java.
References com.neuronrobotics.bowlerkernel.Bezier3d.manipulation.ui.
Member Data Documentation
color
PhongMaterial com.neuronrobotics.bowlerkernel.Bezier3d.manipulation.color private
Definition at line 40 of file manipulation.java.
Referenced by com.neuronrobotics.bowlerkernel.Bezier3d.manipulation.manipulation().
currentPose
TransformNR com.neuronrobotics.bowlerkernel.Bezier3d.manipulation.currentPose
Definition at line 39 of file manipulation.java.
Referenced by com.neuronrobotics.bowlerkernel.Bezier3d.CartesianManipulator.getX(), com.neuronrobotics.bowlerstudio.printbed.PrintBedObject.getX(), com.neuronrobotics.bowlerkernel.Bezier3d.CartesianManipulator.getY(), com.neuronrobotics.bowlerstudio.printbed.PrintBedObject.getY(), com.neuronrobotics.bowlerkernel.Bezier3d.CartesianManipulator.getZ(), com.neuronrobotics.bowlerstudio.printbed.PrintBedObject.getZ(), and com.neuronrobotics.bowlerkernel.Bezier3d.manipulation.manipulation().
dependants
ArrayList<manipulation> com.neuronrobotics.bowlerkernel.Bezier3d.manipulation.dependants = new ArrayList<>() private
Definition at line 34 of file manipulation.java.
Referenced by com.neuronrobotics.bowlerkernel.Bezier3d.manipulation.addDependant(), and com.neuronrobotics.bowlerkernel.Bezier3d.manipulation.fireMove().
eventListeners
ArrayList<Runnable> com.neuronrobotics.bowlerkernel.Bezier3d.manipulation.eventListeners = new ArrayList<>() private
Definition at line 32 of file manipulation.java.
Referenced by com.neuronrobotics.bowlerkernel.Bezier3d.manipulation.addEventListener(), com.neuronrobotics.bowlerkernel.Bezier3d.manipulation.clearListeners(), and com.neuronrobotics.bowlerkernel.Bezier3d.manipulation.fireMove().
globalPose
TransformNR com.neuronrobotics.bowlerkernel.Bezier3d.manipulation.globalPose private
Definition at line 38 of file manipulation.java.
Referenced by com.neuronrobotics.bowlerkernel.Bezier3d.manipulation.manipulation().
highlight
PhongMaterial com.neuronrobotics.bowlerkernel.Bezier3d.manipulation.highlight = new PhongMaterial(Color.GOLD) private
Definition at line 41 of file manipulation.java.
manip
CSG com.neuronrobotics.bowlerkernel.Bezier3d.manipulation.manip private
Definition at line 37 of file manipulation.java.
manipulationMatrix
Affine com.neuronrobotics.bowlerkernel.Bezier3d.manipulation.manipulationMatrix private
Definition at line 35 of file manipulation.java.
Referenced by com.neuronrobotics.bowlerkernel.Bezier3d.manipulation.manipulation().
orintation
Vector3d com.neuronrobotics.bowlerkernel.Bezier3d.manipulation.orintation private
Definition at line 36 of file manipulation.java.
saveListeners
ArrayList<Runnable> com.neuronrobotics.bowlerkernel.Bezier3d.manipulation.saveListeners = new ArrayList<>() private
Definition at line 33 of file manipulation.java.
Referenced by com.neuronrobotics.bowlerkernel.Bezier3d.manipulation.addSaveListener(), com.neuronrobotics.bowlerkernel.Bezier3d.manipulation.clearListeners(), and com.neuronrobotics.bowlerkernel.Bezier3d.manipulation.fireSave().
state
DragState com.neuronrobotics.bowlerkernel.Bezier3d.manipulation.state = DragState.IDLE private
Definition at line 47 of file manipulation.java.
ui
IInteractiveUIElementProvider com.neuronrobotics.bowlerkernel.Bezier3d.manipulation.ui static private
Initial value:
= new IInteractiveUIElementProvider() {
    }
Definition at line 29 of file manipulation.java.
Referenced by com.neuronrobotics.bowlerkernel.Bezier3d.manipulation.setUi().
The documentation for this class was generated from the following file:
src/main/java/com/neuronrobotics/bowlerkernel/Bezier3d/manipulation.java