BowlerKernel: com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager Class Reference
com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager Class Reference
Classes
class IMobileBaseUIlocal
Public Member Functions
void addIRenderSynchronizationEvent (IRenderSynchronizationEvent ev)
void removeIRenderSynchronizationEvent (IRenderSynchronizationEvent ev)
int getCADProgressPercent ()
boolean isCADFinished ()
void run ()
IgenerateBed getIgenerateBed () throws Throwable
ArrayList< CSG > generateBody ()
ArrayList< CSG > generateBody (MobileBase base, boolean clear)
File getCadScriptFromLimnb (DHParameterKinematics l)
File getCadScriptFromMobileBase (MobileBase device)
LinkConfiguration getLinkConfiguration (CSG cad)
ArrayList< File > generateStls (MobileBase base, File baseDirForFiles, boolean kinematic) throws Exception
IgenerateBed getPrintBed (File baseDirForFiles, IgenerateBed bed, File baseWorkspaceFile) throws IOException
ArrayList< File > _generateStls (MobileBase base, File baseDirForFiles, boolean kinematic) throws IOException
MobileBase getMobileBase ()
void setMobileBase (MobileBase b)
ArrayList< CSG > generateCad (DHParameterKinematics dh)
void selectCsgByMobileBase (MobileBase base)
void selectCsgByLimb (MobileBase base, DHParameterKinematics limb)
void selectCsgByLink (MobileBase base, LinkConfiguration limb)
void generateCad ()
void onTabClosing ()
void setGitCadEngine (String gitsId, String file, DHParameterKinematics dh) throws InvalidRemoteException, TransportException, GitAPIException, IOException
void setGitCadEngine (String gitsId, String file, MobileBase device) throws InvalidRemoteException, TransportException, GitAPIException, IOException
ArrayList< CSG > getAllCad ()
void setAllCad (ArrayList< CSG > allCad)
DoubleProperty getProcesIndictor ()
void setProcesIndictor (DoubleProperty pi)
HashMap< MobileBase, ArrayList< CSG > > getBasetoCadMap ()
void setBasetoCadMap (HashMap< MobileBase, ArrayList< CSG >> basetoCadMap)
HashMap< DHParameterKinematics, ArrayList< CSG > > getDHtoCadMap ()
void setDHtoCadMap (HashMap< DHParameterKinematics, ArrayList< CSG >> dHtoCadMap)
HashMap< LinkConfiguration, ArrayList< CSG > > getLinktoCadMap ()
void setLinktoCadMap (HashMap< LinkConfiguration, ArrayList< CSG >> linktoCadMap)
boolean getAutoRegen ()
void setAutoRegen (boolean autoRegen)
IMobileBaseUI getUi ()
void setUi (IMobileBaseUI ui)
void setConfigurationViewerMode (boolean b)
void invalidateModelCache ()
Static Public Member Functions
static void runLater (Runnable r)
static MobileBaseCadManager get (MobileBase device, IMobileBaseUI ui)
static MobileBaseCadManager get (MobileBase device)
static HashMap< LinkConfiguration, ArrayList< CSG > > getSimplecad (MobileBase device)
static ArrayList< CSG > getBaseCad (MobileBase device)
Protected Member Functions
void clear ()
Private Member Functions
void fireIRenderSynchronizationEvent ()
void loadJointPose (MobileBase base, HashMap< DHParameterKinematics, double[]> jointPoses)
void updateMobileBase (MobileBase b, TransformNR baseLoc, HashMap< Affine, TransformNR > map2, HashMap< DHParameterKinematics, double[]> jointPoses)
void updateLimb (DHParameterKinematics k, TransformNR baseLoc, HashMap< Affine, TransformNR > map2, HashMap< DHParameterKinematics, double[]> jointPoses)
TransformNR updateBase (MobileBase base, TransformNR baseLoc, HashMap< Affine, TransformNR > map2)
MobileBaseCadManager (MobileBase base, IMobileBaseUI myUI)
Object scriptFromFileInfo (String name, String[] args, Runnable r) throws Throwable
void closeScriptFromFileInfo (String[] args)
IgenerateBody getIgenerateBody (MobileBase b) throws Throwable
IgenerateCad getIgenerateCad (DHParameterKinematics dh) throws Throwable
ICadGenerator getConfigurationDisplay () throws Throwable
void set (MobileBase base, int limb, int link)
void setMaster (MobileBaseCadManager master)
ArrayList< CSG > localGetBaseCad (MobileBase device)
Private Attributes
MobileBase base
ArrayList< MobileBaseCadManager > slaves = new ArrayList<MobileBaseCadManager>()
HashMap< DHParameterKinematics, ArrayList< CSG > > DHtoCadMap = new HashMap<>()
HashMap< LinkConfiguration, ArrayList< CSG > > LinktoCadMap = new HashMap<>()
HashMap< MobileBase, ArrayList< CSG > > BasetoCadMap = new HashMap<>()
boolean cadGenerating = false
boolean showingStl = false
ArrayList< CSG > allCad = new ArrayList<>()
boolean bail = false
IMobileBaseUI ui = null
boolean configMode = false
boolean autoRegen = true
DoubleProperty pi = new SimpleDoubleProperty(0)
MobileBaseCadManager master
Thread renderWrangler = null
HashMap< String, Object > cadScriptCache = new HashMap<>()
ArrayList< IRenderSynchronizationEvent > rendersync =new ArrayList<>()
Static Private Attributes
static HashMap< MobileBase, MobileBaseCadManager > cadmap = new HashMap<>()
static ICadGenerator cadEngineConfiguration = null
static ArrayList< Runnable > toRun = new ArrayList<Runnable>()
Detailed Description
Definition at line 56 of file MobileBaseCadManager.java.
Constructor & Destructor Documentation
MobileBaseCadManager()
com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.MobileBaseCadManager (MobileBase base, IMobileBaseUI myUI) private
Definition at line 449 of file MobileBaseCadManager.java.
References com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.base, com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.setMobileBase(), and com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.setUi().
Referenced by com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.get().
Member Function Documentation
_generateStls()
ArrayList<File> com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager._generateStls (MobileBase base, File baseDirForFiles, boolean kinematic) throws IOException
Definition at line 828 of file MobileBaseCadManager.java.
References com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.base, com.neuronrobotics.sdk.addons.kinematics.MobileBase.getAllDHChains(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getBasetoCadMap(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getCadScriptFromMobileBase(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getDHtoCadMap(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getLinkConfiguration(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getLinkIndex(), eu.mihosoft.vrl.v3d.CSG.getMinY(), eu.mihosoft.vrl.v3d.CSG.getName(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getProcesIndictor(), com.neuronrobotics.sdk.common.BowlerAbstractDevice.getScriptingName(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getUi(), com.neuronrobotics.bowlerstudio.creature.IMobileBaseUI.highlightException(), eu.mihosoft.vrl.v3d.CSG.movey(), eu.mihosoft.vrl.v3d.CSG.prepForManufacturing(), com.neuronrobotics.bowlerstudio.creature.IMobileBaseUI.setAllCSG(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.showingStl, eu.mihosoft.vrl.v3d.CSG.toStlString(), eu.mihosoft.vrl.v3d.CSG.toXMax(), eu.mihosoft.vrl.v3d.CSG.toYMax(), and eu.mihosoft.vrl.v3d.FileUtil.write().
Referenced by com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.generateStls(), and com.neuronrobotics.bowlerstudio.BowlerKernel.processReturnedObjects().
addIRenderSynchronizationEvent()
void com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.addIRenderSynchronizationEvent (IRenderSynchronizationEvent ev)
Definition at line 88 of file MobileBaseCadManager.java.
References com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.rendersync.
clear()
void com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.clear () protected
Definition at line 116 of file MobileBaseCadManager.java.
References com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.allCad, com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.BasetoCadMap, com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.cadScriptCache, com.neuronrobotics.bowlerstudio.vitamins.Vitamins.clear(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.DHtoCadMap, com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.LinktoCadMap, and com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.slaves.
Referenced by com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.generateBody(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.generateCad(), and com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.setMobileBase().
closeScriptFromFileInfo()
void com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.closeScriptFromFileInfo (String[] args) private
Definition at line 525 of file MobileBaseCadManager.java.
References com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.cadScriptCache, com.neuronrobotics.bowlerstudio.util.FileChangeWatcher.close(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.fileFromGit().
Referenced by com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.setGitCadEngine().
fireIRenderSynchronizationEvent()
void com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.fireIRenderSynchronizationEvent () private
Definition at line 97 of file MobileBaseCadManager.java.
References com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.rendersync.
Referenced by com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.run().
generateBody() [1/2]
ArrayList<CSG> com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.generateBody ()
Definition at line 607 of file MobileBaseCadManager.java.
References com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getMobileBase().
Referenced by com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.generateCad(), and com.neuronrobotics.bowlerstudio.BowlerKernel.processReturnedObjects().
generateBody() [2/2]
ArrayList<CSG> com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.generateBody (MobileBase base, boolean clear)
Definition at line 611 of file MobileBaseCadManager.java.
References com.neuronrobotics.bowlerstudio.creature.IMobileBaseUI.addCSG(), com.neuronrobotics.bowlerstudio.creature.IMobileBaseUI.addCsg(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.bail, com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.base, com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.clear(), com.neuronrobotics.bowlerstudio.creature.IgenerateBody.generateBody(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.generateCad(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getAllCad(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.getAllDHChains(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getBasetoCadMap(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getCadScriptFromLimnb(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getCadScriptFromMobileBase(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getConfigurationDisplay(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getDHtoCadMap(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getIgenerateBody(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getProcesIndictor(), com.neuronrobotics.sdk.common.BowlerAbstractDevice.getScriptingName(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getUi(), com.neuronrobotics.bowlerstudio.creature.IMobileBaseUI.highlightException(), com.neuronrobotics.sdk.common.NonBowlerDevice.isAvailable(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.localGetBaseCad(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.setAllCad(), com.neuronrobotics.bowlerstudio.creature.IMobileBaseUI.setAllCSG(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.showingStl, com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.slaves, and com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.ui.
generateCad() [1/2]
void com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.generateCad ()
Definition at line 1103 of file MobileBaseCadManager.java.
References com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.allCad, com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.base, com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.cadGenerating, com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.clear(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.generateBody(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.get(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getAutoRegen(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getCadScriptFromMobileBase(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getProcesIndictor(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getUi(), com.neuronrobotics.bowlerstudio.creature.IMobileBaseUI.highlightException(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.master, com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.run(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.setAllCad(), and com.neuronrobotics.bowlerstudio.creature.IMobileBaseUI.setCsg().
Referenced by com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.generateBody().
generateCad() [2/2]
ArrayList<CSG> com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.generateCad (DHParameterKinematics dh)
This function iterates through the links generating them
Parameters
dh
Returns
Definition at line 992 of file MobileBaseCadManager.java.
References com.neuronrobotics.bowlerstudio.creature.IMobileBaseUI.addCSG(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.addLinkListener(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.bail, com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.base, com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.configMode, com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.generateBody(), com.neuronrobotics.bowlerstudio.creature.IgenerateCad.generateCad(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.getAllDHChains(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getAutoRegen(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getCadScriptFromLimnb(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getConfigurationDisplay(), com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getDhLink(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getFactory(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getIgenerateCad(), com.neuronrobotics.sdk.addons.kinematics.LinkFactory.getLink(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getLinkConfiguration(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getLinktoCadMap(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getMobileBase(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getNumberOfLinks(), com.neuronrobotics.sdk.addons.kinematics.DHLink.getSlaveMobileBase(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getUi(), com.neuronrobotics.bowlerstudio.creature.IMobileBaseUI.highlightException(), and com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.selectCsgByLimb().
Referenced by com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getConfigurationDisplay().
generateStls()
ArrayList<File> com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.generateStls (MobileBase base, File baseDirForFiles, boolean kinematic) throws Exception
Definition at line 779 of file MobileBaseCadManager.java.
References com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager._generateStls(), com.neuronrobotics.bowlerstudio.creature.IgenerateBed.arrangeBed(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.base, com.neuronrobotics.bowlerstudio.creature.CadFileExporter.generateManufacturingParts(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getCadScriptFromMobileBase(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.getGitSelfSource(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getPrintBed(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getRepositoryCloneDirectory(), com.neuronrobotics.sdk.common.BowlerAbstractDevice.getScriptingName(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getUi(), and com.neuronrobotics.bowlerstudio.creature.IMobileBaseUI.setAllCSG().
get() [1/2]
static MobileBaseCadManager com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.get (MobileBase device) static
Definition at line 1204 of file MobileBaseCadManager.java.
References com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.cadmap.
get() [2/2]
static MobileBaseCadManager com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.get (MobileBase device, IMobileBaseUI ui) static
Definition at line 1185 of file MobileBaseCadManager.java.
References com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.cadmap, com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getUi(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.MobileBaseCadManager(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.setUi(), and com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.ui.
Referenced by com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.generateCad(), com.neuronrobotics.bowlerstudio.BowlerKernel.processReturnedObjects(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.selectCsgByLink(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.selectCsgByMobileBase(), com.neuronrobotics.bowlerstudio.creature.MobileBaseLoader.setDefaultDhParameterKinematics(), and com.neuronrobotics.bowlerstudio.creature.MobileBaseLoader.setGitWalkingEngine().
getAllCad()
ArrayList<CSG> com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getAllCad ()
Definition at line 1168 of file MobileBaseCadManager.java.
References com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.allCad.
Referenced by com.neuronrobotics.bowlerstudio.creature.UserManagedPrintBed.arrangeBed(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.generateBody(), and com.neuronrobotics.bowlerstudio.creature.IMobileBaseUI.setCsg().
getAutoRegen()
boolean com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getAutoRegen ()
Definition at line 1283 of file MobileBaseCadManager.java.
References com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.autoRegen.
Referenced by com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.generateCad().
getBaseCad()
static ArrayList<CSG> com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getBaseCad (MobileBase device) static
Definition at line 1247 of file MobileBaseCadManager.java.
References com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.localGetBaseCad().
Referenced by com.neuronrobotics.bowlerstudio.physics.MobileBasePhysicsManager.MobileBasePhysicsManager().
getBasetoCadMap()
HashMap<MobileBase, ArrayList<CSG> > com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getBasetoCadMap ()
Definition at line 1259 of file MobileBaseCadManager.java.
References com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.BasetoCadMap.
Referenced by com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager._generateStls(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.generateBody(), and com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.selectCsgByMobileBase().
getCADProgressPercent()
int com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getCADProgressPercent ()
get the progress of the cad in an integer percent
Returns
percent completion of CAD
Definition at line 109 of file MobileBaseCadManager.java.
References com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getProcesIndictor().
Referenced by com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.isCADFinished().
getCadScriptFromLimnb()
File com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getCadScriptFromLimnb (DHParameterKinematics l)
Definition at line 733 of file MobileBaseCadManager.java.
References com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.fileFromGit(), and com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getGitCadEngine().
Referenced by com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.generateBody(), and com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.generateCad().
getCadScriptFromMobileBase()
File com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getCadScriptFromMobileBase (MobileBase device)
Definition at line 743 of file MobileBaseCadManager.java.
References com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.fileFromGit(), and com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getGitCadEngine().
Referenced by com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager._generateStls(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.generateBody(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.generateCad(), and com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.generateStls().
getConfigurationDisplay()
ICadGenerator com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getConfigurationDisplay () throws Throwable private
Definition at line 584 of file MobileBaseCadManager.java.
References com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.autoRegen, com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.cadEngineConfiguration, com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.cadmap, com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.configMode, com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.generateCad(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getUi(), com.neuronrobotics.bowlerstudio.creature.IMobileBaseUI.highlightException(), and com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.scriptFromFileInfo().
Referenced by com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.generateBody(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.generateCad(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getIgenerateBody(), and com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getIgenerateCad().
getDHtoCadMap()
HashMap<DHParameterKinematics, ArrayList<CSG> > com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getDHtoCadMap ()
Definition at line 1267 of file MobileBaseCadManager.java.
References com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.DHtoCadMap.
Referenced by com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager._generateStls(), and com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.generateBody().
getIgenerateBed()
IgenerateBed com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getIgenerateBed () throws Throwable
Definition at line 574 of file MobileBaseCadManager.java.
References com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.base, com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getGitCadEngine(), com.neuronrobotics.sdk.common.BowlerAbstractDevice.getScriptingName(), and com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.scriptFromFileInfo().
Referenced by com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getPrintBed(), and com.neuronrobotics.bowlerstudio.BowlerKernel.processReturnedObjects().
getIgenerateBody()
IgenerateBody com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getIgenerateBody (MobileBase b) throws Throwable private
Definition at line 548 of file MobileBaseCadManager.java.
References com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.configMode, com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getConfigurationDisplay(), and com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.scriptFromFileInfo().
Referenced by com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.generateBody().
getIgenerateCad()
IgenerateCad com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getIgenerateCad (DHParameterKinematics dh) throws Throwable private
Definition at line 561 of file MobileBaseCadManager.java.
References com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.configMode, com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getConfigurationDisplay(), and com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.scriptFromFileInfo().
Referenced by com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.generateCad().
getLinkConfiguration()
LinkConfiguration com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getLinkConfiguration (CSG cad)
Definition at line 767 of file MobileBaseCadManager.java.
References com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.LinktoCadMap.
Referenced by com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager._generateStls().
getLinktoCadMap()
HashMap<LinkConfiguration, ArrayList<CSG> > com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getLinktoCadMap ()
Definition at line 1275 of file MobileBaseCadManager.java.
References com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.LinktoCadMap.
Referenced by com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.generateCad(), and com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.selectCsgByLink().
getMobileBase()
MobileBase com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getMobileBase ()
Definition at line 931 of file MobileBaseCadManager.java.
References com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.base.
Referenced by com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.generateBody(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.generateCad(), and com.neuronrobotics.bowlerstudio.creature.UserManagedPrintBed.UserManagedPrintBed().
getPrintBed()
IgenerateBed com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getPrintBed (File baseDirForFiles, IgenerateBed bed, File baseWorkspaceFile) throws IOException
Definition at line 798 of file MobileBaseCadManager.java.
References com.neuronrobotics.bowlerstudio.printbed.PrintBedManager.file, com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getIgenerateBed(), com.neuronrobotics.bowlerstudio.vitamins.VitaminBomManager.MANUFACTURING_BOM_CSV, and com.neuronrobotics.bowlerstudio.vitamins.VitaminBomManager.MANUFACTURING_BOM_JSON.
Referenced by com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.generateStls(), and com.neuronrobotics.bowlerstudio.BowlerKernel.processReturnedObjects().
getProcesIndictor()
DoubleProperty com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getProcesIndictor ()
Definition at line 1251 of file MobileBaseCadManager.java.
References com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.pi.
Referenced by com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager._generateStls(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.generateBody(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.generateCad(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getCADProgressPercent(), and com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.set().
getSimplecad()
static HashMap<LinkConfiguration, ArrayList<CSG> > com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getSimplecad (MobileBase device) static
Definition at line 1238 of file MobileBaseCadManager.java.
References com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.LinktoCadMap.
getUi()
IMobileBaseUI com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getUi ()
Definition at line 1294 of file MobileBaseCadManager.java.
References com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.ui.
Referenced by com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager._generateStls(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.generateBody(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.generateCad(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.generateStls(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.get(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getConfigurationDisplay(), com.neuronrobotics.bowlerstudio.BowlerKernel.processReturnedObjects(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.run(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.scriptFromFileInfo(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.selectCsgByLimb(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.selectCsgByLink(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.selectCsgByMobileBase(), com.neuronrobotics.bowlerstudio.creature.MobileBaseLoader.setDefaultDhParameterKinematics(), and com.neuronrobotics.bowlerstudio.creature.MobileBaseLoader.setGitWalkingEngine().
invalidateModelCache()
void com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.invalidateModelCache ()
Definition at line 1309 of file MobileBaseCadManager.java.
isCADFinished()
boolean com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.isCADFinished ()
Definition at line 113 of file MobileBaseCadManager.java.
References com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getCADProgressPercent().
loadJointPose()
void com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.loadJointPose (MobileBase base, HashMap< DHParameterKinematics, double[]> jointPoses) private
Definition at line 358 of file MobileBaseCadManager.java.
References com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.base, and com.neuronrobotics.sdk.addons.kinematics.MobileBase.getAllDHChains().
Referenced by com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.run().
localGetBaseCad()
ArrayList<CSG> com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.localGetBaseCad (MobileBase device) private
Definition at line 1242 of file MobileBaseCadManager.java.
References com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.BasetoCadMap.
Referenced by com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.generateBody(), and com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getBaseCad().
onTabClosing()
void com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.onTabClosing ()
Definition at line 1152 of file MobileBaseCadManager.java.
removeIRenderSynchronizationEvent()
void com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.removeIRenderSynchronizationEvent (IRenderSynchronizationEvent ev)
Definition at line 93 of file MobileBaseCadManager.java.
References com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.rendersync.
run()
void com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.run ()
Definition at line 199 of file MobileBaseCadManager.java.
References com.neuronrobotics.sdk.addons.kinematics.MobileBase.addIOnMobileBaseRenderChange(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.addRegistrationListener(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.base, com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.fireIRenderSynchronizationEvent(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.getAllDHChains(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getFiducialToGlobalTransform(), com.neuronrobotics.sdk.common.BowlerAbstractDevice.getScriptingName(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getUi(), com.neuronrobotics.bowlerstudio.creature.IMobileBaseUI.highlightException(), com.neuronrobotics.sdk.common.NonBowlerDevice.isAvailable(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.loadJointPose(), com.neuronrobotics.bowlerstudio.physics.TransformFactory.nrToAffine(), com.neuronrobotics.sdk.addons.kinematics.IOnMobileBaseRenderChange.onIOnMobileBaseRenderChange(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.renderWrangler, com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.toRun, and com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.updateMobileBase().
Referenced by com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.generateCad(), and com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.setMobileBase().
runLater()
static void com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.runLater (Runnable r) static
Definition at line 192 of file MobileBaseCadManager.java.
References com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.toRun.
scriptFromFileInfo()
Object com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.scriptFromFileInfo (String name, String[] args, Runnable r) throws Throwable private
Definition at line 465 of file MobileBaseCadManager.java.
References com.neuronrobotics.sdk.common.BowlerAbstractDevice.addConnectionEventListener(), com.neuronrobotics.bowlerstudio.util.FileChangeWatcher.addIFileChangeListener(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.base, com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.cadGenerating, com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.cadScriptCache, com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.fileFromGit(), com.neuronrobotics.sdk.common.BowlerAbstractDevice.getScriptingName(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getUi(), com.neuronrobotics.bowlerstudio.creature.IMobileBaseUI.highlightException(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.inlineFileScriptRun(), com.neuronrobotics.bowlerstudio.util.FileChangeWatcher.removeIFileChangeListener(), and com.neuronrobotics.bowlerstudio.util.FileChangeWatcher.watch().
Referenced by com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getConfigurationDisplay(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getIgenerateBed(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getIgenerateBody(), and com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getIgenerateCad().
selectCsgByLimb()
void com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.selectCsgByLimb (MobileBase base, DHParameterKinematics limb)
Definition at line 1081 of file MobileBaseCadManager.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getRootListener(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getUi(), and com.neuronrobotics.bowlerstudio.creature.IMobileBaseUI.setSelected().
Referenced by com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.generateCad().
selectCsgByLink()
void com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.selectCsgByLink (MobileBase base, LinkConfiguration limb)
Definition at line 1093 of file MobileBaseCadManager.java.
References com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.base, com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.get(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getLinktoCadMap(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getUi(), and com.neuronrobotics.bowlerstudio.creature.IMobileBaseUI.setSelectedCsg().
selectCsgByMobileBase()
void com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.selectCsgByMobileBase (MobileBase base)
Definition at line 1069 of file MobileBaseCadManager.java.
References com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.base, com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.get(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getBasetoCadMap(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getUi(), and com.neuronrobotics.bowlerstudio.creature.IMobileBaseUI.setSelectedCsg().
set()
void com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.set (MobileBase base, int limb, int link) private
Definition at line 753 of file MobileBaseCadManager.java.
References com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.base, com.neuronrobotics.sdk.addons.kinematics.MobileBase.getAllDHChains(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getNumberOfLinks(), and com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getProcesIndictor().
setAllCad()
void com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.setAllCad (ArrayList< CSG > allCad)
Definition at line 1172 of file MobileBaseCadManager.java.
References eu.mihosoft.vrl.v3d.parametrics.CSGDatabase.addParameterListener(), and com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.allCad.
Referenced by com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.generateBody(), and com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.generateCad().
setAutoRegen()
void com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.setAutoRegen (boolean autoRegen)
Definition at line 1287 of file MobileBaseCadManager.java.
References com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.autoRegen, and com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.slaves.
setBasetoCadMap()
void com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.setBasetoCadMap (HashMap< MobileBase, ArrayList< CSG >> basetoCadMap)
Definition at line 1263 of file MobileBaseCadManager.java.
References com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.BasetoCadMap.
setConfigurationViewerMode()
void com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.setConfigurationViewerMode (boolean b)
Definition at line 1302 of file MobileBaseCadManager.java.
References com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.configMode, and com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.slaves.
Referenced by com.neuronrobotics.bowlerstudio.BowlerKernel.processReturnedObjects().
setDHtoCadMap()
void com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.setDHtoCadMap (HashMap< DHParameterKinematics, ArrayList< CSG >> dHtoCadMap)
Definition at line 1271 of file MobileBaseCadManager.java.
References com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.DHtoCadMap.
setGitCadEngine() [1/2]
void com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.setGitCadEngine (String gitsId, String file, DHParameterKinematics dh) throws InvalidRemoteException, TransportException, GitAPIException, IOException
Definition at line 1156 of file MobileBaseCadManager.java.
References com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.closeScriptFromFileInfo().
setGitCadEngine() [2/2]
void com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.setGitCadEngine (String gitsId, String file, MobileBase device) throws InvalidRemoteException, TransportException, GitAPIException, IOException
Definition at line 1162 of file MobileBaseCadManager.java.
References com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.closeScriptFromFileInfo().
setLinktoCadMap()
void com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.setLinktoCadMap (HashMap< LinkConfiguration, ArrayList< CSG >> linktoCadMap)
Definition at line 1279 of file MobileBaseCadManager.java.
References com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.LinktoCadMap.
setMaster()
void com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.setMaster (MobileBaseCadManager master) private
Definition at line 1200 of file MobileBaseCadManager.java.
References com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.master.
setMobileBase()
void com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.setMobileBase (MobileBase b)
Definition at line 935 of file MobileBaseCadManager.java.
References com.neuronrobotics.sdk.common.BowlerAbstractDevice.addConnectionEventListener(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.bail, com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.base, com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.cadmap, com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.clear(), com.neuronrobotics.bowlerstudio.creature.MobileBaseLoader.get(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.getAllDHChains(), com.neuronrobotics.sdk.common.BowlerAbstractDevice.getScriptingName(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.master, com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.run(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.setRenderWrangler(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.slaves, and com.neuronrobotics.sdk.addons.kinematics.MobileBase.updatePositions().
Referenced by com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.MobileBaseCadManager().
setProcesIndictor()
void com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.setProcesIndictor (DoubleProperty pi)
Definition at line 1255 of file MobileBaseCadManager.java.
References com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.pi.
setUi()
void com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.setUi (IMobileBaseUI ui)
Definition at line 1298 of file MobileBaseCadManager.java.
References com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.ui.
Referenced by com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.get(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.MobileBaseCadManager(), and com.neuronrobotics.bowlerstudio.BowlerKernel.processReturnedObjects().
updateBase()
TransformNR com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.updateBase (MobileBase base, TransformNR baseLoc, HashMap< Affine, TransformNR > map2) private
Definition at line 419 of file MobileBaseCadManager.java.
References com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.base, com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.forwardOffset(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.getAllDHChains(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getFiducialToGlobalTransform(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getRootListener(), com.neuronrobotics.sdk.common.BowlerAbstractDevice.getScriptingName(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.setGlobalToFiducialTransform(), and com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.setRootListener().
Referenced by com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.updateMobileBase().
updateLimb()
void com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.updateLimb (DHParameterKinematics k, TransformNR baseLoc, HashMap< Affine, TransformNR > map2, HashMap< DHParameterKinematics, double[]> jointPoses) private
Definition at line 383 of file MobileBaseCadManager.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getAbstractLink(), com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getChain(), com.neuronrobotics.sdk.addons.kinematics.DHChain.getChain(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getFiducialToGlobalTransform(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getGlobalPositionListener(), com.neuronrobotics.sdk.addons.kinematics.DHChain.getLinks(), com.neuronrobotics.sdk.addons.kinematics.DHLink.getListener(), com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getSlaveMobileBase(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setGlobalPositionListener(), com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.setGlobalToFiducialTransform(), com.neuronrobotics.sdk.addons.kinematics.DHLink.setListener(), and com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.updateMobileBase().
Referenced by com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.updateMobileBase().
updateMobileBase()
void com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.updateMobileBase (MobileBase b, TransformNR baseLoc, HashMap< Affine, TransformNR > map2, HashMap< DHParameterKinematics, double[]> jointPoses) private
Definition at line 374 of file MobileBaseCadManager.java.
References com.neuronrobotics.sdk.addons.kinematics.MobileBase.getAllDHChains(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.updateBase(), and com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.updateLimb().
Referenced by com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.run(), and com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.updateLimb().
Member Data Documentation
allCad
ArrayList<CSG> com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.allCad = new ArrayList<>() private
Definition at line 73 of file MobileBaseCadManager.java.
Referenced by com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.clear(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.generateCad(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getAllCad(), and com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.setAllCad().
autoRegen
boolean com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.autoRegen = true private
Definition at line 79 of file MobileBaseCadManager.java.
Referenced by com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getAutoRegen(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getConfigurationDisplay(), and com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.setAutoRegen().
bail
boolean com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.bail = false private
Definition at line 75 of file MobileBaseCadManager.java.
Referenced by com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.generateBody(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.generateCad(), and com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.setMobileBase().
base
MobileBase com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.base private
Definition at line 62 of file MobileBaseCadManager.java.
Referenced by com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager._generateStls(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.generateBody(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.generateCad(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.generateStls(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getIgenerateBed(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getMobileBase(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.loadJointPose(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.MobileBaseCadManager(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.run(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.scriptFromFileInfo(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.selectCsgByLink(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.selectCsgByMobileBase(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.set(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.setMobileBase(), and com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.updateBase().
BasetoCadMap
HashMap<MobileBase, ArrayList<CSG> > com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.BasetoCadMap = new HashMap<>() private
Definition at line 69 of file MobileBaseCadManager.java.
Referenced by com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.clear(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getBasetoCadMap(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.localGetBaseCad(), and com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.setBasetoCadMap().
cadEngineConfiguration
ICadGenerator com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.cadEngineConfiguration = null static private
Definition at line 77 of file MobileBaseCadManager.java.
Referenced by com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getConfigurationDisplay().
cadGenerating
boolean com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.cadGenerating = false private
Definition at line 71 of file MobileBaseCadManager.java.
Referenced by com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.generateCad(), and com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.scriptFromFileInfo().
cadmap
HashMap<MobileBase, MobileBaseCadManager> com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.cadmap = new HashMap<>() static private
Definition at line 59 of file MobileBaseCadManager.java.
Referenced by com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.get(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getConfigurationDisplay(), and com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.setMobileBase().
cadScriptCache
HashMap<String, Object> com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.cadScriptCache = new HashMap<>() private
Definition at line 84 of file MobileBaseCadManager.java.
Referenced by com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.clear(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.closeScriptFromFileInfo(), and com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.scriptFromFileInfo().
configMode
boolean com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.configMode = false private
Definition at line 78 of file MobileBaseCadManager.java.
Referenced by com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.generateCad(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getConfigurationDisplay(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getIgenerateBody(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getIgenerateCad(), and com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.setConfigurationViewerMode().
DHtoCadMap
HashMap<DHParameterKinematics, ArrayList<CSG> > com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.DHtoCadMap = new HashMap<>() private
Definition at line 67 of file MobileBaseCadManager.java.
Referenced by com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.clear(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getDHtoCadMap(), and com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.setDHtoCadMap().
LinktoCadMap
HashMap<LinkConfiguration, ArrayList<CSG> > com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.LinktoCadMap = new HashMap<>() private
Definition at line 68 of file MobileBaseCadManager.java.
Referenced by com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.clear(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getLinkConfiguration(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getLinktoCadMap(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getSimplecad(), and com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.setLinktoCadMap().
master
MobileBaseCadManager com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.master private
Definition at line 81 of file MobileBaseCadManager.java.
Referenced by com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.generateCad(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.setMaster(), and com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.setMobileBase().
pi
DoubleProperty com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.pi = new SimpleDoubleProperty(0) private
Definition at line 80 of file MobileBaseCadManager.java.
Referenced by com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getProcesIndictor(), and com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.setProcesIndictor().
rendersync
ArrayList<IRenderSynchronizationEvent> com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.rendersync =new ArrayList<>() private
Definition at line 86 of file MobileBaseCadManager.java.
Referenced by com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.addIRenderSynchronizationEvent(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.fireIRenderSynchronizationEvent(), and com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.removeIRenderSynchronizationEvent().
renderWrangler
Thread com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.renderWrangler = null private
Definition at line 83 of file MobileBaseCadManager.java.
Referenced by com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.run().
showingStl
boolean com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.showingStl = false private
Definition at line 72 of file MobileBaseCadManager.java.
Referenced by com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager._generateStls(), and com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.generateBody().
slaves
ArrayList<MobileBaseCadManager> com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.slaves = new ArrayList<MobileBaseCadManager>() private
Definition at line 63 of file MobileBaseCadManager.java.
Referenced by com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.clear(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.generateBody(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.setAutoRegen(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.setConfigurationViewerMode(), and com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.setMobileBase().
toRun
ArrayList<Runnable> com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.toRun = new ArrayList<Runnable>() static private
Definition at line 85 of file MobileBaseCadManager.java.
Referenced by com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.run(), and com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.runLater().
ui
IMobileBaseUI com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.ui = null private
Definition at line 76 of file MobileBaseCadManager.java.
Referenced by com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.generateBody(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.get(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getUi(), and com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.setUi().
The documentation for this class was generated from the following file:
src/main/java/com/neuronrobotics/bowlerstudio/creature/MobileBaseCadManager.java