BowlerKernel: com.piro.bezier.BezierHistory Class Reference
com.piro.bezier.BezierHistory Class Reference
Public Member Functions
BezierHistory ()
void setStartPoint (float x, float y)
void setLastPoint (float x, float y)
void setLastKnot (float x, float y)
Detailed Description
Definition at line 5 of file BezierHistory.java.
Constructor & Destructor Documentation
BezierHistory()
com.piro.bezier.BezierHistory.BezierHistory ()
Definition at line 12 of file BezierHistory.java.
Member Function Documentation
setLastKnot()
void com.piro.bezier.BezierHistory.setLastKnot (float x, float y)
Definition at line 26 of file BezierHistory.java.
References com.piro.bezier.Vector2.set().
Referenced by com.piro.bezier.BezierListProducer.curvetoCubicAbs(), com.piro.bezier.BezierListProducer.curvetoCubicSmoothAbs(), com.piro.bezier.BezierListProducer.curvetoQuadraticAbs(), com.piro.bezier.BezierListProducer.endPath(), and com.piro.bezier.BezierListProducer.linetoAbs().
setLastPoint()
void com.piro.bezier.BezierHistory.setLastPoint (float x, float y)
Definition at line 21 of file BezierHistory.java.
References com.piro.bezier.Vector2.set().
Referenced by com.piro.bezier.BezierListProducer.curvetoCubicAbs(), com.piro.bezier.BezierListProducer.curvetoCubicSmoothAbs(), com.piro.bezier.BezierListProducer.curvetoQuadraticAbs(), com.piro.bezier.BezierListProducer.endPath(), com.piro.bezier.BezierListProducer.linetoAbs(), and com.piro.bezier.BezierListProducer.movetoAbs().
setStartPoint()
void com.piro.bezier.BezierHistory.setStartPoint (float x, float y)
Definition at line 16 of file BezierHistory.java.
References com.piro.bezier.Vector2.set().
The documentation for this class was generated from the following file:
JCSG/src/main/java/com/piro/bezier/BezierHistory.java