BowlerKernel: eu.mihosoft.vrl.v3d.ext.imagej.STLLoader Class Reference
eu.mihosoft.vrl.v3d.ext.imagej.STLLoader Class Reference
Public Member Functions
STLLoader ()
ArrayList< Point3f > parse (File f) throws IOException
Private Member Functions
void parseAscii (File f)
void parseBinary (File f)
float parseFloat (String string) throws ParseException
float leBytesToFloat (byte b0, byte b1, byte b2, byte b3)
Private Attributes
ArrayList< Point3f > vertices = new ArrayList<>()
Point3f normal = new Point3f(0.0f, 0.0f, 0.0f)
FileInputStream fis
int triangles
Detailed Description
The Class STLLoader.
Definition at line 28 of file STLLoader.java.
Constructor & Destructor Documentation
STLLoader()
eu.mihosoft.vrl.v3d.ext.imagej.STLLoader.STLLoader ()
Instantiates a new STL loader.
Definition at line 50 of file STLLoader.java.
Member Function Documentation
leBytesToFloat()
float eu.mihosoft.vrl.v3d.ext.imagej.STLLoader.leBytesToFloat (byte b0, byte b1, byte b2, byte b3) private
Le bytes to float.
Parameters
b0 the b0
b1 the b1
b2 the b2
b3 the b3
Returns
the float
Definition at line 222 of file STLLoader.java.
Referenced by eu.mihosoft.vrl.v3d.ext.imagej.STLLoader.parseBinary().
parse()
ArrayList<Point3f> eu.mihosoft.vrl.v3d.ext.imagej.STLLoader.parse (File f) throws IOException
Parses the.
Parameters
f the f
Returns
the array list
Exceptions
IOException Signals that an I/O exception has occurred.
Definition at line 82 of file STLLoader.java.
References eu.mihosoft.vrl.v3d.ext.imagej.STLLoader.parseAscii(), eu.mihosoft.vrl.v3d.ext.imagej.STLLoader.parseBinary(), eu.mihosoft.vrl.v3d.ext.imagej.STLLoader.triangles, and eu.mihosoft.vrl.v3d.ext.imagej.STLLoader.vertices.
Referenced by eu.mihosoft.vrl.v3d.STL.file().
parseAscii()
void eu.mihosoft.vrl.v3d.ext.imagej.STLLoader.parseAscii (File f) private
Parses the ascii.
Parameters
f the f
Definition at line 123 of file STLLoader.java.
References eu.mihosoft.vrl.v3d.ext.imagej.STLLoader.normal, eu.mihosoft.vrl.v3d.ext.imagej.STLLoader.parseFloat(), and eu.mihosoft.vrl.v3d.ext.imagej.STLLoader.vertices.
Referenced by eu.mihosoft.vrl.v3d.ext.imagej.STLLoader.parse().
parseBinary()
void eu.mihosoft.vrl.v3d.ext.imagej.STLLoader.parseBinary (File f) private
Parses the binary.
Parameters
f the f
Definition at line 158 of file STLLoader.java.
References eu.mihosoft.vrl.v3d.ext.imagej.STLLoader.fis, eu.mihosoft.vrl.v3d.ext.imagej.STLLoader.leBytesToFloat(), eu.mihosoft.vrl.v3d.ext.imagej.STLLoader.normal, eu.mihosoft.vrl.v3d.ext.imagej.STLLoader.triangles, and eu.mihosoft.vrl.v3d.ext.imagej.STLLoader.vertices.
Referenced by eu.mihosoft.vrl.v3d.ext.imagej.STLLoader.parse().
parseFloat()
float eu.mihosoft.vrl.v3d.ext.imagej.STLLoader.parseFloat (String string) throws ParseException private
Parses the float.
Parameters
string the string
Returns
the float
Exceptions
ParseException the parse exception
Definition at line 208 of file STLLoader.java.
Referenced by eu.mihosoft.vrl.v3d.ext.imagej.STLLoader.parseAscii().
Member Data Documentation
fis
FileInputStream eu.mihosoft.vrl.v3d.ext.imagej.STLLoader.fis private
The fis.
Definition at line 67 of file STLLoader.java.
Referenced by eu.mihosoft.vrl.v3d.ext.imagej.STLLoader.parseBinary().
normal
Point3f eu.mihosoft.vrl.v3d.ext.imagej.STLLoader.normal = new Point3f(0.0f, 0.0f, 0.0f) private
The normal.
Definition at line 64 of file STLLoader.java.
Referenced by eu.mihosoft.vrl.v3d.ext.imagej.STLLoader.parseAscii(), and eu.mihosoft.vrl.v3d.ext.imagej.STLLoader.parseBinary().
triangles
int eu.mihosoft.vrl.v3d.ext.imagej.STLLoader.triangles private
The triangles.
Definition at line 70 of file STLLoader.java.
Referenced by eu.mihosoft.vrl.v3d.ext.imagej.STLLoader.parse(), and eu.mihosoft.vrl.v3d.ext.imagej.STLLoader.parseBinary().
vertices
ArrayList<Point3f> eu.mihosoft.vrl.v3d.ext.imagej.STLLoader.vertices = new ArrayList<>() private
The vertices.
Definition at line 61 of file STLLoader.java.
Referenced by eu.mihosoft.vrl.v3d.ext.imagej.STLLoader.parse(), eu.mihosoft.vrl.v3d.ext.imagej.STLLoader.parseAscii(), and eu.mihosoft.vrl.v3d.ext.imagej.STLLoader.parseBinary().
The documentation for this class was generated from the following file:
JCSG/src/main/java/eu/mihosoft/vrl/v3d/ext/imagej/STLLoader.java