BowlerKernel: com.neuronrobotics.sdk.dyio.peripherals.UARTChannel.UARTRxChannel Class Reference
com.neuronrobotics.sdk.dyio.peripherals.UARTChannel.UARTRxChannel Class Reference
Public Member Functions
UARTRxChannel (DyIOChannel channel)
void onChannelEvent (DyIOChannelEvent e)
int getInStreamSize ()
byte[] getBytes (int inStreamSize)
DyIOInputStream getInputStream ()
boolean hasAsync ()
Public Member Functions inherited from com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral
DyIOAbstractPeripheral (DyIOChannel channel, DyIOChannelMode myMode, boolean async)
DyIOChannelMode getClassMode ()
boolean isEnabled ()
boolean setMode ()
boolean setMode (boolean async)
boolean setMode (DyIOChannelMode mode, boolean async)
DyIOChannel getChannel ()
DyIOChannelMode getMode ()
boolean setValue (int value) throws InvalidResponseException
boolean setValue (ByteList value) throws InvalidResponseException
int getValue () throws InvalidResponseException
boolean SavePosition (int pos)
boolean configAdvancedAsyncNotEqual ()
boolean configAdvancedAsyncDeadBand (int deadbandSize)
boolean configAdvancedAsyncTreshhold (int threshholdValue, AsyncThreshholdEdgeType edgeType)
boolean configAdvancedAsyncAutoSample ()
boolean configAdvancedAsyncNotEqual (int msTime)
boolean configAdvancedAsyncDeadBand (int msTime, int deadbandSize)
boolean configAdvancedAsyncTreshhold (int msTime, int threshholdValue, AsyncThreshholdEdgeType edgeType)
boolean configAdvancedAsyncAutoSample (int msTime)
boolean flush ()
void setAsync (boolean b)
int getConfiguration ()
Detailed Description
The Class UARTRxChannel.
Definition at line 284 of file UARTChannel.java.
Constructor & Destructor Documentation
UARTRxChannel()
com.neuronrobotics.sdk.dyio.peripherals.UARTChannel.UARTRxChannel.UARTRxChannel (DyIOChannel channel)
Instantiates a new UART rx channel.
Parameters
channel the channel
Definition at line 294 of file UARTChannel.java.
References com.neuronrobotics.sdk.dyio.DyIOChannel.addChannelEventListener(), and com.neuronrobotics.sdk.dyio.DyIOChannelMode.USART_RX.
Member Function Documentation
getBytes()
byte [] com.neuronrobotics.sdk.dyio.peripherals.UARTChannel.UARTRxChannel.getBytes (int inStreamSize)
Gets the bytes.
Parameters
inStreamSize the in stream size
Returns
the bytes
Definition at line 327 of file UARTChannel.java.
References com.neuronrobotics.sdk.dyio.DyIOInputStream.read().
Referenced by com.neuronrobotics.sdk.dyio.peripherals.UARTChannel.getBytes().
getInputStream()
DyIOInputStream com.neuronrobotics.sdk.dyio.peripherals.UARTChannel.UARTRxChannel.getInputStream ()
Gets the input stream.
Returns
the input stream
Definition at line 348 of file UARTChannel.java.
getInStreamSize()
int com.neuronrobotics.sdk.dyio.peripherals.UARTChannel.UARTRxChannel.getInStreamSize ()
Gets the in stream size.
Returns
the in stream size
Definition at line 317 of file UARTChannel.java.
References com.neuronrobotics.sdk.dyio.DyIOInputStream.available().
Referenced by com.neuronrobotics.sdk.dyio.peripherals.UARTChannel.getBytes(), and com.neuronrobotics.sdk.dyio.peripherals.UARTChannel.getInStreamSize().
hasAsync()
boolean com.neuronrobotics.sdk.dyio.peripherals.UARTChannel.UARTRxChannel.hasAsync ()
This method is to check if this peripheral is capable to be set as up as asynchronous.
Returns
if it cna be async
Reimplemented from com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral.
Definition at line 356 of file UARTChannel.java.
onChannelEvent()
void com.neuronrobotics.sdk.dyio.peripherals.UARTChannel.UARTRxChannel.onChannelEvent (DyIOChannelEvent e)
On channel event.
Parameters
e the e
Implements com.neuronrobotics.sdk.dyio.IChannelEventListener.
Definition at line 307 of file UARTChannel.java.
References com.neuronrobotics.sdk.dyio.DyIOChannelEvent.getData(), and com.neuronrobotics.sdk.dyio.DyIOInputStream.write().
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/dyio/peripherals/UARTChannel.java