BowlerKernel: com.neuronrobotics.sdk.dyio.peripherals.ServoChannel Class Reference
com.neuronrobotics.sdk.dyio.peripherals.ServoChannel Class Reference
Classes
class powerOverridePacket
Public Member Functions
ServoChannel (int channel)
ServoChannel (DyIO dyio, int channel)
ServoChannel (DyIOChannel channel)
boolean SetPosition (int pos)
boolean SetPosition (int pos, double time)
boolean SetPosition (int pos, float time)
boolean hasAsync ()
void addIServoPositionUpdateListener (IServoPositionUpdateListener l)
void removeIServoPositionUpdateListener (IServoPositionUpdateListener l)
void enablePowerOverride ()
void disablePowerOverride ()
void onChannelEvent (DyIOChannelEvent e)
Public Member Functions inherited from com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral
DyIOAbstractPeripheral (DyIOChannel channel, DyIOChannelMode myMode, boolean async)
DyIOChannelMode getClassMode ()
boolean isEnabled ()
boolean setMode ()
boolean setMode (boolean async)
boolean setMode (DyIOChannelMode mode, boolean async)
DyIOChannel getChannel ()
DyIOChannelMode getMode ()
boolean setValue (int value) throws InvalidResponseException
boolean setValue (ByteList value) throws InvalidResponseException
int getValue () throws InvalidResponseException
boolean SavePosition (int pos)
boolean configAdvancedAsyncNotEqual ()
boolean configAdvancedAsyncDeadBand (int deadbandSize)
boolean configAdvancedAsyncTreshhold (int threshholdValue, AsyncThreshholdEdgeType edgeType)
boolean configAdvancedAsyncAutoSample ()
boolean configAdvancedAsyncNotEqual (int msTime)
boolean configAdvancedAsyncDeadBand (int msTime, int deadbandSize)
boolean configAdvancedAsyncTreshhold (int msTime, int threshholdValue, AsyncThreshholdEdgeType edgeType)
boolean configAdvancedAsyncAutoSample (int msTime)
boolean flush ()
void setAsync (boolean b)
int getConfiguration ()
Private Member Functions
boolean validate ()
void firePositionUpdate (int pos, double time)
Private Attributes
ArrayList< IServoPositionUpdateListener > listeners = new ArrayList<IServoPositionUpdateListener >()
Detailed Description
The Class ServoChannel.
Definition at line 32 of file ServoChannel.java.
Constructor & Destructor Documentation
ServoChannel() [1/3]
com.neuronrobotics.sdk.dyio.peripherals.ServoChannel.ServoChannel (int channel)
Constructor. Creates an counter input input channel that is syncronous only by default.
Parameters
channel - the channel object requested from the DyIO
Definition at line 43 of file ServoChannel.java.
References com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral.channel, com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral.getChannel(), and com.neuronrobotics.sdk.common.DeviceManager.getSpecificDevice().
ServoChannel() [2/3]
com.neuronrobotics.sdk.dyio.peripherals.ServoChannel.ServoChannel (DyIO dyio, int channel)
Constructor. Creates an counter input input channel that is syncronous only by default.
Parameters
dyio the dyio
channel - the channel object requested from the DyIO
Definition at line 54 of file ServoChannel.java.
References com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral.channel, and com.neuronrobotics.sdk.dyio.DyIO.getChannel().
ServoChannel() [3/3]
com.neuronrobotics.sdk.dyio.peripherals.ServoChannel.ServoChannel (DyIOChannel channel)
Instantiates a new servo channel.
Parameters
channel the channel
Definition at line 63 of file ServoChannel.java.
References com.neuronrobotics.sdk.dyio.DyIOChannel.addChannelEventListener(), com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral.channel, com.neuronrobotics.sdk.dyio.DyIOChannelMode.SERVO_OUT, com.neuronrobotics.sdk.dyio.DyIOChannel.setDap(), and com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral.setMode().
Member Function Documentation
addIServoPositionUpdateListener()
void com.neuronrobotics.sdk.dyio.peripherals.ServoChannel.addIServoPositionUpdateListener (IServoPositionUpdateListener l)
THis method allows you to listen to servo setpoint changes.
Parameters
l the l
Definition at line 154 of file ServoChannel.java.
References com.neuronrobotics.sdk.dyio.peripherals.ServoChannel.listeners.
Referenced by com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.addIServoPositionUpdateListener().
disablePowerOverride()
void com.neuronrobotics.sdk.dyio.peripherals.ServoChannel.disablePowerOverride ()
This method allows you to re enable the lock-out.
Definition at line 181 of file ServoChannel.java.
References com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral.getChannel(), com.neuronrobotics.sdk.dyio.DyIOChannel.getDevice(), and com.neuronrobotics.sdk.dyio.DyIO.send().
enablePowerOverride()
void com.neuronrobotics.sdk.dyio.peripherals.ServoChannel.enablePowerOverride ()
This method allows you to override the servo voltage lock-out it is enabled by default.
Definition at line 174 of file ServoChannel.java.
References com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral.getChannel(), com.neuronrobotics.sdk.dyio.DyIOChannel.getDevice(), and com.neuronrobotics.sdk.dyio.DyIO.send().
firePositionUpdate()
void com.neuronrobotics.sdk.dyio.peripherals.ServoChannel.firePositionUpdate (int pos, double time) private
Fire position update.
Parameters
pos the pos
time the time
Definition at line 143 of file ServoChannel.java.
References com.neuronrobotics.sdk.dyio.peripherals.ServoChannel.listeners.
Referenced by com.neuronrobotics.sdk.dyio.peripherals.ServoChannel.onChannelEvent().
hasAsync()
boolean com.neuronrobotics.sdk.dyio.peripherals.ServoChannel.hasAsync ()
This method is to check if this peripheral is capable to be set as up as asynchronous.
Returns
if it cna be async
Reimplemented from com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral.
Definition at line 133 of file ServoChannel.java.
onChannelEvent()
void com.neuronrobotics.sdk.dyio.peripherals.ServoChannel.onChannelEvent (DyIOChannelEvent e)
On channel event.
Parameters
e the e
Implements com.neuronrobotics.sdk.dyio.IChannelEventListener.
Definition at line 206 of file ServoChannel.java.
References com.neuronrobotics.sdk.dyio.peripherals.ServoChannel.firePositionUpdate(), and com.neuronrobotics.sdk.dyio.DyIOChannelEvent.getUnsignedValue().
removeIServoPositionUpdateListener()
void com.neuronrobotics.sdk.dyio.peripherals.ServoChannel.removeIServoPositionUpdateListener (IServoPositionUpdateListener l)
removes a specified listener.
Parameters
l the l
Definition at line 165 of file ServoChannel.java.
References com.neuronrobotics.sdk.dyio.peripherals.ServoChannel.listeners.
Referenced by com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.removeIServoPositionUpdateListener().
SetPosition() [1/3]
boolean com.neuronrobotics.sdk.dyio.peripherals.ServoChannel.SetPosition (int pos)
Set the servo to a given position.
Parameters
pos the pos
Returns
if the action was successful
Definition at line 78 of file ServoChannel.java.
Referenced by com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.addServoChannel(), com.neuronrobotics.sdk.addons.irobot.CreateArm.check(), com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.flush(), com.neuronrobotics.sdk.addons.irobot.CreateArm.gripClose(), com.neuronrobotics.sdk.addons.irobot.CreateArm.gripOpen(), com.neuronrobotics.sdk.addons.irobot.CreateArm.setAngles(), com.neuronrobotics.sdk.dyio.peripherals.ServoChannel.SetPosition(), and com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.sync().
SetPosition() [2/3]
boolean com.neuronrobotics.sdk.dyio.peripherals.ServoChannel.SetPosition (int pos, double time)
Steps the servo though a transformation over a given amount of time.
Parameters
pos - the end position
time - the number of seconds for the transition to take place
Returns
if the action was successful
Definition at line 88 of file ServoChannel.java.
References com.neuronrobotics.sdk.dyio.peripherals.ServoChannel.SetPosition().
SetPosition() [3/3]
boolean com.neuronrobotics.sdk.dyio.peripherals.ServoChannel.SetPosition (int pos, float time)
Steps the servo though a transformation over a given amount of time.
Parameters
pos - the end position
time - the number of seconds for the transition to take place
Returns
if the action was successful
Definition at line 99 of file ServoChannel.java.
References com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral.flush(), com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral.getChannel(), com.neuronrobotics.sdk.dyio.DyIOChannel.setCachedTime(), com.neuronrobotics.sdk.dyio.DyIOChannel.setCachedValue(), and com.neuronrobotics.sdk.dyio.peripherals.ServoChannel.validate().
validate()
boolean com.neuronrobotics.sdk.dyio.peripherals.ServoChannel.validate () private
Validate.
Returns
true, if successful
Definition at line 122 of file ServoChannel.java.
References com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral.getMode(), com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral.isEnabled(), and com.neuronrobotics.sdk.dyio.DyIOChannelMode.SERVO_OUT.
Referenced by com.neuronrobotics.sdk.dyio.peripherals.ServoChannel.SetPosition().
Member Data Documentation
listeners
ArrayList<IServoPositionUpdateListener > com.neuronrobotics.sdk.dyio.peripherals.ServoChannel.listeners = new ArrayList<IServoPositionUpdateListener >() private
The listeners.
Definition at line 35 of file ServoChannel.java.
Referenced by com.neuronrobotics.sdk.dyio.peripherals.ServoChannel.addIServoPositionUpdateListener(), com.neuronrobotics.sdk.dyio.peripherals.ServoChannel.firePositionUpdate(), and com.neuronrobotics.sdk.dyio.peripherals.ServoChannel.removeIServoPositionUpdateListener().
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/dyio/peripherals/ServoChannel.java