BowlerKernel: com.neuronrobotics.sdk.common.ConfigManager Class Reference
com.neuronrobotics.sdk.common.ConfigManager Class Reference
Static Public Member Functions
static BowlerAbstractConnection loadDefaultConnection (String filename)
Static Private Member Functions
static String getElementValue (Element e, String key, String dval)
Detailed Description
The Class ConfigManager.
Definition at line 21 of file ConfigManager.java.
Member Function Documentation
getElementValue()
static String com.neuronrobotics.sdk.common.ConfigManager.getElementValue (Element e, String key, String dval) static private
Gets the element value.
Parameters
e the e
key the key
dval the dval
Returns
the element value
Definition at line 81 of file ConfigManager.java.
Referenced by com.neuronrobotics.sdk.common.ConfigManager.loadDefaultConnection().
loadDefaultConnection()
static BowlerAbstractConnection com.neuronrobotics.sdk.common.ConfigManager.loadDefaultConnection (String filename) static
Load default connection.
Parameters
filename the filename
Returns
the bowler abstract connection
Definition at line 29 of file ConfigManager.java.
References com.neuronrobotics.sdk.common.ConfigManager.getElementValue().
Referenced by com.neuronrobotics.sdk.ui.ConnectionDialog.getHeadlessConnection().
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/common/ConfigManager.java