BowlerKernel: eu.mihosoft.vrl.v3d.CSGtoJavafx Class Reference
eu.mihosoft.vrl.v3d.CSGtoJavafx Class Reference
Static Public Member Functions
static MeshContainer meshFromPolygon (Polygon... poly)
static MeshContainer meshFromPolygon (List< Polygon > poly)
Detailed Description
Definition at line 8 of file CSGtoJavafx.java.
Member Function Documentation
meshFromPolygon() [1/2]
static MeshContainer eu.mihosoft.vrl.v3d.CSGtoJavafx.meshFromPolygon (List< Polygon > poly) static
Definition at line 13 of file CSGtoJavafx.java.
References eu.mihosoft.vrl.v3d.Vertex.pos, eu.mihosoft.vrl.v3d.Vector3d.x(), eu.mihosoft.vrl.v3d.Vector3d.y(), and eu.mihosoft.vrl.v3d.Vector3d.z().
meshFromPolygon() [2/2]
static MeshContainer eu.mihosoft.vrl.v3d.CSGtoJavafx.meshFromPolygon (Polygon... poly) static
Definition at line 10 of file CSGtoJavafx.java.
Referenced by eu.mihosoft.vrl.v3d.CSG.toJavaFXMeshSimple().
The documentation for this class was generated from the following file:
JCSG/src/main/java/eu/mihosoft/vrl/v3d/CSGtoJavafx.java