BowlerKernel: com.neuronrobotics.bowlerstudio.physics.WheelCSGPhysicsManager Class Reference
com.neuronrobotics.bowlerstudio.physics.WheelCSGPhysicsManager Class Reference
Public Member Functions
WheelCSGPhysicsManager (ArrayList< CSG > baseCSG, Transform pose, double mass, PhysicsCore c, RaycastVehicle v, int wheelIndex)
void update (float timeStep)
double getTarget ()
void setTarget (double target)
void setMuscleStrength (double muscleStrength)
IClosedLoopController getController ()
void setController (IClosedLoopController controller)
WheelInfo getWheelInfo ()
int getWheelIndex ()
Public Member Functions inherited from com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager
CSGPhysicsManager (List< CSG > baseCSG, Transform pose, double mass, boolean adjustCenter, PhysicsCore core)
CSGPhysicsManager (ArrayList< CSG > baseCSG, Vector3f start, double mass, PhysicsCore core)
void setup (CollisionShape fallShape, Transform pose, double mass, PhysicsCore core)
RigidBody getFallRigidBody ()
void setFallRigidBody (RigidBody fallRigidBody)
List< CSG > getBaseCSG ()
void setBaseCSG (List< CSG > baseCSG)
Transform getUpdateTransform ()
Affine getRigidBodyLocation ()
IPhysicsUpdate getUpdateManager ()
void setUpdateManager (IPhysicsUpdate updateManager)
PhysicsCore getCore ()
void setCore (PhysicsCore core)
Static Public Member Functions
static float getMotorStrength ()
static void setMuscleStrength (float ms)
Static Public Member Functions inherited from com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager
static CSG getBoundingBox (CSG incoming)
Private Attributes
IClosedLoopController controller = null
double target = 0
double velocity
RaycastVehicle vehicle
final int wheelIndex
Static Private Attributes
static float muscleStrength = (float) 1000
Additional Inherited Members
Protected Member Functions inherited from com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager
CSG loadCSGToPoints (CSG baseCSG, boolean adjustCenter, Transform pose, ObjectArrayList< Vector3f > arg0)
Protected Attributes inherited from com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager
List< CSG > baseCSG = null
Detailed Description
Definition at line 15 of file WheelCSGPhysicsManager.java.
Constructor & Destructor Documentation
WheelCSGPhysicsManager()
com.neuronrobotics.bowlerstudio.physics.WheelCSGPhysicsManager.WheelCSGPhysicsManager (ArrayList< CSG > baseCSG, Transform pose, double mass, PhysicsCore c, RaycastVehicle v, int wheelIndex)
Definition at line 25 of file WheelCSGPhysicsManager.java.
References com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager.baseCSG, and com.neuronrobotics.bowlerstudio.physics.WheelCSGPhysicsManager.wheelIndex.
Member Function Documentation
getController()
IClosedLoopController com.neuronrobotics.bowlerstudio.physics.WheelCSGPhysicsManager.getController ()
Definition at line 74 of file WheelCSGPhysicsManager.java.
References com.neuronrobotics.bowlerstudio.physics.WheelCSGPhysicsManager.controller.
Referenced by com.neuronrobotics.bowlerstudio.physics.WheelCSGPhysicsManager.update().
getMotorStrength()
static float com.neuronrobotics.bowlerstudio.physics.WheelCSGPhysicsManager.getMotorStrength () static
Definition at line 62 of file WheelCSGPhysicsManager.java.
References com.neuronrobotics.bowlerstudio.physics.WheelCSGPhysicsManager.muscleStrength.
getTarget()
double com.neuronrobotics.bowlerstudio.physics.WheelCSGPhysicsManager.getTarget ()
Definition at line 54 of file WheelCSGPhysicsManager.java.
References com.neuronrobotics.bowlerstudio.physics.WheelCSGPhysicsManager.target.
Referenced by com.neuronrobotics.bowlerstudio.physics.WheelCSGPhysicsManager.update().
getWheelIndex()
int com.neuronrobotics.bowlerstudio.physics.WheelCSGPhysicsManager.getWheelIndex ()
Definition at line 86 of file WheelCSGPhysicsManager.java.
References com.neuronrobotics.bowlerstudio.physics.WheelCSGPhysicsManager.wheelIndex.
Referenced by com.neuronrobotics.bowlerstudio.physics.WheelCSGPhysicsManager.getWheelInfo(), and com.neuronrobotics.bowlerstudio.physics.WheelCSGPhysicsManager.update().
getWheelInfo()
WheelInfo com.neuronrobotics.bowlerstudio.physics.WheelCSGPhysicsManager.getWheelInfo ()
Definition at line 82 of file WheelCSGPhysicsManager.java.
References com.neuronrobotics.bowlerstudio.physics.WheelCSGPhysicsManager.getWheelIndex(), and com.neuronrobotics.bowlerstudio.physics.WheelCSGPhysicsManager.vehicle.
Referenced by com.neuronrobotics.bowlerstudio.physics.WheelCSGPhysicsManager.update().
setController()
void com.neuronrobotics.bowlerstudio.physics.WheelCSGPhysicsManager.setController (IClosedLoopController controller)
Definition at line 78 of file WheelCSGPhysicsManager.java.
References com.neuronrobotics.bowlerstudio.physics.WheelCSGPhysicsManager.controller.
setMuscleStrength() [1/2]
void com.neuronrobotics.bowlerstudio.physics.WheelCSGPhysicsManager.setMuscleStrength (double muscleStrength)
Definition at line 70 of file WheelCSGPhysicsManager.java.
References com.neuronrobotics.bowlerstudio.physics.WheelCSGPhysicsManager.muscleStrength, and com.neuronrobotics.bowlerstudio.physics.WheelCSGPhysicsManager.setMuscleStrength().
setMuscleStrength() [2/2]
static void com.neuronrobotics.bowlerstudio.physics.WheelCSGPhysicsManager.setMuscleStrength (float ms) static
Definition at line 66 of file WheelCSGPhysicsManager.java.
References com.neuronrobotics.bowlerstudio.physics.WheelCSGPhysicsManager.muscleStrength.
Referenced by com.neuronrobotics.bowlerstudio.physics.WheelCSGPhysicsManager.setMuscleStrength().
setTarget()
void com.neuronrobotics.bowlerstudio.physics.WheelCSGPhysicsManager.setTarget (double target)
Definition at line 58 of file WheelCSGPhysicsManager.java.
References com.neuronrobotics.bowlerstudio.physics.WheelCSGPhysicsManager.target.
update()
void com.neuronrobotics.bowlerstudio.physics.WheelCSGPhysicsManager.update (float timeStep)
Run the update for this ridgid body. Run any controllers for links
Reimplemented from com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager.
Definition at line 33 of file WheelCSGPhysicsManager.java.
References com.neuronrobotics.bowlerstudio.physics.TransformFactory.bulletToNr(), com.neuronrobotics.sdk.common.IClosedLoopController.compute(), com.neuronrobotics.bowlerstudio.physics.WheelCSGPhysicsManager.getController(), com.neuronrobotics.bowlerstudio.physics.WheelCSGPhysicsManager.getTarget(), com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager.getUpdateManager(), com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager.getUpdateTransform(), com.neuronrobotics.bowlerstudio.physics.WheelCSGPhysicsManager.getWheelIndex(), com.neuronrobotics.bowlerstudio.physics.WheelCSGPhysicsManager.getWheelInfo(), com.neuronrobotics.bowlerstudio.physics.TransformFactory.nrToBullet(), com.neuronrobotics.bowlerstudio.physics.IPhysicsUpdate.update(), com.neuronrobotics.bowlerstudio.physics.WheelCSGPhysicsManager.vehicle, and com.neuronrobotics.bowlerstudio.physics.WheelCSGPhysicsManager.velocity.
Member Data Documentation
controller
IClosedLoopController com.neuronrobotics.bowlerstudio.physics.WheelCSGPhysicsManager.controller = null private
Definition at line 17 of file WheelCSGPhysicsManager.java.
Referenced by com.neuronrobotics.bowlerstudio.physics.WheelCSGPhysicsManager.getController(), and com.neuronrobotics.bowlerstudio.physics.WheelCSGPhysicsManager.setController().
muscleStrength
float com.neuronrobotics.bowlerstudio.physics.WheelCSGPhysicsManager.muscleStrength = (float) 1000 static private
Definition at line 19 of file WheelCSGPhysicsManager.java.
Referenced by com.neuronrobotics.bowlerstudio.physics.WheelCSGPhysicsManager.getMotorStrength(), and com.neuronrobotics.bowlerstudio.physics.WheelCSGPhysicsManager.setMuscleStrength().
target
double com.neuronrobotics.bowlerstudio.physics.WheelCSGPhysicsManager.target = 0 private
Definition at line 18 of file WheelCSGPhysicsManager.java.
Referenced by com.neuronrobotics.bowlerstudio.physics.WheelCSGPhysicsManager.getTarget(), and com.neuronrobotics.bowlerstudio.physics.WheelCSGPhysicsManager.setTarget().
vehicle
RaycastVehicle com.neuronrobotics.bowlerstudio.physics.WheelCSGPhysicsManager.vehicle private
Definition at line 22 of file WheelCSGPhysicsManager.java.
Referenced by com.neuronrobotics.bowlerstudio.physics.WheelCSGPhysicsManager.getWheelInfo(), and com.neuronrobotics.bowlerstudio.physics.WheelCSGPhysicsManager.update().
velocity
double com.neuronrobotics.bowlerstudio.physics.WheelCSGPhysicsManager.velocity private
Definition at line 21 of file WheelCSGPhysicsManager.java.
Referenced by com.neuronrobotics.bowlerstudio.physics.WheelCSGPhysicsManager.update().
wheelIndex
final int com.neuronrobotics.bowlerstudio.physics.WheelCSGPhysicsManager.wheelIndex private
Definition at line 23 of file WheelCSGPhysicsManager.java.
Referenced by com.neuronrobotics.bowlerstudio.physics.WheelCSGPhysicsManager.getWheelIndex(), and com.neuronrobotics.bowlerstudio.physics.WheelCSGPhysicsManager.WheelCSGPhysicsManager().
The documentation for this class was generated from the following file:
src/main/java/com/neuronrobotics/bowlerstudio/physics/WheelCSGPhysicsManager.java