BowlerKernel: com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory Class Reference
com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory Class Reference
Classes
class UniquePersonUI
Public Member Functions
void clear ()
String save ()
void disconnectDeviceImp ()
boolean connectDeviceImp ()
void addFace (Mat matrix, Rect crop, ai.djl.modality.cv.output.Point nose)
ArrayList< String > getNamespacesImp ()
HashMap< UniquePerson, Point > getCurrentPersons ()
void setWorkingMemory (VBox workingMemory)
File getDatabase ()
void setDatabase (File database)
boolean isProcessFlag ()
void setProcessFlag ()
Public Member Functions inherited from com.neuronrobotics.sdk.common.NonBowlerDevice
boolean connect ()
boolean isAvailable () throws InvalidConnectionException
void disconnect ()
void onAsyncResponse (BowlerDatagram data)
ArrayList< String > getNamespaces ()
Public Member Functions inherited from com.neuronrobotics.sdk.common.BowlerAbstractDevice
void addConnectionEventListener (final IDeviceConnectionEventListener l)
void removeConnectionEventListener (IDeviceConnectionEventListener l)
void setConnection (BowlerAbstractConnection connection)
BowlerAbstractConnection getConnection ()
void setAddress (MACAddress address)
MACAddress getAddress ()
BowlerDatagram send (BowlerAbstractCommand command) throws NoConnectionAvailableException, InvalidResponseException
BowlerDatagram send (BowlerAbstractCommand command, int retry) throws NoConnectionAvailableException, InvalidResponseException
Object[] send (String namespace, BowlerMethod method, String rpcString, Object[] arguments, int retry) throws DeviceConnectionException
Object[] send (String namespace, BowlerMethod method, String rpcString, Object[] arguments) throws DeviceConnectionException
boolean ping ()
boolean ping (boolean switchParser)
ArrayList< ByteList > getRevisions ()
boolean hasNamespace (String string)
void startHeartBeat ()
void startHeartBeat (long msHeartBeatTime)
void stopHeartBeat ()
void setThreadedUpstreamPackets (boolean up)
ArrayList< RpcEncapsulation > getRpcList (String namespace)
void loadRpcList ()
void onAllResponse (BowlerDatagram data)
boolean isKeepAlive ()
void setKeepAlive (boolean keepAlive)
long getLastPacketTime ()
void setLastPacketTime (long lastPacketTime)
String getScriptingName ()
void setScriptingName (String scriptingName)
ArrayList< IDeviceConnectionEventListener > getDisconnectListeners ()
Static Public Member Functions
static UniquePersonFactory get ()
static UniquePersonFactory get (File index)
static double getConfidence ()
static void setConfidence (double confidence)
static long getTimeout ()
static void setTimeout (long timeout)
static int getNumberOfTrainingHashes ()
static void setNumberOfTrainingHashes (int numberOfTrainingHashes)
Private Member Functions
UniquePersonUI getUI (UniquePerson p)
UniquePersonFactory (File database)
void processBlocking ()
EventHandler< ActionEvent > setAction (UniquePerson p)
boolean processMemory (HashMap< UniquePerson, org.opencv.core.Point > tmpPersons, BufferedImage imgBuff, Point point, float[] id, boolean found, ArrayList< UniquePerson > duplicates, UniquePerson pp)
void resetHash ()
Private Attributes
File database
HashSet< UniquePerson > longTermMemory = new HashSet<>()
ArrayList< UniquePerson > shortTermMemory = new ArrayList<>()
Thread processor
boolean run = true
HashMap< BufferedImage, Point > factoryFromImageTMp = null
HashMap< UniquePerson, Point > currentPersons = null
ImageFactory factory
VBox workingMemory = new VBox()
boolean processFlag = false
HashMap< UniquePerson, UniquePersonUI > uiElelments = new HashMap<UniquePerson, UniquePersonFactory.UniquePersonUI>()
HashMap< BufferedImage, Point > localMailbox
Static Private Attributes
static double confidence = 0.8
static long timeout = 30000
static long countPeople = 1
static int numberOfTrainingHashes = 30
Additional Inherited Members
Protected Member Functions inherited from com.neuronrobotics.sdk.common.BowlerAbstractDevice
void fireDisconnectEvent ()
void fireConnectEvent ()
Detailed Description
Definition at line 49 of file UniquePersonFactory.java.
Constructor & Destructor Documentation
UniquePersonFactory()
com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.UniquePersonFactory (File database) private
Definition at line 101 of file UniquePersonFactory.java.
References com.neuronrobotics.bowlerkernel.djl.PredictorFactory.faceFeatureFactory(), com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.factory, and com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.setDatabase().
Referenced by com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.get().
Member Function Documentation
addFace()
void com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.addFace (Mat matrix, Rect crop, ai.djl.modality.cv.output.Point nose)
Definition at line 218 of file UniquePersonFactory.java.
References com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.factoryFromImageTMp.
clear()
void com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.clear ()
Definition at line 120 of file UniquePersonFactory.java.
References com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.currentPersons, com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.factoryFromImageTMp, and com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.isProcessFlag().
Referenced by com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.setWorkingMemory().
connectDeviceImp()
boolean com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.connectDeviceImp ()
Connect device imp.
Returns
true, if successful
Reimplemented from com.neuronrobotics.sdk.common.NonBowlerDevice.
Definition at line 208 of file UniquePersonFactory.java.
References com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.disconnectDeviceImp(), com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.processBlocking(), com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.processor, and com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.run.
disconnectDeviceImp()
void com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.disconnectDeviceImp ()
This method tells the connection object to disconnect its pipes and close out the connection. Once this is called, it is safe to remove your device.
Reimplemented from com.neuronrobotics.sdk.common.NonBowlerDevice.
Definition at line 201 of file UniquePersonFactory.java.
References com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.processor, and com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.run.
Referenced by com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.connectDeviceImp().
get() [1/2]
static UniquePersonFactory com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.get () static
Definition at line 90 of file UniquePersonFactory.java.
References com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getWorkspace().
get() [2/2]
static UniquePersonFactory com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.get (File index) static
Definition at line 95 of file UniquePersonFactory.java.
References com.neuronrobotics.sdk.common.DeviceManager.getSpecificDevice(), and com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.UniquePersonFactory().
getConfidence()
static double com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.getConfidence () static
Returns
the confidence
Definition at line 161 of file UniquePersonFactory.java.
References com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.confidence.
getCurrentPersons()
HashMap<UniquePerson, Point> com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.getCurrentPersons ()
Returns
the currentPersons
Definition at line 424 of file UniquePersonFactory.java.
References com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.currentPersons.
getDatabase()
File com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.getDatabase ()
Returns
the database
Definition at line 454 of file UniquePersonFactory.java.
References com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.database.
Referenced by com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.save().
getNamespacesImp()
ArrayList<String> com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.getNamespacesImp ()
Gets the namespaces imp.
Returns
the namespaces imp
Reimplemented from com.neuronrobotics.sdk.common.NonBowlerDevice.
Definition at line 416 of file UniquePersonFactory.java.
getNumberOfTrainingHashes()
static int com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.getNumberOfTrainingHashes () static
Returns
the numberOfTrainingHashes
Definition at line 189 of file UniquePersonFactory.java.
References com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.numberOfTrainingHashes.
getTimeout()
static long com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.getTimeout () static
Returns
the timeout
Definition at line 175 of file UniquePersonFactory.java.
References com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.timeout.
getUI()
UniquePersonUI com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.getUI (UniquePerson p) private
Definition at line 83 of file UniquePersonFactory.java.
References com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.uiElelments.
Referenced by com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.processBlocking(), com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.processMemory(), com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.save(), and com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.setAction().
isProcessFlag()
boolean com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.isProcessFlag ()
Returns
the processFlag
Definition at line 501 of file UniquePersonFactory.java.
References com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.processFlag.
Referenced by com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.clear(), com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.processBlocking(), and com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.setProcessFlag().
processBlocking()
void com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.processBlocking () private
Definition at line 246 of file UniquePersonFactory.java.
References com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.countPeople, com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.currentPersons, com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.factory, com.neuronrobotics.bowlerkernel.djl.UniquePerson.features, com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.getUI(), com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.isProcessFlag(), com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.localMailbox, com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.longTermMemory, com.neuronrobotics.bowlerkernel.djl.UniquePerson.name, com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.numberOfTrainingHashes, com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.processFlag, com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.processMemory(), com.neuronrobotics.bowlerkernel.djl.UniquePerson.referenceImageLocation, com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.resetHash(), com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.run, com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.save(), com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.shortTermMemory, com.neuronrobotics.bowlerkernel.djl.UniquePerson.time, com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.timeout, com.neuronrobotics.bowlerkernel.djl.UniquePerson.timesSeen, com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.uiElelments, com.neuronrobotics.bowlerkernel.djl.UniquePerson.UUID, and com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.workingMemory.
Referenced by com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.connectDeviceImp().
processMemory()
boolean com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.processMemory (HashMap< UniquePerson, org.opencv.core.Point > tmpPersons, BufferedImage imgBuff, Point point, float[] id, boolean found, ArrayList< UniquePerson > duplicates, UniquePerson pp) private
Definition at line 352 of file UniquePersonFactory.java.
References com.neuronrobotics.bowlerkernel.djl.PredictorFactory.calculSimilarFaceFeature(), com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.confidence, com.neuronrobotics.bowlerkernel.djl.UniquePerson.features, com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.getUI(), com.neuronrobotics.bowlerkernel.djl.UniquePerson.name, com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.numberOfTrainingHashes, com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.save(), com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.setAction(), com.neuronrobotics.bowlerkernel.djl.UniquePerson.time, com.neuronrobotics.bowlerkernel.djl.UniquePerson.timesSeen, and com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.workingMemory.
Referenced by com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.processBlocking().
resetHash()
void com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.resetHash () private
Definition at line 458 of file UniquePersonFactory.java.
References com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.countPeople, com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.longTermMemory, and com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.shortTermMemory.
Referenced by com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.processBlocking(), and com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.setDatabase().
save()
String com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.save ()
Definition at line 138 of file UniquePersonFactory.java.
References com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.getDatabase(), com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.getUI(), com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.longTermMemory, com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.shortTermMemory, and com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.workingMemory.
Referenced by com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.processBlocking(), com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.processMemory(), com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.setAction(), and com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.setDatabase().
setAction()
EventHandler<ActionEvent> com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.setAction (UniquePerson p) private
Definition at line 343 of file UniquePersonFactory.java.
References com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.getUI(), com.neuronrobotics.bowlerkernel.djl.UniquePerson.name, and com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.save().
Referenced by com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.processMemory().
setConfidence()
static void com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.setConfidence (double confidence) static
Parameters
confidence the confidence to set
Definition at line 168 of file UniquePersonFactory.java.
References com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.confidence.
setDatabase()
void com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.setDatabase (File database)
Parameters
database the database to set
Definition at line 475 of file UniquePersonFactory.java.
References com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.database, com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.longTermMemory, com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.resetHash(), and com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.save().
Referenced by com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.UniquePersonFactory().
setNumberOfTrainingHashes()
static void com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.setNumberOfTrainingHashes (int numberOfTrainingHashes) static
Parameters
numberOfTrainingHashes the numberOfTrainingHashes to set
Definition at line 196 of file UniquePersonFactory.java.
References com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.numberOfTrainingHashes.
setProcessFlag()
void com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.setProcessFlag ()
Parameters
processFlag the processFlag to set
Definition at line 508 of file UniquePersonFactory.java.
References com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.factoryFromImageTMp, com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.isProcessFlag(), and com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.localMailbox.
setTimeout()
static void com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.setTimeout (long timeout) static
Parameters
timeout the timeout to set
Definition at line 182 of file UniquePersonFactory.java.
References com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.timeout.
setWorkingMemory()
void com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.setWorkingMemory (VBox workingMemory)
Parameters
workingMemory the workingMemory to set
Definition at line 439 of file UniquePersonFactory.java.
References com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.clear(), com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.uiElelments, and com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.workingMemory.
Member Data Documentation
confidence
double com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.confidence = 0.8 static private
Definition at line 58 of file UniquePersonFactory.java.
Referenced by com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.getConfidence(), com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.processMemory(), and com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.setConfidence().
countPeople
long com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.countPeople = 1 static private
Definition at line 60 of file UniquePersonFactory.java.
Referenced by com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.processBlocking(), and com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.resetHash().
currentPersons
HashMap<UniquePerson, Point> com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.currentPersons = null private
Definition at line 65 of file UniquePersonFactory.java.
Referenced by com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.clear(), com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.getCurrentPersons(), and com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.processBlocking().
database
File com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.database private
Definition at line 50 of file UniquePersonFactory.java.
Referenced by com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.getDatabase(), and com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.setDatabase().
factory
ImageFactory com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.factory private
Definition at line 66 of file UniquePersonFactory.java.
Referenced by com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.processBlocking(), and com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.UniquePersonFactory().
factoryFromImageTMp
HashMap<BufferedImage, Point> com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.factoryFromImageTMp = null private
Definition at line 64 of file UniquePersonFactory.java.
Referenced by com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.addFace(), com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.clear(), and com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.setProcessFlag().
localMailbox
HashMap<BufferedImage, Point> com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.localMailbox private
Definition at line 81 of file UniquePersonFactory.java.
Referenced by com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.processBlocking(), and com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.setProcessFlag().
longTermMemory
HashSet<UniquePerson> com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.longTermMemory = new HashSet<>() private
Definition at line 54 of file UniquePersonFactory.java.
Referenced by com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.processBlocking(), com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.resetHash(), com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.save(), and com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.setDatabase().
numberOfTrainingHashes
int com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.numberOfTrainingHashes = 30 static private
Definition at line 61 of file UniquePersonFactory.java.
Referenced by com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.getNumberOfTrainingHashes(), com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.processBlocking(), com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.processMemory(), and com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.setNumberOfTrainingHashes().
processFlag
boolean com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.processFlag = false private
Definition at line 68 of file UniquePersonFactory.java.
Referenced by com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.isProcessFlag(), and com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.processBlocking().
processor
Thread com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.processor private
Definition at line 62 of file UniquePersonFactory.java.
Referenced by com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.connectDeviceImp(), and com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.disconnectDeviceImp().
run
boolean com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.run = true private
Definition at line 63 of file UniquePersonFactory.java.
Referenced by com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.connectDeviceImp(), com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.disconnectDeviceImp(), and com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.processBlocking().
shortTermMemory
ArrayList<UniquePerson> com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.shortTermMemory = new ArrayList<>() private
Definition at line 55 of file UniquePersonFactory.java.
Referenced by com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.processBlocking(), com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.resetHash(), and com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.save().
timeout
long com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.timeout = 30000 static private
Definition at line 59 of file UniquePersonFactory.java.
Referenced by com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.getTimeout(), com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.processBlocking(), and com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.setTimeout().
uiElelments
HashMap<UniquePerson, UniquePersonUI> com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.uiElelments = new HashMap<UniquePerson, UniquePersonFactory.UniquePersonUI>() private
Definition at line 80 of file UniquePersonFactory.java.
Referenced by com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.getUI(), com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.processBlocking(), and com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.setWorkingMemory().
workingMemory
VBox com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.workingMemory = new VBox() private
Definition at line 67 of file UniquePersonFactory.java.
Referenced by com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.processBlocking(), com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.processMemory(), com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.save(), and com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.setWorkingMemory().
The documentation for this class was generated from the following file:
src/main/java/com/neuronrobotics/bowlerkernel/djl/UniquePersonFactory.java