BowlerKernel: com.neuronrobotics.sdk.common.BowlerDatagram Class Reference
com.neuronrobotics.sdk.common.BowlerDatagram Class Reference
Public Member Functions
BowlerDatagram (BowlerDatagramFactory factory)
BowlerDatagram (ByteList data, BowlerDatagramFactory factory)
void parse (ByteList raw)
void setData (byte[] bs)
ByteList getPayload ()
MACAddress getAddress ()
byte getRevision ()
BowlerMethod getMethod ()
byte getNamespaceResolutionID ()
boolean isSyncronous ()
boolean isUpstream ()
byte getTransactionUpstream ()
byte getCRC ()
String getRPC ()
ByteList getData ()
byte[] getBytes ()
String toString ()
long getTimestamp ()
void setAsAsync (int id)
void clear ()
void setAddress (MACAddress address)
void setMethod (BowlerMethod method)
void setNamespaceResolutionID (byte namespaceResolutionID)
void setUpstream (boolean upstream)
boolean isFree ()
void setFree (boolean isFree, BowlerDatagramFactory factory)
void onTimeout (String message)
void calcCRC ()
void setRpc (String opCode)
Static Public Member Functions
static byte genDataCrc (ByteList data)
static boolean isUseBowlerV4 ()
static void setUseBowlerV4 (boolean useBowlerV4)
Static Public Attributes
static final byte REVISION = 3
static final int HEADER_SIZE = 11
static final int CRC_INDEX = 10
static final int MAX_PACKET_SIZE = HEADER_SIZE+255
Private Member Functions
byte getCrc ()
void setCrc (byte crc)
byte getDataCrc ()
void setDataCrc (byte crc)
void validate (BowlerDatagramFactory factory)
int getSessionID ()
void checkValidPacket ()
void setNotFree ()
void setToFree ()
Static Private Member Functions
static byte genCRC (int index, int len, ByteList data)
static byte genCrc (ByteList data)
static byte getCRC (ByteList data)
static byte getDataCrc (ByteList data)
Private Attributes
MACAddress address = new MACAddress()
BowlerMethod method
byte namespaceResolutionID
boolean upstream
byte crc
byte dataCrc
ByteList data = new ByteList()
boolean isPackedAvailibleForLoading = true
ThreadedTimeout timeout =new ThreadedTimeout()
Static Private Attributes
static boolean useBowlerV4 =true
Detailed Description
Formats data into a Bowler packet.
Author
rbreznak, Kevin Harrington
Definition at line 41 of file BowlerDatagram.java.
Constructor & Destructor Documentation
BowlerDatagram() [1/2]
com.neuronrobotics.sdk.common.BowlerDatagram.BowlerDatagram (BowlerDatagramFactory factory)
Default constructor.
Parameters
factory the factory
Definition at line 94 of file BowlerDatagram.java.
References com.neuronrobotics.sdk.common.BowlerDatagram.setFree(), and com.neuronrobotics.sdk.common.BowlerDatagram.validate().
BowlerDatagram() [2/2]
com.neuronrobotics.sdk.common.BowlerDatagram.BowlerDatagram (ByteList data, BowlerDatagramFactory factory)
Constructs a BowlerDatagram that will parse the given data into a packet. Data must be at least the size of a standard Bowler packet header (11 bytes long)
Parameters
data the data
factory the factory
Definition at line 209 of file BowlerDatagram.java.
References com.neuronrobotics.sdk.common.BowlerDatagram.data, com.neuronrobotics.sdk.common.BowlerDatagram.parse(), and com.neuronrobotics.sdk.common.BowlerDatagram.validate().
Member Function Documentation
calcCRC()
void com.neuronrobotics.sdk.common.BowlerDatagram.calcCRC ()
Calc crc.
Definition at line 668 of file BowlerDatagram.java.
References com.neuronrobotics.sdk.common.BowlerDatagram.checkValidPacket(), and com.neuronrobotics.sdk.common.BowlerDatagram.getBytes().
Referenced by com.neuronrobotics.sdk.common.BowlerDatagram.setUpstream().
checkValidPacket()
void com.neuronrobotics.sdk.common.BowlerDatagram.checkValidPacket () private
Check valid packet.
Definition at line 589 of file BowlerDatagram.java.
References com.neuronrobotics.sdk.common.BowlerDatagram.isFree(), com.neuronrobotics.sdk.common.ThreadedTimeout.isTimedOut(), com.neuronrobotics.sdk.common.BowlerDatagram.setFree(), and com.neuronrobotics.sdk.common.BowlerDatagram.timeout.
Referenced by com.neuronrobotics.sdk.common.BowlerDatagram.calcCRC(), com.neuronrobotics.sdk.common.BowlerDatagram.getAddress(), com.neuronrobotics.sdk.common.BowlerDatagram.getBytes(), com.neuronrobotics.sdk.common.BowlerDatagram.getCrc(), com.neuronrobotics.sdk.common.BowlerDatagram.getCRC(), com.neuronrobotics.sdk.common.BowlerDatagram.getData(), com.neuronrobotics.sdk.common.BowlerDatagram.getDataCrc(), com.neuronrobotics.sdk.common.BowlerDatagram.getMethod(), com.neuronrobotics.sdk.common.BowlerDatagram.getNamespaceResolutionID(), com.neuronrobotics.sdk.common.BowlerDatagram.getPayload(), com.neuronrobotics.sdk.common.BowlerDatagram.getRevision(), com.neuronrobotics.sdk.common.BowlerDatagram.getRPC(), com.neuronrobotics.sdk.common.BowlerDatagram.getSessionID(), com.neuronrobotics.sdk.common.BowlerDatagram.getTimestamp(), com.neuronrobotics.sdk.common.BowlerDatagram.getTransactionUpstream(), com.neuronrobotics.sdk.common.BowlerDatagram.isSyncronous(), com.neuronrobotics.sdk.common.BowlerDatagram.isUpstream(), com.neuronrobotics.sdk.common.BowlerDatagram.parse(), com.neuronrobotics.sdk.common.BowlerDatagram.setAddress(), com.neuronrobotics.sdk.common.BowlerDatagram.setAsAsync(), com.neuronrobotics.sdk.common.BowlerDatagram.setCrc(), com.neuronrobotics.sdk.common.BowlerDatagram.setData(), com.neuronrobotics.sdk.common.BowlerDatagram.setDataCrc(), com.neuronrobotics.sdk.common.BowlerDatagram.setMethod(), com.neuronrobotics.sdk.common.BowlerDatagram.setNamespaceResolutionID(), and com.neuronrobotics.sdk.common.BowlerDatagram.setUpstream().
clear()
void com.neuronrobotics.sdk.common.BowlerDatagram.clear ()
Clear.
Definition at line 534 of file BowlerDatagram.java.
References com.neuronrobotics.sdk.common.ByteList.clear(), and com.neuronrobotics.sdk.common.BowlerDatagram.data.
Referenced by com.neuronrobotics.sdk.common.BowlerDatagram.setNotFree().
genCrc()
static byte com.neuronrobotics.sdk.common.BowlerDatagram.genCrc (ByteList data) static private
Assumes that the packet starts at byte 0.
Parameters
data the data
Returns
the byte
Definition at line 125 of file BowlerDatagram.java.
References com.neuronrobotics.sdk.common.BowlerDatagram.data, com.neuronrobotics.sdk.common.BowlerDatagram.genCRC(), and com.neuronrobotics.sdk.common.BowlerDatagram.HEADER_SIZE.
Referenced by com.neuronrobotics.sdk.common.BowlerDatagram.getBytes().
genCRC()
static byte com.neuronrobotics.sdk.common.BowlerDatagram.genCRC (int index, int len, ByteList data) static private
Generate a CRC of a section of bytes,.
Parameters
index Start o the section
len LEngth of the section
data the data
Returns
The Calculated CRC
Definition at line 107 of file BowlerDatagram.java.
References com.neuronrobotics.sdk.common.BowlerDatagram.data, com.neuronrobotics.sdk.common.ByteList.getByte(), and com.neuronrobotics.sdk.common.ByteList.size().
Referenced by com.neuronrobotics.sdk.common.BowlerDatagram.genCrc(), and com.neuronrobotics.sdk.common.BowlerDatagram.genDataCrc().
genDataCrc()
static byte com.neuronrobotics.sdk.common.BowlerDatagram.genDataCrc (ByteList data) static
Assumes that the packet starts at byte 0.
Parameters
data the data
Returns
the byte
Definition at line 167 of file BowlerDatagram.java.
References com.neuronrobotics.sdk.common.BowlerDatagram.data, com.neuronrobotics.sdk.common.BowlerDatagram.genCRC(), com.neuronrobotics.sdk.common.ByteList.getUnsigned(), and com.neuronrobotics.sdk.common.BowlerDatagram.HEADER_SIZE.
Referenced by com.neuronrobotics.sdk.common.BowlerDatagram.getBytes().
getAddress()
MACAddress com.neuronrobotics.sdk.common.BowlerDatagram.getAddress ()
Get the datagram's current address.
Returns
the current address
Definition at line 298 of file BowlerDatagram.java.
References com.neuronrobotics.sdk.common.BowlerDatagram.address, and com.neuronrobotics.sdk.common.BowlerDatagram.checkValidPacket().
Referenced by com.neuronrobotics.sdk.dyio.DyIO.getAllChannelModes(), com.neuronrobotics.sdk.common.BowlerDatagram.getBytes(), com.neuronrobotics.sdk.common.BowlerAbstractConnection.send(), and com.neuronrobotics.sdk.common.BowlerDatagram.toString().
getBytes()
byte [] com.neuronrobotics.sdk.common.BowlerDatagram.getBytes ()
Gets the bytes.
Returns
the bytes
Implements com.neuronrobotics.sdk.common.ISendable.
Definition at line 412 of file BowlerDatagram.java.
References com.neuronrobotics.sdk.common.ByteList.add(), com.neuronrobotics.sdk.common.BowlerDatagram.checkValidPacket(), com.neuronrobotics.sdk.common.BowlerDatagram.data, com.neuronrobotics.sdk.common.BowlerDatagram.genCrc(), com.neuronrobotics.sdk.common.BowlerDatagram.genDataCrc(), com.neuronrobotics.sdk.common.BowlerDatagram.getAddress(), com.neuronrobotics.sdk.common.ByteList.getBytes(), com.neuronrobotics.sdk.common.BowlerDatagram.getCRC(), com.neuronrobotics.sdk.common.BowlerDatagram.getDataCrc(), com.neuronrobotics.sdk.common.BowlerDatagram.getMethod(), com.neuronrobotics.sdk.common.BowlerDatagram.getTransactionUpstream(), com.neuronrobotics.sdk.common.BowlerDatagram.isUseBowlerV4(), com.neuronrobotics.sdk.common.BowlerDatagram.REVISION, com.neuronrobotics.sdk.common.BowlerDatagram.setCrc(), com.neuronrobotics.sdk.common.BowlerDatagram.setDataCrc(), and com.neuronrobotics.sdk.common.ByteList.size().
Referenced by com.neuronrobotics.sdk.common.BowlerDatagram.calcCRC(), com.neuronrobotics.sdk.common.BowlerAbstractConnection.sendSynchronusly(), and com.neuronrobotics.sdk.common.BowlerDatagram.toString().
getCrc()
byte com.neuronrobotics.sdk.common.BowlerDatagram.getCrc () private
Gets the crc.
Returns
the crc
Definition at line 144 of file BowlerDatagram.java.
References com.neuronrobotics.sdk.common.BowlerDatagram.checkValidPacket(), and com.neuronrobotics.sdk.common.BowlerDatagram.crc.
Referenced by com.neuronrobotics.sdk.common.BowlerDatagram.getCRC(), and com.neuronrobotics.sdk.common.BowlerDatagram.toString().
getCRC() [1/2]
byte com.neuronrobotics.sdk.common.BowlerDatagram.getCRC ()
Generates the valid CRC of the datagram.
Returns
The datagram's CRC
Definition at line 372 of file BowlerDatagram.java.
References com.neuronrobotics.sdk.common.BowlerDatagram.checkValidPacket(), and com.neuronrobotics.sdk.common.BowlerDatagram.getCrc().
Referenced by com.neuronrobotics.sdk.common.BowlerDatagram.getBytes(), and com.neuronrobotics.sdk.common.BowlerDatagram.parse().
getCRC() [2/2]
static byte com.neuronrobotics.sdk.common.BowlerDatagram.getCRC (ByteList data) static private
Assumes the packet starts at byte 0.
Parameters
data the data
Returns
the byte holding the header crc
Definition at line 135 of file BowlerDatagram.java.
References com.neuronrobotics.sdk.common.BowlerDatagram.CRC_INDEX, com.neuronrobotics.sdk.common.BowlerDatagram.data, and com.neuronrobotics.sdk.common.ByteList.getByte().
getData()
ByteList com.neuronrobotics.sdk.common.BowlerDatagram.getData ()
Get the datagram's current data payload after the RPC.
Returns
the current data payload
Definition at line 405 of file BowlerDatagram.java.
References com.neuronrobotics.sdk.common.BowlerDatagram.checkValidPacket(), com.neuronrobotics.sdk.common.BowlerDatagram.data, and com.neuronrobotics.sdk.common.ByteList.getBytes().
Referenced by com.neuronrobotics.sdk.dyio.dypid.DyPIDConfiguration.DyPIDConfiguration(), com.neuronrobotics.sdk.dyio.DyIO.getAllChannelModes(), com.neuronrobotics.sdk.dyio.DyIO.getAllChannelValues(), com.neuronrobotics.sdk.namespace.bcs.pid.LegacyPidNamespaceImp.GetAllPIDPosition(), com.neuronrobotics.sdk.dyio.DyIO.getAvailibleChannelModes(), com.neuronrobotics.sdk.bootloader.NRBootLoader.getBootloaderID(), com.neuronrobotics.sdk.dyio.DyIO.getDyIOChannelCount(), com.neuronrobotics.sdk.dyio.DyIO.getHeartBeatTime(), com.neuronrobotics.sdk.bowlercam.device.BowlerCamDevice.getImageServerURL(), com.neuronrobotics.sdk.common.BowlerAbstractConnection.getNamespaces(), com.neuronrobotics.sdk.namespace.bcs.pid.LegacyPidNamespaceImp.getPIDChannelCount(), com.neuronrobotics.sdk.namespace.bcs.pid.LegacyPidNamespaceImp.GetPIDPosition(), com.neuronrobotics.sdk.common.BowlerAbstractDevice.getRevisions(), com.neuronrobotics.sdk.common.BowlerAbstractConnection.getRpcList(), com.neuronrobotics.sdk.dyio.DyIOChannel.getValue(), com.neuronrobotics.sdk.common.device.server.BowlerAbstractDeviceServer.onAllResponse(), com.neuronrobotics.sdk.bowlercam.device.BowlerCamDevice.onAsyncResponse(), com.neuronrobotics.sdk.dyio.DyIO.onAsyncResponse(), com.neuronrobotics.sdk.namespace.bcs.pid.LegacyPidNamespaceImp.onAsyncResponse(), com.neuronrobotics.sdk.namespace.bcs.pid.PidNamespaceImp.onAsyncResponse(), com.neuronrobotics.sdk.common.RpcEncapsulation.parseResponse(), com.neuronrobotics.sdk.pid.PDVelocityConfiguration.PDVelocityConfiguration(), com.neuronrobotics.sdk.pid.PIDConfiguration.PIDConfiguration(), com.neuronrobotics.sdk.pid.PIDEvent.PIDEvent(), com.neuronrobotics.sdk.pid.PIDLimitEvent.PIDLimitEvent(), com.neuronrobotics.sdk.dyio.DyIO.powerEvent(), com.neuronrobotics.sdk.dyio.DyIOChannel.resync(), com.neuronrobotics.sdk.common.BowlerDatagram.toString(), com.neuronrobotics.sdk.dyio.peripherals.PPMReaderChannel.updateValues(), and com.neuronrobotics.sdk.dyio.peripherals.SPIChannel.write().
getDataCrc() [1/2]
byte com.neuronrobotics.sdk.common.BowlerDatagram.getDataCrc () private
Gets the data crc.
Returns
the data crc
Definition at line 186 of file BowlerDatagram.java.
References com.neuronrobotics.sdk.common.BowlerDatagram.checkValidPacket(), and com.neuronrobotics.sdk.common.BowlerDatagram.dataCrc.
Referenced by com.neuronrobotics.sdk.common.BowlerDatagram.getBytes(), and com.neuronrobotics.sdk.common.BowlerDatagram.toString().
getDataCrc() [2/2]
static byte com.neuronrobotics.sdk.common.BowlerDatagram.getDataCrc (ByteList data) static private
Assumes the packet starts at byte 0.
Parameters
data the data
Returns
the byte holding the header crc
Definition at line 177 of file BowlerDatagram.java.
References com.neuronrobotics.sdk.common.BowlerDatagram.data, com.neuronrobotics.sdk.common.ByteList.getByte(), com.neuronrobotics.sdk.common.ByteList.getUnsigned(), and com.neuronrobotics.sdk.common.BowlerDatagram.HEADER_SIZE.
getMethod()
BowlerMethod com.neuronrobotics.sdk.common.BowlerDatagram.getMethod ()
Get the datagram's current method.
Returns
the current method
Definition at line 318 of file BowlerDatagram.java.
References com.neuronrobotics.sdk.common.BowlerDatagram.checkValidPacket(), and com.neuronrobotics.sdk.common.BowlerDatagram.method.
Referenced by com.neuronrobotics.sdk.common.device.server.BowlerAbstractDeviceServerNamespace.checkRpc(), com.neuronrobotics.sdk.common.BowlerDatagram.getBytes(), com.neuronrobotics.sdk.common.BowlerDatagram.isSyncronous(), com.neuronrobotics.sdk.common.BowlerDatagram.parse(), com.neuronrobotics.sdk.common.device.server.BowlerAbstractDeviceServerNamespace.process(), and com.neuronrobotics.sdk.common.BowlerDatagram.toString().
getNamespaceResolutionID()
byte com.neuronrobotics.sdk.common.BowlerDatagram.getNamespaceResolutionID ()
Get the datagram's current transaction id.
Returns
the current transaction id
Definition at line 328 of file BowlerDatagram.java.
References com.neuronrobotics.sdk.common.BowlerDatagram.checkValidPacket(), and com.neuronrobotics.sdk.common.BowlerDatagram.namespaceResolutionID.
Referenced by com.neuronrobotics.sdk.common.BowlerDatagram.getSessionID(), and com.neuronrobotics.sdk.common.BowlerDatagram.getTransactionUpstream().
getPayload()
ByteList com.neuronrobotics.sdk.common.BowlerDatagram.getPayload ()
Get the payload including the RPC.
Returns
byte list of the paload
Definition at line 288 of file BowlerDatagram.java.
References com.neuronrobotics.sdk.common.BowlerDatagram.checkValidPacket(), com.neuronrobotics.sdk.common.BowlerDatagram.data, and com.neuronrobotics.sdk.common.ByteList.getBytes().
getRevision()
byte com.neuronrobotics.sdk.common.BowlerDatagram.getRevision ()
Get the datagram's current revision.
Returns
the current revision
Definition at line 308 of file BowlerDatagram.java.
References com.neuronrobotics.sdk.common.BowlerDatagram.checkValidPacket(), and com.neuronrobotics.sdk.common.BowlerDatagram.REVISION.
getRPC()
String com.neuronrobotics.sdk.common.BowlerDatagram.getRPC ()
Gets the String representation of the datagram's RPC.
Returns
A string representation of the datagram's RPC
Definition at line 380 of file BowlerDatagram.java.
References com.neuronrobotics.sdk.common.BowlerDatagram.checkValidPacket(), com.neuronrobotics.sdk.common.BowlerDatagram.data, and com.neuronrobotics.sdk.common.ByteList.getBytes().
Referenced by com.neuronrobotics.sdk.common.device.server.BowlerAbstractDeviceServerNamespace.checkRpc(), com.neuronrobotics.sdk.common.BowlerAbstractConnection.getRpcList(), com.neuronrobotics.sdk.common.device.server.BowlerAbstractDeviceServer.onAllResponse(), com.neuronrobotics.sdk.bowlercam.device.BowlerCamDevice.onAsyncResponse(), com.neuronrobotics.sdk.dyio.DyIO.onAsyncResponse(), com.neuronrobotics.sdk.namespace.bcs.pid.LegacyPidNamespaceImp.onAsyncResponse(), com.neuronrobotics.sdk.namespace.bcs.pid.PidNamespaceImp.onAsyncResponse(), com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.onSyncReceive(), com.neuronrobotics.sdk.pid.PIDEvent.PIDEvent(), com.neuronrobotics.sdk.pid.PIDLimitEvent.PIDLimitEvent(), com.neuronrobotics.sdk.dyio.DyIO.powerEvent(), com.neuronrobotics.sdk.common.device.server.BowlerAbstractDeviceServerNamespace.process(), com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.processLocal(), com.neuronrobotics.sdk.common.BowlerDatagram.toString(), and com.neuronrobotics.sdk.bootloader.NRBootLoader.write().
getSessionID()
int com.neuronrobotics.sdk.common.BowlerDatagram.getSessionID () private
Gets the Datagram's Session ID.
Returns
The Session ID
Definition at line 395 of file BowlerDatagram.java.
References com.neuronrobotics.sdk.common.BowlerDatagram.checkValidPacket(), and com.neuronrobotics.sdk.common.BowlerDatagram.getNamespaceResolutionID().
Referenced by com.neuronrobotics.sdk.common.BowlerDatagram.toString().
getTimestamp()
long com.neuronrobotics.sdk.common.BowlerDatagram.getTimestamp ()
Gets the timestamp.
Returns
the timestamp
Definition at line 514 of file BowlerDatagram.java.
References com.neuronrobotics.sdk.common.BowlerDatagram.checkValidPacket(), com.neuronrobotics.sdk.common.ThreadedTimeout.getStartTime(), and com.neuronrobotics.sdk.common.BowlerDatagram.timeout.
getTransactionUpstream()
byte com.neuronrobotics.sdk.common.BowlerDatagram.getTransactionUpstream ()
Gets the transaction upstream.
Returns
the transaction upstream
Definition at line 361 of file BowlerDatagram.java.
References com.neuronrobotics.sdk.common.BowlerDatagram.checkValidPacket(), com.neuronrobotics.sdk.common.BowlerDatagram.getNamespaceResolutionID(), and com.neuronrobotics.sdk.common.BowlerDatagram.isUpstream().
Referenced by com.neuronrobotics.sdk.common.BowlerDatagram.getBytes().
isFree()
boolean com.neuronrobotics.sdk.common.BowlerDatagram.isFree ()
Checks if is free.
Returns
true, if is free
Definition at line 603 of file BowlerDatagram.java.
References com.neuronrobotics.sdk.common.BowlerDatagram.isPackedAvailibleForLoading.
Referenced by com.neuronrobotics.sdk.common.BowlerDatagram.checkValidPacket(), com.neuronrobotics.sdk.common.BowlerDatagram.onTimeout(), com.neuronrobotics.sdk.common.BowlerDatagram.setFree(), com.neuronrobotics.sdk.common.BowlerDatagram.toString(), and com.neuronrobotics.sdk.common.BowlerDatagram.validate().
isSyncronous()
boolean com.neuronrobotics.sdk.common.BowlerDatagram.isSyncronous ()
Determines if the datagram is being sent synchronously or not.
Returns
true if Synchronous
Definition at line 338 of file BowlerDatagram.java.
References com.neuronrobotics.sdk.common.BowlerMethod.ASYNCHRONOUS, com.neuronrobotics.sdk.common.BowlerDatagram.checkValidPacket(), and com.neuronrobotics.sdk.common.BowlerDatagram.getMethod().
Referenced by com.neuronrobotics.sdk.common.BowlerAbstractConnection.fireAsyncOnResponse(), com.neuronrobotics.sdk.common.BowlerAbstractConnection.fireSyncOnReceive(), com.neuronrobotics.sdk.common.BowlerAbstractConnection.onDataReceived(), and com.neuronrobotics.sdk.common.BowlerAbstractConnection.QueueManager.run().
isUpstream()
boolean com.neuronrobotics.sdk.common.BowlerDatagram.isUpstream ()
Checks if is upstream.
Returns
true, if is upstream
Definition at line 351 of file BowlerDatagram.java.
References com.neuronrobotics.sdk.common.BowlerDatagram.checkValidPacket(), and com.neuronrobotics.sdk.common.BowlerDatagram.upstream.
Referenced by com.neuronrobotics.sdk.common.BowlerDatagram.getTransactionUpstream(), com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.onSyncReceive(), and com.neuronrobotics.sdk.common.BowlerDatagram.toString().
isUseBowlerV4()
static boolean com.neuronrobotics.sdk.common.BowlerDatagram.isUseBowlerV4 () static
Checks if is use bowler v4.
Returns
true, if is use bowler v4
Definition at line 689 of file BowlerDatagram.java.
References com.neuronrobotics.sdk.common.BowlerDatagram.useBowlerV4.
Referenced by com.neuronrobotics.sdk.common.BowlerDatagram.getBytes(), com.neuronrobotics.sdk.common.BowlerAbstractConnection.sendSynchronusly(), and com.neuronrobotics.sdk.common.BowlerDatagram.toString().
onTimeout()
void com.neuronrobotics.sdk.common.BowlerDatagram.onTimeout (String message)
On timeout.
Parameters
message the message
Implements com.neuronrobotics.sdk.common.IthreadedTimoutListener.
Definition at line 652 of file BowlerDatagram.java.
References com.neuronrobotics.sdk.common.Log.error(), com.neuronrobotics.sdk.common.ThreadedTimeout.getAmountOfTimeForTimerToRun(), com.neuronrobotics.sdk.common.ThreadedTimeout.getStartTime(), com.neuronrobotics.sdk.common.ThreadedTimeout.initialize(), com.neuronrobotics.sdk.common.BowlerDatagram.isFree(), com.neuronrobotics.sdk.common.BowlerDatagram.setFree(), and com.neuronrobotics.sdk.common.BowlerDatagram.timeout.
parse()
void com.neuronrobotics.sdk.common.BowlerDatagram.parse (ByteList raw)
Breaks a chunk of data into the proper Bowler datagram fields.
Parameters
raw the chunk of data
Definition at line 231 of file BowlerDatagram.java.
References com.neuronrobotics.sdk.common.BowlerDatagram.checkValidPacket(), com.neuronrobotics.sdk.common.Log.error(), com.neuronrobotics.sdk.common.BowlerMethod.get(), com.neuronrobotics.sdk.common.ByteList.getByte(), com.neuronrobotics.sdk.common.ByteList.getBytes(), com.neuronrobotics.sdk.common.BowlerDatagram.getCRC(), com.neuronrobotics.sdk.common.BowlerDatagram.getMethod(), com.neuronrobotics.sdk.common.ByteList.getUnsigned(), com.neuronrobotics.sdk.common.BowlerDatagram.HEADER_SIZE, com.neuronrobotics.sdk.common.BowlerDatagram.REVISION, com.neuronrobotics.sdk.common.BowlerDatagram.setAddress(), com.neuronrobotics.sdk.common.BowlerDatagram.setCrc(), com.neuronrobotics.sdk.common.BowlerDatagram.setData(), com.neuronrobotics.sdk.common.BowlerDatagram.setDataCrc(), com.neuronrobotics.sdk.common.BowlerDatagram.setFree(), com.neuronrobotics.sdk.common.BowlerDatagram.setMethod(), com.neuronrobotics.sdk.common.BowlerDatagram.setNamespaceResolutionID(), com.neuronrobotics.sdk.common.BowlerDatagram.setUpstream(), com.neuronrobotics.sdk.common.ByteList.size(), and com.neuronrobotics.sdk.common.BowlerMethod.STATUS.
Referenced by com.neuronrobotics.sdk.common.BowlerDatagram.BowlerDatagram().
setAddress()
void com.neuronrobotics.sdk.common.BowlerDatagram.setAddress (MACAddress address)
Sets the address.
Parameters
address the new address
Definition at line 544 of file BowlerDatagram.java.
References com.neuronrobotics.sdk.common.BowlerDatagram.address, and com.neuronrobotics.sdk.common.BowlerDatagram.checkValidPacket().
Referenced by com.neuronrobotics.sdk.common.BowlerDatagram.parse().
setAsAsync()
void com.neuronrobotics.sdk.common.BowlerDatagram.setAsAsync (int id)
Sets the as async.
Parameters
id the new as async
Definition at line 524 of file BowlerDatagram.java.
References com.neuronrobotics.sdk.common.BowlerMethod.ASYNCHRONOUS, com.neuronrobotics.sdk.common.BowlerDatagram.checkValidPacket(), com.neuronrobotics.sdk.common.BowlerDatagram.setMethod(), and com.neuronrobotics.sdk.common.BowlerDatagram.setNamespaceResolutionID().
setCrc()
void com.neuronrobotics.sdk.common.BowlerDatagram.setCrc (byte crc) private
Sets the crc.
Parameters
crc the new crc
Definition at line 155 of file BowlerDatagram.java.
References com.neuronrobotics.sdk.common.BowlerDatagram.checkValidPacket(), and com.neuronrobotics.sdk.common.BowlerDatagram.crc.
Referenced by com.neuronrobotics.sdk.common.BowlerDatagram.getBytes(), and com.neuronrobotics.sdk.common.BowlerDatagram.parse().
setData()
void com.neuronrobotics.sdk.common.BowlerDatagram.setData (byte[] bs)
Sets the data.
Parameters
bs the new data
Definition at line 277 of file BowlerDatagram.java.
References com.neuronrobotics.sdk.common.ByteList.add(), com.neuronrobotics.sdk.common.BowlerDatagram.checkValidPacket(), com.neuronrobotics.sdk.common.ByteList.clear(), and com.neuronrobotics.sdk.common.BowlerDatagram.data.
Referenced by com.neuronrobotics.sdk.common.BowlerDatagram.parse().
setDataCrc()
void com.neuronrobotics.sdk.common.BowlerDatagram.setDataCrc (byte crc) private
Sets the data crc.
Parameters
crc the new data crc
Definition at line 197 of file BowlerDatagram.java.
References com.neuronrobotics.sdk.common.BowlerDatagram.checkValidPacket(), and com.neuronrobotics.sdk.common.BowlerDatagram.crc.
Referenced by com.neuronrobotics.sdk.common.BowlerDatagram.getBytes(), and com.neuronrobotics.sdk.common.BowlerDatagram.parse().
setFree()
void com.neuronrobotics.sdk.common.BowlerDatagram.setFree (boolean isFree, BowlerDatagramFactory factory)
Sets the free.
Parameters
isFree the is free
factory the factory
Definition at line 614 of file BowlerDatagram.java.
References com.neuronrobotics.sdk.common.BowlerDatagram.isFree().
Referenced by com.neuronrobotics.sdk.common.BowlerDatagram.BowlerDatagram(), com.neuronrobotics.sdk.common.BowlerDatagram.checkValidPacket(), com.neuronrobotics.sdk.common.BowlerDatagram.onTimeout(), and com.neuronrobotics.sdk.common.BowlerDatagram.parse().
setMethod()
void com.neuronrobotics.sdk.common.BowlerDatagram.setMethod (BowlerMethod method)
Sets the method.
Parameters
method the new method
Definition at line 555 of file BowlerDatagram.java.
References com.neuronrobotics.sdk.common.BowlerDatagram.checkValidPacket(), and com.neuronrobotics.sdk.common.BowlerDatagram.method.
Referenced by com.neuronrobotics.sdk.common.BowlerDatagram.parse(), and com.neuronrobotics.sdk.common.BowlerDatagram.setAsAsync().
setNamespaceResolutionID()
void com.neuronrobotics.sdk.common.BowlerDatagram.setNamespaceResolutionID (byte namespaceResolutionID)
Sets the namespace resolution id.
Parameters
namespaceResolutionID the new namespace resolution id
Definition at line 566 of file BowlerDatagram.java.
References com.neuronrobotics.sdk.common.BowlerDatagram.checkValidPacket(), and com.neuronrobotics.sdk.common.BowlerDatagram.namespaceResolutionID.
Referenced by com.neuronrobotics.sdk.common.BowlerDatagram.parse(), and com.neuronrobotics.sdk.common.BowlerDatagram.setAsAsync().
setNotFree()
void com.neuronrobotics.sdk.common.BowlerDatagram.setNotFree () private
Sets the not free.
Definition at line 622 of file BowlerDatagram.java.
References com.neuronrobotics.sdk.common.BowlerDatagram.clear(), com.neuronrobotics.sdk.common.ThreadedTimeout.stop(), and com.neuronrobotics.sdk.common.BowlerDatagram.timeout.
setRpc()
void com.neuronrobotics.sdk.common.BowlerDatagram.setRpc (String opCode)
Sets the rpc.
Parameters
opCode the new rpc
Definition at line 679 of file BowlerDatagram.java.
setToFree()
void com.neuronrobotics.sdk.common.BowlerDatagram.setToFree () private
Sets the to free.
Definition at line 630 of file BowlerDatagram.java.
References com.neuronrobotics.sdk.common.ThreadedTimeout.initialize(), and com.neuronrobotics.sdk.common.BowlerDatagram.timeout.
setUpstream()
void com.neuronrobotics.sdk.common.BowlerDatagram.setUpstream (boolean upstream)
Sets the upstream.
Parameters
upstream the new upstream
Definition at line 577 of file BowlerDatagram.java.
References com.neuronrobotics.sdk.common.BowlerDatagram.calcCRC(), com.neuronrobotics.sdk.common.BowlerDatagram.checkValidPacket(), and com.neuronrobotics.sdk.common.BowlerDatagram.upstream.
Referenced by com.neuronrobotics.sdk.common.BowlerDatagram.parse(), and com.neuronrobotics.sdk.common.BowlerAbstractConnection.sendSynchronusly().
setUseBowlerV4()
static void com.neuronrobotics.sdk.common.BowlerDatagram.setUseBowlerV4 (boolean useBowlerV4) static
Sets the use bowler v4.
Parameters
useBowlerV4 the new use bowler v4
Definition at line 698 of file BowlerDatagram.java.
References com.neuronrobotics.sdk.common.BowlerDatagram.useBowlerV4, and com.neuronrobotics.sdk.common.Log.warning().
Referenced by com.neuronrobotics.sdk.common.DeviceManager.addConnection(), and com.neuronrobotics.sdk.common.BowlerAbstractConnection.sendSynchronusly().
toString()
String com.neuronrobotics.sdk.common.BowlerDatagram.toString ()
Definition at line 438 of file BowlerDatagram.java.
References com.neuronrobotics.sdk.common.BowlerDatagram.data, com.neuronrobotics.sdk.common.BowlerDatagram.getAddress(), com.neuronrobotics.sdk.common.BowlerDatagram.getBytes(), com.neuronrobotics.sdk.common.BowlerDatagram.getCrc(), com.neuronrobotics.sdk.common.BowlerDatagram.getData(), com.neuronrobotics.sdk.common.BowlerDatagram.getDataCrc(), com.neuronrobotics.sdk.common.BowlerDatagram.getMethod(), com.neuronrobotics.sdk.common.BowlerDatagram.getRPC(), com.neuronrobotics.sdk.common.BowlerDatagram.getSessionID(), com.neuronrobotics.sdk.common.BowlerDatagram.isFree(), com.neuronrobotics.sdk.common.Log.isPrinting(), com.neuronrobotics.sdk.common.BowlerDatagram.isUpstream(), com.neuronrobotics.sdk.common.BowlerDatagram.isUseBowlerV4(), com.neuronrobotics.sdk.common.BowlerDatagram.REVISION, and com.neuronrobotics.sdk.common.ByteList.size().
Referenced by com.neuronrobotics.sdk.dyio.DyIO.onAsyncResponse(), and com.neuronrobotics.sdk.dyio.DyIOAsyncEvent.toString().
validate()
void com.neuronrobotics.sdk.common.BowlerDatagram.validate (BowlerDatagramFactory factory) private
Validate.
Parameters
factory the factory
Definition at line 219 of file BowlerDatagram.java.
References com.neuronrobotics.sdk.common.ThreadedTimeout.initialize(), com.neuronrobotics.sdk.common.BowlerDatagram.isFree(), and com.neuronrobotics.sdk.common.BowlerDatagram.timeout.
Referenced by com.neuronrobotics.sdk.common.BowlerDatagram.BowlerDatagram().
Member Data Documentation
address
MACAddress com.neuronrobotics.sdk.common.BowlerDatagram.address = new MACAddress() private
The address.
Definition at line 56 of file BowlerDatagram.java.
Referenced by com.neuronrobotics.sdk.common.BowlerDatagram.getAddress(), and com.neuronrobotics.sdk.common.BowlerDatagram.setAddress().
crc
byte com.neuronrobotics.sdk.common.BowlerDatagram.crc private
The crc.
Definition at line 68 of file BowlerDatagram.java.
Referenced by com.neuronrobotics.sdk.common.BowlerDatagram.getCrc(), com.neuronrobotics.sdk.common.BowlerDatagram.setCrc(), and com.neuronrobotics.sdk.common.BowlerDatagram.setDataCrc().
CRC_INDEX
final int com.neuronrobotics.sdk.common.BowlerDatagram.CRC_INDEX = 10 static
The Constant CRC_INDEX.
Definition at line 50 of file BowlerDatagram.java.
Referenced by com.neuronrobotics.sdk.common.BowlerDatagram.getCRC().
data
ByteList com.neuronrobotics.sdk.common.BowlerDatagram.data = new ByteList() private
The data.
Definition at line 74 of file BowlerDatagram.java.
Referenced by com.neuronrobotics.sdk.common.BowlerDatagram.BowlerDatagram(), com.neuronrobotics.sdk.common.BowlerDatagram.clear(), com.neuronrobotics.sdk.common.BowlerDatagram.genCrc(), com.neuronrobotics.sdk.common.BowlerDatagram.genCRC(), com.neuronrobotics.sdk.common.BowlerDatagram.genDataCrc(), com.neuronrobotics.sdk.common.BowlerDatagram.getBytes(), com.neuronrobotics.sdk.common.BowlerDatagram.getCRC(), com.neuronrobotics.sdk.common.BowlerDatagram.getData(), com.neuronrobotics.sdk.common.BowlerDatagram.getDataCrc(), com.neuronrobotics.sdk.common.BowlerDatagram.getPayload(), com.neuronrobotics.sdk.common.BowlerDatagram.getRPC(), com.neuronrobotics.sdk.common.BowlerDatagram.setData(), and com.neuronrobotics.sdk.common.BowlerDatagram.toString().
dataCrc
byte com.neuronrobotics.sdk.common.BowlerDatagram.dataCrc private
The Data crc.
Definition at line 71 of file BowlerDatagram.java.
Referenced by com.neuronrobotics.sdk.common.BowlerDatagram.getDataCrc().
HEADER_SIZE
final int com.neuronrobotics.sdk.common.BowlerDatagram.HEADER_SIZE = 11 static
The Constant HEADER_SIZE.
Definition at line 47 of file BowlerDatagram.java.
Referenced by com.neuronrobotics.sdk.common.BowlerDatagram.genCrc(), com.neuronrobotics.sdk.common.BowlerDatagram.genDataCrc(), com.neuronrobotics.sdk.common.BowlerDatagram.getDataCrc(), and com.neuronrobotics.sdk.common.BowlerDatagram.parse().
isPackedAvailibleForLoading
boolean com.neuronrobotics.sdk.common.BowlerDatagram.isPackedAvailibleForLoading = true private
time of instantiation *.
Definition at line 80 of file BowlerDatagram.java.
Referenced by com.neuronrobotics.sdk.common.BowlerDatagram.isFree().
MAX_PACKET_SIZE
final int com.neuronrobotics.sdk.common.BowlerDatagram.MAX_PACKET_SIZE = HEADER_SIZE+255 static
The Constant MAX_PACKET_SIZE.
Definition at line 53 of file BowlerDatagram.java.
method
BowlerMethod com.neuronrobotics.sdk.common.BowlerDatagram.method private
The method.
Definition at line 59 of file BowlerDatagram.java.
Referenced by com.neuronrobotics.sdk.common.BowlerDatagram.getMethod(), and com.neuronrobotics.sdk.common.BowlerDatagram.setMethod().
namespaceResolutionID
byte com.neuronrobotics.sdk.common.BowlerDatagram.namespaceResolutionID private
The transaction id.
Definition at line 62 of file BowlerDatagram.java.
Referenced by com.neuronrobotics.sdk.common.BowlerDatagram.getNamespaceResolutionID(), and com.neuronrobotics.sdk.common.BowlerDatagram.setNamespaceResolutionID().
REVISION
final byte com.neuronrobotics.sdk.common.BowlerDatagram.REVISION = 3 static
The Constant REVISION.
Definition at line 44 of file BowlerDatagram.java.
Referenced by com.neuronrobotics.sdk.common.BowlerDatagram.getBytes(), com.neuronrobotics.sdk.common.BowlerDatagram.getRevision(), com.neuronrobotics.sdk.common.BowlerDatagram.parse(), and com.neuronrobotics.sdk.common.BowlerDatagram.toString().
timeout
ThreadedTimeout com.neuronrobotics.sdk.common.BowlerDatagram.timeout =new ThreadedTimeout() private
The timeout.
Definition at line 83 of file BowlerDatagram.java.
Referenced by com.neuronrobotics.sdk.common.BowlerDatagram.checkValidPacket(), com.neuronrobotics.sdk.common.BowlerDatagram.getTimestamp(), com.neuronrobotics.sdk.common.BowlerDatagram.onTimeout(), com.neuronrobotics.sdk.common.BowlerDatagram.setNotFree(), com.neuronrobotics.sdk.common.BowlerDatagram.setToFree(), and com.neuronrobotics.sdk.common.BowlerDatagram.validate().
upstream
boolean com.neuronrobotics.sdk.common.BowlerDatagram.upstream private
The upstream.
Definition at line 65 of file BowlerDatagram.java.
Referenced by com.neuronrobotics.sdk.common.BowlerDatagram.isUpstream(), and com.neuronrobotics.sdk.common.BowlerDatagram.setUpstream().
useBowlerV4
boolean com.neuronrobotics.sdk.common.BowlerDatagram.useBowlerV4 =true static private
The use bowler v4.
Definition at line 86 of file BowlerDatagram.java.
Referenced by com.neuronrobotics.sdk.common.BowlerDatagram.isUseBowlerV4(), and com.neuronrobotics.sdk.common.BowlerDatagram.setUseBowlerV4().
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/common/BowlerDatagram.java