BowlerKernel: com.neuronrobotics.sdk.addons.kinematics.SearchTreeSolver.configuration Class Reference
com.neuronrobotics.sdk.addons.kinematics.SearchTreeSolver.configuration Class Reference
Public Member Functions
configuration (double[] joints, TransformNR t)
TransformNR getTransform ()
double[] getJoints ()
double getOffsetOrentationMagnitude ()
double getOffsetVectorMagnitude ()
boolean same (configuration c)
String toString ()
Private Attributes
final double[] joints
TransformNR transform
final TransformNR target
Detailed Description
The Class configuration.
Definition at line 224 of file SearchTreeSolver.java.
Constructor & Destructor Documentation
configuration()
com.neuronrobotics.sdk.addons.kinematics.SearchTreeSolver.configuration.configuration (double[] joints, TransformNR t)
Instantiates a new configuration.
Parameters
joints the joints
t the t
Definition at line 247 of file SearchTreeSolver.java.
References com.neuronrobotics.sdk.addons.kinematics.SearchTreeSolver.configuration.joints, and com.neuronrobotics.sdk.addons.kinematics.SearchTreeSolver.configuration.target.
Member Function Documentation
getJoints()
double [] com.neuronrobotics.sdk.addons.kinematics.SearchTreeSolver.configuration.getJoints ()
Gets the joints.
Returns
the joints
Definition at line 271 of file SearchTreeSolver.java.
References com.neuronrobotics.sdk.addons.kinematics.SearchTreeSolver.configuration.joints.
Referenced by com.neuronrobotics.sdk.addons.kinematics.SearchTreeSolver.configuration.getTransform(), com.neuronrobotics.sdk.addons.kinematics.SearchTreeSolver.inverseKinematics(), and com.neuronrobotics.sdk.addons.kinematics.SearchTreeSolver.configuration.same().
getOffsetOrentationMagnitude()
double com.neuronrobotics.sdk.addons.kinematics.SearchTreeSolver.configuration.getOffsetOrentationMagnitude ()
Gets the offset orentation magnitude.
Returns
the offset orentation magnitude
Definition at line 280 of file SearchTreeSolver.java.
References com.neuronrobotics.sdk.addons.kinematics.SearchTreeSolver.configuration.getTransform().
Referenced by com.neuronrobotics.sdk.addons.kinematics.SearchTreeSolver.inverseKinematics().
getOffsetVectorMagnitude()
double com.neuronrobotics.sdk.addons.kinematics.SearchTreeSolver.configuration.getOffsetVectorMagnitude ()
Gets the offset vector magnitude.
Returns
the offset vector magnitude
Definition at line 290 of file SearchTreeSolver.java.
References com.neuronrobotics.sdk.addons.kinematics.SearchTreeSolver.configuration.getTransform().
Referenced by com.neuronrobotics.sdk.addons.kinematics.SearchTreeSolver.inverseKinematics().
getTransform()
TransformNR com.neuronrobotics.sdk.addons.kinematics.SearchTreeSolver.configuration.getTransform ()
Gets the transform.
Returns
the transform
Definition at line 257 of file SearchTreeSolver.java.
References com.neuronrobotics.sdk.addons.kinematics.SearchTreeSolver.fk(), com.neuronrobotics.sdk.addons.kinematics.SearchTreeSolver.configuration.getJoints(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getOffsetOrentationMagnitude(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getOffsetVectorMagnitude(), com.neuronrobotics.sdk.addons.kinematics.SearchTreeSolver.configuration.target, and com.neuronrobotics.sdk.addons.kinematics.SearchTreeSolver.configuration.transform.
Referenced by com.neuronrobotics.sdk.addons.kinematics.SearchTreeSolver.configuration.getOffsetOrentationMagnitude(), com.neuronrobotics.sdk.addons.kinematics.SearchTreeSolver.configuration.getOffsetVectorMagnitude(), and com.neuronrobotics.sdk.addons.kinematics.SearchTreeSolver.configuration.toString().
same()
boolean com.neuronrobotics.sdk.addons.kinematics.SearchTreeSolver.configuration.same (configuration c)
Same.
Parameters
c the c
Returns
true, if successful
Definition at line 301 of file SearchTreeSolver.java.
References com.neuronrobotics.sdk.addons.kinematics.SearchTreeSolver.configuration.getJoints().
Referenced by com.neuronrobotics.sdk.addons.kinematics.SearchTreeSolver.searchTree.getBest().
toString()
String com.neuronrobotics.sdk.addons.kinematics.SearchTreeSolver.configuration.toString ()
Definition at line 314 of file SearchTreeSolver.java.
References com.neuronrobotics.sdk.addons.kinematics.SearchTreeSolver.configuration.getTransform(), com.neuronrobotics.sdk.addons.kinematics.SearchTreeSolver.configuration.target, and com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.toString().
Member Data Documentation
joints
final double [] com.neuronrobotics.sdk.addons.kinematics.SearchTreeSolver.configuration.joints private
The joints.
Definition at line 227 of file SearchTreeSolver.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.SearchTreeSolver.configuration.configuration(), and com.neuronrobotics.sdk.addons.kinematics.SearchTreeSolver.configuration.getJoints().
target
final TransformNR com.neuronrobotics.sdk.addons.kinematics.SearchTreeSolver.configuration.target private
The target.
Definition at line 233 of file SearchTreeSolver.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.SearchTreeSolver.configuration.configuration(), com.neuronrobotics.sdk.addons.kinematics.SearchTreeSolver.configuration.getTransform(), and com.neuronrobotics.sdk.addons.kinematics.SearchTreeSolver.configuration.toString().
transform
TransformNR com.neuronrobotics.sdk.addons.kinematics.SearchTreeSolver.configuration.transform private
The transform.
Definition at line 230 of file SearchTreeSolver.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.SearchTreeSolver.configuration.getTransform().
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/addons/kinematics/SearchTreeSolver.java