BowlerKernel: com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup Class Reference
com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup Class Reference
Public Member Functions
TransformNR getTipOffsetFromThisLinkInLimb (DHParameterKinematics control, int index)
ParallelGroup (String name)
void addLimb (DHParameterKinematics limb, TransformNR tip, String name, int index)
DHParameterKinematics getFKLimb ()
TransformNR calcHome ()
void setupReferencedLimb (DHParameterKinematics limb, TransformNR tip, String name, int index)
void setupReferencedLimbStartup (DHParameterKinematics limb, TransformNR tip, String name, int index)
void clearReferencedLimb (DHParameterKinematics limb)
void disconnectDevice ()
boolean connectDevice ()
void setCurrentPoseTarget (TransformNR currentPoseTarget)
double[] getCurrentJointSpaceVector (DHParameterKinematics k)
double[] inverseKinematics (TransformNR taskSpaceTransform) throws Exception
void printError (TransformNR taskSpaceTransform) throws Exception
void printError (TransformNR taskSpaceTransform, Consumer< String > printer) throws Exception
TransformNR forwardKinematics (double[] jointSpaceVector)
String[] getGitCadToolEngine ()
void setGitCadToolEngine (String[] cadEngine)
ArrayList< DHParameterKinematics > getConstituantLimbs ()
HashMap< DHParameterKinematics, TransformNR > getTipOffset ()
TransformNR getTipOffset (DHParameterKinematics l)
void setTipOffset (DHParameterKinematics l, TransformNR n)
String getTipOffsetRelativeName (DHParameterKinematics l)
int getTipOffsetRelativeIndex (DHParameterKinematics l)
void setTipOffset (HashMap< DHParameterKinematics, TransformNR > tipOffset)
void removeLimb (DHParameterKinematics limb)
String getNameOfParallelGroup ()
void close ()
Public Member Functions inherited from com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics
DHParameterKinematics (BowlerAbstractDevice bad, Element linkStream)
DHParameterKinematics (BowlerAbstractDevice bad, InputStream linkStream)
DHParameterKinematics (BowlerAbstractDevice bad, InputStream linkStream, InputStream depricated)
DHParameterKinematics (BowlerAbstractDevice bad)
DHParameterKinematics (BowlerAbstractDevice bad, String file)
DHParameterKinematics (BowlerAbstractDevice bad, File configFile) throws FileNotFoundException
DHParameterKinematics ()
DHParameterKinematics (String file)
DHParameterKinematics (Element linkStream)
DHParameterKinematics (File configFile) throws FileNotFoundException
Matrix getJacobian (DHChain chain, double[] jointSpaceVector, int index)
Matrix getJacobian ()
Matrix getJacobian (int index)
Matrix getJacobian (double[] jointSpaceVector, int index)
ArrayList< TransformNR > getChainTransformations ()
void setDhChain (DHChain chain)
DHChain getDhChain ()
DHChain getChain ()
void setChain (DHChain chain)
String getXml ()
String getEmbedableXml ()
void onTaskSpaceUpdate (AbstractKinematicsNR source, TransformNR pose)
void onTargetTaskSpaceUpdate (AbstractKinematicsNR source, TransformNR pose)
DhInverseSolver getInverseSolver ()
void setInverseSolver (DhInverseSolver inverseSolver)
Object getCurrentTargetObject ()
void addNewLink (LinkConfiguration newLink, DHLink dhLink)
void removeLink (int index)
ArrayList< TransformNR > updateCadLocations ()
void onJointSpaceUpdate (final AbstractKinematicsNR source, final double[] joints)
void setGlobalToFiducialTransform (TransformNR frameToBase)
void onJointSpaceTargetUpdate (AbstractKinematicsNR source, double[] joints)
void onJointSpaceLimit (AbstractKinematicsNR source, int axis, JointLimit event)
TransformNR linkCoM (double linkAngleToClaculate, int linkIndex)
TransformNR linkCoM (int linkIndex)
Object getLinkObjectManipulator (int index)
double getDH_Theta (int index)
double getDH_D (int index)
double getDH_R (int index)
double getDH_Alpha (int index)
void setDH_Theta (int index, double value)
void setDH_D (int index, double value)
void setDH_R (int index, double value)
void setDH_Alpha (int index, double value)
DHLink getDhLink (int i)
Object getListener (int i)
void setRobotToFiducialTransform (TransformNR newTrans)
void refreshPose ()
MobileBase getSlaveMobileBase (int index)
void throwExceptionOnJointLimit (boolean b)
TransformNR getLinkTip (int linkIndex)
Public Member Functions inherited from com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR
Object getRootListener ()
void setRootListener (Object listener)
ArrayList< String > getNamespacesImp ()
void disconnectDeviceImp ()
boolean connectDeviceImp ()
AbstractKinematicsNR ()
AbstractKinematicsNR (InputStream configFile, LinkFactory f)
AbstractKinematicsNR (Element doc, LinkFactory f)
LinkConfiguration getLinkConfiguration (int linkIndex)
ArrayList< LinkConfiguration > getLinkConfigurations ()
PIDConfiguration getLinkCurrentConfiguration (int chan)
void setLinkCurrentConfiguration (int chan, PIDConfiguration c)
AbstractLink getAbstractLink (int index)
int getNumberOfLinks ()
TransformNR getCurrentTaskSpaceTransform ()
double readLinkValue (int index)
double readLinkTarget (int index)
double[] getCurrentJointSpaceVector ()
double[] getCurrentJointSpaceTarget ()
double getCurrentLinkEngineeringUnits (int linkIndex)
double[] setDesiredTaskSpaceTransform (TransformNR taskSpaceTransform, double seconds) throws Exception
boolean checkTaskSpaceTransform (TransformNR taskSpaceTransform, double seconds)
boolean checkTaskSpaceTransform (TransformNR taskSpaceTransform)
double getBestTime (TransformNR currentTaskSpaceTransform)
double getBestTime (double[] jointSpaceVect)
double[] setDesiredJointSpaceVector (double[] jointSpaceVect, double seconds) throws Exception
TransformNR calcForward (double[] jointSpaceVect)
void setDesiredJointAxisValue (int axis, double value, double seconds) throws Exception
void firePoseUpdate ()
TransformNR getFiducialToGlobalTransform ()
TransformNR getRobotToFiducialTransform ()
void setGlobalToFiducialTransform (TransformNR frameToBase, boolean fireUpdate)
TransformNR inverseOffset (TransformNR t)
TransformNR forwardOffset (TransformNR t)
void addJointSpaceListener (IJointSpaceUpdateListenerNR l)
void removeJointSpaceUpdateListener (IJointSpaceUpdateListenerNR l)
void addRegistrationListener (IRegistrationListenerNR l)
void removeRegestrationUpdateListener (IRegistrationListenerNR l)
void addPoseUpdateListener (ITaskSpaceUpdateListenerNR l)
void removePoseUpdateListener (ITaskSpaceUpdateListenerNR l)
void onLinkPositionUpdate (AbstractLink source, double engineeringUnitsValue)
void onPIDEvent (PIDEvent e)
void onPIDLimitEvent (PIDLimitEvent e)
void onPIDReset (int group, float currentValue)
void homeAllLinks ()
void homeLink (int link)
void emergencyStop ()
ArrayList< PIDConfiguration > getAxisPidConfiguration ()
TransformNR getCurrentPoseTarget ()
void setFactory (LinkFactory factory)
LinkFactory getFactory ()
void setNoFlush (boolean noFlush)
boolean isNoFlush ()
int getRetryNumberBeforeFail ()
void setRetryNumberBeforeFail (int retryNumberBeforeFail)
void onLinkLimit (AbstractLink arg0, PIDLimitEvent arg1)
DHChain getDhParametersChain ()
void setDhParametersChain (DHChain dhParametersChain)
String[] getGitDhEngine ()
void setGitDhEngine (String[] dhEngine)
String[] getGitCadEngine ()
void setGitCadEngine (String[] cadEngine)
IMU getImu ()
void boundedLinkValueSet (int index, double value) throws Exception
double boundToLinkLimits (int index, double value)
double linkMass (int linkIndex)
double getMaxEngineeringUnits (int linkIndex)
double getMinEngineeringUnits (int linkIndex)
void setMaxEngineeringUnits (int linkIndex, double maxLimit)
void setMinEngineeringUnits (int linkIndex, double minLimit)
String getElectroMechanicalType (int linkIndex)
void setElectroMechanicalType (int linkIndex, String electroMechanicalType)
String getElectroMechanicalSize (int linkIndex)
void setElectroMechanicalSize (int linkIndex, String electroMechanicalSize)
String getShaftType (int linkIndex)
void setShaftType (int linkIndex, String shaftType)
String getShaftSize (int linkIndex)
void setDeviceMaximumValue (int linkIndex, double max)
void setDeviceMinimumValue (int linkIndex, double min)
double getDeviceMaximumValue (int linkIndex)
double getDeviceMinimumValue (int linkIndex)
void addChangeListener (int linkIndex, ILinkConfigurationChangeListener l)
void removeChangeListener (int linkIndex, ILinkConfigurationChangeListener l)
void clearChangeListener (int linkIndex)
void runRenderWrangler ()
void setRenderWrangler (Runnable renderWrangler)
TransformNR getDeltaToTarget (TransformNR target)
TransformNR getTipAlongTrajectory (TransformNR startingPoint, TransformNR deltaToTarget, double unitIncrement)
void asyncInterpolatedMove (TransformNR target, double seconds, InterpolationType type, IOnInterpolationDone listener, double ...conf)
InterpolationMoveState blockingInterpolatedMove (TransformNR target, double seconds, InterpolationType type, double ...conf)
Public Member Functions inherited from com.neuronrobotics.sdk.common.NonBowlerDevice
boolean connect ()
boolean isAvailable () throws InvalidConnectionException
void disconnect ()
void onAsyncResponse (BowlerDatagram data)
ArrayList< String > getNamespaces ()
Public Member Functions inherited from com.neuronrobotics.sdk.common.BowlerAbstractDevice
void addConnectionEventListener (final IDeviceConnectionEventListener l)
void removeConnectionEventListener (IDeviceConnectionEventListener l)
void setConnection (BowlerAbstractConnection connection)
BowlerAbstractConnection getConnection ()
void setAddress (MACAddress address)
MACAddress getAddress ()
BowlerDatagram send (BowlerAbstractCommand command) throws NoConnectionAvailableException, InvalidResponseException
BowlerDatagram send (BowlerAbstractCommand command, int retry) throws NoConnectionAvailableException, InvalidResponseException
Object[] send (String namespace, BowlerMethod method, String rpcString, Object[] arguments, int retry) throws DeviceConnectionException
Object[] send (String namespace, BowlerMethod method, String rpcString, Object[] arguments) throws DeviceConnectionException
boolean ping ()
boolean ping (boolean switchParser)
ArrayList< ByteList > getRevisions ()
boolean hasNamespace (String string)
void startHeartBeat ()
void startHeartBeat (long msHeartBeatTime)
void stopHeartBeat ()
void setThreadedUpstreamPackets (boolean up)
ArrayList< RpcEncapsulation > getRpcList (String namespace)
void loadRpcList ()
void onAllResponse (BowlerDatagram data)
boolean isKeepAlive ()
void setKeepAlive (boolean keepAlive)
long getLastPacketTime ()
void setLastPacketTime (long lastPacketTime)
String getScriptingName ()
void setScriptingName (String scriptingName)
ArrayList< IDeviceConnectionEventListener > getDisconnectListeners ()
Private Member Functions
double[] compute (DHParameterKinematics ldh, HashMap< String, double[]> IKvalues, TransformNR taskSpaceTransform) throws Exception
DHParameterKinematics findReferencedLimb (String refLimbName)
Private Attributes
ArrayList< DHParameterKinematics > constituantLimbs = new ArrayList<DHParameterKinematics>()
HashMap< DHParameterKinematics, TransformNR > tipOffset = new HashMap<DHParameterKinematics, TransformNR>()
HashMap< DHParameterKinematics, String > tipOffsetRelativeToName = new HashMap<>()
HashMap< DHParameterKinematics, Integer > tipOffsetRelativeIndex = new HashMap<>()
String[] toolEngine
String name
Additional Inherited Members
Static Public Member Functions inherited from com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR
static boolean checkTaskSpaceTransform (AbstractKinematicsNR dev, TransformNR taskSpaceTransform, double seconds)
static boolean checkTaskSpaceTransform (AbstractKinematicsNR dev, TransformNR taskSpaceTransform)
Protected Member Functions inherited from com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR
ArrayList< LinkConfiguration > loadConfig (Element doc)
LinkFactory getDevice ()
void setDevice (LinkFactory f, ArrayList< LinkConfiguration > linkConfigs)
void firePoseTransform (TransformNR transform)
void fireTargetJointsUpdate (double[] jointSpaceVector, TransformNR fwd)
String getCode (Element e, String tag)
String[] getGitCodes (Element doc, String tag)
Protected Member Functions inherited from com.neuronrobotics.sdk.common.BowlerAbstractDevice
void fireDisconnectEvent ()
void fireConnectEvent ()
Protected Attributes inherited from com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR
ArrayList< IJointSpaceUpdateListenerNR > jointSpaceUpdateListeners = new ArrayList<IJointSpaceUpdateListenerNR>()
Detailed Description
Definition at line 14 of file ParallelGroup.java.
Constructor & Destructor Documentation
ParallelGroup()
com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.ParallelGroup (String name)
Definition at line 38 of file ParallelGroup.java.
References com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.name.
Member Function Documentation
addLimb()
void com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.addLimb (DHParameterKinematics limb, TransformNR tip, String name, int index)
Definition at line 44 of file ParallelGroup.java.
References com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.name, and com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.setupReferencedLimb().
Referenced by com.neuronrobotics.sdk.addons.kinematics.MobileBase.addLimbToParallel().
calcHome()
TransformNR com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.calcHome ()
Calc home.
Returns
the transform nr
Reimplemented from com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.
Definition at line 66 of file ParallelGroup.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.calcHome(), and com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.getFKLimb().
Referenced by com.neuronrobotics.sdk.addons.kinematics.MobileBase.initializeParalellGroups().
clearReferencedLimb()
void com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.clearReferencedLimb (DHParameterKinematics limb)
Definition at line 126 of file ParallelGroup.java.
References com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.getTipOffset(), com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.tipOffsetRelativeIndex, and com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.tipOffsetRelativeToName.
Referenced by com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.removeLimb(), and com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.setupReferencedLimbStartup().
close()
void com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.close ()
Definition at line 345 of file ParallelGroup.java.
References com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.constituantLimbs, com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.tipOffset, and com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.tipOffsetRelativeToName.
Referenced by com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.disconnectDevice(), and com.neuronrobotics.sdk.addons.kinematics.MobileBase.shutDownParallel().
compute()
double [] com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.compute (DHParameterKinematics ldh, HashMap< String, double[]> IKvalues, TransformNR taskSpaceTransform) throws Exception private
Definition at line 148 of file ParallelGroup.java.
References com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.findReferencedLimb(), com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getChain(), com.neuronrobotics.sdk.addons.kinematics.DHChain.getChain(), com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.getTipOffset(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.inverse(), com.neuronrobotics.sdk.common.BowlerAbstractDevice.scriptingName, com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.tipOffsetRelativeIndex, and com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.tipOffsetRelativeToName.
Referenced by com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.inverseKinematics(), and com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.printError().
connectDevice()
boolean com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.connectDevice ()
Connect device.
Returns
true, if successful
Reimplemented from com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.
Definition at line 143 of file ParallelGroup.java.
disconnectDevice()
void com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.disconnectDevice ()
This method tells the connection object to disconnect its pipes and close out the connection. Once this is called, it is safe to remove your device.
Reimplemented from com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.
Definition at line 133 of file ParallelGroup.java.
References com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.close(), and com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.getConstituantLimbs().
findReferencedLimb()
DHParameterKinematics com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.findReferencedLimb (String refLimbName) private
Definition at line 176 of file ParallelGroup.java.
References com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.getConstituantLimbs().
Referenced by com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.compute().
forwardKinematics()
TransformNR com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.forwardKinematics (double[] jointSpaceVector)
Forward kinematics.
Parameters
jointSpaceVector the joint space vector
Returns
6x1 vector in task space, unit in mm,radians [x,y,z,rotx,rotY,rotZ]
Reimplemented from com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.
Definition at line 267 of file ParallelGroup.java.
References com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.getConstituantLimbs(), and com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.getFKLimb().
getConstituantLimbs()
ArrayList<DHParameterKinematics> com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.getConstituantLimbs ()
Definition at line 295 of file ParallelGroup.java.
References com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.constituantLimbs.
Referenced by com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.disconnectDevice(), com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.findReferencedLimb(), com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.forwardKinematics(), com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.getFKLimb(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.initializeParalellGroups(), com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.inverseKinematics(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.main(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.makeLimbTag(), com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.printError(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.removeLimFromParallel(), com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.setupReferencedLimb(), and com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.setupReferencedLimbStartup().
getCurrentJointSpaceVector()
double [] com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.getCurrentJointSpaceVector (DHParameterKinematics k)
Definition at line 201 of file ParallelGroup.java.
getFKLimb()
DHParameterKinematics com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.getFKLimb ()
Definition at line 50 of file ParallelGroup.java.
References com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.getConstituantLimbs(), and com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.getTipOffset().
Referenced by com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.calcHome(), com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.forwardKinematics(), and com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.setupReferencedLimbStartup().
getGitCadToolEngine()
String [] com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.getGitCadToolEngine ()
Gets the cad engine.
Returns
the cad engine
Definition at line 281 of file ParallelGroup.java.
References com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.toolEngine.
Referenced by com.neuronrobotics.sdk.addons.kinematics.MobileBase.getEmbedableXml().
getNameOfParallelGroup()
String com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.getNameOfParallelGroup ()
Definition at line 341 of file ParallelGroup.java.
References com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.name.
Referenced by com.neuronrobotics.sdk.addons.kinematics.MobileBase.initializeParalellGroups(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.removeLimFromParallel(), and com.neuronrobotics.sdk.addons.kinematics.MobileBase.shutDownParallel().
getTipOffset() [1/2]
HashMap<DHParameterKinematics, TransformNR> com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.getTipOffset ()
Definition at line 303 of file ParallelGroup.java.
References com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.tipOffset.
Referenced by com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.clearReferencedLimb(), com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.compute(), com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.getFKLimb(), com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.getTipOffsetFromThisLinkInLimb(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.main(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.makeLimbTag(), and com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.setupReferencedLimbStartup().
getTipOffset() [2/2]
TransformNR com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.getTipOffset (DHParameterKinematics l)
Definition at line 307 of file ParallelGroup.java.
References com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.tipOffset.
getTipOffsetFromThisLinkInLimb()
TransformNR com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.getTipOffsetFromThisLinkInLimb (DHParameterKinematics control, int index)
Definition at line 25 of file ParallelGroup.java.
References com.neuronrobotics.sdk.common.BowlerAbstractDevice.getScriptingName(), com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.getTipOffset(), com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.name, com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.tipOffsetRelativeIndex, and com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.tipOffsetRelativeToName.
getTipOffsetRelativeIndex()
int com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.getTipOffsetRelativeIndex (DHParameterKinematics l)
Definition at line 319 of file ParallelGroup.java.
References com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.tipOffsetRelativeIndex.
Referenced by com.neuronrobotics.sdk.addons.kinematics.MobileBase.makeLimbTag().
getTipOffsetRelativeName()
String com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.getTipOffsetRelativeName (DHParameterKinematics l)
Definition at line 315 of file ParallelGroup.java.
References com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.tipOffsetRelativeToName.
Referenced by com.neuronrobotics.sdk.addons.kinematics.MobileBase.makeLimbTag().
inverseKinematics()
double [] com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.inverseKinematics (TransformNR taskSpaceTransform) throws Exception
Inverse kinematics.
Parameters
taskSpaceTransform the task space transform
Returns
Nx1 vector in task space, in mm where N is number of links
Exceptions
Exception the exception
Reimplemented from com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.
Definition at line 206 of file ParallelGroup.java.
References com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.compute(), and com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.getConstituantLimbs().
printError() [1/2]
void com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.printError (TransformNR taskSpaceTransform) throws Exception
Definition at line 228 of file ParallelGroup.java.
printError() [2/2]
void com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.printError (TransformNR taskSpaceTransform, Consumer< String > printer) throws Exception
Definition at line 233 of file ParallelGroup.java.
References com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.compute(), com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.getConstituantLimbs(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getLowerLimit(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getUpperLimit(), and com.neuronrobotics.sdk.addons.kinematics.AbstractLink.toLinkUnits().
removeLimb()
void com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.removeLimb (DHParameterKinematics limb)
Definition at line 327 of file ParallelGroup.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkFactory.addLink(), com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.clearReferencedLimb(), com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.constituantLimbs, com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getFactory(), and com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.setFactory().
Referenced by com.neuronrobotics.sdk.addons.kinematics.MobileBase.removeLimFromParallel().
setCurrentPoseTarget()
void com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.setCurrentPoseTarget (TransformNR currentPoseTarget)
Sets the current pose target.
Parameters
currentPoseTarget the new current pose target
Reimplemented from com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.
Definition at line 195 of file ParallelGroup.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.checkTaskSpaceTransform(), and com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.currentPoseTarget.
setGitCadToolEngine()
void com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.setGitCadToolEngine (String[] cadEngine)
Sets the cad engine.
Parameters
cadEngine the new cad engine
Definition at line 290 of file ParallelGroup.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.cadEngine.
Referenced by com.neuronrobotics.sdk.addons.kinematics.MobileBase.loadConfigs().
setTipOffset() [1/2]
void com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.setTipOffset (DHParameterKinematics l, TransformNR n)
Definition at line 311 of file ParallelGroup.java.
References com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.tipOffset.
setTipOffset() [2/2]
void com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.setTipOffset (HashMap< DHParameterKinematics, TransformNR > tipOffset)
Definition at line 323 of file ParallelGroup.java.
References com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.tipOffset.
setupReferencedLimb()
void com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.setupReferencedLimb (DHParameterKinematics limb, TransformNR tip, String name, int index)
Definition at line 70 of file ParallelGroup.java.
References com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.getConstituantLimbs(), com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.name, and com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.setupReferencedLimbStartup().
Referenced by com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.addLimb().
setupReferencedLimbStartup()
void com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.setupReferencedLimbStartup (DHParameterKinematics limb, TransformNR tip, String name, int index)
Definition at line 80 of file ParallelGroup.java.
References com.neuronrobotics.sdk.addons.kinematics.LinkFactory.addLink(), com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.clearReferencedLimb(), com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.getConstituantLimbs(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getFactory(), com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.getFKLimb(), com.neuronrobotics.sdk.addons.kinematics.LinkFactory.getLink(), com.neuronrobotics.sdk.addons.kinematics.LinkFactory.getLinkConfigurations(), com.neuronrobotics.sdk.common.BowlerAbstractDevice.getScriptingName(), com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.getTipOffset(), com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.name, com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.tipOffsetRelativeIndex, and com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.tipOffsetRelativeToName.
Referenced by com.neuronrobotics.sdk.addons.kinematics.MobileBase.loadLimb(), and com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.setupReferencedLimb().
Member Data Documentation
constituantLimbs
ArrayList<DHParameterKinematics> com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.constituantLimbs = new ArrayList<DHParameterKinematics>() private
Definition at line 16 of file ParallelGroup.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.close(), com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.getConstituantLimbs(), and com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.removeLimb().
name
String com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.name private
Definition at line 23 of file ParallelGroup.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.addLimb(), com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.getNameOfParallelGroup(), com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.getTipOffsetFromThisLinkInLimb(), com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.ParallelGroup(), com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.setupReferencedLimb(), and com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.setupReferencedLimbStartup().
tipOffset
HashMap<DHParameterKinematics, TransformNR> com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.tipOffset = new HashMap<DHParameterKinematics, TransformNR>() private
Definition at line 17 of file ParallelGroup.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.close(), com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.getTipOffset(), and com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.setTipOffset().
tipOffsetRelativeIndex
HashMap<DHParameterKinematics, Integer> com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.tipOffsetRelativeIndex = new HashMap<>() private
Definition at line 19 of file ParallelGroup.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.clearReferencedLimb(), com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.compute(), com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.getTipOffsetFromThisLinkInLimb(), com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.getTipOffsetRelativeIndex(), and com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.setupReferencedLimbStartup().
tipOffsetRelativeToName
HashMap<DHParameterKinematics, String> com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.tipOffsetRelativeToName = new HashMap<>() private
Definition at line 18 of file ParallelGroup.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.clearReferencedLimb(), com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.close(), com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.compute(), com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.getTipOffsetFromThisLinkInLimb(), com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.getTipOffsetRelativeName(), and com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.setupReferencedLimbStartup().
toolEngine
String [] com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.toolEngine private
Initial value:
= new String[] { "https://gist.github.com/33f2c10ab3adc5bd91f0a58ea7f24d14.git",
            "parallelTool.groovy" }
The cad engine.
Definition at line 21 of file ParallelGroup.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.getGitCadToolEngine().
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/addons/kinematics/parallel/ParallelGroup.java