BowlerKernel: com.neuronrobotics.sdk.pid.PIDLimitEvent Class Reference
com.neuronrobotics.sdk.pid.PIDLimitEvent Class Reference
Public Member Functions
PIDLimitEvent (int chan, double tick, PIDLimitEventType type, long time)
PIDLimitEvent (BowlerDatagram data)
void setGroup (int channel)
int getGroup ()
void setValue (double ticks)
double getValue ()
void setTimeStamp (long timeStamp)
long getTimeStamp ()
String toString ()
void setLimitType (PIDLimitEventType limitIndex)
PIDLimitEventType getLimitType ()
Private Attributes
int channel
double ticks
long timeStamp
PIDLimitEventType limitType
Detailed Description
The Class PIDLimitEvent.
Definition at line 10 of file PIDLimitEvent.java.
Constructor & Destructor Documentation
PIDLimitEvent() [1/2]
com.neuronrobotics.sdk.pid.PIDLimitEvent.PIDLimitEvent (int chan, double tick, PIDLimitEventType type, long time)
Instantiates a new PID limit event.
Parameters
chan the chan
tick the tick
type the type
time the time
Definition at line 32 of file PIDLimitEvent.java.
References com.neuronrobotics.sdk.pid.PIDLimitEvent.setGroup(), com.neuronrobotics.sdk.pid.PIDLimitEvent.setLimitType(), com.neuronrobotics.sdk.pid.PIDLimitEvent.setTimeStamp(), and com.neuronrobotics.sdk.pid.PIDLimitEvent.setValue().
PIDLimitEvent() [2/2]
com.neuronrobotics.sdk.pid.PIDLimitEvent.PIDLimitEvent (BowlerDatagram data)
Instantiates a new PID limit event.
Parameters
data the data
Definition at line 45 of file PIDLimitEvent.java.
References com.neuronrobotics.sdk.common.ByteList.convertToInt(), com.neuronrobotics.sdk.pid.PIDLimitEventType.get(), com.neuronrobotics.sdk.common.ByteList.getByte(), com.neuronrobotics.sdk.common.ByteList.getBytes(), com.neuronrobotics.sdk.common.BowlerDatagram.getData(), com.neuronrobotics.sdk.common.BowlerDatagram.getRPC(), com.neuronrobotics.sdk.pid.PIDLimitEvent.setGroup(), com.neuronrobotics.sdk.pid.PIDLimitEvent.setLimitType(), com.neuronrobotics.sdk.pid.PIDLimitEvent.setTimeStamp(), and com.neuronrobotics.sdk.pid.PIDLimitEvent.setValue().
Member Function Documentation
getGroup()
int com.neuronrobotics.sdk.pid.PIDLimitEvent.getGroup ()
Gets the group.
Returns
the group
Definition at line 69 of file PIDLimitEvent.java.
References com.neuronrobotics.sdk.pid.PIDLimitEvent.channel.
Referenced by com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.onPIDLimitEvent(), and com.neuronrobotics.sdk.pid.PIDChannel.setPid().
getLimitType()
PIDLimitEventType com.neuronrobotics.sdk.pid.PIDLimitEvent.getLimitType ()
Gets the limit type.
Returns
the limit type
Definition at line 131 of file PIDLimitEvent.java.
References com.neuronrobotics.sdk.pid.PIDLimitEvent.limitType.
Referenced by com.neuronrobotics.sdk.addons.kinematics.JointLimit.JointLimit().
getTimeStamp()
long com.neuronrobotics.sdk.pid.PIDLimitEvent.getTimeStamp ()
Gets the time stamp.
Returns
the time stamp
Definition at line 105 of file PIDLimitEvent.java.
References com.neuronrobotics.sdk.pid.PIDLimitEvent.timeStamp.
Referenced by com.neuronrobotics.sdk.addons.kinematics.JointLimit.JointLimit().
getValue()
double com.neuronrobotics.sdk.pid.PIDLimitEvent.getValue ()
Gets the value.
Returns
the value
Definition at line 87 of file PIDLimitEvent.java.
References com.neuronrobotics.sdk.pid.PIDLimitEvent.ticks.
Referenced by com.neuronrobotics.sdk.addons.kinematics.JointLimit.JointLimit().
setGroup()
void com.neuronrobotics.sdk.pid.PIDLimitEvent.setGroup (int channel)
Sets the group.
Parameters
channel the new group
Definition at line 60 of file PIDLimitEvent.java.
References com.neuronrobotics.sdk.pid.PIDLimitEvent.channel.
Referenced by com.neuronrobotics.sdk.pid.PIDLimitEvent.PIDLimitEvent().
setLimitType()
void com.neuronrobotics.sdk.pid.PIDLimitEvent.setLimitType (PIDLimitEventType limitIndex)
Sets the limit type.
Parameters
limitIndex the new limit type
Definition at line 122 of file PIDLimitEvent.java.
Referenced by com.neuronrobotics.sdk.pid.PIDLimitEvent.PIDLimitEvent().
setTimeStamp()
void com.neuronrobotics.sdk.pid.PIDLimitEvent.setTimeStamp (long timeStamp)
Sets the time stamp.
Parameters
timeStamp the new time stamp
Definition at line 96 of file PIDLimitEvent.java.
References com.neuronrobotics.sdk.pid.PIDLimitEvent.timeStamp.
Referenced by com.neuronrobotics.sdk.pid.PIDLimitEvent.PIDLimitEvent().
setValue()
void com.neuronrobotics.sdk.pid.PIDLimitEvent.setValue (double ticks)
Sets the value.
Parameters
ticks the new value
Definition at line 78 of file PIDLimitEvent.java.
References com.neuronrobotics.sdk.pid.PIDLimitEvent.ticks.
Referenced by com.neuronrobotics.sdk.pid.PIDLimitEvent.PIDLimitEvent().
toString()
String com.neuronrobotics.sdk.pid.PIDLimitEvent.toString ()
Definition at line 113 of file PIDLimitEvent.java.
References com.neuronrobotics.sdk.pid.PIDLimitEvent.channel, com.neuronrobotics.sdk.pid.PIDLimitEvent.limitType, com.neuronrobotics.sdk.pid.PIDLimitEvent.ticks, and com.neuronrobotics.sdk.pid.PIDLimitEvent.timeStamp.
Member Data Documentation
channel
int com.neuronrobotics.sdk.pid.PIDLimitEvent.channel private
The channel.
Definition at line 13 of file PIDLimitEvent.java.
Referenced by com.neuronrobotics.sdk.pid.PIDLimitEvent.getGroup(), com.neuronrobotics.sdk.pid.PIDLimitEvent.setGroup(), and com.neuronrobotics.sdk.pid.PIDLimitEvent.toString().
limitType
PIDLimitEventType com.neuronrobotics.sdk.pid.PIDLimitEvent.limitType private
The limit type.
Definition at line 22 of file PIDLimitEvent.java.
Referenced by com.neuronrobotics.sdk.pid.PIDLimitEvent.getLimitType(), and com.neuronrobotics.sdk.pid.PIDLimitEvent.toString().
ticks
double com.neuronrobotics.sdk.pid.PIDLimitEvent.ticks private
The ticks.
Definition at line 16 of file PIDLimitEvent.java.
Referenced by com.neuronrobotics.sdk.pid.PIDLimitEvent.getValue(), com.neuronrobotics.sdk.pid.PIDLimitEvent.setValue(), and com.neuronrobotics.sdk.pid.PIDLimitEvent.toString().
timeStamp
long com.neuronrobotics.sdk.pid.PIDLimitEvent.timeStamp private
The time stamp.
Definition at line 19 of file PIDLimitEvent.java.
Referenced by com.neuronrobotics.sdk.pid.PIDLimitEvent.getTimeStamp(), com.neuronrobotics.sdk.pid.PIDLimitEvent.setTimeStamp(), and com.neuronrobotics.sdk.pid.PIDLimitEvent.toString().
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/pid/PIDLimitEvent.java