BowlerKernel: com.neuronrobotics.bowlerstudio.assets.StudioBuildInfo Class Reference
com.neuronrobotics.bowlerstudio.assets.StudioBuildInfo Class Reference
Static Public Member Functions
static String getVersion ()
static int getProtocolVersion ()
static int getSDKVersion ()
static int getBuildVersion ()
static int[] getBuildInfo ()
static String getBuildDate ()
static String getSDKVersionString ()
static boolean isOS64bit ()
static boolean isARM ()
static boolean isLinux ()
static boolean isWindows ()
static boolean isMac ()
static boolean isUnix ()
static Class getBaseBuildInfoClass ()
static void setBaseBuildInfoClass (Class c)
static String getName ()
Static Private Member Functions
static String getTag (String target)
static InputStream getBuildPropertiesStream ()
Static Private Attributes
static Class baseBuildInfoClass = BowlerKernel.class
Detailed Description
Definition at line 10 of file StudioBuildInfo.java.
Member Function Documentation
getBaseBuildInfoClass()
static Class com.neuronrobotics.bowlerstudio.assets.StudioBuildInfo.getBaseBuildInfoClass () static
Definition at line 125 of file StudioBuildInfo.java.
References com.neuronrobotics.bowlerstudio.assets.StudioBuildInfo.baseBuildInfoClass.
getBuildDate()
static String com.neuronrobotics.bowlerstudio.assets.StudioBuildInfo.getBuildDate () static
Definition at line 77 of file StudioBuildInfo.java.
getBuildInfo()
static int [] com.neuronrobotics.bowlerstudio.assets.StudioBuildInfo.getBuildInfo () static
Definition at line 35 of file StudioBuildInfo.java.
References com.neuronrobotics.bowlerstudio.assets.StudioBuildInfo.getVersion().
Referenced by com.neuronrobotics.bowlerstudio.assets.StudioBuildInfo.getBuildVersion(), com.neuronrobotics.bowlerstudio.assets.StudioBuildInfo.getProtocolVersion(), and com.neuronrobotics.bowlerstudio.assets.StudioBuildInfo.getSDKVersion().
getBuildPropertiesStream()
static InputStream com.neuronrobotics.bowlerstudio.assets.StudioBuildInfo.getBuildPropertiesStream () static private
Definition at line 93 of file StudioBuildInfo.java.
References com.neuronrobotics.bowlerstudio.assets.StudioBuildInfo.baseBuildInfoClass.
Referenced by com.neuronrobotics.bowlerstudio.assets.StudioBuildInfo.getTag().
getBuildVersion()
static int com.neuronrobotics.bowlerstudio.assets.StudioBuildInfo.getBuildVersion () static
Definition at line 31 of file StudioBuildInfo.java.
References com.neuronrobotics.bowlerstudio.assets.StudioBuildInfo.getBuildInfo().
Referenced by com.neuronrobotics.bowlerstudio.assets.StudioBuildInfo.getName().
getName()
static String com.neuronrobotics.bowlerstudio.assets.StudioBuildInfo.getName () static
Definition at line 133 of file StudioBuildInfo.java.
References com.neuronrobotics.bowlerstudio.assets.StudioBuildInfo.getBuildVersion(), com.neuronrobotics.bowlerstudio.assets.StudioBuildInfo.getProtocolVersion(), and com.neuronrobotics.bowlerstudio.assets.StudioBuildInfo.getSDKVersion().
Referenced by com.neuronrobotics.bowlerstudio.assets.StudioBuildInfo.getSDKVersionString().
getProtocolVersion()
static int com.neuronrobotics.bowlerstudio.assets.StudioBuildInfo.getProtocolVersion () static
Definition at line 23 of file StudioBuildInfo.java.
References com.neuronrobotics.bowlerstudio.assets.StudioBuildInfo.getBuildInfo().
Referenced by com.neuronrobotics.bowlerstudio.assets.StudioBuildInfo.getName().
getSDKVersion()
static int com.neuronrobotics.bowlerstudio.assets.StudioBuildInfo.getSDKVersion () static
Definition at line 27 of file StudioBuildInfo.java.
References com.neuronrobotics.bowlerstudio.assets.StudioBuildInfo.getBuildInfo().
Referenced by com.neuronrobotics.bowlerstudio.assets.StudioBuildInfo.getName().
getSDKVersionString()
static String com.neuronrobotics.bowlerstudio.assets.StudioBuildInfo.getSDKVersionString () static
Definition at line 97 of file StudioBuildInfo.java.
References com.neuronrobotics.bowlerstudio.assets.StudioBuildInfo.getName().
getTag()
static String com.neuronrobotics.bowlerstudio.assets.StudioBuildInfo.getTag (String target) static private
Definition at line 50 of file StudioBuildInfo.java.
References com.neuronrobotics.bowlerstudio.assets.StudioBuildInfo.getBuildPropertiesStream().
Referenced by com.neuronrobotics.bowlerstudio.assets.StudioBuildInfo.getVersion().
getVersion()
static String com.neuronrobotics.bowlerstudio.assets.StudioBuildInfo.getVersion () static
Definition at line 14 of file StudioBuildInfo.java.
References com.neuronrobotics.bowlerstudio.assets.StudioBuildInfo.getTag().
Referenced by com.neuronrobotics.bowlerstudio.IssueReportingExceptionHandler.except(), com.neuronrobotics.bowlerstudio.assets.StudioBuildInfo.getBuildInfo(), com.neuronrobotics.bowlerstudio.assets.AssetFactory.loadAllAssets(), and com.neuronrobotics.bowlerstudio.IssueReportingExceptionHandler.runReport().
isARM()
static boolean com.neuronrobotics.bowlerstudio.assets.StudioBuildInfo.isARM () static
Definition at line 105 of file StudioBuildInfo.java.
isLinux()
static boolean com.neuronrobotics.bowlerstudio.assets.StudioBuildInfo.isLinux () static
Definition at line 109 of file StudioBuildInfo.java.
Referenced by com.neuronrobotics.bowlerstudio.assets.StudioBuildInfo.isUnix().
isMac()
static boolean com.neuronrobotics.bowlerstudio.assets.StudioBuildInfo.isMac () static
Definition at line 117 of file StudioBuildInfo.java.
Referenced by com.neuronrobotics.bowlerstudio.assets.StudioBuildInfo.isUnix().
isOS64bit()
static boolean com.neuronrobotics.bowlerstudio.assets.StudioBuildInfo.isOS64bit () static
Definition at line 101 of file StudioBuildInfo.java.
isUnix()
static boolean com.neuronrobotics.bowlerstudio.assets.StudioBuildInfo.isUnix () static
Definition at line 121 of file StudioBuildInfo.java.
References com.neuronrobotics.bowlerstudio.assets.StudioBuildInfo.isLinux(), and com.neuronrobotics.bowlerstudio.assets.StudioBuildInfo.isMac().
isWindows()
static boolean com.neuronrobotics.bowlerstudio.assets.StudioBuildInfo.isWindows () static
Definition at line 113 of file StudioBuildInfo.java.
setBaseBuildInfoClass()
static void com.neuronrobotics.bowlerstudio.assets.StudioBuildInfo.setBaseBuildInfoClass (Class c) static
Definition at line 129 of file StudioBuildInfo.java.
References com.neuronrobotics.bowlerstudio.assets.StudioBuildInfo.baseBuildInfoClass.
Member Data Documentation
baseBuildInfoClass
Class com.neuronrobotics.bowlerstudio.assets.StudioBuildInfo.baseBuildInfoClass = BowlerKernel.class static private
Definition at line 12 of file StudioBuildInfo.java.
Referenced by com.neuronrobotics.bowlerstudio.assets.StudioBuildInfo.getBaseBuildInfoClass(), com.neuronrobotics.bowlerstudio.assets.StudioBuildInfo.getBuildPropertiesStream(), and com.neuronrobotics.bowlerstudio.assets.StudioBuildInfo.setBaseBuildInfoClass().
The documentation for this class was generated from the following file:
src/main/java/com/neuronrobotics/bowlerstudio/assets/StudioBuildInfo.java