BowlerKernel: com.neuronrobotics.application.xmpp.DyIOConversation Class Reference
com.neuronrobotics.application.xmpp.DyIOConversation Class Reference
Classes
class ChatAsyncListener
Public Member Functions
DyIOConversation (IChatLog log)
void processMessage (Chat chat, Message message)
String onMessage (String input, Chat chat, String from)
void onChannelEvent (DyIOChannelEvent e)
Private Member Functions
ChatAsyncListener getListener (Chat c, String from)
String help ()
Private Attributes
ArrayList< ChatAsyncListener > listeners = new ArrayList<ChatAsyncListener>()
IChatLog log
Detailed Description
The Class DyIOConversation.
Definition at line 23 of file DyIOConversation.java.
Constructor & Destructor Documentation
DyIOConversation()
com.neuronrobotics.application.xmpp.DyIOConversation.DyIOConversation (IChatLog log)
Instantiates a new dy io conversation.
Parameters
log the log
Definition at line 36 of file DyIOConversation.java.
References com.neuronrobotics.application.xmpp.DyIOConversation.log.
Member Function Documentation
getListener()
ChatAsyncListener com.neuronrobotics.application.xmpp.DyIOConversation.getListener (Chat c, String from) private
Gets the listener.
Parameters
c the c
from the from
Returns
the listener
Definition at line 144 of file DyIOConversation.java.
References com.neuronrobotics.application.xmpp.DyIOConversation.listeners.
Referenced by com.neuronrobotics.application.xmpp.DyIOConversation.onMessage().
help()
String com.neuronrobotics.application.xmpp.DyIOConversation.help () private
Help.
Returns
the string
Definition at line 248 of file DyIOConversation.java.
Referenced by com.neuronrobotics.application.xmpp.DyIOConversation.onMessage().
onChannelEvent()
void com.neuronrobotics.application.xmpp.DyIOConversation.onChannelEvent (DyIOChannelEvent e)
On channel event.
Parameters
e the e
Implements com.neuronrobotics.sdk.dyio.IChannelEventListener.
Definition at line 270 of file DyIOConversation.java.
onMessage()
String com.neuronrobotics.application.xmpp.DyIOConversation.onMessage (String input, Chat chat, String from)
On message.
Parameters
input the input
chat the chat
from the from
Returns
the string
Implements com.neuronrobotics.application.xmpp.IConversation.
Definition at line 71 of file DyIOConversation.java.
References com.neuronrobotics.sdk.dyio.DyIOChannelMode.DIGITAL_IN, com.neuronrobotics.application.xmpp.DyIOConversation.getListener(), com.neuronrobotics.sdk.common.DeviceManager.getSpecificDevice(), com.neuronrobotics.application.xmpp.DyIOConversation.help(), and com.neuronrobotics.sdk.dyio.DyIOChannelMode.toSlug().
Referenced by com.neuronrobotics.application.xmpp.DyIOConversation.processMessage().
processMessage()
void com.neuronrobotics.application.xmpp.DyIOConversation.processMessage (Chat chat, Message message)
Definition at line 43 of file DyIOConversation.java.
References com.neuronrobotics.application.xmpp.DyIOConversation.log, com.neuronrobotics.application.xmpp.GoogleChat.IChatLog.onLogEvent(), and com.neuronrobotics.application.xmpp.DyIOConversation.onMessage().
Member Data Documentation
listeners
ArrayList<ChatAsyncListener> com.neuronrobotics.application.xmpp.DyIOConversation.listeners = new ArrayList<ChatAsyncListener>() private
The listeners.
Definition at line 26 of file DyIOConversation.java.
Referenced by com.neuronrobotics.application.xmpp.DyIOConversation.getListener().
log
IChatLog com.neuronrobotics.application.xmpp.DyIOConversation.log private
The log.
Definition at line 29 of file DyIOConversation.java.
Referenced by com.neuronrobotics.application.xmpp.DyIOConversation.DyIOConversation(), and com.neuronrobotics.application.xmpp.DyIOConversation.processMessage().
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/application/xmpp/DyIOConversation.java