BowlerKernel: com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.DyIOFlusher Class Reference
com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.DyIOFlusher Class Reference
Public Member Functions
void run ()
boolean isRunning ()
void setFlush ()
boolean isFlush ()
Private Attributes
boolean running = true
boolean flush = false
Detailed Description
The Class DyIOFlusher.
Definition at line 450 of file CoreScheduler.java.
Member Function Documentation
isFlush()
boolean com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.DyIOFlusher.isFlush ()
Checks if is flush.
Returns
true, if is flush
Definition at line 513 of file CoreScheduler.java.
References com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.DyIOFlusher.flush.
Referenced by com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.DyIOFlusher.run().
isRunning()
boolean com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.DyIOFlusher.isRunning ()
Checks if is running.
Returns
true, if is running
Definition at line 497 of file CoreScheduler.java.
References com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.DyIOFlusher.running.
Referenced by com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.DyIOFlusher.run().
run()
void com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.DyIOFlusher.run ()
Definition at line 461 of file CoreScheduler.java.
References com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.DyIOFlusher.flush, com.neuronrobotics.sdk.dyio.DyIO.flushCache(), com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.flushTime, com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.getDyIO(), com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.getLoopTime(), com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.getOutputs(), com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.DyIOFlusher.isFlush(), and com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.DyIOFlusher.isRunning().
setFlush()
void com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.DyIOFlusher.setFlush ()
Sets the flush.
Definition at line 504 of file CoreScheduler.java.
Referenced by com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.setCurrentTime().
Member Data Documentation
flush
boolean com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.DyIOFlusher.flush = false private
The flush.
Definition at line 456 of file CoreScheduler.java.
Referenced by com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.DyIOFlusher.isFlush(), and com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.DyIOFlusher.run().
running
boolean com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.DyIOFlusher.running = true private
The running.
Definition at line 453 of file CoreScheduler.java.
Referenced by com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.DyIOFlusher.isRunning().
The documentation for this class was generated from the following file:
src/main/java/com/neuronrobotics/sdk/dyio/sequencer/CoreScheduler.java