BowlerKernel: eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter Class Reference
eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter Class Reference
Public Member Functions
Set< String > getMeshes ()
PolyObjImporter (String filename) throws FileNotFoundException, IOException
PolyObjImporter (InputStream inputStream) throws IOException
PolygonMesh getMesh ()
Material getMaterial ()
PolygonMesh getMesh (String key)
Material getMaterial (String key)
PolygonMeshView buildPolygonMeshView (String key)
Static Public Member Functions
static void setDebug (boolean debug)
static void setScale (float scale)
static void setFlatXZ (boolean flatXZ)
Private Member Functions
int vertexIndex (int vertexIndex)
int uvIndex (int uvIndex)
int normalIndex (int normalIndex)
void read (InputStream inputStream) throws IOException
void addMesh (String key)
Private Attributes
Map< String, PolygonMesh > meshes = new HashMap<>()
Map< String, Material > materials = new HashMap<>()
List< Map< String, Material > > materialLibrary = new ArrayList<>()
String objFilename
FloatArrayList vertexes = new FloatArrayList()
FloatArrayList uvs = new FloatArrayList()
List< int[]> faces = new ArrayList<>()
IntegerArrayList smoothingGroups = new IntegerArrayList()
FloatArrayList normals = new FloatArrayList()
List< int[]> faceNormals = new ArrayList<>()
Material material = new PhongMaterial(Color.WHITE)
int facesStart = 0
int facesNormalStart = 0
int smoothingGroupsStart = 0
Static Private Attributes
static boolean debug = false
static float scale = 1
static boolean flatXZ = false
Detailed Description
OBJ object loader.
Definition at line 55 of file PolyObjImporter.java.
Constructor & Destructor Documentation
PolyObjImporter() [1/2]
eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.PolyObjImporter (String filename) throws FileNotFoundException, IOException
Instantiates a new poly obj importer.
Parameters
filename the filename
Exceptions
FileNotFoundException the file not found exception
IOException Signals that an I/O exception has occurred.
Definition at line 147 of file PolyObjImporter.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.read().
PolyObjImporter() [2/2]
eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.PolyObjImporter (InputStream inputStream) throws IOException
Instantiates a new poly obj importer.
Parameters
inputStream the input stream
Exceptions
IOException Signals that an I/O exception has occurred.
Definition at line 159 of file PolyObjImporter.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.read().
Member Function Documentation
addMesh()
void eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.addMesh (String key) private
Adds the mesh.
Parameters
key the key
Definition at line 373 of file PolyObjImporter.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.add(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.SmoothingGroups.calcSmoothGroups(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.debug, eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.faceNormals, eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.faces, eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMesh.faces, eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.facesNormalStart, eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.facesStart, eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.get(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMesh.getFaceSmoothingGroups(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMesh.getPoints(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMesh.getTexCoords(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.material, eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.materials, eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.meshes, eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.normals, eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.size, eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.size, eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.smoothingGroups, eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.smoothingGroupsStart, eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.subList(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.toFloatArray(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.uvs, and eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.vertexes.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.read().
buildPolygonMeshView()
PolygonMeshView eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.buildPolygonMeshView (String key)
Builds the polygon mesh view.
Parameters
key the key
Returns
the polygon mesh view
Definition at line 207 of file PolyObjImporter.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.materials, eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.meshes, eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.setMaterial(), and eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.setMesh().
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjOrPolyObjImporter.load().
getMaterial() [1/2]
Material eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.getMaterial ()
Gets the material.
Returns
the material
Definition at line 177 of file PolyObjImporter.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.materials.
getMaterial() [2/2]
Material eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.getMaterial (String key)
Gets the material.
Parameters
key the key
Returns
the material
Definition at line 197 of file PolyObjImporter.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.materials.
getMesh() [1/2]
PolygonMesh eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.getMesh ()
Gets the mesh.
Returns
the mesh
Definition at line 168 of file PolyObjImporter.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.meshes.
getMesh() [2/2]
PolygonMesh eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.getMesh (String key)
Gets the mesh.
Parameters
key the key
Returns
the mesh
Definition at line 187 of file PolyObjImporter.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.meshes.
getMeshes()
Set<String> eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.getMeshes ()
Gets the meshes.
Returns
the meshes
Definition at line 124 of file PolyObjImporter.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.meshes.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjOrPolyObjImporter.load().
normalIndex()
int eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.normalIndex (int normalIndex) private
Normal index.
Parameters
normalIndex the normal index
Returns
the int
Definition at line 91 of file PolyObjImporter.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.normals, and eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.size.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.read().
read()
void eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.read (InputStream inputStream) throws IOException private
Read.
Parameters
inputStream the input stream
Exceptions
IOException Signals that an I/O exception has occurred.
Definition at line 270 of file PolyObjImporter.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.add(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.add(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.addMesh(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.faceNormals, eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.faces, eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.flatXZ, eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.MtlReader.getMaterials(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.material, eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.materialLibrary, eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.normalIndex(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.normals, eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.objFilename, eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.scale, eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.size, eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.size, eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.smoothingGroups, eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.uvIndex(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.uvs, eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.vertexes, and eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.vertexIndex().
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.PolyObjImporter().
setDebug()
static void eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.setDebug (boolean debug) static
Sets the debug.
Parameters
debug the new debug
Definition at line 221 of file PolyObjImporter.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.debug.
setFlatXZ()
static void eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.setFlatXZ (boolean flatXZ) static
Sets the flat xz.
Parameters
flatXZ the new flat xz
Definition at line 491 of file PolyObjImporter.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.flatXZ.
setScale()
static void eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.setScale (float scale) static
Sets the scale.
Parameters
scale the new scale
Definition at line 230 of file PolyObjImporter.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.scale.
uvIndex()
int eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.uvIndex (int uvIndex) private
Uv index.
Parameters
uvIndex the uv index
Returns
the int
Definition at line 77 of file PolyObjImporter.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.size, and eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.uvs.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.read().
vertexIndex()
int eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.vertexIndex (int vertexIndex) private
Vertex index.
Parameters
vertexIndex the vertex index
Returns
the int
Definition at line 63 of file PolyObjImporter.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.size, and eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.vertexes.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.read().
Member Data Documentation
debug
boolean eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.debug = false static private
The debug.
Definition at line 100 of file PolyObjImporter.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.addMesh(), and eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.setDebug().
faceNormals
List<int[]> eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.faceNormals = new ArrayList<>() private
The face normals.
Definition at line 250 of file PolyObjImporter.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.addMesh(), and eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.read().
faces
List<int[]> eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.faces = new ArrayList<>() private
The faces.
Definition at line 241 of file PolyObjImporter.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.addMesh(), and eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.read().
facesNormalStart
int eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.facesNormalStart = 0 private
The faces normal start.
Definition at line 259 of file PolyObjImporter.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.addMesh().
facesStart
int eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.facesStart = 0 private
The faces start.
Definition at line 256 of file PolyObjImporter.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.addMesh().
flatXZ
boolean eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.flatXZ = false static private
The flat xz.
Definition at line 106 of file PolyObjImporter.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.read(), and eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.setFlatXZ().
material
Material eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.material = new PhongMaterial(Color.WHITE) private
The material.
Definition at line 253 of file PolyObjImporter.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.addMesh(), and eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.read().
materialLibrary
List<Map<String, Material> > eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.materialLibrary = new ArrayList<>() private
The material library.
Definition at line 135 of file PolyObjImporter.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.read().
materials
Map<String, Material> eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.materials = new HashMap<>() private
The materials.
Definition at line 132 of file PolyObjImporter.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.addMesh(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.buildPolygonMeshView(), and eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.getMaterial().
meshes
Map<String, PolygonMesh> eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.meshes = new HashMap<>() private
The meshes.
Definition at line 129 of file PolyObjImporter.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.addMesh(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.buildPolygonMeshView(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.getMesh(), and eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.getMeshes().
normals
FloatArrayList eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.normals = new FloatArrayList() private
The normals.
Definition at line 247 of file PolyObjImporter.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.addMesh(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.normalIndex(), and eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.read().
objFilename
String eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.objFilename private
The obj filename.
Definition at line 138 of file PolyObjImporter.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.read().
scale
float eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.scale = 1 static private
The scale.
Definition at line 103 of file PolyObjImporter.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.read(), and eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.setScale().
smoothingGroups
IntegerArrayList eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.smoothingGroups = new IntegerArrayList() private
The smoothing groups.
Definition at line 244 of file PolyObjImporter.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.addMesh(), and eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.read().
smoothingGroupsStart
int eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.smoothingGroupsStart = 0 private
The smoothing groups start.
Definition at line 262 of file PolyObjImporter.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.addMesh().
uvs
FloatArrayList eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.uvs = new FloatArrayList() private
The uvs.
Definition at line 238 of file PolyObjImporter.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.addMesh(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.read(), and eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.uvIndex().
vertexes
FloatArrayList eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.vertexes = new FloatArrayList() private
The vertexes.
Definition at line 235 of file PolyObjImporter.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.addMesh(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.read(), and eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.vertexIndex().
The documentation for this class was generated from the following file:
JCSG/src/main/java/eu/mihosoft/vrl/v3d/ext/openjfx/importers/obj/PolyObjImporter.java