BowlerKernel: com.neuronrobotics.bowlerstudio.util.FileWatchDeviceWrapper Class Reference
com.neuronrobotics.bowlerstudio.util.FileWatchDeviceWrapper Class Reference
Static Public Member Functions
static FileChangeWatcher watch (BowlerAbstractDevice device, File code, IFileChangeListener cadWatcher)
Detailed Description
Definition at line 9 of file FileWatchDeviceWrapper.java.
Member Function Documentation
watch()
static FileChangeWatcher com.neuronrobotics.bowlerstudio.util.FileWatchDeviceWrapper.watch (BowlerAbstractDevice device, File code, IFileChangeListener cadWatcher) static
Definition at line 11 of file FileWatchDeviceWrapper.java.
References com.neuronrobotics.sdk.common.BowlerAbstractDevice.addConnectionEventListener(), com.neuronrobotics.bowlerstudio.util.FileChangeWatcher.addIFileChangeListener(), com.neuronrobotics.bowlerstudio.util.FileChangeWatcher.removeIFileChangeListener(), and com.neuronrobotics.bowlerstudio.util.FileChangeWatcher.watch().
Referenced by com.neuronrobotics.bowlerstudio.creature.MobileBaseLoader.setDefaultDhParameterKinematics(), and com.neuronrobotics.bowlerstudio.creature.MobileBaseLoader.setGitWalkingEngine().
The documentation for this class was generated from the following file:
src/main/java/com/neuronrobotics/bowlerstudio/util/FileWatchDeviceWrapper.java