BowlerKernel: com.neuronrobotics.bowlerkernel.djl.PredictorFactory Class Reference
com.neuronrobotics.bowlerkernel.djl.PredictorFactory Class Reference
Static Public Member Functions
static Predictor< Image, DetectedObjects > imageContentsFactory (ImagePredictorType type) throws ModelNotFoundException, MalformedModelException, IOException
static Predictor< Image, float[]> faceFeatureFactory () throws ModelNotFoundException, MalformedModelException, IOException
static float calculSimilarFaceFeature (float[] feature1, ArrayList< float[]> people)
static float calculSimilarFaceFeature (float[] feature1, float[] feature2)
Static Private Attributes
static HashMap< ImagePredictorType, Predictor< Image, DetectedObjects > > preloaded = new HashMap<>()
static Predictor< Image, float[]> features = null
Detailed Description
Definition at line 19 of file PredictorFactory.java.
Member Function Documentation
calculSimilarFaceFeature() [1/2]
static float com.neuronrobotics.bowlerkernel.djl.PredictorFactory.calculSimilarFaceFeature (float[] feature1, ArrayList< float[]> people) static
Definition at line 108 of file PredictorFactory.java.
Referenced by com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.processMemory().
calculSimilarFaceFeature() [2/2]
static float com.neuronrobotics.bowlerkernel.djl.PredictorFactory.calculSimilarFaceFeature (float[] feature1, float[] feature2) static
Definition at line 123 of file PredictorFactory.java.
faceFeatureFactory()
static Predictor<Image, float[]> com.neuronrobotics.bowlerkernel.djl.PredictorFactory.faceFeatureFactory () throws ModelNotFoundException, MalformedModelException, IOException static
Definition at line 92 of file PredictorFactory.java.
References com.neuronrobotics.bowlerkernel.djl.PredictorFactory.features.
Referenced by com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.UniquePersonFactory().
imageContentsFactory()
static Predictor<Image, DetectedObjects> com.neuronrobotics.bowlerkernel.djl.PredictorFactory.imageContentsFactory (ImagePredictorType type) throws ModelNotFoundException, MalformedModelException, IOException static
Definition at line 27 of file PredictorFactory.java.
References com.neuronrobotics.bowlerkernel.djl.PredictorFactory.preloaded.
Member Data Documentation
features
Predictor<Image, float[]> com.neuronrobotics.bowlerkernel.djl.PredictorFactory.features = null static private
Definition at line 25 of file PredictorFactory.java.
Referenced by com.neuronrobotics.bowlerkernel.djl.PredictorFactory.faceFeatureFactory().
preloaded
HashMap<ImagePredictorType, Predictor<Image, DetectedObjects> > com.neuronrobotics.bowlerkernel.djl.PredictorFactory.preloaded = new HashMap<>() static private
Definition at line 24 of file PredictorFactory.java.
Referenced by com.neuronrobotics.bowlerkernel.djl.PredictorFactory.imageContentsFactory().
The documentation for this class was generated from the following file:
src/main/java/com/neuronrobotics/bowlerkernel/djl/PredictorFactory.java