BowlerKernel: com.neuronrobotics.sdk.ui.BluetoothConnectionPanel Class Reference
com.neuronrobotics.sdk.ui.BluetoothConnectionPanel Class Reference
Classes
class BluetoothSearchProcess
Public Member Functions
BluetoothConnectionPanel (ConnectionDialog connectionDialog)
BluetoothSerialConnection getConnection ()
void refresh ()
Public Member Functions inherited from com.neuronrobotics.sdk.ui.AbstractConnectionPanel
AbstractConnectionPanel (String title, ImageIcon icon, ConnectionDialog connectionDialog)
AbstractConnectionPanel (String title, ConnectionDialog connectionDialog)
void setTitle (String title)
String getTitle ()
void setIcon (ImageIcon icon)
ImageIcon getIcon ()
ConnectionDialog getConnectionDialog ()
void setConnectionDialog (ConnectionDialog connectionDialog)
Private Attributes
BluetoothSerialConnection connection
BlueCoveManager blue = null
boolean displayWarning = false
JComboBox connectionCbo
JButton search
JProgressBar progress = new JProgressBar()
JLabel message = new JLabel()
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
The Class BluetoothConnectionPanel.
Definition at line 40 of file BluetoothConnectionPanel.java.
Constructor & Destructor Documentation
BluetoothConnectionPanel()
com.neuronrobotics.sdk.ui.BluetoothConnectionPanel.BluetoothConnectionPanel (ConnectionDialog connectionDialog)
Instantiates a new bluetooth connection panel.
Parameters
connectionDialog the connection dialog
Definition at line 71 of file BluetoothConnectionPanel.java.
References com.neuronrobotics.sdk.ui.BluetoothConnectionPanel.connectionCbo, com.neuronrobotics.sdk.ui.AbstractConnectionPanel.connectionDialog, com.neuronrobotics.sdk.ui.BluetoothConnectionPanel.displayWarning, com.neuronrobotics.sdk.ui.ConnectionImageIconFactory.getIcon(), com.neuronrobotics.sdk.ui.BluetoothConnectionPanel.message, com.neuronrobotics.sdk.ui.BluetoothConnectionPanel.progress, com.neuronrobotics.sdk.ui.BluetoothConnectionPanel.refresh(), and com.neuronrobotics.sdk.ui.BluetoothConnectionPanel.search.
Member Function Documentation
getConnection()
BluetoothSerialConnection com.neuronrobotics.sdk.ui.BluetoothConnectionPanel.getConnection ()
Gets the connection.
Returns
the connection
Reimplemented from com.neuronrobotics.sdk.ui.AbstractConnectionPanel.
Definition at line 106 of file BluetoothConnectionPanel.java.
References com.neuronrobotics.sdk.ui.BluetoothConnectionPanel.blue, com.neuronrobotics.sdk.ui.BluetoothConnectionPanel.connection, com.neuronrobotics.sdk.ui.BluetoothConnectionPanel.connectionCbo, com.neuronrobotics.sdk.wireless.bluetooth.BlueCoveManager.getDevice(), com.neuronrobotics.sdk.common.Log.info(), and com.neuronrobotics.sdk.common.Log.warning().
refresh()
void com.neuronrobotics.sdk.ui.BluetoothConnectionPanel.refresh ()
Refresh.
Reimplemented from com.neuronrobotics.sdk.ui.AbstractConnectionPanel.
Definition at line 122 of file BluetoothConnectionPanel.java.
References com.neuronrobotics.sdk.util.ProcessMonitor.addProcessMonitorListener(), com.neuronrobotics.sdk.ui.BluetoothConnectionPanel.connectionCbo, com.neuronrobotics.sdk.ui.AbstractConnectionPanel.getConnectionDialog(), com.neuronrobotics.sdk.common.Log.info(), com.neuronrobotics.sdk.ui.BluetoothConnectionPanel.message, com.neuronrobotics.sdk.ui.BluetoothConnectionPanel.progress, com.neuronrobotics.sdk.ui.BluetoothConnectionPanel.search, and com.neuronrobotics.sdk.util.ProcessMonitor.start().
Referenced by com.neuronrobotics.sdk.ui.BluetoothConnectionPanel.BluetoothConnectionPanel().
Member Data Documentation
blue
BlueCoveManager com.neuronrobotics.sdk.ui.BluetoothConnectionPanel.blue = null private
The blue.
Definition at line 49 of file BluetoothConnectionPanel.java.
Referenced by com.neuronrobotics.sdk.ui.BluetoothConnectionPanel.getConnection(), and com.neuronrobotics.sdk.ui.BluetoothConnectionPanel.BluetoothSearchProcess.run().
connection
BluetoothSerialConnection com.neuronrobotics.sdk.ui.BluetoothConnectionPanel.connection private
The connection.
Definition at line 46 of file BluetoothConnectionPanel.java.
Referenced by com.neuronrobotics.sdk.ui.BluetoothConnectionPanel.getConnection(), and com.neuronrobotics.sdk.ui.BluetoothConnectionPanel.BluetoothSearchProcess.run().
connectionCbo
JComboBox com.neuronrobotics.sdk.ui.BluetoothConnectionPanel.connectionCbo private
The connection cbo.
Definition at line 55 of file BluetoothConnectionPanel.java.
Referenced by com.neuronrobotics.sdk.ui.BluetoothConnectionPanel.BluetoothConnectionPanel(), com.neuronrobotics.sdk.ui.BluetoothConnectionPanel.getConnection(), com.neuronrobotics.sdk.ui.BluetoothConnectionPanel.refresh(), and com.neuronrobotics.sdk.ui.BluetoothConnectionPanel.BluetoothSearchProcess.run().
displayWarning
boolean com.neuronrobotics.sdk.ui.BluetoothConnectionPanel.displayWarning = false private
The display warning.
Definition at line 52 of file BluetoothConnectionPanel.java.
Referenced by com.neuronrobotics.sdk.ui.BluetoothConnectionPanel.BluetoothConnectionPanel(), and com.neuronrobotics.sdk.ui.BluetoothConnectionPanel.BluetoothSearchProcess.run().
message
JLabel com.neuronrobotics.sdk.ui.BluetoothConnectionPanel.message = new JLabel() private
The message.
Definition at line 64 of file BluetoothConnectionPanel.java.
Referenced by com.neuronrobotics.sdk.ui.BluetoothConnectionPanel.BluetoothConnectionPanel(), com.neuronrobotics.sdk.ui.BluetoothConnectionPanel.refresh(), and com.neuronrobotics.sdk.ui.BluetoothConnectionPanel.BluetoothSearchProcess.run().
progress
JProgressBar com.neuronrobotics.sdk.ui.BluetoothConnectionPanel.progress = new JProgressBar() private
The progress.
Definition at line 61 of file BluetoothConnectionPanel.java.
Referenced by com.neuronrobotics.sdk.ui.BluetoothConnectionPanel.BluetoothConnectionPanel(), and com.neuronrobotics.sdk.ui.BluetoothConnectionPanel.refresh().
search
JButton com.neuronrobotics.sdk.ui.BluetoothConnectionPanel.search private
The search.
Definition at line 58 of file BluetoothConnectionPanel.java.
Referenced by com.neuronrobotics.sdk.ui.BluetoothConnectionPanel.BluetoothConnectionPanel(), and com.neuronrobotics.sdk.ui.BluetoothConnectionPanel.refresh().
serialVersionUID
final long com.neuronrobotics.sdk.ui.BluetoothConnectionPanel.serialVersionUID = 1L static private
The Constant serialVersionUID.
Definition at line 43 of file BluetoothConnectionPanel.java.
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/ui/BluetoothConnectionPanel.java