BowlerKernel: com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.Tester Class Reference
com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.Tester Class Reference
Public Member Functions
void run ()
void kill ()
Private Attributes
boolean running =true
Detailed Description
The Class Tester.
Definition at line 493 of file ServoOutputScheduleChannel.java.
Member Function Documentation
kill()
void com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.Tester.kill ()
Kill.
Definition at line 513 of file ServoOutputScheduleChannel.java.
References com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.Tester.running.
Referenced by com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.stopTest().
run()
void com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.Tester.run ()
Definition at line 501 of file ServoOutputScheduleChannel.java.
References com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.flush(), com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.getInterval(), and com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.Tester.running.
Member Data Documentation
running
boolean com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.Tester.running =true private
The running.
Definition at line 496 of file ServoOutputScheduleChannel.java.
Referenced by com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.Tester.kill(), and com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.Tester.run().
The documentation for this class was generated from the following file:
src/main/java/com/neuronrobotics/sdk/dyio/sequencer/ServoOutputScheduleChannel.java