BowlerKernel: com.neuronrobotics.sdk.bootloader.NRBoot Class Reference
com.neuronrobotics.sdk.bootloader.NRBoot Class Reference
Classes
class CoreLoader
Public Member Functions
NRBoot (BowlerAbstractDevice pm)
NRBoot (String serialPort)
boolean load (Core core)
void reset ()
NRBootLoader getDevice ()
void loadCores (ArrayList< Core > cores)
boolean isLoadDone ()
int getProgressMax ()
int getProgressValue ()
Private Member Functions
IntelHexParser getParser (Core core)
void send (IntelHexParser parse, int core)
Private Attributes
NRBootLoader boot
CoreLoader loader
int progressMax =0
int progressValue =0
Detailed Description
The Class NRBoot.
Definition at line 17 of file NRBoot.java.
Constructor & Destructor Documentation
NRBoot() [1/2]
com.neuronrobotics.sdk.bootloader.NRBoot.NRBoot (BowlerAbstractDevice pm)
Instantiates a new NR boot.
Parameters
pm the pm
Definition at line 36 of file NRBoot.java.
References com.neuronrobotics.sdk.bootloader.NRBoot.boot.
NRBoot() [2/2]
com.neuronrobotics.sdk.bootloader.NRBoot.NRBoot (String serialPort)
Instantiates a new NR boot.
Parameters
serialPort the serial port
Definition at line 53 of file NRBoot.java.
References com.neuronrobotics.sdk.bootloader.NRBoot.boot, com.neuronrobotics.sdk.bootloader.NRBootLoader.connect(), com.neuronrobotics.sdk.common.BowlerAbstractDevice.disconnect(), and com.neuronrobotics.sdk.common.BowlerAbstractDevice.ping().
Member Function Documentation
getDevice()
NRBootLoader com.neuronrobotics.sdk.bootloader.NRBoot.getDevice ()
Gets the device.
Returns
the device
Definition at line 151 of file NRBoot.java.
References com.neuronrobotics.sdk.bootloader.NRBoot.boot.
Referenced by com.neuronrobotics.sdk.bootloader.NRBoot.load().
getParser()
IntelHexParser com.neuronrobotics.sdk.bootloader.NRBoot.getParser (Core core) private
Gets the parser.
Parameters
core the core
Returns
the parser
Definition at line 97 of file NRBoot.java.
References com.neuronrobotics.sdk.bootloader.Core.getLines(), and com.neuronrobotics.sdk.bootloader.Core.getType().
Referenced by com.neuronrobotics.sdk.bootloader.NRBoot.CoreLoader.CoreLoader(), and com.neuronrobotics.sdk.bootloader.NRBoot.load().
getProgressMax()
int com.neuronrobotics.sdk.bootloader.NRBoot.getProgressMax ()
Gets the progress max.
Returns
the progress max
Definition at line 227 of file NRBoot.java.
References com.neuronrobotics.sdk.bootloader.NRBoot.progressMax.
getProgressValue()
int com.neuronrobotics.sdk.bootloader.NRBoot.getProgressValue ()
Gets the progress value.
Returns
the progress value
Definition at line 237 of file NRBoot.java.
References com.neuronrobotics.sdk.bootloader.NRBoot.progressValue.
isLoadDone()
boolean com.neuronrobotics.sdk.bootloader.NRBoot.isLoadDone ()
Checks if is load done.
Returns
true, if is load done
Definition at line 170 of file NRBoot.java.
References com.neuronrobotics.sdk.bootloader.NRBoot.CoreLoader.isDone, and com.neuronrobotics.sdk.bootloader.NRBoot.loader.
load()
boolean com.neuronrobotics.sdk.bootloader.NRBoot.load (Core core)
Load.
Parameters
core the core
Returns
true, if successful
Definition at line 71 of file NRBoot.java.
References com.neuronrobotics.sdk.bootloader.NRBootLoader.getBootloaderID(), com.neuronrobotics.sdk.bootloader.NRBoot.getDevice(), com.neuronrobotics.sdk.bootloader.Core.getIndex(), com.neuronrobotics.sdk.bootloader.NRBoot.getParser(), com.neuronrobotics.sdk.bootloader.NRBootCoreType.getReadableName(), com.neuronrobotics.sdk.bootloader.Core.getType(), and com.neuronrobotics.sdk.bootloader.NRBoot.send().
Referenced by com.neuronrobotics.sdk.bootloader.NRBoot.CoreLoader.run().
loadCores()
void com.neuronrobotics.sdk.bootloader.NRBoot.loadCores (ArrayList< Core > cores)
Load cores.
Parameters
cores the cores
Definition at line 160 of file NRBoot.java.
References com.neuronrobotics.sdk.bootloader.NRBoot.loader.
reset()
void com.neuronrobotics.sdk.bootloader.NRBoot.reset ()
Reset.
Definition at line 138 of file NRBoot.java.
References com.neuronrobotics.sdk.bootloader.NRBoot.boot, com.neuronrobotics.sdk.common.BowlerAbstractDevice.disconnect(), and com.neuronrobotics.sdk.bootloader.NRBootLoader.reset().
Referenced by com.neuronrobotics.sdk.bootloader.NRBoot.CoreLoader.run().
send()
void com.neuronrobotics.sdk.bootloader.NRBoot.send (IntelHexParser parse, int core) private
Send.
Parameters
parse the parse
core the core
Definition at line 111 of file NRBoot.java.
References com.neuronrobotics.sdk.bootloader.NRBoot.boot, com.neuronrobotics.sdk.bootloader.NRBootLoader.erase(), com.neuronrobotics.sdk.bootloader.IntelHexParser.getNext(), com.neuronrobotics.sdk.bootloader.NRBoot.progressValue, and com.neuronrobotics.sdk.bootloader.NRBootLoader.write().
Referenced by com.neuronrobotics.sdk.bootloader.NRBoot.load().
Member Data Documentation
boot
NRBootLoader com.neuronrobotics.sdk.bootloader.NRBoot.boot private
The boot.
Definition at line 20 of file NRBoot.java.
Referenced by com.neuronrobotics.sdk.bootloader.NRBoot.getDevice(), com.neuronrobotics.sdk.bootloader.NRBoot.NRBoot(), com.neuronrobotics.sdk.bootloader.NRBoot.reset(), and com.neuronrobotics.sdk.bootloader.NRBoot.send().
loader
CoreLoader com.neuronrobotics.sdk.bootloader.NRBoot.loader private
The loader.
Definition at line 23 of file NRBoot.java.
Referenced by com.neuronrobotics.sdk.bootloader.NRBoot.isLoadDone(), and com.neuronrobotics.sdk.bootloader.NRBoot.loadCores().
progressMax
int com.neuronrobotics.sdk.bootloader.NRBoot.progressMax =0 private
The progress max.
Definition at line 26 of file NRBoot.java.
Referenced by com.neuronrobotics.sdk.bootloader.NRBoot.CoreLoader.CoreLoader(), and com.neuronrobotics.sdk.bootloader.NRBoot.getProgressMax().
progressValue
int com.neuronrobotics.sdk.bootloader.NRBoot.progressValue =0 private
The progress value.
Definition at line 29 of file NRBoot.java.
Referenced by com.neuronrobotics.sdk.bootloader.NRBoot.CoreLoader.CoreLoader(), com.neuronrobotics.sdk.bootloader.NRBoot.getProgressValue(), com.neuronrobotics.sdk.bootloader.NRBoot.CoreLoader.run(), and com.neuronrobotics.sdk.bootloader.NRBoot.send().
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/bootloader/NRBoot.java