BowlerKernel: com.neuronrobotics.sdk.common.Log.Message Class Reference
com.neuronrobotics.sdk.common.Log.Message Class Reference
Public Member Functions
Message (String message, int importance)
void init (String message, int importance)
String toString ()
Private Attributes
String message
int importance
Date datetime
String callingClass
Detailed Description
A log message.
Author
rbreznak
Definition at line 349 of file Log.java.
Constructor & Destructor Documentation
Message()
com.neuronrobotics.sdk.common.Log.Message.Message (String message, int importance)
Instantiates a new message.
Parameters
message the message
importance the importance
Definition at line 369 of file Log.java.
References com.neuronrobotics.sdk.common.Log.Message.importance, com.neuronrobotics.sdk.common.Log.Message.init(), and com.neuronrobotics.sdk.common.Log.Message.message.
Member Function Documentation
init()
void com.neuronrobotics.sdk.common.Log.Message.init (String message, int importance)
Inits the.
Parameters
message the message
importance the importance
Definition at line 379 of file Log.java.
References com.neuronrobotics.sdk.common.Log.Message.callingClass, com.neuronrobotics.sdk.common.Log.Message.datetime, com.neuronrobotics.sdk.common.Log.Message.importance, and com.neuronrobotics.sdk.common.Log.Message.message.
Referenced by com.neuronrobotics.sdk.common.Log.add(), and com.neuronrobotics.sdk.common.Log.Message.Message().
toString()
String com.neuronrobotics.sdk.common.Log.Message.toString ()
Definition at line 396 of file Log.java.
References com.neuronrobotics.sdk.common.Log.Message.callingClass, com.neuronrobotics.sdk.common.Log.dateFormat, com.neuronrobotics.sdk.common.Log.Message.datetime, com.neuronrobotics.sdk.common.Log.getColorNormalizationCode(), com.neuronrobotics.sdk.common.Log.getImportance(), com.neuronrobotics.sdk.common.Log.getImportanceColor(), com.neuronrobotics.sdk.common.Log.Message.importance, and com.neuronrobotics.sdk.common.Log.Message.message.
Member Data Documentation
callingClass
String com.neuronrobotics.sdk.common.Log.Message.callingClass private
The calling class.
Definition at line 361 of file Log.java.
Referenced by com.neuronrobotics.sdk.common.Log.Message.init(), and com.neuronrobotics.sdk.common.Log.Message.toString().
datetime
Date com.neuronrobotics.sdk.common.Log.Message.datetime private
The datetime.
Definition at line 358 of file Log.java.
Referenced by com.neuronrobotics.sdk.common.Log.Message.init(), and com.neuronrobotics.sdk.common.Log.Message.toString().
importance
int com.neuronrobotics.sdk.common.Log.Message.importance private
The importance.
Definition at line 355 of file Log.java.
Referenced by com.neuronrobotics.sdk.common.Log.Message.init(), com.neuronrobotics.sdk.common.Log.Message.Message(), and com.neuronrobotics.sdk.common.Log.Message.toString().
message
String com.neuronrobotics.sdk.common.Log.Message.message private
The message.
Definition at line 352 of file Log.java.
Referenced by com.neuronrobotics.sdk.common.Log.Message.init(), com.neuronrobotics.sdk.common.Log.Message.Message(), and com.neuronrobotics.sdk.common.Log.Message.toString().
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/common/Log.java