BowlerKernel: eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder Class Reference
eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder Class Reference
Classes
class Edge
class EdgeInfo
class FaceInfo
class PointInfo
Public Member Functions
SymbolicSubdivisionBuilder (SymbolicPolygonMesh oldMesh, BoundaryMode boundaryMode, MapBorderMode mapBorderMode)
SymbolicPolygonMesh subdivide ()
Static Public Member Functions
static SymbolicPolygonMesh subdivide (SymbolicPolygonMesh oldMesh, BoundaryMode boundaryMode, MapBorderMode mapBorderMode)
Private Member Functions
void addEdge (Edge edge, FaceInfo faceInfo)
void addPoint (int point, FaceInfo faceInfo, Edge edge)
void addPoint (int point, Edge edge)
void collectInfo ()
int calcControlPoint (int srcPointIndex)
void calcControlTexCoord (FaceInfo faceInfo, int srcPointIndex, int srcTexCoordIndex, int destTexCoordIndex)
int getPointNewIndex (int srcPointIndex)
int getPointNewIndex (FaceInfo faceInfo, int edgeInd)
int getPointNewIndex (FaceInfo faceInfo)
int getTexCoordNewIndex (FaceInfo faceInfo, int srcPointIndex, int srcTexCoordIndex)
int getTexCoordNewIndex (FaceInfo faceInfo, int edgeInd)
int getTexCoordNewIndex (FaceInfo faceInfo)
Private Attributes
SymbolicPolygonMesh oldMesh
Map< Edge, EdgeInfo > edgeInfos
FaceInfo[] faceInfos
PointInfo[] pointInfos
SubdividedPointArray points
float[] texCoords
int[] reindex
int newTexCoordIndex
BoundaryMode boundaryMode
MapBorderMode mapBorderMode
Detailed Description
Data structure builder for Catmull Clark subdivision surface.
Definition at line 49 of file SymbolicSubdivisionBuilder.java.
Constructor & Destructor Documentation
SymbolicSubdivisionBuilder()
eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.SymbolicSubdivisionBuilder (SymbolicPolygonMesh oldMesh, BoundaryMode boundaryMode, MapBorderMode mapBorderMode)
Instantiates a new symbolic subdivision builder.
Parameters
oldMesh the old mesh
boundaryMode the boundary mode
mapBorderMode the map border mode
Definition at line 88 of file SymbolicSubdivisionBuilder.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.boundaryMode, eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.mapBorderMode, and eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.oldMesh.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.subdivide().
Member Function Documentation
addEdge()
void eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.addEdge (Edge edge, FaceInfo faceInfo) private
Adds the edge.
Parameters
edge the edge
faceInfo the face info
Definition at line 168 of file SymbolicSubdivisionBuilder.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.edgeInfos.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.collectInfo().
addPoint() [1/2]
void eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.addPoint (int point, Edge edge) private
Adds the point.
Parameters
point the point
edge the edge
Definition at line 201 of file SymbolicSubdivisionBuilder.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.pointInfos.
addPoint() [2/2]
void eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.addPoint (int point, FaceInfo faceInfo, Edge edge) private
Adds the point.
Parameters
point the point
faceInfo the face info
edge the edge
Definition at line 185 of file SymbolicSubdivisionBuilder.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.pointInfos.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.collectInfo().
calcControlPoint()
int eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.calcControlPoint (int srcPointIndex) private
Calc control point.
Parameters
srcPointIndex the src point index
Returns
the int
Definition at line 280 of file SymbolicSubdivisionBuilder.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SubdividedPointArray.addControlPoint(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.edgeInfos, eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.PointInfo.hasInternalEdge(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.PointInfo.isBoundary(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.pointInfos, and eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.points.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.getPointNewIndex().
calcControlTexCoord()
void eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.calcControlTexCoord (FaceInfo faceInfo, int srcPointIndex, int srcTexCoordIndex, int destTexCoordIndex) private
Calc control tex coord.
Parameters
faceInfo the face info
srcPointIndex the src point index
srcTexCoordIndex the src tex coord index
destTexCoordIndex the dest tex coord index
Definition at line 313 of file SymbolicSubdivisionBuilder.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.PointInfo.hasInternalEdge(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.PointInfo.isBoundary(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.mapBorderMode, eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.oldMesh, eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.pointInfos, eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicPolygonMesh.points, eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.MapBorderMode.SMOOTH_ALL, eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.MapBorderMode.SMOOTH_INTERNAL, eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicPolygonMesh.texCoords, and eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.texCoords.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.getTexCoordNewIndex().
collectInfo()
void eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.collectInfo () private
Collect info.
Definition at line 213 of file SymbolicSubdivisionBuilder.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.addEdge(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SubdividedPointArray.addEdgePoint(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SubdividedPointArray.addFacePoint(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.addPoint(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.boundaryMode, eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.edgeInfos, eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.faceInfos, eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicPolygonMesh.faces, eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicPointArray.numPoints, eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.oldMesh, eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.pointInfos, eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicPolygonMesh.points, eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.points, and eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicPolygonMesh.texCoords.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.subdivide().
getPointNewIndex() [1/3]
int eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.getPointNewIndex (FaceInfo faceInfo) private
Gets the point new index.
Parameters
faceInfo the face info
Returns
the point new index
Definition at line 368 of file SymbolicSubdivisionBuilder.java.
getPointNewIndex() [2/3]
int eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.getPointNewIndex (FaceInfo faceInfo, int edgeInd) private
Gets the point new index.
Parameters
faceInfo the face info
edgeInd the edge ind
Returns
the point new index
Definition at line 356 of file SymbolicSubdivisionBuilder.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.edgeInfos.
getPointNewIndex() [3/3]
int eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.getPointNewIndex (int srcPointIndex) private
Gets the point new index.
Parameters
srcPointIndex the src point index
Returns
the point new index
Definition at line 340 of file SymbolicSubdivisionBuilder.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.calcControlPoint(), and eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.reindex.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.subdivide().
getTexCoordNewIndex() [1/3]
int eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.getTexCoordNewIndex (FaceInfo faceInfo) private
Gets the tex coord new index.
Parameters
faceInfo the face info
Returns
the tex coord new index
Definition at line 408 of file SymbolicSubdivisionBuilder.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.newTexCoordIndex, and eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.texCoords.
getTexCoordNewIndex() [2/3]
int eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.getTexCoordNewIndex (FaceInfo faceInfo, int edgeInd) private
Gets the tex coord new index.
Parameters
faceInfo the face info
edgeInd the edge ind
Returns
the tex coord new index
Definition at line 394 of file SymbolicSubdivisionBuilder.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.newTexCoordIndex, and eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.texCoords.
getTexCoordNewIndex() [3/3]
int eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.getTexCoordNewIndex (FaceInfo faceInfo, int srcPointIndex, int srcTexCoordIndex) private
Gets the tex coord new index.
Parameters
faceInfo the face info
srcPointIndex the src point index
srcTexCoordIndex the src tex coord index
Returns
the tex coord new index
Definition at line 380 of file SymbolicSubdivisionBuilder.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.calcControlTexCoord(), and eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.newTexCoordIndex.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.subdivide().
subdivide() [1/2]
SymbolicPolygonMesh eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.subdivide ()
Subdivide.
Returns
the symbolic polygon mesh
Definition at line 99 of file SymbolicSubdivisionBuilder.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.collectInfo(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.faceInfos, eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicPolygonMesh.faces, eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicPolygonMesh.faceSmoothingGroups, eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicPolygonMesh.getNumEdgesInFaces(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.getPointNewIndex(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.getTexCoordNewIndex(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.newTexCoordIndex, eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicPointArray.numPoints, eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.oldMesh, eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicPolygonMesh.points, eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.points, eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.reindex, and eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.texCoords.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.subdivide(), and eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.update().
subdivide() [2/2]
static SymbolicPolygonMesh eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.subdivide (SymbolicPolygonMesh oldMesh, BoundaryMode boundaryMode, MapBorderMode mapBorderMode) static
Subdivide.
Parameters
oldMesh the old mesh
boundaryMode the boundary mode
mapBorderMode the map border mode
Returns
the symbolic polygon mesh
Definition at line 157 of file SymbolicSubdivisionBuilder.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.boundaryMode, eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.mapBorderMode, eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.oldMesh, eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.subdivide(), and eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.SymbolicSubdivisionBuilder().
Member Data Documentation
boundaryMode
BoundaryMode eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.boundaryMode private
The boundary mode.
Definition at line 76 of file SymbolicSubdivisionBuilder.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.collectInfo(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.subdivide(), and eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.SymbolicSubdivisionBuilder().
edgeInfos
Map<Edge, EdgeInfo> eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.edgeInfos private
The edge infos.
Definition at line 55 of file SymbolicSubdivisionBuilder.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.addEdge(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.calcControlPoint(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.collectInfo(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.getPointNewIndex(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.PointInfo.hasInternalEdge(), and eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.PointInfo.isBoundary().
faceInfos
FaceInfo [] eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.faceInfos private
The face infos.
Definition at line 58 of file SymbolicSubdivisionBuilder.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.collectInfo(), and eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.subdivide().
mapBorderMode
MapBorderMode eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.mapBorderMode private
The map border mode.
Definition at line 79 of file SymbolicSubdivisionBuilder.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.calcControlTexCoord(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.subdivide(), and eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.SymbolicSubdivisionBuilder().
newTexCoordIndex
int eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.newTexCoordIndex private
The new tex coord index.
Definition at line 73 of file SymbolicSubdivisionBuilder.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.getTexCoordNewIndex(), and eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.subdivide().
oldMesh
SymbolicPolygonMesh eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.oldMesh private
The old mesh.
Definition at line 52 of file SymbolicSubdivisionBuilder.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.calcControlTexCoord(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.collectInfo(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.subdivide(), and eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.SymbolicSubdivisionBuilder().
pointInfos
PointInfo [] eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.pointInfos private
The point infos.
Definition at line 61 of file SymbolicSubdivisionBuilder.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.addPoint(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.calcControlPoint(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.calcControlTexCoord(), and eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.collectInfo().
points
SubdividedPointArray eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.points private
The points.
Definition at line 64 of file SymbolicSubdivisionBuilder.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.calcControlPoint(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.collectInfo(), and eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.subdivide().
reindex
int [] eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.reindex private
The reindex.
Definition at line 70 of file SymbolicSubdivisionBuilder.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.getPointNewIndex(), and eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.subdivide().
texCoords
float [] eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.texCoords private
The tex coords.
Definition at line 67 of file SymbolicSubdivisionBuilder.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.calcControlTexCoord(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.getTexCoordNewIndex(), and eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.subdivide().
The documentation for this class was generated from the following file:
JCSG/src/main/java/eu/mihosoft/vrl/v3d/ext/openjfx/shape3d/symbolic/SymbolicSubdivisionBuilder.java