BowlerKernel: com.neuronrobotics.sdk.addons.kinematics.MockRotoryLink Class Reference
com.neuronrobotics.sdk.addons.kinematics.MockRotoryLink Class Reference
Public Member Functions
MockRotoryLink (LinkConfiguration conf)
void cacheTargetValueDevice ()
void flushDevice (double time)
double getCurrentPosition ()
void flushAllDevice (double time)
Public Member Functions inherited from com.neuronrobotics.sdk.addons.kinematics.AbstractRotoryLink
AbstractRotoryLink (LinkConfiguration conf)
void incrementAngle (double inc)
void setTargetAngle (double pos)
void setCurrentAsAngle (double angle)
double getCurrentAngle ()
double getTargetAngle ()
double getMaxAngle ()
double getMinAngle ()
boolean isMaxAngle ()
boolean isMinAngle ()
Public Member Functions inherited from com.neuronrobotics.sdk.addons.kinematics.AbstractLink
double getDeviceMaximumValue ()
double getDeviceMinimumValue ()
void setDeviceMaximumValue (double max)
void setDeviceMinimumValue (double min)
double getDeviceMaxEngineeringUnits ()
double getDeviceMinEngineeringUnits ()
AbstractLink (LinkConfiguration conf)
void cacheTargetValue ()
void flush (double time)
void flushAll (double time)
double toEngineeringUnits (double value)
double toLinkUnits (double euValue)
void addLinkListener (ILinkListener l)
void removeLinkListener (ILinkListener l)
void fireLinkListener (double linkUnitsValue)
void fireLinkLimitEvent (PIDLimitEvent e)
void Home ()
void incrementEngineeringUnits (double inc)
void setTargetEngineeringUnits (double pos)
void setCurrentEngineeringUnits (double angle)
double getCurrentEngineeringUnits ()
double getTargetEngineeringUnits ()
double getMaxEngineeringUnits ()
double getMinEngineeringUnits ()
void setMinEngineeringUnits (double minLimit)
void setMaxEngineeringUnits (double maxLimit)
double getMaxVelocityEngineeringUnits ()
void setMaxVelocityEngineeringUnits (double max)
boolean isMaxEngineeringUnits ()
boolean isMinEngineeringUnits ()
double getTargetValue ()
void setUpperLimit (int upperLimit)
void setLowerLimit (int lowerLimit)
void setHome (int home)
void setScale (double d)
double getScale ()
double getUpperLimit ()
double getLowerLimit ()
double getHome ()
void setCurrentAsUpperLimit ()
void setCurrentAsLowerLimit ()
void setUseLimits (boolean useLimits)
boolean isUseLimits ()
void setLinkConfiguration (LinkConfiguration conf)
LinkConfiguration getLinkConfiguration ()
ArrayList< ILinkListener > getLinks ()
void setLinks (ArrayList< ILinkListener > links)
void removeAllLinkListener ()
void setGlobalPositionListener (Object Object)
Object getGlobalPositionListener ()
LinkFactory getSlaveFactory ()
void setSlaveFactory (LinkFactory slaveFactory)
IMU getImu ()
void addChangeListener (ILinkConfigurationChangeListener l)
void removeChangeListener (ILinkConfigurationChangeListener l)
void clearChangeListener ()
Additional Inherited Members
Protected Member Functions inherited from com.neuronrobotics.sdk.addons.kinematics.AbstractLink
void setPosition (double val)
void setTargetValue (double val)
Detailed Description
The Class MockRotoryLink.
Definition at line 7 of file MockRotoryLink.java.
Constructor & Destructor Documentation
MockRotoryLink()
com.neuronrobotics.sdk.addons.kinematics.MockRotoryLink.MockRotoryLink (LinkConfiguration conf)
Instantiates a new mock rotory link.
Parameters
conf the conf
Definition at line 17 of file MockRotoryLink.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractLink.conf, com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setDeviceTheoreticalMax(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setDeviceTheoreticalMin(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setHome(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setLowerLimit(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setPauseEvents(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setScale(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setTargetValue(), and com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setUpperLimit().
Member Function Documentation
cacheTargetValueDevice()
void com.neuronrobotics.sdk.addons.kinematics.MockRotoryLink.cacheTargetValueDevice ()
This method is called in order to take the target value and pass it to the implementation's target value This method should not alter the position of the implementations link If the implementation target does not handle chached values, this should be chached in code.
Reimplemented from com.neuronrobotics.sdk.addons.kinematics.AbstractLink.
Definition at line 34 of file MockRotoryLink.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getTargetValue().
flushAllDevice()
void com.neuronrobotics.sdk.addons.kinematics.MockRotoryLink.flushAllDevice (double time)
This method will force one link to update its position in the given time (seconds) This will also flush the host controller.
Parameters
time (seconds) for the position update to take
Reimplemented from com.neuronrobotics.sdk.addons.kinematics.AbstractLink.
Definition at line 61 of file MockRotoryLink.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getTargetValue().
flushDevice()
void com.neuronrobotics.sdk.addons.kinematics.MockRotoryLink.flushDevice (double time)
This method will force one link to update its position in the given time (seconds).
Parameters
time (seconds) for the position update to take
Reimplemented from com.neuronrobotics.sdk.addons.kinematics.AbstractLink.
Definition at line 43 of file MockRotoryLink.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getTargetValue().
getCurrentPosition()
double com.neuronrobotics.sdk.addons.kinematics.MockRotoryLink.getCurrentPosition ()
This method should return the current position of the link This method is expected to perform a communication with the device .
Returns
the current position of the link
Reimplemented from com.neuronrobotics.sdk.addons.kinematics.AbstractLink.
Definition at line 52 of file MockRotoryLink.java.
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/addons/kinematics/MockRotoryLink.java