BowlerKernel: eu.mihosoft.vrl.v3d.Slice Class Reference
eu.mihosoft.vrl.v3d.Slice Class Reference
Classes
class DefaultSliceImp
Static Public Member Functions
static List< Polygon > slice (CSG incoming, Transform slicePlane, double normalInsetDistance)
static List< Polygon > slice (CSG incoming)
static List< Polygon > slice (CSG incoming, double normalInsetDistance)
static ISlice getSliceEngine ()
static void setSliceEngine (ISlice sliceEngine)
static int getMaxRes ()
static void setNumFacesInOffset (int numFacesInOffset)
static void setMaxRes (int mr)
Static Private Member Functions
static boolean isPolygonAtZero (Polygon polygon)
static boolean isVertexAtZero (Vertex vertex)
static List< Polygon > sanatize (List< Polygon > slice)
Static Private Attributes
static int maxRes = 3000
static ISlice sliceEngine = new DefaultSliceImp()
Detailed Description
Definition at line 26 of file Slice.java.
Member Function Documentation
getMaxRes()
static int eu.mihosoft.vrl.v3d.Slice.getMaxRes () static
Definition at line 504 of file Slice.java.
References eu.mihosoft.vrl.v3d.Slice.maxRes.
getSliceEngine()
static ISlice eu.mihosoft.vrl.v3d.Slice.getSliceEngine () static
Definition at line 496 of file Slice.java.
References eu.mihosoft.vrl.v3d.Slice.sliceEngine.
Referenced by eu.mihosoft.vrl.v3d.Slice.slice().
isPolygonAtZero()
static boolean eu.mihosoft.vrl.v3d.Slice.isPolygonAtZero (Polygon polygon) static private
Returns true if this polygon lies entirely in the z plane
Parameters
polygon The polygon to check
Returns
True if this polygon is entirely in the z plane
Definition at line 428 of file Slice.java.
References eu.mihosoft.vrl.v3d.Slice.isVertexAtZero(), and eu.mihosoft.vrl.v3d.Polygon.vertices.
isVertexAtZero()
static boolean eu.mihosoft.vrl.v3d.Slice.isVertexAtZero (Vertex vertex) static private
Returns true if this vertex is at z coordinate zero
Parameters
vertex The vertex to check
Returns
True if this vertex is at z coordinate zero
Definition at line 446 of file Slice.java.
References eu.mihosoft.vrl.v3d.Vertex.getZ().
Referenced by eu.mihosoft.vrl.v3d.Slice.isPolygonAtZero().
sanatize()
static List<Polygon> eu.mihosoft.vrl.v3d.Slice.sanatize (List< Polygon > slice) static private
Definition at line 474 of file Slice.java.
References eu.mihosoft.vrl.v3d.Polygon.fromPoints(), eu.mihosoft.vrl.v3d.Polygon.getPoints(), eu.mihosoft.vrl.v3d.Extrude.isCCW(), and eu.mihosoft.vrl.v3d.Slice.slice().
Referenced by eu.mihosoft.vrl.v3d.Slice.slice().
setMaxRes()
static void eu.mihosoft.vrl.v3d.Slice.setMaxRes (int mr) static
Definition at line 511 of file Slice.java.
References eu.mihosoft.vrl.v3d.Slice.maxRes.
setNumFacesInOffset()
static void eu.mihosoft.vrl.v3d.Slice.setNumFacesInOffset (int numFacesInOffset) static
Definition at line 508 of file Slice.java.
References eu.mihosoft.vrl.v3d.CSG.setNumFacesInOffset().
setSliceEngine()
static void eu.mihosoft.vrl.v3d.Slice.setSliceEngine (ISlice sliceEngine) static
Definition at line 500 of file Slice.java.
References eu.mihosoft.vrl.v3d.Slice.sliceEngine.
slice() [1/3]
static List<Polygon> eu.mihosoft.vrl.v3d.Slice.slice (CSG incoming) static
Definition at line 490 of file Slice.java.
References eu.mihosoft.vrl.v3d.Slice.slice().
slice() [2/3]
static List<Polygon> eu.mihosoft.vrl.v3d.Slice.slice (CSG incoming, double normalInsetDistance) static
Definition at line 493 of file Slice.java.
References eu.mihosoft.vrl.v3d.Slice.slice().
slice() [3/3]
static List<Polygon> eu.mihosoft.vrl.v3d.Slice.slice (CSG incoming, Transform slicePlane, double normalInsetDistance) static
Definition at line 456 of file Slice.java.
References eu.mihosoft.vrl.v3d.CSG.getPolygons(), eu.mihosoft.vrl.v3d.Slice.getSliceEngine(), eu.mihosoft.vrl.v3d.JavaFXInitializer.go(), eu.mihosoft.vrl.v3d.Slice.sanatize(), and eu.mihosoft.vrl.v3d.Slice.sliceEngine.
Referenced by eu.mihosoft.vrl.v3d.svg.SVGExporter.addCsg(), eu.mihosoft.vrl.v3d.Fillet.outerFillet(), eu.mihosoft.vrl.v3d.Slice.sanatize(), and eu.mihosoft.vrl.v3d.Slice.slice().
Member Data Documentation
maxRes
int eu.mihosoft.vrl.v3d.Slice.maxRes = 3000 static private
Definition at line 27 of file Slice.java.
Referenced by eu.mihosoft.vrl.v3d.Slice.getMaxRes(), and eu.mihosoft.vrl.v3d.Slice.setMaxRes().
sliceEngine
ISlice eu.mihosoft.vrl.v3d.Slice.sliceEngine = new DefaultSliceImp() static private
Definition at line 419 of file Slice.java.
Referenced by eu.mihosoft.vrl.v3d.Slice.getSliceEngine(), eu.mihosoft.vrl.v3d.Slice.setSliceEngine(), and eu.mihosoft.vrl.v3d.Slice.slice().
The documentation for this class was generated from the following file:
JCSG/src/main/java/eu/mihosoft/vrl/v3d/Slice.java