BowlerKernel: com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel Class Reference
com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel Class Reference
Classes
class MapData
class Tester
Public Member Functions
ServoOutputScheduleChannel (ServoChannel srv)
int getChannelNumber ()
void pauseRecording ()
void resumeRecording ()
void addAnalogInputListener (IAnalogInputListener l)
void startRecording ()
void onTimeUpdate (double ms)
void setIntervalTime (int msInterval, int totalTime)
void onAnalogValueChange (AnalogInputChannel chan, double value)
void setOutput (ServoChannel output)
ServoChannel getOutput ()
void setInputCenter (int inputCenter)
int getInputCenter ()
void setInputScale (double inputScale)
double getInputScale ()
void setOutputMinMax (int outputMin, int outputMax)
int getOutputMax ()
int getOutputMin ()
boolean isRecording ()
void addIServoPositionUpdateListener (IServoPositionUpdateListener l)
void removeIServoPositionUpdateListener (IServoPositionUpdateListener l)
String getXml ()
int getInputChannelNumber ()
void setData (int[] data2)
void startTest ()
void stopTest ()
boolean isTesting ()
void setInterval (double interval)
double getInterval ()
void setCurrentTargetValue (int inputValue)
int getCurrentTargetValue ()
void flush ()
void setAnalogInputChannelNumber (int analogInputChannelNumber)
int getAnalogInputChannelNumber ()
void setRecording (boolean recording)
void onReset ()
void onPlay ()
void onPause ()
int getCurrentValue ()
void setCurrentValue (int currentValue)
void sync (int loopTime)
Private Member Functions
void initInput ()
Private Attributes
ServoChannel output
double inputScale =.25
int inputCenter = 128
int inputValue
boolean recording =false
double interval
int currentValue
ArrayList< MapData > data = new ArrayList<MapData>()
int outputMax =255
int outputMin =0
int index =0
Tester directTester
int analogInputChannelNumber =8
Detailed Description
The Class ServoOutputScheduleChannel.
Definition at line 14 of file ServoOutputScheduleChannel.java.
Constructor & Destructor Documentation
ServoOutputScheduleChannel()
com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.ServoOutputScheduleChannel (ServoChannel srv)
Instantiates a new servo output schedule channel.
Parameters
srv the srv
Definition at line 63 of file ServoOutputScheduleChannel.java.
References com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral.getValue(), com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.output, and com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.setCurrentValue().
Member Function Documentation
addAnalogInputListener()
void com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.addAnalogInputListener (IAnalogInputListener l)
Adds the analog input listener.
Parameters
l the l
Definition at line 105 of file ServoOutputScheduleChannel.java.
References com.neuronrobotics.sdk.dyio.peripherals.AnalogInputChannel.addAnalogInputListener(), com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral.configAdvancedAsyncNotEqual(), and com.neuronrobotics.sdk.dyio.peripherals.AnalogInputChannel.setAsync().
Referenced by com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.initInput().
addIServoPositionUpdateListener()
void com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.addIServoPositionUpdateListener (IServoPositionUpdateListener l)
Adds the i servo position update listener.
Parameters
l the l
Definition at line 320 of file ServoOutputScheduleChannel.java.
References com.neuronrobotics.sdk.dyio.peripherals.ServoChannel.addIServoPositionUpdateListener(), and com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.getOutput().
flush()
void com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.flush ()
Flush.
Definition at line 455 of file ServoOutputScheduleChannel.java.
References com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral.flush(), com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.getCurrentTargetValue(), com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.output, and com.neuronrobotics.sdk.dyio.peripherals.ServoChannel.SetPosition().
Referenced by com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.Tester.run().
getAnalogInputChannelNumber()
int com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.getAnalogInputChannelNumber ()
Gets the analog input channel number.
Returns
the analog input channel number
Definition at line 475 of file ServoOutputScheduleChannel.java.
References com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.analogInputChannelNumber, com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral.getChannel(), and com.neuronrobotics.sdk.dyio.DyIOChannel.getChannelNumber().
Referenced by com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.getInputChannelNumber(), com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.getXml(), and com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.initInput().
getChannelNumber()
int com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.getChannelNumber ()
Gets the channel number.
Returns
the channel number
Definition at line 74 of file ServoOutputScheduleChannel.java.
References com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral.getChannel(), com.neuronrobotics.sdk.dyio.DyIOChannel.getChannelNumber(), and com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.output.
Referenced by com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.getXml(), and com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.startTest().
getCurrentTargetValue()
int com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.getCurrentTargetValue ()
Gets the current target value.
Returns
the current target value
Definition at line 448 of file ServoOutputScheduleChannel.java.
References com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.inputValue.
Referenced by com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.flush(), com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.onAnalogValueChange(), com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.onTimeUpdate(), and com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.setIntervalTime().
getCurrentValue()
int com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.getCurrentValue ()
Gets the current value.
Returns
the current value
Definition at line 550 of file ServoOutputScheduleChannel.java.
References com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.currentValue.
Referenced by com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.onTimeUpdate(), com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.setIntervalTime(), and com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.sync().
getInputCenter()
int com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.getInputCenter ()
Gets the input center.
Returns
the input center
Definition at line 237 of file ServoOutputScheduleChannel.java.
References com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.inputCenter.
Referenced by com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.onAnalogValueChange().
getInputChannelNumber()
int com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.getInputChannelNumber ()
Gets the input channel number.
Returns
the input channel number
Definition at line 364 of file ServoOutputScheduleChannel.java.
References com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.getAnalogInputChannelNumber(), com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral.getChannel(), and com.neuronrobotics.sdk.dyio.DyIOChannel.getChannelNumber().
getInputScale()
double com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.getInputScale ()
Gets the input scale.
Returns
the input scale
Definition at line 255 of file ServoOutputScheduleChannel.java.
References com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.inputScale.
Referenced by com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.onAnalogValueChange().
getInterval()
double com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.getInterval ()
Gets the interval.
Returns
the interval
Definition at line 427 of file ServoOutputScheduleChannel.java.
References com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.interval.
Referenced by com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.onTimeUpdate(), and com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.Tester.run().
getOutput()
ServoChannel com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.getOutput ()
Gets the output.
Returns
the output
Definition at line 219 of file ServoOutputScheduleChannel.java.
References com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.output.
Referenced by com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.addIServoPositionUpdateListener(), com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.removeIServoPositionUpdateListener(), and com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.sync().
getOutputMax()
int com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.getOutputMax ()
Gets the output max.
Returns
the output max
Definition at line 275 of file ServoOutputScheduleChannel.java.
References com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.outputMax.
Referenced by com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.onAnalogValueChange(), and com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.setIntervalTime().
getOutputMin()
int com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.getOutputMin ()
Gets the output min.
Returns
the output min
Definition at line 284 of file ServoOutputScheduleChannel.java.
References com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.outputMin.
Referenced by com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.onAnalogValueChange(), and com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.setIntervalTime().
getXml()
String com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.getXml ()
Gets the xml.
Returns
the xml
Definition at line 338 of file ServoOutputScheduleChannel.java.
References com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.data, com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.getAnalogInputChannelNumber(), com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.getChannelNumber(), com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.inputCenter, com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.inputScale, com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.isRecording(), com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.outputMax, and com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.outputMin.
initInput()
void com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.initInput () private
Inits the input.
Definition at line 114 of file ServoOutputScheduleChannel.java.
References com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.addAnalogInputListener(), com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.analogInputChannelNumber, com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.getAnalogInputChannelNumber(), com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral.getChannel(), com.neuronrobotics.sdk.dyio.DyIO.getChannel(), com.neuronrobotics.sdk.dyio.DyIOChannel.getChannelNumber(), com.neuronrobotics.sdk.dyio.DyIOChannel.getDevice(), com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.output, and com.neuronrobotics.sdk.dyio.peripherals.AnalogInputChannel.removeAllAnalogInputListeners().
Referenced by com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.resumeRecording(), com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.startRecording(), and com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.startTest().
isRecording()
boolean com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.isRecording ()
Checks if is recording.
Returns
true, if is recording
Definition at line 311 of file ServoOutputScheduleChannel.java.
References com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.recording.
Referenced by com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.getXml(), and com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.onTimeUpdate().
isTesting()
boolean com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.isTesting ()
Checks if is testing.
Returns
true, if is testing
Definition at line 409 of file ServoOutputScheduleChannel.java.
References com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.directTester.
onAnalogValueChange()
void com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.onAnalogValueChange (AnalogInputChannel chan, double value)
IAnalogInputListener.
Parameters
chan the chan
value The value of the analog channel is sent to listeners
Implements com.neuronrobotics.sdk.dyio.peripherals.IAnalogInputListener.
Definition at line 186 of file ServoOutputScheduleChannel.java.
References com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.getCurrentTargetValue(), com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.getInputCenter(), com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.getInputScale(), com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.getOutputMax(), com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.getOutputMin(), and com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.setCurrentTargetValue().
onPause()
void com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.onPause ()
On pause.
Implements com.neuronrobotics.sdk.dyio.sequencer.ISchedulerListener.
Definition at line 540 of file ServoOutputScheduleChannel.java.
onPlay()
void com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.onPlay ()
On play.
Implements com.neuronrobotics.sdk.dyio.sequencer.ISchedulerListener.
Definition at line 531 of file ServoOutputScheduleChannel.java.
onReset()
void com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.onReset ()
This function is called when the seceduler is stopped.
Implements com.neuronrobotics.sdk.dyio.sequencer.ISchedulerListener.
Definition at line 522 of file ServoOutputScheduleChannel.java.
onTimeUpdate()
void com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.onTimeUpdate (double ms)
This is called by the scheduler on regular intervals .
Parameters
ms the current time of the running scheduler
Implements com.neuronrobotics.sdk.dyio.sequencer.ISchedulerListener.
Definition at line 139 of file ServoOutputScheduleChannel.java.
References com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.data, com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.getCurrentTargetValue(), com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.getCurrentValue(), com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.getInterval(), com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.index, com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.isRecording(), and com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.setCurrentValue().
pauseRecording()
void com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.pauseRecording ()
Pause recording.
Definition at line 81 of file ServoOutputScheduleChannel.java.
References com.neuronrobotics.sdk.dyio.peripherals.AnalogInputChannel.removeAnalogInputListener(), and com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.setRecording().
Referenced by com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.loadFromFile().
removeIServoPositionUpdateListener()
void com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.removeIServoPositionUpdateListener (IServoPositionUpdateListener l)
Removes the i servo position update listener.
Parameters
l the l
Definition at line 329 of file ServoOutputScheduleChannel.java.
References com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.getOutput(), and com.neuronrobotics.sdk.dyio.peripherals.ServoChannel.removeIServoPositionUpdateListener().
resumeRecording()
void com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.resumeRecording ()
Resume recording.
Definition at line 91 of file ServoOutputScheduleChannel.java.
References com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.initInput(), and com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.setRecording().
Referenced by com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.startRecording().
setAnalogInputChannelNumber()
void com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.setAnalogInputChannelNumber (int analogInputChannelNumber)
Sets the analog input channel number.
Parameters
analogInputChannelNumber the new analog input channel number
Definition at line 465 of file ServoOutputScheduleChannel.java.
References com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.analogInputChannelNumber.
Referenced by com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.loadFromFile().
setCurrentTargetValue()
void com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.setCurrentTargetValue (int inputValue)
Sets the current target value.
Parameters
inputValue the new current target value
Definition at line 436 of file ServoOutputScheduleChannel.java.
References com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.inputValue.
Referenced by com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.onAnalogValueChange(), and com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.setIntervalTime().
setCurrentValue()
void com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.setCurrentValue (int currentValue)
Sets the current value.
Parameters
currentValue the new current value
Definition at line 559 of file ServoOutputScheduleChannel.java.
References com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.currentValue.
Referenced by com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.onTimeUpdate(), com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.ServoOutputScheduleChannel(), and com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.setIntervalTime().
setData()
void com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.setData (int[] data2)
Sets the data.
Parameters
data2 the new data
Definition at line 375 of file ServoOutputScheduleChannel.java.
References com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.data.
Referenced by com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.loadFromFile().
setInputCenter()
void com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.setInputCenter (int inputCenter)
Sets the input center.
Parameters
inputCenter the new input center
Definition at line 228 of file ServoOutputScheduleChannel.java.
References com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.inputCenter.
Referenced by com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.loadFromFile().
setInputScale()
void com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.setInputScale (double inputScale)
Sets the input scale.
Parameters
inputScale the new input scale
Definition at line 246 of file ServoOutputScheduleChannel.java.
References com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.inputScale.
Referenced by com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.loadFromFile().
setInterval()
void com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.setInterval (double interval)
Sets the interval.
Parameters
interval the new interval
Definition at line 418 of file ServoOutputScheduleChannel.java.
References com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.interval.
Referenced by com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.setIntervalTime().
setIntervalTime()
void com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.setIntervalTime (int msInterval, int totalTime)
This method is to configure the listeners timing. This passes in the time interval that the scheduler will run at
Parameters
msInterval the total time for the loop
totalTime the total time
Implements com.neuronrobotics.sdk.dyio.sequencer.ISchedulerListener.
Definition at line 160 of file ServoOutputScheduleChannel.java.
References com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.data, com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.getCurrentTargetValue(), com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.getCurrentValue(), com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.getOutputMax(), com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.getOutputMin(), com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.setCurrentTargetValue(), com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.setCurrentValue(), and com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.setInterval().
Referenced by com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.addServoChannel().
setOutput()
void com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.setOutput (ServoChannel output)
Sets the output.
Parameters
output the new output
Definition at line 210 of file ServoOutputScheduleChannel.java.
References com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.output.
setOutputMinMax()
void com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.setOutputMinMax (int outputMin, int outputMax)
Sets the output min max.
Parameters
outputMin the output min
outputMax the output max
Definition at line 265 of file ServoOutputScheduleChannel.java.
References com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.outputMax, and com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.outputMin.
Referenced by com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.loadFromFile().
setRecording()
void com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.setRecording (boolean recording)
Sets the recording.
Parameters
recording the new recording
Definition at line 486 of file ServoOutputScheduleChannel.java.
References com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.recording.
Referenced by com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.pauseRecording(), and com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.resumeRecording().
startRecording()
void com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.startRecording ()
Start recording.
Definition at line 130 of file ServoOutputScheduleChannel.java.
References com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.initInput(), and com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.resumeRecording().
Referenced by com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.loadFromFile().
startTest()
void com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.startTest ()
Start test.
Definition at line 385 of file ServoOutputScheduleChannel.java.
References com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.directTester, com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.getChannelNumber(), and com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.initInput().
stopTest()
void com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.stopTest ()
Stop test.
Definition at line 395 of file ServoOutputScheduleChannel.java.
References com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.directTester, com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.Tester.kill(), and com.neuronrobotics.sdk.dyio.peripherals.AnalogInputChannel.removeAnalogInputListener().
sync()
void com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.sync (int loopTime)
Sync.
Parameters
loopTime the loop time
Definition at line 568 of file ServoOutputScheduleChannel.java.
References com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.getCurrentValue(), com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.getOutput(), and com.neuronrobotics.sdk.dyio.peripherals.ServoChannel.SetPosition().
Member Data Documentation
analogInputChannelNumber
int com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.analogInputChannelNumber =8 private
The analog input channel number.
Definition at line 56 of file ServoOutputScheduleChannel.java.
Referenced by com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.getAnalogInputChannelNumber(), com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.initInput(), and com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.setAnalogInputChannelNumber().
currentValue
int com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.currentValue private
The current value.
Definition at line 38 of file ServoOutputScheduleChannel.java.
Referenced by com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.getCurrentValue(), and com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.setCurrentValue().
data
ArrayList<MapData> com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.data = new ArrayList<MapData>() private
The data.
Definition at line 41 of file ServoOutputScheduleChannel.java.
Referenced by com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.getXml(), com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.onTimeUpdate(), com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.setData(), and com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.setIntervalTime().
directTester
Tester com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.directTester private
The direct tester.
Definition at line 53 of file ServoOutputScheduleChannel.java.
Referenced by com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.isTesting(), com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.startTest(), and com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.stopTest().
index
int com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.index =0 private
The index.
Definition at line 50 of file ServoOutputScheduleChannel.java.
Referenced by com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.onTimeUpdate().
inputCenter
int com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.inputCenter = 128 private
The input center.
Definition at line 26 of file ServoOutputScheduleChannel.java.
Referenced by com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.getInputCenter(), com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.getXml(), and com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.setInputCenter().
inputScale
double com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.inputScale =.25 private
The input scale.
Definition at line 23 of file ServoOutputScheduleChannel.java.
Referenced by com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.getInputScale(), com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.getXml(), and com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.setInputScale().
inputValue
int com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.inputValue private
The input value.
Definition at line 29 of file ServoOutputScheduleChannel.java.
Referenced by com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.getCurrentTargetValue(), and com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.setCurrentTargetValue().
interval
double com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.interval private
The interval.
Definition at line 35 of file ServoOutputScheduleChannel.java.
Referenced by com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.getInterval(), and com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.setInterval().
output
ServoChannel com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.output private
The output.
Definition at line 17 of file ServoOutputScheduleChannel.java.
Referenced by com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.flush(), com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.getChannelNumber(), com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.getOutput(), com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.initInput(), com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.ServoOutputScheduleChannel(), and com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.setOutput().
outputMax
int com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.outputMax =255 private
The output max.
Definition at line 44 of file ServoOutputScheduleChannel.java.
Referenced by com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.getOutputMax(), com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.getXml(), and com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.setOutputMinMax().
outputMin
int com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.outputMin =0 private
The output min.
Definition at line 47 of file ServoOutputScheduleChannel.java.
Referenced by com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.getOutputMin(), com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.getXml(), and com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.setOutputMinMax().
recording
boolean com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.recording =false private
The recording.
Definition at line 32 of file ServoOutputScheduleChannel.java.
Referenced by com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.isRecording(), and com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.setRecording().
The documentation for this class was generated from the following file:
src/main/java/com/neuronrobotics/sdk/dyio/sequencer/ServoOutputScheduleChannel.java