BowlerKernel: com.neuronrobotics.sdk.bootloader.Core Class Reference
com.neuronrobotics.sdk.bootloader.Core Class Reference
Public Member Functions
Core (int core, ArrayList< hexLine > lines, NRBootCoreType type)
Core (int core, String file, NRBootCoreType type)
void setIndex (int index)
int getIndex ()
void setType (NRBootCoreType type)
NRBootCoreType getType ()
void setLines (ArrayList< hexLine > lines)
ArrayList< hexLine > getLines ()
String toString ()
Private Attributes
int index
NRBootCoreType type
ArrayList< hexLine > lines = new ArrayList<hexLine>()
Detailed Description
The Class Core.
Definition at line 13 of file Core.java.
Constructor & Destructor Documentation
Core() [1/2]
com.neuronrobotics.sdk.bootloader.Core.Core (int core, ArrayList< hexLine > lines, NRBootCoreType type)
Instantiates a new core.
Parameters
core the core
lines the lines
type the type
Definition at line 31 of file Core.java.
References com.neuronrobotics.sdk.bootloader.Core.lines, com.neuronrobotics.sdk.bootloader.Core.setIndex(), and com.neuronrobotics.sdk.bootloader.Core.setType().
Core() [2/2]
com.neuronrobotics.sdk.bootloader.Core.Core (int core, String file, NRBootCoreType type)
Instantiates a new core.
Parameters
core the core
file the file
type the type
Definition at line 44 of file Core.java.
References com.neuronrobotics.sdk.bootloader.Core.setIndex(), com.neuronrobotics.sdk.bootloader.Core.setLines(), and com.neuronrobotics.sdk.bootloader.Core.setType().
Member Function Documentation
getIndex()
int com.neuronrobotics.sdk.bootloader.Core.getIndex ()
Gets the index.
Returns
the index
Definition at line 83 of file Core.java.
References com.neuronrobotics.sdk.bootloader.Core.index.
Referenced by com.neuronrobotics.sdk.bootloader.NRBoot.load().
getLines()
ArrayList<hexLine> com.neuronrobotics.sdk.bootloader.Core.getLines ()
Gets the lines.
Returns
the lines
Definition at line 119 of file Core.java.
References com.neuronrobotics.sdk.bootloader.Core.lines.
Referenced by com.neuronrobotics.sdk.bootloader.NRBoot.getParser().
getType()
NRBootCoreType com.neuronrobotics.sdk.bootloader.Core.getType ()
Gets the type.
Returns
the type
Definition at line 101 of file Core.java.
References com.neuronrobotics.sdk.bootloader.Core.type.
Referenced by com.neuronrobotics.sdk.bootloader.NRBoot.getParser(), and com.neuronrobotics.sdk.bootloader.NRBoot.load().
setIndex()
void com.neuronrobotics.sdk.bootloader.Core.setIndex (int index)
Sets the index.
Parameters
index the new index
Definition at line 74 of file Core.java.
References com.neuronrobotics.sdk.bootloader.Core.index.
Referenced by com.neuronrobotics.sdk.bootloader.Core.Core().
setLines()
void com.neuronrobotics.sdk.bootloader.Core.setLines (ArrayList< hexLine > lines)
Sets the lines.
Parameters
lines the new lines
Definition at line 110 of file Core.java.
References com.neuronrobotics.sdk.bootloader.Core.lines.
Referenced by com.neuronrobotics.sdk.bootloader.Core.Core().
setType()
void com.neuronrobotics.sdk.bootloader.Core.setType (NRBootCoreType type)
Sets the type.
Parameters
type the new type
Definition at line 92 of file Core.java.
References com.neuronrobotics.sdk.bootloader.Core.type.
Referenced by com.neuronrobotics.sdk.bootloader.Core.Core().
toString()
String com.neuronrobotics.sdk.bootloader.Core.toString ()
Definition at line 127 of file Core.java.
References com.neuronrobotics.sdk.bootloader.Core.index, and com.neuronrobotics.sdk.bootloader.Core.type.
Member Data Documentation
index
int com.neuronrobotics.sdk.bootloader.Core.index private
The index.
Definition at line 16 of file Core.java.
Referenced by com.neuronrobotics.sdk.bootloader.Core.getIndex(), com.neuronrobotics.sdk.bootloader.Core.setIndex(), and com.neuronrobotics.sdk.bootloader.Core.toString().
lines
ArrayList<hexLine> com.neuronrobotics.sdk.bootloader.Core.lines = new ArrayList<hexLine>() private
The lines.
Definition at line 22 of file Core.java.
Referenced by com.neuronrobotics.sdk.bootloader.Core.Core(), com.neuronrobotics.sdk.bootloader.Core.getLines(), and com.neuronrobotics.sdk.bootloader.Core.setLines().
type
NRBootCoreType com.neuronrobotics.sdk.bootloader.Core.type private
The type.
Definition at line 19 of file Core.java.
Referenced by com.neuronrobotics.sdk.bootloader.Core.getType(), com.neuronrobotics.sdk.bootloader.Core.setType(), and com.neuronrobotics.sdk.bootloader.Core.toString().
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/bootloader/Core.java