BowlerKernel: com.neuronrobotics.sdk.addons.kinematics.math.RotationNRLegacy Class Reference
com.neuronrobotics.sdk.addons.kinematics.math.RotationNRLegacy Class Reference
Public Member Functions
RotationNRLegacy ()
RotationNRLegacy (double tilt, double elevation, double azumeth)
RotationNRLegacy (double[][] rotationMatrix)
RotationNRLegacy (double[] values)
RotationNRLegacy (double w, double x, double y, double z)
RotationNRLegacy (Matrix m)
double[][] getRotationMatrix ()
String toString ()
String toString (double[][] array)
double getRotationTilt ()
double getRotationElevation ()
double getRotationAzimuth ()
double getRotationMatrix2QuaturnionW ()
double getRotationMatrix2QuaturnionX ()
double getRotationMatrix2QuaturnionY ()
double getRotationMatrix2QuaturnionZ ()
Static Public Member Functions
static RotationNRLegacy getRotationX (double rotationAngleDegrees)
static RotationNRLegacy getRotationY (double rotationAngleDegrees)
static RotationNRLegacy getRotationZ (double rotationAngleDegrees)
static boolean bound (double low, double high, double n)
Protected Member Functions
void quaternion2RotationMatrix (double w, double x, double y, double z)
Private Member Functions
void loadFromAngles (double tilt, double azumeth, double elevation)
void loadRotations (double[][] rotM)
double getRotAngle (int index)
Detailed Description
This class is to represent a 3x3 rotation sub-matrix This class also contains static methods for dealing with 3x3 rotations.
Author
Kevin Harrington
Definition at line 16 of file RotationNRLegacy.java.
Constructor & Destructor Documentation
RotationNRLegacy() [1/6]
com.neuronrobotics.sdk.addons.kinematics.math.RotationNRLegacy.RotationNRLegacy ()
Null constructor forms a.
Definition at line 24 of file RotationNRLegacy.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.math.RotationNRLegacy.getRotationX(), com.neuronrobotics.sdk.addons.kinematics.math.RotationNRLegacy.getRotationY(), and com.neuronrobotics.sdk.addons.kinematics.math.RotationNRLegacy.getRotationZ().
RotationNRLegacy() [2/6]
com.neuronrobotics.sdk.addons.kinematics.math.RotationNRLegacy.RotationNRLegacy (double tilt, double elevation, double azumeth)
Instantiates a new rotation nr.
Parameters
elevation the elevation
tilt the tilt
azumeth the azumeth
Definition at line 38 of file RotationNRLegacy.java.
References com.neuronrobotics.sdk.addons.kinematics.math.RotationNRLegacy.getRotationMatrix2QuaturnionW(), com.neuronrobotics.sdk.addons.kinematics.math.RotationNRLegacy.getRotationMatrix2QuaturnionX(), com.neuronrobotics.sdk.addons.kinematics.math.RotationNRLegacy.getRotationMatrix2QuaturnionY(), com.neuronrobotics.sdk.addons.kinematics.math.RotationNRLegacy.getRotationMatrix2QuaturnionZ(), and com.neuronrobotics.sdk.addons.kinematics.math.RotationNRLegacy.loadFromAngles().
RotationNRLegacy() [3/6]
com.neuronrobotics.sdk.addons.kinematics.math.RotationNRLegacy.RotationNRLegacy (double rotationMatrix[][])
Instantiates a new rotation nr.
Parameters
rotationMatrix the rotation matrix
Definition at line 89 of file RotationNRLegacy.java.
References com.neuronrobotics.sdk.addons.kinematics.math.RotationNRLegacy.loadRotations().
RotationNRLegacy() [4/6]
com.neuronrobotics.sdk.addons.kinematics.math.RotationNRLegacy.RotationNRLegacy (double[] values)
Instantiates a new rotation nr.
Parameters
values the values
Definition at line 99 of file RotationNRLegacy.java.
RotationNRLegacy() [5/6]
com.neuronrobotics.sdk.addons.kinematics.math.RotationNRLegacy.RotationNRLegacy (double w, double x, double y, double z)
Instantiates a new rotation nr.
Parameters
w the w
x the x
y the y
z the z
Definition at line 197 of file RotationNRLegacy.java.
References com.neuronrobotics.sdk.addons.kinematics.math.RotationNRLegacy.quaternion2RotationMatrix().
RotationNRLegacy() [6/6]
com.neuronrobotics.sdk.addons.kinematics.math.RotationNRLegacy.RotationNRLegacy (Matrix m)
Instantiates a new rotation nr.
Parameters
m the m
Definition at line 207 of file RotationNRLegacy.java.
References com.neuronrobotics.sdk.addons.kinematics.math.RotationNRLegacy.loadRotations().
Member Function Documentation
bound()
static boolean com.neuronrobotics.sdk.addons.kinematics.math.RotationNRLegacy.bound (double low, double high, double n) static
Bound.
Parameters
low the low
high the high
n the n
Returns
true, if successful
Definition at line 472 of file RotationNRLegacy.java.
getRotAngle()
double com.neuronrobotics.sdk.addons.kinematics.math.RotationNRLegacy.getRotAngle (int index) private
Gets the rot angle.
Parameters
index the index
Returns
the rot angle
Definition at line 483 of file RotationNRLegacy.java.
References com.neuronrobotics.sdk.addons.kinematics.math.RotationNRLegacy.getRotationMatrix2QuaturnionW(), com.neuronrobotics.sdk.addons.kinematics.math.RotationNRLegacy.getRotationMatrix2QuaturnionX(), com.neuronrobotics.sdk.addons.kinematics.math.RotationNRLegacy.getRotationMatrix2QuaturnionY(), com.neuronrobotics.sdk.addons.kinematics.math.RotationNRLegacy.getRotationMatrix2QuaturnionZ(), and com.neuronrobotics.sdk.common.Log.warning().
Referenced by com.neuronrobotics.sdk.addons.kinematics.math.RotationNRLegacy.getRotationAzimuth(), com.neuronrobotics.sdk.addons.kinematics.math.RotationNRLegacy.getRotationElevation(), and com.neuronrobotics.sdk.addons.kinematics.math.RotationNRLegacy.getRotationTilt().
getRotationAzimuth()
double com.neuronrobotics.sdk.addons.kinematics.math.RotationNRLegacy.getRotationAzimuth ()
Gets the rotation azimuth.
Returns
the rotation azimuth
Definition at line 576 of file RotationNRLegacy.java.
References com.neuronrobotics.sdk.addons.kinematics.math.RotationNRLegacy.getRotAngle().
Referenced by com.neuronrobotics.sdk.addons.kinematics.math.RotationNRLegacy.toString().
getRotationElevation()
double com.neuronrobotics.sdk.addons.kinematics.math.RotationNRLegacy.getRotationElevation ()
Gets the rotation elevation.
Returns
the rotation elevation
Definition at line 566 of file RotationNRLegacy.java.
References com.neuronrobotics.sdk.addons.kinematics.math.RotationNRLegacy.getRotAngle().
Referenced by com.neuronrobotics.sdk.addons.kinematics.math.RotationNRLegacy.toString().
getRotationMatrix()
double [][] com.neuronrobotics.sdk.addons.kinematics.math.RotationNRLegacy.getRotationMatrix ()
Gets the rotation matrix.
Returns
the rotation matrix
Definition at line 246 of file RotationNRLegacy.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.math.RotationNRLegacy.toString().
getRotationMatrix2QuaturnionW()
double com.neuronrobotics.sdk.addons.kinematics.math.RotationNRLegacy.getRotationMatrix2QuaturnionW ()
Gets the rotation x.
Returns
the rotation x Gets the rotation y.
the rotation y Gets the rotation z.
the rotation z Gets the rotation matrix2 quaturnion w.
the rotation matrix2 quaturnion w
Definition at line 620 of file RotationNRLegacy.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.math.RotationNRLegacy.getRotAngle(), com.neuronrobotics.sdk.addons.kinematics.math.RotationNRLegacy.RotationNRLegacy(), and com.neuronrobotics.sdk.addons.kinematics.math.RotationNRLegacy.toString().
getRotationMatrix2QuaturnionX()
double com.neuronrobotics.sdk.addons.kinematics.math.RotationNRLegacy.getRotationMatrix2QuaturnionX ()
Gets the rotation matrix2 quaturnion x.
Returns
the rotation matrix2 quaturnion x
Definition at line 632 of file RotationNRLegacy.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.math.RotationNRLegacy.getRotAngle(), com.neuronrobotics.sdk.addons.kinematics.math.RotationNRLegacy.RotationNRLegacy(), and com.neuronrobotics.sdk.addons.kinematics.math.RotationNRLegacy.toString().
getRotationMatrix2QuaturnionY()
double com.neuronrobotics.sdk.addons.kinematics.math.RotationNRLegacy.getRotationMatrix2QuaturnionY ()
Gets the rotation matrix2 quaturnion y.
Returns
the rotation matrix2 quaturnion y
Definition at line 642 of file RotationNRLegacy.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.math.RotationNRLegacy.getRotAngle(), com.neuronrobotics.sdk.addons.kinematics.math.RotationNRLegacy.RotationNRLegacy(), and com.neuronrobotics.sdk.addons.kinematics.math.RotationNRLegacy.toString().
getRotationMatrix2QuaturnionZ()
double com.neuronrobotics.sdk.addons.kinematics.math.RotationNRLegacy.getRotationMatrix2QuaturnionZ ()
Gets the rotation matrix2 quaturnion z.
Returns
the rotation matrix2 quaturnion z
Definition at line 652 of file RotationNRLegacy.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.math.RotationNRLegacy.getRotAngle(), com.neuronrobotics.sdk.addons.kinematics.math.RotationNRLegacy.RotationNRLegacy(), and com.neuronrobotics.sdk.addons.kinematics.math.RotationNRLegacy.toString().
getRotationTilt()
double com.neuronrobotics.sdk.addons.kinematics.math.RotationNRLegacy.getRotationTilt ()
Gets the rotation tilt.
Returns
the rotation tilt
Definition at line 555 of file RotationNRLegacy.java.
References com.neuronrobotics.sdk.addons.kinematics.math.RotationNRLegacy.getRotAngle().
Referenced by com.neuronrobotics.sdk.addons.kinematics.math.RotationNRLegacy.toString().
getRotationX()
static RotationNRLegacy com.neuronrobotics.sdk.addons.kinematics.math.RotationNRLegacy.getRotationX (double rotationAngleDegrees) static
Get a rotation matrix with a rotation around X.
Parameters
rotationAngleDegrees in degrees
Returns
the static matrix
Definition at line 110 of file RotationNRLegacy.java.
References com.neuronrobotics.sdk.addons.kinematics.math.RotationNRLegacy.RotationNRLegacy().
getRotationY()
static RotationNRLegacy com.neuronrobotics.sdk.addons.kinematics.math.RotationNRLegacy.getRotationY (double rotationAngleDegrees) static
Get a rotation matrix with a rotation around Y.
Parameters
rotationAngleDegrees in degrees
Returns
the static matrix
Definition at line 137 of file RotationNRLegacy.java.
References com.neuronrobotics.sdk.addons.kinematics.math.RotationNRLegacy.RotationNRLegacy().
getRotationZ()
static RotationNRLegacy com.neuronrobotics.sdk.addons.kinematics.math.RotationNRLegacy.getRotationZ (double rotationAngleDegrees) static
Get a rotation matrix with a rotation around Z.
Parameters
rotationAngleDegrees in degrees
Returns
the static matrix
Definition at line 164 of file RotationNRLegacy.java.
References com.neuronrobotics.sdk.addons.kinematics.math.RotationNRLegacy.RotationNRLegacy().
loadFromAngles()
void com.neuronrobotics.sdk.addons.kinematics.math.RotationNRLegacy.loadFromAngles (double tilt, double azumeth, double elevation) private
Definition at line 57 of file RotationNRLegacy.java.
References com.neuronrobotics.sdk.addons.kinematics.math.RotationNRLegacy.quaternion2RotationMatrix().
Referenced by com.neuronrobotics.sdk.addons.kinematics.math.RotationNRLegacy.RotationNRLegacy().
loadRotations()
void com.neuronrobotics.sdk.addons.kinematics.math.RotationNRLegacy.loadRotations (double rotM[][]) private
Load rotations.
Parameters
rotM the rot m
Definition at line 223 of file RotationNRLegacy.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.math.RotationNRLegacy.RotationNRLegacy().
quaternion2RotationMatrix()
void com.neuronrobotics.sdk.addons.kinematics.math.RotationNRLegacy.quaternion2RotationMatrix (double w, double x, double y, double z) protected
Quaternion2 rotation matrix.
Parameters
w the w
x the x
y the y
z the z
Definition at line 312 of file RotationNRLegacy.java.
References com.neuronrobotics.sdk.addons.kinematics.math.RotationNRLegacy.toString().
Referenced by com.neuronrobotics.sdk.addons.kinematics.math.RotationNRLegacy.loadFromAngles(), and com.neuronrobotics.sdk.addons.kinematics.math.RotationNRLegacy.RotationNRLegacy().
toString() [1/2]
String com.neuronrobotics.sdk.addons.kinematics.math.RotationNRLegacy.toString ()
Definition at line 262 of file RotationNRLegacy.java.
References com.neuronrobotics.sdk.addons.kinematics.math.RotationNRLegacy.getRotationAzimuth(), com.neuronrobotics.sdk.addons.kinematics.math.RotationNRLegacy.getRotationElevation(), com.neuronrobotics.sdk.addons.kinematics.math.RotationNRLegacy.getRotationMatrix(), com.neuronrobotics.sdk.addons.kinematics.math.RotationNRLegacy.getRotationMatrix2QuaturnionW(), com.neuronrobotics.sdk.addons.kinematics.math.RotationNRLegacy.getRotationMatrix2QuaturnionX(), com.neuronrobotics.sdk.addons.kinematics.math.RotationNRLegacy.getRotationMatrix2QuaturnionY(), com.neuronrobotics.sdk.addons.kinematics.math.RotationNRLegacy.getRotationMatrix2QuaturnionZ(), and com.neuronrobotics.sdk.addons.kinematics.math.RotationNRLegacy.getRotationTilt().
Referenced by com.neuronrobotics.sdk.addons.kinematics.math.RotationNRLegacy.quaternion2RotationMatrix().
toString() [2/2]
String com.neuronrobotics.sdk.addons.kinematics.math.RotationNRLegacy.toString (double array[][])
To string.
Parameters
array the array
Returns
the string
Definition at line 287 of file RotationNRLegacy.java.
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/addons/kinematics/math/RotationNRLegacy.java