BowlerKernel: com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine Class Reference
com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine Class Reference
Static Public Member Functions
static void setWorkspace (File file)
static void addLogListener (GitLogProgressMonitor l)
static void removeLogListener (GitLogProgressMonitor l)
static void clearLogListener ()
static Git openGit (String url)
static boolean isUrlAlreadyOpen (String URL)
static Git openGit (Repository localRepo)
static void closeGit (Git git)
static void addOnCommitEventListeners (String url, Runnable event)
static void removeOnCommitEventListeners (String url, Runnable event)
static Object inlineScriptRun (File code, ArrayList< Object > args, String shellTypeStorage) throws Exception
static Object inlineScriptStringRun (String line, ArrayList< Object > args, String shellTypeStorage) throws Exception
static void addScriptingLanguage (IScriptingLanguage lang)
static void addIGithubLoginListener (IGithubLoginListener l)
static void removeIGithubLoginListener (IGithubLoginListener l)
static File getWorkspace ()
static String getShellType (String name)
static void login () throws IOException
static void logout () throws IOException
static GitHub setupAnyonmous () throws IOException
static String urlToGist (String in)
static List< String > getCurrentGist (String addr, Object engine)
static void waitForLogin () throws IOException, InvalidRemoteException, TransportException, GitAPIException
static void waitForRepo (String remoteURI, String reason)
static void deleteRepo (String remoteURI)
static void deleteCache ()
static ArrayList< String > filesInGit (String remote, String branch, String extnetion) throws Exception
static ArrayList< String > filesInGit (String remote, String branch, String extnetion, Git ref) throws Exception
static ArrayList< String > filesInGit (String remote) throws Exception
static ArrayList< String > filesInGit (String remote, Git ref) throws Exception
static String getUserIdOfGist (String id) throws Exception
static File createFile (String git, String fileName, String commitMessage) throws Exception
static void pushCodeToGit (String id, String branch, String FileName, String content, String commitMessage) throws Exception
static void commit (String id, String branch, String FileName, String content, String commitMessage, boolean flagNewFile) throws Exception
static void commit (String id, String branch, String FileName, String content, String commitMessage, boolean flagNewFile, Git gitRef) throws Exception
static void pushCodeToGit (String remoteURI, String branch, String FileName, String content, String commitMessage, boolean flagNewFile) throws Exception
static String[] codeFromGit (String id, String FileName) throws Exception
static Object inlineFileScriptRun (File f, ArrayList< Object > args) throws Exception
static Object inlineGistScriptRun (String gistID, String Filename, ArrayList< Object > args) throws Exception
static Object gitScriptRun (String gitURL, String Filename) throws Exception
static Object gitScriptRun (String gitURL, String Filename, ArrayList< Object > args) throws Exception
static File fileFromGit (String remoteURI, String fileInRepo) throws InvalidRemoteException, TransportException, GitAPIException, IOException
static File fileFromGit (String remoteURI, String branch, String fileInRepo) throws InvalidRemoteException, TransportException, GitAPIException, IOException
static File uriToFile (String remoteURI)
static String getBranch (String remoteURI) throws IOException, RefAlreadyExistsException, RefNotFoundException, InvalidRefNameException, CheckoutConflictException, InvalidRemoteException, TransportException, GitAPIException
static String getFullBranch (String remoteURI) throws IOException, RefAlreadyExistsException, RefNotFoundException, InvalidRefNameException, CheckoutConflictException, InvalidRemoteException, TransportException, GitAPIException
static void deleteBranch (String remoteURI, String toDelete) throws Exception
static String newBranch (String remoteURI, String newBranch) throws IOException, RefAlreadyExistsException, RefNotFoundException, InvalidRefNameException, CheckoutConflictException, InvalidRemoteException, TransportException, GitAPIException
static void newBranch (String remoteURI, String newBranch, RevCommit source) throws IOException, RefAlreadyExistsException, RefNotFoundException, InvalidRefNameException, CheckoutConflictException, InvalidRemoteException, TransportException, GitAPIException
static List< Ref > listBranches (String remoteURI) throws Exception
static List< Ref > listBranches (String remoteURI, Git git) throws Exception
static List< Ref > listLocalBranches (String remoteURI) throws IOException
static List< String > listLocalBranchNames (String remoteURI) throws Exception
static List< String > listBranchNames (String remoteURI) throws Exception
static void pull (String remoteURI, String branch) throws IOException, CheckoutConflictException, NoHeadException, InvalidRemoteException, WrongRepositoryStateException
static void pull (String remoteURI) throws IOException, RefAlreadyExistsException, RefNotFoundException, InvalidRefNameException, InvalidRemoteException, TransportException, GitAPIException
static void checkoutCommit (String remoteURI, String branch, String commitHash) throws IOException
static void checkout (String remoteURI, RevCommit commit) throws IOException, RefAlreadyExistsException, RefNotFoundException, InvalidRefNameException, CheckoutConflictException, InvalidRemoteException, TransportException, GitAPIException
static void checkout (String remoteURI, Ref branch) throws IOException, RefAlreadyExistsException, RefNotFoundException, InvalidRefNameException, CheckoutConflictException, InvalidRemoteException, TransportException, GitAPIException
static void checkout (String remoteURI, String branch) throws IOException, RefAlreadyExistsException, RefNotFoundException, InvalidRefNameException, CheckoutConflictException, InvalidRemoteException, TransportException, GitAPIException
static File cloneRepo (String remoteURI, String branch)
static String locateGitUrl (File f) throws IOException
static String locateGitUrl (File f, Git ref) throws IOException
static Git locateGit (File f) throws IOException
static String getText (URL website) throws Exception
static File getLastFile ()
static void setLastFile (File lastFile)
static File getFileEngineRunByName (String filename)
static String[] getImports ()
static IGitHubLoginManager getLoginManager ()
static void setLoginManager (IGitHubLoginManager lm)
static boolean isAutoupdate ()
static boolean setAutoupdate (boolean autoupdate) throws IOException
static String findLocalPath (File currentFile, Git git)
static String findLocalPath (File currentFile)
static String[] findGitTagFromFile (File currentFile) throws IOException
static String[] findGitTagFromFile (File currentFile, Git ref) throws IOException
static boolean checkOwner (String url)
static boolean checkOwner (File currentFile)
static GHGist forkGist (String currentGist) throws Exception
static String fork (String sourceURL, String newRepoName, String newRepoDescription) throws Exception
static GHRepository makeNewRepoNoFailOver (String newName, String description) throws IOException, org.kohsuke.github.HttpException
static GHRepository makeNewRepo (String newName, String description) throws IOException
static String locateGitUrlString (File f)
static String urlToString (URL htmlUrl)
static String urlToGist (URL htmlUrl)
static List< String > getAllLangauges ()
static HashMap< String, IScriptingLanguage > getLangaugesMap ()
static IScriptingLanguage getLangaugeByExtention (String extention)
static boolean hasNetwork ()
static boolean isLoginSuccess ()
static String[] copyGitFile (String sourceGit, String targetGit, String filename)
static String[] copyGitFile (String sourceGit, String targetGit, String filename, String outFile, boolean bailIfExisting)
static Ref getBranch (String remoteURI, String branch) throws IOException, GitAPIException
static Collection< Ref > getAllBranches (String remoteURI) throws IOException, GitAPIException
static Repository getRepository (String remoteURI) throws IOException
static File getRepositoryCloneDirectory (String remoteURI)
static void setCommitContentsAsCurrent (String url, String branch, RevCommit commit) throws IOException, GitAPIException
static File getAppData ()
static int versionCompare (String v1, String v2)
static List< String > getAllTags (String gitRepo)
static boolean tagExists (String remoteURI, String newTag)
static void tagRepo (String remoteURI, String newTag)
Static Private Member Functions
static Git cloneRepoLocalSelectAuth (String remoteURI, File dir, boolean useSSH) throws InvalidRemoteException, TransportException, GitAPIException
static Git cloneRepoLocal (String remoteURI, File dir) throws InvalidRemoteException, TransportException, GitAPIException
static ProgressMonitor getProgressMoniter (String type, String remoteURI)
static GitTimeoutThread makeTimeoutThread (Git git)
static List< String > returnFirstGist (String html)
static void deleteFolder (File folder)
static void loadFilesToList (ArrayList< String > f, File directory, String extnetion)
static void loadFilesToList (ArrayList< String > f, File directory, String extnetion, Git ref)
static boolean ensureExistance (File desired) throws IOException
static String[] codeFromGistID (String id, String FileName) throws Exception
static void newBranchLocal (String newBranch, String remoteURI, Git git, RevCommit source) throws GitAPIException, RefNotFoundException, InvalidRefNameException, CheckoutConflictException, InvalidRemoteException, TransportException, IOException
static boolean hasAtLeastOneReference (Git git) throws Exception
static void shallowCheckout (String remoteURI, String branch, Git git) throws GitAPIException, RefAlreadyExistsException, InvalidRefNameException, RefNotFoundException, CheckoutConflictException
static boolean resolveConflict (String remoteURI, CheckoutConflictException con, Git git)
static File fileFromGistID (String string, String string2) throws InvalidRemoteException, TransportException, GitAPIException, IOException
static boolean checkOwner (Git git)
static void commit (String url, String branch, String message) throws IOException, GitAPIException, NoHeadException, NoMessageException, UnmergedPathsException, ConcurrentRefUpdateException, WrongRepositoryStateException, AbortedByHookException
static void commit (String url, String branch, String message, Git passedRef) throws IOException, GitAPIException, NoHeadException, NoMessageException, UnmergedPathsException, ConcurrentRefUpdateException, WrongRepositoryStateException, AbortedByHookException
Static Private Attributes
static final int TIME_TO_WAIT_BETWEEN_GIT_PULL = 100000
static final ArrayList< GitLogProgressMonitor > logListeners = new ArrayList<>()
static boolean autoupdate = false
static final String[] imports
static HashMap< String, File > filesRun = new HashMap<>()
static File workspace
static File appdata
static File lastFile
static TransportConfigCallback transportConfigCallback = new SshTransportConfigCallback()
static ArrayList< IGithubLoginListener > loginListeners = new ArrayList<IGithubLoginListener>()
static HashMap< String, IScriptingLanguage > langauges = new HashMap<>()
static HashMap< String, ArrayList< Runnable > > onCommitEventListeners = new HashMap<>()
Detailed Description
Definition at line 86 of file ScriptingEngine.java.
Member Function Documentation
addIGithubLoginListener()
static void com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.addIGithubLoginListener (IGithubLoginListener l) static
Definition at line 474 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.loginListeners.
addLogListener()
static void com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.addLogListener (GitLogProgressMonitor l) static
Definition at line 168 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.logListeners.
addOnCommitEventListeners()
static void com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.addOnCommitEventListeners (String url, Runnable event) static
Definition at line 412 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.onCommitEventListeners.
addScriptingLanguage()
static void com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.addScriptingLanguage (IScriptingLanguage lang) static
Definition at line 470 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.scripting.IScriptingLanguage.getShellType(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.langauges.
checkout() [1/3]
static void com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.checkout (String remoteURI, Ref branch) throws IOException, RefAlreadyExistsException, RefNotFoundException, InvalidRefNameException, CheckoutConflictException, InvalidRemoteException, TransportException, GitAPIException static
Definition at line 1477 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.checkout().
checkout() [2/3]
static void com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.checkout (String remoteURI, RevCommit commit) throws IOException, RefAlreadyExistsException, RefNotFoundException, InvalidRefNameException, CheckoutConflictException, InvalidRemoteException, TransportException, GitAPIException static
Definition at line 1471 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.checkout(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.commit().
Referenced by com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.checkout(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.cloneRepo(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.setCommitContentsAsCurrent().
checkout() [3/3]
static void com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.checkout (String remoteURI, String branch) throws IOException, RefAlreadyExistsException, RefNotFoundException, InvalidRefNameException, CheckoutConflictException, InvalidRemoteException, TransportException, GitAPIException static
Definition at line 1485 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.scripting.PasswordManager.checkInternet(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.closeGit(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getAllBranches(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getFullBranch(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.hasNetwork(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.newBranch(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.openGit(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.resolveConflict(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.shallowCheckout(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.uriToFile().
checkoutCommit()
static void com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.checkoutCommit (String remoteURI, String branch, String commitHash) throws IOException static
Definition at line 1450 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.closeGit(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.openGit(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.uriToFile(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.waitForRepo().
checkOwner() [1/3]
static boolean com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.checkOwner (File currentFile) static
Definition at line 1853 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.checkOwner(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.closeGit(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.locateGit().
checkOwner() [2/3]
static boolean com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.checkOwner (Git git) static private
Definition at line 1875 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.scripting.PasswordManager.getCredentialProvider(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.transportConfigCallback, and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.waitForLogin().
checkOwner() [3/3]
static boolean com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.checkOwner (String url) static
Definition at line 1840 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.closeGit(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getRepository(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.openGit().
Referenced by com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.checkOwner().
clearLogListener()
static void com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.clearLogListener () static
Definition at line 180 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.logListeners.
cloneRepo()
static File com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.cloneRepo (String remoteURI, String branch) static
This function retrieves the local cached version of a given git repository. If it does not exist, it clones it.
Returns
The local directory containing the .git
Definition at line 1635 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.scripting.PasswordManager.checkInternet(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.checkout(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.cloneRepoLocal(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.closeGit(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getFullBranch(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getRepositoryCloneDirectory(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.hasAtLeastOneReference(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.hasNetwork(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.waitForRepo().
Referenced by com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.commit(), com.neuronrobotics.bowlerstudio.CoquiDockerManager.CoquiDockerManager(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.deleteBranch(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.fileFromGit(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.filesInGit(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getAllBranches(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getBranch(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getFullBranch(), com.neuronrobotics.bowlerstudio.vitamins.Vitamins.getGitRepoDatabase(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.listBranches(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.listLocalBranches(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.makeNewRepo(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.pull(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.pushCodeToGit().
cloneRepoLocal()
static Git com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.cloneRepoLocal (String remoteURI, File dir) throws InvalidRemoteException, TransportException, GitAPIException static private
CLoe git and start a timeout timer
Parameters
remoteURI
branch
dir
Returns
Exceptions
InvalidRemoteException
TransportException
GitAPIException
Definition at line 214 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.cloneRepoLocalSelectAuth(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.deleteRepo().
Referenced by com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.cloneRepo().
cloneRepoLocalSelectAuth()
static Git com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.cloneRepoLocalSelectAuth (String remoteURI, File dir, boolean useSSH) throws InvalidRemoteException, TransportException, GitAPIException static private
Definition at line 185 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.scripting.PasswordManager.getCredentialProvider(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getProgressMoniter(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.makeTimeoutThread(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.transportConfigCallback.
Referenced by com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.cloneRepoLocal().
closeGit()
static void com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.closeGit (Git git) static
Close GIt and disable the timeout timer for this object
Parameters
git
Definition at line 383 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.IssueReportingExceptionHandler.uncaughtException().
Referenced by com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.checkout(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.checkoutCommit(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.checkOwner(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.cloneRepo(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.commit(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.deleteBranch(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.findGitTagFromFile(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.findLocalPath(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.fork(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getAllBranches(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getAllTags(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.listBranches(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.listLocalBranches(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.locateGitUrl(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.locateGitUrlString(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.newBranch(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.pull(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.pushCodeToGit(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.tagRepo().
codeFromGistID()
static String [] com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.codeFromGistID (String id, String FileName) throws Exception static private
Definition at line 982 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.fileFromGit().
Referenced by com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.inlineGistScriptRun().
codeFromGit()
static String [] com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.codeFromGit (String id, String FileName) throws Exception static
Definition at line 967 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.fileFromGit().
Referenced by com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.copyGitFile(), com.neuronrobotics.bowlerstudio.creature.MobileBaseLoader.fromGit(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.gitScriptRun(), and com.neuronrobotics.bowlerstudio.vitamins.VitaminBomManager.saveLocal().
commit() [1/4]
static void com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.commit (String id, String branch, String FileName, String content, String commitMessage, boolean flagNewFile) throws Exception static
Definition at line 818 of file ScriptingEngine.java.
Referenced by com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.checkout(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.commit(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.makeNewRepo(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.pushCodeToGit(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.resolveConflict(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.setCommitContentsAsCurrent().
commit() [2/4]
static void com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.commit (String id, String branch, String FileName, String content, String commitMessage, boolean flagNewFile, Git gitRef) throws Exception static
Definition at line 824 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.cloneRepo(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.closeGit(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.commit(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.fileFromGit(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.filesInGit(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.findGitTagFromFile(), eu.mihosoft.vrl.v3d.parametrics.CSGDatabase.getDbFile(), com.neuronrobotics.bowlerstudio.scripting.PasswordManager.getUsername(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.hasNetwork(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.login(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.openGit(), eu.mihosoft.vrl.v3d.parametrics.CSGDatabase.saveDatabase(), eu.mihosoft.vrl.v3d.parametrics.CSGDatabase.setDbFile(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.waitForRepo().
commit() [3/4]
static void com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.commit (String url, String branch, String message) throws IOException, GitAPIException, NoHeadException, NoMessageException, UnmergedPathsException, ConcurrentRefUpdateException, WrongRepositoryStateException, AbortedByHookException static private
Definition at line 2209 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.commit().
commit() [4/4]
static void com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.commit (String url, String branch, String message, Git passedRef) throws IOException, GitAPIException, NoHeadException, NoMessageException, UnmergedPathsException, ConcurrentRefUpdateException, WrongRepositoryStateException, AbortedByHookException static private
Definition at line 2215 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.closeGit(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getRepository(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.onCommitEventListeners, and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.openGit().
copyGitFile() [1/2]
static String [] com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.copyGitFile (String sourceGit, String targetGit, String filename) static
Definition at line 2080 of file ScriptingEngine.java.
Referenced by com.neuronrobotics.bowlerstudio.scripting.RobotHelper.getDefaultContents().
copyGitFile() [2/2]
static String [] com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.copyGitFile (String sourceGit, String targetGit, String filename, String outFile, boolean bailIfExisting) static
Definition at line 2084 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.codeFromGit(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.createFile(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.fileFromGit(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getFullBranch(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.pushCodeToGit(), and com.neuronrobotics.sdk.util.ThreadUtil.wait().
createFile()
static File com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.createFile (String git, String fileName, String commitMessage) throws Exception static
Definition at line 785 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.fileFromGit(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getFullBranch(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.pushCodeToGit().
Referenced by com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.copyGitFile(), and com.neuronrobotics.bowlerstudio.assets.AssetFactory.loadAsset().
deleteBranch()
static void com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.deleteBranch (String remoteURI, String toDelete) throws Exception static
Definition at line 1079 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.cloneRepo(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.closeGit(), com.neuronrobotics.bowlerstudio.scripting.PasswordManager.getCredentialProvider(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getProgressMoniter(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.listBranchNames(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.openGit(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.uriToFile(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.waitForRepo().
deleteCache()
static void com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.deleteCache () static
Definition at line 678 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.deleteFolder(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getWorkspace().
deleteFolder()
static void com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.deleteFolder (File folder) static private
Definition at line 682 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.util.FileChangeWatcher.close(), and com.neuronrobotics.bowlerstudio.util.FileChangeWatcher.notifyOfDelete().
Referenced by com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.deleteCache(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.deleteRepo().
deleteRepo()
static void com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.deleteRepo (String remoteURI) static
Definition at line 666 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.deleteFolder(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.uriToFile(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.waitForRepo().
Referenced by com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.cloneRepoLocal(), com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.getDatabase(), com.neuronrobotics.bowlerstudio.vitamins.Vitamins.reLoadDatabaseFromFiles(), com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.save(), and com.neuronrobotics.bowlerstudio.creature.MobileBaseLoader.setGitWalkingEngine().
ensureExistance()
static boolean com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.ensureExistance (File desired) throws IOException static private
Definition at line 803 of file ScriptingEngine.java.
Referenced by com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.pushCodeToGit().
fileFromGistID()
static File com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.fileFromGistID (String string, String string2) throws InvalidRemoteException, TransportException, GitAPIException, IOException static private
Definition at line 1789 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.fileFromGit().
fileFromGit() [1/2]
static File com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.fileFromGit (String remoteURI, String branch, String fileInRepo) throws InvalidRemoteException, TransportException, GitAPIException, IOException static
Definition at line 1024 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.cloneRepo().
fileFromGit() [2/2]
static File com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.fileFromGit (String remoteURI, String fileInRepo) throws InvalidRemoteException, TransportException, GitAPIException, IOException static
Definition at line 1016 of file ScriptingEngine.java.
Referenced by com.neuronrobotics.bowlerstudio.sequence.TimeSequence.addWavFileRun(), com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.BezierEditor(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.closeScriptFromFileInfo(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.codeFromGistID(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.codeFromGit(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.commit(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.copyGitFile(), com.neuronrobotics.bowlerstudio.CoquiDockerManager.CoquiDockerManager(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.createFile(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.fileFromGistID(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.fork(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getCadScriptFromLimnb(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getCadScriptFromMobileBase(), com.neuronrobotics.bowlerstudio.vitamins.Purchasing.getDatabase(), com.neuronrobotics.bowlerstudio.vitamins.Vitamins.getScriptFile(), com.neuronrobotics.bowlerstudio.vitamins.Vitamins.getVitaminFile(), com.neuronrobotics.bowlerstudio.vitamins.Purchasing.listVitaminTypes(), com.neuronrobotics.bowlerstudio.lipsync.VoskLipSync.loadDictionary(), com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.loadFile(), com.neuronrobotics.bowlerstudio.assets.AssetFactory.loadFile(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.resolveConflict(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.scriptFromFileInfo(), com.neuronrobotics.bowlerstudio.creature.MobileBaseLoader.setDefaultDhParameterKinematics(), com.neuronrobotics.bowlerstudio.creature.MobileBaseLoader.setGitWalkingEngine(), com.neuronrobotics.bowlerstudio.printbed.PrintBedManager.write(), and com.neuronrobotics.bowlerstudio.vitamins.VitaminBomManager.write().
filesInGit() [1/4]
static ArrayList<String> com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.filesInGit (String remote) throws Exception static
Definition at line 766 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.filesInGit().
filesInGit() [2/4]
static ArrayList<String> com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.filesInGit (String remote, Git ref) throws Exception static
Definition at line 770 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.filesInGit().
filesInGit() [3/4]
static ArrayList<String> com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.filesInGit (String remote, String branch, String extnetion) throws Exception static
Definition at line 750 of file ScriptingEngine.java.
Referenced by com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.commit(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.filesInGit(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.fork(), com.neuronrobotics.bowlerstudio.assets.AssetFactory.loadAllAssets(), and com.neuronrobotics.bowlerstudio.BowlerKernel.main().
filesInGit() [4/4]
static ArrayList<String> com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.filesInGit (String remote, String branch, String extnetion, Git ref) throws Exception static
Definition at line 754 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.cloneRepo(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.loadFilesToList().
findGitTagFromFile() [1/2]
static String [] com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.findGitTagFromFile (File currentFile) throws IOException static
Definition at line 1818 of file ScriptingEngine.java.
Referenced by com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.commit(), com.neuronrobotics.bowlerstudio.scripting.RobotHelper.inlineScriptRun(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.pushCodeToGit().
findGitTagFromFile() [2/2]
static String [] com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.findGitTagFromFile (File currentFile, Git ref) throws IOException static
Definition at line 1822 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.closeGit(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.findLocalPath(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.locateGit(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.locateGitUrl().
findLocalPath() [1/2]
static String com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.findLocalPath (File currentFile) static
Definition at line 1803 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.closeGit(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.findLocalPath(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.locateGit().
findLocalPath() [2/2]
static String com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.findLocalPath (File currentFile, Git git) static
Definition at line 1794 of file ScriptingEngine.java.
Referenced by com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.findGitTagFromFile(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.findLocalPath(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.loadFilesToList().
fork()
static String com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.fork (String sourceURL, String newRepoName, String newRepoDescription) throws Exception static
Fork a git repo
Parameters
sourceURL the URL of the source repo
Returns
the URL of the target repo
Exceptions
Exception
Definition at line 1925 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.closeGit(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.fileFromGit(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.filesInGit(), com.neuronrobotics.bowlerstudio.scripting.PasswordManager.getCredentialProvider(), com.neuronrobotics.bowlerstudio.scripting.PasswordManager.getGithub(), com.neuronrobotics.bowlerstudio.scripting.PasswordManager.getLoginID(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getProgressMoniter(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.locateGit(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.makeNewRepoNoFailOver(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.transportConfigCallback.
forkGist()
static GHGist com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.forkGist (String currentGist) throws Exception static
Definition at line 1901 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.scripting.PasswordManager.getGithub(), com.neuronrobotics.bowlerstudio.scripting.PasswordManager.getUsername(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.loginListeners, and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.waitForLogin().
getAllBranches()
static Collection<Ref> com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getAllBranches (String remoteURI) throws IOException, GitAPIException static
Definition at line 2152 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.cloneRepo(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.closeGit(), com.neuronrobotics.bowlerstudio.scripting.PasswordManager.getCredentialProvider(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getRepository(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.openGit(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.transportConfigCallback.
Referenced by com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.checkout(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getBranch(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.setCommitContentsAsCurrent().
getAllLangauges()
static List<String> com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getAllLangauges () static
Definition at line 2050 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getLangaugesMap().
getAllTags()
static List<String> com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getAllTags (String gitRepo) static
Definition at line 2284 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.closeGit(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.openGit(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.versionCompare().
Referenced by com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.tagExists().
getAppData()
static File com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getAppData () static
Definition at line 2243 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.appdata.
getBranch() [1/2]
static String com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getBranch (String remoteURI) throws IOException, RefAlreadyExistsException, RefNotFoundException, InvalidRefNameException, CheckoutConflictException, InvalidRemoteException, TransportException, GitAPIException static
Definition at line 1044 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.cloneRepo(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.uriToFile().
Referenced by com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.pull(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.pushCodeToGit(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.resolveConflict().
getBranch() [2/2]
static Ref com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getBranch (String remoteURI, String branch) throws IOException, GitAPIException static
Definition at line 2140 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.cloneRepo(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getAllBranches().
getCurrentGist()
static List<String> com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getCurrentGist (String addr, Object engine) static
Definition at line 586 of file ScriptingEngine.java.
References com.neuronrobotics.sdk.common.Log.debug(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.returnFirstGist(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.urlToGist().
getFileEngineRunByName()
static File com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getFileEngineRunByName (String filename) static
Definition at line 1759 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.filesRun.
getFullBranch()
static String com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getFullBranch (String remoteURI) throws IOException, RefAlreadyExistsException, RefNotFoundException, InvalidRefNameException, CheckoutConflictException, InvalidRemoteException, TransportException, GitAPIException static
Definition at line 1061 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.cloneRepo(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.uriToFile().
Referenced by com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.checkout(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.cloneRepo(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.copyGitFile(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.createFile(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.newBranch(), com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.save(), com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.save(), com.neuronrobotics.bowlerstudio.vitamins.Purchasing.saveDatabase(), and com.neuronrobotics.bowlerstudio.vitamins.Vitamins.saveDatabase().
getImports()
static String [] com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getImports () static
Definition at line 1763 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.imports.
Referenced by com.neuronrobotics.bowlerstudio.scripting.GroovyHelper.inline().
getLangaugeByExtention()
static IScriptingLanguage com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getLangaugeByExtention (String extention) static
Definition at line 2062 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getLangaugesMap(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.langauges.
getLangaugesMap()
static HashMap<String, IScriptingLanguage> com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getLangaugesMap () static
Definition at line 2058 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.langauges.
Referenced by com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getAllLangauges(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getLangaugeByExtention().
getLastFile()
static File com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getLastFile () static
Definition at line 1749 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getWorkspace(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.lastFile.
getLoginManager()
static IGitHubLoginManager com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getLoginManager () static
Definition at line 1767 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.scripting.PasswordManager.getLoginManager().
getProgressMoniter()
static ProgressMonitor com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getProgressMoniter (String type, String remoteURI) static private
Definition at line 234 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getRepositoryCloneDirectory(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.logListeners, and com.neuronrobotics.bowlerstudio.scripting.GitTimeoutThread.resetTimer().
Referenced by com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.cloneRepoLocalSelectAuth(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.deleteBranch(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.fork(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.newBranchLocal(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.pull(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.pushCodeToGit(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.tagRepo().
getRepository()
static Repository com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getRepository (String remoteURI) throws IOException static
Definition at line 2168 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getRepositoryCloneDirectory().
Referenced by com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.checkOwner(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.commit(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getAllBranches(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.newBranch(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.openGit().
getRepositoryCloneDirectory()
static File com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getRepositoryCloneDirectory (String remoteURI) static
Definition at line 2177 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getWorkspace().
Referenced by com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.cloneRepo(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.generateStls(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getProgressMoniter(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getRepository(), com.neuronrobotics.bowlerstudio.vitamins.Vitamins.listVitaminTypes(), com.neuronrobotics.bowlerstudio.BowlerKernel.main(), com.neuronrobotics.bowlerstudio.printbed.PrintBedManager.PrintBedManager(), com.neuronrobotics.bowlerstudio.BowlerKernel.processReturnedObjects(), and com.neuronrobotics.bowlerstudio.vitamins.VitaminBomManager.VitaminBomManager().
getShellType()
static String com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getShellType (String name) static
Definition at line 507 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.langauges.
Referenced by com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.gitScriptRun(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.inlineFileScriptRun(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.inlineGistScriptRun().
getText()
static String com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getText (URL website) throws Exception static
Definition at line 1733 of file ScriptingEngine.java.
getUserIdOfGist()
static String com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getUserIdOfGist (String id) throws Exception static
Definition at line 774 of file ScriptingEngine.java.
References com.neuronrobotics.sdk.common.Log.debug(), com.neuronrobotics.bowlerstudio.scripting.PasswordManager.getGithub(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.waitForLogin().
getWorkspace()
static File com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getWorkspace () static
Definition at line 486 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.setWorkspace(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.workspace.
Referenced by com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.deleteCache(), com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.get(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getLastFile(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getRepositoryCloneDirectory(), com.neuronrobotics.bowlerstudio.lipsync.RhubarbManager.processRaw(), com.neuronrobotics.bowlerstudio.lipsync.VoskLipSync.processRaw(), com.neuronrobotics.bowlerstudio.lipsync.VoskLipSync.promptFromMicrophone(), com.neuronrobotics.bowlerstudio.lipsync.VoskLipSync.setModelName(), com.neuronrobotics.bowlerstudio.lipsync.RhubarbManager.startProcessing(), com.neuronrobotics.bowlerstudio.lipsync.VoskLipSync.startProcessing(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.uriToFile().
gitScriptRun() [1/2]
static Object com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.gitScriptRun (String gitURL, String Filename) throws Exception static
Definition at line 1007 of file ScriptingEngine.java.
Referenced by com.neuronrobotics.bowlerstudio.vitamins.Vitamins.get(), com.neuronrobotics.bowlerstudio.BowlerKernel.main(), and com.neuronrobotics.bowlerstudio.sequence.TimeSequence.runSequence().
gitScriptRun() [2/2]
static Object com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.gitScriptRun (String gitURL, String Filename, ArrayList< Object > args) throws Exception static
Definition at line 1011 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.codeFromGit(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getShellType(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.inlineScriptRun().
hasAtLeastOneReference()
static boolean com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.hasAtLeastOneReference (Git git) throws Exception static private
Definition at line 1205 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.listBranches().
Referenced by com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.cloneRepo().
hasNetwork()
static boolean com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.hasNetwork () static
Definition at line 2071 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.scripting.PasswordManager.hasNetwork().
Referenced by com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.checkout(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.cloneRepo(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.commit(), com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.getGitSource(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.pull(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.pushCodeToGit().
inlineFileScriptRun()
static Object com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.inlineFileScriptRun (File f, ArrayList< Object > args) throws Exception static
Definition at line 997 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getShellType(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.inlineScriptRun().
Referenced by com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.getDatabase(), com.neuronrobotics.bowlerstudio.BowlerKernel.main(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.scriptFromFileInfo(), com.neuronrobotics.bowlerstudio.creature.MobileBaseLoader.setDefaultDhParameterKinematics(), and com.neuronrobotics.bowlerstudio.creature.MobileBaseLoader.setGitWalkingEngine().
inlineGistScriptRun()
static Object com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.inlineGistScriptRun (String gistID, String Filename, ArrayList< Object > args) throws Exception static
Definition at line 1002 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.codeFromGistID(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getShellType(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.inlineScriptRun().
inlineScriptRun()
static Object com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.inlineScriptRun (File code, ArrayList< Object > args, String shellTypeStorage) throws Exception static
This interface is for adding additional language support.
Parameters
code file content of the code to be executed
args the incoming arguments as a list of objects
Returns
the objects returned form the code that ran
Definition at line 442 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.filesRun, and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.langauges.
Referenced by com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.gitScriptRun(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.inlineFileScriptRun(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.inlineGistScriptRun().
inlineScriptStringRun()
static Object com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.inlineScriptStringRun (String line, ArrayList< Object > args, String shellTypeStorage) throws Exception static
This interface is for adding additional language support.
Parameters
line the text content of the code to be executed
args the incoming arguments as a list of objects
Returns
the objects returned form the code that ran
Definition at line 461 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.langauges.
Referenced by com.neuronrobotics.bowlerstudio.BowlerKernel.main().
isAutoupdate()
static boolean com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.isAutoupdate () static
Definition at line 1775 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.autoupdate.
isLoginSuccess()
static boolean com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.isLoginSuccess () static
Definition at line 2076 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.scripting.PasswordManager.loggedIn().
Referenced by com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.getGitSource(), and com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.save().
isUrlAlreadyOpen()
static boolean com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.isUrlAlreadyOpen (String URL) static
Definition at line 325 of file ScriptingEngine.java.
Referenced by com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.waitForRepo().
listBranches() [1/2]
static List<Ref> com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.listBranches (String remoteURI) throws Exception static
Definition at line 1232 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.cloneRepo(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.closeGit(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.openGit(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.uriToFile().
Referenced by com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.hasAtLeastOneReference(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.listBranchNames().
listBranches() [2/2]
static List<Ref> com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.listBranches (String remoteURI, Git git) throws Exception static
Definition at line 1249 of file ScriptingEngine.java.
listBranchNames()
static List<String> com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.listBranchNames (String remoteURI) throws Exception static
Definition at line 1292 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.listBranches().
Referenced by com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.deleteBranch(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.newBranch().
listLocalBranches()
static List<Ref> com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.listLocalBranches (String remoteURI) throws IOException static
Definition at line 1259 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.cloneRepo(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.closeGit(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.openGit(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.uriToFile().
Referenced by com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.listLocalBranchNames().
listLocalBranchNames()
static List<String> com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.listLocalBranchNames (String remoteURI) throws Exception static
Definition at line 1280 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.listLocalBranches().
loadFilesToList() [1/2]
static void com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.loadFilesToList (ArrayList< String > f, File directory, String extnetion) static private
Definition at line 719 of file ScriptingEngine.java.
Referenced by com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.filesInGit(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.loadFilesToList().
loadFilesToList() [2/2]
static void com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.loadFilesToList (ArrayList< String > f, File directory, String extnetion, Git ref) static private
Definition at line 723 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.findLocalPath(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.langauges, and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.loadFilesToList().
locateGit()
static Git com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.locateGit (File f) throws IOException static
Definition at line 1717 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.openGit().
Referenced by com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.checkOwner(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.findGitTagFromFile(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.findLocalPath(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.fork(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.locateGitUrlString().
locateGitUrl() [1/2]
static String com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.locateGitUrl (File f) throws IOException static
Definition at line 1691 of file ScriptingEngine.java.
Referenced by com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.findGitTagFromFile(), com.neuronrobotics.bowlerstudio.printbed.PrintBedManager.PrintBedManager(), and com.neuronrobotics.bowlerstudio.BowlerKernel.processReturnedObjectsStart().
locateGitUrl() [2/2]
static String com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.locateGitUrl (File f, Git ref) throws IOException static
Definition at line 1695 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.closeGit(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.openGit().
locateGitUrlString()
static String com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.locateGitUrlString (File f) static
Definition at line 2024 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.closeGit(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.locateGit().
login()
static void com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.login () throws IOException static
Definition at line 516 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.scripting.PasswordManager.getUsername(), com.neuronrobotics.bowlerstudio.scripting.PasswordManager.hasNetwork(), com.neuronrobotics.bowlerstudio.scripting.PasswordManager.loggedIn(), com.neuronrobotics.bowlerstudio.scripting.PasswordManager.login(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.loginListeners.
Referenced by com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.commit(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.pushCodeToGit(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.waitForLogin().
logout()
static void com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.logout () throws IOException static
Definition at line 526 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.scripting.PasswordManager.getUsername(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.loginListeners, and com.neuronrobotics.bowlerstudio.scripting.PasswordManager.logout().
makeNewRepo()
static GHRepository com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.makeNewRepo (String newName, String description) throws IOException static
Definition at line 1997 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.cloneRepo(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.commit(), com.neuronrobotics.bowlerstudio.scripting.PasswordManager.getGithub(), com.neuronrobotics.bowlerstudio.scripting.PasswordManager.getLoginID(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.makeNewRepoNoFailOver(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.newBranch().
makeNewRepoNoFailOver()
static GHRepository com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.makeNewRepoNoFailOver (String newName, String description) throws IOException, org.kohsuke.github.HttpException static
Definition at line 1970 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.scripting.PasswordManager.getGithub().
Referenced by com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.fork(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.makeNewRepo().
makeTimeoutThread()
static GitTimeoutThread com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.makeTimeoutThread (Git git) static private
Make a timeout thread for printing an exception whenever a git object is opened and not closed within 5 seconds
Returns
Definition at line 405 of file ScriptingEngine.java.
Referenced by com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.cloneRepoLocalSelectAuth(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.openGit().
newBranch() [1/2]
static String com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.newBranch (String remoteURI, String newBranch) throws IOException, RefAlreadyExistsException, RefNotFoundException, InvalidRefNameException, CheckoutConflictException, InvalidRemoteException, TransportException, GitAPIException static
Definition at line 1127 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getFullBranch().
Referenced by com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.checkout(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.makeNewRepo(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.newBranch(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.newBranchLocal(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.pull(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.setCommitContentsAsCurrent().
newBranch() [2/2]
static void com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.newBranch (String remoteURI, String newBranch, RevCommit source) throws IOException, RefAlreadyExistsException, RefNotFoundException, InvalidRefNameException, CheckoutConflictException, InvalidRemoteException, TransportException, GitAPIException static
Definition at line 1134 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.closeGit(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getRepository(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.listBranchNames(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.newBranch(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.newBranchLocal(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.openGit(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.shallowCheckout(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.waitForRepo().
newBranchLocal()
static void com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.newBranchLocal (String newBranch, String remoteURI, Git git, RevCommit source) throws GitAPIException, RefNotFoundException, InvalidRefNameException, CheckoutConflictException, InvalidRemoteException, TransportException, IOException static private
Definition at line 1177 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.scripting.PasswordManager.getCredentialProvider(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getProgressMoniter(), com.neuronrobotics.bowlerstudio.scripting.PasswordManager.loggedIn(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.newBranch().
Referenced by com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.newBranch(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.pull().
openGit() [1/2]
static Git com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.openGit (Repository localRepo) static
Open a git object and start a timeout timer for closing it
Parameters
localRepo
Returns
Definition at line 346 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.scripting.GitTimeoutThread.getException(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.makeTimeoutThread(), and com.neuronrobotics.sdk.util.ThreadUtil.wait().
openGit() [2/2]
static Git com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.openGit (String url) static
Open a git object and start a timeout timer for closing it
Parameters
url
Returns
Definition at line 313 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getRepository().
Referenced by com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.checkout(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.checkoutCommit(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.checkOwner(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.commit(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.deleteBranch(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getAllBranches(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getAllTags(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.listBranches(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.listLocalBranches(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.locateGit(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.locateGitUrl(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.newBranch(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.pull(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.pushCodeToGit(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.tagRepo().
pull() [1/2]
static void com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.pull (String remoteURI) throws IOException, RefAlreadyExistsException, RefNotFoundException, InvalidRefNameException, InvalidRemoteException, TransportException, GitAPIException static
Definition at line 1442 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getBranch(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.hasNetwork(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.pull().
pull() [2/2]
static void com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.pull (String remoteURI, String branch) throws IOException, CheckoutConflictException, NoHeadException, InvalidRemoteException, WrongRepositoryStateException static
Definition at line 1304 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.scripting.PasswordManager.checkInternet(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.cloneRepo(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.closeGit(), com.neuronrobotics.bowlerstudio.scripting.PasswordManager.getCredentialProvider(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getProgressMoniter(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.hasNetwork(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.newBranch(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.newBranchLocal(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.openGit(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.transportConfigCallback, com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.uriToFile(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.waitForRepo().
Referenced by com.neuronrobotics.bowlerstudio.CoquiDockerManager.CoquiDockerManager(), com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.getDatabase(), com.neuronrobotics.bowlerstudio.BowlerKernel.main(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.pull(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.pushCodeToGit(), and com.neuronrobotics.bowlerstudio.vitamins.Vitamins.reLoadDatabaseFromFiles().
pushCodeToGit() [1/2]
static void com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.pushCodeToGit (String id, String branch, String FileName, String content, String commitMessage) throws Exception static
Definition at line 790 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.cloneRepo(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.ensureExistance(), com.neuronrobotics.bowlerstudio.scripting.PasswordManager.getUsername(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.hasNetwork(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.login().
Referenced by com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.copyGitFile(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.createFile(), com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.save(), com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.save(), com.neuronrobotics.bowlerstudio.vitamins.Purchasing.saveDatabase(), and com.neuronrobotics.bowlerstudio.vitamins.Vitamins.saveDatabase().
pushCodeToGit() [2/2]
static void com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.pushCodeToGit (String remoteURI, String branch, String FileName, String content, String commitMessage, boolean flagNewFile) throws Exception static
Definition at line 896 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.cloneRepo(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.closeGit(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.commit(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.findGitTagFromFile(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getBranch(), com.neuronrobotics.bowlerstudio.scripting.PasswordManager.getCredentialProvider(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getProgressMoniter(), com.neuronrobotics.bowlerstudio.scripting.PasswordManager.getUsername(), com.neuronrobotics.bowlerstudio.scripting.PasswordManager.hasNetwork(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.hasNetwork(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.login(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.openGit(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.pull(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.transportConfigCallback, com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.waitForLogin(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.waitForRepo().
removeIGithubLoginListener()
static void com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.removeIGithubLoginListener (IGithubLoginListener l) static
Definition at line 480 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.loginListeners.
removeLogListener()
static void com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.removeLogListener (GitLogProgressMonitor l) static
Definition at line 174 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.logListeners.
removeOnCommitEventListeners()
static void com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.removeOnCommitEventListeners (String url, Runnable event) static
Definition at line 423 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.onCommitEventListeners.
resolveConflict()
static boolean com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.resolveConflict (String remoteURI, CheckoutConflictException con, Git git) static private
Definition at line 1581 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.scripting.PasswordManager.checkInternet(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.commit(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.fileFromGit(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getBranch(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.waitForRepo().
Referenced by com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.checkout(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.shallowCheckout().
returnFirstGist()
static List<String> com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.returnFirstGist (String html) static private
System.out.println("Found gist embed: "+e);
Definition at line 565 of file ScriptingEngine.java.
Referenced by com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getCurrentGist().
setAutoupdate()
static boolean com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.setAutoupdate (boolean autoupdate) throws IOException static
Definition at line 1779 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.autoupdate.
Referenced by com.neuronrobotics.bowlerstudio.vitamins.Vitamins.getGitRepoDatabase(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.setupAnyonmous().
setCommitContentsAsCurrent()
static void com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.setCommitContentsAsCurrent (String url, String branch, RevCommit commit) throws IOException, GitAPIException static
Definition at line 2192 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.checkout(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.commit(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getAllBranches(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.newBranch().
setLastFile()
static void com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.setLastFile (File lastFile) static
Definition at line 1755 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.lastFile.
setLoginManager()
static void com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.setLoginManager (IGitHubLoginManager lm) static
Definition at line 1771 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.scripting.PasswordManager.setLoginManager().
setupAnyonmous()
static GitHub com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.setupAnyonmous () throws IOException static
Definition at line 534 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.setAutoupdate(), and com.neuronrobotics.bowlerstudio.scripting.PasswordManager.setupAnyonmous().
setWorkspace()
static void com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.setWorkspace (File file) static
Definition at line 147 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.appdata, com.neuronrobotics.bowlerstudio.scripting.PasswordManager.loadLoginData(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.workspace.
Referenced by com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getWorkspace().
shallowCheckout()
static void com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.shallowCheckout (String remoteURI, String branch, Git git) throws GitAPIException, RefAlreadyExistsException, InvalidRefNameException, RefNotFoundException, CheckoutConflictException static private
Definition at line 1563 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.resolveConflict().
Referenced by com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.checkout(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.newBranch().
tagExists()
static boolean com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.tagExists (String remoteURI, String newTag) static
Definition at line 2308 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getAllTags().
Referenced by com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.tagRepo().
tagRepo()
static void com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.tagRepo (String remoteURI, String newTag) static
Definition at line 2319 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.closeGit(), com.neuronrobotics.bowlerstudio.scripting.PasswordManager.getCredentialProvider(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getProgressMoniter(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.openGit(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.tagExists(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.transportConfigCallback.
uriToFile()
static File com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.uriToFile (String remoteURI) static
Definition at line 1030 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getWorkspace().
Referenced by com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.checkout(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.checkoutCommit(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.deleteBranch(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.deleteRepo(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getBranch(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getFullBranch(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.listBranches(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.listLocalBranches(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.pull().
urlToGist() [1/2]
static String com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.urlToGist (String in) static
Definition at line 539 of file ScriptingEngine.java.
References com.neuronrobotics.sdk.common.Log.debug().
Referenced by com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getCurrentGist(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.urlToGist().
urlToGist() [2/2]
static String com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.urlToGist (URL htmlUrl) static
Definition at line 2044 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.urlToGist(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.urlToString().
urlToString()
static String com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.urlToString (URL htmlUrl) static
Definition at line 2040 of file ScriptingEngine.java.
Referenced by com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.urlToGist().
versionCompare()
static int com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.versionCompare (String v1, String v2) static
Definition at line 2250 of file ScriptingEngine.java.
Referenced by com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getAllTags().
waitForLogin()
static void com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.waitForLogin () throws IOException, InvalidRemoteException, TransportException, GitAPIException static
The GistID we are waiting to see
Definition at line 616 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.scripting.PasswordManager.getLoginID(), com.neuronrobotics.bowlerstudio.scripting.PasswordManager.getPassword(), com.neuronrobotics.bowlerstudio.scripting.PasswordManager.hasNetwork(), com.neuronrobotics.bowlerstudio.scripting.PasswordManager.loggedIn(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.login(), and com.neuronrobotics.bowlerstudio.scripting.PasswordManager.waitForLogin().
Referenced by com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.checkOwner(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.forkGist(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getUserIdOfGist(), com.neuronrobotics.bowlerstudio.BowlerKernel.main(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.pushCodeToGit().
waitForRepo()
static void com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.waitForRepo (String remoteURI, String reason) static
Definition at line 647 of file ScriptingEngine.java.
References com.neuronrobotics.bowlerstudio.scripting.GitTimeoutThread.getException(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.isUrlAlreadyOpen(), and com.neuronrobotics.sdk.util.ThreadUtil.wait().
Referenced by com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.checkoutCommit(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.cloneRepo(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.commit(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.deleteBranch(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.deleteRepo(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.newBranch(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.pull(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.pushCodeToGit(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.resolveConflict().
Member Data Documentation
appdata
File com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.appdata static private
Definition at line 118 of file ScriptingEngine.java.
Referenced by com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getAppData(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.setWorkspace().
autoupdate
boolean com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.autoupdate = false static private
Definition at line 96 of file ScriptingEngine.java.
Referenced by com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.isAutoupdate(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.setAutoupdate().
filesRun
HashMap<String, File> com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.filesRun = new HashMap<>() static private
Definition at line 113 of file ScriptingEngine.java.
Referenced by com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getFileEngineRunByName(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.inlineScriptRun().
imports
final String [] com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.imports static private
Initial value:
= new String[] {
            "java.nio.file", "java.util", "java.awt.image", "javafx.scene.text", "javafx.scene", "javafx.scene.control",
            "eu.mihosoft.vrl.v3d", "eu.mihosoft.vrl.v3d.svg", "eu.mihosoft.vrl.v3d.samples",
            "eu.mihosoft.vrl.v3d.parametrics", "com.neuronrobotics.imageprovider",
            "com.neuronrobotics.sdk.addons.kinematics.xml", "com.neuronrobotics.sdk.addons.kinematics",
            "com.neuronrobotics.sdk.dyio.peripherals", "com.neuronrobotics.sdk.dyio", "com.neuronrobotics.sdk.common",
            "com.neuronrobotics.sdk.ui", "com.neuronrobotics.sdk.util", "com.neuronrobotics.sdk.serial",
            "com.neuronrobotics.sdk.addons.kinematics", "com.neuronrobotics.sdk.addons.kinematics.math",
            "com.neuronrobotics.sdk.addons.kinematics.gui", "com.neuronrobotics.sdk.config",
            "com.neuronrobotics.bowlerkernel", "com.neuronrobotics.bowlerstudio",
            "com.neuronrobotics.bowlerstudio.scripting", "com.neuronrobotics.bowlerstudio.tabs",
            "com.neuronrobotics.bowlerstudio.physics", "com.neuronrobotics.bowlerstudio.physics",
            "com.neuronrobotics.bowlerstudio.vitamins", "com.neuronrobotics.bowlerstudio.creature",
            "com.neuronrobotics.bowlerstudio.threed" }
Definition at line 98 of file ScriptingEngine.java.
Referenced by com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getImports().
langauges
HashMap<String, IScriptingLanguage> com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.langauges = new HashMap<>() static private
Definition at line 126 of file ScriptingEngine.java.
Referenced by com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.addScriptingLanguage(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getLangaugeByExtention(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getLangaugesMap(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getShellType(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.inlineScriptRun(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.inlineScriptStringRun(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.loadFilesToList().
lastFile
File com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.lastFile static private
Definition at line 119 of file ScriptingEngine.java.
Referenced by com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getLastFile(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.setLastFile().
loginListeners
ArrayList<IGithubLoginListener> com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.loginListeners = new ArrayList<IGithubLoginListener>() static private
Definition at line 124 of file ScriptingEngine.java.
Referenced by com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.addIGithubLoginListener(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.forkGist(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.login(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.logout(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.removeIGithubLoginListener().
logListeners
final ArrayList<GitLogProgressMonitor> com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.logListeners = new ArrayList<>() static private
Definition at line 94 of file ScriptingEngine.java.
Referenced by com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.addLogListener(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.clearLogListener(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getProgressMoniter(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.removeLogListener().
onCommitEventListeners
HashMap<String, ArrayList<Runnable> > com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.onCommitEventListeners = new HashMap<>() static private
Definition at line 127 of file ScriptingEngine.java.
Referenced by com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.addOnCommitEventListeners(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.commit(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.removeOnCommitEventListeners().
TIME_TO_WAIT_BETWEEN_GIT_PULL
final int com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.TIME_TO_WAIT_BETWEEN_GIT_PULL = 100000 static private
Definition at line 89 of file ScriptingEngine.java.
transportConfigCallback
TransportConfigCallback com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.transportConfigCallback = new SshTransportConfigCallback() static private
Definition at line 120 of file ScriptingEngine.java.
Referenced by com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.checkOwner(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.cloneRepoLocalSelectAuth(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.fork(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getAllBranches(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.pull(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.pushCodeToGit(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.tagRepo().
workspace
File com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.workspace static private
Definition at line 117 of file ScriptingEngine.java.
Referenced by com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getWorkspace(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.setWorkspace().
The documentation for this class was generated from the following file:
src/main/java/com/neuronrobotics/bowlerstudio/scripting/ScriptingEngine.java