BowlerKernel: com.neuronrobotics.javacad.JavaCadBuildInfo Class Reference
com.neuronrobotics.javacad.JavaCadBuildInfo Class Reference
Static Public Member Functions
static String getVersion ()
static int getProtocolVersion ()
static int getSDKVersion ()
static int getBuildVersion ()
static int[] getBuildInfo ()
static String getBuildDate ()
static String getSDKVersionString ()
static boolean isOS64bit ()
static boolean isARM ()
static boolean isLinux ()
static boolean isWindows ()
static boolean isMac ()
static boolean isUnix ()
Static Private Member Functions
static String getTag (String target)
static InputStream getBuildPropertiesStream ()
Static Private Attributes
static final String NAME
Detailed Description
The Class SDKBuildInfo.
Definition at line 12 of file JavaCadBuildInfo.java.
Member Function Documentation
getBuildDate()
static String com.neuronrobotics.javacad.JavaCadBuildInfo.getBuildDate () static
Gets the builds the date.
Returns
the builds the date
Definition at line 108 of file JavaCadBuildInfo.java.
getBuildInfo()
static int [] com.neuronrobotics.javacad.JavaCadBuildInfo.getBuildInfo () static
Gets the builds the info.
Returns
the builds the info
Definition at line 62 of file JavaCadBuildInfo.java.
References com.neuronrobotics.javacad.JavaCadBuildInfo.getVersion().
Referenced by com.neuronrobotics.javacad.JavaCadBuildInfo.getBuildVersion(), com.neuronrobotics.javacad.JavaCadBuildInfo.getProtocolVersion(), and com.neuronrobotics.javacad.JavaCadBuildInfo.getSDKVersion().
getBuildPropertiesStream()
static InputStream com.neuronrobotics.javacad.JavaCadBuildInfo.getBuildPropertiesStream () static private
Gets the builds the properties stream.
Returns
the builds the properties stream
Definition at line 129 of file JavaCadBuildInfo.java.
Referenced by com.neuronrobotics.javacad.JavaCadBuildInfo.getTag().
getBuildVersion()
static int com.neuronrobotics.javacad.JavaCadBuildInfo.getBuildVersion () static
Gets the builds the version.
Returns
the builds the version
Definition at line 53 of file JavaCadBuildInfo.java.
References com.neuronrobotics.javacad.JavaCadBuildInfo.getBuildInfo().
getProtocolVersion()
static int com.neuronrobotics.javacad.JavaCadBuildInfo.getProtocolVersion () static
Gets the protocol version.
Returns
the protocol version
Definition at line 35 of file JavaCadBuildInfo.java.
References com.neuronrobotics.javacad.JavaCadBuildInfo.getBuildInfo().
getSDKVersion()
static int com.neuronrobotics.javacad.JavaCadBuildInfo.getSDKVersion () static
Gets the SDK version.
Returns
the SDK version
Definition at line 44 of file JavaCadBuildInfo.java.
References com.neuronrobotics.javacad.JavaCadBuildInfo.getBuildInfo().
getSDKVersionString()
static String com.neuronrobotics.javacad.JavaCadBuildInfo.getSDKVersionString () static
Gets the SDK version string.
Returns
the SDK version string
Definition at line 138 of file JavaCadBuildInfo.java.
References com.neuronrobotics.javacad.JavaCadBuildInfo.NAME.
getTag()
static String com.neuronrobotics.javacad.JavaCadBuildInfo.getTag (String target) static private
Gets the tag.
Parameters
target the target
Returns
the tag
Definition at line 78 of file JavaCadBuildInfo.java.
References com.neuronrobotics.javacad.JavaCadBuildInfo.getBuildPropertiesStream().
Referenced by com.neuronrobotics.javacad.JavaCadBuildInfo.getVersion().
getVersion()
static String com.neuronrobotics.javacad.JavaCadBuildInfo.getVersion () static
Gets the version.
Returns
the version
Definition at line 23 of file JavaCadBuildInfo.java.
References com.neuronrobotics.javacad.JavaCadBuildInfo.getTag().
Referenced by com.neuronrobotics.bowlerstudio.IssueReportingExceptionHandler.except(), and com.neuronrobotics.javacad.JavaCadBuildInfo.getBuildInfo().
isARM()
static boolean com.neuronrobotics.javacad.JavaCadBuildInfo.isARM () static
Checks if is arm.
Returns
true, if is arm
Definition at line 156 of file JavaCadBuildInfo.java.
isLinux()
static boolean com.neuronrobotics.javacad.JavaCadBuildInfo.isLinux () static
Checks if is linux.
Returns
true, if is linux
Definition at line 165 of file JavaCadBuildInfo.java.
Referenced by com.neuronrobotics.javacad.JavaCadBuildInfo.isUnix().
isMac()
static boolean com.neuronrobotics.javacad.JavaCadBuildInfo.isMac () static
Checks if is mac.
Returns
true, if is mac
Definition at line 183 of file JavaCadBuildInfo.java.
Referenced by com.neuronrobotics.javacad.JavaCadBuildInfo.isUnix().
isOS64bit()
static boolean com.neuronrobotics.javacad.JavaCadBuildInfo.isOS64bit () static
Checks if is o s64bit.
Returns
true, if is o s64bit
Definition at line 147 of file JavaCadBuildInfo.java.
isUnix()
static boolean com.neuronrobotics.javacad.JavaCadBuildInfo.isUnix () static
Checks if is unix.
Returns
true, if is unix
Definition at line 192 of file JavaCadBuildInfo.java.
References com.neuronrobotics.javacad.JavaCadBuildInfo.isLinux(), and com.neuronrobotics.javacad.JavaCadBuildInfo.isMac().
isWindows()
static boolean com.neuronrobotics.javacad.JavaCadBuildInfo.isWindows () static
Checks if is windows.
Returns
true, if is windows
Definition at line 174 of file JavaCadBuildInfo.java.
Member Data Documentation
NAME
final String com.neuronrobotics.javacad.JavaCadBuildInfo.NAME static private
Initial value:
= "Neuron Robotics SDK "
            + getProtocolVersion() + "." + getSDKVersion() + "("
            + getBuildVersion() + ")"
The Constant NAME.
Definition at line 14 of file JavaCadBuildInfo.java.
Referenced by com.neuronrobotics.javacad.JavaCadBuildInfo.getSDKVersionString().
The documentation for this class was generated from the following file:
JCSG/src/main/java/com/neuronrobotics/javacad/JavaCadBuildInfo.java