BowlerKernel: com.neuronrobotics.sdk.namespace.bcs.pid.AbstractPidNamespaceImp Class Reference
com.neuronrobotics.sdk.namespace.bcs.pid.AbstractPidNamespaceImp Class Reference abstract
Public Member Functions
AbstractPidNamespaceImp (BowlerAbstractDevice device)
float GetCachedPosition (int group)
void SetCachedPosition (int group, float value)
void flushPIDChannels (double time)
boolean SetPIDInterpolatedVelocity (int group, int unitsPerSecond, double seconds) throws PIDCommandException
int getNumberOfChannels ()
void addPIDEventListener (IPIDEventListener l)
void removePIDEventListener (IPIDEventListener l)
void firePIDLimitEvent (PIDLimitEvent e)
void firePIDEvent (PIDEvent e)
void firePIDResetEvent (int group, float value)
BowlerAbstractDevice getDevice ()
void setDevice (BowlerAbstractDevice device)
PIDChannel getPIDChannel (int group)
boolean isAvailable ()
abstract void onAsyncResponse (BowlerDatagram data)
ArrayList< PIDChannel > getChannels ()
void setChannels (ArrayList< PIDChannel > channels)
Integer getChannelCount ()
void setChannelCount (Integer channelCount)
Public Member Functions inherited from com.neuronrobotics.sdk.namespace.bcs.pid.IExtendedPIDControl
boolean runOutputHysteresisCalibration (int group)
Public Member Functions inherited from com.neuronrobotics.sdk.namespace.bcs.pid.IPidControlNamespace
boolean ResetPIDChannel (int group, float valueToSetCurrentTo)
boolean ConfigurePIDController (PIDConfiguration config)
PIDConfiguration getPIDConfiguration (int group)
boolean ConfigurePDVelovityController (PDVelocityConfiguration config)
PDVelocityConfiguration getPDVelocityConfiguration (int group)
int getPIDChannelCount ()
boolean SetPIDSetPoint (int group, float setpoint, double seconds)
boolean SetAllPIDSetPoint (float[]setpoints, double seconds)
float GetPIDPosition (int group)
float[] GetAllPIDPosition ()
boolean SetPDVelocity (int group, int unitsPerSecond, double seconds) throws PIDCommandException
boolean killAllPidGroups ()
Protected Attributes
ArrayList< PIDChannel > channels = null
long[] lastPacketTime = null
Private Attributes
ArrayList< IPIDEventListener > PIDEventListeners = new ArrayList<IPIDEventListener>()
BowlerAbstractDevice device
Integer channelCount =null
Detailed Description
The Class AbstractPidNamespaceImp.
Definition at line 18 of file AbstractPidNamespaceImp.java.
Constructor & Destructor Documentation
AbstractPidNamespaceImp()
com.neuronrobotics.sdk.namespace.bcs.pid.AbstractPidNamespaceImp.AbstractPidNamespaceImp (BowlerAbstractDevice device)
Instantiates a new abstract pid namespace imp.
Parameters
device the device
Definition at line 40 of file AbstractPidNamespaceImp.java.
References com.neuronrobotics.sdk.namespace.bcs.pid.AbstractPidNamespaceImp.addPIDEventListener(), com.neuronrobotics.sdk.pid.PIDEvent.getGroup(), com.neuronrobotics.sdk.namespace.bcs.pid.AbstractPidNamespaceImp.getPIDChannel(), com.neuronrobotics.sdk.pid.PIDEvent.getValue(), com.neuronrobotics.sdk.pid.PIDChannel.setCurrentCachedPosition(), and com.neuronrobotics.sdk.namespace.bcs.pid.AbstractPidNamespaceImp.setDevice().
Member Function Documentation
addPIDEventListener()
void com.neuronrobotics.sdk.namespace.bcs.pid.AbstractPidNamespaceImp.addPIDEventListener (IPIDEventListener l)
Allows a user to attach a listener to the device to listen for PID events Events include: PID reset, where the user is notified if the controllers input is reset from software PID limit, if the device generates a Home, Upper limit, or Lower limit event from a hardware event PID position, if the current position of the PID controllers sensor input changes.
Parameters
l the l
Implements com.neuronrobotics.sdk.namespace.bcs.pid.IPidControlNamespace.
Definition at line 113 of file AbstractPidNamespaceImp.java.
References com.neuronrobotics.sdk.namespace.bcs.pid.AbstractPidNamespaceImp.PIDEventListeners.
Referenced by com.neuronrobotics.sdk.namespace.bcs.pid.AbstractPidNamespaceImp.AbstractPidNamespaceImp(), and com.neuronrobotics.sdk.pid.GenericPIDDevice.addPIDEventListener().
firePIDEvent()
void com.neuronrobotics.sdk.namespace.bcs.pid.AbstractPidNamespaceImp.firePIDEvent (PIDEvent e)
Fire pid event.
Parameters
e the e
Definition at line 147 of file AbstractPidNamespaceImp.java.
References com.neuronrobotics.sdk.common.Log.error(), com.neuronrobotics.sdk.pid.PIDEvent.getGroup(), com.neuronrobotics.sdk.pid.PIDEvent.getTimeStamp(), com.neuronrobotics.sdk.pid.PIDEvent.getValue(), com.neuronrobotics.sdk.namespace.bcs.pid.AbstractPidNamespaceImp.lastPacketTime, com.neuronrobotics.sdk.pid.IPIDEventListener.onPIDEvent(), com.neuronrobotics.sdk.namespace.bcs.pid.AbstractPidNamespaceImp.PIDEventListeners, and com.neuronrobotics.sdk.namespace.bcs.pid.AbstractPidNamespaceImp.SetCachedPosition().
Referenced by com.neuronrobotics.sdk.pid.GenericPIDDevice.firePIDEvent(), com.neuronrobotics.sdk.namespace.bcs.pid.LegacyPidNamespaceImp.onAsyncResponse(), and com.neuronrobotics.sdk.namespace.bcs.pid.PidNamespaceImp.onAsyncResponse().
firePIDLimitEvent()
void com.neuronrobotics.sdk.namespace.bcs.pid.AbstractPidNamespaceImp.firePIDLimitEvent (PIDLimitEvent e)
Fire pid limit event.
Parameters
e the e
Definition at line 134 of file AbstractPidNamespaceImp.java.
References com.neuronrobotics.sdk.namespace.bcs.pid.AbstractPidNamespaceImp.PIDEventListeners.
Referenced by com.neuronrobotics.sdk.namespace.bcs.pid.LegacyPidNamespaceImp.onAsyncResponse(), and com.neuronrobotics.sdk.namespace.bcs.pid.PidNamespaceImp.onAsyncResponse().
firePIDResetEvent()
void com.neuronrobotics.sdk.namespace.bcs.pid.AbstractPidNamespaceImp.firePIDResetEvent (int group, float value)
Fire pid reset event.
Parameters
group the group
value the value
Definition at line 172 of file AbstractPidNamespaceImp.java.
References com.neuronrobotics.sdk.namespace.bcs.pid.AbstractPidNamespaceImp.PIDEventListeners, and com.neuronrobotics.sdk.namespace.bcs.pid.AbstractPidNamespaceImp.SetCachedPosition().
Referenced by com.neuronrobotics.sdk.pid.GenericPIDDevice.firePIDResetEvent(), and com.neuronrobotics.sdk.namespace.bcs.pid.LegacyPidNamespaceImp.ResetPIDChannel().
flushPIDChannels()
void com.neuronrobotics.sdk.namespace.bcs.pid.AbstractPidNamespaceImp.flushPIDChannels (double time)
This method will read all of the cached or current setpoints for all PID controllers and calls SetAllPIDSetPoint with its internal data.
Parameters
time the time
Implements com.neuronrobotics.sdk.namespace.bcs.pid.IPidControlNamespace.
Definition at line 78 of file AbstractPidNamespaceImp.java.
References com.neuronrobotics.sdk.pid.PIDChannel.getCachedTargetValue(), com.neuronrobotics.sdk.namespace.bcs.pid.AbstractPidNamespaceImp.getNumberOfChannels(), com.neuronrobotics.sdk.namespace.bcs.pid.AbstractPidNamespaceImp.getPIDChannel(), com.neuronrobotics.sdk.common.Log.info(), and com.neuronrobotics.sdk.namespace.bcs.pid.IPidControlNamespace.SetAllPIDSetPoint().
Referenced by com.neuronrobotics.sdk.pid.GenericPIDDevice.flushPIDChannels().
GetCachedPosition()
float com.neuronrobotics.sdk.namespace.bcs.pid.AbstractPidNamespaceImp.GetCachedPosition (int group)
Gets the cached position.
Parameters
group the group
Returns
the int
Definition at line 58 of file AbstractPidNamespaceImp.java.
References com.neuronrobotics.sdk.pid.PIDChannel.getCurrentCachedPosition(), and com.neuronrobotics.sdk.namespace.bcs.pid.AbstractPidNamespaceImp.getPIDChannel().
Referenced by com.neuronrobotics.sdk.namespace.bcs.pid.AbstractPidNamespaceImp.SetPIDInterpolatedVelocity().
getChannelCount()
Integer com.neuronrobotics.sdk.namespace.bcs.pid.AbstractPidNamespaceImp.getChannelCount ()
Gets the channel count.
Returns
the channel count
Definition at line 258 of file AbstractPidNamespaceImp.java.
References com.neuronrobotics.sdk.namespace.bcs.pid.AbstractPidNamespaceImp.channelCount.
Referenced by com.neuronrobotics.sdk.namespace.bcs.pid.LegacyPidNamespaceImp.getPIDChannelCount().
getChannels()
ArrayList<PIDChannel> com.neuronrobotics.sdk.namespace.bcs.pid.AbstractPidNamespaceImp.getChannels ()
Gets the channels.
Returns
the channels
Definition at line 232 of file AbstractPidNamespaceImp.java.
References com.neuronrobotics.sdk.namespace.bcs.pid.AbstractPidNamespaceImp.channels, com.neuronrobotics.sdk.namespace.bcs.pid.AbstractPidNamespaceImp.getPIDChannel(), and com.neuronrobotics.sdk.namespace.bcs.pid.IPidControlNamespace.getPIDChannelCount().
Referenced by com.neuronrobotics.sdk.namespace.bcs.pid.LegacyPidNamespaceImp.GetAllPIDPosition(), com.neuronrobotics.sdk.pid.GenericPIDDevice.getChannels(), com.neuronrobotics.sdk.namespace.bcs.pid.AbstractPidNamespaceImp.getNumberOfChannels(), and com.neuronrobotics.sdk.namespace.bcs.pid.AbstractPidNamespaceImp.getPIDChannel().
getDevice()
BowlerAbstractDevice com.neuronrobotics.sdk.namespace.bcs.pid.AbstractPidNamespaceImp.getDevice ()
Gets the device.
Returns
the device
Definition at line 184 of file AbstractPidNamespaceImp.java.
References com.neuronrobotics.sdk.namespace.bcs.pid.AbstractPidNamespaceImp.device.
Referenced by com.neuronrobotics.sdk.namespace.bcs.pid.LegacyPidNamespaceImp.ConfigurePDVelovityController(), com.neuronrobotics.sdk.namespace.bcs.pid.LegacyPidNamespaceImp.ConfigurePIDController(), com.neuronrobotics.sdk.namespace.bcs.pid.LegacyPidNamespaceImp.GetAllPIDPosition(), com.neuronrobotics.sdk.namespace.bcs.pid.LegacyPidNamespaceImp.getPDVelocityConfiguration(), com.neuronrobotics.sdk.namespace.bcs.pid.LegacyPidNamespaceImp.getPIDChannelCount(), com.neuronrobotics.sdk.namespace.bcs.pid.LegacyPidNamespaceImp.getPIDConfiguration(), com.neuronrobotics.sdk.namespace.bcs.pid.LegacyPidNamespaceImp.GetPIDPosition(), com.neuronrobotics.sdk.namespace.bcs.pid.LegacyPidNamespaceImp.killAllPidGroups(), com.neuronrobotics.sdk.namespace.bcs.pid.LegacyPidNamespaceImp.ResetPIDChannel(), com.neuronrobotics.sdk.namespace.bcs.pid.PidNamespaceImp.send(), com.neuronrobotics.sdk.namespace.bcs.pid.LegacyPidNamespaceImp.SetAllPIDSetPoint(), com.neuronrobotics.sdk.namespace.bcs.pid.LegacyPidNamespaceImp.SetPDVelocity(), and com.neuronrobotics.sdk.namespace.bcs.pid.LegacyPidNamespaceImp.SetPIDSetPoint().
getNumberOfChannels()
int com.neuronrobotics.sdk.namespace.bcs.pid.AbstractPidNamespaceImp.getNumberOfChannels ()
Gets the number of PID channels availible to the system. It is determined by how many PID channels the device reports back after a calling GetAllPIDPosition();
Returns
the number of channels
Definition at line 105 of file AbstractPidNamespaceImp.java.
References com.neuronrobotics.sdk.namespace.bcs.pid.AbstractPidNamespaceImp.getChannels().
Referenced by com.neuronrobotics.sdk.namespace.bcs.pid.AbstractPidNamespaceImp.flushPIDChannels(), com.neuronrobotics.sdk.namespace.bcs.pid.LegacyPidNamespaceImp.GetAllPIDPosition(), com.neuronrobotics.sdk.namespace.bcs.pid.AbstractPidNamespaceImp.getPIDChannel(), com.neuronrobotics.sdk.pid.GenericPIDDevice.getPIDChannelCount(), com.neuronrobotics.sdk.namespace.bcs.pid.LegacyPidNamespaceImp.onAsyncResponse(), com.neuronrobotics.sdk.namespace.bcs.pid.PidNamespaceImp.onAsyncResponse(), and com.neuronrobotics.sdk.namespace.bcs.pid.LegacyPidNamespaceImp.SetAllPIDSetPoint().
getPIDChannel()
PIDChannel com.neuronrobotics.sdk.namespace.bcs.pid.AbstractPidNamespaceImp.getPIDChannel (int group)
Gets the PID channel wrapper for a specific channel. The channel wrappers can be used to cache values for use with the cache/flush system. This wrapper will encapsulate a specific PID channel.
Parameters
group the index of the PID group
Returns
a PIDChannel encapsulation object
Implements com.neuronrobotics.sdk.namespace.bcs.pid.IPidControlNamespace.
Definition at line 200 of file AbstractPidNamespaceImp.java.
References com.neuronrobotics.sdk.namespace.bcs.pid.AbstractPidNamespaceImp.getChannels(), and com.neuronrobotics.sdk.namespace.bcs.pid.AbstractPidNamespaceImp.getNumberOfChannels().
Referenced by com.neuronrobotics.sdk.namespace.bcs.pid.AbstractPidNamespaceImp.AbstractPidNamespaceImp(), com.neuronrobotics.sdk.namespace.bcs.pid.AbstractPidNamespaceImp.flushPIDChannels(), com.neuronrobotics.sdk.namespace.bcs.pid.AbstractPidNamespaceImp.GetCachedPosition(), com.neuronrobotics.sdk.namespace.bcs.pid.AbstractPidNamespaceImp.getChannels(), com.neuronrobotics.sdk.pid.GenericPIDDevice.getPIDChannel(), com.neuronrobotics.sdk.namespace.bcs.pid.LegacyPidNamespaceImp.SetAllPIDSetPoint(), com.neuronrobotics.sdk.namespace.bcs.pid.AbstractPidNamespaceImp.SetCachedPosition(), and com.neuronrobotics.sdk.namespace.bcs.pid.LegacyPidNamespaceImp.SetPIDSetPoint().
isAvailable()
boolean com.neuronrobotics.sdk.namespace.bcs.pid.AbstractPidNamespaceImp.isAvailable ()
Checks to see if the PID controller object is connected with its device.
Returns
true, if is available
Implements com.neuronrobotics.sdk.namespace.bcs.pid.IPidControlNamespace.
Definition at line 215 of file AbstractPidNamespaceImp.java.
References com.neuronrobotics.sdk.namespace.bcs.pid.AbstractPidNamespaceImp.device, and com.neuronrobotics.sdk.common.BowlerAbstractDevice.isAvailable().
onAsyncResponse()
abstract void com.neuronrobotics.sdk.namespace.bcs.pid.AbstractPidNamespaceImp.onAsyncResponse (BowlerDatagram data) abstract
On async response.
Parameters
data the data
Reimplemented in com.neuronrobotics.sdk.namespace.bcs.pid.PidNamespaceImp, and com.neuronrobotics.sdk.namespace.bcs.pid.LegacyPidNamespaceImp.
Referenced by com.neuronrobotics.sdk.pid.GenericPIDDevice.onAsyncResponse().
removePIDEventListener()
void com.neuronrobotics.sdk.namespace.bcs.pid.AbstractPidNamespaceImp.removePIDEventListener (IPIDEventListener l)
Removes a specific IPIDEventListener.
Parameters
l the l
Implements com.neuronrobotics.sdk.namespace.bcs.pid.IPidControlNamespace.
Definition at line 122 of file AbstractPidNamespaceImp.java.
References com.neuronrobotics.sdk.namespace.bcs.pid.AbstractPidNamespaceImp.PIDEventListeners.
Referenced by com.neuronrobotics.sdk.pid.GenericPIDDevice.removePIDEventListener().
SetCachedPosition()
void com.neuronrobotics.sdk.namespace.bcs.pid.AbstractPidNamespaceImp.SetCachedPosition (int group, float value)
Sets the cached position.
Parameters
group the group
value the value
Definition at line 68 of file AbstractPidNamespaceImp.java.
References com.neuronrobotics.sdk.namespace.bcs.pid.AbstractPidNamespaceImp.getPIDChannel(), and com.neuronrobotics.sdk.pid.PIDChannel.setCurrentCachedPosition().
Referenced by com.neuronrobotics.sdk.namespace.bcs.pid.AbstractPidNamespaceImp.firePIDEvent(), and com.neuronrobotics.sdk.namespace.bcs.pid.AbstractPidNamespaceImp.firePIDResetEvent().
setChannelCount()
void com.neuronrobotics.sdk.namespace.bcs.pid.AbstractPidNamespaceImp.setChannelCount (Integer channelCount)
Sets the channel count.
Parameters
channelCount the new channel count
Definition at line 268 of file AbstractPidNamespaceImp.java.
References com.neuronrobotics.sdk.namespace.bcs.pid.AbstractPidNamespaceImp.channelCount.
Referenced by com.neuronrobotics.sdk.namespace.bcs.pid.LegacyPidNamespaceImp.getPIDChannelCount(), and com.neuronrobotics.sdk.pid.VirtualGenericPIDDevice.VirtualGenericPIDDevice().
setChannels()
void com.neuronrobotics.sdk.namespace.bcs.pid.AbstractPidNamespaceImp.setChannels (ArrayList< PIDChannel > channels)
Sets the channels.
Parameters
channels the new channels
Definition at line 248 of file AbstractPidNamespaceImp.java.
References com.neuronrobotics.sdk.namespace.bcs.pid.AbstractPidNamespaceImp.channels.
Referenced by com.neuronrobotics.sdk.pid.GenericPIDDevice.setChannels().
setDevice()
void com.neuronrobotics.sdk.namespace.bcs.pid.AbstractPidNamespaceImp.setDevice (BowlerAbstractDevice device)
Sets the device.
Parameters
device the new device
Definition at line 193 of file AbstractPidNamespaceImp.java.
References com.neuronrobotics.sdk.namespace.bcs.pid.AbstractPidNamespaceImp.device.
Referenced by com.neuronrobotics.sdk.namespace.bcs.pid.AbstractPidNamespaceImp.AbstractPidNamespaceImp().
SetPIDInterpolatedVelocity()
boolean com.neuronrobotics.sdk.namespace.bcs.pid.AbstractPidNamespaceImp.SetPIDInterpolatedVelocity (int group, int unitsPerSecond, double seconds) throws PIDCommandException
This method will use the linear interpolation system to set an output velocity of the PID controller. This method can be bounded by the maximum value representable by the sensor and can fail if that value is out of range.
Parameters
group the index of the PID group
unitsPerSecond a velocity in raw units per second
seconds the amount of time to run at this velocity
Returns
true if successful
Exceptions
PIDCommandException If the values are out of range with the given data
Implements com.neuronrobotics.sdk.namespace.bcs.pid.IPidControlNamespace.
Definition at line 90 of file AbstractPidNamespaceImp.java.
References com.neuronrobotics.sdk.namespace.bcs.pid.AbstractPidNamespaceImp.GetCachedPosition(), and com.neuronrobotics.sdk.namespace.bcs.pid.IPidControlNamespace.SetPIDSetPoint().
Referenced by com.neuronrobotics.sdk.namespace.bcs.pid.LegacyPidNamespaceImp.SetPDVelocity(), and com.neuronrobotics.sdk.pid.GenericPIDDevice.SetPIDInterpolatedVelocity().
Member Data Documentation
channelCount
Integer com.neuronrobotics.sdk.namespace.bcs.pid.AbstractPidNamespaceImp.channelCount =null private
The channel count.
Definition at line 33 of file AbstractPidNamespaceImp.java.
Referenced by com.neuronrobotics.sdk.namespace.bcs.pid.AbstractPidNamespaceImp.getChannelCount(), and com.neuronrobotics.sdk.namespace.bcs.pid.AbstractPidNamespaceImp.setChannelCount().
channels
ArrayList<PIDChannel> com.neuronrobotics.sdk.namespace.bcs.pid.AbstractPidNamespaceImp.channels = null protected
The channels.
Definition at line 24 of file AbstractPidNamespaceImp.java.
Referenced by com.neuronrobotics.sdk.namespace.bcs.pid.AbstractPidNamespaceImp.getChannels(), and com.neuronrobotics.sdk.namespace.bcs.pid.AbstractPidNamespaceImp.setChannels().
device
BowlerAbstractDevice com.neuronrobotics.sdk.namespace.bcs.pid.AbstractPidNamespaceImp.device private
The device.
Definition at line 30 of file AbstractPidNamespaceImp.java.
Referenced by com.neuronrobotics.sdk.namespace.bcs.pid.AbstractPidNamespaceImp.getDevice(), com.neuronrobotics.sdk.namespace.bcs.pid.AbstractPidNamespaceImp.isAvailable(), com.neuronrobotics.sdk.namespace.bcs.pid.LegacyPidNamespaceImp.LegacyPidNamespaceImp(), com.neuronrobotics.sdk.namespace.bcs.pid.PidNamespaceImp.PidNamespaceImp(), and com.neuronrobotics.sdk.namespace.bcs.pid.AbstractPidNamespaceImp.setDevice().
lastPacketTime
long [] com.neuronrobotics.sdk.namespace.bcs.pid.AbstractPidNamespaceImp.lastPacketTime = null protected
The last packet time.
Definition at line 27 of file AbstractPidNamespaceImp.java.
Referenced by com.neuronrobotics.sdk.namespace.bcs.pid.AbstractPidNamespaceImp.firePIDEvent(), and com.neuronrobotics.sdk.namespace.bcs.pid.LegacyPidNamespaceImp.GetAllPIDPosition().
PIDEventListeners
ArrayList<IPIDEventListener> com.neuronrobotics.sdk.namespace.bcs.pid.AbstractPidNamespaceImp.PIDEventListeners = new ArrayList<IPIDEventListener>() private
The PID event listeners.
Definition at line 21 of file AbstractPidNamespaceImp.java.
Referenced by com.neuronrobotics.sdk.namespace.bcs.pid.AbstractPidNamespaceImp.addPIDEventListener(), com.neuronrobotics.sdk.namespace.bcs.pid.AbstractPidNamespaceImp.firePIDEvent(), com.neuronrobotics.sdk.namespace.bcs.pid.AbstractPidNamespaceImp.firePIDLimitEvent(), com.neuronrobotics.sdk.namespace.bcs.pid.AbstractPidNamespaceImp.firePIDResetEvent(), and com.neuronrobotics.sdk.namespace.bcs.pid.AbstractPidNamespaceImp.removePIDEventListener().
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/namespace/bcs/pid/AbstractPidNamespaceImp.java