BowlerKernel: com.neuronrobotics.bowlerkernel.Bezier3d.CartesianManipulator Class Reference
com.neuronrobotics.bowlerkernel.Bezier3d.CartesianManipulator Class Reference
Public Member Functions
CartesianManipulator (TransformNR globalPose)
void addEventListener (Runnable r)
void addSaveListener (Runnable r)
List< CSG > get ()
double getX ()
double getY ()
double getZ ()
void addDependant (CartesianManipulator r)
boolean isMoving ()
void clearListeners ()
void set (double newX, double newY, double newZ)
Public Attributes
Affine manipulationMatrix = new Affine()
Private Attributes
manipulation[] manipulationList = new manipulation[3]
Detailed Description
Definition at line 15 of file CartesianManipulator.java.
Constructor & Destructor Documentation
CartesianManipulator()
com.neuronrobotics.bowlerkernel.Bezier3d.CartesianManipulator.CartesianManipulator (TransformNR globalPose)
Definition at line 23 of file CartesianManipulator.java.
References com.neuronrobotics.bowlerkernel.Bezier3d.CartesianManipulator.manipulationList, com.neuronrobotics.bowlerkernel.Bezier3d.CartesianManipulator.manipulationMatrix, and eu.mihosoft.vrl.v3d.CSG.setMfg().
Member Function Documentation
addDependant()
void com.neuronrobotics.bowlerkernel.Bezier3d.CartesianManipulator.addDependant (CartesianManipulator r)
Definition at line 59 of file CartesianManipulator.java.
References com.neuronrobotics.bowlerkernel.Bezier3d.CartesianManipulator.manipulationList.
Referenced by com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.BezierEditor(), and com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.setStartManip().
addEventListener()
void com.neuronrobotics.bowlerkernel.Bezier3d.CartesianManipulator.addEventListener (Runnable r)
Definition at line 33 of file CartesianManipulator.java.
References com.neuronrobotics.bowlerkernel.Bezier3d.CartesianManipulator.manipulationList.
Referenced by com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.BezierEditor(), and com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.setStartManip().
addSaveListener()
void com.neuronrobotics.bowlerkernel.Bezier3d.CartesianManipulator.addSaveListener (Runnable r)
Definition at line 38 of file CartesianManipulator.java.
References com.neuronrobotics.bowlerkernel.Bezier3d.CartesianManipulator.manipulationList.
Referenced by com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.BezierEditor(), and com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.setStartManip().
clearListeners()
void com.neuronrobotics.bowlerkernel.Bezier3d.CartesianManipulator.clearListeners ()
Definition at line 70 of file CartesianManipulator.java.
References com.neuronrobotics.bowlerkernel.Bezier3d.CartesianManipulator.manipulationList.
Referenced by com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.setStartManip().
get()
List<CSG> com.neuronrobotics.bowlerkernel.Bezier3d.CartesianManipulator.get ()
Definition at line 43 of file CartesianManipulator.java.
Referenced by com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.getCSG().
getX()
double com.neuronrobotics.bowlerkernel.Bezier3d.CartesianManipulator.getX ()
Definition at line 47 of file CartesianManipulator.java.
References com.neuronrobotics.bowlerkernel.Bezier3d.manipulation.currentPose, com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getX(), and com.neuronrobotics.bowlerkernel.Bezier3d.CartesianManipulator.manipulationList.
Referenced by com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.save(), com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.transforms(), com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.update(), and com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.updateLines().
getY()
double com.neuronrobotics.bowlerkernel.Bezier3d.CartesianManipulator.getY ()
Definition at line 51 of file CartesianManipulator.java.
References com.neuronrobotics.bowlerkernel.Bezier3d.manipulation.currentPose, com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getY(), and com.neuronrobotics.bowlerkernel.Bezier3d.CartesianManipulator.manipulationList.
Referenced by com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.save(), com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.transforms(), com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.update(), and com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.updateLines().
getZ()
double com.neuronrobotics.bowlerkernel.Bezier3d.CartesianManipulator.getZ ()
Definition at line 55 of file CartesianManipulator.java.
References com.neuronrobotics.bowlerkernel.Bezier3d.manipulation.currentPose, com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getZ(), and com.neuronrobotics.bowlerkernel.Bezier3d.CartesianManipulator.manipulationList.
Referenced by com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.save(), com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.transforms(), com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.update(), and com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.updateLines().
isMoving()
boolean com.neuronrobotics.bowlerkernel.Bezier3d.CartesianManipulator.isMoving ()
Definition at line 63 of file CartesianManipulator.java.
References com.neuronrobotics.bowlerkernel.Bezier3d.CartesianManipulator.manipulationList.
Referenced by com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.update().
set()
void com.neuronrobotics.bowlerkernel.Bezier3d.CartesianManipulator.set (double newX, double newY, double newZ)
Definition at line 76 of file CartesianManipulator.java.
References com.neuronrobotics.bowlerkernel.Bezier3d.CartesianManipulator.manipulationList.
Referenced by com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.setCP1(), com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.setCP2(), com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.setEnd(), com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.setStart(), and com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.update().
Member Data Documentation
manipulationList
manipulation [] com.neuronrobotics.bowlerkernel.Bezier3d.CartesianManipulator.manipulationList = new manipulation[3] private
Definition at line 20 of file CartesianManipulator.java.
Referenced by com.neuronrobotics.bowlerkernel.Bezier3d.CartesianManipulator.addDependant(), com.neuronrobotics.bowlerkernel.Bezier3d.CartesianManipulator.addEventListener(), com.neuronrobotics.bowlerkernel.Bezier3d.CartesianManipulator.addSaveListener(), com.neuronrobotics.bowlerkernel.Bezier3d.CartesianManipulator.CartesianManipulator(), com.neuronrobotics.bowlerkernel.Bezier3d.CartesianManipulator.clearListeners(), com.neuronrobotics.bowlerkernel.Bezier3d.CartesianManipulator.getX(), com.neuronrobotics.bowlerkernel.Bezier3d.CartesianManipulator.getY(), com.neuronrobotics.bowlerkernel.Bezier3d.CartesianManipulator.getZ(), com.neuronrobotics.bowlerkernel.Bezier3d.CartesianManipulator.isMoving(), and com.neuronrobotics.bowlerkernel.Bezier3d.CartesianManipulator.set().
manipulationMatrix
Affine com.neuronrobotics.bowlerkernel.Bezier3d.CartesianManipulator.manipulationMatrix = new Affine()
Definition at line 16 of file CartesianManipulator.java.
Referenced by com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.BezierEditor(), com.neuronrobotics.bowlerkernel.Bezier3d.CartesianManipulator.CartesianManipulator(), and com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.setStartManip().
The documentation for this class was generated from the following file:
src/main/java/com/neuronrobotics/bowlerkernel/Bezier3d/CartesianManipulator.java