BowlerKernel: eu.mihosoft.vrl.v3d.FileUtil Class Reference
eu.mihosoft.vrl.v3d.FileUtil Class Reference
Static Public Member Functions
static void write (Path p, String s) throws IOException
static String read (Path p) throws IOException
Private Member Functions
FileUtil ()
Detailed Description
File util class.
Author
Michael Hoffer <info@.nosp@m.mich.nosp@m.aelho.nosp@m.ffer.nosp@m..de>
Definition at line 46 of file FileUtil.java.
Constructor & Destructor Documentation
FileUtil()
eu.mihosoft.vrl.v3d.FileUtil.FileUtil () private
Instantiates a new file util.
Definition at line 51 of file FileUtil.java.
Member Function Documentation
read()
static String eu.mihosoft.vrl.v3d.FileUtil.read (Path p) throws IOException static
Reads the specified file to a string.
Parameters
p file to read
Returns
the content of the file
Exceptions
IOException if reading from file failed
Definition at line 78 of file FileUtil.java.
write()
static void eu.mihosoft.vrl.v3d.FileUtil.write (Path p, String s) throws IOException static
Writes the specified string to a file.
Parameters
p file destination (existing files will be overwritten)
s string to save
Exceptions
IOException if writing to file fails
Definition at line 63 of file FileUtil.java.
Referenced by com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager._generateStls(), com.neuronrobotics.bowlerstudio.creature.CadFileExporter.makeObj(), com.neuronrobotics.bowlerstudio.creature.CadFileExporter.makeStl(), and eu.mihosoft.vrl.v3d.ObjFile.toFiles().
The documentation for this class was generated from the following file:
JCSG/src/main/java/eu/mihosoft/vrl/v3d/FileUtil.java