BowlerKernel: com.neuronrobotics.sdk.addons.kinematics.math.TransformNR Class Reference
com.neuronrobotics.sdk.addons.kinematics.math.TransformNR Class Reference
Public Member Functions
TransformNR (Matrix m)
TransformNR (double x, double y, double z, double w, double rotx, double roty, double rotz)
TransformNR (double[] cartesianSpaceVector, double[][] rotationMatrix)
TransformNR (double[] cartesianSpaceVector, double[] quaternionVector)
TransformNR (double x, double y, double z, RotationNR q)
TransformNR (double[] cartesianSpaceVector, RotationNR q)
TransformNR ()
double getX ()
double getY ()
double getZ ()
double[][] getRotationMatrixArray ()
RotationNR getRotationMatrix ()
double getRotationValue (int i, int j)
RotationNR getRotation ()
TransformNR times (TransformNR t)
String toString ()
double[] getPositionArray ()
Matrix getMatrixTransform ()
double getOffsetOrentationMagnitude (TransformNR t)
double getOffsetVectorMagnitude (TransformNR t)
TransformNR inverse ()
TransformNR scale (BigDecimal scale)
TransformNR scale (double t)
TransformNR copy ()
TransformNR translateX (double translation)
TransformNR translateY (double translation)
TransformNR translateZ (double translation)
TransformNR set (double tx, double ty, double tz, double[][] poseRot)
TransformNR setX (double tx)
TransformNR setY (double ty)
TransformNR setZ (double tz)
String getXml ()
TransformNR setRotation (RotationNR rotation)
void addChangeListener (ITransformNRChangeListener l)
void removeChangeListener (ITransformNRChangeListener l)
void clearChangeListener ()
ArrayList< ITransformNRChangeListener > getListeners ()
void setTiltDegrees (double newAngleDegrees)
void setElevationDegrees (double newAngleDegrees)
void setAzimuthDegrees (double newAngleDegrees)
Static Public Member Functions
static String getMatrixString (Matrix matrix)
Private Attributes
ArrayList< ITransformNRChangeListener > listeners =null
double x
double y
double z
RotationNR rotation
Detailed Description
The Class TransformNR.
Definition at line 13 of file TransformNR.java.
Constructor & Destructor Documentation
TransformNR() [1/7]
com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.TransformNR (Matrix m)
Instantiates a new transform nr.
Parameters
m the m
Definition at line 34 of file TransformNR.java.
References com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.setRotation(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.setX(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.setY(), and com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.setZ().
TransformNR() [2/7]
com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.TransformNR (double x, double y, double z, double w, double rotx, double roty, double rotz)
Instantiates a new transform nr.
Parameters
x the x
y the y
z the z
w the w
rotx the rotx
roty the roty
rotz the rotz
Definition at line 52 of file TransformNR.java.
References com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.setRotation(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.setX(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.setY(), and com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.setZ().
TransformNR() [3/7]
com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.TransformNR (double[] cartesianSpaceVector, double rotationMatrix[][])
Instantiates a new transform nr.
Parameters
cartesianSpaceVector the cartesian space vector
rotationMatrix the rotation matrix
Definition at line 66 of file TransformNR.java.
References com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.setRotation(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.setX(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.setY(), and com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.setZ().
TransformNR() [4/7]
com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.TransformNR (double[] cartesianSpaceVector, double[] quaternionVector)
Instantiates a new transform nr.
Parameters
cartesianSpaceVector the cartesian space vector
quaternionVector the quaternion vector
Definition at line 79 of file TransformNR.java.
References com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.setRotation(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.setX(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.setY(), and com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.setZ().
TransformNR() [5/7]
com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.TransformNR (double x, double y, double z, RotationNR q)
Instantiates a new transform nr.
Parameters
x the x
y the y
z the z
q the q
Definition at line 94 of file TransformNR.java.
References com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.setRotation(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.setX(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.setY(), and com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.setZ().
TransformNR() [6/7]
com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.TransformNR (double[] cartesianSpaceVector, RotationNR q)
Instantiates a new transform nr.
Parameters
cartesianSpaceVector the cartesian space vector
q the q
Definition at line 107 of file TransformNR.java.
References com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.setRotation(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.setX(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.setY(), and com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.setZ().
TransformNR() [7/7]
com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.TransformNR ()
Instantiates a new transform nr.
Definition at line 117 of file TransformNR.java.
References com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.setRotation(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.setX(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.setY(), and com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.setZ().
Referenced by com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.copy(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.inverse(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.scale(), and com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.times().
Member Function Documentation
addChangeListener()
void com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.addChangeListener (ITransformNRChangeListener l)
Definition at line 487 of file TransformNR.java.
References com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getListeners().
Referenced by com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setCenterOfMassFromCentroid(), and com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setimuFromCentroid().
clearChangeListener()
void com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.clearChangeListener ()
Definition at line 495 of file TransformNR.java.
References com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getListeners(), and com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.listeners.
copy()
TransformNR com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.copy ()
Copy.
Returns
the transform nr
Definition at line 357 of file TransformNR.java.
References com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getMatrixTransform(), and com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.TransformNR().
Referenced by com.neuronrobotics.bowlerstudio.vitamins.VitaminBomManager.getCoMLocation(), com.neuronrobotics.sdk.addons.kinematics.ik.DeltaIKModel.inverseKinematics6dof(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.main(), com.neuronrobotics.bowlerkernel.Bezier3d.manipulation.manipulation(), com.neuronrobotics.bowlerstudio.physics.MobileBasePhysicsManager.MobileBasePhysicsManager(), and com.neuronrobotics.bowlerkernel.Bezier3d.manipulation.performMove().
getListeners()
ArrayList<ITransformNRChangeListener> com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getListeners ()
Definition at line 499 of file TransformNR.java.
References com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.listeners.
Referenced by com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.addChangeListener(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.clearChangeListener(), and com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.removeChangeListener().
getMatrixString()
static String com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getMatrixString (Matrix matrix) static
Gets the matrix string.
Parameters
matrix the matrix
Returns
the matrix string
Definition at line 220 of file TransformNR.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.toString().
getMatrixTransform()
Matrix com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getMatrixTransform ()
Gets the matrix transform.
Returns
the matrix transform
Definition at line 262 of file TransformNR.java.
References com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getRotationMatrixArray(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getX(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getY(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getZ(), and com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.rotation.
Referenced by com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.copy(), com.neuronrobotics.sdk.addons.kinematics.DHLink.DhStepInverse(), com.neuronrobotics.sdk.addons.kinematics.DHChain.forwardKinematicsMatrix(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.forwardOffset(), com.neuronrobotics.sdk.addons.kinematics.DHChain.getInverseSolver(), com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getJacobian(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.inverse(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.inverseOffset(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.times(), and com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.toString().
getOffsetOrentationMagnitude()
double com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getOffsetOrentationMagnitude (TransformNR t)
Gets the offset orentation magnitude.
Parameters
t the t
Returns
the offset orentation magnitude
Definition at line 290 of file TransformNR.java.
References com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getRotation(), com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.getRotationMatrix2QuaturnionX(), com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.getRotationMatrix2QuaturnionY(), com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.getRotationMatrix2QuaturnionZ(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.x, com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.y, and com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.z.
Referenced by com.neuronrobotics.sdk.addons.kinematics.SearchTreeSolver.configuration.getTransform(), com.neuronrobotics.sdk.addons.kinematics.GradiantDecent.inverseKinematics(), and com.neuronrobotics.sdk.addons.kinematics.GradiantDecentNode.stepOrent().
getOffsetVectorMagnitude()
double com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getOffsetVectorMagnitude (TransformNR t)
Gets the offset vector magnitude.
Parameters
t the t
Returns
the offset vector magnitude
Definition at line 307 of file TransformNR.java.
References com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getX(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getY(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getZ(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.x, com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.y, and com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.z.
Referenced by com.neuronrobotics.sdk.addons.kinematics.SearchTreeSolver.configuration.getTransform(), com.neuronrobotics.sdk.addons.kinematics.GradiantDecent.inverseKinematics(), and com.neuronrobotics.sdk.addons.kinematics.GradiantDecentNode.stepLin().
getPositionArray()
double [] com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getPositionArray ()
Gets the position array.
Returns
the position array
Definition at line 253 of file TransformNR.java.
References com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getX(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getY(), and com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getZ().
getRotation()
RotationNR com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getRotation ()
Gets the rotation.
Returns
the rotation
Definition at line 185 of file TransformNR.java.
References com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.rotation.
Referenced by com.neuronrobotics.sdk.addons.kinematics.WalkingDriveEngine.DriveArc(), com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.eulerFix(), com.neuronrobotics.sdk.addons.kinematics.DHChain.getInverseSolver(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getOffsetOrentationMagnitude(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getRotationMatrix(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getRotationMatrixArray(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getRotationValue(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getXml(), com.neuronrobotics.sdk.addons.kinematics.ik.DeltaIKModel.inverseKinematics6dof(), com.neuronrobotics.bowlerstudio.physics.TransformFactory.nrToBullet(), com.neuronrobotics.bowlerstudio.physics.TransformFactory.nrToCSG(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.scale(), com.neuronrobotics.bowlerstudio.physics.TransformFactory.scale(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.set(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.setAzimuthDegrees(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.setElevationDegrees(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.setTiltDegrees(), and com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.toString().
getRotationMatrix()
RotationNR com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getRotationMatrix ()
Gets the rotation matrix.
Returns
the rotation matrix
Definition at line 165 of file TransformNR.java.
References com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getRotation().
Referenced by com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getJacobian().
getRotationMatrixArray()
double [][] com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getRotationMatrixArray ()
Gets the rotation matrix array.
Returns
the rotation matrix array
Definition at line 156 of file TransformNR.java.
References com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getRotation(), and com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.getRotationMatrix().
Referenced by com.neuronrobotics.bowlerstudio.physics.TransformFactory.affineToNr(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getMatrixTransform(), and com.neuronrobotics.bowlerstudio.physics.TransformFactory.nrToAffine().
getRotationValue()
double com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getRotationValue (int i, int j)
Gets the rotation value.
Parameters
i the i
j the j
Returns
the rotation value
Definition at line 176 of file TransformNR.java.
References com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getRotation(), and com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.getRotationMatrix().
getX()
double com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getX ()
Gets the x.
Returns
the x
Definition at line 129 of file TransformNR.java.
References com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.x.
Referenced by com.neuronrobotics.bowlerstudio.printbed.PrintBedObject.checkBounds(), com.neuronrobotics.replicator.driver.delta.DeltaRobotKinematics.delta_calcInverse(), com.neuronrobotics.sdk.addons.kinematics.WalkingDriveEngine.DriveArc(), com.neuronrobotics.sdk.addons.kinematics.DHChain.getInverseSolver(), com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getJacobian(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getMatrixTransform(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getOffsetVectorMagnitude(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getPositionArray(), com.neuronrobotics.bowlerkernel.Bezier3d.CartesianManipulator.getX(), com.neuronrobotics.bowlerstudio.printbed.PrintBedObject.getX(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getXml(), com.neuronrobotics.sdk.addons.kinematics.ik.DeltaIKModel.inverseKinematics6dof(), com.neuronrobotics.sdk.commands.cartesian.LinearInterpolationCommand.LinearInterpolationCommand(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.main(), com.neuronrobotics.bowlerstudio.physics.TransformFactory.nrToAffine(), com.neuronrobotics.bowlerstudio.physics.TransformFactory.nrToBullet(), com.neuronrobotics.bowlerstudio.physics.TransformFactory.nrToCSG(), com.neuronrobotics.bowlerkernel.Bezier3d.manipulation.performMove(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.scale(), com.neuronrobotics.bowlerstudio.physics.TransformFactory.scale(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.translateX(), and com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.update().
getXml()
String com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getXml ()
Gets the xml.
Returns
the xml
Definition at line 457 of file TransformNR.java.
References com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getRotation(), com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.getRotationMatrix2QuaturnionW(), com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.getRotationMatrix2QuaturnionX(), com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.getRotationMatrix2QuaturnionY(), com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.getRotationMatrix2QuaturnionZ(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getX(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getY(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getZ(), and com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.setRotation().
Referenced by com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getEmbedableXml(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.getEmbedableXml(), and com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getXml().
getY()
double com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getY ()
Gets the y.
Returns
the y
Definition at line 138 of file TransformNR.java.
References com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.y.
Referenced by com.neuronrobotics.bowlerstudio.printbed.PrintBedObject.checkBounds(), com.neuronrobotics.replicator.driver.delta.DeltaRobotKinematics.delta_calcInverse(), com.neuronrobotics.sdk.addons.kinematics.WalkingDriveEngine.DriveArc(), com.neuronrobotics.sdk.addons.kinematics.DHChain.getInverseSolver(), com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getJacobian(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getMatrixTransform(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getOffsetVectorMagnitude(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getPositionArray(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getXml(), com.neuronrobotics.bowlerkernel.Bezier3d.CartesianManipulator.getY(), com.neuronrobotics.bowlerstudio.printbed.PrintBedObject.getY(), com.neuronrobotics.sdk.addons.kinematics.ik.DeltaIKModel.inverseKinematics6dof(), com.neuronrobotics.sdk.commands.cartesian.LinearInterpolationCommand.LinearInterpolationCommand(), com.neuronrobotics.bowlerstudio.physics.TransformFactory.nrToAffine(), com.neuronrobotics.bowlerstudio.physics.TransformFactory.nrToBullet(), com.neuronrobotics.bowlerstudio.physics.TransformFactory.nrToCSG(), com.neuronrobotics.bowlerkernel.Bezier3d.manipulation.performMove(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.scale(), com.neuronrobotics.bowlerstudio.physics.TransformFactory.scale(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.translateY(), com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.update(), and com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.updateLines().
getZ()
double com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getZ ()
Gets the z.
Returns
the z
Definition at line 147 of file TransformNR.java.
References com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.z.
Referenced by com.neuronrobotics.bowlerstudio.printbed.PrintBedObject.checkBounds(), com.neuronrobotics.replicator.driver.delta.DeltaRobotKinematics.delta_calcInverse(), com.neuronrobotics.sdk.addons.kinematics.WalkingDriveEngine.DriveArc(), com.neuronrobotics.sdk.addons.kinematics.DHChain.getInverseSolver(), com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getJacobian(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getMatrixTransform(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getOffsetVectorMagnitude(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getPositionArray(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getXml(), com.neuronrobotics.bowlerkernel.Bezier3d.CartesianManipulator.getZ(), com.neuronrobotics.bowlerstudio.printbed.PrintBedObject.getZ(), com.neuronrobotics.sdk.addons.kinematics.ik.DeltaIKModel.inverseKinematics6dof(), com.neuronrobotics.sdk.commands.cartesian.LinearInterpolationCommand.LinearInterpolationCommand(), com.neuronrobotics.bowlerstudio.physics.TransformFactory.nrToAffine(), com.neuronrobotics.bowlerstudio.physics.TransformFactory.nrToBullet(), com.neuronrobotics.bowlerstudio.physics.TransformFactory.nrToCSG(), com.neuronrobotics.bowlerkernel.Bezier3d.manipulation.performMove(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.scale(), com.neuronrobotics.bowlerstudio.physics.TransformFactory.scale(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.translateZ(), com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.update(), and com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.updateLines().
inverse()
TransformNR com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.inverse ()
Inverse.
Returns
the transform nr
Definition at line 320 of file TransformNR.java.
References com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getMatrixTransform(), and com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.TransformNR().
Referenced by com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.compute(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getDeltaToTarget(), and com.neuronrobotics.sdk.addons.kinematics.ik.DeltaIKModel.inverseKinematics6dof().
removeChangeListener()
void com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.removeChangeListener (ITransformNRChangeListener l)
Definition at line 491 of file TransformNR.java.
References com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getListeners().
Referenced by com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setCenterOfMassFromCentroid(), and com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setimuFromCentroid().
scale() [1/2]
TransformNR com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.scale (BigDecimal scale)
Scale.
Parameters
scale the scale
Returns
the transform nr
Definition at line 330 of file TransformNR.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getTipAlongTrajectory().
scale() [2/2]
TransformNR com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.scale (double t)
Scale.
Parameters
t the scale from 0 to 1.0
Returns
the transform nr
Definition at line 340 of file TransformNR.java.
References com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getRotation(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getX(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getY(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getZ(), and com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.TransformNR().
set()
TransformNR com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.set (double tx, double ty, double tz, double poseRot[][])
Definition at line 394 of file TransformNR.java.
References com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getRotation(), com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.set(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.x, com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.y, and com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.z.
Referenced by com.neuronrobotics.bowlerstudio.physics.TransformFactory.affineToNr().
setAzimuthDegrees()
void com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.setAzimuthDegrees (double newAngleDegrees)
Definition at line 553 of file TransformNR.java.
References com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getRotation(), and com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.setRotation().
setElevationDegrees()
void com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.setElevationDegrees (double newAngleDegrees)
Definition at line 536 of file TransformNR.java.
References com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getRotation(), and com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.setRotation().
setRotation()
TransformNR com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.setRotation (RotationNR rotation)
Sets the rotation.
Parameters
rotation the new rotation
Definition at line 480 of file TransformNR.java.
References com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.rotation.
Referenced by com.neuronrobotics.sdk.addons.kinematics.WalkingDriveEngine.DriveArc(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getXml(), com.neuronrobotics.bowlerkernel.Bezier3d.manipulation.performMove(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.setAzimuthDegrees(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.setElevationDegrees(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.setTiltDegrees(), and com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.TransformNR().
setTiltDegrees()
void com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.setTiltDegrees (double newAngleDegrees)
Definition at line 517 of file TransformNR.java.
References com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getRotation(), and com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.setRotation().
setX()
TransformNR com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.setX (double tx)
Sets the x.
Parameters
tx the new x
Definition at line 414 of file TransformNR.java.
References com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.x.
Referenced by com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.BezierEditor(), com.neuronrobotics.bowlerkernel.Bezier3d.manipulation.mouseRelease(), com.neuronrobotics.bowlerkernel.Bezier3d.manipulation.performMove(), com.neuronrobotics.bowlerkernel.Bezier3d.manipulation.set(), com.neuronrobotics.bowlerkernel.Bezier3d.manipulation.setGlobal(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.TransformNR(), and com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.translateX().
setY()
TransformNR com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.setY (double ty)
Sets the y.
Parameters
ty the new y
Definition at line 427 of file TransformNR.java.
References com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.y.
Referenced by com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.BezierEditor(), com.neuronrobotics.bowlerkernel.Bezier3d.manipulation.mouseRelease(), com.neuronrobotics.bowlerkernel.Bezier3d.manipulation.performMove(), com.neuronrobotics.bowlerkernel.Bezier3d.manipulation.set(), com.neuronrobotics.bowlerkernel.Bezier3d.manipulation.setGlobal(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.TransformNR(), and com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.translateY().
setZ()
TransformNR com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.setZ (double tz)
Sets the z.
Parameters
tz the new z
Definition at line 440 of file TransformNR.java.
References com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.z.
Referenced by com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.BezierEditor(), com.neuronrobotics.bowlerkernel.Bezier3d.manipulation.mouseRelease(), com.neuronrobotics.bowlerkernel.Bezier3d.manipulation.performMove(), com.neuronrobotics.bowlerkernel.Bezier3d.manipulation.set(), com.neuronrobotics.bowlerkernel.Bezier3d.manipulation.setGlobal(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.TransformNR(), and com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.translateZ().
times()
TransformNR com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.times (TransformNR t)
Times.
Parameters
t the t
Returns
the transform nr
Definition at line 196 of file TransformNR.java.
References com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getMatrixTransform(), and com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.TransformNR().
Referenced by com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.eulerFix(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getDeltaToTarget(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.getTipAlongTrajectory(), com.neuronrobotics.sdk.addons.kinematics.ik.DeltaIKModel.inverseKinematics6dof(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.main(), com.neuronrobotics.bowlerkernel.Bezier3d.manipulation.performMove(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.pose(), com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.update(), and com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.updateLines().
toString()
String com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.toString ()
Definition at line 206 of file TransformNR.java.
References com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getMatrixString(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getMatrixTransform(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getRotation(), and com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.toString().
Referenced by com.neuronrobotics.sdk.addons.kinematics.SearchTreeSolver.configuration.toString().
translateX()
TransformNR com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.translateX (double translation)
Translate x.
Parameters
translation the translation
Returns
Definition at line 367 of file TransformNR.java.
References com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getX(), and com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.setX().
Referenced by com.neuronrobotics.bowlerstudio.printbed.PrintBedObject.checkBounds(), com.neuronrobotics.sdk.addons.kinematics.WalkingDriveEngine.DriveArc(), com.neuronrobotics.bowlerstudio.vitamins.VitaminBomManager.getCoMLocation(), com.neuronrobotics.sdk.addons.kinematics.ik.DeltaIKModel.inverseKinematics6dof(), com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager.loadCSGToPoints(), and com.neuronrobotics.sdk.addons.kinematics.MobileBase.main().
translateY()
TransformNR com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.translateY (double translation)
Translate y.
Parameters
translation the translation
Definition at line 377 of file TransformNR.java.
References com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getY(), and com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.setY().
Referenced by com.neuronrobotics.bowlerstudio.printbed.PrintBedObject.checkBounds(), com.neuronrobotics.sdk.addons.kinematics.WalkingDriveEngine.DriveArc(), com.neuronrobotics.bowlerstudio.vitamins.VitaminBomManager.getCoMLocation(), and com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager.loadCSGToPoints().
translateZ()
TransformNR com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.translateZ (double translation)
Translate z.
Parameters
translation the translation
Definition at line 388 of file TransformNR.java.
References com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getZ(), and com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.setZ().
Referenced by com.neuronrobotics.sdk.addons.kinematics.WalkingDriveEngine.DriveArc(), com.neuronrobotics.bowlerstudio.vitamins.VitaminBomManager.getCoMLocation(), com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager.loadCSGToPoints(), and com.neuronrobotics.bowlerstudio.physics.MobileBasePhysicsManager.MobileBasePhysicsManager().
Member Data Documentation
listeners
ArrayList<ITransformNRChangeListener> com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.listeners =null private
Definition at line 14 of file TransformNR.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.clearChangeListener(), and com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getListeners().
rotation
RotationNR com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.rotation private
The rotation.
Definition at line 25 of file TransformNR.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getMatrixTransform(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getRotation(), and com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.setRotation().
x
double com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.x private
The x.
Definition at line 16 of file TransformNR.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getOffsetOrentationMagnitude(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getOffsetVectorMagnitude(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getX(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.set(), and com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.setX().
y
double com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.y private
The y.
Definition at line 19 of file TransformNR.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getOffsetOrentationMagnitude(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getOffsetVectorMagnitude(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getY(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.set(), and com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.setY().
z
double com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.z private
The z.
Definition at line 22 of file TransformNR.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getOffsetOrentationMagnitude(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getOffsetVectorMagnitude(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getZ(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.set(), and com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.setZ().
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/addons/kinematics/math/TransformNR.java