BowlerKernel: com.neuronrobotics.bowlerstudio.scripting.GitTimeoutThread Class Reference
com.neuronrobotics.bowlerstudio.scripting.GitTimeoutThread Class Reference
Public Member Functions
GitTimeoutThread (Git g)
void run ()
void resetTimer ()
RuntimeException getException ()
Private Member Functions
void setException (RuntimeException ex)
Private Attributes
RuntimeException ex
Detailed Description
Definition at line 7 of file GitTimeoutThread.java.
Constructor & Destructor Documentation
GitTimeoutThread()
com.neuronrobotics.bowlerstudio.scripting.GitTimeoutThread.GitTimeoutThread (Git g)
Definition at line 12 of file GitTimeoutThread.java.
References com.neuronrobotics.bowlerstudio.scripting.GitTimeoutThread.setException().
Member Function Documentation
getException()
RuntimeException com.neuronrobotics.bowlerstudio.scripting.GitTimeoutThread.getException ()
Definition at line 34 of file GitTimeoutThread.java.
References com.neuronrobotics.bowlerstudio.scripting.GitTimeoutThread.ex.
Referenced by com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.openGit(), com.neuronrobotics.bowlerstudio.scripting.GitTimeoutThread.run(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.waitForRepo().
resetTimer()
void com.neuronrobotics.bowlerstudio.scripting.GitTimeoutThread.resetTimer ()
Definition at line 31 of file GitTimeoutThread.java.
Referenced by com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getProgressMoniter(), and com.neuronrobotics.bowlerstudio.scripting.GitTimeoutThread.run().
run()
void com.neuronrobotics.bowlerstudio.scripting.GitTimeoutThread.run ()
Definition at line 19 of file GitTimeoutThread.java.
References com.neuronrobotics.bowlerstudio.scripting.GitTimeoutThread.getException(), com.neuronrobotics.bowlerstudio.scripting.GitTimeoutThread.resetTimer(), and com.neuronrobotics.bowlerstudio.IssueReportingExceptionHandler.uncaughtException().
setException()
void com.neuronrobotics.bowlerstudio.scripting.GitTimeoutThread.setException (RuntimeException ex) private
Definition at line 37 of file GitTimeoutThread.java.
References com.neuronrobotics.bowlerstudio.scripting.GitTimeoutThread.ex.
Referenced by com.neuronrobotics.bowlerstudio.scripting.GitTimeoutThread.GitTimeoutThread().
Member Data Documentation
ex
RuntimeException com.neuronrobotics.bowlerstudio.scripting.GitTimeoutThread.ex private
Definition at line 10 of file GitTimeoutThread.java.
Referenced by com.neuronrobotics.bowlerstudio.scripting.GitTimeoutThread.getException(), and com.neuronrobotics.bowlerstudio.scripting.GitTimeoutThread.setException().
The documentation for this class was generated from the following file:
src/main/java/com/neuronrobotics/bowlerstudio/scripting/GitTimeoutThread.java