BowlerKernel: com.neuronrobotics.sdk.util.ThreadUtil Class Reference
com.neuronrobotics.sdk.util.ThreadUtil Class Reference
Static Public Member Functions
static void wait (int time)
static void wait (int time0, int time1)
Detailed Description
The Class ThreadUtil.
Definition at line 7 of file ThreadUtil.java.
Member Function Documentation
wait() [1/2]
static void com.neuronrobotics.sdk.util.ThreadUtil.wait (int time) static
Wait.
Parameters
time the time
Definition at line 14 of file ThreadUtil.java.
Referenced by com.neuronrobotics.sdk.common.DeviceManager.addConnection(), com.neuronrobotics.bowlerstudio.sequence.TimeSequence.addWavFileRun(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.blockingInterpolatedMove(), com.neuronrobotics.bowlerstudio.physics.PhysicsCore.clear(), com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.connectDeviceImp(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.copyGitFile(), com.neuronrobotics.sdk.addons.kinematics.WalkingDriveEngine.DriveArc(), com.neuronrobotics.sdk.bowlercam.device.BowlerCamDevice.getHighSpeedImage(), com.neuronrobotics.sdk.dyio.sequencer.SequencerWAV.main(), com.neuronrobotics.bowlerstudio.physics.MobileBasePhysicsManager.MobileBasePhysicsManager(), com.neuronrobotics.sdk.ui.UsbConnectionPanel.onDeviceEvent(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.openGit(), com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.play(), com.neuronrobotics.sdk.network.BowlerTCPClient.reconnect(), com.neuronrobotics.sdk.common.BowlerAbstractConnection.QueueManager.run(), com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.SchedulerThread.run(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.runHome(), com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.runLine(), com.neuronrobotics.sdk.common.BowlerAbstractConnection.send(), com.neuronrobotics.sdk.common.BowlerAbstractConnection.sendSynchronusly(), com.neuronrobotics.bowlerstudio.physics.PhysicsCore.startPhysicsThread(), com.neuronrobotics.sdk.dyio.DyIO.validateChannel(), com.neuronrobotics.sdk.common.BowlerAbstractConnection.waitForConnectioToBeReady(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.waitForRepo(), com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.write(), and com.neuronrobotics.sdk.dyio.peripherals.SPIChannel.write().
wait() [2/2]
static void com.neuronrobotics.sdk.util.ThreadUtil.wait (int time0, int time1) static
Wait.
Parameters
time0 the time0
time1 the time1
Definition at line 24 of file ThreadUtil.java.
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/util/ThreadUtil.java