BowlerKernel: com.neuronrobotics.sdk.addons.kinematics.GradiantDecentNode Class Reference
com.neuronrobotics.sdk.addons.kinematics.GradiantDecentNode Class Reference
Public Member Functions
GradiantDecentNode (DHChain chain, int index, double[] jointSpaceVector, TransformNR cartesianSpace, double u, double l)
boolean stepOrent ()
boolean stepLin ()
boolean step ()
void jitter ()
void setIndex (int index)
int getIndex ()
Private Attributes
int index
final DHChain chain
Detailed Description
The Class GradiantDecentNode.
Definition at line 10 of file GradiantDecentNode.java.
Constructor & Destructor Documentation
GradiantDecentNode()
com.neuronrobotics.sdk.addons.kinematics.GradiantDecentNode.GradiantDecentNode (DHChain chain, int index, double[] jointSpaceVector, TransformNR cartesianSpace, double u, double l)
Instantiates a new gradiant decent node.
Parameters
chain the chain
index the index
jointSpaceVector the joint space vector
cartesianSpace the cartesian space
u the u
l the l
Definition at line 80 of file GradiantDecentNode.java.
References com.neuronrobotics.sdk.addons.kinematics.GradiantDecentNode.chain, com.neuronrobotics.sdk.addons.kinematics.GradiantDecentNode.index, and com.neuronrobotics.sdk.addons.kinematics.GradiantDecentNode.setIndex().
Member Function Documentation
getIndex()
int com.neuronrobotics.sdk.addons.kinematics.GradiantDecentNode.getIndex ()
Gets the index.
Returns
the index
Definition at line 268 of file GradiantDecentNode.java.
References com.neuronrobotics.sdk.addons.kinematics.GradiantDecentNode.index.
Referenced by com.neuronrobotics.sdk.addons.kinematics.GradiantDecentNode.jitter(), com.neuronrobotics.sdk.addons.kinematics.GradiantDecentNode.stepLin(), and com.neuronrobotics.sdk.addons.kinematics.GradiantDecentNode.stepOrent().
jitter()
void com.neuronrobotics.sdk.addons.kinematics.GradiantDecentNode.jitter ()
Jitter.
Definition at line 228 of file GradiantDecentNode.java.
References com.neuronrobotics.sdk.addons.kinematics.GradiantDecentNode.getIndex().
Referenced by com.neuronrobotics.sdk.addons.kinematics.GradiantDecent.inverseKinematics().
setIndex()
void com.neuronrobotics.sdk.addons.kinematics.GradiantDecentNode.setIndex (int index)
Sets the index.
Parameters
index the new index
Definition at line 259 of file GradiantDecentNode.java.
References com.neuronrobotics.sdk.addons.kinematics.GradiantDecentNode.index.
Referenced by com.neuronrobotics.sdk.addons.kinematics.GradiantDecentNode.GradiantDecentNode().
step()
boolean com.neuronrobotics.sdk.addons.kinematics.GradiantDecentNode.step ()
Step.
Returns
true, if successful
Definition at line 220 of file GradiantDecentNode.java.
References com.neuronrobotics.sdk.addons.kinematics.GradiantDecentNode.stepLin(), and com.neuronrobotics.sdk.addons.kinematics.GradiantDecentNode.stepOrent().
Referenced by com.neuronrobotics.sdk.addons.kinematics.GradiantDecent.inverseKinematics().
stepLin()
boolean com.neuronrobotics.sdk.addons.kinematics.GradiantDecentNode.stepLin ()
Step lin.
Returns
true, if successful
Definition at line 160 of file GradiantDecentNode.java.
References com.neuronrobotics.sdk.addons.kinematics.GradiantDecentNode.chain, com.neuronrobotics.sdk.addons.kinematics.DHChain.forwardKinematics(), com.neuronrobotics.sdk.addons.kinematics.GradiantDecentNode.getIndex(), and com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getOffsetVectorMagnitude().
Referenced by com.neuronrobotics.sdk.addons.kinematics.GradiantDecentNode.step().
stepOrent()
boolean com.neuronrobotics.sdk.addons.kinematics.GradiantDecentNode.stepOrent ()
Step orent.
Returns
true, if successful
Definition at line 100 of file GradiantDecentNode.java.
References com.neuronrobotics.sdk.addons.kinematics.GradiantDecentNode.chain, com.neuronrobotics.sdk.addons.kinematics.DHChain.forwardKinematics(), com.neuronrobotics.sdk.addons.kinematics.GradiantDecentNode.getIndex(), and com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getOffsetOrentationMagnitude().
Referenced by com.neuronrobotics.sdk.addons.kinematics.GradiantDecentNode.step().
Member Data Documentation
chain
final DHChain com.neuronrobotics.sdk.addons.kinematics.GradiantDecentNode.chain private
The chain.
Definition at line 34 of file GradiantDecentNode.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.GradiantDecentNode.GradiantDecentNode(), com.neuronrobotics.sdk.addons.kinematics.GradiantDecentNode.stepLin(), and com.neuronrobotics.sdk.addons.kinematics.GradiantDecentNode.stepOrent().
index
int com.neuronrobotics.sdk.addons.kinematics.GradiantDecentNode.index private
The index.
Definition at line 16 of file GradiantDecentNode.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.GradiantDecentNode.getIndex(), com.neuronrobotics.sdk.addons.kinematics.GradiantDecentNode.GradiantDecentNode(), and com.neuronrobotics.sdk.addons.kinematics.GradiantDecentNode.setIndex().
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/addons/kinematics/GradiantDecentNode.java