BowlerKernel: com.neuronrobotics.sdk.bootloader.IntelHexParser Class Reference
com.neuronrobotics.sdk.bootloader.IntelHexParser Class Reference
Public Member Functions
IntelHexParser (ArrayList< hexLine > lines, NRBootCoreType type) throws IOException
int size ()
ByteData getNext ()
Static Public Member Functions
static String hex (long n)
Private Member Functions
void checkAddressValidity (long currentAddress, NRBootCoreType type)
Private Attributes
long highAddress =0
long dataIndex =0
long base = 0x1D00A000L
long head = 0x1D01FFFFL
Detailed Description
The Class IntelHexParser.
Author
hephaestus
Definition at line 17 of file IntelHexParser.java.
Constructor & Destructor Documentation
IntelHexParser()
com.neuronrobotics.sdk.bootloader.IntelHexParser.IntelHexParser (ArrayList< hexLine > lines, NRBootCoreType type) throws IOException
Instantiates a new intel hex parser.
Parameters
lines the lines
type the type
Exceptions
IOException Signals that an I/O exception has occurred.
Definition at line 70 of file IntelHexParser.java.
References com.neuronrobotics.sdk.bootloader.NRBootCoreType.AVRxx4p, com.neuronrobotics.sdk.bootloader.IntelHexParser.checkAddressValidity(), com.neuronrobotics.sdk.common.ByteList.convertToInt(), com.neuronrobotics.sdk.bootloader.ByteData.getData(), com.neuronrobotics.sdk.bootloader.hexLine.getDataBytes(), com.neuronrobotics.sdk.bootloader.hexLine.getEndAddress(), com.neuronrobotics.sdk.bootloader.IntelHexParser.highAddress, com.neuronrobotics.sdk.bootloader.NRBootCoreType.PIC32, and com.neuronrobotics.sdk.bootloader.ByteData.setData().
Member Function Documentation
checkAddressValidity()
void com.neuronrobotics.sdk.bootloader.IntelHexParser.checkAddressValidity (long currentAddress, NRBootCoreType type) private
Check address validity.
Parameters
currentAddress the current address
type the type
Definition at line 51 of file IntelHexParser.java.
References com.neuronrobotics.sdk.bootloader.IntelHexParser.base, com.neuronrobotics.sdk.bootloader.IntelHexParser.head, com.neuronrobotics.sdk.bootloader.IntelHexParser.hex(), and com.neuronrobotics.sdk.bootloader.NRBootCoreType.PIC32.
Referenced by com.neuronrobotics.sdk.bootloader.IntelHexParser.IntelHexParser().
getNext()
ByteData com.neuronrobotics.sdk.bootloader.IntelHexParser.getNext ()
Gets the next.
Returns
the next
Definition at line 139 of file IntelHexParser.java.
References com.neuronrobotics.sdk.bootloader.IntelHexParser.dataIndex.
Referenced by com.neuronrobotics.sdk.bootloader.NRBoot.send().
hex()
static String com.neuronrobotics.sdk.bootloader.IntelHexParser.hex (long n) static
Hex.
Parameters
n the n
Returns
the string
Definition at line 40 of file IntelHexParser.java.
Referenced by com.neuronrobotics.sdk.bootloader.IntelHexParser.checkAddressValidity().
size()
int com.neuronrobotics.sdk.bootloader.IntelHexParser.size ()
Size.
Returns
the int
Definition at line 130 of file IntelHexParser.java.
Referenced by com.neuronrobotics.sdk.bootloader.NRBoot.CoreLoader.CoreLoader().
Member Data Documentation
base
long com.neuronrobotics.sdk.bootloader.IntelHexParser.base = 0x1D00A000L private
The base.
Definition at line 29 of file IntelHexParser.java.
Referenced by com.neuronrobotics.sdk.bootloader.IntelHexParser.checkAddressValidity().
dataIndex
long com.neuronrobotics.sdk.bootloader.IntelHexParser.dataIndex =0 private
The data index.
Definition at line 26 of file IntelHexParser.java.
Referenced by com.neuronrobotics.sdk.bootloader.IntelHexParser.getNext().
head
long com.neuronrobotics.sdk.bootloader.IntelHexParser.head = 0x1D01FFFFL private
The head.
Definition at line 32 of file IntelHexParser.java.
Referenced by com.neuronrobotics.sdk.bootloader.IntelHexParser.checkAddressValidity().
highAddress
long com.neuronrobotics.sdk.bootloader.IntelHexParser.highAddress =0 private
The high address.
Definition at line 20 of file IntelHexParser.java.
Referenced by com.neuronrobotics.sdk.bootloader.IntelHexParser.IntelHexParser().
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/bootloader/IntelHexParser.java