BowlerKernel: com.neuronrobotics.bowlerkernel.djl.UniquePerson Class Reference
com.neuronrobotics.bowlerkernel.djl.UniquePerson Class Reference
Public Attributes
long UUID =1
String name =""
ArrayList< float[]> features =new ArrayList<float[]>()
String referenceImageLocation
long timesSeen = 1
long time =System.currentTimeMillis()
Detailed Description
Definition at line 5 of file UniquePerson.java.
Member Data Documentation
features
ArrayList<float[]> com.neuronrobotics.bowlerkernel.djl.UniquePerson.features =new ArrayList<float[]>()
Definition at line 8 of file UniquePerson.java.
Referenced by com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.processBlocking(), and com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.processMemory().
name
String com.neuronrobotics.bowlerkernel.djl.UniquePerson.name =""
Definition at line 7 of file UniquePerson.java.
Referenced by com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.processBlocking(), com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.processMemory(), and com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.setAction().
referenceImageLocation
String com.neuronrobotics.bowlerkernel.djl.UniquePerson.referenceImageLocation
Definition at line 9 of file UniquePerson.java.
Referenced by com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.processBlocking().
time
long com.neuronrobotics.bowlerkernel.djl.UniquePerson.time =System.currentTimeMillis()
Definition at line 11 of file UniquePerson.java.
Referenced by com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.processBlocking(), and com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.processMemory().
timesSeen
long com.neuronrobotics.bowlerkernel.djl.UniquePerson.timesSeen = 1
Definition at line 10 of file UniquePerson.java.
Referenced by com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.processBlocking(), and com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.processMemory().
UUID
long com.neuronrobotics.bowlerkernel.djl.UniquePerson.UUID =1
Definition at line 6 of file UniquePerson.java.
Referenced by com.neuronrobotics.bowlerkernel.djl.UniquePersonFactory.processBlocking().
The documentation for this class was generated from the following file:
src/main/java/com/neuronrobotics/bowlerkernel/djl/UniquePerson.java