BowlerKernel: com.neuronrobotics.bowlerstudio.scripting.JythonHelper Class Reference
com.neuronrobotics.bowlerstudio.scripting.JythonHelper Class Reference
Public Member Functions
Object inlineScriptRun (String code, ArrayList< Object > args)
Object inlineScriptRun (File code, ArrayList< Object > args)
String getShellType ()
String getDefaultContents ()
boolean getIsTextFile ()
ArrayList< String > getFileExtenetion ()
Public Member Functions inherited from com.neuronrobotics.bowlerstudio.scripting.IScriptingLanguage
default boolean isSupportedFileExtenetion (String filename)
default String getDefaultContents (String gitURL, String fileSlug)
Detailed Description
Definition at line 21 of file JythonHelper.java.
Member Function Documentation
getDefaultContents()
String com.neuronrobotics.bowlerstudio.scripting.JythonHelper.getDefaultContents ()
Get the contents of an empty file
Returns
Implements com.neuronrobotics.bowlerstudio.scripting.IScriptingLanguage.
Definition at line 101 of file JythonHelper.java.
getFileExtenetion()
ArrayList<String> com.neuronrobotics.bowlerstudio.scripting.JythonHelper.getFileExtenetion ()
Returns the list of supported file extentions Convention is to provide just the leters that make up the file extention
Implements com.neuronrobotics.bowlerstudio.scripting.IScriptingLanguage.
Definition at line 111 of file JythonHelper.java.
getIsTextFile()
boolean com.neuronrobotics.bowlerstudio.scripting.JythonHelper.getIsTextFile ()
This function returns if this is a binary file or a text file
Returns
true if the file is a text file.
Implements com.neuronrobotics.bowlerstudio.scripting.IScriptingLanguage.
Definition at line 105 of file JythonHelper.java.
getShellType()
String com.neuronrobotics.bowlerstudio.scripting.JythonHelper.getShellType ()
Returns the HashMap key for this language
Implements com.neuronrobotics.bowlerstudio.scripting.IScriptingLanguage.
Definition at line 93 of file JythonHelper.java.
inlineScriptRun() [1/2]
Object com.neuronrobotics.bowlerstudio.scripting.JythonHelper.inlineScriptRun (File code, ArrayList< Object > args)
This interface is for adding additional language support.
Parameters
code file content of the code to be executed
args the incoming arguments as a list of objects
Returns
the objects returned form the code that ran
Implements com.neuronrobotics.bowlerstudio.scripting.IScriptingLanguage.
Definition at line 78 of file JythonHelper.java.
References com.neuronrobotics.bowlerstudio.scripting.JythonHelper.inlineScriptRun().
inlineScriptRun() [2/2]
Object com.neuronrobotics.bowlerstudio.scripting.JythonHelper.inlineScriptRun (String code, ArrayList< Object > args)
This interface is for adding additional language support.
Parameters
code the text content of the code to be executed
args the incoming arguments as a list of objects
Returns
the objects returned form the code that ran
Implements com.neuronrobotics.bowlerstudio.scripting.IScriptingLanguage.
Definition at line 27 of file JythonHelper.java.
References com.neuronrobotics.sdk.common.Log.debug().
Referenced by com.neuronrobotics.bowlerstudio.scripting.JythonHelper.inlineScriptRun().
The documentation for this class was generated from the following file:
src/main/java/com/neuronrobotics/bowlerstudio/scripting/JythonHelper.java