BowlerKernel: com.neuronrobotics.sdk.addons.kinematics.math.RotationNR Class Reference
com.neuronrobotics.sdk.addons.kinematics.math.RotationNR Class Reference
Public Member Functions
RotationNR ()
RotationNR (Rotation store)
RotationNR (double tilt, double azumeth, double elevation)
RotationNR (double[][] rotationMatrix)
RotationNR (double[] values)
RotationNR (double w, double x, double y, double z)
RotationNR (Matrix m)
double[][] getRotationMatrix ()
String toString ()
String toString (double[][] array)
double getRotationTilt ()
double getRotationElevation ()
double getRotationAzimuth ()
double getRotationMatrix2QuaturnionW ()
double getRotationMatrix2QuaturnionX ()
double getRotationMatrix2QuaturnionY ()
double getRotationMatrix2QuaturnionZ ()
Rotation getStorage ()
void setStorage (Rotation storage)
void set (double[][] poseRot)
Static Public Member Functions
static RotationNR getRotationX (double rotationAngleDegrees)
static RotationNR getRotationY (double rotationAngleDegrees)
static RotationNR getRotationZ (double rotationAngleDegrees)
static boolean bound (double low, double high, double n)
static RotationOrder getOrder ()
static void setOrder (RotationOrder o)
static RotationConvention getConvention ()
static void setConvention (RotationConvention convention)
Protected Member Functions
void quaternion2RotationMatrix (double w, double x, double y, double z)
Private Member Functions
void loadRotations (double[][] rotM)
void loadFromAngles (double tilt, double azumeth, double elevation)
void simpilfyAngles (double[] angles)
double eulerFix (double offsetSize, int index)
double getAngle (int index)
Private Attributes
Rotation storage = new Rotation(1, 0, 0, 0, false)
Static Private Attributes
static RotationOrder order = RotationOrder.ZYX
static RotationConvention convention = RotationConvention.VECTOR_OPERATOR
Detailed Description
This class is to represent a 3x3 rotation sub-matrix This class also contains static methods for dealing with 3x3 rotations.
Author
Kevin Harrington
Definition at line 21 of file RotationNR.java.
Constructor & Destructor Documentation
RotationNR() [1/7]
com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.RotationNR ()
Null constructor forms a.
Definition at line 33 of file RotationNR.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.eulerFix(), com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.getRotationX(), com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.getRotationY(), and com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.getRotationZ().
RotationNR() [2/7]
com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.RotationNR (Rotation store)
Instatiate using the org.apache.commons.math3.geometry.euclidean.threed.Rotation .
Parameters
store A org.apache.commons.math3.geometry.euclidean.threed.Rotation instance
Definition at line 44 of file RotationNR.java.
References com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.storage.
RotationNR() [3/7]
com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.RotationNR (double tilt, double azumeth, double elevation)
Instantiates a new rotation nr.
Parameters
tilt the tilt
azumeth the azumeth
elevation the elevation
Definition at line 59 of file RotationNR.java.
References com.neuronrobotics.sdk.common.Log.error(), com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.getRotationMatrix2QuaturnionW(), com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.getRotationMatrix2QuaturnionX(), com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.getRotationMatrix2QuaturnionY(), com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.getRotationMatrix2QuaturnionZ(), and com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.loadFromAngles().
RotationNR() [4/7]
com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.RotationNR (double rotationMatrix[][])
Instantiates a new rotation nr.
Parameters
rotationMatrix the rotation matrix
Definition at line 85 of file RotationNR.java.
References com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.loadRotations().
RotationNR() [5/7]
com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.RotationNR (double[] values)
Instantiates a new rotation nr.
Parameters
values the values
Definition at line 95 of file RotationNR.java.
RotationNR() [6/7]
com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.RotationNR (double w, double x, double y, double z)
Instantiates a new rotation nr.
Parameters
w the w
x the x
y the y
z the z
Definition at line 193 of file RotationNR.java.
References com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.quaternion2RotationMatrix().
RotationNR() [7/7]
com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.RotationNR (Matrix m)
Instantiates a new rotation nr.
Parameters
m the m
Definition at line 203 of file RotationNR.java.
References com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.loadRotations().
Member Function Documentation
bound()
static boolean com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.bound (double low, double high, double n) static
Bound.
Parameters
low the low
high the high
n the n
Returns
true, if successful
Definition at line 314 of file RotationNR.java.
eulerFix()
double com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.eulerFix (double offsetSize, int index) private
Definition at line 360 of file RotationNR.java.
References com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.getConvention(), com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.getOrder(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getRotation(), com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.getStorage(), com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.RotationNR(), com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.simpilfyAngles(), and com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.times().
Referenced by com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.getAngle().
getAngle()
double com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.getAngle (int index) private
Definition at line 369 of file RotationNR.java.
References com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.eulerFix(), com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.getConvention(), com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.getOrder(), and com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.getStorage().
Referenced by com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.getRotationAzimuth(), com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.getRotationElevation(), and com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.getRotationTilt().
getConvention()
static RotationConvention com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.getConvention () static
Definition at line 428 of file RotationNR.java.
References com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.convention.
Referenced by com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.eulerFix(), com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.getAngle(), and com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.loadFromAngles().
getOrder()
static RotationOrder com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.getOrder () static
Definition at line 420 of file RotationNR.java.
References com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.order.
Referenced by com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.eulerFix(), com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.getAngle(), and com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.loadFromAngles().
getRotationAzimuth()
double com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.getRotationAzimuth ()
Gets the rotation azimuth.
Returns
the rotation azimuth
Definition at line 347 of file RotationNR.java.
References com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.getAngle().
Referenced by com.neuronrobotics.sdk.addons.kinematics.WalkingDriveEngine.DriveArc(), com.neuronrobotics.sdk.addons.kinematics.ik.DeltaIKModel.inverseKinematics6dof(), com.neuronrobotics.bowlerstudio.physics.TransformFactory.scale(), and com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.toString().
getRotationElevation()
double com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.getRotationElevation ()
Gets the rotation elevation.
Returns
the rotation elevation
Definition at line 337 of file RotationNR.java.
References com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.getAngle().
Referenced by com.neuronrobotics.sdk.addons.kinematics.WalkingDriveEngine.DriveArc(), com.neuronrobotics.bowlerstudio.physics.TransformFactory.scale(), and com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.toString().
getRotationMatrix()
double [][] com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.getRotationMatrix ()
Gets the rotation matrix.
Returns
the rotation matrix
Definition at line 235 of file RotationNR.java.
References com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.getStorage().
Referenced by com.neuronrobotics.sdk.addons.kinematics.GenericKinematicsModelNR.forwardKinematics(), com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getJacobian(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getRotationMatrixArray(), and com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getRotationValue().
getRotationMatrix2QuaturnionW()
double com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.getRotationMatrix2QuaturnionW ()
Gets the rotation matrix2 quaturnion w.
Returns
the rotation matrix2 quaturnion w
Definition at line 389 of file RotationNR.java.
References com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.getStorage().
Referenced by com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getXml(), com.neuronrobotics.bowlerstudio.physics.TransformFactory.nrToBullet(), com.neuronrobotics.bowlerstudio.physics.TransformFactory.nrToCSG(), com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.RotationNR(), and com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.toString().
getRotationMatrix2QuaturnionX()
double com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.getRotationMatrix2QuaturnionX ()
Gets the rotation matrix2 quaturnion x.
Returns
the rotation matrix2 quaturnion x
Definition at line 398 of file RotationNR.java.
References com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.getStorage().
Referenced by com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getOffsetOrentationMagnitude(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getXml(), com.neuronrobotics.bowlerstudio.physics.TransformFactory.nrToBullet(), com.neuronrobotics.bowlerstudio.physics.TransformFactory.nrToCSG(), com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.RotationNR(), com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.simpilfyAngles(), and com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.toString().
getRotationMatrix2QuaturnionY()
double com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.getRotationMatrix2QuaturnionY ()
Gets the rotation matrix2 quaturnion y.
Returns
the rotation matrix2 quaturnion y
Definition at line 407 of file RotationNR.java.
References com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.getStorage().
Referenced by com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getOffsetOrentationMagnitude(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getXml(), com.neuronrobotics.bowlerstudio.physics.TransformFactory.nrToBullet(), com.neuronrobotics.bowlerstudio.physics.TransformFactory.nrToCSG(), com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.RotationNR(), and com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.toString().
getRotationMatrix2QuaturnionZ()
double com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.getRotationMatrix2QuaturnionZ ()
Gets the rotation matrix2 quaturnion z.
Returns
the rotation matrix2 quaturnion z
Definition at line 416 of file RotationNR.java.
References com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.getStorage().
Referenced by com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getOffsetOrentationMagnitude(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getXml(), com.neuronrobotics.bowlerstudio.physics.TransformFactory.nrToBullet(), com.neuronrobotics.bowlerstudio.physics.TransformFactory.nrToCSG(), com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.RotationNR(), com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.simpilfyAngles(), and com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.toString().
getRotationTilt()
double com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.getRotationTilt ()
Gets the rotation tilt.
Returns
the rotation tilt
Definition at line 328 of file RotationNR.java.
References com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.getAngle().
Referenced by com.neuronrobotics.sdk.addons.kinematics.WalkingDriveEngine.DriveArc(), com.neuronrobotics.bowlerstudio.physics.TransformFactory.scale(), and com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.toString().
getRotationX()
static RotationNR com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.getRotationX (double rotationAngleDegrees) static
Get a rotation matrix with a rotation around X.
Parameters
rotationAngleDegrees in degrees
Returns
the static matrix
Definition at line 106 of file RotationNR.java.
References com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.RotationNR().
Referenced by com.neuronrobotics.sdk.addons.kinematics.GenericKinematicsModelNR.forwardKinematics().
getRotationY()
static RotationNR com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.getRotationY (double rotationAngleDegrees) static
Get a rotation matrix with a rotation around Y.
Parameters
rotationAngleDegrees in degrees
Returns
the static matrix
Definition at line 133 of file RotationNR.java.
References com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.RotationNR().
Referenced by com.neuronrobotics.sdk.addons.kinematics.GenericKinematicsModelNR.forwardKinematics().
getRotationZ()
static RotationNR com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.getRotationZ (double rotationAngleDegrees) static
Get a rotation matrix with a rotation around Z.
Parameters
rotationAngleDegrees in degrees
Returns
the static matrix
Definition at line 160 of file RotationNR.java.
References com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.RotationNR().
Referenced by com.neuronrobotics.sdk.addons.kinematics.GenericKinematicsModelNR.forwardKinematics().
getStorage()
Rotation com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.getStorage ()
Definition at line 436 of file RotationNR.java.
References com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.storage.
Referenced by com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.eulerFix(), com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.getAngle(), com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.getRotationMatrix(), com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.getRotationMatrix2QuaturnionW(), com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.getRotationMatrix2QuaturnionX(), com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.getRotationMatrix2QuaturnionY(), and com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.getRotationMatrix2QuaturnionZ().
loadFromAngles()
void com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.loadFromAngles (double tilt, double azumeth, double elevation) private
Definition at line 318 of file RotationNR.java.
References com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.getConvention(), com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.getOrder(), and com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.setStorage().
Referenced by com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.RotationNR().
loadRotations()
void com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.loadRotations (double rotM[][]) private
Load rotations.
Parameters
rotM the rot m
Definition at line 219 of file RotationNR.java.
References com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.setStorage().
Referenced by com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.RotationNR(), and com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.set().
quaternion2RotationMatrix()
void com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.quaternion2RotationMatrix (double w, double x, double y, double z) protected
Quaternion2 rotation matrix.
Parameters
w the w
x the x
y the y
z the z
Definition at line 291 of file RotationNR.java.
References com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.setStorage().
Referenced by com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.RotationNR().
set()
void com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.set (double poseRot[][])
Definition at line 444 of file RotationNR.java.
References com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.loadRotations().
Referenced by com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.set().
setConvention()
static void com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.setConvention (RotationConvention convention) static
Definition at line 432 of file RotationNR.java.
References com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.convention.
setOrder()
static void com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.setOrder (RotationOrder o) static
Definition at line 424 of file RotationNR.java.
References com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.order.
setStorage()
void com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.setStorage (Rotation storage)
Definition at line 440 of file RotationNR.java.
References com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.storage.
Referenced by com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.loadFromAngles(), com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.loadRotations(), and com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.quaternion2RotationMatrix().
simpilfyAngles()
void com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.simpilfyAngles (double[] angles) private
Definition at line 350 of file RotationNR.java.
References com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.getRotationMatrix2QuaturnionX(), and com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.getRotationMatrix2QuaturnionZ().
Referenced by com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.eulerFix().
toString() [1/2]
String com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.toString ()
Definition at line 246 of file RotationNR.java.
References com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.getRotationAzimuth(), com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.getRotationElevation(), com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.getRotationMatrix2QuaturnionW(), com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.getRotationMatrix2QuaturnionX(), com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.getRotationMatrix2QuaturnionY(), com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.getRotationMatrix2QuaturnionZ(), and com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.getRotationTilt().
Referenced by com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.toString().
toString() [2/2]
String com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.toString (double array[][])
To string.
Parameters
array the array
Returns
the string
Definition at line 266 of file RotationNR.java.
Member Data Documentation
convention
RotationConvention com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.convention = RotationConvention.VECTOR_OPERATOR static private
Definition at line 27 of file RotationNR.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.getConvention(), and com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.setConvention().
order
RotationOrder com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.order = RotationOrder.ZYX static private
Definition at line 26 of file RotationNR.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.getOrder(), and com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.setOrder().
storage
Rotation com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.storage = new Rotation(1, 0, 0, 0, false) private
The rotation matrix.
Definition at line 25 of file RotationNR.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.getStorage(), com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.RotationNR(), and com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.setStorage().
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/addons/kinematics/math/RotationNR.java