BowlerKernel: com.neuronrobotics.sdk.addons.kinematics.SearchTreeSolver Class Reference
com.neuronrobotics.sdk.addons.kinematics.SearchTreeSolver Class Reference
Classes
class configuration
class searchNode
class searchTree
Public Member Functions
SearchTreeSolver (DHChain dhChain, boolean debug)
double[] inverseKinematics (TransformNR target, double[] jointSpaceVector, DHChain chain)
TransformNR getTarget ()
void setTarget (TransformNR target)
DHChain getDhChain ()
void setDhChain (DHChain dhChain)
TransformNR fk (double[] jointSpaceVector)
Private Attributes
DHChain dhChain
double[] upper
double[] lower
boolean debug
TransformNR target
Detailed Description
The Class SearchTreeSolver.
Definition at line 11 of file SearchTreeSolver.java.
Constructor & Destructor Documentation
SearchTreeSolver()
com.neuronrobotics.sdk.addons.kinematics.SearchTreeSolver.SearchTreeSolver (DHChain dhChain, boolean debug)
Instantiates a new search tree solver.
Parameters
dhChain the dh chain
debug the debug
Definition at line 37 of file SearchTreeSolver.java.
References com.neuronrobotics.sdk.addons.kinematics.SearchTreeSolver.debug, com.neuronrobotics.sdk.addons.kinematics.SearchTreeSolver.dhChain, com.neuronrobotics.sdk.addons.kinematics.DHChain.getlowerLimits(), com.neuronrobotics.sdk.addons.kinematics.DHChain.getUpperLimits(), com.neuronrobotics.sdk.addons.kinematics.SearchTreeSolver.lower, com.neuronrobotics.sdk.addons.kinematics.SearchTreeSolver.setDhChain(), and com.neuronrobotics.sdk.addons.kinematics.SearchTreeSolver.upper.
Member Function Documentation
fk()
TransformNR com.neuronrobotics.sdk.addons.kinematics.SearchTreeSolver.fk (double[] jointSpaceVector)
Fk.
Parameters
jointSpaceVector the joint space vector
Returns
the transform nr
Definition at line 121 of file SearchTreeSolver.java.
References com.neuronrobotics.sdk.addons.kinematics.DHChain.forwardKinematics(), and com.neuronrobotics.sdk.addons.kinematics.SearchTreeSolver.getDhChain().
Referenced by com.neuronrobotics.sdk.addons.kinematics.SearchTreeSolver.configuration.getTransform().
getDhChain()
DHChain com.neuronrobotics.sdk.addons.kinematics.SearchTreeSolver.getDhChain ()
Gets the dh chain.
Returns
the dh chain
Definition at line 102 of file SearchTreeSolver.java.
References com.neuronrobotics.sdk.addons.kinematics.SearchTreeSolver.dhChain.
Referenced by com.neuronrobotics.sdk.addons.kinematics.SearchTreeSolver.fk().
getTarget()
TransformNR com.neuronrobotics.sdk.addons.kinematics.SearchTreeSolver.getTarget ()
Gets the target.
Returns
the target
Definition at line 84 of file SearchTreeSolver.java.
References com.neuronrobotics.sdk.addons.kinematics.SearchTreeSolver.target.
Referenced by com.neuronrobotics.sdk.addons.kinematics.SearchTreeSolver.searchTree.getBest().
inverseKinematics()
double [] com.neuronrobotics.sdk.addons.kinematics.SearchTreeSolver.inverseKinematics (TransformNR target, double[] jointSpaceVector, DHChain chain)
Inverse kinematics.
Parameters
target the target
jointSpaceVector the joint space vector
chain the chain
Returns
the double[]
Implements com.neuronrobotics.sdk.addons.kinematics.DhInverseSolver.
Definition at line 48 of file SearchTreeSolver.java.
References com.neuronrobotics.sdk.addons.kinematics.SearchTreeSolver.searchTree.getBest(), com.neuronrobotics.sdk.addons.kinematics.SearchTreeSolver.configuration.getJoints(), com.neuronrobotics.sdk.addons.kinematics.DHChain.getLinks(), com.neuronrobotics.sdk.addons.kinematics.SearchTreeSolver.configuration.getOffsetOrentationMagnitude(), com.neuronrobotics.sdk.addons.kinematics.SearchTreeSolver.configuration.getOffsetVectorMagnitude(), com.neuronrobotics.sdk.addons.kinematics.SearchTreeSolver.setTarget(), and com.neuronrobotics.sdk.addons.kinematics.SearchTreeSolver.target.
setDhChain()
void com.neuronrobotics.sdk.addons.kinematics.SearchTreeSolver.setDhChain (DHChain dhChain)
Sets the dh chain.
Parameters
dhChain the new dh chain
Definition at line 111 of file SearchTreeSolver.java.
References com.neuronrobotics.sdk.addons.kinematics.SearchTreeSolver.dhChain.
Referenced by com.neuronrobotics.sdk.addons.kinematics.SearchTreeSolver.SearchTreeSolver().
setTarget()
void com.neuronrobotics.sdk.addons.kinematics.SearchTreeSolver.setTarget (TransformNR target)
Sets the target.
Parameters
target the new target
Definition at line 93 of file SearchTreeSolver.java.
References com.neuronrobotics.sdk.addons.kinematics.SearchTreeSolver.target.
Referenced by com.neuronrobotics.sdk.addons.kinematics.SearchTreeSolver.inverseKinematics().
Member Data Documentation
debug
boolean com.neuronrobotics.sdk.addons.kinematics.SearchTreeSolver.debug private
The debug.
Definition at line 23 of file SearchTreeSolver.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.SearchTreeSolver.SearchTreeSolver().
dhChain
DHChain com.neuronrobotics.sdk.addons.kinematics.SearchTreeSolver.dhChain private
The dh chain.
Definition at line 14 of file SearchTreeSolver.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.SearchTreeSolver.getDhChain(), com.neuronrobotics.sdk.addons.kinematics.SearchTreeSolver.SearchTreeSolver(), and com.neuronrobotics.sdk.addons.kinematics.SearchTreeSolver.setDhChain().
lower
double [] com.neuronrobotics.sdk.addons.kinematics.SearchTreeSolver.lower private
The lower.
Definition at line 20 of file SearchTreeSolver.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.SearchTreeSolver.SearchTreeSolver().
target
TransformNR com.neuronrobotics.sdk.addons.kinematics.SearchTreeSolver.target private
The target.
Definition at line 29 of file SearchTreeSolver.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.SearchTreeSolver.getTarget(), com.neuronrobotics.sdk.addons.kinematics.SearchTreeSolver.inverseKinematics(), and com.neuronrobotics.sdk.addons.kinematics.SearchTreeSolver.setTarget().
upper
double [] com.neuronrobotics.sdk.addons.kinematics.SearchTreeSolver.upper private
The upper.
Definition at line 17 of file SearchTreeSolver.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.SearchTreeSolver.SearchTreeSolver().
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/addons/kinematics/SearchTreeSolver.java