BowlerKernel: com.neuronrobotics.bowlerstudio.printbed.PrintBedObject Class Reference
com.neuronrobotics.bowlerstudio.printbed.PrintBedObject Class Reference
Public Member Functions
PrintBedObject (String name, CSG part, double xMax, double xMin, double yMax, double yMin, TransformNR startPose)
void addEventListener (Runnable r)
void addSaveListener (Runnable r)
List< CSG > get ()
double getX ()
double getY ()
double getZ ()
void checkBounds ()
Private Attributes
double xMax
double xMin
double yMax
double yMin
CSG part
String name
manipulation manip
Affine affine = new Affine()
TransformNR globalPose
Detailed Description
Definition at line 13 of file PrintBedObject.java.
Constructor & Destructor Documentation
PrintBedObject()
com.neuronrobotics.bowlerstudio.printbed.PrintBedObject.PrintBedObject (String name, CSG part, double xMax, double xMin, double yMax, double yMin, TransformNR startPose)
Definition at line 23 of file PrintBedObject.java.
References com.neuronrobotics.bowlerkernel.Bezier3d.manipulation.addSaveListener(), com.neuronrobotics.bowlerstudio.printbed.PrintBedObject.affine, com.neuronrobotics.bowlerstudio.printbed.PrintBedObject.checkBounds(), com.neuronrobotics.bowlerstudio.printbed.PrintBedObject.manip, com.neuronrobotics.bowlerstudio.printbed.PrintBedObject.name, com.neuronrobotics.bowlerstudio.printbed.PrintBedObject.part, com.neuronrobotics.bowlerstudio.printbed.PrintBedObject.xMax, com.neuronrobotics.bowlerstudio.printbed.PrintBedObject.xMin, com.neuronrobotics.bowlerstudio.printbed.PrintBedObject.yMax, and com.neuronrobotics.bowlerstudio.printbed.PrintBedObject.yMin.
Member Function Documentation
addEventListener()
void com.neuronrobotics.bowlerstudio.printbed.PrintBedObject.addEventListener (Runnable r)
Definition at line 36 of file PrintBedObject.java.
References com.neuronrobotics.bowlerkernel.Bezier3d.manipulation.addEventListener(), and com.neuronrobotics.bowlerstudio.printbed.PrintBedObject.manip.
addSaveListener()
void com.neuronrobotics.bowlerstudio.printbed.PrintBedObject.addSaveListener (Runnable r)
Definition at line 40 of file PrintBedObject.java.
References com.neuronrobotics.bowlerkernel.Bezier3d.manipulation.addSaveListener(), and com.neuronrobotics.bowlerstudio.printbed.PrintBedObject.manip.
Referenced by com.neuronrobotics.bowlerstudio.printbed.PrintBedManager.init().
checkBounds()
void com.neuronrobotics.bowlerstudio.printbed.PrintBedObject.checkBounds ()
Definition at line 58 of file PrintBedObject.java.
References eu.mihosoft.vrl.v3d.CSG.getMaxX(), eu.mihosoft.vrl.v3d.CSG.getMaxY(), eu.mihosoft.vrl.v3d.CSG.getMinX(), eu.mihosoft.vrl.v3d.CSG.getMinY(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getX(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getY(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getZ(), com.neuronrobotics.bowlerstudio.printbed.PrintBedObject.globalPose, com.neuronrobotics.bowlerstudio.printbed.PrintBedObject.manip, com.neuronrobotics.bowlerstudio.printbed.PrintBedObject.part, com.neuronrobotics.bowlerkernel.Bezier3d.manipulation.set(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.translateX(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.translateY(), com.neuronrobotics.bowlerstudio.printbed.PrintBedObject.xMax, com.neuronrobotics.bowlerstudio.printbed.PrintBedObject.xMin, com.neuronrobotics.bowlerstudio.printbed.PrintBedObject.yMax, and com.neuronrobotics.bowlerstudio.printbed.PrintBedObject.yMin.
Referenced by com.neuronrobotics.bowlerstudio.printbed.PrintBedManager.init(), and com.neuronrobotics.bowlerstudio.printbed.PrintBedObject.PrintBedObject().
get()
List<CSG> com.neuronrobotics.bowlerstudio.printbed.PrintBedObject.get ()
Definition at line 43 of file PrintBedObject.java.
References com.neuronrobotics.bowlerstudio.printbed.PrintBedObject.part.
getX()
double com.neuronrobotics.bowlerstudio.printbed.PrintBedObject.getX ()
Definition at line 47 of file PrintBedObject.java.
References com.neuronrobotics.bowlerkernel.Bezier3d.manipulation.currentPose, com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getX(), and com.neuronrobotics.bowlerstudio.printbed.PrintBedObject.manip.
getY()
double com.neuronrobotics.bowlerstudio.printbed.PrintBedObject.getY ()
Definition at line 51 of file PrintBedObject.java.
References com.neuronrobotics.bowlerkernel.Bezier3d.manipulation.currentPose, com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getY(), and com.neuronrobotics.bowlerstudio.printbed.PrintBedObject.manip.
getZ()
double com.neuronrobotics.bowlerstudio.printbed.PrintBedObject.getZ ()
Definition at line 55 of file PrintBedObject.java.
References com.neuronrobotics.bowlerkernel.Bezier3d.manipulation.currentPose, com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getZ(), and com.neuronrobotics.bowlerstudio.printbed.PrintBedObject.manip.
Member Data Documentation
affine
Affine com.neuronrobotics.bowlerstudio.printbed.PrintBedObject.affine = new Affine() private
Definition at line 21 of file PrintBedObject.java.
Referenced by com.neuronrobotics.bowlerstudio.printbed.PrintBedObject.PrintBedObject().
globalPose
TransformNR com.neuronrobotics.bowlerstudio.printbed.PrintBedObject.globalPose private
Definition at line 22 of file PrintBedObject.java.
Referenced by com.neuronrobotics.bowlerstudio.printbed.PrintBedObject.checkBounds().
manip
manipulation com.neuronrobotics.bowlerstudio.printbed.PrintBedObject.manip private
Definition at line 20 of file PrintBedObject.java.
Referenced by com.neuronrobotics.bowlerstudio.printbed.PrintBedObject.addEventListener(), com.neuronrobotics.bowlerstudio.printbed.PrintBedObject.addSaveListener(), com.neuronrobotics.bowlerstudio.printbed.PrintBedObject.checkBounds(), com.neuronrobotics.bowlerstudio.printbed.PrintBedObject.getX(), com.neuronrobotics.bowlerstudio.printbed.PrintBedObject.getY(), com.neuronrobotics.bowlerstudio.printbed.PrintBedObject.getZ(), and com.neuronrobotics.bowlerstudio.printbed.PrintBedObject.PrintBedObject().
name
String com.neuronrobotics.bowlerstudio.printbed.PrintBedObject.name private
Definition at line 19 of file PrintBedObject.java.
Referenced by com.neuronrobotics.bowlerstudio.printbed.PrintBedObject.PrintBedObject().
part
CSG com.neuronrobotics.bowlerstudio.printbed.PrintBedObject.part private
Definition at line 18 of file PrintBedObject.java.
Referenced by com.neuronrobotics.bowlerstudio.printbed.PrintBedObject.checkBounds(), com.neuronrobotics.bowlerstudio.printbed.PrintBedObject.get(), and com.neuronrobotics.bowlerstudio.printbed.PrintBedObject.PrintBedObject().
xMax
double com.neuronrobotics.bowlerstudio.printbed.PrintBedObject.xMax private
Definition at line 14 of file PrintBedObject.java.
Referenced by com.neuronrobotics.bowlerstudio.printbed.PrintBedObject.checkBounds(), and com.neuronrobotics.bowlerstudio.printbed.PrintBedObject.PrintBedObject().
xMin
double com.neuronrobotics.bowlerstudio.printbed.PrintBedObject.xMin private
Definition at line 15 of file PrintBedObject.java.
Referenced by com.neuronrobotics.bowlerstudio.printbed.PrintBedObject.checkBounds(), and com.neuronrobotics.bowlerstudio.printbed.PrintBedObject.PrintBedObject().
yMax
double com.neuronrobotics.bowlerstudio.printbed.PrintBedObject.yMax private
Definition at line 16 of file PrintBedObject.java.
Referenced by com.neuronrobotics.bowlerstudio.printbed.PrintBedObject.checkBounds(), and com.neuronrobotics.bowlerstudio.printbed.PrintBedObject.PrintBedObject().
yMin
double com.neuronrobotics.bowlerstudio.printbed.PrintBedObject.yMin private
Definition at line 17 of file PrintBedObject.java.
Referenced by com.neuronrobotics.bowlerstudio.printbed.PrintBedObject.checkBounds(), and com.neuronrobotics.bowlerstudio.printbed.PrintBedObject.PrintBedObject().
The documentation for this class was generated from the following file:
src/main/java/com/neuronrobotics/bowlerstudio/printbed/PrintBedObject.java