BowlerKernel: com.neuronrobotics.sdk.dyio.DyIOOutputStream Class Reference
com.neuronrobotics.sdk.dyio.DyIOOutputStream Class Reference
Public Member Functions
DyIOOutputStream (DyIOChannel channel)
void write (ByteList bl) throws IOException
void write (int b) throws IOException
void write (byte[] b) throws IOException
void write (byte[] b, int off, int len) throws IOException
Detailed Description
The Class DyIOOutputStream.
Definition at line 26 of file DyIOOutputStream.java.
Constructor & Destructor Documentation
DyIOOutputStream()
com.neuronrobotics.sdk.dyio.DyIOOutputStream.DyIOOutputStream (DyIOChannel channel)
Instantiates a new dy io output stream.
Parameters
channel the channel
Definition at line 36 of file DyIOOutputStream.java.
Member Function Documentation
write() [1/4]
void com.neuronrobotics.sdk.dyio.DyIOOutputStream.write (byte[] b) throws IOException
Definition at line 80 of file DyIOOutputStream.java.
References com.neuronrobotics.sdk.dyio.DyIOOutputStream.write().
write() [2/4]
void com.neuronrobotics.sdk.dyio.DyIOOutputStream.write (byte[] b, int off, int len) throws IOException
Definition at line 88 of file DyIOOutputStream.java.
References com.neuronrobotics.sdk.dyio.DyIOOutputStream.write().
write() [3/4]
void com.neuronrobotics.sdk.dyio.DyIOOutputStream.write (ByteList bl) throws IOException
Writes bl to this output stream as a single packet verses individual writes for each byte.
Parameters
bl
the data
Exceptions
IOException
if an I/O error occurs.
Definition at line 49 of file DyIOOutputStream.java.
References com.neuronrobotics.sdk.dyio.DyIOChannel.getMode(), com.neuronrobotics.sdk.dyio.DyIOChannel.setValue(), and com.neuronrobotics.sdk.dyio.DyIOChannelMode.USART_TX.
Referenced by com.neuronrobotics.sdk.dyio.peripherals.UARTChannel.UARTTxChannel.putStream(), and com.neuronrobotics.sdk.dyio.DyIOOutputStream.write().
write() [4/4]
void com.neuronrobotics.sdk.dyio.DyIOOutputStream.write (int b) throws IOException
Definition at line 72 of file DyIOOutputStream.java.
References com.neuronrobotics.sdk.dyio.DyIOOutputStream.write().
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/dyio/DyIOOutputStream.java