BowlerKernel: com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeRotory Class Reference
com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeRotory Class Reference
Public Member Functions
GcodeRotory (LinkConfiguration conf, GcodeDevice device, String linkAxis)
void cacheTargetValueDevice ()
void flushDevice (double time)
void flushAllDevice (double time)
double getCurrentPosition ()
String getAxis ()
void setAxis (String axis)
double getValue ()
void setValue (double value)
Public Member Functions inherited from com.neuronrobotics.sdk.addons.kinematics.AbstractRotoryLink
AbstractRotoryLink (LinkConfiguration conf)
void incrementAngle (double inc)
void setTargetAngle (double pos)
void setCurrentAsAngle (double angle)
double getCurrentAngle ()
double getTargetAngle ()
double getMaxAngle ()
double getMinAngle ()
boolean isMaxAngle ()
boolean isMinAngle ()
Public Member Functions inherited from com.neuronrobotics.sdk.addons.kinematics.AbstractLink
double getDeviceMaximumValue ()
double getDeviceMinimumValue ()
void setDeviceMaximumValue (double max)
void setDeviceMinimumValue (double min)
double getDeviceMaxEngineeringUnits ()
double getDeviceMinEngineeringUnits ()
AbstractLink (LinkConfiguration conf)
void cacheTargetValue ()
void flush (double time)
void flushAll (double time)
double toEngineeringUnits (double value)
double toLinkUnits (double euValue)
void addLinkListener (ILinkListener l)
void removeLinkListener (ILinkListener l)
void fireLinkListener (double linkUnitsValue)
void fireLinkLimitEvent (PIDLimitEvent e)
void Home ()
void incrementEngineeringUnits (double inc)
void setTargetEngineeringUnits (double pos)
void setCurrentEngineeringUnits (double angle)
double getCurrentEngineeringUnits ()
double getTargetEngineeringUnits ()
double getMaxEngineeringUnits ()
double getMinEngineeringUnits ()
void setMinEngineeringUnits (double minLimit)
void setMaxEngineeringUnits (double maxLimit)
double getMaxVelocityEngineeringUnits ()
void setMaxVelocityEngineeringUnits (double max)
boolean isMaxEngineeringUnits ()
boolean isMinEngineeringUnits ()
double getTargetValue ()
void setUpperLimit (int upperLimit)
void setLowerLimit (int lowerLimit)
void setHome (int home)
void setScale (double d)
double getScale ()
double getUpperLimit ()
double getLowerLimit ()
double getHome ()
void setCurrentAsUpperLimit ()
void setCurrentAsLowerLimit ()
void setUseLimits (boolean useLimits)
boolean isUseLimits ()
void setLinkConfiguration (LinkConfiguration conf)
LinkConfiguration getLinkConfiguration ()
ArrayList< ILinkListener > getLinks ()
void setLinks (ArrayList< ILinkListener > links)
void removeAllLinkListener ()
void setGlobalPositionListener (Object Object)
Object getGlobalPositionListener ()
LinkFactory getSlaveFactory ()
void setSlaveFactory (LinkFactory slaveFactory)
IMU getImu ()
void addChangeListener (ILinkConfigurationChangeListener l)
void removeChangeListener (ILinkConfigurationChangeListener l)
void clearChangeListener ()
Private Member Functions
void loadCurrent ()
Private Attributes
GcodeDevice device
String axis = ""
double value =0
Additional Inherited Members
Protected Member Functions inherited from com.neuronrobotics.sdk.addons.kinematics.AbstractLink
void setPosition (double val)
void setTargetValue (double val)
Detailed Description
Definition at line 7 of file GcodeRotory.java.
Constructor & Destructor Documentation
GcodeRotory()
com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeRotory.GcodeRotory (LinkConfiguration conf, GcodeDevice device, String linkAxis)
Definition at line 11 of file GcodeRotory.java.
References com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeRotory.axis, com.neuronrobotics.sdk.addons.kinematics.AbstractLink.conf, and com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeRotory.device.
Member Function Documentation
cacheTargetValueDevice()
void com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeRotory.cacheTargetValueDevice ()
This method is called in order to take the target value and pass it to the implementation's target value This method should not alter the position of the implementations link If the implementation target does not handle chached values, this should be chached in code.
Reimplemented from com.neuronrobotics.sdk.addons.kinematics.AbstractLink.
Definition at line 20 of file GcodeRotory.java.
flushAllDevice()
void com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeRotory.flushAllDevice (double time)
This method will force one link to update its position in the given time (seconds) This will also flush the host controller.
Parameters
time (seconds) for the position update to take
Reimplemented from com.neuronrobotics.sdk.addons.kinematics.AbstractLink.
Definition at line 40 of file GcodeRotory.java.
References com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeRotory.device, and com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.flush().
flushDevice()
void com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeRotory.flushDevice (double time)
This method will force one link to update its position in the given time (seconds).
Parameters
time (seconds) for the position update to take
Reimplemented from com.neuronrobotics.sdk.addons.kinematics.AbstractLink.
Definition at line 29 of file GcodeRotory.java.
References com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeRotory.device, com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeRotory.getAxis(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.getTargetValue(), com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeRotory.getValue(), com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeRotory.loadCurrent(), and com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.runLine().
getAxis()
String com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeRotory.getAxis ()
Return the gcode axis of this channel
Returns
the axis
Implements com.neuronrobotics.sdk.addons.kinematics.gcodebridge.IGCodeChannel.
Definition at line 50 of file GcodeRotory.java.
References com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeRotory.axis.
Referenced by com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeRotory.flushDevice().
getCurrentPosition()
double com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeRotory.getCurrentPosition ()
This method should return the current position of the link This method is expected to perform a communication with the device .
Returns
the current position of the link
Reimplemented from com.neuronrobotics.sdk.addons.kinematics.AbstractLink.
Definition at line 45 of file GcodeRotory.java.
References com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeRotory.getValue().
getValue()
double com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeRotory.getValue ()
Definition at line 58 of file GcodeRotory.java.
References com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeRotory.value.
Referenced by com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeRotory.flushDevice(), and com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeRotory.getCurrentPosition().
loadCurrent()
void com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeRotory.loadCurrent () private
Definition at line 24 of file GcodeRotory.java.
References com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeRotory.device, and com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.loadCurrent().
Referenced by com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeRotory.flushDevice().
setAxis()
void com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeRotory.setAxis (String axis)
Definition at line 54 of file GcodeRotory.java.
References com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeRotory.axis.
setValue()
void com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeRotory.setValue (double value)
Set a value of the current position
Parameters
value of the current psition
Implements com.neuronrobotics.sdk.addons.kinematics.gcodebridge.IGCodeChannel.
Definition at line 62 of file GcodeRotory.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractLink.fireLinkListener(), and com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeRotory.value.
Member Data Documentation
axis
String com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeRotory.axis = "" private
Definition at line 9 of file GcodeRotory.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeRotory.GcodeRotory(), com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeRotory.getAxis(), and com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeRotory.setAxis().
device
GcodeDevice com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeRotory.device private
Definition at line 8 of file GcodeRotory.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeRotory.flushAllDevice(), com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeRotory.flushDevice(), com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeRotory.GcodeRotory(), and com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeRotory.loadCurrent().
value
double com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeRotory.value =0 private
Definition at line 10 of file GcodeRotory.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeRotory.getValue(), and com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeRotory.setValue().
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/addons/kinematics/gcodebridge/GcodeRotory.java