BowlerKernel: com.neuronrobotics.sdk.bootloader.Hexml Class Reference
com.neuronrobotics.sdk.bootloader.Hexml Class Reference
Public Member Functions
Hexml (File hexml) throws ParserConfigurationException, SAXException, IOException
ArrayList< Core > getCores ()
String getRevision ()
Private Member Functions
void loadRevision (Document doc)
Static Private Member Functions
static String getTagValue (String sTag, Element eElement)
Private Attributes
String revision =""
Detailed Description
The Class Hexml.
Definition at line 22 of file Hexml.java.
Constructor & Destructor Documentation
Hexml()
com.neuronrobotics.sdk.bootloader.Hexml.Hexml (File hexml) throws ParserConfigurationException, SAXException, IOException
Instantiates a new hexml.
Parameters
hexml the hexml
Exceptions
ParserConfigurationException the parser configuration exception
SAXException the SAX exception
IOException Signals that an I/O exception has occurred.
sample code from http://www.mkyong.com/java/how-to-read-xml-file-in-java-dom-parser/
Definition at line 38 of file Hexml.java.
References com.neuronrobotics.sdk.bootloader.NRBootCoreType.find(), com.neuronrobotics.sdk.bootloader.Hexml.getTagValue(), and com.neuronrobotics.sdk.bootloader.Hexml.loadRevision().
Member Function Documentation
getCores()
ArrayList<Core> com.neuronrobotics.sdk.bootloader.Hexml.getCores ()
Gets the cores.
Returns
the cores
Definition at line 121 of file Hexml.java.
getRevision()
String com.neuronrobotics.sdk.bootloader.Hexml.getRevision ()
Gets the revision.
Returns
the revision
Definition at line 130 of file Hexml.java.
References com.neuronrobotics.sdk.bootloader.Hexml.revision.
getTagValue()
static String com.neuronrobotics.sdk.bootloader.Hexml.getTagValue (String sTag, Element eElement) static private
Gets the tag value.
Parameters
sTag the s tag
eElement the e element
Returns
the tag value
Definition at line 110 of file Hexml.java.
Referenced by com.neuronrobotics.sdk.bootloader.Hexml.Hexml().
loadRevision()
void com.neuronrobotics.sdk.bootloader.Hexml.loadRevision (Document doc) private
Load revision.
Parameters
doc the doc
Definition at line 93 of file Hexml.java.
References com.neuronrobotics.sdk.bootloader.Hexml.revision.
Referenced by com.neuronrobotics.sdk.bootloader.Hexml.Hexml().
Member Data Documentation
revision
String com.neuronrobotics.sdk.bootloader.Hexml.revision ="" private
The revision.
Definition at line 28 of file Hexml.java.
Referenced by com.neuronrobotics.sdk.bootloader.Hexml.getRevision(), and com.neuronrobotics.sdk.bootloader.Hexml.loadRevision().
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/bootloader/Hexml.java