BowlerKernel: com.neuronrobotics.imageprovider.ProcessingPipeline Class Reference
com.neuronrobotics.imageprovider.ProcessingPipeline Class Reference
Public Member Functions
void addAbstractImageProvider (AbstractImageProvider newIp)
BufferedImage getLatestImage (int index, BufferedImage inputImage, BufferedImage displayImage)
List< Detection > getObjects (int index, BufferedImage inputImage, BufferedImage displayImage)
void addDetector (IObjectDetector newDetect)
int getProviderSize ()
int getDetectorSize ()
Private Attributes
ArrayList< AbstractImageProvider > imageProviders = new ArrayList<AbstractImageProvider>()
ArrayList< IObjectDetector > detectors = new ArrayList<IObjectDetector>()
Detailed Description
Definition at line 8 of file ProcessingPipeline.java.
Member Function Documentation
addAbstractImageProvider()
void com.neuronrobotics.imageprovider.ProcessingPipeline.addAbstractImageProvider (AbstractImageProvider newIp)
Definition at line 12 of file ProcessingPipeline.java.
References com.neuronrobotics.imageprovider.ProcessingPipeline.imageProviders.
addDetector()
void com.neuronrobotics.imageprovider.ProcessingPipeline.addDetector (IObjectDetector newDetect)
Definition at line 24 of file ProcessingPipeline.java.
References com.neuronrobotics.imageprovider.ProcessingPipeline.detectors.
getDetectorSize()
int com.neuronrobotics.imageprovider.ProcessingPipeline.getDetectorSize ()
Definition at line 32 of file ProcessingPipeline.java.
References com.neuronrobotics.imageprovider.ProcessingPipeline.detectors.
getLatestImage()
BufferedImage com.neuronrobotics.imageprovider.ProcessingPipeline.getLatestImage (int index, BufferedImage inputImage, BufferedImage displayImage)
Definition at line 16 of file ProcessingPipeline.java.
References com.neuronrobotics.imageprovider.ProcessingPipeline.imageProviders.
getObjects()
List<Detection> com.neuronrobotics.imageprovider.ProcessingPipeline.getObjects (int index, BufferedImage inputImage, BufferedImage displayImage)
Definition at line 20 of file ProcessingPipeline.java.
References com.neuronrobotics.imageprovider.ProcessingPipeline.detectors.
getProviderSize()
int com.neuronrobotics.imageprovider.ProcessingPipeline.getProviderSize ()
Definition at line 28 of file ProcessingPipeline.java.
References com.neuronrobotics.imageprovider.ProcessingPipeline.imageProviders.
Member Data Documentation
detectors
ArrayList<IObjectDetector> com.neuronrobotics.imageprovider.ProcessingPipeline.detectors = new ArrayList<IObjectDetector>() private
Definition at line 10 of file ProcessingPipeline.java.
Referenced by com.neuronrobotics.imageprovider.ProcessingPipeline.addDetector(), com.neuronrobotics.imageprovider.ProcessingPipeline.getDetectorSize(), and com.neuronrobotics.imageprovider.ProcessingPipeline.getObjects().
imageProviders
ArrayList<AbstractImageProvider> com.neuronrobotics.imageprovider.ProcessingPipeline.imageProviders = new ArrayList<AbstractImageProvider>() private
Definition at line 9 of file ProcessingPipeline.java.
Referenced by com.neuronrobotics.imageprovider.ProcessingPipeline.addAbstractImageProvider(), com.neuronrobotics.imageprovider.ProcessingPipeline.getLatestImage(), and com.neuronrobotics.imageprovider.ProcessingPipeline.getProviderSize().
The documentation for this class was generated from the following file:
src/main/java/com/neuronrobotics/imageprovider/ProcessingPipeline.java