BowlerKernel: com.neuronrobotics.sdk.ui.UDPConnectionPanel Class Reference
com.neuronrobotics.sdk.ui.UDPConnectionPanel Class Reference
Classes
class NetworkSearchProcess
Public Member Functions
UDPConnectionPanel (ConnectionDialog connectionDialog)
BowlerAbstractConnection getConnection ()
void refresh ()
Public Member Functions inherited from com.neuronrobotics.sdk.ui.AbstractConnectionPanel
AbstractConnectionPanel (String title, ImageIcon icon, ConnectionDialog connectionDialog)
AbstractConnectionPanel (String title, ConnectionDialog connectionDialog)
void setTitle (String title)
String getTitle ()
void setIcon (ImageIcon icon)
ImageIcon getIcon ()
ConnectionDialog getConnectionDialog ()
void setConnectionDialog (ConnectionDialog connectionDialog)
Private Attributes
JComboBox connectionCbo = null
JButton refresh
JTextField port = new JTextField(8)
Static Private Attributes
static final long serialVersionUID = 1L
static final int defaultPortNum = 1865
Detailed Description
The Class UDPConnectionPanel.
Definition at line 40 of file UDPConnectionPanel.java.
Constructor & Destructor Documentation
UDPConnectionPanel()
com.neuronrobotics.sdk.ui.UDPConnectionPanel.UDPConnectionPanel (ConnectionDialog connectionDialog)
Instantiates a new UDP connection panel.
Parameters
connectionDialog the connection dialog
Definition at line 66 of file UDPConnectionPanel.java.
References com.neuronrobotics.sdk.ui.UDPConnectionPanel.connectionCbo, com.neuronrobotics.sdk.ui.AbstractConnectionPanel.connectionDialog, com.neuronrobotics.sdk.ui.UDPConnectionPanel.defaultPortNum, com.neuronrobotics.sdk.ui.ConnectionImageIconFactory.getIcon(), com.neuronrobotics.sdk.ui.UDPConnectionPanel.port, and com.neuronrobotics.sdk.ui.UDPConnectionPanel.refresh.
Member Function Documentation
getConnection()
BowlerAbstractConnection com.neuronrobotics.sdk.ui.UDPConnectionPanel.getConnection ()
Gets the connection.
Returns
the connection
Reimplemented from com.neuronrobotics.sdk.ui.AbstractConnectionPanel.
Definition at line 101 of file UDPConnectionPanel.java.
References com.neuronrobotics.sdk.ui.UDPConnectionPanel.connectionCbo, com.neuronrobotics.sdk.ui.UDPConnectionPanel.port, and com.neuronrobotics.sdk.network.UDPBowlerConnection.setAddress().
refresh()
void com.neuronrobotics.sdk.ui.UDPConnectionPanel.refresh ()
Refresh.
Reimplemented from com.neuronrobotics.sdk.ui.AbstractConnectionPanel.
Definition at line 125 of file UDPConnectionPanel.java.
References com.neuronrobotics.sdk.util.ProcessMonitor.addProcessMonitorListener(), com.neuronrobotics.sdk.ui.UDPConnectionPanel.connectionCbo, com.neuronrobotics.sdk.ui.AbstractConnectionPanel.getConnectionDialog(), com.neuronrobotics.sdk.ui.UDPConnectionPanel.port, com.neuronrobotics.sdk.ui.UDPConnectionPanel.refresh, and com.neuronrobotics.sdk.util.ProcessMonitor.start().
Member Data Documentation
connectionCbo
JComboBox com.neuronrobotics.sdk.ui.UDPConnectionPanel.connectionCbo = null private
The connection cbo.
Definition at line 49 of file UDPConnectionPanel.java.
Referenced by com.neuronrobotics.sdk.ui.UDPConnectionPanel.getConnection(), com.neuronrobotics.sdk.ui.UDPConnectionPanel.refresh(), com.neuronrobotics.sdk.ui.UDPConnectionPanel.NetworkSearchProcess.run(), and com.neuronrobotics.sdk.ui.UDPConnectionPanel.UDPConnectionPanel().
defaultPortNum
final int com.neuronrobotics.sdk.ui.UDPConnectionPanel.defaultPortNum = 1865 static private
The Constant defaultPortNum.
Definition at line 46 of file UDPConnectionPanel.java.
Referenced by com.neuronrobotics.sdk.ui.UDPConnectionPanel.NetworkSearchProcess.run(), and com.neuronrobotics.sdk.ui.UDPConnectionPanel.UDPConnectionPanel().
port
JTextField com.neuronrobotics.sdk.ui.UDPConnectionPanel.port = new JTextField(8) private
The port.
Definition at line 55 of file UDPConnectionPanel.java.
Referenced by com.neuronrobotics.sdk.ui.UDPConnectionPanel.getConnection(), com.neuronrobotics.sdk.ui.UDPConnectionPanel.refresh(), com.neuronrobotics.sdk.ui.UDPConnectionPanel.NetworkSearchProcess.run(), and com.neuronrobotics.sdk.ui.UDPConnectionPanel.UDPConnectionPanel().
refresh
JButton com.neuronrobotics.sdk.ui.UDPConnectionPanel.refresh private
The refresh.
Definition at line 52 of file UDPConnectionPanel.java.
Referenced by com.neuronrobotics.sdk.ui.UDPConnectionPanel.refresh(), and com.neuronrobotics.sdk.ui.UDPConnectionPanel.UDPConnectionPanel().
serialVersionUID
final long com.neuronrobotics.sdk.ui.UDPConnectionPanel.serialVersionUID = 1L static private
The Constant serialVersionUID.
Definition at line 43 of file UDPConnectionPanel.java.
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/ui/UDPConnectionPanel.java