BowlerKernel: com.neuronrobotics.sdk.common.DMDevice Class Reference
com.neuronrobotics.sdk.common.DMDevice Class Reference
Public Member Functions
DMDevice (Object o) throws NoSuchMethodException, SecurityException
String getScriptingName ()
ArrayList< String > getNamespacesImp ()
void disconnectDeviceImp ()
boolean isAvailable () throws InvalidConnectionException
boolean connectDeviceImp ()
Object getWrapped ()
void setWrapped (Object wrapped)
Public Member Functions inherited from com.neuronrobotics.sdk.common.NonBowlerDevice
boolean connect ()
void disconnect ()
void onAsyncResponse (BowlerDatagram data)
ArrayList< String > getNamespaces ()
Public Member Functions inherited from com.neuronrobotics.sdk.common.BowlerAbstractDevice
void addConnectionEventListener (final IDeviceConnectionEventListener l)
void removeConnectionEventListener (IDeviceConnectionEventListener l)
void setConnection (BowlerAbstractConnection connection)
BowlerAbstractConnection getConnection ()
void setAddress (MACAddress address)
MACAddress getAddress ()
BowlerDatagram send (BowlerAbstractCommand command) throws NoConnectionAvailableException, InvalidResponseException
BowlerDatagram send (BowlerAbstractCommand command, int retry) throws NoConnectionAvailableException, InvalidResponseException
Object[] send (String namespace, BowlerMethod method, String rpcString, Object[] arguments, int retry) throws DeviceConnectionException
Object[] send (String namespace, BowlerMethod method, String rpcString, Object[] arguments) throws DeviceConnectionException
boolean ping ()
boolean ping (boolean switchParser)
ArrayList< ByteList > getRevisions ()
boolean hasNamespace (String string)
void startHeartBeat ()
void startHeartBeat (long msHeartBeatTime)
void stopHeartBeat ()
void setThreadedUpstreamPackets (boolean up)
ArrayList< RpcEncapsulation > getRpcList (String namespace)
void loadRpcList ()
void onAllResponse (BowlerDatagram data)
boolean isKeepAlive ()
void setKeepAlive (boolean keepAlive)
long getLastPacketTime ()
void setLastPacketTime (long lastPacketTime)
void setScriptingName (String scriptingName)
ArrayList< IDeviceConnectionEventListener > getDisconnectListeners ()
Static Public Member Functions
static boolean wrappable (Object o)
static boolean methodExists (Object clazz, String methodName)
Private Attributes
Object wrapped = null
Additional Inherited Members
Protected Member Functions inherited from com.neuronrobotics.sdk.common.BowlerAbstractDevice
void fireDisconnectEvent ()
void fireConnectEvent ()
Detailed Description
Definition at line 7 of file DMDevice.java.
Constructor & Destructor Documentation
DMDevice()
com.neuronrobotics.sdk.common.DMDevice.DMDevice (Object o) throws NoSuchMethodException, SecurityException
Definition at line 16 of file DMDevice.java.
References com.neuronrobotics.sdk.common.DMDevice.getWrapped(), com.neuronrobotics.sdk.common.DMDevice.methodExists(), com.neuronrobotics.sdk.common.DMDevice.setWrapped(), and com.neuronrobotics.sdk.common.DMDevice.wrappable().
Member Function Documentation
connectDeviceImp()
boolean com.neuronrobotics.sdk.common.DMDevice.connectDeviceImp ()
Connect device imp.
Returns
true, if successful
Reimplemented from com.neuronrobotics.sdk.common.NonBowlerDevice.
Definition at line 92 of file DMDevice.java.
References com.neuronrobotics.sdk.common.DMDevice.getWrapped().
disconnectDeviceImp()
void com.neuronrobotics.sdk.common.DMDevice.disconnectDeviceImp ()
This method tells the connection object to disconnect its pipes and close out the connection. Once this is called, it is safe to remove your device.
Reimplemented from com.neuronrobotics.sdk.common.NonBowlerDevice.
Definition at line 58 of file DMDevice.java.
References com.neuronrobotics.sdk.common.DMDevice.getWrapped().
getNamespacesImp()
ArrayList<String> com.neuronrobotics.sdk.common.DMDevice.getNamespacesImp ()
Gets the namespaces imp.
Returns
the namespaces imp
Reimplemented from com.neuronrobotics.sdk.common.NonBowlerDevice.
Definition at line 52 of file DMDevice.java.
getScriptingName()
String com.neuronrobotics.sdk.common.DMDevice.getScriptingName ()
Gets the scripting name.
Returns
the scripting name
Reimplemented from com.neuronrobotics.sdk.common.BowlerAbstractDevice.
Definition at line 28 of file DMDevice.java.
References com.neuronrobotics.sdk.common.DMDevice.getWrapped().
getWrapped()
Object com.neuronrobotics.sdk.common.DMDevice.getWrapped ()
Definition at line 123 of file DMDevice.java.
References com.neuronrobotics.sdk.common.DMDevice.wrapped.
Referenced by com.neuronrobotics.sdk.common.DeviceManager.addConnectionBAD(), com.neuronrobotics.sdk.common.DMDevice.connectDeviceImp(), com.neuronrobotics.sdk.common.DMDevice.disconnectDeviceImp(), com.neuronrobotics.sdk.common.DMDevice.DMDevice(), com.neuronrobotics.sdk.common.DMDevice.getScriptingName(), and com.neuronrobotics.sdk.common.DMDevice.isAvailable().
isAvailable()
boolean com.neuronrobotics.sdk.common.DMDevice.isAvailable () throws InvalidConnectionException
Determines if the device is available.
Returns
true if the device is avaiable, false if it is not
Exceptions
InvalidConnectionException the invalid connection exception
Reimplemented from com.neuronrobotics.sdk.common.NonBowlerDevice.
Definition at line 73 of file DMDevice.java.
References com.neuronrobotics.sdk.common.DMDevice.getWrapped().
methodExists()
static boolean com.neuronrobotics.sdk.common.DMDevice.methodExists (Object clazz, String methodName) static
Definition at line 114 of file DMDevice.java.
Referenced by com.neuronrobotics.sdk.common.DMDevice.DMDevice(), and com.neuronrobotics.sdk.common.DMDevice.wrappable().
setWrapped()
void com.neuronrobotics.sdk.common.DMDevice.setWrapped (Object wrapped)
Definition at line 127 of file DMDevice.java.
References com.neuronrobotics.sdk.common.DMDevice.wrapped.
Referenced by com.neuronrobotics.sdk.common.DMDevice.DMDevice().
wrappable()
static boolean com.neuronrobotics.sdk.common.DMDevice.wrappable (Object o) static
Definition at line 107 of file DMDevice.java.
References com.neuronrobotics.sdk.common.DMDevice.methodExists().
Referenced by com.neuronrobotics.sdk.common.DeviceManager.addConnection(), and com.neuronrobotics.sdk.common.DMDevice.DMDevice().
Member Data Documentation
wrapped
Object com.neuronrobotics.sdk.common.DMDevice.wrapped = null private
Definition at line 8 of file DMDevice.java.
Referenced by com.neuronrobotics.sdk.common.DMDevice.getWrapped(), and com.neuronrobotics.sdk.common.DMDevice.setWrapped().
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/common/DMDevice.java