BowlerKernel: com.neuronrobotics.sdk.dyio.peripherals.ServoChannel.powerOverridePacket Class Reference
com.neuronrobotics.sdk.dyio.peripherals.ServoChannel.powerOverridePacket Class Reference
Public Member Functions
powerOverridePacket (boolean ovr)
Public Member Functions inherited from com.neuronrobotics.sdk.common.BowlerAbstractCommand
byte[] getCallingData ()
void setOpCode (String opCode)
String getOpCode ()
void setMethod (BowlerMethod method)
BowlerMethod getMethod ()
byte getLength ()
BowlerDatagram validate (BowlerDatagram data) throws InvalidResponseException
byte[] getBytes ()
String toString ()
void setData (ByteList data)
ByteList getCallingDataStorage ()
void setNamespaceIndex (int namespaceIndex)
int getNamespaceIndex ()
Additional Inherited Members
Static Public Member Functions inherited from com.neuronrobotics.sdk.common.BowlerAbstractCommand
static BowlerAbstractCommand parse (BowlerDatagram data)
Detailed Description
The Class powerOverridePacket.
Definition at line 188 of file ServoChannel.java.
Constructor & Destructor Documentation
powerOverridePacket()
com.neuronrobotics.sdk.dyio.peripherals.ServoChannel.powerOverridePacket.powerOverridePacket (boolean ovr)
Instantiates a new power override packet.
Parameters
ovr the ovr
Definition at line 195 of file ServoChannel.java.
References com.neuronrobotics.sdk.common.ByteList.add(), com.neuronrobotics.sdk.common.BowlerMethod.CRITICAL, com.neuronrobotics.sdk.common.BowlerAbstractCommand.getCallingDataStorage(), com.neuronrobotics.sdk.common.BowlerAbstractCommand.setMethod(), and com.neuronrobotics.sdk.common.BowlerAbstractCommand.setOpCode().
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/dyio/peripherals/ServoChannel.java