BowlerKernel: eu.mihosoft.vrl.v3d.Polyhedron Class Reference
eu.mihosoft.vrl.v3d.Polyhedron Class Reference
Public Member Functions
Polyhedron (List< Vector3d > points, List< List< Integer >> faces)
Polyhedron (Vector3d[] points, Integer[][] faces)
List< Polygon > toPolygons ()
PropertyStorage getProperties ()
Public Member Functions inherited from eu.mihosoft.vrl.v3d.Primitive
CSG toCSG ()
Private Attributes
final PropertyStorage properties = new PropertyStorage()
final List< Vector3d > points = new ArrayList<>()
final List< List< Integer > > faces = new ArrayList<>()
Detailed Description
Polyhedron.
Author
Michael Hoffer <info@.nosp@m.mich.nosp@m.aelho.nosp@m.ffer.nosp@m..de>
Definition at line 20 of file Polyhedron.java.
Constructor & Destructor Documentation
Polyhedron() [1/2]
eu.mihosoft.vrl.v3d.Polyhedron.Polyhedron (List< Vector3d > points, List< List< Integer >> faces)
Constructor. Creates a polyhedron defined by a list of points and a list of faces.
Parameters
points points (Vector3d list)
faces list of faces (list of point index lists)
Definition at line 38 of file Polyhedron.java.
References eu.mihosoft.vrl.v3d.Polyhedron.faces, and eu.mihosoft.vrl.v3d.Polyhedron.points.
Polyhedron() [2/2]
eu.mihosoft.vrl.v3d.Polyhedron.Polyhedron (Vector3d[] points, Integer faces[][])
Constructor. Creates a polyhedron defined by a list of points and a list of faces.
Parameters
points points (Vector3d array)
faces list of faces (array of point index arrays)
Definition at line 50 of file Polyhedron.java.
References eu.mihosoft.vrl.v3d.Polyhedron.faces, and eu.mihosoft.vrl.v3d.Polyhedron.points.
Member Function Documentation
getProperties()
PropertyStorage eu.mihosoft.vrl.v3d.Polyhedron.getProperties ()
Returns the property storage of this primitive.
Returns
the property storage of this primitive
Reimplemented from eu.mihosoft.vrl.v3d.Primitive.
Definition at line 83 of file Polyhedron.java.
References eu.mihosoft.vrl.v3d.Polyhedron.properties.
toPolygons()
List<Polygon> eu.mihosoft.vrl.v3d.Polyhedron.toPolygons ()
Returns the polygons that define this primitive.
Note: this method computes the polygons each time this method is called. The polygons can be cached inside a CSG object.
Returns
a list of polygons that define this primitive
Reimplemented from eu.mihosoft.vrl.v3d.Primitive.
Definition at line 63 of file Polyhedron.java.
References eu.mihosoft.vrl.v3d.Polyhedron.faces, eu.mihosoft.vrl.v3d.Polygon.fromPoints(), eu.mihosoft.vrl.v3d.Polyhedron.points, and eu.mihosoft.vrl.v3d.Polyhedron.properties.
Member Data Documentation
faces
final List<List<Integer> > eu.mihosoft.vrl.v3d.Polyhedron.faces = new ArrayList<>() private
The faces.
Definition at line 29 of file Polyhedron.java.
Referenced by eu.mihosoft.vrl.v3d.Polyhedron.Polyhedron(), and eu.mihosoft.vrl.v3d.Polyhedron.toPolygons().
points
final List<Vector3d> eu.mihosoft.vrl.v3d.Polyhedron.points = new ArrayList<>() private
The points.
Definition at line 26 of file Polyhedron.java.
Referenced by eu.mihosoft.vrl.v3d.Polyhedron.Polyhedron(), and eu.mihosoft.vrl.v3d.Polyhedron.toPolygons().
properties
final PropertyStorage eu.mihosoft.vrl.v3d.Polyhedron.properties = new PropertyStorage() private
The properties.
Definition at line 23 of file Polyhedron.java.
Referenced by eu.mihosoft.vrl.v3d.Polyhedron.getProperties(), and eu.mihosoft.vrl.v3d.Polyhedron.toPolygons().
The documentation for this class was generated from the following file:
JCSG/src/main/java/eu/mihosoft/vrl/v3d/Polyhedron.java