BowlerKernel: eu.mihosoft.vrl.v3d.Bounds Class Reference
eu.mihosoft.vrl.v3d.Bounds Class Reference
Public Member Functions
Bounds (Vector3d min, Vector3d max)
Bounds clone ()
Vector3d getCenter ()
Vector3d getBounds ()
CSG toCSG ()
Cube toCube ()
boolean contains (Vertex v)
boolean contains (Vector3d v)
boolean contains (Polygon p)
boolean intersects (Polygon p)
boolean intersects (Bounds b)
Vector3d getMin ()
Vector3d getMax ()
String toString ()
Private Attributes
final Vector3d center
final Vector3d bounds
final Vector3d min
final Vector3d max
CSG csg
Cube cube
Detailed Description
Bounding box for CSGs.
Author
Michael Hoffer <info@.nosp@m.mich.nosp@m.aelho.nosp@m.ffer.nosp@m..de>
Definition at line 14 of file Bounds.java.
Constructor & Destructor Documentation
Bounds()
eu.mihosoft.vrl.v3d.Bounds.Bounds (Vector3d min, Vector3d max)
Constructor.
Parameters
min min x,y,z values
max max x,y,z values
Definition at line 40 of file Bounds.java.
References eu.mihosoft.vrl.v3d.Vector3d.clone(), eu.mihosoft.vrl.v3d.Bounds.max, eu.mihosoft.vrl.v3d.Bounds.min, eu.mihosoft.vrl.v3d.Vector3d.x(), eu.mihosoft.vrl.v3d.Vector3d.y(), and eu.mihosoft.vrl.v3d.Vector3d.z().
Referenced by eu.mihosoft.vrl.v3d.Bounds.clone().
Member Function Documentation
clone()
Bounds eu.mihosoft.vrl.v3d.Bounds.clone ()
Definition at line 59 of file Bounds.java.
References eu.mihosoft.vrl.v3d.Bounds.Bounds(), eu.mihosoft.vrl.v3d.Vector3d.clone(), eu.mihosoft.vrl.v3d.Bounds.max, and eu.mihosoft.vrl.v3d.Bounds.min.
contains() [1/3]
boolean eu.mihosoft.vrl.v3d.Bounds.contains (Polygon p)
Indicates whether the specified polygon is contained within this bounding box (check includes box boundary).
Parameters
p polygon to check
Returns
true
if the polygon is contained within this bounding box;
false
otherwise
Definition at line 145 of file Bounds.java.
References eu.mihosoft.vrl.v3d.Bounds.contains(), and eu.mihosoft.vrl.v3d.Polygon.vertices.
contains() [2/3]
boolean eu.mihosoft.vrl.v3d.Bounds.contains (Vector3d v)
Indicates whether the specified point is contained within this bounding box (check includes box boundary).
Parameters
v vertex to check
Returns
true
if the point is contained within this bounding box;
false
otherwise
Definition at line 129 of file Bounds.java.
References eu.mihosoft.vrl.v3d.Bounds.max, eu.mihosoft.vrl.v3d.Bounds.min, eu.mihosoft.vrl.v3d.Vector3d.x(), eu.mihosoft.vrl.v3d.Vector3d.y(), and eu.mihosoft.vrl.v3d.Vector3d.z().
contains() [3/3]
boolean eu.mihosoft.vrl.v3d.Bounds.contains (Vertex v)
Indicates whether the specified vertex is contained within this bounding box (check includes box boundary).
Parameters
v vertex to check
Returns
true
if the vertex is contained within this bounding box;
false
otherwise
Definition at line 117 of file Bounds.java.
References eu.mihosoft.vrl.v3d.Vertex.pos.
Referenced by eu.mihosoft.vrl.v3d.Bounds.contains().
getBounds()
Vector3d eu.mihosoft.vrl.v3d.Bounds.getBounds ()
Returns the bounds (width,height,depth).
Returns
the bounds (width,height,depth)
Definition at line 77 of file Bounds.java.
References eu.mihosoft.vrl.v3d.Bounds.bounds.
getCenter()
Vector3d eu.mihosoft.vrl.v3d.Bounds.getCenter ()
Returns the position of the center.
Returns
the center position
Definition at line 68 of file Bounds.java.
References eu.mihosoft.vrl.v3d.Bounds.center.
getMax()
Vector3d eu.mihosoft.vrl.v3d.Bounds.getMax ()
Gets the max.
Returns
the max x,y,z values
Definition at line 201 of file Bounds.java.
References eu.mihosoft.vrl.v3d.Bounds.max.
Referenced by eu.mihosoft.vrl.v3d.XModifier.eval(), eu.mihosoft.vrl.v3d.YModifier.eval(), eu.mihosoft.vrl.v3d.ZModifier.eval(), eu.mihosoft.vrl.v3d.Bounds.intersects(), eu.mihosoft.vrl.v3d.CSG.toXMax(), eu.mihosoft.vrl.v3d.CSG.toYMax(), and eu.mihosoft.vrl.v3d.CSG.toZMax().
getMin()
Vector3d eu.mihosoft.vrl.v3d.Bounds.getMin ()
Gets the min.
Returns
the min x,y,z values
Definition at line 192 of file Bounds.java.
References eu.mihosoft.vrl.v3d.Bounds.min.
Referenced by eu.mihosoft.vrl.v3d.XModifier.eval(), eu.mihosoft.vrl.v3d.YModifier.eval(), eu.mihosoft.vrl.v3d.ZModifier.eval(), eu.mihosoft.vrl.v3d.Bounds.intersects(), eu.mihosoft.vrl.v3d.CSG.toXMin(), eu.mihosoft.vrl.v3d.CSG.toYMin(), and eu.mihosoft.vrl.v3d.CSG.toZMin().
intersects() [1/2]
boolean eu.mihosoft.vrl.v3d.Bounds.intersects (Bounds b)
Indicates whether the specified bounding box intersects with this bounding box (check includes box boundary).
Parameters
b box to check
Returns
true
if the bounding box intersects this bounding box;
false
otherwise
Definition at line 171 of file Bounds.java.
References eu.mihosoft.vrl.v3d.Bounds.getMax(), eu.mihosoft.vrl.v3d.Bounds.getMin(), eu.mihosoft.vrl.v3d.Vector3d.x(), eu.mihosoft.vrl.v3d.Vector3d.y(), and eu.mihosoft.vrl.v3d.Vector3d.z().
intersects() [2/2]
boolean eu.mihosoft.vrl.v3d.Bounds.intersects (Polygon p)
Indicates whether the specified polygon intersects with this bounding box (check includes box boundary).
Parameters
p polygon to check
Returns
true
if the polygon intersects this bounding box;
false
otherwise
Deprecated:
not implemented yet
Definition at line 159 of file Bounds.java.
Referenced by eu.mihosoft.vrl.v3d.CSG._differencePolygonBoundsOpt(), eu.mihosoft.vrl.v3d.CSG._unionIntersectOpt(), and eu.mihosoft.vrl.v3d.CSG._unionPolygonBoundsOpt().
toCSG()
CSG eu.mihosoft.vrl.v3d.Bounds.toCSG ()
Returns this bounding box as csg.
Returns
this bounding box as csg
Definition at line 86 of file Bounds.java.
References eu.mihosoft.vrl.v3d.Bounds.bounds, eu.mihosoft.vrl.v3d.Bounds.center, eu.mihosoft.vrl.v3d.Bounds.csg, eu.mihosoft.vrl.v3d.Bounds.cube, and eu.mihosoft.vrl.v3d.Primitive.toCSG().
Referenced by eu.mihosoft.vrl.v3d.CSG._differenceCSGBoundsOpt().
toCube()
Cube eu.mihosoft.vrl.v3d.Bounds.toCube ()
Returns this bounding box as cube.
Returns
this bounding box as cube
Definition at line 100 of file Bounds.java.
References eu.mihosoft.vrl.v3d.Bounds.bounds, eu.mihosoft.vrl.v3d.Bounds.center, eu.mihosoft.vrl.v3d.Bounds.csg, eu.mihosoft.vrl.v3d.Bounds.cube, and eu.mihosoft.vrl.v3d.Primitive.toCSG().
toString()
String eu.mihosoft.vrl.v3d.Bounds.toString ()
Definition at line 209 of file Bounds.java.
References eu.mihosoft.vrl.v3d.Bounds.bounds, and eu.mihosoft.vrl.v3d.Bounds.center.
Referenced by eu.mihosoft.vrl.v3d.MeshContainer.toString().
Member Data Documentation
bounds
final Vector3d eu.mihosoft.vrl.v3d.Bounds.bounds private
The bounds.
Definition at line 20 of file Bounds.java.
Referenced by eu.mihosoft.vrl.v3d.Bounds.getBounds(), eu.mihosoft.vrl.v3d.Bounds.toCSG(), eu.mihosoft.vrl.v3d.Bounds.toCube(), and eu.mihosoft.vrl.v3d.Bounds.toString().
center
final Vector3d eu.mihosoft.vrl.v3d.Bounds.center private
The center.
Definition at line 17 of file Bounds.java.
Referenced by eu.mihosoft.vrl.v3d.Bounds.getCenter(), eu.mihosoft.vrl.v3d.Bounds.toCSG(), eu.mihosoft.vrl.v3d.Bounds.toCube(), and eu.mihosoft.vrl.v3d.Bounds.toString().
csg
CSG eu.mihosoft.vrl.v3d.Bounds.csg private
The csg.
Definition at line 29 of file Bounds.java.
Referenced by eu.mihosoft.vrl.v3d.Bounds.toCSG(), and eu.mihosoft.vrl.v3d.Bounds.toCube().
cube
Cube eu.mihosoft.vrl.v3d.Bounds.cube private
The cube.
Definition at line 32 of file Bounds.java.
Referenced by eu.mihosoft.vrl.v3d.Bounds.toCSG(), and eu.mihosoft.vrl.v3d.Bounds.toCube().
max
final Vector3d eu.mihosoft.vrl.v3d.Bounds.max private
The max.
Definition at line 26 of file Bounds.java.
Referenced by eu.mihosoft.vrl.v3d.Bounds.Bounds(), eu.mihosoft.vrl.v3d.Bounds.clone(), eu.mihosoft.vrl.v3d.Bounds.contains(), and eu.mihosoft.vrl.v3d.Bounds.getMax().
min
final Vector3d eu.mihosoft.vrl.v3d.Bounds.min private
The min.
Definition at line 23 of file Bounds.java.
Referenced by eu.mihosoft.vrl.v3d.Bounds.Bounds(), eu.mihosoft.vrl.v3d.Bounds.clone(), eu.mihosoft.vrl.v3d.Bounds.contains(), and eu.mihosoft.vrl.v3d.Bounds.getMin().
The documentation for this class was generated from the following file:
JCSG/src/main/java/eu/mihosoft/vrl/v3d/Bounds.java