BowlerKernel: com.neuronrobotics.sdk.commands.bcs.pid.DyPID.ConfigureDynamicPIDCommand Class Reference
com.neuronrobotics.sdk.commands.bcs.pid.DyPID.ConfigureDynamicPIDCommand Class Reference
Public Member Functions
ConfigureDynamicPIDCommand (int group)
ConfigureDynamicPIDCommand (char group, int inputChannel, DyIOChannelMode inputMode, int outputChannel, DyIOChannelMode outputMode)
ConfigureDynamicPIDCommand (DyPIDConfiguration config)
Public Member Functions inherited from com.neuronrobotics.sdk.common.BowlerAbstractCommand
byte[] getCallingData ()
void setOpCode (String opCode)
String getOpCode ()
void setMethod (BowlerMethod method)
BowlerMethod getMethod ()
byte getLength ()
BowlerDatagram validate (BowlerDatagram data) throws InvalidResponseException
byte[] getBytes ()
String toString ()
void setData (ByteList data)
ByteList getCallingDataStorage ()
void setNamespaceIndex (int namespaceIndex)
int getNamespaceIndex ()
Additional Inherited Members
Static Public Member Functions inherited from com.neuronrobotics.sdk.common.BowlerAbstractCommand
static BowlerAbstractCommand parse (BowlerDatagram data)
Detailed Description
The Class ConfigureDynamicPIDCommand.
Definition at line 12 of file ConfigureDynamicPIDCommand.java.
Constructor & Destructor Documentation
ConfigureDynamicPIDCommand() [1/3]
com.neuronrobotics.sdk.commands.bcs.pid.DyPID.ConfigureDynamicPIDCommand.ConfigureDynamicPIDCommand (int group)
Instantiates a new configure dynamic pid command.
Parameters
group the group
Definition at line 19 of file ConfigureDynamicPIDCommand.java.
References com.neuronrobotics.sdk.common.ByteList.add(), com.neuronrobotics.sdk.common.BowlerMethod.GET, com.neuronrobotics.sdk.common.BowlerAbstractCommand.getCallingDataStorage(), com.neuronrobotics.sdk.common.BowlerAbstractCommand.setMethod(), and com.neuronrobotics.sdk.common.BowlerAbstractCommand.setOpCode().
ConfigureDynamicPIDCommand() [2/3]
com.neuronrobotics.sdk.commands.bcs.pid.DyPID.ConfigureDynamicPIDCommand.ConfigureDynamicPIDCommand (char group, int inputChannel, DyIOChannelMode inputMode, int outputChannel, DyIOChannelMode outputMode)
Instantiates a new configure dynamic pid command.
Parameters
group the group
inputChannel the input channel
inputMode the input mode
outputChannel the output channel
outputMode the output mode
Definition at line 34 of file ConfigureDynamicPIDCommand.java.
References com.neuronrobotics.sdk.common.ByteList.add(), com.neuronrobotics.sdk.common.BowlerMethod.CRITICAL, com.neuronrobotics.sdk.common.BowlerAbstractCommand.getCallingDataStorage(), com.neuronrobotics.sdk.dyio.DyIOChannelMode.getValue(), com.neuronrobotics.sdk.common.BowlerAbstractCommand.setMethod(), and com.neuronrobotics.sdk.common.BowlerAbstractCommand.setOpCode().
ConfigureDynamicPIDCommand() [3/3]
com.neuronrobotics.sdk.commands.bcs.pid.DyPID.ConfigureDynamicPIDCommand.ConfigureDynamicPIDCommand (DyPIDConfiguration config)
Instantiates a new configure dynamic pid command.
Parameters
config the config
Definition at line 50 of file ConfigureDynamicPIDCommand.java.
References com.neuronrobotics.sdk.common.ByteList.add(), com.neuronrobotics.sdk.common.BowlerMethod.CRITICAL, com.neuronrobotics.sdk.common.BowlerAbstractCommand.getCallingDataStorage(), com.neuronrobotics.sdk.dyio.dypid.DyPIDConfiguration.getGroup(), com.neuronrobotics.sdk.dyio.dypid.DyPIDConfiguration.getInputChannel(), com.neuronrobotics.sdk.dyio.dypid.DyPIDConfiguration.getInputMode(), com.neuronrobotics.sdk.dyio.dypid.DyPIDConfiguration.getOutputChannel(), com.neuronrobotics.sdk.dyio.dypid.DyPIDConfiguration.getOutputMode(), com.neuronrobotics.sdk.dyio.DyIOChannelMode.getValue(), com.neuronrobotics.sdk.common.BowlerAbstractCommand.setMethod(), and com.neuronrobotics.sdk.common.BowlerAbstractCommand.setOpCode().
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/commands/bcs/pid/DyPID/ConfigureDynamicPIDCommand.java