BowlerKernel: com.neuronrobotics.bowlerstudio.printbed.PrintBedManager Class Reference
com.neuronrobotics.bowlerstudio.printbed.PrintBedManager Class Reference
Public Member Functions
PrintBedManager (String url, ArrayList< CSG > parts)
PrintBedManager (File dir, ArrayList< CSG > parts)
boolean init (File dir, ArrayList< CSG > parts)
ArrayList< CSG > makePrintBeds ()
ArrayList< CSG > get ()
boolean hasPrintBed ()
void setHasPrintBed (boolean hasPrintBed)
Static Public Attributes
static String file = "printbed.json"
Private Member Functions
synchronized void saveLocal ()
void write (String file, String content) throws InvalidRemoteException, TransportException, GitAPIException, IOException
void save ()
Private Attributes
UserManagedPrintBedData database = null
String url
ArrayList< CSG > parts
HashSet< String > names = new HashSet<String>()
boolean hasPrintBed = false
Detailed Description
Definition at line 33 of file PrintBedManager.java.
Constructor & Destructor Documentation
PrintBedManager() [1/2]
com.neuronrobotics.bowlerstudio.printbed.PrintBedManager.PrintBedManager (String url, ArrayList< CSG > parts)
Definition at line 47 of file PrintBedManager.java.
References com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getRepositoryCloneDirectory(), com.neuronrobotics.bowlerstudio.printbed.PrintBedManager.init(), com.neuronrobotics.bowlerstudio.printbed.PrintBedManager.parts, and com.neuronrobotics.bowlerstudio.printbed.PrintBedManager.url.
PrintBedManager() [2/2]
com.neuronrobotics.bowlerstudio.printbed.PrintBedManager.PrintBedManager (File dir, ArrayList< CSG > parts)
Definition at line 54 of file PrintBedManager.java.
References com.neuronrobotics.bowlerstudio.printbed.PrintBedManager.init(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.locateGitUrl(), com.neuronrobotics.bowlerstudio.printbed.PrintBedManager.parts, and com.neuronrobotics.bowlerstudio.printbed.PrintBedManager.setHasPrintBed().
Member Function Documentation
get()
ArrayList<CSG> com.neuronrobotics.bowlerstudio.printbed.PrintBedManager.get ()
Definition at line 186 of file PrintBedManager.java.
hasPrintBed()
boolean com.neuronrobotics.bowlerstudio.printbed.PrintBedManager.hasPrintBed ()
Returns
the hasPrintBed
Definition at line 227 of file PrintBedManager.java.
References com.neuronrobotics.bowlerstudio.printbed.PrintBedManager.hasPrintBed.
init()
boolean com.neuronrobotics.bowlerstudio.printbed.PrintBedManager.init (File dir, ArrayList< CSG > parts)
Definition at line 63 of file PrintBedManager.java.
References com.neuronrobotics.bowlerstudio.printbed.PrintBedObject.addSaveListener(), com.neuronrobotics.bowlerstudio.creature.UserManagedPrintBedData.bedX, com.neuronrobotics.bowlerstudio.creature.UserManagedPrintBedData.bedY, com.neuronrobotics.bowlerstudio.printbed.PrintBedObject.checkBounds(), com.neuronrobotics.bowlerstudio.printbed.PrintBedManager.database, com.neuronrobotics.bowlerstudio.printbed.PrintBedManager.file, eu.mihosoft.vrl.v3d.CSG.getMaxX(), eu.mihosoft.vrl.v3d.CSG.getMaxY(), eu.mihosoft.vrl.v3d.CSG.getMinX(), eu.mihosoft.vrl.v3d.CSG.getMinY(), eu.mihosoft.vrl.v3d.CSG.getName(), com.neuronrobotics.bowlerstudio.creature.UserManagedPrintBedData.init(), com.neuronrobotics.bowlerstudio.creature.UserManagedPrintBedData.locations, eu.mihosoft.vrl.v3d.CSG.movey(), com.neuronrobotics.bowlerstudio.printbed.PrintBedManager.names, com.neuronrobotics.bowlerstudio.printbed.PrintBedManager.parts, eu.mihosoft.vrl.v3d.CSG.prepForManufacturing(), eu.mihosoft.vrl.v3d.CSG.rotz(), com.neuronrobotics.bowlerstudio.printbed.PrintBedManager.save(), eu.mihosoft.vrl.v3d.CSG.setColor(), eu.mihosoft.vrl.v3d.Primitive.toCSG(), eu.mihosoft.vrl.v3d.CSG.toXMin(), eu.mihosoft.vrl.v3d.CSG.toYMin(), eu.mihosoft.vrl.v3d.CSG.toZMax(), and com.neuronrobotics.bowlerstudio.printbed.PrintBedManager.url.
Referenced by com.neuronrobotics.bowlerstudio.printbed.PrintBedManager.PrintBedManager().
makePrintBeds()
ArrayList<CSG> com.neuronrobotics.bowlerstudio.printbed.PrintBedManager.makePrintBeds ()
Definition at line 123 of file PrintBedManager.java.
References eu.mihosoft.vrl.v3d.CSG.addExportFormat(), com.neuronrobotics.bowlerstudio.printbed.PrintBedManager.database, eu.mihosoft.vrl.v3d.CSG.dumbUnion(), eu.mihosoft.vrl.v3d.CSG.getExportFormats(), com.neuronrobotics.bowlerstudio.creature.UserManagedPrintBedData.locations, com.neuronrobotics.bowlerstudio.printbed.PrintBedManager.names, com.neuronrobotics.bowlerstudio.physics.TransformFactory.nrToCSG(), com.neuronrobotics.bowlerstudio.printbed.PrintBedManager.parts, eu.mihosoft.vrl.v3d.CSG.setManufacturing(), eu.mihosoft.vrl.v3d.CSG.setName(), eu.mihosoft.vrl.v3d.Primitive.toCSG(), eu.mihosoft.vrl.v3d.CSG.toZMin(), and com.neuronrobotics.bowlerstudio.printbed.PrintBedManager.url.
Referenced by com.neuronrobotics.bowlerstudio.creature.UserManagedPrintBed.arrangeBed(), and com.neuronrobotics.bowlerstudio.BowlerKernel.processReturnedObjectsStart().
save()
void com.neuronrobotics.bowlerstudio.printbed.PrintBedManager.save () private
Definition at line 218 of file PrintBedManager.java.
References com.neuronrobotics.bowlerstudio.printbed.PrintBedManager.saveLocal().
Referenced by com.neuronrobotics.bowlerstudio.printbed.PrintBedManager.init().
saveLocal()
synchronized void com.neuronrobotics.bowlerstudio.printbed.PrintBedManager.saveLocal () private
Definition at line 197 of file PrintBedManager.java.
References com.neuronrobotics.bowlerstudio.printbed.PrintBedManager.database, com.neuronrobotics.bowlerstudio.printbed.PrintBedManager.file, and com.neuronrobotics.bowlerstudio.printbed.PrintBedManager.write().
Referenced by com.neuronrobotics.bowlerstudio.printbed.PrintBedManager.save().
setHasPrintBed()
void com.neuronrobotics.bowlerstudio.printbed.PrintBedManager.setHasPrintBed (boolean hasPrintBed)
Parameters
hasPrintBed the hasPrintBed to set
Definition at line 234 of file PrintBedManager.java.
References com.neuronrobotics.bowlerstudio.printbed.PrintBedManager.hasPrintBed.
Referenced by com.neuronrobotics.bowlerstudio.printbed.PrintBedManager.PrintBedManager().
write()
void com.neuronrobotics.bowlerstudio.printbed.PrintBedManager.write (String file, String content) throws InvalidRemoteException, TransportException, GitAPIException, IOException private
Definition at line 208 of file PrintBedManager.java.
References com.neuronrobotics.bowlerstudio.printbed.PrintBedManager.file, com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.fileFromGit(), and com.neuronrobotics.bowlerstudio.printbed.PrintBedManager.url.
Referenced by com.neuronrobotics.bowlerstudio.printbed.PrintBedManager.saveLocal().
Member Data Documentation
database
UserManagedPrintBedData com.neuronrobotics.bowlerstudio.printbed.PrintBedManager.database = null private
Definition at line 35 of file PrintBedManager.java.
Referenced by com.neuronrobotics.bowlerstudio.printbed.PrintBedManager.init(), com.neuronrobotics.bowlerstudio.printbed.PrintBedManager.makePrintBeds(), and com.neuronrobotics.bowlerstudio.printbed.PrintBedManager.saveLocal().
file
String com.neuronrobotics.bowlerstudio.printbed.PrintBedManager.file = "printbed.json" static
Definition at line 39 of file PrintBedManager.java.
Referenced by com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getPrintBed(), com.neuronrobotics.bowlerstudio.printbed.PrintBedManager.init(), com.neuronrobotics.bowlerstudio.printbed.PrintBedManager.saveLocal(), and com.neuronrobotics.bowlerstudio.printbed.PrintBedManager.write().
hasPrintBed
boolean com.neuronrobotics.bowlerstudio.printbed.PrintBedManager.hasPrintBed = false private
Definition at line 46 of file PrintBedManager.java.
Referenced by com.neuronrobotics.bowlerstudio.printbed.PrintBedManager.hasPrintBed(), com.neuronrobotics.bowlerstudio.BowlerKernel.processReturnedObjectsStart(), and com.neuronrobotics.bowlerstudio.printbed.PrintBedManager.setHasPrintBed().
names
HashSet<String> com.neuronrobotics.bowlerstudio.printbed.PrintBedManager.names = new HashSet<String>() private
Definition at line 45 of file PrintBedManager.java.
Referenced by com.neuronrobotics.bowlerstudio.printbed.PrintBedManager.init(), and com.neuronrobotics.bowlerstudio.printbed.PrintBedManager.makePrintBeds().
parts
ArrayList<CSG> com.neuronrobotics.bowlerstudio.printbed.PrintBedManager.parts private
Definition at line 44 of file PrintBedManager.java.
Referenced by com.neuronrobotics.bowlerstudio.printbed.PrintBedManager.init(), com.neuronrobotics.bowlerstudio.printbed.PrintBedManager.makePrintBeds(), and com.neuronrobotics.bowlerstudio.printbed.PrintBedManager.PrintBedManager().
url
String com.neuronrobotics.bowlerstudio.printbed.PrintBedManager.url private
Definition at line 41 of file PrintBedManager.java.
Referenced by com.neuronrobotics.bowlerstudio.printbed.PrintBedManager.init(), com.neuronrobotics.bowlerstudio.printbed.PrintBedManager.makePrintBeds(), com.neuronrobotics.bowlerstudio.printbed.PrintBedManager.PrintBedManager(), and com.neuronrobotics.bowlerstudio.printbed.PrintBedManager.write().
The documentation for this class was generated from the following file:
src/main/java/com/neuronrobotics/bowlerstudio/printbed/PrintBedManager.java