BowlerKernel: com.neuronrobotics.bowlerstudio.vitamins.Purchasing Class Reference
com.neuronrobotics.bowlerstudio.vitamins.Purchasing Class Reference
Static Public Member Functions
static HashMap< String, PurchasingData > getConfiguration (String type, String id)
static void saveDatabase (String type) throws Exception
static String makeJson (String type)
static void newVitamin (String type, String id) throws Exception
static void setParameter (String type, String id, String parameterName, PurchasingData parameter) throws Exception
static HashMap< String, HashMap< String, PurchasingData > > getDatabase (String type)
static ArrayList< String > listVitaminTypes ()
static ArrayList< String > listVitaminSizes (String type)
static ArrayList< String > listVitaminVariants (String type, String size)
static PurchasingData get (String type, String size, String variant)
static String getGitRpoDatabase () throws IOException
static void setGitRpoDatabase (String gitRpoDatabase)
static String getJsonRootDir ()
static void setJsonRootDir (String jsonRootDir)
Static Private Member Functions
static String getRootFolder ()
Static Private Attributes
static String jsonRootDir = "json/"
static final Map< String, CSG > fileLastLoaded = new HashMap<String, CSG>()
static final Map< String, HashMap< String, HashMap< String, PurchasingData > > > databaseSet
static final String defaultgitRpoDatabase = "https://github.com/CommonWealthRobotics/Hardware-Purchasing.git"
static String gitRpoDatabase = defaultgitRpoDatabase
static Type TT_mapStringString
static Gson gson = new GsonBuilder().disableHtmlEscaping().setPrettyPrinting().create()
static boolean checked
Detailed Description
Definition at line 46 of file Purchasing.java.
Member Function Documentation
get()
static PurchasingData com.neuronrobotics.bowlerstudio.vitamins.Purchasing.get (String type, String size, String variant) static
Definition at line 243 of file Purchasing.java.
References com.neuronrobotics.bowlerstudio.vitamins.Purchasing.getDatabase().
Referenced by com.neuronrobotics.bowlerstudio.vitamins.Vitamins.get().
getConfiguration()
static HashMap<String, PurchasingData> com.neuronrobotics.bowlerstudio.vitamins.Purchasing.getConfiguration (String type, String id) static
Definition at line 62 of file Purchasing.java.
References com.neuronrobotics.bowlerstudio.vitamins.Purchasing.getDatabase().
Referenced by com.neuronrobotics.bowlerstudio.vitamins.Purchasing.newVitamin(), and com.neuronrobotics.bowlerstudio.vitamins.Purchasing.setParameter().
getDatabase()
static HashMap<String, HashMap<String, PurchasingData> > com.neuronrobotics.bowlerstudio.vitamins.Purchasing.getDatabase (String type) static
Definition at line 128 of file Purchasing.java.
References com.neuronrobotics.bowlerstudio.vitamins.Purchasing.databaseSet, com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.fileFromGit(), com.neuronrobotics.bowlerstudio.vitamins.Purchasing.getGitRpoDatabase(), com.neuronrobotics.bowlerstudio.vitamins.Purchasing.getRootFolder(), com.neuronrobotics.bowlerstudio.vitamins.Purchasing.gson, and com.neuronrobotics.bowlerstudio.vitamins.Purchasing.TT_mapStringString.
Referenced by com.neuronrobotics.bowlerstudio.vitamins.Purchasing.get(), com.neuronrobotics.bowlerstudio.vitamins.Purchasing.getConfiguration(), com.neuronrobotics.bowlerstudio.vitamins.Purchasing.listVitaminSizes(), com.neuronrobotics.bowlerstudio.vitamins.Purchasing.listVitaminVariants(), com.neuronrobotics.bowlerstudio.vitamins.Purchasing.makeJson(), and com.neuronrobotics.bowlerstudio.vitamins.Purchasing.newVitamin().
getGitRpoDatabase()
static String com.neuronrobotics.bowlerstudio.vitamins.Purchasing.getGitRpoDatabase () throws IOException static
Definition at line 253 of file Purchasing.java.
References com.neuronrobotics.bowlerstudio.vitamins.Purchasing.gitRpoDatabase.
Referenced by com.neuronrobotics.bowlerstudio.vitamins.Purchasing.getDatabase(), com.neuronrobotics.bowlerstudio.vitamins.Purchasing.listVitaminTypes(), and com.neuronrobotics.bowlerstudio.vitamins.Purchasing.saveDatabase().
getJsonRootDir()
static String com.neuronrobotics.bowlerstudio.vitamins.Purchasing.getJsonRootDir () static
Definition at line 261 of file Purchasing.java.
References com.neuronrobotics.bowlerstudio.vitamins.Purchasing.jsonRootDir.
Referenced by com.neuronrobotics.bowlerstudio.vitamins.Purchasing.getRootFolder().
getRootFolder()
static String com.neuronrobotics.bowlerstudio.vitamins.Purchasing.getRootFolder () static private
Definition at line 164 of file Purchasing.java.
References com.neuronrobotics.bowlerstudio.vitamins.Purchasing.getJsonRootDir().
Referenced by com.neuronrobotics.bowlerstudio.vitamins.Purchasing.getDatabase(), com.neuronrobotics.bowlerstudio.vitamins.Purchasing.listVitaminTypes(), and com.neuronrobotics.bowlerstudio.vitamins.Purchasing.saveDatabase().
listVitaminSizes()
static ArrayList<String> com.neuronrobotics.bowlerstudio.vitamins.Purchasing.listVitaminSizes (String type) static
Definition at line 193 of file Purchasing.java.
References com.neuronrobotics.bowlerstudio.vitamins.Purchasing.getDatabase().
listVitaminTypes()
static ArrayList<String> com.neuronrobotics.bowlerstudio.vitamins.Purchasing.listVitaminTypes () static
Definition at line 168 of file Purchasing.java.
References com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.fileFromGit(), com.neuronrobotics.bowlerstudio.vitamins.Purchasing.getGitRpoDatabase(), and com.neuronrobotics.bowlerstudio.vitamins.Purchasing.getRootFolder().
listVitaminVariants()
static ArrayList<String> com.neuronrobotics.bowlerstudio.vitamins.Purchasing.listVitaminVariants (String type, String size) static
Definition at line 207 of file Purchasing.java.
References com.neuronrobotics.bowlerstudio.vitamins.PurchasingData.getAPIUrl(), com.neuronrobotics.bowlerstudio.vitamins.PurchasingData.getCartUrl(), and com.neuronrobotics.bowlerstudio.vitamins.Purchasing.getDatabase().
makeJson()
static String com.neuronrobotics.bowlerstudio.vitamins.Purchasing.makeJson (String type) static
Definition at line 92 of file Purchasing.java.
References com.neuronrobotics.bowlerstudio.vitamins.Purchasing.getDatabase(), com.neuronrobotics.bowlerstudio.vitamins.Purchasing.gson, and com.neuronrobotics.bowlerstudio.vitamins.Purchasing.TT_mapStringString.
Referenced by com.neuronrobotics.bowlerstudio.vitamins.Purchasing.saveDatabase().
newVitamin()
static void com.neuronrobotics.bowlerstudio.vitamins.Purchasing.newVitamin (String type, String id) throws Exception static
Definition at line 96 of file Purchasing.java.
References com.neuronrobotics.bowlerstudio.vitamins.Purchasing.getConfiguration(), and com.neuronrobotics.bowlerstudio.vitamins.Purchasing.getDatabase().
saveDatabase()
static void com.neuronrobotics.bowlerstudio.vitamins.Purchasing.saveDatabase (String type) throws Exception static
Definition at line 71 of file Purchasing.java.
References com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getFullBranch(), com.neuronrobotics.bowlerstudio.vitamins.Purchasing.getGitRpoDatabase(), com.neuronrobotics.bowlerstudio.vitamins.Purchasing.getRootFolder(), com.neuronrobotics.bowlerstudio.vitamins.Purchasing.makeJson(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.pushCodeToGit().
setGitRpoDatabase()
static void com.neuronrobotics.bowlerstudio.vitamins.Purchasing.setGitRpoDatabase (String gitRpoDatabase) static
Definition at line 257 of file Purchasing.java.
References com.neuronrobotics.bowlerstudio.vitamins.Purchasing.gitRpoDatabase.
setJsonRootDir()
static void com.neuronrobotics.bowlerstudio.vitamins.Purchasing.setJsonRootDir (String jsonRootDir) static
Definition at line 265 of file Purchasing.java.
References com.neuronrobotics.bowlerstudio.vitamins.Purchasing.jsonRootDir.
setParameter()
static void com.neuronrobotics.bowlerstudio.vitamins.Purchasing.setParameter (String type, String id, String parameterName, PurchasingData parameter) throws Exception static
Definition at line 120 of file Purchasing.java.
References com.neuronrobotics.bowlerstudio.vitamins.Purchasing.getConfiguration().
Member Data Documentation
checked
boolean com.neuronrobotics.bowlerstudio.vitamins.Purchasing.checked static private
Definition at line 59 of file Purchasing.java.
databaseSet
final Map<String, HashMap<String, HashMap<String, PurchasingData> > > com.neuronrobotics.bowlerstudio.vitamins.Purchasing.databaseSet static private
Initial value:
=
      new HashMap<String, HashMap<String, HashMap<String, PurchasingData>>>()
Definition at line 50 of file Purchasing.java.
Referenced by com.neuronrobotics.bowlerstudio.vitamins.Purchasing.getDatabase().
defaultgitRpoDatabase
final String com.neuronrobotics.bowlerstudio.vitamins.Purchasing.defaultgitRpoDatabase = "https://github.com/CommonWealthRobotics/Hardware-Purchasing.git" static private
Definition at line 52 of file Purchasing.java.
fileLastLoaded
final Map<String, CSG> com.neuronrobotics.bowlerstudio.vitamins.Purchasing.fileLastLoaded = new HashMap<String, CSG>() static private
Definition at line 49 of file Purchasing.java.
gitRpoDatabase
String com.neuronrobotics.bowlerstudio.vitamins.Purchasing.gitRpoDatabase = defaultgitRpoDatabase static private
Definition at line 53 of file Purchasing.java.
Referenced by com.neuronrobotics.bowlerstudio.vitamins.Purchasing.getGitRpoDatabase(), and com.neuronrobotics.bowlerstudio.vitamins.Purchasing.setGitRpoDatabase().
gson
Gson com.neuronrobotics.bowlerstudio.vitamins.Purchasing.gson = new GsonBuilder().disableHtmlEscaping().setPrettyPrinting().create() static private
Definition at line 58 of file Purchasing.java.
Referenced by com.neuronrobotics.bowlerstudio.vitamins.Purchasing.getDatabase(), and com.neuronrobotics.bowlerstudio.vitamins.Purchasing.makeJson().
jsonRootDir
String com.neuronrobotics.bowlerstudio.vitamins.Purchasing.jsonRootDir = "json/" static private
Definition at line 48 of file Purchasing.java.
Referenced by com.neuronrobotics.bowlerstudio.vitamins.Purchasing.getJsonRootDir(), and com.neuronrobotics.bowlerstudio.vitamins.Purchasing.setJsonRootDir().
TT_mapStringString
Type com.neuronrobotics.bowlerstudio.vitamins.Purchasing.TT_mapStringString static private
Initial value:
= new TypeToken<HashMap<String, HashMap<String, PurchasingData>>>() {
  }.getType()
Definition at line 55 of file Purchasing.java.
Referenced by com.neuronrobotics.bowlerstudio.vitamins.Purchasing.getDatabase(), and com.neuronrobotics.bowlerstudio.vitamins.Purchasing.makeJson().
The documentation for this class was generated from the following file:
src/main/java/com/neuronrobotics/bowlerstudio/vitamins/Purchasing.java