BowlerKernel: com.neuronrobotics.sdk.pid.VirtualGenericPIDDevice.SyncThread Class Reference
com.neuronrobotics.sdk.pid.VirtualGenericPIDDevice.SyncThread Class Reference
Public Member Functions
void run ()
boolean isPause ()
void setPause (boolean pause)
Private Attributes
boolean sync = false
Boolean pause = false
Detailed Description
This class is designed to simulate a wheel driveing with a perfect controller.
Author
hephaestus
Definition at line 353 of file VirtualGenericPIDDevice.java.
Member Function Documentation
isPause()
boolean com.neuronrobotics.sdk.pid.VirtualGenericPIDDevice.SyncThread.isPause ()
Definition at line 418 of file VirtualGenericPIDDevice.java.
References com.neuronrobotics.sdk.pid.VirtualGenericPIDDevice.SyncThread.pause.
Referenced by com.neuronrobotics.sdk.pid.VirtualGenericPIDDevice.SyncThread.run().
run()
void com.neuronrobotics.sdk.pid.VirtualGenericPIDDevice.SyncThread.run ()
Definition at line 364 of file VirtualGenericPIDDevice.java.
References com.neuronrobotics.sdk.addons.kinematics.IHardwareSyncPulseProvider.doSync(), com.neuronrobotics.sdk.pid.GenericPIDDevice.firePIDEvent(), com.neuronrobotics.sdk.pid.PIDConfiguration.getGroup(), com.neuronrobotics.sdk.pid.VirtualGenericPIDDevice.interpolationEngines, com.neuronrobotics.sdk.pid.VirtualGenericPIDDevice.SyncThread.isPause(), com.neuronrobotics.sdk.pid.VirtualGenericPIDDevice.numChannels, com.neuronrobotics.sdk.pid.VirtualGenericPIDDevice.SyncThread.pause, com.neuronrobotics.sdk.pid.VirtualGenericPIDDevice.runSync, com.neuronrobotics.sdk.pid.PIDEvent.set(), com.neuronrobotics.sdk.pid.VirtualGenericPIDDevice.SyncThread.sync, com.neuronrobotics.sdk.pid.VirtualGenericPIDDevice.threadTime, and com.neuronrobotics.sdk.pid.InterpolationEngine.update().
setPause()
void com.neuronrobotics.sdk.pid.VirtualGenericPIDDevice.SyncThread.setPause (boolean pause)
Definition at line 422 of file VirtualGenericPIDDevice.java.
References com.neuronrobotics.sdk.pid.VirtualGenericPIDDevice.SyncThread.pause.
Referenced by com.neuronrobotics.sdk.pid.VirtualGenericPIDDevice.ResetPIDChannel(), com.neuronrobotics.sdk.pid.VirtualGenericPIDDevice.SetAllPIDSetPoint(), and com.neuronrobotics.sdk.pid.VirtualGenericPIDDevice.SetPIDSetPoint().
Member Data Documentation
pause
Boolean com.neuronrobotics.sdk.pid.VirtualGenericPIDDevice.SyncThread.pause = false private
Definition at line 357 of file VirtualGenericPIDDevice.java.
Referenced by com.neuronrobotics.sdk.pid.VirtualGenericPIDDevice.SyncThread.isPause(), com.neuronrobotics.sdk.pid.VirtualGenericPIDDevice.SyncThread.run(), and com.neuronrobotics.sdk.pid.VirtualGenericPIDDevice.SyncThread.setPause().
sync
boolean com.neuronrobotics.sdk.pid.VirtualGenericPIDDevice.SyncThread.sync = false private
The pause.
Definition at line 356 of file VirtualGenericPIDDevice.java.
Referenced by com.neuronrobotics.sdk.pid.VirtualGenericPIDDevice.SyncThread.run().
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/pid/VirtualGenericPIDDevice.java