BowlerKernel: com.neuronrobotics.bowlerstudio.physics.HingeCSGPhysicsManager Class Reference
com.neuronrobotics.bowlerstudio.physics.HingeCSGPhysicsManager Class Reference
Public Member Functions
HingeCSGPhysicsManager (ArrayList< CSG > baseCSG, Transform pose, double mass, PhysicsCore c)
void update (float timeStep)
HingeConstraint getConstraint ()
void setConstraint (HingeConstraint constraint)
double getTarget ()
void setTarget (double target)
void setMuscleStrength (double muscleStrength)
IClosedLoopController getController ()
void setController (IClosedLoopController controller)
Public Member Functions inherited from com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager
CSGPhysicsManager (List< CSG > baseCSG, Transform pose, double mass, boolean adjustCenter, PhysicsCore core)
CSGPhysicsManager (ArrayList< CSG > baseCSG, Vector3f start, double mass, PhysicsCore core)
void setup (CollisionShape fallShape, Transform pose, double mass, PhysicsCore core)
RigidBody getFallRigidBody ()
void setFallRigidBody (RigidBody fallRigidBody)
List< CSG > getBaseCSG ()
void setBaseCSG (List< CSG > baseCSG)
Transform getUpdateTransform ()
Affine getRigidBodyLocation ()
IPhysicsUpdate getUpdateManager ()
void setUpdateManager (IPhysicsUpdate updateManager)
PhysicsCore getCore ()
void setCore (PhysicsCore core)
Static Public Member Functions
static float getMuscleStrength ()
static void setMuscleStrength (float ms)
Static Public Member Functions inherited from com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager
static CSG getBoundingBox (CSG incoming)
Private Attributes
HingeConstraint constraint = null
IClosedLoopController controller = null
double target = 0
double velocity
Static Private Attributes
static float muscleStrength = (float) 1000
Additional Inherited Members
Protected Member Functions inherited from com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager
CSG loadCSGToPoints (CSG baseCSG, boolean adjustCenter, Transform pose, ObjectArrayList< Vector3f > arg0)
Protected Attributes inherited from com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager
List< CSG > baseCSG = null
Detailed Description
Definition at line 15 of file HingeCSGPhysicsManager.java.
Constructor & Destructor Documentation
HingeCSGPhysicsManager()
com.neuronrobotics.bowlerstudio.physics.HingeCSGPhysicsManager.HingeCSGPhysicsManager (ArrayList< CSG > baseCSG, Transform pose, double mass, PhysicsCore c)
Definition at line 24 of file HingeCSGPhysicsManager.java.
References com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager.baseCSG.
Member Function Documentation
getConstraint()
HingeConstraint com.neuronrobotics.bowlerstudio.physics.HingeCSGPhysicsManager.getConstraint ()
Definition at line 57 of file HingeCSGPhysicsManager.java.
References com.neuronrobotics.bowlerstudio.physics.HingeCSGPhysicsManager.constraint.
getController()
IClosedLoopController com.neuronrobotics.bowlerstudio.physics.HingeCSGPhysicsManager.getController ()
Definition at line 85 of file HingeCSGPhysicsManager.java.
References com.neuronrobotics.bowlerstudio.physics.HingeCSGPhysicsManager.controller.
Referenced by com.neuronrobotics.bowlerstudio.physics.HingeCSGPhysicsManager.update().
getMuscleStrength()
static float com.neuronrobotics.bowlerstudio.physics.HingeCSGPhysicsManager.getMuscleStrength () static
Definition at line 73 of file HingeCSGPhysicsManager.java.
References com.neuronrobotics.bowlerstudio.physics.HingeCSGPhysicsManager.muscleStrength.
Referenced by com.neuronrobotics.bowlerstudio.physics.HingeCSGPhysicsManager.update().
getTarget()
double com.neuronrobotics.bowlerstudio.physics.HingeCSGPhysicsManager.getTarget ()
Definition at line 65 of file HingeCSGPhysicsManager.java.
References com.neuronrobotics.bowlerstudio.physics.HingeCSGPhysicsManager.target.
Referenced by com.neuronrobotics.bowlerstudio.physics.HingeCSGPhysicsManager.update().
setConstraint()
void com.neuronrobotics.bowlerstudio.physics.HingeCSGPhysicsManager.setConstraint (HingeConstraint constraint)
Definition at line 61 of file HingeCSGPhysicsManager.java.
References com.neuronrobotics.bowlerstudio.physics.HingeCSGPhysicsManager.constraint.
Referenced by com.neuronrobotics.bowlerstudio.physics.MobileBasePhysicsManager.MobileBasePhysicsManager(), and com.neuronrobotics.bowlerstudio.physics.HingeCSGPhysicsManager.update().
setController()
void com.neuronrobotics.bowlerstudio.physics.HingeCSGPhysicsManager.setController (IClosedLoopController controller)
Definition at line 89 of file HingeCSGPhysicsManager.java.
References com.neuronrobotics.bowlerstudio.physics.HingeCSGPhysicsManager.controller.
Referenced by com.neuronrobotics.bowlerstudio.physics.MobileBasePhysicsManager.MobileBasePhysicsManager().
setMuscleStrength() [1/2]
void com.neuronrobotics.bowlerstudio.physics.HingeCSGPhysicsManager.setMuscleStrength (double muscleStrength)
Definition at line 81 of file HingeCSGPhysicsManager.java.
References com.neuronrobotics.bowlerstudio.physics.HingeCSGPhysicsManager.muscleStrength, and com.neuronrobotics.bowlerstudio.physics.HingeCSGPhysicsManager.setMuscleStrength().
setMuscleStrength() [2/2]
static void com.neuronrobotics.bowlerstudio.physics.HingeCSGPhysicsManager.setMuscleStrength (float ms) static
Definition at line 77 of file HingeCSGPhysicsManager.java.
References com.neuronrobotics.bowlerstudio.physics.HingeCSGPhysicsManager.muscleStrength.
Referenced by com.neuronrobotics.bowlerstudio.physics.MobileBasePhysicsManager.MobileBasePhysicsManager(), and com.neuronrobotics.bowlerstudio.physics.HingeCSGPhysicsManager.setMuscleStrength().
setTarget()
void com.neuronrobotics.bowlerstudio.physics.HingeCSGPhysicsManager.setTarget (double target)
Definition at line 69 of file HingeCSGPhysicsManager.java.
References com.neuronrobotics.bowlerstudio.physics.HingeCSGPhysicsManager.target.
Referenced by com.neuronrobotics.bowlerstudio.physics.MobileBasePhysicsManager.MobileBasePhysicsManager().
update()
void com.neuronrobotics.bowlerstudio.physics.HingeCSGPhysicsManager.update (float timeStep)
Run the update for this ridgid body. Run any controllers for links
Reimplemented from com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager.
Definition at line 31 of file HingeCSGPhysicsManager.java.
References com.neuronrobotics.bowlerstudio.physics.PhysicsCore.add(), com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager.baseCSG, com.neuronrobotics.sdk.common.IClosedLoopController.compute(), com.neuronrobotics.bowlerstudio.physics.HingeCSGPhysicsManager.constraint, com.neuronrobotics.bowlerstudio.physics.HingeCSGPhysicsManager.getController(), com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager.getCore(), com.neuronrobotics.bowlerstudio.physics.HingeCSGPhysicsManager.getMuscleStrength(), com.neuronrobotics.bowlerstudio.physics.HingeCSGPhysicsManager.getTarget(), com.neuronrobotics.bowlerstudio.physics.PhysicsCore.remove(), com.neuronrobotics.bowlerstudio.physics.HingeCSGPhysicsManager.setConstraint(), and com.neuronrobotics.bowlerstudio.physics.HingeCSGPhysicsManager.velocity.
Member Data Documentation
constraint
HingeConstraint com.neuronrobotics.bowlerstudio.physics.HingeCSGPhysicsManager.constraint = null private
Definition at line 17 of file HingeCSGPhysicsManager.java.
Referenced by com.neuronrobotics.bowlerstudio.physics.HingeCSGPhysicsManager.getConstraint(), com.neuronrobotics.bowlerstudio.physics.HingeCSGPhysicsManager.setConstraint(), and com.neuronrobotics.bowlerstudio.physics.HingeCSGPhysicsManager.update().
controller
IClosedLoopController com.neuronrobotics.bowlerstudio.physics.HingeCSGPhysicsManager.controller = null private
Definition at line 18 of file HingeCSGPhysicsManager.java.
Referenced by com.neuronrobotics.bowlerstudio.physics.HingeCSGPhysicsManager.getController(), and com.neuronrobotics.bowlerstudio.physics.HingeCSGPhysicsManager.setController().
muscleStrength
float com.neuronrobotics.bowlerstudio.physics.HingeCSGPhysicsManager.muscleStrength = (float) 1000 static private
Definition at line 20 of file HingeCSGPhysicsManager.java.
Referenced by com.neuronrobotics.bowlerstudio.physics.HingeCSGPhysicsManager.getMuscleStrength(), and com.neuronrobotics.bowlerstudio.physics.HingeCSGPhysicsManager.setMuscleStrength().
target
double com.neuronrobotics.bowlerstudio.physics.HingeCSGPhysicsManager.target = 0 private
Definition at line 19 of file HingeCSGPhysicsManager.java.
Referenced by com.neuronrobotics.bowlerstudio.physics.HingeCSGPhysicsManager.getTarget(), and com.neuronrobotics.bowlerstudio.physics.HingeCSGPhysicsManager.setTarget().
velocity
double com.neuronrobotics.bowlerstudio.physics.HingeCSGPhysicsManager.velocity private
Definition at line 22 of file HingeCSGPhysicsManager.java.
Referenced by com.neuronrobotics.bowlerstudio.physics.HingeCSGPhysicsManager.update().
The documentation for this class was generated from the following file:
src/main/java/com/neuronrobotics/bowlerstudio/physics/HingeCSGPhysicsManager.java