BowlerKernel: eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMesh Class Reference
eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMesh Class Reference
Public Member Functions
PolygonMesh ()
PolygonMesh (float[] points, float[] texCoords, int[][] faces)
ObservableFloatArray getPoints ()
ObservableFloatArray getTexCoords ()
ObservableIntegerArray getFaceSmoothingGroups ()
int getNumEdgesInFaces ()
int getPointElementSize ()
int getTexCoordElementSize ()
int getFaceElementSize ()
Public Attributes
int[][] faces = new int[0][0]
Protected Attributes
int numEdgesInFaces = -1
Private Attributes
final ObservableFloatArray points = FXCollections.observableFloatArray()
final ObservableFloatArray texCoords = FXCollections.observableFloatArray()
final ObservableIntegerArray faceSmoothingGroups = FXCollections.observableIntegerArray()
Static Private Attributes
static final int NUM_COMPONENTS_PER_POINT = 3
static final int NUM_COMPONENTS_PER_TEXCOORD = 2
static final int NUM_COMPONENTS_PER_FACE = 6
Detailed Description
A Mesh where each face can be a Polygon
can convert to using ObservableIntegerArray.
Definition at line 44 of file PolygonMesh.java.
Constructor & Destructor Documentation
PolygonMesh() [1/2]
eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMesh.PolygonMesh ()
Instantiates a new polygon mesh.
Definition at line 64 of file PolygonMesh.java.
PolygonMesh() [2/2]
eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMesh.PolygonMesh (float[] points, float[] texCoords, int faces[][])
Instantiates a new polygon mesh.
Parameters
points the points
texCoords the tex coords
faces the faces
Definition at line 73 of file PolygonMesh.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMesh.faces, eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMesh.points, and eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMesh.texCoords.
Member Function Documentation
getFaceElementSize()
int eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMesh.getFaceElementSize ()
Gets the face element size.
Returns
the face element size
Definition at line 155 of file PolygonMesh.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMesh.NUM_COMPONENTS_PER_FACE.
getFaceSmoothingGroups()
ObservableIntegerArray eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMesh.getFaceSmoothingGroups ()
Gets the face smoothing groups.
Returns
the face smoothing groups
Definition at line 102 of file PolygonMesh.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMesh.faceSmoothingGroups.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.addMesh(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicPolygonMesh.SymbolicPolygonMesh(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.update(), and eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.updateMesh().
getNumEdgesInFaces()
int eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMesh.getNumEdgesInFaces ()
Gets the num edges in faces.
Returns
the num edges in faces
Definition at line 111 of file PolygonMesh.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMesh.faces, and eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMesh.numEdgesInFaces.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.updateMesh().
getPointElementSize()
int eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMesh.getPointElementSize ()
Gets the point element size.
Returns
the point element size
Definition at line 137 of file PolygonMesh.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMesh.NUM_COMPONENTS_PER_POINT.
getPoints()
ObservableFloatArray eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMesh.getPoints ()
Gets the points.
Returns
the points
Definition at line 84 of file PolygonMesh.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMesh.points.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.addMesh(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.OriginalPointArray.OriginalPointArray(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.subdivisionLevelProperty(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.SubdivisionMesh(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.update(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.OriginalPointArray.update(), and eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.updateMesh().
getTexCoordElementSize()
int eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMesh.getTexCoordElementSize ()
Gets the tex coord element size.
Returns
the tex coord element size
Definition at line 146 of file PolygonMesh.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMesh.NUM_COMPONENTS_PER_TEXCOORD.
getTexCoords()
ObservableFloatArray eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMesh.getTexCoords ()
Gets the tex coords.
Returns
the tex coords
Definition at line 93 of file PolygonMesh.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMesh.texCoords.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.addMesh(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.SubdivisionMesh(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicPolygonMesh.SymbolicPolygonMesh(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.update(), and eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.updateMesh().
Member Data Documentation
faces
int [][] eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMesh.faces = new int[0][0]
The faces.
Definition at line 53 of file PolygonMesh.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.addMesh(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMesh.getNumEdgesInFaces(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMesh.PolygonMesh(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicPolygonMesh.SymbolicPolygonMesh(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.update(), and eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.updateMesh().
faceSmoothingGroups
final ObservableIntegerArray eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMesh.faceSmoothingGroups = FXCollections.observableIntegerArray() private
The face smoothing groups.
Definition at line 56 of file PolygonMesh.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMesh.getFaceSmoothingGroups().
NUM_COMPONENTS_PER_FACE
final int eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMesh.NUM_COMPONENTS_PER_FACE = 6 static private
The Constant NUM_COMPONENTS_PER_FACE.
Definition at line 130 of file PolygonMesh.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMesh.getFaceElementSize().
NUM_COMPONENTS_PER_POINT
final int eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMesh.NUM_COMPONENTS_PER_POINT = 3 static private
The Constant NUM_COMPONENTS_PER_POINT.
Definition at line 124 of file PolygonMesh.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMesh.getPointElementSize().
NUM_COMPONENTS_PER_TEXCOORD
final int eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMesh.NUM_COMPONENTS_PER_TEXCOORD = 2 static private
The Constant NUM_COMPONENTS_PER_TEXCOORD.
Definition at line 127 of file PolygonMesh.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMesh.getTexCoordElementSize().
numEdgesInFaces
int eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMesh.numEdgesInFaces = -1 protected
The num edges in faces.
Definition at line 59 of file PolygonMesh.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMesh.getNumEdgesInFaces(), and eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.update().
points
final ObservableFloatArray eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMesh.points = FXCollections.observableFloatArray() private
The points.
Definition at line 47 of file PolygonMesh.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMesh.getPoints(), and eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMesh.PolygonMesh().
texCoords
final ObservableFloatArray eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMesh.texCoords = FXCollections.observableFloatArray() private
The tex coords.
Definition at line 50 of file PolygonMesh.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMesh.getTexCoords(), and eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMesh.PolygonMesh().
The documentation for this class was generated from the following file:
JCSG/src/main/java/eu/mihosoft/vrl/v3d/ext/openjfx/shape3d/PolygonMesh.java