BowlerKernel: com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.SchedulerThread Class Reference
com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.SchedulerThread Class Reference
Public Member Functions
SchedulerThread (double ms, final long so)
void playStep ()
void run ()
void pause ()
void kill ()
boolean isRun ()
boolean isPause ()
void setPause (boolean pause)
Private Attributes
double time
boolean run = true
boolean pause = false
Detailed Description
The Class SchedulerThread.
Definition at line 523 of file CoreScheduler.java.
Constructor & Destructor Documentation
SchedulerThread()
com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.SchedulerThread.SchedulerThread (double ms, final long so)
Instantiates a new scheduler thread.
Parameters
ms the ms
so the so
Definition at line 543 of file CoreScheduler.java.
References com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.getLoopTime(), com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.getOutputs(), com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.mp3, com.neuronrobotics.sdk.dyio.sequencer.SequencerWAV.setCurrentTime(), com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.StartOffset, and com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.SchedulerThread.time.
Member Function Documentation
isPause()
boolean com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.SchedulerThread.isPause ()
Checks if is pause.
Returns
true, if is pause
Definition at line 641 of file CoreScheduler.java.
References com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.SchedulerThread.pause.
Referenced by com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.isPlaying().
isRun()
boolean com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.SchedulerThread.isRun ()
Checks if is run.
Returns
true, if is run
Definition at line 627 of file CoreScheduler.java.
References com.neuronrobotics.sdk.dyio.sequencer.SequencerWAV.isPlaying(), com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.mp3, and com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.SchedulerThread.run.
Referenced by com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.SchedulerThread.run().
kill()
void com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.SchedulerThread.kill ()
Kill.
Definition at line 615 of file CoreScheduler.java.
References com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.mp3, com.neuronrobotics.sdk.dyio.sequencer.SequencerWAV.pause(), and com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.SchedulerThread.setPause().
Referenced by com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.SchedulerThread.playStep().
pause()
void com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.SchedulerThread.pause ()
Pause.
Definition at line 605 of file CoreScheduler.java.
References com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.mp3, com.neuronrobotics.sdk.dyio.sequencer.SequencerWAV.pause(), and com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.SchedulerThread.setPause().
playStep()
void com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.SchedulerThread.playStep ()
Play step.
Definition at line 558 of file CoreScheduler.java.
References com.neuronrobotics.sdk.dyio.sequencer.SequencerWAV.getCurrentTime(), com.neuronrobotics.sdk.dyio.sequencer.SequencerWAV.isPlaying(), com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.SchedulerThread.kill(), com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.mp3, com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.setCurrentTime(), com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.StartOffset, and com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.SchedulerThread.time.
Referenced by com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.playStep(), and com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.SchedulerThread.run().
run()
void com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.SchedulerThread.run ()
Definition at line 582 of file CoreScheduler.java.
References com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.callPause(), com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.callReset(), com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.getLoopTime(), com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.SchedulerThread.isRun(), com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.SchedulerThread.pause, com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.SchedulerThread.playStep(), com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.setCurrentTime(), com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.SchedulerThread.setPause(), and com.neuronrobotics.sdk.util.ThreadUtil.wait().
setPause()
void com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.SchedulerThread.setPause (boolean pause)
Sets the pause.
Parameters
pause the new pause
Definition at line 650 of file CoreScheduler.java.
References com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.SchedulerThread.pause.
Referenced by com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.SchedulerThread.kill(), com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.SchedulerThread.pause(), com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.play(), com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.SchedulerThread.run(), and com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.setSt().
Member Data Documentation
pause
boolean com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.SchedulerThread.pause = false private
The pause.
Definition at line 535 of file CoreScheduler.java.
Referenced by com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.SchedulerThread.isPause(), com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.pause(), com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.SchedulerThread.run(), and com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.SchedulerThread.setPause().
run
boolean com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.SchedulerThread.run = true private
The run.
Definition at line 529 of file CoreScheduler.java.
Referenced by com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.SchedulerThread.isRun().
time
double com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.SchedulerThread.time private
The time.
Definition at line 526 of file CoreScheduler.java.
Referenced by com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.SchedulerThread.playStep(), and com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.SchedulerThread.SchedulerThread().
The documentation for this class was generated from the following file:
src/main/java/com/neuronrobotics/sdk/dyio/sequencer/CoreScheduler.java