BowlerKernel: com.neuronrobotics.sdk.dyio.DyIOChannelEvent Class Reference
com.neuronrobotics.sdk.dyio.DyIOChannelEvent Class Reference
Public Member Functions
DyIOChannelEvent (DyIOChannel channel, ByteList data)
DyIOChannelEvent (DyIOChannel c, Integer integer)
DyIOChannel getChannel ()
ByteList getData ()
int getValue ()
int getUnsignedValue ()
int getSignedValue ()
Private Attributes
ByteList data
DyIOChannel channel
Integer integer
Detailed Description
a DyIO Channel Event.
Author
rbreznak
Definition at line 25 of file DyIOChannelEvent.java.
Constructor & Destructor Documentation
DyIOChannelEvent() [1/2]
com.neuronrobotics.sdk.dyio.DyIOChannelEvent.DyIOChannelEvent (DyIOChannel channel, ByteList data)
Instantiates a new dy io channel event.
Parameters
channel the channel
data the data
Definition at line 42 of file DyIOChannelEvent.java.
References com.neuronrobotics.sdk.dyio.DyIOChannelEvent.channel, and com.neuronrobotics.sdk.dyio.DyIOChannelEvent.data.
DyIOChannelEvent() [2/2]
com.neuronrobotics.sdk.dyio.DyIOChannelEvent.DyIOChannelEvent (DyIOChannel c, Integer integer)
Instantiates a new dy io channel event.
Parameters
c the c
integer the integer
Definition at line 53 of file DyIOChannelEvent.java.
References com.neuronrobotics.sdk.dyio.DyIOChannelEvent.integer.
Member Function Documentation
getChannel()
DyIOChannel com.neuronrobotics.sdk.dyio.DyIOChannelEvent.getChannel ()
Gets the channel.
Returns
the channel
Definition at line 65 of file DyIOChannelEvent.java.
References com.neuronrobotics.sdk.dyio.DyIOChannelEvent.channel.
Referenced by com.neuronrobotics.sdk.dyio.DyIOChannelEvent.getValue(), and com.neuronrobotics.application.xmpp.DyIOConversation.ChatAsyncListener.onChannelEvent().
getData()
ByteList com.neuronrobotics.sdk.dyio.DyIOChannelEvent.getData ()
Gets the data.
Returns
the data
Definition at line 74 of file DyIOChannelEvent.java.
References com.neuronrobotics.sdk.dyio.DyIOChannelEvent.data.
Referenced by com.neuronrobotics.sdk.dyio.DyIOChannelEvent.getSignedValue(), com.neuronrobotics.sdk.dyio.DyIOChannelEvent.getUnsignedValue(), com.neuronrobotics.sdk.dyio.peripherals.PPMReaderChannel.onChannelEvent(), com.neuronrobotics.sdk.dyio.peripherals.SPIChannel.onChannelEvent(), and com.neuronrobotics.sdk.dyio.peripherals.UARTChannel.UARTRxChannel.onChannelEvent().
getSignedValue()
int com.neuronrobotics.sdk.dyio.DyIOChannelEvent.getSignedValue ()
Gets the signed value.
Returns
the signed value
Definition at line 120 of file DyIOChannelEvent.java.
References com.neuronrobotics.sdk.common.ByteList.convertToInt(), com.neuronrobotics.sdk.dyio.DyIOChannelEvent.getData(), and com.neuronrobotics.sdk.dyio.DyIOChannelEvent.integer.
Referenced by com.neuronrobotics.sdk.dyio.DyIOChannelEvent.getValue(), com.neuronrobotics.sdk.dyio.peripherals.CounterInputChannel.onChannelEvent(), and com.neuronrobotics.sdk.dyio.peripherals.CounterOutputChannel.onChannelEvent().
getUnsignedValue()
int com.neuronrobotics.sdk.dyio.DyIOChannelEvent.getUnsignedValue ()
Gets the unsigned value.
Returns
the unsigned value
Definition at line 109 of file DyIOChannelEvent.java.
References com.neuronrobotics.sdk.common.ByteList.convertToInt(), com.neuronrobotics.sdk.dyio.DyIOChannelEvent.getData(), and com.neuronrobotics.sdk.dyio.DyIOChannelEvent.integer.
Referenced by com.neuronrobotics.sdk.dyio.DyIOChannelEvent.getValue(), com.neuronrobotics.sdk.dyio.peripherals.AnalogInputChannel.onChannelEvent(), com.neuronrobotics.sdk.dyio.peripherals.DigitalInputChannel.onChannelEvent(), and com.neuronrobotics.sdk.dyio.peripherals.ServoChannel.onChannelEvent().
getValue()
int com.neuronrobotics.sdk.dyio.DyIOChannelEvent.getValue ()
Gets the value.
Returns
the value
Definition at line 83 of file DyIOChannelEvent.java.
References com.neuronrobotics.sdk.dyio.DyIOChannelEvent.channel, com.neuronrobotics.sdk.dyio.DyIOChannelEvent.getChannel(), com.neuronrobotics.sdk.dyio.DyIOChannel.getCurrentMode(), com.neuronrobotics.sdk.dyio.DyIOChannelEvent.getSignedValue(), com.neuronrobotics.sdk.dyio.DyIOChannelEvent.getUnsignedValue(), com.neuronrobotics.sdk.dyio.DyIOChannelEvent.integer, and com.neuronrobotics.sdk.dyio.DyIOChannel.isStreamChannel().
Referenced by com.neuronrobotics.sdk.dyio.DyIO.getAllChannelValues(), com.neuronrobotics.sdk.dyio.DyIOChannel.getValue(), com.neuronrobotics.application.xmpp.DyIOConversation.ChatAsyncListener.onChannelEvent(), and com.neuronrobotics.sdk.dyio.DyIOChannel.parseDyIOChannelEvent().
Member Data Documentation
channel
DyIOChannel com.neuronrobotics.sdk.dyio.DyIOChannelEvent.channel private
The channel.
Definition at line 31 of file DyIOChannelEvent.java.
Referenced by com.neuronrobotics.sdk.dyio.DyIOChannelEvent.DyIOChannelEvent(), com.neuronrobotics.sdk.dyio.DyIOChannelEvent.getChannel(), and com.neuronrobotics.sdk.dyio.DyIOChannelEvent.getValue().
data
ByteList com.neuronrobotics.sdk.dyio.DyIOChannelEvent.data private
The data.
Definition at line 28 of file DyIOChannelEvent.java.
Referenced by com.neuronrobotics.sdk.dyio.DyIOChannelEvent.DyIOChannelEvent(), and com.neuronrobotics.sdk.dyio.DyIOChannelEvent.getData().
integer
Integer com.neuronrobotics.sdk.dyio.DyIOChannelEvent.integer private
The integer.
Definition at line 34 of file DyIOChannelEvent.java.
Referenced by com.neuronrobotics.sdk.dyio.DyIOChannelEvent.DyIOChannelEvent(), com.neuronrobotics.sdk.dyio.DyIOChannelEvent.getSignedValue(), com.neuronrobotics.sdk.dyio.DyIOChannelEvent.getUnsignedValue(), and com.neuronrobotics.sdk.dyio.DyIOChannelEvent.getValue().
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/dyio/DyIOChannelEvent.java