BowlerKernel: com.neuronrobotics.application.xmpp.GoogleChat.GoogleChatEngine Class Reference
com.neuronrobotics.application.xmpp.GoogleChat.GoogleChatEngine Class Reference
Public Member Functions
GoogleChatEngine (IConversationFactory responder, String user, String pass) throws XMPPException
GoogleChatEngine (IConversationFactory responder, InputStream config) throws XMPPException
void chatCreated (Chat arg0, boolean arg1)
GoogleChat startChat (String user)
GoogleChat startChat (String user, MessageListener listener)
ArrayList< GoogleChat > getChats ()
void disconnect ()
Static Public Member Functions
static String getTagValue (String sTag, Element eElement)
Private Member Functions
void setup (IConversationFactory responder) throws XMPPException
void setLoginInfo (InputStream config)
MessageListener getNewMessageListener ()
Private Attributes
ConnectionConfiguration connConfig
XMPPConnection connection
Presence presence
ChatManager chatmanager
IConversationFactory responder
Static Private Attributes
static String username = "user@gmail.com"
static String password = "pass1234"
static String host = "talk.google.com"
static String service = "gmail.com"
static int port = 5222
Detailed Description
The Class GoogleChatEngine.
Definition at line 36 of file GoogleChatEngine.java.
Constructor & Destructor Documentation
GoogleChatEngine() [1/2]
com.neuronrobotics.application.xmpp.GoogleChat.GoogleChatEngine.GoogleChatEngine (IConversationFactory responder, String user, String pass) throws XMPPException
Instantiates a new google chat engine.
Parameters
responder the responder
user the user
pass the pass
Exceptions
XMPPException the XMPP exception
Definition at line 80 of file GoogleChatEngine.java.
References com.neuronrobotics.application.xmpp.GoogleChat.GoogleChatEngine.password, com.neuronrobotics.application.xmpp.GoogleChat.GoogleChatEngine.responder, com.neuronrobotics.application.xmpp.GoogleChat.GoogleChatEngine.setup(), and com.neuronrobotics.application.xmpp.GoogleChat.GoogleChatEngine.username.
GoogleChatEngine() [2/2]
com.neuronrobotics.application.xmpp.GoogleChat.GoogleChatEngine.GoogleChatEngine (IConversationFactory responder, InputStream config) throws XMPPException
Instantiates a new google chat engine.
Parameters
responder the responder
config the config
Exceptions
XMPPException the XMPP exception
Definition at line 93 of file GoogleChatEngine.java.
References com.neuronrobotics.application.xmpp.GoogleChat.GoogleChatEngine.responder, com.neuronrobotics.application.xmpp.GoogleChat.GoogleChatEngine.setLoginInfo(), and com.neuronrobotics.application.xmpp.GoogleChat.GoogleChatEngine.setup().
Member Function Documentation
chatCreated()
void com.neuronrobotics.application.xmpp.GoogleChat.GoogleChatEngine.chatCreated (Chat arg0, boolean arg1)
Definition at line 177 of file GoogleChatEngine.java.
References com.neuronrobotics.application.xmpp.GoogleChat.GoogleChatEngine.getNewMessageListener().
disconnect()
void com.neuronrobotics.application.xmpp.GoogleChat.GoogleChatEngine.disconnect ()
Disconnect.
Definition at line 233 of file GoogleChatEngine.java.
References com.neuronrobotics.application.xmpp.GoogleChat.GoogleChatEngine.connection.
getChats()
ArrayList<GoogleChat> com.neuronrobotics.application.xmpp.GoogleChat.GoogleChatEngine.getChats ()
Gets the chats.
Returns
the chats
Definition at line 215 of file GoogleChatEngine.java.
getNewMessageListener()
MessageListener com.neuronrobotics.application.xmpp.GoogleChat.GoogleChatEngine.getNewMessageListener () private
Gets the new message listener.
Returns
the new message listener
Definition at line 169 of file GoogleChatEngine.java.
References com.neuronrobotics.application.xmpp.IConversationFactory.getConversation(), and com.neuronrobotics.application.xmpp.GoogleChat.GoogleChatEngine.responder.
Referenced by com.neuronrobotics.application.xmpp.GoogleChat.GoogleChatEngine.chatCreated(), and com.neuronrobotics.application.xmpp.GoogleChat.GoogleChatEngine.startChat().
getTagValue()
static String com.neuronrobotics.application.xmpp.GoogleChat.GoogleChatEngine.getTagValue (String sTag, Element eElement) static
Gets the tag value.
Parameters
sTag the s tag
eElement the e element
Returns
the tag value
Definition at line 157 of file GoogleChatEngine.java.
Referenced by com.neuronrobotics.application.xmpp.GoogleChat.GoogleChatEngine.setLoginInfo().
setLoginInfo()
void com.neuronrobotics.application.xmpp.GoogleChat.GoogleChatEngine.setLoginInfo (InputStream config) private
Sets the login info.
Parameters
config the new login info
Definition at line 123 of file GoogleChatEngine.java.
References com.neuronrobotics.application.xmpp.GoogleChat.GoogleChatEngine.getTagValue(), com.neuronrobotics.application.xmpp.GoogleChat.GoogleChatEngine.password, and com.neuronrobotics.application.xmpp.GoogleChat.GoogleChatEngine.username.
Referenced by com.neuronrobotics.application.xmpp.GoogleChat.GoogleChatEngine.GoogleChatEngine().
setup()
void com.neuronrobotics.application.xmpp.GoogleChat.GoogleChatEngine.setup (IConversationFactory responder) throws XMPPException private
Sets the up.
Parameters
responder the new up
Exceptions
XMPPException the XMPP exception
Definition at line 104 of file GoogleChatEngine.java.
References com.neuronrobotics.application.xmpp.GoogleChat.GoogleChatEngine.chatmanager, com.neuronrobotics.application.xmpp.GoogleChat.GoogleChatEngine.connConfig, com.neuronrobotics.application.xmpp.GoogleChat.GoogleChatEngine.connection, com.neuronrobotics.application.xmpp.GoogleChat.GoogleChatEngine.host, com.neuronrobotics.application.xmpp.GoogleChat.GoogleChatEngine.password, com.neuronrobotics.application.xmpp.GoogleChat.GoogleChatEngine.port, com.neuronrobotics.application.xmpp.GoogleChat.GoogleChatEngine.presence, com.neuronrobotics.application.xmpp.GoogleChat.GoogleChatEngine.responder, com.neuronrobotics.application.xmpp.GoogleChat.GoogleChatEngine.service, and com.neuronrobotics.application.xmpp.GoogleChat.GoogleChatEngine.username.
Referenced by com.neuronrobotics.application.xmpp.GoogleChat.GoogleChatEngine.GoogleChatEngine().
startChat() [1/2]
GoogleChat com.neuronrobotics.application.xmpp.GoogleChat.GoogleChatEngine.startChat (String user)
Start chat.
Parameters
user the user
Returns
the google chat
Definition at line 189 of file GoogleChatEngine.java.
References com.neuronrobotics.application.xmpp.GoogleChat.GoogleChatEngine.chatmanager, and com.neuronrobotics.application.xmpp.GoogleChat.GoogleChatEngine.getNewMessageListener().
startChat() [2/2]
GoogleChat com.neuronrobotics.application.xmpp.GoogleChat.GoogleChatEngine.startChat (String user, MessageListener listener)
Start chat.
Parameters
user the user
listener the listener
Returns
the google chat
Definition at line 203 of file GoogleChatEngine.java.
References com.neuronrobotics.application.xmpp.GoogleChat.GoogleChatEngine.chatmanager.
Member Data Documentation
chatmanager
ChatManager com.neuronrobotics.application.xmpp.GoogleChat.GoogleChatEngine.chatmanager private
The chatmanager.
Definition at line 64 of file GoogleChatEngine.java.
Referenced by com.neuronrobotics.application.xmpp.GoogleChat.GoogleChatEngine.setup(), and com.neuronrobotics.application.xmpp.GoogleChat.GoogleChatEngine.startChat().
connConfig
ConnectionConfiguration com.neuronrobotics.application.xmpp.GoogleChat.GoogleChatEngine.connConfig private
The conn config.
Definition at line 55 of file GoogleChatEngine.java.
Referenced by com.neuronrobotics.application.xmpp.GoogleChat.GoogleChatEngine.setup().
connection
XMPPConnection com.neuronrobotics.application.xmpp.GoogleChat.GoogleChatEngine.connection private
The connection.
Definition at line 58 of file GoogleChatEngine.java.
Referenced by com.neuronrobotics.application.xmpp.GoogleChat.GoogleChatEngine.disconnect(), and com.neuronrobotics.application.xmpp.GoogleChat.GoogleChatEngine.setup().
host
String com.neuronrobotics.application.xmpp.GoogleChat.GoogleChatEngine.host = "talk.google.com" static private
The host.
Definition at line 46 of file GoogleChatEngine.java.
Referenced by com.neuronrobotics.application.xmpp.GoogleChat.GoogleChatEngine.setup().
password
String com.neuronrobotics.application.xmpp.GoogleChat.GoogleChatEngine.password = "pass1234" static private
The password.
Definition at line 42 of file GoogleChatEngine.java.
Referenced by com.neuronrobotics.application.xmpp.GoogleChat.GoogleChatEngine.GoogleChatEngine(), com.neuronrobotics.application.xmpp.GoogleChat.GoogleChatEngine.setLoginInfo(), and com.neuronrobotics.application.xmpp.GoogleChat.GoogleChatEngine.setup().
port
int com.neuronrobotics.application.xmpp.GoogleChat.GoogleChatEngine.port = 5222 static private
The port.
Definition at line 52 of file GoogleChatEngine.java.
Referenced by com.neuronrobotics.application.xmpp.GoogleChat.GoogleChatEngine.setup().
presence
Presence com.neuronrobotics.application.xmpp.GoogleChat.GoogleChatEngine.presence private
The presence.
Definition at line 61 of file GoogleChatEngine.java.
Referenced by com.neuronrobotics.application.xmpp.GoogleChat.GoogleChatEngine.setup().
responder
IConversationFactory com.neuronrobotics.application.xmpp.GoogleChat.GoogleChatEngine.responder private
The responder.
Definition at line 70 of file GoogleChatEngine.java.
Referenced by com.neuronrobotics.application.xmpp.GoogleChat.GoogleChatEngine.getNewMessageListener(), com.neuronrobotics.application.xmpp.GoogleChat.GoogleChatEngine.GoogleChatEngine(), and com.neuronrobotics.application.xmpp.GoogleChat.GoogleChatEngine.setup().
service
String com.neuronrobotics.application.xmpp.GoogleChat.GoogleChatEngine.service = "gmail.com" static private
The service.
Definition at line 49 of file GoogleChatEngine.java.
Referenced by com.neuronrobotics.application.xmpp.GoogleChat.GoogleChatEngine.setup().
username
String com.neuronrobotics.application.xmpp.GoogleChat.GoogleChatEngine.username = "user@gmail.com" static private
The username.
Definition at line 39 of file GoogleChatEngine.java.
Referenced by com.neuronrobotics.application.xmpp.GoogleChat.GoogleChatEngine.GoogleChatEngine(), com.neuronrobotics.application.xmpp.GoogleChat.GoogleChatEngine.setLoginInfo(), and com.neuronrobotics.application.xmpp.GoogleChat.GoogleChatEngine.setup().
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/application/xmpp/GoogleChat/GoogleChatEngine.java