BowlerKernel: eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView Class Reference
eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView Class Reference
Public Member Functions
PolygonMesh getMesh ()
void setMesh (PolygonMesh mesh)
ObjectProperty< PolygonMesh > meshProperty ()
final void setDrawMode (DrawMode value)
final DrawMode getDrawMode ()
final ObjectProperty< DrawMode > drawModeProperty ()
final void setCullFace (CullFace value)
final CullFace getCullFace ()
final ObjectProperty< CullFace > cullFaceProperty ()
Material getMaterial ()
void setMaterial (Material material)
ObjectProperty< Material > materialProperty ()
void setSubdivisionLevel (int subdivisionLevel)
int getSubdivisionLevel ()
SimpleIntegerProperty subdivisionLevelProperty ()
void setBoundaryMode (BoundaryMode boundaryMode)
BoundaryMode getBoundaryMode ()
SimpleObjectProperty< BoundaryMode > boundaryModeProperty ()
void setMapBorderMode (MapBorderMode mapBorderMode)
MapBorderMode getMapBorderMode ()
SimpleObjectProperty< MapBorderMode > mapBorderModeProperty ()
PolygonMeshView ()
PolygonMeshView (PolygonMesh mesh)
Private Member Functions
void updateMesh ()
float distanceBetweenPoints (float x1, float y1, float z1, float x2, float y2, float z2)
Private Attributes
final MeshView meshView = new MeshView()
TriangleMesh triangleMesh = new TriangleMesh()
SubdivisionMesh subdivisionMesh
final ArrayChangeListener< ObservableFloatArray > meshPointsListener
final ArrayChangeListener< ObservableFloatArray > meshTexCoordListener
boolean pointsDirty = true
boolean pointsSizeDirty = true
boolean texCoordsDirty = true
boolean facesDirty = true
ObjectProperty< PolygonMesh > meshProperty
ObjectProperty< DrawMode > drawMode
ObjectProperty< CullFace > cullFace
ObjectProperty< Material > materialProperty = new SimpleObjectProperty<Material>()
SimpleIntegerProperty subdivisionLevelProperty
SimpleObjectProperty< BoundaryMode > boundaryMode
SimpleObjectProperty< MapBorderMode > mapBorderMode
Static Private Attributes
static final boolean DEBUG = false
Detailed Description
A MeshView node for Polygon Meshes.
Definition at line 55 of file PolygonMeshView.java.
Constructor & Destructor Documentation
PolygonMeshView() [1/2]
eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.PolygonMeshView ()
Instantiates a new polygon mesh view.
Definition at line 390 of file PolygonMeshView.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.materialProperty, and eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.meshView.
PolygonMeshView() [2/2]
eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.PolygonMeshView (PolygonMesh mesh)
Instantiates a new polygon mesh view.
Parameters
mesh the mesh
Definition at line 400 of file PolygonMeshView.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.setMesh().
Member Function Documentation
boundaryModeProperty()
SimpleObjectProperty<BoundaryMode> eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.boundaryModeProperty ()
Boundary mode property.
Returns
the simple object property
Definition at line 326 of file PolygonMeshView.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.boundaryMode, eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.getBoundaryMode(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.pointsDirty, eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.setBoundaryMode(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.subdivisionMesh, eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.update(), and eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.updateMesh().
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.setBoundaryMode().
cullFaceProperty()
final ObjectProperty<CullFace> eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.cullFaceProperty ()
Cull face property.
Returns
the object property
Definition at line 211 of file PolygonMeshView.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.cullFace, and eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.meshView.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.setCullFace().
distanceBetweenPoints()
float eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.distanceBetweenPoints (float x1, float y1, float z1, float x2, float y2, float z2) private
Distance between points.
Parameters
x1 the x1
y1 the y1
z1 the z1
x2 the x2
y2 the y2
z2 the z2
Returns
the float
Definition at line 570 of file PolygonMeshView.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.updateMesh().
drawModeProperty()
final ObjectProperty<DrawMode> eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.drawModeProperty ()
Draw mode property.
Returns
the object property
Definition at line 172 of file PolygonMeshView.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.drawMode, eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.facesDirty, eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.meshView, eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.pointsDirty, eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.pointsSizeDirty, eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.texCoordsDirty, and eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.updateMesh().
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.setDrawMode().
getBoundaryMode()
BoundaryMode eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.getBoundaryMode ()
Gets the boundary mode.
Returns
the boundary mode
Definition at line 319 of file PolygonMeshView.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.boundaryMode, and eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.BoundaryMode.CREASE_EDGES.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.boundaryModeProperty(), and eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.subdivisionLevelProperty().
getCullFace()
final CullFace eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.getCullFace ()
Gets the cull face.
Returns
the cull face
Definition at line 204 of file PolygonMeshView.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.cullFace.
getDrawMode()
final DrawMode eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.getDrawMode ()
Gets the draw mode.
Returns
the draw mode
Definition at line 165 of file PolygonMeshView.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.drawMode.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.updateMesh().
getMapBorderMode()
MapBorderMode eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.getMapBorderMode ()
Gets the map border mode.
Returns
the map border mode
Definition at line 361 of file PolygonMeshView.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.mapBorderMode, and eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.MapBorderMode.NOT_SMOOTH.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.mapBorderModeProperty(), and eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.subdivisionLevelProperty().
getMaterial()
Material eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.getMaterial ()
Gets the material.
Returns
the material
Definition at line 236 of file PolygonMeshView.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.materialProperty.
getMesh()
PolygonMesh eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.getMesh ()
Gets the mesh.
Returns
the mesh
Definition at line 109 of file PolygonMeshView.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.meshProperty.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.subdivisionLevelProperty(), and eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.updateMesh().
getSubdivisionLevel()
int eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.getSubdivisionLevel ()
Gets the subdivision level.
Returns
the subdivision level
Definition at line 271 of file PolygonMeshView.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.subdivisionLevelProperty.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.subdivisionLevelProperty().
mapBorderModeProperty()
SimpleObjectProperty<MapBorderMode> eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.mapBorderModeProperty ()
Map border mode property.
Returns
the simple object property
Definition at line 368 of file PolygonMeshView.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.getMapBorderMode(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.mapBorderMode, eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.setMapBorderMode(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.subdivisionMesh, eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.texCoordsDirty, eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.update(), and eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.updateMesh().
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.setMapBorderMode().
materialProperty()
ObjectProperty<Material> eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.materialProperty ()
Material property.
Returns
the object property
Definition at line 250 of file PolygonMeshView.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.materialProperty().
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.materialProperty().
meshProperty()
ObjectProperty<PolygonMesh> eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.meshProperty ()
Mesh property.
Returns
the object property
Definition at line 123 of file PolygonMeshView.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.facesDirty, eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.meshPointsListener, eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.meshProperty, eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.meshTexCoordListener, eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.pointsDirty, eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.pointsSizeDirty, eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.texCoordsDirty, and eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.updateMesh().
setBoundaryMode()
void eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.setBoundaryMode (BoundaryMode boundaryMode)
Sets the boundary mode.
Parameters
boundaryMode the new boundary mode
Definition at line 312 of file PolygonMeshView.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.boundaryMode, and eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.boundaryModeProperty().
setCullFace()
final void eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.setCullFace (CullFace value)
Sets the cull face.
Parameters
value the new cull face
Definition at line 197 of file PolygonMeshView.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.cullFaceProperty().
setDrawMode()
final void eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.setDrawMode (DrawMode value)
Sets the draw mode.
Parameters
value the new draw mode
Definition at line 158 of file PolygonMeshView.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.drawModeProperty().
setMapBorderMode()
void eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.setMapBorderMode (MapBorderMode mapBorderMode)
Sets the map border mode.
Parameters
mapBorderMode the new map border mode
Definition at line 354 of file PolygonMeshView.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.mapBorderMode, and eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.mapBorderModeProperty().
setMaterial()
void eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.setMaterial (Material material)
Sets the material.
Parameters
material the new material
Definition at line 243 of file PolygonMeshView.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.materialProperty.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.buildPolygonMeshView().
setMesh()
void eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.setMesh (PolygonMesh mesh)
Sets the mesh.
Parameters
mesh the new mesh
Definition at line 116 of file PolygonMeshView.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.meshProperty.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.PolyObjImporter.buildPolygonMeshView(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.PolygonMeshView(), and eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.subdivisionLevelProperty().
setSubdivisionLevel()
void eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.setSubdivisionLevel (int subdivisionLevel)
Sets the subdivision level.
Parameters
subdivisionLevel the new subdivision level
Definition at line 264 of file PolygonMeshView.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.subdivisionLevelProperty.
subdivisionLevelProperty()
SimpleIntegerProperty eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.subdivisionLevelProperty ()
Subdivision level property.
Returns
the simple integer property
Definition at line 278 of file PolygonMeshView.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.facesDirty, eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.getBoundaryMode(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.getMapBorderMode(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.getMesh(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.getOriginalMesh(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMesh.getPoints(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.getSubdivisionLevel(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.pointsDirty, eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.pointsSizeDirty, eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.setMesh(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.setSubdivisionLevel(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.subdivisionLevelProperty, eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.subdivisionMesh, eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.texCoordsDirty, eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.SubdivisionMesh.update(), and eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.updateMesh().
updateMesh()
void eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.updateMesh () private
Update mesh.
Definition at line 411 of file PolygonMeshView.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.DEBUG, eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.distanceBetweenPoints(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMesh.faces, eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.facesDirty, eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.getDrawMode(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMesh.getFaceSmoothingGroups(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.getMesh(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMesh.getNumEdgesInFaces(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMesh.getPoints(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMesh.getTexCoords(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.meshView, eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.pointsDirty, eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.pointsSizeDirty, eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.texCoordsDirty, and eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.triangleMesh.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.boundaryModeProperty(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.drawModeProperty(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.mapBorderModeProperty(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.meshProperty(), and eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.subdivisionLevelProperty().
Member Data Documentation
boundaryMode
SimpleObjectProperty<BoundaryMode> eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.boundaryMode private
Texture mapping boundary rule for Catmull Clark subdivision applied to the mesh.
@defaultValue BoundaryMode.CREASE_EDGES
Definition at line 305 of file PolygonMeshView.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.boundaryModeProperty(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.getBoundaryMode(), and eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.setBoundaryMode().
cullFace
ObjectProperty<CullFace> eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.cullFace private
Defines the drawMode this
Shape3D
.
@defaultValue CullFace.BACK
Definition at line 190 of file PolygonMeshView.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.cullFaceProperty(), and eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.getCullFace().
DEBUG
final boolean eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.DEBUG = false static private
The Constant DEBUG.
Definition at line 58 of file PolygonMeshView.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.updateMesh().
drawMode
ObjectProperty<DrawMode> eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.drawMode private
Defines the drawMode this
Shape3D
.
@defaultValue DrawMode.FILL
Definition at line 151 of file PolygonMeshView.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.drawModeProperty(), and eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.getDrawMode().
facesDirty
boolean eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.facesDirty = true private
The faces dirty.
Definition at line 92 of file PolygonMeshView.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.drawModeProperty(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.meshProperty(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.subdivisionLevelProperty(), and eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.updateMesh().
mapBorderMode
SimpleObjectProperty<MapBorderMode> eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.mapBorderMode private
Texture mapping smoothness option for Catmull Clark subdivision applied to the mesh.
@defaultValue MapBorderMode.NOT_SMOOTH
Definition at line 347 of file PolygonMeshView.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.getMapBorderMode(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.mapBorderModeProperty(), and eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.setMapBorderMode().
materialProperty
ObjectProperty<Material> eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.materialProperty = new SimpleObjectProperty<Material>() private
Defines the material this
Shape3D
. The default material is null. If
Material
is null, a PhongMaterial with a diffuse color of Color.LIGHTGRAY is used for rendering.
@defaultValue null
Definition at line 229 of file PolygonMeshView.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.getMaterial(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.PolygonMeshView(), and eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.setMaterial().
meshPointsListener
final ArrayChangeListener<ObservableFloatArray> eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.meshPointsListener private
Initial value:
= (t, bln, i, i1) -> {
        pointsDirty = true;
        updateMesh();
    }
The mesh points listener.
Definition at line 71 of file PolygonMeshView.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.meshProperty().
meshProperty
ObjectProperty<PolygonMesh> eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.meshProperty private
Specifies the 3D mesh data of this
MeshView
.
@defaultValue null
Definition at line 102 of file PolygonMeshView.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.getMesh(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.meshProperty(), and eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.setMesh().
meshTexCoordListener
final ArrayChangeListener<ObservableFloatArray> eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.meshTexCoordListener private
Initial value:
= (t, bln, i, i1) -> {
        texCoordsDirty = true;
        updateMesh();
    }
The mesh tex coord listener.
Definition at line 77 of file PolygonMeshView.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.meshProperty().
meshView
final MeshView eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.meshView = new MeshView() private
The mesh view.
Definition at line 61 of file PolygonMeshView.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.cullFaceProperty(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.drawModeProperty(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.PolygonMeshView(), and eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.updateMesh().
pointsDirty
boolean eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.pointsDirty = true private
The points dirty.
Definition at line 83 of file PolygonMeshView.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.boundaryModeProperty(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.drawModeProperty(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.meshProperty(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.subdivisionLevelProperty(), and eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.updateMesh().
pointsSizeDirty
boolean eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.pointsSizeDirty = true private
The points size dirty.
Definition at line 86 of file PolygonMeshView.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.drawModeProperty(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.meshProperty(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.subdivisionLevelProperty(), and eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.updateMesh().
subdivisionLevelProperty
SimpleIntegerProperty eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.subdivisionLevelProperty private
Number of iterations of Catmull Clark subdivision to apply to the mesh.
@defaultValue 0
Definition at line 257 of file PolygonMeshView.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.getSubdivisionLevel(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.setSubdivisionLevel(), and eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.subdivisionLevelProperty().
subdivisionMesh
SubdivisionMesh eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.subdivisionMesh private
The subdivision mesh.
Definition at line 68 of file PolygonMeshView.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.boundaryModeProperty(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.mapBorderModeProperty(), and eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.subdivisionLevelProperty().
texCoordsDirty
boolean eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.texCoordsDirty = true private
The tex coords dirty.
Definition at line 89 of file PolygonMeshView.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.drawModeProperty(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.mapBorderModeProperty(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.meshProperty(), eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.subdivisionLevelProperty(), and eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.updateMesh().
triangleMesh
TriangleMesh eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.triangleMesh = new TriangleMesh() private
The triangle mesh.
Definition at line 64 of file PolygonMeshView.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.PolygonMeshView.updateMesh().
The documentation for this class was generated from the following file:
JCSG/src/main/java/eu/mihosoft/vrl/v3d/ext/openjfx/shape3d/PolygonMeshView.java