BowlerKernel: com.piro.bezier.BezierListProducer Class Reference
com.piro.bezier.BezierListProducer Class Reference
Public Member Functions
void startPath () throws ParseException
void movetoRel (float x, float y) throws ParseException
void movetoAbs (float x, float y) throws ParseException
void closePath () throws ParseException
void linetoRel (float x, float y) throws ParseException
void linetoAbs (float x, float y) throws ParseException
void linetoHorizontalRel (float x) throws ParseException
void linetoHorizontalAbs (float x) throws ParseException
void linetoVerticalRel (float y) throws ParseException
void linetoVerticalAbs (float y) throws ParseException
void curvetoCubicRel (float x1, float y1, float x2, float y2, float x, float y) throws ParseException
void curvetoCubicAbs (float x1, float y1, float x2, float y2, float x, float y) throws ParseException
void curvetoCubicSmoothRel (float x2, float y2, float x, float y) throws ParseException
void curvetoCubicSmoothAbs (float x2, float y2, float x, float y) throws ParseException
void curvetoQuadraticRel (float x1, float y1, float x, float y) throws ParseException
void curvetoQuadraticAbs (float x1, float y1, float x, float y) throws ParseException
void curvetoQuadraticSmoothRel (float x, float y)
void curvetoQuadraticSmoothAbs (float x, float y) throws ParseException
void arcRel (float rx, float ry, float xAxisRotation, boolean largeArcFlag, boolean sweepFlag, float x, float y) throws ParseException
void arcAbs (float rx, float ry, float xAxisRotation, boolean largeArcFlag, boolean sweepFlag, float x, float y) throws ParseException
void endPath () throws ParseException
Detailed Description
A handler class that generates an array of shorts and an array floats from parsing path data.
Author
Cameron McCormack
Version
Id
PathArrayProducer.java 475685 2006-11-16 11:16:05Z cam
Definition at line 30 of file BezierListProducer.java.
Member Function Documentation
arcAbs()
void com.piro.bezier.BezierListProducer.arcAbs (float rx, float ry, float xAxisRotation, boolean largeArcFlag, boolean sweepFlag, float x, float y) throws ParseException
Invoked when an absolute elliptical arc command has been parsed.
Command : A
Parameters
rx the X axis radius for the ellipse
ry the Y axis radius for the ellipse
xAxisRotation the rotation angle in degrees for the ellipse's X-axis relative to the X-axis
largeArcFlag the value of the large-arc-flag
sweepFlag the value of the sweep-flag
x the absolute x coordinate for the end point
y the absolute y coordinate for the end point
Exceptions
ParseException if an error occured while processing the path
Implements com.piro.bezier.PathHandler.
Definition at line 220 of file BezierListProducer.java.
arcRel()
void com.piro.bezier.BezierListProducer.arcRel (float rx, float ry, float xAxisRotation, boolean largeArcFlag, boolean sweepFlag, float x, float y) throws ParseException
Invoked when a relative elliptical arc command has been parsed.
Command : a
Parameters
rx the X axis radius for the ellipse
ry the Y axis radius for the ellipse
xAxisRotation the rotation angle in degrees for the ellipse's X-axis relative to the X-axis
largeArcFlag the value of the large-arc-flag
sweepFlag the value of the sweep-flag
x the relative x coordinate for the end point
y the relative y coordinate for the end point
Exceptions
ParseException if an error occured while processing the path
Implements com.piro.bezier.PathHandler.
Definition at line 212 of file BezierListProducer.java.
closePath()
void com.piro.bezier.BezierListProducer.closePath () throws ParseException
Invoked when a closepath has been parsed.
Command : z | Z
Exceptions
ParseException if an error occured while processing the path
Implements com.piro.bezier.PathHandler.
Definition at line 57 of file BezierListProducer.java.
Referenced by com.piro.bezier.BezierPath.parsePathList().
curvetoCubicAbs()
void com.piro.bezier.BezierListProducer.curvetoCubicAbs (float x1, float y1, float x2, float y2, float x, float y) throws ParseException
Invoked when an absolute cubic bezier curve command has been parsed.
Command : C
Parameters
x1 the absolute x coordinate for the first control point
y1 the absolute y coordinate for the first control point
x2 the absolute x coordinate for the second control point
y2 the absolute y coordinate for the second control point
x the absolute x coordinate for the end point
y the absolute y coordinate for the end point
Exceptions
ParseException if an error occured while processing the path
Implements com.piro.bezier.PathHandler.
Definition at line 117 of file BezierListProducer.java.
References com.piro.bezier.Bezier.getLength(), com.piro.bezier.BezierHistory.setLastKnot(), com.piro.bezier.BezierHistory.setLastPoint(), com.piro.bezier.Vector2.x, and com.piro.bezier.Vector2.y.
Referenced by com.piro.bezier.BezierListProducer.curvetoCubicRel(), and com.piro.bezier.BezierPath.parsePathList().
curvetoCubicRel()
void com.piro.bezier.BezierListProducer.curvetoCubicRel (float x1, float y1, float x2, float y2, float x, float y) throws ParseException
Invoked when a relative cubic bezier curve command has been parsed.
Command : c
Parameters
x1 the relative x coordinate for the first control point
y1 the relative y coordinate for the first control point
x2 the relative x coordinate for the second control point
y2 the relative y coordinate for the second control point
x the relative x coordinate for the end point
y the relative y coordinate for the end point
Exceptions
ParseException if an error occured while processing the path
Implements com.piro.bezier.PathHandler.
Definition at line 105 of file BezierListProducer.java.
References com.piro.bezier.BezierListProducer.curvetoCubicAbs(), com.piro.bezier.Vector2.x, and com.piro.bezier.Vector2.y.
Referenced by com.piro.bezier.BezierPath.parsePathList().
curvetoCubicSmoothAbs()
void com.piro.bezier.BezierListProducer.curvetoCubicSmoothAbs (float x2, float y2, float x, float y) throws ParseException
Invoked when an absolute smooth cubic bezier curve command has been parsed. The first control point is assumed to be the reflection of the second control point on the previous command relative to the current point.
Command : S
Parameters
x2 the absolute x coordinate for the second control point
y2 the absolute y coordinate for the second control point
x the absolute x coordinate for the end point
y the absolute y coordinate for the end point
Exceptions
ParseException if an error occured while processing the path
Implements com.piro.bezier.PathHandler.
Definition at line 145 of file BezierListProducer.java.
References com.piro.bezier.Bezier.getLength(), com.piro.bezier.BezierHistory.setLastKnot(), com.piro.bezier.BezierHistory.setLastPoint(), com.piro.bezier.Vector2.x, and com.piro.bezier.Vector2.y.
Referenced by com.piro.bezier.BezierListProducer.curvetoCubicSmoothRel(), and com.piro.bezier.BezierPath.parsePathList().
curvetoCubicSmoothRel()
void com.piro.bezier.BezierListProducer.curvetoCubicSmoothRel (float x2, float y2, float x, float y) throws ParseException
Invoked when a relative smooth cubic bezier curve command has been parsed. The first control point is assumed to be the reflection of the second control point on the previous command relative to the current point.
Command : s
Parameters
x2 the relative x coordinate for the second control point
y2 the relative y coordinate for the second control point
x the relative x coordinate for the end point
y the relative y coordinate for the end point
Exceptions
ParseException if an error occured while processing the path
Implements com.piro.bezier.PathHandler.
Definition at line 136 of file BezierListProducer.java.
References com.piro.bezier.BezierListProducer.curvetoCubicSmoothAbs(), com.piro.bezier.Vector2.x, and com.piro.bezier.Vector2.y.
Referenced by com.piro.bezier.BezierPath.parsePathList().
curvetoQuadraticAbs()
void com.piro.bezier.BezierListProducer.curvetoQuadraticAbs (float x1, float y1, float x, float y) throws ParseException
Invoked when an absolute quadratic bezier curve command has been parsed.
Command : Q
Parameters
x1 the absolute x coordinate for the control point
y1 the absolute y coordinate for the control point
x the absolute x coordinate for the end point
y the absolute x coordinate for the end point
Exceptions
ParseException if an error occured while processing the path
Implements com.piro.bezier.PathHandler.
Definition at line 180 of file BezierListProducer.java.
References com.piro.bezier.Bezier.getLength(), com.piro.bezier.BezierHistory.setLastKnot(), com.piro.bezier.BezierHistory.setLastPoint(), com.piro.bezier.Vector2.x, and com.piro.bezier.Vector2.y.
Referenced by com.piro.bezier.BezierListProducer.curvetoQuadraticRel(), com.piro.bezier.BezierListProducer.curvetoQuadraticSmoothAbs(), and com.piro.bezier.BezierPath.parsePathList().
curvetoQuadraticRel()
void com.piro.bezier.BezierListProducer.curvetoQuadraticRel (float x1, float y1, float x, float y) throws ParseException
Invoked when a relative quadratic bezier curve command has been parsed.
Command : q
Parameters
x1 the relative x coordinate for the control point
y1 the relative y coordinate for the control point
x the relative x coordinate for the end point
y the relative x coordinate for the end point
Exceptions
ParseException if an error occured while processing the path
Implements com.piro.bezier.PathHandler.
Definition at line 171 of file BezierListProducer.java.
References com.piro.bezier.BezierListProducer.curvetoQuadraticAbs(), com.piro.bezier.Vector2.x, and com.piro.bezier.Vector2.y.
curvetoQuadraticSmoothAbs()
void com.piro.bezier.BezierListProducer.curvetoQuadraticSmoothAbs (float x, float y) throws ParseException
Invoked when an absolute smooth quadratic bezier curve command has been parsed. The control point is assumed to be the reflection of the control point on the previous command relative to the current point.
Command : T
Parameters
x the absolute x coordinate for the end point
y the absolute y coordinate for the end point
Exceptions
ParseException if an error occured while processing the path
Implements com.piro.bezier.PathHandler.
Definition at line 205 of file BezierListProducer.java.
References com.piro.bezier.BezierListProducer.curvetoQuadraticAbs(), com.piro.bezier.Vector2.x, and com.piro.bezier.Vector2.y.
Referenced by com.piro.bezier.BezierListProducer.curvetoQuadraticSmoothRel(), and com.piro.bezier.BezierPath.parsePathList().
curvetoQuadraticSmoothRel()
void com.piro.bezier.BezierListProducer.curvetoQuadraticSmoothRel (float x, float y)
Invoked when a relative smooth quadratic bezier curve command has been parsed. The control point is assumed to be the reflection of the control point on the previous command relative to the current point.
Command : t
Parameters
x the relative x coordinate for the end point
y the relative y coordinate for the end point
Exceptions
ParseException if an error occured while processing the path
Implements com.piro.bezier.PathHandler.
Definition at line 197 of file BezierListProducer.java.
References com.piro.bezier.BezierListProducer.curvetoQuadraticSmoothAbs(), com.piro.bezier.Vector2.x, and com.piro.bezier.Vector2.y.
Referenced by com.piro.bezier.BezierPath.parsePathList().
endPath()
void com.piro.bezier.BezierListProducer.endPath () throws ParseException
Invoked when the path ends.
Exceptions
ParseException if an error occured while processing the path
Implements com.piro.bezier.PathHandler.
Definition at line 228 of file BezierListProducer.java.
References com.piro.bezier.BezierHistory.setLastKnot(), com.piro.bezier.BezierHistory.setLastPoint(), com.piro.bezier.Vector2.x, and com.piro.bezier.Vector2.y.
linetoAbs()
void com.piro.bezier.BezierListProducer.linetoAbs (float x, float y) throws ParseException
Invoked when an absolute line command has been parsed.
Command : L
Parameters
x the absolute x coordinate for the end point
y the absolute y coordinate for the end point
Exceptions
ParseException if an error occured while processing the path
Implements com.piro.bezier.PathHandler.
Definition at line 70 of file BezierListProducer.java.
References com.piro.bezier.Bezier.getLength(), com.piro.bezier.BezierHistory.setLastKnot(), com.piro.bezier.BezierHistory.setLastPoint(), com.piro.bezier.Vector2.x, and com.piro.bezier.Vector2.y.
Referenced by com.piro.bezier.BezierListProducer.linetoHorizontalAbs(), com.piro.bezier.BezierListProducer.linetoHorizontalRel(), com.piro.bezier.BezierListProducer.linetoRel(), com.piro.bezier.BezierListProducer.linetoVerticalAbs(), com.piro.bezier.BezierListProducer.linetoVerticalRel(), and com.piro.bezier.BezierPath.parsePathList().
linetoHorizontalAbs()
void com.piro.bezier.BezierListProducer.linetoHorizontalAbs (float x) throws ParseException
Invoked when an horizontal absolute line command has been parsed.
Command : H
Parameters
x the absolute X coordinate of the end point
Exceptions
ParseException if an error occured while processing the path
Implements com.piro.bezier.PathHandler.
Definition at line 90 of file BezierListProducer.java.
References com.piro.bezier.BezierListProducer.linetoAbs(), and com.piro.bezier.Vector2.y.
Referenced by com.piro.bezier.BezierPath.parsePathList().
linetoHorizontalRel()
void com.piro.bezier.BezierListProducer.linetoHorizontalRel (float x) throws ParseException
Invoked when an horizontal relative line command has been parsed.
Command : h
Parameters
x the relative X coordinate of the end point
Exceptions
ParseException if an error occured while processing the path
Implements com.piro.bezier.PathHandler.
Definition at line 85 of file BezierListProducer.java.
References com.piro.bezier.BezierListProducer.linetoAbs(), com.piro.bezier.Vector2.x, and com.piro.bezier.Vector2.y.
Referenced by com.piro.bezier.BezierPath.parsePathList().
linetoRel()
void com.piro.bezier.BezierListProducer.linetoRel (float x, float y) throws ParseException
Invoked when a relative line command has been parsed.
Command : l
Parameters
x the relative x coordinates for the end point
y the relative y coordinates for the end point
Exceptions
ParseException if an error occured while processing the path
Implements com.piro.bezier.PathHandler.
Definition at line 62 of file BezierListProducer.java.
References com.piro.bezier.BezierListProducer.linetoAbs(), com.piro.bezier.Vector2.x, and com.piro.bezier.Vector2.y.
Referenced by com.piro.bezier.BezierPath.parsePathList().
linetoVerticalAbs()
void com.piro.bezier.BezierListProducer.linetoVerticalAbs (float y) throws ParseException
Invoked when a vertical absolute line command has been parsed.
Command : V
Parameters
y the absolute Y coordinate of the end point
Exceptions
ParseException if an error occured while processing the path
Implements com.piro.bezier.PathHandler.
Definition at line 100 of file BezierListProducer.java.
References com.piro.bezier.BezierListProducer.linetoAbs(), and com.piro.bezier.Vector2.x.
Referenced by com.piro.bezier.BezierPath.parsePathList().
linetoVerticalRel()
void com.piro.bezier.BezierListProducer.linetoVerticalRel (float y) throws ParseException
Invoked when a vertical relative line command has been parsed.
Command : v
Parameters
y the relative Y coordinate of the end point
Exceptions
ParseException if an error occured while processing the path
Implements com.piro.bezier.PathHandler.
Definition at line 95 of file BezierListProducer.java.
References com.piro.bezier.BezierListProducer.linetoAbs(), com.piro.bezier.Vector2.x, and com.piro.bezier.Vector2.y.
movetoAbs()
void com.piro.bezier.BezierListProducer.movetoAbs (float x, float y) throws ParseException
Invoked when an absolute moveto command has been parsed.
Command : M
Parameters
x the absolute x coordinate for the end point
y the absolute y coordinate for the end point
Exceptions
ParseException if an error occured while processing the path
Implements com.piro.bezier.PathHandler.
Definition at line 52 of file BezierListProducer.java.
References com.piro.bezier.BezierHistory.setLastPoint().
Referenced by com.piro.bezier.BezierListProducer.movetoRel(), and com.piro.bezier.BezierPath.parsePathList().
movetoRel()
void com.piro.bezier.BezierListProducer.movetoRel (float x, float y) throws ParseException
Invoked when a relative moveto command has been parsed.
Command : m
Parameters
x the relative x coordinate for the end point
y the relative y coordinate for the end point
Exceptions
ParseException if an error occured while processing the path
Implements com.piro.bezier.PathHandler.
Definition at line 44 of file BezierListProducer.java.
References com.piro.bezier.BezierListProducer.movetoAbs(), com.piro.bezier.Vector2.x, and com.piro.bezier.Vector2.y.
Referenced by com.piro.bezier.BezierPath.parsePathList().
startPath()
void com.piro.bezier.BezierListProducer.startPath () throws ParseException
Invoked when the path starts.
Exceptions
ParseException if an error occured while processing the path
Implements com.piro.bezier.PathHandler.
Definition at line 38 of file BezierListProducer.java.
The documentation for this class was generated from the following file:
JCSG/src/main/java/com/piro/bezier/BezierListProducer.java