BowlerKernel: com.neuronrobotics.application.xmpp.DyIOConversation.ChatAsyncListener Class Reference
com.neuronrobotics.application.xmpp.DyIOConversation.ChatAsyncListener Class Reference
Public Member Functions
ChatAsyncListener (Chat c, String from)
Chat getChat ()
void onChannelEvent (DyIOChannelEvent e)
void setChat (Chat chat)
void setFrom (String from)
String getFrom ()
Private Attributes
Chat chat
String from
Detailed Description
The listener interface for receiving chatAsync events. The class that is interested in processing a chatAsync event implements this interface, and the object created with that class is registered with a component using the component's addChatAsyncListener method. When the chatAsync event occurs, that object's appropriate method is invoked.
Definition at line 170 of file DyIOConversation.java.
Constructor & Destructor Documentation
ChatAsyncListener()
com.neuronrobotics.application.xmpp.DyIOConversation.ChatAsyncListener.ChatAsyncListener (Chat c, String from)
Instantiates a new chat async listener.
Parameters
c the c
from the from
Definition at line 184 of file DyIOConversation.java.
References com.neuronrobotics.application.xmpp.DyIOConversation.ChatAsyncListener.setChat(), and com.neuronrobotics.application.xmpp.DyIOConversation.ChatAsyncListener.setFrom().
Member Function Documentation
getChat()
Chat com.neuronrobotics.application.xmpp.DyIOConversation.ChatAsyncListener.getChat ()
Gets the chat.
Returns
the chat
Definition at line 194 of file DyIOConversation.java.
References com.neuronrobotics.application.xmpp.DyIOConversation.ChatAsyncListener.chat.
getFrom()
String com.neuronrobotics.application.xmpp.DyIOConversation.ChatAsyncListener.getFrom ()
Gets the from.
Returns
the from
Definition at line 238 of file DyIOConversation.java.
References com.neuronrobotics.application.xmpp.DyIOConversation.ChatAsyncListener.from.
Referenced by com.neuronrobotics.application.xmpp.DyIOConversation.ChatAsyncListener.onChannelEvent().
onChannelEvent()
void com.neuronrobotics.application.xmpp.DyIOConversation.ChatAsyncListener.onChannelEvent (DyIOChannelEvent e)
On channel event.
Parameters
e the e
Implements com.neuronrobotics.sdk.dyio.IChannelEventListener.
Definition at line 202 of file DyIOConversation.java.
References com.neuronrobotics.application.xmpp.DyIOConversation.ChatAsyncListener.chat, com.neuronrobotics.sdk.dyio.DyIOChannelEvent.getChannel(), com.neuronrobotics.sdk.dyio.DyIOChannel.getChannelNumber(), com.neuronrobotics.application.xmpp.DyIOConversation.ChatAsyncListener.getFrom(), and com.neuronrobotics.sdk.dyio.DyIOChannelEvent.getValue().
setChat()
void com.neuronrobotics.application.xmpp.DyIOConversation.ChatAsyncListener.setChat (Chat chat)
Sets the chat.
Parameters
chat the new chat
Definition at line 220 of file DyIOConversation.java.
References com.neuronrobotics.application.xmpp.DyIOConversation.ChatAsyncListener.chat.
Referenced by com.neuronrobotics.application.xmpp.DyIOConversation.ChatAsyncListener.ChatAsyncListener().
setFrom()
void com.neuronrobotics.application.xmpp.DyIOConversation.ChatAsyncListener.setFrom (String from)
Sets the from.
Parameters
from the new from
Definition at line 229 of file DyIOConversation.java.
References com.neuronrobotics.application.xmpp.DyIOConversation.ChatAsyncListener.from.
Referenced by com.neuronrobotics.application.xmpp.DyIOConversation.ChatAsyncListener.ChatAsyncListener().
Member Data Documentation
chat
Chat com.neuronrobotics.application.xmpp.DyIOConversation.ChatAsyncListener.chat private
The chat.
Definition at line 173 of file DyIOConversation.java.
Referenced by com.neuronrobotics.application.xmpp.DyIOConversation.ChatAsyncListener.getChat(), com.neuronrobotics.application.xmpp.DyIOConversation.ChatAsyncListener.onChannelEvent(), and com.neuronrobotics.application.xmpp.DyIOConversation.ChatAsyncListener.setChat().
from
String com.neuronrobotics.application.xmpp.DyIOConversation.ChatAsyncListener.from private
The from.
Definition at line 176 of file DyIOConversation.java.
Referenced by com.neuronrobotics.application.xmpp.DyIOConversation.ChatAsyncListener.getFrom(), and com.neuronrobotics.application.xmpp.DyIOConversation.ChatAsyncListener.setFrom().
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/application/xmpp/DyIOConversation.java