BowlerKernel: com.neuronrobotics.sdk.util.OsInfoUtil Class Reference
com.neuronrobotics.sdk.util.OsInfoUtil Class Reference
Static Public Member Functions
static boolean is64Bit ()
static boolean isARM ()
static boolean isPPC ()
static boolean isCortexA8 ()
static boolean isWindows ()
static boolean isLinux ()
static boolean isOSX ()
static String getExtension ()
static String getOsName ()
static String getOsArch ()
static String getIdentifier ()
Detailed Description
The Class OsInfoUtil.
Definition at line 7 of file OsInfoUtil.java.
Member Function Documentation
getExtension()
static String com.neuronrobotics.sdk.util.OsInfoUtil.getExtension () static
Gets the extension.
Returns
the extension
Definition at line 86 of file OsInfoUtil.java.
References com.neuronrobotics.sdk.util.OsInfoUtil.isLinux(), com.neuronrobotics.sdk.util.OsInfoUtil.isOSX(), and com.neuronrobotics.sdk.util.OsInfoUtil.isWindows().
getIdentifier()
static String com.neuronrobotics.sdk.util.OsInfoUtil.getIdentifier () static
Gets the identifier.
Returns
the identifier
Definition at line 123 of file OsInfoUtil.java.
References com.neuronrobotics.sdk.util.OsInfoUtil.getOsArch(), and com.neuronrobotics.sdk.util.OsInfoUtil.getOsName().
getOsArch()
static String com.neuronrobotics.sdk.util.OsInfoUtil.getOsArch () static
Gets the os arch.
Returns
the os arch
Definition at line 113 of file OsInfoUtil.java.
Referenced by com.neuronrobotics.sdk.util.OsInfoUtil.getIdentifier(), com.neuronrobotics.sdk.util.OsInfoUtil.is64Bit(), com.neuronrobotics.sdk.util.OsInfoUtil.isARM(), and com.neuronrobotics.sdk.util.OsInfoUtil.isPPC().
getOsName()
static String com.neuronrobotics.sdk.util.OsInfoUtil.getOsName () static
Gets the os name.
Returns
the os name
Definition at line 104 of file OsInfoUtil.java.
Referenced by com.neuronrobotics.sdk.util.OsInfoUtil.getIdentifier(), com.neuronrobotics.sdk.util.OsInfoUtil.isLinux(), com.neuronrobotics.sdk.util.OsInfoUtil.isOSX(), and com.neuronrobotics.sdk.util.OsInfoUtil.isWindows().
is64Bit()
static boolean com.neuronrobotics.sdk.util.OsInfoUtil.is64Bit () static
Checks if is 64 bit.
Returns
true, if is 64 bit
Definition at line 14 of file OsInfoUtil.java.
References com.neuronrobotics.sdk.util.OsInfoUtil.getOsArch().
isARM()
static boolean com.neuronrobotics.sdk.util.OsInfoUtil.isARM () static
Checks if is arm.
Returns
true, if is arm
Definition at line 25 of file OsInfoUtil.java.
References com.neuronrobotics.sdk.util.OsInfoUtil.getOsArch().
Referenced by com.neuronrobotics.sdk.util.OsInfoUtil.isCortexA8().
isCortexA8()
static boolean com.neuronrobotics.sdk.util.OsInfoUtil.isCortexA8 () static
Checks if is cortex a8.
Returns
true, if is cortex a8
Definition at line 43 of file OsInfoUtil.java.
References com.neuronrobotics.sdk.util.OsInfoUtil.isARM().
isLinux()
static boolean com.neuronrobotics.sdk.util.OsInfoUtil.isLinux () static
Checks if is linux.
Returns
true, if is linux
Definition at line 68 of file OsInfoUtil.java.
References com.neuronrobotics.sdk.util.OsInfoUtil.getOsName().
Referenced by com.neuronrobotics.sdk.util.OsInfoUtil.getExtension().
isOSX()
static boolean com.neuronrobotics.sdk.util.OsInfoUtil.isOSX () static
Checks if is osx.
Returns
true, if is osx
Definition at line 77 of file OsInfoUtil.java.
References com.neuronrobotics.sdk.util.OsInfoUtil.getOsName().
Referenced by com.neuronrobotics.sdk.util.OsInfoUtil.getExtension().
isPPC()
static boolean com.neuronrobotics.sdk.util.OsInfoUtil.isPPC () static
Checks if is ppc.
Returns
true, if is ppc
Definition at line 34 of file OsInfoUtil.java.
References com.neuronrobotics.sdk.util.OsInfoUtil.getOsArch().
isWindows()
static boolean com.neuronrobotics.sdk.util.OsInfoUtil.isWindows () static
Checks if is windows.
Returns
true, if is windows
Definition at line 56 of file OsInfoUtil.java.
References com.neuronrobotics.sdk.util.OsInfoUtil.getOsName().
Referenced by com.neuronrobotics.sdk.util.OsInfoUtil.getExtension(), and com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.resetUsbSystem().
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/util/OsInfoUtil.java