BowlerKernel: com.neuronrobotics.sdk.dyio.sequencer.SequencerWAV Class Reference
com.neuronrobotics.sdk.dyio.sequencer.SequencerWAV Class Reference
Public Member Functions
SequencerWAV (String filename)
void pause ()
void close ()
boolean isPlaying ()
int getCurrentTime ()
void setCurrentTime (int time)
int getTrackLength ()
void playStep ()
void play ()
Static Public Member Functions
static void main (String[] args)
Private Member Functions
double getPercent ()
Private Attributes
String fn =""
Clip player
int trackLength = 37
Detailed Description
The Class SequencerWAV.
Definition at line 10 of file SequencerWAV.java.
Constructor & Destructor Documentation
SequencerWAV()
com.neuronrobotics.sdk.dyio.sequencer.SequencerWAV.SequencerWAV (String filename)
Definition at line 22 of file SequencerWAV.java.
References com.neuronrobotics.sdk.dyio.sequencer.SequencerWAV.fn, com.neuronrobotics.sdk.dyio.sequencer.SequencerWAV.player, and com.neuronrobotics.sdk.dyio.sequencer.SequencerWAV.trackLength.
Referenced by com.neuronrobotics.sdk.dyio.sequencer.SequencerWAV.main().
Member Function Documentation
close()
void com.neuronrobotics.sdk.dyio.sequencer.SequencerWAV.close ()
Close.
Definition at line 49 of file SequencerWAV.java.
References com.neuronrobotics.sdk.dyio.sequencer.SequencerWAV.player.
getCurrentTime()
int com.neuronrobotics.sdk.dyio.sequencer.SequencerWAV.getCurrentTime ()
Gets the current time.
Returns
the current time
Definition at line 70 of file SequencerWAV.java.
References com.neuronrobotics.sdk.dyio.sequencer.SequencerWAV.player.
Referenced by com.neuronrobotics.sdk.dyio.sequencer.SequencerWAV.main(), and com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.SchedulerThread.playStep().
getPercent()
double com.neuronrobotics.sdk.dyio.sequencer.SequencerWAV.getPercent () private
Gets the percent.
Returns
the percent
Definition at line 97 of file SequencerWAV.java.
References com.neuronrobotics.sdk.dyio.sequencer.SequencerWAV.isPlaying(), and com.neuronrobotics.sdk.dyio.sequencer.SequencerWAV.player.
Referenced by com.neuronrobotics.sdk.dyio.sequencer.SequencerWAV.main().
getTrackLength()
int com.neuronrobotics.sdk.dyio.sequencer.SequencerWAV.getTrackLength ()
Gets the track length.
Returns
length in Ms
Definition at line 88 of file SequencerWAV.java.
References com.neuronrobotics.sdk.dyio.sequencer.SequencerWAV.trackLength.
Referenced by com.neuronrobotics.sdk.dyio.sequencer.SequencerWAV.main(), and com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.setAudioFile().
isPlaying()
boolean com.neuronrobotics.sdk.dyio.sequencer.SequencerWAV.isPlaying ()
Checks if is playing.
Returns
true, if is playing
Definition at line 59 of file SequencerWAV.java.
References com.neuronrobotics.sdk.dyio.sequencer.SequencerWAV.player.
Referenced by com.neuronrobotics.sdk.dyio.sequencer.SequencerWAV.getPercent(), com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.SchedulerThread.isRun(), com.neuronrobotics.sdk.dyio.sequencer.SequencerWAV.main(), and com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.SchedulerThread.playStep().
main()
static void com.neuronrobotics.sdk.dyio.sequencer.SequencerWAV.main (String[] args) static
The main method.
Parameters
args the arguments
Definition at line 138 of file SequencerWAV.java.
References com.neuronrobotics.sdk.dyio.sequencer.SequencerWAV.getCurrentTime(), com.neuronrobotics.sdk.dyio.sequencer.SequencerWAV.getPercent(), com.neuronrobotics.sdk.dyio.sequencer.SequencerWAV.getTrackLength(), com.neuronrobotics.sdk.dyio.sequencer.SequencerWAV.isPlaying(), com.neuronrobotics.sdk.dyio.sequencer.SequencerWAV.play(), com.neuronrobotics.sdk.dyio.sequencer.SequencerWAV.SequencerWAV(), and com.neuronrobotics.sdk.util.ThreadUtil.wait().
pause()
void com.neuronrobotics.sdk.dyio.sequencer.SequencerWAV.pause ()
Pause.
Definition at line 42 of file SequencerWAV.java.
References com.neuronrobotics.sdk.dyio.sequencer.SequencerWAV.player.
Referenced by com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.SchedulerThread.kill(), com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.pause(), and com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.SchedulerThread.pause().
play()
void com.neuronrobotics.sdk.dyio.sequencer.SequencerWAV.play ()
Play.
Definition at line 124 of file SequencerWAV.java.
References com.neuronrobotics.sdk.dyio.sequencer.SequencerWAV.player.
Referenced by com.neuronrobotics.sdk.dyio.sequencer.SequencerWAV.main(), and com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.play().
playStep()
void com.neuronrobotics.sdk.dyio.sequencer.SequencerWAV.playStep ()
Play step.
Definition at line 114 of file SequencerWAV.java.
References com.neuronrobotics.sdk.dyio.sequencer.SequencerWAV.player.
setCurrentTime()
void com.neuronrobotics.sdk.dyio.sequencer.SequencerWAV.setCurrentTime (int time)
Sets the current time.
Parameters
time the new current time
Definition at line 79 of file SequencerWAV.java.
References com.neuronrobotics.sdk.dyio.sequencer.SequencerWAV.player.
Referenced by com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.SchedulerThread.SchedulerThread(), and com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.setSequenceParams().
Member Data Documentation
fn
String com.neuronrobotics.sdk.dyio.sequencer.SequencerWAV.fn ="" private
The fn.
Definition at line 13 of file SequencerWAV.java.
Referenced by com.neuronrobotics.sdk.dyio.sequencer.SequencerWAV.SequencerWAV().
player
Clip com.neuronrobotics.sdk.dyio.sequencer.SequencerWAV.player private
The player.
Definition at line 17 of file SequencerWAV.java.
Referenced by com.neuronrobotics.sdk.dyio.sequencer.SequencerWAV.close(), com.neuronrobotics.sdk.dyio.sequencer.SequencerWAV.getCurrentTime(), com.neuronrobotics.sdk.dyio.sequencer.SequencerWAV.getPercent(), com.neuronrobotics.sdk.dyio.sequencer.SequencerWAV.isPlaying(), com.neuronrobotics.sdk.dyio.sequencer.SequencerWAV.pause(), com.neuronrobotics.sdk.dyio.sequencer.SequencerWAV.play(), com.neuronrobotics.sdk.dyio.sequencer.SequencerWAV.playStep(), com.neuronrobotics.sdk.dyio.sequencer.SequencerWAV.SequencerWAV(), and com.neuronrobotics.sdk.dyio.sequencer.SequencerWAV.setCurrentTime().
trackLength
int com.neuronrobotics.sdk.dyio.sequencer.SequencerWAV.trackLength = 37 private
The track length.
Definition at line 20 of file SequencerWAV.java.
Referenced by com.neuronrobotics.sdk.dyio.sequencer.SequencerWAV.getTrackLength(), and com.neuronrobotics.sdk.dyio.sequencer.SequencerWAV.SequencerWAV().
The documentation for this class was generated from the following file:
src/main/java/com/neuronrobotics/sdk/dyio/sequencer/SequencerWAV.java