BowlerKernel: com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager Class Reference
com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager Class Reference
Public Member Functions
CSGPhysicsManager (List< CSG > baseCSG, Transform pose, double mass, boolean adjustCenter, PhysicsCore core)
CSGPhysicsManager (ArrayList< CSG > baseCSG, Vector3f start, double mass, PhysicsCore core)
void setup (CollisionShape fallShape, Transform pose, double mass, PhysicsCore core)
void update (float timeStep)
RigidBody getFallRigidBody ()
void setFallRigidBody (RigidBody fallRigidBody)
List< CSG > getBaseCSG ()
void setBaseCSG (List< CSG > baseCSG)
Transform getUpdateTransform ()
Affine getRigidBodyLocation ()
IPhysicsUpdate getUpdateManager ()
void setUpdateManager (IPhysicsUpdate updateManager)
PhysicsCore getCore ()
void setCore (PhysicsCore core)
Static Public Member Functions
static CSG getBoundingBox (CSG incoming)
Protected Member Functions
CSG loadCSGToPoints (CSG baseCSG, boolean adjustCenter, Transform pose, ObjectArrayList< Vector3f > arg0)
Protected Attributes
List< CSG > baseCSG = null
Private Attributes
RigidBody fallRigidBody
final Affine ballLocation = new Affine()
Transform updateTransform = new Transform()
IPhysicsUpdate updateManager = null
PhysicsCore core
Detailed Description
Definition at line 30 of file CSGPhysicsManager.java.
Constructor & Destructor Documentation
CSGPhysicsManager() [1/2]
com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager.CSGPhysicsManager (List< CSG > baseCSG, Transform pose, double mass, boolean adjustCenter, PhysicsCore core)
Definition at line 39 of file CSGPhysicsManager.java.
References com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager.baseCSG, com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager.core, com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager.loadCSGToPoints(), com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager.setBaseCSG(), eu.mihosoft.vrl.v3d.CSG.setManipulator(), and com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager.setup().
CSGPhysicsManager() [2/2]
com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager.CSGPhysicsManager (ArrayList< CSG > baseCSG, Vector3f start, double mass, PhysicsCore core)
Definition at line 54 of file CSGPhysicsManager.java.
References com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager.baseCSG, and com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager.core.
Member Function Documentation
getBaseCSG()
List<CSG> com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager.getBaseCSG ()
Return the CSG that tis being modelsed
Implements com.neuronrobotics.bowlerstudio.physics.IPhysicsManager.
Definition at line 143 of file CSGPhysicsManager.java.
References com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager.baseCSG.
getBoundingBox()
static CSG com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager.getBoundingBox (CSG incoming) static
Get Bounding box
Returns
A CSG that completely encapsulates the base CSG, centered around it
Definition at line 98 of file CSGPhysicsManager.java.
References eu.mihosoft.vrl.v3d.CSG.getMaxX(), eu.mihosoft.vrl.v3d.CSG.getMaxY(), eu.mihosoft.vrl.v3d.CSG.getMaxZ(), eu.mihosoft.vrl.v3d.CSG.getMinX(), eu.mihosoft.vrl.v3d.CSG.getMinY(), eu.mihosoft.vrl.v3d.CSG.getMinZ(), eu.mihosoft.vrl.v3d.CSG.movex(), eu.mihosoft.vrl.v3d.CSG.movey(), eu.mihosoft.vrl.v3d.CSG.movez(), eu.mihosoft.vrl.v3d.Primitive.toCSG(), eu.mihosoft.vrl.v3d.CSG.toXMax(), eu.mihosoft.vrl.v3d.CSG.toYMax(), and eu.mihosoft.vrl.v3d.CSG.toZMax().
Referenced by com.neuronrobotics.bowlerstudio.physics.MobileBasePhysicsManager.MobileBasePhysicsManager().
getCore()
PhysicsCore com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager.getCore ()
Definition at line 170 of file CSGPhysicsManager.java.
References com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager.core.
Referenced by com.neuronrobotics.bowlerstudio.physics.HingeCSGPhysicsManager.update().
getFallRigidBody()
RigidBody com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager.getFallRigidBody ()
Return a RigidBody for the physics engine
Implements com.neuronrobotics.bowlerstudio.physics.IPhysicsManager.
Definition at line 134 of file CSGPhysicsManager.java.
References com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager.fallRigidBody.
Referenced by com.neuronrobotics.bowlerstudio.physics.MobileBasePhysicsManager.MobileBasePhysicsManager(), com.neuronrobotics.bowlerstudio.physics.VehicleCSGPhysicsManager.update(), and com.neuronrobotics.bowlerstudio.physics.VehicleCSGPhysicsManager.VehicleCSGPhysicsManager().
getRigidBodyLocation()
Affine com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager.getRigidBodyLocation ()
Return the current spatial location fo the rigid body
Implements com.neuronrobotics.bowlerstudio.physics.IPhysicsManager.
Definition at line 158 of file CSGPhysicsManager.java.
References com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager.ballLocation.
Referenced by com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager.setBaseCSG().
getUpdateManager()
IPhysicsUpdate com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager.getUpdateManager ()
Definition at line 162 of file CSGPhysicsManager.java.
References com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager.updateManager.
Referenced by com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager.update(), com.neuronrobotics.bowlerstudio.physics.VehicleCSGPhysicsManager.update(), and com.neuronrobotics.bowlerstudio.physics.WheelCSGPhysicsManager.update().
getUpdateTransform()
Transform com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager.getUpdateTransform ()
The Bullet version of the location
Implements com.neuronrobotics.bowlerstudio.physics.IPhysicsManager.
Definition at line 154 of file CSGPhysicsManager.java.
References com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager.updateTransform.
Referenced by com.neuronrobotics.bowlerstudio.physics.VehicleCSGPhysicsManager.update(), and com.neuronrobotics.bowlerstudio.physics.WheelCSGPhysicsManager.update().
loadCSGToPoints()
CSG com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager.loadCSGToPoints (CSG baseCSG, boolean adjustCenter, Transform pose, ObjectArrayList< Vector3f > arg0) protected
Definition at line 58 of file CSGPhysicsManager.java.
References com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager.baseCSG, com.neuronrobotics.bowlerstudio.physics.TransformFactory.bulletToNr(), eu.mihosoft.vrl.v3d.CSG.getPolygons(), eu.mihosoft.vrl.v3d.Vertex.getX(), eu.mihosoft.vrl.v3d.Vertex.getY(), eu.mihosoft.vrl.v3d.Vertex.getZ(), eu.mihosoft.vrl.v3d.CSG.movex(), eu.mihosoft.vrl.v3d.CSG.movey(), eu.mihosoft.vrl.v3d.CSG.movez(), com.neuronrobotics.bowlerstudio.physics.TransformFactory.nrToBullet(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.translateX(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.translateY(), and com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.translateZ().
Referenced by com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager.CSGPhysicsManager().
setBaseCSG()
void com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager.setBaseCSG (List< CSG > baseCSG)
Definition at line 147 of file CSGPhysicsManager.java.
References com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager.baseCSG, and com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager.getRigidBodyLocation().
Referenced by com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager.CSGPhysicsManager(), and com.neuronrobotics.bowlerstudio.physics.MobileBasePhysicsManager.MobileBasePhysicsManager().
setCore()
void com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager.setCore (PhysicsCore core)
Definition at line 174 of file CSGPhysicsManager.java.
References com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager.core.
Referenced by com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager.setup().
setFallRigidBody()
void com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager.setFallRigidBody (RigidBody fallRigidBody)
Definition at line 138 of file CSGPhysicsManager.java.
References com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager.fallRigidBody.
Referenced by com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager.setup().
setup()
void com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager.setup (CollisionShape fallShape, Transform pose, double mass, PhysicsCore core)
Definition at line 105 of file CSGPhysicsManager.java.
References com.neuronrobotics.bowlerstudio.physics.TransformFactory.bulletToNr(), com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager.setCore(), and com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager.setFallRigidBody().
Referenced by com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager.CSGPhysicsManager().
setUpdateManager()
void com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager.setUpdateManager (IPhysicsUpdate updateManager)
Definition at line 166 of file CSGPhysicsManager.java.
References com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager.updateManager.
Referenced by com.neuronrobotics.bowlerstudio.physics.MobileBasePhysicsManager.MobileBasePhysicsManager().
update()
void com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager.update (float timeStep)
Run the update for this ridgid body. Run any controllers for links
Implements com.neuronrobotics.bowlerstudio.physics.IPhysicsManager.
Reimplemented in com.neuronrobotics.bowlerstudio.physics.WheelCSGPhysicsManager, com.neuronrobotics.bowlerstudio.physics.VehicleCSGPhysicsManager, and com.neuronrobotics.bowlerstudio.physics.HingeCSGPhysicsManager.
Definition at line 122 of file CSGPhysicsManager.java.
References com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager.fallRigidBody, com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager.getUpdateManager(), com.neuronrobotics.bowlerstudio.physics.IPhysicsUpdate.update(), and com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager.updateTransform.
Member Data Documentation
ballLocation
final Affine com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager.ballLocation = new Affine() private
Definition at line 33 of file CSGPhysicsManager.java.
Referenced by com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager.getRigidBodyLocation().
baseCSG
List<CSG> com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager.baseCSG = null protected
Definition at line 34 of file CSGPhysicsManager.java.
Referenced by com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager.CSGPhysicsManager(), com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager.getBaseCSG(), com.neuronrobotics.bowlerstudio.physics.HingeCSGPhysicsManager.HingeCSGPhysicsManager(), com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager.loadCSGToPoints(), com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager.setBaseCSG(), com.neuronrobotics.bowlerstudio.physics.HingeCSGPhysicsManager.update(), com.neuronrobotics.bowlerstudio.physics.VehicleCSGPhysicsManager.VehicleCSGPhysicsManager(), and com.neuronrobotics.bowlerstudio.physics.WheelCSGPhysicsManager.WheelCSGPhysicsManager().
core
PhysicsCore com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager.core private
Definition at line 37 of file CSGPhysicsManager.java.
Referenced by com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager.CSGPhysicsManager(), com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager.getCore(), com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager.setCore(), and com.neuronrobotics.bowlerstudio.physics.VehicleCSGPhysicsManager.VehicleCSGPhysicsManager().
fallRigidBody
RigidBody com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager.fallRigidBody private
Definition at line 32 of file CSGPhysicsManager.java.
Referenced by com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager.getFallRigidBody(), com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager.setFallRigidBody(), and com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager.update().
updateManager
IPhysicsUpdate com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager.updateManager = null private
Definition at line 36 of file CSGPhysicsManager.java.
Referenced by com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager.getUpdateManager(), and com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager.setUpdateManager().
updateTransform
Transform com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager.updateTransform = new Transform() private
Definition at line 35 of file CSGPhysicsManager.java.
Referenced by com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager.getUpdateTransform(), and com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager.update().
The documentation for this class was generated from the following file:
src/main/java/com/neuronrobotics/bowlerstudio/physics/CSGPhysicsManager.java