BowlerKernel: com.neuronrobotics.bowlerstudio.lipsync.RhubarbManager Class Reference
com.neuronrobotics.bowlerstudio.lipsync.RhubarbManager Class Reference
Public Member Functions
void processRaw (File f, String ttsLocation) throws Exception
AudioInputStream startProcessing (AudioInputStream ais, String TTSString)
AudioStatus update (AudioStatus current, double amplitudeUnitVector, double currentRollingAverage, double currentDerivitiveTerm, double percent)
Static Private Attributes
static String RhubarbVersion = "1.13.0"
Detailed Description
Definition at line 33 of file RhubarbManager.java.
Member Function Documentation
processRaw()
void com.neuronrobotics.bowlerstudio.lipsync.RhubarbManager.processRaw (File f, String ttsLocation) throws Exception
Definition at line 37 of file RhubarbManager.java.
References com.neuronrobotics.bowlerstudio.AudioStatus.get(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getWorkspace(), and com.neuronrobotics.bowlerstudio.lipsync.RhubarbManager.RhubarbVersion.
Referenced by com.neuronrobotics.bowlerstudio.lipsync.RhubarbManager.startProcessing().
startProcessing()
AudioInputStream com.neuronrobotics.bowlerstudio.lipsync.RhubarbManager.startProcessing (AudioInputStream ais, String TTSString)
Implements com.neuronrobotics.bowlerstudio.IAudioProcessingLambda.
Definition at line 112 of file RhubarbManager.java.
References com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getWorkspace(), and com.neuronrobotics.bowlerstudio.lipsync.RhubarbManager.processRaw().
update()
AudioStatus com.neuronrobotics.bowlerstudio.lipsync.RhubarbManager.update (AudioStatus current, double amplitudeUnitVector, double currentRollingAverage, double currentDerivitiveTerm, double percent)
Implements com.neuronrobotics.bowlerstudio.IAudioProcessingLambda.
Definition at line 139 of file RhubarbManager.java.
References com.neuronrobotics.bowlerstudio.AudioStatus.get(), and com.neuronrobotics.bowlerstudio.AudioStatus.X_NO_SOUND.
Member Data Documentation
RhubarbVersion
String com.neuronrobotics.bowlerstudio.lipsync.RhubarbManager.RhubarbVersion = "1.13.0" static private
Definition at line 35 of file RhubarbManager.java.
Referenced by com.neuronrobotics.bowlerstudio.lipsync.RhubarbManager.processRaw().
The documentation for this class was generated from the following file:
src/main/java/com/neuronrobotics/bowlerstudio/lipsync/RhubarbManager.java