BowlerKernel: com.neuronrobotics.sdk.dyio.dypid.DyPIDConfiguration Class Reference
com.neuronrobotics.sdk.dyio.dypid.DyPIDConfiguration Class Reference
Public Member Functions
DyPIDConfiguration (int group)
DyPIDConfiguration (int group, int inputChannel, DyIOChannelMode inputMode, int outputChannel, DyIOChannelMode outputMode)
DyPIDConfiguration (BowlerDatagram conf)
void setGroup (int group)
int getGroup ()
void setInputChannel (int inputChannel)
int getInputChannel ()
void setInputMode (DyIOChannelMode inputMode)
DyIOChannelMode getInputMode ()
void setOutputChannel (int outputChannel)
int getOutputChannel ()
void setOutputMode (DyIOChannelMode outputMode)
DyIOChannelMode getOutputMode ()
Private Attributes
int group
int inputChannel
DyIOChannelMode inputMode =DyIOChannelMode.DIGITAL_IN
int outputChannel
DyIOChannelMode outputMode =DyIOChannelMode.DIGITAL_OUT
Detailed Description
The Class DyPIDConfiguration.
Definition at line 10 of file DyPIDConfiguration.java.
Constructor & Destructor Documentation
DyPIDConfiguration() [1/3]
com.neuronrobotics.sdk.dyio.dypid.DyPIDConfiguration.DyPIDConfiguration (int group)
Instantiates a new dy pid configuration.
Parameters
group the group
Definition at line 32 of file DyPIDConfiguration.java.
References com.neuronrobotics.sdk.dyio.dypid.DyPIDConfiguration.group, com.neuronrobotics.sdk.dyio.dypid.DyPIDConfiguration.setGroup(), com.neuronrobotics.sdk.dyio.dypid.DyPIDConfiguration.setInputChannel(), and com.neuronrobotics.sdk.dyio.dypid.DyPIDConfiguration.setOutputChannel().
DyPIDConfiguration() [2/3]
com.neuronrobotics.sdk.dyio.dypid.DyPIDConfiguration.DyPIDConfiguration (int group, int inputChannel, DyIOChannelMode inputMode, int outputChannel, DyIOChannelMode outputMode)
Instantiates a new dy pid configuration.
Parameters
group the group
inputChannel the input channel
inputMode the input mode
outputChannel the output channel
outputMode the output mode
Definition at line 48 of file DyPIDConfiguration.java.
References com.neuronrobotics.sdk.dyio.dypid.DyPIDConfiguration.group, com.neuronrobotics.sdk.dyio.dypid.DyPIDConfiguration.inputChannel, com.neuronrobotics.sdk.dyio.dypid.DyPIDConfiguration.inputMode, com.neuronrobotics.sdk.dyio.dypid.DyPIDConfiguration.outputChannel, com.neuronrobotics.sdk.dyio.dypid.DyPIDConfiguration.outputMode, com.neuronrobotics.sdk.dyio.dypid.DyPIDConfiguration.setGroup(), com.neuronrobotics.sdk.dyio.dypid.DyPIDConfiguration.setInputChannel(), com.neuronrobotics.sdk.dyio.dypid.DyPIDConfiguration.setInputMode(), com.neuronrobotics.sdk.dyio.dypid.DyPIDConfiguration.setOutputChannel(), and com.neuronrobotics.sdk.dyio.dypid.DyPIDConfiguration.setOutputMode().
DyPIDConfiguration() [3/3]
com.neuronrobotics.sdk.dyio.dypid.DyPIDConfiguration.DyPIDConfiguration (BowlerDatagram conf)
Instantiates a new dy pid configuration.
Parameters
conf the conf
Definition at line 61 of file DyPIDConfiguration.java.
References com.neuronrobotics.sdk.dyio.DyIOChannelMode.get(), com.neuronrobotics.sdk.common.ByteList.get(), com.neuronrobotics.sdk.common.BowlerDatagram.getData(), com.neuronrobotics.sdk.common.ByteList.getUnsigned(), com.neuronrobotics.sdk.dyio.dypid.DyPIDConfiguration.setGroup(), com.neuronrobotics.sdk.dyio.dypid.DyPIDConfiguration.setInputChannel(), com.neuronrobotics.sdk.dyio.dypid.DyPIDConfiguration.setInputMode(), com.neuronrobotics.sdk.dyio.dypid.DyPIDConfiguration.setOutputChannel(), and com.neuronrobotics.sdk.dyio.dypid.DyPIDConfiguration.setOutputMode().
Member Function Documentation
getGroup()
int com.neuronrobotics.sdk.dyio.dypid.DyPIDConfiguration.getGroup ()
Gets the group.
Returns
the group
Definition at line 83 of file DyPIDConfiguration.java.
References com.neuronrobotics.sdk.dyio.dypid.DyPIDConfiguration.group.
Referenced by com.neuronrobotics.sdk.commands.bcs.pid.DyPID.ConfigureDynamicPIDCommand.ConfigureDynamicPIDCommand().
getInputChannel()
int com.neuronrobotics.sdk.dyio.dypid.DyPIDConfiguration.getInputChannel ()
Gets the input channel.
Returns
the input channel
Definition at line 101 of file DyPIDConfiguration.java.
References com.neuronrobotics.sdk.dyio.dypid.DyPIDConfiguration.inputChannel.
Referenced by com.neuronrobotics.sdk.commands.bcs.pid.DyPID.ConfigureDynamicPIDCommand.ConfigureDynamicPIDCommand().
getInputMode()
DyIOChannelMode com.neuronrobotics.sdk.dyio.dypid.DyPIDConfiguration.getInputMode ()
Gets the input mode.
Returns
the input mode
Definition at line 119 of file DyPIDConfiguration.java.
References com.neuronrobotics.sdk.dyio.dypid.DyPIDConfiguration.inputMode.
Referenced by com.neuronrobotics.sdk.commands.bcs.pid.DyPID.ConfigureDynamicPIDCommand.ConfigureDynamicPIDCommand().
getOutputChannel()
int com.neuronrobotics.sdk.dyio.dypid.DyPIDConfiguration.getOutputChannel ()
Gets the output channel.
Returns
the output channel
Definition at line 137 of file DyPIDConfiguration.java.
References com.neuronrobotics.sdk.dyio.dypid.DyPIDConfiguration.outputChannel.
Referenced by com.neuronrobotics.sdk.commands.bcs.pid.DyPID.ConfigureDynamicPIDCommand.ConfigureDynamicPIDCommand().
getOutputMode()
DyIOChannelMode com.neuronrobotics.sdk.dyio.dypid.DyPIDConfiguration.getOutputMode ()
Gets the output mode.
Returns
the output mode
Definition at line 155 of file DyPIDConfiguration.java.
References com.neuronrobotics.sdk.dyio.dypid.DyPIDConfiguration.outputMode.
Referenced by com.neuronrobotics.sdk.commands.bcs.pid.DyPID.ConfigureDynamicPIDCommand.ConfigureDynamicPIDCommand().
setGroup()
void com.neuronrobotics.sdk.dyio.dypid.DyPIDConfiguration.setGroup (int group)
Sets the group.
Parameters
group the new group
Definition at line 74 of file DyPIDConfiguration.java.
References com.neuronrobotics.sdk.dyio.dypid.DyPIDConfiguration.group.
Referenced by com.neuronrobotics.sdk.dyio.dypid.DyPIDConfiguration.DyPIDConfiguration().
setInputChannel()
void com.neuronrobotics.sdk.dyio.dypid.DyPIDConfiguration.setInputChannel (int inputChannel)
Sets the input channel.
Parameters
inputChannel the new input channel
Definition at line 92 of file DyPIDConfiguration.java.
References com.neuronrobotics.sdk.dyio.dypid.DyPIDConfiguration.inputChannel.
Referenced by com.neuronrobotics.sdk.dyio.dypid.DyPIDConfiguration.DyPIDConfiguration().
setInputMode()
void com.neuronrobotics.sdk.dyio.dypid.DyPIDConfiguration.setInputMode (DyIOChannelMode inputMode)
Sets the input mode.
Parameters
inputMode the new input mode
Definition at line 110 of file DyPIDConfiguration.java.
References com.neuronrobotics.sdk.dyio.dypid.DyPIDConfiguration.inputMode.
Referenced by com.neuronrobotics.sdk.dyio.dypid.DyPIDConfiguration.DyPIDConfiguration().
setOutputChannel()
void com.neuronrobotics.sdk.dyio.dypid.DyPIDConfiguration.setOutputChannel (int outputChannel)
Sets the output channel.
Parameters
outputChannel the new output channel
Definition at line 128 of file DyPIDConfiguration.java.
References com.neuronrobotics.sdk.dyio.dypid.DyPIDConfiguration.outputChannel.
Referenced by com.neuronrobotics.sdk.dyio.dypid.DyPIDConfiguration.DyPIDConfiguration().
setOutputMode()
void com.neuronrobotics.sdk.dyio.dypid.DyPIDConfiguration.setOutputMode (DyIOChannelMode outputMode)
Sets the output mode.
Parameters
outputMode the new output mode
Definition at line 146 of file DyPIDConfiguration.java.
References com.neuronrobotics.sdk.dyio.dypid.DyPIDConfiguration.outputMode.
Referenced by com.neuronrobotics.sdk.dyio.dypid.DyPIDConfiguration.DyPIDConfiguration().
Member Data Documentation
group
int com.neuronrobotics.sdk.dyio.dypid.DyPIDConfiguration.group private
The group.
Definition at line 13 of file DyPIDConfiguration.java.
Referenced by com.neuronrobotics.sdk.dyio.dypid.DyPIDConfiguration.DyPIDConfiguration(), com.neuronrobotics.sdk.dyio.dypid.DyPIDConfiguration.getGroup(), and com.neuronrobotics.sdk.dyio.dypid.DyPIDConfiguration.setGroup().
inputChannel
int com.neuronrobotics.sdk.dyio.dypid.DyPIDConfiguration.inputChannel private
The input channel.
Definition at line 16 of file DyPIDConfiguration.java.
Referenced by com.neuronrobotics.sdk.dyio.dypid.DyPIDConfiguration.DyPIDConfiguration(), com.neuronrobotics.sdk.dyio.dypid.DyPIDConfiguration.getInputChannel(), and com.neuronrobotics.sdk.dyio.dypid.DyPIDConfiguration.setInputChannel().
inputMode
DyIOChannelMode com.neuronrobotics.sdk.dyio.dypid.DyPIDConfiguration.inputMode =DyIOChannelMode.DIGITAL_IN private
The input mode.
Definition at line 19 of file DyPIDConfiguration.java.
Referenced by com.neuronrobotics.sdk.dyio.dypid.DyPIDConfiguration.DyPIDConfiguration(), com.neuronrobotics.sdk.dyio.dypid.DyPIDConfiguration.getInputMode(), and com.neuronrobotics.sdk.dyio.dypid.DyPIDConfiguration.setInputMode().
outputChannel
int com.neuronrobotics.sdk.dyio.dypid.DyPIDConfiguration.outputChannel private
The output channel.
Definition at line 22 of file DyPIDConfiguration.java.
Referenced by com.neuronrobotics.sdk.dyio.dypid.DyPIDConfiguration.DyPIDConfiguration(), com.neuronrobotics.sdk.dyio.dypid.DyPIDConfiguration.getOutputChannel(), and com.neuronrobotics.sdk.dyio.dypid.DyPIDConfiguration.setOutputChannel().
outputMode
DyIOChannelMode com.neuronrobotics.sdk.dyio.dypid.DyPIDConfiguration.outputMode =DyIOChannelMode.DIGITAL_OUT private
The output mode.
Definition at line 25 of file DyPIDConfiguration.java.
Referenced by com.neuronrobotics.sdk.dyio.dypid.DyPIDConfiguration.DyPIDConfiguration(), com.neuronrobotics.sdk.dyio.dypid.DyPIDConfiguration.getOutputMode(), and com.neuronrobotics.sdk.dyio.dypid.DyPIDConfiguration.setOutputMode().
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/dyio/dypid/DyPIDConfiguration.java