BowlerKernel: com.neuronrobotics.bowlerstudio.CoquiDockerManager Class Reference
com.neuronrobotics.bowlerstudio.CoquiDockerManager Class Reference
Public Member Functions
void disconnect ()
int speak (String text, float gainValue, boolean daemon, boolean join, ISpeakingProgress progress)
Static Public Member Functions
static int getNummberOfOptions ()
static CoquiDockerManager get (double doubleValue) throws InvalidRemoteException, TransportException, InterruptedException, GitAPIException, IOException, URISyntaxException
Private Member Functions
CoquiDockerManager (String voice) throws InterruptedException, InvalidRemoteException, TransportException, GitAPIException, IOException, URISyntaxException
Private Attributes
String voice
DockerHttpClient client
String id
DockerClient dockerClient
Container forMe = null
int hostPort = 5002
int containerPort = 5002
boolean started =false
int voiceOption =0
Static Private Attributes
static HashMap< String, CoquiDockerManager > managers = new HashMap<>()
static List< String > voiceOptions
static List< String > options = Arrays.asList("tts_models/en/vctk/vits", "tts_models/en/jenny/jenny")
static List< String > speakerNeeded = Arrays.asList("tts_models/en/vctk/vits")
Detailed Description
Definition at line 45 of file CoquiDockerManager.java.
Constructor & Destructor Documentation
CoquiDockerManager()
com.neuronrobotics.bowlerstudio.CoquiDockerManager.CoquiDockerManager (String voice) throws InterruptedException, InvalidRemoteException, TransportException, GitAPIException, IOException, URISyntaxException private
Definition at line 76 of file CoquiDockerManager.java.
References com.neuronrobotics.bowlerstudio.CoquiDockerManager.client, com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.cloneRepo(), com.neuronrobotics.bowlerstudio.CoquiDockerManager.containerPort, com.neuronrobotics.bowlerstudio.CoquiDockerManager.dockerClient, com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.fileFromGit(), com.neuronrobotics.bowlerstudio.CoquiDockerManager.forMe, com.neuronrobotics.bowlerstudio.CoquiDockerManager.hostPort, com.neuronrobotics.bowlerstudio.CoquiDockerManager.managers, com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.pull(), com.neuronrobotics.bowlerstudio.CoquiDockerManager.started, and com.neuronrobotics.bowlerstudio.CoquiDockerManager.voice.
Referenced by com.neuronrobotics.bowlerstudio.CoquiDockerManager.get().
Member Function Documentation
disconnect()
void com.neuronrobotics.bowlerstudio.CoquiDockerManager.disconnect ()
Definition at line 196 of file CoquiDockerManager.java.
References com.neuronrobotics.bowlerstudio.CoquiDockerManager.dockerClient.
get()
static CoquiDockerManager com.neuronrobotics.bowlerstudio.CoquiDockerManager.get (double doubleValue) throws InvalidRemoteException, TransportException, InterruptedException, GitAPIException, IOException, URISyntaxException static
Definition at line 201 of file CoquiDockerManager.java.
References com.neuronrobotics.bowlerstudio.CoquiDockerManager.CoquiDockerManager(), com.neuronrobotics.bowlerstudio.CoquiDockerManager.managers, com.neuronrobotics.bowlerstudio.CoquiDockerManager.options, com.neuronrobotics.bowlerstudio.CoquiDockerManager.voiceOption, and com.neuronrobotics.bowlerstudio.CoquiDockerManager.voiceOptions.
Referenced by com.neuronrobotics.bowlerstudio.BowlerKernel.speak().
getNummberOfOptions()
static int com.neuronrobotics.bowlerstudio.CoquiDockerManager.getNummberOfOptions () static
Definition at line 72 of file CoquiDockerManager.java.
References com.neuronrobotics.bowlerstudio.CoquiDockerManager.options, and com.neuronrobotics.bowlerstudio.CoquiDockerManager.voiceOptions.
speak()
int com.neuronrobotics.bowlerstudio.CoquiDockerManager.speak (String text, float gainValue, boolean daemon, boolean join, ISpeakingProgress progress)
Transform text to speech
Parameters
text The text that will be transformed to speech
daemon
True The thread that will start the text to speech Player will be a daemon Thread
False The thread that will start the text to speech Player will be a normal non daemon Thread
join
True The current Thread calling this method will wait(blocked) until the Thread which is playing the Speech finish
False The current Thread calling this method will continue freely after calling this method
progress
Implements com.neuronrobotics.bowlerstudio.ITTSEngine.
Definition at line 221 of file CoquiDockerManager.java.
References com.neuronrobotics.bowlerstudio.AudioPlayer.setAudio(), com.neuronrobotics.bowlerstudio.AudioPlayer.setGain(), com.neuronrobotics.bowlerstudio.AudioPlayer.setSpeakProgress(), com.neuronrobotics.bowlerstudio.CoquiDockerManager.speakerNeeded, com.neuronrobotics.bowlerstudio.CoquiDockerManager.voice, com.neuronrobotics.bowlerstudio.CoquiDockerManager.voiceOption, and com.neuronrobotics.bowlerstudio.CoquiDockerManager.voiceOptions.
Referenced by com.neuronrobotics.bowlerstudio.BowlerKernel.speak().
Member Data Documentation
client
DockerHttpClient com.neuronrobotics.bowlerstudio.CoquiDockerManager.client private
Definition at line 60 of file CoquiDockerManager.java.
Referenced by com.neuronrobotics.bowlerstudio.CoquiDockerManager.CoquiDockerManager().
containerPort
int com.neuronrobotics.bowlerstudio.CoquiDockerManager.containerPort = 5002 private
Definition at line 68 of file CoquiDockerManager.java.
Referenced by com.neuronrobotics.bowlerstudio.CoquiDockerManager.CoquiDockerManager().
dockerClient
DockerClient com.neuronrobotics.bowlerstudio.CoquiDockerManager.dockerClient private
Definition at line 65 of file CoquiDockerManager.java.
Referenced by com.neuronrobotics.bowlerstudio.CoquiDockerManager.CoquiDockerManager(), and com.neuronrobotics.bowlerstudio.CoquiDockerManager.disconnect().
forMe
Container com.neuronrobotics.bowlerstudio.CoquiDockerManager.forMe = null private
Definition at line 66 of file CoquiDockerManager.java.
Referenced by com.neuronrobotics.bowlerstudio.CoquiDockerManager.CoquiDockerManager().
hostPort
int com.neuronrobotics.bowlerstudio.CoquiDockerManager.hostPort = 5002 private
Definition at line 67 of file CoquiDockerManager.java.
Referenced by com.neuronrobotics.bowlerstudio.CoquiDockerManager.CoquiDockerManager().
id
String com.neuronrobotics.bowlerstudio.CoquiDockerManager.id private
Definition at line 63 of file CoquiDockerManager.java.
managers
HashMap<String, CoquiDockerManager> com.neuronrobotics.bowlerstudio.CoquiDockerManager.managers = new HashMap<>() static private
Definition at line 47 of file CoquiDockerManager.java.
Referenced by com.neuronrobotics.bowlerstudio.CoquiDockerManager.CoquiDockerManager(), and com.neuronrobotics.bowlerstudio.CoquiDockerManager.get().
options
List<String> com.neuronrobotics.bowlerstudio.CoquiDockerManager.options = Arrays.asList("tts_models/en/vctk/vits", "tts_models/en/jenny/jenny") static private
Definition at line 57 of file CoquiDockerManager.java.
Referenced by com.neuronrobotics.bowlerstudio.CoquiDockerManager.get(), and com.neuronrobotics.bowlerstudio.CoquiDockerManager.getNummberOfOptions().
speakerNeeded
List<String> com.neuronrobotics.bowlerstudio.CoquiDockerManager.speakerNeeded = Arrays.asList("tts_models/en/vctk/vits") static private
Definition at line 58 of file CoquiDockerManager.java.
Referenced by com.neuronrobotics.bowlerstudio.CoquiDockerManager.speak().
started
boolean com.neuronrobotics.bowlerstudio.CoquiDockerManager.started =false private
Definition at line 69 of file CoquiDockerManager.java.
Referenced by com.neuronrobotics.bowlerstudio.CoquiDockerManager.CoquiDockerManager().
voice
String com.neuronrobotics.bowlerstudio.CoquiDockerManager.voice private
Definition at line 59 of file CoquiDockerManager.java.
Referenced by com.neuronrobotics.bowlerstudio.CoquiDockerManager.CoquiDockerManager(), and com.neuronrobotics.bowlerstudio.CoquiDockerManager.speak().
voiceOption
int com.neuronrobotics.bowlerstudio.CoquiDockerManager.voiceOption =0 private
Definition at line 70 of file CoquiDockerManager.java.
Referenced by com.neuronrobotics.bowlerstudio.CoquiDockerManager.get(), and com.neuronrobotics.bowlerstudio.CoquiDockerManager.speak().
voiceOptions
List<String> com.neuronrobotics.bowlerstudio.CoquiDockerManager.voiceOptions static private
Initial value:
= Arrays.asList("p225" , "p226" , "p227" , "p228" , "p229" , "p230" , "p231" , "p232" , "p233" , "p234" , "p236" , "p237" ,
        "p238" , "p239" , "p240" , "p241" , "p243" , "p244" , "p245" , "p246" , "p247" , "p248" , "p249" , "p250" , "p251" ,
        "p252" , "p253" , "p254" , "p255" , "p256" , "p257" , "p258" , "p259" , "p260" , "p261" , "p262" , "p263" , "p264" , "p265" , "p266" , "p267" , "p268" , "p269" , "p270" ,
        "p271" , "p272" , "p273" , "p274" , "p275" , "p276" , "p277" , "p278" , "p279" , "p280" , "p281" , "p282" , "p283" , "p284" , "p285" , "p286" , "p287" , "p288" , "p292" ,
        "p293" , "p294" , "p295" , "p297", "p298" , "p299" , "p300" , "p301" , "p302" , "p303" , "p304" , "p305" , "p306" , "p307" , "p308" , "p310" , "p311" , "p312" , "p313" ,
        "p314" , "p316" , "p317" , "p318" , "p323" , "p326" , "p329" , "p330" , "p333" , "p334" , "p335" , "p336" , "p339" , "p340" , "p341" , "p343" , "p345" , "p347" , "p351" ,
        "p360" , "p361" , "p362" , "p363" , "p364" , "p374" , "p376"
    )
Definition at line 49 of file CoquiDockerManager.java.
Referenced by com.neuronrobotics.bowlerstudio.CoquiDockerManager.get(), com.neuronrobotics.bowlerstudio.CoquiDockerManager.getNummberOfOptions(), and com.neuronrobotics.bowlerstudio.CoquiDockerManager.speak().
The documentation for this class was generated from the following file:
src/main/java/com/neuronrobotics/bowlerstudio/CoquiDockerManager.java