BowlerKernel: com.neuronrobotics.bowlerstudio.util.FileChangeWatcher Class Reference
com.neuronrobotics.bowlerstudio.util.FileChangeWatcher Class Reference
Public Member Functions
void addIFileChangeListener (IFileChangeListener l)
void removeIFileChangeListener (IFileChangeListener l)
void watch ()
File getFileToWatch ()
void setFileToWatch (File fileToWatch)
boolean isRun ()
void close ()
Static Public Member Functions
static void clearAll ()
static void notifyOfDelete (File fileToWatch)
static void close (File fileToWatch)
static FileChangeWatcher watch (File fileToWatch) throws IOException
Private Member Functions
FileChangeWatcher (File fileToWatch) throws IOException
void register (Path dir) throws IOException
void registerAll (final Path start) throws IOException
Private Attributes
File fileToWatch
boolean run = true
final WatchService watcher
final Map< WatchKey, Path > keys
final boolean recursive = false
ArrayList< IFileChangeListener > listeners = new ArrayList<IFileChangeListener>()
Thread watcherThread = null
Static Private Attributes
static boolean runThread = true
static HashMap< String, FileChangeWatcher > activeListener = new HashMap<String, FileChangeWatcher>()
Detailed Description
The Class FileChangeWatcher.
Definition at line 48 of file FileChangeWatcher.java.
Constructor & Destructor Documentation
FileChangeWatcher()
com.neuronrobotics.bowlerstudio.util.FileChangeWatcher.FileChangeWatcher (File fileToWatch) throws IOException private
Instantiates a new file change watcher.
Parameters
fileToWatch the file to watch
Exceptions
IOException Signals that an I/O exception has occurred.
Definition at line 130 of file FileChangeWatcher.java.
References com.neuronrobotics.bowlerstudio.util.FileChangeWatcher.fileToWatch, com.neuronrobotics.bowlerstudio.util.FileChangeWatcher.recursive, com.neuronrobotics.bowlerstudio.util.FileChangeWatcher.registerAll(), com.neuronrobotics.bowlerstudio.util.FileChangeWatcher.run, com.neuronrobotics.bowlerstudio.util.FileChangeWatcher.setFileToWatch(), com.neuronrobotics.bowlerstudio.util.FileChangeWatcher.watch(), and com.neuronrobotics.bowlerstudio.util.FileChangeWatcher.watcherThread.
Referenced by com.neuronrobotics.bowlerstudio.util.FileChangeWatcher.watch().
Member Function Documentation
addIFileChangeListener()
void com.neuronrobotics.bowlerstudio.util.FileChangeWatcher.addIFileChangeListener (IFileChangeListener l)
Adds the i file change listener.
Parameters
l the l
Definition at line 178 of file FileChangeWatcher.java.
References com.neuronrobotics.bowlerstudio.util.FileChangeWatcher.listeners.
Referenced by com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.scriptFromFileInfo(), and com.neuronrobotics.bowlerstudio.util.FileWatchDeviceWrapper.watch().
clearAll()
static void com.neuronrobotics.bowlerstudio.util.FileChangeWatcher.clearAll () static
clear the listeners
Definition at line 78 of file FileChangeWatcher.java.
References com.neuronrobotics.bowlerstudio.util.FileChangeWatcher.activeListener.
close() [1/2]
void com.neuronrobotics.bowlerstudio.util.FileChangeWatcher.close ()
Close.
Definition at line 353 of file FileChangeWatcher.java.
References com.neuronrobotics.bowlerstudio.util.FileChangeWatcher.activeListener, com.neuronrobotics.bowlerstudio.util.FileChangeWatcher.fileToWatch, and com.neuronrobotics.bowlerstudio.util.FileChangeWatcher.watcher.
close() [2/2]
static void com.neuronrobotics.bowlerstudio.util.FileChangeWatcher.close (File fileToWatch) static
Definition at line 98 of file FileChangeWatcher.java.
References com.neuronrobotics.bowlerstudio.util.FileChangeWatcher.activeListener, and com.neuronrobotics.bowlerstudio.util.FileChangeWatcher.fileToWatch.
Referenced by com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.closeScriptFromFileInfo(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.deleteFolder().
getFileToWatch()
File com.neuronrobotics.bowlerstudio.util.FileChangeWatcher.getFileToWatch ()
Gets the file to watch.
Returns
the file to watch
Definition at line 327 of file FileChangeWatcher.java.
References com.neuronrobotics.bowlerstudio.util.FileChangeWatcher.fileToWatch.
Referenced by com.neuronrobotics.bowlerstudio.util.FileChangeWatcher.watch().
isRun()
boolean com.neuronrobotics.bowlerstudio.util.FileChangeWatcher.isRun ()
Checks if is run.
Returns
true, if is run
Definition at line 346 of file FileChangeWatcher.java.
References com.neuronrobotics.bowlerstudio.util.FileChangeWatcher.run.
notifyOfDelete()
static void com.neuronrobotics.bowlerstudio.util.FileChangeWatcher.notifyOfDelete (File fileToWatch) static
Definition at line 87 of file FileChangeWatcher.java.
References com.neuronrobotics.bowlerstudio.util.FileChangeWatcher.activeListener, com.neuronrobotics.bowlerstudio.util.FileChangeWatcher.fileToWatch, and com.neuronrobotics.bowlerstudio.util.IFileChangeListener.onFileDelete().
Referenced by com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.deleteFolder().
register()
void com.neuronrobotics.bowlerstudio.util.FileChangeWatcher.register (Path dir) throws IOException private
Register the given directory with the WatchService.
Parameters
dir the dir
Exceptions
IOException Signals that an I/O exception has occurred.
Definition at line 221 of file FileChangeWatcher.java.
References com.neuronrobotics.bowlerstudio.util.FileChangeWatcher.keys, and com.neuronrobotics.bowlerstudio.util.FileChangeWatcher.watcher.
registerAll()
void com.neuronrobotics.bowlerstudio.util.FileChangeWatcher.registerAll (final Path start) throws IOException private
Register the given directory, and all its sub-directories, with the WatchService.
Parameters
start the start
Exceptions
IOException Signals that an I/O exception has occurred.
Definition at line 245 of file FileChangeWatcher.java.
Referenced by com.neuronrobotics.bowlerstudio.util.FileChangeWatcher.FileChangeWatcher().
removeIFileChangeListener()
void com.neuronrobotics.bowlerstudio.util.FileChangeWatcher.removeIFileChangeListener (IFileChangeListener l)
Removes the i file change listener.
Parameters
l the l
Definition at line 190 of file FileChangeWatcher.java.
References com.neuronrobotics.bowlerstudio.util.FileChangeWatcher.listeners.
Referenced by com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.scriptFromFileInfo(), and com.neuronrobotics.bowlerstudio.util.FileWatchDeviceWrapper.watch().
setFileToWatch()
void com.neuronrobotics.bowlerstudio.util.FileChangeWatcher.setFileToWatch (File fileToWatch)
Sets the file to watch.
Parameters
fileToWatch the new file to watch
Definition at line 337 of file FileChangeWatcher.java.
References com.neuronrobotics.bowlerstudio.util.FileChangeWatcher.fileToWatch.
Referenced by com.neuronrobotics.bowlerstudio.util.FileChangeWatcher.FileChangeWatcher().
watch() [1/2]
void com.neuronrobotics.bowlerstudio.util.FileChangeWatcher.watch ()
Perfom the watch execution
Definition at line 259 of file FileChangeWatcher.java.
References com.neuronrobotics.bowlerstudio.util.FileChangeWatcher.fileToWatch, com.neuronrobotics.bowlerstudio.util.FileChangeWatcher.getFileToWatch(), com.neuronrobotics.bowlerstudio.util.FileChangeWatcher.keys, com.neuronrobotics.bowlerstudio.util.FileChangeWatcher.listeners, com.neuronrobotics.bowlerstudio.util.FileChangeWatcher.run, and com.neuronrobotics.bowlerstudio.util.FileChangeWatcher.watcher.
Referenced by com.neuronrobotics.bowlerstudio.util.FileChangeWatcher.FileChangeWatcher().
watch() [2/2]
static FileChangeWatcher com.neuronrobotics.bowlerstudio.util.FileChangeWatcher.watch (File fileToWatch) throws IOException static
Start watching a file
Parameters
fileToWatch a file that should be watched
Returns
the watcher object for this file
Exceptions
IOException
Definition at line 113 of file FileChangeWatcher.java.
References com.neuronrobotics.bowlerstudio.util.FileChangeWatcher.activeListener, com.neuronrobotics.bowlerstudio.util.FileChangeWatcher.FileChangeWatcher(), and com.neuronrobotics.bowlerstudio.util.FileChangeWatcher.fileToWatch.
Referenced by com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.scriptFromFileInfo(), and com.neuronrobotics.bowlerstudio.util.FileWatchDeviceWrapper.watch().
Member Data Documentation
activeListener
HashMap<String, FileChangeWatcher> com.neuronrobotics.bowlerstudio.util.FileChangeWatcher.activeListener = new HashMap<String, FileChangeWatcher>() static private
Definition at line 69 of file FileChangeWatcher.java.
Referenced by com.neuronrobotics.bowlerstudio.util.FileChangeWatcher.clearAll(), com.neuronrobotics.bowlerstudio.util.FileChangeWatcher.close(), com.neuronrobotics.bowlerstudio.util.FileChangeWatcher.notifyOfDelete(), and com.neuronrobotics.bowlerstudio.util.FileChangeWatcher.watch().
fileToWatch
File com.neuronrobotics.bowlerstudio.util.FileChangeWatcher.fileToWatch private
The file to watch.
Definition at line 51 of file FileChangeWatcher.java.
Referenced by com.neuronrobotics.bowlerstudio.util.FileChangeWatcher.close(), com.neuronrobotics.bowlerstudio.util.FileChangeWatcher.FileChangeWatcher(), com.neuronrobotics.bowlerstudio.util.FileChangeWatcher.getFileToWatch(), com.neuronrobotics.bowlerstudio.util.FileChangeWatcher.notifyOfDelete(), com.neuronrobotics.bowlerstudio.util.FileChangeWatcher.setFileToWatch(), and com.neuronrobotics.bowlerstudio.util.FileChangeWatcher.watch().
keys
final Map<WatchKey, Path> com.neuronrobotics.bowlerstudio.util.FileChangeWatcher.keys private
The keys.
Definition at line 60 of file FileChangeWatcher.java.
Referenced by com.neuronrobotics.bowlerstudio.util.FileChangeWatcher.register(), and com.neuronrobotics.bowlerstudio.util.FileChangeWatcher.watch().
listeners
ArrayList<IFileChangeListener> com.neuronrobotics.bowlerstudio.util.FileChangeWatcher.listeners = new ArrayList<IFileChangeListener>() private
The listeners.
Definition at line 66 of file FileChangeWatcher.java.
Referenced by com.neuronrobotics.bowlerstudio.util.FileChangeWatcher.addIFileChangeListener(), com.neuronrobotics.bowlerstudio.util.FileChangeWatcher.removeIFileChangeListener(), and com.neuronrobotics.bowlerstudio.util.FileChangeWatcher.watch().
recursive
final boolean com.neuronrobotics.bowlerstudio.util.FileChangeWatcher.recursive = false private
The recursive.
Definition at line 63 of file FileChangeWatcher.java.
Referenced by com.neuronrobotics.bowlerstudio.util.FileChangeWatcher.FileChangeWatcher().
run
boolean com.neuronrobotics.bowlerstudio.util.FileChangeWatcher.run = true private
The run.
Definition at line 54 of file FileChangeWatcher.java.
Referenced by com.neuronrobotics.bowlerstudio.util.FileChangeWatcher.FileChangeWatcher(), com.neuronrobotics.bowlerstudio.util.FileChangeWatcher.isRun(), and com.neuronrobotics.bowlerstudio.util.FileChangeWatcher.watch().
runThread
boolean com.neuronrobotics.bowlerstudio.util.FileChangeWatcher.runThread = true static private
Definition at line 67 of file FileChangeWatcher.java.
watcher
final WatchService com.neuronrobotics.bowlerstudio.util.FileChangeWatcher.watcher private
The watcher.
Definition at line 57 of file FileChangeWatcher.java.
Referenced by com.neuronrobotics.bowlerstudio.util.FileChangeWatcher.close(), com.neuronrobotics.bowlerstudio.util.FileChangeWatcher.register(), and com.neuronrobotics.bowlerstudio.util.FileChangeWatcher.watch().
watcherThread
Thread com.neuronrobotics.bowlerstudio.util.FileChangeWatcher.watcherThread = null private
Definition at line 70 of file FileChangeWatcher.java.
Referenced by com.neuronrobotics.bowlerstudio.util.FileChangeWatcher.FileChangeWatcher().
The documentation for this class was generated from the following file:
src/main/java/com/neuronrobotics/bowlerstudio/util/FileChangeWatcher.java