BowlerKernel: com.neuronrobotics.sdk.common.Log Class Reference
com.neuronrobotics.sdk.common.Log Class Reference
Classes
class Message
Public Member Functions
String getImportance (int importance)
String getImportanceColor (int importance)
Static Public Member Functions
static void error (String message)
static void warning (String message)
static void info (String message)
static void log (String message)
static void debug (String message)
static void add (String message)
static void enableSystemPrint (boolean systemprint)
static void enableDebugPrint ()
static void enableDebugPrint (boolean flag)
static void enableInfoPrint ()
static void enableWarningPrint ()
static void enableErrorPrint ()
static void setMinimumPrintLevel (int level)
static int getMinimumPrintLevel ()
static Log instance ()
static PrintStream getErrStream ()
static void setErrStream (PrintStream newerrStream)
static PrintStream getOutStream ()
static void setOutStream (PrintStream newoutStream)
static boolean isUseColoredPrints ()
static void setUseColoredPrints (boolean useColoredPrints)
static boolean isPrinting ()
static void error (Throwable ex)
Static Public Attributes
static final int LOG =-1
static final int INFO = 0
static final int DEBUG = 1
static final int WARNING = 2
static final int ERROR = 3
Private Member Functions
Log ()
void add (String message, int importance)
String getColorNormalizationCode ()
Private Attributes
Message m
DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss:SS")
int minprintlevel = WARNING
boolean systemprint = false
boolean debugprint = false
boolean useColoredPrints =false
Static Private Attributes
static Log instance
static PrintStream outStream = System.out
static PrintStream errStream = System.err
Detailed Description
This class is the Logging Class for the NRsdk.
Author
rbreznak
Definition at line 31 of file Log.java.
Constructor & Destructor Documentation
Log()
com.neuronrobotics.sdk.common.Log.Log () private
Instantiates a new log.
Definition at line 82 of file Log.java.
References com.neuronrobotics.sdk.common.Log.add(), com.neuronrobotics.sdk.config.SDKBuildInfo.getSDKVersionString(), and com.neuronrobotics.sdk.common.Log.INFO.
Referenced by com.neuronrobotics.sdk.common.Log.instance().
Member Function Documentation
add() [1/2]
static void com.neuronrobotics.sdk.common.Log.add (String message) static
Add a line to the log.
Parameters
message The line to add
Definition at line 137 of file Log.java.
References com.neuronrobotics.sdk.common.Log.add(), com.neuronrobotics.sdk.common.Log.instance, and com.neuronrobotics.sdk.common.Log.LOG.
Referenced by com.neuronrobotics.sdk.common.Log.add(), com.neuronrobotics.sdk.common.Log.debug(), com.neuronrobotics.sdk.common.Log.error(), com.neuronrobotics.sdk.common.Log.info(), com.neuronrobotics.sdk.common.Log.Log(), com.neuronrobotics.sdk.common.Log.log(), and com.neuronrobotics.sdk.common.Log.warning().
add() [2/2]
void com.neuronrobotics.sdk.common.Log.add (String message, int importance) private
Add a string to the log with a specific importance.
Parameters
message the message to add
importance the importance to log it as.
Definition at line 147 of file Log.java.
References com.neuronrobotics.sdk.common.Log.debugprint, com.neuronrobotics.sdk.common.Log.errStream, com.neuronrobotics.sdk.common.Log.Message.init(), com.neuronrobotics.sdk.common.Log.isPrinting(), com.neuronrobotics.sdk.common.Log.m, com.neuronrobotics.sdk.common.Log.minprintlevel, com.neuronrobotics.sdk.common.Log.outStream, and com.neuronrobotics.sdk.common.Log.systemprint.
debug()
static void com.neuronrobotics.sdk.common.Log.debug (String message) static
Log a debug message.
Parameters
message The debug message to log
Definition at line 128 of file Log.java.
References com.neuronrobotics.sdk.common.Log.add(), com.neuronrobotics.sdk.common.Log.DEBUG, and com.neuronrobotics.sdk.common.Log.instance.
Referenced by com.neuronrobotics.replicator.driver.interpreter.GCodeInterpreter.addDefaultHandlers(), com.neuronrobotics.replicator.driver.interpreter.GCodeInterpreter.executeLine(), com.neuronrobotics.sdk.namespace.bcs.pid.LegacyPidNamespaceImp.GetAllPIDPosition(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getCurrentGist(), com.neuronrobotics.sdk.common.BowlerAbstractConnection.getNamespaces(), com.neuronrobotics.sdk.common.BowlerAbstractDevice.getRevisions(), com.neuronrobotics.sdk.common.BowlerAbstractConnection.getRpcList(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getUserIdOfGist(), com.neuronrobotics.bowlerstudio.scripting.JythonHelper.inlineScriptRun(), com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.onSyncReceive(), com.neuronrobotics.replicator.driver.interpreter.GCodeInterpreter.processSingleGCODELine(), com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.pushAsyncPacket(), com.neuronrobotics.sdk.common.BowlerAbstractConnection.runHeartBeat(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.runHome(), com.neuronrobotics.sdk.dyio.DyIOChannel.setMode(), com.neuronrobotics.sdk.namespace.bcs.pid.LegacyPidNamespaceImp.SetPDVelocity(), com.neuronrobotics.sdk.dyio.peripherals.PPMReaderChannel.updateValues(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.urlToGist().
enableDebugPrint() [1/2]
static void com.neuronrobotics.sdk.common.Log.enableDebugPrint () static
Enable printing of debug output.
Definition at line 187 of file Log.java.
References com.neuronrobotics.sdk.common.Log.DEBUG, com.neuronrobotics.sdk.common.Log.enableSystemPrint(), and com.neuronrobotics.sdk.common.Log.setMinimumPrintLevel().
enableDebugPrint() [2/2]
static void com.neuronrobotics.sdk.common.Log.enableDebugPrint (boolean flag) static
Enable printing of debug output.
Parameters
flag the flag
Definition at line 198 of file Log.java.
References com.neuronrobotics.sdk.common.Log.DEBUG, com.neuronrobotics.sdk.common.Log.enableSystemPrint(), and com.neuronrobotics.sdk.common.Log.setMinimumPrintLevel().
enableErrorPrint()
static void com.neuronrobotics.sdk.common.Log.enableErrorPrint () static
Enable printing of debug output.
Definition at line 225 of file Log.java.
References com.neuronrobotics.sdk.common.Log.enableSystemPrint(), com.neuronrobotics.sdk.common.Log.ERROR, and com.neuronrobotics.sdk.common.Log.setMinimumPrintLevel().
Referenced by com.neuronrobotics.sdk.common.BowlerAbstractConnection.QueueManager.run().
enableInfoPrint()
static void com.neuronrobotics.sdk.common.Log.enableInfoPrint () static
Enable printing of debug output.
Definition at line 207 of file Log.java.
References com.neuronrobotics.sdk.common.Log.enableSystemPrint(), com.neuronrobotics.sdk.common.Log.INFO, and com.neuronrobotics.sdk.common.Log.setMinimumPrintLevel().
Referenced by com.neuronrobotics.sdk.namespace.bcs.pid.PidDeviceServer.main().
enableSystemPrint()
static void com.neuronrobotics.sdk.common.Log.enableSystemPrint (boolean systemprint) static
Enable printing of output to standard out.
Parameters
systemprint the systemprint
Definition at line 179 of file Log.java.
References com.neuronrobotics.sdk.common.Log.instance, and com.neuronrobotics.sdk.common.Log.systemprint.
Referenced by com.neuronrobotics.sdk.common.Log.enableDebugPrint(), com.neuronrobotics.sdk.common.Log.enableErrorPrint(), com.neuronrobotics.sdk.common.Log.enableInfoPrint(), and com.neuronrobotics.sdk.common.Log.enableWarningPrint().
enableWarningPrint()
static void com.neuronrobotics.sdk.common.Log.enableWarningPrint () static
Enable printing of debug output.
Definition at line 216 of file Log.java.
References com.neuronrobotics.sdk.common.Log.enableSystemPrint(), com.neuronrobotics.sdk.common.Log.setMinimumPrintLevel(), and com.neuronrobotics.sdk.common.Log.WARNING.
error() [1/2]
static void com.neuronrobotics.sdk.common.Log.error (String message) static
Log an error message.
Parameters
message the message to log as an error
Definition at line 92 of file Log.java.
References com.neuronrobotics.sdk.common.Log.add(), com.neuronrobotics.sdk.common.Log.ERROR, and com.neuronrobotics.sdk.common.Log.instance.
Referenced by com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.addBowlerDeviceServerNamespace(), com.neuronrobotics.replicator.driver.interpreter.GCodeInterpreter.addDefaultHandlers(), com.neuronrobotics.sdk.common.BowlerRuntimeException.BowlerRuntimeException(), com.neuronrobotics.sdk.network.BowlerTCPClient.BowlerTCPClient(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.checkVector(), com.neuronrobotics.sdk.javaxusb.UsbCDCSerialConnection.connect(), com.neuronrobotics.sdk.serial.SerialConnection.connect(), com.neuronrobotics.sdk.wireless.bluetooth.BluetoothSerialConnection.connect(), com.neuronrobotics.sdk.addons.kinematics.MobileBase.connectDevice(), com.neuronrobotics.sdk.addons.irobot.Create.driveStraightBlocking(), com.neuronrobotics.sdk.common.Log.error(), com.neuronrobotics.sdk.dyio.DyIOChannel.fireModeChangeEvent(), com.neuronrobotics.sdk.namespace.bcs.pid.AbstractPidNamespaceImp.firePIDEvent(), com.neuronrobotics.sdk.common.ByteList.get(), com.neuronrobotics.bowlerstudio.vitamins.Vitamins.get(), com.neuronrobotics.sdk.dyio.DyIO.getAllChannelModes(), com.neuronrobotics.sdk.dyio.DyIO.getAvailibleChannelModes(), com.neuronrobotics.sdk.common.RpcEncapsulation.getCommand(), com.neuronrobotics.sdk.common.BowlerDocumentationFactory.getDocumentationURL(), com.neuronrobotics.sdk.bowlercam.device.BowlerCamDevice.getHighSpeedImage(), com.neuronrobotics.sdk.common.BowlerAbstractConnection.getNamespaces(), com.neuronrobotics.sdk.common.BowlerAbstractDevice.getRevisions(), com.neuronrobotics.sdk.common.BowlerAbstractConnection.getRpcList(), com.neuronrobotics.sdk.common.ByteList.getUnsigned(), com.neuronrobotics.sdk.dyio.DyIOChannel.getValue(), com.neuronrobotics.sdk.network.UDPBowlerConnection.init(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.LinkConfiguration(), com.neuronrobotics.sdk.ui.ConnectionDialog.loadDefaultConnections(), com.neuronrobotics.sdk.common.BowlerAbstractConnection.loadPacketFromPhy(), com.neuronrobotics.sdk.dyio.DyIO.onAsyncResponse(), com.neuronrobotics.sdk.addons.irobot.Create.onChannelEvent(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.onLinkPositionUpdate(), com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.onSyncReceive(), com.neuronrobotics.sdk.common.BowlerDatagram.onTimeout(), com.neuronrobotics.sdk.common.BowlerDatagram.parse(), com.neuronrobotics.sdk.common.RpcEncapsulation.parseResponse(), com.neuronrobotics.sdk.common.BowlerAbstractConnection.ping(), com.neuronrobotics.sdk.dyio.DyIO.powerEvent(), com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.processLocal(), com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.pushAsyncPacket(), com.neuronrobotics.sdk.network.BowlerTCPClient.reconnect(), com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.removeServer(), com.neuronrobotics.sdk.dyio.DyIO.resync(), com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.RotationNR(), com.neuronrobotics.sdk.bowlercam.device.BowlerCamDevice.ImageReader.run(), com.neuronrobotics.sdk.common.BowlerAbstractConnection.QueueManager.run(), com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.runLine(), com.neuronrobotics.sdk.pid.GenericPIDDevice.runOutputHysteresisCalibration(), com.neuronrobotics.sdk.common.BowlerAbstractConnection.QueueManager.runPacketUpdate(), com.neuronrobotics.sdk.common.BowlerAbstractConnection.send(), com.neuronrobotics.sdk.common.BowlerAbstractConnection.sendAsync(), com.neuronrobotics.sdk.common.BowlerAbstractConnection.sendSynchronusly(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.setDevice(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.setGlobalToFiducialTransform(), com.neuronrobotics.sdk.dyio.DyIOChannel.setMode(), com.neuronrobotics.sdk.namespace.bcs.pid.LegacyPidNamespaceImp.SetPDVelocity(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.setRobotToFiducialTransform(), com.neuronrobotics.sdk.addons.irobot.Create.turnBlocking(), com.neuronrobotics.sdk.dyio.DyIOChannel.update(), com.neuronrobotics.sdk.commands.bcs.io.GetChannelModeCommand.validate(), com.neuronrobotics.sdk.dyio.DyIO.validateChannel(), and com.neuronrobotics.sdk.common.BowlerAbstractConnection.write().
error() [2/2]
static void com.neuronrobotics.sdk.common.Log.error (Throwable ex) static
Definition at line 441 of file Log.java.
References com.neuronrobotics.sdk.common.Log.error().
getColorNormalizationCode()
String com.neuronrobotics.sdk.common.Log.getColorNormalizationCode () private
Gets the color normalization code.
Returns
the color normalization code
Definition at line 407 of file Log.java.
References com.neuronrobotics.sdk.common.Log.isUseColoredPrints().
Referenced by com.neuronrobotics.sdk.common.Log.Message.toString().
getErrStream()
static PrintStream com.neuronrobotics.sdk.common.Log.getErrStream () static
get the current error PrintStream.
Returns
the current Error PrintStream
Definition at line 313 of file Log.java.
References com.neuronrobotics.sdk.common.Log.errStream.
getImportance()
String com.neuronrobotics.sdk.common.Log.getImportance (int importance)
Get a string describing the given importance level.
Parameters
importance The given importance level.
Returns
the importance
Definition at line 268 of file Log.java.
References com.neuronrobotics.sdk.common.Log.DEBUG, com.neuronrobotics.sdk.common.Log.ERROR, com.neuronrobotics.sdk.common.Log.INFO, com.neuronrobotics.sdk.common.Log.LOG, and com.neuronrobotics.sdk.common.Log.WARNING.
Referenced by com.neuronrobotics.sdk.common.Log.Message.toString().
getImportanceColor()
String com.neuronrobotics.sdk.common.Log.getImportanceColor (int importance)
Get a string describing the given importance level.
Parameters
importance The given importance level.
Returns
the importance
Definition at line 289 of file Log.java.
References com.neuronrobotics.sdk.common.Log.DEBUG, com.neuronrobotics.sdk.common.Log.ERROR, com.neuronrobotics.sdk.common.Log.INFO, com.neuronrobotics.sdk.common.Log.isUseColoredPrints(), com.neuronrobotics.sdk.common.Log.LOG, and com.neuronrobotics.sdk.common.Log.WARNING.
Referenced by com.neuronrobotics.sdk.common.Log.Message.toString().
getMinimumPrintLevel()
static int com.neuronrobotics.sdk.common.Log.getMinimumPrintLevel () static
Set the minimum level of importance to dsplay. Messages below this wont be displayed.
Returns
the minimum print level
Definition at line 246 of file Log.java.
References com.neuronrobotics.sdk.common.Log.instance, and com.neuronrobotics.sdk.common.Log.minprintlevel.
Referenced by com.neuronrobotics.sdk.common.BowlerAbstractConnection.QueueManager.run().
getOutStream()
static PrintStream com.neuronrobotics.sdk.common.Log.getOutStream () static
Get the current output PrintStream.
Returns
The current output PrintStream
Definition at line 331 of file Log.java.
References com.neuronrobotics.sdk.common.Log.outStream.
info()
static void com.neuronrobotics.sdk.common.Log.info (String message) static
Log a info message.
Parameters
message the message to log as a piece of information.
Definition at line 110 of file Log.java.
References com.neuronrobotics.sdk.common.Log.add(), com.neuronrobotics.sdk.common.Log.INFO, and com.neuronrobotics.sdk.common.Log.instance.
Referenced by com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.AbstractKinematicsNR(), com.neuronrobotics.sdk.common.ByteList.add(), com.neuronrobotics.sdk.wireless.bluetooth.BluetoothSerialConnection.BluetoothSerialConnection(), com.neuronrobotics.sdk.common.device.server.BowlerDeviceReServerNamespace.BowlerDeviceReServerNamespace(), com.neuronrobotics.sdk.network.BowlerTCPClient.BowlerTCPClient(), com.neuronrobotics.sdk.dyio.DyIO.checkFirmwareRev(), com.neuronrobotics.sdk.network.UDPBowlerConnection.connect(), com.neuronrobotics.sdk.wireless.bluetooth.BlueCoveManager.connect(), com.neuronrobotics.sdk.ui.ConnectionDialog.ConnectionDialog(), com.neuronrobotics.sdk.common.BowlerAbstractConnection.disconnect(), com.neuronrobotics.sdk.common.BowlerAbstractDevice.disconnect(), com.neuronrobotics.sdk.wireless.bluetooth.BlueCoveManager.disconnect(), com.neuronrobotics.sdk.addons.irobot.Create.driveStraightBlocking(), com.neuronrobotics.sdk.wireless.bluetooth.BlueCoveManager.find(), com.neuronrobotics.sdk.common.BowlerAbstractConnection.fireAsyncOnResponse(), com.neuronrobotics.sdk.dyio.DyIOChannel.fireChannelEvent(), com.neuronrobotics.sdk.dyio.DyIOChannel.fireModeChangeEvent(), com.neuronrobotics.sdk.dyio.DyIOChannel.flush(), com.neuronrobotics.sdk.namespace.bcs.pid.AbstractPidNamespaceImp.flushPIDChannels(), com.neuronrobotics.sdk.pid.VirtualGenericPIDDevice.flushPIDChannels(), com.neuronrobotics.sdk.network.UDPBowlerConnection.getAllAddresses(), com.neuronrobotics.sdk.dyio.DyIO.getAllChannelValues(), com.neuronrobotics.sdk.dyio.DyIO.getAvailibleChannelModes(), com.neuronrobotics.sdk.ui.ConnectionDialog.getBowlerDevice(), com.neuronrobotics.sdk.ui.BluetoothConnectionPanel.getConnection(), com.neuronrobotics.sdk.ui.SerialConnectionPanel.getConnection(), com.neuronrobotics.sdk.ui.TCPConnectionPanel.getConnection(), com.neuronrobotics.sdk.ui.UsbConnectionPanel.getConnection(), com.neuronrobotics.sdk.bowlercam.device.BowlerCamDevice.getHighSpeedImage(), com.neuronrobotics.sdk.common.BowlerAbstractConnection.getNamespaces(), com.neuronrobotics.sdk.common.BowlerAbstractConnection.getRpcList(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.homeLink(), com.neuronrobotics.sdk.addons.irobot.Create.InitCreateBlocking(), com.neuronrobotics.sdk.network.BowlerUDPServer.loadPacketFromPhy(), com.neuronrobotics.sdk.network.UDPBowlerConnection.loadPacketFromPhy(), com.neuronrobotics.sdk.common.device.server.BowlerAbstractDeviceServer.onAllResponse(), com.neuronrobotics.sdk.bowlercam.device.BowlerCamDevice.onAsyncResponse(), com.neuronrobotics.sdk.dyio.DyIO.onAsyncResponse(), com.neuronrobotics.sdk.common.BowlerAbstractConnection.onDataReceived(), com.neuronrobotics.sdk.namespace.bcs.pid.PidDeviceServer.onPIDEvent(), com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.onSyncReceive(), com.neuronrobotics.sdk.namespace.bcs.pid.PidDeviceServer.PidDeviceServer(), com.neuronrobotics.sdk.namespace.bcs.pid.PidDeviceServerNamespace.PidDeviceServerNamespace(), com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.pushAsyncPacket(), com.neuronrobotics.sdk.wireless.bluetooth.BluetoothSerialConnection.recon(), com.neuronrobotics.sdk.ui.BluetoothConnectionPanel.refresh(), com.neuronrobotics.sdk.dyio.DyIO.resync(), com.neuronrobotics.sdk.common.BowlerAbstractConnection.QueueManager.run(), com.neuronrobotics.sdk.ui.BluetoothConnectionPanel.BluetoothSearchProcess.run(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.runHome(), com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.runLine(), com.neuronrobotics.sdk.common.BowlerAbstractConnection.QueueManager.runPacketUpdate(), com.neuronrobotics.sdk.common.BowlerAbstractConnection.sendSynchronusly(), com.neuronrobotics.sdk.addons.irobot.CreateArm.setAngles(), com.neuronrobotics.sdk.pid.PIDChannel.setCachedTargetValue(), com.neuronrobotics.sdk.addons.irobot.CreateArm.setCartesianPose(), com.neuronrobotics.sdk.common.BowlerAbstractConnection.setConnected(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.setDesiredJointAxisValue(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.setDesiredTaskSpaceTransform(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.setDevice(), com.neuronrobotics.sdk.dyio.DyIOChannel.setMode(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setName(), com.neuronrobotics.sdk.namespace.bcs.pid.LegacyPidNamespaceImp.SetPIDSetPoint(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.setRobotToFiducialTransform(), com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setTargetValue(), com.neuronrobotics.sdk.network.BowlerTCPClient.setTCPSocket(), com.neuronrobotics.sdk.dyio.peripherals.CounterOutputChannel.setValue(), com.neuronrobotics.sdk.addons.irobot.Create.turnBlocking(), com.neuronrobotics.sdk.addons.irobot.CreateArm.updateCartesian(), com.neuronrobotics.sdk.common.BowlerAbstractConnection.waitForConnectioToBeReady(), and com.neuronrobotics.sdk.network.BowlerUDPServer.write().
instance()
static Log com.neuronrobotics.sdk.common.Log.instance () static
Get the current log (singleton) instance.
Returns
The log instance.
Definition at line 255 of file Log.java.
References com.neuronrobotics.sdk.common.Log.instance, and com.neuronrobotics.sdk.common.Log.Log().
isPrinting()
static boolean com.neuronrobotics.sdk.common.Log.isPrinting () static
Checks if is printing.
Returns
true, if is printing
Definition at line 436 of file Log.java.
References com.neuronrobotics.sdk.common.Log.instance, and com.neuronrobotics.sdk.common.Log.systemprint.
Referenced by com.neuronrobotics.sdk.common.Log.add(), and com.neuronrobotics.sdk.common.BowlerDatagram.toString().
isUseColoredPrints()
static boolean com.neuronrobotics.sdk.common.Log.isUseColoredPrints () static
Checks if is use colored prints.
Returns
true, if is use colored prints
Definition at line 418 of file Log.java.
References com.neuronrobotics.sdk.common.Log.instance, and com.neuronrobotics.sdk.common.Log.useColoredPrints.
Referenced by com.neuronrobotics.sdk.common.Log.getColorNormalizationCode(), and com.neuronrobotics.sdk.common.Log.getImportanceColor().
log()
static void com.neuronrobotics.sdk.common.Log.log (String message) static
Log a string.
Parameters
message The string to log.
Definition at line 119 of file Log.java.
References com.neuronrobotics.sdk.common.Log.add(), com.neuronrobotics.sdk.common.Log.instance, and com.neuronrobotics.sdk.common.Log.LOG.
setErrStream()
static void com.neuronrobotics.sdk.common.Log.setErrStream (PrintStream newerrStream) static
set the current error PrintStream.
Parameters
newerrStream the new err stream
Definition at line 322 of file Log.java.
References com.neuronrobotics.sdk.common.Log.errStream.
setMinimumPrintLevel()
static void com.neuronrobotics.sdk.common.Log.setMinimumPrintLevel (int level) static
Set the minimum level of importance to dsplay. Messages below this wont be displayed.
Parameters
level The minimu importance level
Definition at line 236 of file Log.java.
References com.neuronrobotics.sdk.common.Log.instance, and com.neuronrobotics.sdk.common.Log.minprintlevel.
Referenced by com.neuronrobotics.sdk.common.Log.enableDebugPrint(), com.neuronrobotics.sdk.common.Log.enableErrorPrint(), com.neuronrobotics.sdk.common.Log.enableInfoPrint(), com.neuronrobotics.sdk.common.Log.enableWarningPrint(), and com.neuronrobotics.sdk.common.BowlerAbstractConnection.QueueManager.run().
setOutStream()
static void com.neuronrobotics.sdk.common.Log.setOutStream (PrintStream newoutStream) static
Set the current output PrintStream.
Parameters
newoutStream the new out stream
Definition at line 340 of file Log.java.
References com.neuronrobotics.sdk.common.Log.outStream.
setUseColoredPrints()
static void com.neuronrobotics.sdk.common.Log.setUseColoredPrints (boolean useColoredPrints) static
Sets the use colored prints.
Parameters
useColoredPrints the new use colored prints
Definition at line 427 of file Log.java.
References com.neuronrobotics.sdk.common.Log.instance, and com.neuronrobotics.sdk.common.Log.useColoredPrints.
warning()
static void com.neuronrobotics.sdk.common.Log.warning (String message) static
Log an warning message.
Parameters
message the message to log as a warning
Definition at line 101 of file Log.java.
References com.neuronrobotics.sdk.common.Log.add(), com.neuronrobotics.sdk.common.Log.instance, and com.neuronrobotics.sdk.common.Log.WARNING.
Referenced by com.neuronrobotics.sdk.common.DeviceManager.addConnectionBAD(), com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.addServer(), com.neuronrobotics.sdk.network.BowlerTCPServer.connect(), com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.connectDeviceImp(), com.neuronrobotics.sdk.common.ConnectionUnavailableException.ConnectionUnavailableException(), com.neuronrobotics.sdk.network.BowlerTCPClient.disconnect(), com.neuronrobotics.sdk.network.BowlerTCPServer.disconnect(), com.neuronrobotics.sdk.serial.SerialConnection.disconnect(), com.neuronrobotics.sdk.ui.BluetoothConnectionPanel.getConnection(), com.neuronrobotics.sdk.common.BowlerAbstractConnection.getNamespaces(), com.neuronrobotics.sdk.addons.kinematics.math.RotationNRLegacy.getRotAngle(), com.neuronrobotics.sdk.common.MalformattedDatagram.MalformattedDatagram(), com.neuronrobotics.sdk.common.MissingNativeLibraryException.MissingNativeLibraryException(), com.neuronrobotics.sdk.dyio.DyIO.onAsyncResponse(), com.neuronrobotics.sdk.network.BowlerTCPClient.reconnect(), com.neuronrobotics.sdk.common.BowlerAbstractConnection.sendSynchronusly(), com.neuronrobotics.sdk.common.BowlerAbstractConnection.setSynchronusPacketTimeoutTime(), com.neuronrobotics.sdk.common.BowlerDatagram.setUseBowlerV4(), and com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.startNetworkServer().
Member Data Documentation
dateFormat
DateFormat com.neuronrobotics.sdk.common.Log.dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss:SS") private
The date format.
Definition at line 58 of file Log.java.
Referenced by com.neuronrobotics.sdk.common.Log.Message.toString().
DEBUG
final int com.neuronrobotics.sdk.common.Log.DEBUG = 1 static
The Constant DEBUG.
Definition at line 42 of file Log.java.
Referenced by com.neuronrobotics.sdk.common.Log.debug(), com.neuronrobotics.sdk.common.Log.enableDebugPrint(), com.neuronrobotics.sdk.common.Log.getImportance(), and com.neuronrobotics.sdk.common.Log.getImportanceColor().
debugprint
boolean com.neuronrobotics.sdk.common.Log.debugprint = false private
The debugprint.
Definition at line 67 of file Log.java.
Referenced by com.neuronrobotics.sdk.common.Log.add().
ERROR
final int com.neuronrobotics.sdk.common.Log.ERROR = 3 static
The Constant ERROR.
Definition at line 48 of file Log.java.
Referenced by com.neuronrobotics.sdk.common.Log.enableErrorPrint(), com.neuronrobotics.sdk.common.Log.error(), com.neuronrobotics.sdk.common.Log.getImportance(), and com.neuronrobotics.sdk.common.Log.getImportanceColor().
errStream
PrintStream com.neuronrobotics.sdk.common.Log.errStream = System.err static private
The err stream.
Definition at line 73 of file Log.java.
Referenced by com.neuronrobotics.sdk.common.Log.add(), com.neuronrobotics.sdk.common.Log.getErrStream(), and com.neuronrobotics.sdk.common.Log.setErrStream().
INFO
final int com.neuronrobotics.sdk.common.Log.INFO = 0 static
The Constant INFO.
Definition at line 39 of file Log.java.
Referenced by com.neuronrobotics.sdk.common.Log.enableInfoPrint(), com.neuronrobotics.sdk.common.Log.getImportance(), com.neuronrobotics.sdk.common.Log.getImportanceColor(), com.neuronrobotics.sdk.common.Log.info(), and com.neuronrobotics.sdk.common.Log.Log().
instance
Log com.neuronrobotics.sdk.common.Log.instance static private
The instance.
Definition at line 51 of file Log.java.
Referenced by com.neuronrobotics.sdk.common.Log.add(), com.neuronrobotics.sdk.common.Log.debug(), com.neuronrobotics.sdk.common.Log.enableSystemPrint(), com.neuronrobotics.sdk.common.Log.error(), com.neuronrobotics.sdk.common.Log.getMinimumPrintLevel(), com.neuronrobotics.sdk.common.Log.info(), com.neuronrobotics.sdk.common.Log.instance(), com.neuronrobotics.sdk.common.Log.isPrinting(), com.neuronrobotics.sdk.common.Log.isUseColoredPrints(), com.neuronrobotics.sdk.common.Log.log(), com.neuronrobotics.sdk.common.Log.setMinimumPrintLevel(), com.neuronrobotics.sdk.common.Log.setUseColoredPrints(), and com.neuronrobotics.sdk.common.Log.warning().
LOG
final int com.neuronrobotics.sdk.common.Log.LOG =-1 static
The Constant LOG.
Definition at line 36 of file Log.java.
Referenced by com.neuronrobotics.sdk.common.Log.add(), com.neuronrobotics.sdk.common.Log.getImportance(), com.neuronrobotics.sdk.common.Log.getImportanceColor(), and com.neuronrobotics.sdk.common.Log.log().
m
Message com.neuronrobotics.sdk.common.Log.m private
The messages.
Definition at line 54 of file Log.java.
Referenced by com.neuronrobotics.sdk.common.Log.add().
minprintlevel
int com.neuronrobotics.sdk.common.Log.minprintlevel = WARNING private
The minprintlevel.
Definition at line 61 of file Log.java.
Referenced by com.neuronrobotics.sdk.common.Log.add(), com.neuronrobotics.sdk.common.Log.getMinimumPrintLevel(), and com.neuronrobotics.sdk.common.Log.setMinimumPrintLevel().
outStream
PrintStream com.neuronrobotics.sdk.common.Log.outStream = System.out static private
The out stream.
Definition at line 70 of file Log.java.
Referenced by com.neuronrobotics.sdk.common.Log.add(), com.neuronrobotics.sdk.common.Log.getOutStream(), and com.neuronrobotics.sdk.common.Log.setOutStream().
systemprint
boolean com.neuronrobotics.sdk.common.Log.systemprint = false private
The systemprint.
Definition at line 64 of file Log.java.
Referenced by com.neuronrobotics.sdk.common.Log.add(), com.neuronrobotics.sdk.common.Log.enableSystemPrint(), and com.neuronrobotics.sdk.common.Log.isPrinting().
useColoredPrints
boolean com.neuronrobotics.sdk.common.Log.useColoredPrints =false private
The use colored prints.
Definition at line 76 of file Log.java.
Referenced by com.neuronrobotics.sdk.common.Log.isUseColoredPrints(), and com.neuronrobotics.sdk.common.Log.setUseColoredPrints().
WARNING
final int com.neuronrobotics.sdk.common.Log.WARNING = 2 static
The Constant WARNING.
Definition at line 45 of file Log.java.
Referenced by com.neuronrobotics.sdk.common.Log.enableWarningPrint(), com.neuronrobotics.sdk.common.Log.getImportance(), com.neuronrobotics.sdk.common.Log.getImportanceColor(), and com.neuronrobotics.sdk.common.Log.warning().
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/common/Log.java