BowlerKernel: com.neuronrobotics.imageprovider.NativeResource Class Reference
com.neuronrobotics.imageprovider.NativeResource Class Reference
Public Member Functions
synchronized void load (String libraryName) throws NativeResourceException
Static Public Member Functions
static File inJarLoad (Class inputClass, String name) throws IOException
static File inJarLoad (InputStream inputStream, String name) throws IOException
static void copyResource (InputStream io, File file) throws IOException
static File prepResourceLocation (String fileName) throws NativeResourceException
static boolean is64Bit ()
static boolean isARM ()
static boolean isCortexA8 ()
static boolean isWindows ()
static boolean isLinux ()
static boolean isOSX ()
static String getExtension ()
static String getOsName ()
static String getOsArch ()
static String getIdentifier ()
Private Member Functions
void inJarLoad (String name) throws UnsatisfiedLinkError, NativeResourceException
void loadLib (String name) throws NativeResourceException
void testNativeCode () throws UnsatisfiedLinkError
InputStream locateResource (String name)
void loadResource (File resource)
Private Attributes
boolean loaded = false
Detailed Description
Definition at line 9 of file NativeResource.java.
Member Function Documentation
copyResource()
static void com.neuronrobotics.imageprovider.NativeResource.copyResource (InputStream io, File file) throws IOException static
Definition at line 116 of file NativeResource.java.
Referenced by com.neuronrobotics.imageprovider.NativeResource.inJarLoad().
getExtension()
static String com.neuronrobotics.imageprovider.NativeResource.getExtension () static
Definition at line 225 of file NativeResource.java.
Referenced by com.neuronrobotics.imageprovider.NativeResource.locateResource(), and com.neuronrobotics.imageprovider.NativeResource.prepResourceLocation().
getIdentifier()
static String com.neuronrobotics.imageprovider.NativeResource.getIdentifier () static
Definition at line 238 of file NativeResource.java.
References com.neuronrobotics.imageprovider.NativeResource.getOsArch(), and com.neuronrobotics.imageprovider.NativeResource.getOsName().
getOsArch()
static String com.neuronrobotics.imageprovider.NativeResource.getOsArch () static
Definition at line 233 of file NativeResource.java.
Referenced by com.neuronrobotics.imageprovider.NativeResource.getIdentifier(), com.neuronrobotics.imageprovider.NativeResource.is64Bit(), com.neuronrobotics.imageprovider.NativeResource.isARM(), and com.neuronrobotics.imageprovider.NativeResource.locateResource().
getOsName()
static String com.neuronrobotics.imageprovider.NativeResource.getOsName () static
Definition at line 229 of file NativeResource.java.
Referenced by com.neuronrobotics.imageprovider.NativeResource.getIdentifier(), com.neuronrobotics.imageprovider.NativeResource.isLinux(), com.neuronrobotics.imageprovider.NativeResource.isOSX(), and com.neuronrobotics.imageprovider.NativeResource.isWindows().
inJarLoad() [1/3]
static File com.neuronrobotics.imageprovider.NativeResource.inJarLoad (Class inputClass, String name) throws IOException static
Definition at line 49 of file NativeResource.java.
References com.neuronrobotics.imageprovider.NativeResource.copyResource(), and com.neuronrobotics.imageprovider.NativeResource.prepResourceLocation().
inJarLoad() [2/3]
static File com.neuronrobotics.imageprovider.NativeResource.inJarLoad (InputStream inputStream, String name) throws IOException static
Definition at line 58 of file NativeResource.java.
References com.neuronrobotics.imageprovider.NativeResource.copyResource(), and com.neuronrobotics.imageprovider.NativeResource.prepResourceLocation().
inJarLoad() [3/3]
void com.neuronrobotics.imageprovider.NativeResource.inJarLoad (String name) throws UnsatisfiedLinkError, NativeResourceException private
Definition at line 34 of file NativeResource.java.
References com.neuronrobotics.imageprovider.NativeResource.loadResource(), com.neuronrobotics.imageprovider.NativeResource.locateResource(), and com.neuronrobotics.imageprovider.NativeResource.testNativeCode().
Referenced by com.neuronrobotics.imageprovider.NativeResource.loadLib().
is64Bit()
static boolean com.neuronrobotics.imageprovider.NativeResource.is64Bit () static
Definition at line 198 of file NativeResource.java.
References com.neuronrobotics.imageprovider.NativeResource.getOsArch().
Referenced by com.neuronrobotics.imageprovider.NativeResource.locateResource().
isARM()
static boolean com.neuronrobotics.imageprovider.NativeResource.isARM () static
Definition at line 202 of file NativeResource.java.
References com.neuronrobotics.imageprovider.NativeResource.getOsArch().
Referenced by com.neuronrobotics.imageprovider.NativeResource.isCortexA8(), and com.neuronrobotics.imageprovider.NativeResource.locateResource().
isCortexA8()
static boolean com.neuronrobotics.imageprovider.NativeResource.isCortexA8 () static
Definition at line 205 of file NativeResource.java.
References com.neuronrobotics.imageprovider.NativeResource.isARM().
isLinux()
static boolean com.neuronrobotics.imageprovider.NativeResource.isLinux () static
Definition at line 217 of file NativeResource.java.
References com.neuronrobotics.imageprovider.NativeResource.getOsName().
Referenced by com.neuronrobotics.imageprovider.NativeResource.locateResource().
isOSX()
static boolean com.neuronrobotics.imageprovider.NativeResource.isOSX () static
Definition at line 221 of file NativeResource.java.
References com.neuronrobotics.imageprovider.NativeResource.getOsName().
Referenced by com.neuronrobotics.imageprovider.NativeResource.locateResource().
isWindows()
static boolean com.neuronrobotics.imageprovider.NativeResource.isWindows () static
Definition at line 212 of file NativeResource.java.
References com.neuronrobotics.imageprovider.NativeResource.getOsName().
Referenced by com.neuronrobotics.imageprovider.NativeResource.locateResource().
load()
synchronized void com.neuronrobotics.imageprovider.NativeResource.load (String libraryName) throws NativeResourceException
Definition at line 12 of file NativeResource.java.
References com.neuronrobotics.imageprovider.NativeResource.loaded, and com.neuronrobotics.imageprovider.NativeResource.loadLib().
loadLib()
void com.neuronrobotics.imageprovider.NativeResource.loadLib (String name) throws NativeResourceException private
Definition at line 67 of file NativeResource.java.
References com.neuronrobotics.imageprovider.NativeResource.inJarLoad().
Referenced by com.neuronrobotics.imageprovider.NativeResource.load().
loadResource()
void com.neuronrobotics.imageprovider.NativeResource.loadResource (File resource) private
Definition at line 109 of file NativeResource.java.
Referenced by com.neuronrobotics.imageprovider.NativeResource.inJarLoad().
locateResource()
InputStream com.neuronrobotics.imageprovider.NativeResource.locateResource (String name) private
Definition at line 80 of file NativeResource.java.
References com.neuronrobotics.imageprovider.NativeResource.getExtension(), com.neuronrobotics.imageprovider.NativeResource.getOsArch(), com.neuronrobotics.imageprovider.NativeResource.is64Bit(), com.neuronrobotics.imageprovider.NativeResource.isARM(), com.neuronrobotics.imageprovider.NativeResource.isLinux(), com.neuronrobotics.imageprovider.NativeResource.isOSX(), and com.neuronrobotics.imageprovider.NativeResource.isWindows().
Referenced by com.neuronrobotics.imageprovider.NativeResource.inJarLoad().
prepResourceLocation()
static File com.neuronrobotics.imageprovider.NativeResource.prepResourceLocation (String fileName) throws NativeResourceException static
Definition at line 129 of file NativeResource.java.
References com.neuronrobotics.imageprovider.NativeResource.getExtension().
Referenced by com.neuronrobotics.imageprovider.NativeResource.inJarLoad().
testNativeCode()
void com.neuronrobotics.imageprovider.NativeResource.testNativeCode () throws UnsatisfiedLinkError private
Definition at line 76 of file NativeResource.java.
Referenced by com.neuronrobotics.imageprovider.NativeResource.inJarLoad().
Member Data Documentation
loaded
boolean com.neuronrobotics.imageprovider.NativeResource.loaded = false private
Definition at line 11 of file NativeResource.java.
Referenced by com.neuronrobotics.imageprovider.NativeResource.load().
The documentation for this class was generated from the following file:
src/main/java/com/neuronrobotics/imageprovider/NativeResource.java