BowlerKernel: eu.mihosoft.vrl.v3d.ChamferedCylinder Class Reference
eu.mihosoft.vrl.v3d.ChamferedCylinder Class Reference
Public Member Functions
PropertyStorage getProperties ()
ChamferedCylinder (double r, double h, double chamferHeight)
List< Polygon > toPolygons ()
Public Member Functions inherited from eu.mihosoft.vrl.v3d.Primitive
CSG toCSG ()
Private Attributes
final PropertyStorage properties = new PropertyStorage()
Detailed Description
Definition at line 5 of file ChamferedCylinder.java.
Constructor & Destructor Documentation
ChamferedCylinder()
eu.mihosoft.vrl.v3d.ChamferedCylinder.ChamferedCylinder (double r, double h, double chamferHeight)
Constructor. Creates a new cuboid with center
[0,0,0]
and with the specified dimensions.
Parameters
r radius
h height
chamferHeight the chamfer height
Definition at line 23 of file ChamferedCylinder.java.
Member Function Documentation
getProperties()
PropertyStorage eu.mihosoft.vrl.v3d.ChamferedCylinder.getProperties ()
Returns the property storage of this primitive.
Returns
the property storage of this primitive
Reimplemented from eu.mihosoft.vrl.v3d.Primitive.
Definition at line 11 of file ChamferedCylinder.java.
References eu.mihosoft.vrl.v3d.ChamferedCylinder.properties.
toPolygons()
List<Polygon> eu.mihosoft.vrl.v3d.ChamferedCylinder.toPolygons ()
Returns the polygons that define this primitive.
Note: this method computes the polygons each time this method is called. The polygons can be cached inside a CSG object.
Returns
a list of polygons that define this primitive
Reimplemented from eu.mihosoft.vrl.v3d.Primitive.
Definition at line 36 of file ChamferedCylinder.java.
References eu.mihosoft.vrl.v3d.CSG.getPolygons(), eu.mihosoft.vrl.v3d.CSG.hull(), eu.mihosoft.vrl.v3d.CSG.movez(), eu.mihosoft.vrl.v3d.Primitive.toCSG(), and eu.mihosoft.vrl.v3d.CSG.union().
Member Data Documentation
properties
final PropertyStorage eu.mihosoft.vrl.v3d.ChamferedCylinder.properties = new PropertyStorage() private
The properties.
Definition at line 9 of file ChamferedCylinder.java.
Referenced by eu.mihosoft.vrl.v3d.ChamferedCylinder.getProperties().
The documentation for this class was generated from the following file:
JCSG/src/main/java/eu/mihosoft/vrl/v3d/ChamferedCylinder.java