BowlerKernel: com.neuronrobotics.sdk.addons.kinematics.AnalogPrismaticLink Class Reference
com.neuronrobotics.sdk.addons.kinematics.AnalogPrismaticLink Class Reference
Public Member Functions
AnalogPrismaticLink (AnalogInputChannel c, LinkConfiguration conf)
void cacheTargetValueDevice ()
void flushDevice (double time)
void flushAllDevice (double time)
double getCurrentPosition ()
void setAnalogChannel (AnalogInputChannel channel)
AnalogInputChannel getChannel ()
void onAnalogValueChange (AnalogInputChannel chan, double value)
Public Member Functions inherited from com.neuronrobotics.sdk.addons.kinematics.AbstractPrismaticLink
AbstractPrismaticLink (LinkConfiguration conf)
void incrementDisplacment (double inc)
void setTargetDisplacment (double pos)
void setCurrentAsDisplacment (double Displacment)
double getCurrentDisplacment ()
double getTargetDisplacment ()
double getMaxDisplacment ()
double getMinDisplacment ()
boolean isMaxDisplacment ()
boolean isMinDisplacment ()
Public Member Functions inherited from com.neuronrobotics.sdk.addons.kinematics.AbstractLink
double getDeviceMaximumValue ()
double getDeviceMinimumValue ()
void setDeviceMaximumValue (double max)
void setDeviceMinimumValue (double min)
double getDeviceMaxEngineeringUnits ()
double getDeviceMinEngineeringUnits ()
AbstractLink (LinkConfiguration conf)
void cacheTargetValue ()
void flush (double time)
void flushAll (double time)
double toEngineeringUnits (double value)
double toLinkUnits (double euValue)
void addLinkListener (ILinkListener l)
void removeLinkListener (ILinkListener l)
void fireLinkListener (double linkUnitsValue)
void fireLinkLimitEvent (PIDLimitEvent e)
void Home ()
void incrementEngineeringUnits (double inc)
void setTargetEngineeringUnits (double pos)
void setCurrentEngineeringUnits (double angle)
double getCurrentEngineeringUnits ()
double getTargetEngineeringUnits ()
double getMaxEngineeringUnits ()
double getMinEngineeringUnits ()
void setMinEngineeringUnits (double minLimit)
void setMaxEngineeringUnits (double maxLimit)
double getMaxVelocityEngineeringUnits ()
void setMaxVelocityEngineeringUnits (double max)
boolean isMaxEngineeringUnits ()
boolean isMinEngineeringUnits ()
double getTargetValue ()
void setUpperLimit (int upperLimit)
void setLowerLimit (int lowerLimit)
void setHome (int home)
void setScale (double d)
double getScale ()
double getUpperLimit ()
double getLowerLimit ()
double getHome ()
void setCurrentAsUpperLimit ()
void setCurrentAsLowerLimit ()
void setUseLimits (boolean useLimits)
boolean isUseLimits ()
void setLinkConfiguration (LinkConfiguration conf)
LinkConfiguration getLinkConfiguration ()
ArrayList< ILinkListener > getLinks ()
void setLinks (ArrayList< ILinkListener > links)
void removeAllLinkListener ()
void setGlobalPositionListener (Object Object)
Object getGlobalPositionListener ()
LinkFactory getSlaveFactory ()
void setSlaveFactory (LinkFactory slaveFactory)
IMU getImu ()
void addChangeListener (ILinkConfigurationChangeListener l)
void removeChangeListener (ILinkConfigurationChangeListener l)
void clearChangeListener ()
Private Attributes
AnalogInputChannel channel
Additional Inherited Members
Protected Member Functions inherited from com.neuronrobotics.sdk.addons.kinematics.AbstractLink
void setPosition (double val)
void setTargetValue (double val)
Detailed Description
The Class AnalogPrismaticLink.
Definition at line 11 of file AnalogPrismaticLink.java.
Constructor & Destructor Documentation
AnalogPrismaticLink()
com.neuronrobotics.sdk.addons.kinematics.AnalogPrismaticLink.AnalogPrismaticLink (AnalogInputChannel c, LinkConfiguration conf)
Instantiates a new analog prismatic link.
Parameters
c the c
conf the conf
Definition at line 22 of file AnalogPrismaticLink.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractLink.conf, and com.neuronrobotics.sdk.addons.kinematics.AnalogPrismaticLink.setAnalogChannel().
Member Function Documentation
cacheTargetValueDevice()
void com.neuronrobotics.sdk.addons.kinematics.AnalogPrismaticLink.cacheTargetValueDevice ()
This method is called in order to take the target value and pass it to the implementation's target value This method should not alter the position of the implementations link If the implementation target does not handle chached values, this should be chached in code.
Reimplemented from com.neuronrobotics.sdk.addons.kinematics.AbstractLink.
Definition at line 32 of file AnalogPrismaticLink.java.
flushAllDevice()
void com.neuronrobotics.sdk.addons.kinematics.AnalogPrismaticLink.flushAllDevice (double time)
This method will force one link to update its position in the given time (seconds) This will also flush the host controller.
Parameters
time (seconds) for the position update to take
Reimplemented from com.neuronrobotics.sdk.addons.kinematics.AbstractLink.
Definition at line 48 of file AnalogPrismaticLink.java.
flushDevice()
void com.neuronrobotics.sdk.addons.kinematics.AnalogPrismaticLink.flushDevice (double time)
This method will force one link to update its position in the given time (seconds).
Parameters
time (seconds) for the position update to take
Reimplemented from com.neuronrobotics.sdk.addons.kinematics.AbstractLink.
Definition at line 40 of file AnalogPrismaticLink.java.
getChannel()
AnalogInputChannel com.neuronrobotics.sdk.addons.kinematics.AnalogPrismaticLink.getChannel ()
Gets the channel.
Returns
the channel
Definition at line 79 of file AnalogPrismaticLink.java.
References com.neuronrobotics.sdk.addons.kinematics.AnalogPrismaticLink.channel.
Referenced by com.neuronrobotics.sdk.addons.kinematics.AnalogPrismaticLink.getCurrentPosition(), and com.neuronrobotics.sdk.addons.kinematics.AnalogPrismaticLink.onAnalogValueChange().
getCurrentPosition()
double com.neuronrobotics.sdk.addons.kinematics.AnalogPrismaticLink.getCurrentPosition ()
This method should return the current position of the link This method is expected to perform a communication with the device .
Returns
the current position of the link
Reimplemented from com.neuronrobotics.sdk.addons.kinematics.AbstractLink.
Definition at line 56 of file AnalogPrismaticLink.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractLink.fireLinkListener(), com.neuronrobotics.sdk.addons.kinematics.AnalogPrismaticLink.getChannel(), and com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral.getValue().
onAnalogValueChange()
void com.neuronrobotics.sdk.addons.kinematics.AnalogPrismaticLink.onAnalogValueChange (AnalogInputChannel chan, double value)
IAnalogInputListener.
Parameters
chan the chan
value The value of the analog channel is sent to listeners
Implements com.neuronrobotics.sdk.dyio.peripherals.IAnalogInputListener.
Definition at line 87 of file AnalogPrismaticLink.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractLink.fireLinkListener(), and com.neuronrobotics.sdk.addons.kinematics.AnalogPrismaticLink.getChannel().
setAnalogChannel()
void com.neuronrobotics.sdk.addons.kinematics.AnalogPrismaticLink.setAnalogChannel (AnalogInputChannel channel)
Sets the analog channel.
Parameters
channel the new analog channel
Definition at line 67 of file AnalogPrismaticLink.java.
References com.neuronrobotics.sdk.dyio.peripherals.AnalogInputChannel.addAnalogInputListener(), com.neuronrobotics.sdk.addons.kinematics.AnalogPrismaticLink.channel, and com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral.configAdvancedAsyncNotEqual().
Referenced by com.neuronrobotics.sdk.addons.kinematics.AnalogPrismaticLink.AnalogPrismaticLink().
Member Data Documentation
channel
AnalogInputChannel com.neuronrobotics.sdk.addons.kinematics.AnalogPrismaticLink.channel private
The channel.
Definition at line 14 of file AnalogPrismaticLink.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.AnalogPrismaticLink.getChannel(), and com.neuronrobotics.sdk.addons.kinematics.AnalogPrismaticLink.setAnalogChannel().
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/addons/kinematics/AnalogPrismaticLink.java