BowlerKernel: eu.mihosoft.vrl.v3d.Vertex Class Reference
eu.mihosoft.vrl.v3d.Vertex Class Reference
Public Member Functions
Vertex (Vector3d pos, Vector3d normal)
Vertex clone ()
void flip ()
Vertex interpolate (Vertex other, double t)
String toStlString ()
StringBuilder toStlString (StringBuilder sb)
StringBuilder toObjString (StringBuilder sb)
String toObjString ()
Vertex transform (Transform transform)
Vertex transformed (Transform transform)
double getWeight ()
void setWeight (double weight)
int hashCode ()
boolean equals (Object obj)
String toString ()
double getX ()
double getY ()
double getZ ()
Public Attributes
Vector3d pos
Vector3d normal
Private Member Functions
Vertex (Vector3d pos, Vector3d normal, double weight)
Private Attributes
double weight = 1.0
Detailed Description
Represents a vertex of a polygon. This class provides normal so primitives like Cube can return a smooth vertex normal, but normal is not used anywhere else.
Definition at line 44 of file Vertex.java.
Constructor & Destructor Documentation
Vertex() [1/2]
eu.mihosoft.vrl.v3d.Vertex.Vertex (Vector3d pos, Vector3d normal)
Constructor. Creates a vertex.
Parameters
pos position
normal normal
Definition at line 65 of file Vertex.java.
References eu.mihosoft.vrl.v3d.Vertex.normal, and eu.mihosoft.vrl.v3d.Vertex.pos.
Referenced by eu.mihosoft.vrl.v3d.Vertex.clone(), eu.mihosoft.vrl.v3d.Vertex.equals(), and eu.mihosoft.vrl.v3d.Vertex.interpolate().
Vertex() [2/2]
eu.mihosoft.vrl.v3d.Vertex.Vertex (Vector3d pos, Vector3d normal, double weight) private
Constructor. Creates a vertex.
Parameters
pos position
normal normal
weight weight
Definition at line 78 of file Vertex.java.
References eu.mihosoft.vrl.v3d.Vertex.normal, eu.mihosoft.vrl.v3d.Vertex.pos, and eu.mihosoft.vrl.v3d.Vertex.weight.
Member Function Documentation
clone()
Vertex eu.mihosoft.vrl.v3d.Vertex.clone ()
Definition at line 88 of file Vertex.java.
References eu.mihosoft.vrl.v3d.Vector3d.clone(), eu.mihosoft.vrl.v3d.Vertex.normal, eu.mihosoft.vrl.v3d.Vertex.pos, eu.mihosoft.vrl.v3d.Vertex.Vertex(), and eu.mihosoft.vrl.v3d.Vertex.weight.
Referenced by eu.mihosoft.vrl.v3d.Plane.splitPolygon(), and eu.mihosoft.vrl.v3d.Vertex.transformed().
equals()
boolean eu.mihosoft.vrl.v3d.Vertex.equals (Object obj)
Definition at line 205 of file Vertex.java.
References eu.mihosoft.vrl.v3d.Plane.EPSILON_Point, eu.mihosoft.vrl.v3d.Vertex.pos, eu.mihosoft.vrl.v3d.Vector3d.test(), and eu.mihosoft.vrl.v3d.Vertex.Vertex().
Referenced by eu.mihosoft.vrl.v3d.Edge._toPolygons(), eu.mihosoft.vrl.v3d.Edge.boundaryPaths(), and eu.mihosoft.vrl.v3d.Edge.toPolygons().
flip()
void eu.mihosoft.vrl.v3d.Vertex.flip ()
Inverts all orientation-specific data. (e.g. vertex normal).
Definition at line 95 of file Vertex.java.
References eu.mihosoft.vrl.v3d.Vector3d.negated(), and eu.mihosoft.vrl.v3d.Vertex.normal.
getWeight()
double eu.mihosoft.vrl.v3d.Vertex.getWeight ()
Gets the weight.
Returns
the weight
Definition at line 178 of file Vertex.java.
References eu.mihosoft.vrl.v3d.Vertex.weight.
getX()
double eu.mihosoft.vrl.v3d.Vertex.getX ()
Definition at line 228 of file Vertex.java.
References eu.mihosoft.vrl.v3d.Vertex.pos, and eu.mihosoft.vrl.v3d.Vector3d.x().
Referenced by com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager.loadCSGToPoints(), eu.mihosoft.vrl.v3d.CSG.move(), eu.mihosoft.vrl.v3d.Transform.move(), and eu.mihosoft.vrl.v3d.Edge.toString().
getY()
double eu.mihosoft.vrl.v3d.Vertex.getY ()
Definition at line 231 of file Vertex.java.
References eu.mihosoft.vrl.v3d.Vertex.pos, and eu.mihosoft.vrl.v3d.Vector3d.y().
Referenced by com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager.loadCSGToPoints(), eu.mihosoft.vrl.v3d.CSG.move(), eu.mihosoft.vrl.v3d.Transform.move(), and eu.mihosoft.vrl.v3d.Edge.toString().
getZ()
double eu.mihosoft.vrl.v3d.Vertex.getZ ()
Definition at line 234 of file Vertex.java.
References eu.mihosoft.vrl.v3d.Vertex.pos, and eu.mihosoft.vrl.v3d.Vector3d.z().
Referenced by eu.mihosoft.vrl.v3d.Slice.isVertexAtZero(), com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager.loadCSGToPoints(), eu.mihosoft.vrl.v3d.CSG.move(), eu.mihosoft.vrl.v3d.Transform.move(), and eu.mihosoft.vrl.v3d.Edge.toString().
hashCode()
int eu.mihosoft.vrl.v3d.Vertex.hashCode ()
Definition at line 195 of file Vertex.java.
interpolate()
Vertex eu.mihosoft.vrl.v3d.Vertex.interpolate (Vertex other, double t)
Create a new vertex between this vertex and the specified vertex by linearly interpolating all properties using a parameter t.
Parameters
other vertex
t interpolation parameter
Returns
a new vertex between this and the specified vertex
Definition at line 107 of file Vertex.java.
References eu.mihosoft.vrl.v3d.Vector3d.lerp(), eu.mihosoft.vrl.v3d.Vertex.normal, eu.mihosoft.vrl.v3d.Vertex.pos, and eu.mihosoft.vrl.v3d.Vertex.Vertex().
Referenced by eu.mihosoft.vrl.v3d.Plane.splitPolygon().
setWeight()
void eu.mihosoft.vrl.v3d.Vertex.setWeight (double weight)
Sets the weight.
Parameters
weight the weight to set
Definition at line 187 of file Vertex.java.
References eu.mihosoft.vrl.v3d.Vertex.weight.
toObjString() [1/2]
String eu.mihosoft.vrl.v3d.Vertex.toObjString ()
Returns this vertex in OBJ string format.
Returns
this vertex in OBJ string format
Definition at line 148 of file Vertex.java.
toObjString() [2/2]
StringBuilder eu.mihosoft.vrl.v3d.Vertex.toObjString (StringBuilder sb)
Returns this vertex in OBJ string format.
Parameters
sb string builder
Returns
the specified string builder
Definition at line 138 of file Vertex.java.
References eu.mihosoft.vrl.v3d.Vector3d.toObjString().
Referenced by eu.mihosoft.vrl.v3d.CSG.toObjString().
toStlString() [1/2]
String eu.mihosoft.vrl.v3d.Vertex.toStlString ()
Returns this vertex in STL string format.
Returns
this vertex in STL string format
Definition at line 117 of file Vertex.java.
References eu.mihosoft.vrl.v3d.Vector3d.toStlString().
toStlString() [2/2]
StringBuilder eu.mihosoft.vrl.v3d.Vertex.toStlString (StringBuilder sb)
Returns this vertex in STL string format.
Parameters
sb string builder
Returns
the specified string builder
Definition at line 127 of file Vertex.java.
References eu.mihosoft.vrl.v3d.Vector3d.toStlString().
toString()
String eu.mihosoft.vrl.v3d.Vertex.toString ()
Definition at line 223 of file Vertex.java.
References eu.mihosoft.vrl.v3d.Vertex.pos, and eu.mihosoft.vrl.v3d.Vector3d.toString().
transform()
Vertex eu.mihosoft.vrl.v3d.Vertex.transform (Transform transform)
Applies the specified transform to this vertex.
Parameters
transform the transform to apply
Returns
this vertex
Definition at line 158 of file Vertex.java.
References eu.mihosoft.vrl.v3d.Vertex.pos, eu.mihosoft.vrl.v3d.Vector3d.transform(), and eu.mihosoft.vrl.v3d.Vertex.weight.
Referenced by eu.mihosoft.vrl.v3d.CSG.toObjString(), and eu.mihosoft.vrl.v3d.Vertex.transformed().
transformed()
Vertex eu.mihosoft.vrl.v3d.Vertex.transformed (Transform transform)
Applies the specified transform to a copy of this vertex.
Parameters
transform the transform to apply
Returns
a copy of this transform
Definition at line 169 of file Vertex.java.
References eu.mihosoft.vrl.v3d.Vertex.clone(), and eu.mihosoft.vrl.v3d.Vertex.transform().
Member Data Documentation
normal
Vector3d eu.mihosoft.vrl.v3d.Vertex.normal
Normal.
Definition at line 54 of file Vertex.java.
Referenced by eu.mihosoft.vrl.v3d.Vertex.clone(), eu.mihosoft.vrl.v3d.Vertex.flip(), eu.mihosoft.vrl.v3d.Vertex.interpolate(), and eu.mihosoft.vrl.v3d.Vertex.Vertex().
pos
Vector3d eu.mihosoft.vrl.v3d.Vertex.pos
Vertex position.
Definition at line 49 of file Vertex.java.
Referenced by eu.mihosoft.vrl.v3d.Edge._toPolygons(), eu.mihosoft.vrl.v3d.Edge.boundaryPaths(), eu.mihosoft.vrl.v3d.Vertex.clone(), eu.mihosoft.vrl.v3d.Edge.colinear(), eu.mihosoft.vrl.v3d.Polygon.contains(), eu.mihosoft.vrl.v3d.Edge.contains(), eu.mihosoft.vrl.v3d.Bounds.contains(), eu.mihosoft.vrl.v3d.Edge.Edge(), eu.mihosoft.vrl.v3d.Edge.equals(), eu.mihosoft.vrl.v3d.Vertex.equals(), eu.mihosoft.vrl.v3d.Edge.falseBoundaryEdgeSharedWithOtherEdge(), eu.mihosoft.vrl.v3d.CSG.getBounds(), eu.mihosoft.vrl.v3d.Polygon.getBounds(), eu.mihosoft.vrl.v3d.Edge.getClosestPoint(), eu.mihosoft.vrl.v3d.Vertex.getX(), eu.mihosoft.vrl.v3d.Vertex.getY(), eu.mihosoft.vrl.v3d.Vertex.getZ(), eu.mihosoft.vrl.v3d.Vertex.interpolate(), eu.mihosoft.vrl.v3d.Extrude.isCCW(), eu.mihosoft.vrl.v3d.Edge.isThisPointOneOfMine(), eu.mihosoft.vrl.v3d.Edge.length(), eu.mihosoft.vrl.v3d.CSGtoJavafx.meshFromPolygon(), eu.mihosoft.vrl.v3d.CSG.minkowskiHullShape(), eu.mihosoft.vrl.v3d.ext.org.poly2tri.PolygonUtil.pruneDuplicatePoints(), eu.mihosoft.vrl.v3d.Plane.splitPolygon(), eu.mihosoft.vrl.v3d.Edge.toPolygons(), eu.mihosoft.vrl.v3d.svg.SVGExporter.toPolyLine(), eu.mihosoft.vrl.v3d.Vertex.toString(), eu.mihosoft.vrl.v3d.Vertex.transform(), and eu.mihosoft.vrl.v3d.Vertex.Vertex().
weight
double eu.mihosoft.vrl.v3d.Vertex.weight = 1.0 private
The weight.
Definition at line 57 of file Vertex.java.
Referenced by eu.mihosoft.vrl.v3d.Vertex.clone(), eu.mihosoft.vrl.v3d.Vertex.getWeight(), eu.mihosoft.vrl.v3d.Vertex.setWeight(), eu.mihosoft.vrl.v3d.Vertex.transform(), and eu.mihosoft.vrl.v3d.Vertex.Vertex().
The documentation for this class was generated from the following file:
JCSG/src/main/java/eu/mihosoft/vrl/v3d/Vertex.java