BowlerKernel: eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.PointInfo Class Reference
eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.PointInfo Class Reference
Public Member Functions
boolean isBoundary ()
boolean hasInternalEdge ()
Detailed Description
The Class PointInfo.
Definition at line 499 of file SymbolicSubdivisionBuilder.java.
Member Function Documentation
hasInternalEdge()
boolean eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.PointInfo.hasInternalEdge ()
A point is internal if at least one of its adjacent edges is not in the boundary.
Returns
true, if successful
Definition at line 526 of file SymbolicSubdivisionBuilder.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.edgeInfos.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.calcControlPoint(), and eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.calcControlTexCoord().
isBoundary()
boolean eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.PointInfo.isBoundary ()
A point is in the boundary if any of its adjacent edges is in the boundary.
Returns
true, if is boundary
Definition at line 512 of file SymbolicSubdivisionBuilder.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.edgeInfos.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.calcControlPoint(), and eu.mihosoft.vrl.v3d.ext.openjfx.shape3d.symbolic.SymbolicSubdivisionBuilder.calcControlTexCoord().
The documentation for this class was generated from the following file:
JCSG/src/main/java/eu/mihosoft/vrl/v3d/ext/openjfx/shape3d/symbolic/SymbolicSubdivisionBuilder.java