BowlerKernel: com.neuronrobotics.sdk.bowlercam.device.BowlerCamDevice.highSpeedAutoCapture Class Reference
com.neuronrobotics.sdk.bowlercam.device.BowlerCamDevice.highSpeedAutoCapture Class Reference
Public Member Functions
highSpeedAutoCapture (int cam, double scale, int fps)
void run ()
void kill ()
Detailed Description
The Class highSpeedAutoCapture.
Definition at line 319 of file BowlerCamDevice.java.
Constructor & Destructor Documentation
highSpeedAutoCapture()
com.neuronrobotics.sdk.bowlercam.device.BowlerCamDevice.highSpeedAutoCapture.highSpeedAutoCapture (int cam, double scale, int fps)
Instantiates a new high speed auto capture.
Parameters
cam the cam
scale the scale
fps the fps
Definition at line 340 of file BowlerCamDevice.java.
Member Function Documentation
kill()
void com.neuronrobotics.sdk.bowlercam.device.BowlerCamDevice.highSpeedAutoCapture.kill ()
Kill.
Definition at line 390 of file BowlerCamDevice.java.
run()
void com.neuronrobotics.sdk.bowlercam.device.BowlerCamDevice.highSpeedAutoCapture.run ()
Definition at line 354 of file BowlerCamDevice.java.
References com.neuronrobotics.sdk.bowlercam.device.BowlerCamDevice.fireIWebcamImageListenerEvent(), com.neuronrobotics.sdk.bowlercam.device.BowlerCamDevice.getHighSpeedImage(), com.neuronrobotics.sdk.common.BowlerAbstractDevice.isAvailable(), and com.neuronrobotics.sdk.bowlercam.device.BowlerCamDevice.resize().
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/bowlercam/device/BowlerCamDevice.java