BowlerKernel: com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral Class Reference
com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral Class Reference abstract
Public Member Functions
DyIOAbstractPeripheral (DyIOChannel channel, DyIOChannelMode myMode, boolean async)
DyIOChannelMode getClassMode ()
boolean isEnabled ()
boolean setMode ()
boolean setMode (boolean async)
boolean setMode (DyIOChannelMode mode, boolean async)
DyIOChannel getChannel ()
DyIOChannelMode getMode ()
boolean setValue (int value) throws InvalidResponseException
boolean setValue (ByteList value) throws InvalidResponseException
int getValue () throws InvalidResponseException
boolean SavePosition (int pos)
abstract boolean hasAsync ()
boolean configAdvancedAsyncNotEqual ()
boolean configAdvancedAsyncDeadBand (int deadbandSize)
boolean configAdvancedAsyncTreshhold (int threshholdValue, AsyncThreshholdEdgeType edgeType)
boolean configAdvancedAsyncAutoSample ()
boolean configAdvancedAsyncNotEqual (int msTime)
boolean configAdvancedAsyncDeadBand (int msTime, int deadbandSize)
boolean configAdvancedAsyncTreshhold (int msTime, int threshholdValue, AsyncThreshholdEdgeType edgeType)
boolean configAdvancedAsyncAutoSample (int msTime)
boolean flush ()
void setAsync (boolean b)
int getConfiguration ()
Private Member Functions
int getConfigurationFromDevice ()
void setConfiguration (int configuration)
Private Attributes
DyIOChannel channel
boolean enabled = false
int configuration =0
Detailed Description
The Class DyIOAbstractPeripheral.
Definition at line 31 of file DyIOAbstractPeripheral.java.
Constructor & Destructor Documentation
DyIOAbstractPeripheral()
com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral.DyIOAbstractPeripheral (DyIOChannel channel, DyIOChannelMode myMode, boolean async)
DyIOAbstractPeripheral.
Parameters
channel The channel object to set up as whatever peripheral is needed
myMode the my mode
async the async
Definition at line 49 of file DyIOAbstractPeripheral.java.
References com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral.channel, com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral.getConfigurationFromDevice(), com.neuronrobotics.sdk.dyio.DyIOChannel.getMode(), com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral.setConfiguration(), and com.neuronrobotics.sdk.dyio.DyIOChannel.setMode().
Member Function Documentation
configAdvancedAsyncAutoSample() [1/2]
boolean com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral.configAdvancedAsyncAutoSample ()
This method configures the advanced async mode for a given DyIO channel to trigger on any event where the value is sampled on a real-time This sets the sample time to 100 ms clock and sent as async regardless of value change.
Returns
true if success
Definition at line 280 of file DyIOAbstractPeripheral.java.
configAdvancedAsyncAutoSample() [2/2]
boolean com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral.configAdvancedAsyncAutoSample (int msTime)
This method configures the advanced async mode for a given DyIO channel to trigger on any event where the value is sampled on a real-time clock and sent as async regardless of value change.
Parameters
msTime the sample time in MiliSeconds
Returns
true if success
Definition at line 322 of file DyIOAbstractPeripheral.java.
configAdvancedAsyncDeadBand() [1/2]
boolean com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral.configAdvancedAsyncDeadBand (int deadbandSize)
This method configures the advanced async mode for a given DyIO channel to trigger on any event where the values are outside a deadband This sets the sample time to 100 ms.
Parameters
deadbandSize the size in sensor units of the deadband
Returns
true if success
Definition at line 257 of file DyIOAbstractPeripheral.java.
configAdvancedAsyncDeadBand() [2/2]
boolean com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral.configAdvancedAsyncDeadBand (int msTime, int deadbandSize)
This method configures the advanced async mode for a given DyIO channel to trigger on any event where the values are outside a deadband.
Parameters
msTime the sample time in MiliSeconds
deadbandSize the size in sensor units of the deadband
Returns
true if success
Definition at line 299 of file DyIOAbstractPeripheral.java.
configAdvancedAsyncNotEqual() [1/2]
boolean com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral.configAdvancedAsyncNotEqual ()
This method configures the advanced async mode for a given DyIO channel to trigger on any event where the values are not equal. This sets the sample time to 100 ms
Returns
true is success
Definition at line 246 of file DyIOAbstractPeripheral.java.
Referenced by com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.addAnalogInputListener(), com.neuronrobotics.sdk.addons.kinematics.AnalogPrismaticLink.setAnalogChannel(), and com.neuronrobotics.sdk.addons.kinematics.AnalogRotoryLink.setAnalogChannel().
configAdvancedAsyncNotEqual() [2/2]
boolean com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral.configAdvancedAsyncNotEqual (int msTime)
This method configures the advanced async mode for a given DyIO channel to trigger on any event where the values are not equal.
Parameters
msTime the sample time in MiliSeconds
Returns
true if success
Definition at line 288 of file DyIOAbstractPeripheral.java.
configAdvancedAsyncTreshhold() [1/2]
boolean com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral.configAdvancedAsyncTreshhold (int msTime, int threshholdValue, AsyncThreshholdEdgeType edgeType)
This method configures the advanced async mode for a given DyIO channel to trigger on any event where the value crosses a threshhold.
Parameters
msTime the sample time in MiliSeconds
threshholdValue a value setpoint that triggers an even when it is crossed
edgeType Rising, Falling, or both
Returns
true if success
Definition at line 311 of file DyIOAbstractPeripheral.java.
configAdvancedAsyncTreshhold() [2/2]
boolean com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral.configAdvancedAsyncTreshhold (int threshholdValue, AsyncThreshholdEdgeType edgeType)
This method configures the advanced async mode for a given DyIO channel to trigger on any event where the value crosses a threshhold This sets the sample time to 100 ms.
Parameters
threshholdValue a value setpoint that triggers an even when it is crossed
edgeType Rising, Falling, or both
Returns
true if success
Definition at line 269 of file DyIOAbstractPeripheral.java.
flush()
boolean com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral.flush ()
THis method performs a cache flush on the channel wrapped by this object.
Returns
true if success
Definition at line 331 of file DyIOAbstractPeripheral.java.
Referenced by com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.addServoChannel(), com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.flush(), com.neuronrobotics.sdk.dyio.peripherals.CounterOutputChannel.SetPosition(), com.neuronrobotics.sdk.dyio.peripherals.ServoChannel.SetPosition(), and com.neuronrobotics.sdk.dyio.DyIOChannel.setValue().
getChannel()
DyIOChannel com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral.getChannel ()
Returns the channel object used by the peripheral.
Returns
returns the channel object
Implements com.neuronrobotics.sdk.dyio.IDyIOChannel.
Definition at line 141 of file DyIOAbstractPeripheral.java.
References com.neuronrobotics.sdk.dyio.DyIOChannel.getChannel().
Referenced by com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.addServoChannel(), com.neuronrobotics.sdk.dyio.peripherals.AnalogInputChannel.AnalogInputChannel(), com.neuronrobotics.sdk.dyio.peripherals.CounterInputChannel.CounterInputChannel(), com.neuronrobotics.sdk.dyio.peripherals.CounterOutputChannel.CounterOutputChannel(), com.neuronrobotics.sdk.dyio.peripherals.DCMotorOutputChannel.DCMotorOutputChannel(), com.neuronrobotics.sdk.dyio.peripherals.DigitalInputChannel.DigitalInputChannel(), com.neuronrobotics.sdk.dyio.peripherals.DigitalOutputChannel.DigitalOutputChannel(), com.neuronrobotics.sdk.dyio.peripherals.ServoChannel.disablePowerOverride(), com.neuronrobotics.sdk.dyio.peripherals.ServoChannel.enablePowerOverride(), com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.getAnalogInputChannelNumber(), com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.getChannelNumber(), com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral.getConfigurationFromDevice(), com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.getInputChannelNumber(), com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.initInput(), com.neuronrobotics.sdk.dyio.peripherals.PPMReaderChannel.PPMReaderChannel(), com.neuronrobotics.sdk.dyio.peripherals.PWMOutputChannel.PWMOutputChannel(), com.neuronrobotics.sdk.dyio.peripherals.ServoChannel.ServoChannel(), com.neuronrobotics.sdk.dyio.peripherals.PPMReaderChannel.setCrossLink(), com.neuronrobotics.sdk.dyio.peripherals.CounterOutputChannel.SetPosition(), com.neuronrobotics.sdk.dyio.peripherals.ServoChannel.SetPosition(), and com.neuronrobotics.sdk.dyio.peripherals.PPMReaderChannel.updateValues().
getClassMode()
DyIOChannelMode com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral.getClassMode ()
This method retrieves the channel mode of this peripheral.
Returns
the class mode
Definition at line 89 of file DyIOAbstractPeripheral.java.
getConfiguration()
int com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral.getConfiguration ()
Gets the configuration.
Returns
the configuration
Definition at line 349 of file DyIOAbstractPeripheral.java.
getConfigurationFromDevice()
int com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral.getConfigurationFromDevice () private
Gets the configuration from device.
Returns
the configuration from device
Definition at line 65 of file DyIOAbstractPeripheral.java.
References com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral.channel, com.neuronrobotics.sdk.common.BowlerMethod.CRITICAL, com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral.getChannel(), com.neuronrobotics.sdk.dyio.DyIOChannel.getChannelNumber(), com.neuronrobotics.sdk.dyio.DyIOChannel.getDevice(), com.neuronrobotics.sdk.dyio.DyIOChannel.getMode(), com.neuronrobotics.sdk.dyio.DyIO.send(), and com.neuronrobotics.sdk.dyio.DyIOChannelMode.SERVO_OUT.
Referenced by com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral.DyIOAbstractPeripheral().
getMode()
DyIOChannelMode com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral.getMode ()
This method gets the current mode of this peripheral.
Returns
returns the mode of this channel
Implements com.neuronrobotics.sdk.dyio.IDyIOChannel.
Definition at line 151 of file DyIOAbstractPeripheral.java.
Referenced by com.neuronrobotics.sdk.dyio.peripherals.CounterOutputChannel.validate(), and com.neuronrobotics.sdk.dyio.peripherals.ServoChannel.validate().
getValue()
int com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral.getValue () throws InvalidResponseException
This method gets the value of the given peripheral.
Returns
the value of the channel on the DyIO
Exceptions
InvalidResponseException the invalid response exception
Implements com.neuronrobotics.sdk.dyio.IDyIOChannel.
Definition at line 186 of file DyIOAbstractPeripheral.java.
Referenced by com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.addServoChannel(), com.neuronrobotics.sdk.addons.kinematics.AnalogPrismaticLink.getCurrentPosition(), com.neuronrobotics.sdk.addons.kinematics.AnalogRotoryLink.getCurrentPosition(), com.neuronrobotics.sdk.dyio.peripherals.AnalogInputChannel.getScaledValue(), com.neuronrobotics.sdk.dyio.peripherals.DigitalInputChannel.isHigh(), com.neuronrobotics.sdk.dyio.peripherals.DigitalOutputChannel.isHigh(), and com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.ServoOutputScheduleChannel().
hasAsync()
abstract boolean com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral.hasAsync () abstract
This method is to check if this peripheral is capable to be set as up as asynchronous.
Returns
if it cna be async
Reimplemented in com.neuronrobotics.sdk.dyio.peripherals.UARTChannel.UARTRxChannel, com.neuronrobotics.sdk.dyio.peripherals.UARTChannel.UARTTxChannel, com.neuronrobotics.sdk.dyio.peripherals.ServoChannel, com.neuronrobotics.sdk.dyio.peripherals.PWMOutputChannel, com.neuronrobotics.sdk.dyio.peripherals.PPMReaderChannel, com.neuronrobotics.sdk.dyio.peripherals.DigitalOutputChannel, com.neuronrobotics.sdk.dyio.peripherals.DigitalInputChannel, com.neuronrobotics.sdk.dyio.peripherals.DCMotorOutputChannel, com.neuronrobotics.sdk.dyio.peripherals.CounterOutputChannel, com.neuronrobotics.sdk.dyio.peripherals.CounterInputChannel, and com.neuronrobotics.sdk.dyio.peripherals.AnalogInputChannel.
isEnabled()
boolean com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral.isEnabled ()
isEnabled.
Returns
if the channel is enabled
Definition at line 98 of file DyIOAbstractPeripheral.java.
Referenced by com.neuronrobotics.sdk.dyio.peripherals.CounterOutputChannel.validate(), and com.neuronrobotics.sdk.dyio.peripherals.ServoChannel.validate().
SavePosition()
boolean com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral.SavePosition (int pos)
This method sets the value of the output of the giver peripheral, and also stores this value as the "default" value in non volatile memory to use at startup of the peripheral.
Parameters
pos the position to set as the new starting point for the channel
Returns
if the save worked or not.
Definition at line 199 of file DyIOAbstractPeripheral.java.
References com.neuronrobotics.sdk.common.BowlerMethod.CRITICAL.
setAsync()
void com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral.setAsync (boolean b)
This method sets the async mode for this peripheral .
Parameters
b if it should be async or not
Reimplemented in com.neuronrobotics.sdk.dyio.peripherals.DigitalInputChannel, com.neuronrobotics.sdk.dyio.peripherals.CounterOutputChannel, com.neuronrobotics.sdk.dyio.peripherals.CounterInputChannel, and com.neuronrobotics.sdk.dyio.peripherals.AnalogInputChannel.
Definition at line 340 of file DyIOAbstractPeripheral.java.
setConfiguration()
void com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral.setConfiguration (int configuration) private
Sets the configuration.
Parameters
configuration the new configuration
Definition at line 358 of file DyIOAbstractPeripheral.java.
Referenced by com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral.DyIOAbstractPeripheral().
setMode() [1/3]
boolean com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral.setMode ()
This sets the mode of this peripheral.
Returns
if the set worked. Not all channels have all peripherals
Definition at line 107 of file DyIOAbstractPeripheral.java.
Referenced by com.neuronrobotics.sdk.dyio.peripherals.AnalogInputChannel.AnalogInputChannel(), com.neuronrobotics.sdk.dyio.peripherals.DCMotorOutputChannel.DCMotorOutputChannel(), com.neuronrobotics.sdk.dyio.peripherals.DigitalInputChannel.DigitalInputChannel(), com.neuronrobotics.sdk.dyio.peripherals.DigitalOutputChannel.DigitalOutputChannel(), com.neuronrobotics.sdk.dyio.peripherals.PPMReaderChannel.PPMReaderChannel(), com.neuronrobotics.sdk.dyio.peripherals.PWMOutputChannel.PWMOutputChannel(), com.neuronrobotics.sdk.dyio.peripherals.ServoChannel.ServoChannel(), com.neuronrobotics.sdk.dyio.peripherals.AnalogInputChannel.setAsync(), com.neuronrobotics.sdk.dyio.peripherals.CounterInputChannel.setAsync(), com.neuronrobotics.sdk.dyio.peripherals.CounterOutputChannel.setAsync(), and com.neuronrobotics.sdk.dyio.peripherals.DigitalInputChannel.setAsync().
setMode() [2/3]
boolean com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral.setMode (boolean async)
This method sets the current mode of this peripheral.
Parameters
async If the channel should be set into async mode
Returns
if the set worked. Not all channels have all peripherals
Definition at line 117 of file DyIOAbstractPeripheral.java.
setMode() [3/3]
boolean com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral.setMode (DyIOChannelMode mode, boolean async)
This method sets the current mode of this peripheral.
Parameters
mode the DyIO mode to set the channel to
async If the channel should be set into async mode
Returns
if the set worked. Not all channels have all peripherals
Exceptions
InvalidResponseException the invalid response exception
Implements com.neuronrobotics.sdk.dyio.IDyIOChannel.
Definition at line 129 of file DyIOAbstractPeripheral.java.
setValue() [1/2]
boolean com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral.setValue (ByteList value) throws InvalidResponseException
This method sets the value of the output of the giver peripheral.
Parameters
value Sets this value to the channel
Returns
if the set worked
Exceptions
InvalidResponseException the invalid response exception
Implements com.neuronrobotics.sdk.dyio.IDyIOChannel.
Definition at line 175 of file DyIOAbstractPeripheral.java.
setValue() [2/2]
boolean com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral.setValue (int value) throws InvalidResponseException
This method sets the value of the output of the giver peripheral.
Parameters
value Sets this value to the channel
Returns
if the set worked
Exceptions
InvalidResponseException the invalid response exception
Implements com.neuronrobotics.sdk.dyio.IDyIOChannel.
Reimplemented in com.neuronrobotics.sdk.dyio.peripherals.CounterOutputChannel, and com.neuronrobotics.sdk.dyio.peripherals.CounterInputChannel.
Definition at line 163 of file DyIOAbstractPeripheral.java.
Referenced by com.neuronrobotics.sdk.dyio.peripherals.PWMOutputChannel.SetDutyPercent(), com.neuronrobotics.sdk.dyio.peripherals.DigitalOutputChannel.setHigh(), and com.neuronrobotics.sdk.dyio.peripherals.DCMotorOutputChannel.SetVelocity().
Member Data Documentation
channel
DyIOChannel com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral.channel private
The channel.
Definition at line 34 of file DyIOAbstractPeripheral.java.
Referenced by com.neuronrobotics.sdk.dyio.peripherals.AnalogInputChannel.AnalogInputChannel(), com.neuronrobotics.sdk.dyio.peripherals.CounterInputChannel.CounterInputChannel(), com.neuronrobotics.sdk.dyio.peripherals.CounterOutputChannel.CounterOutputChannel(), com.neuronrobotics.sdk.dyio.peripherals.DCMotorOutputChannel.DCMotorOutputChannel(), com.neuronrobotics.sdk.dyio.peripherals.DigitalInputChannel.DigitalInputChannel(), com.neuronrobotics.sdk.dyio.peripherals.DigitalOutputChannel.DigitalOutputChannel(), com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral.DyIOAbstractPeripheral(), com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral.getConfigurationFromDevice(), com.neuronrobotics.sdk.dyio.peripherals.CounterInputChannel.init(), com.neuronrobotics.sdk.dyio.peripherals.CounterOutputChannel.init(), com.neuronrobotics.sdk.dyio.peripherals.PPMReaderChannel.PPMReaderChannel(), com.neuronrobotics.sdk.dyio.peripherals.PWMOutputChannel.PWMOutputChannel(), and com.neuronrobotics.sdk.dyio.peripherals.ServoChannel.ServoChannel().
configuration
int com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral.configuration =0 private
The configuration.
Definition at line 40 of file DyIOAbstractPeripheral.java.
enabled
boolean com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral.enabled = false private
The enabled.
Definition at line 37 of file DyIOAbstractPeripheral.java.
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/dyio/peripherals/DyIOAbstractPeripheral.java