BowlerKernel: com.neuronrobotics.sdk.pid.PIDConfiguration Class Reference
com.neuronrobotics.sdk.pid.PIDConfiguration Class Reference
Public Member Functions
PIDConfiguration ()
PIDConfiguration (int channel)
PIDConfiguration (int group, boolean enabled, boolean inverted, boolean async, double KP, double KI, double KD, double latch, boolean useLatch, boolean stopOnLatch, double up, double low, double hStop)
PIDConfiguration (int group, boolean enabled, boolean inverted, boolean async, double KP, double KI, double KD, double latch, boolean useLatch, boolean stopOnLatch)
PIDConfiguration (BowlerDatagram conf)
PIDConfiguration (Object[] args)
String toString ()
void setGroup (int group)
int getGroup ()
void setEnabled (boolean enabled)
boolean isEnabled ()
void setInverted (boolean inverted)
boolean isInverted ()
void setAsync (boolean async)
boolean isAsync ()
void setKP (double kP)
double getKP ()
void setKI (double kI)
double getKI ()
void setKD (double kD)
double getKD ()
double getIndexLatch ()
void setIndexLatch (double latch)
void setUseLatch (boolean useLatch)
boolean isUseLatch ()
void setStopOnIndex (boolean stopOnIndex)
boolean isStopOnIndex ()
Object[] getArgs ()
double getUpperHystersys ()
void setUpperHystersys (double up)
double getLowerHystersys ()
void setLowerHystersys (double low)
double getHystersysStop ()
void setHystersysStop (double hStop)
Private Attributes
int group =0
boolean enabled =false
boolean inverted =false
boolean async =false
double KP =.1
double KI =0
double KD =0
int latch =0
boolean useLatch =false
boolean stopOnIndex =false
double up =0
double low =0
double hStop =0
Detailed Description
The Class PIDConfiguration.
Definition at line 10 of file PIDConfiguration.java.
Constructor & Destructor Documentation
PIDConfiguration() [1/6]
com.neuronrobotics.sdk.pid.PIDConfiguration.PIDConfiguration ()
Instantiates a new PID configuration.
Definition at line 54 of file PIDConfiguration.java.
PIDConfiguration() [2/6]
com.neuronrobotics.sdk.pid.PIDConfiguration.PIDConfiguration (int channel)
Instantiates a new PID configuration.
Parameters
channel the channel
Definition at line 63 of file PIDConfiguration.java.
References com.neuronrobotics.sdk.pid.PIDConfiguration.group.
PIDConfiguration() [3/6]
com.neuronrobotics.sdk.pid.PIDConfiguration.PIDConfiguration (int group, boolean enabled, boolean inverted, boolean async, double KP, double KI, double KD, double latch, boolean useLatch, boolean stopOnLatch, double up, double low, double hStop)
Instantiates a new PID configuration.
Parameters
group This is the PID group this configuration object represents
enabled True if the controller is running, false otherwise
inverted This inverts the output value. Set true if the controller diverges
async sets the flag to send this channels async values upstream
KP Proportional constant
KI Integral constant
KD Derivative constant
latch The value to latch into the PID controller if the home switch is hit (encoder only, not used in analog PID)
useLatch Use the value to latch into the PID controller if the home switch is hit (encoder only, not used in analog PID)
stopOnLatch Set the setpoint of the controller to current if home switch is hit (encoder only, not used in analog PID)
up the up
low the low
hStop the h stop
Definition at line 84 of file PIDConfiguration.java.
References com.neuronrobotics.sdk.pid.PIDConfiguration.async, com.neuronrobotics.sdk.pid.PIDConfiguration.enabled, com.neuronrobotics.sdk.pid.PIDConfiguration.group, com.neuronrobotics.sdk.pid.PIDConfiguration.hStop, com.neuronrobotics.sdk.pid.PIDConfiguration.inverted, com.neuronrobotics.sdk.pid.PIDConfiguration.KD, com.neuronrobotics.sdk.pid.PIDConfiguration.KI, com.neuronrobotics.sdk.pid.PIDConfiguration.KP, com.neuronrobotics.sdk.pid.PIDConfiguration.latch, com.neuronrobotics.sdk.pid.PIDConfiguration.low, com.neuronrobotics.sdk.pid.PIDConfiguration.setAsync(), com.neuronrobotics.sdk.pid.PIDConfiguration.setEnabled(), com.neuronrobotics.sdk.pid.PIDConfiguration.setGroup(), com.neuronrobotics.sdk.pid.PIDConfiguration.setHystersysStop(), com.neuronrobotics.sdk.pid.PIDConfiguration.setIndexLatch(), com.neuronrobotics.sdk.pid.PIDConfiguration.setInverted(), com.neuronrobotics.sdk.pid.PIDConfiguration.setKD(), com.neuronrobotics.sdk.pid.PIDConfiguration.setKI(), com.neuronrobotics.sdk.pid.PIDConfiguration.setKP(), com.neuronrobotics.sdk.pid.PIDConfiguration.setLowerHystersys(), com.neuronrobotics.sdk.pid.PIDConfiguration.setStopOnIndex(), com.neuronrobotics.sdk.pid.PIDConfiguration.setUpperHystersys(), com.neuronrobotics.sdk.pid.PIDConfiguration.setUseLatch(), com.neuronrobotics.sdk.pid.PIDConfiguration.up, and com.neuronrobotics.sdk.pid.PIDConfiguration.useLatch.
PIDConfiguration() [4/6]
com.neuronrobotics.sdk.pid.PIDConfiguration.PIDConfiguration (int group, boolean enabled, boolean inverted, boolean async, double KP, double KI, double KD, double latch, boolean useLatch, boolean stopOnLatch)
Instantiates a new PID configuration.
Parameters
group the group
enabled the enabled
inverted the inverted
async the async
KP the kp
KI the ki
KD the kd
latch the latch
useLatch the use latch
stopOnLatch the stop on latch
Definition at line 115 of file PIDConfiguration.java.
References com.neuronrobotics.sdk.pid.PIDConfiguration.async, com.neuronrobotics.sdk.pid.PIDConfiguration.enabled, com.neuronrobotics.sdk.pid.PIDConfiguration.group, com.neuronrobotics.sdk.pid.PIDConfiguration.inverted, com.neuronrobotics.sdk.pid.PIDConfiguration.KD, com.neuronrobotics.sdk.pid.PIDConfiguration.KI, com.neuronrobotics.sdk.pid.PIDConfiguration.KP, com.neuronrobotics.sdk.pid.PIDConfiguration.latch, and com.neuronrobotics.sdk.pid.PIDConfiguration.useLatch.
PIDConfiguration() [5/6]
com.neuronrobotics.sdk.pid.PIDConfiguration.PIDConfiguration (BowlerDatagram conf)
Used to parse a PID configuration out of a PID packet.
Parameters
conf the conf
Definition at line 131 of file PIDConfiguration.java.
References com.neuronrobotics.sdk.common.ByteList.convertToInt(), com.neuronrobotics.sdk.common.ByteList.get(), com.neuronrobotics.sdk.common.ByteList.getBytes(), com.neuronrobotics.sdk.common.BowlerDatagram.getData(), com.neuronrobotics.sdk.pid.PIDConfiguration.setAsync(), com.neuronrobotics.sdk.pid.PIDConfiguration.setEnabled(), com.neuronrobotics.sdk.pid.PIDConfiguration.setGroup(), com.neuronrobotics.sdk.pid.PIDConfiguration.setHystersysStop(), com.neuronrobotics.sdk.pid.PIDConfiguration.setIndexLatch(), com.neuronrobotics.sdk.pid.PIDConfiguration.setInverted(), com.neuronrobotics.sdk.pid.PIDConfiguration.setKD(), com.neuronrobotics.sdk.pid.PIDConfiguration.setKI(), com.neuronrobotics.sdk.pid.PIDConfiguration.setKP(), com.neuronrobotics.sdk.pid.PIDConfiguration.setLowerHystersys(), com.neuronrobotics.sdk.pid.PIDConfiguration.setStopOnIndex(), com.neuronrobotics.sdk.pid.PIDConfiguration.setUpperHystersys(), and com.neuronrobotics.sdk.pid.PIDConfiguration.setUseLatch().
PIDConfiguration() [6/6]
com.neuronrobotics.sdk.pid.PIDConfiguration.PIDConfiguration (Object[] args)
Used to parse a PID configuration out of a PID packet.
Parameters
args the args
Definition at line 160 of file PIDConfiguration.java.
References com.neuronrobotics.sdk.pid.PIDConfiguration.setAsync(), com.neuronrobotics.sdk.pid.PIDConfiguration.setEnabled(), com.neuronrobotics.sdk.pid.PIDConfiguration.setGroup(), com.neuronrobotics.sdk.pid.PIDConfiguration.setHystersysStop(), com.neuronrobotics.sdk.pid.PIDConfiguration.setIndexLatch(), com.neuronrobotics.sdk.pid.PIDConfiguration.setInverted(), com.neuronrobotics.sdk.pid.PIDConfiguration.setKD(), com.neuronrobotics.sdk.pid.PIDConfiguration.setKI(), com.neuronrobotics.sdk.pid.PIDConfiguration.setKP(), com.neuronrobotics.sdk.pid.PIDConfiguration.setLowerHystersys(), com.neuronrobotics.sdk.pid.PIDConfiguration.setStopOnIndex(), com.neuronrobotics.sdk.pid.PIDConfiguration.setUpperHystersys(), and com.neuronrobotics.sdk.pid.PIDConfiguration.setUseLatch().
Member Function Documentation
getArgs()
Object [] com.neuronrobotics.sdk.pid.PIDConfiguration.getArgs ()
Gets the args.
Returns
the args
Definition at line 382 of file PIDConfiguration.java.
References com.neuronrobotics.sdk.pid.PIDConfiguration.async, com.neuronrobotics.sdk.pid.PIDConfiguration.enabled, com.neuronrobotics.sdk.pid.PIDConfiguration.group, com.neuronrobotics.sdk.pid.PIDConfiguration.hStop, com.neuronrobotics.sdk.pid.PIDConfiguration.inverted, com.neuronrobotics.sdk.pid.PIDConfiguration.KD, com.neuronrobotics.sdk.pid.PIDConfiguration.KI, com.neuronrobotics.sdk.pid.PIDConfiguration.KP, com.neuronrobotics.sdk.pid.PIDConfiguration.latch, com.neuronrobotics.sdk.pid.PIDConfiguration.low, com.neuronrobotics.sdk.pid.PIDConfiguration.stopOnIndex, com.neuronrobotics.sdk.pid.PIDConfiguration.up, and com.neuronrobotics.sdk.pid.PIDConfiguration.useLatch.
Referenced by com.neuronrobotics.sdk.namespace.bcs.pid.PidNamespaceImp.ConfigurePIDController(), and com.neuronrobotics.sdk.namespace.bcs.pid.PidDeviceServerNamespace.PidDeviceServerNamespace().
getGroup()
int com.neuronrobotics.sdk.pid.PIDConfiguration.getGroup ()
Gets the group.
Returns
the group
Definition at line 211 of file PIDConfiguration.java.
References com.neuronrobotics.sdk.pid.PIDConfiguration.group.
Referenced by com.neuronrobotics.sdk.commands.bcs.pid.ConfigurePIDCommand.ConfigurePIDCommand(), com.neuronrobotics.sdk.pid.VirtualGenericPIDDevice.ConfigurePIDController(), com.neuronrobotics.sdk.pid.VirtualGenericPIDDevice.SyncThread.run(), and com.neuronrobotics.sdk.pid.PIDConfiguration.toString().
getHystersysStop()
double com.neuronrobotics.sdk.pid.PIDConfiguration.getHystersysStop ()
Gets the hystersys stop.
Returns
the hystersys stop
Definition at line 442 of file PIDConfiguration.java.
References com.neuronrobotics.sdk.pid.PIDConfiguration.hStop.
Referenced by com.neuronrobotics.sdk.pid.PIDConfiguration.toString().
getIndexLatch()
double com.neuronrobotics.sdk.pid.PIDConfiguration.getIndexLatch ()
Gets the index latch.
Returns
the index latch
Definition at line 328 of file PIDConfiguration.java.
References com.neuronrobotics.sdk.pid.PIDConfiguration.latch.
Referenced by com.neuronrobotics.sdk.commands.bcs.pid.ConfigurePIDCommand.ConfigurePIDCommand(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setPidConfiguration(), and com.neuronrobotics.sdk.pid.PIDConfiguration.toString().
getKD()
double com.neuronrobotics.sdk.pid.PIDConfiguration.getKD ()
Gets the kd.
Returns
the kd
Definition at line 319 of file PIDConfiguration.java.
References com.neuronrobotics.sdk.pid.PIDConfiguration.KD.
Referenced by com.neuronrobotics.sdk.commands.bcs.pid.ConfigurePIDCommand.ConfigurePIDCommand(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setPidConfiguration(), and com.neuronrobotics.sdk.pid.PIDConfiguration.toString().
getKI()
double com.neuronrobotics.sdk.pid.PIDConfiguration.getKI ()
Gets the ki.
Returns
the ki
Definition at line 301 of file PIDConfiguration.java.
References com.neuronrobotics.sdk.pid.PIDConfiguration.KI.
Referenced by com.neuronrobotics.sdk.commands.bcs.pid.ConfigurePIDCommand.ConfigurePIDCommand(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setPidConfiguration(), and com.neuronrobotics.sdk.pid.PIDConfiguration.toString().
getKP()
double com.neuronrobotics.sdk.pid.PIDConfiguration.getKP ()
Gets the kp.
Returns
the kp
Definition at line 283 of file PIDConfiguration.java.
References com.neuronrobotics.sdk.pid.PIDConfiguration.KP.
Referenced by com.neuronrobotics.sdk.commands.bcs.pid.ConfigurePIDCommand.ConfigurePIDCommand(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setPidConfiguration(), and com.neuronrobotics.sdk.pid.PIDConfiguration.toString().
getLowerHystersys()
double com.neuronrobotics.sdk.pid.PIDConfiguration.getLowerHystersys ()
Gets the lower hystersys.
Returns
the lower hystersys
Definition at line 424 of file PIDConfiguration.java.
References com.neuronrobotics.sdk.pid.PIDConfiguration.low.
Referenced by com.neuronrobotics.sdk.pid.PIDConfiguration.toString().
getUpperHystersys()
double com.neuronrobotics.sdk.pid.PIDConfiguration.getUpperHystersys ()
Gets the upper hystersys.
Returns
the upper hystersys
Definition at line 406 of file PIDConfiguration.java.
References com.neuronrobotics.sdk.pid.PIDConfiguration.up.
Referenced by com.neuronrobotics.sdk.pid.PIDConfiguration.toString().
isAsync()
boolean com.neuronrobotics.sdk.pid.PIDConfiguration.isAsync ()
Checks if is async.
Returns
true, if is async
Definition at line 265 of file PIDConfiguration.java.
References com.neuronrobotics.sdk.pid.PIDConfiguration.async.
Referenced by com.neuronrobotics.sdk.commands.bcs.pid.ConfigurePIDCommand.ConfigurePIDCommand(), and com.neuronrobotics.sdk.pid.PIDConfiguration.toString().
isEnabled()
boolean com.neuronrobotics.sdk.pid.PIDConfiguration.isEnabled ()
Checks if is enabled.
Returns
true, if is enabled
Definition at line 229 of file PIDConfiguration.java.
References com.neuronrobotics.sdk.pid.PIDConfiguration.enabled.
Referenced by com.neuronrobotics.sdk.commands.bcs.pid.ConfigurePIDCommand.ConfigurePIDCommand(), and com.neuronrobotics.sdk.pid.PIDConfiguration.toString().
isInverted()
boolean com.neuronrobotics.sdk.pid.PIDConfiguration.isInverted ()
Checks if is inverted.
Returns
true, if is inverted
Definition at line 247 of file PIDConfiguration.java.
References com.neuronrobotics.sdk.pid.PIDConfiguration.inverted.
Referenced by com.neuronrobotics.sdk.commands.bcs.pid.ConfigurePIDCommand.ConfigurePIDCommand(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setPidConfiguration(), and com.neuronrobotics.sdk.pid.PIDConfiguration.toString().
isStopOnIndex()
boolean com.neuronrobotics.sdk.pid.PIDConfiguration.isStopOnIndex ()
Checks if is stop on index.
Returns
true, if is stop on index
Definition at line 373 of file PIDConfiguration.java.
References com.neuronrobotics.sdk.pid.PIDConfiguration.stopOnIndex.
Referenced by com.neuronrobotics.sdk.commands.bcs.pid.ConfigurePIDCommand.ConfigurePIDCommand(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setPidConfiguration(), and com.neuronrobotics.sdk.pid.PIDConfiguration.toString().
isUseLatch()
boolean com.neuronrobotics.sdk.pid.PIDConfiguration.isUseLatch ()
Checks if is use latch.
Returns
true, if is use latch
Definition at line 355 of file PIDConfiguration.java.
References com.neuronrobotics.sdk.pid.PIDConfiguration.useLatch.
Referenced by com.neuronrobotics.sdk.commands.bcs.pid.ConfigurePIDCommand.ConfigurePIDCommand(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setPidConfiguration(), and com.neuronrobotics.sdk.pid.PIDConfiguration.toString().
setAsync()
void com.neuronrobotics.sdk.pid.PIDConfiguration.setAsync (boolean async)
Sets the async.
Parameters
async the new async
Definition at line 256 of file PIDConfiguration.java.
References com.neuronrobotics.sdk.pid.PIDConfiguration.async.
Referenced by com.neuronrobotics.sdk.pid.PIDConfiguration.PIDConfiguration(), and com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.setDevice().
setEnabled()
void com.neuronrobotics.sdk.pid.PIDConfiguration.setEnabled (boolean enabled)
Sets the enabled.
Parameters
enabled the new enabled
Definition at line 220 of file PIDConfiguration.java.
References com.neuronrobotics.sdk.pid.PIDConfiguration.enabled.
Referenced by com.neuronrobotics.sdk.pid.VirtualGenericPIDDevice.GetAllPIDPosition(), com.neuronrobotics.sdk.pid.PIDConfiguration.PIDConfiguration(), and com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.setDevice().
setGroup()
void com.neuronrobotics.sdk.pid.PIDConfiguration.setGroup (int group)
Sets the group.
Parameters
group the new group
Definition at line 202 of file PIDConfiguration.java.
References com.neuronrobotics.sdk.pid.PIDConfiguration.group.
Referenced by com.neuronrobotics.sdk.pid.PIDChannel.ConfigurePIDController(), com.neuronrobotics.sdk.pid.VirtualGenericPIDDevice.GetAllPIDPosition(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getPidConfiguration(), com.neuronrobotics.sdk.pid.PIDConfiguration.PIDConfiguration(), and com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.setDevice().
setHystersysStop()
void com.neuronrobotics.sdk.pid.PIDConfiguration.setHystersysStop (double hStop)
Sets the hystersys stop.
Parameters
hStop the new hystersys stop
Definition at line 451 of file PIDConfiguration.java.
References com.neuronrobotics.sdk.pid.PIDConfiguration.hStop.
Referenced by com.neuronrobotics.sdk.pid.PIDConfiguration.PIDConfiguration().
setIndexLatch()
void com.neuronrobotics.sdk.pid.PIDConfiguration.setIndexLatch (double latch)
Sets the index latch.
Parameters
latch the new index latch
Definition at line 337 of file PIDConfiguration.java.
References com.neuronrobotics.sdk.pid.PIDConfiguration.latch.
Referenced by com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getPidConfiguration(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.homeLink(), com.neuronrobotics.sdk.pid.PIDConfiguration.PIDConfiguration(), and com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.setDevice().
setInverted()
void com.neuronrobotics.sdk.pid.PIDConfiguration.setInverted (boolean inverted)
Sets the inverted.
Parameters
inverted the new inverted
Definition at line 238 of file PIDConfiguration.java.
References com.neuronrobotics.sdk.pid.PIDConfiguration.inverted.
Referenced by com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getPidConfiguration(), com.neuronrobotics.sdk.pid.PIDConfiguration.PIDConfiguration(), and com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.setDevice().
setKD()
void com.neuronrobotics.sdk.pid.PIDConfiguration.setKD (double kD)
Sets the kd.
Parameters
kD the new kd
Definition at line 310 of file PIDConfiguration.java.
References com.neuronrobotics.sdk.pid.PIDConfiguration.KD.
Referenced by com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getPidConfiguration(), com.neuronrobotics.sdk.pid.PIDConfiguration.PIDConfiguration(), and com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.setDevice().
setKI()
void com.neuronrobotics.sdk.pid.PIDConfiguration.setKI (double kI)
Sets the ki.
Parameters
kI the new ki
Definition at line 292 of file PIDConfiguration.java.
References com.neuronrobotics.sdk.pid.PIDConfiguration.KI.
Referenced by com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getPidConfiguration(), com.neuronrobotics.sdk.pid.PIDConfiguration.PIDConfiguration(), and com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.setDevice().
setKP()
void com.neuronrobotics.sdk.pid.PIDConfiguration.setKP (double kP)
Sets the kp.
Parameters
kP the new kp
Definition at line 274 of file PIDConfiguration.java.
References com.neuronrobotics.sdk.pid.PIDConfiguration.KP.
Referenced by com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getPidConfiguration(), com.neuronrobotics.sdk.pid.PIDConfiguration.PIDConfiguration(), and com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.setDevice().
setLowerHystersys()
void com.neuronrobotics.sdk.pid.PIDConfiguration.setLowerHystersys (double low)
Sets the lower hystersys.
Parameters
low the new lower hystersys
Definition at line 433 of file PIDConfiguration.java.
References com.neuronrobotics.sdk.pid.PIDConfiguration.low.
Referenced by com.neuronrobotics.sdk.pid.PIDConfiguration.PIDConfiguration().
setStopOnIndex()
void com.neuronrobotics.sdk.pid.PIDConfiguration.setStopOnIndex (boolean stopOnIndex)
Sets the stop on index.
Parameters
stopOnIndex the new stop on index
Definition at line 364 of file PIDConfiguration.java.
References com.neuronrobotics.sdk.pid.PIDConfiguration.stopOnIndex.
Referenced by com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.getPidConfiguration(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.homeLink(), com.neuronrobotics.sdk.pid.PIDConfiguration.PIDConfiguration(), and com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.setDevice().
setUpperHystersys()
void com.neuronrobotics.sdk.pid.PIDConfiguration.setUpperHystersys (double up)
Sets the upper hystersys.
Parameters
up the new upper hystersys
Definition at line 415 of file PIDConfiguration.java.
References com.neuronrobotics.sdk.pid.PIDConfiguration.up.
Referenced by com.neuronrobotics.sdk.pid.PIDConfiguration.PIDConfiguration().
setUseLatch()
void com.neuronrobotics.sdk.pid.PIDConfiguration.setUseLatch (boolean useLatch)
Sets the use latch.
Parameters
useLatch the new use latch
Definition at line 346 of file PIDConfiguration.java.
References com.neuronrobotics.sdk.pid.PIDConfiguration.useLatch.
Referenced by com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.homeLink(), com.neuronrobotics.sdk.pid.PIDConfiguration.PIDConfiguration(), and com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.setDevice().
toString()
String com.neuronrobotics.sdk.pid.PIDConfiguration.toString ()
Definition at line 182 of file PIDConfiguration.java.
References com.neuronrobotics.sdk.pid.PIDConfiguration.getGroup(), com.neuronrobotics.sdk.pid.PIDConfiguration.getHystersysStop(), com.neuronrobotics.sdk.pid.PIDConfiguration.getIndexLatch(), com.neuronrobotics.sdk.pid.PIDConfiguration.getKD(), com.neuronrobotics.sdk.pid.PIDConfiguration.getKI(), com.neuronrobotics.sdk.pid.PIDConfiguration.getKP(), com.neuronrobotics.sdk.pid.PIDConfiguration.getLowerHystersys(), com.neuronrobotics.sdk.pid.PIDConfiguration.getUpperHystersys(), com.neuronrobotics.sdk.pid.PIDConfiguration.isAsync(), com.neuronrobotics.sdk.pid.PIDConfiguration.isEnabled(), com.neuronrobotics.sdk.pid.PIDConfiguration.isInverted(), com.neuronrobotics.sdk.pid.PIDConfiguration.isStopOnIndex(), and com.neuronrobotics.sdk.pid.PIDConfiguration.isUseLatch().
Member Data Documentation
async
boolean com.neuronrobotics.sdk.pid.PIDConfiguration.async =false private
The async.
Definition at line 22 of file PIDConfiguration.java.
Referenced by com.neuronrobotics.sdk.pid.PIDConfiguration.getArgs(), com.neuronrobotics.sdk.pid.PIDConfiguration.isAsync(), com.neuronrobotics.sdk.pid.PIDConfiguration.PIDConfiguration(), and com.neuronrobotics.sdk.pid.PIDConfiguration.setAsync().
enabled
boolean com.neuronrobotics.sdk.pid.PIDConfiguration.enabled =false private
The enabled.
Definition at line 16 of file PIDConfiguration.java.
Referenced by com.neuronrobotics.sdk.pid.PIDConfiguration.getArgs(), com.neuronrobotics.sdk.pid.PIDConfiguration.isEnabled(), com.neuronrobotics.sdk.pid.PIDConfiguration.PIDConfiguration(), and com.neuronrobotics.sdk.pid.PIDConfiguration.setEnabled().
group
int com.neuronrobotics.sdk.pid.PIDConfiguration.group =0 private
The group.
Definition at line 13 of file PIDConfiguration.java.
Referenced by com.neuronrobotics.sdk.pid.PIDConfiguration.getArgs(), com.neuronrobotics.sdk.pid.PIDConfiguration.getGroup(), com.neuronrobotics.sdk.pid.PIDConfiguration.PIDConfiguration(), and com.neuronrobotics.sdk.pid.PIDConfiguration.setGroup().
hStop
double com.neuronrobotics.sdk.pid.PIDConfiguration.hStop =0 private
The h stop.
Definition at line 49 of file PIDConfiguration.java.
Referenced by com.neuronrobotics.sdk.pid.PIDConfiguration.getArgs(), com.neuronrobotics.sdk.pid.PIDConfiguration.getHystersysStop(), com.neuronrobotics.sdk.pid.PIDConfiguration.PIDConfiguration(), and com.neuronrobotics.sdk.pid.PIDConfiguration.setHystersysStop().
inverted
boolean com.neuronrobotics.sdk.pid.PIDConfiguration.inverted =false private
The inverted.
Definition at line 19 of file PIDConfiguration.java.
Referenced by com.neuronrobotics.sdk.pid.PIDConfiguration.getArgs(), com.neuronrobotics.sdk.pid.PIDConfiguration.isInverted(), com.neuronrobotics.sdk.pid.PIDConfiguration.PIDConfiguration(), and com.neuronrobotics.sdk.pid.PIDConfiguration.setInverted().
KD
double com.neuronrobotics.sdk.pid.PIDConfiguration.KD =0 private
The kd.
Definition at line 31 of file PIDConfiguration.java.
Referenced by com.neuronrobotics.sdk.pid.PIDConfiguration.getArgs(), com.neuronrobotics.sdk.pid.PIDConfiguration.getKD(), com.neuronrobotics.sdk.pid.PIDConfiguration.PIDConfiguration(), and com.neuronrobotics.sdk.pid.PIDConfiguration.setKD().
KI
double com.neuronrobotics.sdk.pid.PIDConfiguration.KI =0 private
The ki.
Definition at line 28 of file PIDConfiguration.java.
Referenced by com.neuronrobotics.sdk.pid.PIDConfiguration.getArgs(), com.neuronrobotics.sdk.pid.PIDConfiguration.getKI(), com.neuronrobotics.sdk.pid.PIDConfiguration.PIDConfiguration(), and com.neuronrobotics.sdk.pid.PIDConfiguration.setKI().
KP
double com.neuronrobotics.sdk.pid.PIDConfiguration.KP =.1 private
The kp.
Definition at line 25 of file PIDConfiguration.java.
Referenced by com.neuronrobotics.sdk.pid.PIDConfiguration.getArgs(), com.neuronrobotics.sdk.pid.PIDConfiguration.getKP(), com.neuronrobotics.sdk.pid.PIDConfiguration.PIDConfiguration(), and com.neuronrobotics.sdk.pid.PIDConfiguration.setKP().
latch
int com.neuronrobotics.sdk.pid.PIDConfiguration.latch =0 private
The latch.
Definition at line 34 of file PIDConfiguration.java.
Referenced by com.neuronrobotics.sdk.pid.PIDConfiguration.getArgs(), com.neuronrobotics.sdk.pid.PIDConfiguration.getIndexLatch(), com.neuronrobotics.sdk.pid.PIDConfiguration.PIDConfiguration(), and com.neuronrobotics.sdk.pid.PIDConfiguration.setIndexLatch().
low
double com.neuronrobotics.sdk.pid.PIDConfiguration.low =0 private
The low.
Definition at line 46 of file PIDConfiguration.java.
Referenced by com.neuronrobotics.sdk.pid.PIDConfiguration.getArgs(), com.neuronrobotics.sdk.pid.PIDConfiguration.getLowerHystersys(), com.neuronrobotics.sdk.pid.PIDConfiguration.PIDConfiguration(), and com.neuronrobotics.sdk.pid.PIDConfiguration.setLowerHystersys().
stopOnIndex
boolean com.neuronrobotics.sdk.pid.PIDConfiguration.stopOnIndex =false private
The stop on index.
Definition at line 40 of file PIDConfiguration.java.
Referenced by com.neuronrobotics.sdk.pid.PIDConfiguration.getArgs(), com.neuronrobotics.sdk.pid.PIDConfiguration.isStopOnIndex(), and com.neuronrobotics.sdk.pid.PIDConfiguration.setStopOnIndex().
up
double com.neuronrobotics.sdk.pid.PIDConfiguration.up =0 private
The up.
Definition at line 43 of file PIDConfiguration.java.
Referenced by com.neuronrobotics.sdk.pid.PIDConfiguration.getArgs(), com.neuronrobotics.sdk.pid.PIDConfiguration.getUpperHystersys(), com.neuronrobotics.sdk.pid.PIDConfiguration.PIDConfiguration(), and com.neuronrobotics.sdk.pid.PIDConfiguration.setUpperHystersys().
useLatch
boolean com.neuronrobotics.sdk.pid.PIDConfiguration.useLatch =false private
The use latch.
Definition at line 37 of file PIDConfiguration.java.
Referenced by com.neuronrobotics.sdk.pid.PIDConfiguration.getArgs(), com.neuronrobotics.sdk.pid.PIDConfiguration.isUseLatch(), com.neuronrobotics.sdk.pid.PIDConfiguration.PIDConfiguration(), and com.neuronrobotics.sdk.pid.PIDConfiguration.setUseLatch().
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/pid/PIDConfiguration.java