BowlerKernel: eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter Class Reference
eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter Class Reference
Public Member Functions
Set< String > getMeshes ()
ObjImporter (String objFileUrl) throws FileNotFoundException, IOException
ObjImporter (InputStream inputStream) throws IOException
ObjImporter (ObjFile obj) throws IOException
TriangleMesh getMesh ()
Collection< TriangleMesh > getMeshCollection ()
Collection< Material > getMaterialCollection ()
Material getMaterial ()
TriangleMesh getMesh (String key)
Material getMaterial (String key)
MeshView buildMeshView (String key)
Static Public Member Functions
static void setDebug (boolean debug)
static void setScale (float scale)
static void setFlatXZ (boolean flatXZ)
Private Member Functions
int vertexIndex (int vertexIndex)
int uvIndex (int uvIndex)
int normalIndex (int normalIndex)
void read (InputStream objInputStream) throws IOException
void read (InputStream objInputStream, InputStream mtlInputStream) throws IOException
void addMesh (String key)
Private Attributes
final Map< String, TriangleMesh > meshes = new HashMap<>()
final Map< String, Material > materials = new HashMap<>()
final List< Map< String, Material > > materialLibrary = new ArrayList<>()
String objFileUrl
FloatArrayList vertexes = new FloatArrayList()
FloatArrayList uvs = new FloatArrayList()
IntegerArrayList faces = new IntegerArrayList()
IntegerArrayList smoothingGroups = new IntegerArrayList()
FloatArrayList normals = new FloatArrayList()
IntegerArrayList faceNormals = new IntegerArrayList()
Material material = new PhongMaterial(Color.WHITE)
int facesStart = 0
int facesNormalStart = 0
int smoothingGroupsStart = 0
Static Private Attributes
static boolean debug = false
static float scale = 1
static boolean flatXZ = false
Detailed Description
Obj file reader.
Definition at line 62 of file ObjImporter.java.
Constructor & Destructor Documentation
ObjImporter() [1/3]
eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.ObjImporter (String objFileUrl) throws FileNotFoundException, IOException
Instantiates a new obj importer.
Parameters
objFileUrl the obj file url
Exceptions
FileNotFoundException the file not found exception
IOException Signals that an I/O exception has occurred.
Definition at line 154 of file ObjImporter.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.objFileUrl, and eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.read().
ObjImporter() [2/3]
eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.ObjImporter (InputStream inputStream) throws IOException
Instantiates a new obj importer.
Parameters
inputStream the input stream
Exceptions
IOException Signals that an I/O exception has occurred.
Definition at line 166 of file ObjImporter.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.read().
ObjImporter() [3/3]
eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.ObjImporter (ObjFile obj) throws IOException
Instantiates a new obj importer.
Parameters
obj the obj
Exceptions
IOException Signals that an I/O exception has occurred.
Definition at line 176 of file ObjImporter.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.read().
Member Function Documentation
addMesh()
void eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.addMesh (String key) private
Adds the mesh.
Parameters
key the key
Definition at line 489 of file ObjImporter.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.add(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.SmoothingGroups.calcSmoothGroups(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.faceNormals, eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.faces, eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.facesNormalStart, eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.facesStart, eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.get(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.get(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.material, eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.materials, eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.meshes, eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.normals, eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.set(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.size, eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.size, eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.smoothingGroups, eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.smoothingGroupsStart, eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.subList(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.toFloatArray(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.uvs, and eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.vertexes.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.read().
buildMeshView()
MeshView eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.buildMeshView (String key)
Builds the mesh view.
Parameters
key the key
Returns
the mesh view
Definition at line 242 of file ObjImporter.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.materials, and eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.meshes.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjOrPolyObjImporter.load().
getMaterial() [1/2]
Material eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.getMaterial ()
Gets the material.
Returns
the material
Definition at line 212 of file ObjImporter.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.materials.
getMaterial() [2/2]
Material eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.getMaterial (String key)
Gets the material.
Parameters
key the key
Returns
the material
Definition at line 232 of file ObjImporter.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.materials.
getMaterialCollection()
Collection<Material> eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.getMaterialCollection ()
Gets the material collection.
Returns
the material collection
Definition at line 203 of file ObjImporter.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.materials.
getMesh() [1/2]
TriangleMesh eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.getMesh ()
Gets the mesh.
Returns
the mesh
Definition at line 185 of file ObjImporter.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.meshes.
getMesh() [2/2]
TriangleMesh eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.getMesh (String key)
Gets the mesh.
Parameters
key the key
Returns
the mesh
Definition at line 222 of file ObjImporter.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.meshes.
getMeshCollection()
Collection<TriangleMesh> eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.getMeshCollection ()
Gets the mesh collection.
Returns
the mesh collection
Definition at line 194 of file ObjImporter.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.meshes.
getMeshes()
Set<String> eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.getMeshes ()
Gets the meshes.
Returns
the meshes
Definition at line 131 of file ObjImporter.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.meshes.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjOrPolyObjImporter.load().
normalIndex()
int eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.normalIndex (int normalIndex) private
Normal index.
Parameters
normalIndex the normal index
Returns
the int
Definition at line 98 of file ObjImporter.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.normals, and eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.size.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.read().
read() [1/2]
void eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.read (InputStream objInputStream) throws IOException private
Read.
Parameters
objInputStream the obj input stream
Exceptions
IOException Signals that an I/O exception has occurred.
Definition at line 305 of file ObjImporter.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.ObjImporter().
read() [2/2]
void eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.read (InputStream objInputStream, InputStream mtlInputStream) throws IOException private
Read.
Parameters
objInputStream the obj input stream
mtlInputStream the mtl input stream
Exceptions
IOException Signals that an I/O exception has occurred.
Definition at line 316 of file ObjImporter.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.add(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.add(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.addMesh(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.faceNormals, eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.faces, eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.flatXZ, eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.MtlReader.getMaterials(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.material, eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.materialLibrary, eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.normalIndex(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.normals, eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.objFileUrl, eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.scale, eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.size, eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.IntegerArrayList.size, eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.smoothingGroups, eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.uvIndex(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.uvs, eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.vertexes, and eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.vertexIndex().
setDebug()
static void eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.setDebug (boolean debug) static
Sets the debug.
Parameters
debug the new debug
Definition at line 256 of file ObjImporter.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.debug.
setFlatXZ()
static void eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.setFlatXZ (boolean flatXZ) static
Sets the flat xz.
Parameters
flatXZ the new flat xz
Definition at line 592 of file ObjImporter.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.flatXZ.
setScale()
static void eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.setScale (float scale) static
Sets the scale.
Parameters
scale the new scale
Definition at line 265 of file ObjImporter.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.scale.
uvIndex()
int eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.uvIndex (int uvIndex) private
Uv index.
Parameters
uvIndex the uv index
Returns
the int
Definition at line 84 of file ObjImporter.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.size, and eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.uvs.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.read().
vertexIndex()
int eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.vertexIndex (int vertexIndex) private
Vertex index.
Parameters
vertexIndex the vertex index
Returns
the int
Definition at line 70 of file ObjImporter.java.
References eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.FloatArrayList.size, and eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.vertexes.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.read().
Member Data Documentation
debug
boolean eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.debug = false static private
The debug.
Definition at line 107 of file ObjImporter.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.setDebug().
faceNormals
IntegerArrayList eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.faceNormals = new IntegerArrayList() private
The face normals.
Definition at line 285 of file ObjImporter.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.addMesh(), and eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.read().
faces
IntegerArrayList eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.faces = new IntegerArrayList() private
The faces.
Definition at line 276 of file ObjImporter.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.addMesh(), and eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.read().
facesNormalStart
int eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.facesNormalStart = 0 private
The faces normal start.
Definition at line 294 of file ObjImporter.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.addMesh().
facesStart
int eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.facesStart = 0 private
The faces start.
Definition at line 291 of file ObjImporter.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.addMesh().
flatXZ
boolean eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.flatXZ = false static private
The flat xz.
Definition at line 113 of file ObjImporter.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.read(), and eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.setFlatXZ().
material
Material eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.material = new PhongMaterial(Color.WHITE) private
The material.
Definition at line 288 of file ObjImporter.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.addMesh(), and eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.read().
materialLibrary
final List<Map<String, Material> > eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.materialLibrary = new ArrayList<>() private
The material library.
Definition at line 142 of file ObjImporter.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.read().
materials
final Map<String, Material> eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.materials = new HashMap<>() private
The materials.
Definition at line 139 of file ObjImporter.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.addMesh(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.buildMeshView(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.getMaterial(), and eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.getMaterialCollection().
meshes
final Map<String, TriangleMesh> eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.meshes = new HashMap<>() private
The meshes.
Definition at line 136 of file ObjImporter.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.addMesh(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.buildMeshView(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.getMesh(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.getMeshCollection(), and eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.getMeshes().
normals
FloatArrayList eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.normals = new FloatArrayList() private
The normals.
Definition at line 282 of file ObjImporter.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.addMesh(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.normalIndex(), and eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.read().
objFileUrl
String eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.objFileUrl private
The obj file url.
Definition at line 145 of file ObjImporter.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.ObjImporter(), and eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.read().
scale
float eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.scale = 1 static private
The scale.
Definition at line 110 of file ObjImporter.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.read(), and eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.setScale().
smoothingGroups
IntegerArrayList eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.smoothingGroups = new IntegerArrayList() private
The smoothing groups.
Definition at line 279 of file ObjImporter.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.addMesh(), and eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.read().
smoothingGroupsStart
int eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.smoothingGroupsStart = 0 private
The smoothing groups start.
Definition at line 297 of file ObjImporter.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.addMesh().
uvs
FloatArrayList eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.uvs = new FloatArrayList() private
The uvs.
Definition at line 273 of file ObjImporter.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.addMesh(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.read(), and eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.uvIndex().
vertexes
FloatArrayList eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.vertexes = new FloatArrayList() private
The vertexes.
Definition at line 270 of file ObjImporter.java.
Referenced by eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.addMesh(), eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.read(), and eu.mihosoft.vrl.v3d.ext.openjfx.importers.obj.ObjImporter.vertexIndex().
The documentation for this class was generated from the following file:
JCSG/src/main/java/eu/mihosoft/vrl/v3d/ext/openjfx/importers/obj/ObjImporter.java