BowlerKernel: com.neuronrobotics.bowlerstudio.vitamins.Vitamins Class Reference
com.neuronrobotics.bowlerstudio.vitamins.Vitamins Class Reference
Static Public Member Functions
static void clear ()
static CSG get (File resource)
static CSG get (String type, String id, String purchasingVariant) throws Exception
static CSG get (String type, String id) throws Exception
static File getScriptFile (String type)
static Map< String, Object > getMeta (String type)
static void setScript (String type, String git, String file) throws Exception
static Map< String, Object > getConfiguration (String type, String id)
static void putMeasurment (String type, String size, String measurementName, Object measurmentValue)
static Object getMeasurement (String type, String size, String measurementName)
static HashMap< String, Object > getConfigurationRW (String type, String id)
static String makeJson (String type)
static void saveDatabase (String type) throws Exception
static void saveDatabaseForkIfMissing (String type) throws Exception
static void newVitamin (String type, String id) throws Exception
static void setParameter (String type, String id, String parameterName, Object parameter) throws Exception
static HashMap< String, HashMap< String, Object > > getDatabase (String type)
static File getVitaminFile (String type, Runnable onChange, boolean oneShot) throws InvalidRemoteException, TransportException, GitAPIException, IOException
static ArrayList< String > listVitaminActuators ()
static ArrayList< String > listVitaminShafts ()
static boolean isShaft (String vitaminsType)
static boolean isActuator (String vitaminsType)
static void setIsShaft (String type)
static void setIsActuator (String type)
static ArrayList< String > listVitaminTypes ()
static ArrayList< String > listVitaminSizes (String type)
static String getGitRepoDatabase ()
static void reLoadDatabaseFromFiles ()
static void setGitRepoDatabase (String gitRpoDatabase)
static String getJsonRootDir ()
static void setJsonRootDir (String jsonRootDir) throws IOException
Static Private Member Functions
static CSG get (String type, String id, int depthGauge) throws Exception
static void processSelfPR (GHPullRequest request) throws IOException
static void sanatize (String parameterName, HashMap< String, Object > config)
static String getRootFolder ()
Static Private Attributes
static String jsonRootDir = "json/"
static final Map< String, CSG > fileLastLoaded = new HashMap<String, CSG>()
static final Map< String, HashMap< String, HashMap< String, Object > > > databaseSet = new HashMap<String, HashMap<String, HashMap<String, Object>>>()
static final String defaultgitRpoDatabase = "https://github.com/madhephaestus/Hardware-Dimensions.git"
static String gitRpoDatabase = defaultgitRpoDatabase
static Type TT_mapStringString
static Gson gson = new GsonBuilder().disableHtmlEscaping().setPrettyPrinting().create()
static boolean checked
static HashMap< String, Runnable > changeListeners = new HashMap<String, Runnable>()
Detailed Description
Definition at line 49 of file Vitamins.java.
Member Function Documentation
clear()
static void com.neuronrobotics.bowlerstudio.vitamins.Vitamins.clear () static
Definition at line 64 of file Vitamins.java.
References com.neuronrobotics.bowlerstudio.vitamins.Vitamins.databaseSet, and com.neuronrobotics.bowlerstudio.vitamins.Vitamins.fileLastLoaded.
Referenced by com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.clear(), and com.neuronrobotics.bowlerstudio.vitamins.Vitamins.get().
get() [1/4]
static CSG com.neuronrobotics.bowlerstudio.vitamins.Vitamins.get (File resource) static
Definition at line 77 of file Vitamins.java.
References eu.mihosoft.vrl.v3d.STL.file(), and com.neuronrobotics.bowlerstudio.vitamins.Vitamins.fileLastLoaded.
Referenced by com.neuronrobotics.bowlerstudio.vitamins.VitaminBomManager.get().
get() [2/4]
static CSG com.neuronrobotics.bowlerstudio.vitamins.Vitamins.get (String type, String id) throws Exception static
Definition at line 140 of file Vitamins.java.
get() [3/4]
static CSG com.neuronrobotics.bowlerstudio.vitamins.Vitamins.get (String type, String id, int depthGauge) throws Exception static private
Definition at line 144 of file Vitamins.java.
References com.neuronrobotics.bowlerstudio.vitamins.Vitamins.clear(), com.neuronrobotics.bowlerstudio.vitamins.Vitamins.defaultgitRpoDatabase, com.neuronrobotics.sdk.common.Log.error(), com.neuronrobotics.bowlerstudio.vitamins.Vitamins.getMeta(), com.neuronrobotics.bowlerstudio.vitamins.Vitamins.gitRpoDatabase, com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.gitScriptRun(), com.neuronrobotics.bowlerstudio.vitamins.Vitamins.listVitaminSizes(), com.neuronrobotics.bowlerstudio.vitamins.Vitamins.newVitamin(), and eu.mihosoft.vrl.v3d.parametrics.Parameter.setStrValue().
get() [4/4]
static CSG com.neuronrobotics.bowlerstudio.vitamins.Vitamins.get (String type, String id, String purchasingVariant) throws Exception static
Definition at line 112 of file Vitamins.java.
References com.neuronrobotics.bowlerstudio.vitamins.Vitamins.clear(), com.neuronrobotics.bowlerstudio.vitamins.Vitamins.defaultgitRpoDatabase, com.neuronrobotics.bowlerstudio.vitamins.Vitamins.fileLastLoaded, com.neuronrobotics.bowlerstudio.vitamins.Purchasing.get(), com.neuronrobotics.bowlerstudio.vitamins.PurchasingData.getVariantParameters(), com.neuronrobotics.bowlerstudio.vitamins.Vitamins.gitRpoDatabase, and eu.mihosoft.vrl.v3d.parametrics.Parameter.setMM().
getConfiguration()
static Map<String, Object> com.neuronrobotics.bowlerstudio.vitamins.Vitamins.getConfiguration (String type, String id) static
Definition at line 209 of file Vitamins.java.
References com.neuronrobotics.bowlerstudio.vitamins.Vitamins.getConfigurationRW().
Referenced by com.neuronrobotics.bowlerstudio.vitamins.VitaminBomManager.getConfiguration().
getConfigurationRW()
static HashMap<String, Object> com.neuronrobotics.bowlerstudio.vitamins.Vitamins.getConfigurationRW (String type, String id) static
Definition at line 218 of file Vitamins.java.
References com.neuronrobotics.bowlerstudio.IssueReportingExceptionHandler.except(), com.neuronrobotics.bowlerstudio.vitamins.Vitamins.getDatabase(), and com.neuronrobotics.bowlerstudio.vitamins.Vitamins.sanatize().
Referenced by com.neuronrobotics.bowlerstudio.vitamins.Vitamins.getConfiguration(), com.neuronrobotics.bowlerstudio.vitamins.Vitamins.getMeasurement(), com.neuronrobotics.bowlerstudio.vitamins.Vitamins.getMeta(), com.neuronrobotics.bowlerstudio.vitamins.Vitamins.newVitamin(), com.neuronrobotics.bowlerstudio.vitamins.Vitamins.putMeasurment(), and com.neuronrobotics.bowlerstudio.vitamins.Vitamins.setParameter().
getDatabase()
static HashMap<String, HashMap<String, Object> > com.neuronrobotics.bowlerstudio.vitamins.Vitamins.getDatabase (String type) static
Definition at line 402 of file Vitamins.java.
References com.neuronrobotics.bowlerstudio.vitamins.Vitamins.changeListeners, com.neuronrobotics.bowlerstudio.vitamins.Vitamins.databaseSet, com.neuronrobotics.bowlerstudio.vitamins.Vitamins.getVitaminFile(), com.neuronrobotics.bowlerstudio.vitamins.Vitamins.gson, and com.neuronrobotics.bowlerstudio.vitamins.Vitamins.TT_mapStringString.
Referenced by com.neuronrobotics.bowlerstudio.vitamins.Vitamins.getConfigurationRW(), com.neuronrobotics.bowlerstudio.vitamins.Vitamins.listVitaminSizes(), com.neuronrobotics.bowlerstudio.vitamins.Vitamins.makeJson(), and com.neuronrobotics.bowlerstudio.vitamins.Vitamins.newVitamin().
getGitRepoDatabase()
static String com.neuronrobotics.bowlerstudio.vitamins.Vitamins.getGitRepoDatabase () static
Definition at line 566 of file Vitamins.java.
References com.neuronrobotics.bowlerstudio.vitamins.Vitamins.checked, com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.cloneRepo(), com.neuronrobotics.bowlerstudio.vitamins.Vitamins.defaultgitRpoDatabase, com.neuronrobotics.bowlerstudio.scripting.PasswordManager.getGithub(), com.neuronrobotics.bowlerstudio.scripting.PasswordManager.getLoginID(), com.neuronrobotics.bowlerstudio.scripting.PasswordManager.getUsername(), com.neuronrobotics.bowlerstudio.vitamins.Vitamins.gitRpoDatabase, com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.setAutoupdate(), com.neuronrobotics.bowlerstudio.vitamins.Vitamins.setGitRepoDatabase(), and com.neuronrobotics.bowlerstudio.IssueReportingExceptionHandler.uncaughtException().
Referenced by com.neuronrobotics.bowlerstudio.vitamins.Vitamins.getVitaminFile(), com.neuronrobotics.bowlerstudio.vitamins.Vitamins.listVitaminTypes(), com.neuronrobotics.bowlerstudio.vitamins.Vitamins.reLoadDatabaseFromFiles(), com.neuronrobotics.bowlerstudio.vitamins.Vitamins.saveDatabase(), and com.neuronrobotics.bowlerstudio.vitamins.Vitamins.setJsonRootDir().
getJsonRootDir()
static String com.neuronrobotics.bowlerstudio.vitamins.Vitamins.getJsonRootDir () static
Definition at line 620 of file Vitamins.java.
References com.neuronrobotics.bowlerstudio.vitamins.Vitamins.jsonRootDir.
Referenced by com.neuronrobotics.bowlerstudio.vitamins.Vitamins.getRootFolder().
getMeasurement()
static Object com.neuronrobotics.bowlerstudio.vitamins.Vitamins.getMeasurement (String type, String size, String measurementName) static
Definition at line 215 of file Vitamins.java.
References com.neuronrobotics.bowlerstudio.vitamins.Vitamins.getConfigurationRW().
getMeta()
static Map<String, Object> com.neuronrobotics.bowlerstudio.vitamins.Vitamins.getMeta (String type) static
Definition at line 200 of file Vitamins.java.
References com.neuronrobotics.bowlerstudio.vitamins.Vitamins.getConfigurationRW().
Referenced by com.neuronrobotics.bowlerstudio.vitamins.Vitamins.get(), com.neuronrobotics.bowlerstudio.vitamins.Vitamins.getScriptFile(), com.neuronrobotics.bowlerstudio.vitamins.Vitamins.isActuator(), com.neuronrobotics.bowlerstudio.vitamins.Vitamins.isShaft(), com.neuronrobotics.bowlerstudio.vitamins.Vitamins.setIsActuator(), and com.neuronrobotics.bowlerstudio.vitamins.Vitamins.setIsShaft().
getRootFolder()
static String com.neuronrobotics.bowlerstudio.vitamins.Vitamins.getRootFolder () static private
Definition at line 485 of file Vitamins.java.
References com.neuronrobotics.bowlerstudio.vitamins.Vitamins.getJsonRootDir().
Referenced by com.neuronrobotics.bowlerstudio.vitamins.Vitamins.getVitaminFile(), com.neuronrobotics.bowlerstudio.vitamins.Vitamins.listVitaminTypes(), and com.neuronrobotics.bowlerstudio.vitamins.Vitamins.saveDatabase().
getScriptFile()
static File com.neuronrobotics.bowlerstudio.vitamins.Vitamins.getScriptFile (String type) static
Definition at line 179 of file Vitamins.java.
References com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.fileFromGit(), and com.neuronrobotics.bowlerstudio.vitamins.Vitamins.getMeta().
getVitaminFile()
static File com.neuronrobotics.bowlerstudio.vitamins.Vitamins.getVitaminFile (String type, Runnable onChange, boolean oneShot) throws InvalidRemoteException, TransportException, GitAPIException, IOException static
Definition at line 469 of file Vitamins.java.
References com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.fileFromGit(), com.neuronrobotics.bowlerstudio.vitamins.Vitamins.getGitRepoDatabase(), and com.neuronrobotics.bowlerstudio.vitamins.Vitamins.getRootFolder().
Referenced by com.neuronrobotics.bowlerstudio.vitamins.Vitamins.getDatabase(), and com.neuronrobotics.bowlerstudio.vitamins.Vitamins.saveDatabase().
isActuator()
static boolean com.neuronrobotics.bowlerstudio.vitamins.Vitamins.isActuator (String vitaminsType) static
Definition at line 512 of file Vitamins.java.
References com.neuronrobotics.bowlerstudio.vitamins.Vitamins.getMeta().
Referenced by com.neuronrobotics.bowlerstudio.vitamins.Vitamins.listVitaminActuators().
isShaft()
static boolean com.neuronrobotics.bowlerstudio.vitamins.Vitamins.isShaft (String vitaminsType) static
Definition at line 506 of file Vitamins.java.
References com.neuronrobotics.bowlerstudio.vitamins.Vitamins.getMeta().
Referenced by com.neuronrobotics.bowlerstudio.vitamins.Vitamins.listVitaminShafts().
listVitaminActuators()
static ArrayList<String> com.neuronrobotics.bowlerstudio.vitamins.Vitamins.listVitaminActuators () static
Definition at line 488 of file Vitamins.java.
References com.neuronrobotics.bowlerstudio.vitamins.Vitamins.isActuator(), and com.neuronrobotics.bowlerstudio.vitamins.Vitamins.listVitaminTypes().
listVitaminShafts()
static ArrayList<String> com.neuronrobotics.bowlerstudio.vitamins.Vitamins.listVitaminShafts () static
Definition at line 497 of file Vitamins.java.
References com.neuronrobotics.bowlerstudio.vitamins.Vitamins.isShaft(), and com.neuronrobotics.bowlerstudio.vitamins.Vitamins.listVitaminTypes().
listVitaminSizes()
static ArrayList<String> com.neuronrobotics.bowlerstudio.vitamins.Vitamins.listVitaminSizes (String type) static
Definition at line 549 of file Vitamins.java.
References com.neuronrobotics.bowlerstudio.vitamins.Vitamins.getDatabase().
Referenced by com.neuronrobotics.bowlerstudio.vitamins.Vitamins.get().
listVitaminTypes()
static ArrayList<String> com.neuronrobotics.bowlerstudio.vitamins.Vitamins.listVitaminTypes () static
Definition at line 527 of file Vitamins.java.
References com.neuronrobotics.bowlerstudio.vitamins.Vitamins.getGitRepoDatabase(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getRepositoryCloneDirectory(), and com.neuronrobotics.bowlerstudio.vitamins.Vitamins.getRootFolder().
Referenced by com.neuronrobotics.bowlerstudio.vitamins.Vitamins.listVitaminActuators(), com.neuronrobotics.bowlerstudio.vitamins.Vitamins.listVitaminShafts(), and com.neuronrobotics.bowlerstudio.vitamins.Vitamins.reLoadDatabaseFromFiles().
makeJson()
static String com.neuronrobotics.bowlerstudio.vitamins.Vitamins.makeJson (String type) static
Definition at line 248 of file Vitamins.java.
References com.neuronrobotics.bowlerstudio.vitamins.Vitamins.getDatabase(), com.neuronrobotics.bowlerstudio.vitamins.Vitamins.gson, and com.neuronrobotics.bowlerstudio.vitamins.Vitamins.TT_mapStringString.
Referenced by com.neuronrobotics.bowlerstudio.vitamins.Vitamins.saveDatabase().
newVitamin()
static void com.neuronrobotics.bowlerstudio.vitamins.Vitamins.newVitamin (String type, String id) throws Exception static
Definition at line 360 of file Vitamins.java.
References com.neuronrobotics.bowlerstudio.vitamins.Vitamins.getConfigurationRW(), and com.neuronrobotics.bowlerstudio.vitamins.Vitamins.getDatabase().
Referenced by com.neuronrobotics.bowlerstudio.vitamins.Vitamins.get().
processSelfPR()
static void com.neuronrobotics.bowlerstudio.vitamins.Vitamins.processSelfPR (GHPullRequest request) throws IOException static private
Definition at line 340 of file Vitamins.java.
References com.neuronrobotics.bowlerstudio.scripting.PasswordManager.getUsername(), com.neuronrobotics.bowlerstudio.vitamins.Vitamins.reLoadDatabaseFromFiles(), and com.neuronrobotics.bowlerstudio.BowlerKernel.upenURL().
Referenced by com.neuronrobotics.bowlerstudio.vitamins.Vitamins.saveDatabaseForkIfMissing().
putMeasurment()
static void com.neuronrobotics.bowlerstudio.vitamins.Vitamins.putMeasurment (String type, String size, String measurementName, Object measurmentValue) static
Definition at line 212 of file Vitamins.java.
References com.neuronrobotics.bowlerstudio.vitamins.Vitamins.getConfigurationRW().
reLoadDatabaseFromFiles()
static void com.neuronrobotics.bowlerstudio.vitamins.Vitamins.reLoadDatabaseFromFiles () static
Definition at line 594 of file Vitamins.java.
References com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.deleteRepo(), com.neuronrobotics.bowlerstudio.vitamins.Vitamins.getGitRepoDatabase(), com.neuronrobotics.bowlerstudio.vitamins.Vitamins.listVitaminTypes(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.pull(), com.neuronrobotics.bowlerstudio.vitamins.Vitamins.setGitRepoDatabase(), and com.neuronrobotics.bowlerstudio.IssueReportingExceptionHandler.uncaughtException().
Referenced by com.neuronrobotics.bowlerstudio.vitamins.Vitamins.processSelfPR().
sanatize()
static void com.neuronrobotics.bowlerstudio.vitamins.Vitamins.sanatize (String parameterName, HashMap< String, Object > config) static private
Definition at line 393 of file Vitamins.java.
Referenced by com.neuronrobotics.bowlerstudio.vitamins.Vitamins.getConfigurationRW(), and com.neuronrobotics.bowlerstudio.vitamins.Vitamins.setParameter().
saveDatabase()
static void com.neuronrobotics.bowlerstudio.vitamins.Vitamins.saveDatabase (String type) throws Exception static
Definition at line 252 of file Vitamins.java.
References com.neuronrobotics.bowlerstudio.vitamins.Vitamins.defaultgitRpoDatabase, com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.getFullBranch(), com.neuronrobotics.bowlerstudio.vitamins.Vitamins.getGitRepoDatabase(), com.neuronrobotics.bowlerstudio.vitamins.Vitamins.getRootFolder(), com.neuronrobotics.bowlerstudio.scripting.PasswordManager.getUsername(), com.neuronrobotics.bowlerstudio.vitamins.Vitamins.getVitaminFile(), com.neuronrobotics.bowlerstudio.vitamins.Vitamins.makeJson(), and com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.pushCodeToGit().
Referenced by com.neuronrobotics.bowlerstudio.vitamins.Vitamins.saveDatabaseForkIfMissing().
saveDatabaseForkIfMissing()
static void com.neuronrobotics.bowlerstudio.vitamins.Vitamins.saveDatabaseForkIfMissing (String type) throws Exception static
Definition at line 273 of file Vitamins.java.
References com.neuronrobotics.bowlerstudio.scripting.PasswordManager.getGithub(), com.neuronrobotics.bowlerstudio.scripting.PasswordManager.getUsername(), com.neuronrobotics.bowlerstudio.vitamins.Vitamins.gitRpoDatabase, com.neuronrobotics.bowlerstudio.vitamins.Vitamins.processSelfPR(), com.neuronrobotics.bowlerstudio.vitamins.Vitamins.saveDatabase(), com.neuronrobotics.bowlerstudio.IssueReportingExceptionHandler.uncaughtException(), and com.neuronrobotics.bowlerstudio.BowlerKernel.upenURL().
setGitRepoDatabase()
static void com.neuronrobotics.bowlerstudio.vitamins.Vitamins.setGitRepoDatabase (String gitRpoDatabase) static
Definition at line 613 of file Vitamins.java.
References com.neuronrobotics.bowlerstudio.vitamins.Vitamins.databaseSet, com.neuronrobotics.bowlerstudio.vitamins.Vitamins.fileLastLoaded, and com.neuronrobotics.bowlerstudio.vitamins.Vitamins.gitRpoDatabase.
Referenced by com.neuronrobotics.bowlerstudio.vitamins.Vitamins.getGitRepoDatabase(), com.neuronrobotics.bowlerstudio.vitamins.Vitamins.reLoadDatabaseFromFiles(), and com.neuronrobotics.bowlerstudio.vitamins.Vitamins.setJsonRootDir().
setIsActuator()
static void com.neuronrobotics.bowlerstudio.vitamins.Vitamins.setIsActuator (String type) static
Definition at line 523 of file Vitamins.java.
References com.neuronrobotics.bowlerstudio.vitamins.Vitamins.getMeta().
setIsShaft()
static void com.neuronrobotics.bowlerstudio.vitamins.Vitamins.setIsShaft (String type) static
Definition at line 518 of file Vitamins.java.
References com.neuronrobotics.bowlerstudio.vitamins.Vitamins.getMeta().
setJsonRootDir()
static void com.neuronrobotics.bowlerstudio.vitamins.Vitamins.setJsonRootDir (String jsonRootDir) throws IOException static
Definition at line 624 of file Vitamins.java.
References com.neuronrobotics.bowlerstudio.vitamins.Vitamins.getGitRepoDatabase(), com.neuronrobotics.bowlerstudio.vitamins.Vitamins.jsonRootDir, and com.neuronrobotics.bowlerstudio.vitamins.Vitamins.setGitRepoDatabase().
setParameter()
static void com.neuronrobotics.bowlerstudio.vitamins.Vitamins.setParameter (String type, String id, String parameterName, Object parameter) throws Exception static
Definition at line 384 of file Vitamins.java.
References com.neuronrobotics.bowlerstudio.vitamins.Vitamins.getConfigurationRW(), and com.neuronrobotics.bowlerstudio.vitamins.Vitamins.sanatize().
Referenced by com.neuronrobotics.bowlerstudio.vitamins.Vitamins.setScript().
setScript()
static void com.neuronrobotics.bowlerstudio.vitamins.Vitamins.setScript (String type, String git, String file) throws Exception static
Definition at line 204 of file Vitamins.java.
References com.neuronrobotics.bowlerstudio.vitamins.Vitamins.setParameter().
Member Data Documentation
changeListeners
HashMap<String,Runnable> com.neuronrobotics.bowlerstudio.vitamins.Vitamins.changeListeners = new HashMap<String, Runnable>() static private
Definition at line 63 of file Vitamins.java.
Referenced by com.neuronrobotics.bowlerstudio.vitamins.Vitamins.getDatabase().
checked
boolean com.neuronrobotics.bowlerstudio.vitamins.Vitamins.checked static private
Definition at line 62 of file Vitamins.java.
Referenced by com.neuronrobotics.bowlerstudio.vitamins.Vitamins.getGitRepoDatabase().
databaseSet
final Map<String, HashMap<String, HashMap<String, Object> > > com.neuronrobotics.bowlerstudio.vitamins.Vitamins.databaseSet = new HashMap<String, HashMap<String, HashMap<String, Object>>>() static private
Definition at line 53 of file Vitamins.java.
Referenced by com.neuronrobotics.bowlerstudio.vitamins.Vitamins.clear(), com.neuronrobotics.bowlerstudio.vitamins.Vitamins.getDatabase(), and com.neuronrobotics.bowlerstudio.vitamins.Vitamins.setGitRepoDatabase().
defaultgitRpoDatabase
final String com.neuronrobotics.bowlerstudio.vitamins.Vitamins.defaultgitRpoDatabase = "https://github.com/madhephaestus/Hardware-Dimensions.git" static private
Definition at line 54 of file Vitamins.java.
Referenced by com.neuronrobotics.bowlerstudio.vitamins.Vitamins.get(), com.neuronrobotics.bowlerstudio.vitamins.Vitamins.getGitRepoDatabase(), and com.neuronrobotics.bowlerstudio.vitamins.Vitamins.saveDatabase().
fileLastLoaded
final Map<String, CSG> com.neuronrobotics.bowlerstudio.vitamins.Vitamins.fileLastLoaded = new HashMap<String, CSG>() static private
Definition at line 52 of file Vitamins.java.
Referenced by com.neuronrobotics.bowlerstudio.vitamins.Vitamins.clear(), com.neuronrobotics.bowlerstudio.vitamins.Vitamins.get(), and com.neuronrobotics.bowlerstudio.vitamins.Vitamins.setGitRepoDatabase().
gitRpoDatabase
String com.neuronrobotics.bowlerstudio.vitamins.Vitamins.gitRpoDatabase = defaultgitRpoDatabase static private
Definition at line 55 of file Vitamins.java.
Referenced by com.neuronrobotics.bowlerstudio.vitamins.Vitamins.get(), com.neuronrobotics.bowlerstudio.vitamins.Vitamins.getGitRepoDatabase(), com.neuronrobotics.bowlerstudio.vitamins.Vitamins.saveDatabaseForkIfMissing(), and com.neuronrobotics.bowlerstudio.vitamins.Vitamins.setGitRepoDatabase().
gson
Gson com.neuronrobotics.bowlerstudio.vitamins.Vitamins.gson = new GsonBuilder().disableHtmlEscaping().setPrettyPrinting().create() static private
Definition at line 61 of file Vitamins.java.
Referenced by com.neuronrobotics.bowlerstudio.vitamins.Vitamins.getDatabase(), and com.neuronrobotics.bowlerstudio.vitamins.Vitamins.makeJson().
jsonRootDir
String com.neuronrobotics.bowlerstudio.vitamins.Vitamins.jsonRootDir = "json/" static private
Definition at line 51 of file Vitamins.java.
Referenced by com.neuronrobotics.bowlerstudio.vitamins.Vitamins.getJsonRootDir(), and com.neuronrobotics.bowlerstudio.vitamins.Vitamins.setJsonRootDir().
TT_mapStringString
Type com.neuronrobotics.bowlerstudio.vitamins.Vitamins.TT_mapStringString static private
Initial value:
= new TypeToken<HashMap<String, HashMap<String, Object>>>() {
    }.getType()
Definition at line 58 of file Vitamins.java.
Referenced by com.neuronrobotics.bowlerstudio.vitamins.Vitamins.getDatabase(), and com.neuronrobotics.bowlerstudio.vitamins.Vitamins.makeJson().
The documentation for this class was generated from the following file:
src/main/java/com/neuronrobotics/bowlerstudio/vitamins/Vitamins.java