BowlerKernel: com.neuronrobotics.sdk.addons.kinematics.DHChain Class Reference
com.neuronrobotics.sdk.addons.kinematics.DHChain Class Reference
Public Member Functions
DHChain (AbstractKinematicsNR kin)
void addLink (DHLink link)
void removeLink (DHLink link)
double[] inverseKinematics (TransformNR target, double[] jointSpaceVector) throws Exception
TransformNR forwardKinematics (double[] jointSpaceVector)
TransformNR forwardKinematics (double[] jointSpaceVector, boolean store)
Matrix forwardKinematicsMatrix (double[] jointSpaceVector, boolean store)
Matrix forwardKinematicsMatrix (double[] jointSpaceVector, ArrayList< TransformNR > chainToLoad)
void setChain (ArrayList< TransformNR > chain)
ArrayList< TransformNR > getChain (double[] jointSpaceVector)
ArrayList< TransformNR > getCachedChain ()
double[] getUpperLimits ()
double[] getlowerLimits ()
void setLinks (ArrayList< DHLink > links)
ArrayList< DHLink > getLinks ()
String toString ()
DhInverseSolver getInverseSolver ()
void setInverseSolver (DhInverseSolver is)
LinkFactory getFactory ()
void setFactory (LinkFactory factory)
Public Attributes
AbstractKinematicsNR kin
Private Member Functions
double[] crossProduct (double[] a, double[] b)
TransformNR forwardOffset (TransformNR transformNR)
Private Attributes
ArrayList< DHLink > links = new ArrayList<DHLink>()
ArrayList< TransformNR > chain = new ArrayList<TransformNR>()
ArrayList< TransformNR > intChain = new ArrayList<TransformNR>()
double[] upperLimits
double[] lowerLimits
boolean debug =false
DhInverseSolver is
LinkFactory factory
Detailed Description
The Class DHChain.
Definition at line 22 of file DHChain.java.
Constructor & Destructor Documentation
DHChain()
com.neuronrobotics.sdk.addons.kinematics.DHChain.DHChain (AbstractKinematicsNR kin)
Instantiates a new DH chain.
Parameters
kin the kin
Definition at line 57 of file DHChain.java.
References com.neuronrobotics.sdk.addons.kinematics.DHChain.kin.
Member Function Documentation
addLink()
void com.neuronrobotics.sdk.addons.kinematics.DHChain.addLink (DHLink link)
Adds the link.
Parameters
link the link
Definition at line 67 of file DHChain.java.
References com.neuronrobotics.sdk.addons.kinematics.DHChain.getLinks().
Referenced by com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.addNewLink().
crossProduct()
double [] com.neuronrobotics.sdk.addons.kinematics.DHChain.crossProduct (double[] a, double[] b) private
Cross product.
Parameters
a the a
b the b
Returns
the double[]
Definition at line 164 of file DHChain.java.
forwardKinematics() [1/2]
TransformNR com.neuronrobotics.sdk.addons.kinematics.DHChain.forwardKinematics (double[] jointSpaceVector)
Forward kinematics.
Parameters
jointSpaceVector the joint space vector
Returns
the transform nr
Definition at line 140 of file DHChain.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.SearchTreeSolver.fk(), com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.forwardKinematics(), com.neuronrobotics.sdk.addons.kinematics.ComputedGeometricModel.inverseKinematics(), com.neuronrobotics.sdk.addons.kinematics.GradiantDecent.inverseKinematics(), com.neuronrobotics.sdk.addons.kinematics.GradiantDecentNode.stepLin(), and com.neuronrobotics.sdk.addons.kinematics.GradiantDecentNode.stepOrent().
forwardKinematics() [2/2]
TransformNR com.neuronrobotics.sdk.addons.kinematics.DHChain.forwardKinematics (double[] jointSpaceVector, boolean store)
Forward kinematics.
Parameters
jointSpaceVector the joint space vector
store the store
Returns
the transform nr
Definition at line 151 of file DHChain.java.
References com.neuronrobotics.sdk.addons.kinematics.DHChain.forwardKinematicsMatrix().
forwardKinematicsMatrix() [1/2]
Matrix com.neuronrobotics.sdk.addons.kinematics.DHChain.forwardKinematicsMatrix (double[] jointSpaceVector, ArrayList< TransformNR > chainToLoad)
Definition at line 184 of file DHChain.java.
References com.neuronrobotics.sdk.addons.kinematics.DHChain.forwardOffset(), com.neuronrobotics.sdk.addons.kinematics.DHChain.getFactory(), com.neuronrobotics.sdk.addons.kinematics.LinkFactory.getLinkConfigurations(), com.neuronrobotics.sdk.addons.kinematics.DHChain.getLinks(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getMatrixTransform(), com.neuronrobotics.sdk.addons.kinematics.DHChain.intChain, and com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.isPrismatic().
forwardKinematicsMatrix() [2/2]
Matrix com.neuronrobotics.sdk.addons.kinematics.DHChain.forwardKinematicsMatrix (double[] jointSpaceVector, boolean store)
Forward kinematics matrix.
Parameters
jointSpaceVector the joint space vector
store the store
Returns
the matrix
Definition at line 181 of file DHChain.java.
References com.neuronrobotics.sdk.addons.kinematics.DHChain.getCachedChain().
Referenced by com.neuronrobotics.sdk.addons.kinematics.DHChain.forwardKinematics(), com.neuronrobotics.sdk.addons.kinematics.DHChain.getChain(), and com.neuronrobotics.sdk.addons.kinematics.ik.DeltaIKModel.inverseKinematics6dof().
forwardOffset()
TransformNR com.neuronrobotics.sdk.addons.kinematics.DHChain.forwardOffset (TransformNR transformNR) private
Forward offset.
Parameters
transformNR the transform nr
Returns
the transform nr
Definition at line 239 of file DHChain.java.
References com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.forwardOffset(), and com.neuronrobotics.sdk.addons.kinematics.DHChain.kin.
Referenced by com.neuronrobotics.sdk.addons.kinematics.DHChain.forwardKinematicsMatrix().
getCachedChain()
ArrayList<TransformNR> com.neuronrobotics.sdk.addons.kinematics.DHChain.getCachedChain ()
Gets the cached chain.
Returns
the cached chain
Definition at line 273 of file DHChain.java.
References com.neuronrobotics.sdk.addons.kinematics.DHChain.chain.
Referenced by com.neuronrobotics.sdk.addons.kinematics.DHChain.forwardKinematicsMatrix(), com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getLinkTip(), com.neuronrobotics.bowlerstudio.physics.MobileBasePhysicsManager.MobileBasePhysicsManager(), and com.neuronrobotics.sdk.addons.kinematics.DHChain.setChain().
getChain()
ArrayList<TransformNR> com.neuronrobotics.sdk.addons.kinematics.DHChain.getChain (double[] jointSpaceVector)
Gets the chain.
Parameters
jointSpaceVector the joint space vector
Returns
the chain
Definition at line 262 of file DHChain.java.
References com.neuronrobotics.sdk.addons.kinematics.DHChain.forwardKinematicsMatrix().
Referenced by com.neuronrobotics.sdk.addons.kinematics.parallel.ParallelGroup.compute(), com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getChainTransformations(), com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getJacobian(), com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.linkCoM(), com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.setGlobalToFiducialTransform(), com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.updateCadLocations(), and com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.updateLimb().
getFactory()
LinkFactory com.neuronrobotics.sdk.addons.kinematics.DHChain.getFactory ()
Gets the factory.
Returns
the factory
Definition at line 472 of file DHChain.java.
References com.neuronrobotics.sdk.addons.kinematics.DHChain.factory.
Referenced by com.neuronrobotics.sdk.addons.kinematics.DHChain.forwardKinematicsMatrix().
getInverseSolver()
DhInverseSolver com.neuronrobotics.sdk.addons.kinematics.DHChain.getInverseSolver ()
Gets the inverse solver.
Returns
the inverse solver
Definition at line 334 of file DHChain.java.
References com.neuronrobotics.sdk.addons.kinematics.DHChain.chain, com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getMatrixTransform(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getRotation(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getX(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getY(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getZ(), com.neuronrobotics.sdk.addons.kinematics.DHChain.inverseKinematics(), com.neuronrobotics.sdk.addons.kinematics.DHChain.is, and com.neuronrobotics.sdk.addons.kinematics.DHChain.links.
Referenced by com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getInverseSolver(), and com.neuronrobotics.sdk.addons.kinematics.DHChain.inverseKinematics().
getLinks()
ArrayList<DHLink> com.neuronrobotics.sdk.addons.kinematics.DHChain.getLinks ()
Gets the links.
Returns
the links
Definition at line 313 of file DHChain.java.
References com.neuronrobotics.sdk.addons.kinematics.DHChain.links.
Referenced by com.neuronrobotics.sdk.addons.kinematics.DHChain.addLink(), com.neuronrobotics.sdk.addons.kinematics.DHChain.forwardKinematicsMatrix(), com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getDH_Alpha(), com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getDH_D(), com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getDH_R(), com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getDH_Theta(), com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getDhLink(), com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getEmbedableXml(), com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getJacobian(), com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getLinkObjectManipulator(), com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.getListener(), com.neuronrobotics.sdk.addons.kinematics.DHChain.inverseKinematics(), com.neuronrobotics.sdk.addons.kinematics.ComputedGeometricModel.inverseKinematics(), com.neuronrobotics.sdk.addons.kinematics.GradiantDecent.inverseKinematics(), com.neuronrobotics.sdk.addons.kinematics.SearchTreeSolver.inverseKinematics(), com.neuronrobotics.sdk.addons.kinematics.ik.DeltaIKModel.inverseKinematics6dof(), com.neuronrobotics.bowlerstudio.physics.MobileBasePhysicsManager.MobileBasePhysicsManager(), com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.onJointSpaceUpdate(), com.neuronrobotics.sdk.addons.kinematics.DHChain.removeLink(), com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.removeLink(), com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.setChain(), com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.setDH_Alpha(), com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.setDH_D(), com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.setDH_R(), com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.setDH_Theta(), com.neuronrobotics.sdk.addons.kinematics.DHChain.toString(), and com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.updateLimb().
getlowerLimits()
double [] com.neuronrobotics.sdk.addons.kinematics.DHChain.getlowerLimits ()
Gets the lower limits.
Returns
the lower limits
Definition at line 294 of file DHChain.java.
References com.neuronrobotics.sdk.addons.kinematics.DHChain.lowerLimits.
Referenced by com.neuronrobotics.sdk.addons.kinematics.GradiantDecent.inverseKinematics(), and com.neuronrobotics.sdk.addons.kinematics.SearchTreeSolver.SearchTreeSolver().
getUpperLimits()
double [] com.neuronrobotics.sdk.addons.kinematics.DHChain.getUpperLimits ()
Gets the upper limits.
Returns
the upper limits
Definition at line 284 of file DHChain.java.
References com.neuronrobotics.sdk.addons.kinematics.DHChain.upperLimits.
Referenced by com.neuronrobotics.sdk.addons.kinematics.GradiantDecent.inverseKinematics(), and com.neuronrobotics.sdk.addons.kinematics.SearchTreeSolver.SearchTreeSolver().
inverseKinematics()
double [] com.neuronrobotics.sdk.addons.kinematics.DHChain.inverseKinematics (TransformNR target, double[] jointSpaceVector) throws Exception
Inverse kinematics.
Parameters
target the target
jointSpaceVector the joint space vector
Returns
the double[]
Exceptions
Exception the exception
Definition at line 113 of file DHChain.java.
References com.neuronrobotics.sdk.addons.kinematics.DHChain.debug, com.neuronrobotics.sdk.addons.kinematics.DHChain.getInverseSolver(), com.neuronrobotics.sdk.addons.kinematics.DHChain.getLinks(), com.neuronrobotics.sdk.addons.kinematics.DhInverseSolver.inverseKinematics(), and com.neuronrobotics.sdk.addons.kinematics.DHChain.setInverseSolver().
Referenced by com.neuronrobotics.sdk.addons.kinematics.DHChain.getInverseSolver(), and com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.inverseKinematics().
removeLink()
void com.neuronrobotics.sdk.addons.kinematics.DHChain.removeLink (DHLink link)
Removes the link.
Parameters
link the link
Definition at line 78 of file DHChain.java.
References com.neuronrobotics.sdk.addons.kinematics.DHChain.getLinks().
setChain()
void com.neuronrobotics.sdk.addons.kinematics.DHChain.setChain (ArrayList< TransformNR > chain)
Sets the chain.
Parameters
chain the new chain
Definition at line 248 of file DHChain.java.
References com.neuronrobotics.sdk.addons.kinematics.DHChain.chain, and com.neuronrobotics.sdk.addons.kinematics.DHChain.getCachedChain().
Referenced by com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.setGlobalToFiducialTransform().
setFactory()
void com.neuronrobotics.sdk.addons.kinematics.DHChain.setFactory (LinkFactory factory)
Sets the factory.
Parameters
factory the new factory
Definition at line 481 of file DHChain.java.
References com.neuronrobotics.sdk.addons.kinematics.DHChain.factory, com.neuronrobotics.sdk.addons.kinematics.LinkFactory.getLowerLimits(), com.neuronrobotics.sdk.addons.kinematics.LinkFactory.getUpperLimits(), com.neuronrobotics.sdk.addons.kinematics.DHChain.lowerLimits, and com.neuronrobotics.sdk.addons.kinematics.DHChain.upperLimits.
Referenced by com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.addNewLink().
setInverseSolver()
void com.neuronrobotics.sdk.addons.kinematics.DHChain.setInverseSolver (DhInverseSolver is)
Sets the inverse solver.
Parameters
is the new inverse solver
Definition at line 463 of file DHChain.java.
References com.neuronrobotics.sdk.addons.kinematics.DHChain.is.
Referenced by com.neuronrobotics.sdk.addons.kinematics.DHChain.inverseKinematics(), and com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.setInverseSolver().
setLinks()
void com.neuronrobotics.sdk.addons.kinematics.DHChain.setLinks (ArrayList< DHLink > links)
Sets the links.
Parameters
links the new links
Definition at line 304 of file DHChain.java.
References com.neuronrobotics.sdk.addons.kinematics.DHChain.links.
toString()
String com.neuronrobotics.sdk.addons.kinematics.DHChain.toString ()
Definition at line 320 of file DHChain.java.
References com.neuronrobotics.sdk.addons.kinematics.DHChain.getLinks().
Member Data Documentation
chain
ArrayList<TransformNR> com.neuronrobotics.sdk.addons.kinematics.DHChain.chain = new ArrayList<TransformNR>() private
The chain.
Definition at line 28 of file DHChain.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.DHChain.getCachedChain(), com.neuronrobotics.sdk.addons.kinematics.DHChain.getInverseSolver(), and com.neuronrobotics.sdk.addons.kinematics.DHChain.setChain().
debug
boolean com.neuronrobotics.sdk.addons.kinematics.DHChain.debug =false private
The debug.
Definition at line 40 of file DHChain.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.DHChain.inverseKinematics().
factory
LinkFactory com.neuronrobotics.sdk.addons.kinematics.DHChain.factory private
The factory.
Definition at line 49 of file DHChain.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.DHChain.getFactory(), and com.neuronrobotics.sdk.addons.kinematics.DHChain.setFactory().
intChain
ArrayList<TransformNR> com.neuronrobotics.sdk.addons.kinematics.DHChain.intChain = new ArrayList<TransformNR>() private
The int chain.
Definition at line 31 of file DHChain.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.DHChain.forwardKinematicsMatrix().
is
DhInverseSolver com.neuronrobotics.sdk.addons.kinematics.DHChain.is private
The is.
Definition at line 43 of file DHChain.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.DHChain.getInverseSolver(), and com.neuronrobotics.sdk.addons.kinematics.DHChain.setInverseSolver().
kin
AbstractKinematicsNR com.neuronrobotics.sdk.addons.kinematics.DHChain.kin
The kin.
Definition at line 46 of file DHChain.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.DHChain.DHChain(), com.neuronrobotics.sdk.addons.kinematics.DHChain.forwardOffset(), com.neuronrobotics.sdk.addons.kinematics.ik.DeltaIKModel.inverseKinematics6dof(), and com.neuronrobotics.sdk.addons.kinematics.WristNormalizer.normalize().
links
ArrayList<DHLink> com.neuronrobotics.sdk.addons.kinematics.DHChain.links = new ArrayList<DHLink>() private
The links.
Definition at line 25 of file DHChain.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.DHChain.getInverseSolver(), com.neuronrobotics.sdk.addons.kinematics.DHChain.getLinks(), and com.neuronrobotics.sdk.addons.kinematics.DHChain.setLinks().
lowerLimits
double [] com.neuronrobotics.sdk.addons.kinematics.DHChain.lowerLimits private
The lower limits.
Definition at line 37 of file DHChain.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.DHChain.getlowerLimits(), and com.neuronrobotics.sdk.addons.kinematics.DHChain.setFactory().
upperLimits
double [] com.neuronrobotics.sdk.addons.kinematics.DHChain.upperLimits private
The upper limits.
Definition at line 34 of file DHChain.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.DHChain.getUpperLimits(), and com.neuronrobotics.sdk.addons.kinematics.DHChain.setFactory().
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/addons/kinematics/DHChain.java