BowlerKernel: com.neuronrobotics.sdk.common.device.server.BowlerAbstractDeviceServer Class Reference
com.neuronrobotics.sdk.common.device.server.BowlerAbstractDeviceServer Class Reference abstract
Public Member Functions
boolean connect ()
void addNamespace (String nms)
void onAllResponse (BowlerDatagram data)
void onAsyncResponse (BowlerDatagram data)
void sendAsync (BowlerAbstractCommand command, int rpcIndexID) throws IOException
void sendSyncResponse (BowlerAbstractCommand command) throws IOException
void sendPacketWithNoResponse (BowlerDatagram data) throws IOException
abstract void onSynchronusRecive (BowlerDatagram data)
Public Member Functions inherited from com.neuronrobotics.sdk.common.BowlerAbstractDevice
boolean isAvailable () throws InvalidConnectionException
void addConnectionEventListener (final IDeviceConnectionEventListener l)
void removeConnectionEventListener (IDeviceConnectionEventListener l)
void setConnection (BowlerAbstractConnection connection)
void disconnect ()
BowlerAbstractConnection getConnection ()
void setAddress (MACAddress address)
MACAddress getAddress ()
BowlerDatagram send (BowlerAbstractCommand command) throws NoConnectionAvailableException, InvalidResponseException
BowlerDatagram send (BowlerAbstractCommand command, int retry) throws NoConnectionAvailableException, InvalidResponseException
Object[] send (String namespace, BowlerMethod method, String rpcString, Object[] arguments, int retry) throws DeviceConnectionException
Object[] send (String namespace, BowlerMethod method, String rpcString, Object[] arguments) throws DeviceConnectionException
boolean ping ()
boolean ping (boolean switchParser)
ArrayList< ByteList > getRevisions ()
ArrayList< String > getNamespaces ()
boolean hasNamespace (String string)
void startHeartBeat ()
void startHeartBeat (long msHeartBeatTime)
void stopHeartBeat ()
void setThreadedUpstreamPackets (boolean up)
ArrayList< RpcEncapsulation > getRpcList (String namespace)
void loadRpcList ()
boolean isKeepAlive ()
void setKeepAlive (boolean keepAlive)
long getLastPacketTime ()
void setLastPacketTime (long lastPacketTime)
String getScriptingName ()
void setScriptingName (String scriptingName)
ArrayList< IDeviceConnectionEventListener > getDisconnectListeners ()
Private Attributes
String core = "bcs.core.*;0.3;;"
ArrayList< String > namespaces = new ArrayList<String>()
Additional Inherited Members
Protected Member Functions inherited from com.neuronrobotics.sdk.common.BowlerAbstractDevice
void fireDisconnectEvent ()
void fireConnectEvent ()
Detailed Description
The Class BowlerAbstractDeviceServer.
Definition at line 19 of file BowlerAbstractDeviceServer.java.
Member Function Documentation
addNamespace()
void com.neuronrobotics.sdk.common.device.server.BowlerAbstractDeviceServer.addNamespace (String nms)
Adds the namespace.
Parameters
nms the nms
Definition at line 42 of file BowlerAbstractDeviceServer.java.
References com.neuronrobotics.sdk.common.device.server.BowlerAbstractDeviceServer.namespaces.
Referenced by com.neuronrobotics.sdk.common.device.server.BowlerAbstractDeviceServer.connect().
connect()
boolean com.neuronrobotics.sdk.common.device.server.BowlerAbstractDeviceServer.connect ()
This method tells the connection object to start and connects the up and down streams pipes. Once this method is called and returns without exception, the device is ready to communicate with
Returns
true, if successful
Exceptions
InvalidConnectionException the invalid connection exception
Reimplemented from com.neuronrobotics.sdk.common.BowlerAbstractDevice.
Definition at line 31 of file BowlerAbstractDeviceServer.java.
References com.neuronrobotics.sdk.common.device.server.BowlerAbstractDeviceServer.addNamespace(), com.neuronrobotics.sdk.common.device.server.BowlerAbstractDeviceServer.core, and com.neuronrobotics.sdk.common.BowlerAbstractDevice.isAvailable().
onAllResponse()
void com.neuronrobotics.sdk.common.device.server.BowlerAbstractDeviceServer.onAllResponse (BowlerDatagram data)
On all response.
Parameters
data the data
Reimplemented from com.neuronrobotics.sdk.common.BowlerAbstractDevice.
Definition at line 50 of file BowlerAbstractDeviceServer.java.
References com.neuronrobotics.sdk.common.ByteList.get(), com.neuronrobotics.sdk.common.BowlerDatagram.getData(), com.neuronrobotics.sdk.common.BowlerDatagram.getRPC(), com.neuronrobotics.sdk.common.Log.info(), com.neuronrobotics.sdk.common.device.server.BowlerAbstractDeviceServer.namespaces, com.neuronrobotics.sdk.common.device.server.BowlerAbstractDeviceServer.onSynchronusRecive(), com.neuronrobotics.sdk.common.device.server.BowlerAbstractDeviceServer.sendSyncResponse(), and com.neuronrobotics.sdk.common.ByteList.size().
onAsyncResponse()
void com.neuronrobotics.sdk.common.device.server.BowlerAbstractDeviceServer.onAsyncResponse (BowlerDatagram data)
On async response.
Parameters
data the data
Implements com.neuronrobotics.sdk.common.IBowlerDatagramListener.
Definition at line 87 of file BowlerAbstractDeviceServer.java.
onSynchronusRecive()
abstract void com.neuronrobotics.sdk.common.device.server.BowlerAbstractDeviceServer.onSynchronusRecive (BowlerDatagram data) abstract
On synchronus recive.
Parameters
data the data
Referenced by com.neuronrobotics.sdk.common.device.server.BowlerAbstractDeviceServer.onAllResponse().
sendAsync()
void com.neuronrobotics.sdk.common.device.server.BowlerAbstractDeviceServer.sendAsync (BowlerAbstractCommand command, int rpcIndexID) throws IOException
Send a sendable to the getConnection().
Parameters
command the command
rpcIndexID the rpc index id
Exceptions
IOException Signals that an I/O exception has occurred.
Definition at line 99 of file BowlerAbstractDeviceServer.java.
References com.neuronrobotics.sdk.common.BowlerAbstractDevice.getAddress(), com.neuronrobotics.sdk.common.BowlerAbstractDevice.getConnection(), com.neuronrobotics.sdk.common.BowlerAbstractConnection.getDataOuts(), and com.neuronrobotics.sdk.common.BowlerAbstractConnection.sendAsync().
sendPacketWithNoResponse()
void com.neuronrobotics.sdk.common.device.server.BowlerAbstractDeviceServer.sendPacketWithNoResponse (BowlerDatagram data) throws IOException
Send packet with no response.
Parameters
data the data
Exceptions
IOException Signals that an I/O exception has occurred.
Definition at line 126 of file BowlerAbstractDeviceServer.java.
References com.neuronrobotics.sdk.common.BowlerAbstractDevice.getConnection(), com.neuronrobotics.sdk.common.BowlerAbstractConnection.getDataOuts(), and com.neuronrobotics.sdk.common.BowlerAbstractConnection.sendAsync().
sendSyncResponse()
void com.neuronrobotics.sdk.common.device.server.BowlerAbstractDeviceServer.sendSyncResponse (BowlerAbstractCommand command) throws IOException
Send a sendable to the getConnection().
Parameters
command the command
Exceptions
IOException Signals that an I/O exception has occurred.
Definition at line 113 of file BowlerAbstractDeviceServer.java.
References com.neuronrobotics.sdk.common.BowlerAbstractDevice.getAddress(), com.neuronrobotics.sdk.common.BowlerAbstractDevice.getConnection(), com.neuronrobotics.sdk.common.BowlerAbstractConnection.getDataOuts(), and com.neuronrobotics.sdk.common.BowlerAbstractConnection.sendAsync().
Referenced by com.neuronrobotics.sdk.common.device.server.BowlerAbstractDeviceServer.onAllResponse().
Member Data Documentation
core
String com.neuronrobotics.sdk.common.device.server.BowlerAbstractDeviceServer.core = "bcs.core.*;0.3;;" private
The core.
Definition at line 22 of file BowlerAbstractDeviceServer.java.
Referenced by com.neuronrobotics.sdk.common.device.server.BowlerAbstractDeviceServer.connect().
namespaces
ArrayList<String> com.neuronrobotics.sdk.common.device.server.BowlerAbstractDeviceServer.namespaces = new ArrayList<String>() private
The namespaces.
Definition at line 25 of file BowlerAbstractDeviceServer.java.
Referenced by com.neuronrobotics.sdk.common.device.server.BowlerAbstractDeviceServer.addNamespace(), and com.neuronrobotics.sdk.common.device.server.BowlerAbstractDeviceServer.onAllResponse().
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/common/device/server/BowlerAbstractDeviceServer.java