BowlerKernel: com.piro.bezier.Bezier Class Reference
com.piro.bezier.Bezier Class Reference
Public Member Functions
Bezier (float sx, float sy, float[] coords, int numCoords)
void setCoords (float sx, float sy, float[] coords, int numCoords)
float getLength ()
Vector2 getFinalPoint (Vector2 point)
Private Member Functions
void calcLength ()
float lineLength (float x1, float y1, float x2, float y2)
double bernstein (int numKnots, int knotNo, double param)
int choose (int num, int denom)
Detailed Description
Class that represents a Bèzier curve
Definition at line 10 of file Bezier.java.
Constructor & Destructor Documentation
Bezier()
com.piro.bezier.Bezier.Bezier (float sx, float sy, float[] coords, int numCoords)
Definition at line 15 of file Bezier.java.
References com.piro.bezier.Bezier.setCoords().
Member Function Documentation
bernstein()
double com.piro.bezier.Bezier.bernstein (int numKnots, int knotNo, double param) private
Calculates the bernstein polynomial for evaluating parametric bezier
Parameters
numKnots - one less than number of knots in this curve hull
knotNo - knot we are evaluating Bernstein for
param - Parametric value we are evaluating at
Definition at line 87 of file Bezier.java.
References com.piro.bezier.Bezier.choose().
calcLength()
void com.piro.bezier.Bezier.calcLength () private
Definition at line 42 of file Bezier.java.
References com.piro.bezier.Bezier.lineLength().
Referenced by com.piro.bezier.Bezier.setCoords().
choose()
int com.piro.bezier.Bezier.choose (int num, int denom) private
Definition at line 153 of file Bezier.java.
Referenced by com.piro.bezier.Bezier.bernstein().
getFinalPoint()
Vector2 com.piro.bezier.Bezier.getFinalPoint (Vector2 point)
Definition at line 57 of file Bezier.java.
References com.piro.bezier.Vector2.x, and com.piro.bezier.Vector2.y.
getLength()
float com.piro.bezier.Bezier.getLength ()
Retuns aproximation of the length of the bezier
Definition at line 37 of file Bezier.java.
Referenced by com.piro.bezier.BezierListProducer.curvetoCubicAbs(), com.piro.bezier.BezierListProducer.curvetoCubicSmoothAbs(), com.piro.bezier.BezierListProducer.curvetoQuadraticAbs(), com.piro.bezier.BezierPath.eval(), and com.piro.bezier.BezierListProducer.linetoAbs().
lineLength()
float com.piro.bezier.Bezier.lineLength (float x1, float y1, float x2, float y2) private
Definition at line 51 of file Bezier.java.
Referenced by com.piro.bezier.Bezier.calcLength().
setCoords()
void com.piro.bezier.Bezier.setCoords (float sx, float sy, float[] coords, int numCoords)
Definition at line 20 of file Bezier.java.
References com.piro.bezier.Bezier.calcLength().
Referenced by com.piro.bezier.Bezier.Bezier().
The documentation for this class was generated from the following file:
JCSG/src/main/java/com/piro/bezier/Bezier.java