BowlerKernel: com.neuronrobotics.bowlerstudio.physics.PhysicsCore Class Reference
com.neuronrobotics.bowlerstudio.physics.PhysicsCore Class Reference
Public Member Functions
PhysicsCore () throws Exception
BroadphaseInterface getBroadphase ()
void setBroadphase (BroadphaseInterface broadphase)
DefaultCollisionConfiguration getCollisionConfiguration ()
void setCollisionConfiguration (DefaultCollisionConfiguration collisionConfiguration)
CollisionDispatcher getDispatcher ()
void setDispatcher (CollisionDispatcher dispatcher)
SequentialImpulseConstraintSolver getSolver ()
void setSolver (SequentialImpulseConstraintSolver solver)
DiscreteDynamicsWorld getDynamicsWorld ()
void setDynamicsWorld (DiscreteDynamicsWorld dynamicsWorld)
CollisionShape getGroundShape ()
void setGroundShape (CollisionShape cs)
ArrayList< IPhysicsManager > getPhysicsObjects ()
void setDamping (float lin_damping, float ang_damping)
void setSleepingThresholds (float linearSleepThreshhold, float angularSleepThreshhold)
void setDeactivationTime (float deactivationTime)
void setObjects (ArrayList< IPhysicsManager > objects)
void startPhysicsThread (int ms)
ArrayList< CSG > getCsgFromEngine ()
void stopPhysicsThread ()
void step (float timeStep)
void stepMs (double timeStep)
void add (IPhysicsManager manager)
void remove (IPhysicsManager manager)
void clear ()
int getSimulationSubSteps ()
float getDeactivationTime ()
void setSimulationSubSteps (int simpulationSubSteps)
float getLin_damping ()
float getAng_damping ()
float getLinearSleepThreshhold ()
float getAngularSleepThreshhold ()
Private Attributes
BroadphaseInterface broadphase = new DbvtBroadphase()
DefaultCollisionConfiguration collisionConfiguration = new DefaultCollisionConfiguration()
CollisionDispatcher dispatcher = new CollisionDispatcher(collisionConfiguration)
SequentialImpulseConstraintSolver solver = new SequentialImpulseConstraintSolver()
DiscreteDynamicsWorld dynamicsWorld
CollisionShape groundShape = null
ArrayList< IPhysicsManager > objects = new ArrayList<>()
RigidBody groundRigidBody
boolean runEngine = false
int msTime = 16
Thread physicsThread = null
int simulationSubSteps = 5
float lin_damping
float ang_damping
float linearSleepThreshhold
float angularSleepThreshhold
float deactivationTime
Detailed Description
Definition at line 28 of file PhysicsCore.java.
Constructor & Destructor Documentation
PhysicsCore()
com.neuronrobotics.bowlerstudio.physics.PhysicsCore.PhysicsCore () throws Exception
Definition at line 56 of file PhysicsCore.java.
References com.neuronrobotics.bowlerstudio.physics.PhysicsCore.getDynamicsWorld(), com.neuronrobotics.bowlerstudio.physics.MobileBasePhysicsManager.PhysicsGravityScalar, and com.neuronrobotics.bowlerstudio.physics.PhysicsCore.setGroundShape().
Member Function Documentation
add()
void com.neuronrobotics.bowlerstudio.physics.PhysicsCore.add (IPhysicsManager manager)
Definition at line 224 of file PhysicsCore.java.
References com.neuronrobotics.bowlerstudio.physics.PhysicsCore.getDynamicsWorld(), com.neuronrobotics.bowlerstudio.physics.IPhysicsManager.getFallRigidBody(), and com.neuronrobotics.bowlerstudio.physics.PhysicsCore.getPhysicsObjects().
Referenced by com.neuronrobotics.bowlerstudio.physics.MobileBasePhysicsManager.MobileBasePhysicsManager(), and com.neuronrobotics.bowlerstudio.physics.HingeCSGPhysicsManager.update().
clear()
void com.neuronrobotics.bowlerstudio.physics.PhysicsCore.clear ()
Definition at line 264 of file PhysicsCore.java.
References com.neuronrobotics.bowlerstudio.physics.PhysicsCore.getDynamicsWorld(), com.neuronrobotics.bowlerstudio.physics.PhysicsCore.getPhysicsObjects(), com.neuronrobotics.bowlerstudio.physics.PhysicsCore.msTime, com.neuronrobotics.bowlerstudio.physics.PhysicsCore.stopPhysicsThread(), and com.neuronrobotics.sdk.util.ThreadUtil.wait().
getAng_damping()
float com.neuronrobotics.bowlerstudio.physics.PhysicsCore.getAng_damping ()
Definition at line 302 of file PhysicsCore.java.
References com.neuronrobotics.bowlerstudio.physics.PhysicsCore.ang_damping.
getAngularSleepThreshhold()
float com.neuronrobotics.bowlerstudio.physics.PhysicsCore.getAngularSleepThreshhold ()
Definition at line 310 of file PhysicsCore.java.
References com.neuronrobotics.bowlerstudio.physics.PhysicsCore.angularSleepThreshhold.
getBroadphase()
BroadphaseInterface com.neuronrobotics.bowlerstudio.physics.PhysicsCore.getBroadphase ()
Definition at line 64 of file PhysicsCore.java.
References com.neuronrobotics.bowlerstudio.physics.PhysicsCore.broadphase.
getCollisionConfiguration()
DefaultCollisionConfiguration com.neuronrobotics.bowlerstudio.physics.PhysicsCore.getCollisionConfiguration ()
Definition at line 72 of file PhysicsCore.java.
References com.neuronrobotics.bowlerstudio.physics.PhysicsCore.collisionConfiguration.
getCsgFromEngine()
ArrayList<CSG> com.neuronrobotics.bowlerstudio.physics.PhysicsCore.getCsgFromEngine ()
Definition at line 183 of file PhysicsCore.java.
References com.neuronrobotics.bowlerstudio.physics.PhysicsCore.getPhysicsObjects().
Referenced by com.neuronrobotics.bowlerstudio.physics.PhysicsEngine.getCsgFromEngine().
getDeactivationTime()
float com.neuronrobotics.bowlerstudio.physics.PhysicsCore.getDeactivationTime ()
Definition at line 290 of file PhysicsCore.java.
References com.neuronrobotics.bowlerstudio.physics.PhysicsCore.deactivationTime.
getDispatcher()
CollisionDispatcher com.neuronrobotics.bowlerstudio.physics.PhysicsCore.getDispatcher ()
Definition at line 80 of file PhysicsCore.java.
References com.neuronrobotics.bowlerstudio.physics.PhysicsCore.dispatcher.
getDynamicsWorld()
DiscreteDynamicsWorld com.neuronrobotics.bowlerstudio.physics.PhysicsCore.getDynamicsWorld ()
Definition at line 96 of file PhysicsCore.java.
References com.neuronrobotics.bowlerstudio.physics.PhysicsCore.dynamicsWorld.
Referenced by com.neuronrobotics.bowlerstudio.physics.PhysicsCore.add(), com.neuronrobotics.bowlerstudio.physics.PhysicsCore.clear(), com.neuronrobotics.bowlerstudio.physics.MobileBasePhysicsManager.MobileBasePhysicsManager(), com.neuronrobotics.bowlerstudio.physics.PhysicsCore.PhysicsCore(), com.neuronrobotics.bowlerstudio.physics.PhysicsCore.remove(), com.neuronrobotics.bowlerstudio.physics.PhysicsCore.setGroundShape(), com.neuronrobotics.bowlerstudio.physics.PhysicsCore.step(), and com.neuronrobotics.bowlerstudio.physics.VehicleCSGPhysicsManager.VehicleCSGPhysicsManager().
getGroundShape()
CollisionShape com.neuronrobotics.bowlerstudio.physics.PhysicsCore.getGroundShape ()
Definition at line 104 of file PhysicsCore.java.
References com.neuronrobotics.bowlerstudio.physics.PhysicsCore.groundShape.
getLin_damping()
float com.neuronrobotics.bowlerstudio.physics.PhysicsCore.getLin_damping ()
Definition at line 298 of file PhysicsCore.java.
References com.neuronrobotics.bowlerstudio.physics.PhysicsCore.lin_damping.
getLinearSleepThreshhold()
float com.neuronrobotics.bowlerstudio.physics.PhysicsCore.getLinearSleepThreshhold ()
Definition at line 306 of file PhysicsCore.java.
References com.neuronrobotics.bowlerstudio.physics.PhysicsCore.linearSleepThreshhold.
getPhysicsObjects()
ArrayList<IPhysicsManager> com.neuronrobotics.bowlerstudio.physics.PhysicsCore.getPhysicsObjects ()
Definition at line 126 of file PhysicsCore.java.
References com.neuronrobotics.bowlerstudio.physics.PhysicsCore.objects.
Referenced by com.neuronrobotics.bowlerstudio.physics.PhysicsCore.add(), com.neuronrobotics.bowlerstudio.physics.PhysicsCore.clear(), com.neuronrobotics.bowlerstudio.physics.PhysicsCore.getCsgFromEngine(), com.neuronrobotics.bowlerstudio.physics.PhysicsCore.remove(), com.neuronrobotics.bowlerstudio.physics.PhysicsCore.setDamping(), com.neuronrobotics.bowlerstudio.physics.PhysicsCore.setDeactivationTime(), com.neuronrobotics.bowlerstudio.physics.PhysicsCore.setSleepingThresholds(), and com.neuronrobotics.bowlerstudio.physics.PhysicsCore.step().
getSimulationSubSteps()
int com.neuronrobotics.bowlerstudio.physics.PhysicsCore.getSimulationSubSteps ()
Definition at line 286 of file PhysicsCore.java.
References com.neuronrobotics.bowlerstudio.physics.PhysicsCore.simulationSubSteps.
Referenced by com.neuronrobotics.bowlerstudio.physics.PhysicsCore.step().
getSolver()
SequentialImpulseConstraintSolver com.neuronrobotics.bowlerstudio.physics.PhysicsCore.getSolver ()
Definition at line 88 of file PhysicsCore.java.
References com.neuronrobotics.bowlerstudio.physics.PhysicsCore.solver.
remove()
void com.neuronrobotics.bowlerstudio.physics.PhysicsCore.remove (IPhysicsManager manager)
Definition at line 244 of file PhysicsCore.java.
References com.neuronrobotics.bowlerstudio.physics.PhysicsCore.getDynamicsWorld(), and com.neuronrobotics.bowlerstudio.physics.PhysicsCore.getPhysicsObjects().
Referenced by com.neuronrobotics.bowlerstudio.physics.HingeCSGPhysicsManager.update().
setBroadphase()
void com.neuronrobotics.bowlerstudio.physics.PhysicsCore.setBroadphase (BroadphaseInterface broadphase)
Definition at line 68 of file PhysicsCore.java.
References com.neuronrobotics.bowlerstudio.physics.PhysicsCore.broadphase.
setCollisionConfiguration()
void com.neuronrobotics.bowlerstudio.physics.PhysicsCore.setCollisionConfiguration (DefaultCollisionConfiguration collisionConfiguration)
Definition at line 76 of file PhysicsCore.java.
References com.neuronrobotics.bowlerstudio.physics.PhysicsCore.collisionConfiguration.
setDamping()
void com.neuronrobotics.bowlerstudio.physics.PhysicsCore.setDamping (float lin_damping, float ang_damping)
Definition at line 130 of file PhysicsCore.java.
References com.neuronrobotics.bowlerstudio.physics.PhysicsCore.ang_damping, com.neuronrobotics.bowlerstudio.physics.PhysicsCore.getPhysicsObjects(), and com.neuronrobotics.bowlerstudio.physics.PhysicsCore.lin_damping.
setDeactivationTime()
void com.neuronrobotics.bowlerstudio.physics.PhysicsCore.setDeactivationTime (float deactivationTime)
Definition at line 146 of file PhysicsCore.java.
References com.neuronrobotics.bowlerstudio.physics.PhysicsCore.deactivationTime, and com.neuronrobotics.bowlerstudio.physics.PhysicsCore.getPhysicsObjects().
setDispatcher()
void com.neuronrobotics.bowlerstudio.physics.PhysicsCore.setDispatcher (CollisionDispatcher dispatcher)
Definition at line 84 of file PhysicsCore.java.
References com.neuronrobotics.bowlerstudio.physics.PhysicsCore.dispatcher.
setDynamicsWorld()
void com.neuronrobotics.bowlerstudio.physics.PhysicsCore.setDynamicsWorld (DiscreteDynamicsWorld dynamicsWorld)
Definition at line 100 of file PhysicsCore.java.
References com.neuronrobotics.bowlerstudio.physics.PhysicsCore.dynamicsWorld.
setGroundShape()
void com.neuronrobotics.bowlerstudio.physics.PhysicsCore.setGroundShape (CollisionShape cs)
Definition at line 108 of file PhysicsCore.java.
References com.neuronrobotics.bowlerstudio.physics.PhysicsCore.dynamicsWorld, com.neuronrobotics.bowlerstudio.physics.PhysicsCore.getDynamicsWorld(), com.neuronrobotics.bowlerstudio.physics.PhysicsCore.groundRigidBody, and com.neuronrobotics.bowlerstudio.physics.PhysicsCore.groundShape.
Referenced by com.neuronrobotics.bowlerstudio.physics.PhysicsCore.PhysicsCore().
setObjects()
void com.neuronrobotics.bowlerstudio.physics.PhysicsCore.setObjects (ArrayList< IPhysicsManager > objects)
Definition at line 153 of file PhysicsCore.java.
References com.neuronrobotics.bowlerstudio.physics.PhysicsCore.objects.
setSimulationSubSteps()
void com.neuronrobotics.bowlerstudio.physics.PhysicsCore.setSimulationSubSteps (int simpulationSubSteps)
Definition at line 294 of file PhysicsCore.java.
setSleepingThresholds()
void com.neuronrobotics.bowlerstudio.physics.PhysicsCore.setSleepingThresholds (float linearSleepThreshhold, float angularSleepThreshhold)
Definition at line 138 of file PhysicsCore.java.
References com.neuronrobotics.bowlerstudio.physics.PhysicsCore.angularSleepThreshhold, com.neuronrobotics.bowlerstudio.physics.PhysicsCore.getPhysicsObjects(), and com.neuronrobotics.bowlerstudio.physics.PhysicsCore.linearSleepThreshhold.
setSolver()
void com.neuronrobotics.bowlerstudio.physics.PhysicsCore.setSolver (SequentialImpulseConstraintSolver solver)
Definition at line 92 of file PhysicsCore.java.
References com.neuronrobotics.bowlerstudio.physics.PhysicsCore.solver.
startPhysicsThread()
void com.neuronrobotics.bowlerstudio.physics.PhysicsCore.startPhysicsThread (int ms)
Definition at line 157 of file PhysicsCore.java.
References com.neuronrobotics.bowlerstudio.physics.PhysicsCore.msTime, com.neuronrobotics.bowlerstudio.physics.PhysicsCore.physicsThread, com.neuronrobotics.bowlerstudio.physics.PhysicsCore.runEngine, com.neuronrobotics.bowlerstudio.physics.PhysicsCore.stepMs(), and com.neuronrobotics.sdk.util.ThreadUtil.wait().
step()
void com.neuronrobotics.bowlerstudio.physics.PhysicsCore.step (float timeStep)
Definition at line 198 of file PhysicsCore.java.
References com.neuronrobotics.bowlerstudio.physics.TransformFactory.bulletToAffine(), com.neuronrobotics.bowlerstudio.physics.PhysicsCore.getDynamicsWorld(), com.neuronrobotics.bowlerstudio.physics.PhysicsCore.getPhysicsObjects(), and com.neuronrobotics.bowlerstudio.physics.PhysicsCore.getSimulationSubSteps().
Referenced by com.neuronrobotics.bowlerstudio.physics.PhysicsCore.stepMs().
stepMs()
void com.neuronrobotics.bowlerstudio.physics.PhysicsCore.stepMs (double timeStep)
Definition at line 220 of file PhysicsCore.java.
References com.neuronrobotics.bowlerstudio.physics.PhysicsCore.step().
Referenced by com.neuronrobotics.bowlerstudio.physics.PhysicsCore.startPhysicsThread().
stopPhysicsThread()
void com.neuronrobotics.bowlerstudio.physics.PhysicsCore.stopPhysicsThread ()
Definition at line 193 of file PhysicsCore.java.
References com.neuronrobotics.bowlerstudio.physics.PhysicsCore.physicsThread, and com.neuronrobotics.bowlerstudio.physics.PhysicsCore.runEngine.
Referenced by com.neuronrobotics.bowlerstudio.physics.PhysicsCore.clear().
Member Data Documentation
ang_damping
float com.neuronrobotics.bowlerstudio.physics.PhysicsCore.ang_damping private
Definition at line 51 of file PhysicsCore.java.
Referenced by com.neuronrobotics.bowlerstudio.physics.PhysicsCore.getAng_damping(), and com.neuronrobotics.bowlerstudio.physics.PhysicsCore.setDamping().
angularSleepThreshhold
float com.neuronrobotics.bowlerstudio.physics.PhysicsCore.angularSleepThreshhold private
Definition at line 53 of file PhysicsCore.java.
Referenced by com.neuronrobotics.bowlerstudio.physics.PhysicsCore.getAngularSleepThreshhold(), and com.neuronrobotics.bowlerstudio.physics.PhysicsCore.setSleepingThresholds().
broadphase
BroadphaseInterface com.neuronrobotics.bowlerstudio.physics.PhysicsCore.broadphase = new DbvtBroadphase() private
Definition at line 30 of file PhysicsCore.java.
Referenced by com.neuronrobotics.bowlerstudio.physics.PhysicsCore.getBroadphase(), and com.neuronrobotics.bowlerstudio.physics.PhysicsCore.setBroadphase().
collisionConfiguration
DefaultCollisionConfiguration com.neuronrobotics.bowlerstudio.physics.PhysicsCore.collisionConfiguration = new DefaultCollisionConfiguration() private
Definition at line 31 of file PhysicsCore.java.
Referenced by com.neuronrobotics.bowlerstudio.physics.PhysicsCore.getCollisionConfiguration(), and com.neuronrobotics.bowlerstudio.physics.PhysicsCore.setCollisionConfiguration().
deactivationTime
float com.neuronrobotics.bowlerstudio.physics.PhysicsCore.deactivationTime private
Definition at line 54 of file PhysicsCore.java.
Referenced by com.neuronrobotics.bowlerstudio.physics.PhysicsCore.getDeactivationTime(), and com.neuronrobotics.bowlerstudio.physics.PhysicsCore.setDeactivationTime().
dispatcher
CollisionDispatcher com.neuronrobotics.bowlerstudio.physics.PhysicsCore.dispatcher = new CollisionDispatcher(collisionConfiguration) private
Definition at line 32 of file PhysicsCore.java.
Referenced by com.neuronrobotics.bowlerstudio.physics.PhysicsCore.getDispatcher(), and com.neuronrobotics.bowlerstudio.physics.PhysicsCore.setDispatcher().
dynamicsWorld
DiscreteDynamicsWorld com.neuronrobotics.bowlerstudio.physics.PhysicsCore.dynamicsWorld private
Initial value:
= new DiscreteDynamicsWorld(dispatcher, broadphase,
      solver,
      collisionConfiguration)
Definition at line 36 of file PhysicsCore.java.
Referenced by com.neuronrobotics.bowlerstudio.physics.PhysicsCore.getDynamicsWorld(), com.neuronrobotics.bowlerstudio.physics.PhysicsCore.setDynamicsWorld(), and com.neuronrobotics.bowlerstudio.physics.PhysicsCore.setGroundShape().
groundRigidBody
RigidBody com.neuronrobotics.bowlerstudio.physics.PhysicsCore.groundRigidBody private
Definition at line 43 of file PhysicsCore.java.
Referenced by com.neuronrobotics.bowlerstudio.physics.PhysicsCore.setGroundShape().
groundShape
CollisionShape com.neuronrobotics.bowlerstudio.physics.PhysicsCore.groundShape = null private
Definition at line 40 of file PhysicsCore.java.
Referenced by com.neuronrobotics.bowlerstudio.physics.PhysicsCore.getGroundShape(), and com.neuronrobotics.bowlerstudio.physics.PhysicsCore.setGroundShape().
lin_damping
float com.neuronrobotics.bowlerstudio.physics.PhysicsCore.lin_damping private
Definition at line 50 of file PhysicsCore.java.
Referenced by com.neuronrobotics.bowlerstudio.physics.PhysicsCore.getLin_damping(), and com.neuronrobotics.bowlerstudio.physics.PhysicsCore.setDamping().
linearSleepThreshhold
float com.neuronrobotics.bowlerstudio.physics.PhysicsCore.linearSleepThreshhold private
Definition at line 52 of file PhysicsCore.java.
Referenced by com.neuronrobotics.bowlerstudio.physics.PhysicsCore.getLinearSleepThreshhold(), and com.neuronrobotics.bowlerstudio.physics.PhysicsCore.setSleepingThresholds().
msTime
int com.neuronrobotics.bowlerstudio.physics.PhysicsCore.msTime = 16 private
Definition at line 46 of file PhysicsCore.java.
Referenced by com.neuronrobotics.bowlerstudio.physics.PhysicsCore.clear(), and com.neuronrobotics.bowlerstudio.physics.PhysicsCore.startPhysicsThread().
objects
ArrayList<IPhysicsManager> com.neuronrobotics.bowlerstudio.physics.PhysicsCore.objects = new ArrayList<>() private
Definition at line 42 of file PhysicsCore.java.
Referenced by com.neuronrobotics.bowlerstudio.physics.PhysicsCore.getPhysicsObjects(), and com.neuronrobotics.bowlerstudio.physics.PhysicsCore.setObjects().
physicsThread
Thread com.neuronrobotics.bowlerstudio.physics.PhysicsCore.physicsThread = null private
Definition at line 48 of file PhysicsCore.java.
Referenced by com.neuronrobotics.bowlerstudio.physics.PhysicsCore.startPhysicsThread(), and com.neuronrobotics.bowlerstudio.physics.PhysicsCore.stopPhysicsThread().
runEngine
boolean com.neuronrobotics.bowlerstudio.physics.PhysicsCore.runEngine = false private
Definition at line 45 of file PhysicsCore.java.
Referenced by com.neuronrobotics.bowlerstudio.physics.PhysicsCore.startPhysicsThread(), and com.neuronrobotics.bowlerstudio.physics.PhysicsCore.stopPhysicsThread().
simulationSubSteps
int com.neuronrobotics.bowlerstudio.physics.PhysicsCore.simulationSubSteps = 5 private
Definition at line 49 of file PhysicsCore.java.
Referenced by com.neuronrobotics.bowlerstudio.physics.PhysicsCore.getSimulationSubSteps().
solver
SequentialImpulseConstraintSolver com.neuronrobotics.bowlerstudio.physics.PhysicsCore.solver = new SequentialImpulseConstraintSolver() private
Definition at line 34 of file PhysicsCore.java.
Referenced by com.neuronrobotics.bowlerstudio.physics.PhysicsCore.getSolver(), and com.neuronrobotics.bowlerstudio.physics.PhysicsCore.setSolver().
The documentation for this class was generated from the following file:
src/main/java/com/neuronrobotics/bowlerstudio/physics/PhysicsCore.java