BowlerKernel: com.neuronrobotics.sdk.common.device.server.bcs.rpc.BcsRpcNamespaceImp Class Reference
com.neuronrobotics.sdk.common.device.server.bcs.rpc.BcsRpcNamespaceImp Class Reference
Public Member Functions
BcsRpcNamespaceImp (BowlerAbstractServer s, MACAddress mac)
Public Member Functions inherited from com.neuronrobotics.sdk.common.device.server.BowlerAbstractDeviceServerNamespace
BowlerAbstractDeviceServerNamespace (MACAddress addr, String namespaceString)
boolean checkRpc (BowlerDatagram data)
String getNamespace ()
ArrayList< RpcEncapsulation > getRpcList ()
void addRpc (RpcEncapsulation newRpc)
MACAddress getAddress ()
BowlerDatagram process (BowlerDatagram data)
int getNamespaceIndex ()
void setNamespaceIndex (int ns)
Private Attributes
BowlerAbstractServer server
Additional Inherited Members
Protected Attributes inherited from com.neuronrobotics.sdk.common.device.server.BowlerAbstractDeviceServerNamespace
ArrayList< RpcEncapsulation > rpc =new ArrayList<RpcEncapsulation>()
final String ns
Detailed Description
The Class BcsRpcNamespaceImp.
Definition at line 16 of file BcsRpcNamespaceImp.java.
Constructor & Destructor Documentation
BcsRpcNamespaceImp()
com.neuronrobotics.sdk.common.device.server.bcs.rpc.BcsRpcNamespaceImp.BcsRpcNamespaceImp (BowlerAbstractServer s, MACAddress mac)
Instantiates a new bcs rpc namespace imp.
Parameters
s the s
mac the mac
Definition at line 27 of file BcsRpcNamespaceImp.java.
References com.neuronrobotics.sdk.common.BowlerMethod.GET, com.neuronrobotics.sdk.common.RpcEncapsulation.getDownstreamArguments(), com.neuronrobotics.sdk.common.RpcEncapsulation.getDownstreamMethod(), com.neuronrobotics.sdk.common.device.server.BowlerAbstractDeviceServerNamespace.getNamespace(), com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.getNamespaces(), com.neuronrobotics.sdk.common.RpcEncapsulation.getUpstreamArguments(), com.neuronrobotics.sdk.common.RpcEncapsulation.getUpStreamMethod(), com.neuronrobotics.sdk.common.BowlerMethod.getValue(), com.neuronrobotics.sdk.common.BowlerDataType.I08, com.neuronrobotics.sdk.common.device.server.BowlerAbstractDeviceServerNamespace.mac, com.neuronrobotics.sdk.common.BowlerMethod.POST, com.neuronrobotics.sdk.common.device.server.BowlerAbstractDeviceServerNamespace.process(), com.neuronrobotics.sdk.common.device.server.BowlerAbstractDeviceServerNamespace.rpc, com.neuronrobotics.sdk.common.device.server.bcs.rpc.BcsRpcNamespaceImp.server, and com.neuronrobotics.sdk.common.BowlerDataType.STR.
Member Data Documentation
server
BowlerAbstractServer com.neuronrobotics.sdk.common.device.server.bcs.rpc.BcsRpcNamespaceImp.server private
The server.
Definition at line 19 of file BcsRpcNamespaceImp.java.
Referenced by com.neuronrobotics.sdk.common.device.server.bcs.rpc.BcsRpcNamespaceImp.BcsRpcNamespaceImp().
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/common/device/server/bcs/rpc/BcsRpcNamespaceImp.java