BowlerKernel: com.neuronrobotics.bowlerstudio.physics.TransformFactory Class Reference
com.neuronrobotics.bowlerstudio.physics.TransformFactory Class Reference
Static Public Member Functions
static Affine newAffine (double x, double y, double z)
static Affine nrToAffine (TransformNR input)
static TransformNR affineToNr (Affine input)
static TransformNR affineToNr (TransformNR outputValue, Affine rotations)
static Affine nrToAffine (TransformNR input, Affine rotations)
static void nrToBullet (TransformNR nr, com.bulletphysics.linearmath.Transform bullet)
static TransformNR bulletToNr (com.bulletphysics.linearmath.Transform bullet)
static void bulletToAffine (Affine affine, com.bulletphysics.linearmath.Transform bullet)
static void affineToBullet (Affine affine, com.bulletphysics.linearmath.Transform bullet)
static eu.mihosoft.vrl.v3d.Transform nrToCSG (TransformNR nr)
static TransformNR scale (TransformNR incoming, double scale)
static TransformNR csgToNR (eu.mihosoft.vrl.v3d.Transform csg)
Detailed Description
A factory for creating Transform objects.
Definition at line 20 of file TransformFactory.java.
Member Function Documentation
affineToBullet()
static void com.neuronrobotics.bowlerstudio.physics.TransformFactory.affineToBullet (Affine affine, com.bulletphysics.linearmath.Transform bullet) static
Definition at line 154 of file TransformFactory.java.
affineToNr() [1/2]
static TransformNR com.neuronrobotics.bowlerstudio.physics.TransformFactory.affineToNr (Affine input) static
Gets the transform.
Parameters
input the input
Returns
the transform
Definition at line 51 of file TransformFactory.java.
affineToNr() [2/2]
static TransformNR com.neuronrobotics.bowlerstudio.physics.TransformFactory.affineToNr (TransformNR outputValue, Affine rotations) static
Gets the transform.
Parameters
outputValue the input
rotations the rotations
Returns
the transform
Definition at line 62 of file TransformFactory.java.
References com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getRotationMatrixArray(), and com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.set().
bulletToAffine()
static void com.neuronrobotics.bowlerstudio.physics.TransformFactory.bulletToAffine (Affine affine, com.bulletphysics.linearmath.Transform bullet) static
Definition at line 129 of file TransformFactory.java.
Referenced by com.neuronrobotics.bowlerstudio.physics.MobileBasePhysicsManager.MobileBasePhysicsManager(), and com.neuronrobotics.bowlerstudio.physics.PhysicsCore.step().
bulletToNr()
static TransformNR com.neuronrobotics.bowlerstudio.physics.TransformFactory.bulletToNr (com.bulletphysics.linearmath.Transform bullet) static
Definition at line 123 of file TransformFactory.java.
Referenced by com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager.loadCSGToPoints(), com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager.setup(), and com.neuronrobotics.bowlerstudio.physics.WheelCSGPhysicsManager.update().
csgToNR()
static TransformNR com.neuronrobotics.bowlerstudio.physics.TransformFactory.csgToNR (eu.mihosoft.vrl.v3d.Transform csg) static
Definition at line 182 of file TransformFactory.java.
Referenced by com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.update().
newAffine()
static Affine com.neuronrobotics.bowlerstudio.physics.TransformFactory.newAffine (double x, double y, double z) static
Gets the transform.
Parameters
x the x
y the y
z the z
Returns
the transform
Definition at line 30 of file TransformFactory.java.
nrToAffine() [1/2]
static Affine com.neuronrobotics.bowlerstudio.physics.TransformFactory.nrToAffine (TransformNR input) static
Gets the transform.
Parameters
input the input
Returns
the transform
Definition at line 40 of file TransformFactory.java.
Referenced by com.neuronrobotics.bowlerkernel.Bezier3d.manipulation.manipulation(), com.neuronrobotics.bowlerstudio.physics.MobileBasePhysicsManager.MobileBasePhysicsManager(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.run(), com.neuronrobotics.bowlerkernel.Bezier3d.manipulation.setGlobal(), com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.update(), and com.neuronrobotics.bowlerkernel.Bezier3d.BezierEditor.updateLines().
nrToAffine() [2/2]
static Affine com.neuronrobotics.bowlerstudio.physics.TransformFactory.nrToAffine (TransformNR input, Affine rotations) static
Gets the transform.
Parameters
input the input
rotations the rotations
Returns
the transform
Definition at line 87 of file TransformFactory.java.
References com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getRotationMatrixArray(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getX(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getY(), and com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getZ().
nrToBullet()
static void com.neuronrobotics.bowlerstudio.physics.TransformFactory.nrToBullet (TransformNR nr, com.bulletphysics.linearmath.Transform bullet) static
Definition at line 115 of file TransformFactory.java.
References com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getRotation(), com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.getRotationMatrix2QuaturnionW(), com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.getRotationMatrix2QuaturnionX(), com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.getRotationMatrix2QuaturnionY(), com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.getRotationMatrix2QuaturnionZ(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getX(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getY(), and com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getZ().
Referenced by com.neuronrobotics.bowlerstudio.physics.MobileBasePhysicsManager.getUpdater(), com.neuronrobotics.bowlerstudio.physics.CSGPhysicsManager.loadCSGToPoints(), com.neuronrobotics.bowlerstudio.physics.MobileBasePhysicsManager.MobileBasePhysicsManager(), and com.neuronrobotics.bowlerstudio.physics.WheelCSGPhysicsManager.update().
nrToCSG()
static eu.mihosoft.vrl.v3d.Transform com.neuronrobotics.bowlerstudio.physics.TransformFactory.nrToCSG (TransformNR nr) static
Definition at line 159 of file TransformFactory.java.
References com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getRotation(), com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.getRotationMatrix2QuaturnionW(), com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.getRotationMatrix2QuaturnionX(), com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.getRotationMatrix2QuaturnionY(), com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.getRotationMatrix2QuaturnionZ(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getX(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getY(), and com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getZ().
Referenced by com.neuronrobotics.bowlerstudio.vitamins.VitaminBomManager.get(), com.neuronrobotics.bowlerstudio.printbed.PrintBedManager.makePrintBeds(), and com.neuronrobotics.bowlerstudio.physics.MobileBasePhysicsManager.MobileBasePhysicsManager().
scale()
static TransformNR com.neuronrobotics.bowlerstudio.physics.TransformFactory.scale (TransformNR incoming, double scale) static
Definition at line 175 of file TransformFactory.java.
References com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getRotation(), com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.getRotationAzimuth(), com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.getRotationElevation(), com.neuronrobotics.sdk.addons.kinematics.math.RotationNR.getRotationTilt(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getX(), com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getY(), and com.neuronrobotics.sdk.addons.kinematics.math.TransformNR.getZ().
The documentation for this class was generated from the following file:
src/main/java/com/neuronrobotics/bowlerstudio/physics/TransformFactory.java