BowlerKernel: com.neuronrobotics.replicator.driver.delta.DeltaJointAngles Class Reference
com.neuronrobotics.replicator.driver.delta.DeltaJointAngles Class Reference
Public Member Functions
DeltaJointAngles (double theta1, double theta2, double theta3)
double getTheta1 ()
double getTheta2 ()
double getTheta3 ()
Private Member Functions
void setTheta1 (double theta1)
void setTheta2 (double theta2)
void setTheta3 (double theta3)
Private Attributes
double theta1
Detailed Description
The Class DeltaJointAngles.
Definition at line 7 of file DeltaJointAngles.java.
Constructor & Destructor Documentation
DeltaJointAngles()
com.neuronrobotics.replicator.driver.delta.DeltaJointAngles.DeltaJointAngles (double theta1, double theta2, double theta3)
All angles in radians.
Parameters
theta1 the theta1
theta2 the theta2
theta3 the theta3
Definition at line 19 of file DeltaJointAngles.java.
References com.neuronrobotics.replicator.driver.delta.DeltaJointAngles.setTheta1(), com.neuronrobotics.replicator.driver.delta.DeltaJointAngles.setTheta2(), com.neuronrobotics.replicator.driver.delta.DeltaJointAngles.setTheta3(), and com.neuronrobotics.replicator.driver.delta.DeltaJointAngles.theta1.
Member Function Documentation
getTheta1()
double com.neuronrobotics.replicator.driver.delta.DeltaJointAngles.getTheta1 ()
Gets the theta1.
Returns
the theta1
Definition at line 39 of file DeltaJointAngles.java.
References com.neuronrobotics.replicator.driver.delta.DeltaJointAngles.theta1.
getTheta2()
double com.neuronrobotics.replicator.driver.delta.DeltaJointAngles.getTheta2 ()
Gets the theta2.
Returns
the theta2
Definition at line 57 of file DeltaJointAngles.java.
getTheta3()
double com.neuronrobotics.replicator.driver.delta.DeltaJointAngles.getTheta3 ()
Gets the theta3.
Returns
the theta3
Definition at line 75 of file DeltaJointAngles.java.
setTheta1()
void com.neuronrobotics.replicator.driver.delta.DeltaJointAngles.setTheta1 (double theta1) private
Sets the theta1.
Parameters
theta1 the new theta1
Definition at line 30 of file DeltaJointAngles.java.
References com.neuronrobotics.replicator.driver.delta.DeltaJointAngles.theta1.
Referenced by com.neuronrobotics.replicator.driver.delta.DeltaJointAngles.DeltaJointAngles().
setTheta2()
void com.neuronrobotics.replicator.driver.delta.DeltaJointAngles.setTheta2 (double theta2) private
Sets the theta2.
Parameters
theta2 the new theta2
Definition at line 48 of file DeltaJointAngles.java.
Referenced by com.neuronrobotics.replicator.driver.delta.DeltaJointAngles.DeltaJointAngles().
setTheta3()
void com.neuronrobotics.replicator.driver.delta.DeltaJointAngles.setTheta3 (double theta3) private
Sets the theta3.
Parameters
theta3 the new theta3
Definition at line 66 of file DeltaJointAngles.java.
Referenced by com.neuronrobotics.replicator.driver.delta.DeltaJointAngles.DeltaJointAngles().
Member Data Documentation
theta1
double com.neuronrobotics.replicator.driver.delta.DeltaJointAngles.theta1 private
The theta3.
Definition at line 10 of file DeltaJointAngles.java.
Referenced by com.neuronrobotics.replicator.driver.delta.DeltaJointAngles.DeltaJointAngles(), com.neuronrobotics.replicator.driver.delta.DeltaJointAngles.getTheta1(), and com.neuronrobotics.replicator.driver.delta.DeltaJointAngles.setTheta1().
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/replicator/driver/delta/DeltaJointAngles.java