BowlerKernel: com.piro.bezier.BezierPath Class Reference
com.piro.bezier.BezierPath Class Reference
Public Member Functions
BezierPath ()
BezierPath (String path)
void parsePathString (String d)
Vector3d eval (float interp)
ArrayList< Vector3d > evaluate ()
Protected Member Functions
void parsePathList (String list)
Static Protected Member Functions
static float nextFloat (LinkedList< String > l)
Private Attributes
ArrayList< Vector3d > pointList = new ArrayList<Vector3d>()
Detailed Description
Definition at line 11 of file BezierPath.java.
Constructor & Destructor Documentation
BezierPath() [1/2]
com.piro.bezier.BezierPath.BezierPath ()
Creates a new instance of Animate
Definition at line 21 of file BezierPath.java.
BezierPath() [2/2]
com.piro.bezier.BezierPath.BezierPath (String path)
Creates a new instance of Animate
Definition at line 25 of file BezierPath.java.
References com.piro.bezier.BezierPath.parsePathString().
Member Function Documentation
eval()
Vector3d com.piro.bezier.BezierPath.eval (float interp)
Evaluates this animation element for the passed interpolation time. Interp must be on [0..1].
Definition at line 179 of file BezierPath.java.
References com.piro.bezier.Bezier.getLength().
Referenced by eu.mihosoft.vrl.v3d.Extrude.bezierToTransforms(), and eu.mihosoft.vrl.v3d.Extrude.moveBezier().
evaluate()
ArrayList<Vector3d> com.piro.bezier.BezierPath.evaluate ()
Evaluates this animation element for the passed interpolation time. Interp must be on [0..1].
Definition at line 207 of file BezierPath.java.
References com.piro.bezier.BezierPath.pointList.
Referenced by eu.mihosoft.vrl.v3d.svg.SVGLoad.loadSingle().
nextFloat()
static float com.piro.bezier.BezierPath.nextFloat (LinkedList< String > l) static protected
Definition at line 170 of file BezierPath.java.
Referenced by com.piro.bezier.BezierPath.parsePathList().
parsePathList()
void com.piro.bezier.BezierPath.parsePathList (String list) protected
Definition at line 36 of file BezierPath.java.
References com.piro.bezier.BezierListProducer.closePath(), com.piro.bezier.BezierListProducer.curvetoCubicAbs(), com.piro.bezier.BezierListProducer.curvetoCubicRel(), com.piro.bezier.BezierListProducer.curvetoCubicSmoothAbs(), com.piro.bezier.BezierListProducer.curvetoCubicSmoothRel(), com.piro.bezier.BezierListProducer.curvetoQuadraticAbs(), com.piro.bezier.BezierListProducer.curvetoQuadraticSmoothAbs(), com.piro.bezier.BezierListProducer.curvetoQuadraticSmoothRel(), com.piro.bezier.BezierListProducer.linetoAbs(), com.piro.bezier.BezierListProducer.linetoHorizontalAbs(), com.piro.bezier.BezierListProducer.linetoHorizontalRel(), com.piro.bezier.BezierListProducer.linetoRel(), com.piro.bezier.BezierListProducer.linetoVerticalAbs(), com.piro.bezier.BezierListProducer.movetoAbs(), com.piro.bezier.BezierListProducer.movetoRel(), com.piro.bezier.BezierPath.nextFloat(), and com.piro.bezier.BezierPath.pointList.
Referenced by com.piro.bezier.BezierPath.parsePathString().
parsePathString()
void com.piro.bezier.BezierPath.parsePathString (String d)
Definition at line 29 of file BezierPath.java.
References com.piro.bezier.BezierPath.parsePathList().
Referenced by com.piro.bezier.BezierPath.BezierPath(), eu.mihosoft.vrl.v3d.Extrude.bezierToTransforms(), eu.mihosoft.vrl.v3d.svg.SVGLoad.loadSingle(), eu.mihosoft.vrl.v3d.Extrude.moveBezier(), and eu.mihosoft.vrl.v3d.Extrude.pathToTransforms().
Member Data Documentation
pointList
ArrayList<Vector3d> com.piro.bezier.BezierPath.pointList = new ArrayList<Vector3d>() private
Definition at line 17 of file BezierPath.java.
Referenced by com.piro.bezier.BezierPath.evaluate(), and com.piro.bezier.BezierPath.parsePathList().
The documentation for this class was generated from the following file:
JCSG/src/main/java/com/piro/bezier/BezierPath.java