BowlerKernel: com.neuronrobotics.bowlerkernel.BowlerKernelBuildInfo Class Reference
com.neuronrobotics.bowlerkernel.BowlerKernelBuildInfo Class Reference
Static Public Member Functions
static String getVersion ()
static int getProtocolVersion ()
static int getSDKVersion ()
static int getBuildVersion ()
static int[] getBuildInfo ()
static String getBuildDate ()
static String getSDKVersionString ()
static boolean isOS64bit ()
static boolean isARM ()
static boolean isLinux ()
static boolean isWindows ()
static boolean isMac ()
static boolean isUnix ()
Static Private Member Functions
static String getTag (String target)
static InputStream getBuildPropertiesStream ()
Static Private Attributes
static final String NAME
Detailed Description
The Class SDKBuildInfo.
Definition at line 11 of file BowlerKernelBuildInfo.java.
Member Function Documentation
getBuildDate()
static String com.neuronrobotics.bowlerkernel.BowlerKernelBuildInfo.getBuildDate () static
Gets the builds the date.
Returns
the builds the date
Definition at line 111 of file BowlerKernelBuildInfo.java.
getBuildInfo()
static int [] com.neuronrobotics.bowlerkernel.BowlerKernelBuildInfo.getBuildInfo () static
Gets the builds the info.
Returns
the builds the info
Definition at line 65 of file BowlerKernelBuildInfo.java.
References com.neuronrobotics.bowlerkernel.BowlerKernelBuildInfo.getVersion().
Referenced by com.neuronrobotics.bowlerkernel.BowlerKernelBuildInfo.getBuildVersion(), com.neuronrobotics.bowlerkernel.BowlerKernelBuildInfo.getProtocolVersion(), and com.neuronrobotics.bowlerkernel.BowlerKernelBuildInfo.getSDKVersion().
getBuildPropertiesStream()
static InputStream com.neuronrobotics.bowlerkernel.BowlerKernelBuildInfo.getBuildPropertiesStream () static private
Gets the builds the properties stream.
Returns
the builds the properties stream
Definition at line 132 of file BowlerKernelBuildInfo.java.
Referenced by com.neuronrobotics.bowlerkernel.BowlerKernelBuildInfo.getTag().
getBuildVersion()
static int com.neuronrobotics.bowlerkernel.BowlerKernelBuildInfo.getBuildVersion () static
Gets the builds the version.
Returns
the builds the version
Definition at line 56 of file BowlerKernelBuildInfo.java.
References com.neuronrobotics.bowlerkernel.BowlerKernelBuildInfo.getBuildInfo().
getProtocolVersion()
static int com.neuronrobotics.bowlerkernel.BowlerKernelBuildInfo.getProtocolVersion () static
Gets the protocol version.
Returns
the protocol version
Definition at line 38 of file BowlerKernelBuildInfo.java.
References com.neuronrobotics.bowlerkernel.BowlerKernelBuildInfo.getBuildInfo().
getSDKVersion()
static int com.neuronrobotics.bowlerkernel.BowlerKernelBuildInfo.getSDKVersion () static
Gets the SDK version.
Returns
the SDK version
Definition at line 47 of file BowlerKernelBuildInfo.java.
References com.neuronrobotics.bowlerkernel.BowlerKernelBuildInfo.getBuildInfo().
getSDKVersionString()
static String com.neuronrobotics.bowlerkernel.BowlerKernelBuildInfo.getSDKVersionString () static
Gets the SDK version string.
Returns
the SDK version string
Definition at line 141 of file BowlerKernelBuildInfo.java.
References com.neuronrobotics.bowlerkernel.BowlerKernelBuildInfo.NAME.
getTag()
static String com.neuronrobotics.bowlerkernel.BowlerKernelBuildInfo.getTag (String target) static private
Gets the tag.
Parameters
target the target
Returns
the tag
Definition at line 81 of file BowlerKernelBuildInfo.java.
References com.neuronrobotics.bowlerkernel.BowlerKernelBuildInfo.getBuildPropertiesStream().
Referenced by com.neuronrobotics.bowlerkernel.BowlerKernelBuildInfo.getVersion().
getVersion()
static String com.neuronrobotics.bowlerkernel.BowlerKernelBuildInfo.getVersion () static
Gets the version.
Returns
the version
Definition at line 25 of file BowlerKernelBuildInfo.java.
References com.neuronrobotics.bowlerkernel.BowlerKernelBuildInfo.getTag().
Referenced by com.neuronrobotics.bowlerstudio.IssueReportingExceptionHandler.except(), and com.neuronrobotics.bowlerkernel.BowlerKernelBuildInfo.getBuildInfo().
isARM()
static boolean com.neuronrobotics.bowlerkernel.BowlerKernelBuildInfo.isARM () static
Checks if is arm.
Returns
true, if is arm
Definition at line 159 of file BowlerKernelBuildInfo.java.
isLinux()
static boolean com.neuronrobotics.bowlerkernel.BowlerKernelBuildInfo.isLinux () static
Checks if is linux.
Returns
true, if is linux
Definition at line 168 of file BowlerKernelBuildInfo.java.
Referenced by com.neuronrobotics.bowlerkernel.BowlerKernelBuildInfo.isUnix().
isMac()
static boolean com.neuronrobotics.bowlerkernel.BowlerKernelBuildInfo.isMac () static
Checks if is mac.
Returns
true, if is mac
Definition at line 186 of file BowlerKernelBuildInfo.java.
Referenced by com.neuronrobotics.bowlerkernel.BowlerKernelBuildInfo.isUnix().
isOS64bit()
static boolean com.neuronrobotics.bowlerkernel.BowlerKernelBuildInfo.isOS64bit () static
Checks if is o s64bit.
Returns
true, if is o s64bit
Definition at line 150 of file BowlerKernelBuildInfo.java.
isUnix()
static boolean com.neuronrobotics.bowlerkernel.BowlerKernelBuildInfo.isUnix () static
Checks if is unix.
Returns
true, if is unix
Definition at line 195 of file BowlerKernelBuildInfo.java.
References com.neuronrobotics.bowlerkernel.BowlerKernelBuildInfo.isLinux(), and com.neuronrobotics.bowlerkernel.BowlerKernelBuildInfo.isMac().
isWindows()
static boolean com.neuronrobotics.bowlerkernel.BowlerKernelBuildInfo.isWindows () static
Checks if is windows.
Returns
true, if is windows
Definition at line 177 of file BowlerKernelBuildInfo.java.
Member Data Documentation
NAME
final String com.neuronrobotics.bowlerkernel.BowlerKernelBuildInfo.NAME static private
Initial value:
= "CommonWealthRobotics SDK "
      + getProtocolVersion() + "." + getSDKVersion() + "("
      + getBuildVersion() + ")"
The Constant NAME.
Definition at line 16 of file BowlerKernelBuildInfo.java.
Referenced by com.neuronrobotics.bowlerkernel.BowlerKernelBuildInfo.getSDKVersionString().
The documentation for this class was generated from the following file:
src/main/java/com/neuronrobotics/bowlerkernel/BowlerKernelBuildInfo.java