BowlerKernel: com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler Class Reference
com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler Class Reference
Classes
class DyIOFlusher
class SchedulerThread
Public Member Functions
CoreScheduler (DyIO d, int loopTime, int duration)
CoreScheduler (DyIO d, File f)
void loadFromFile (File f)
void setAudioFile (File f)
int getTrackLength ()
void setLooping (boolean b)
boolean isPlaying ()
ServoOutputScheduleChannel addServoChannel (int dyIOChannel)
void removeServoOutputScheduleChannel (ServoOutputScheduleChannel s)
void setSequenceParams (int setpoint, long StartOffset)
void playStep ()
void play ()
void play (int setpoint, long StartOffset)
void pause ()
void addISchedulerListener (ISchedulerListener l)
void removeISchedulerListener (ISchedulerListener l)
void setCurrentTime (long time)
String getXml ()
void setOutputs (ArrayList< ServoOutputScheduleChannel > outputs)
ArrayList< ServoOutputScheduleChannel > getOutputs ()
File getAudioFile ()
void setDyIO (DyIO dyio)
DyIO getDyIO ()
void setLoopTime (int loopTime)
int getLoopTime ()
SchedulerThread getSt ()
void setSt (SchedulerThread st)
Private Member Functions
boolean isLooping ()
void callReset ()
void callPause ()
void callPlay ()
Static Private Member Functions
static String getTagValue (String sTag, Element eElement)
Private Attributes
int loopTime
long flushTime = 0
SchedulerThread st =null
SequencerWAV mp3
boolean loop = false
ArrayList< ISchedulerListener > listeners = new ArrayList< ISchedulerListener>()
ArrayList< ServoOutputScheduleChannel > outputs = new ArrayList< ServoOutputScheduleChannel>()
DyIO dyio
String filename =null
int msDuration =0
File audioFile =null
long StartOffset
Detailed Description
The Class CoreScheduler.
Author
hephaestus
Definition at line 29 of file CoreScheduler.java.
Constructor & Destructor Documentation
CoreScheduler() [1/2]
com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.CoreScheduler (DyIO d, int loopTime, int duration)
Instantiates a new core scheduler.
Parameters
d the d
loopTime the loop time
duration the duration
Definition at line 78 of file CoreScheduler.java.
References com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.msDuration, com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.setDyIO(), and com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.setLoopTime().
CoreScheduler() [2/2]
com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.CoreScheduler (DyIO d, File f)
Instantiates a new core scheduler.
Parameters
d the d
f the f
Definition at line 90 of file CoreScheduler.java.
References com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.loadFromFile(), and com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.setDyIO().
Member Function Documentation
addISchedulerListener()
void com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.addISchedulerListener (ISchedulerListener l)
Adds the i scheduler listener.
Parameters
l the l
Definition at line 347 of file CoreScheduler.java.
References com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.listeners.
Referenced by com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.addServoChannel().
addServoChannel()
ServoOutputScheduleChannel com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.addServoChannel (int dyIOChannel)
Adds the servo channel.
Parameters
dyIOChannel the dy io channel
Returns
the servo output schedule channel
Definition at line 261 of file CoreScheduler.java.
References com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.addISchedulerListener(), com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral.flush(), com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral.getChannel(), com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.getDyIO(), com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.getLoopTime(), com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.getOutputs(), com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.getTrackLength(), com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral.getValue(), com.neuronrobotics.sdk.dyio.DyIOChannel.setCachedMode(), com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.setIntervalTime(), and com.neuronrobotics.sdk.dyio.peripherals.ServoChannel.SetPosition().
Referenced by com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.loadFromFile().
callPause()
void com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.callPause () private
Call pause.
Definition at line 393 of file CoreScheduler.java.
References com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.listeners.
Referenced by com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.pause(), and com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.SchedulerThread.run().
callPlay()
void com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.callPlay () private
Call play.
Definition at line 402 of file CoreScheduler.java.
References com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.listeners.
Referenced by com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.play().
callReset()
void com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.callReset () private
Call reset.
Definition at line 384 of file CoreScheduler.java.
References com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.listeners.
Referenced by com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.SchedulerThread.run().
getAudioFile()
File com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.getAudioFile ()
Gets the audio file.
Returns
the audio file
Definition at line 660 of file CoreScheduler.java.
References com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.audioFile.
getDyIO()
DyIO com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.getDyIO ()
Gets the dy io.
Returns
the dy io
Definition at line 680 of file CoreScheduler.java.
References com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.dyio.
Referenced by com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.addServoChannel(), and com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.DyIOFlusher.run().
getLoopTime()
int com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.getLoopTime ()
Gets the loop time.
Returns
the loop time
Definition at line 698 of file CoreScheduler.java.
References com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.loopTime.
Referenced by com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.addServoChannel(), com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.getXml(), com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.DyIOFlusher.run(), com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.SchedulerThread.run(), and com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.SchedulerThread.SchedulerThread().
getOutputs()
ArrayList< ServoOutputScheduleChannel> com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.getOutputs ()
Gets the outputs.
Returns
the outputs
Definition at line 443 of file CoreScheduler.java.
References com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.outputs.
Referenced by com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.addServoChannel(), com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.getXml(), com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.removeServoOutputScheduleChannel(), com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.DyIOFlusher.run(), com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.SchedulerThread.SchedulerThread(), and com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.setCurrentTime().
getSt()
SchedulerThread com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.getSt ()
Gets the st.
Returns
the st
Definition at line 707 of file CoreScheduler.java.
References com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.st.
Referenced by com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.isPlaying(), com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.pause(), com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.play(), com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.playStep(), and com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.setSequenceParams().
getTagValue()
static String com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.getTagValue (String sTag, Element eElement) static private
Gets the tag value.
Parameters
sTag the s tag
eElement the e element
Returns
the tag value
Definition at line 193 of file CoreScheduler.java.
Referenced by com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.loadFromFile().
getTrackLength()
int com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.getTrackLength ()
Gets the track length.
Returns
the track length
Definition at line 222 of file CoreScheduler.java.
References com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.msDuration.
Referenced by com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.addServoChannel().
getXml()
String com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.getXml ()
Gets the xml.
Returns
the xml
Definition at line 413 of file CoreScheduler.java.
References com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.filename, com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.getLoopTime(), com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.getOutputs(), com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.mp3, and com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.msDuration.
isLooping()
boolean com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.isLooping () private
Checks if is looping.
Returns
true, if is looping
Definition at line 240 of file CoreScheduler.java.
References com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.loop.
isPlaying()
boolean com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.isPlaying ()
Checks if is playing.
Returns
true, if is playing
Definition at line 249 of file CoreScheduler.java.
References com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.getSt(), and com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.SchedulerThread.isPause().
loadFromFile()
void com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.loadFromFile (File f)
Load from file.
Parameters
f The file to load the scheduler configuration from. This should be an xml.
sample code from http://www.mkyong.com/java/how-to-read-xml-file-in-java-dom-parser/
Definition at line 101 of file CoreScheduler.java.
References com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.addServoChannel(), com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.filename, com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.getTagValue(), com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.msDuration, com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.pauseRecording(), com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.setAnalogInputChannelNumber(), com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.setAudioFile(), com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.setData(), com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.setInputCenter(), com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.setInputScale(), com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.setLoopTime(), com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.setOutputMinMax(), and com.neuronrobotics.sdk.dyio.sequencer.ServoOutputScheduleChannel.startRecording().
Referenced by com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.CoreScheduler().
pause()
void com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.pause ()
Pause.
Definition at line 335 of file CoreScheduler.java.
References com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.callPause(), com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.getSt(), com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.mp3, com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.SchedulerThread.pause, and com.neuronrobotics.sdk.dyio.sequencer.SequencerWAV.pause().
play() [1/2]
void com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.play ()
Play.
Definition at line 314 of file CoreScheduler.java.
References com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.callPlay(), com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.getSt(), com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.mp3, com.neuronrobotics.sdk.dyio.sequencer.SequencerWAV.play(), com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.SchedulerThread.setPause(), and com.neuronrobotics.sdk.util.ThreadUtil.wait().
Referenced by com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.play().
play() [2/2]
void com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.play (int setpoint, long StartOffset)
Play.
Parameters
setpoint the setpoint
StartOffset the start offset
Definition at line 327 of file CoreScheduler.java.
References com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.play(), com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.setSequenceParams(), and com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.StartOffset.
playStep()
void com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.playStep ()
Play step.
Definition at line 303 of file CoreScheduler.java.
References com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.getSt(), and com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.SchedulerThread.playStep().
removeISchedulerListener()
void com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.removeISchedulerListener (ISchedulerListener l)
Removes the i scheduler listener.
Parameters
l the l
Definition at line 360 of file CoreScheduler.java.
References com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.listeners.
removeServoOutputScheduleChannel()
void com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.removeServoOutputScheduleChannel (ServoOutputScheduleChannel s)
Removes the servo output schedule channel.
Parameters
s the s
Definition at line 280 of file CoreScheduler.java.
References com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.getOutputs().
setAudioFile()
void com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.setAudioFile (File f)
Sets the audio file.
Parameters
f the new audio file
Definition at line 205 of file CoreScheduler.java.
References com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.audioFile, com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.filename, com.neuronrobotics.sdk.dyio.sequencer.SequencerWAV.getTrackLength(), com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.mp3, com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.msDuration, and com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.setSequenceParams().
Referenced by com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.loadFromFile().
setCurrentTime()
void com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.setCurrentTime (long time)
Sets the current time.
Parameters
time the new current time
Definition at line 369 of file CoreScheduler.java.
References com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.getOutputs(), com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.listeners, and com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.DyIOFlusher.setFlush().
Referenced by com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.SchedulerThread.playStep(), and com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.SchedulerThread.run().
setDyIO()
void com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.setDyIO (DyIO dyio)
Sets the dy io.
Parameters
dyio the new dy io
Definition at line 669 of file CoreScheduler.java.
References com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.dyio.
Referenced by com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.CoreScheduler().
setLooping()
void com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.setLooping (boolean b)
Sets the looping.
Parameters
b the new looping
Definition at line 231 of file CoreScheduler.java.
References com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.loop.
setLoopTime()
void com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.setLoopTime (int loopTime)
Sets the loop time.
Parameters
loopTime the new loop time
Definition at line 689 of file CoreScheduler.java.
References com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.loopTime.
Referenced by com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.CoreScheduler(), and com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.loadFromFile().
setOutputs()
void com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.setOutputs (ArrayList< ServoOutputScheduleChannel > outputs)
Sets the outputs.
Parameters
outputs the new outputs
Definition at line 434 of file CoreScheduler.java.
References com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.outputs.
setSequenceParams()
void com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.setSequenceParams (int setpoint, long StartOffset)
Sets the sequence params.
Parameters
setpoint the setpoint
StartOffset the start offset
Definition at line 290 of file CoreScheduler.java.
References com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.getSt(), com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.mp3, com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.msDuration, com.neuronrobotics.sdk.dyio.sequencer.SequencerWAV.setCurrentTime(), com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.setSt(), and com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.StartOffset.
Referenced by com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.play(), and com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.setAudioFile().
setSt()
void com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.setSt (SchedulerThread st)
Sets the st.
Parameters
st the new st
Definition at line 716 of file CoreScheduler.java.
References com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.SchedulerThread.setPause(), and com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.st.
Referenced by com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.setSequenceParams().
Member Data Documentation
audioFile
File com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.audioFile =null private
The audio file.
Definition at line 63 of file CoreScheduler.java.
Referenced by com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.getAudioFile(), and com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.setAudioFile().
dyio
DyIO com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.dyio private
The dyio.
Definition at line 53 of file CoreScheduler.java.
Referenced by com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.getDyIO(), and com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.setDyIO().
filename
String com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.filename =null private
The filename.
Definition at line 56 of file CoreScheduler.java.
Referenced by com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.getXml(), com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.loadFromFile(), and com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.setAudioFile().
flushTime
long com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.flushTime = 0 private
The flush time.
Definition at line 35 of file CoreScheduler.java.
Referenced by com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.DyIOFlusher.run().
listeners
ArrayList< ISchedulerListener> com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.listeners = new ArrayList< ISchedulerListener>() private
The listeners.
Definition at line 47 of file CoreScheduler.java.
Referenced by com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.addISchedulerListener(), com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.callPause(), com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.callPlay(), com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.callReset(), com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.removeISchedulerListener(), and com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.setCurrentTime().
loop
boolean com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.loop = false private
The loop.
Definition at line 44 of file CoreScheduler.java.
Referenced by com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.isLooping(), and com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.setLooping().
loopTime
int com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.loopTime private
The loop time.
Definition at line 32 of file CoreScheduler.java.
Referenced by com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.getLoopTime(), and com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.setLoopTime().
mp3
SequencerWAV com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.mp3 private
The mp3.
Definition at line 41 of file CoreScheduler.java.
Referenced by com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.getXml(), com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.SchedulerThread.isRun(), com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.SchedulerThread.kill(), com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.pause(), com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.SchedulerThread.pause(), com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.play(), com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.SchedulerThread.playStep(), com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.SchedulerThread.SchedulerThread(), com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.setAudioFile(), and com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.setSequenceParams().
msDuration
int com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.msDuration =0 private
The ms duration.
Definition at line 59 of file CoreScheduler.java.
Referenced by com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.CoreScheduler(), com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.getTrackLength(), com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.getXml(), com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.loadFromFile(), com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.setAudioFile(), and com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.setSequenceParams().
outputs
ArrayList< ServoOutputScheduleChannel> com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.outputs = new ArrayList< ServoOutputScheduleChannel>() private
The outputs.
Definition at line 50 of file CoreScheduler.java.
Referenced by com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.getOutputs(), and com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.setOutputs().
st
SchedulerThread com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.st =null private
The st.
Definition at line 38 of file CoreScheduler.java.
Referenced by com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.getSt(), and com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.setSt().
StartOffset
long com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.StartOffset private
The Start offset.
Definition at line 69 of file CoreScheduler.java.
Referenced by com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.play(), com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.SchedulerThread.playStep(), com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.SchedulerThread.SchedulerThread(), and com.neuronrobotics.sdk.dyio.sequencer.CoreScheduler.setSequenceParams().
The documentation for this class was generated from the following file:
src/main/java/com/neuronrobotics/sdk/dyio/sequencer/CoreScheduler.java