BowlerKernel: com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice Class Reference
com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice Class Reference
Public Member Functions
BowlerJInputDevice (String... names)
BowlerJInputDevice (List< String > searches)
void disconnectDeviceImp ()
double getValue (String component)
boolean connectDeviceImp ()
String getControllerName ()
void setController (Controller controller)
void removeListeners (IGameControlEvent l)
void clearListeners ()
void addListeners (IGameControlEvent l)
ArrayList< String > getNamespacesImp ()
String toString ()
String getMaps ()
void map (String controllerVal, String persistantVal)
String getName ()
void setName (String name)
Public Member Functions inherited from com.neuronrobotics.sdk.common.NonBowlerDevice
boolean connect ()
boolean isAvailable () throws InvalidConnectionException
void disconnect ()
void onAsyncResponse (BowlerDatagram data)
ArrayList< String > getNamespaces ()
Public Member Functions inherited from com.neuronrobotics.sdk.common.BowlerAbstractDevice
void addConnectionEventListener (final IDeviceConnectionEventListener l)
void removeConnectionEventListener (IDeviceConnectionEventListener l)
void setConnection (BowlerAbstractConnection connection)
BowlerAbstractConnection getConnection ()
void setAddress (MACAddress address)
MACAddress getAddress ()
BowlerDatagram send (BowlerAbstractCommand command) throws NoConnectionAvailableException, InvalidResponseException
BowlerDatagram send (BowlerAbstractCommand command, int retry) throws NoConnectionAvailableException, InvalidResponseException
Object[] send (String namespace, BowlerMethod method, String rpcString, Object[] arguments, int retry) throws DeviceConnectionException
Object[] send (String namespace, BowlerMethod method, String rpcString, Object[] arguments) throws DeviceConnectionException
boolean ping ()
boolean ping (boolean switchParser)
ArrayList< ByteList > getRevisions ()
boolean hasNamespace (String string)
void startHeartBeat ()
void startHeartBeat (long msHeartBeatTime)
void stopHeartBeat ()
void setThreadedUpstreamPackets (boolean up)
ArrayList< RpcEncapsulation > getRpcList (String namespace)
void loadRpcList ()
void onAllResponse (BowlerDatagram data)
boolean isKeepAlive ()
void setKeepAlive (boolean keepAlive)
long getLastPacketTime ()
void setLastPacketTime (long lastPacketTime)
String getScriptingName ()
void setScriptingName (String scriptingName)
ArrayList< IDeviceConnectionEventListener > getDisconnectListeners ()
Static Public Member Functions
static ArrayList< String > getControllers ()
static void main (String[] args) throws InterruptedException
Private Member Functions
void setControllerByName (List< String > names)
Static Private Member Functions
static ArrayList< Controller > controllers ()
Private Attributes
Controller controller
ArrayList< IGameControlEvent > listeners = new ArrayList<IGameControlEvent>()
HashMap< String, Double > recentValue = new HashMap<String, Double>()
Thread poller
String name
List< String > searches
Additional Inherited Members
Protected Member Functions inherited from com.neuronrobotics.sdk.common.BowlerAbstractDevice
void fireDisconnectEvent ()
void fireConnectEvent ()
Detailed Description
The Class BowlerJInputDevice.
Definition at line 24 of file BowlerJInputDevice.java.
Constructor & Destructor Documentation
BowlerJInputDevice() [1/2]
com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.BowlerJInputDevice (String... names)
Instantiates a new bowler j input device.
Definition at line 76 of file BowlerJInputDevice.java.
References com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.setControllerByName().
Referenced by com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.main().
BowlerJInputDevice() [2/2]
com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.BowlerJInputDevice (List< String > searches)
Definition at line 80 of file BowlerJInputDevice.java.
References com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.searches, and com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.setControllerByName().
Member Function Documentation
addListeners()
void com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.addListeners (IGameControlEvent l)
Adds the listeners.
Parameters
l the l
Definition at line 273 of file BowlerJInputDevice.java.
References com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.listeners.
Referenced by com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.main(), and com.neuronrobotics.sdk.addons.gamepad.JogTrainerWidget.reset().
clearListeners()
void com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.clearListeners ()
Removes all the listeners.
Definition at line 264 of file BowlerJInputDevice.java.
connectDeviceImp()
boolean com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.connectDeviceImp ()
Connect device imp.
Returns
true, if successful
Reimplemented from com.neuronrobotics.sdk.common.NonBowlerDevice.
Definition at line 135 of file BowlerJInputDevice.java.
References com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.controller, com.neuronrobotics.sdk.common.NonBowlerDevice.disconnect(), com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase.getGitSource(), com.neuronrobotics.sdk.addons.gamepad.PersistantControllerMap.getMappedAxisName(), com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.listeners, com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.name, com.neuronrobotics.sdk.addons.gamepad.IGameControlEvent.onEvent(), com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.poller, com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.recentValue, com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.searches, com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.setControllerByName(), com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.setName(), com.neuronrobotics.sdk.util.ThreadUtil.wait(), and com.neuronrobotics.sdk.common.Log.warning().
controllers()
static ArrayList<Controller> com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.controllers () static private
Definition at line 46 of file BowlerJInputDevice.java.
References com.neuronrobotics.sdk.addons.gamepad.ControllerEnvironment.getControllers(), com.neuronrobotics.sdk.addons.gamepad.ControllerEnvironment.getDefaultEnvironment(), and com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.getName().
Referenced by com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.getControllers(), and com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.setControllerByName().
disconnectDeviceImp()
void com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.disconnectDeviceImp ()
This method tells the connection object to disconnect its pipes and close out the connection. Once this is called, it is safe to remove your device.
Reimplemented from com.neuronrobotics.sdk.common.NonBowlerDevice.
Definition at line 117 of file BowlerJInputDevice.java.
References com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.listeners, and com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.poller.
getControllerName()
String com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.getControllerName ()
Gets the controller.
Returns
the controller
Definition at line 225 of file BowlerJInputDevice.java.
References com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.controller.
getControllers()
static ArrayList<String> com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.getControllers () static
Definition at line 60 of file BowlerJInputDevice.java.
References com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.controller, com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.controllers(), and com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.name.
getMaps()
String com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.getMaps ()
Definition at line 304 of file BowlerJInputDevice.java.
References com.neuronrobotics.sdk.addons.gamepad.PersistantControllerMap.getMappedAxis(), com.neuronrobotics.sdk.addons.gamepad.PersistantControllerMap.getMappedAxisName(), com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.name, and com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.recentValue.
getName()
String com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.getName ()
Definition at line 344 of file BowlerJInputDevice.java.
References com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.name.
Referenced by com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.controllers(), and com.neuronrobotics.sdk.addons.gamepad.JogTrainerWidget.reset().
getNamespacesImp()
ArrayList<String> com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.getNamespacesImp ()
Gets the namespaces imp.
Returns
the namespaces imp
Reimplemented from com.neuronrobotics.sdk.common.NonBowlerDevice.
Definition at line 284 of file BowlerJInputDevice.java.
getValue()
double com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.getValue (String component)
Definition at line 123 of file BowlerJInputDevice.java.
References com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.recentValue.
Referenced by com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.toString().
main()
static void com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.main (String[] args) throws InterruptedException static
Definition at line 322 of file BowlerJInputDevice.java.
References com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.addListeners(), com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.BowlerJInputDevice(), com.neuronrobotics.sdk.common.NonBowlerDevice.connect(), eu.mihosoft.vrl.v3d.JavaFXInitializer.go(), com.neuronrobotics.sdk.common.NonBowlerDevice.isAvailable(), and com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.name.
map()
void com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.map (String controllerVal, String persistantVal)
Definition at line 316 of file BowlerJInputDevice.java.
References com.neuronrobotics.sdk.addons.gamepad.PersistantControllerMap.map(), and com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.name.
removeListeners()
void com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.removeListeners (IGameControlEvent l)
Removes the listeners.
Parameters
l the l
Definition at line 255 of file BowlerJInputDevice.java.
References com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.listeners.
setController()
void com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.setController (Controller controller)
Sets the controller.
Parameters
controller the new controller
Definition at line 234 of file BowlerJInputDevice.java.
References com.neuronrobotics.sdk.addons.gamepad.PersistantControllerMap.areAllAxisMapped(), com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.controller, com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.name, com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.recentValue, and com.neuronrobotics.sdk.addons.gamepad.JogTrainerWidget.run().
Referenced by com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.setControllerByName().
setControllerByName()
void com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.setControllerByName (List< String > names) private
Definition at line 84 of file BowlerJInputDevice.java.
References com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.controller, com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.controllers(), com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.searches, and com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.setController().
Referenced by com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.BowlerJInputDevice(), and com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.connectDeviceImp().
setName()
void com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.setName (String name)
Definition at line 348 of file BowlerJInputDevice.java.
References com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.name.
Referenced by com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.connectDeviceImp().
toString()
String com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.toString ()
Definition at line 290 of file BowlerJInputDevice.java.
References com.neuronrobotics.sdk.addons.gamepad.PersistantControllerMap.getMappedAxis(), com.neuronrobotics.sdk.addons.gamepad.PersistantControllerMap.getMappedAxisName(), com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.getValue(), com.neuronrobotics.sdk.addons.gamepad.PersistantControllerMap.isMapedAxis(), com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.name, and com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.recentValue.
Member Data Documentation
controller
Controller com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.controller private
The controller.
Definition at line 27 of file BowlerJInputDevice.java.
Referenced by com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.connectDeviceImp(), com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.getControllerName(), com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.getControllers(), com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.setController(), and com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.setControllerByName().
listeners
ArrayList<IGameControlEvent> com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.listeners = new ArrayList<IGameControlEvent>() private
The listeners.
Definition at line 30 of file BowlerJInputDevice.java.
Referenced by com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.addListeners(), com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.connectDeviceImp(), com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.disconnectDeviceImp(), and com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.removeListeners().
name
String com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.name private
Definition at line 40 of file BowlerJInputDevice.java.
Referenced by com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.connectDeviceImp(), com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.getControllers(), com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.getMaps(), com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.getName(), com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.main(), com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.map(), com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.setController(), com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.setName(), and com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.toString().
poller
Thread com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.poller private
The poller.
Definition at line 38 of file BowlerJInputDevice.java.
Referenced by com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.connectDeviceImp(), and com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.disconnectDeviceImp().
recentValue
HashMap<String, Double> com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.recentValue = new HashMap<String, Double>() private
Definition at line 35 of file BowlerJInputDevice.java.
Referenced by com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.connectDeviceImp(), com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.getMaps(), com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.getValue(), com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.setController(), and com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.toString().
searches
List<String> com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.searches private
Definition at line 41 of file BowlerJInputDevice.java.
Referenced by com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.BowlerJInputDevice(), com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.connectDeviceImp(), and com.neuronrobotics.sdk.addons.gamepad.BowlerJInputDevice.setControllerByName().
The documentation for this class was generated from the following file:
src/main/java/com/neuronrobotics/sdk/addons/gamepad/BowlerJInputDevice.java