BowlerKernel: eu.mihosoft.vrl.v3d.parametrics.CSGDatabase Class Reference
eu.mihosoft.vrl.v3d.parametrics.CSGDatabase Class Reference
Static Public Member Functions
static void set (String key, Parameter value)
static Parameter get (String key)
static void clear ()
static void addParameterListener (String key, IParameterChanged l)
static void removeParameterListener (String key, IParameterChanged l)
static ArrayList< IParameterChanged > getParamListeners (String key)
static void delete (String key)
static void loadDatabaseFromFile (File f)
static String getDataBaseString ()
static void saveDatabase ()
static File getDbFile ()
static void setDbFile (File dbFile)
Static Private Member Functions
static HashMap< String, Parameter > getDatabase ()
static void setDatabase (HashMap< String, Parameter > database)
Static Private Attributes
static HashMap< String, Parameter > database =null
static File dbFile =new File("CSGdatabase.json")
static final Type TT_mapStringString = new TypeToken<HashMap<String,Parameter>>(){}.getType()
static final Gson gson = new GsonBuilder().disableHtmlEscaping().setPrettyPrinting().create()
static final HashMap< String, ArrayList< IParameterChanged > > parameterListeners =new HashMap<>()
Detailed Description
Definition at line 17 of file CSGDatabase.java.
Member Function Documentation
addParameterListener()
static void eu.mihosoft.vrl.v3d.parametrics.CSGDatabase.addParameterListener (String key, IParameterChanged l) static
Definition at line 48 of file CSGDatabase.java.
References eu.mihosoft.vrl.v3d.parametrics.CSGDatabase.getParamListeners().
Referenced by com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.setAllCad(), and eu.mihosoft.vrl.v3d.parametrics.Parameter.setup().
clear()
static void eu.mihosoft.vrl.v3d.parametrics.CSGDatabase.clear () static
Definition at line 39 of file CSGDatabase.java.
References eu.mihosoft.vrl.v3d.parametrics.CSGDatabase.database, eu.mihosoft.vrl.v3d.parametrics.CSGDatabase.getDatabase(), eu.mihosoft.vrl.v3d.parametrics.CSGDatabase.parameterListeners, and eu.mihosoft.vrl.v3d.parametrics.CSGDatabase.saveDatabase().
delete()
static void eu.mihosoft.vrl.v3d.parametrics.CSGDatabase.delete (String key) static
Definition at line 72 of file CSGDatabase.java.
References eu.mihosoft.vrl.v3d.parametrics.CSGDatabase.getDatabase().
get()
static Parameter eu.mihosoft.vrl.v3d.parametrics.CSGDatabase.get (String key) static
Definition at line 30 of file CSGDatabase.java.
References eu.mihosoft.vrl.v3d.parametrics.CSGDatabase.getDatabase().
Referenced by eu.mihosoft.vrl.v3d.CSG.historySync(), eu.mihosoft.vrl.v3d.CSG.setParameter(), eu.mihosoft.vrl.v3d.CSG.setParameterIfNull(), and eu.mihosoft.vrl.v3d.parametrics.Parameter.setup().
getDatabase()
static HashMap<String,Parameter> eu.mihosoft.vrl.v3d.parametrics.CSGDatabase.getDatabase () static private
Definition at line 77 of file CSGDatabase.java.
References eu.mihosoft.vrl.v3d.parametrics.CSGDatabase.database, eu.mihosoft.vrl.v3d.parametrics.CSGDatabase.dbFile, eu.mihosoft.vrl.v3d.parametrics.CSGDatabase.getDbFile(), eu.mihosoft.vrl.v3d.parametrics.CSGDatabase.gson, eu.mihosoft.vrl.v3d.parametrics.CSGDatabase.saveDatabase(), eu.mihosoft.vrl.v3d.parametrics.CSGDatabase.setDatabase(), and eu.mihosoft.vrl.v3d.parametrics.CSGDatabase.TT_mapStringString.
Referenced by eu.mihosoft.vrl.v3d.parametrics.CSGDatabase.clear(), eu.mihosoft.vrl.v3d.parametrics.CSGDatabase.delete(), eu.mihosoft.vrl.v3d.parametrics.CSGDatabase.get(), eu.mihosoft.vrl.v3d.parametrics.CSGDatabase.getDataBaseString(), and eu.mihosoft.vrl.v3d.parametrics.CSGDatabase.set().
getDataBaseString()
static String eu.mihosoft.vrl.v3d.parametrics.CSGDatabase.getDataBaseString () static
Definition at line 158 of file CSGDatabase.java.
References eu.mihosoft.vrl.v3d.parametrics.CSGDatabase.database, eu.mihosoft.vrl.v3d.parametrics.CSGDatabase.getDatabase(), eu.mihosoft.vrl.v3d.parametrics.CSGDatabase.gson, and eu.mihosoft.vrl.v3d.parametrics.CSGDatabase.TT_mapStringString.
Referenced by eu.mihosoft.vrl.v3d.parametrics.CSGDatabase.saveDatabase().
getDbFile()
static File eu.mihosoft.vrl.v3d.parametrics.CSGDatabase.getDbFile () static
Definition at line 193 of file CSGDatabase.java.
References eu.mihosoft.vrl.v3d.parametrics.CSGDatabase.dbFile.
Referenced by com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.commit(), eu.mihosoft.vrl.v3d.parametrics.CSGDatabase.getDatabase(), and eu.mihosoft.vrl.v3d.parametrics.CSGDatabase.saveDatabase().
getParamListeners()
static ArrayList<IParameterChanged> eu.mihosoft.vrl.v3d.parametrics.CSGDatabase.getParamListeners (String key) static
Definition at line 64 of file CSGDatabase.java.
References eu.mihosoft.vrl.v3d.parametrics.CSGDatabase.parameterListeners.
Referenced by eu.mihosoft.vrl.v3d.parametrics.CSGDatabase.addParameterListener(), eu.mihosoft.vrl.v3d.parametrics.Parameter.setStrValue(), and eu.mihosoft.vrl.v3d.parametrics.Parameter.setValue().
loadDatabaseFromFile()
static void eu.mihosoft.vrl.v3d.parametrics.CSGDatabase.loadDatabaseFromFile (File f) static
Definition at line 135 of file CSGDatabase.java.
References eu.mihosoft.vrl.v3d.parametrics.CSGDatabase.gson, eu.mihosoft.vrl.v3d.parametrics.CSGDatabase.saveDatabase(), and eu.mihosoft.vrl.v3d.parametrics.CSGDatabase.TT_mapStringString.
Referenced by eu.mihosoft.vrl.v3d.parametrics.CSGDatabase.setDbFile().
removeParameterListener()
static void eu.mihosoft.vrl.v3d.parametrics.CSGDatabase.removeParameterListener (String key, IParameterChanged l) static
Definition at line 54 of file CSGDatabase.java.
References eu.mihosoft.vrl.v3d.parametrics.CSGDatabase.parameterListeners.
saveDatabase()
static void eu.mihosoft.vrl.v3d.parametrics.CSGDatabase.saveDatabase () static
Definition at line 167 of file CSGDatabase.java.
References eu.mihosoft.vrl.v3d.parametrics.CSGDatabase.getDataBaseString(), and eu.mihosoft.vrl.v3d.parametrics.CSGDatabase.getDbFile().
Referenced by eu.mihosoft.vrl.v3d.parametrics.CSGDatabase.clear(), com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.commit(), eu.mihosoft.vrl.v3d.parametrics.CSGDatabase.getDatabase(), and eu.mihosoft.vrl.v3d.parametrics.CSGDatabase.loadDatabaseFromFile().
set()
static void eu.mihosoft.vrl.v3d.parametrics.CSGDatabase.set (String key, Parameter value) static
Definition at line 24 of file CSGDatabase.java.
References eu.mihosoft.vrl.v3d.parametrics.CSGDatabase.getDatabase().
Referenced by eu.mihosoft.vrl.v3d.CSG.setParameter(), and eu.mihosoft.vrl.v3d.parametrics.Parameter.setup().
setDatabase()
static void eu.mihosoft.vrl.v3d.parametrics.CSGDatabase.setDatabase (HashMap< String, Parameter > database) static private
Definition at line 187 of file CSGDatabase.java.
References eu.mihosoft.vrl.v3d.parametrics.CSGDatabase.database.
Referenced by eu.mihosoft.vrl.v3d.parametrics.CSGDatabase.getDatabase().
setDbFile()
static void eu.mihosoft.vrl.v3d.parametrics.CSGDatabase.setDbFile (File dbFile) static
Definition at line 196 of file CSGDatabase.java.
References eu.mihosoft.vrl.v3d.parametrics.CSGDatabase.dbFile, and eu.mihosoft.vrl.v3d.parametrics.CSGDatabase.loadDatabaseFromFile().
Referenced by com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.commit().
Member Data Documentation
database
HashMap<String,Parameter> eu.mihosoft.vrl.v3d.parametrics.CSGDatabase.database =null static private
Definition at line 19 of file CSGDatabase.java.
Referenced by eu.mihosoft.vrl.v3d.parametrics.CSGDatabase.clear(), eu.mihosoft.vrl.v3d.parametrics.CSGDatabase.getDatabase(), eu.mihosoft.vrl.v3d.parametrics.CSGDatabase.getDataBaseString(), and eu.mihosoft.vrl.v3d.parametrics.CSGDatabase.setDatabase().
dbFile
File eu.mihosoft.vrl.v3d.parametrics.CSGDatabase.dbFile =new File("CSGdatabase.json") static private
Definition at line 20 of file CSGDatabase.java.
Referenced by eu.mihosoft.vrl.v3d.parametrics.CSGDatabase.getDatabase(), eu.mihosoft.vrl.v3d.parametrics.CSGDatabase.getDbFile(), and eu.mihosoft.vrl.v3d.parametrics.CSGDatabase.setDbFile().
gson
final Gson eu.mihosoft.vrl.v3d.parametrics.CSGDatabase.gson = new GsonBuilder().disableHtmlEscaping().setPrettyPrinting().create() static private
Definition at line 22 of file CSGDatabase.java.
Referenced by eu.mihosoft.vrl.v3d.parametrics.CSGDatabase.getDatabase(), eu.mihosoft.vrl.v3d.parametrics.CSGDatabase.getDataBaseString(), and eu.mihosoft.vrl.v3d.parametrics.CSGDatabase.loadDatabaseFromFile().
parameterListeners
final HashMap<String,ArrayList<IParameterChanged> > eu.mihosoft.vrl.v3d.parametrics.CSGDatabase.parameterListeners =new HashMap<>() static private
Definition at line 23 of file CSGDatabase.java.
Referenced by eu.mihosoft.vrl.v3d.parametrics.CSGDatabase.clear(), eu.mihosoft.vrl.v3d.parametrics.CSGDatabase.getParamListeners(), and eu.mihosoft.vrl.v3d.parametrics.CSGDatabase.removeParameterListener().
TT_mapStringString
final Type eu.mihosoft.vrl.v3d.parametrics.CSGDatabase.TT_mapStringString = new TypeToken<HashMap<String,Parameter>>(){}.getType() static private
Definition at line 21 of file CSGDatabase.java.
Referenced by eu.mihosoft.vrl.v3d.parametrics.CSGDatabase.getDatabase(), eu.mihosoft.vrl.v3d.parametrics.CSGDatabase.getDataBaseString(), and eu.mihosoft.vrl.v3d.parametrics.CSGDatabase.loadDatabaseFromFile().
The documentation for this class was generated from the following file:
JCSG/src/main/java/eu/mihosoft/vrl/v3d/parametrics/CSGDatabase.java