BowlerKernel: eu.mihosoft.vrl.v3d.Parabola Class Reference
eu.mihosoft.vrl.v3d.Parabola Class Reference
Public Member Functions
Parabola fromEquation (double Radius, double a, double b)
Parabola fromFocalLength (double Radius, double Focus)
ArrayList< Vector3d > getpoints ()
Static Public Member Functions
static CSG coneByEquation (double Radius, double a, double b)
static CSG cone (double Radius, double height)
static CSG cone (double Radius, double height, double b)
static CSG coneByHeight (double Radius, double height)
static CSG coneByHeight (double Radius, double height, double b)
static CSG coneByFocalLength (double Radius, double FocalLength)
static CSG extrudeByEquation (double Radius, double a, double b, double thickness)
Private Member Functions
Parabola ()
double computeY (double x)
Detailed Description
Definition at line 5 of file Parabola.java.
Constructor & Destructor Documentation
Parabola()
eu.mihosoft.vrl.v3d.Parabola.Parabola () private
Definition at line 12 of file Parabola.java.
Referenced by eu.mihosoft.vrl.v3d.Parabola.coneByEquation(), eu.mihosoft.vrl.v3d.Parabola.coneByFocalLength(), eu.mihosoft.vrl.v3d.Parabola.coneByHeight(), and eu.mihosoft.vrl.v3d.Parabola.extrudeByEquation().
Member Function Documentation
computeY()
double eu.mihosoft.vrl.v3d.Parabola.computeY (double x) private
Definition at line 16 of file Parabola.java.
Referenced by eu.mihosoft.vrl.v3d.Parabola.getpoints().
cone() [1/2]
static CSG eu.mihosoft.vrl.v3d.Parabola.cone (double Radius, double height) static
Definition at line 74 of file Parabola.java.
References eu.mihosoft.vrl.v3d.Parabola.coneByHeight(), eu.mihosoft.vrl.v3d.CSG.rotx(), and eu.mihosoft.vrl.v3d.CSG.toZMin().
cone() [2/2]
static CSG eu.mihosoft.vrl.v3d.Parabola.cone (double Radius, double height, double b) static
Definition at line 77 of file Parabola.java.
References eu.mihosoft.vrl.v3d.Parabola.coneByHeight(), eu.mihosoft.vrl.v3d.CSG.rotx(), and eu.mihosoft.vrl.v3d.CSG.toZMin().
coneByEquation()
static CSG eu.mihosoft.vrl.v3d.Parabola.coneByEquation (double Radius, double a, double b) static
Definition at line 59 of file Parabola.java.
References eu.mihosoft.vrl.v3d.Parabola.Parabola(), and eu.mihosoft.vrl.v3d.Transform.roty().
coneByFocalLength()
static CSG eu.mihosoft.vrl.v3d.Parabola.coneByFocalLength (double Radius, double FocalLength) static
Definition at line 99 of file Parabola.java.
References eu.mihosoft.vrl.v3d.Parabola.Parabola(), and eu.mihosoft.vrl.v3d.Transform.roty().
coneByHeight() [1/2]
static CSG eu.mihosoft.vrl.v3d.Parabola.coneByHeight (double Radius, double height) static
Definition at line 80 of file Parabola.java.
Referenced by eu.mihosoft.vrl.v3d.Parabola.cone().
coneByHeight() [2/2]
static CSG eu.mihosoft.vrl.v3d.Parabola.coneByHeight (double Radius, double height, double b) static
Definition at line 84 of file Parabola.java.
References eu.mihosoft.vrl.v3d.Parabola.Parabola(), and eu.mihosoft.vrl.v3d.Transform.roty().
extrudeByEquation()
static CSG eu.mihosoft.vrl.v3d.Parabola.extrudeByEquation (double Radius, double a, double b, double thickness) static
Definition at line 114 of file Parabola.java.
References eu.mihosoft.vrl.v3d.Parabola.fromEquation(), eu.mihosoft.vrl.v3d.Parabola.getpoints(), eu.mihosoft.vrl.v3d.Parabola.Parabola(), and eu.mihosoft.vrl.v3d.Extrude.points().
fromEquation()
Parabola eu.mihosoft.vrl.v3d.Parabola.fromEquation (double Radius, double a, double b)
Definition at line 24 of file Parabola.java.
Referenced by eu.mihosoft.vrl.v3d.Parabola.extrudeByEquation().
fromFocalLength()
Parabola eu.mihosoft.vrl.v3d.Parabola.fromFocalLength (double Radius, double Focus)
Definition at line 37 of file Parabola.java.
getpoints()
ArrayList<Vector3d> eu.mihosoft.vrl.v3d.Parabola.getpoints ()
Definition at line 47 of file Parabola.java.
References eu.mihosoft.vrl.v3d.Parabola.computeY().
Referenced by eu.mihosoft.vrl.v3d.Parabola.extrudeByEquation().
The documentation for this class was generated from the following file:
JCSG/src/main/java/eu/mihosoft/vrl/v3d/Parabola.java