BowlerKernel: com.neuronrobotics.sdk.util.ProcessMonitor Class Reference
com.neuronrobotics.sdk.util.ProcessMonitor Class Reference
Public Member Functions
ProcessMonitor (IMonitorable process)
void addProcessMonitorListener (IProgressMonitorListener listener)
void start ()
void actionPerformed (ActionEvent arg0)
Private Attributes
Timer timer = new Timer(100, this)
IMonitorable process
ArrayList< IProgressMonitorListener > listeners = new ArrayList<IProgressMonitorListener>()
Detailed Description
The Class ProcessMonitor.
Definition at line 12 of file ProcessMonitor.java.
Constructor & Destructor Documentation
ProcessMonitor()
com.neuronrobotics.sdk.util.ProcessMonitor.ProcessMonitor (IMonitorable process)
Instantiates a new process monitor.
Parameters
process the process
Definition at line 28 of file ProcessMonitor.java.
References com.neuronrobotics.sdk.util.ProcessMonitor.process.
Member Function Documentation
actionPerformed()
void com.neuronrobotics.sdk.util.ProcessMonitor.actionPerformed (ActionEvent arg0)
Definition at line 52 of file ProcessMonitor.java.
References com.neuronrobotics.sdk.util.IMonitorable.getPercentage(), com.neuronrobotics.sdk.util.IMonitorable.isComplete(), com.neuronrobotics.sdk.util.ProcessMonitor.listeners, com.neuronrobotics.sdk.util.ProcessMonitor.process, and com.neuronrobotics.sdk.util.ProcessMonitor.timer.
addProcessMonitorListener()
void com.neuronrobotics.sdk.util.ProcessMonitor.addProcessMonitorListener (IProgressMonitorListener listener)
Adds the process monitor listener.
Parameters
listener the listener
Definition at line 37 of file ProcessMonitor.java.
References com.neuronrobotics.sdk.util.ProcessMonitor.listeners.
Referenced by com.neuronrobotics.sdk.ui.BluetoothConnectionPanel.refresh(), and com.neuronrobotics.sdk.ui.UDPConnectionPanel.refresh().
start()
void com.neuronrobotics.sdk.util.ProcessMonitor.start ()
Start.
Definition at line 44 of file ProcessMonitor.java.
References com.neuronrobotics.sdk.util.ProcessMonitor.timer.
Referenced by com.neuronrobotics.sdk.ui.BluetoothConnectionPanel.refresh(), and com.neuronrobotics.sdk.ui.UDPConnectionPanel.refresh().
Member Data Documentation
listeners
ArrayList<IProgressMonitorListener> com.neuronrobotics.sdk.util.ProcessMonitor.listeners = new ArrayList<IProgressMonitorListener>() private
The listeners.
Definition at line 21 of file ProcessMonitor.java.
Referenced by com.neuronrobotics.sdk.util.ProcessMonitor.actionPerformed(), and com.neuronrobotics.sdk.util.ProcessMonitor.addProcessMonitorListener().
process
IMonitorable com.neuronrobotics.sdk.util.ProcessMonitor.process private
The process.
Definition at line 18 of file ProcessMonitor.java.
Referenced by com.neuronrobotics.sdk.util.ProcessMonitor.actionPerformed(), and com.neuronrobotics.sdk.util.ProcessMonitor.ProcessMonitor().
timer
Timer com.neuronrobotics.sdk.util.ProcessMonitor.timer = new Timer(100, this) private
The timer.
Definition at line 15 of file ProcessMonitor.java.
Referenced by com.neuronrobotics.sdk.util.ProcessMonitor.actionPerformed(), and com.neuronrobotics.sdk.util.ProcessMonitor.start().
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/util/ProcessMonitor.java