BowlerKernel: eu.mihosoft.vrl.v3d.ZModifier Class Reference
eu.mihosoft.vrl.v3d.ZModifier Class Reference
Public Member Functions
ZModifier ()
ZModifier (boolean centered)
double eval (Vector3d pos, CSG csg)
Private Attributes
Bounds bounds
double min = 0
double max = 1.0
double sPerUnit
boolean centered
Detailed Description
Modifies along z axis.
Author
Michael Hoffer <info@.nosp@m.mich.nosp@m.aelho.nosp@m.ffer.nosp@m..de>
Definition at line 14 of file ZModifier.java.
Constructor & Destructor Documentation
ZModifier() [1/2]
eu.mihosoft.vrl.v3d.ZModifier.ZModifier ()
Constructor.
Definition at line 34 of file ZModifier.java.
ZModifier() [2/2]
eu.mihosoft.vrl.v3d.ZModifier.ZModifier (boolean centered)
Constructor.
Parameters
centered defines whether to center origin at the csg location
Definition at line 42 of file ZModifier.java.
References eu.mihosoft.vrl.v3d.ZModifier.centered.
Member Function Documentation
eval()
double eu.mihosoft.vrl.v3d.ZModifier.eval (Vector3d v, CSG csg)
Evaluates the function at the specified location.
Parameters
v location
csg csg
Returns
the weight of the specified position
Implements eu.mihosoft.vrl.v3d.WeightFunction.
Definition at line 50 of file ZModifier.java.
References eu.mihosoft.vrl.v3d.ZModifier.bounds, eu.mihosoft.vrl.v3d.ZModifier.centered, eu.mihosoft.vrl.v3d.CSG.getBounds(), eu.mihosoft.vrl.v3d.Bounds.getMax(), eu.mihosoft.vrl.v3d.Bounds.getMin(), eu.mihosoft.vrl.v3d.ZModifier.max, eu.mihosoft.vrl.v3d.ZModifier.min, eu.mihosoft.vrl.v3d.ZModifier.sPerUnit, and eu.mihosoft.vrl.v3d.Vector3d.z().
Member Data Documentation
bounds
Bounds eu.mihosoft.vrl.v3d.ZModifier.bounds private
The bounds.
Definition at line 17 of file ZModifier.java.
Referenced by eu.mihosoft.vrl.v3d.ZModifier.eval().
centered
boolean eu.mihosoft.vrl.v3d.ZModifier.centered private
The centered.
Definition at line 29 of file ZModifier.java.
Referenced by eu.mihosoft.vrl.v3d.ZModifier.eval(), and eu.mihosoft.vrl.v3d.ZModifier.ZModifier().
max
double eu.mihosoft.vrl.v3d.ZModifier.max = 1.0 private
The max.
Definition at line 23 of file ZModifier.java.
Referenced by eu.mihosoft.vrl.v3d.ZModifier.eval().
min
double eu.mihosoft.vrl.v3d.ZModifier.min = 0 private
The min.
Definition at line 20 of file ZModifier.java.
Referenced by eu.mihosoft.vrl.v3d.ZModifier.eval().
sPerUnit
double eu.mihosoft.vrl.v3d.ZModifier.sPerUnit private
The s per unit.
Definition at line 26 of file ZModifier.java.
Referenced by eu.mihosoft.vrl.v3d.ZModifier.eval().
The documentation for this class was generated from the following file:
JCSG/src/main/java/eu/mihosoft/vrl/v3d/ZModifier.java