BowlerKernel: com.neuronrobotics.sdk.pid.PDVelocityConfiguration Class Reference
com.neuronrobotics.sdk.pid.PDVelocityConfiguration Class Reference
Public Member Functions
PDVelocityConfiguration ()
PDVelocityConfiguration (int group, boolean enabled, boolean inverted, boolean async, double KP, double KI, double KD, double latch, boolean useLatch, boolean stopOnLatch)
PDVelocityConfiguration (BowlerDatagram conf)
PDVelocityConfiguration (Object[] args)
String toString ()
void setGroup (int group)
int getGroup ()
void setKP (double kP)
double getKP ()
void setKD (double kD)
double getKD ()
Object[] getArgs ()
Private Attributes
int group =0
double KP =1
double KD =0
Detailed Description
The Class PDVelocityConfiguration.
Definition at line 10 of file PDVelocityConfiguration.java.
Constructor & Destructor Documentation
PDVelocityConfiguration() [1/4]
com.neuronrobotics.sdk.pid.PDVelocityConfiguration.PDVelocityConfiguration ()
Instantiates a new PD velocity configuration.
Definition at line 24 of file PDVelocityConfiguration.java.
PDVelocityConfiguration() [2/4]
com.neuronrobotics.sdk.pid.PDVelocityConfiguration.PDVelocityConfiguration (int group, boolean enabled, boolean inverted, boolean async, double KP, double KI, double KD, double latch, boolean useLatch, boolean stopOnLatch)
Instantiates a new PD velocity configuration.
Parameters
group This is the PID group this configuration object represents
enabled True if the controller is running, false otherwise
inverted This inverts the output value. Set true if the controller diverges
async sets the flag to send this channels async values upstream
KP Proportional constant
KI Integral constant
KD Derivative constant
latch The value to latch into the PID controller if the home switch is hit (encoder only, not used in analog PID)
useLatch Use the value to latch into the PID controller if the home switch is hit (encoder only, not used in analog PID)
stopOnLatch Set the setpoint of the controller to current if home switch is hit (encoder only, not used in analog PID)
Definition at line 42 of file PDVelocityConfiguration.java.
References com.neuronrobotics.sdk.pid.PDVelocityConfiguration.group, com.neuronrobotics.sdk.pid.PDVelocityConfiguration.KD, com.neuronrobotics.sdk.pid.PDVelocityConfiguration.KP, com.neuronrobotics.sdk.pid.PDVelocityConfiguration.setGroup(), com.neuronrobotics.sdk.pid.PDVelocityConfiguration.setKD(), and com.neuronrobotics.sdk.pid.PDVelocityConfiguration.setKP().
PDVelocityConfiguration() [3/4]
com.neuronrobotics.sdk.pid.PDVelocityConfiguration.PDVelocityConfiguration (BowlerDatagram conf)
Used to parse a PID configuration out of a PID packet.
Parameters
conf the conf
Definition at line 54 of file PDVelocityConfiguration.java.
References com.neuronrobotics.sdk.common.ByteList.convertToInt(), com.neuronrobotics.sdk.common.ByteList.get(), com.neuronrobotics.sdk.common.ByteList.getBytes(), com.neuronrobotics.sdk.common.BowlerDatagram.getData(), com.neuronrobotics.sdk.pid.PDVelocityConfiguration.setGroup(), com.neuronrobotics.sdk.pid.PDVelocityConfiguration.setKD(), and com.neuronrobotics.sdk.pid.PDVelocityConfiguration.setKP().
PDVelocityConfiguration() [4/4]
com.neuronrobotics.sdk.pid.PDVelocityConfiguration.PDVelocityConfiguration (Object[] args)
Instantiates a new PD velocity configuration.
Parameters
args the args
Definition at line 65 of file PDVelocityConfiguration.java.
References com.neuronrobotics.sdk.pid.PDVelocityConfiguration.setGroup(), com.neuronrobotics.sdk.pid.PDVelocityConfiguration.setKD(), and com.neuronrobotics.sdk.pid.PDVelocityConfiguration.setKP().
Member Function Documentation
getArgs()
Object [] com.neuronrobotics.sdk.pid.PDVelocityConfiguration.getArgs ()
Gets the args.
Returns
the args
Definition at line 140 of file PDVelocityConfiguration.java.
References com.neuronrobotics.sdk.pid.PDVelocityConfiguration.group, com.neuronrobotics.sdk.pid.PDVelocityConfiguration.KD, and com.neuronrobotics.sdk.pid.PDVelocityConfiguration.KP.
Referenced by com.neuronrobotics.sdk.namespace.bcs.pid.PidNamespaceImp.ConfigurePDVelovityController(), and com.neuronrobotics.sdk.namespace.bcs.pid.PidDeviceServerNamespace.PidDeviceServerNamespace().
getGroup()
int com.neuronrobotics.sdk.pid.PDVelocityConfiguration.getGroup ()
Gets the group.
Returns
the group
Definition at line 95 of file PDVelocityConfiguration.java.
References com.neuronrobotics.sdk.pid.PDVelocityConfiguration.group.
Referenced by com.neuronrobotics.sdk.commands.bcs.pid.ConfigurePDVelocityCommand.ConfigurePDVelocityCommand(), com.neuronrobotics.sdk.pid.VirtualGenericPIDDevice.ConfigurePDVelovityController(), and com.neuronrobotics.sdk.pid.PDVelocityConfiguration.toString().
getKD()
double com.neuronrobotics.sdk.pid.PDVelocityConfiguration.getKD ()
Gets the kd.
Returns
the kd
Definition at line 131 of file PDVelocityConfiguration.java.
References com.neuronrobotics.sdk.pid.PDVelocityConfiguration.KD.
Referenced by com.neuronrobotics.sdk.commands.bcs.pid.ConfigurePDVelocityCommand.ConfigurePDVelocityCommand(), and com.neuronrobotics.sdk.pid.PDVelocityConfiguration.toString().
getKP()
double com.neuronrobotics.sdk.pid.PDVelocityConfiguration.getKP ()
Gets the kp.
Returns
the kp
Definition at line 113 of file PDVelocityConfiguration.java.
References com.neuronrobotics.sdk.pid.PDVelocityConfiguration.KP.
Referenced by com.neuronrobotics.sdk.commands.bcs.pid.ConfigurePDVelocityCommand.ConfigurePDVelocityCommand(), and com.neuronrobotics.sdk.pid.PDVelocityConfiguration.toString().
setGroup()
void com.neuronrobotics.sdk.pid.PDVelocityConfiguration.setGroup (int group)
Sets the group.
Parameters
group the new group
Definition at line 86 of file PDVelocityConfiguration.java.
References com.neuronrobotics.sdk.pid.PDVelocityConfiguration.group.
Referenced by com.neuronrobotics.sdk.pid.PDVelocityConfiguration.PDVelocityConfiguration().
setKD()
void com.neuronrobotics.sdk.pid.PDVelocityConfiguration.setKD (double kD)
Sets the kd.
Parameters
kD the new kd
Definition at line 122 of file PDVelocityConfiguration.java.
References com.neuronrobotics.sdk.pid.PDVelocityConfiguration.KD.
Referenced by com.neuronrobotics.sdk.pid.PDVelocityConfiguration.PDVelocityConfiguration().
setKP()
void com.neuronrobotics.sdk.pid.PDVelocityConfiguration.setKP (double kP)
Sets the kp.
Parameters
kP the new kp
Definition at line 104 of file PDVelocityConfiguration.java.
References com.neuronrobotics.sdk.pid.PDVelocityConfiguration.KP.
Referenced by com.neuronrobotics.sdk.pid.PDVelocityConfiguration.PDVelocityConfiguration().
toString()
String com.neuronrobotics.sdk.pid.PDVelocityConfiguration.toString ()
Definition at line 75 of file PDVelocityConfiguration.java.
References com.neuronrobotics.sdk.pid.PDVelocityConfiguration.getGroup(), com.neuronrobotics.sdk.pid.PDVelocityConfiguration.getKD(), and com.neuronrobotics.sdk.pid.PDVelocityConfiguration.getKP().
Member Data Documentation
group
int com.neuronrobotics.sdk.pid.PDVelocityConfiguration.group =0 private
The group.
Definition at line 13 of file PDVelocityConfiguration.java.
Referenced by com.neuronrobotics.sdk.pid.PDVelocityConfiguration.getArgs(), com.neuronrobotics.sdk.pid.PDVelocityConfiguration.getGroup(), com.neuronrobotics.sdk.pid.PDVelocityConfiguration.PDVelocityConfiguration(), and com.neuronrobotics.sdk.pid.PDVelocityConfiguration.setGroup().
KD
double com.neuronrobotics.sdk.pid.PDVelocityConfiguration.KD =0 private
The kd.
Definition at line 19 of file PDVelocityConfiguration.java.
Referenced by com.neuronrobotics.sdk.pid.PDVelocityConfiguration.getArgs(), com.neuronrobotics.sdk.pid.PDVelocityConfiguration.getKD(), com.neuronrobotics.sdk.pid.PDVelocityConfiguration.PDVelocityConfiguration(), and com.neuronrobotics.sdk.pid.PDVelocityConfiguration.setKD().
KP
double com.neuronrobotics.sdk.pid.PDVelocityConfiguration.KP =1 private
The kp.
Definition at line 16 of file PDVelocityConfiguration.java.
Referenced by com.neuronrobotics.sdk.pid.PDVelocityConfiguration.getArgs(), com.neuronrobotics.sdk.pid.PDVelocityConfiguration.getKP(), com.neuronrobotics.sdk.pid.PDVelocityConfiguration.PDVelocityConfiguration(), and com.neuronrobotics.sdk.pid.PDVelocityConfiguration.setKP().
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/pid/PDVelocityConfiguration.java