BowlerKernel: com.neuronrobotics.bowlerstudio.scripting.GitHubWebFlow Class Reference
com.neuronrobotics.bowlerstudio.scripting.GitHubWebFlow Class Reference
Public Member Functions
String[] prompt (String loginID)
String twoFactorAuthCodePrompt ()
Static Public Member Functions
static Supplier< String > getMyAPI ()
static void setMyAPI (Supplier< String > myAPI)
static Supplier< String > getName ()
static void setName (Supplier< String > mykey)
static IURLOpen getOpen ()
static void setOpen (IURLOpen open)
Private Member Functions
void doStepOne (String id)
void runStep2 (String id, final String code)
Static Private Attributes
static int WEBSERVER_PORT = 3737
static Supplier< String > myAPI
static Supplier< String > myname
static IURLOpen open
Detailed Description
This Class is to allow for users to request a temporary login token that will be used later to get an authorization token.
REF: https://dzone.com/articles/how-to-implement-java-oauth-20-to-sign-in-with-git-1
Author
hephaestus
Definition at line 45 of file GitHubWebFlow.java.
Member Function Documentation
doStepOne()
void com.neuronrobotics.bowlerstudio.scripting.GitHubWebFlow.doStepOne (String id) private
Definition at line 138 of file GitHubWebFlow.java.
References com.neuronrobotics.bowlerstudio.scripting.PasswordManager.getListOfScopes(), com.neuronrobotics.bowlerstudio.scripting.GitHubWebFlow.getMyAPI(), com.neuronrobotics.bowlerstudio.scripting.GitHubWebFlow.getOpen(), com.neuronrobotics.bowlerstudio.scripting.IURLOpen.open(), and com.neuronrobotics.bowlerstudio.scripting.GitHubWebFlow.WEBSERVER_PORT.
Referenced by com.neuronrobotics.bowlerstudio.scripting.GitHubWebFlow.prompt().
getMyAPI()
static Supplier<String> com.neuronrobotics.bowlerstudio.scripting.GitHubWebFlow.getMyAPI () static
Definition at line 221 of file GitHubWebFlow.java.
References com.neuronrobotics.bowlerstudio.scripting.GitHubWebFlow.myAPI.
Referenced by com.neuronrobotics.bowlerstudio.scripting.GitHubWebFlow.doStepOne(), and com.neuronrobotics.bowlerstudio.scripting.GitHubWebFlow.runStep2().
getName()
static Supplier<String> com.neuronrobotics.bowlerstudio.scripting.GitHubWebFlow.getName () static
Definition at line 229 of file GitHubWebFlow.java.
References com.neuronrobotics.bowlerstudio.scripting.GitHubWebFlow.myname.
Referenced by com.neuronrobotics.bowlerstudio.scripting.GitHubWebFlow.runStep2().
getOpen()
static IURLOpen com.neuronrobotics.bowlerstudio.scripting.GitHubWebFlow.getOpen () static
Definition at line 236 of file GitHubWebFlow.java.
References com.neuronrobotics.bowlerstudio.scripting.GitHubWebFlow.open.
Referenced by com.neuronrobotics.bowlerstudio.scripting.GitHubWebFlow.doStepOne().
prompt()
String [] com.neuronrobotics.bowlerstudio.scripting.GitHubWebFlow.prompt (String loginID)
Prompt user for login information and return when it has been entered
Returns
an array of strings of length 2 that contains the username in the 0th index, and the password in the 1th index
Implements com.neuronrobotics.bowlerstudio.scripting.IGitHubLoginManager.
Definition at line 63 of file GitHubWebFlow.java.
References com.neuronrobotics.bowlerstudio.scripting.GitHubWebFlow.doStepOne(), com.neuronrobotics.bowlerstudio.scripting.GitHubWebFlow.runStep2(), and com.neuronrobotics.bowlerstudio.scripting.GitHubWebFlow.WEBSERVER_PORT.
runStep2()
void com.neuronrobotics.bowlerstudio.scripting.GitHubWebFlow.runStep2 (String id, final String code) private
Definition at line 168 of file GitHubWebFlow.java.
References com.neuronrobotics.bowlerstudio.scripting.GitHubWebFlow.getMyAPI(), and com.neuronrobotics.bowlerstudio.scripting.GitHubWebFlow.getName().
Referenced by com.neuronrobotics.bowlerstudio.scripting.GitHubWebFlow.prompt().
setMyAPI()
static void com.neuronrobotics.bowlerstudio.scripting.GitHubWebFlow.setMyAPI (Supplier< String > myAPI) static
Definition at line 225 of file GitHubWebFlow.java.
References com.neuronrobotics.bowlerstudio.scripting.GitHubWebFlow.myAPI.
setName()
static void com.neuronrobotics.bowlerstudio.scripting.GitHubWebFlow.setName (Supplier< String > mykey) static
Definition at line 233 of file GitHubWebFlow.java.
References com.neuronrobotics.bowlerstudio.scripting.GitHubWebFlow.myname.
setOpen()
static void com.neuronrobotics.bowlerstudio.scripting.GitHubWebFlow.setOpen (IURLOpen open) static
Definition at line 239 of file GitHubWebFlow.java.
References com.neuronrobotics.bowlerstudio.scripting.GitHubWebFlow.open.
twoFactorAuthCodePrompt()
String com.neuronrobotics.bowlerstudio.scripting.GitHubWebFlow.twoFactorAuthCodePrompt ()
prompt the user for a 2 factor authentication code
Returns
a string containing the OTP code from the user
Implements com.neuronrobotics.bowlerstudio.scripting.IGitHubLoginManager.
Definition at line 216 of file GitHubWebFlow.java.
Member Data Documentation
myAPI
Supplier<String> com.neuronrobotics.bowlerstudio.scripting.GitHubWebFlow.myAPI static private
Initial value:
= () -> {
        return "1edf79fae494c232d4d2";
    }
Definition at line 48 of file GitHubWebFlow.java.
Referenced by com.neuronrobotics.bowlerstudio.scripting.GitHubWebFlow.getMyAPI(), and com.neuronrobotics.bowlerstudio.scripting.GitHubWebFlow.setMyAPI().
myname
Supplier<String> com.neuronrobotics.bowlerstudio.scripting.GitHubWebFlow.myname static private
Initial value:
=() -> {
        JFrame jframe = new JFrame();
        jframe.setAlwaysOnTop(true);
        String answer = JOptionPane.showInputDialog(jframe, "Enter API secret");
        jframe.dispose();
        return answer;
    }
Definition at line 51 of file GitHubWebFlow.java.
Referenced by com.neuronrobotics.bowlerstudio.scripting.GitHubWebFlow.getName(), and com.neuronrobotics.bowlerstudio.scripting.GitHubWebFlow.setName().
open
IURLOpen com.neuronrobotics.bowlerstudio.scripting.GitHubWebFlow.open static private
Initial value:
= new IURLOpen() {
    }
Definition at line 58 of file GitHubWebFlow.java.
Referenced by com.neuronrobotics.bowlerstudio.scripting.GitHubWebFlow.getOpen(), and com.neuronrobotics.bowlerstudio.scripting.GitHubWebFlow.setOpen().
WEBSERVER_PORT
int com.neuronrobotics.bowlerstudio.scripting.GitHubWebFlow.WEBSERVER_PORT = 3737 static private
Definition at line 46 of file GitHubWebFlow.java.
Referenced by com.neuronrobotics.bowlerstudio.scripting.GitHubWebFlow.doStepOne(), and com.neuronrobotics.bowlerstudio.scripting.GitHubWebFlow.prompt().
The documentation for this class was generated from the following file:
GithubPasswordManager/GithubPasswordManager/src/main/java/com/neuronrobotics/bowlerstudio/scripting/GitHubWebFlow.java