BowlerKernel: com.neuronrobotics.sdk.dyio.peripherals.DigitalOutputChannel Class Reference
com.neuronrobotics.sdk.dyio.peripherals.DigitalOutputChannel Class Reference
Public Member Functions
DigitalOutputChannel (int channel)
DigitalOutputChannel (DyIO dyio, int channel)
DigitalOutputChannel (DyIOChannel channel)
boolean setHigh (boolean high)
boolean isHigh ()
boolean hasAsync ()
Public Member Functions inherited from com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral
DyIOAbstractPeripheral (DyIOChannel channel, DyIOChannelMode myMode, boolean async)
DyIOChannelMode getClassMode ()
boolean isEnabled ()
boolean setMode ()
boolean setMode (boolean async)
boolean setMode (DyIOChannelMode mode, boolean async)
DyIOChannel getChannel ()
DyIOChannelMode getMode ()
boolean setValue (int value) throws InvalidResponseException
boolean setValue (ByteList value) throws InvalidResponseException
int getValue () throws InvalidResponseException
boolean SavePosition (int pos)
boolean configAdvancedAsyncNotEqual ()
boolean configAdvancedAsyncDeadBand (int deadbandSize)
boolean configAdvancedAsyncTreshhold (int threshholdValue, AsyncThreshholdEdgeType edgeType)
boolean configAdvancedAsyncAutoSample ()
boolean configAdvancedAsyncNotEqual (int msTime)
boolean configAdvancedAsyncDeadBand (int msTime, int deadbandSize)
boolean configAdvancedAsyncTreshhold (int msTime, int threshholdValue, AsyncThreshholdEdgeType edgeType)
boolean configAdvancedAsyncAutoSample (int msTime)
boolean flush ()
void setAsync (boolean b)
int getConfiguration ()
Detailed Description
The Class DigitalOutputChannel.
Definition at line 26 of file DigitalOutputChannel.java.
Constructor & Destructor Documentation
DigitalOutputChannel() [1/3]
com.neuronrobotics.sdk.dyio.peripherals.DigitalOutputChannel.DigitalOutputChannel (int channel)
Constructor. Creates an counter input input channel that is syncronous only by default.
Parameters
channel - the channel object requested from the DyIO
Definition at line 33 of file DigitalOutputChannel.java.
References com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral.channel, com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral.getChannel(), and com.neuronrobotics.sdk.common.DeviceManager.getSpecificDevice().
DigitalOutputChannel() [2/3]
com.neuronrobotics.sdk.dyio.peripherals.DigitalOutputChannel.DigitalOutputChannel (DyIO dyio, int channel)
Constructor. Creates an counter input input channel that is syncronous only by default.
Parameters
dyio the dyio
channel - the channel object requested from the DyIO
Definition at line 44 of file DigitalOutputChannel.java.
References com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral.channel, and com.neuronrobotics.sdk.dyio.DyIO.getChannel().
DigitalOutputChannel() [3/3]
com.neuronrobotics.sdk.dyio.peripherals.DigitalOutputChannel.DigitalOutputChannel (DyIOChannel channel)
DigitalOutChannel.
Parameters
channel The channel object to set up as a digital output
Definition at line 55 of file DigitalOutputChannel.java.
References com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral.channel, com.neuronrobotics.sdk.dyio.DyIOChannelMode.DIGITAL_OUT, and com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral.setMode().
Member Function Documentation
hasAsync()
boolean com.neuronrobotics.sdk.dyio.peripherals.DigitalOutputChannel.hasAsync ()
This method is to check if this peripheral is capable to be set as up as asynchronous.
Returns
if it cna be async
Reimplemented from com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral.
Definition at line 87 of file DigitalOutputChannel.java.
isHigh()
boolean com.neuronrobotics.sdk.dyio.peripherals.DigitalOutputChannel.isHigh ()
isHigh.
Returns
the state of the pin
Definition at line 79 of file DigitalOutputChannel.java.
References com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral.getValue().
setHigh()
boolean com.neuronrobotics.sdk.dyio.peripherals.DigitalOutputChannel.setHigh (boolean high)
setHigh.
Parameters
high boolean to set high or not high
Returns
if it worked
Definition at line 70 of file DigitalOutputChannel.java.
References com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral.setValue().
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/dyio/peripherals/DigitalOutputChannel.java