BowlerKernel: com.neuronrobotics.sdk.dyio.DyIOInputStream Class Reference
com.neuronrobotics.sdk.dyio.DyIOInputStream Class Reference
Public Member Functions
DyIOInputStream (DyIOChannel channel)
void write (ByteList data)
int read () throws IOException
int available ()
Private Attributes
ByteList buffer = new ByteList()
Detailed Description
The Class DyIOInputStream.
Definition at line 26 of file DyIOInputStream.java.
Constructor & Destructor Documentation
DyIOInputStream()
com.neuronrobotics.sdk.dyio.DyIOInputStream.DyIOInputStream (DyIOChannel channel)
Instantiates a new dy io input stream.
Parameters
channel the channel
Definition at line 39 of file DyIOInputStream.java.
Member Function Documentation
available()
int com.neuronrobotics.sdk.dyio.DyIOInputStream.available ()
Definition at line 79 of file DyIOInputStream.java.
References com.neuronrobotics.sdk.dyio.DyIOInputStream.buffer, and com.neuronrobotics.sdk.common.ByteList.size().
Referenced by com.neuronrobotics.sdk.dyio.peripherals.UARTChannel.UARTRxChannel.getInStreamSize(), and com.neuronrobotics.sdk.dyio.DyIOInputStream.read().
read()
int com.neuronrobotics.sdk.dyio.DyIOInputStream.read () throws IOException
Definition at line 58 of file DyIOInputStream.java.
References com.neuronrobotics.sdk.dyio.DyIOInputStream.available(), com.neuronrobotics.sdk.dyio.DyIOInputStream.buffer, com.neuronrobotics.sdk.dyio.DyIOChannel.getMode(), com.neuronrobotics.sdk.common.ByteList.pop(), and com.neuronrobotics.sdk.dyio.DyIOChannelMode.USART_RX.
Referenced by com.neuronrobotics.sdk.dyio.peripherals.UARTChannel.UARTRxChannel.getBytes().
write()
void com.neuronrobotics.sdk.dyio.DyIOInputStream.write (ByteList data)
Write.
Parameters
data the data
Definition at line 48 of file DyIOInputStream.java.
References com.neuronrobotics.sdk.common.ByteList.add(), and com.neuronrobotics.sdk.dyio.DyIOInputStream.buffer.
Referenced by com.neuronrobotics.sdk.dyio.peripherals.UARTChannel.UARTRxChannel.onChannelEvent().
Member Data Documentation
buffer
ByteList com.neuronrobotics.sdk.dyio.DyIOInputStream.buffer = new ByteList() private
The buffer.
Definition at line 29 of file DyIOInputStream.java.
Referenced by com.neuronrobotics.sdk.dyio.DyIOInputStream.available(), com.neuronrobotics.sdk.dyio.DyIOInputStream.read(), and com.neuronrobotics.sdk.dyio.DyIOInputStream.write().
The documentation for this class was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/dyio/DyIOInputStream.java