BowlerKernel: com.neuronrobotics.sdk.common.BowlerDataType Enum Reference
com.neuronrobotics.sdk.common.BowlerDataType Enum Reference
Public Member Functions
byte getValue ()
byte[] getBytes ()
String toString ()
Static Public Member Functions
[static initializer]
static BowlerDataType get (byte code)
Public Attributes
I08 =(8)
I16 =(16)
I32 =(32)
STR =(37)
I32STR =(38)
ASCII =(39)
FIXED100 =(41)
FIXED1k =(42)
BOOL =(43)
FIXED1k_STR =(44)
INVALID =(0)
Private Member Functions
BowlerDataType (int val)
Private Attributes
byte value =0
Static Private Attributes
static final Map< Byte, BowlerDataType > lookup = new HashMap<Byte,BowlerDataType>()
Detailed Description
The Enum BowlerMethod.
Definition at line 25 of file BowlerDataType.java.
Constructor & Destructor Documentation
BowlerDataType()
com.neuronrobotics.sdk.common.BowlerDataType.BowlerDataType (int val) private
Instantiates a new bowler method.
Parameters
val the val
Definition at line 78 of file BowlerDataType.java.
Member Function Documentation
[static initializer]()
com.neuronrobotics.sdk.common.BowlerDataType.[static initializer] static
get()
static BowlerDataType com.neuronrobotics.sdk.common.BowlerDataType.get (byte code) static
Gets the.
Parameters
code the code
Returns
the bowler method
Definition at line 97 of file BowlerDataType.java.
References com.neuronrobotics.sdk.common.BowlerDataType.get(), and com.neuronrobotics.sdk.common.BowlerDataType.INVALID.
Referenced by com.neuronrobotics.sdk.common.BowlerDataType.get(), and com.neuronrobotics.sdk.common.BowlerAbstractConnection.getRpcList().
getBytes()
byte [] com.neuronrobotics.sdk.common.BowlerDataType.getBytes ()
Gets the bytes.
Returns
the bytes
Implements com.neuronrobotics.sdk.common.ISendable.
Definition at line 115 of file BowlerDataType.java.
getValue()
byte com.neuronrobotics.sdk.common.BowlerDataType.getValue ()
Gets the value.
Returns
the value
Definition at line 87 of file BowlerDataType.java.
toString()
String com.neuronrobotics.sdk.common.BowlerDataType.toString ()
Definition at line 123 of file BowlerDataType.java.
Member Data Documentation
ASCII
com.neuronrobotics.sdk.common.BowlerDataType.ASCII =(39)
ASCII String null terminated.
Definition at line 43 of file BowlerDataType.java.
Referenced by com.neuronrobotics.sdk.common.device.server.bcs.core.BcsCoreNamespaceImp.BcsCoreNamespaceImp().
BOOL
com.neuronrobotics.sdk.common.BowlerDataType.BOOL =(43)
Boolean value, 0 is false, not 0 is true.
Definition at line 52 of file BowlerDataType.java.
FIXED100
com.neuronrobotics.sdk.common.BowlerDataType.FIXED100 =(41)
Signed Fixed point times 100.
Definition at line 46 of file BowlerDataType.java.
Referenced by com.neuronrobotics.sdk.namespace.bcs.pid.PidDeviceServerNamespace.PidDeviceServerNamespace().
FIXED1k
com.neuronrobotics.sdk.common.BowlerDataType.FIXED1k =(42)
Signed Fixed point times 1000.
Definition at line 49 of file BowlerDataType.java.
Referenced by com.neuronrobotics.sdk.namespace.bcs.pid.PidDeviceServerNamespace.PidDeviceServerNamespace().
FIXED1k_STR
com.neuronrobotics.sdk.common.BowlerDataType.FIXED1k_STR =(44)
stream of floats, first byte is unsigned char to indicate number of data values in the stream.
Definition at line 55 of file BowlerDataType.java.
I08
com.neuronrobotics.sdk.common.BowlerDataType.I08 =(8)
8 bit unsigned int.
Definition at line 28 of file BowlerDataType.java.
Referenced by com.neuronrobotics.sdk.common.device.server.bcs.core.BcsCoreNamespaceImp.BcsCoreNamespaceImp(), com.neuronrobotics.sdk.common.device.server.bcs.rpc.BcsRpcNamespaceImp.BcsRpcNamespaceImp(), and com.neuronrobotics.sdk.namespace.bcs.pid.PidDeviceServerNamespace.PidDeviceServerNamespace().
I16
com.neuronrobotics.sdk.common.BowlerDataType.I16 =(16)
16 bit signed int.
Definition at line 31 of file BowlerDataType.java.
I32
com.neuronrobotics.sdk.common.BowlerDataType.I32 =(32)
32 bit signed int.
Definition at line 34 of file BowlerDataType.java.
Referenced by com.neuronrobotics.sdk.namespace.bcs.pid.PidDeviceServerNamespace.PidDeviceServerNamespace().
I32STR
com.neuronrobotics.sdk.common.BowlerDataType.I32STR =(38)
stream of 32 bit signed ints, first byte is unsigned char to indicate number of data values in the stream.
Definition at line 40 of file BowlerDataType.java.
Referenced by com.neuronrobotics.sdk.namespace.bcs.pid.PidDeviceServerNamespace.PidDeviceServerNamespace().
INVALID
com.neuronrobotics.sdk.common.BowlerDataType.INVALID =(0)
Unknown*.
Definition at line 58 of file BowlerDataType.java.
Referenced by com.neuronrobotics.sdk.common.BowlerDataType.get().
lookup
final Map<Byte,BowlerDataType> com.neuronrobotics.sdk.common.BowlerDataType.lookup = new HashMap<Byte,BowlerDataType>() static private
The Constant lookup.
Definition at line 62 of file BowlerDataType.java.
STR
com.neuronrobotics.sdk.common.BowlerDataType.STR =(37)
stream of 8 bit unsigned ints, first byte is unsigned char to indicate number of data values in the stream.
Definition at line 37 of file BowlerDataType.java.
Referenced by com.neuronrobotics.sdk.common.device.server.bcs.rpc.BcsRpcNamespaceImp.BcsRpcNamespaceImp().
value
byte com.neuronrobotics.sdk.common.BowlerDataType.value =0 private
The value.
Definition at line 64 of file BowlerDataType.java.
The documentation for this enum was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/common/BowlerDataType.java