BowlerKernel: com.neuronrobotics.bowlerstudio.AudioStatus Enum Reference
com.neuronrobotics.bowlerstudio.AudioStatus Enum Reference
Public Member Functions
double mouthOpenVector ()
boolean isOpen ()
AudioStatus (char self)
Static Public Member Functions
[static initializer]
static AudioStatus get (char code)
static AudioStatus get (String code)
static AudioStatus getFromPhoneme (String code)
static Set< String > getPhonemes ()
Public Attributes
A_PBM_SOUNDS =('A')
B_KST_SOUNDS =('B')
C_EH_AE_SOUNDS =('C')
D_AA_SOUNDS =('D')
E_AO_ER_SOUNDS =('E')
F_UW_OW_W_SOUNDS =('F')
G_F_V_SOUNDS =('G')
H_L_SOUNDS =('H')
X_NO_SOUND =('X')
I_user_defined =('I')
J_user_defined =('J')
K_user_defined =('K')
L_user_defined =('L')
M_user_defined =('M')
final char parsed
Static Private Attributes
static final Map< Character, AudioStatus > lookup = new HashMap<>()
static Map< String, AudioStatus > ArpabetToBlair
Detailed Description
Define the types of mouth shapes
content from https://github.com/DanielSWolf/rhubarb-lip-sync
Author
hephaestus
Definition at line 15 of file AudioStatus.java.
Constructor & Destructor Documentation
AudioStatus()
com.neuronrobotics.bowlerstudio.AudioStatus.AudioStatus (char self)
Definition at line 225 of file AudioStatus.java.
Member Function Documentation
[static initializer]()
com.neuronrobotics.bowlerstudio.AudioStatus.[static initializer] static
References com.neuronrobotics.bowlerstudio.AudioStatus.A_PBM_SOUNDS, com.neuronrobotics.bowlerstudio.AudioStatus.ArpabetToBlair, com.neuronrobotics.bowlerstudio.AudioStatus.B_KST_SOUNDS, com.neuronrobotics.bowlerstudio.AudioStatus.C_EH_AE_SOUNDS, com.neuronrobotics.bowlerstudio.AudioStatus.D_AA_SOUNDS, com.neuronrobotics.bowlerstudio.AudioStatus.E_AO_ER_SOUNDS, com.neuronrobotics.bowlerstudio.AudioStatus.F_UW_OW_W_SOUNDS, com.neuronrobotics.bowlerstudio.AudioStatus.G_F_V_SOUNDS, com.neuronrobotics.bowlerstudio.AudioStatus.H_L_SOUNDS, and com.neuronrobotics.bowlerstudio.AudioStatus.X_NO_SOUND.
get() [1/2]
static AudioStatus com.neuronrobotics.bowlerstudio.AudioStatus.get (char code) static
Definition at line 174 of file AudioStatus.java.
References com.neuronrobotics.bowlerstudio.AudioStatus.get().
Referenced by com.neuronrobotics.bowlerstudio.AudioStatus.get(), com.neuronrobotics.bowlerstudio.AudioStatus.getFromPhoneme(), com.neuronrobotics.bowlerstudio.lipsync.RhubarbManager.processRaw(), com.neuronrobotics.bowlerstudio.lipsync.RhubarbManager.update(), and com.neuronrobotics.bowlerstudio.lipsync.VoskLipSync.update().
get() [2/2]
static AudioStatus com.neuronrobotics.bowlerstudio.AudioStatus.get (String code) static
Definition at line 177 of file AudioStatus.java.
References com.neuronrobotics.bowlerstudio.AudioStatus.get().
getFromPhoneme()
static AudioStatus com.neuronrobotics.bowlerstudio.AudioStatus.getFromPhoneme (String code) static
Definition at line 180 of file AudioStatus.java.
References com.neuronrobotics.bowlerstudio.AudioStatus.get().
Referenced by com.neuronrobotics.bowlerstudio.lipsync.PhoneticDictionary.find(), and com.neuronrobotics.bowlerstudio.lipsync.VoskLipSync.toStatus().
getPhonemes()
static Set<String> com.neuronrobotics.bowlerstudio.AudioStatus.getPhonemes () static
Definition at line 183 of file AudioStatus.java.
Referenced by com.neuronrobotics.bowlerstudio.lipsync.PhoneticDictionary.find().
isOpen()
boolean com.neuronrobotics.bowlerstudio.AudioStatus.isOpen ()
Definition at line 212 of file AudioStatus.java.
mouthOpenVector()
double com.neuronrobotics.bowlerstudio.AudioStatus.mouthOpenVector ()
Definition at line 187 of file AudioStatus.java.
Member Data Documentation
A_PBM_SOUNDS
com.neuronrobotics.bowlerstudio.AudioStatus.A_PBM_SOUNDS =('A')
Definition at line 20 of file AudioStatus.java.
Referenced by com.neuronrobotics.bowlerstudio.AudioStatus.[static initializer](), and com.neuronrobotics.bowlerstudio.lipsync.VoskLipSync.addWord().
ArpabetToBlair
Map<String, AudioStatus> com.neuronrobotics.bowlerstudio.AudioStatus.ArpabetToBlair static private
Definition at line 93 of file AudioStatus.java.
Referenced by com.neuronrobotics.bowlerstudio.AudioStatus.[static initializer]().
B_KST_SOUNDS
com.neuronrobotics.bowlerstudio.AudioStatus.B_KST_SOUNDS =('B')
Definition at line 26 of file AudioStatus.java.
Referenced by com.neuronrobotics.bowlerstudio.AudioStatus.[static initializer](), and com.neuronrobotics.bowlerstudio.lipsync.VoskLipSync.addWord().
C_EH_AE_SOUNDS
com.neuronrobotics.bowlerstudio.AudioStatus.C_EH_AE_SOUNDS =('C')
Definition at line 34 of file AudioStatus.java.
Referenced by com.neuronrobotics.bowlerstudio.AudioStatus.[static initializer](), and com.neuronrobotics.bowlerstudio.lipsync.VoskLipSync.addWord().
D_AA_SOUNDS
com.neuronrobotics.bowlerstudio.AudioStatus.D_AA_SOUNDS =('D')
Definition at line 38 of file AudioStatus.java.
Referenced by com.neuronrobotics.bowlerstudio.AudioStatus.[static initializer](), and com.neuronrobotics.bowlerstudio.lipsync.VoskLipSync.addWord().
E_AO_ER_SOUNDS
com.neuronrobotics.bowlerstudio.AudioStatus.E_AO_ER_SOUNDS =('E')
Definition at line 47 of file AudioStatus.java.
Referenced by com.neuronrobotics.bowlerstudio.AudioStatus.[static initializer](), and com.neuronrobotics.bowlerstudio.lipsync.VoskLipSync.addWord().
F_UW_OW_W_SOUNDS
com.neuronrobotics.bowlerstudio.AudioStatus.F_UW_OW_W_SOUNDS =('F')
Definition at line 52 of file AudioStatus.java.
Referenced by com.neuronrobotics.bowlerstudio.AudioStatus.[static initializer](), and com.neuronrobotics.bowlerstudio.lipsync.VoskLipSync.addWord().
G_F_V_SOUNDS
com.neuronrobotics.bowlerstudio.AudioStatus.G_F_V_SOUNDS =('G')
Definition at line 60 of file AudioStatus.java.
Referenced by com.neuronrobotics.bowlerstudio.AudioStatus.[static initializer]().
H_L_SOUNDS
com.neuronrobotics.bowlerstudio.AudioStatus.H_L_SOUNDS =('H')
Definition at line 71 of file AudioStatus.java.
Referenced by com.neuronrobotics.bowlerstudio.AudioStatus.[static initializer](), and com.neuronrobotics.bowlerstudio.lipsync.VoskLipSync.addWord().
I_user_defined
com.neuronrobotics.bowlerstudio.AudioStatus.I_user_defined =('I')
Definition at line 86 of file AudioStatus.java.
J_user_defined
com.neuronrobotics.bowlerstudio.AudioStatus.J_user_defined =('J')
Definition at line 87 of file AudioStatus.java.
K_user_defined
com.neuronrobotics.bowlerstudio.AudioStatus.K_user_defined =('K')
Definition at line 88 of file AudioStatus.java.
L_user_defined
com.neuronrobotics.bowlerstudio.AudioStatus.L_user_defined =('L')
Definition at line 89 of file AudioStatus.java.
lookup
final Map<Character, AudioStatus> com.neuronrobotics.bowlerstudio.AudioStatus.lookup = new HashMap<>() static private
Definition at line 92 of file AudioStatus.java.
M_user_defined
com.neuronrobotics.bowlerstudio.AudioStatus.M_user_defined =('M')
Definition at line 90 of file AudioStatus.java.
parsed
final char com.neuronrobotics.bowlerstudio.AudioStatus.parsed
Definition at line 172 of file AudioStatus.java.
X_NO_SOUND
com.neuronrobotics.bowlerstudio.AudioStatus.X_NO_SOUND =('X')
Definition at line 83 of file AudioStatus.java.
Referenced by com.neuronrobotics.bowlerstudio.AudioStatus.[static initializer](), com.neuronrobotics.bowlerstudio.lipsync.VoskLipSync.addWord(), com.neuronrobotics.bowlerstudio.lipsync.VoskLipSync.processRaw(), com.neuronrobotics.bowlerstudio.AudioPlayer.run(), com.neuronrobotics.bowlerstudio.lipsync.VoskLipSync.toStatus(), com.neuronrobotics.bowlerstudio.lipsync.RhubarbManager.update(), and com.neuronrobotics.bowlerstudio.lipsync.VoskLipSync.update().
The documentation for this enum was generated from the following file:
src/main/java/com/neuronrobotics/bowlerstudio/AudioStatus.java