BowlerKernel: com.neuronrobotics.sdk.dyio.DyIOChannelMode Enum Reference
com.neuronrobotics.sdk.dyio.DyIOChannelMode Enum Reference
Public Member Functions
byte getValue ()
String toString ()
String toSlug ()
byte[] getBytes ()
Static Public Member Functions
[static initializer]
static Collection< DyIOChannelMode > getModes ()
static DyIOChannelMode get (byte code)
static DyIOChannelMode getFromSlug (String slug)
Public Attributes
NO_CHANGE =(0x00, "No Change")
OFF =(0x01, "Off")
DIGITAL_IN =(0x02, "Digital In")
DIGITAL_OUT =(0x03, "Digital Out")
ANALOG_IN =(0x04, "Analog In")
ANALOG_OUT =(0x05, "Analog Out")
PWM_OUT =(0x06, "PWM Out")
SERVO_OUT =(0x07, "Servo Out")
USART_TX =(0x08, "USART Tx")
USART_RX =(0x09, "USART Rx")
SPI_MOSI =(0x0A, "SPI MoSi")
SPI_MISO =(0x0B, "SPI MiSo")
SPI_CLOCK =(0x0C, "SPI Clock")
SPI_SELECT =(0x0D, "SPI Select")
COUNT_IN_INT =(0x0E, "Counter In Int")
COUNT_IN_DIR =(0x0F, "Counter In Dir")
COUNT_IN_HOME =(0x10, "Counter In Home")
COUNT_OUT_INT =(0x11, "Counter Out Int")
COUNT_OUT_DIR =(0x12, "Counter Out Dir")
COUNT_OUT_HOME =(0x13, "Counter Out Home")
DC_MOTOR_VEL =(0x14, "DC Motor Velocity")
DC_MOTOR_DIR =(0x15, "DC Motor Direction")
PPM_IN =(0x16, "PPM Reader")
DEBUG_TX =(0x17, "DEBUG_TX")
DEBUG_RX =(0x18, "DEBUG_RX")
Private Member Functions
DyIOChannelMode (int val, String name)
Private Attributes
byte value
String readableName
Static Private Attributes
static final Map< Byte, DyIOChannelMode > lookup = new HashMap<Byte,DyIOChannelMode>()
Detailed Description
An enumeration of all the possible DyIO channel modes.
Author
rbreznak
Definition at line 29 of file DyIOChannelMode.java.
Constructor & Destructor Documentation
DyIOChannelMode()
com.neuronrobotics.sdk.dyio.DyIOChannelMode.DyIOChannelMode (int val, String name) private
Instantiates a new dy io channel mode.
Parameters
val the val
name the name
Definition at line 126 of file DyIOChannelMode.java.
Member Function Documentation
[static initializer]()
com.neuronrobotics.sdk.dyio.DyIOChannelMode.[static initializer] static
get()
static DyIOChannelMode com.neuronrobotics.sdk.dyio.DyIOChannelMode.get (byte code) static
Gets the.
Parameters
code the code
Returns
the dy io channel mode
Definition at line 155 of file DyIOChannelMode.java.
References com.neuronrobotics.sdk.dyio.DyIOChannelMode.get().
Referenced by com.neuronrobotics.sdk.dyio.dypid.DyPIDConfiguration.DyPIDConfiguration(), com.neuronrobotics.sdk.dyio.DyIOChannelMode.get(), com.neuronrobotics.sdk.dyio.DyIO.getAllChannelModes(), com.neuronrobotics.sdk.dyio.DyIO.getAvailibleChannelModes(), com.neuronrobotics.sdk.dyio.DyIO.resync(), com.neuronrobotics.sdk.dyio.DyIOChannel.resync(), and com.neuronrobotics.sdk.dyio.DyIOChannel.setMode().
getBytes()
byte [] com.neuronrobotics.sdk.dyio.DyIOChannelMode.getBytes ()
Gets the bytes.
Returns
the bytes
Implements com.neuronrobotics.sdk.common.ISendable.
Definition at line 195 of file DyIOChannelMode.java.
getFromSlug()
static DyIOChannelMode com.neuronrobotics.sdk.dyio.DyIOChannelMode.getFromSlug (String slug) static
Gets the from slug.
Parameters
slug the slug
Returns
the from slug
Definition at line 167 of file DyIOChannelMode.java.
getModes()
static Collection<DyIOChannelMode> com.neuronrobotics.sdk.dyio.DyIOChannelMode.getModes () static
Gets the modes.
Returns
the modes
Definition at line 136 of file DyIOChannelMode.java.
getValue()
byte com.neuronrobotics.sdk.dyio.DyIOChannelMode.getValue ()
Gets the value.
Returns
the value
Definition at line 145 of file DyIOChannelMode.java.
Referenced by com.neuronrobotics.sdk.commands.bcs.pid.DyPID.ConfigureDynamicPIDCommand.ConfigureDynamicPIDCommand().
toSlug()
String com.neuronrobotics.sdk.dyio.DyIOChannelMode.toSlug ()
To slug.
Returns
the string
Definition at line 187 of file DyIOChannelMode.java.
Referenced by com.neuronrobotics.application.xmpp.DyIOConversation.onMessage().
toString()
String com.neuronrobotics.sdk.dyio.DyIOChannelMode.toString ()
Definition at line 178 of file DyIOChannelMode.java.
Referenced by com.neuronrobotics.sdk.dyio.DyIO.getAvailibleChannelModes().
Member Data Documentation
ANALOG_IN
com.neuronrobotics.sdk.dyio.DyIOChannelMode.ANALOG_IN =(0x04, "Analog In")
The analog in.
Definition at line 44 of file DyIOChannelMode.java.
Referenced by com.neuronrobotics.sdk.dyio.peripherals.AnalogInputChannel.AnalogInputChannel(), and com.neuronrobotics.sdk.dyio.peripherals.AnalogInputChannel.setAsync().
ANALOG_OUT
com.neuronrobotics.sdk.dyio.DyIOChannelMode.ANALOG_OUT =(0x05, "Analog Out")
The analog out.
Definition at line 47 of file DyIOChannelMode.java.
COUNT_IN_DIR
com.neuronrobotics.sdk.dyio.DyIOChannelMode.COUNT_IN_DIR =(0x0F, "Counter In Dir")
The count in dir.
Definition at line 77 of file DyIOChannelMode.java.
COUNT_IN_HOME
com.neuronrobotics.sdk.dyio.DyIOChannelMode.COUNT_IN_HOME =(0x10, "Counter In Home")
The count in home.
Definition at line 80 of file DyIOChannelMode.java.
COUNT_IN_INT
com.neuronrobotics.sdk.dyio.DyIOChannelMode.COUNT_IN_INT =(0x0E, "Counter In Int")
The count in int.
Definition at line 74 of file DyIOChannelMode.java.
Referenced by com.neuronrobotics.sdk.dyio.peripherals.CounterInputChannel.CounterInputChannel(), com.neuronrobotics.sdk.dyio.peripherals.CounterInputChannel.init(), and com.neuronrobotics.sdk.dyio.peripherals.CounterInputChannel.setAsync().
COUNT_OUT_DIR
com.neuronrobotics.sdk.dyio.DyIOChannelMode.COUNT_OUT_DIR =(0x12, "Counter Out Dir")
The count out dir.
Definition at line 86 of file DyIOChannelMode.java.
COUNT_OUT_HOME
com.neuronrobotics.sdk.dyio.DyIOChannelMode.COUNT_OUT_HOME =(0x13, "Counter Out Home")
The count out home.
Definition at line 89 of file DyIOChannelMode.java.
COUNT_OUT_INT
com.neuronrobotics.sdk.dyio.DyIOChannelMode.COUNT_OUT_INT =(0x11, "Counter Out Int")
The count out int.
Definition at line 83 of file DyIOChannelMode.java.
Referenced by com.neuronrobotics.sdk.dyio.peripherals.CounterOutputChannel.CounterOutputChannel(), com.neuronrobotics.sdk.dyio.peripherals.CounterOutputChannel.init(), com.neuronrobotics.sdk.dyio.peripherals.CounterOutputChannel.setAsync(), and com.neuronrobotics.sdk.dyio.peripherals.CounterOutputChannel.validate().
DC_MOTOR_DIR
com.neuronrobotics.sdk.dyio.DyIOChannelMode.DC_MOTOR_DIR =(0x15, "DC Motor Direction")
The dc motor dir.
Definition at line 95 of file DyIOChannelMode.java.
DC_MOTOR_VEL
com.neuronrobotics.sdk.dyio.DyIOChannelMode.DC_MOTOR_VEL =(0x14, "DC Motor Velocity")
The dc motor vel.
Definition at line 92 of file DyIOChannelMode.java.
Referenced by com.neuronrobotics.sdk.dyio.peripherals.DCMotorOutputChannel.DCMotorOutputChannel().
DEBUG_RX
com.neuronrobotics.sdk.dyio.DyIOChannelMode.DEBUG_RX =(0x18, "DEBUG_RX")
DEBUG_RX
Definition at line 103 of file DyIOChannelMode.java.
DEBUG_TX
com.neuronrobotics.sdk.dyio.DyIOChannelMode.DEBUG_TX =(0x17, "DEBUG_TX")
DEBUG_TX
Definition at line 100 of file DyIOChannelMode.java.
DIGITAL_IN
com.neuronrobotics.sdk.dyio.DyIOChannelMode.DIGITAL_IN =(0x02, "Digital In")
The digital in.
Definition at line 38 of file DyIOChannelMode.java.
Referenced by com.neuronrobotics.sdk.dyio.peripherals.DigitalInputChannel.DigitalInputChannel(), com.neuronrobotics.sdk.dyio.DyIOChannel.fireModeChangeEvent(), com.neuronrobotics.application.xmpp.DyIOConversation.onMessage(), and com.neuronrobotics.sdk.dyio.peripherals.DigitalInputChannel.setAsync().
DIGITAL_OUT
com.neuronrobotics.sdk.dyio.DyIOChannelMode.DIGITAL_OUT =(0x03, "Digital Out")
The digital out.
Definition at line 41 of file DyIOChannelMode.java.
Referenced by com.neuronrobotics.sdk.dyio.peripherals.DigitalOutputChannel.DigitalOutputChannel(), and com.neuronrobotics.sdk.dyio.DyIO.resync().
lookup
final Map<Byte,DyIOChannelMode> com.neuronrobotics.sdk.dyio.DyIOChannelMode.lookup = new HashMap<Byte,DyIOChannelMode>() static private
The Constant lookup.
Definition at line 106 of file DyIOChannelMode.java.
NO_CHANGE
com.neuronrobotics.sdk.dyio.DyIOChannelMode.NO_CHANGE =(0x00, "No Change")
The no change.
Definition at line 32 of file DyIOChannelMode.java.
Referenced by com.neuronrobotics.sdk.dyio.DyIOChannel.update().
OFF
com.neuronrobotics.sdk.dyio.DyIOChannelMode.OFF =(0x01, "Off")
The off.
Definition at line 35 of file DyIOChannelMode.java.
PPM_IN
com.neuronrobotics.sdk.dyio.DyIOChannelMode.PPM_IN =(0x16, "PPM Reader")
The ppm in.
Definition at line 98 of file DyIOChannelMode.java.
PWM_OUT
com.neuronrobotics.sdk.dyio.DyIOChannelMode.PWM_OUT =(0x06, "PWM Out")
The pwm out.
Definition at line 50 of file DyIOChannelMode.java.
Referenced by com.neuronrobotics.sdk.dyio.peripherals.PWMOutputChannel.PWMOutputChannel().
readableName
String com.neuronrobotics.sdk.dyio.DyIOChannelMode.readableName private
The readable name.
Definition at line 112 of file DyIOChannelMode.java.
SERVO_OUT
com.neuronrobotics.sdk.dyio.DyIOChannelMode.SERVO_OUT =(0x07, "Servo Out")
The servo out.
Definition at line 53 of file DyIOChannelMode.java.
Referenced by com.neuronrobotics.sdk.dyio.DyIOChannel.getAvailableModes(), com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral.getConfigurationFromDevice(), com.neuronrobotics.sdk.dyio.peripherals.ServoChannel.ServoChannel(), com.neuronrobotics.sdk.dyio.DyIOChannel.setMode(), and com.neuronrobotics.sdk.dyio.peripherals.ServoChannel.validate().
SPI_CLOCK
com.neuronrobotics.sdk.dyio.DyIOChannelMode.SPI_CLOCK =(0x0C, "SPI Clock")
The spi clock.
Definition at line 68 of file DyIOChannelMode.java.
Referenced by com.neuronrobotics.sdk.dyio.peripherals.SPIChannel.SPIChannel().
SPI_MISO
com.neuronrobotics.sdk.dyio.DyIOChannelMode.SPI_MISO =(0x0B, "SPI MiSo")
The spi miso.
Definition at line 65 of file DyIOChannelMode.java.
SPI_MOSI
com.neuronrobotics.sdk.dyio.DyIOChannelMode.SPI_MOSI =(0x0A, "SPI MoSi")
The spi mosi.
Definition at line 62 of file DyIOChannelMode.java.
SPI_SELECT
com.neuronrobotics.sdk.dyio.DyIOChannelMode.SPI_SELECT =(0x0D, "SPI Select")
The spi select.
Definition at line 71 of file DyIOChannelMode.java.
USART_RX
com.neuronrobotics.sdk.dyio.DyIOChannelMode.USART_RX =(0x09, "USART Rx")
The usart rx.
Definition at line 59 of file DyIOChannelMode.java.
Referenced by com.neuronrobotics.sdk.dyio.DyIOInputStream.read(), com.neuronrobotics.sdk.dyio.DyIOChannel.setValue(), and com.neuronrobotics.sdk.dyio.peripherals.UARTChannel.UARTRxChannel.UARTRxChannel().
USART_TX
com.neuronrobotics.sdk.dyio.DyIOChannelMode.USART_TX =(0x08, "USART Tx")
The usart tx.
Definition at line 56 of file DyIOChannelMode.java.
Referenced by com.neuronrobotics.sdk.dyio.DyIOChannel.setValue(), com.neuronrobotics.sdk.dyio.peripherals.UARTChannel.UARTTxChannel.UARTTxChannel(), and com.neuronrobotics.sdk.dyio.DyIOOutputStream.write().
value
byte com.neuronrobotics.sdk.dyio.DyIOChannelMode.value private
The value.
Definition at line 109 of file DyIOChannelMode.java.
The documentation for this enum was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/dyio/DyIOChannelMode.java