BowlerKernel: com.neuronrobotics.sdk.commands.bcs.io.AsyncMode Enum Reference
com.neuronrobotics.sdk.commands.bcs.io.AsyncMode Enum Reference
Public Member Functions
String toString ()
byte getValue ()
byte[] getBytes ()
Static Public Member Functions
[static initializer]
static AsyncMode get (byte code)
Public Attributes
NOTEQUAL =(0x00)
DEADBAND =(0x01)
THRESHHOLD =(0x02)
AUTOSAMP =(0x03)
Private Member Functions
AsyncMode (int val)
Private Attributes
byte value
Static Private Attributes
static final Map< Byte, AsyncMode > lookup = new HashMap<Byte,AsyncMode>()
Detailed Description
The Enum AsyncMode.
Definition at line 13 of file AsyncMode.java.
Constructor & Destructor Documentation
AsyncMode()
com.neuronrobotics.sdk.commands.bcs.io.AsyncMode.AsyncMode (int val) private
Instantiates a new bowler method.
Parameters
val the val
Definition at line 62 of file AsyncMode.java.
Member Function Documentation
[static initializer]()
com.neuronrobotics.sdk.commands.bcs.io.AsyncMode.[static initializer] static
get()
static AsyncMode com.neuronrobotics.sdk.commands.bcs.io.AsyncMode.get (byte code) static
Gets the.
Parameters
code the code
Returns
the bowler method
Definition at line 81 of file AsyncMode.java.
References com.neuronrobotics.sdk.commands.bcs.io.AsyncMode.get().
Referenced by com.neuronrobotics.sdk.commands.bcs.io.AsyncMode.get().
getBytes()
byte [] com.neuronrobotics.sdk.commands.bcs.io.AsyncMode.getBytes ()
Gets the bytes.
Returns
the bytes
Implements com.neuronrobotics.sdk.common.ISendable.
Definition at line 88 of file AsyncMode.java.
getValue()
byte com.neuronrobotics.sdk.commands.bcs.io.AsyncMode.getValue ()
Gets the value.
Returns
the value
Definition at line 71 of file AsyncMode.java.
Referenced by com.neuronrobotics.sdk.commands.bcs.io.ConfigAsyncCommand.ConfigAsyncCommand().
toString()
String com.neuronrobotics.sdk.commands.bcs.io.AsyncMode.toString ()
Definition at line 30 of file AsyncMode.java.
Member Data Documentation
AUTOSAMP
com.neuronrobotics.sdk.commands.bcs.io.AsyncMode.AUTOSAMP =(0x03)
The CRITICAL.
Definition at line 26 of file AsyncMode.java.
Referenced by com.neuronrobotics.sdk.dyio.DyIO.configAdvancedAsyncAutoSample(), and com.neuronrobotics.sdk.commands.bcs.io.ConfigAsyncCommand.ConfigAsyncCommand().
DEADBAND
com.neuronrobotics.sdk.commands.bcs.io.AsyncMode.DEADBAND =(0x01)
The GET.
Definition at line 20 of file AsyncMode.java.
Referenced by com.neuronrobotics.sdk.commands.bcs.io.ConfigAsyncCommand.ConfigAsyncCommand().
lookup
final Map<Byte,AsyncMode> com.neuronrobotics.sdk.commands.bcs.io.AsyncMode.lookup = new HashMap<Byte,AsyncMode>() static private
The Constant lookup.
Definition at line 46 of file AsyncMode.java.
NOTEQUAL
com.neuronrobotics.sdk.commands.bcs.io.AsyncMode.NOTEQUAL =(0x00)
#define NOTEQUAL 0 #define DEADBAND 1 #define THRESHHOLD 2 #define AUTOSAMP 3. The STATUS.
Definition at line 17 of file AsyncMode.java.
Referenced by com.neuronrobotics.sdk.dyio.DyIO.configAdvancedAsyncNotEqual(), and com.neuronrobotics.sdk.commands.bcs.io.ConfigAsyncCommand.ConfigAsyncCommand().
THRESHHOLD
com.neuronrobotics.sdk.commands.bcs.io.AsyncMode.THRESHHOLD =(0x02)
The POST.
Definition at line 23 of file AsyncMode.java.
Referenced by com.neuronrobotics.sdk.commands.bcs.io.ConfigAsyncCommand.ConfigAsyncCommand().
value
byte com.neuronrobotics.sdk.commands.bcs.io.AsyncMode.value private
The value.
Definition at line 55 of file AsyncMode.java.
The documentation for this enum was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/commands/bcs/io/AsyncMode.java