BowlerKernel: com.neuronrobotics.sdk.addons.kinematics.LinkType Enum Reference
com.neuronrobotics.sdk.addons.kinematics.LinkType Enum Reference
Public Member Functions
String getName ()
String toString ()
Static Public Member Functions
[static initializer]
static ArrayList< String > getUserDefined ()
static void addType (String type)
static LinkType fromString (String name)
Public Attributes
PID =("pid")
PID_TOOL =("pid-tool")
PID_PRISMATIC =("pid-prismatic")
ANALOG_ROTORY =("analog-rotory")
ANALOG_PRISMATIC =("analog-prismatic")
DUMMY =("dummy")
VIRTUAL =("virtual")
GCODE_STEPPER_ROTORY =("gcode-stepper-rotory")
GCODE_STEPPER_TOOL =("gcode-stepper-tool")
GCODE_STEPPER_PRISMATIC =("gcode-stepper-prismatic")
GCODE_HEATER_TOOL =("gcode-heater-tool")
CAMERA =("camera")
USERDEFINED =(null)
Private Member Functions
LinkType (String name)
Private Attributes
final String name
Static Private Attributes
static final Map< String, LinkType > map
Detailed Description
The Enum LinkType.
Definition at line 12 of file LinkType.java.
Constructor & Destructor Documentation
LinkType()
com.neuronrobotics.sdk.addons.kinematics.LinkType.LinkType (String name) private
Instantiates a new link type.
Parameters
name the name
Definition at line 90 of file LinkType.java.
Member Function Documentation
[static initializer]()
com.neuronrobotics.sdk.addons.kinematics.LinkType.[static initializer] static
addType()
static void com.neuronrobotics.sdk.addons.kinematics.LinkType.addType (String type) static
Only classes in this package should add types, and only from LinkFactory
Parameters
type a new type name to regester as user defined
Definition at line 81 of file LinkType.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.LinkFactory.addLinkProvider().
fromString()
static LinkType com.neuronrobotics.sdk.addons.kinematics.LinkType.fromString (String name) static
From string.
Parameters
name the name
Returns
the link type
Definition at line 109 of file LinkType.java.
getName()
String com.neuronrobotics.sdk.addons.kinematics.LinkType.getName ()
Gets the name.
Returns
the name
Definition at line 99 of file LinkType.java.
getUserDefined()
static ArrayList<String> com.neuronrobotics.sdk.addons.kinematics.LinkType.getUserDefined () static
Definition at line 67 of file LinkType.java.
toString()
String com.neuronrobotics.sdk.addons.kinematics.LinkType.toString ()
Definition at line 123 of file LinkType.java.
Member Data Documentation
ANALOG_PRISMATIC
com.neuronrobotics.sdk.addons.kinematics.LinkType.ANALOG_PRISMATIC =("analog-prismatic")
The analog prismatic.
Definition at line 31 of file LinkType.java.
ANALOG_ROTORY
com.neuronrobotics.sdk.addons.kinematics.LinkType.ANALOG_ROTORY =("analog-rotory")
The analog rotory.
Definition at line 28 of file LinkType.java.
CAMERA
com.neuronrobotics.sdk.addons.kinematics.LinkType.CAMERA =("camera")
Camera
Definition at line 50 of file LinkType.java.
DUMMY
com.neuronrobotics.sdk.addons.kinematics.LinkType.DUMMY =("dummy")
The dummy.
Definition at line 34 of file LinkType.java.
GCODE_HEATER_TOOL
com.neuronrobotics.sdk.addons.kinematics.LinkType.GCODE_HEATER_TOOL =("gcode-heater-tool")
The stepper tool.
Definition at line 47 of file LinkType.java.
GCODE_STEPPER_PRISMATIC
com.neuronrobotics.sdk.addons.kinematics.LinkType.GCODE_STEPPER_PRISMATIC =("gcode-stepper-prismatic")
The stepper tool.
Definition at line 45 of file LinkType.java.
GCODE_STEPPER_ROTORY
com.neuronrobotics.sdk.addons.kinematics.LinkType.GCODE_STEPPER_ROTORY =("gcode-stepper-rotory")
The stepper rotory.
Definition at line 41 of file LinkType.java.
GCODE_STEPPER_TOOL
com.neuronrobotics.sdk.addons.kinematics.LinkType.GCODE_STEPPER_TOOL =("gcode-stepper-tool")
The stepper tool.
Definition at line 43 of file LinkType.java.
map
final Map<String, LinkType> com.neuronrobotics.sdk.addons.kinematics.LinkType.map static private
Initial value:
=
                                 new HashMap<String, LinkType>()
The Constant map.
Definition at line 59 of file LinkType.java.
name
final String com.neuronrobotics.sdk.addons.kinematics.LinkType.name private
The name.
Definition at line 55 of file LinkType.java.
PID
com.neuronrobotics.sdk.addons.kinematics.LinkType.PID =("pid")
The pid.
Definition at line 19 of file LinkType.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.homeLink(), com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.LinkConfiguration(), com.neuronrobotics.sdk.addons.kinematics.AbstractKinematicsNR.setDevice(), and com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.setPidConfiguration().
PID_PRISMATIC
com.neuronrobotics.sdk.addons.kinematics.LinkType.PID_PRISMATIC =("pid-prismatic")
The pid prismatic.
Definition at line 25 of file LinkType.java.
PID_TOOL
com.neuronrobotics.sdk.addons.kinematics.LinkType.PID_TOOL =("pid-tool")
The pid tool.
Definition at line 22 of file LinkType.java.
USERDEFINED
com.neuronrobotics.sdk.addons.kinematics.LinkType.USERDEFINED =(null)
Camera
Definition at line 52 of file LinkType.java.
VIRTUAL
com.neuronrobotics.sdk.addons.kinematics.LinkType.VIRTUAL =("virtual")
The virtual.
Definition at line 37 of file LinkType.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.LinkConfiguration.LinkConfiguration().
The documentation for this enum was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/addons/kinematics/LinkType.java