BowlerKernel: com.neuronrobotics.sdk.pid.PIDLimitEventType Enum Reference
com.neuronrobotics.sdk.pid.PIDLimitEventType Enum Reference
Public Member Functions
byte getValue ()
byte[] getBytes ()
Static Public Member Functions
[static initializer]
static PIDLimitEventType get (byte code)
static List< PIDLimitEventType > getAllLimitMasks (byte code)
Public Attributes
NO_LIMIT =(0x00)
LOWERLIMIT =(0x01)
INDEXEVENT =(0x02)
UPPERLIMIT =(0x04)
OVERCURRENT =(0x08)
CONTROLLER_ERROR =(0x10)
HOME_EVENT =(0x20)
Private Member Functions
PIDLimitEventType (int val)
Private Attributes
byte value
Static Private Attributes
static final Map< Byte, PIDLimitEventType > lookup = new HashMap<Byte,PIDLimitEventType>()
Detailed Description
The Enum PIDLimitEventType.
Definition at line 28 of file PIDLimitEventType.java.
Constructor & Destructor Documentation
PIDLimitEventType()
com.neuronrobotics.sdk.pid.PIDLimitEventType.PIDLimitEventType (int val) private
Instantiates a new bowler method.
Parameters
val the val
Definition at line 73 of file PIDLimitEventType.java.
Member Function Documentation
[static initializer]()
com.neuronrobotics.sdk.pid.PIDLimitEventType.[static initializer] static
get()
static PIDLimitEventType com.neuronrobotics.sdk.pid.PIDLimitEventType.get (byte code) static
Gets the.
Parameters
code the code
Returns
the bowler method
Definition at line 92 of file PIDLimitEventType.java.
References com.neuronrobotics.sdk.pid.PIDLimitEventType.get().
Referenced by com.neuronrobotics.sdk.pid.PIDLimitEventType.get(), and com.neuronrobotics.sdk.pid.PIDLimitEvent.PIDLimitEvent().
getAllLimitMasks()
static List<PIDLimitEventType> com.neuronrobotics.sdk.pid.PIDLimitEventType.getAllLimitMasks (byte code) static
Gets the.
Parameters
code the code
Returns
the bowler method
Definition at line 103 of file PIDLimitEventType.java.
getBytes()
byte [] com.neuronrobotics.sdk.pid.PIDLimitEventType.getBytes ()
Gets the bytes.
Returns
the bytes
Definition at line 122 of file PIDLimitEventType.java.
getValue()
byte com.neuronrobotics.sdk.pid.PIDLimitEventType.getValue ()
Gets the value.
Returns
the value
Definition at line 82 of file PIDLimitEventType.java.
Member Data Documentation
CONTROLLER_ERROR
com.neuronrobotics.sdk.pid.PIDLimitEventType.CONTROLLER_ERROR =(0x10)
Definition at line 48 of file PIDLimitEventType.java.
HOME_EVENT
com.neuronrobotics.sdk.pid.PIDLimitEventType.HOME_EVENT =(0x20)
a home event
Definition at line 53 of file PIDLimitEventType.java.
INDEXEVENT
com.neuronrobotics.sdk.pid.PIDLimitEventType.INDEXEVENT =(0x02)
The indexevent.
Definition at line 38 of file PIDLimitEventType.java.
lookup
final Map<Byte,PIDLimitEventType> com.neuronrobotics.sdk.pid.PIDLimitEventType.lookup = new HashMap<Byte,PIDLimitEventType>() static private
The Constant lookup.
Definition at line 57 of file PIDLimitEventType.java.
LOWERLIMIT
com.neuronrobotics.sdk.pid.PIDLimitEventType.LOWERLIMIT =(0x01)
The lowerlimit.
Definition at line 35 of file PIDLimitEventType.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setTargetValue().
NO_LIMIT
com.neuronrobotics.sdk.pid.PIDLimitEventType.NO_LIMIT =(0x00)
Definition at line 33 of file PIDLimitEventType.java.
OVERCURRENT
com.neuronrobotics.sdk.pid.PIDLimitEventType.OVERCURRENT =(0x08)
The overcurrent.
Definition at line 44 of file PIDLimitEventType.java.
UPPERLIMIT
com.neuronrobotics.sdk.pid.PIDLimitEventType.UPPERLIMIT =(0x04)
The upperlimit.
Definition at line 41 of file PIDLimitEventType.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.AbstractLink.setTargetValue().
value
byte com.neuronrobotics.sdk.pid.PIDLimitEventType.value private
The value.
Definition at line 66 of file PIDLimitEventType.java.
The documentation for this enum was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/pid/PIDLimitEventType.java