BowlerKernel: com.neuronrobotics.sdk.common.BowlerMethod Enum Reference
com.neuronrobotics.sdk.common.BowlerMethod Enum Reference
Public Member Functions
byte getValue ()
byte[] getBytes ()
String toString ()
Static Public Member Functions
[static initializer]
static BowlerMethod get (byte code)
Public Attributes
STATUS =(0x00)
GET =(0x10)
POST =(0x20)
CRITICAL =(0x30)
ASYNCHRONOUS =(0x40)
Private Member Functions
BowlerMethod (int val)
Private Attributes
byte value
Static Private Attributes
static final Map< Byte, BowlerMethod > lookup = new HashMap<Byte,BowlerMethod>()
Detailed Description
The Enum BowlerMethod.
Definition at line 25 of file BowlerMethod.java.
Constructor & Destructor Documentation
BowlerMethod()
com.neuronrobotics.sdk.common.BowlerMethod.BowlerMethod (int val) private
Instantiates a new bowler method.
Parameters
val the val
Definition at line 60 of file BowlerMethod.java.
Member Function Documentation
[static initializer]()
com.neuronrobotics.sdk.common.BowlerMethod.[static initializer] static
get()
static BowlerMethod com.neuronrobotics.sdk.common.BowlerMethod.get (byte code) static
Gets the.
Parameters
code the code
Returns
the bowler method
Definition at line 79 of file BowlerMethod.java.
References com.neuronrobotics.sdk.common.BowlerMethod.get().
Referenced by com.neuronrobotics.sdk.common.BowlerMethod.get(), com.neuronrobotics.sdk.common.BowlerAbstractConnection.getRpcList(), and com.neuronrobotics.sdk.common.BowlerDatagram.parse().
getBytes()
byte [] com.neuronrobotics.sdk.common.BowlerMethod.getBytes ()
Gets the bytes.
Returns
the bytes
Implements com.neuronrobotics.sdk.common.ISendable.
Definition at line 86 of file BowlerMethod.java.
getValue()
byte com.neuronrobotics.sdk.common.BowlerMethod.getValue ()
Gets the value.
Returns
the value
Definition at line 69 of file BowlerMethod.java.
Referenced by com.neuronrobotics.sdk.common.device.server.bcs.rpc.BcsRpcNamespaceImp.BcsRpcNamespaceImp().
toString()
String com.neuronrobotics.sdk.common.BowlerMethod.toString ()
Definition at line 94 of file BowlerMethod.java.
Member Data Documentation
ASYNCHRONOUS
com.neuronrobotics.sdk.common.BowlerMethod.ASYNCHRONOUS =(0x40)
The ASYNCHRONOUS.
Definition at line 40 of file BowlerMethod.java.
Referenced by com.neuronrobotics.sdk.common.BowlerDatagram.isSyncronous(), com.neuronrobotics.sdk.common.device.server.BowlerAbstractServer.pushAsyncPacket(), and com.neuronrobotics.sdk.common.BowlerDatagram.setAsAsync().
CRITICAL
com.neuronrobotics.sdk.common.BowlerMethod.CRITICAL =(0x30)
The CRITICAL.
Definition at line 37 of file BowlerMethod.java.
Referenced by com.neuronrobotics.sdk.commands.bcs.io.ConfigAsyncCommand.ConfigAsyncCommand(), com.neuronrobotics.sdk.commands.bcs.pid.DyPID.ConfigureDynamicPIDCommand.ConfigureDynamicPIDCommand(), com.neuronrobotics.sdk.commands.bcs.pid.ConfigurePDVelocityCommand.ConfigurePDVelocityCommand(), com.neuronrobotics.sdk.namespace.bcs.pid.PidNamespaceImp.ConfigurePDVelovityController(), com.neuronrobotics.sdk.commands.bcs.pid.ConfigurePIDCommand.ConfigurePIDCommand(), com.neuronrobotics.sdk.namespace.bcs.pid.PidNamespaceImp.ConfigurePIDController(), com.neuronrobotics.sdk.commands.neuronrobotics.bootloader.EraseFlashCommand.EraseFlashCommand(), com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral.getConfigurationFromDevice(), com.neuronrobotics.sdk.commands.bcs.pid.KillAllPIDCommand.KillAllPIDCommand(), com.neuronrobotics.sdk.namespace.bcs.pid.PidNamespaceImp.killAllPidGroups(), com.neuronrobotics.sdk.namespace.bcs.pid.PidDeviceServerNamespace.PidDeviceServerNamespace(), com.neuronrobotics.sdk.commands.neuronrobotics.dyio.PowerCommand.PowerCommand(), com.neuronrobotics.sdk.dyio.peripherals.ServoChannel.powerOverridePacket.powerOverridePacket(), com.neuronrobotics.sdk.commands.neuronrobotics.bootloader.ProgramSectionCommand.ProgramSectionCommand(), com.neuronrobotics.sdk.commands.neuronrobotics.dyio.ProvisionCommand.ProvisionCommand(), com.neuronrobotics.sdk.commands.neuronrobotics.bootloader.ResetChipCommand.ResetChipCommand(), com.neuronrobotics.sdk.dyio.peripherals.DyIOAbstractPeripheral.SavePosition(), com.neuronrobotics.sdk.commands.bcs.io.SetChannelValueCommand.SetChannelValueCommand(), com.neuronrobotics.sdk.dyio.peripherals.UARTChannel.setUARTBaudrate(), and com.neuronrobotics.sdk.commands.bcs.io.SetUARTBaudrateCommand.SetUARTBaudrateCommand().
GET
com.neuronrobotics.sdk.common.BowlerMethod.GET =(0x10)
The GET.
Definition at line 31 of file BowlerMethod.java.
Referenced by com.neuronrobotics.sdk.commands.bcs.io.AsyncCommand.AsyncCommand(), com.neuronrobotics.sdk.common.device.server.bcs.core.BcsCoreNamespaceImp.BcsCoreNamespaceImp(), com.neuronrobotics.sdk.common.device.server.bcs.rpc.BcsRpcNamespaceImp.BcsRpcNamespaceImp(), com.neuronrobotics.sdk.commands.neuronrobotics.bowlercam.BlobCommand.BlobCommand(), com.neuronrobotics.sdk.commands.neuronrobotics.bootloader.BootloaderIDCommand.BootloaderIDCommand(), com.neuronrobotics.sdk.commands.bcs.pid.DyPID.ConfigureDynamicPIDCommand.ConfigureDynamicPIDCommand(), com.neuronrobotics.sdk.commands.bcs.pid.ConfigurePDVelocityCommand.ConfigurePDVelocityCommand(), com.neuronrobotics.sdk.commands.bcs.pid.ConfigurePIDCommand.ConfigurePIDCommand(), com.neuronrobotics.sdk.commands.bcs.pid.ControlAllPIDCommand.ControlAllPIDCommand(), com.neuronrobotics.sdk.commands.bcs.pid.ControlPIDCommand.ControlPIDCommand(), com.neuronrobotics.sdk.dyio.DyIO.getAllChannelModes(), com.neuronrobotics.sdk.dyio.DyIO.getAllChannelValues(), com.neuronrobotics.sdk.commands.neuronrobotics.dyio.GetAllChannelValuesCommand.GetAllChannelValuesCommand(), com.neuronrobotics.sdk.namespace.bcs.pid.PidNamespaceImp.GetAllPIDPosition(), com.neuronrobotics.sdk.dyio.DyIO.getAvailibleChannelModes(), com.neuronrobotics.sdk.commands.bcs.io.GetChannelModeCommand.GetChannelModeCommand(), com.neuronrobotics.sdk.commands.bcs.io.GetChannelModeListCommand.GetChannelModeListCommand(), com.neuronrobotics.sdk.dyio.DyIO.getDyIOChannelCount(), com.neuronrobotics.sdk.commands.bcs.io.GetDyIOChannelCountCommand.GetDyIOChannelCountCommand(), com.neuronrobotics.sdk.namespace.bcs.pid.PidNamespaceImp.getPDVelocityConfiguration(), com.neuronrobotics.sdk.namespace.bcs.pid.PidNamespaceImp.getPIDChannelCount(), com.neuronrobotics.sdk.commands.bcs.pid.GetPIDChannelCountCommand.GetPIDChannelCountCommand(), com.neuronrobotics.sdk.namespace.bcs.pid.PidNamespaceImp.getPIDConfiguration(), com.neuronrobotics.sdk.namespace.bcs.pid.PidNamespaceImp.GetPIDPosition(), com.neuronrobotics.sdk.commands.bcs.io.GetValueCommand.GetValueCommand(), com.neuronrobotics.sdk.commands.neuronrobotics.bowlercam.ImageCommand.ImageCommand(), com.neuronrobotics.sdk.commands.neuronrobotics.bowlercam.ImageURLCommand.ImageURLCommand(), com.neuronrobotics.sdk.commands.neuronrobotics.dyio.InfoFirmwareRevisionCommand.InfoFirmwareRevisionCommand(), com.neuronrobotics.sdk.commands.bcs.core.NamespaceCommand.NamespaceCommand(), com.neuronrobotics.sdk.namespace.bcs.pid.PidDeviceServerNamespace.PidDeviceServerNamespace(), com.neuronrobotics.sdk.commands.bcs.core.PingCommand.PingCommand(), com.neuronrobotics.sdk.common.BowlerAbstractConnection.PingCommand.PingCommand(), com.neuronrobotics.sdk.commands.neuronrobotics.dyio.PowerCommand.PowerCommand(), com.neuronrobotics.sdk.commands.bcs.core.RpcArgumentsCommand.RpcArgumentsCommand(), com.neuronrobotics.sdk.commands.bcs.core.RpcCommand.RpcCommand(), com.neuronrobotics.sdk.commands.bcs.safe.SafeModeCommand.SafeModeCommand(), and com.neuronrobotics.sdk.dyio.peripherals.PPMReaderChannel.updateValues().
lookup
final Map<Byte,BowlerMethod> com.neuronrobotics.sdk.common.BowlerMethod.lookup = new HashMap<Byte,BowlerMethod>() static private
The Constant lookup.
Definition at line 44 of file BowlerMethod.java.
POST
com.neuronrobotics.sdk.common.BowlerMethod.POST =(0x20)
The POST.
Definition at line 34 of file BowlerMethod.java.
Referenced by com.neuronrobotics.sdk.commands.bcs.io.AsyncCommand.AsyncCommand(), com.neuronrobotics.sdk.common.device.server.bcs.core.BcsCoreNamespaceImp.BcsCoreNamespaceImp(), com.neuronrobotics.sdk.common.device.server.bcs.rpc.BcsRpcArgsCommand.BcsRpcArgsCommand(), com.neuronrobotics.sdk.common.device.server.bcs.rpc.BcsRpcCommand.BcsRpcCommand(), com.neuronrobotics.sdk.common.device.server.bcs.rpc.BcsRpcNamespaceImp.BcsRpcNamespaceImp(), com.neuronrobotics.sdk.commands.neuronrobotics.bowlercam.BlobCommand.BlobCommand(), com.neuronrobotics.sdk.commands.cartesian.CancelPrintCommand.CancelPrintCommand(), com.neuronrobotics.sdk.commands.bcs.pid.ControlAllPIDCommand.ControlAllPIDCommand(), com.neuronrobotics.sdk.commands.bcs.pid.ControlPIDCommand.ControlPIDCommand(), com.neuronrobotics.sdk.dyio.DyIOChannel.flush(), com.neuronrobotics.sdk.dyio.DyIO.flushCache(), com.neuronrobotics.sdk.commands.neuronrobotics.bowlercam.ImageCommand.ImageCommand(), com.neuronrobotics.sdk.commands.neuronrobotics.bowlercam.ImageURLCommand.ImageURLCommand(), com.neuronrobotics.sdk.commands.cartesian.LinearInterpolationCommand.LinearInterpolationCommand(), com.neuronrobotics.sdk.commands.bcs.core.NamespaceCommand.NamespaceCommand(), com.neuronrobotics.sdk.commands.bcs.pid.PDVelocityCommand.PDVelocityCommand(), com.neuronrobotics.sdk.namespace.bcs.pid.PidDeviceServerNamespace.PidDeviceServerNamespace(), com.neuronrobotics.sdk.namespace.bcs.pid.PidNamespaceImp.ResetPIDChannel(), com.neuronrobotics.sdk.commands.bcs.pid.ResetPIDCommand.ResetPIDCommand(), com.neuronrobotics.sdk.namespace.bcs.pid.PidNamespaceImp.runOutputHysteresisCalibration(), com.neuronrobotics.sdk.commands.bcs.safe.SafeModeCommand.SafeModeCommand(), com.neuronrobotics.sdk.commands.bcs.io.SetAllChannelValuesCommand.SetAllChannelValuesCommand(), com.neuronrobotics.sdk.namespace.bcs.pid.PidNamespaceImp.SetAllPIDSetPoint(), com.neuronrobotics.sdk.commands.bcs.io.setmode.SetChannelModeCommand.SetChannelModeCommand(), com.neuronrobotics.sdk.commands.bcs.io.SetChannelValueCommand.SetChannelValueCommand(), com.neuronrobotics.sdk.dyio.peripherals.PPMReaderChannel.setCrossLink(), com.neuronrobotics.sdk.dyio.DyIOChannel.setMode(), com.neuronrobotics.sdk.namespace.bcs.pid.PidNamespaceImp.SetPDVelocity(), com.neuronrobotics.sdk.namespace.bcs.pid.PidNamespaceImp.SetPIDSetPoint(), com.neuronrobotics.sdk.dyio.DyIOChannel.setValue(), and com.neuronrobotics.sdk.dyio.peripherals.SPIChannel.write().
STATUS
com.neuronrobotics.sdk.common.BowlerMethod.STATUS =(0x00)
The STATUS.
Definition at line 28 of file BowlerMethod.java.
Referenced by com.neuronrobotics.sdk.commands.bcs.core.ErrorCommand.ErrorCommand(), com.neuronrobotics.sdk.common.BowlerDatagram.parse(), com.neuronrobotics.sdk.namespace.bcs.pid.PidDeviceServerNamespace.PidDeviceServerNamespace(), and com.neuronrobotics.sdk.commands.bcs.core.ReadyCommand.ReadyCommand().
value
byte com.neuronrobotics.sdk.common.BowlerMethod.value private
The value.
Definition at line 53 of file BowlerMethod.java.
The documentation for this enum was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/common/BowlerMethod.java