BowlerKernel: com.neuronrobotics.sdk.addons.irobot.CreateSensorRequest Enum Reference
com.neuronrobotics.sdk.addons.irobot.CreateSensorRequest Enum Reference
Public Member Functions
byte getValue ()
String toString ()
Static Public Member Functions
static CreateSensorRequest get (byte code)
Public Attributes
ALL =(0x00)
IO =(0x01)
DRIVE =(0x02)
BATTERY =(0x03)
NONE =(0xFF)
Private Member Functions
CreateSensorRequest (int val)
Private Attributes
byte value
Static Private Attributes
static final Map< Byte, CreateSensorRequest > lookup = new HashMap<Byte,CreateSensorRequest>()
Detailed Description
The Enum CreateSensorRequest.
Definition at line 24 of file CreateSensorRequest.java.
Constructor & Destructor Documentation
CreateSensorRequest()
com.neuronrobotics.sdk.addons.irobot.CreateSensorRequest.CreateSensorRequest (int val) private
Instantiates a new creates the sensor request.
Parameters
val the val
Definition at line 52 of file CreateSensorRequest.java.
Member Function Documentation
get()
static CreateSensorRequest com.neuronrobotics.sdk.addons.irobot.CreateSensorRequest.get (byte code) static
Gets the.
Parameters
code the code
Returns
the creates the sensor request
Definition at line 71 of file CreateSensorRequest.java.
References com.neuronrobotics.sdk.addons.irobot.CreateSensorRequest.get().
Referenced by com.neuronrobotics.sdk.addons.irobot.CreateSensorRequest.get().
getValue()
byte com.neuronrobotics.sdk.addons.irobot.CreateSensorRequest.getValue ()
Gets the value.
Returns
the value
Definition at line 61 of file CreateSensorRequest.java.
Referenced by com.neuronrobotics.sdk.addons.irobot.Create.requestSensors().
toString()
String com.neuronrobotics.sdk.addons.irobot.CreateSensorRequest.toString ()
Definition at line 78 of file CreateSensorRequest.java.
Member Data Documentation
ALL
com.neuronrobotics.sdk.addons.irobot.CreateSensorRequest.ALL =(0x00)
The all.
Definition at line 27 of file CreateSensorRequest.java.
Referenced by com.neuronrobotics.sdk.addons.irobot.Create.requestSensors().
BATTERY
com.neuronrobotics.sdk.addons.irobot.CreateSensorRequest.BATTERY =(0x03)
The battery.
Definition at line 36 of file CreateSensorRequest.java.
DRIVE
com.neuronrobotics.sdk.addons.irobot.CreateSensorRequest.DRIVE =(0x02)
The drive.
Definition at line 33 of file CreateSensorRequest.java.
IO
com.neuronrobotics.sdk.addons.irobot.CreateSensorRequest.IO =(0x01)
The io.
Definition at line 30 of file CreateSensorRequest.java.
lookup
final Map<Byte,CreateSensorRequest> com.neuronrobotics.sdk.addons.irobot.CreateSensorRequest.lookup = new HashMap<Byte,CreateSensorRequest>() static private
The Constant lookup.
Definition at line 45 of file CreateSensorRequest.java.
NONE
com.neuronrobotics.sdk.addons.irobot.CreateSensorRequest.NONE =(0xFF)
The none.
Definition at line 39 of file CreateSensorRequest.java.
Referenced by com.neuronrobotics.sdk.addons.irobot.Create.onChannelEvent().
value
byte com.neuronrobotics.sdk.addons.irobot.CreateSensorRequest.value private
The value.
Definition at line 42 of file CreateSensorRequest.java.
The documentation for this enum was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/addons/irobot/CreateSensorRequest.java