BowlerKernel: com.neuronrobotics.sdk.bootloader.NRBootCoreType Enum Reference
com.neuronrobotics.sdk.bootloader.NRBootCoreType Enum Reference
Public Member Functions
void setBytesPerWord (int bytesPerWord)
int getBytesPerWord ()
void setReadableName (String readableName)
String getReadableName ()
String toString ()
Static Public Member Functions
static NRBootCoreType find (String tagValue)
Public Attributes
AVRxx4p =(2, "avr_atmegaXX4p")
PIC32 =(4, "pic32mx440f128h")
Private Member Functions
NRBootCoreType (int bytesPerWord, String name)
Private Attributes
int bytesPerWord
String readableName
Detailed Description
The Enum NRBootCoreType.
Definition at line 7 of file NRBootCoreType.java.
Constructor & Destructor Documentation
NRBootCoreType()
com.neuronrobotics.sdk.bootloader.NRBootCoreType.NRBootCoreType (int bytesPerWord, String name) private
Instantiates a new NR boot core type.
Parameters
bytesPerWord the bytes per word
name the name
Definition at line 27 of file NRBootCoreType.java.
Member Function Documentation
find()
static NRBootCoreType com.neuronrobotics.sdk.bootloader.NRBootCoreType.find (String tagValue) static
Find.
Parameters
tagValue the tag value
Returns
the NR boot core type
Definition at line 74 of file NRBootCoreType.java.
References com.neuronrobotics.sdk.bootloader.NRBootCoreType.AVRxx4p, and com.neuronrobotics.sdk.bootloader.NRBootCoreType.PIC32.
Referenced by com.neuronrobotics.sdk.bootloader.Hexml.Hexml().
getBytesPerWord()
int com.neuronrobotics.sdk.bootloader.NRBootCoreType.getBytesPerWord ()
Gets the bytes per word.
Returns
the bytes per word
Definition at line 46 of file NRBootCoreType.java.
getReadableName()
String com.neuronrobotics.sdk.bootloader.NRBootCoreType.getReadableName ()
Gets the readable name.
Returns
the readable name
Definition at line 64 of file NRBootCoreType.java.
Referenced by com.neuronrobotics.sdk.bootloader.NRBoot.load().
setBytesPerWord()
void com.neuronrobotics.sdk.bootloader.NRBootCoreType.setBytesPerWord (int bytesPerWord)
Sets the bytes per word.
Parameters
bytesPerWord the new bytes per word
Definition at line 37 of file NRBootCoreType.java.
setReadableName()
void com.neuronrobotics.sdk.bootloader.NRBootCoreType.setReadableName (String readableName)
Sets the readable name.
Parameters
readableName the new readable name
Definition at line 55 of file NRBootCoreType.java.
toString()
String com.neuronrobotics.sdk.bootloader.NRBootCoreType.toString ()
Definition at line 88 of file NRBootCoreType.java.
Member Data Documentation
AVRxx4p
com.neuronrobotics.sdk.bootloader.NRBootCoreType.AVRxx4p =(2, "avr_atmegaXX4p")
The AV rxx4p.
Definition at line 10 of file NRBootCoreType.java.
Referenced by com.neuronrobotics.sdk.bootloader.NRBootCoreType.find(), and com.neuronrobotics.sdk.bootloader.IntelHexParser.IntelHexParser().
bytesPerWord
int com.neuronrobotics.sdk.bootloader.NRBootCoreType.bytesPerWord private
The bytes per word.
Definition at line 16 of file NRBootCoreType.java.
PIC32
com.neuronrobotics.sdk.bootloader.NRBootCoreType.PIC32 =(4, "pic32mx440f128h")
The PI c32.
Definition at line 13 of file NRBootCoreType.java.
Referenced by com.neuronrobotics.sdk.bootloader.IntelHexParser.checkAddressValidity(), com.neuronrobotics.sdk.bootloader.NRBootCoreType.find(), and com.neuronrobotics.sdk.bootloader.IntelHexParser.IntelHexParser().
readableName
String com.neuronrobotics.sdk.bootloader.NRBootCoreType.readableName private
The readable name.
Definition at line 19 of file NRBootCoreType.java.
The documentation for this enum was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/bootloader/NRBootCoreType.java