BowlerKernel: com.neuronrobotics.sdk.commands.bcs.io.AsyncThreshholdEdgeType Enum Reference
com.neuronrobotics.sdk.commands.bcs.io.AsyncThreshholdEdgeType Enum Reference
Public Member Functions
String toString ()
byte getValue ()
byte[] getBytes ()
Static Public Member Functions
[static initializer]
static AsyncThreshholdEdgeType get (byte code)
Public Attributes
BOTH =(0x00)
RISING =(0x01)
FALLING =(0x02)
Private Member Functions
AsyncThreshholdEdgeType (int val)
Private Attributes
byte value
Static Private Attributes
static final Map< Byte, AsyncThreshholdEdgeType > lookup = new HashMap<Byte,AsyncThreshholdEdgeType>()
Detailed Description
The Enum AsyncThreshholdEdgeType.
Definition at line 13 of file AsyncThreshholdEdgeType.java.
Constructor & Destructor Documentation
AsyncThreshholdEdgeType()
com.neuronrobotics.sdk.commands.bcs.io.AsyncThreshholdEdgeType.AsyncThreshholdEdgeType (int val) private
Instantiates a new bowler method.
Parameters
val the val
Definition at line 58 of file AsyncThreshholdEdgeType.java.
Member Function Documentation
[static initializer]()
com.neuronrobotics.sdk.commands.bcs.io.AsyncThreshholdEdgeType.[static initializer] static
get()
static AsyncThreshholdEdgeType com.neuronrobotics.sdk.commands.bcs.io.AsyncThreshholdEdgeType.get (byte code) static
Gets the.
Parameters
code the code
Returns
the bowler method
Definition at line 77 of file AsyncThreshholdEdgeType.java.
References com.neuronrobotics.sdk.commands.bcs.io.AsyncThreshholdEdgeType.get().
Referenced by com.neuronrobotics.sdk.commands.bcs.io.AsyncThreshholdEdgeType.get().
getBytes()
byte [] com.neuronrobotics.sdk.commands.bcs.io.AsyncThreshholdEdgeType.getBytes ()
Gets the bytes.
Returns
the bytes
Implements com.neuronrobotics.sdk.common.ISendable.
Definition at line 84 of file AsyncThreshholdEdgeType.java.
getValue()
byte com.neuronrobotics.sdk.commands.bcs.io.AsyncThreshholdEdgeType.getValue ()
Gets the value.
Returns
the value
Definition at line 67 of file AsyncThreshholdEdgeType.java.
Referenced by com.neuronrobotics.sdk.commands.bcs.io.ConfigAsyncCommand.ConfigAsyncCommand().
toString()
String com.neuronrobotics.sdk.commands.bcs.io.AsyncThreshholdEdgeType.toString ()
Definition at line 28 of file AsyncThreshholdEdgeType.java.
Member Data Documentation
BOTH
com.neuronrobotics.sdk.commands.bcs.io.AsyncThreshholdEdgeType.BOTH =(0x00)
#define ASYN_BOTH 0 #define ASYN_RISING 1 #define ASYN_FALLING 2. The STATUS.
Definition at line 17 of file AsyncThreshholdEdgeType.java.
FALLING
com.neuronrobotics.sdk.commands.bcs.io.AsyncThreshholdEdgeType.FALLING =(0x02)
The POST.
Definition at line 23 of file AsyncThreshholdEdgeType.java.
lookup
final Map<Byte,AsyncThreshholdEdgeType> com.neuronrobotics.sdk.commands.bcs.io.AsyncThreshholdEdgeType.lookup = new HashMap<Byte,AsyncThreshholdEdgeType>() static private
The Constant lookup.
Definition at line 42 of file AsyncThreshholdEdgeType.java.
RISING
com.neuronrobotics.sdk.commands.bcs.io.AsyncThreshholdEdgeType.RISING =(0x01)
The GET.
Definition at line 20 of file AsyncThreshholdEdgeType.java.
value
byte com.neuronrobotics.sdk.commands.bcs.io.AsyncThreshholdEdgeType.value private
The value.
Definition at line 51 of file AsyncThreshholdEdgeType.java.
The documentation for this enum was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/commands/bcs/io/AsyncThreshholdEdgeType.java