BowlerKernel: com.neuronrobotics.sdk.addons.kinematics.gcodebridge.IGCodeChannel Interface Reference
com.neuronrobotics.sdk.addons.kinematics.gcodebridge.IGCodeChannel Interface Reference
Public Member Functions
String getAxis ()
void setValue (double value)
Detailed Description
Definition at line 3 of file IGCodeChannel.java.
Member Function Documentation
getAxis()
String com.neuronrobotics.sdk.addons.kinematics.gcodebridge.IGCodeChannel.getAxis ()
Return the gcode axis of this channel
Returns
the axis
Implemented in com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeRotory, com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodePrismatic, and com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GCodeHeater.
Referenced by com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.flush(), and com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.loadCurrent().
setValue()
void com.neuronrobotics.sdk.addons.kinematics.gcodebridge.IGCodeChannel.setValue (double value)
Set a value of the current position
Parameters
value of the current psition
Implemented in com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeRotory, com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodePrismatic, and com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GCodeHeater.
Referenced by com.neuronrobotics.sdk.addons.kinematics.gcodebridge.GcodeDevice.loadCurrent().
The documentation for this interface was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/addons/kinematics/gcodebridge/IGCodeChannel.java