BowlerKernel: com.neuronrobotics.bowlerstudio.creature.IMobileBaseUI Interface Reference
com.neuronrobotics.bowlerstudio.creature.IMobileBaseUI Interface Reference
Public Member Functions
void setAllCSG (Collection< CSG > toAdd, File source)
void addCSG (Collection< CSG > toAdd, File source)
void highlightException (File fileEngineRunByName, Throwable ex)
Set< CSG > getVisibleCSGs ()
void setSelectedCsg (Collection< CSG > selectedCsg)
void setSelected (Affine rootListener)
default void selectCsgByFile (File script, int lineNumber)
default void setCsg (CSG toAdd, File source)
default void setCsg (List< CSG > toAdd)
default void setCsg (CSG toAdd)
default void setCsg (MobileBaseCadManager thread, File cadScript)
default void addCsg (CSG toAdd, File source)
Detailed Description
Definition at line 13 of file IMobileBaseUI.java.
Member Function Documentation
addCSG()
void com.neuronrobotics.bowlerstudio.creature.IMobileBaseUI.addCSG (Collection< CSG > toAdd, File source)
Add these objects to the UI.
Parameters
toAdd CSGs to add
source script source file
Referenced by com.neuronrobotics.bowlerstudio.creature.IMobileBaseUI.addCsg(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.generateBody(), and com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.generateCad().
addCsg()
default void com.neuronrobotics.bowlerstudio.creature.IMobileBaseUI.addCsg (CSG toAdd, File source)
Definition at line 96 of file IMobileBaseUI.java.
References com.neuronrobotics.bowlerstudio.creature.IMobileBaseUI.addCSG().
Referenced by com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.generateBody().
getVisibleCSGs()
Set<CSG> com.neuronrobotics.bowlerstudio.creature.IMobileBaseUI.getVisibleCSGs ()
Return the CSGs currently visible in the UI.
Returns
visible CSGs
Referenced by com.neuronrobotics.bowlerstudio.creature.IMobileBaseUI.selectCsgByFile().
highlightException()
void com.neuronrobotics.bowlerstudio.creature.IMobileBaseUI.highlightException (File fileEngineRunByName, Throwable ex)
Highlight the exception-causing lines in a file.
Parameters
fileEngineRunByName The file that was running when the exception occurred
ex the stack trace for file names of open files, or for open or executed file names
Referenced by com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager._generateStls(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.generateBody(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.generateCad(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getConfigurationDisplay(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.run(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.scriptFromFileInfo(), com.neuronrobotics.bowlerstudio.creature.MobileBaseLoader.setDefaultDhParameterKinematics(), and com.neuronrobotics.bowlerstudio.creature.MobileBaseLoader.setGitWalkingEngine().
selectCsgByFile()
default void com.neuronrobotics.bowlerstudio.creature.IMobileBaseUI.selectCsgByFile (File script, int lineNumber)
Definition at line 57 of file IMobileBaseUI.java.
References com.neuronrobotics.bowlerstudio.creature.IMobileBaseUI.getVisibleCSGs(), and com.neuronrobotics.bowlerstudio.creature.IMobileBaseUI.setSelectedCsg().
setAllCSG()
void com.neuronrobotics.bowlerstudio.creature.IMobileBaseUI.setAllCSG (Collection< CSG > toAdd, File source)
Replace all objects in the UI with these CSGs.
Parameters
toAdd CSGs to add
source script source file
Referenced by com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager._generateStls(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.generateBody(), com.neuronrobotics.bowlerstudio.creature.CadFileExporter.generateManufacturingParts(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.generateStls(), and com.neuronrobotics.bowlerstudio.creature.IMobileBaseUI.setCsg().
setCsg() [1/4]
default void com.neuronrobotics.bowlerstudio.creature.IMobileBaseUI.setCsg (CSG toAdd)
Definition at line 88 of file IMobileBaseUI.java.
References com.neuronrobotics.bowlerstudio.creature.IMobileBaseUI.setAllCSG().
setCsg() [2/4]
default void com.neuronrobotics.bowlerstudio.creature.IMobileBaseUI.setCsg (CSG toAdd, File source)
Definition at line 80 of file IMobileBaseUI.java.
References com.neuronrobotics.bowlerstudio.creature.IMobileBaseUI.setAllCSG().
Referenced by com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.generateCad(), and com.neuronrobotics.bowlerstudio.creature.CadFileExporter.generateManufacturingParts().
setCsg() [3/4]
default void com.neuronrobotics.bowlerstudio.creature.IMobileBaseUI.setCsg (List< CSG > toAdd)
Definition at line 84 of file IMobileBaseUI.java.
References com.neuronrobotics.bowlerstudio.creature.IMobileBaseUI.setAllCSG().
setCsg() [4/4]
default void com.neuronrobotics.bowlerstudio.creature.IMobileBaseUI.setCsg (MobileBaseCadManager thread, File cadScript)
Definition at line 92 of file IMobileBaseUI.java.
References com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.getAllCad(), and com.neuronrobotics.bowlerstudio.creature.IMobileBaseUI.setAllCSG().
setSelected()
void com.neuronrobotics.bowlerstudio.creature.IMobileBaseUI.setSelected (Affine rootListener)
Referenced by com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.selectCsgByLimb().
setSelectedCsg()
void com.neuronrobotics.bowlerstudio.creature.IMobileBaseUI.setSelectedCsg (Collection< CSG > selectedCsg)
Highlight the given list of CSGs. This should not change the CSG, just highlight it.
Parameters
selectedCsg the list to highlight NULL is used as a clear highlights
Referenced by com.neuronrobotics.bowlerstudio.creature.IMobileBaseUI.selectCsgByFile(), com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.selectCsgByLink(), and com.neuronrobotics.bowlerstudio.creature.MobileBaseCadManager.selectCsgByMobileBase().
The documentation for this interface was generated from the following file:
src/main/java/com/neuronrobotics/bowlerstudio/creature/IMobileBaseUI.java