BowlerKernel: com.neuronrobotics.sdk.addons.kinematics.IHardwareSyncPulseProvider Interface Reference
com.neuronrobotics.sdk.addons.kinematics.IHardwareSyncPulseProvider Interface Reference
Public Member Functions
default void addIHardwareSyncPulseReciver (IHardwareSyncPulseReciver r)
default void removeIHardwareSyncPulseReciver (IHardwareSyncPulseReciver r)
default void doSync ()
default ArrayList< IHardwareSyncPulseReciver > getListeners ()
Public Attributes
HashMap< IHardwareSyncPulseProvider, ArrayList< IHardwareSyncPulseReciver > > syncPulse =new HashMap<>()
Detailed Description
Definition at line 6 of file IHardwareSyncPulseProvider.java.
Member Function Documentation
addIHardwareSyncPulseReciver()
default void com.neuronrobotics.sdk.addons.kinematics.IHardwareSyncPulseProvider.addIHardwareSyncPulseReciver (IHardwareSyncPulseReciver r)
Definition at line 10 of file IHardwareSyncPulseProvider.java.
References com.neuronrobotics.sdk.addons.kinematics.IHardwareSyncPulseProvider.getListeners().
Referenced by com.neuronrobotics.sdk.addons.kinematics.MobileBase.addListeners(), com.neuronrobotics.sdk.addons.kinematics.LinkFactory.getLinkLocal(), and com.neuronrobotics.sdk.addons.kinematics.LinkFactory.getVirtual().
doSync()
default void com.neuronrobotics.sdk.addons.kinematics.IHardwareSyncPulseProvider.doSync ()
Definition at line 21 of file IHardwareSyncPulseProvider.java.
References com.neuronrobotics.sdk.addons.kinematics.IHardwareSyncPulseProvider.getListeners().
Referenced by com.neuronrobotics.sdk.pid.VirtualGenericPIDDevice.SyncThread.run(), com.neuronrobotics.sdk.addons.kinematics.LinkFactory.sync(), and com.neuronrobotics.sdk.addons.kinematics.MobileBase.sync().
getListeners()
default ArrayList<IHardwareSyncPulseReciver> com.neuronrobotics.sdk.addons.kinematics.IHardwareSyncPulseProvider.getListeners ()
Definition at line 28 of file IHardwareSyncPulseProvider.java.
References com.neuronrobotics.sdk.addons.kinematics.IHardwareSyncPulseProvider.syncPulse.
Referenced by com.neuronrobotics.sdk.addons.kinematics.IHardwareSyncPulseProvider.addIHardwareSyncPulseReciver(), com.neuronrobotics.sdk.addons.kinematics.IHardwareSyncPulseProvider.doSync(), and com.neuronrobotics.sdk.addons.kinematics.IHardwareSyncPulseProvider.removeIHardwareSyncPulseReciver().
removeIHardwareSyncPulseReciver()
default void com.neuronrobotics.sdk.addons.kinematics.IHardwareSyncPulseProvider.removeIHardwareSyncPulseReciver (IHardwareSyncPulseReciver r)
Definition at line 16 of file IHardwareSyncPulseProvider.java.
References com.neuronrobotics.sdk.addons.kinematics.IHardwareSyncPulseProvider.getListeners().
Member Data Documentation
syncPulse
HashMap<IHardwareSyncPulseProvider,ArrayList<IHardwareSyncPulseReciver> > com.neuronrobotics.sdk.addons.kinematics.IHardwareSyncPulseProvider.syncPulse =new HashMap<>()
Definition at line 7 of file IHardwareSyncPulseProvider.java.
Referenced by com.neuronrobotics.sdk.addons.kinematics.IHardwareSyncPulseProvider.getListeners().
The documentation for this interface was generated from the following file:
java-bowler/src/main/java/com/neuronrobotics/sdk/addons/kinematics/IHardwareSyncPulseProvider.java