BowlerKernel: com.neuronrobotics.bowlerstudio.scripting.IScriptingLanguage Interface Reference
com.neuronrobotics.bowlerstudio.scripting.IScriptingLanguage Interface Reference
Public Member Functions
abstract Object inlineScriptRun (File code, ArrayList< Object > args) throws Exception
abstract Object inlineScriptRun (String code, ArrayList< Object > args) throws Exception
abstract String getShellType ()
abstract ArrayList< String > getFileExtenetion ()
default boolean isSupportedFileExtenetion (String filename)
String getDefaultContents ()
default String getDefaultContents (String gitURL, String fileSlug)
boolean getIsTextFile ()
Detailed Description
Adding additional language support to bowler studio THis interface is for adding new scripting languages Add the new langauge in the Static declaration of ScriptingEngine or dynamically via:
ScriptingEngine.addScriptingLanguage(new IScriptingLanguage());
Author
hephaestus
Definition at line 16 of file IScriptingLanguage.java.
Member Function Documentation
getDefaultContents() [1/2]
String com.neuronrobotics.bowlerstudio.scripting.IScriptingLanguage.getDefaultContents ()
Get the contents of an empty file
Returns
Implemented in com.neuronrobotics.bowlerstudio.scripting.SvgLoader, com.neuronrobotics.bowlerstudio.scripting.SequenceRunner, com.neuronrobotics.bowlerstudio.scripting.RobotHelper, com.neuronrobotics.bowlerstudio.scripting.JythonHelper, com.neuronrobotics.bowlerstudio.scripting.JsonRunner, com.neuronrobotics.bowlerstudio.scripting.GroovyHelper, com.neuronrobotics.bowlerstudio.scripting.ClojureHelper, com.neuronrobotics.bowlerstudio.scripting.BashLoader, and com.neuronrobotics.bowlerstudio.scripting.ArduinoLoader.
Referenced by com.neuronrobotics.bowlerstudio.scripting.IScriptingLanguage.getDefaultContents().
getDefaultContents() [2/2]
default String com.neuronrobotics.bowlerstudio.scripting.IScriptingLanguage.getDefaultContents (String gitURL, String fileSlug)
Get the contents of an empty file
Parameters
fileSlug
Returns
Implemented in com.neuronrobotics.bowlerstudio.scripting.RobotHelper.
Definition at line 73 of file IScriptingLanguage.java.
References com.neuronrobotics.bowlerstudio.scripting.IScriptingLanguage.getDefaultContents().
getFileExtenetion()
abstract ArrayList<String> com.neuronrobotics.bowlerstudio.scripting.IScriptingLanguage.getFileExtenetion () abstract
Returns the list of supported file extentions Convention is to provide just the leters that make up the file extention
Implemented in com.neuronrobotics.bowlerstudio.scripting.SvgLoader, com.neuronrobotics.bowlerstudio.scripting.SequenceRunner, com.neuronrobotics.bowlerstudio.scripting.RobotHelper, com.neuronrobotics.bowlerstudio.scripting.JythonHelper, com.neuronrobotics.bowlerstudio.scripting.JsonRunner, com.neuronrobotics.bowlerstudio.scripting.GroovyHelper, com.neuronrobotics.bowlerstudio.scripting.ClojureHelper, com.neuronrobotics.bowlerstudio.scripting.BashLoader, and com.neuronrobotics.bowlerstudio.scripting.ArduinoLoader.
Referenced by com.neuronrobotics.bowlerstudio.scripting.IScriptingLanguage.isSupportedFileExtenetion().
getIsTextFile()
boolean com.neuronrobotics.bowlerstudio.scripting.IScriptingLanguage.getIsTextFile ()
This function returns if this is a binary file or a text file
Returns
true if the file is a text file.
Implemented in com.neuronrobotics.bowlerstudio.scripting.SvgLoader, com.neuronrobotics.bowlerstudio.scripting.SequenceRunner, com.neuronrobotics.bowlerstudio.scripting.RobotHelper, com.neuronrobotics.bowlerstudio.scripting.JythonHelper, com.neuronrobotics.bowlerstudio.scripting.JsonRunner, com.neuronrobotics.bowlerstudio.scripting.GroovyHelper, com.neuronrobotics.bowlerstudio.scripting.ClojureHelper, com.neuronrobotics.bowlerstudio.scripting.BashLoader, and com.neuronrobotics.bowlerstudio.scripting.ArduinoLoader.
getShellType()
abstract String com.neuronrobotics.bowlerstudio.scripting.IScriptingLanguage.getShellType () abstract
Returns the HashMap key for this language
Implemented in com.neuronrobotics.bowlerstudio.scripting.SvgLoader, com.neuronrobotics.bowlerstudio.scripting.SequenceRunner, com.neuronrobotics.bowlerstudio.scripting.RobotHelper, com.neuronrobotics.bowlerstudio.scripting.JythonHelper, com.neuronrobotics.bowlerstudio.scripting.JsonRunner, com.neuronrobotics.bowlerstudio.scripting.GroovyHelper, com.neuronrobotics.bowlerstudio.scripting.ClojureHelper, com.neuronrobotics.bowlerstudio.scripting.BashLoader, and com.neuronrobotics.bowlerstudio.scripting.ArduinoLoader.
Referenced by com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.addScriptingLanguage().
inlineScriptRun() [1/2]
abstract Object com.neuronrobotics.bowlerstudio.scripting.IScriptingLanguage.inlineScriptRun (File code, ArrayList< Object > args) throws Exception abstract
This interface is for adding additional language support.
Parameters
code file content of the code to be executed
args the incoming arguments as a list of objects
Returns
the objects returned form the code that ran
Implemented in com.neuronrobotics.bowlerstudio.scripting.SvgLoader, com.neuronrobotics.bowlerstudio.scripting.SequenceRunner, com.neuronrobotics.bowlerstudio.scripting.RobotHelper, com.neuronrobotics.bowlerstudio.scripting.JythonHelper, com.neuronrobotics.bowlerstudio.scripting.JsonRunner, com.neuronrobotics.bowlerstudio.scripting.GroovyHelper, com.neuronrobotics.bowlerstudio.scripting.ClojureHelper, com.neuronrobotics.bowlerstudio.scripting.BashLoader, and com.neuronrobotics.bowlerstudio.scripting.ArduinoLoader.
inlineScriptRun() [2/2]
abstract Object com.neuronrobotics.bowlerstudio.scripting.IScriptingLanguage.inlineScriptRun (String code, ArrayList< Object > args) throws Exception abstract
This interface is for adding additional language support.
Parameters
code the text content of the code to be executed
args the incoming arguments as a list of objects
Returns
the objects returned form the code that ran
Implemented in com.neuronrobotics.bowlerstudio.scripting.SvgLoader, com.neuronrobotics.bowlerstudio.scripting.SequenceRunner, com.neuronrobotics.bowlerstudio.scripting.RobotHelper, com.neuronrobotics.bowlerstudio.scripting.JythonHelper, com.neuronrobotics.bowlerstudio.scripting.JsonRunner, com.neuronrobotics.bowlerstudio.scripting.GroovyHelper, com.neuronrobotics.bowlerstudio.scripting.ClojureHelper, com.neuronrobotics.bowlerstudio.scripting.BashLoader, and com.neuronrobotics.bowlerstudio.scripting.ArduinoLoader.
isSupportedFileExtenetion()
default boolean com.neuronrobotics.bowlerstudio.scripting.IScriptingLanguage.isSupportedFileExtenetion (String filename)
This function should return true is the filename provided is of a supported file extension. This function may never be called if this language is only used internally.
Parameters
filename the filename of the file to be executed
Returns
true if the file extension is supported, false otherwise.
Definition at line 54 of file IScriptingLanguage.java.
References com.neuronrobotics.bowlerstudio.scripting.IScriptingLanguage.getFileExtenetion().
The documentation for this interface was generated from the following file:
src/main/java/com/neuronrobotics/bowlerstudio/scripting/IScriptingLanguage.java