name: "Test Build"
on:  
   push:
       branches:
         - development
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
         submodules: recursive        
        
    - name: List directory contents
      run: pwd; ls -la      
      
    - name: start xvfb
      run:
        Xvfb :0 &

    - name: initialize the X11 DISPLAY variable
      run:
        export DISPLAY=:0

    - name: After checkout, list directory contnts
      run: pwd; ls -la        

    - name: Pull a JavaFX JDK
      run: wget http://static.azul.com/zulu/bin/zulu8.33.0.1-ca-fx-jdk8.0.192-linux_x64.tar.gz

    - name: After JDK download, list directory contnts
      run: pwd; ls -la

    - name: Set Java
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        jdkFile: ./zulu8.33.0.1-ca-fx-jdk8.0.192-linux_x64.tar.gz
        
     
    - name: Build with Gradle 
      run: ./gradlew shadowJar
      
    - name: Test Local 
      run:  xvfb-run -s '-screen 0 1024x768x24' java -jar build/libs/bowler-kernel.jar -f kernel-return-test.groovy
      
    - name: Clean Cad 
      run: rm -rf $HOME/bowler-workspace/gitcache/github.com/Hephaestus-Arm/HephaestusArm2
    - name: build Cad 
      run:  xvfb-run -s '-screen 0 1024x768x24' java -jar build/libs/bowler-kernel.jar -g https://github.com/Hephaestus-Arm/HephaestusArm2.git hephaestus.xml
